### ISSUE TITLE
Murmur reporting as Kinetic Damage type

### ISSUE THREAD

**Issue by yunaforever009** [DestinyItemManager/DIM#10]
The Murmur Fusion Rifle special weapon is being listed as a Kinetic type of weapon. The item attributes sent from Bungie list the Murmur as having a damage type of 0 which generally means that it is a kinetic weapon. In this case though, there are selectable perks that alter the weapon element from kinetic to either solar or arc. 

Not sure how to address this without creating an exception for Murmur since it is the only weapon with this distinction or by later using the active perks to then designate the damage type for Murmur so that if person A has solar activated, it checks for the solar perk being flagged active and displays Solar as the dmgtype. I think that weapons with an element also list the perk associated with that element so that parsing Icebreaker would show the Solar perk as active (even though you could never deactivate it) and you'd then display Solar damage as the dmgtype.

**Comment by cardozaj** [comment]
Murmur should show up for Solar and Arc filters regardless of which perk is actively selected.
If Kinetic is the only damage type sent, then an exception will likely be necessary.

**Comment by yunaforever009** [comment]
Well, from what I saw in the item attributes, Bungie sets the Murmur's damage type as kinetic (dmgType==0) and then the solar or arc damage perks are applied. I imagine if they include any similar guns in HoW it will be a similar problem, the gun's attribute are set as kinetic and you'd have to look to the perks for void, arc or solar damage in order to determine what element type it's utilizing.

**Comment by kyleshay** [comment]
Hmm, I like the idea of the murmur (and possibly future similar guns) to show up for all filters that it can be an element of if it has that perk. When I'm doing an arc burn it would be nice to know that I have a special arc weapon even if my murmur is currently set to be solar.

**Comment by yunaforever009** [comment]
I think that by using the perk hashes you can do that quite easily. Implementing said perk hash parsing would simultaneously allow doing searches of is: armor piercing et cetera.

**Comment by kyleshay** [comment]
this is fixed
