### ISSUE TITLE
Subclass plugsets in subclass plug drawer aren't ordered like they're meant to

### ISSUE THREAD

**Issue by robojumper** [DestinyItemManager/DIM#10014]
https://discord.com/channels/316217202766512130/333464468241514497/1167260888949071922

**Comment by robojumper** [comment]
The bug report on the Discord server shows the Dawnblade (Solar Warlock) subclass plug drawer with grenades coming directly after supers (which is incorrect), but I can't reproduce that in Firefox nor Edge. Bug report was on Safari on iOS 11 - can someone reproduce this bug on iOS?

Relevant code: https://github.com/DestinyItemManager/DIM/blob/524d50b3980ec5bbf78b61fb956d3c433d403fbb/src/app/loadout/SubclassPlugDrawer.tsx#L46-L55

**Comment by bhollis** [comment]
I can't repro for any of my unlocked subclasses on iOS.

**Comment by bhollis** [comment]
Closing until we can get a repro
