### ISSUE TITLE
PR Previews: Table of Contents

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#10019]
### Proposed change

have pr.destinyitemmanger.com list all open deployed PRs with PR Title

### How does this fit into your workflow?

Quick easy to navigate ~~or optionally/additionally add a link from the PR to the deployment without the need to manually type the web address and the PR number.~~ apparently it does this when a valid url is generated.

**Comment by bhollis** [comment]
Any idea how we'd discover the list? I guess I could write some PHP to just look at the directories...

**Comment by delphiactual** [comment]
It could be part of the workflow, with the cleanup removing
