### ISSUE TITLE
Roll Details

### ISSUE THREAD

**Issue by sidferreira** [DestinyItemManager/DIM#10026]
### Proposed change

I was checking https://raw.githubusercontent.com/48klocs/dim-wish-list-sources/master/choosy_voltron.txt and I found something interesting:

```
// Mechabre (PvE first-choice roll)
// Fluted Barrel, (Flared Magwell, Tactical Mag), Perpetual Motion, Voltshot
//notes:Inspired by DMB PvE Podcast 37. PvE first-choice roll for building into Arc 3.0 subclasses. The Origin Trait, gaining better ADS and strafe speed when on your own, might be useful when you're away from your fireteam, but think of it more as a useful added extra when it's procced. Direct competitor to Occluded Finality, but with a much more reasonable 45 Zoom. You don't really need to worry about range, so look no further than Fluted Barrel to boost Handling and Stability. You want to make your reloads as fast as possible, so Flared Magwell or Tactical Mag are you mag choices. In the first trait column, Perpetual Motion boosts Reload Speed even more so that when you get your first add kill, you can reload as fast as possible to proc Jolt with Voltshot in the second column for additional damage against a Major or Boss and add clear of any Minors nearby. This is as close as you'll get to a legendary Cloudstrike. Recommended MW: Reload Speed, with a damage-boosting (Major, Boss or Taken Spec) mod. Tags: PvE, PvE-God, PvE-MinorSpec, PvE-MajorSpec, PvE-BossSpec, PvE-EndGame, Controller, MKB|tags: PvE, PvE-God, PvE-MinorSpec, PvE-MajorSpec, PvE-BossSpec, PvE-EndGame, Controller, MKB
dimwishlist:item=1280894514&perks=1840239774,3230963543,1428297954,2173046394
dimwishlist:item=1280894514&perks=1840239774,106909392,1428297954,2173046394
``` 

As a new light, having details like `PvE first-choice roll` or `PvE backup roll` is VERY interesting.

I would like to suggest a way to see this information, maybe a small line at the bottom saying `Mechabre (PvE first-choice roll)` and when pressed, it displays the notes about the roll.

I'm glad to work into it if there's opening for the idea

### How does this fit into your workflow?

As new light, helps to find out how good a roll is...

**Comment by robojumper** [comment]
You can click the "Triage" tab in the item popup to view notes for your roll, and you can also see all of those by clicking the item name in the item popup to open the "Armory" and see all wishlisted rolls with notes.

**Comment by bhollis** [comment]
Click the tab labeled "Triage" on the item popup to see this on matching items. To see all the rolls that are in the wish list for an item, click the title of the item to open the Armory view.

See the user guide here: https://github.com/DestinyItemManager/DIM/wiki
