### ISSUE TITLE
Increase Item Max Size

### ISSUE THREAD

**Issue by sidferreira** [DestinyItemManager/DIM#10027]
### Proposed change

Today, the max size is 66, which can be small on some screens.
I suggest changing it to 80 or even 100, as people can choose the best for them.

Sample screenshots below

<table>
<tr><td>66px</td><td>80px</td></tr>
<tr><td><img width="300" src="https://github.com/DestinyItemManager/DIM/assets/143615/75b4e172-cfe4-4597-a709-87de8ea93138" /></td><td><img width="300" src="https://github.com/DestinyItemManager/DIM/assets/143615/ad8f718a-7e7b-400a-a904-475e721deccb" /></td></tr>
</table>

### How does this fit into your workflow?

UX improvement

**Comment by bhollis** [comment]
I'd recommend zooming the whole interface if you need it bigger, instead of increasing the item size.
