### ISSUE TITLE
Platfom symbols for D1 accounts no longer show up

### ISSUE THREAD

**Issue by lowPolySkeleton** [DestinyItemManager/DIM#10038]
### DIM Version

Current beta and prod 

### Browser Details

All

### OS Details

All

### Describe the bug

![Screenshot_20231102_110537_Edge](https://github.com/DestinyItemManager/DIM/assets/29002828/c2dac91e-0940-42b4-85e3-8c7656c5b4b4)

**Comment by robojumper** [comment]
Likely regression from #9916:

> Also filtered out Stadia (unless it's the only account type)

But the code does

`.filter((p) => account.platforms.length > 1 && p !== BungieMembershipType.TigerStadia)`

which always filters out Stadia and also accounts with only one platform.
