### ISSUE TITLE
Error authorizing DIM / Unable to load characters and inventory

### ISSUE THREAD

**Issue by dingleberry001** [DestinyItemManager/DIM#10047]
### DIM Version

Version 7.92.0

### Browser Details

Chrome 118.0.0.0

### OS Details

Windows 10

### Describe the bug

I entered dim, and first thing I noticed was that images of the guns were not loading, I tried to refresh and it said that there was a problem trying to load my character. It said to check my connection or remove any content blockers. I checked my internet connection and it was fine, I turned off everything that I could turn off from windows defender, and I used to have Mcafee antivirus but my subscription recently expired and I deleted all files relating to Mcafee and uninstalled it. After doing all that, the problem was still there and I logged out and tried to re-enter but I only ended up to a white page that states Error authorizing dim. I tried to do what I did stated above again, but the problem still persisted. I even attempted to go on my phone to use dim as my phone had nothing that blocked content and I still got the same results. I'm not sure if this issue is a problem on my devices, or on dim, or on Bungie. Please help me with this.

![troubleshoot](https://github.com/DestinyItemManager/DIM/assets/149961362/a600423f-6c56-4c9d-8580-515237f627df)

### Logs

```shell
no placements
(anonymous) @ content.js:2
Show 1 more frame
Show less
debug:1 Access to fetch at 'https://www.bungie.net/Platform/GlobalAlerts/?' from origin 'https://app.destinyitemmanager.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
www.bungie.net/Platform/GlobalAlerts/?:1 
        
        
       Failed to load resource: net::ERR_FAILED
instrument.ts:144 [BungieAlerts] Unable to get Bungie.net alerts:  DimError: You may not be connected to the internet, or an ad blocking or privacy extension may be blocking Bungie.net.
    at bungie-service-helper.ts:107:11
    at bungie-service-helper.ts:82:7
    at async a (bungie-core-api.ts:14:3)
    at async alerts.ts:15:18
(anonymous) @ instrument.ts:144
banner.js?style={%22a%22:{%22display%22:%22none%22},%20%22h2%22:{%22color%22:%22white%22}}:89 Unrecognized Content-Security-Policy directive 'prefetch-src'.
OpenCollectiveWidget.inject @ banner.js?style={%22a%22:{%22display%22:%22none%22},%20%22h2%22:{%22color%22:%22white%22}}:89
```

**Comment by robojumper** [comment]
Yep, Bungie.net is serving CORS errors/captchas to some people. Bungie is aware, but there's no ETA for a fix yet. A VPN tunneling to a different country/region, or turning off your VPN may work around this.

**Comment by Spotted-Owlet** [comment]
I'm having same error with this case in DIM since yesterday. Is it possible to log in to destiny 2 companion app and other thirth-party apps for you? In my case, my account is not working on those apps at all.

**Comment by dingleberry001** [comment]
Yup, I just tried to enter and it was successful.
