### ISSUE TITLE
DIM says A content blocker is interfering with either DIM or Bungie.net, or you are not connected to the internet. This might be a problem with DIM, or it might be an issue with Bungie.net or your browser.

### ISSUE THREAD

**Issue by SleepyJynn** [DestinyItemManager/DIM#10058]
### DIM Version

Version 7.93.0 (release), built on 11/6/2023, 9:56:53 AM

### Browser Details

Opera GX 	102.0.4880.90 / 3 October 2023

### OS Details

Windows 10

### Describe the bug

DIM says A content blocker is interfering with either DIM or Bungie.net, or you are not connected to the internet. This might be a problem with DIM, or it might be an issue with Bungie.net or your browser.

I tried most of the things on the troubleshooting page of the github page, tried using DIM on my phone, allowed all cookies, turned off my ad blocker, used a different browser and DIM still says the same thing.
![Screenshot 2023-11-06 205624](https://github.com/DestinyItemManager/DIM/assets/150030290/044ecfb8-6bd7-45e7-a8d2-5f864d004a18)

**Comment by delphiactual** [comment]
Dupe #10047
