### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by ierihon161rus** [DestinyItemManager/DIM#10057]
### DIM Version

Версия 7.93.0 (release), собрана 06.11.2023, 04:56:53

### Browser Details

Yandex, Opera

### OS Details

Windows 10

### Describe the bug

![2023-11-06_14-36-29](https://github.com/DestinyItemManager/DIM/assets/149939588/cf68c055-972b-45a5-b394-0a8005f96e1e)
Всегда работало, а со вчерашнего дня перестало, и при входе выдаёт такую ошибку. ни каких антивирусов не устанавливал, систему тоже не переустанавливал, ни чего не менял.

### Logs

```shell
hpc.ts:41 Refused to load the image 'https://yastatic.net/s3/trbro/v20.5.1.0/i/service_name.svg' because it violates the following Content Security Policy directive: "img-src 'self' data: github.githubassets.com media.githubusercontent.com camo.githubusercontent.com identicons.github.com avatars.githubusercontent.com github-cloud.s3.amazonaws.com objects.githubusercontent.com secured-user-images.githubusercontent.com/ user-images.githubusercontent.com/ private-user-images.githubusercontent.com opengraph.githubassets.com github-production-user-asset-6210df.s3.amazonaws.com customer-stories-feed.github.com spotlights-feed.github.com objects-origin.githubusercontent.com *.githubusercontent.com".
```

**Comment by delphiactual** [comment]
Dupe #10056
