### ISSUE TITLE
[FR] Debug Mode

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#1006]
Add a setting that allows a user to be able to easily access the information a DIM dev would need to help troubleshoot problem items.

By enabling this setting a user would have a button enabled on every item, that would either console.log(item) or open a new window with the json of the item prettified for posting to GitHub/Reddit.

EDIT:
This value should always be off, and only enabled when a user directly selects it - next reload/refresh it should revert to off.

**Comment by delphiactual** [comment]
https://github.com/DestinyItemManager/DIM/issues/591
https://github.com/DestinyItemManager/DIM/issues/981
https://github.com/DestinyItemManager/DIM/issues/969

**Comment by bhollis** [comment]
Great idea! I'll whip something up.

**Comment by bhollis** [comment]
Closing in favor of #1010.
