### ISSUE TITLE
(Safari) LO left column width shrinking 

### ISSUE THREAD

**Issue by guise** [DestinyItemManager/DIM#10071]
### DIM Version

Version 7.93.0.1003087 (beta), built on 07/11/2023, 20:13:00

### Browser Details

Safari 17.0 (19616.1.27.211.1)

### OS Details

macOS Sonoma 14.0

### Describe the bug

Clicking on the Loadouts nav link while LOs are being evaluated shrinks the left-hand column. 

The issue persists for the browser session. 
Only appears to affect Safari, but haven't done extensive testing 

![LO-width](https://github.com/DestinyItemManager/DIM/assets/1396158/b25f8c15-7d63-4c0f-9668-2969fe31d8e8)

Steps: 

1. Open LO 
2. Enable some stats 
3. While LOs are being evaluated i.e.
    - After mouse-up when clicking a tier
    - Or releasing a drag 
4. Click on the "Loadouts" navigation link 
5. The LHS column width reverts back to width used on the main Loadouts page even when navigating back into the LO

**Comment by bhollis** [comment]
That's certainly a weird one. The width is entirely controlled by a CSS variable, so either Safari is *very* broken with how it decides to evaluate vars, or React is being broken by not updating the class names on the sidebar.

**Comment by robojumper** [comment]
I think this is again a CSS loading order / specificity issue similar to #10030 - I can reproduce this on Firefox, current beta by reloading DIM on the Loadouts page, clicking "Loadout Optimizer", then clicking "Vendors" in the title bar, then clicking "Loadouts" in the title bar, and finally clicking Loadout Optimizer again.

**Comment by bhollis** [comment]
I see. It doesn't happen on dev which is using `style-loader` but happens in beta. Yet another place where we really need CSS `@layer`.

I pushed a fix with `!important`.
