### ISSUE TITLE
Mod Picker: Factor out common raid mod text

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#10097]
<img width="744" alt="image" src="https://github.com/DestinyItemManager/DIM/assets/313208/e2987c26-3392-48de-bdeb-8402209cb48a">

We should factor out the "This mod's perks are only active in the X raid" text and either put it as a subtitle to the category or omit it entirely.

**Comment by grSalonga** [comment]
I could remove the italicized text from all mods and replace it with "Stackable" or "Unstackable".
