### ISSUE TITLE
Recently DIM became less responsive

### ISSUE THREAD

**Issue by Prometheus3375** [DestinyItemManager/DIM#10091]
### DIM Version

Version 7.93.0 (release), built on 06.11.2023, 04:56:53

### Browser Details

Chrome 119.0.0.0

### OS Details

Windows 10

### Describe the bug

Recently I noticed that if quickly drag-and-drop items, DIM does not move them. Here is the shot videos with my attempts.

https://github.com/DestinyItemManager/DIM/assets/35541026/359f7fe4-b0e1-47a2-9605-df78bb67cb0c

As you can see, DIM highlights a place when cursor is over it, but cursor icon stays 🚫 instead of changing to normal cursor during drag-and-drop.

### Logs

[app.destinyitemmanager.com-1699652971975.txt](https://github.com/DestinyItemManager/DIM/files/13323365/app.destinyitemmanager.com-1699652971975.txt)

**Comment by bhollis** [comment]
This isn't something we've heard other reports of. In the past stuff like this has been caused by bad mouse drivers...

**Comment by Prometheus3375** [comment]
I haven't changed mouse drivers since 2021. Could be related to Chrome versions.

**Comment by Prometheus3375** [comment]
Now I completely lost the ability move items via mouse. Yesterday it was working. 🤔

https://github.com/DestinyItemManager/DIM/assets/35541026/38465f85-2f63-43fe-9963-a2c3cb919930


Chrome 120.0.6099.110
DIM Version 7.99.0 (release), built on 18.12.2023, 04:58:52
Windows 10

**Comment by bhollis** [comment]
This remains something we're not seeing broadly, but have in the past had reports from Windows users on, and the root cause in those instances was drivers / system software.

**Comment by bhollis** [comment]
A good thing to check is to see if you can drag and drop on other sites: https://react-dnd.github.io/react-dnd/examples/tutorial

**Comment by Prometheus3375** [comment]
Ok, I checked that site, DnD works in incognito, but not in common mode. Will investigate further.

**Comment by Prometheus3375** [comment]
It is actually Clockify extension makes DnD not to work!

https://github.com/DestinyItemManager/DIM/assets/35541026/609ad6b0-6055-4704-aadf-07fae1c27406

I will report the issue to them.
