### ISSUE TITLE
Loadouts not working correctly as of 3.10.6.454

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#1011]
Not sure which commit broke this... Here are some screenshots:

![screenshot 2016-10-01 22 35 42](https://cloud.githubusercontent.com/assets/4798491/19018626/76cb137c-8827-11e6-8f57-61aaacf1982d.png)

![screenshot 2016-10-01 22 35 48](https://cloud.githubusercontent.com/assets/4798491/19018627/783fe30e-8827-11e6-9b54-cb00a080e346.png)

The maximize light is not moving any items even though it is reporting that it is...

EDIT: it was a commit that happened today so:
https://github.com/DestinyItemManager/DIM/pull/1004
https://github.com/DestinyItemManager/DIM/pull/1002
https://github.com/DestinyItemManager/DIM/pull/1001

Most likely one of these two though:
https://github.com/DestinyItemManager/DIM/pull/984
https://github.com/DestinyItemManager/DIM/pull/1003

**Comment by bhollis** [comment]
Probably some of my.recent changes. I'll investigate

**Comment by bhollis** [comment]
When this happens, what's most useful is to see what's in the console. So far I haven't been able to reproduce it.

**Comment by delphiactual** [comment]
![screenshot 2016-10-01 23 32 15](https://cloud.githubusercontent.com/assets/4798491/19018899/5092c184-882f-11e6-80e9-0baab57694db.png)

**Comment by bhollis** [comment]
I think I got it with ac645bfd2a46f2871e0b511aafba8b6ded9dcf8d. Try `dev`.

**Comment by delphiactual** [comment]
fixed

**Comment by delphiactual** [comment]
This has something to do with your new logic in https://github.com/DestinyItemManager/DIM/commit/bd54a7e6257659821e9bde838f2152ee470b3bfe

![screenshot 2016-10-02 00 10 59](https://cloud.githubusercontent.com/assets/4798491/19019044/d4e4afe2-8834-11e6-9e05-4afb4938558e.png)
