### ISSUE TITLE
search bar in Records page doesn't return weapon patterns if 'name:' keyword is used, but works properly without keyword

### ISSUE THREAD

**Issue by jerrycarlson** [DestinyItemManager/DIM#10135]
### DIM Version

Version 7.95.0 (release), built on 11/19/2023, 7:59:00 PM

### Browser Details

Chrome 119.0.6045.160 (latest updated)

### OS Details

Windows 10 (latest updated)

### Describe the bug

Using keyword "name:" in the search bar on the Records page will return results in Collections but not in Patterns.

For example, searching [ "resistance" ] on the Records page returns many results, including the Path of Least Resistance trace rifle in Collections.  As a craftable weapon, Path of Least Resistance also has an entry in Patterns which also shows up in these results.

However, searching [ name:"path of least resistance" ] on the Records page returns only the Collections entry and not the Patterns entry.

I confirmed that "hide completed triumphs" was disabled in case it was causing the issue.  I also confirmed using weapons from other slots ("ammit" and "cataclysmis") in case it was type-specific; the issue persisted.

=====

On a somewhat related note, I would request that exotic weapon catalyst entries also show up when using keyword "name:" in the search bar on the Records page too.  For example, searching [ name:hawkmoon ] ought to return both the item in Collections as well as the item in Catalysts.

=====

I thank the team for all of its hard work.  The game is nigh unplayable without DIM and the team's endless efforts maintaining and improving it over the years.

**Comment by jerrycarlson** [comment]
typo: should have read "cataclysmic" instead of "cataclysmis" in the weapon name examples above.

**Comment by bhollis** [comment]
This is because those are Triumphs, not items, so item search doesn't work on them. There isn't an actual link between them right now.
