### ISSUE TITLE
in the Records/Patterns & Catalysts section, add link to same weapon popup as in the Records/Collections section

### ISSUE THREAD

**Issue by jerrycarlson** [DestinyItemManager/DIM#10134]
### Proposed change

In most places, DIM lets you click a weapon thumbnail to open a weapon popup.  From that popup the user can then reach the weapon's Armory entry and get links to offsite resources.  For sake of consistency, and in the spirit of "would be nice to have", I would request that clicking the name of a weapon in the Records/Patterns & Catalysts section (or clicking the thumbnail, whichever is easiest to implement) would bring up the Armory page for that weapon.

### How does this fit into your workflow?

When viewing the Records/Patterns & Catalysts section, each given pattern lists the weapon name and progress on unlocking that weapon's pattern.  However, if you want to review that weapon you either need to switch back to the Inventory page and manually enter the weapon name to access the weapon's Armory page, or go find the weapon in the Records/Collections section and click the thumbnail there to access the weapon's Armory page -- in either case, a multi-step process to reach the Armory.

Allowing access to a pattern weapon's Armory page by clicking the weapon's name (or thumbnail) in the Patterns section reduces that process to a single click.

**Comment by bhollis** [comment]
It's a bit difficult because these are really Triumphs, not Collections items, which means that the connection to real items is tough and the interaction pattern is not really set up to show an item popup.
