### ISSUE TITLE
LO: add visual indicator to stat tier bar when any loadouts are found which have a half-tier above the last whole tier for that stat

### ISSUE THREAD

**Issue by jerrycarlson** [DestinyItemManager/DIM#10133]
### Proposed change

Currently, the LO stat tier bars indicate which stats have whole tiers available for a given armor selection.  The LO output matrix includes a very handy visual indicator when a given loadout candidate has at least a half tier, eg., "REC 8.5".  However, this indicator is only helpful when the candidate is on-screen. The indicator is invisible (and thus may as well not exist) to the user unless the user scrolls the entire list of LO matrix output, which can be very tedious at times.

I would request that the stat tier bar include a visual indicator when such a half-tier loadout shows up the results, so the user is immediately aware of it.  Since the highest whole tier is a white number on a light gray box, and the remaining higher whole tiers are gray numbers on a dark gray" box, maybe the "half tier" indicator could be an orange number on a dark gray box (orange just keeping with the existing graphics theme).

In the example image I'm attaching to this request, the number 5 tier in mobility would be colored orange instead of gray if there were any loadouts with 4.5 mobility (but with the same color background as the remaining higher tiers of mobility).  Obviously, specific indicator/color choice should be determined by your UX folks.  I'm just trying to think of something that feels easiest to implement (famous last words, I know).

![Capture](https://github.com/DestinyItemManager/DIM/assets/9376071/99e964cb-e44a-4e99-b641-238ea99b75f4)

### How does this fit into your workflow?

When I'm analyzing loadouts in the LO, I often find myself weighing the presence, cost, and contribution of half tiers (.5's) in loadouts as much as I do with whole tiers.  I consider how much investment each candidate distribution requires versus each other candidate that doesn't.  Sometimes a loadout that requires a half-tier investment in a stat is a better choice over another candidate that only has whole tiers.

The current stat tier bars are very handy for getting a quick big picture visualization of the population of available loadouts in terms of whole tiers, but it would be materially improved if that big picture included just a little more resolution so that half-tiers at the upper end per stat are easily seen too.  Otherwise the user has to scroll through the LO output matrix and risk missing the ".5" in a sea of numbers and symbols.

**Comment by bhollis** [comment]
Linking #10111

**Comment by bhollis** [comment]
Overall the idea of half-tiers has been somewhat obsoleted by the auto stat mods assignment, since all free spots will be occupied by stat mods automatically. Besides that, I believe with stat mods disabled we'll still sort builds with half-tier mods above sets at the same total tier that don't have half-tier mods. The stat constraint selector is not really intended to be a display of what has been found in the overall sets - the highlighting there is simply to help indicate what minimums could be set without causing no sets to be found.
