### ISSUE TITLE
Bounties should not be sorted

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#1013]
They should show in the the same order as in game.

**Comment by bhollis** [comment]
Good point! (I always leave those sections collapsed...)

**Comment by delphiactual** [comment]
I made a local commit with this change and they appear to be effected by the same problem as postmaster. The Bungie API is not returning them in the correct order, that they were obtained.

**Comment by bhollis** [comment]
Fixed by #1027.
