### ISSUE TITLE
Minimize Character Columns?

### ISSUE THREAD

**Issue by JakeWhitaker** [DestinyItemManager/DIM#1015]
I usually vault everything and mostly leave my characters  bare except the one I'm playing currently. When I'm done I take a second to "clean" that character out, so I never have to go looking for gear when I get on next. It'd be nice if I could collapse the characters I'm not playing. Maybe just  move the minimized characters to the other side of the vault, with a column width of their emblem. 

For a future UI idea, you could even make all the characters and vault collapsable, or make them auto collapse and kind of slide open(pinnable of course) when you move the cursor over them or touch them.

**Comment by bhollis** [comment]
Hmm, I'm not sure how we'd do that and still make it easy to have a full overview of your gear.

**Comment by JakeWhitaker** [comment]
Not sure what you mean by full overview. Would pinning them open or have them pinned open by default solve the problem you're foreseeing?

**Comment by phillipspc** [comment]
I would also like the ability to collapse a character column. Despite having 3 characters, I use one 99% of the time, so it would be nice to hide the others (similar to how you can collapse a weapon/armor category)

**Comment by delphiactual** [comment]
@JakeWhitaker, @phillipspc: What happens when an item you want is hidden behind the collapsed view?

**Comment by JakeWhitaker** [comment]
Consolidate all items from collapsed characters into the vault view.

http://imgur.com/a/uD314

**Comment by kyleshay** [comment]
we'll cover this with 
https://github.com/DestinyItemManager/DIM/issues/196 https://github.com/DestinyItemManager/DIM/issues/208
