### ISSUE TITLE
Harmonic Scavenger mod improperly identified as a seasonal artifact mod

### ISSUE THREAD

**Issue by Korrasera** [DestinyItemManager/DIM#10158]
### DIM Version

Version 7.97.0.1003156 (beta), built on 12/3/2023, 6:02:13 PM

### Browser Details

Chrome 119.0.0.0

### OS Details

Windows 10

### Describe the bug

DIM will flag the Harmonic Scavenger mod as a discounted seasonal artifact mod, sorting it into the list of discounted mods in the socket stripper and highlighting builds on the loadout page that contain it as including seasonal mods. The harmonic scavenger mod is a universal armor mod that everyone has access to and it already costs 1 energy. Additionally, the seasonal artifact for Season 23 - Season of the Wish does not contain any discounted scavenger mods.

This behavior is inconsistent as it appears that the mod always shows up as a discounted mod in the socket stripper, but some loadouts will flag it as a seasonal mod while some will not.

Here's an example of a void warlock build that demonstrates the issue:
![1](https://github.com/DestinyItemManager/DIM/assets/118650/e31dd9a9-6611-41e6-a531-baa0db025621)

And here's what it looks like when I remove the harmonic scavenger mod from that loadout:
![2](https://github.com/DestinyItemManager/DIM/assets/118650/12a058bc-3570-47f6-8c48-f2107ce03f07)

Finally, this is an example of the strip sockets feature showing a harmonic scavenger mod as a seasonal discounted mod:
![3](https://github.com/DestinyItemManager/DIM/assets/118650/8a60ec0c-b7dd-41a7-945b-c0e3effdbc1d)

**Comment by robojumper** [comment]
Wild. The [1-cost copy](https://data.destinysets.com/i/InventoryItem:877723168) of Harmonic Scavenger totally looks like it is the reduced-cost version of the canonical [2-cost mod](https://data.destinysets.com/i/InventoryItem:1301391064) (note the `collectibleHash` of the canonical mod). I wonder why the reduced-cost version of that mod is still available this season...

**Comment by mattjacobi** [comment]
Something really weird is going on because my harmonic scavenger mod (both in DIM and in game) costs 2, where it costs 1 for my friends. I think I removed that artifact perk before the end of the season, so I wonder if that's why I don't have it anymore.

**Comment by robojumper** [comment]
Thank for for the info. It's certainly possible that the artifact unlock continues to have an effect this season, but that'd mean DIM is ultimately correct here in considering the 1-cost mod still a seasonal mod.
