### ISSUE TITLE
Pouka Pond listed with "only show uncollected items" checked

### ISSUE THREAD

**Issue by craigguest** [DestinyItemManager/DIM#10175]
### DIM Version

Version 7.98.0 (release), built on 11/12/2023, 01:59:05

### Browser Details

Edge 120.0.0.0

### OS Details

Windows 11

### Describe the bug

When I select the “Only show uncollected items” option on the “Vendors” tab of DIM, the Pouka Pond vendor is displayed. However, I have already purchased all available fragments and aspects, so this behavior seems incorrect.

I have included portions of the Vendors API response, hopefully that will be useful to you!

### DIM Display

![image](https://github.com/DestinyItemManager/DIM/assets/3973190/93299141-1229-4e15-8952-0b873b168e18)

### Game Display

![image](https://github.com/DestinyItemManager/DIM/assets/3973190/e87e581a-6948-4883-b338-ef23ffbce219)

### Response/vendors/data

```json
"1413212512": {
    "canPurchase": false,
    "vendorLocationIndex": 0,
     "vendorHash": 1413212512,
     "nextRefreshDate": "2023-12-16T09:00:00Z",
    "enabled": true
}
```

### Response/sales/data

```json
"1413212512": {
    "saleItems": {
        "1": {
            "saleStatus": 8,
            "failureIndexes": [
                0
            ],
            "augments": 0,
            "vendorItemIndex": 1,
            "itemHash": 2099896459,
            "quantity": 1,
            "costs": []
        },
        "2": {
            "saleStatus": 0,
            "failureIndexes": [],
            "augments": 0,
            "vendorItemIndex": 2,
            "itemHash": 2269884985,
            "quantity": 1,
            "costs": []
        }
    }
},
```

**Comment by craigguest** [comment]
I don't have experience with the Destiny API, but it looks like there are two items listed for sale with no associated cost?

That seems odd to me, not sure if that helps you at all though.

**Comment by robojumper** [comment]
We don't get vendor data for this vendor, so we don't have information about which items you purchased, and due to https://github.com/Bungie-net/api/issues/1572 we also don't get accurate information about the unlock status for subclass config that we could otherwise use to determine which of these items are collected.

So this is basically a Bungie.net API bug.
