### ISSUE TITLE
Add an indicator to the item pop-up/compare page/organizer to show if an item is "deepsight harmonizable"

### ISSUE THREAD

**Issue by malbrec2** [DestinyItemManager/DIM#10181]
### Proposed change

Add an indicator to a weapon's display that indicates whether it is deepsight harmonizable.  This should be displayed when you click on the weapon, inside the compare page for comparing items of the same type, and when you pull up the organizer page.

### How does this fit into your workflow?

When deciding which weapons to shard/keep, I often try to keep at least enough "harmonizable" weapons of a given type in the vault to finish a pattern.  If I could see a weapon's harmonizability in DIM, I could make a decision about what to shard/keep from the compare page rather than having to check each item in-game.

Item pop-up
![image](https://github.com/DestinyItemManager/DIM/assets/3878061/07f6f6c0-949e-4ce7-8368-c4a35ef53f4b)

Compare page
![image](https://github.com/DestinyItemManager/DIM/assets/3878061/661ca1c0-6076-4c1d-a9c6-ee376c55dc31)

**Comment by bhollis** [comment]
See that little deepsight harmonizer icon on the left? That's the indicator

**Comment by malbrec2** [comment]
Didn't realize that.... makes sense.

Would it be possible to add a similar icon to the compare page?

**Comment by bhollis** [comment]
It would be possible, but there are lots of things that could go on the compare page. We should probably add it as a column in the Organizer then change Compare to be driven off the Organizer columns (and thus allow people to choose what to see).

**Comment by bhollis** [comment]
Linking #10183 and #10184
