### ISSUE TITLE
Add harmonizable column to Organizer

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#10184]
This would be to add a new column or columns to Columns.tsx for:

1. Whether an item is harmonizable.
2. What its deepsight level is.

**Comment by bhollis** [comment]
Hmm we also don't have deepsight level

**Comment by JakeSidSmith** [comment]
Was just about to open an issue and came across this. There may be some overlap.

I was going to say it'd be real nice if there were some kind of indication (icon?) which weapons were hormonizable, and a tag or something for weapons I want to "harmonize".

I use the "infuse" for high level weapons I'll be putting into others, and "keep" for weapons I use/want to hang on to.

Weapons that I just keep for harmonizing doesn't really fit into either.

Can open a separate issue for the tagging if you like.

**Comment by bhollis** [comment]
We won't be adding a separate tag for it but there is an icon in the item popup and a search filter already.
