### ISSUE TITLE
Better stats available doesn't take into account ignored stats

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#10196]
This is interesting - this loadout doesn't say "better stats available", but there is a set with the same values for all included stats *and* more points in ignored stats. Should we tweak the algorithm to find these?

<img width="1206" alt="Screenshot 2023-12-23 at 4 53 55 PM" src="https://github.com/DestinyItemManager/DIM/assets/313208/3083d921-5b7e-4cac-9906-62ad333b6102">

<img width="1160" alt="Screenshot 2023-12-23 at 4 53 29 PM" src="https://github.com/DestinyItemManager/DIM/assets/313208/cfcb03b2-4d28-4787-9f4f-05fa891873e9">

**Comment by robojumper** [comment]
It'd be neat but it's a can of worms - we'd have to extend our sorting to include ignored tiers too and LO SetTracker set sorting is already a bit shaky with the way we predict the stats string. It's also not entirely clear where in the lexicographic set comparison the "total tier" should be (vs. the total enabled tier), see https://discord.com/channels/316217202766512130/1174038965108613211/1174046151100604466 for some more discussion.

**Comment by nev-r** [comment]
definitely anti-including ignored stats, maybe ever, or at least not until there's either a snooze button, or some hypothetical advanced priority selection

**Comment by bhollis** [comment]
But why not? If it meets all the other objectives of the loadout but also has more of some stat, wouldn't it be worth it to swap out a piece to make that happen?

**Comment by nev-r** [comment]
because it's a bad feature if harasses me into accepting a stat tier i don't want, precluding later identification of a stat tier i wanted

**Comment by bhollis** [comment]
I don't think it should preclude a better result later - improvements in the enabled stats should always take priority
