### ISSUE TITLE
Wishlist grouping on Armory page not as expected

### ISSUE THREAD

**Issue by gaaasstly** [DestinyItemManager/DIM#10202]
### DIM Version

Version 7.99.0 (release), built on 12/17/2023, 8:58:52 PM

### Browser Details

Chrome 120.0.0.0

### OS Details

Windows 10

### Describe the bug

I apologize if this has been addressed previously or is labeled as a bug incorrectly.

I wanted to create my own wishlist and I'm using the recommended website, https://wishlists.littlelight.club/, from [COMMUNITY_CURATIONS](https://github.com/DestinyItemManager/DIM/blob/master/docs/COMMUNITY_CURATIONS.md).

![image](https://github.com/DestinyItemManager/DIM/assets/104249255/a609c34d-0239-4a9b-967c-0d028f729893)

```
// Irukandji (pve)
//notes: tags:pve
dimwishlist:item=2673925403&perks=839105230,1087426260,968510818,124408337
...

// Irukandji (pve)
//notes: tags:pve
dimwishlist:item=2673925403&perks=839105230,2420895100,1354429876,124408337
...
```

I'm looking at my IRUKANDJI and it doesn't show what I'd expect: the **Thumbs Up (These perks exactly match a weapon roll on your wishlist.)** for **Tactical Mag**, even when hovering or clicking.

![image](https://github.com/DestinyItemManager/DIM/assets/104249255/d6c04aa7-4a07-46c3-a742-913cd6be5f29)

There's a sentence under **Community Curations (Wish Lists)** that may explain this.

> We'll match the first of them that we can find.

I'm assuming this is true because I put the line with **Tactical Mag** above the line with **Appended Mag** and **Tactical Mag** got the **Thumbs Up**. This would mean that you can't, at-a-glance, identify all desirable perk combinations without ordering them by priority. But why? This is undesirable as it's significantly more work for folks that don't care about min/maxing.

I was looking at the **Armory** **Wishlisted Rolls** section and...

![image](https://github.com/DestinyItemManager/DIM/assets/104249255/20ccde29-e8e9-46c9-b007-a592fd7a7b7d)

They don't seem to be grouped, sorted, or parsed correctly. Referencing my LL wishlist image and export, I would expect to see these consolidated into two "builds" and either one or two sections titled "tags:pve" but instead I see a second section titled "No Notes".

**Comment by bhollis** [comment]
Yes, you are correct that it will stop after the first match. This is how it has always been, and while we have an issue to change that in a wish lists overhaul, nobody is working on it.

**Comment by bhollis** [comment]
Can you share your full wishlist so we can reproduce this?

**Comment by gaaasstly** [comment]
Sure. Here are the LL and DIM exports, respectively: 

- [My wishlist.json](https://github.com/DestinyItemManager/DIM/files/13826654/My.wishlist.json)
- [My wishlist.txt](https://github.com/DestinyItemManager/DIM/files/13826655/My.wishlist.txt)

**Comment by bhollis** [comment]
Closing as this is an edge case that likely won't get fixed before wish lists are revamped.
