### ISSUE TITLE
Sorting broken

### ISSUE THREAD

**Issue by JakeWhitaker** [DestinyItemManager/DIM#1021]
Posted yesterday, but today its actually not working but on the beta app, sorting by primary stat roll works, primary stat works, but rarity does not. Screenshot is sorted by rarity
![2016-10-04](https://cloud.githubusercontent.com/assets/21060251/19074276/7055f45c-8a0d-11e6-96eb-7b71a804fdb2.png)

**Comment by kyleshay** [comment]
whooops, thanks!
