### ISSUE TITLE
Energy bar @ mod placement screen

### ISSUE THREAD

**Issue by Revadike** [DestinyItemManager/DIM#10227]
### Proposed change

![image](https://github.com/DestinyItemManager/DIM/assets/4411977/01e5f223-d258-4859-a963-ac4f508f8cd3)

### How does this fit into your workflow?

I always have to make the calculations in my head, this would be easier

**Comment by robojumper** [comment]
Are you aware of the energy bar below the items in your screenshot?

**Comment by Revadike** [comment]
Not until now, it's quite small

**Comment by bhollis** [comment]
Which calculations are you doing in your head?

**Comment by Revadike** [comment]
how many energy points are left

**Comment by bhollis** [comment]
Ah, sure, I was mostly wondering if you were trying to accomplish something using that information that we could design the UI to accommodate. Regardless, you know where this is now.

**Comment by Revadike** [comment]
it's very small though, perhaps my suggested placement is better?
