### ISSUE TITLE
Missing Weapons

### ISSUE THREAD

**Issue by DonPitts** [DestinyItemManager/DIM#10235]
### DIM Version

8.3.0 (2024-01-14)

### Browser Details

Chrome, Firefox, and Brave

### OS Details

Windows 10

### Describe the bug

Since the latest update I no longer have the ability to see my weapons with my armor. Usually when I log in I can drag and drop weapons. Now I can no longer do that I have yet to figure out what was changed to why I can't see them. I have not changed my settings from the default, I have signed out and back in to it on different devices and browsers. And yet I still can not see my weapons where they usually are. I have tried to see if anyone else has this issue, but I can not find anyone with the issue at all just based of a general search on google as well as youtube. 
![DIM issue](https://github.com/DestinyItemManager/DIM/assets/157271986/41f94564-ef0d-4184-8916-bc6ebab48e34)
![Dim issues2](https://github.com/DestinyItemManager/DIM/assets/157271986/0a9feb46-05a5-486f-ac5b-a87c96af48df)

**Comment by delphiactual** [comment]
![image](https://github.com/DestinyItemManager/DIM/assets/4798491/6fd342d6-a4ba-459d-a5d1-7c9e2b5423c1)

`Click to expand`

**Comment by DonPitts** [comment]
> ![image](https://private-user-images.githubusercontent.com/4798491/298369337-6fd342d6-a4ba-459d-a5d1-7c9e2b5423c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4NTcwOTQsIm5iZiI6MTcwNTg1Njc5NCwicGF0aCI6Ii80Nzk4NDkxLzI5ODM2OTMzNy02ZmQzNDJkNi1hNGJhLTQ1OWQtYTVkMS03YzllMmI1NDIzYzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjFUMTcwNjM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmQwNGI4MjMzZmE5M2E4ODAyNmYzZWE0MTI3MmQ5YTY5MzVkZTNkYWIwZWFiYTVkZmMxY2ZhMGZiMTdmNjkxOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.R1-sDA9Jev263jvVBlZl1RQ69bWuzpl0rvqkoErCqYA)
> 
> `Click to expand`

I dont think you read and understood what I wrong vs just looking and replying because if you look I put a second screen shot of when I click weapons it breaks each of them down, but does not give me the ability to drag and drop like it originally did all I can do it click them after I select something like a scout. Click the check box and that is it. There is no transfer or drag and drop feature. So no disrespect please make sure you read and look before replying.
