### ISSUE TITLE
Tag limit

### ISSUE THREAD

**Issue by ArsNG** [DestinyItemManager/DIM#1024]
Version 3.11.0.479 beta
I  just tagged around 200 items and can't tag anything more, it's jut not saving and after reloading DIM's tab i got my fresh previous tags gone.

**Comment by SunburnedGoose** [comment]
Yep.  Bug in the data storage feature.  We're working on a new way to save data that gives us more storage.

**Comment by SunburnedGoose** [comment]
Related to #892.  Refer to that issue for updates.
