### ISSUE TITLE
is:wishlist not matching on Belisarius-D

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#10256]
### DIM Version

current beta

### Browser Details

chrome

### OS Details

Windows 11

### Describe the bug

I have a Belisarius-D that has a 5/5 match with a wishlist role.

dimwishlist:item=2313726158&perks=839105230,1561002382,3619207468,460017080,3465198467

![image](https://github.com/DestinyItemManager/DIM/assets/25425159/4d2595ba-d56b-4c10-945d-dbea63eb3231)

![image](https://github.com/DestinyItemManager/DIM/assets/25425159/d05a7aad-09de-4ce3-85f8-bd92ee182463)

However there is no wishlist thumbs up on the item, and it is not selected by is:wishlist.

![image](https://github.com/DestinyItemManager/DIM/assets/25425159/fab8dce2-edcb-4dc6-b740-ad62e0672ef6)

**Comment by bhollis** [comment]
Can you share your profile export? Are you using the default voltron wishlist?

**Comment by philkernick** [comment]
Yes, default voltron wishlist.  Not sure how to share a profile export.

The only thing I can see that is different about that weapon is that the 5th column perk is in the wishlist.  And it's the only weapon I can find that the 5th column perk is selectable betwen an origin trait and a stock.

**Comment by bhollis** [comment]
A profile export can be saved from the Settings page in beta, at the bottom.

**Comment by philkernick** [comment]
Profile attached.  
[profile-data.json](https://github.com/DestinyItemManager/DIM/files/14318162/profile-data.json)

**Comment by bhollis** [comment]
I loaded up the profile export, and I see two Belisarius-D that both match the wish list and have a thumbs up. Are you still seeing this issue?

**Comment by philkernick** [comment]
I only have one Belisarius-D, which is strange.  But yes, the issue remains, and it continues to be the only weapon that has this problem.  Current beta.

**Comment by philkernick** [comment]
I unchecked Voltron, clicked clear wishlist, then recheckedc Voltron.  Same problem.  All the other wishlist items are correct, but not Belisarius.

And I really only have one of them.

![image](https://github.com/DestinyItemManager/DIM/assets/25425159/7f05a6dd-348e-4c73-a422-597410f0cd76)

**Comment by delphiactual** [comment]
submit a new profile data

**Comment by philkernick** [comment]
New profile attached.
[profile-data.json](https://github.com/DestinyItemManager/DIM/files/15441151/profile-data.json)

**Comment by bhollis** [comment]
Loading that profile, I see this:

<img width="510" alt="Screenshot 2024-05-25 at 11 46 55 AM" src="https://github.com/DestinyItemManager/DIM/assets/313208/49d855b6-fddc-43cc-8443-5dbb2b542c72">

**Comment by bhollis** [comment]
Oh, interesting, that seems to be matching from the Just Another Team wishlist. Just voltron doesn't match.

**Comment by bhollis** [comment]
OK, solved:

https://github.com/48klocs/dim-wish-list-sources/blob/f7414f3a29237eb8f37e506f2372ae6f36497c6e/PandaPaxxy/panda_s23_vendor.txt#L89-L220

The PandaPaxxy rolls for Belisarius-D specify that the roll must include Composite Stock AND Hand-Laid Stock AND Short-Action Stock. Obviously, that's impossible. @48klocs it looks like we need some validation on these rolls.

**Comment by bhollis** [comment]
Closing, see linked issue https://github.com/48klocs/dim-wish-list-sources/issues/189
