### ISSUE TITLE
Item popup when adding weapons on loadout edit

### ISSUE THREAD

**Issue by xXAquaNightXx** [DestinyItemManager/DIM#10263]
### Proposed change

Would it be possible to have an item popup showing perks on the loadout edit screen, as it is if there are multiple copies of a weapon there is no way to see what perks it has until it is selected, clicking on the gun adds it to the loadout and then you would have to click to check the perks as usual. Maybe a SHIFT + Click on the item to bring up the perks popup.

![Screenshot_1](https://github.com/DestinyItemManager/DIM/assets/24309423/cc41630f-cec6-4ec2-9fc4-ed562b07a42f)

![dim](https://github.com/DestinyItemManager/DIM/assets/24309423/318aee52-7667-499d-8241-d0dea1cd5b01)

### How does this fit into your workflow?

This would make it easier to select a specific roll of a weapon you want to add to a loadout instead of having to click back and forth. to see the perks the gun you're selecting has.

**Comment by bhollis** [comment]
https://github.com/DestinyItemManager/DIM/issues/3591 is our tracking issue for this. In the meantime please use tags and notes to distinguish between similar items, or drag and drop them into the loadout editor from the Inventory or Loadouts screen.
