### ISSUE TITLE
DIM Sync has become noticeable slower since last D2 update

### ISSUE THREAD

**Issue by Globespy** [DestinyItemManager/DIM#10273]
### DIM Version

8.7.0

### Browser Details

Edge Chromium - Version 121.0.2277.128 (Official build) (64-bit)

### OS Details

Win 11 - 23H2 (OS Build 22631.3155)

### Describe the bug

Recently DIM has become unreliably slow in how it is being synced with D2 servers.
DIM regularly shows that the info has not been updated for 7-10 minutes, which is very restrictive when building/changing loadout stats in DIM.
If this is a problem caused by Bungie and nothing can be done, then I guess I need to be a LOT more patient.
Love this app, keep up the good work.

**Comment by bhollis** [comment]
7-10 minutes is far longer than we normally see. However, as we don't run the Bungie.net service, there's nothing we can do for you if you're seeing this. It may vary for different countries, etc. or just be a quirk of how things are going at Bungie on any given day.
