### ISSUE TITLE
exclude weird no-stats exotics from vendor compare

### ISSUE THREAD

**Issue by nev-r** [DestinyItemManager/DIM#10279]
![image](https://github.com/DestinyItemManager/DIM/assets/2764675/9a4b284b-387c-416c-bca6-614239010d6d)

lot of investigation here, thank you @FlaminSarge:
https://github.com/DestinyItemManager/DIM/pull/10262

**Comment by FlaminSarge** [comment]
I'll take a crack at this when I can.

**Comment by FlaminSarge** [comment]
How does https://github.com/DestinyItemManager/d2-additional-info/blob/master/output/bad-vendors.json get used? Is it viable to co-opt it for this?

**Comment by delphiactual** [comment]
![image](https://github.com/DestinyItemManager/DIM/assets/4798491/1a507ce8-599d-48b0-8c71-99cc7d264d4d)
It was useful in year 2, you can use it for this.
