### ISSUE TITLE
Switching first/second column perks in compare can change values on multiple weapons

### ISSUE THREAD

**Issue by thomaskchan** [DestinyItemManager/DIM#10285]
### DIM Version

Version 8.10.0.3249 (beta), built on 3/3/2024, 6:08:08 

### Browser Details

Safari

### OS Details

ipados

### Describe the bug

I noticed this issue when comparing a number of hullabaloos, but was also able to reproduce on a cartesian.  When changing the first or second column perks, the numbers on multiple guns will change.  This is most common on the second column but sometimes it works with the first column perks.

**Comment by robojumper** [comment]
Can you post some screenshots? The colors on the numbers are expected to change, but not the values themselves. I can't reproduce the values changing...

**Comment by thomaskchan** [comment]
Hmm, I must have misread it.  Sorry for the bad report.
