### ISSUE TITLE
Expand item tagging menu into individual menu items in the item popup

### ISSUE THREAD

**Issue by Revadike** [DestinyItemManager/DIM#10283]
### Proposed change

The sidebar to the item UI popup is only a fraction of the whole popup height, so why put tags in another submenu. Just put it there directly for ez increased productivity

![image](https://github.com/DestinyItemManager/DIM/assets/4411977/fe84c91c-80ca-4500-9e66-87051bf14e46)

### How does this fit into your workflow?

Less clicking

**Comment by bhollis** [comment]
Don't forget you can use keyboard shortcuts.

**Comment by Revadike** [comment]
> Don't forget you can use keyboard shortcuts.

Yep its indicated nicely

**Comment by grSalonga** [comment]
So I came up with two ways of solving this, either I delete the drop down and create six new buttons for tagging, or I force the drop down to always be open and move it to the bottom of the ui popup so it doesn't cover anything. Which would be better or should I try something else?

**Comment by bhollis** [comment]
I don't think we've agreed that this is something desirable to implement in DIM.

**Comment by Revadike** [comment]
@bhollis but why put it in a submenu, decreasing productivity, when we have enough room to display all options directly?

**Comment by bhollis** [comment]
Because unlike all the rest of the buttons, it is a selection of one of several choices. Between the dropdown and the shortcuts, this is already well handled and will not be changed.
