### ISSUE TITLE
Icons not displaying

### ISSUE THREAD

**Issue by unkshine** [DestinyItemManager/DIM#10293]
### DIM Version

Version 8.12.0

### Browser Details

Firefox 123.0.1 Edge 122.0.2365.92 

### OS Details

Windows 11

### Describe the bug

![dim missing icons](https://github.com/DestinyItemManager/DIM/assets/163940343/3fc44ac5-d932-4b32-818c-5030dc4e7e3c)
Having an issue with icons not showing at all. This happens 90% of the time. Image is attached. Have tried with fresh browser installs with no extensions on Firefox and Edge, no bueno. Have also tried using DIM beta and the issue was present there also.

**Comment by bhollis** [comment]
How long has this happened? Have you tried all the troubleshooting steps? Do you have free disk space? Do all the images show up when you use the D2 Companion app from the same network?

**Comment by unkshine** [comment]
I only returned to the game about a week ago, it's been present every time. I believe I've tried all the troubleshooting steps that are applicable to my case. I have plenty of free disk space. Just checked the D2 app a few times and everything seems fine there, using the same network.

**Comment by bhollis** [comment]
Your best bet is probably to ask in the Discord so someone can walk you through some things to try.
