### ISSUE TITLE
Missing Spacing Between Archetype & Weapon Type UI Text in Item Feed View

### ISSUE THREAD

**Issue by rinhugs** [DestinyItemManager/DIM#10307]
### DIM Version

Version 8.13.0 (release), built on 3/24/2024, 8:53:35 PM

### Browser Details

DIM AppStore 7

### OS Details

iOS 17.3.1

### Describe the bug

UI Text Display Bug
![IMG_3636](https://github.com/DestinyItemManager/DIM/assets/124543344/32c98669-0391-4f2a-b95a-f0830d7a69ad)

* Missing Spacing Between Archetype & Weapon Type
* Example: “Precision FrameSubmachine Gun” => “Precision Frame Submachine Gun”
* Where = Item Feed View on Mobile.

**Comment by nev-r** [comment]
fixed in https://github.com/DestinyItemManager/DIM/commit/0b0fc6e7f638f1d49da831929fe1d2eae7d87156
