### ISSUE TITLE
Enhanceable weapons filter

### ISSUE THREAD

**Issue by jonasdametto** [DestinyItemManager/DIM#10301]
### Proposed change

With the Final Shape DLC we will have some weapons that can have perks enhanced.
Could we have a filter tag for enhanceable weapons?
e.g: is:enhanceable

I dont know if we have this information from destiny api's, but is it possible ?

### How does this fit into your workflow?

Its a good way to filter what is usefull on the inventory. Honestly for me I just care about craftable weapons (and now enhanceable weapons)

**Comment by danmckinley** [comment]
This would be great

**Comment by bhollis** [comment]
Probably will have to wait for The Final Shape to release.
