### ISSUE TITLE
Allow any loadout for streamdeck

### ISSUE THREAD

**Issue by TheDummi** [DestinyItemManager/DIM#10325]
### Proposed change

Allow streamdeck loadouts to be dim saved loadouts instead of just in game loadouts.

### How does this fit into your workflow?

If you're in an activity you can't use dim to equip a loadout so I barely use the streamdeck feature, however it would be nice to have non in game saved loadouts for streamdeck just before you launch an activity.

**Comment by lowPolySkeleton** [comment]
this probably belongs in the streamdeck repo, we don't make that. https://github.com/dim-stream-deck/com.dim.streamdeck

**Comment by bhollis** [comment]
But also I believe the streamdeck plugin does allow adding DIM loadouts to your streamdeck.

**Comment by TheDummi** [comment]
I didn't know the repo's were different, sorry for that, as well as I might just be incapable of getting the loadouts setup on the streamdeck :)
