### ISSUE TITLE
Clear Character slots button

### ISSUE THREAD

**Issue by TheDummi** [DestinyItemManager/DIM#10324]
### Proposed change

Can there be a button to either instantly clear every character slot (on current character) or have each slot have their own button.

### How does this fit into your workflow?

Everytime I am focusing armor and there is about 60+ engrams to go through, I have to pull from postmaster which will then put it in the vault because my character has most of its slots used already, and it does take quite a bit of time for dim to process and you having to then pull from vault to character again. Currently I manually move all of my armor 1 by 1, from my character into the vault, so that I can then focus armor.

**Comment by robojumper** [comment]
This should be covered by bulk actions:

https://github.com/DestinyItemManager/DIM/wiki/Item-Search#bulk-actions
https://github.com/DestinyItemManager/DIM/wiki/Item-Search-Useful-Queries

Try `is:incurrentchar is:armor -is:equipped`, click the three dots in the search bar, Send to Vault

**Comment by TheDummi** [comment]
This works, thanks, wouldn't mind a button for it though.

**Comment by bhollis** [comment]
We've definitely heard that request - however, leaving this as a search feature opens the door to folks crafting all kinds of different searches to move items, which are specific to their workflows.
