### ISSUE TITLE
Switch to enable / disable closing the item popup window when pulling to item to character

### ISSUE THREAD

**Issue by austinriceone** [DestinyItemManager/DIM#10326]
### Proposed change

Add a setting switch to enable or disable closing the popups when performing actions inside. It seems like the closing behavior is a recent change, because I don't remember it happening before.

### How does this fit into your workflow?

The item popup closing like this is pretty disruptive to a particular flow I had, where I would pull up the details for a weapon so I could see all the versions I had. From there I would move all the ones I didn't want to my current character for deletion, but now I can only do one at a time, significantly slowing this process down.

**Comment by bhollis** [comment]
Nothing has changed about this behavior for many years. 

We won't be adding a setting to control this behavior, but I'd like to understand more about this particular workflow. How were you opening multiple popups at once? 

Also did you know there's a shortcut key (V) to vault an item?

**Comment by austinriceone** [comment]
It has been awhile since I was doing this in the app. I think I was conflating this detail window with the compare window (which does not close when I pull items)

As far as the workflow I'm describing, I can walk you through steps:
Click a weapon icon > Click weapon name in popup > (detail dialog opens) > scroll to compare section > click weapon icon again > (new weapon popup opens) > click pull to {character} > popup, detail screen, and popup within detail screen all close

So clicking compare instead gets me to a place where I can see all instances of the item in the drawer dialog and choose what I want to pull, then close the drawer manually.

I didn't realize there was a set of shortcuts for moving items until I started looking in the code and noticed those in DesktopItemActions. Nice feature to have.

**Comment by bhollis** [comment]
You can also hit ? and a screen will show up with all the shortcuts. See 

I'm going to close this since there isn't an issue, but thanks for sharing your workflow!
