### ISSUE TITLE
add a source:brave filter

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#10337]
### Proposed change

The new brave weapons released with into the light have a new seasonal icon.  There is no search term that allows them to be found.

I propose a new search term source:brave that will allow them to be selected.

### How does this fit into your workflow?

Use case: Which weapons do I need to use to complete the triumph and seal that requires getting kills with a brave weapon.

**Comment by prunetracy** [comment]
Try `source:intothelight`. It doesn't show shiny Recluse or Hung Jury, but everything else seems to appear.

**Comment by bjacobel** [comment]
I've made a PR to add this in https://github.com/DestinyItemManager/d2-additional-info/pull/580, though I don't know what's up with the Arcite quest rewards.
