### ISSUE TITLE
source:intothelight not showing all weapons

### ISSUE THREAD

**Issue by prunetracy** [DestinyItemManager/DIM#10338]
### DIM Version

Version 8.16.0 (release), built on 4/14/2024, 11:51:07 PM

### Browser Details

Chrome 122.0.6261.129

### OS Details

Windows 11

### Describe the bug

`source:intothelight` shows most things correctly, but does not highlight the curated shiny rolls for Hung Jury and Recluse rewarded from the Arcite quests. I don't have other shiny rolls of these, so not sure if it's all shiny or just the quest rewards. R

### Screenshot
![image](https://github.com/DestinyItemManager/DIM/assets/3656086/b93427f2-f131-4516-89d8-7f58849b8c6c)

**Comment by delphiactual** [comment]
fixed in beta
