### ISSUE TITLE
improve wishlist view to select between different rolls of the same weapon

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#10343]
### Proposed change

Currently if you click on the title of weapon it opens wishlst view.  In this view you can see every copy of the weapon you have.

![image](https://github.com/DestinyItemManager/DIM/assets/25425159/5b7668a8-c66a-4026-a587-0f6b3dbe9a49)

I want to be able to double-click or shift-click on each of the differnt rolls shown under "your items" and have it update the perks panel above.

Currently if you click on the different rolls, it just brings up the weapon details panel.  This will need to be retained to be able to tag or move the item.

### How does this fit into your workflow?

In the example I've included in the screenshot, I have 6 copies of Elsie's Rifle.  I want to see how close to a wishlist roll each is, but there is no way to do it other than manually selecting each one.  There is no way to do an (a) vs (b) comparison.

**Comment by bhollis** [comment]
This is understandable, but will be too complex an interaction with the existing tiles. Also, the info for a particular set of selected perks is mostly the same as what's shown (more compactly) on the item tile. You can, however, open the item popup for one of those items then click its header again to see its roll in the Armory if you want.
