### ISSUE TITLE
Siege Engine Tech material showing in wrong location.

### ISSUE THREAD

**Issue by scorp508** [DestinyItemManager/DIM#1035]
Found in: Version 3.11.1.483

A consumable material named "Siege Engine Tech" worth 3k glimmer (mine is, maybe they can be different) is currently shown in the wrong location. Rather than the item being with other consumable/material items it is located next to your current faction pledge just above the Postmaster.

![set-00](https://cloud.githubusercontent.com/assets/22648747/19135231/3021cff8-8b31-11e6-9602-a4dfa1745e13.JPG)

**Comment by SunburnedGoose** [comment]
That is where it is located in game.

**Comment by scorp508** [comment]
Ah... hadn't even noticed. I assumed it was any other run of the mill glimmer consumable. :)
