### ISSUE TITLE
Interest in Angular 2?

### ISSUE THREAD

**Issue by SnareChops** [DestinyItemManager/DIM#1036]
Just a question, is there any interest in an Angular 2 refactor? Even if in the distant future?

**Comment by SunburnedGoose** [comment]
Yeah, I've been kicking the tires with ngrx to create an immutable store too.

**Comment by SnareChops** [comment]
@SunburnedGoose I guess let me set the background. I love DIM and use it every day and have been wanting to contribute back to the project that has helped me so much in the game. Imagining life in destiny without DIM, is pretty dark.

A little about me, I am a senior software engineer that specializes in Angular 2, Typescript, and Hybrid Mobile Applications and have been working as the head of frontend development at an Australian company for close to two years now. We have been using Angular 2 IN PRODUCTION since the early days of the alpha (it was the reason I was hired). The only reason that I brought this up is because I know the benefits in performance, development time, and maintenance of apps in Angular 2 compared to Angular 1. Since this is the area of my expertise, it could be a great way to contribute to the project in a more meaningful way then just bug fixes (though I know how much those can help too).

Over the last two weeks or so I have been playing around with the DIM codebase locally and have been trying to come up with the best strategy for an upgrade and have come to the conclusion that due to the way the application is currently written, the changes required to upgrade from it's current state would be very drastic and very disorienting if they were dropped in all at once. Not to mention a full upgrade would probably take about 3-4 weeks of full time man hours (at it's current state).

So instead of attempting to drop a huge codebase shift in your pull request box I thought it would be a better move to try and coordinate a strategy with the DIM team, and take a more progressive approach to the project. Also since not everyone writes code in the same style, I wanted to possibly discuss your code style rule and preferences. Angular 2 has many options for use, and though they do recommend an approach, it doesn't mean that it's the only way, we may be able to find a good compromise that works for all the core DIM developers.

Also having been through a good portion of the code base by now I can confirm that this project would be able to use, and benefit from AOT compilation. Which is a HUGE win for performance and load times.

I would be happy to discuss any questions or concerns with you, and I would be happy to coordinate and possibly discuss an upgrade strategy tailored for this project that everyone can get on board with. My skype is snare_chops and discord SnareChops#2903. Feel free to contact me anytime, and I hope that I can help the DIM project continue to grow.

**Comment by SunburnedGoose** [comment]
Would love to have a chat about this. I'll ping you on Skype.
