### ISSUE TITLE
Search filter request! source:collections or source:reobtainable

### ISSUE THREAD

**Issue by TannerFox** [DestinyItemManager/DIM#10371]
### Proposed change

I think this could really help with cleaning the vault removing weapons that are in collections. Also, when you search in the records tab, this would make a great spot to search for weapons that may fit criteria for Bounties, Burns and build synergy.

### How does this fit into your workflow?

I am running out of Vault space. I keep a couple core exotics, craftable ones, and random rolls (hawkmoon). 

I have 2 exotics I tag for infusion, I use these two anytime I want a different exotic, I just reobtain, infuse, and i'm good to go. 

Playing PvP or PvE I'll run over to to Records, and is:exotic. Do a quick browse of every exotic weapon in the game. Now that weapons are getting un-sunset(?) there are a lot of weapons that i'm not going to carry around that id love to have in a search via collections that I know is reobtainable

In the same sense, if vault cleaning is a goal, source:collections or source:reobtainable could be a great way to get some quick space or infusion fodder in a pinch.

**Comment by TannerFox** [comment]
This would not include exotic armor in my opinion, simply because it is not truly something you can reobtain from collections. 
Correction: is:reobtainable not source:reobtainable
Thanks!

**Comment by delphiactual** [comment]
here is where and the why that the old search was removed https://github.com/DestinyItemManager/DIM/pull/5597

**Comment by TannerFox** [comment]
(is:exotic is:weapon -is:crafted) or (source:ritual-weapon) is pretty much the best I ca ndo on my own. Thanks!
