### ISSUE TITLE
Custom hot keys for filters

### ISSUE THREAD

**Issue by themacguy2k** [DestinyItemManager/DIM#1038]
There are SO many filters that it could be nice to have a few hotkeyed or allow the user to set hotkeys for a few favs.

Alternatively, maybe a few buttons at the top of dim that can be used this way. I know would clutter the interface but 3-5 wouldn't be bad.

My main use is for this request is the  is:unlock filter so having a way to activate this quickly would be nice, especially with all the new items we are getting right now. I have to imagine other ppl have a few favs as well.

**Comment by bhollis** [comment]
Definitely something I want to do for #397.
