### ISSUE TITLE
mobile vault dropdown: "material counts" lost its icon color inversion

### ISSUE THREAD

**Issue by nev-r** [DestinyItemManager/DIM#10393]
![image](https://github.com/DestinyItemManager/DIM/assets/68782081/3b906354-fd8b-4aba-8113-84d974526aea)

**Comment by Samaresh-Das** [comment]
Hi. Can you elaborate the issue more. The color version part. I would love to work on this.

**Comment by bhollis** [comment]
There is an icon next to "Material Counts" in the loadout popup menu for the vault. It's supposed to be inverted so it is white-on-black, but for some reason the styles aren't applying correctly so it's black-on-black.
