### ISSUE TITLE
DIM showing armor I don't have when optimizing armor

### ISSUE THREAD

**Issue by ArconusNocturn** [DestinyItemManager/DIM#10390]
### DIM Version

Version 8.18.1.3319 (beta)

### Browser Details

Chrome

### OS Details

Windows 11 Pro

### Describe the bug

DIM is adding items I don't have into the armor optimizer when I try to optimize loadouts.

**Comment by robojumper** [comment]
These are vendor items, as indicated by the shopping cart icon. If you don't want that, enter `-is:vendor` in the search bar.
