### ISSUE TITLE
Perk from wishlist is not displayed

### ISSUE THREAD

**Issue by benjaminfunk** [DestinyItemManager/DIM#10409]
### DIM Version

Version 8.19.1 (release), erstellt am 13.5.2024, 08:02:42

### Browser Details

Chrome 124.0.0.0

### OS Details

Windows 10

### Describe the bug

I'm not sure if it's a bug or if I misunderstood it.

I have several grenade launchers (EDGE TRANSIT). For one, "Envious Assassin" is marked as recommended in the wish list, but for the other, it is not.

I use the Voltron wish list

<img width="376" alt="Screenshot 2024-05-13 113616" src="https://github.com/DestinyItemManager/DIM/assets/856290/3b45f20d-b250-4d88-849c-aa5268d12d31">

<img width="353" alt="Screenshot 2024-05-13 113645" src="https://github.com/DestinyItemManager/DIM/assets/856290/3510c849-a133-4fa4-a25f-938aefad8889">

**Comment by bhollis** [comment]
See https://guide.dim.gg/Wish-Lists for info on how wish lists work.
