### ISSUE TITLE
New filter is:uncollected

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#10404]
### Proposed change

The vendor page has a checkbox named "only show uncollected items".  I'm proposing this exact functionality be exposed as a filter is:uncollected

Other optional names for the opposite sense of the same filter is:collected is:incollection

### How does this fit into your workflow?

The real use for this filter is on the records page.  I want to determine which weapons I have never acquired.

I want to find the weapons highlighted below.

![image](https://github.com/DestinyItemManager/DIM/assets/25425159/37e89586-7704-45b8-a731-38418d5b8160)

Optionally, if not a filter, then the same checkbox from the vendors page could be added to the records page.

**Comment by bhollis** [comment]
https://pr.dim.gg/10584/ has a version of this. It's a bit weird, since some items don't show as collected for some reason...

**Comment by bhollis** [comment]
@philkernick did you have a chance to try this out?

**Comment by philkernick** [comment]
I can see it's been implemented as is:collected.  Which means to find the uncollected, I need -is:collected. The screenshots below have -is:collected applied.

Mostly it seems to work as expected, but I note the following minor issues.

For the craftable exotic mission catalysts they still show up as uncollected, but if I click into any of them they say unlocked in collections.

![image](https://github.com/user-attachments/assets/982a49f1-99c4-4046-846c-1185b48ea7ff)

Emotes and ghost projects are not consistent.  All of the ones that are not shaded should not be shown as I have them.

![image](https://github.com/user-attachments/assets/bb0193b6-e2af-4dcb-b9d3-50d62c74256c)

![image](https://github.com/user-attachments/assets/813ecda7-be45-49a5-94f8-ddc7d254b65f)

Universal ornaments are also not consistent.

![image](https://github.com/user-attachments/assets/f010ccfd-3083-4c0f-92b0-f316eb725e5e)


The blue ticked ones are unlocked in collections, so shouldn't be showing here.

**Comment by bhollis** [comment]
Yeah, this is only implementing the same check that vendors uses, in the spirit of "I'm proposing this exact functionality be exposed as a filter is:uncollected". It doesn't have any extra logic to handle all the other special cases in collections.

**Comment by bhollis** [comment]
Since there hasn't been any other interest, and the definition of "collected" is so difficult, it's not worth it.
