### ISSUE TITLE
Automatically add loadout stat totals to notes section

### ISSUE THREAD

**Issue by Keelhauler** [DestinyItemManager/DIM#10418]
### Proposed change

When saving a custom loadout, automatically add the total stats, or at least the tiers of each stat, into the notes section for ease of sharing.

### How does this fit into your workflow?

I've seen too many loadouts get shared that did not include a stat total so there had to be some guessing for totals and how a build might prioritize something slightly differently than how I normally do things, I believe this is true for many people that simply share loadouts with friends without giving any in-depth context on a build other than, this build seems sick, here are the mods and exotic I run along with a dim loadout link.

Having the stat totals be automatically input would allow anyone to easily create their own loadouts using the shared loadout as a base without having to wait for a reply should the sender leave for an extended period of time.

**Comment by bhollis** [comment]
This is a feature of the loadout optimizer - if you set your stat priorities when building a loadout, that info will be captured and shared so the recipient can make their own build that meets those constraints. We don't do that for loadouts that weren't made in loadout optimizer because there's no way to know if those stats were actually important or not.

**Comment by Keelhauler** [comment]
That's strange then, all of my loadouts were created with the optimizer and when I tried sharing them with friends there were no stat totals received anywhere. The same goes for loadouts I've received from friends. We all build using the loadouts optimizer, and I've confirmed as much.

**Comment by delphiactual** [comment]
please post a link to a shared loadout so we can troubleshoot

**Comment by Keelhauler** [comment]
Sure, here's a loadout with the stat totals: https://dim.gg/e3ujwva/Battle-Harmony
Then one that was created earlier in the current season but does not have the stat totals when shared: https://dim.gg/vhendwy/Dawn-Chorus-Explosions

Unless it seems like a fluke on my end, I think the issue is inconsistent and sometimes the stat totals are included when shared now that I take a look at both.

**Comment by bhollis** [comment]
Best I can guess is that one of those was created with the loadout optimzier settings saved in it, and one was not.
