### ISSUE TITLE
Feature/Bug: Felwinter artifact makes tier analysis not useful

### ISSUE THREAD

**Issue by vanhauser-thc** [DestinyItemManager/DIM#1042]
Hi,

wenn performing the tier analysis, all options recommend selecting the felwinter artifact (as it achieves 5/5/4 for all my chars).

but as felwinter obviously disables the INT rating, this makes the analysis flawed.

my recommendation: make an option to ignore the felwinter artifact - or ignore it always.

**Comment by wein3967** [comment]
FYI, shift+clicking on an item excludes it from load-out calculations.
