### ISSUE TITLE
(S20) mindbender is matched by source:strikes and not matched by source:nightfall

### ISSUE THREAD

**Issue by deangaudet** [DestinyItemManager/DIM#10425]
### DIM Version

Version 8.19.2.3340 (beta), built on 5/17/2024, 12:45:08 AM

### Browser Details

125.0.6422.61

### OS Details

Windows 10

### Describe the bug

i did this testing on the records page because i don't have any of these guns currently

mindbender non-adept (hash 1586231351) seems to match source:strikes, yet it is the only nightfall gun present in source:strikes so i think that is an error.  i think it should be matched by source:nightfall rather than source:strikes.

mindbender legacy and mindbender adept both match source:nightfall and don't match source:strikes so i think they're good.

thanks!

**Comment by delphiactual** [comment]
https://data.destinysets.com/i/InventoryItem:1586231351/Collectible:3399616395
