### ISSUE TITLE
Bring back sub-order by name

### ISSUE THREAD

**Issue by dhinged** [DestinyItemManager/DIM#1043]
Apparently this was removed (or the option is not easy to find) to completely sub-sort by light level (regardless of stat or rarity), which makes cleaning out duplicates difficult.

The current Settings now only allow for Primary stat or Rarity, with no way to change the default sub-sort. Since light already displays by default on the item, it's relatively easy to find the light level you need regardless of sort; however since item name does not display (and wouldn't be legible anyways), it's difficult to find duplicate items.

If you don't find this feature useful or it's not planned on coming back as an option, you may point me to the place(s) in code where this can be added (back). Thanks.

**Comment by kyleshay** [comment]
We do have an item comparison feature coming soon which will help with cleaning out duplicates and other items by comparing them directly. Until then, there is a filter `is:dupe` or `is:duplicate` which will highlight all duplicate items. 

Do you think either of those things could help for cleaning out duplicates?

**Comment by dhinged** [comment]
Sure, but it sub-ordered by name before so I don't know why that was removed or shouldn't have been left as an option.

Would it get in the way to bring back the "name" sub-order option? Can you point to me where in the code I would add that to save me some time? Thanks.

**Comment by kshep** [comment]
is:dupe with alphabetical sort used to be my primary cleaning tool. The ability to select different items and compare them really doesn't replace that, since you have to hunt around and find the dupes to compare. With the removal of alphabetical sort, my usage of destinychecklist is way up.

**Comment by dhinged** [comment]
@kshep Not sure why your reply email notification didn't have a link to this webpage (had to click the link on kyleshay's reply email), but what do you mean by "is:dupe"? Ditto?

I'll have to check out destinychecklist, but a one-stop app like DIM mostly is would be a better solution, and I'll contribute if someone will point me to where to change the code otherwise it may take me a while or inordinate amount of time to find it as I haven't worked on this yet but am adept with web technologies.

**Comment by kshep** [comment]
@dhinged I was referring to the "is:dupe" filter in DIM. My ideal clean-up mode would be to just display duplicates, move them to my vault to get them all in one place, then just sort by name to see items grouped independent of light level.

I'd definitely like DIM to be my one-stop app, but destinychecklist still offers some sorting and filter-by-tag functionality that probably doesn't fit the DIM UX easily.

**Comment by kyleshay** [comment]
we have tags + notes coming (it's already there in the beta branch), so you can mark items as 'junk' so you know which to trash

**Comment by JakeWhitaker** [comment]
In addition to this, it'd be nice to have vault sorting sub-options like sorting armor by class>rarity>percentage.

**Comment by bhollis** [comment]
@JakeWhitaker see #647

**Comment by bhollis** [comment]
I'm going to resolve this in favor of #647.
