### ISSUE TITLE
Character next to light level?

### ISSUE THREAD

**Issue by shockthealien** [DestinyItemManager/DIM#1045]
Hi, was just checking the new feature that lets you see the max possible light before equipping it (great feature by the way) when i realised theres a symbol next to the light level. Dont know why i never noticed it at the top, but the point is that it doesnt display correctly. What is it supposed to be?

![screen shot 2016-10-12 at 09 54 10](https://cloud.githubusercontent.com/assets/2083273/19303899/671444c4-9062-11e6-96e8-96ccab6e93a8.png)

zoomed in

![screen shot 2016-10-12 at 09 59 43](https://cloud.githubusercontent.com/assets/2083273/19303953/9f560a20-9062-11e6-8ba4-48089e0700bd.png)

**Comment by kyleshay** [comment]
hmm, that's odd.

![screen shot 2016-10-12 at 12 10 57 pm](https://cloud.githubusercontent.com/assets/424158/19318016/f4dcc990-9074-11e6-85b6-6db6f5941def.png)

**Comment by shockthealien** [comment]
maybe a font conflict?

**Comment by bhollis** [comment]
What OS are you on?
