### ISSUE TITLE
Destiny Item Manager Won't Load

### ISSUE THREAD

**Issue by bradb1982** [DestinyItemManager/DIM#10454]
### DIM Version

 v8.20.0.3360

### Browser Details

Version 124.0.6367.208 (Official Build) (64-bit)

### OS Details

Win 11

### Describe the bug

It doesn't seem to load, I tried both Beta and the regular DIM.  

### Logs

```shell
console.ts:40 [app] DIM v8.20.0.3360 (beta) - Please report any errors to https://www.github.com/DestinyItemManager/DIM/issues
```

**Comment by bhollis** [comment]
Not enough info here to help. Please drop by the discord and someone can walk you through describing the problem.
