### ISSUE TITLE
Troubleshooting Guide - Update

### ISSUE THREAD

**Issue by bradb1982** [DestinyItemManager/DIM#10453]
### Proposed change

The link below, for clearing chrome settings, doesn't work on chrome anymore and this section could be updated. 
If you want to clear data manually, make sure to clear it all for destinyitemmanager.com, not just "last 24 hours". In Chrome, you can visit chrome://settings/siteData?searchSubpage=destinyitemmanager.com and click the trash can next to the version of DIM you want to clear. WARNING: If you didn't have [DIM Sync](https://github.com/DestinyItemManager/DIM/wiki/DIM-Sync) enabled, you will lose all your data when you clear site data! Make sure you have a backup!

### How does this fit into your workflow?

Just a suggestion.

**Comment by bhollis** [comment]
Thanks, we've removed that.
