### ISSUE TITLE
Enhanced Bipod stat penalties are displayed incorrectly

### ISSUE THREAD

**Issue by Prometheus3375** [DestinyItemManager/DIM#10479]
### DIM Version

Version 8.21.1 (release), built on 27.05.2024, 20:49:58

### Browser Details

Chrome 124.0.0.0

### OS Details

Windows 10

### Describe the bug

Variant w/o Bipod.
![image](https://github.com/DestinyItemManager/DIM/assets/35541026/70ffd86d-7b75-4345-8c4d-c685530e0119)

Variant w/ Bipod.
Blast radius: 95 -> 65 (correct)
Reload speed: 38 -> 18 (correct)
![image](https://github.com/DestinyItemManager/DIM/assets/35541026/8abf00a2-4582-47f7-a868-fdc7d25a1aa4)

Variant w/ Enhanced Bipod.
Blast radius: 95 -> 40 (incorrect, should be 70)
Reload speed: 38 -> 3 (incorrect, should be 23)
![image](https://github.com/DestinyItemManager/DIM/assets/35541026/05278354-87ac-4345-a2fb-05be799ca19a)

It looks like when calculating penalties for Enhanced Bipod, penalties of regular Bipod are also included. 95 - (30 + 25) = 40 and 38 - (20 + 15) = 3.

**Comment by bhollis** [comment]
https://data.destinysets.com/i/InventoryItem:2282937672

<img width="548" alt="Screenshot 2024-05-31 at 12 20 27 PM" src="https://github.com/DestinyItemManager/DIM/assets/313208/a8df45e8-ae5d-48af-be34-6bbe43c0dd6a">

So that's what Bungie says. `isConditionallyActive` of course is the trick - we can't know what the conditions are.

**Comment by Prometheus3375** [comment]
I see, Light.gg also has this issue, but foundry displays it correctly, maybe they manually fixed that.

**Comment by bhollis** [comment]
We could check all plugs and see if we can get away with a rule of "if the same stat is present twice, take the second occurrence"

**Comment by bhollis** [comment]
Hmm, this is a bit more complicated than expected. For example, here's Enhanced Lasting Impression: https://data.destinysets.com/i/InventoryItem:1167468626

<img width="542" alt="Screenshot 2024-06-19 at 2 17 05 PM" src="https://github.com/DestinyItemManager/DIM/assets/313208/57932a1f-954b-41c6-b5d9-307e5e263ac6">

It *does* appear to grant 55 blast radius.

**Comment by bhollis** [comment]
And interestingly, Enhanced Bipod was fixed in the definitions.
