### ISSUE TITLE
Small Icons for Perks

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#1049]
> Is there a way to change the perk node size and if not would it be possible to add one? It might be because I have a 1440p display but all the perk nodes are super tiny.

https://www.reddit.com/r/DestinyItemManager/comments/57aqoc/perk_nodes_are_way_to_small_on_my_display/

![dim perk size](https://cloud.githubusercontent.com/assets/984608/19355384/d225b9aa-912f-11e6-92d1-8515a3f91b6c.png)

**Comment by delphiactual** [comment]
https://www.reddit.com/r/DestinyItemManager/comments/554nwh/bug_perks_of_weaponsarmor_are_shown_to_small/

**Comment by bhollis** [comment]
Weird, I've never seen that.

**Comment by kyleshay** [comment]
28c833aace5114320e0321a4e1962208ddd876a4
