### ISSUE TITLE
Three copies of every memento

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#10493]
Not sure if this is new to The Final Shape but we show three copies of every memento in the socket picker:

<img width="832" alt="Screenshot 2024-06-04 at 4 54 27 PM" src="https://github.com/DestinyItemManager/DIM/assets/313208/51a19e03-4318-4ef4-9288-6cf023077288">

**Comment by robojumper** [comment]
D2AI always came up with three hashes per memento type too so the data isn't much different
