### ISSUE TITLE
Double traits en perks for all weapons

### ISSUE THREAD

**Issue by UserrX** [DestinyItemManager/DIM#10505]
### DIM Version

Version (release), built on 03/06/2024, 04:01:57

### Browser Details

Brave 125.0.0.0

### OS Details

Linux

### Describe the bug

All weapons show double traits en perks.

![image](https://github.com/DestinyItemManager/DIM/assets/132231043/7c6fa5ea-ee89-4146-a472-6957900119bd)

![image](https://github.com/DestinyItemManager/DIM/assets/132231043/d23f197c-fedc-45c3-811c-c3a2aa9fe71f)

**Comment by robojumper** [comment]
This is a Bungie.net API bug, related to https://mastodon.social/@bungiehelp/112560171695573350

**Comment by pdxHAVOC** [comment]
Is there a fix or an ETA on one? This makes DIM almost unusable.

**Comment by bhollis** [comment]
No, we have to wait for Bungie to fix it.
