### ISSUE TITLE
Loadout Search: Replace subclass: with super:?

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#10502]
With the prismatic subclass, I wonder if we should search by `super:void` instead of `subclass:void`.

**Comment by ryan-rushton** [comment]
yeah we probably should, I wonder how the community is referring to them atm. I might ask on discord over the weekend

**Comment by ryan-rushton** [comment]
Ok, after playing around with search and the stasis prismatic build I have it doesn't currently show up when I search for stasis. I am not sold now whether we should use subclass or super as the keyword, let me have a bit of think

**Comment by bhollis** [comment]
I think it's good as is. We can't easily figure out (without a hardcoded map) which element the selected prismatic super is.
