### ISSUE TITLE
Label "Better stats available" on Equipped, pressing "Optimize Armor" shows the same loadout

### ISSUE THREAD

**Issue by Prometheus3375** [DestinyItemManager/DIM#10518]
### DIM Version

Version (release), built on 03.06.2024, 05:01:57

### Browser Details

Chrome 124.0.0.0

### OS Details

Windows 10

### Describe the bug

I have a loadout which was optimized by DIM. Here are the settings (no pinned or excluded items) and results:

![image](https://github.com/DestinyItemManager/DIM/assets/35541026/d5c092be-7f01-4857-b56f-38c98d41b1ab)

My loadout is the best among the results and DIM does not show label "Better stats available" on it.

When I equip it, DIM shows label "Better stats available" on Equipped:

![image](https://github.com/DestinyItemManager/DIM/assets/35541026/d4c93691-44a0-48eb-9541-73b08cb5c755)

When I press "Optimize Armor", I see next settings selected:

![image](https://github.com/DestinyItemManager/DIM/assets/35541026/14760dc2-801c-4237-8e67-537dc5fb7924)

For whatever reason Strength is disabled and the suggested loadouts have more Discipline, but less Strength. When I use the same settings as for the original loadout, it shows me the same loadout, but it should show variants better than current.

![image](https://github.com/DestinyItemManager/DIM/assets/35541026/2aa54794-14cb-4ab4-93ac-7a90f33a4dbe)

I did not find an option to reset optimizer settings for Equipped, so I post this report.

**Comment by robojumper** [comment]
@Prometheus3375 For the currently equipped loadout, the background analyzer should take your saved LO settings, so if those exclude Strength, then that's what the optimization for the Equipped loadout it going to use. What does Loadout Optimizer look like if you visit it directly (Loadouts -> "Loadout Optimizer" button -> choose the correct class)? Can you re-enable strength there?

**Comment by Prometheus3375** [comment]
Just checked, indeed, I have disabled Strength there. Once re-enabled the label disappeared.
