### ISSUE TITLE
Ergo Sum - Weapon Card Tidy

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#10519]
We should hide this mod that doesn't actually exist.
![image](https://github.com/DestinyItemManager/DIM/assets/4798491/229918f3-b0e1-460d-ad81-835db302f4e3)
![image](https://github.com/DestinyItemManager/DIM/assets/4798491/da204508-66be-4424-aa46-958e2f6a49b7)

**Comment by nev-r** [comment]
we also need to clean up/design the display for the frame (in your screenshot, the "lightweight" icon)

no weapon has had both a frame and an intrinsic before

@lowPolySkeleton input welcome

**Comment by nev-r** [comment]
item feed also needs a useful display that includes both intrinsic and frame

**Comment by Prometheus3375** [comment]
I have 6 wishlisted rolls for Ergo Sum, all of them includes random intrinsic. This is how they are displayed (not displayed at all).

![image](https://github.com/DestinyItemManager/DIM/assets/35541026/1d00b509-9b3e-48aa-8098-a5d1675a2f7c)

Regardless, DIM correctly identifies wishlisted rolls with intrinsic. For example I have wishlisted Wolfpack Rounds, 3 blades and Lightweight frame. Roll with Wolfpack Rounds is marked with 👍🏻, roll with other intrinsic, but same blades and frame is not.

**Comment by bhollis** [comment]
Yeah the intrinsic isn't included in the wish list display
