### ISSUE TITLE
Show the pathfinder challenges in Progress

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#10525]
I have an in-progress branch for this if someone would like to take it: https://github.com/DestinyItemManager/DIM/tree/pathfinder

The SeasonalChallenges component would likely need to be forked for this into something more customized to the Pathfinder. One question I have is whether we should show all of the pathfinder challenges that are active at once, or only the "next" ones (or show both and separate them somehow?). I don't really know how the pathfinder works.

**Comment by delphiactual** [comment]
Pathfinder allows all challenges to be advanced at once, but can only be turned in if a challenge that touches is completed.

**Comment by hilfandy** [comment]
I think all nodes should be shown as viable for progress. It'd be pretty slick if it could prioritize ones that take you to the right as a chain, and maybe group (or filter) by activity type. That way you could click to show vanguard progressable nodes and only see the ones you can progress in your chosen activity and prioritize by what will complete a chain
