### ISSUE TITLE
Applying armour mods or changing fragments/aspects fails with a "bungie.net servers are down for maintenance" error

### ISSUE THREAD

**Issue by whiteteapoison** [DestinyItemManager/DIM#10521]
### DIM Version

Version (release), built on 10/06/2024, 03:04:20

### Browser Details

Chrome Version 125.0.6422.142 (Official Build) (64-bit)

### OS Details

Windows 10

### Describe the bug

Apologies if this is a duplicate, but I can't find anything online. Appreciate there may have been breaking API changes with final shape, so could just be that, but since final shape I can't apply any loadouts or change mods in armour (equipped or not) on the inventory screen without getting the error pictured 

![Screenshot 2024-06-10 083018](https://github.com/DestinyItemManager/DIM/assets/47848828/a0aa8904-3029-4467-8fcc-67953de5e998)

**Comment by delphiactual** [comment]
Plugging was disabled by Bungie shortly into day 1 due to a bug, once reenabled loadouts will work again.

**Comment by jamieastley** [comment]
wasn't in the patch notes but Bungie devs confirmed in the Discord earlier today that the Socket Plug API can be used again now so looks like this is resolved 🎉

**Comment by whiteteapoison** [comment]
Spotted it last night myself. Was gonna come back and update today - thanks!
