### ISSUE TITLE
Incorrect light levels. 

### ISSUE THREAD

**Issue by Funktion29** [DestinyItemManager/DIM#1052]
Hi, when using the latest version of DIM I've noticed that the 'Maximize Light' feature calculates light levels wrong when very close to the next level. 

For instance I'm currently at 373 in game with the Light bar being very very close to 374 (I'd guess 1 light or less away). Yet in DIM it shows me at 374.0 light. When I select Maximize Light it says it transfers all the items, but my light doesn't change from 373 to 374 (also no items actually move). 

I also noticed this when I was at a lower value last week during IB, same set of circumstances: I was 367/8 or 364/5 and DIM showed me at 365.0 yet couldn't actually get there in game. 

thanks and let me know if you need more info.

~s

<img width="345" alt="screen shot 2016-10-13 at 8 27 34 pm" src="https://cloud.githubusercontent.com/assets/22829473/19374931/7c1d82c2-9184-11e6-9c68-3f5f5728c025.png">

<img width="689" alt="screen shot 2016-10-13 at 8 37 54 pm" src="https://cloud.githubusercontent.com/assets/22829473/19375012/f46359b4-9184-11e6-98ce-37f3efae2077.png">

**Comment by kyleshay** [comment]
thanks @Funktion29! this has been resolved and currently the fix lives in the beta branch. we should do a push soon so it's live for everyone.
