### ISSUE TITLE
API Health Status Page

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#1053]
It might be useful to give the user a sense of the API health.

**Comment by delphiactual** [comment]
Or even a dot in the upper right hand corner near gamertag that changes color based on the API health

**Comment by delphiactual** [comment]
- [ ] Perk healthcheck
- [ ] Vendor API healthcheck

Are there any more?
If it is just two we could do a split circle design, where each half represents the status of the specific API and the combined status would be known at a glance.
If it is more we could do a thermometer display, or a graph for each one.
If we do go with a graph a simple way would be
Bar | Color | Status
----|-------|----------
Full | green | all data
Half | yellow | some data missing
Empty | red | no data

**Comment by popepeter** [comment]
Maybe use the destiny logo? Right now there's two APIs that would be healthchecked - there's two pieces in the destiny logo. However, because the destiny logo is a tricorn, you could potentially split off each of those into an API if there's more APIs that need to have a healthcheck.

**Comment by bhollis** [comment]
Would we maintain this manually?

**Comment by SunburnedGoose** [comment]
We should start saving a JSON file on our web server to give us a sense of load and provide dynamic data to the client after release.

**Comment by kyleshay** [comment]
We now are pretty good about showing bungie errors in the toast, does that cover this enough?

**Comment by delphiactual** [comment]
Have not had many recurring questions since we added the additional info for the API bits
