### ISSUE TITLE
A "Maximize Light Level" button for all characters - instead of one at a time.

### ISSUE THREAD

**Issue by sk8rdude461** [DestinyItemManager/DIM#1054]
Currently in DIM there is a drop down for each character that has a button to "Maximize Light". I like it as it helps me quickly throw items between characters for max light when claiming vanguard rep packs or whatever.

Though, this feature doesn't work if you're trying to max out more than one character as it will pull gear of the others.

Hence my suggestion. It would probably be quite a pain to implement, but here's the idea:

You click the "Maximize Light" button.

 It pops up asking which order (This isn't really needed, but a way to pick which should be the highest would be awesome) out of your characters. You move the warlock to 1 and your hunter to 2, putting the titan at 3. You hit "Go".

DIM then loads your warlock out with the highest gear possible, including worn items from other characters. Then it "locks" those 10 items from being used in the next 2 characters. Rinse and repeat until all 3 are at their respected max.

Sorry if it's the wrong format. Couldn't add a label or anything to mark it as a suggestion.

**Comment by shockthealien** [comment]
Dont understand why this would be useful, you cant play more than one at the time anyway

**Comment by sk8rdude461** [comment]
Right...

But then you have people like me that have gear so all 3 characters can be the highest light level without the need of transferring gear over.

And if I click "Maximize Light" on one character, it may pull gear from another, I'd like the ability for that to not happen.. And if it does pull gear from a different character; they get stuck with whatever they had in inventory (and if nothing, a random vault item).

**Comment by geck0s** [comment]
It may be simpler from a UI perspective to simply have a toggle (maybe a pair of checkboxes) that disallows taking items equipped on your other characters.  A toaster could explain the usage:  First, max one character with stealing enabled.  Then, move to the next character, uncheck stealing from the first char and mostly-max the second character.  Next, move to the third character and mostly-max without stealing from either of the first two.

Perhaps we could even have a setting to change the default to having stealing from both other characters checked by default unless you've just maxed another character or two in the last say 10 seconds or 5 actions or something, you could exempt the previously maxed characters checkboxes when the menu is opened.  

I'm not sure if such a scheme is as intuitive as possible or easily explained, but by having a setting enable it the majority of users will do what they are used to and the setting would save some clicks for those who want to maximize all 3 most of the time.

I think this avoids the awkwardness of a dialog box that many users won't be interested in.

**Comment by kyleshay** [comment]
The way that max-light currently works is that it pulls the best items that are closest to the character you hit the button on. 

If you hit the button on your warlock, and your warlock has a 400 primary in it's inventory, it will equip that one. If it didn't have one in it's inv, then it would pull from the vault... if the vault didn't have one, it would pull from the inventory of a random other character... if they don't have one in their inventory it will pull it from their equipped items. 

I'll keep this issue on the table for now if anyone wants to pick it up. I'd reccomend making it part of the same row on the max-light button, similar to 'Gather engrams ----  (\ ) Exotics' so it would be 'Max light *387 ---- All Characters'

**Comment by kshep** [comment]
How about having an option to "lock" a character? That'd come in handy both here and with farming. Then I could max light my Titan, lock it, max light the next character, lock it, max light the third.

**Comment by sk8rdude461** [comment]
I really like the ideas guys.

@kshep The lock could work, and would probably be easier from a developer standpoint.

Though my initial idea was to have a single button that would max the light for all 3. But if that's too much work for a not-so-needed feature, I'd gladly accept character locking.

@kyleshay 
I understand, however the problem is that if I hit "Max light level" on one character, and another is wearing the best gear, it'll pull it. I'd _like_ to be able to make the primary character the highest light level possible out of all 3 characters, and the other two wear the highest available otherwise.

I.E: Click a button, it loads my warlock out to 388LL, my titan to 386, and my hunter to 385, as that was available within the vault.

I did have the idea about the button next to the engrams (no really, I was gonna make a mock up and everything lol) but got caught up with some stuff.

**Comment by bhollis** [comment]
My gut feeling is that this suggestion, and the "lock character" suggestion, are both more complexity and fidgety detail than we want to add to the app.

**Comment by geck0s** [comment]
Yeah, that's a definite possibility.  I don't like the original idea of a dialog box, I don't feel like my ideas with checkboxes is very simple or immediately obvious what it's for.  I like the lock suggestion but it might have the disadvantage of the lock on another player preventing a user from fully maxing a different character if they have forgotten about locking the other or they just fiddled with that setting without understanding what it was for.  

I think a fair number of players yearn for the ability to lock their characters to protect against accidental deletion so they would click on a lock icon without knowing what it was actually for.

@kshep Can you explain how a character lock feature would come in handy farming?

**Comment by SunburnedGoose** [comment]
This falls into the cosmetic area of features which are really low on the priority list.  I don't see an advantage for such a feature that enhances a players game time.
