### ISSUE TITLE
Loadout Replace All

### ISSUE THREAD

**Issue by Jcooke212** [DestinyItemManager/DIM#10551]
### Proposed change

It would be very useful to be able to replace an item in all loadouts at once.

### How does this fit into your workflow?

An example workflow for this would be

1. Set up multiple builds that use the same instance of the new Stasis burst hand cannon 
2. Unlock the crafting pattern for this hand cannon
3. Make a crafted version of this same hand cannon
4. Replace all instances of the original hand cannon in loadouts with the new crafted one

Without this feature you have to open each loadout separately and replace the hand cannon. This would also allow you to quickly update loadouts that are all missing the same deleted item.

**Comment by bhollis** [comment]
If we did it, it would be part of https://github.com/DestinyItemManager/DIM/issues/9812, but I'm not confident that we'd support replacing arbitrary items. 

The recommendation is to create independent loadouts - make one for your weapons and one for your armor, and then apply both, one at a time. This means you don't need to copy the same items to a bunch of loadouts.
