### ISSUE TITLE
Capatin's Log pursuit (Failsafe Reputation Weekly is not Pinnacle +2 Power Reward)

### ISSUE THREAD

**Issue by Endracion** [DestinyItemManager/DIM#10564]
### DIM Version

Version 8.24.0.3436 (beta), built on 6/17/2024, 6:44:43 PM

### Browser Details

Chrome 125.0.0.0

### OS Details

Windows 10

### Describe the bug

Captain's Log Identified as Pinnacle, but in games shown as Powerful Tier 2, and when opened, it was indeed just powerful. I'm 1993 power and it dropped at my level since I'm beyond the powerful cap.

![image](https://github.com/DestinyItemManager/DIM/assets/12702990/57a5feda-b4ab-40b3-8fff-9f9534150e59)

### Logs

```shell
N/A
```

**Comment by bhollis** [comment]
If that's really the case, then Bungie is sending back the wrong info. We can hack around it...

**Comment by Endracion** [comment]
Just to confirm what's shown in game, I progressed to get it on my 3rd character too, will update again once complete to triple confirm.
![image](https://github.com/DestinyItemManager/DIM/assets/12702990/fc15d0d1-061a-452a-82cd-7f1c53fdda70)

**Comment by Endracion** [comment]
![image](https://github.com/DestinyItemManager/DIM/assets/12702990/148d76ab-ebe9-4ac2-b690-8ed1197569dd)
![image](https://github.com/DestinyItemManager/DIM/assets/12702990/1dd792c1-5715-41c8-95ae-bd71ce715063)
![image](https://github.com/DestinyItemManager/DIM/assets/12702990/ba5d6718-113c-4a97-a222-52dcc9602bea)
Triple confirmation, it's definitely just powerful and not pinnacle.
