### ISSUE TITLE
Plugin System

### ISSUE THREAD

**Issue by xetrics** [DestinyItemManager/DIM#10568]
### Proposed change

I'm sure this has been suggested in the past, but it would be nice for DIM to have plugins as a feature so we can customize the experience more. 

### How does this fit into your workflow?

This would let me write custom plugins for stuff I want to automate. It would also allow the community to start sharing useful plugins.

**Comment by bhollis** [comment]
You're right - this has been suggested in the past, and providing a stable plugin API for DIM is both more work than we would like to take on, and unlikely to be leveraged by many users. If  you have particular plugins you'd like to build, feel free to suggest them as features and/or submit a PR.
