### ISSUE TITLE
Allow revealing raid challenges descriptions

### ISSUE THREAD

**Issue by GlennKintscher** [DestinyItemManager/DIM#10574]
I would love to have an option to reveal the “description” of raid challenges, so that I do not have to refer to other sources for this information (option in the sidebar as well as replacing the default “A challenge awaits…” in the tooltip):

<img width="1446" alt="image" src="https://github.com/DestinyItemManager/DIM/assets/23224757/6ff00ec3-459a-4f53-a121-a4c870d8e0a3">

From my understanding, this data is not part of the manifests etc., so it would have to be provided statically (e.g., src/data/d2/raid-challenges.json). For missing data, the default text would be shown.

Even though I haven't been using React for a long time, I would love to try to implement this feature, should it be interesting.

**Comment by bhollis** [comment]
Yeah, the issue here is 100% that the information isn't available to us and would need to be provided by someone, ideally in each language.
