### ISSUE TITLE
Enterprising Explorer II completed but subsequently still shows as +2 power.

### ISSUE THREAD

**Issue by Endracion** [DestinyItemManager/DIM#10586]
### DIM Version

Version 8.24.0.3445 (beta), built on 6/19/2024, 1:21:13 PM

### Browser Details

Chrome 125.0.0.0

### OS Details

Windows 10

### Describe the bug

![image](https://github.com/DestinyItemManager/DIM/assets/12702990/ed8cccb1-e8ca-479f-acad-6665eb9417c6)

Once the pinnacle is completed, it does indeed become a Tier 2 powerful, but is the detail display here supposed to be like that? And should it still appear as a pinnacle after it's been completed? Or does it mean that it can be cycled 2 more times and it becomes Pinnacle again?

**Comment by bhollis** [comment]
There's definitely some complexity about how rewards work, some of which we can't easily display correctly here. For example these multi phase milestones give rewards based on in game scripts we don't have access to. We do have some improvements in progress for milestones though.

**Comment by Endracion** [comment]
I see, then feel free to close this if it's not considered a bug.

**Comment by bhollis** [comment]
Can you tell me if it's any better at https://pr.dim.gg/10578/ ?

**Comment by Endracion** [comment]
It looks the same to me?

![image](https://github.com/DestinyItemManager/DIM/assets/12702990/e5b46a00-1d9a-41da-928e-3e63325c96b3)

**Comment by delphiactual** [comment]
try now

**Comment by Endracion** [comment]
Ok, I see it gets shifted to powerful +0 in my case on the character that already has the pinnacle completed.
![image](https://github.com/DestinyItemManager/DIM/assets/12702990/85eb27c0-b015-4180-b7e7-42017c6be8b5)

It lists multiple tier 2 powerfuls though, I'm not sure it's repeatable that many times? But I haven't tried either.

**Comment by bhollis** [comment]
OK, we'll have to figure out how to tie rewards to the phase the quest is at, if that's even possible.

**Comment by Endracion** [comment]
The first quest is Explorer I (Pinnacle) and next one is Explorer II (Powerful Tier 2), so maybe there's an Explorer III, I think the updated version above is still better, because it at least removes it from the Pinnacle rewards.
