### ISSUE TITLE
Fixed-roll items are no longer wish-listable

### ISSUE THREAD

**Issue by Entropy-cmd** [DestinyItemManager/DIM#10598]
### DIM Version

Version 8.25.0 (2024-06-23)

### Browser Details

Firefox 127.0.1

### OS Details

Windows 11 Pro

### Describe the bug

Previously wish listed items that had the "thumbs up" icon, before the recent update on June 23rd, no longer have have them such as MIDA Mini-Tool and Last Rite. Would it be possible that I may have access to a previous version? I would like to rollback the update as the wish listing was working as intended for me the previous patch.

**Comment by bhollis** [comment]
Yes, the change unintentionally removed wish-listability from items that do not randomly roll. The good news is you have the best roll of those weapons! But we'll be tweaking things so wish lists can still match them.
