### ISSUE TITLE
Background Artifacts in Loadout Builder

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#1059]
Something is going on with the layout in Loadout Builder. The background color isn't filling the page completely.
![screen shot 2016-10-18 at 3 16 53 pm](https://cloud.githubusercontent.com/assets/984608/19494797/58d0bed6-9546-11e6-9eca-8f58d99cee50.png)

**Comment by ericnelson0** [comment]
I'm not able to reproduce this. Still happening?

**Comment by bhollis** [comment]
Have you seen this again? I haven't noticed it.
