### ISSUE TITLE
Collections filter - is:uncrafted

### ISSUE THREAD

**Issue by frostydj** [DestinyItemManager/DIM#10600]
### Proposed change

From the collections screen, be able to search for (or have a toggle for) uncrafted weapons.

Uncrafted weapons are weapons that are craftable, but the player does not have a crafted version in their inventory/vault.

I have no idea of any limitations between searching from collections to inventory.

### How does this fit into your workflow?

As a collector/completionist, I would like to have a crafted version of every weapon.

As far as I am aware, there is no easy way to do this besides going through each weapon one by one and searching to see if I have this crafted. 

Being able to apply a filter, or toggle an option to only see those weapons that I have not crafted yet, would be a great tool for me and I imagine other players would find it useful too.

**Comment by bhollis** [comment]
I'd recommend using https://engram.blue/crafting for this type of thing - it's a nice, focused tool for managing crafted items.
