### ISSUE TITLE
Marsilion-C weapon card lists enhanced traits

### ISSUE THREAD

**Issue by Prometheus3375** [DestinyItemManager/DIM#10605]
### DIM Version

Version (release), built on 24.06.2024, 05:03:47

### Browser Details

Chrome 126.0.0.0

### OS Details

Windows 10

### Describe the bug

Usually, enhanced traits are listed only if weapon is craftable. For example, my Adept Forbearance is enhanceable, but its card does not list enhanced traits.

Marsilion-C was mislabeled as craftable and shortly after the release of Lightfall this was fixed. But DIM still lists enhanced traits on its weapon card. Moreover, this weapon is not enhanceable right now, so there is no way to get them on this weapon.

![image](https://github.com/DestinyItemManager/DIM/assets/35541026/cd011b71-3587-45e1-bd2a-6d7c02dd91c3)

To be fair, both Light.gg and Foundry have the similar issues:
- For Indebted Kindness "Enhance" in Foundry does nothing, but for Marcilion-C Foundry shows enhanced traits.
- Light.gg does not have button "Show Enhanced Perks" for Indebted Kindness, but it is present for Marcilion-C.

**Comment by bhollis** [comment]
We should probably show the enhanced perks on anything enhanceable. Fixing individual bad data probably isn't in scope.

**Comment by bhollis** [comment]
This is indeed a bug in the Bungie data - I don't think we'll fix it manually.
