### ISSUE TITLE
Scrollbar is too small.

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#1060]
The vertical scrollbar is too small horizontally.  I can't even grab it with the mouse on my mac since the windows have no chrome unlike windows.  Fatten' it up!

![screen shot 2016-10-18 at 3 21 26 pm](https://cloud.githubusercontent.com/assets/984608/19494852/9eff267c-9546-11e6-8da3-aa17443b6bb6.png)

**Comment by kyleshay** [comment]
it's 2016 get a trackpad/mouse with a scroll wheel! 🙉 

😛 

what if on hover of that area it got wider. best of both...

**Comment by SunburnedGoose** [comment]
As long as I can grab it when my nose is near the edge.

**Comment by SunburnedGoose** [comment]
*mouse.
