### ISSUE TITLE
Missing german translation

### ISSUE THREAD

**Issue by benjaminfunk** [DestinyItemManager/DIM#10610]
### DIM Version

Version (release), erstellt am 24.6.2024, 04:03:47

### Browser Details

Chrome 126.0.0.0

### OS Details

Windows 10

### Describe the bug

Missing translation for the german language for "Progress > Milestones"

<img width="922" alt="Screenshot 2024-06-27 140404" src="https://github.com/DestinyItemManager/DIM/assets/856290/111c4356-b42d-4619-800c-952b7bafd0c6">

**Comment by bhollis** [comment]
This is unfortunately a missing translation in the Bungie data.

**Comment by bhollis** [comment]
This seems to already be fixed: https://data.destinysets.com/i/Milestone:1842744102
