### ISSUE TITLE
Loadout builder ignores items below 280 light even in "current light" mode

### ISSUE THREAD

**Issue by geck0s** [DestinyItemManager/DIM#1061]
Rares and Legendaries below 280 are excluded from the show gear list even when full and current are selected under advanced options.  I'm sure many users will acquire better gear before discovering DIM, so this is more of a corner case, mostly releveant only to players returning, new-class alts, switching consoles, or just crossing 280 light as they level up.  

I fired up DIM on my other gamertag and found that my Titan and Hunter don't get any suggestions even though the Titan does have a y2 exotic helm at 280.  It simply says Loading best sets (0.00%) and the advanced settings button is not present.

![image](https://cloud.githubusercontent.com/assets/12294244/19420412/d070dd02-93b8-11e6-80f5-f23b3aa5f259.png)

Only the warlock with 290 exotic arms generates a list which then stays visible when I switch classes until the filter sets drop down is changed.  

![image](https://cloud.githubusercontent.com/assets/12294244/19503323/bd4922ce-9580-11e6-88d3-1528eeabb3d1.png)

Using the beta extension Version 3.11.1.494

**Comment by kyleshay** [comment]
Out of scope for D1 - We'll fix this in D2, as we'll probably have to re-work the loadout builder anyway.
