### ISSUE TITLE
Xur inventory refresh timer is very wrong

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#10623]
### DIM Version

current beta

### Browser Details

chrome

### OS Details

windows 11

### Describe the bug

Xur inventory refresh timer says it refreshes in nearly 3 million days.

![image](https://github.com/DestinyItemManager/DIM/assets/25425159/e060ef12-2c90-499f-b8ca-4a7d8983ba87)

**Comment by bhollis** [comment]
Can you describe how you got to that screen? I don't see the same:

<img width="1141" alt="Screenshot 2024-06-28 at 9 33 03 PM" src="https://github.com/DestinyItemManager/DIM/assets/313208/6b5ac313-f69c-4a42-9c95-b7ddd0c79b40">

**Comment by philkernick** [comment]
Vendors, then clicked on Strange Gear Offers.  I see exactly the same number on More Strange Offers.

I've checked all the other similar panels for ever other vendor, and I see the same thing for Last Wish offers from Hawthorne.

![image](https://github.com/DestinyItemManager/DIM/assets/25425159/cab91458-b406-42e9-967c-695fc7850a21)

Also on Sabotage from Variks.

![image](https://github.com/DestinyItemManager/DIM/assets/25425159/ad52b6ae-346e-4240-8f2d-931b1b9f4be3)

Every other one looks right.

**Comment by bhollis** [comment]
I'm afraid I can't reproduce this at all.
