### ISSUE TITLE
Loadout search field shouldn't autocomplete

### ISSUE THREAD

**Issue by Revadike** [DestinyItemManager/DIM#10635]
### DIM Version

Version 8.26.0.3495 (beta), built on 05/07/2024, 20:25:30

### Browser Details

Firefox 127.0.2 (64-bit)

### OS Details

Windows 11

### Describe the bug

Similar to this issue:
https://github.com/DestinyItemManager/DIM/issues/8636

The search field shouldn't autocomplete, because it obscures the search results, which is really annoying:
![image](https://github.com/DestinyItemManager/DIM/assets/4411977/9e55689c-adbf-4540-85b5-8ca456147f5b)
![image](https://github.com/DestinyItemManager/DIM/assets/4411977/ead262e1-51c7-4142-b791-49e814e85c74)

**Comment by bhollis** [comment]
I disagree - without autocomplete, it's extremely difficult to make use of the search keywords and operators. If you want to dismiss the menu, hit the `Enter` key after typing however much you want.
