### ISSUE TITLE
Please move grouping options into the inventory screen

### ISSUE THREAD

**Issue by bocktm** [DestinyItemManager/DIM#10633]
### Proposed change

I LOVE the ability to group items on the inventory screen, but would love it even more if we were able to regroup them right from the inventory screen (instead of burying the feature in the settings page).

![DIMInventoryGroupBy](https://github.com/DestinyItemManager/DIM/assets/1713259/07898b23-6ea5-4dd5-9b17-b4b8089c4ad2)

### How does this fit into your workflow?

The search tool is great for locating specific items or item characteristics; however, when trying to bulk manage the items in our vault - or to search for something we're not sure the characteristics of - the ability to group (and regroup) them right from the inventory screen would be immensely helpful.

**Comment by bhollis** [comment]
The inventory page is for quickly finding and moving items - for deciding on which items to keep use the Organizer or Compare tools.
