### ISSUE TITLE
Increase/remove max note length

### ISSUE THREAD

**Issue by Revadike** [DestinyItemManager/DIM#10636]
### Proposed change

Increase/remove max note length

### How does this fit into your workflow?

For months now, I have been running a script that removes the `maxlength` attribute from notes, because I do not have enough room to always describe all rolls I want for guns. All this time I have not run into any issues. So, it would be nice to have this change natively added to DIM.

**Comment by bhollis** [comment]
I will update it to a max length of 1024 characters, which is the most the backend will accept.

**Comment by bhollis** [comment]
That said - if you would like to describe the rolls you want for guns, I'd suggest using a wish list.

**Comment by Revadike** [comment]
Thanks!

> That said - if you would like to describe the rolls you want for guns, I'd suggest using a wish list.
 Wishlists seem terribly inconvenient to maintain. They should be better integrated, as opposed to requiring external tools. Allow us to select the preferred perks directly on the weapon, when inspecting them. It would also be nice to define multiple god roll combo's or variations.
