### ISSUE TITLE
Max LL gear issue per character

### ISSUE THREAD

**Issue by SeifMerzban** [DestinyItemManager/DIM#10642]
### DIM Version

8.27.0 (beta)

### Browser Details

Chrome 126.0.6478.127

### OS Details

Windows 11

### Describe the bug

My hunter has full 2000 LL gear. Whenever I preview either my titan or warlock to see which armor pieces need upgrading, it previews my hunter armor
![image](https://github.com/user-attachments/assets/517b5a7a-fbe9-49ee-ace3-fe436cc9ce8a)

**Comment by SeifMerzban** [comment]
![image](https://github.com/user-attachments/assets/a7894b94-e850-4e16-8345-daa9d69fe2ac)
This is all the logs that show up from the moment I open DIM and just click on my titan LL

**Comment by delphiactual** [comment]
LL is account wide as of The Final Shape
