### ISSUE TITLE
Add search option to filter by Deepsight Pattern Progress?

### ISSUE THREAD

**Issue by dev-asya** [DestinyItemManager/DIM#10643]
### Proposed change

I would like to see the addition of a search filter that allows user to filter inventory by how much Deepsight progress a weapon has acquired/ how many remain to unlock the pattern for crafting. Perhaps the filter could work similarly to "power:"
i.e.
"patternprogress:3" would return all weapons that are on 3/5 deepsight progress for the pattern.

Note that not all weapons require 5 drops, such as throne world weapons that only require 2 deepsights.

### How does this fit into your workflow?

I horde weapons whose patterns i have not unlocked if they are not easily farmable (either raid weapons, or weapons from previous seasons that I did not get the pattern for and who only drop from Xur)
Implementing this feature would help me identify which weapons I am closer to unlocking, so I can use a deepsight harmonizer on weapons that are nearly unlocked.

**Comment by dev-asya** [comment]
i'm relatively new to github but i have a keen interest in destiny so i am happy to try learn to implement this myself (as I think it's a relatively easy issue to implement in most cases?)

**Comment by bhollis** [comment]
I think you're looking for the `deepsight:harmonizable` search. For more detailed craftable weapon info, I'd recommend https://engram.blue/crafting

**Comment by dev-asya** [comment]
Ah that'll do! Thanks for sharing, I always forget about that website
