### ISSUE TITLE
Weapon/Armor Export: Year column is captured incorrectly

### ISSUE THREAD

**Issue by knuxem95** [DestinyItemManager/DIM#1064]
I brought this up in a thread about filters not working correctly for what year an item is, but I think this is a separate issue, albeit surely related.

Essentially, with the .csv weapon and armor exports, the year column is not correct for some items. You can see some example in the image attached. I've filtered this list for Year = 1 and sorted by light. Clearly, anything over 170 isn't a year 1 item. I use this data for the collection worksheet I maintain in Excel and I would have to completely redo my VBA code if this isn't looked at, so any help would be appreciated.

![weapons](https://cloud.githubusercontent.com/assets/18519504/19523229/e0e41880-95e7-11e6-84a9-9af3fb924e61.JPG)

It should be noted that the is:ttk, is:roi, is:vanilla filters don't work completely correctly either in DIM itself, either, but that's a separate issue.

**Comment by bhollis** [comment]
It seems to be working now - take another look?

**Comment by knuxem95** [comment]
I'm still seeing the same issue as before for a number of weapons (didn't even look at armor). See attached.
![capture](https://cloud.githubusercontent.com/assets/18519504/19928538/330523a0-a0d5-11e6-987f-ebfea54ef549.JPG)

**Comment by delphiactual** [comment]
@knuxem95 are you using the stable or beta version of DIM?

**Comment by bhollis** [comment]
Mine seem to be OK:

![screen shot 2016-11-03 at 7 35 17 pm](https://cloud.githubusercontent.com/assets/313208/19992626/bb8bfea6-a1fc-11e6-96c5-3bebce31da6a.png)

**Comment by knuxem95** [comment]
It does appear to be fixed now in the Beta build. Thanks guys!
