### ISSUE TITLE
Unrecognized Content-Security-Policy directive 'prefetch-src'

### ISSUE THREAD

**Issue by GooDeeJAY** [DestinyItemManager/DIM#10684]
### DIM Version

Version (release), built on 8/12/2024, 7:09:50 AM

### Browser Details

Edge - 127.0.2651.98 (Official build) (64-bit)

### OS Details

Windows 10

### Describe the bug

When trying to move multiple items at once, I'm getting this error:

![image](https://github.com/user-attachments/assets/0dbcf84b-7065-4880-b945-acf501dee212)

I've turned off all my extensions from accessing the page, can be seen in sources, no extension source is being loaded:

![image](https://github.com/user-attachments/assets/7f8fffa5-ecb3-4035-83dc-e63548b3992a)

In the beginning of the console output I'm seeing this error:

    Unrecognized Content-Security-Policy directive 'prefetch-src'.

**Comment by GooDeeJAY** [comment]
So, after minutes of playing around with extensions by turning them on/off one by one. I've realized the issue might be coming from the extension called [Free Download Manager](https://chromewebstore.google.com/detail/free-download-manager/ahmpjcflkgiildlgicmcieglgoilbfdp)

I wonder if there is possibility to allow extension to work on all sites except DIM

**Comment by bhollis** [comment]
The warning about the CSP directive is harmless. It's just something that other browsers support that Firefox doesn't.
