### ISSUE TITLE
solar icon no longer has a name

### ISSUE THREAD

**Issue by lowPolySkeleton** [DestinyItemManager/DIM#10686]
### DIM Version

all

### Browser Details

all

### OS Details

all

### Describe the bug

solar icon appears to not have a name anymore 
![image](https://github.com/user-attachments/assets/21a7dd3b-4bc6-4adb-bee1-9ee4801967af)

![image](https://github.com/user-attachments/assets/f710c03f-9a81-45b5-a414-23b9b8c12aee)

**Comment by bhollis** [comment]
https://github.com/DestinyItemManager/dim-custom-symbols/pull/30
