### ISSUE TITLE
All saved loudouts are now missing the subclass, Aspects, Fragments & weapon mods. Plus engrams are now blank if I have any.

### ISSUE THREAD

**Issue by xSALTY-DUFFx** [DestinyItemManager/DIM#10710]
### DIM Version

Version 8.34.1.3561 (beta), built on 31/08/2024, 23:11:00

### Browser Details

Chrome 128.0.0.0

### OS Details

Windows 10

### Describe the bug

Since updating the Blue version of DIM yesterday, my saved loudouts are missing the Subclass, Aspects, Fragments & weapon mods. Also if I have eny engrams on my character, they now show as blank engrams on DIM. It would appear to only be a visual bug though, as I am still equip the the saved loadouts. Just a bit annoying when trying to advise my friend what to put on their build when I can't view mine unless I equip the build first. I did post a screen shot on DIM Discord yesterday about it.
![image](https://github.com/user-attachments/assets/2ccca842-812d-4a29-968f-c798b37ecd9b)
![image](https://github.com/user-attachments/assets/e6de19c1-c87a-4bfe-8b9c-6e830ecb3a97)

**Comment by bhollis** [comment]
I can't reproduce in Chrome 128 on macOS (or any other browser):

<img width="1727" alt="Screenshot 2024-09-01 at 9 49 30 AM" src="https://github.com/user-attachments/assets/7987e12e-5ceb-46e2-93ad-74490054d08e">

Can you follow the steps in https://github.com/DestinyItemManager/DIM/wiki/Troubleshooting and:

1. Make sure that you don't have any extensions/addons enabled.
2. Check the logs and paste them into this issue.

**Comment by xSALTY-DUFFx** [comment]
> I can't reproduce in Chrome 128 on macOS (or any other browser):
> 
> <img alt="Screenshot 2024-09-01 at 9 49 30 AM" width="1727" src="https://private-user-images.githubusercontent.com/313208/363506478-7987e12e-5ceb-46e2-93ad-74490054d08e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMTExNDcsIm5iZiI6MTcyNTIxMDg0NywicGF0aCI6Ii8zMTMyMDgvMzYzNTA2NDc4LTc5ODdlMTJlLTVjZWItNDZlMi05M2FkLTc0NDkwMDU0ZDA4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMVQxNzE0MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTU2OWI1Mzg2NzJlZjU4YTc5ZGQxY2YwYWU1ZjUyZTBmY2Y4YTViOThmYzQ3MzkwM2RiMzM4OTExOTY2OWZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TheL-eeCz0BULIc1hX48wxmsh-ekt1nQfR2NBfcvRPU">
> Can you follow the steps in https://github.com/DestinyItemManager/DIM/wiki/Troubleshooting and:
> 
> 1. Make sure that you don't have any extensions/addons enabled. My guess is you have an adblocker that blocks items with css classes that happen to have a string like "ad" in them, which can happen randomly as our class names are generated.
> 2. Check the logs and paste them into this issue.

Thank you. Pausing adblock & then logging out & back in again fixed the issue.
