### ISSUE TITLE
Full dupe finder [feature req/idea]

### ISSUE THREAD

**Issue by tcurtin** [DestinyItemManager/DIM#1073]
Going through inventory yesterday and paring down (because still don't have unlimited vault space) I found myself digging around using searches like "is:intellect is:discipline auto rain" to highlight all armor that did the same thing, allowing me to keep the best and scrap the rest.  The current is:dupe finds the exact same piece of armor, but ignores stats within armor, and doesn't find stat dupes across armor which in many ways is more important.  I'm not sure what this would be called, and I suspect it wouldn't actually fit under an is: search but would need its own tool like the loadout builder.

Thoughts?

**Comment by wein3967** [comment]
I think that is a solid suggestion. I agree that it can be more useful to find armor pieces that provide the same perks regardless of their name. It does sound like something similar to the part of the loadout builder where you can isolate different perks.

**Comment by kyleshay** [comment]
soon™ https://github.com/DestinyItemManager/DIM/pull/494#issuecomment-252823291
