### ISSUE TITLE
Postmaster items in loadout cause equip to fail with misleading error message

### ISSUE THREAD

**Issue by geck0s** [DestinyItemManager/DIM#1074]
It's nice that the loadout builder lets me create a loadout with the postmaster items, that should not change.

However, when trying to select that loadout, it gives this error:
![image](https://cloud.githubusercontent.com/assets/12294244/19626530/37313b42-9902-11e6-9ae6-b8eef280fd91.png)

Perhaps a new check to see if the item is in the postmaster is necessary to put a better error message in the toaster.

Might want to work on this while addressing #944 
Let me know if it would have been better to just post this there.  It seemed different enough that I decided to make a separate issue for it.

**Comment by bhollis** [comment]
I'll fix this when I fix #1067.

**Comment by delphiactual** [comment]
This now gives the error `The item requested was not found.`
