### ISSUE TITLE
Transfer attempting to equip an unattuned artifact fails with misleading error message

### ISSUE THREAD

**Issue by geck0s** [DestinyItemManager/DIM#1075]
So I just tried to transfer my 107% Two-Sided Coin hunter artifact to my warlock so I could infuse it with the 83% 385 Oddly Colored Cube.

![image](https://cloud.githubusercontent.com/assets/12294244/19627249/a0f4a31c-9910-11e6-8fe7-7f1d64b1a407.png)

Whatever tries to equip something else so that it can be transferred to the vault (not sure if DIM specifies that or if the API decides on it's own) is selecting the 113% 386 Memory of Silimar, presumably because it is highest light and already on the hunter.  However it has not been attuned by my hunter so the error message "Your character has not experienced enough to use this item... yet."  is displayed in a toaster with the title "Two-Sided Coin", which is not the item with the issue.  

Ideally, DIM would automatically try to equip something else and then retry the transfer instead of stopping with an error when something like this comes up.  Alternately, we could score artifacts that we don't know are attuned lower and equip something else in their place first.  

Since I understood the issue, I simply tranferred Memory of Similiar to my titan, then when I moved the two sided coin to my warlock, it worked fine, equipping the 105% 340 Dredgen Yor's Rose on my hunter and then making the transfer.

**Comment by bhollis** [comment]
Yup, that's the same as #951.

Retrying is one way to handle it, but this is the first time we've needed to retry. For everything else, we can figure out if you're qualified to equip it just by looking at item properties.
