### ISSUE TITLE
Add `unknown` tag 

### ISSUE THREAD

**Issue by Lordfirespeed** [DestinyItemManager/DIM#10750]
### Proposed change

Add a new tag, `unknown`, whose symbol is a question mark.

### How does this fit into your workflow?

When a new season releases, god-rolls of new weapons are generally undecided and wishlist files need to be updated.

During this time, I would like to mark new weapons I collect as 'unknown' before I put them in my vault so that, when wishlists are updated, I can quickly find all those weapons and decide which ones to keep.

I would also use this feature regularly when I want to quickly dump items in my vault as I don't have time to consider whether I would like to keep them or not.

**Comment by bhollis** [comment]
Thanks for the suggestion. Please check out https://github.com/DestinyItemManager/DIM/wiki/Frequently-Requested-Features#add-more-tag-values for the rationale behind not adding more tag values. 

You can use a hashtag in notes for this - or use untagged for the unknown state.

**Comment by Lordfirespeed** [comment]
@bhollis thanks for the tip! That will work perfectly for me :)
