### ISSUE TITLE
LO settings do not save boolean flag for "Automatically add stat mods"

### ISSUE THREAD

**Issue by Prometheus3375** [DestinyItemManager/DIM#10763]
### DIM Version

Version 8.43.0 (release), built on 21.10.2024, 05:22:15

### Browser Details

Chrome 129.0.0.0

### OS Details

Windows 10

### Describe the bug

I've already posted a similar issue #10518, but that was for currently equipped loadout. This, however, affect all loadouts.

Today I noticed that most of my loadouts have label "Better stats available". I pressed "Optimize Armor", but it featured the same loadout but with mods, disabling "Automatically add stat mods" showed zero loadout options which were better. Note: for most loadouts this settings was disabled, i.e., pressing "Optimize Armor" should have this option as turned off.

I checked settings for base LO and disabled "Optimize Armor" there. Then I reset LO setting for some loadouts with this label. Despite that, they still possessed such label. I am unsure if it is expected behavior or not.

I resaved my one loadout labeled as "Better stats available" with "Automatically add stat mods" turned off, but shortly after the label reappeared. I thought this was a fluke and resaved again. It seemed it worked, so I resaved all labeled Warlock loadouts with "Automatically add stat mods" turned off.

But then the label returned for all of them. Meanwhile, I noticed that "Automatically add stat mods" in base LO settings was again turned on (I turned it off previously as this post narrates).

After an additional test I measured that option "Automatically add stat mods" resets to turned on for base LO and all loadouts after ~10 minutes of them being non-edited. During these 10 minutes DIM can be reloaded or reopened, the label will NOT reappear due to these actions, it is time based.

Here is logs for the issue: [app.destinyitemmanager.com-1729551561655.txt](https://github.com/user-attachments/files/17467663/app.destinyitemmanager.com-1729551561655.txt)
They were generated in the following way:
1. I opened DIM.
2. Went to base LO, disabled "Automatically add stat mods" there.
3. Resaved one loadout with "Automatically add stat mods" turned off.
4. That loadout was no longer showing label "Better stats available".
5. I left PC for 10+ minutes.
6. When I returned, base LO had "Automatically add stat mods" turned on, the loadout had the label and pressing "Optimize Armor" had "Automatically add stat mods" turned on.
7. Some idle time after that.

I suspect that DIM uses cached data for 10 mins, but then invalidates it and uses data from the cloud where boolean flag for "Automatically add stat mods" is always set to true for whatever reason.

**Comment by bhollis** [comment]
Should be fixed in ~15 minutes.
