### ISSUE TITLE
[manifest] Error saving manifest file / serialized value is too large

### ISSUE THREAD

**Issue by qwartzi** [DestinyItemManager/DIM#10764]
### DIM Version

Version 8.43.0

### Browser Details

Firefox 131.0

### OS Details

Windows 11

### Describe the bug

Get Error Message on Firefox (but DIM works)
Console Error:
[manifest] Error saving manifest file DOMException: IDBObjectStore.put: The serialized value is too large (size=269822244 bytes, max=267386880 bytes).
    i idb-keyval.ts:95
    _withIDBStore idb-keyval.ts:52
    _withIDBStore idb-keyval.ts:45
console.ts:40:19
    mt console.ts:40
    a log.ts:47
    s manifest-service-json.ts:265
![Screenshot](https://github.com/user-attachments/assets/5d99a4ab-a250-48be-8a30-7fc4b4a65e34)

**Comment by bhollis** [comment]
How much space do you have available on your machine?

**Comment by qwartzi** [comment]
Which Space you mean?
SSD, about 720GB (free)
RAM, about 15GB (free)

**Comment by bhollis** [comment]
Can you visit the debug page? (Go to About DIM, click "Debug") I'm not sure what causes Firefox to limit what you can store locally, but the Destiny database has gotten very large with recent content drops. 

https://developer.mozilla.org/en-US/docs/Web/API/Storage_API/Storage_quotas_and_eviction_criteria#how_much_data_can_be_stored has some guidelines, which suggests you shouldn't be limited, but I also don't know what settings or extensions you have set in Firefox.

Of course, using a different browser that doesn't limit your storage in this way is always an option.

**Comment by qwartzi** [comment]
Seems ok,
Debug: "DIM benutzt insgesamt 15.71 MB von 10.00 GB, auf diesem Gerät."
No Extensions active.
I will take a look... an write here.

**Comment by jimbot70** [comment]
Having the same issue in firefox 132.0.  Debug menu is showing "DIM is using 15.97 MB out of 10.00 GB available to it on this device."

Using DIM in another browser(Chrome) shows "DIM is using 1.24 GB out of 1.09 TB available to it on this device."

**Comment by robojumper** [comment]
With the latest manifest update this seems to be happening to many Firefox users. If I'm understanding the problem right, it's specifically the definitions object that got too large, so Firefox simply won't save it in IDB anymore. Everything else still gets stored fine. So if this is not about the total size of the database, we could split up the definitions into multiple DB objects, e.g. separate the InventoryItem table.

**Comment by bhollis** [comment]
Right. Though it's weird that Firefox has this arbitrary undocumented value limit. We should probably separate out the definition tables into separate objects, but I also want to try again to switch to Origin Private File System and see if it has a higher limit.

**Comment by gavinanderegg** [comment]
Wanted to note that I also have this issue with Firefox 132. I didn't see the warning when using Firefox 131, but then saw it immediately after updating. I'm also seeing a max size of "267386880 bytes" in the console.

![Screenshot 2024-10-31 at 13 42 57](https://github.com/user-attachments/assets/5a4ec71a-59b6-4d77-a369-3fd9be562b0c)

**Comment by bhollis** [comment]
Yep they definitely changed something

**Comment by bhollis** [comment]
Links for future reference:

* [Bug where Firefox over-counts the size of objects](https://bugzilla.mozilla.org/show_bug.cgi?id=1857439)
* 267386880 appears to be Firefox's IPC limit.
