### ISSUE TITLE
Optimizing Armor while editing a copy of a loadout overwrites that loadout on save

### ISSUE THREAD

**Issue by Prometheus3375** [DestinyItemManager/DIM#10767]
### DIM Version

Version 8.43.0 (release), built on 21.10.2024, 05:22:15

### Browser Details

Chrome 129.0.0.0

### OS Details

Windows 10

### Describe the bug

1. Press "Edit Copy" on loadout. 
2. Set its name to "My new loadout".
3. Press "Optimize Armor" in the popup.
4. Do optimization, press "Update Loadout" on the desired armor selection.
5. In the popup notice that the name for loadout is "My new loadout".
6. Press "Save Changes".

### Expected result
I have two loadouts: old one and new one with name "My new loadout".

### Actual result
I have one loadout: the old one is replaced with loadout "My new loadout".

https://github.com/user-attachments/assets/91dcb1cb-766a-4c42-8819-0c09dafafbcd

The fact that after pressing "Update Loadout" DIM shows the name for loadout-copy, deceives a user into thinking they are updating a copy, but they actually updating the original.

Logs: [app.destinyitemmanager.com-1729890647481.txt](https://github.com/user-attachments/files/17527599/app.destinyitemmanager.com-1729890647481.txt)

**Comment by bhollis** [comment]
Should be fixed in beta now.
