### ISSUE TITLE
Maximize light calculation incorrect

### ISSUE THREAD

**Issue by Humper** [DestinyItemManager/DIM#1077]
DIM is showing "maximize light 398.0" for my titan.  Clicking on it results in this loadout (which is my max light):

400 primary
400 special
399 heavy
395 ghost
399 helmet
398 gauntlets
397 chest
394 boots
396 mark
400 artifact

DIM thinks this is a 398 weighted average, but in-game it's 397 (a sliver away from 398).

**Comment by kyleshay** [comment]
Thanks for the report! :) Fixed in the next version! https://github.com/DestinyItemManager/DIM/blob/dev/CHANGELOG.md#next

**Comment by Humper** [comment]
Oh, awesome.  I figured it was probably a rounding issue.  I was actually about to start digging into the code to find it.  Keep up the good work; this game would be unplayable without you.
