### ISSUE TITLE
Search Autocompletion got worse

### ISSUE THREAD

**Issue by chainrez** [DestinyItemManager/DIM#10787]
![image](https://github.com/user-attachments/assets/4e7be16e-1771-4d15-ada4-7105e290beae)
![image](https://github.com/user-attachments/assets/f11d92d1-859c-4190-a227-8ea21eb8f761)

It is no longer suggesting after a colon is typed.

**Comment by bhollis** [comment]
Weird. I'm not aware of any changes here.
