### ISSUE TITLE
All weapons reporting as 'Void Damage' in the perk tree

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#1078]
Even thought it is reporting correctly in the header every special and heavy weapon perk tree shows as void.
![screenshot 2016-10-24 16 02 30](https://cloud.githubusercontent.com/assets/4798491/19665679/646c135a-9a03-11e6-9a60-50aad051e854.png)

**Comment by kyleshay** [comment]
is bungie's bug.

https://www.bungie.net/en/Clan/Post/39966/213743863/0/0
