### ISSUE TITLE
Incorrect ammo counts for certain weapons

### ISSUE THREAD

**Issue by brian6932** [DestinyItemManager/DIM#10798]
### DIM Version

Version 8.46.0.3658 (beta), built on 11/17/2024, 6:13:46 PM

### Browser Details

Firefox 132.0

### OS Details

Windows 10

### Describe the bug

![](https://github.com/user-attachments/assets/249276a1-9058-441d-a317-c4cf8f513fff)
![](https://github.com/user-attachments/assets/377f7676-552f-4333-a074-1e5a091ea8c8)
Both d2foundry and the game calculate the mag size as `5` https://d2foundry.gg/w/4166221755?p=839105230,1087426260,3400784728,1546637391&m=3336648220&mw=758092021. In fact, when `Extended Mag` is in the slot, instead of `Appended Mag`, then it shows the correct `5`. If there's some fractional rounding issue going on here, DIM should be ceiling instead of flooring or rounding, as that's how the game handles it.

**Comment by bhollis** [comment]
https://github.com/DestinyItemManager/DIM/wiki/FAQ#why-is-the-magazine-stat-in-dim-different-from-in-game

**Comment by brian6932** [comment]
This doesn't really tell me how d2foundry has it accurate.

**Comment by bhollis** [comment]
If you round "incorrectly", you'll sometimes get it "right" according to the game, and sometimes get it wrong. If you round the way the Bungie developers tell you to round (using banker's rounding) you'll sometimes get it "right" according to the game, and sometimes get it wrong. You can't look at a single item and say "d2foundry gets it right", you have to look at *all* items and say "d2foundry *always* gets it right".
