### ISSUE TITLE
engrama gigante

### ISSUE THREAD

**Issue by Variedz97** [DestinyItemManager/DIM#10802]
### DIM Version

18/11/2024

### Browser Details

Versión 131.0.6778.69 (Build oficial) (64 bits)

### OS Details

Windows 10

### Describe the bug

Tengo un engrama gigante en mi lista de inventario
![image](https://github.com/user-attachments/assets/79847839-4257-4823-8ea3-888b4e47f633)

**Comment by bhollis** [comment]
Please update to the latest version of DIM.
