### ISSUE TITLE
Roll Notification

### ISSUE THREAD

**Issue by LegoZ3** [DestinyItemManager/DIM#10806]
### Proposed change

I would love it if you guys implemented a way for DIM to notify you when a wishlist (or maybe custom) roll is collected

### How does this fit into your workflow?

I would appreciate this so that while I'm farming or doing runs of activities, I won't have to check DIM for each and every weopon before deleting it. It's not bad the way it is now, but having this feature will make things faster and easier.

**Comment by bhollis** [comment]
We're not likely to do this - sending a notification out of band requires server infrastructure we're not willing to pay for (and web notification support is spotty). Instead, we have the Item Feed feature, which lets you watch drops as they appear, and you'll see a thumbs up if they are on your wishlist.
