### ISSUE TITLE
Limit Farming Mode to weapons and armor slots

### ISSUE THREAD

**Issue by JustTooKrul** [DestinyItemManager/DIM#10805]
### Proposed change

Currently, when you turn on Farming Mode, DIM tries to create empty space in every slot--including the "equipment" slots (Ghosts, Sparrows / Skimmers, and Ships). It would be great if there was an option to either (a) limit item movement to only include Armor and Weapons or (b) exclude moving Ghosts, Sparrows / Skimmers, and Ships (I offer both to account for ease of implementation and edge cases I'm not thinking about... But, (a) is probably better since all the other slots aren't really "farmed.")  

### How does this fit into your workflow?

In general, whenever I use farming mode and one of my characters has a full Ghost / Ship / Etc. inventory, DIM moves things into the vault and those eat up valuable storage slots for the things I am actually farming. Also, items other than armor and weapons don't really drop regularly while playing / farming, so it creates extra work and (as stated) sometimes eats up vault space unnecessarily. In fact, sometimes these items fill the vault and prevent other items from moving.

**Comment by bhollis** [comment]
Checking the code, the only one of those that actually gets farmed is Ghosts - Ships, Sparrows, etc are not moved. We can remove Ghosts from the list, though I find they frequently drop from Eververse engrams. Not so much in regular gameplay though.
