### ISSUE TITLE
Hide Archived Items

### ISSUE THREAD

**Issue by doctordjphd** [DestinyItemManager/DIM#10810]
### Proposed change

Similar to how class specific weapons are completely invisible in 1 pane. Add a filter or setting to remove weapons with the archive tag completely from view.

### How does this fit into your workflow?

The meta relies on around 10 weapons from each class. It would be a big boon to meta players if they could filter for specific weapons, more than just dimming out the weapons that aren't in vogue.

**Comment by bhollis** [comment]
Thanks, but we won't be hiding items like that. I'd suggest just making "meta" loadouts.
