### ISSUE TITLE
Add a way of identifying item perks when selecting items for loadouts

### ISSUE THREAD

**Issue by radwadas** [DestinyItemManager/DIM#10827]
### Proposed change

Currently I didn't see a way to tell a difference between items when trying to select them for a loadout. This is now quite a ball ache to find the right class item, or even a weapon if I have more than one (with different perks). Items are impossible to tell apart unless they have a unique combination of power, upgrade, tag,  lock or notes (all notes having the same icon).

I hoped that by adding a note to an item, it'd show when hovering over it, but it didn't. 

Adding perk names or item notes to the hover over text would be nice clean way that would work for me in the browser, not sure if there's a better way that would work on other platforms.

### How does this fit into your workflow?

Being able to tell which of my craftable weapons is for PvE or PvP, or which of the class items has what I need would help me build loadouts in free time, without being in the game,

**Comment by bhollis** [comment]
Linking https://github.com/DestinyItemManager/DIM/pull/7673
