### ISSUE TITLE
is:enhanceableperks search

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#10836]
It would be nice to have a search for items that have perks that could be enhanced, and which are high enough level to enhance them, but the perks haven't yet been enhanced.

**Comment by FlaminSarge** [comment]
For crafted weapons, this would be by perk level requirements, but for enhanced weapons (which simply require levels 11 and 17 for each column), would it make sense to use this keyword?
One of the cases I thought of was that a weapon would be >=11 but the user kept it on Enhancement Tier 1.
`is:enhanceable` currently does not look at weapon level, as if it did, Enhancement Tier 1 weapons would only show up once they reached level 11, despite Tier 2 being reachable (eventually) for the weapon; using `enhanceableperks` to handle that case would be more convenient than adding e.g. `is:readytoenhance`
