### ISSUE TITLE
Character order wrong (fixed by character age)

### ISSUE THREAD

**Issue by Genesis-Legion** [DestinyItemManager/DIM#1084]
For some reason after deleting and remaking one of my characters DIM is showing the order of them wrong.
I have 3 characters listed as 392, 348, and 345 ingame (top to bottom) and DIM shows them 392, 345, 348.
I know this isn't a huge issue or anything and it only started happening after I deleted one of my characters. If this could be looked at or able to add in a custom order for your characters would be awesome.
Appreciate all your work on this.

**Comment by kyleshay** [comment]
Unfortunately, we have a way to get that information. 

We do have an issue open that lets people define custom orders:

https://github.com/DestinyItemManager/DIM/issues/208
