### ISSUE TITLE
[Suggestion]Vendors Page

### ISSUE THREAD

**Issue by JakeWhitaker** [DestinyItemManager/DIM#1093]
1. The page was really long. I think grouping similar vendors together would be a good way to shorten it(e.g. the three Vanguard Vendors who sell armor, the Vanguard and Crucible Gun vendors, etc.)
   ![0015 vendor mock3wide](https://cloud.githubusercontent.com/assets/21060251/19793736/2eaf871a-9c9c-11e6-88fe-52bff4d40344.gif)
2. IMO the tabs at the top don't break up the groups effectively. It seems to be
   `Useful items || Vanity || Useful items pt2 || Bounties || Vanity || Vanity`
   I think its slightly redundant to have to look at two separate place to find Eris' Class Items and Consumables. I also think Kiosk items should be under one category, with a sub category for ships, shaders, etc. along with vendors like Eva Levante and Amanda Holiday who only sell those items.
   ![0015 vendor mock3catagories](https://cloud.githubusercontent.com/assets/21060251/19794041/7e5953ee-9c9d-11e6-973c-f3deb5f175fc.gif)
   or `Weapons || Armor || "other" || Bounty || Kiosk` where the entirety of Variks, Eris, Petra, etc go under other, despite them selling weapons or armor. This way You only have to look in one spot
3. I think that compressed view is definitely the way to go, it makes it feel very much like the base function of DIM

**Comment by bhollis** [comment]
I'm definitely onboard for talking about how to reorganize the categories better. As for other stuff... I'd only like to do grouping or other smart stuff if we can do it programmatically based on the data, without hardcoding stuff. I did do some experiments with multi-column layout to make better use of the space, and IMO they looked bad - it made it way harder to scan for the vendor I was looking for.

**Comment by geck0s** [comment]
Can we have the vendor's page display stat rolls and responding to filtering for quality?  

One of the things I'd like to use it for is checking for when Variks, Shiro, or the Speaker are offering good stats on their class items.

**Comment by delphiactual** [comment]
@geck0s As soon as bungie fixes the API this will return.

**Comment by geck0s** [comment]
It's working in Destiny Loot History again, so I assumed they had already fixed whatever was holding this back.

**Comment by delphiactual** [comment]
He forced it in there with this code 
https://github.com/ArkahnX/DestinyLootHistory/blob/50c91e93bc31579a4b08dad376a3433028eedc89/app/scripts/pages/vendor.js#L187

**Comment by JakeWhitaker** [comment]
@bhollis I dunno anything about the coding. If it can be done or not I mean. I don't think multi columns is the way to go either, or rather, not two or three dedicated columns. What I mean by that is I think there are places where putting vendors side by side(crucible and vanguard sparrows, vanguard armor, queens wrath and house judgment bounties, to name a few) would eliminate a line or more of items and condense the vendor pages. 

Similar to how factions are displayed with  hunter, warlock, titan gear all in a row, although i think there should be space between the classes sections, especially in the exotic blueprints section.

**Comment by delphiactual** [comment]
Also duplicate ghosts are shown which are not actually available.
If I goto the warlock vanguard as a hunter, I cannot buy the ghost from them.
All the ghosts have the same stats so the extras should just be hidden.

**Comment by bhollis** [comment]
@delphiactual please file separate issues in GitHub for individual problems.

**Comment by bhollis** [comment]
> I think there are places where putting vendors side by side(crucible and vanguard sparrows, vanguard armor, queens wrath and house judgment bounties, to name a few) would eliminate a line or more of items and condense the vendor pages.

I tried this, and there are two problems as I see it:

1. I find it more difficult to read the page with some of them side by side. It makes it harder to scan for the one I want by just scrolling.
2. We'd have to have some rule for when to combine them that doesn't rely on a lot of hardcoding.

**Comment by JakeWhitaker** [comment]
> I find it more difficult to read the page with some of them side by side. It makes it harder to scan for the one I want by just scrolling.

What about icons to the left with the groupings. So FWC, DO, NM are readily apparent? Oor which specifically are you having trouble locating/ would the reorganization conversation help with this?

> We'd have to have some rule for when to combine them that doesn't rely on a lot of hardcoding.

Could it be done based on the items they're selling? I.E. DO FWC and NM each sell 6(7?) weapons and a full set of armor per class so they're grouped together?

**Comment by bhollis** [comment]
Resolving as I think the Vendors page is pretty much in the state we want it to be in.
