### ISSUE TITLE
Vendors Enhancement: Highlight items for sale that the user doesn't own

### ISSUE THREAD

**Issue by chrisfried** [DestinyItemManager/DIM#1094]
i.e. If Eva's selling an emblem that isn't available in my kiosk, this should be pointed out to me on the Vendor page.

**Comment by bhollis** [comment]
It'll be a bit of a puzzle to do this efficiently, but it's a great idea. Anyone got an idea for a visual treatment for the highlighting?

**Comment by delphiactual** [comment]
Yellow Borders!

**Comment by bhollis** [comment]
That seems weird, though?

**Comment by chrisfried** [comment]
Agreed. I was thinking more like a tag on a corner of the item.

**Comment by kyleshay** [comment]
Maybe a filter at the top (similar to the "all" filter/tab) that shows items that are currently for sale, and not owned? Quick way to scan of what would be worth collecting?

**Comment by chrisfried** [comment]
Yeah, I was thinking a filter would be good, too.

I'm sure other Vendor filters could be dreamt up, while we're at it. Like, things I already have, but are available with a better roll.

**Comment by Mulchman** [comment]
> i.e. If Eva's selling an emblem that isn't available in my kiosk, this should be pointed out to me on the Vendor page.

The Android Tower+ app can do this. Dunno if anyone wants to ping its author re: calculations @bhollis mentioned in the second post. Just throwing it out there.

Tower+ on the Play Store: https://play.google.com/store/apps/details?id=scave.dvend&hl=en

**Comment by chrisfried** [comment]
I pinged him in the Slack.

**Comment by dustinrue** [comment]
![new-tag](https://cloud.githubusercontent.com/assets/573953/19950029/20ce3a70-a123-11e6-9911-9988c64f25e1.png)

put that in the corner

**Comment by kyleshay** [comment]
In addition to emblems--

* Shaders
* Ships
* Sparrows

**Comment by kyleshay** [comment]
https://www.guardianoutfitter.com

**Comment by wein3967** [comment]
I just saw this on Reddit. Pretty nice.

**Comment by kyleshay** [comment]
When we implement this we should also add a search filter (unless it's just a new tab)

#1526

**Comment by bhollis** [comment]
Closing out D1-specific stuff that isn't going to make it.
