### ISSUE TITLE
is:new broken in current beta

### ISSUE THREAD

**Issue by tcurtin** [DestinyItemManager/DIM#1095]
Just noticing that the current beta (3.11.1.510) seems to have lost the is:new functionality - nothing is highlighted when setting that filter

**Comment by tcurtin** [comment]
(whups - ignore spurious close - was a mis-click)

**Comment by kyleshay** [comment]
Is this fixed? @bhollis noticed you added `Fix a bug in the new filters for source.` to the changelog for last release.

**Comment by bhollis** [comment]
Sorry, that was "the new filters" like `is:ttk` and stuff. Not the `is:new` filter. I'll check this when I get some new items.

**Comment by tcurtin** [comment]
I did a few runs last night and can confirm that is:new is still not
working as of last night's beta.


*Tim Curtin*
Custom Logic Test Data Analysis
*T *+1 802.769.2791 <1.802.769.2791> | Tim.Curtin@GlobalFoundries.com
*GLOBALFOUNDRIES* 1000 River Road, Essex Junction, VT 05452

IBM/GF Contact tool: https://unity.btv.ibm.com/Applications/GFContacts/
Useful info for ex-IBMers: https://unity.btv.ibm.com/Documents/GF/
