### ISSUE TITLE
General section, if full - does not correctly manage items.

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#1096]
For example if the general section is full and I try to move something to it:
![rec](https://cloud.githubusercontent.com/assets/424158/19821872/ae153dc8-9d2e-11e6-8682-057777527dcc.gif)

This action would work as expected if it was Weapons or Armor.

I wonder, is it because I have an item that won't even show as classified, and thus my General section is showing as 71/72 items, so DIM thinks there is space so it's not moving something?

**Comment by delphiactual** [comment]
Can confirm it is due to having a classified item in your `General` section of `Vault`. As I do not and transfers management working as expected with a full vault.

**Comment by delphiactual** [comment]
Need to add `Unknown` Buckets to: `Weapons`, `Armor`, and `General` to be able to show the classified item instead of just only adding to the section count.

**Comment by delphiactual** [comment]
https://github.com/DestinyItemManager/DIM/pull/1097
