### ISSUE TITLE
Perks View Option (Idea)

### ISSUE THREAD

**Issue by davewhiffen** [DestinyItemManager/DIM#1108]
http://imgur.com/e6PvOnu

Toggle perks view.   Playing with a few different styles.  The ticks on the right are INT/DIS/STR and you could label colours to different ones.

http://imgur.com/GdwoDXk (Earlier, more cluttered build)

This was a continuation of the idea: http://imgur.com/YWXVr0x (Still rough)

**Comment by bhollis** [comment]
Hmm, we're getting kinda crowded for on-item indicators...

**Comment by kyleshay** [comment]
can also be solved by doing `intellect strength` and you'll see all matching perk types.

maybe the compare feature (#494) will solve the need for this anyway?
