### ISSUE TITLE
is:trials also returns exotics

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#1111]
filter `is:trials`, exotics also come back...

![screen shot 2016-10-31 at 2 27 27 pm](https://cloud.githubusercontent.com/assets/424158/19866352/34f497a0-9f76-11e6-936c-5de53e5f1881.png)

**Comment by delphiactual** [comment]
because trials can reward exotics, (e.g. `is:nightfall` would return these as well as `is:wotm`)

**Comment by kyleshay** [comment]
hmm. good point, suppose i can solve this myself by doing `is:trials not:exotic`

**Comment by cotto** [comment]
Unless that's how the API responds and it's hard to change, this seems weird.  What's the use case for also returning exotics?  Is it likely that any user will search for is:trials and will expect both exotics and trials gear to be matched?

**Comment by delphiactual** [comment]
This is how the API identifies them with sourceHashes... We can prolly do some post-processing on the filter tho...
