### ISSUE TITLE
Materials Exchange doesn't include old materials or glimmer consumables (in beta build)

### ISSUE THREAD

**Issue by SableCentaur** [DestinyItemManager/DIM#1114]
I have a hoard of old radiant and ascendant materials that can be turned in for motes and/or glimmer which I have mainly held onto for faction ranking. It would be nice to see the amount they would give me as well as the current options. I also hold onto the glimmer consumables instead of turning them in (house banners, silken codex, royal amethysts, etc) which is a huge chunk of my "bank" of glimmer that's not being included.

**Comment by bhollis** [comment]
/cc @TheHandsomeCoder 

We should try to drive this dialog off the vendors data.

**Comment by TheHandsomeCoder** [comment]
@bhollis could there be performance concerns behind using the vender data to populate the mats exchange?

@SableCentaur would you expect it to poule all the glimmer consumables and then show how many weapon parts you can get?

**Comment by TheHandsomeCoder** [comment]
The problem I have is how best to convey when one needs to trade something several times, the prime example is raid shards and energy. What is then best way to indicate that you need to convert energy + glimmer -> Shards -> Motes of light -> Rep

**Comment by SableCentaur** [comment]
I'd like to see (if possible) two versions, one with just the glimmer on hand converted to weapon parts converted to rep, and one with all glimmer consumables converted to weapon parts to rep.

For materials with multiple conversions, maybe if I clicked on the material icon and it popped up with a "Energy+glimmer (probably show total required) to shards to motes at the speaker" thing? Or bypass the extra box altogether and just show Energy + Glimmer -> Shards -> Motes -> Rep? On my screen there's enough room for 4 material icons, so that particular example wouldn't be an issue for me.

**Comment by TheHandsomeCoder** [comment]
@SableCentaur If we bundle all the glimmer together, if for instance you also include your trades to Variks, should the glimmer poule decrease to the same amount you trade to variks?

**Comment by SableCentaur** [comment]
If I toggle that on, yes.

**Comment by bhollis** [comment]
@TheHandsomeCoder I don't see why there would be perf problems. We should be able to calculate everything quickly.

**Comment by JakeWhitaker** [comment]
Possibly list only Ascendant energy and the amount of rep you can get from it, and then if they click on it, show the process?

**Comment by bhollis** [comment]
Resolving for now as Material Exchange has been backburnered.
