### ISSUE TITLE
Materials From Trade sometimes shows rank, sometimes XP

### ISSUE THREAD

**Issue by philipmat** [DestinyItemManager/DIM#1115]
![screen shot 2016-10-31 at 3 05 39 pm](https://cloud.githubusercontent.com/assets/709928/19869758/a8a425b2-9f7b-11e6-81f0-0c35e25c104f.png)

I'm assuming the first row is 250 XP but the rest are rank increases.

Version 3.13.0.527

**Comment by JakeWhitaker** [comment]
I think overall it would be more simple and appealing with the current design to show rep gains rather than the percentage of a rank up(1250xp is better than .5 rank up imo)

**Comment by bhollis** [comment]
Resolving for now as Material Exchange has been backburnered.
