### ISSUE TITLE
[Vendors] Duplicated Items

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#1119]
Duplicate ghosts are shown which are not actually available.
If I goto the warlock vanguard as a hunter, I cannot buy the ghost from them.
All the ghosts have the same stats so the extras should just be hidden.

**Comment by bhollis** [comment]
Could you explain in some more detail what the problem is? I don't understand.

**Comment by delphiactual** [comment]
The titan vanguard does not offer 3 ghosts, if I go to the titan vanguard as a non-titan he does not offer a ghost.
![screenshot 2016-11-01 22 16 35](https://cloud.githubusercontent.com/assets/4798491/19916581/dfc402be-a080-11e6-9d90-1cf84a34edc7.png)

**Comment by bhollis** [comment]
Turns out Bungie is returning three ghosts for each vanguard vendor. They're not distinguishable from each other. I can unique-ify them...
