### ISSUE TITLE
Materials exchange design

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#1127]
Let's chat about how to improve the design of the material exchange dialog. IMO it's pretty confusing right now:

<img width="1422" alt="screen shot 2016-11-01 at 11 26 03 pm" src="https://cloud.githubusercontent.com/assets/313208/19918691/aa7984c6-a08a-11e6-8b17-b9d04904dc79.png">

**Comment by bhollis** [comment]
Some random observations:

1. I can click on the faction icons, my characters, and the "Materials On Hand", but I'm not sure what any of those selections affects.
2. I don't know what any of the fractional numbers mean.
3. The icon in the header doesn't suggest "material exchange" to me. I'm not sure we should be adding more icons and hoping people guess what they are.

The design from https://github.com/DestinyItemManager/DIM/pull/1046#issuecomment-253256759 made more sense to me, though I'm still not sure what the numbers meant.

**Comment by bhollis** [comment]
/cc @TheHandsomeCoder 

Linking #1115.

**Comment by JakeWhitaker** [comment]
> I can click on the faction icons, my characters, and the "Materials On Hand", but I'm not sure what any of those selections affects.

Perhaps if you put faction rank under each of the factions, and showed all three at once, it would be a better indication that you're selecting and affecting one faction.

>I don't know what any of the fractional numbers mean.

I think xp values would be more appropriate and appealing(1250 rep vs .5 rank ups)

>The icon in the header doesn't suggest "material exchange" to me. I'm not sure we should be adding more icons and hoping people guess what they are.

Could go with something like a recycling symbol, or maybe a blank reputation diamond

![0013 mats3](https://cloud.githubusercontent.com/assets/21060251/19943330/5317f158-a10d-11e6-9a2a-620261699f96.gif)

**Comment by Mulchman** [comment]
There's also no "Back to DIM" type button/link (like on the Loadout Builder page).

**Comment by kyleshay** [comment]
could we reuse the character selection dropdown that we have in the loadout builder?

**Comment by bhollis** [comment]
Maybe we should move the rep section in here, too, if it's going to be full
screen.

**Comment by bhollis** [comment]
Resolving for now as Material Exchange has been backburnered.
