### ISSUE TITLE
Expanded details menu requires scrolling

### ISSUE THREAD

**Issue by aidojc** [DestinyItemManager/DIM#1129]
Would be great if the expanded details popup displayed all content on screen without scrolling. Attached screen shot is from my laptop running at 1366 X 768 res.

![dim - expanded info requires scrolling](https://cloud.githubusercontent.com/assets/23152051/19933687/adf316b6-a0ea-11e6-8075-3295a43ef719.PNG)

**Comment by bhollis** [comment]
We use a strategy to try and prevent the pop-up from going off the screen
so you can always see it. Given the height of the pop-up, often it will
choose to put the pop-up below the item because there's more space below
than above. We have design ideas around putting this in a sidebar or
something other than a pop-up which could help with this. We could also put
the pop-up beside the item, bit when I've tried that it's been unclear
which item the pop-up is attached to.

**Comment by kshep** [comment]
I usually notice this when I'm trying to move things around and have to keep scrolling to get to the Equip/Store row. This is probably an independent suggestion, but it might be handy if the little "v" "^" button in the upper right hand corner of the box was sticky, and changed the "Always show item details" status.

**Comment by aidojc** [comment]
Thanks guys - just an idea, how about always anchoring the unexpanded pop-up to the top-right of the icon inclicked icon? If the icon is closer to the bottom of the displayable area, position the pop-up bottom-up from the top-right of the icon, if it's closest to the top of the displayable area render it top down from the top-right corner of the icon? That might reduce the scrolling and some of the 'jumpiness' of the pop-up.

**Comment by delphiactual** [comment]
What if when it is put it beside it, also highlight the item with a border of some sort.

**Comment by aidojc** [comment]
I think that's a good idea... maybe some sort of callout part to the dialog that anchors to the top-right of the icon? That might allow you place the pop-up anywhere on screen while still obviously referencing the parent item.

**Comment by JakeWhitaker** [comment]
Do you mean something like this? ![0016 infowindow](https://cloud.githubusercontent.com/assets/21060251/19943532/39a1fef2-a10e-11e6-844c-043699467f2e.gif)

**Comment by aidojc** [comment]
Not quiet - so the issue (or my issue :) ) is scrolling when looking at the pop-up. To me it's all about screen position of the pop-up while retaining the context of the icon that was clicked. So maybe a callout style for the pop-up might help, that emanates from the top-right corner of the icon.

That may allow for the dialog to be positioned is a similar position each time (maybe being automatically repositioned left or right for optimal viewing), but never needing to be scrolled. 

A couple of mock-ups:

![dim - anchoring pop-up to top right of icon 1]

(https://cloud.githubusercontent.com/assets/23152051/19944663/2dced30c-a113-11e6-9d54-8cbfa1305c22.png)


and 


![dim - anchoring pop-up to top right of icon 2](https://cloud.githubusercontent.com/assets/23152051/19944681/3a3d488a-a113-11e6-9a4e-8e4029545bc6.png)

**Comment by JakeWhitaker** [comment]
Maybe putting stats and detailed view in a side bar, and leaving transfer buttons where they are?

**Comment by aidojc** [comment]
That would work too... maybe have the "^" slider push the details out horizontally? Horizontal scrolling would need to be avoided though.

**Comment by aidojc** [comment]
And what about making the title banner of the pop-out match the rarity of the item? Yellow with black text for exotics, Purple with white text for Legendary, Blue with white text for Rare, Green with white text for Uncommon, White with black text for common?

**Comment by JakeWhitaker** [comment]
I would do white text with black outline for all of them personally if possible. It's visible on any hue shade or tint

Jake Whitaker

Sent from BlueMail<http://www.bluemail.me/r>

On Nov 3, 2016, at 12:29, aidojc <notifications@github.com<mailto:notifications@github.com>> wrote:

And what about making the title banner of the pop-out match the rarity of the item? Yellow with black text for exotics, Purple with white text for Legendary, Blue with white text for Rare, Green with white text for Uncommon, White with black text for common?

**Comment by aidojc** [comment]
Decided to record a short video highlighting the details dialog bouncing around, and the way scrolling is needed to address.


[DIM - Scrolling issue.zip](https://github.com/DestinyItemManager/DIM/files/609822/DIM.-.Scrolling.issue.zip)

**Comment by bhollis** [comment]
Thanks, we definitely know about it, just haven't had the time to address it yet. Trust me, it's coming!

**Comment by bhollis** [comment]
This should be much better in Beta now. Give it a look and let me know!

**Comment by aidojc** [comment]
nicely done - looks great in the beta!
