### ISSUE TITLE
Prefer Rarer Exotics when Farming Mode is Active

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#1134]
Favoring rarity when sequestering items should help the user when trying to make room.  Curious if there is some automation here to help the users who only want to preserve their purple pickups.

**Comment by kyleshay** [comment]
I believe we do, unless you're talking about something else?

https://github.com/DestinyItemManager/DIM/blob/dev/app/scripts/services/dimFarmingService.factory.js#L137-L150

**Comment by bhollis** [comment]
I'm planning on rewriting our prioritization function soon.

**Comment by bhollis** [comment]
@SunburnedGoose could you elaborate on exactly what behavior you'd like to see here?

**Comment by SunburnedGoose** [comment]
If there are no sources available to move an item (characters/vault) full, move a blue/purple engram away from the vault and put the exotic into the vault.  It's a strategy to ensure that I have the option to delete lesser engrams to ensure I can always pick up an exotic.

It would involve juggling the engrams already saved into the vault back to the current character to safely sequester the exotic.

**Comment by tcurtin** [comment]
and same for legendaries - I'd always prefer to put higher level
gear/engrams in the vault first so I can quickly delete things once no
spaces are left and know I'm getting rid of the worst stuff first.  Maybe
that's a mechanic that triggers only when we're almost out of space, that
way we'd see all the weapon or armor transfers happening and know we're
full?


*Tim Curtin*
Custom Logic Test Data Analysis
*T *+1 802.769.2791 <1.802.769.2791> | Tim.Curtin@GlobalFoundries.com
*GLOBALFOUNDRIES* 1000 River Road, Essex Junction, VT 05452

IBM/GF Contact tool: https://unity.btv.ibm.com/Applications/GFContacts/
Useful info for ex-IBMers: https://unity.btv.ibm.com/Documents/GF/
