### ISSUE TITLE
Compare not always selectable

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#1137]
Cannot select compare on auto-rifle when language is set to german.

![screenshot 2016-11-05 10 50 00](https://cloud.githubusercontent.com/assets/4798491/20031931/9fb03e32-a345-11e6-9bf8-6d93d0af321a.png)

**Comment by bhollis** [comment]
Because there's an error or because the text is too long?

**Comment by delphiactual** [comment]
test is too long, should probably relocate the compare button

**Comment by JoshuaJones** [comment]
What about keeping the text to one line and having css ellipsis the text like in the screenie?

![screen shot 2016-11-10 at 11 36 58 am](https://cloud.githubusercontent.com/assets/142342/20191418/39c48404-a73a-11e6-953f-b9cf743343b0.png)

**Comment by delphiactual** [comment]
![screenshot 2016-12-14 20 12 45](https://cloud.githubusercontent.com/assets/4798491/21210635/e0087766-c239-11e6-9a38-0af669cfa04d.png)

@JoshuaJones Unfortunately that would not work, because the tag drop-down also get larger for other languages.

Either need to add a 3rd line to the header or rearrange the layout for tags and compare

**Comment by JoshuaJones** [comment]
@delphiactual True. What about swapping out the "tag" text for a icon. Could keep the `select` with a little bit of css hacking. Unless you guys are trying to avoid overuse of iconography.

**Comment by kyleshay** [comment]
We need someone to create a proper mockup (not an implementation) of what the move popup should look like.

Keeping mobile in mind.

**Comment by delphiactual** [comment]
![screenshot 2016-12-19 14 44 01](https://cloud.githubusercontent.com/assets/4798491/21330426/9c95c7a8-c5fa-11e6-92e2-7bae4f161228.png)
