### ISSUE TITLE
The tooltip for int/dis/str bars under the character card does not correctly substitute the translation

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#1138]
https://github.com/DestinyItemManager/DIM/pull/1029/commits/4beafc75adf581e45576002f7ba3312a94de86d7

Breaks stat hover on the character cards... Reverting breaks stat hover in Loadout Builder...

**Comment by bhollis** [comment]
Could you expand on what you mean by "break"? It's super helpful to get information like "I was expecting to see X, but instead I saw Y".

**Comment by delphiactual** [comment]
![screenshot 2016-11-05 14 10 40](https://cloud.githubusercontent.com/assets/4798491/20033228/b4ff444c-a361-11e6-8d39-abe0538c76dd.png)

**Comment by bhollis** [comment]
So the bug is "The tooltip for int/dis/str bars under the character card does not correctly substitute the translation"?

**Comment by delphiactual** [comment]
sure but is is translating it fine in loadout builder. and reverting translates it in the character card but not loadout builder.

**Comment by bhollis** [comment]
The bug does not include places where things are working correctly :-)

**Comment by bhollis** [comment]
The issue was that the stat name is already translated, and it was getting double-translated.
