### ISSUE TITLE
Max Light button should prefer legendary over blue

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#1139]
I have both a rare and legendary artifact at level 397. When I hit max light, it should prefer the Legendary.

**Comment by marsman12019** [comment]
What would the benefits be to that?

**Comment by kyleshay** [comment]
I use the max light button to get my best gear to my characters. Suppose I could use a loadout specifically for that, but for a while I kept running into the issue where I'd be playing PvP and notice that I had a blue instead of my legendary Jolder artifact equipped. 

We typically prefer higher light or lower light gear depending on the action, so it would be good to do similar there.

**Comment by Ninjamau5** [comment]
i agree with this, rare and legendary items of the same light, should have legendary items chosen first
