### ISSUE TITLE
Farming move-aside subtly broken

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#1141]
#1057 subtly broke how farming mode works - now, with a full vault but space on other characters, farming mode will refuse to transfer items off my primary character in order to make space. Before, it would move items out of the vault to make room. I'll fix it, but filing this issue to track it.

**Comment by kyleshay** [comment]
should make sure it is on by default also

**Comment by bhollis** [comment]
Yeah it wasn't for me when I upgraded, though I looked at the settings and saw that it defaults to on. Any ideas what's going on there?

**Comment by kyleshay** [comment]
Guessing this is now in the stable branch... I haven't had time to login and test. Can someone please confirm this is fixed or still an issue?

**Comment by bhollis** [comment]
It's fixed in #1156.
