### ISSUE TITLE
Record books crashing DIM

### ISSUE THREAD

**Issue by shockthealien** [DestinyItemManager/DIM#1142]
Hey, not sure if this is new but never happened to me before. 

When I click on any of the uncompleted record books (RoI book and SRL, My MoT y3 is complete and works fine), it makes DIM unresponsive and even crash. Any other item i tested works and brings up the detail modal but the record books are the only ones i can find doing this.

Is there any log or something i can dig out for you guy to see whats what?

**Comment by bhollis** [comment]
Confirmed. I'll look at it.

**Comment by bhollis** [comment]
Fixed in #1145.
