### ISSUE TITLE
Item tags not saving

### ISSUE THREAD

**Issue by tigerkzr** [DestinyItemManager/DIM#1150]
Been using beta for a while now. currently on 3.13.0.558.  Having an issue where any tag I add or change disappears.

**Comment by wein3967** [comment]
May just want to see how many things you have tagged have notes. There is currently a limit (data) on how much tagging you can do.

**Comment by tigerkzr** [comment]
0 notes, just tags

**Comment by delphiactual** [comment]
they use the same storage.

**Comment by wein3967** [comment]
The, in your case it depends on how many tags you've used. I think the last time someone did a count, it was 119 (max).

**Comment by tigerkzr** [comment]
Will have to check. Thanks

**Comment by kyleshay** [comment]
Thanks for the heads up, tags + notes still need some work/aren't officially supported (which is why they are only in the beta branch and not the main release.)

**Comment by tigerkzr** [comment]
Figured that. Just wanted to make sure you guys were aware. I saw the limit
post but was t using notes so thought it a separate issue.

To follow up, I definitely was exceeding the current tag limit.

**Comment by kyleshay** [comment]
Appreciate the report! Useful to get feedback on the beta branch so we have higher confidence pushing to release :)
