### ISSUE TITLE
Filter Entry Box Gone in Beta 3.13.0.558

### ISSUE THREAD

**Issue by rvvisse** [DestinyItemManager/DIM#1151]
I've been using .558 for a week and it's been awesome, but my filter box disappeared today.  I rebooted my browser but it's still gone.  Thanks for the awesome app, big fan!!  LOVE the new features.
![nofilterbox](https://cloud.githubusercontent.com/assets/12124120/20072946/663ac208-a4f8-11e6-9ba0-7cc4fd36326b.JPG)

**Comment by delphiactual** [comment]
fixed by https://github.com/DestinyItemManager/DIM/pull/1149

**Comment by rvvisse** [comment]
Ah thank you!

**Comment by delphiactual** [comment]
it's not merged yet
