### ISSUE TITLE
img artifacts on loadout builder page (no stat bars)

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#1153]
the stat bars are not showing up where they normally do above the loadout

<img width="901" alt="screen shot 2016-11-07 at 8 48 24 pm" src="https://cloud.githubusercontent.com/assets/424158/20083649/9c261600-a52b-11e6-8b02-5aa404d6bb44.png">

~~worth noting that i18n for `LB.IncludeRare` is missing~~ Fixed in #1155 
<img width="245" alt="screen shot 2016-11-07 at 8 53 14 pm" src="https://cloud.githubusercontent.com/assets/424158/20083775/4b1b731c-a52c-11e6-9148-61164a7f3034.png">

**Comment by delphiactual** [comment]
fixed typo in i18n https://github.com/DestinyItemManager/DIM/pull/1155

**Comment by delphiactual** [comment]
linking https://github.com/DestinyItemManager/DIM/issues/1138

**Comment by ericnelson0** [comment]
Any console output on this?

**Comment by bhollis** [comment]
That's a good point. We should see if we can log translation misses

**Comment by delphiactual** [comment]
The hover states `Tundefined Disicipline (2/60 for TNaN)` so it appears that https://github.com/bhollis/DIM/commit/f2dae742c357d780492e0d97a8ed650147f3a53d changed the way dimStats should be called.

**Comment by ericnelson0** [comment]
@bhollis You still got this covered?

**Comment by bhollis** [comment]
Feel free to go after it

-Ben
