### ISSUE TITLE
Change "Equip on Current Character" to "service.store.name"

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#1154]
For clarity it would say something along the lines of "Equip on Awoken Female Titan", and would equip to whichever character is selected in the dropdown.

**Comment by ericnelson0** [comment]
This is a good idea, but it has potential to confuse users when they haven't refreshed in a while. The loadout builder doesn't work well with (new gear/ state changes) within the game.

**Comment by philkernick** [comment]
I'd like to +1 this.  The current button does not "do what you expect it to do".  I change character in the dropdown, build a loadout, but the only way to equip it is to name it, save it, quit the builder, and equip from the main screen.  If I click the equip button it tries to equip it on my Hunter and fails!

While a change to do what the OP suggests might confuse users who haven't used DIM in a while, the current behaviour confuses users who use DIM all the time!
