### ISSUE TITLE
Non-i18n compliant code

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#1158]
Browsing through the codebase I came across this.

https://github.com/DestinyItemManager/DIM/blob/de81070d7f2fd9d43e185f3f7949769dfb0e79f4/app/scripts/shell/dimSearchFilter.directive.js#L369

**Comment by delphiactual** [comment]
"nodeStepHash":617082448

**Comment by bhollis** [comment]
Fortunately nobody cares about this anymore ;-)
