### ISSUE TITLE
No Back to DIM link on Available Faction Ranks screen

### ISSUE THREAD

**Issue by tcurtin** [DestinyItemManager/DIM#1160]
As of version 3.13.0.563 there's no way to return to the main view after entering Available Faction Ranks, other than going to Loadout Builder and using its Back link.

**Comment by bhollis** [comment]
Pro tip until the back link is added - you can click the DIM logo.

**Comment by deurk** [comment]
Noticed that too and forgot to add the issue, but +1!

**Comment by bhollis** [comment]
Resolving for now as Material Exchange has been backburnered.
