### ISSUE TITLE
Iron Banner Vendor Doesn't Show All Items

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#1161]
The Iron Banner Vendor has six items for sale, for each class.  Two of them are weapons.  That should be 4 uniques for each class, and two weapons for a total of 14 items.

When I Iook in DIM's vendors, I only see 10 items.  Looking at the API, all of the items are being returned.

![screen shot 2016-11-08 at 5 25 33 pm](https://cloud.githubusercontent.com/assets/984608/20147738/f20fd1fc-a66e-11e6-995c-098451a847b0.png)

**Comment by SunburnedGoose** [comment]
There should be an extra Boots for the Titan and Warlock, and an extra Chest for the Titan and Warlock.

**Comment by SunburnedGoose** [comment]
In fact, the first two items, the hunter boots, are the same item repeated.

**Comment by bhollis** [comment]
Interesting! The issue here is that I've never seen a vendor give different rolls of the same item before. This'll take some tweaking.
