### ISSUE TITLE
Glimmer and Legendary marks reminder

### ISSUE THREAD

**Issue by Korben85** [DestinyItemManager/DIM#1162]
Just an idea that came up.
What if we could add an reminder for Glimmer and legendary marks when they reach a limit.
Maybe the user can set a limit for both in the settings and when DIM recognizes that this limit is reached the user gets a popup info.

**Comment by tcurtin** [comment]
Actually, that's a pretty cool idea.  I was also wondering if the API
provides info on duration in current match for crucible?  Because "heavy's
coming" and "pop 3oC" alerts would also be great.  Ditto for glimmer
consumables running out.

**Comment by marsman12019** [comment]
@tcurtin You should make that request its own issue! I think that's a pretty cool idea.

**Comment by deurk** [comment]
@Korben85 Very good idea, being reminded (with a popup like version changes) that you are at or close to glimmer/marks maximum would avoid wasting some regularly!

**Comment by tcurtin** [comment]
Good idea - separate req created

**Comment by bhollis** [comment]
Should we play a sound too? ;-)
