### ISSUE TITLE
Three of Coins (3oC) Reminder?

### ISSUE THREAD

**Issue by marsman12019** [DestinyItemManager/DIM#1166]
A Three of Coins reminder (a la [Destiny Loot History](https://github.com/ArkahnX/DestinyLootHistory)) would be pretty awesome. Has anybody discussed or worked on that?

To summarize, DIM would pop a 3oC from your vault into your inventory (or back and forth from inventories) at the beginning of every crucible match/raid/story mission/etc.

**Comment by kyleshay** [comment]
It would be nice to integrate that into the Farming mode. Open to other ideas for while you're 'active' with a player.

**Comment by bhollis** [comment]
I don't think we're going to do this. That said, if somebody wanted to build it into farming mode and submit a PR, I'd be into it!
