### ISSUE TITLE
Reduction of tooltip time when hovering over item nodes

### ISSUE THREAD

**Issue by marsman12019** [DestinyItemManager/DIM#1167]
When hovering over nodes in a weapon or armor popup, the tooltips take too long to display what the node is. The actual tooltip timing is a function of the browser itself, but we could create a custom popup to display the information immediately, instead of just allowing the tooltip to use the title.

Alternatively, there might be a better way of displaying the information provided by the nodes instead of burying them under another layer of interaction.

**Comment by bhollis** [comment]
Agreed. There's an existing issue for this, and I'm hoping to make progress
on it this weekend.

**Comment by kyleshay** [comment]
https://github.com/DestinyItemManager/DIM/issues/575
