### ISSUE TITLE
[BUG] Materials Exchange

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#1169]
@TheHandsomeCoder 

angular.js:13920 TypeError: Cannot set property 'amount' of undefined
    at mapXurItems (chrome-extension://nihhbdefbdhifgcmmiphafhmhiamifoe/scripts/shell/dimMaterialsExchangeCtrl.controller.js?v=$DIM_VERSION:148:29)

I ran out of Strange Coins...

**Comment by TheHandsomeCoder** [comment]
Looking into it now, it's to do with missing one of the tradable items, I'm
working on #1128 atm which I can use to fix this

**Comment by delphiactual** [comment]
Fixed in #1234
