### ISSUE TITLE
Filters for weapon stats

### ISSUE THREAD

**Issue by bradchoate** [DestinyItemManager/DIM#1173]
Ie: "impact:>89". Range, stability, reload, aim assistance, mag size, etc.

**Comment by brunnopleffken** [comment]
This is a great idea, and I'm working on it!
The image below is my progress so far: I'm selecting all scout rifles with impact >= 61 (the same archetype as Colovance's Duty). It's working great and I'm expanding this code to other stats, like range, reload, aim assist.

This may interest to @delphiactual and @bhollis.

<img width="1280" alt="screen shot 2016-11-17 at 14 32 06" src="https://cloud.githubusercontent.com/assets/3427344/20397985/bf458a72-acd2-11e6-964a-a79b7b32c0cc.png">

**Comment by bradchoate** [comment]
This looks fantastic and I want it immediately.

**Comment by bhollis** [comment]
Closing in favor of #1191.
