### ISSUE TITLE
[i18n] vm.store.className is pluralized in French...

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#1177]
As reported here: https://github.com/DestinyItemManager/DIM/pull/1163#discussion_r87637492

@crulplay, @Korben85, @JaviG1105, @brunnopleffken can you verify class names are correct in your languages?

EDIT: It appears correct on bungie.net in their gear manager
![screenshot 2016-11-12 15 40 54](https://cloud.githubusercontent.com/assets/4798491/20242545/86dbde8a-a8ee-11e6-9bba-7a9d8ec015fe.png)

**Comment by bhollis** [comment]
We're using the "className" for this, but there are also "classNameMale" and "classNameFemale". I wonder if those are better.

**Comment by bhollis** [comment]
Yeah if I switch that I get "Chasseuse/Chasseur".
