### ISSUE TITLE
[i18n] Loadout - Create or Edit

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#1178]
The class-list dropdown is not translated currently. I could not figure it out.

**Comment by ericnelson0** [comment]
@delphiactual I'll have a look.

**Comment by ericnelson0** [comment]
Are you talking about the drop down for the selection of tiers?

![image](https://cloud.githubusercontent.com/assets/4594931/20610859/a9e96408-b265-11e6-8d2c-524f042c0a8e.png)

The class list looks like it is translated, but the "Tier %d" string isn't

**Comment by delphiactual** [comment]
Closing in favor of #1212
