### ISSUE TITLE
Glimmer Rewarding Items being Moved in Farming Mode

### ISSUE THREAD

**Issue by DestinyBolty** [DestinyItemManager/DIM#1181]
When you use Farming mode and Glimmer Rewarding item, Currently in Rise of Iron most popular is House Banners, Will be sent to the vault despite ever telling the User that it is.

Since Farming mode mainly moves engrams users aren't regularly, if at all, watching how many House Banners they have and then in the end never know those rewards are sitting in their vault waiting for them. 

I think this should be a checkable option like how Green items are!

**Comment by bhollis** [comment]
The text of the farming mode dialog explains that this is what happens.

**Comment by SentryTheDefiant** [comment]
Just noticed it did this last night. I don't think it needs a check box, but maybe a counter.
