### ISSUE TITLE
Can we get a visual indication of notes done on items?

### ISSUE THREAD

**Issue by deurk** [DestinyItemManager/DIM#1186]
The ability to leave notes on items is pretty handy since we can write recommended perks on weapons and such for example. However, there is no visual indication on the item icon that there is a note attached to it.

Could you find a way to add a visual indication of a note?

Thanks!

**Comment by delphiactual** [comment]
filter notes:

**Comment by bhollis** [comment]
We're kinda running out of space to decorate items...

**Comment by deurk** [comment]
The filter works for me, as long as I don't have to click on items I'm golden.
Thanks @delphiactual.
