### ISSUE TITLE
Time-based PvP and PvE alerts

### ISSUE THREAD

**Issue by tcurtin** [DestinyItemManager/DIM#1188]
Does the API provide info on duration in current match for crucible?  Because "heavy's coming" and "pop 3oC" alerts would be great to have.
Similar, but in PvE, a glimmer consumables running out alert.

Self-clearing modal window with a sound toggle maybe?

If the API doesn't provide time in match, maybe this is a "click this button when match starts" button could work... but at that point it starts to feel like a separate utility or app...

**Comment by bhollis** [comment]
I'd be concerned about the amount of API polling this would require (plus it's a whole new avenue for us - so far we've been an item manager, and now we'd start watching your actual game activity).
