### ISSUE TITLE
Farming Mode - Report/Summary Idea Thing

### ISSUE THREAD

**Issue by Mulchman** [DestinyItemManager/DIM#1189]
Saw that Ishtar Commander had a summary thing for farming mode, and mocked up an example in DIM-

![farmreport](https://cloud.githubusercontent.com/assets/11757993/20286854/c5970c7c-aa7d-11e6-8246-835a10e86d6b.gif)

Any interest in pursuing something like this?

**Comment by Mulchman** [comment]
The gif goes a bit fast. Here's a still of the report view-

![image](https://cloud.githubusercontent.com/assets/11757993/20286904/fe5d5b2e-aa7d-11e6-88bf-4a493d1d172a.png)

**Comment by kyleshay** [comment]
really cool option. cool that it can be shown/hidden with that icon toggle! nice work @Mulchman !

**Comment by kyleshay** [comment]
Expanding slightly on this, could be cool to show some stats like average number of MoL/hour or legendaries/hour. Or just show total time that farming mode was running.

**Comment by Mulchman** [comment]
Metrics like MoL/hour could be interesting... here's an updated mockup (and there's a lot of wasted space I'm noticing as of posting this picture)-

![image](https://cloud.githubusercontent.com/assets/11757993/20320859/2e912e42-ab28-11e6-85d1-a935135ce86a.png)

This is an all inclusive list of things I thought might be interested in capturing in the `Farming Summary` screen and definitely open to suggestions...

Also, I can't get the CSS to do what I want which is why the weird centering is happening. I want the `dim-simple-item` guys to be `justify-content: flex-start` and their parent container centered horizontally but all attempts just leave the parent container aligned to the left...

**Comment by kyleshay** [comment]
are you thinking of having the table show just what was gathered during farming, or always displaying everything like that?

we already keep track of "new" items so i'm guessing we could re-use some logic from that?

**Comment by Mulchman** [comment]
> are you thinking of having the table show just what was gathered during farming, or always displaying everything like that?

Just what was gathered while farming mode was enabled.

**Comment by shockthealien** [comment]
love this idea, specially with the stats like kyleshay said.

I wish my vault wasnt so full so i could take advantage of this :(

**Comment by Mulchman** [comment]
> we already keep track of "new" items so i'm guessing we could re-use some logic from that?

I've had some time to actually make it start live tracking and the code is pretty simple. I have a bunch of hashes (this could be a bad approach...?) for rare/legendary/exotic engrams + consumable type things and I'm making a `starting` list and then on each `dimFarmingService.farm()` tick creating a list of things that have changed. This list of changed things is what the UI is displaying.

![screen shot 2016-11-19 at 10 30 34 am](https://cloud.githubusercontent.com/assets/11757993/20457583/4492c08e-ae43-11e6-8fa4-62e34b3d3ffa.png)

It's all in its own separate `service/factory` at the moment, `dimFarmingReportingService`.

As for the metrics, I'm kind of leaning towards showing that kind of stuff as well, in addition to keeping a broader list of everything farmed between multiple farming sessions while the app is open. I know when I use farming mode, I use it for a while, turn it off to decrypt, then turn it right back on. It's only at the end of a long play session that I would be interested in seeing overall stats; ie. I don't want to lose the stats until I close the app not every time I toggle on/off farming mode... if that makes any sense.

**Comment by Mulchman** [comment]
![screen shot 2016-11-25 at 11 35 35 am](https://cloud.githubusercontent.com/assets/11757993/20634233/649babba-b303-11e6-98f1-db597f94a0fb.png)

Added `glimmer`/`legendary marks` + made the timer work.

How do you guys envision the `xyz / hour` thing displaying? Hover? Click? Part of the `amount` string in the bottom right of the item?

**Comment by bhollis** [comment]
Closing in favor of #1214.
