### ISSUE TITLE
Vendor quality rolls not accurate

### ISSUE THREAD

**Issue by shockthealien** [DestinyItemManager/DIM#1193]
Hi

I was so excited when vendor quality stats came back. I noticed Shaxx had awesome 100% gauntlets so i gabbed some for my Titan, only to find out when i got them that they are in fact 98% not 100%. I havent checked any other items but just flagging this in case theres an issue. 

I even infused the gloves up to 390 to see if it was because they come as 350 but no, still 98%

![screen shot 2016-11-18 at 17 27 17](https://cloud.githubusercontent.com/assets/2083273/20439633/56dd593c-adb4-11e6-8141-d3fa7c1dc49e.png)
![screen shot 2016-11-18 at 17 26 59](https://cloud.githubusercontent.com/assets/2083273/20439632/56daaf0c-adb4-11e6-980d-ecb077ef701b.png)

**Comment by wein3967** [comment]
I saw this last night as well. The Tower+ app reported the same thing. So without checking it myself, I'd guess that Bungie is returning incorrect value (rounded?) vs. in-game.

**Comment by bhollis** [comment]
That's right. I don't know why Bungies data pipeline causes the vendor API to not match in game stats, but there's not much we can do about it. 

-Ben

**Comment by bhollis** [comment]
Closing since it's a Bungie data issue.
