### ISSUE TITLE
Item Leveling - Item selection logic

### ISSUE THREAD

**Issue by adamksib** [DestinyItemManager/DIM#1194]
Item levelling works in two astonishing ways.
1. It de-equips items that are not fully levelled
2. Even if the character has items that are not fully levelled, it transfers items from the vault

Logic should be:

1. For any given slot
2. Does the equipped item need levelled
3. If yes, move to next slot
4. If no, does the character have any items not fully levelled in that slot
5. If yes, equip item that is the most levelled
6. If no, as steps 4 & 5 but on other characters
7. If no, as steps 4 & 5 but in the vault

Edit: Updated for @shockthealien comments

**Comment by shockthealien** [comment]
I would add in step 6 to look in your other characters inventory before looking in the vault

**Comment by adamksib** [comment]
Having read the comments in the code, some of the above it is supposed to do.  However, the reason I came here was the it de-equipped my Bones of Eao, the specific item I was trying to level.

**Comment by bhollis** [comment]
Sounds like a bug to me. It shouldn't dequip an item that's not finished. It's probably the logic that tries to handle exotics.

**Comment by bhollis** [comment]
Closing out D1-specific stuff that isn't going to make it.
