### ISSUE TITLE
Exclude multiple Felwinter's Lie

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#1205]
Seems that the auto-exclude function for Loadout Builder only excludes at most one Felwinter's lie.  If players have more than one, then they have to manually exclude the other instances of the item.

DIM should auto exclude all of them.

**Comment by bhollis** [comment]
I pushed a fix for this, but I don't actually have multiples - if somebody gets a change to test, that'd be good.
