### ISSUE TITLE
use buckets instead of the itemtype filter we have

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#121]
https://github.com/kyleshay/DIM/blob/master/app/scripts/services/dimStoreService.factory.js#L386-L421

we get this information in a much cleaner way from the item definition file as their bucket information.

https://github.com/kyleshay/DIMDefs/blob/master/app.js#L36

**Comment by phatsk** [comment]
I had a plan to clean up the code in StoreService to make these a little more manageable, something like:

````javascript
var filters = {
	'Primary': ["Pulse Rifle", "Scout Rifle", "Hand Cannon", "Auto Rifle", "Primary Weapon Engram"],
	'Special': ["Sniper Rifle", "Shotgun", "Fusion Rifle", "Special Weapon Engram"],
    // etc
};

// That can be used like
for(var k in filters)
	if(filters.hasOwnProperty(k) && !!~filters[k].indexOf(type))
		return k;
````

**Comment by kyleshay** [comment]
we also get the primary/special buckets from the item Defs -> 

https://github.com/kyleshay/DIMDefs/blob/master/app.js#L36

and then we have:

  buckets: {
    1498876634:"Primary",
    2465295065:"Special",
    953998645:"Heavy",
    3448274439:"Helmet",
    3551918588:"Gauntlet",
    14239492:"Chest",
    20886954:"Leg Armor",
    2973005342:"Shader",
    4274335291:"Emblem",
    2025709351:"Vehicle",
    284967655:"Ship",
    3865314626:"Material",
    4023194814:"Ghost",
    1469714392:"Consumable",
    1585787867:"Class Item",
    3284755031:"Subclass"
  },

**Comment by kyleshay** [comment]
@phatsk the problem with that are special exotics, such as the vex --> it's a primary fusion rifle, etc

**Comment by SunburnedGoose** [comment]
We should have a 'itemType' and a 'viewItemType' to separate these concepts.

**Comment by kyleshay** [comment]
what would be the difference?

**Comment by SunburnedGoose** [comment]
Mythoclast is a special weapon (itemType) that is available in the primary
slot (itemSlotType).

itemType vs itemSlotType.

Same thing for Postmaster items. I had to make their itemType Postmaster
which can breaks search when looking for Primary Engrams. They won't show
up because I had to manipulate the itemType to fit the view.

It really is just a model-viewModel problem.

**Comment by kyleshay** [comment]
well i mean if we do a search for special items, i don't think the vex should show up... it should show up when you do i primary search. it should also sit in the primary weapon area... i don't think we should say it's a special weapon anywhere... which just means we can go off the bucket information from bungie (which says that it's a primary weapon)

unless i'm missing something?

**Comment by phatsk** [comment]
I think it's important to remember that the game still counts is as a "special" weapon. Take for instance the Iron Banner bounty for headshots with a primary weapons - the Vex _does not_ count towards this bounty. In the grand scheme of things, I think it boils down to not confusing the end-user. Would it be possible to have it appear in all of the following filters:

* `is:fusionrifle`
* `is:primary`
* `is:special`

?

**Comment by kyleshay** [comment]
i've thought about that... it's a tricky one. 

i guess it comes down to will people create an issue/post about the vex showing up in the `is:special` filter or not. i suppose most won't care. the important thing is that it does show up at least the other two filters.

**Comment by TopDawggamer** [comment]
I think the Vex Should only show for
