### ISSUE TITLE
"Make room for Post Items" button suggestion

### ISSUE THREAD

**Issue by SentryTheDefiant** [DestinyItemManager/DIM#1210]
When decrypting loot hauls, it's easy to stop farming mode, and then gather engrams, but my Fireteam feels like the missing function is a button to perfect the process is one to make room for all the stuff in your post office so you can pull it all out and decrypt it at once instead of running back and forth from the post office to the cryptarch. I know if you use farming mode effectively, it's not an issue, but sometimes you don't turn farming mode on until you realize we should have used it from the get go,  and your post office already has items.

**Comment by bhollis** [comment]
Love it! Closing this in favor of https://github.com/DestinyItemManager/DIM/issues/502. Good news is that this is coming soon.
