### ISSUE TITLE
Display a count of items matching the active filter

### ISSUE THREAD

**Issue by bradchoate** [DestinyItemManager/DIM#1219]
If I filter my inventory, a count of items matching that filter should be shown (one count per section — weapons, armor, etc.)

**Comment by bhollis** [comment]
The counts are how much of your vault is occupied.... That doesn't change with filters. 

-Ben

**Comment by bradchoate** [comment]
Let me fix the description. I'm asking for a way to know how many items are matching the filter.

**Comment by bhollis** [comment]
Closing in favor of #1228
