### ISSUE TITLE
[Video]  When moving equipped exotic Heavy Weapon, another heavy is pulled from vault to "equipped" slot, even if there are more Heavy Weapons in inventory.

### ISSUE THREAD

**Issue by Wooleyful** [DestinyItemManager/DIM#1221]
https://www.youtube.com/watch?v=HEkUe9uRBPs&feature=youtu.be

When the Dark Drinker is moved to another character, DIM takes another heavy from vault to equip even though there are heavies already in that character's inventory.  This seems to happen when all of the items in a current slot are all exotics, the bug happens with weapons and armor.

Upon further investigation if there are legendary items in the inventory, an exotic is not pulled from the vault, only when all items in the inventory are exotics.

**Comment by bhollis** [comment]
Fixed in #1156
