### ISSUE TITLE
Moving item to equipped on another character results in a false error "item not found"

### ISSUE THREAD

**Issue by nki2bpz** [DestinyItemManager/DIM#1225]
It moves the item correctly but gives the error "item 'name' not found". If i move the item in two steps, to the character, then equip on that character, it does not error. This seems to happen when the destination character has all slots full.

**Comment by SunburnedGoose** [comment]
We need to improve the error message to show the chain of responsibility. Moving an item to prepare the store for another item can cause an error, but the item name does not reflect the true item errorring.
