### ISSUE TITLE
3.14 Edit loadouts: Incorrect class name shown

### ISSUE THREAD

**Issue by edmiller47** [DestinyItemManager/DIM#1227]
One small issue with the update: When editing a class-specific loadout, the tag that pops up next to the loadout name has the wrong class on it. For example, I have a loadout for my Warlock called "PVP Warlock", which I chose from the Warlock's dropdown, and when I edit it, the tag next to it says "Titan".

**Comment by nki2bpz** [comment]
this was already addressed and changes made just waiting for 3.14.1 to drop. Its probably awaiting google approval? I guess i shouldn't have closed the issue till it was in our hands :/

**Comment by SunburnedGoose** [comment]
Fixed and available now in the stable release, v3.14.1.
