### ISSUE TITLE
[Vendors] category.title is not localized

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#1236]
![screenshot 2016-12-11 04 13 06](https://cloud.githubusercontent.com/assets/4798491/21079729/368ad2c6-bf58-11e6-8085-6b88087ee2aa.png)

![screenshot 2016-12-11 04 13 16](https://cloud.githubusercontent.com/assets/4798491/21079730/3b792922-bf58-11e6-8a2f-da5880b2310e.png)

Possibly an issue with bungie not providing translations.

![screenshot 2016-12-11 04 16 02](https://cloud.githubusercontent.com/assets/4798491/21079744/95399e06-bf58-11e6-879c-40b1495da7b1.png)

**Comment by bhollis** [comment]
We should be using the ones from the manifest. Not sure why they wouldn't be translated.
