### ISSUE TITLE
Takes a long time to unzip manifest file

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#1238]
In this image, it took ~60s for the manifest file to download, be parsed, and saved.  That was a much longer time than I am used to seeing.  Any thoughts why it was taking so long?

![image](https://cloud.githubusercontent.com/assets/984608/21083823/40a3aad8-bfbe-11e6-828b-cd3d916db0f3.png)

**Comment by bhollis** [comment]
Perhaps the web worker wasn't working?

**Comment by bhollis** [comment]
Haven't seen this since...
