### ISSUE TITLE
Vendors do not load

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#1241]
![screenshot 2016-12-11 17 18 57](https://cloud.githubusercontent.com/assets/4798491/21084789/ef2ab93c-bfc5-11e6-835c-ddcc7dd04ed1.png)

No errors in console log.

**Comment by SunburnedGoose** [comment]
They will load when Bungie adds them to their OAuth scope.  Should be when they hotfix their servers again.  Dec 13th?

**Comment by delphiactual** [comment]
They do now
