### ISSUE TITLE
Displaced label positions in item comparison section

### ISSUE THREAD

**Issue by mwallasch** [DestinyItemManager/DIM#1247]
Hi,

the row labels are slightly displaced (one row too far down.)

Browser: Chrome, 54.0.2840.98, Mac 
DIM Version: 3.14.1

![bildschirmfoto 2016-12-12 um 10 58 51](https://cloud.githubusercontent.com/assets/355209/21095406/839d3a64-c05b-11e6-9d7b-1b899da3fef2.png)

**Comment by delphiactual** [comment]
https://www.reddit.com/r/DestinyItemManager/comments/5icytc/compare_numbers_not_lining_up/

Another report, it looks like it is due to the scroll bar...
