### ISSUE TITLE
is:complete not working properly [3.0.3]

### ISSUE THREAD

**Issue by m-s-y** [DestinyItemManager/DIM#125]
DIM 3.0.3:

filter of *is:complete* is not returning all completed items.  Screenshot attached shows that some items are properly identified as complete, but others are not.  

I clicked on Oversoul Edict in the screenshot -- the pop-up shows that DIM identifies it with 331 attack, meaning it must be a complete weapon, yet it's not marked as visible.

I put yellow stars next to other items in my inventory that are also complete, yet not visible with this filter.

![2015-05-15_14-17-42](https://cloud.githubusercontent.com/assets/6401354/7659127/c9541e5c-fb0d-11e4-8fbd-3110b4c679b0.png)

It does appear that *is:xpcomplete* is working properly, though.

**Comment by SunburnedGoose** [comment]
Did you buy that hive disruptor perk?

**Comment by m-s-y** [comment]
yeah, but its Oversoul, not the broken Black Hammer one.  even so, some of the "normal" weapons in my vault aren't triggering properly either

**Comment by SunburnedGoose** [comment]
Ok, I'll check it out.  Looking at my Atheon's Epilogue, it shows 300, but the flag from Bungie says it's not complete.  Gonna have to look at it to see if there is something else we're missing.

**Comment by m-s-y** [comment]
Ever notice that when you transfer some items back into inventory - even if they're complete - the in-game Destiny inventory marks some nodes as "new"?  Could be a bungie API issue...

**Comment by SunburnedGoose** [comment]
Was this pre-patch or post-patch?

**Comment by phatsk** [comment]
Thought: "complete" may not be true until the Ascension tier comes in with HoW. Just about all legendaries will be able to ascend to higher attack values. Maybe also an API issue, as I do have that happen when an item will sometimes come across as "Unupgraded" until you view it

**Comment by SunburnedGoose** [comment]
Looks like the B.net update is changing our gear.  All my guns are slowly becoming incomplete.

Might have to add a new feature is:ascended

**Comment by m-s-y** [comment]
FYI: both pre-and post 1.2.0 patch the behavior is the same.   I just noticed they were updated, and so I grabbed the updated manifests from the Bungie API...  likely this issue *is* related to the HoW release.

is:ascended sounds like it will be useful

**Comment by m-s-y** [comment]
Oops.  Mis-clicked.

**Comment by phatsk** [comment]
Proposal:  

* is:ascended
* notis:ascended

Could we use `notis` as a negative match to existing searches? Or something similar.

**Comment by SunburnedGoose** [comment]
In the future, I see there being three states: is, not, indeterminate. If
we visually represent these options, you would click once to select the
filter to reduce, click again to reduce the opposite, and then click once
more to clear the filter from the collection.

**Comment by SunburnedGoose** [comment]
As for your question, in the near term, I'm fine with is: and not: That
feels the clearest. Now do we have to refactor all of the filters?

**Comment by kyleshay** [comment]
is this still an issue?

**Comment by bhollis** [comment]
This has all been fixed in #382.
