### ISSUE TITLE
Undefined Error when DIM is Unattended

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#1250]
Resuming a session with DIM threw an Undefined error as a toaster, and then the application refreshed.  Need to look into this issue and see if it is related to the OAuth update.

**Comment by delphiactual** [comment]
It seems to be an error with `headers`

![screenshot 2016-12-12 09 26 31](https://cloud.githubusercontent.com/assets/4798491/21106928/22a16e0a-c04d-11e6-8916-c998d9c66418.png)

**Comment by SunburnedGoose** [comment]
Narrowing it down.  We're trying to process a response that doesn't have an ErrorCode.

**Comment by SunburnedGoose** [comment]
Fixed.
