### ISSUE TITLE
Popup windows don't dismiss in Safari 10.0.1

### ISSUE THREAD

**Issue by dustinrue** [DestinyItemManager/DIM#1258]
Safari 10.0.1, OS X 10.12.1. Any popup window created can't be dismissed. 

Click character menu or an item. Try to get rid of the menu or popup. 
![screenshot 2016-12-13 13 33 39](https://cloud.githubusercontent.com/assets/573953/21155707/cc78b30c-c138-11e6-99aa-82df621108ae.png)

**Comment by bhollis** [comment]
Can't repro - at least in OS X Safari. Clicking elsewhere and/or clicking the item again closes the popup. @SunburnedGoose did you fix this?

**Comment by bhollis** [comment]
He did fix it.
