### ISSUE TITLE
Provide fallback for CSS vars (Edge)

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#1266]
Edge doesn't support CSS vars. Detect support and fallback to fixed sizes.

**Comment by delphiactual** [comment]
https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/6261292-css-variables

**Comment by bhollis** [comment]
Nice! Providing fallback won't be hard, though - I'm just waiting until we can easily develop on the website.

**Comment by SunburnedGoose** [comment]
@bhollis, what do you need to make it easier to develop on Edge?  I use a local web server right now and I don't use the chrome extension.

**Comment by bhollis** [comment]
I assume I'm waiting until you merge your branch. I can't auth on dev, running a local web server. 

-Ben

**Comment by SunburnedGoose** [comment]
I tested this today and I can add hard coded values before the CSS Variables and Edge will work.

**Comment by bhollis** [comment]
Fixed!
