### ISSUE TITLE
Create loadout from loadout builder has no class selection

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#1270]
The dropdown is empty

**Comment by delphiactual** [comment]
it should just be hidden and set to the current class

**Comment by delphiactual** [comment]
https://www.reddit.com/r/DestinyItemManager/comments/5ka9lk/3151_stable_build_issues/

**Comment by delphiactual** [comment]
The dropdown is populated on `dev`, but not `beta`

**Comment by delphiactual** [comment]
Clicking on the dropdown repeatedly eventually fills it...
