### ISSUE TITLE
DIM doesn't respond well when Bungie deletes equipped items...

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#1278]
Had the broom sparrow equipped on character 2 & 3...

![screenshot 2016-12-14 15 59 06](https://cloud.githubusercontent.com/assets/4798491/21204852/7e6bdce6-c216-11e6-94e3-99d7df3e674b.png)

**Comment by bhollis** [comment]
Yup.

**Comment by bhollis** [comment]
This is one of those edge cases that's probably not worth fixing, given how our layout mechanisms work. It's unlikely to happen often, and it's not too bad (it's still showing you your stuff). I'm gonna wontfix this one.
