### ISSUE TITLE
"Add to homescreen button"

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#1287]
If a user loads DIM on chrome, we should see if they'd be interested in adding the app to their homescreen.

https://developers.google.com/web/updates/2015/03/increasing-engagement-with-app-install-banners-in-chrome-for-android

**Comment by bhollis** [comment]
Criteria for this has changed, and it's now weirdly automatic, based on a bunch of crazy criteria. We'd at least need a service worker: https://developers.google.com/web/fundamentals/engage-and-retain/app-install-banners/

**Comment by bhollis** [comment]
This should happen automatically now. We can force it ourselves on iOS, but I always hate those popups.
