### ISSUE TITLE
Broken Stats bar for Memory of Felwinter artifact

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#1288]
https://twitter.com/RynoRangerGames/status/811283252635910144

The stats bar is bigger than the space, and is wrapping.

![image](https://cloud.githubusercontent.com/assets/984608/21363954/4e9ec1b6-c6b4-11e6-9b28-537158eebb1d.png)

**Comment by bhollis** [comment]
Yup, it's been like that since RoI launched. Not sure what to do about it - we could rescale the maximum for all items (which would suck) or we could cap Felwinter...

**Comment by kyleshay** [comment]
let's cap it and continue to show the % as we do.

**Comment by SunburnedGoose** [comment]
Looking at the issue, we're showing the stats of the item in white, and the difference in red or green depending if it is positive or negative.  We're doing some math to place the items next to each other.  Could we just refactor to stack them so the white is always on top and we can then just use max-width: 100% of the container for both items?
