### ISSUE TITLE
Consumable/material move popup initial amount

### ISSUE THREAD

**Issue by Mulchman** [DestinyItemManager/DIM#1295]
Something's happened to the way consumables/materials are treated. I'm running dev at https://github.com/DestinyItemManager/DIM/commit/02dfa1c4d820f304ea8f876a2a700c795102b561 .

If you have multiple stacks of an item on a character/vault, when you click one of the stacks the move box gets populated with the sum of all stacks on that character/vault. In this screenshot I clicked the Helium Filaments stack containing 168 yet the dialog added the other stack of 200 to the initial value:

![image](https://cloud.githubusercontent.com/assets/11757993/21436998/214cea98-c836-11e6-8e19-25efa5e1dc63.png)

**Comment by Mulchman** [comment]
Looks like `moveAmount` has been `maximum` for quite some time: https://github.com/DestinyItemManager/DIM/commit/dd27857579541901bd82a91a982f4c163a80efa2#diff-638d9f2f993086cce823cf60e53803b3

I guess I haven't moved stacks via the popup in a while.

To me, it doesn't make sense for the popup value to be different than the stack I clicked.

**Comment by bhollis** [comment]
That's how it's worked since the very beginning of stack support, actually. 

-Ben

**Comment by Mulchman** [comment]
It doesn't really make sense, though. Dragging a stack doesn't suddenly include all the other stacks. Clicking a Clever Dragon and selecting a character doesn't all of a sudden move all other Clever Dragons, too. Plus, Consolidate exists.

**Comment by bhollis** [comment]
I don't see those as the same thing. Dragging just one stack makes sense, and handling all the stacks in a single place as one from the move pop-up, where we offer an amount slider, also makes sense. (You can do multiple stacks while dragging, too - just hold shift or dwell over the drop target)

I like the behavior how it is, though a button for immediately scoping to a single stack (like we have for the drag and drop dialog) would be nice. 

-Ben

**Comment by SunburnedGoose** [comment]
I’ve noticed this before, so it isn’t new, but I’ve never got around to asking.

If we set the default to maximum, how do we just move one stack if that’s the goal of the player?  Tell them to use drag and drop?

The issue I have is that we’ve lost information by defaulting to maximum as there is no easy way to go back to the amount in the stack.  It would be much easier to have a ‘max’ label at the end of the slider than it is to fiddle with the slider to find the number to match the stack.

**Comment by bhollis** [comment]
The stack limits are sort of an arbitrary thin imposed by the game logic. If you're going through the popup we should help out by treating it all as one continuous pile, with a button to limit it to just one stack's worth. All we're missing is "this stack" and "max" quick buttons. 

-Ben

**Comment by SunburnedGoose** [comment]
The question is, which perspective are players more likely to want?  I'm going to riff on what 'max' means here too.

Do we default to...

- the selected stack amount,
- the maximum amount on the character, 
- the maximum number of consumable slots,
- the maximum amount on the account

**Comment by kshep** [comment]
> The question is, which perspective are players more likely to want?

I'd pose it slightly differently: is there a compelling reason to change things from the current behavior, which is what everybody who's using DIM right now is used to.

**Comment by SunburnedGoose** [comment]
We project stackables as stacks in the UI.  When we move them via drag and drop, we're moving just the stack.  In this case, with the popup, we're diverging and defaulting to entire amount of a stackable item on the character for the transfer operation.  

It's the odd-duck that suffers from information loss because it imposes on the player some difficulty to get the slider to the amount selected stack.  In fact, it is not possible in some cases to hit on the stack size with the slider because the amount per pixel can be > 1 so I could never be able to move 200 spinmetal if I had enough.

I have a preference for a consistent behavior when transferring items, and the move popup is a great place to have more options such as moving the slider to max available on character, or creating ticks on the slider to match the stackable so you can choose to move two stacks etc...

**Comment by delphiactual** [comment]
This has been resolved
