### ISSUE TITLE
Vendor Timers do not reset at vendor reset

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#1297]
https://www.reddit.com/r/DestinyItemManager/comments/5kiyrv/vendors_inventory_not_updating_with_reset/

**Comment by bhollis** [comment]
Hmm, perhaps we're using the wrong timestamp to compare with (for example, not converting times to UTC). I live in the same time zone as Bungie's servers, so that may be why it's worked fine for me. The logic is very simple and straightforward, so I'd bet that's what it is.

**Comment by bhollis** [comment]
Hmm, I've spent a while poking at this, but I can't find anywhere we're not using UTC timestamps. Any leads would be appreciated.

**Comment by delphiactual** [comment]
I'll watch it tonight at reset and see what happens

**Comment by delphiactual** [comment]
Easiest one to see this happen on is Hunter, Titan, and Warlock Vanguards... They are only ~2hrs between resets, they will sit at 0:00:00 for awhile.

**Comment by delphiactual** [comment]
So based on the Vanguards, it appears cache-busting is working... but the timers are not updating.. unless stock for the vanguards is static...

**Comment by bhollis** [comment]
I bet the timers are busted!

**Comment by delphiactual** [comment]
https://www.reddit.com/r/DestinyItemManager/comments/60mnkw/vanguard_vendors_reset_times_are_2_hours_too_late/

**Comment by bhollis** [comment]
I'd love it if somebody else would look at this. I poked at it and didn't see any obvious problem. 

-Ben

**Comment by bhollis** [comment]
This one's both minor, old, and as of now, D1-specific. We'll revisit when we make a D2 vendors page.
