### ISSUE TITLE
Store Service Console Logging

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#1301]
![image](https://cloud.githubusercontent.com/assets/984608/21535379/de84916c-cd39-11e6-8a45-10061bb0c6ac.png)

Are these still needed @bhollis?

**Comment by bhollis** [comment]
Nope. They're helpful when judging whether DIM is slow vs Bungie.net being slow, though. 

-Ben

**Comment by SunburnedGoose** [comment]
Sounds like a good feature for a developer toggle.

**Comment by bhollis** [comment]
Yup!
