### ISSUE TITLE
XML request cannot load

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#1302]
@bhollis 

```XMLHttpRequest cannot load https://www.bungie.net/common/destiny_content/sqlite/en/world_sql_content_b8ee8e3cc4c38460966cee2f10e238a3.content. The 'Access-Control-Allow-Origin' header has a value 'https://www.bungie.net' that is not equal to the supplied origin. Origin 'https://beta.destinyitemmanager.com' is therefore not allowed access.```

Was receiving this error on the website, changing languages would work, but upon setting language back to 'en' the error returned.

I had to clear `hosted app data` and then I was able to access the website in `en`

**Comment by bhollis** [comment]
For the website we probably need to make sure the manifest request is authors, I guess?

-Ben

**Comment by bhollis** [comment]
Fixed by using a cache buster. In beta already.
