### ISSUE TITLE
[Filters] some not filters are not working

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#1305]
The following filters are not working correctly
`not:primary` `not:primaryweaponengram` `not:exotic` etc

**Comment by bhollis** [comment]
Did we i18n some of this? is:exotic doesn't work anymore either.

**Comment by delphiactual** [comment]
not that I know of

**Comment by delphiactual** [comment]
@bhollis a hard-refresh `F5` seems to have fixed the issue, but it come back after multiple searches...

**Comment by bhollis** [comment]
Fixed. Such a little thing!
