### ISSUE TITLE
[Webpack] Fix $DIM_VERSION, $DIM_FLAVOR

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#1314]
I think we don't use Grunt anymore, right? Can we fix the things we used grunt for to go through webpack, or otherwise fix the `.travis.yml` so it'll still build and upload the beta extension?

The only other thing I'm worried we're missing is the `$DIM_VERSION`, etc, replacements we did with Grunt.

/cc @joshhunt

**Comment by delphiactual** [comment]
@bhollis 
This might work as a replacement for `grunt-replace` https://github.com/Va1/string-replace-loader

**Comment by joshhunt** [comment]
`DefinePlugin` https://webpack.github.io/docs/list-of-plugins.html#defineplugin

**Comment by bhollis** [comment]
@joshhunt that looks perfect!

**Comment by delphiactual** [comment]
something along these lines...
`webpack.js`
```
      new webpack.DefinePlugin({ // beta version settings below
        // $DIM_VERSION: JSON.stringify(''),
        $DIM_FLAVOR: JSON.stringify('process.env'),
        $DIM_CHANGELOG: JSON.stringify('process.env.CHANGELOG_URL'),
        $DIM_API_KEY: JSON.stringify('process.env.API_KEY'),
        $DIM_AUTH_URL: JSON.stringify('process.env.AUTH_URL')
      }),
```
