### ISSUE TITLE
[Webpack] Split bundle to vendor and 1st-party

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#1315]
Might be worth looking at https://medium.com/webpack/webpack-http-2-7083ec3f3ce6#.6riie98xh

/cc @joshhunt

**Comment by bhollis** [comment]
We probably at least want to split vendor (which should change infrequently and thus be cacheable) from DIM sources (which change all the time).

**Comment by joshhunt** [comment]
Yeah great idea. We're actually already splitting out the SQL.js module
which more than halves the main bundle size.

Increased cacheability of the vendor stuff would be great as well for the
website

**Comment by bhollis** [comment]
http://stackoverflow.com/questions/30329337/how-to-bundle-vendor-scripts-separately-and-require-them-as-needed-with-webpack

**Comment by bhollis** [comment]
This actually turns out to be super complicated, since Webpack goes ahead and modifies your chunks every time you build. There's some stuff to help out with that (like https://github.com/soundcloud/chunk-manifest-webpack-plugin) but that's super hard to set up. Since the goal is to improve cacheability (not just break up files), we'd have to do that.
