### ISSUE TITLE
[Webpack] Update instructions

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#1317]
I can't quite figure out how to either run the site generated by "npm start" as either a website (I tried using `python -m SimpleHTTPServer` but the site doesn't work) or as an extension (there's no manifest for Chrome). It'd be nice to have some quick start docs, even for us old-timers :-)

/cc @joshhunt

**Comment by delphiactual** [comment]
the main trick is to `reload the extension` if you change to/from webpack as the index.html file is moved

**Comment by bhollis** [comment]
I would love to be at the point where reloading is the problem, rather than loading the first time!

**Comment by delphiactual** [comment]
No `reloading` from here: 
![screenshot 2016-12-31 18 33 41](https://cloud.githubusercontent.com/assets/4798491/21579899/b7ddd0a0-cf87-11e6-9b6e-8b4a88c54859.png)

**Comment by bhollis** [comment]
Ah I see what I missed. I thought I had to load the extension from a different path (`app/generated`) but it looks like it was set up to load from `app` just like before. Nice!
