### ISSUE TITLE
Provide the user with view to guide them through the Bungie Authentication process.

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#1326]

**Comment by bhollis** [comment]
Think people need this? It's pretty straightforward.

**Comment by kyleshay** [comment]
At this point it's just click the button and sign in to bungie.net if needed. We have a [Do you want to know more?](https://github.com/DestinyItemManager/DIM/wiki/Authorizing-Destiny-Item-Manager-with-Bungie.net) button which should satisfy this
