### ISSUE TITLE
IFTTT

### ISSUE THREAD

**Issue by joshmedeski** [DestinyItemManager/DIM#1329]
So we've had conversations about using Siri with DIM, here is a question/thought.

Could we someone integrate IFTTT with DIM? There is a [maker service](https://ifttt.com/maker) provided by IFTTT that lets you receive and make web requests to automate things.

If we could build a way to communicate with your DIM instance using web requests it would be really easy to setup commands for Alexa or Google Home (or any service IFTTT supports).

Thoughts?

**Comment by EffortlessFury** [comment]
I think what's difficult about that is no matter what you need a service layer that does routing. It could be done, perhaps, if there was a service that's only job was to redirect requests to the user's instance, but it'd still need to route EVERY request.

Ideally it'd be awesome if the backing services of DIM were cloud based, but alas that'd probably be a bit of an expense.

**Comment by bhollis** [comment]
I think this is a great idea (same with the Alexa stuff) but it'd have to be either another project or, as @EffortlessFury said, a hosted service. If there's a PR that can be made for this, that'd be awesome, but I don't think we should keep this open as a feature request.
