### ISSUE TITLE
Opt-in for enhanced notifications

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#1332]
It would be neat if people could build rules for notifications on the vendor page. For example if a cloak appears with 100% intellect and 100% discipline: on reset they will get a popup showing where it is available.

https://www.reddit.com/r/DestinyTheGame/comments/5lr3ca/the_speaker_is_selling_two_100_stat_roll_class/dbxu7rk/

**Comment by kyleshay** [comment]
Going on this, setting notifications for gunsmith rolls (for example, if you're waiting for an arminius-d with counterbalance, and w\e else.)

**Comment by SunburnedGoose** [comment]
Would be nice if there was a 'test' button to make sure DIM was searching all of your rules.  "No Dave, I do not see one yet..."

**Comment by bhollis** [comment]
Collapsing with #1424.
