### ISSUE TITLE
Errors moving items : "id" of undefined

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#1335]
https://www.reddit.com/r/DestinyItemManager/comments/5lyvda/latest_beta_version_much_more_frequent_item/

I've seen this error too.

> I am noticing with the latest beta version (v3.15.1.671), many more item transfer errors than with the previous version. They all have the error mentionned in the title, preceeded by the name of the item i am attempting to transfer.
> This seems to occur most often when attempting to move an item to a character who has a full inventory for that type (ex: moving a heavy weapon to a character who already has 9 heavy weapons + 1 equipped).
> This error occurs even when there is sufficient space in the vault to make room to transfer the item in question (ex: 4 open spaces in the weapons vault).
> This error also occurs when i try to move a piece of armor from one character to another, but the vault is full, even if there is plenty of room in my characters inventory to move something out of the vault temporarily to make room for the transfer to occur.
> In the previous version, DIM would make room to transfer the item for me by moving one of the items in my inventory, which i liked a lot.
> Is this a bug? Thanks.

**Comment by SunburnedGoose** [comment]
More reports. 

https://twitter.com/k0hum/status/817221584016457729

**Comment by bhollis** [comment]
Yeah, I've seen this, and I've even caught it with a debugger, but I haven't yet figured out what's going on. As far as I know a local variable is failing to be captured in a closure. I didn't think that could happen.

**Comment by SunburnedGoose** [comment]
Nature finds a way.  I'll keep an eye out.  I don't have a repro.

**Comment by bhollis** [comment]
Here's the solution, but I still don't understand the problem: https://github.com/DestinyItemManager/DIM/pull/1345
