### ISSUE TITLE
Applying Loadouts to Vault

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#1336]
https://www.reddit.com/r/DestinyItemManager/comments/5lud9t/v3151_partial_loadout_transfer_problem/

> Hi. Thanks for creating such a useful tool. I just wanted to flag that a feature I used to find very useful has been changed in this build, possibly for the worse.
> For a while I have been creating saved loadouts to hold items for deletion or infusion fuel. To do this I have made sure no items are marked to be equipped and selected "Any" from the dropdown box denoting which characters will see the loadout. These loadouts then hold items from more than one character. This allows for quick sharding, without switching between the app and the game after every item, and allowing quick infusion with readily available fuel.
> The problem I've had with this release is possibly a new feature. Currently items in a loadout will only transfer when they are equipable on that character or, if transferring to the vault, are equipable by all classes. This leads to partial loadout transfers while producing a successful transfer notification.
> There are three main problems I see with this:
> The inability to transfer a loadout to the vault is dangerous and may cause accidental deletions when people think it's safe to delete or infuse any remaining items on a character.
> The ability to transfer something to the vault and back allowed the game itself to highlight items. This allowed an in game verification for items to be discarded, increasing the safety of using DIM for vault management.
> Without the ability to place infusion fuel in its own loadout, items have to be transferred individually making it much more of a chore.
> I can understand that preventing items transferring to characters that can't use them makes some sense but I would argue that it removes utility while adding very little. I would also argue that it should always be possible to transfer a loadout to the vault in its entirety for safety if for no other reason.

**Comment by tcurtin** [comment]
FWIW, there's the capability in the beta version of DIM to tag items as one of Favorite, Keep, Junk, or Infuse.  If you could select based on these tags (I haven't found if that's possible, but it should be), and then transfer based on selection... that seems like it might fit your use case even better than loadouts.

Devs?  Thoughts?

**Comment by tcurtin** [comment]
And I stand corrected: tag:favorite works in the search field.  So all that's left is transferring by search.  (Maybe I'm missing that somewhere too?)

**Comment by delphiactual** [comment]
second loadout in the list when a filter is applied

**Comment by tcurtin** [comment]
Wait - what?!  How did I not notice that before?  Excellent and amazing - thank you!  Closed my other ticket.  @SunburnedGoose - does this help with your use case?

**Comment by delphiactual** [comment]
@tcurtin, its not @SunburnedGoose use-case, he just moved the issue here from reddit for tracking, he is one of the main devs

**Comment by tcurtin** [comment]
Ah!  In that case I'll quit while I'm ahead and go back to killing things.  :)

**Comment by kshep** [comment]
Whoah. Transfering search results is something I've wanted for-ev-er. Creating a 'loadout' from filter results is neat. I never would've figured that out....

**Comment by tcurtin** [comment]
@kshep - yeah, that's a pretty killer feature I didn't spot either.  DIM is good stuff!

**Comment by HTrig** [comment]
Hi all watching this. I was the one to flag this on Reddit, so thought I'd just clarify the problem for anyone interested. 

Currently loadouts will only transfer armour to a character if the character can equip that armour. Similarly it will only transfer armour equipable by "all" to the vault.

This is also true when transferring via the search field as mentioned by @delphiactual. 

So if none of your junk/infusion fuel is equipable by the character you're on, or you just want to move it to the vault, you get the message "your loadout of 0 items has been transferred to ...", as shown in the attached image, and nothing is transferred.

![image](https://cloud.githubusercontent.com/assets/25123985/21957668/a1ce3040-da93-11e6-8274-86a6c3437187.png)

**Comment by bhollis** [comment]
@HTrig that's a bug we introduced recently while fixing something else, and it's tracked at #1350.

**Comment by HTrig** [comment]
@bhollis yes it is the same problem but it also applies to pre-made loadouts which is this particular thread (#1336), opened before #1350.

**Comment by bhollis** [comment]
That's what I'm suggesting. #1350 is the description of the actual problem.

**Comment by bhollis** [comment]
Fixed in #1382
