### ISSUE TITLE
Loadout Builder uses items in Postmaster

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#1337]
Items in the postmaster will be figured into the calculations for Loadout Builder. 

https://twitter.com/5439Elliott/status/816516782320074752

This player had a bad user experience because the loadout that was created continuously failed to equip.  He couldn't find the item in the Destiny Companion App or Gear Manager.  The issue is they don't show what's in the post master.  So it seemed like a bug.  

Maybe a good solution is to create an error message in Loadouts to notify the user that the item they are trying to equip is in the post master.  This will have the least amount of change to our logic and still allow those 100% items to be used in calculations.

**Comment by kyleshay** [comment]
Closing because it's a minor legacy issue.
