### ISSUE TITLE
Defer Loading of the Manifest File

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#1338]
I would like to be able to load DIM without the penalty of loading the Manifest file from Bungie.  It isn't necessary to load it immediately when the application starts.  

Currently the dimBucketService isn't a service, but a promise that immediately upon registration with angular, will try to resolve the manifest file and return the bucket collection.  This doesn't give us any versatility in being able to defer loading of the manifest file.

**Comment by kyleshay** [comment]
Additionally, on mobile we would want to not download the manifest. We should possibly consider a button click to do so.... or maybe a cancel button. Something that shows they are downloading a couple MB of data.

**Comment by SunburnedGoose** [comment]
When Xur is in town, the shell code to load Xur also tries to load his items.  This causes the manifest file to be loaded.  Need to defer this action too.

Thoughts @bhollis?  Can we push this data back to be hydrated when the user clicks on Xur, or have loaded when the manifest file is available?
