### ISSUE TITLE
Transfer items based on search results

### ISSUE THREAD

**Issue by tcurtin** [DestinyItemManager/DIM#1343]
I'd love to be able to transfer (as many as possible of) the items I've tagged Junk to a character for sharding.  I see that you can search by tag:junk, but can't find any way to transfer en masse.  Something I'm missing?  If not, this would be a great addition - I know people are doing this kind of thing via loadouts, but this feels like a more consistent method.  (And would drive adoption of the tags feature as well.)

**Comment by SunburnedGoose** [comment]
It's a loadout. You can move search results in one of the options in the drop down.

**Comment by tcurtin** [comment]
On second thought, already exists.  (Loadout directly below any saved.)  Closing.
