### ISSUE TITLE
increase icon size on MovePopup

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#1346]
If we could increase the icon size here to account for at least 6 letter words instead of only 5 letter words it would make a world of difference for the translation team.

`STORE`, `EQUIP`, `VAULT`, etc

![itempopup 1](https://cloud.githubusercontent.com/assets/4798491/21751541/19272fba-d586-11e6-92c4-8f2310962055.png)

**Comment by bhollis** [comment]
We could also redesign it to not have the words over the icon. 

-Ben

**Comment by delphiactual** [comment]
Change to icons? I'll look thru fontawesome and see if any make sense for these actions...

**Comment by delphiactual** [comment]
Equip - `hand-grab-o`
Store - `shopping-bag`, `shopping-basket`, or `shopping-cart`
Vault - `bank`
Split - `toggle-up`
Take -  `toggle-down`

**Comment by kyleshay** [comment]
this still an issue?
