### ISSUE TITLE
Could the default item sort do a subsort by item experience?

### ISSUE THREAD

**Issue by rslifka** [DestinyItemManager/DIM#1353]
Currently it's LL, which is a great start. Now I have a vault full of 400s, some I want to hang on to for infusion (with 0xp on them), some I'm keeping (all fully leveled). It would be awesome if DIM listed my 'white bordered' items after the 'yellow bordered' ones :)

DIM is awesome, thank you so much!

**Comment by bhollis** [comment]
Let me file this under #647
