### ISSUE TITLE
Comparison: highlight-on-hover items in your inventory?

### ISSUE THREAD

**Issue by tcurtin** [DestinyItemManager/DIM#1356]
Using and loving the comparison tool as a way of cleaning out inventory.  However, without some kind of highlighting or even icons per compared item I'm having a really hard time finding and moving the items around.  (This is especially true when there's more than one of the item.)

How about: the same light grey that's used to highlight the current stat row on hover, put a bar of that same height across the base of the column you're currently hovering over, and also highlight the item in inventory.  (How to highlight the item?  Good question.  Red border maybe?)

**Comment by kyleshay** [comment]
https://github.com/DestinyItemManager/DIM/pull/1351
