### ISSUE TITLE
Comparison: highlight and/or lock item into view

### ISSUE THREAD

**Issue by tcurtin** [DestinyItemManager/DIM#1357]
Using comparison tool to clean out inventory, and having a lot of trouble keeping an eye on a specific item when there's more than a screen-width of items to compare.  For instance: I want to know how a certain scout rifle compares on all of the stats, but have 20 scouts.  Every time I click a row to sort by its stat, I have to go find that scout again.

If a click locked the item as "highlighted," that would help.  As an addition/alternative, a way to stick one item to the farthest left column of the items would mean it was always visible and make comparison to all the others very easy.

This may dovetail nicely with #1356 .

**Comment by bhollis** [comment]
Both your suggestions are implemented in an open PR (I'm on my phone so I don't have the number). Good thinking!

-Ben

**Comment by kyleshay** [comment]
https://github.com/DestinyItemManager/DIM/pull/1351
