### ISSUE TITLE
Increase the Number of Columns in the Vault

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#136]
Aligning vault types with character types just doesn't look right.  

![image](https://cloud.githubusercontent.com/assets/984608/7682792/30792ecc-fd40-11e4-80d5-44fa6bab81c8.png)
 
I would suggest that we don't line up the types, just the categories.  This will reduce the extra space.

**Comment by kyleshay** [comment]
I think that's a great idea. We could also experiment with giving the vault some more columns

**Comment by SunburnedGoose** [comment]
Yeah.  To keep it at three, we would need 12 item columns :/

A combination of additional columns and letting it float will help.

**Comment by chrisfried** [comment]
I blew up my pull request that did that, but I could put it back together
if you'd like.

**Comment by SunburnedGoose** [comment]
So, what's the new default?  Five?  Six?

**Comment by kyleshay** [comment]
fixed with condensed item view -- can consider iterating on this with our responsive redesign
