### ISSUE TITLE
Beta website CSP policy

### ISSUE THREAD

**Issue by floatingatoll** [DestinyItemManager/DIM#1360]
I evolved this over ~25 iterations using mitmproxy+Proxifier.

```
Content-Security-Policy:
default-src 'none';
script-src 'self' 'unsafe-eval' https://apis.google.com https://www.google-analytics.com/ga.js;
style-src 'self' 'unsafe-inline' https://fonts.googleapis.com/css;
connect-src 'self' https://www.bungie.net;
img-src 'self' https://www.bungie.net;
font-src 'self' https://fonts.gstatic.com;
child-src 'self' https://accounts.google.com; 
```

(This should be unwrapped to a single line when deployed, but I used newlines for readability.)

**Comment by floatingatoll** [comment]
Note that when ```connect-src``` does not include ```'self'```, there's a JS bug that causes a max-CPU retry spin (~1000 retries/sec):

```[Error] Refused to connect to https://beta.destinyitemmanager.com/views/inventory.html because it appears in neither the connect-src directive nor the default-src directive of the Content Security Policy. (x19294)```

**Comment by floatingatoll** [comment]
The ```font-src``` includes both ```'self'``` and Google because apparently it loads two separate fonts, one from each site. In the past I've seen where that's accidental and it's only meant to be loading one font, so mentioning that in case it applies here.

**Comment by floatingatoll** [comment]
For ```child-src``` Google, I wasn't able to test the OAuth workflow more closely, other than to include it to permit the /o/oauth2 query. I assume that's sufficient but obviously more testing would be necessary once y'all implement the relevant UX.

**Comment by floatingatoll** [comment]
This CSP doesn't include img-src: https://bungie.net since #1359 is fixed to load emblems from www.bungie.net instead, but you might need to include that temporarily until edb94fcd356bacec8add9ff6f1528d4b4de450f8 is pushed.

**Comment by bhollis** [comment]
Linking #1483

**Comment by bhollis** [comment]
Deployed.
