### ISSUE TITLE
Settings dialog is one option high on web beta (Safari 10.0.2)

### ISSUE THREAD

**Issue by floatingatoll** [DestinyItemManager/DIM#1362]
It's scrollable and seems to function correctly other than the display issue.

![screen shot 2017-01-14 at 16 27 47](https://cloud.githubusercontent.com/assets/92684/21959264/7a82c19e-da76-11e6-93b4-0fbfdeb312d2.png)

**Comment by bhollis** [comment]
Folding into #1260
