### ISSUE TITLE
Web beta refresh spinner has a weird static white line to its left (Safari 10.0.2)

### ISSUE THREAD

**Issue by floatingatoll** [DestinyItemManager/DIM#1363]
The white line doesn't change color when I mouseover the spinner, which changes from white to orange.

The white line disappears when the spinner reverts to the static "not refreshing" icon.

![screen shot 2017-01-14 at 16 31 08](https://cloud.githubusercontent.com/assets/92684/21959283/055a4184-da77-11e6-861d-45fb50bad924.png)

**Comment by floatingatoll** [comment]
It doesn't seem to reliably present itself, but it's been there *most* times I load the page. It might only present on the first automatic refresh, but not successive ones?

**Comment by bhollis** [comment]
Folding into #1260
