### ISSUE TITLE
Website crashes on first visit in Safari (iOS 10.2, OS X 10.12)

### ISSUE THREAD

**Issue by floatingatoll** [DestinyItemManager/DIM#1367]
On first visit on this device, I get the following screenshot:

![photo_ - 1 40](https://cloud.githubusercontent.com/assets/92684/21959576/4c9f9784-da80-11e6-9310-29bb4fc60675.png)

Subsequent visits to https://beta.destinyitemmanager.com/ correctly direct me to login:

![photo_ - 2 7](https://cloud.githubusercontent.com/assets/92684/21959577/516347ca-da80-11e6-89b2-7c98dff18483.png)

Clearing the past hour of history immediately in mobile Safari deletes whatever cookie was set by the initial error page, permitting the issue to be reproduced.

**Comment by floatingatoll** [comment]
This happened to me on desktop safari, too.

**Comment by bhollis** [comment]
Yup, we're working on it.

**Comment by floatingatoll** [comment]
No worries, just repairing the bug report to be more accurate

**Comment by bhollis** [comment]
Can't repro on Safari iOS or desktop. Must have gotten fixed.
