### ISSUE TITLE
Horizontal scrolling desynced between items and emblems on mobile Safari (iOS 10.2)

### ISSUE THREAD

**Issue by floatingatoll** [DestinyItemManager/DIM#1369]
Scrolling horizontally in portrait lets you reach the vault as expected, but the emblems list and the topbar somehow scroll more slowly, which causes half the searchbar to be truncated as well as the Warlock emblem (and vault is completely unreachable). The desync is less apparent in landscape, but the Vault remains just as unreachable.

![photo_ - 1 41](https://cloud.githubusercontent.com/assets/92684/21959608/13965954-da81-11e6-817d-8bae91c57cd8.png)

![photo_ - 2 8](https://cloud.githubusercontent.com/assets/92684/21959609/17244d74-da81-11e6-9e31-f7c3be6086b8.png)

**Comment by bhollis** [comment]
I can't repro in iPad. Phone is 100% not supported right now.
