### ISSUE TITLE
"Classified" items are listed as class "Titan"

### ISSUE THREAD

**Issue by floatingatoll** [DestinyItemManager/DIM#1373]
I have three instances of a Classified item labeled as "Titan Unknown"; two in Consumables on my hunter and warlock, the other is in General in my vault. It probably isn't proper to say "Titan".

![screen shot 2017-01-14 at 18 25 31](https://cloud.githubusercontent.com/assets/92684/21959775/044b6b78-da87-11e6-84fc-f0f0c370815b.png)

**Comment by delphiactual** [comment]
This is already addressed in #1262

**Comment by floatingatoll** [comment]
Sweet, I'll keep an eye on #1262 for the merge.
