### ISSUE TITLE
Tooltip for weapons packages and subclasses have a blank space prepended

### ISSUE THREAD

**Issue by floatingatoll** [DestinyItemManager/DIM#1377]
I assume because it's emitting item.light + " " + item.name, and since neither the packages nor the subclasses have a light level, it gets an odd extra blank space.

**Comment by floatingatoll** [comment]
There's a few instances of this very suspect ```title="{{vm.item.primStat.value}} {{::vm.item.name}}"``` usage in the code.

**Comment by floatingatoll** [comment]
I think this would fix it, technically:

```diff
-'<div title="{{ vm.item.primStat.value }} {{ vm.item.name }}"
+'<div title="{{ vm.item.primStat.value }}{{ vm.item.primStat.value ? ' ' : '' }}{{ vm.item.name }}"

**Comment by bhollis** [comment]
If we care to fix that, we can do it via a filter or a precomputed property, rather than a complicated watch expression. Not sure it's worth the bother though.
