### ISSUE TITLE
Cryptarch item list sorting appears to be random/unsorted

### ISSUE THREAD

**Issue by floatingatoll** [DestinyItemManager/DIM#1379]
It was odd to me that the blue engrams were interrupted by my account-wide legendary marks. Looks randomized, so I assume it's just unsorted.

<img width="909" alt="screen shot 2017-01-14 at 18 53 21" src="https://cloud.githubusercontent.com/assets/92684/21959907/eb4c52c8-da8a-11e6-8646-b1fbadac785c.png">

**Comment by bhollis** [comment]
What would we sort on? It's just built from the set of currencies required by the items on sale. 

-Ben

**Comment by floatingatoll** [comment]
Dunno. Maybe numeric item ID, or item type ("engram", "marks", etc.), or etc.

It's a bit confusing to see blue engrams listed here, and without those, this would all make a lot more sense unsorted.

Should blue engrams available to be decrypted be hidden from the vendors page under the cryptarch? (This would solve an issue with enabling all three Cryptarchs in #1380, as a useful side effect.)

 - R.

**Comment by bhollis** [comment]
It's weird that cryptarch inventory includes undecrypted engrams. We could special-case filter them out.

**Comment by floatingatoll** [comment]
Yeah, it's trippy. It includes one each of the types of engrams you have on character, which is completely nuts, but makes sense in a twisted sort of way. Like Gunsmith and weapons packages, I guess.
