### ISSUE TITLE
Tower & Reef cryptarch legendary armor/weapons engrams missing from Vendors page

### ISSUE THREAD

**Issue by floatingatoll** [DestinyItemManager/DIM#1380]
Legs should be shown, but I can't find them anywhere on this page. I assume the Iron Temple cryptarch overwrote the Tower and Reef ones? (Both extension and website.)

<img width="313" alt="screen shot 2017-01-14 at 18 58 15" src="https://cloud.githubusercontent.com/assets/92684/21959923/7ae05d58-da8b-11e6-9a5a-012036ef4e44.png">

<img width="862" alt="screen shot 2017-01-14 at 18 58 21" src="https://cloud.githubusercontent.com/assets/92684/21959924/7e632b54-da8b-11e6-914c-62dcb9732977.png">

**Comment by floatingatoll** [comment]
They're intentionally hidden by 79601df543b7bbc412156091d4e42aef35aa4d91 but I wasn't able to discern why from the commit:

```
      // Vendors we don't want to load by default
      const vendorBlackList = [
        2021251983, // Postmaster,
        4269570979, // Cryptarch (Tower)
        1303406887 // Cryptarch (Reef)
      ];
```

And I can't find code anywhere else in DIM that permits showing these vendors to see which engrams they have for sale.

**Comment by delphiactual** [comment]
CC @bhollis

**Comment by bhollis** [comment]
Only the Felwinter cryptarch sells interesting gear. IMO nobody cares about the others. 

-Ben

**Comment by floatingatoll** [comment]
I buy primary legendary engrams every time I hit the requisite marks because I badly want a Jade Rabbit, so not being able to check two of the three Cryptarchs to see if any of them are selling primary forces me over to the official Bungie.net site.

 - R.

**Comment by bhollis** [comment]
Interesting. Is that really the best way to get exotics?

I can add them back in, but I think I'd want to do the blacklisting of useless info we talked about in #1379.

**Comment by floatingatoll** [comment]
Well, it's the only way to spend marks for a chance for a primary exotic that I've found so far! If you can point my mark spending in a more productive direction along that specific path I am *so* there :)

One of my clan mates does the same thing to try for a perfect roll for some hand cannon they like, on the theory that one more roll is one more chance.

**Comment by bhollis** [comment]
Another fun twist - Bungie calls all of those (separate) vendors "Cryptarch" so it's hard to tell them apart.

**Comment by floatingatoll** [comment]
Do they have a social space ID that could be used for bonus location grouping or name tag?

**Comment by bhollis** [comment]
They do, but I hate to have to special-case them, and I'm not sure I should show the location for *every* vendor.

**Comment by floatingatoll** [comment]
There is a theory that says inserting a location heading (tower, reef, temple) amidst the vendors list could be useful, if avoiding special casing is the highest priority goal.

**Comment by bhollis** [comment]
Good point. It'd be a fair amount of work to change how the vendors are displayed though.
