### ISSUE TITLE
Compare Popup i18n

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#1388]
Some stats need to be ellipsed to fit:

![screenshot 2017-01-16 14 04 50](https://cloud.githubusercontent.com/assets/4798491/21999013/27a209a0-dbf5-11e6-8de0-0f0c97ee0b67.png)

![screenshot 2017-01-16 14 05 26](https://cloud.githubusercontent.com/assets/4798491/21999016/2a89e23c-dbf5-11e6-8565-438fee931d95.png)

![screenshot 2017-01-16 14 06 03](https://cloud.githubusercontent.com/assets/4798491/21999018/2d556f40-dbf5-11e6-9972-879dfcba4ffb.png)

**Comment by bhollis** [comment]
Good point! Should be easy.

**Comment by bhollis** [comment]
Fixed in #1402.
