### ISSUE TITLE
Logo doesn't change between beta and prod

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#1390]
We probably have to do something tricky to get the blue logo in DIM beta with Webpack.

**Comment by joshhunt** [comment]
this shouldnt be too tricky. Basically need to use the same approach here https://github.com/DestinyItemManager/DIM/pull/1391#discussion_r96337213 to specify different versions for the webpack config to switch between.

**Comment by delphiactual** [comment]
Fixed by #1481
