### ISSUE TITLE
Beta may be broken by Webpack

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#1392]
Looks like we need to do some work on getting the Beta to build post-Webpack: https://travis-ci.org/DestinyItemManager/DIM/jobs/192595327

I pushed a change (2afda1c742ec17d6781237511460bebc90cb86ea) to no longer try to publish the Beta if Webpack fails, but it looks like we published one bad version.

/cc @SunburnedGoose @joshhunt

**Comment by joshhunt** [comment]
hmmmm lets check this out. curious that resolving an image fails in CI but not locally

**Comment by bhollis** [comment]
I figured it out - Macs use a case-insensitive file system, and it was `armor.png` not `Armor.png`.

**Comment by joshhunt** [comment]
oh man, that's annoying. I swear I've seen a warning in other projects to protect against that...

**Comment by delphiactual** [comment]
api key is not set... @bhollis

**Comment by bhollis** [comment]
Yup I saw that. I'm not sure why it thinks that, since we should still run the replacement for the API key: https://github.com/DestinyItemManager/DIM/blob/dev/Gruntfile.js#L83

My guess is uglify.js is eliminating the code before it gets replaced?

**Comment by bhollis** [comment]
I'm trying a quick hack that should make it skip minification (and get our blue icons back...): https://github.com/DestinyItemManager/DIM/commit/d8bff0945b2827e2c888d57e7c1e7f36e0ac5a31

**Comment by bhollis** [comment]
OK, it isn't uglify. Babel or something else is getting rid of the "constant" comparison.

**Comment by bhollis** [comment]
OK, we at least figured out we can defeat the optimization: https://github.com/DestinyItemManager/DIM/commit/6d081bba80edf8708ba18c9aa632f8e81df66218

Beta appears to be working now. I'm sure we'll find more bugs and regressions, let's just file one issue per.
