### ISSUE TITLE
Inform users when Bungie is under maintenance.

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#1397]
Can we put up a persistent banner under the header notifying the users that Bungie is under maintenance and some features will be unavailable?  This isn't just related to Vendors, but it could be one of the triggers.

![screen shot 2017-01-17 at 1 58 41 pm](https://cloud.githubusercontent.com/assets/984608/22037550/3830207c-dcbd-11e6-92ca-50de6e56b39b.png)

**Comment by bhollis** [comment]
Folding this into #1053
