### ISSUE TITLE
Loadouts do not persist

### ISSUE THREAD

**Issue by brailsmt** [DestinyItemManager/DIM#1400]
I am running Chrome (Version 55.0.2883.95 (64-bit))
on Mac OSX 10.11.6.  I recently upgraded my device from an older Mac.  Ever since the update, I can no longer save loadouts between sessions of DIM.  Once I shut down DIM, I lose the loadouts.  I have to go back into loadout builder, and recreate a loadout every time.  I do not see any permissions errors or options that might be changed to allow DIM to write to my local drive.

**Comment by brailsmt** [comment]
Interestingly, I tried to recreate this tonight with screenshots and all.  I created the loadout.  Quit chrome.  Restarted chrome, and the loadout is there.  I know I have seen this consistently for a few weeks.  I'll see if I can recreate it with screenshots a few more times.

**Comment by SunburnedGoose** [comment]
My guess is DIM updated to v3.16 between those sessions.  There was a fix for loadouts in v3.16.

**Comment by Doopysmallz** [comment]
Chrome Version 55.0.2883.87 m (64-bit)
DIM v3.16.0
Loadouts do not save regardless, after creating a loadout and I save.  I goto main menu of DIM, hit drop down and no loadouts.  No setting changes have occurred so no clue why this is happening.
Thank you.

**Comment by bhollis** [comment]
Are you logged in to Chrome?

**Comment by davidc14** [comment]
I'm seeing issues with loadouts too. I'm unable to save new loadouts from any menus. Perhaps this is related or should I open a new issue?

**Comment by TerraReef** [comment]
My "duplicate" post was closed however I have never had an issue saving loadouts that I am aware of.(although the issue causing this could be related)  2, 4, or even all of the loadouts for a user just disappear including ones that were saved 4-5 months ago and used often.  This has happened to me and other users in Windows 10 and the Google Chrome Version 56.0.2924.87 (64-bit).

**Comment by SunburnedGoose** [comment]
Pushed v3.16.1 which has some logic to resolve some of these issues and better error messages when things go wrong.

**Comment by bhollis** [comment]
I think we've handled this with the recent storage updates.
