### ISSUE TITLE
Move templates to separate files

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#1401]
We've done it for some directives, but not all of them. Let's settle on moving them all out into separate files.

**Comment by SunburnedGoose** [comment]
I'm fine with this move now that we bundle.

**Comment by delphiactual** [comment]
I attempted to do this and am recieving the following error.
```
Error: [$compile:tplrt] Template for directive 'dimStoreBucket' must have exactly one root element. 
```
Current diff is https://github.com/DestinyItemManager/DIM/compare/dev...delphiactual:templates
