### ISSUE TITLE
add filters for weapon perks

### ISSUE THREAD

**Issue by doktor5000** [DestinyItemManager/DIM#1404]
It would be pretty nice to be somehow filter for weapon perks, e.g. show all weapons which have firefly, or high caliber rounds or any particular perk. Although what might be an issue is this would require to list all the weapon perks in the filter dialog, but for a start it would be totally sufficient to be able to filter manually with e.g. `is:firefly`

And keep up the good work, guardians :high_brightness:

**Comment by wein3967** [comment]
You can always just type "firefly" in the search field to highlight weapons with that perk.
![firefly perk](https://cloud.githubusercontent.com/assets/11590326/22083399/9209c57e-dd91-11e6-85ef-e4f5204cbae5.PNG)

**Comment by kyleshay** [comment]
yup, what @wein3967 said.
