### ISSUE TITLE
Vault Sorting sub category

### ISSUE THREAD

**Issue by themacguy2k** [DestinyItemManager/DIM#1405]
Sorry if this have been posted, but I didn't find anything when I searched.

I love looking at the weapons I have in groups sometimes. The new compare feature is awesome, but it would be nice to have an option to sort the vault by weapon types in a sub category after the initial sorting.

Example: Sort by Rarity, then by type. 

This would put all the exotics at the top like it is now and so on, but have all weapon types together in a group (pulse, hand cannon, auto rifle, etc). I sometimes forget that I have other types of weapons bc they get placed in different locations in the vault.

**Comment by 22samurai** [comment]
Yes, please let us sort by weapon type, and then let us sort even deeper for impact, range, rate of fire, etc. so we can look not just at "pulse rifles" but at the "High ROF-archeytpe pulse rifles". This would make vault-sorting and cleaning so much easier!

**Comment by bhollis** [comment]
@22samurai don't forget we have search. It's pretty easy to do "stat:rof:>30 is:pulserifle".

@themacguy2k I'm going to fold this into #647.
