### ISSUE TITLE
Stats Quality Value at 335?

### ISSUE THREAD

**Issue by BlisterAgent** [DestinyItemManager/DIM#1406]
The wiki [page ](https://github.com/DestinyItemManager/DIM/wiki/View-how-good-the-stat-(Int-Dis-Str)-roll-on-your-armor-is) says that the stats quality max value is based on the highest light level of 335. Currently, the max light value is 400. In my profile on DIM, I have stat quality values over 100%. Is this still possible in your calculation or will it be capped at 100% with an updated max light value? Thanks and I really like this add-on to Chrome!
![artifact-stat-quality](https://cloud.githubusercontent.com/assets/6599174/22085885/0d07df7e-dda4-11e6-802a-d80448c83ab4.PNG)

**Comment by SunburnedGoose** [comment]
Updated wiki.  Some artifacts are buggy and can go above the baseline for artifacts.  Those are the best ones.

**Comment by wein3967** [comment]
Pretty sure that 335 reference just wasn't updated to 400. The quality estimates are currently correct regardless. The only time you'll see over 100% is with Intellect/Discipline roll artifacts. For whatever reason, those specific artifacts can achieve higher values than other artifacts.
