### ISSUE TITLE
_gaq missing in beta

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#1407]
https://www.reddit.com/r/DestinyItemManager/comments/5ov5fd/error_loading_destiny_info_gaq_is_not_defined/

HI With Version 3.16.0.700 on multiple versions of Chrome I started getting this error. http://imgur.com/a/L1NGe

![image](https://cloud.githubusercontent.com/assets/984608/22097293/ffaf688c-dde5-11e6-82e5-2a2108ff282e.png)

Tried reloading, reinstalling. Doesn't help. Version 3.16.0 works perfectly. But the beta features are awesome. What can I do to fix this?

**Comment by bhollis** [comment]
This tends to be because somebody 's AdBlock blocks google analytics. We used to handle this gracefully though. 

-Ben

**Comment by bhollis** [comment]
OK, I see what happened. The Google stuff got turned into a module, and thus got wrapped in an IIFE automatically so they're not defined.
