### ISSUE TITLE
Loadout Builder: multiple locked perks not respected in search?

### ISSUE THREAD

**Issue by tcurtin** [DestinyItemManager/DIM#1412]
When building a loadout, I'm allowed to select multiple perks per piece of armor (for instance, I want arms with both Rain Blows and Hand Cannon Loader) but it seems like only one of the perks (consistent not random, but also not alphebetical -- maybe pulled from a hash index?) actually effects the search.

In the example above, I select Hand Cannon Loader and get several 5/5/2 options with Hand Cannon.  Now add Rain Blows, and all the 5/5/2 options I see use a set of Arms that has Rain Blows and Scout Rifle, not Hand Cannon.

**Comment by tcurtin** [comment]
(Should add: currently on beta Version 3.16.0.700, but this isn't a new issue.)

**Comment by delphiactual** [comment]
Did you read the "help" section about and/or selection?

**Comment by tcurtin** [comment]
Aw man - I hate when people don't read the help. And the solution is right
there, of course.

So...  consider this bug due to PEBCAK and "closed"...

Thanks again!
