### ISSUE TITLE
Scrollbar in the Platform Dropdown

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#1415]
Shouldn't be one.  I can scroll a little while inside the dropdown.

![2017-01-22 1](https://cloud.githubusercontent.com/assets/984608/22184924/41061f5c-e0a1-11e6-8de0-f295501b7516.png)

**Comment by delphiactual** [comment]
What about changing it to the Xbox/PS slider that is used on so many other Destiny Websites?

**Comment by bhollis** [comment]
As long as it uses labels instead of just being blue/green!

**Comment by delphiactual** [comment]
From DestinyTailor.com

![platformslider](https://cloud.githubusercontent.com/assets/4798491/23183034/d5ebb99e-f837-11e6-82be-393c3f8e6e87.gif)

**Comment by bhollis** [comment]
Fixed this with the new accounts selector.
