### ISSUE TITLE
Multiple views for i18n

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#1422]
We're creating multiple files for each view to support our languages.  We have infrastructure now to add translation tags to the views, so why the duplication of files and extra effort on the developer to update?  Any change we make to the view has to be added to the other files, and atm we have 7 files.  This is a great way to let human error creep into DIM as there is a likelihood that the developer will not verify the change across all languages.

Would it be better to have the text translated (which it has to be done regardless), and let the developer code once, and have confidence their view will render correctly?

**Comment by delphiactual** [comment]
@SunburnedGoose @bhollis This was discussed prior to making individual templates here: #1107

**Comment by SunburnedGoose** [comment]
Another consideration is when we bring the CSS/HTML closer to the components, this pattern will have us making multiple files for the component template if there are translations.

ex., checkout the PlatformChoice component in my branch for example and see how I'm adding the HTML/CSS/JS together.

https://github.com/DestinyItemManager/DIM/tree/bungie-auth-dev/src/scripts/shell

**Comment by bhollis** [comment]
Just to be clear, we're not using this for component or directive templates. Just the big, text-heavy templates like the "About" and "Support" pages, which have minimal formatting, don't change often, and have lot of text to translate together.

That said, feel free to change it around any way you like, as long as the translation stays easy.
