### ISSUE TITLE
featureflag.importExport not available on 'Beta'

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#1425]
According to the code it should be there, but alas it is hiding...

**Comment by bhollis** [comment]
Do you have a stack trace? What do you mean it's not available?

**Comment by delphiactual** [comment]
@bhollis it is missing from `Settings`
![screenshot 2017-01-25 01 45 04](https://cloud.githubusercontent.com/assets/4798491/22283514/f2655542-e29f-11e6-9413-a9f7cac119b4.png)

**Comment by bhollis** [comment]
That probably had more to do with the fact that building the beta extension has been broken so we hadn't shipped a new one for a while. 

-Ben
