### ISSUE TITLE
Beta - no joy on my iPad 2 or phone

### ISSUE THREAD

**Issue by edmiller47** [DestinyItemManager/DIM#1429]
I've been looking forward to this since you first announced it!
This morning I logged into bungie.net on my iPad 2 and then pointed my browser (Safari) to https://beta.destinyitemmanager.com.

This is all that was displayed:

![img_0101](https://cloud.githubusercontent.com/assets/13838005/22333025/df08a08c-e3a1-11e6-985a-6dd8284df503.PNG)

Same result from Chrome on the iPad. Attempted both several times with no luck. Same from my phone.
The icons along the menu bar are unresponsive.

Beta works fine from Chrome on my laptop.

Am I doing something wrong?

**Comment by SunburnedGoose** [comment]
What version of iOS?

**Comment by edmiller47** [comment]
9.3.5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Rick CaseySent: Thursday, January 26, 2017 8:46 AMTo: DestinyItemManager/DIMReply To: DestinyItemManager/DIMCc: edmiller47; AuthorSubject: Re: [DestinyItemManager/DIM] Beta - no joy on my iPad 2 or phone (#1429)What version of iOS?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/DestinyItemManager/DIM","title":"DestinyItemManager/DIM","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/DestinyItemManager/DIM"}},"updates":{"snippets":[{"icon":"PERSON","message":"@SunburnedGoose in #1429: What version of iOS?"}],"action":{"name":"View Issue","url":"https://github.com/DestinyItemManager/DIM/issues/1429#issuecomment-275391428"}}}

**Comment by SunburnedGoose** [comment]
iOS 10 is required right now. Let me see if that could be relaxed, but it depends on features available in Safari on iOS. We have been using the latest features to give you the best experience, but it is not very backwards compatable.

**Comment by edmiller47** [comment]
OK. iPad 2 can't go to iOS 10 so it looks like I may be SOL.

**Comment by SunburnedGoose** [comment]
I am on the bubble myself with my gen 2 iPad mini.

**Comment by SunburnedGoose** [comment]
Whoops. Didn't mean to close it.

**Comment by shockthealien** [comment]
Im having the same issue in my iPhone 7+ and I have iOS 10.2.1

**Comment by bhollis** [comment]
See #1508.
