### ISSUE TITLE
Light & Dropdown Icons Broken

### ISSUE THREAD

**Issue by m-s-y** [DestinyItemManager/DIM#143]
Seems to have broken with the 3.0.5 or .6 update.

The icon for "light" now shoes up as a boxed-in airplane, and the down-carat shows as a double-diamond in a box.  Screenshot attached.

43.0.2357.65 (64-bit) on  Mac OS 10.10.3.

![2015-05-20_12-51-34](https://cloud.githubusercontent.com/assets/6401354/7731548/321567c2-feef-11e4-8c82-a0f3cc47931b.png)

**Comment by SunburnedGoose** [comment]
Are these still broken for you?

**Comment by m-s-y** [comment]
Yes, still broken in 3.0.7.2.  :-(

**Comment by SunburnedGoose** [comment]
Are you downloading open-sans?  Can you press F12 and see if it is in the network tab?

**Comment by SunburnedGoose** [comment]
Clear your cache?

**Comment by m-s-y** [comment]
Negative.  Though I've had issues lately with various _non_ google-analytics.com assets being blocked as if they were from GA by my content filtering.  Doesn't seem to be the case here.

>Request URL:http://fonts.googleapis.com/css?family=Open+Sans
>Request Method:GET
>__Status Code:307 Redirect__
>Response Headers
>Location:https://fonts.googleapis.com/css?family=Open+Sans

**Comment by SunburnedGoose** [comment]
What's the redirect to?  I get 200 OK here.

**Comment by SunburnedGoose** [comment]
Do you have some sort of https redirect w/ google?

**Comment by m-s-y** [comment]
Not locally - this happens on one of my other machines, too.  I need to investigate where that redirect is coming from.  If I hit the url directly, (http://fonts.googleapis.com/css?family=Open+Sans) it does not redirect.  Seems to only happen in the context of the DIM extension.  

Will check in to this in the next day or so and report findings.

**Comment by SunburnedGoose** [comment]
Do you want to have a Google Hangout so I can see the network traffic in Chrome while using it?

**Comment by kyleshay** [comment]
closing for now, as it appears to be functioning as expected in v3.0.17
