### ISSUE TITLE
Switch platforms if there are no characters.

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#1431]
If an account has multiple platforms, and the initial platform does not have characters, swap platforms.  Users get caught up in this thinking DIM isn't working but they havn't learned how to switch platforms.

**Comment by bhollis** [comment]
Agreed. I've looked at it before because this tends to annoy me on a fresh profile, but it wasn't super easy to fix then. Hopefully with the new code it'd be easier.

This may be considered a dup of #329.

**Comment by delphiactual** [comment]
#1721 Item 4
