### ISSUE TITLE
Kanji character for U in Xur's name

### ISSUE THREAD

**Issue by philipmat** [DestinyItemManager/DIM#1432]
Safari 10.0.3 on OS X 10.11.6 El Capitan

![screen shot 2017-01-27 at 11 59 22 am](https://cloud.githubusercontent.com/assets/709928/22381723/5bdfbb4a-e488-11e6-9841-c63e5f775e7f.png)

**Comment by delphiactual** [comment]
Open the Xûr tab and is it also messed up there?
Are you using an adblocker on the extension, if so whitelist DIM. we do not have any ads anyway, but you are possibly blocking the font from downloading correctly.

**Comment by philipmat** [comment]
It is correct in the dialog.
![screen shot 2017-01-27 at 12 36 47 pm](https://cloud.githubusercontent.com/assets/709928/22382945/60d20806-e48d-11e6-80ce-2ce1bd9b35a5.png)

I have beta.destinyitemmanager.com whitelisted in uBlock.

**Comment by SunburnedGoose** [comment]
![2017-02-07 7](https://cloud.githubusercontent.com/assets/984608/22723385/79df55fc-ed83-11e6-855a-db0ce38239a2.png)

**Comment by BinarMorker** [comment]
I noticed it does this for every accents in other languages too. Seems to be a problem with font encoding.

**Comment by delphiactual** [comment]
`<meta charset="utf-8">` is missing from the head of the website

**Comment by bhollis** [comment]
Should be fixed now. Reload?

**Comment by delphiactual** [comment]
Verified working with accented characters
