### ISSUE TITLE
DIM permits Armsday packages to be dragged to the equip slot

### ISSUE THREAD

**Issue by floatingatoll** [DestinyItemManager/DIM#1433]
DIM probably shouldn't let Armsday packages be dropped on the equip slot. If you drag an armsday package to the equip slot, "This can only be equipped on characters at or above level 0" appears. My character is level 40.

**Comment by floatingatoll** [comment]
(3.16.0 extension, not able to test on website at this time.)

**Comment by bhollis** [comment]
This is likely a data issue - Bungie isn't setting the information we use to determine whether an item can be transferred or not. As usual, we could specifically code around these problems, but that is difficult to maintain as the data changes.

I'll look specifically at some Armsday packages to see whether there's anything else we can be looking at to try and determine that they aren't movable.

**Comment by floatingatoll** [comment]
When you click on a weapon, it shows a list of "transfer" and "equip"
buttons at the bottom. That list of buttons is not shown for Armsday
packages, indicating that y'all already realized (somehow) that they can't
be transferred or equipped. I ask only that the same consideration be
applied to the drag-and-drop target.

**Comment by bhollis** [comment]
OK. If that's the case then the code for determining draggability is more broadly broken, not just for armsday items.

**Comment by bhollis** [comment]
Fixed in #1512
