### ISSUE TITLE
Item Leveling loadout should offer to move consumables that help with leveling

### ISSUE THREAD

**Issue by floatingatoll** [DestinyItemManager/DIM#1434]
I store my synths in the vault because there's a billion of them, but item leveling - while helpfully grabbing 9 items to level - did not offer to bring in any synths as well.

**Comment by bhollis** [comment]
I'm a bit confused - what is "item leveling" referring to exactly?

**Comment by floatingatoll** [comment]
<img width="488" alt="screen shot 2017-01-28 at 14 34 02" src="https://cloud.githubusercontent.com/assets/92684/22400346/02bc0a5c-e567-11e6-9524-3283d263e754.png">

**Comment by bhollis** [comment]
Ah, the auto-loadout. OK, so you're suggesting that, in addition to choosing items to level, this automatically bring in other items (consumables) that could help with that leveling (synths, motes of light, etc). 

It's an interesting idea. I wonder if people would be surprised to see these moved for them as part of this loadout.

**Comment by bhollis** [comment]
To expand on my earlier statement, I'd predict some people will get upset because we moved their consumables, and they will demand a variant of this loadout that doesn't do that.

**Comment by floatingatoll** [comment]
Currently it offers a pop up that says "our loadout of 8 items has been equipped". That pop up could have a button that transfers any consumables that are both relevant and absent.

**Comment by floatingatoll** [comment]
To clarify: I think it should *offer* to get relevant items, not just do so automatically.

**Comment by bhollis** [comment]
OK, I understand the idea. We don't really have a UI affordance to make that offer right now, and it'd require some extra design work and infrastructure. While I think it's a neat idea, I don't think it's something we'd work on anytime soon. If somebody wants to submit a PR, that'd be cool, but I'd rather not keep this issue open.
