### ISSUE TITLE
Configure API Key - 3.16.0.717 (beta)

### ISSUE THREAD

**Issue by randalla0622** [DestinyItemManager/DIM#1436]
Version: 3.16.0.717 (beta)

When loading DIM, it's giving me the developer API key page:

Developer Settings

Configure API Key

1. Visit https://www.bungie.net/en/Application/Create
2. Paste [chrome-extension://mkiipknpfaacbjdagdeppdacpgpdjklc] into the "Origin Header" section under "Browser Based Apps".
3. After saving, copy the "API Key" here 
4. Copy the "Authorization URL" here 
5. Save

**Comment by wein3967** [comment]
I am seeing this as well on the beta version
![dim beta response](https://cloud.githubusercontent.com/assets/11590326/22401166/d38b106a-e58f-11e6-8fa1-b7aa3cd04860.PNG)

**Comment by SunburnedGoose** [comment]
We're making some big changes to DIM atm, so expect some chop.

**Comment by rkingsla** [comment]
Fasten your seatbelts.... You're on DIM Airlines. :)

**Comment by SunburnedGoose** [comment]
@bhollis or @kyleshay might know more about the handoff of the build to travis and how we populate the keys.

**Comment by delphiactual** [comment]
@bhollis the variable replacement from DefinePlugin is replacing everything with an empty string currently... 

![screenshot 2017-01-29 16 32 20](https://cloud.githubusercontent.com/assets/4798491/22409026/887c686a-e640-11e6-9a6c-6d5697e2d48b.png)

**Comment by kyleshay** [comment]
https://github.com/DestinyItemManager/DIM/pull/1452/files#diff-215a1699ecae64ba19bb8438a1b125ef
