### ISSUE TITLE
Update uiRouter to v1

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#1439]
The uiRouter team has produced a new router that is optimized for Angular 1.5+, and Angular 2.  The features are 1:1 between the two so our work here will move forward.

New features of the router are lazy loading of components that are in child modules of the application.  This will let us create a PWA that lazy loads the views so we can have a quickly loading shell.

**Comment by SunburnedGoose** [comment]
On Windows, you'll need to be able to build uiRouter when installing the package.  You'll need to have installed Python 2.7, MS Build Tools 2015, and Visual C++ 2015 Build Tools w/ Windows 8.1 SDK.

1. Install Python.
2. Add Python folder to path so python.exe is available.
3. Add 'PYTHON' environment variable to path that contains python.exe.
4. Install MS Build Tools 2015.
5. Install Visual C++ Build Tools 2015 w/ Windows 8.1 SDK.

You might need to install 'node-gyp' package, and set node to use MSVS 2015.

npm config set msvs_version 2015 --global

That Windows lifestyle...

**Comment by Mulchman** [comment]
Seriously?

**Comment by SunburnedGoose** [comment]
Building C++ libraries on Windows isn't simple.

**Comment by delphiactual** [comment]
`npm install windows-build-tools`

**Comment by SunburnedGoose** [comment]
Thanks for that @delphiactual.  I'll update the readme.

**Comment by bhollis** [comment]
Closing in favor of #1442.
