### ISSUE TITLE
vendor filters are highlighting incorrectly

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#1445]
In the vendor screen, set the filter to:
is:intellect is:strength is:gauntlets

Some of the faction gear is "half-highlighted" when it shouldn't be.

![image](https://cloud.githubusercontent.com/assets/25425159/22411884/7b8a2454-e6f8-11e6-896a-a3ab15d05b68.png)

**Comment by delphiactual** [comment]
That gear isn't "half-highlight" it is available for you to purchase, hence the white border.
