### ISSUE TITLE
Weekly Activity

### ISSUE THREAD

**Issue by tda0909** [DestinyItemManager/DIM#145]
How about a weekly activity mouseover or dropdown?  Quick example below thrown together in paint.  Something that would be convenient, but not always shown. 

![quick example](https://cloud.githubusercontent.com/assets/5675919/7752270/859684fe-ffac-11e4-9284-d0d46c048912.png)

**Comment by SunburnedGoose** [comment]
I like the idea, but it is outside the scope of an item manager atm.  There is no bandwidth for this feature.

**Comment by LongLiveCHIEF** [comment]
@SunburnedGoose I'll work on a PR for this if you're up for it. I agree it's not in scope, but I'd hate to make a second extension.

**Comment by tda0909** [comment]
@LongLiveCHIEF I was considering trying to.  But html & chrome are outside my programming knowledge.  just wanted a reason to remove destinystatus from my bookmarks bar.

**Comment by SunburnedGoose** [comment]
Building a PR is fine.  Just work with us upfront on your design and show me your repo where you're working.  I wouldn't want you to build something and then have to rework it to make it fit.

Thanks for helping out.

**Comment by MattWhilden** [comment]
From a broader level, is the goal of DIM to replace all my other bookmarks and become a one stop shop?

**Comment by DrewScoggins** [comment]
I have to agree with @MattWhilden  on this.  It seems like something like this is outside the scope of what DIM is.  I much prefer having a suite of tools that all do their job extremely well rather then clunky tool that tries to be everything to everyone.  Just my .02

**Comment by SunburnedGoose** [comment]
The DIM team is focused on Item Management and related activities.  Now what's a related activity?

* Finding out what weekly activities you can do to get new items
* Status of daily bounties for XP dumps
* Creating dynamic loadouts (based on attributes) to help guardians dump XP into gear easily
* Sharing Loadouts/Public Loadouts
* Gear Collections
* Gear Comparison Features
* Farming Mode that takes of snapshot of your current Guardian, and moves anything else off the character to keep them light.  "No Green Left Behind" Mode :)

Just a few ideas for what we can add to DIM.  I don't think this is taking over Destiny Public Events,

**Comment by kyleshay** [comment]
if there is a nice way to fit if in the tool without it being obtrusive then i'd say go for it. i'd always like for items to be forefront, but if we can sneak a menu option somewhere that's totally cool. (similar to how the loadouts dropdown work- unobtrusive, but easily accessible.) 

if you do go this route, before commiting to all of the work, pass around some mockups on what you're thinking. we can iterate on them and then get them implemented!

otherwise, feel free to get the code done just don't expose it anywhere, and we can work on the view toward the end.

**Comment by bhollis** [comment]
IMO Bungie.net handles this info just fine. Post-TTK, do we still want to do this?

**Comment by Mulchman** [comment]
destinystatus.com and destinchecklist.net do a terrific job tracking this
stuff as well...

**Comment by SunburnedGoose** [comment]
Move it to v4.

**Comment by kyleshay** [comment]
linking: #254 since they use the same API call and return the same data. don't need to be implemented at the same time, but code will be heavily shared.

**Comment by SunburnedGoose** [comment]
Should work closely with DSR on this.

**Comment by tda0909** [comment]
I didn't really expect this to be revived, however my raid group will be extremely pleased to see this added.  I just wish I had the programming experience to help.  Btw guys, great job on where DIM has went from conception, we recommend DIM to everyone now, keep up the good work :)

**Comment by kyleshay** [comment]
Closing in favor of #1886

**Comment by kyleshay** [comment]
@tda0909 let us know what you think! :)

**Comment by tda0909** [comment]
I think that I've needed this in my life for years ;)  it's perfect, and should work well for destiny 2...  Plus it looks much better than my paint mockup from a couple years ago :)

Good work guys, I'm really glad to see this finally come to fruition, keep up the amazing work.

**Comment by kyleshay** [comment]
ha :D thanks for the feedback, agreed it will be useful for D2!!
