### ISSUE TITLE
An active filter affects vendor view

### ISSUE THREAD

**Issue by bradchoate** [DestinyItemManager/DIM#1454]
Looks like the search bar has been removed from the latest build for the vendors view, but if you had a search active on your inventory, then click to view vendors, the vendor items that don't match the search are all dimmed.

Having the option to filter the vendors view is nice. I typically used that for searching to highlight high-quality armor pieces ("quality:>97"). So presently, this bug still allows me to do that. I hope the search field is restored instead of disabling filter support for vendors altogether.

**Comment by bhollis** [comment]
Should still have a search bar. If it doesn't that's a bug. 

-Ben

**Comment by bradchoate** [comment]
According to Chrome, the version installed is 3.16.0.725 (another issue I noted here is the "About" dialog shows "Version ()" as the version). There's no search bar when I view vendors. Instead, it looks like this:

<img width="927" alt="screen shot 2017-02-01 at 5 02 58 pm" src="https://cloud.githubusercontent.com/assets/22245/22533038/62109158-e8a0-11e6-8582-195bdf208f10.png">

I've scrolled the content a little bit to show that the "Back to DIM" link is seen scrolling above and behind the "Vendors" nav bar which is sticky on the page. Of all things, "Back to DIM" is one link I'd like to stay at the top so I can easily exit this view.

**Comment by delphiactual** [comment]
Search bar has returned
