### ISSUE TITLE
Loadout Builder "Process Possibilities" button

### ISSUE THREAD

**Issue by bakaboy182** [DestinyItemManager/DIM#1461]
Greeting DIM dev team,

I just wanted to make a suggestion for Loadout Builder. 
Is it possible to change perk selection and loading process for the build possibilities? DIM processes the possibilities one perk at the time now. Instead, could we have an option to choose perks and then click "Process Possibilities" button of some sort so it won't process the possibilities in the middle of choosing multiple perks. It's working perfectly fine but I thought it'd make things a little bit easier and save a little bit of time. 

Thank you always for a great work!!

**Comment by bhollis** [comment]
@bakaboy182 I recently made loadout builder faster - do you think this is still needed?

**Comment by bakaboy182** [comment]
Hi Ben,

It feels a lot faster now that you mentioned it. Thank you for getting back
to me.
I have another thing that I thought about mentioning. Weapon rating is roll
specific, right?
I was wondering if people know that it's weapon specific when I was reading
some of the reviews.
It might be beneficial to add a line to the review section saying it's roll
specific to get more meaningful review specific to the gun rather than
talking about one gun in general.

Thank you for the great work guys!!

**Comment by bhollis** [comment]
Thanks! We've actually just added that - it'll be in the next release.

If you don't mind, I'll close this out and just focus on making sure the loadout calculation is fast and/or non-blocking.

**Comment by bakaboy182** [comment]
That'll be just fine!! Thank you again.
