### ISSUE TITLE
Eidolon Ally tooltip is poorly styled

### ISSUE THREAD

**Issue by jbccollins** [DestinyItemManager/DIM#1467]
I think this screenshot should be enough to explain the issue.
<img width="346" alt="screen shot 2017-02-09 at 8 24 55 pm" src="https://cloud.githubusercontent.com/assets/8915552/22810308/f2b04526-ef05-11e6-96ca-6a3b87d737a4.png">

**Comment by kyleshay** [comment]
Thanks, looks like this is a duplicate of #1455

**Comment by jbccollins** [comment]
@kyleshay ok cool.
