### ISSUE TITLE
build-dev and build-release minimize differently?

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#1473]
So I diagnosed the issue with #1453 today.  During development with `npm run build-dev`, the code worked fine.  When I ran it with `npm run build-release`, the feature failed.

I was under the assumption that we were doing a minification step in build-dev.  If we are, then there is a difference between dev and release.  If we are not minimizing, then we really need to be sure that we are testing our features using the release build before signing off that it's done, OR we need to add minification to the build.

**Comment by bhollis** [comment]
We do not minify in dev. Agreed that we probably should, if it's not too slow. Now that the source maps are fixed it should be less painful to develop while minified.

**Comment by bhollis** [comment]
Closing in favor of #1587.
