### ISSUE TITLE
3.16.1 Partial Stacks Not Transferring 

### ISSUE THREAD

**Issue by jrmitchell72** [DestinyItemManager/DIM#1474]
Chrome Version 56.0.2924.87 (64-bit)

Trying to transfer any type of partial stack causes DIM to freeze. The "Refresh Destiny Data" symbol spins, but nothing happens. I have to F5 to use DIM again. This issue happens while trying to transfer partial stacks from the vault to any character and vise versa. It appears that this is caused when "hold shift or pause..." pop-up turns green. Once the pop-up turns green, DIM will freeze. The "How many..." pop-up never appears.

I did delete 3.16.1 and the issue remains. I also tested this in the DIM Beta 3.16.1.737 and partial stacks work as intended.

**Comment by SunburnedGoose** [comment]
I did the partial transfers through the move popup when you single click. This is erroring when you drag and you use the popup dialog at the bottom?

**Comment by jrmitchell72** [comment]
Single click and drag and holding shift both cause DIM to freeze.

**Comment by SunburnedGoose** [comment]
I guess it's fixed :)

**Comment by jrmitchell72** [comment]
Yes! I was worried that it was on my end...like last time!
