### ISSUE TITLE
ChromeOS cannot save loadout v3.16.2

### ISSUE THREAD

**Issue by Xilgorn** [DestinyItemManager/DIM#1476]
When trying to save any loadout, ChromeOS responds with
Error saving loadout
Unable to save loadout undefined:
Cannot read property 'items' of undefined

Chrome cache emptied and valid save name provided
![image](https://cloud.githubusercontent.com/assets/25797076/22980029/3ca6790c-f366-11e6-8ff9-090dbd824741.png)

**Comment by bhollis** [comment]
Could you open the developer tools and see if it has any more info?

**Comment by Xilgorn** [comment]
Hi

I just tried to save a loadout again and here is the "dev dump"
Hope this helps

TypeError: Cannot read property 'items' of undefined
    at
chrome-extension://apghicjnekejhfancbkahkhdckhdagna/main-de4007.js:26:15934
    at Function.k.each.k.forEach
(chrome-extension://apghicjnekejhfancbkahkhdckhdagna/main-de4007.js:2:21181)
    at m
(chrome-extension://apghicjnekejhfancbkahkhdckhdagna/main-de4007.js:26:15911)
    at
chrome-extension://apghicjnekejhfancbkahkhdckhdagna/main-de4007.js:26:16641
    at u
(chrome-extension://apghicjnekejhfancbkahkhdckhdagna/main-de4007.js:11:3852)
    at
chrome-extension://apghicjnekejhfancbkahkhdckhdagna/main-de4007.js:11:4274
    at p.$eval
(chrome-extension://apghicjnekejhfancbkahkhdckhdagna/main-de4007.js:11:11429)
    at p.$digest
(chrome-extension://apghicjnekejhfancbkahkhdckhdagna/main-de4007.js:11:9902)
    at p.$apply
(chrome-extension://apghicjnekejhfancbkahkhdckhdagna/main-de4007.js:11:11712)
    at u
(chrome-extension://apghicjnekejhfancbkahkhdckhdagna/main-de4007.js:10:19417)
Possibly unhandled rejection: {}
(anonymous) @ main-de4007.js:10
main-de4007.js:23 TypeError: Cannot read property 'items' of undefined
    at main-de4007.js:26
    at Function.k.each.k.forEach (main-de4007.js:2)
    at m (main-de4007.js:26)
    at main-de4007.js:26
    at u (main-de4007.js:11)
    at main-de4007.js:11
    at p.$eval (main-de4007.js:11)
    at p.$digest (main-de4007.js:11)
    at t.$apply (main-de4007.js:11)
    at HTMLButtonElement.<anonymous> (main-de4007.js:13)
(anonymous) @ main-de4007.js:23

**Comment by bhollis** [comment]
Could you give the beta a try and see if it's any better?

**Comment by Xilgorn** [comment]
Sure, do you have a link to the beta?

**Comment by Xilgorn** [comment]
Hi

Loadouts can be created per character and for "any" character
No problem modifying the loadouts.

Regards
Xil

**Comment by bhollis** [comment]
Awesome! I wonder what the problem was, but I'm glad it's fixed. We'll probably do an extension release pretty soon.
