### ISSUE TITLE
Weapon analysis for preferred combinations

### ISSUE THREAD

**Issue by rkingsla** [DestinyItemManager/DIM#1486]
Granted, this could end up being subjective to a greater degree, and a given person's play style might dictate what is a better perk over another., but there are certain combinations that define if one should shard or keep a given weapon. For example, it's well-known that an Imago Loop with Outlaw, Explosive Rounds and Firefly is the 'god roll'. And, a Grasp of Malok with Counterbalance, Braced Frame / Smallbore / Perfect Balance is considered a 'god roll'.

While armor stats are a lot easier to determine 'quality', what would it take to analyze a weapon and determine if you might consider keeping or sharding it?

As a general reference, The Reddit community "Shard it or Keep It" forum posted this: https://www.reddit.com/r/sharditkeepit/comments/5nklsw/pve_god_roll_quick_reference_guide/

It's a start. And weapon balances like the patch last week (2.14.17) may adjust some perks over others. But, IMHO, it would be an exception over a sweeping change. Possible implementation might be more like armor analysis for T12, but for preferred weapon perks and combinations. Additionally, commentary on the perk or a link to information might explain the good and bad of a perk like "Secret Round".

Thoughts?

**Comment by delphiactual** [comment]
Linking to #515 and closing
