### ISSUE TITLE
locked status filters inconsistent with engrams

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#1489]
There are 2 different ways of looking at the lock status of engrams and they are inconsistent.

is:unlocked - shows weapon engrams as unlocked, but armour engrams as locked
is:locked - shows weapon engrams as unlocked, and armour engrams as unlocked

The error is with the is:unlocked filter for amour engrams, they should not be shown as locked.

![image](https://cloud.githubusercontent.com/assets/25425159/23192561/09b62e64-f8f4-11e6-98ee-26f5a553f4e9.png)

**Comment by delphiactual** [comment]
This is because ingame weapon engrams are lockable and armor engrams are not.

**Comment by philkernick** [comment]
But it doesn't explain why the is:unlocked and is:locked filters show a different result.
In my example, the helmet engram is unlocked, but not shown that way.

**Comment by delphiactual** [comment]
it doesnt have the ability to be locked does mean its unlocked look at other items like `Black Wax Idol`

**Comment by philkernick** [comment]
I'm confused that is:unlocked and not:locked do not show the same thing.  They are semantically and logically identical.

**Comment by delphiactual** [comment]
Currently if something is not lockable we do not show it as unlocked.

**Comment by philkernick** [comment]
I understand.  Can this please be added as a feature request.

**Comment by delphiactual** [comment]
@philkernick I was working through logic while responding to your comments
