### ISSUE TITLE
Better experience for users without bound gamertag or PSNID

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#1492]
User tried to use DIM today and didn't have a bound gamertag or PSNID.  Here's the thread on twitter that shows the images from the console for the errors, and the badly broken UX.

https://twitter.com/abulletaway/status/834419513630134272

**Comment by bhollis** [comment]
I think we do show popups, but they were also hitting the problem with Firefox not working.

**Comment by bhollis** [comment]
Closing since I think we do show appropriate errors.
