### ISSUE TITLE
Xur is missing item quality

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#1500]
Xur is missing a parent classname to turn on the item quality for the armor.

$('body').addClass('itemQuality');

![2017-02-24](https://cloud.githubusercontent.com/assets/984608/23316383/c2cad2fa-fa8f-11e6-81e2-697ebec2095e.png)

**Comment by bhollis** [comment]
I think a recent change moved the "settings" styles from the `body` tag to a div just inside it, but those styles really need to be on `body` for things to work in popups.

**Comment by bhollis** [comment]
Fix/further discussion in #1503.
