### ISSUE TITLE
Allow items to be marked for Infusion

### ISSUE THREAD

**Issue by djspinmonkey** [DestinyItemManager/DIM#1507]
It would be great if there were some way to denote that an item was only being kept for infusion purposes. Being able to, say, fetch a single piece of infusion fodder of a particular type would also be nice.

**Comment by wein3967** [comment]
If you are using the beta version of DIM, there is some limited tagging ability as well as custom notes. Both of which are searchable from the search/filter menu.
![dim tagging](https://cloud.githubusercontent.com/assets/11590326/23335937/f3f58496-fb85-11e6-9104-b6d2767cdc91.PNG)

**Comment by bhollis** [comment]
Yup! We'll probably release this to the non-beta extension soon (#1509).

**Comment by djspinmonkey** [comment]
Oooh, nice! Thanks for the response, and also for being awesome!
