### ISSUE TITLE
Vendors page compare doesn't show roll of already owned item

### ISSUE THREAD

**Issue by shockthealien** [DestinyItemManager/DIM#1517]
As title says, in the Vendors page, when you click on an item and you already have at least one copy already, the pop up has stopped showing the % quality of the roll you already have

![screen shot 2017-02-28 at 15 40 32](https://cloud.githubusercontent.com/assets/2083273/23412220/cf764800-fdcc-11e6-869f-24b843817b1b.png)

**Comment by bhollis** [comment]
This is the same issue that killed stats on Xur items. I've got a fix in PR but I need to figure out how to square it with some upcoming refactoring. 

-Ben
