### ISSUE TITLE
Unable to transfer an un-attuned artifact

### ISSUE THREAD

**Issue by irfanhabib** [DestinyItemManager/DIM#1519]
![image](https://cloud.githubusercontent.com/assets/18684569/23560693/3c76f306-0033-11e7-98f9-add749f339ef.png)

I'm unable to transfer an unattuned artifact to my character. I'm not trying to equip it. 

To resolve this, had to switch character, put the artifact in the vault, and switch back and attune it.

**Comment by delphiactual** [comment]
This does not happen anymore see screen grabs
![unattuned](https://cloud.githubusercontent.com/assets/4798491/24325961/a39a7f84-1169-11e7-9db5-ac603c56294d.gif)
