### ISSUE TITLE
Display extension version

### ISSUE THREAD

**Issue by benwa** [DestinyItemManager/DIM#152]
The `title` attribute of the extension title could display the exact extension version.

Programmatically, it can be obtained with:
`chrome.app.getDetails().version`
![screen shot 2015-05-27 at 6 07 00 pm](https://cloud.githubusercontent.com/assets/1351571/7848595/390331a2-049b-11e5-8703-9a740f690507.png)

**Comment by SunburnedGoose** [comment]
It is available in the about box.

**Comment by kyleshay** [comment]
What goose said- 

we may be moving the version in an upcoming release regardless
