### ISSUE TITLE
Do not see Labels & Notes in Release, only Beta

### ISSUE THREAD

**Issue by m-s-y** [DestinyItemManager/DIM#1521]
Version 3.16.2.795 (beta), I see the UI for labels & notes.  After grabbing the official latest from the Chrome store, I do not see the UI for labels & notes, and when I check About DIM, I see this for version:  "Version ()"

Tried clearing the saved settings from the release version, reinstalled, same thing.

At a loss and on a Mac, Chrome Version 56.0.2924.87 (64-bit)

**Comment by bhollis** [comment]
That's because tags and notes haven't been released. They're only in the beta so far. 

-Ben

**Comment by m-s-y** [comment]
Got it.  I was confused bc the pop-up on the latest 3.16.2 said "Changed the location we use to store tags and notes" and I thought I missed something.
