### ISSUE TITLE
Compare on Vendor page no longer shows item stat quality

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#1525]
In the last few releases there has been a change where comparing an item to what you already have on the Vendor page no longer shows the item stat quality.  It definitely used to.

Here's an example:
![image](https://cloud.githubusercontent.com/assets/25425159/23781742/4da18dc8-059f-11e7-913b-aa0b7aa477ff.png)

The one for sale is a 100% of max roll, but the one in my inventory is 104%, and I can't tell that without going back out of the vendor page.

![image](https://cloud.githubusercontent.com/assets/25425159/23781781/944f3388-059f-11e7-9bc1-35513b22c419.png)

**Comment by delphiactual** [comment]
Already fixed in the beta...

![screenshot 2017-03-09 21 20 02](https://cloud.githubusercontent.com/assets/4798491/23782014/60ffe2fc-050e-11e7-9caa-5f568c2d26e1.png)
