### ISSUE TITLE
[enhancement] filter to show availability of shaders/emblems

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#1526]
This isn't exactly the same as the suggestion to show items that you don't own but are now available, but it is related to it.

I'm suggesting a new filter is:kiosk which will highlight those items that are available for to be purchased from a kiosk because they are unlocked, and the converse, not:kiosk which shows those items that are in a kiosk but that you can't yet purchase.

![image](https://cloud.githubusercontent.com/assets/25425159/23782212/6c796538-05a2-11e7-9716-6d7607b8d3d8.png)

In the above example, the Devoted shader that has never dropped from Trials for me would be highlighted with the not:kiosk filter.  That way I can tell those things I don't yet have.

I suggest exactly the same mechanic for all kiosks: exotic weapons, exotic armor, shaders, emblems, ships, sparrows, holiday gear, etc.

I considered suggesting this overload the is:unlocked filter, but that already has a very specific purpose I don't think it adds any value in confusing it.

**Comment by bhollis** [comment]
Closing out D1-specific stuff that isn't going to make it.
