### ISSUE TITLE
"Hide unfiltered items while filtering" does not work on Vendor page

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#1527]
The setting to "Hide unfiltered items while filtering" has no effect at all on the Vendor pages.

I was expecting that with this setting turned on, and a filter of quality:>96 that all the items that did not match the filter would be hidden in the same way they are on the character page.

**Comment by bhollis** [comment]
Whoops, I always forget about that setting. I've got a fix in a PR.

**Comment by bhollis** [comment]
Closing in favor of #1528.
