### ISSUE TITLE
Xur Speeder Upgrades not Showing up in DIM

### ISSUE THREAD

**Issue by tda0909** [DestinyItemManager/DIM#153]
Void Drive(1880070443), Stealth Drive(1880070442), Plasma Drive(1880070441), and Emerald Coil(1880070440) are not showing up in DIM when they are in your inventory.

EDIT: 
* Items also do not show up in the vault.
* Updated to 3.0.9 to see if there was a fix for it.  Still not showing up.

**Comment by TopDawggamer** [comment]
This is the same as bug report #51 but does give more info :)

**Comment by kyleshay** [comment]
Are these showing up in DIM now?

**Comment by SunburnedGoose** [comment]
Yes.
