### ISSUE TITLE
Record Book Redesign

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#1531]
With the upcoming AoT Record Book (8*11) Records the current design will create a large popup, I propose we remove the Record Books from inventory and add them to the nav bar (since they are all account bound any ways it doesn't make sense currently to replicate the data in all columns). Having a modal being populated with the data instead.

**Comment by bhollis** [comment]
It's a good idea! We can exclude the bucket from display pretty easily and design a nicer screen for it. 

-Ben

**Comment by bhollis** [comment]
Don't get too excited, but I'm making progress. Expect something polished next week.

![screen shot 2017-03-24 at 10 23 57 pm](https://cloud.githubusercontent.com/assets/313208/24319702/a96cea0c-10e0-11e7-9810-d07e6f01695b.png)

**Comment by bhollis** [comment]
<img width="918" alt="screen shot 2017-03-27 at 12 34 21 am" src="https://cloud.githubusercontent.com/assets/313208/24345466/2c1337e0-1285-11e7-86d0-5f5c2e722b70.png">

Fair bit of progress! I'm happy to hear design feedback / ideas at this point - I think I have all the info in place except for the list of rewards, which I'm personally not super interested in, but Bungie.net includes it...

**Comment by SunburnedGoose** [comment]
Will this support 10+ pages for AoT's book? Should we allow collapsible
pages?

**Comment by bhollis** [comment]
It'll certainly support all the pages. We can definitely make individual pages collapsible. I could also make the individual records smaller to cram more on the screen at once...

-Ben

**Comment by kyleshay** [comment]
Wow, that looks really nice! I think the current size works.

If there really are going to be 10 pages of content, what about a "hide completed tasks" setting?
 Makes it more into a functional checklist.

**Comment by bhollis** [comment]
Resolved in #1566. @kyleshay thanks for the suggestion, having the option to hide completed makes things way more useful!
