### ISSUE TITLE
Inconsistent coloring character card

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#1536]
![animation](https://cloud.githubusercontent.com/assets/4798491/23936671/13d334de-0919-11e7-9b3d-f508ece2c154.gif)

**Comment by bhollis** [comment]
That's the hover brightening effect that lets you know it's clickable. 

-Ben

**Comment by delphiactual** [comment]
The icon should be dimmed when not hovered as well then

**Comment by SunburnedGoose** [comment]
Don't brighten to 100%. Keep a bit of the outline of the emblem.

**Comment by bhollis** [comment]
Yup, we can do that.

-Ben

**Comment by SunburnedGoose** [comment]
Leave the emblem at 100% always because it is in the same plane as the text
and drop down icon. Only the background would change on hover. Keep in mind
this is not useful for mobile and so it's only eye candy for mouse users.

**Comment by bhollis** [comment]
Fixed in #1538.
