### ISSUE TITLE
Avoid string concatenation due to i18n troubles

### ISSUE THREAD

**Issue by brunnopleffken** [DestinyItemManager/DIM#1540]
One of the basics about multi-language apps is to avoid string concatenation because each language has its own syntax. Let's take a look:

This makes sense in English, and _"400 attack scout rifle"_ sounds like a natural sentence.
<img width="348" alt="screen shot 2017-03-19 at 14 21 09" src="https://cloud.githubusercontent.com/assets/3427344/24083076/580c7e6e-0caf-11e7-904c-433ec92900a1.png">

But...

In Portuguese and other italic subfamily languages (like French, Spanish, Italian, etc.) some words are swapped (as you can see below in the weapon's name), and _"400 ataque fuzil de batedor"_ sounds weird - the natural way in PT-BR to sound like a sentence would be: _"Fuzil de batedor com 400 de ataque"_.
<img width="341" alt="screen shot 2017-03-19 at 14 25 13" src="https://cloud.githubusercontent.com/assets/3427344/24083106/e73cddea-0caf-11e7-9ce3-6f1d7efdf4c0.png">

Bungie knows that and doesn't use "**Legendary** Fusion Rifle" in a single sentence, as in PT-BR is "Fuzil de Fusão **Lendário**", so they put each string in their place:
<img width="346" alt="screen shot 2017-03-19 at 14 37 06" src="https://cloud.githubusercontent.com/assets/3427344/24083180/9119fbb2-0cb1-11e7-92bb-f6119fd86f99.png">

So, my suggestion: avoid string concatenation, put each string in their place. I'm not sure if it means a small redesign of the popup or simply put a slash between the strings (400 Attack / Scout Rifle), but it will certainly be a good improvement for those who use DIM in other languages.

**Comment by delphiactual** [comment]
Leaving this here for posteriety:
From vthornheart in Slack about getting gender assigned to itemDef...

Okay, so I just happened to have a meeting with our localizers just now, so I asked the question in person - unfortunately there would be a lot of both localization and infrastructure work to provide you with that data.  They said it was not feasible to do, but they recommended that, if at all possible, you should do what the game does: try to find ways to arrange your UI such that you don't need to use sentences with item names integrated into them.


[5:49]  
This seems like a difficult task... but as an example, on BNet we changed a bunch of our Stats UI at one point to go from "3 kills" to "kills: 3" splitting up the phrase so they're more like two separate phrases

**Comment by delphiactual** [comment]
@brunnopleffken if you notice any other strings like this please post and I will get them into the i18n files asap...
