### ISSUE TITLE
Console errors when clicking consumables "Error: [$parse:lexerr] Lexer Error: Unexpected next character  at columns 33-33"

### ISSUE THREAD

**Issue by Mulchman** [DestinyItemManager/DIM#1546]
It's been a while since I've run DIM. I'm getting weird console messages when clicking consumables:

![image](https://cloud.githubusercontent.com/assets/11757993/24279229/d2858196-1005-11e7-918f-f00bf13a9383.png)

Here's what I did-

* Pulled kyleshay `dev` and it's currently @ https://github.com/DestinyItemManager/DIM/commit/212a612c4e435b5cc912b3de1868a1e44946fb94
* Did the `npm install --global windows-build-tools`
* Did the `npm install`
* Did the `npm start .`
* Opened up DIM as a Chrome extension and clicked on exotic shards

This happens on both Mac and Windows. (Obviously I skipped the `windows-build-tools` step on Mac.)

**Comment by SunburnedGoose** [comment]
Why are you using kyle's version of DIM?  I can't repo with our dev.

**Comment by Mulchman** [comment]
The project started out as `kyleshay` and that's how I've always referred to it. (Plus, `https://github.com/kyleshay/dim` just routes you to `https://github.com/DestinyItemManager/DIM` anyways.)

The Mac is using the remote `https://github.com/DestinyItemManager/DIM.git` and that's your repo.

**Comment by SunburnedGoose** [comment]
I just cut a release so double check on your side if this is still an issue. I'm not able to replicate.

**Comment by Mulchman** [comment]
* Cloned `https://github.com/DestinyItemManager/DIM.git` to a new directory
* npm install
* npm start .
* Set up Chrome extension to point to new install

Same problem.

----

Would line endings have this kind of impact? That's the only thing that might be different that I can think of.

**Comment by SunburnedGoose** [comment]
I work on both mac and pc.

**Comment by Mulchman** [comment]
It looks like a quote a missing.

**Comment by Mulchman** [comment]
Ha, I refresh the issue and you've also found the issue. Cheers.

**Comment by Mulchman** [comment]
Thanks @delphiactual

**Comment by SunburnedGoose** [comment]
Still I don't know why I didn't get the same error as you when building and
using DIM...

**Comment by delphiactual** [comment]
happening on beta and stable you have to make the move popup appear with an amount selection to see the error though

**Comment by SunburnedGoose** [comment]
I was doing that with my exotic shards. I even moved the amount I chose.
