### ISSUE TITLE
New quantity UI is terrible

### ISSUE THREAD

**Issue by klausfiend** [DestinyItemManager/DIM#1547]
I get what you guys were trying to do, but the rewind/play/fast-forward mechanism doesn't work for non-stacking items like weapon parts and armor parts. Is it possible to add back the option box to select a variable number of items like previous versions?

**Comment by weborican** [comment]
I don't think that UI was intentional. Here is what he is talking about...
![screen shot 2017-03-24 at 8 18 13 am](https://cloud.githubusercontent.com/assets/12019978/24295847/96ec0b5e-106a-11e7-8757-6e819d33d183.png)

**Comment by bhollis** [comment]
Yeah it's not supposed to be that way. Is it happening in the beta?

-Ben

**Comment by weborican** [comment]
Yes, it is happening on both the release (3.17.0) and the beta(3.17.0.816).

**Comment by bhollis** [comment]
@klausfiend please give us the benefit of the doubt - we aren't intentionally making things worse.

**Comment by klausfiend** [comment]
@bhollis understandable ... this is the release version for me (3.17.0), and I think I am indeed referring to @weborican showed in the screenshot. Not really sure what to make of the UI for some of the quantities of items I keep (e.g., 700+ filaments are hard to gauge with the slider). DIM is otherwise awesome and a huge timesaver (sorry if my initial posting sounded a bit harsh).
