### ISSUE TITLE
Bug: graphical error when moving partial stacks v3.17.0

### ISSUE THREAD

**Issue by GreenLego** [DestinyItemManager/DIM#1548]
I've noticed a graphical error (?) when trying to move partial stacks in the new version 3.17.0.

I can't see the number of items to move and I have to kind of guess. I used to be able to type the number into a text box. Maybe the text box is still there but not viewable.

Screenshot attached.

[http://imgur.com/a/Wg2zB](url)

I'm running DIM v3.17.0 in Chrome in Windows 7 64bit.

**Comment by weborican** [comment]
Isn't this the same as issue https://github.com/DestinyItemManager/DIM/issues/1547 ?

**Comment by GreenLego** [comment]
I was asked by a mod on a reddit thread to post it here:

https://www.reddit.com/r/DestinyItemManager/comments/6180ao/new_bug_in_moving_partial_stacks_popup_v3170/dfcj77y/
