### ISSUE TITLE
Loadout with Unequipped Items will Unequip Equipped Items on Character

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#1567]
Love that title.

Setup:
* I have a loadout with an item that is marked as unequipped (just to move items to character)
* Character has item currently equipped.

Result:
When the loadout transfer occurs, DIM will unequip the item on the character and move it to the inventory.

Expected Result:
Since the item is already on the character, it would be untouched and remain equipped.

**Comment by bhollis** [comment]
Yeah I can see how that would happen. Should be a decently straightforward fix, but I'll have to see.
