### ISSUE TITLE
Multiple Equipped

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#1568]
![2017-03-28 4](https://cloud.githubusercontent.com/assets/984608/24417170/f41a7da2-13ac-11e7-9695-d5f1fde1761b.png)

Created a loadout in Loadout Builder.  Turned off all the equipped markers in the Loadout.  Applied it.  Got this.

**Comment by bhollis** [comment]
I suspect it's related to #1567.

**Comment by bhollis** [comment]
Or maybe not. I wasn't able to reproduce this with or without my fix to #1567.

**Comment by kyleshay** [comment]
Lets re-open if we can reproduce it
