### ISSUE TITLE
Enhancement:  Option to send other stuff to Vault when applying loadout

### ISSUE THREAD

**Issue by powerserge26** [DestinyItemManager/DIM#157]
When applying a loadout to a character, it would be great to have an option for choosing what to do about any gear that's already on the character.  For example, I have made a loadout strictly containing new HoW Weapons so that I can have fun just using those.  When applying that loadout, I would love to see a prompt asking me what I want to do... 

a) Send all other gear to Vault
b) Send all other gear to other character
c) Merge gear

Right now, it always merges... which is usually ok when there's space to do so, but sometimes it would be nice to have a clean loadout exactly as chosen, with nothing else mixed in.

PS - I love DIM.  Keep up the good work!

**Comment by MattWhilden** [comment]
It may be better as an option when creating/modifying the loadout. One of the reasons I really love this thing is that the workflows are just a few clicks. Making the mainline flow have more steps in it should probably be avoided.

**Comment by powerserge26** [comment]
That sounds good too... just something to make room for the loadout you want to apply.

**Comment by kyleshay** [comment]
i like the idea, we'll track this in #224. i copied your suggestion there.
