### ISSUE TITLE
Since 3.18 none of the faction filters work

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#1578]
This is a new issue since 3.18.

None of the following faction filters highlight any items:

- is:nm
- is:do
- is:fwc
- is:variks
- is:speaker
- is:shaxx
- is:eververse

**Comment by delphiactual** [comment]
@bhollis more info here #1581 may not be enough https://www.bungie.net/en/Clan/Post/39966/224154419/0/0
