### ISSUE TITLE
Hashes that are not immutable

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#1583]
https://www.bungie.net/en/Clan/Post/39966/224154419/0/0

This effects DestinyRewardSourceDefinition, which in turn effects, `year`, `vendors`, and `activities`
A method should be written that returns hashes based on identifier or just switch to using identifier completely.

**Comment by bhollis** [comment]
I think I'm actually going to close this - vthorn suggests that we can rely on them being immutable from now on.
