### ISSUE TITLE
ability to export data to google drive

### ISSUE THREAD

**Issue by Ninjamau5** [DestinyItemManager/DIM#1590]
if its possible to import .csv to google drive, please let me know.

**Comment by bhollis** [comment]
Yup, just save the csv, and choose Google Drive as the place you want to save it. 

-Ben

**Comment by kyleshay** [comment]
![rec](https://cloud.githubusercontent.com/assets/424158/24688645/17eeca48-1976-11e7-8954-8cdfaca7d1b0.gif)
