### ISSUE TITLE
DIM wont fully load.

### ISSUE THREAD

**Issue by Hurc59** [DestinyItemManager/DIM#1600]
Every time I try to open the DIM Chrome extension all I get is this error code. Error loading destiny info: bungie.net may be having trouble. Reload to retry. 

I have uninstalled the extension and reinstalled, then tried uninstalling and reinstalling Chrome. Also tried clearing all history and nothing is fixing the issue.

**Comment by SunburnedGoose** [comment]
Do you use ad blockers?
