### ISSUE TITLE
Search box on mobile need to disable auto-everything

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#1601]
Using the current beta on mobile Safari on iPad.

I'm trying to enter is:kf into the search box, but my iPad helpfully autocapitalises it and autocorrects it in "Is:if". Not helpful.

Can you please disable all the auto attributes of this field.
autocomplete="off" autocorrect="off" autocapitalize="off"

**Comment by bhollis** [comment]
Not a bad idea!

**Comment by bhollis** [comment]
Fixed in #1603
