### ISSUE TITLE
Loadout builder needs to prefer gear currently on character

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#1602]
I have a set of near perfect ghosts on each character.  All are at least 24/35.

If I run the loadout builder for my Hunter, it invariably selects a ghost currently in the inventory of my Titan, even though there is an equivalent ghost already in the inventory of the Hunter.

As a workaround I have to check which ghost it's suggesting, then ignore it, then manually find the equivalent ghost and equip it.

**Comment by kyleshay** [comment]
We'll be redoing a lot of this to be relevant for D2
