### ISSUE TITLE
[Proposal] use sass-lint

### ISSUE THREAD

**Issue by hemlok** [DestinyItemManager/DIM#1607]
noticed _styles.scss is ~2000 lines long 🤔 

Incorporating sass-lint and enforcing sass-lint as part of default lint could help maintain code consistency and readability. 

e.g.
```
    "lint":"npm run lint:eslint & ESLINT_PID=$!; npm run lint:sass-lint & SASS_LINT_PID=$!; wait $ESLINT_PID && wait $SASS_LINT_PID",
    "lint:eslint": "eslint .",
    "lint:sass-lint": "sass-lint --verbose --no-exit",

```

Happy to submit a pr with this set up and code cleaned up if there is interest 👍

**Comment by bhollis** [comment]
Thanks for thinking of it! We're slowly moving things off into separate files and component-oriented Sass files. I'm not sure what sort of feedback sass-lint has for us - do you have an example?

**Comment by hemlok** [comment]
Nice! That's definitely the right solution. I think linting css would still help to maintain consistency throughout components too.

Absolutely, here's an example of some of the console output with the default ruleset I like to use.
<img width="847" alt="screen shot 2017-04-14 at 6 06 48 pm" src="https://cloud.githubusercontent.com/assets/9043345/25059542/3bbef564-213d-11e7-8659-3ee8b88e236d.png">

**Comment by bhollis** [comment]
Ah, cool. I bet there are some useful rules in there, but for the most part I don't want to use the naming ones, since they'd cause a lot of churn for very little value.

**Comment by hemlok** [comment]
Fair! Here's a pr with some proposed rules and the output of those rules in the comments. lmk what you think https://github.com/DestinyItemManager/DIM/pull/1608
