### ISSUE TITLE
Feedback for Moving Single and Multiple Items (Loadouts)

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#161]
PR #160 was made to give users more feedback on the operations that are occurring while DIM tries to move items.  

1. Inform users of the scope of an operation?  For example, do we have to perform additional operations to execute the users intent successfully, such as which item will be equipped when the user indicates a dequip operation on the currently equipped item?
2. Notify users that a meaningful transaction occurred while moving an item?  We don't want to pepper them with too much information such as having to move items to the vault to make room for a loadout.  Each of those transactions occurs within the scope of moving an item.

**Comment by kyleshay** [comment]
how do we feel about our current state of messaging? should we be showing more, or should we close this?

**Comment by bhollis** [comment]
I've got other ideas. Let's close this.
