### ISSUE TITLE
Infusion dialog no longer displays

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#1624]
As of `Version 3.18.0.877 (beta)`

Logs:
`
angular.js:12410 GET chrome-extension://kiiagdghonljdlicjpaccpkjobppmhgi/%3Cdiv%20class=%22infus…erItems%22%3E%3C/button%3E%20%20%20%20%3C/div%3E%20%20%3C/div%3E%3C/div%3E net::ERR_FILE_NOT_FOUND
`

`
angular.js:14328 Possibly unhandled rejection: {"data":null,"status":-1,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","cache":{},"headers":{"Accept":"text/html"},"url":"<div class=\"infuseDialog\" ng-controller=\"dimInfuseCtrl as vm\" dim-click-anywhere-but-here=\"vm.closeDialog()\">\r\n  <h1 translate=\"Infusion\"></h1>\r\n  <div class=\"ngdialog-inner-content\">\r\n  <div class=\"infuseHeader\">\r\n\r\n    <div class=\"infuseSourceItemInfo\">\r\n      <dim-simple-item class=\"infuseSourceItem\" item-data=\"vm.source\"></dim-simple-item>\r\n\r\n      <div class=\"infuseSourceDetailsRow\">\r\n        <div><strong>{{vm.source.name}}</strong></div>\r\n        <div>{{vm.source.type}}</div>\r\n      </div>\r\n\r\n      <div class=\"infuseSourceDetailsRow\">\r\n        <div>{{vm.stat.statName}}</div>\r\n        <div class=\"bigValue\">{{vm.source.primStat.value}}</div>\r\n      </div>\r\n    </div>\r\n\r\n    <div class=\"infuseControls\">\r\n      <label><input class=\"controls\" type=\"checkbox\" id=\"infuse-all\" ng-model=\"vm.getAllItems\" ng-change=\"vm.getItems()\"><span translate=\"Infusion.ShowItems\"></span></label>\r\n      <label><input class=\"controls\" type=\"checkbox\" id=\"infuse-locked\" ng-model=\"vm.showLockedItems\" ng-change=\"vm.getItems()\"><span translate=\"Infusion.LockedItems\"></span></label>\r\n    </div>\r\n  </div>\r\n\r\n  <div class=\"gearsContainer grey infuseTargets\">\r\n    <span ng-if=\"!vm.infusable.length\"><strong translate=\"Infusion.NoItems\"></strong></span>\r\n    <span ng-if=\"vm.infusable.length\" translate=\"Infusion.InfuseItems\"></span>\r\n    <div ng-repeat=\"value in vm.infusable track by value.index\">\r\n      <dim-simple-item ng-class=\"{ 'infuse-selected': value == vm.target }\" item-data=\"value\" ng-click=\"vm.selectItem(value, $event)\"></dim-simple-item>\r\n    </div>\r\n  </div>\r\n\r\n  <div class=\"gearsContainer black\">\r\n    <div ng-show=\"vm.infused != 0\">\r\n      <dim-simple-item class=\"infusedItem\" item-data=\"vm.target\"></dim-simple-item>\r\n      <div class=\"result\">\r\n        <span translate=\"Infusion.BringGear\"></span>\r\n        <span class=\"bigValue\">{{vm.infused}}</span>\r\n        <span class=\"green\">(+ {{vm.infused - vm.source.primStat.value}})</span>\r\n        <span translate=\"Infusion.Using3\"> </span><span class=\"currency\"><img alt=\"Legendary Marks\" title=\"Legendary Marks\" src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACUAAAAjCAYAAAATx8MeAAANQ0lEQVR4AcWWBXgTW+JHz73jE22bVEMFKbToU9467627u7u7f7Lu7u7uLk9hFYfCoywUrTeVNC6TsX+26/J3O9/3S8YyOdev4D/Jnh1XKTHdHNV15Rrhu6OOU+8AOqO2Peh7biUa1ReErs43HXexr6/zyN7j42PAAv8JxLWjG/mP0KG3j/qe9wRVePdPRpXtqbQtYskIuaU6g8NpkvEAVdeYmqy3ruXRVZASCNWVhVzjSNX1vnrk/IUfApV/V6onleDf4p6bRjfM5UqvidrqE1IJzXS8AEVJ09W1kXRnH27VYOCKOgd+fZJEW0i7PczsREColwhlEd2uEo3UicbbuHS5OFGuFd5/8OzFzwD+vyo1PNjJv8bmaOezqsi3DPRG09V8ncWsRru1mUzHBkZHNtKzvp1q2SExusSF8RLbd3cyfaJE8VwCoQfU602yK0tUghmkNcu1e9axtOQwfXHmNyenL7wQOME/Qe1I2Pw9Kd+w53O1T+iD6ScO91pkemz2Hy+w5/6b0AKD/k0hueUTeB0ZtDaVwW1d3PVhW5HSR6hTzCezKDo4jsugJjlzPEK0cweLyzVuuH8vJ/an75zqzvx6/OLx5wFf5u8QD7lhx99a5rxoruR+v2944B62aHLk+CpRO8Fr33k32jtsBjdH+Nz7jjN1WtLdm8K0DQIvpFH1EQRopoKqByiaZG46z2Ne2IsdD4kl49z0jVlu/eYCO3bH2HW3TYwfnubi9JEXAR/+G6mnPWg3f+KnvxjXr8kMfJ9Y4n49ccFPb53jKc+6G2EgyeWLDA3FUGWV6dvbSAW78EUDu8Ml0aOj6kAgcasKzoqOLmOUSg2i248jLQehGxy6scAjn7aN84c0irULbL2ui5P75xm7+JsnAl/hj6iL+RJ/4qpM35tXm8r9diQVfrl/hZ7YIE61xMMfP8Lqajdf+MRJ7vugBMttHqGYJLWxxtLKAlJJ49dskmmT9IhN4AuUik/+tzW6+pNMzSxTmCzzwjdvwnWXOXGjTVLcmbPHbmXTSIagceUnfnP+txPAEQBx16sGATBq6p5SVdm3ceD3o6SEEfRDGHDn++i4EiQh5YLDPR+yneEdPbzh1T8he1phqG07/X09JO02rLhBpV5nPj9DmWl236efhzx2I9/45BEKK6uomiQQDXrjV+FPjbBcXULv+zWEGygVxk9//Me3XAdURGcqwoNHt4p8sX5gctXbvanH5vJUnL5kNzXy9I8GHNtbp7utk5VaodVHRrj5pyfZfadB7nW/jRzbV2HuoAnRMpbooKM7weB1Lr0b2vnaB8dI9DcIa21EnA3omsJC7jKp/iLd3AvP9zg7e5Ce4RyFxTbOLe59KfAB5eHX72B1uXav+Zz3mvaYykpeEtE7EQL8oEx7SkVWu1HQuPNDujhzahabGG/40J2oVHOM7k7z60NneP77uqmERTylzkOf04WdaLY6dIb93xDsuD5Om5ZhaGiISq5OvnKeqLqBSEIndOI44jyKSNMZE5u+dMv+z8kbD07gucHT602BKkKqVRXXq9F0XTRLIEMVUzMx4hDpqDI95qIT4/axWRbni8xPLRMKl0K+TrJdo7DosbJawvNd9u87TVrvprEYQ+1coF5yiNpxNEMjDD1s26C9LU5Qy2BFyphq//pdwz17ZL5QSwShsltVVFxfIIXRisQL/DUpzYjSaLjYcYdzY6ukY124ecl7XnmCpZUQIURLqEZnbx/xRB/go2oRvvyhMxz9tsKW7Rm0aieqBeV8CXyFaDyCZkgUqbaOdaTbS9PJU6uaYvuGgQfIdDS5OQy1AU0IPF9BV3RsM0Kj2cDHobBaBxGgaBA6BlHbwlA1ovUuvvPhWSLtUa664yDvfNFhvvmZMa5/TC/f+dTtzNyW4Lqd12G3aWvvq674eGET3TRaAiHIJmEokAg0YeN7IAKFZpURaShyJ4GKokBLDkVK6k4N13OxLIVy0QEBmq4TiVlrs7RUFSxbwV8y+eUPFnj886/kUU/fzVNfvg0tWmLiFp8tGzYRCBen5rG6VKKQW0UqCqZuomsR3LBGGIYomsTQbNw6EAiEMAIpCNcTSqQQmLqBlJIw9Ne+/YZP6GotOYt6WTIwGqPebBC348SjSRLJCNmzIfWaS3qdBKXApfEiXiGC49coFsrUig7Fcg7V9tGkSazNpr09hVA9XC/Aa8U0TVRFQ1EMAl9BhoSGKkEIBdMQCCFbgQAPCMDXiEQtVuddCH0S60KqlSYhkIhHyM9XmJ2cZiWbpenUqeYDwhBctwkiZG6miNI7TbNs0ZVJo9kKflNFs3yCJtgJA1UXaFqAKgx0TSA9TwT27x8MFCJW2Pr20TQNIUIicZNsLs/ych6Q3PjtGW54TCf55hLNuk8QhqwslykXyki8tefdqiTdkSaaiFNvHdesi9TUBS4cFJTzdep5yM3X8WmgqApSSoLAwTQFng+RpILq+KJiagGuJxDCQ9MFIlQJvZCeniRbd6Xxmg0KBUn/hkHueMdODMvkxi8t4C8ahHWDn3z1Ine4Rx9mzGLv96bZGO9j8nKW6PoSd3yYjqV0cdQpcrnyczQhiGVWMe1NyKbArULNnaPqhEjNQbNANvzgfKPpEY2aFEsObSlBw2kSyJCZqRWiooLilLl4foJYQmPvz+b4yocPs3WPzq6HW2y8U5LZcZXPvfsM73nZIVRhYw8v0neXWZarE3zvY7Pk5qucP3eGC+dPEGlfQgQlpicKqEKhVvUItEtk5w06Ug1qZU1RfBBpM/6svu6YnF5oMpRRWVpWENLh+rtm2HdghnPnFujs7mBhusDkxQrObEvkbI26V6ZjAAa2aAxv6yYzZGGnK+QrOS4caWKXR4go7WSLcyh6HEPx+eXeRUxNo28wTlgaoBbMU/HGqRX72TLa5NYDM3uVIAyKUSP18PWderriRwhqKyS72ykWfEo0mLqY4343DGMbOve41xDZrENuStKTTNFY0Vm5BNnzHjPnq2vX/eXOVlIMdo6QyWQoFmrc4T4GccOhXm2ybfsQE6egVqqjhb3o6ZOcPlZjy45urIjPV2888D5luG+rl6sWtySEvnvTpg5On6+yc9SkJi2E55BsNymslLAiFnFTJVdyya40SSYjGJaCFzawLQvbiNAeT2BaytosjRZQa5SpegWidhmv4TM7WyQ7V6Z3oA3p9tHWU2Fu+gyCzVxxjceBQ+Xsz4/e9nph6lFc39l6debKoyPdgWl0bWBs/xj3us8WPE9wdmIJ24SaGxJPmPQPRom1RYi1pDzXZXWpgGWbWDELPwSCgNXFAqEnCIVEA+rFJjPzLpmMzcpSQG+vzcaRIWqFZU4djXDvB/eyOlfga/vGP3zr8Z+8RPBHupLrvrArNfDkzRsUimSYHB9j8/o4WT9Bcd5H8UOkplFvVFEViSZVDN1A1TRkGGIaBlLVCP2AQAiEAEPXsUx77Zm42Y4T1lsiHl3rayjBAhO/s7nnA3dBfYrbJ6L5T936ybsBp9R4NAnAYmHmDQvxrgdql2X79p0F5M5rOH38KHuuTxGODHDitzmcUoOeWC+aqqIoa1LoqoZtGFiWjaHbeL6PokhM2yYRj68JeQ5Uyy6uXqTzqjzTF1oSp1Tueb+t1PPjzM/1cduZfe8sVQqnASH4K3TVeNTu9Xf+ZpussW1bkiC2nn03HmBTn8L263YwvyyZPVvGLfuoUqEtnljrT4alrwkKJLYdJR6LI6QkotsUqzVcWaW9r07TmWT/L8/ikuE+D9jC/PkTlPLrGMtN3nTjoR88lpAiEAj+DkuPvOHKgWtf3yZChgY9Bkav5sjJeS6dGuOK7T0MbdlI3TFYXfWo5v1WHPS15WGtqVqJYEU1OnrjqLqDHa+RX5pk4vQU2ZzGzmt3snlI49ShE1TqAyzLxvHv/+arj3AddxrwAQT/BFXVXrJ93ZVvHYylbLwZrrhqBKMjw/iZWabPnCduhWTWddCeTqIZFqqio2o6WiumpSAVqBTKzFya4+L5LGo0zcat6xndkCKfvcSZ25cw4qOcK1/Y++sTt7zAcZrn/ygU/qtSfxR7wKaukS8PpzckveoS0UiDjZv6SfcPkl1pkM2urm3aSrkCge9iGgqWaQEKphkj1p4gEou25NuI6i4Lk5e4dGEZx2/DbOvmd7nxHx4Z3/8C3/Ozfy30r0v9WUy9tj2aemdLbk/KTBA2S4igQCoVpbsnRSLVgaKbaIYGUq7VmKaqrQiatQqrS8vMTy2xkmvik0CNJCiG5cXTM2Pvvjxz6QtACfD+JPQfkgKQUkZM3XxMWzT1/O5E3xXtZpKIbiA8B4mDoQhs28IPWseGAUIh8CReoBIInYYbEmiSgpPPTq5c+ub0wuXPNpzGBBAAHn/Pvyb1r8glLMO6h2VE7hu3kneJG8n+hB03Ld1GNVRs1UKEAmSIFwbUnTolp7hSahQP54rL+3LFlRsbTv1PfSdYy7+C4D+PUKSSNnVzGCE2hWFoQhiEIVJIIQQibB0EUoqs03TONZqNOaDKGoRAwP8z8r9S8H8BmJrwrAW8/rkAAAAASUVORK5CYII=\"></span>\r\n        <span ng-if=\"vm.exotic\">+ 1 <span class=\"currency\"><img alt=\"Exotic Shards\" title=\"Exotic Shards\" src=\"https://www.bungie.net/common/destiny_content/icons/e6d2a0561e784ae224e2aa53aa66e8a7.jpg\"></span></span>\r\n        <span>+ 250 <span class=\"currency\"><img alt=\"Glimmer\" title=\"Glimmer\" src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACEAAAAiCAYAAADRcLDBAAAJGklEQVR4AZ2WA7Qk3ZJGdxxkZlXdum53j23bXBjPLI1t27Zt27Znnm2rMc3LYuqciPlX1X3222nGF9+h8AbyHg+77cJgdMU73rft8xOaur4J9LwBhHf47//j9eHS7pZvUr7UL+df6hbTLxyMBnsu9dO6WfyVVcPvDZqvA8rrgbzTf17ndWE8Hjtx/kKZu2/0wX0uJpuCkE2pioIuJU6ms6k4930bO7u/4fv2FDBeB+Qjn3jMayJndSnEC1Yvv7IM4QvGo+FeNkUQihgQM5wIpfcs+5550xEct9pkv2ll+XtV8DeAxGtAPvbZLa+OZcqb1iw+rXD++2IIe4OyYBQ8mJENKidsBAFgmQ0RIZnhgEmX0KyLed/9Yu3ij84mk6NX54w8VMF4ObpWqp29XenaTxlF/1VbG6O3jeKoAmx5T2SdOUCtxtALBqiBmiGAAkEcoMxUeNHJ9P7No+OfbVz89fb48OAVxcgb/fkTAdjaPydlVZ0POX16gX3lzvbmGw1CZByEzeAIwMALQycrBwCGzth0wmk2ZgrZwDuYJiMgeAEV6IAXTVse+8Kb91rVr/WD4d8CC86Qj/jrx8jgHd9rVycn39bl/Jkqsrc1GrFZBLbd+kfBwcgLAyeMvXDOw4aDoYekYALJ4CjDJEOj0Ou6eM7coRW43SnPO5hy+8HBEyyGnxjv7P11/bB/auS9H3/qz/n8y2+0v/35DxYtYsJWGdk6CxwFxsFROdj1cDFCASRAADVwAnbmwjzDSYZZhtmZGCfromsVTg2Waiy7xK2Do5+40+RvkTf9t+v7upw+/eLOzoU3Pn+Oc4NINGPoYMM7Bh4uB2EvsBLmBBQwwLGmB8x4CUFgrnC/X2/IWkxj64e3msT/PO35vOj6jaPq4pW3CnXTvOn8ZHru7p371H1i540u8+ZbBSkZ20G4GmE3gGeNnAURXuoABipgvJQocC3CnodbPeRVccLD7835x6c8m+mLriPRkesmhLrt63axzMWgcoenEx5mxvLaZT7pfMlbFVAr9Kzx8lIRCqixonBrMRkwAAMBTGA/wpsO4BFz5deecZdnPBS8XTT4AKg5AR/6vj8NRdGEGGPOilPlafcPGcfz+N3IWxSQDToFOcuwNxDWm63FvBwKq6xHDg4Vfut2xyPvHXPj/gNQQSwjgw18URS+iGXIWUNuG/fQBdVDm5kRVDnulf84zbywdLzrULhWQlZobC1EWWMvI6gzCAJ7cX3+9yfKP91fcP3BAdY1tHWDc4LDSIspsboAQDBsy1IqNWUQKGJgWBaoGWrCcTL+dwZXO+HdRnA+wizDQsED4cwZY916igAPnxq/e3vGrZMZlSg7ReBgqcQYqeua1LSIQTc9LqystkJOad9SH9SULmVYBTfapKTSWCoUAs+tjbstvMuG461L2A+wyNDa2noD7mb4z2Pl3+/PaZYLBvQ4POaE7a0RTZ/QssC2tulOj9E+RXK+FFT11EGfui7OZ3Pq0ZCqyLSpZ9J5BlWgVcMLnGZ42FR5qhfevIR3GQk7Dp7fGo+cGU+adhzWDa5vKR1IqMhqtF1HXbcEL/TJUZQV7O1DXeOGD0UQkesGh3T9Jb9ToqpgRuk9OEedbZXpQWcEB0MntCpcb+AFDVyt3ErY82dLtOvwZqvMmy4TzGEYMQSGVcXpYo6ZkVILCsV4bM77WQghdtn523p6eGlZFCwHFWXbsqNKVmWJXzlRBYdgZ6MlCHCzhQOD65MFy8WMwgcUY4UIbUpE7wBZ/Sv4SM49ORuaEiqStbTDkPve2Xy2zXyCbu9zNJmDZc5vbxG9p5OMcw6fMl4ELw4nhhmUwdF1eZVh13b0QVfvlEVgGCM1rIQUIdCnRJd6+qxo6rFFTdvWXkK5HzTnsbT1eZoanU3oqpJFGTmZLRgUBb0Z3ju888TgVhmpGcmMDo+p0nY9wTkE6FIiOI+6jABVCKgIKWeaJqGmkDPWt2ibhM29cUAo6LvAfIYVB0g1pI4FvWUmyyVlCBQWkSCkBGZGNsMBtSaceHJOhBhXz8oQqVPHMJbEEFaiUt/jENQyueuxvseaBWQFtAsu9VOEpdXzIbOIhkgqCryPROdXzbbpe0AYFHH1YyeCC4HCezBb3VNVQgg4B04d3aoYHN57VHV1jQja91hKEAqwFu3SKFjftSGniaZ+n8UU2po83uQZz3k+V65c4sru1qoo+r4nZYexdmPRduxvjgGjCBHVjHfroJUz1AwDZssFi7pl3rTklYAeMKSsiPvn6IIvg8ynjWubR9PWb85yBvuXYDYhGdzseg6PN3mrq5cYlJFsoCmTcl4Fqdt23eRyQkRwQFZFgEVdczxd0KZ+5cSsbrCuw+oaUNxojI8xDbe2XuhBLF95839jMDqmrd+P1BXMZ2AJvCepcNonjqYzsiZC8KSUAHDicd5x7+hk5VZSZVnXPJiccjRZkDRjBotlQ17M0ekE61pQRZ1/POPtz/TCo2Xjj54AwOKR/+UI4Z24d/P3aRZvj49w+U1gvI3b3MLKIX44YmtrhIhjb3PMxZ1tVDP3T6YrByaLBTEEzIzZbIGaUg5HTO7ewaUeqxeYLw5s79z3SFn9DjCPv/PDIuWHfBwvS/eeHz2maz6be7d+iJxH7OxBKGHvHG7nHFIOcFVFKALDqiS4s2arGVXQnFFYjZhiRq6XuNShoZppDD9j5eDnQrt4uRm3xF/4Z16R9LxnOqrh23N0/2eZnnwwfSecvwyDDWRrF5zDbe/iqgHYenT0RUHuEjn3KyGrZtg16Hw2s/HmH8nO+R93bf0CQHkFJPzyf/DqyNefX9F3H8zh7Z+iS2+Ll5UQBiMQgd2LVFevkfuO3HWQM74syU2Lw9Cy+D2Nw+9ylm8AyqshmDheHe5N36oB/kXL6n3Q/Akc3vsWuuatmU8FDFRxFy6S5jP0+Ih46QrVcIMWu5VD9Q2uKv/GQcNrQeLvPprXlfT8Z4+BD+Pg9g9xevK2mBLe5X0xjHxySHH1TeduPP45qUY/BpzwOiLDP34Sry/1c54+pll+Mrdv/GC89saXuPpmbUr6u4w2fqiwfBPIvB5I9Rv/yxtC+/QnCLvnL8hw46tt7+K/OE0PAxJvAP8PL0JHfOhns6cAAAAASUVORK5CYII=\"></span></span>\r\n        <span>+ {{vm.wildcardMaterialCost | number}} <span class=\"currency\"><img alt=\"Materials\" title=\"Materials\" ng-src=\"{{vm.wildcardMaterialIcon | bungieIcon}}\"></span></span>\r\n      </div>\r\n      <button ng-if=\"vm.getAllItems\" ng-disabled=\"vm.transferInProgress\" ng-click=\"vm.transferItems()\" translate=\"Infusion.TransferItems\"></button>\r\n    </div>\r\n  </div>\r\n</div>\r\n"},"statusText":""}
`

**Comment by bhollis** [comment]
Just need to add "plain:true" to the dialog

-Ben
