### ISSUE TITLE
Change BungieService to use /User/GetCurrentBungieAccount/

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#1631]
We need to switch our service methods:

https://github.com/DestinyItemManager/DIM/blob/dev/src/scripts/services/dimBungieService.factory.js#L226

https://github.com/DestinyItemManager/DIM/blob/dev/src/scripts/services/dimBungieService.factory.js#L253

to use the /User/GetCurrentBungieAccount/ bungie endpoint.  It has all the data within it.

**Comment by SunburnedGoose** [comment]
You can compare the endpoint here, 
https://destinydevs.github.io/BungieNetPlatform/docs/API-Test?code=b458d207ba6da875f8805938d4c06e5b#/GetCurrentBungieAccount

**Comment by SunburnedGoose** [comment]
I think this will resolve the errors we've been facing lately that prevent users from loading characters.

**Comment by bhollis** [comment]
Cool, should be easy to swap

**Comment by SunburnedGoose** [comment]
Should be faster startup too now that we have all the data in one endpoint and are not searching for gamertags/psdids that change...
