### ISSUE TITLE
Add an action to the "Building Destiny Database" view to "Retry"

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#1636]
There are many users who get stuck at the "Building Destiny Database" screen for unknown reasons.  Usually when they dump their cache, the app is successful.  Can we add an action to this screen that will dump the database and attempt to redownload to help avoid these issues?

**Comment by bhollis** [comment]
Note that we already dump the database and redownload in case of unknown errors: https://github.com/DestinyItemManager/DIM/blob/dev/src/scripts/services/dimManifestService.factory.js#L111

**Comment by SunburnedGoose** [comment]
Yeah, but we're not getting an error when we hang on building the database.  Dunno if dumping the data would help kick that off better next time.

**Comment by bhollis** [comment]
I've fixed the causes I can think of for the hang. Dumping the cache isn't going to help anything beyond this, we do a good enough job of checking things.
