### ISSUE TITLE
Add telemetry to "Building Database" to learn why users fail.

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#1637]
Use Google Analytics to report users that are not able to load the database and any reasons that we know why.  Unfortunately some users hard crash when loading and we will never know why for them :/

**Comment by SunburnedGoose** [comment]
https://www.reddit.com/r/DestinyItemManager/comments/69picy/building_destiny_info_data_base/dhatmaz/

Seems like having no space for the data could be the issue.

**Comment by bhollis** [comment]
It's almost always space - but we can't know that as far as I can tell. I've worked around it as best I can.
