### ISSUE TITLE
Change behavior of 'Equip to Current Character' button on Loadout Builder

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#1643]
It's been suggested that we relate the scope of the character at the top of loadout builder with an 'Equip' button in lieu of the 'Equip to Current Character' button for each set built.  This way users can just equip the set for the character.

If the user wants to apply the set to other characters, then they can just make a loadout.

https://twitter.com/ThisIsDIM/status/862354821403246595

**Comment by philkernick** [comment]
This issue has a high level of overlap with #1154
