### ISSUE TITLE
If all the characters are full for a item type, the loadout fails.

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#165]
When trying to equip an item from a loadout, the logic will search for characters that have space to move an item to if the current item type is full on the target character.

If DIM cannot find a character to move an item, (even if the vault has space), the loadout will fail.

Workaround at the moment is to always have at least one character that has an available slot within the item type.

**Comment by bhollis** [comment]
I believe I fixed this while I was tinkering with loadouts for split-stack management (we now favor the vault for moving stuff off a character to make room).
