### ISSUE TITLE
Refactoring for cross-browser support

### ISSUE THREAD

**Issue by sgtfrankieboy** [DestinyItemManager/DIM#166]
I think it would be nice if we could start looking into refactoring some of the code to support FireFox, Safari, etc.

It might be possible to see how [RES](https://github.com/honestbleeps/Reddit-Enhancement-Suite) does it and mimic that, the way that's setup isn't really difficult.

**Comment by SunburnedGoose** [comment]
We are for v4.

**Comment by sgtfrankieboy** [comment]
Sweet, is there a way to communicate besides Reddit/GitHub? Want to help in development with DIM.

**Comment by SunburnedGoose** [comment]
PM me on reddit. You can find me on the DIM sub.

**Comment by danielfilho** [comment]
:+1: on this.
