### ISSUE TITLE
Graphical Error

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#1660]
funny graphical glitch, fill a store, then equip an item to the full store from a non-full store and watch the non-full store.

![glitch](https://cloud.githubusercontent.com/assets/4798491/26038182/92b9e966-38bf-11e7-8b26-55cbede689ed.gif)

**Comment by bhollis** [comment]
I haven't been able to reproduce it...

**Comment by bhollis** [comment]
Linking to #1568.
