### ISSUE TITLE
New item overlay is offset on web version

### ISSUE THREAD

**Issue by shockthealien** [DestinyItemManager/DIM#1670]
![screen shot 2017-05-16 at 16 44 16](https://cloud.githubusercontent.com/assets/2083273/26115077/f4333f1a-3a56-11e7-8e96-3177241363c8.png)

**Comment by bhollis** [comment]
That looks like a bug that affects all versions. Thanks for bringing it up - I'll get a fix out.

That said Chrome 49 is over a year old and isn't supported by us anymore. I'm surprised it works at all. In fact, you should have gotten a warning when DIM started that your browser is too old. You might want to look at Firefox or another browser that may be update-able.

**Comment by bhollis** [comment]
Fixing Chrome version warning in #1684
