### ISSUE TITLE
Node info via title element doesn't work on mobile Safari

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#1671]
Using beta on mobile Safari on iPad iOS 10.3.2.

On Chrome on PC, mouse over any of the nodes in the perk tree of anything and it shows a text popup of the attribute via a title element.

When using mobile Safari, it doesn't do anything.  I've tried light touch, press, long press.  But none of them show the title attribute.

**Comment by bhollis** [comment]
That's right, we haven't implemented that yet, but it is on the backlog. 

-Ben

**Comment by kyleshay** [comment]
Right now we're just using the browser native tooltips. Mobile devices don't really implement it the same way so we need our own custom solution. 

Linking https://github.com/DestinyItemManager/DIM/issues/575
