### ISSUE TITLE
[enhancement] allow compare items to compare vendor rolls

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#1672]
I would be really useful to allow the compare items pane to be able to compare you current items with those the vendors are selling.

Just picking compare with what you currently have from the vendor side doesn't let you compare which perks are on each.

**Comment by bhollis** [comment]
Yeah, that's a cool idea! I'll whip something up soon.

**Comment by bhollis** [comment]
Closing out D1-specific stuff that isn't going to make it.
