### ISSUE TITLE
is:kf and is:wotm show Exotics although is:vog and is:ce do not.

### ISSUE THREAD

**Issue by rowanbrendan** [DestinyItemManager/DIM#1675]
I'd prefer them all to NOT show exotics, but I just wanted to point out the raid filters aren't consistent.

**Comment by delphiactual** [comment]
this is how that data is returned by bungie since the exotics can be acquired through chests in the raids.

**Comment by delphiactual** [comment]
to get the experience you want you can add multiple filters... `is:kf not:wotm`

**Comment by delphiactual** [comment]
Just for background:
All the new raid reprise items had to be added manually to all filters, which is why kf and wotm behave differently because they have always had y2 exotics in their loot pool.
