### ISSUE TITLE
Dragging materials does not update counts

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#1676]
Latest beta web version on Chrome Windows 10.

Dragging materials onto characters doesn't update the count.

I have 195 spinmetal on my Hunter.  I drag 2 spinmetal from the vault onto the Hunter.  The Hunter still shows as having 195, but the 2 from the vault are gone.

Manually refresh and the counts correct.

If I use the fill-stack function, then neither the source nor the destination counts update until you do a manual refresh.

This didn't used to be the case, as the counts updated as soon as the move operation happened.

**Comment by bhollis** [comment]
Thanks for the report! I think I know what causes that, give me a few days to make a fix. 

-Ben

**Comment by bhollis** [comment]
Fix is in #1685.
