### ISSUE TITLE
dev- is there a user setting to disable the gun rating system?

### ISSUE THREAD

**Issue by Mulchman** [DestinyItemManager/DIM#1678]
I'm finally integrating dev changes into my own branch and I don't see a user setting to turn off the gun rating stuff. Am I missing a setting somewhere?

**Comment by bhollis** [comment]
Not currently (you can check the settings service to be sure). It's only on in dev right now. 

-Ben

**Comment by Mulchman** [comment]
There's nothing in settings service at the moment.

Do you ever think this feature will be moved/refactored in a way that it could be excluded completely via $featureFlags? Right now to remove it requires commenting out lines in at least 4 files-

* `src/index.js`
* `src/scripts/move-popup/dimMoveItemProperties.directive.js`
* `src/scripts/services/dimStoreService.factory.js`
* `src/scripts/store/dimStoreItem.directive.js`

**Comment by bhollis** [comment]
Probably not removed completely due to the integration required, but featuredlags should turn it off. 

-Ben

**Comment by Mulchman** [comment]
The `move-popup` template- if you were wanting to remove the lines that had DTR/review/rating stuff on them what would your approach be?

**Comment by delphiactual** [comment]
See #1646

**Comment by bhollis** [comment]
I'm closing this, but I filed #1680 for the concrete task of adding a user preference.
