### ISSUE TITLE
Export Bug/Issue - Weapon Notes

### ISSUE THREAD

**Issue by ProfeC** [DestinyItemManager/DIM#1693]
When exporting the weapons list, items with note are not formatted properly. Specifically, multi-line notes end up as new rows in the exported file. The [solution that was used to resolve the same issue with armor](https://github.com/DestinyItemManager/DIM/blob/dev/src/scripts/services/dimCsvService.factory.js) could probably be used to resolve this issue too; the block starts on line 88.

Here is an example export files to show the potential difference between pre & post fix: [dim-weapons-export-examples.zip](https://github.com/DestinyItemManager/DIM/files/1034159/dim-weapons-export-examples.zip). I manually edited the file after exporting it.

> _Thanks for your time and the excellent app! I hope this bug report helps make the product a little bit better._
>
> _Cheers!_

**Comment by delphiactual** [comment]
#1694
