### ISSUE TITLE
Vendor comparison overflows on Mobile Safari

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#1696]
If you have a lot of the same item that gets compared with the vendor, it overflows the bounding box on Mobile Safari (iOS 10.3.2) but doesn't on Chrome 58 (Windows 10).

Here is a comparison of the vendor Towerwatch Ghost Shell with the 7 I have in my inventory on Chrome 58.  Note that each of the compared items slightly overlaps the previous, keeping it in the bounding box.

![image](https://cloud.githubusercontent.com/assets/25425159/26617207/03e1d74c-4613-11e7-90f1-17d65ea5aacf.png)

Here is the same comparison on Mobile Safari.  Note that there is no overlapping with the previous item, so it flows out the right hand side of the bounding box.

![image](https://cloud.githubusercontent.com/assets/25425159/26617246/409972ee-4613-11e7-9fa0-dc3b61529cf4.png)

A simple workaround is to limit the comparison to 6 items only, or to wrap to a second line.

**Comment by bhollis** [comment]
Closing out D1-specific stuff that isn't going to make it. We can pick this up again if we are able to support vendors in D2.
