### ISSUE TITLE
Age of Triumph filter needs additional sources

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#1705]
Thanks for creating the is:triumph filter.

It is working correctly for emblems, but not for other items.

1. Things it selects, but shouldn't.

All of the Titan/Hunter/Warlock Vanguard armor sets.  These were introduced in RoI, and are selected by is:roi.  They shouldn't be in is:aot.

2. Things it doesn't select, but should.

The "* of Triumph" armor sets that drop from Treasure of Ages boxes.
The Treasure of Ages boxes themselves.
The "* of Legends" class items that drop from the AoT speaker quest.
Age of Triumph ornaments.
The new ornaments, ships and shaders that come from the treasure boxes.  See the Rewards (New Items) section here: https://www.destinygamewiki.com/wiki/Treasure_of_Ages

3. Things that I think should also be in the is:aot filter:

All of the elemental exotic primaries from the raids.
The legendary raid weapons that drop from the updated raids.
The raid armor sets that drop from the updated raids.
The new raid sparrows and ghosts that drop from the updated raids.

**Comment by delphiactual** [comment]
not gonna happen

**Comment by bhollis** [comment]
@delphiactual what's left for this after your PR?

**Comment by delphiactual** [comment]
@bhollis I'll have to check the items listed in number 2 and add some of them to the missing sources

**Comment by delphiactual** [comment]
complete with https://github.com/DestinyItemManager/DIM/pull/1706/commits/ee9f7833f049bc983f83999c60e7afbfe2e2c4d7
