### ISSUE TITLE
Total material needed

### ISSUE THREAD

**Issue by caiobrentano** [DestinyItemManager/DIM#171]
Is it possible to calculate how much of each material and Glimmer is needed to full upgrade all your weapons and gear?

I'm not sure if this is a feature you would like to put on DIM, but I think It would be great if I can know exactly how much do I need to farm.

If it's possible, I'll be happy to help you! :)

**Comment by bhollis** [comment]
It turns out that, as far as I can tell, the actual materials required to unlock a talent node isn't available through the API or manifest.

**Comment by kyleshay** [comment]
http://www.bungie.net/Platform/Destiny/2/Account/4611686018428939884/Character/2305843009221011538/Inventory/6917529064353753348

actually returns `data.talentNodes[].materialsToUpgrade`

it would be rather intense to have to call that for every item though. suppose it could make the call when the move dialog is opened, but i'm not sure if it's actually worth it.

**Comment by SunburnedGoose** [comment]
Is it something we can precipitate in a webworker and cache?
