### ISSUE TITLE
Add direction to adding a review

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#1715]
![image](https://user-images.githubusercontent.com/984608/27113449-76487b3c-5082-11e7-9ef7-17b8cf21a0be.png)

If the user hasn't opted in to sending their data to DT, then we need to let them know when they are trying to submit a review.  They need to be encouraged as easily as possible.  

Add the ability to enable the flag directly in the feature without going to settings dialog maybe?

**Comment by bhollis** [comment]
@48klocs were you going to look at this?

**Comment by 48klocs** [comment]
Yes, the weekend snuck away from me. Soon!
