### ISSUE TITLE
Showing elemental icons all the time is busy

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#1720]
Especially when you have items as small as allowed:

![screen shot 2017-06-13 at 10 29 38 pm](https://user-images.githubusercontent.com/313208/27116759-d40d6f2a-5087-11e7-9055-3f71826845aa.png)

**Comment by randalla0622** [comment]
These icons don't work for me. They aren't visually distinctive enough for me to glance at them and figure out which is which. With all the new elemental primaries, it's hard to tell them apart by icon so I was using the elemental color from before the review change to tell which was which. Now I don't have that ability.

As I don't care much for the review system that's being put in, I would like an option to have the element show as it originally did if you disable the weapon reviews.
