### ISSUE TITLE
Notes and Tags Dropped in Beta

### ISSUE THREAD

**Issue by wein3967** [DestinyItemManager/DIM#1730]
Seems like existing notes and tags on the beta extension got dropped in the weapon reviews update.

**Comment by delphiactual** [comment]
Dupe #1726 & #1729

**Comment by bhollis** [comment]
That definitely shouldn't have happened! I'll look into it. Fortunately I have a backup of my tags...

**Comment by bhollis** [comment]
Hm, I haven't seen it happen for me, though I don't use the extension (only the website). Any other info you might have about what could have happened to them?

FWIW I'm working on much more durable storage (and backup/restore) in #925.

**Comment by wein3967** [comment]
Sorry for the late response. Nah, I don't really have any additional information. I really only use the beta extension. I found and old backup, so that is close enough ... especially until D2 ;)

**Comment by bhollis** [comment]
OK. I'm sorry this happened!
