### ISSUE TITLE
Order by Stat roll Percent

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#1732]
now that weapons have reviews, if the user sets this order mode, should it also order weapons by average review, highest first? would make it easier to quickly scan for your potential best weapons.

**Comment by bhollis** [comment]
Linking #647, I really want to get to that at some point...

**Comment by kyleshay** [comment]
very true! forgot about that. wonder if people would ever want weapons to sort different from armor/etc? might become even more complicated
