### ISSUE TITLE
Display how the rating of a roll compares to the best-rated roll of the same gun

### ISSUE THREAD

**Issue by chrisfried** [DestinyItemManager/DIM#1736]
What roll am I chasing? How close is this roll to the god roll?

**Comment by kyleshay** [comment]
No longer in scope for D1. D2 perks are predefined for a weapon (so ratings for a roll are ratings for the god roll.)

**Comment by gdiab** [comment]
This is back in scope now?

**Comment by kyleshay** [comment]
yeah, I think so - @48klocs ?

**Comment by 48klocs** [comment]
No, still not possible based on where we’re at. I’m working on something that will read in/maybe let you define your platonic rolls and “rate” weapons based off of that.
