### ISSUE TITLE
Extrapolate ratings for perks

### ISSUE THREAD

**Issue by chrisfried** [DestinyItemManager/DIM#1737]
The top roll ratings for each gun will likely have very similar perks, but each with a few perks that never get used and don't actually factor into a roll's godliness. It should be possible (though I have no idea if it's practical) to use roll ratings to suss out which perks actually matter for a gun and/or archetype and highlight those perks for a user.

**Comment by kyleshay** [comment]
No longer in the scope for D1, as D2 perks are all predefined for a gun
