### ISSUE TITLE
Allow users to delete their review

### ISSUE THREAD

**Issue by chrisfried** [DestinyItemManager/DIM#1739]

**Comment by 48klocs** [comment]
There's no API call for this (yet), but good idea!

**Comment by kyleshay** [comment]
could we just send a request to clear out the text area (but keep the 👍 👎 ) 

that is, keep the rating but kill the review

**Comment by 48klocs** [comment]
@kyleshay we could, but I’m not sure if that rises to the point of baking in UI affordances to make it easier than it is. 

Actual deletion of ratings is not possible and it gets tricky - if you delete your instance of an item, how would you delete the review associated with it? That’s basically why delete isn’t in there.

**Comment by kyleshay** [comment]
That's true... I think I may be fine w/ closing this. 

Maybe if there is enough ask, users could log into DTR and view/manage all of their reviews they've made over there.
