### ISSUE TITLE
Transifex Integration with Travis

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#1753]
https://docs.transifex.com/integrations/github#integrating-the-client-with-travis-ci

This would automatically allow for updating our dim-en.json whenever there are changes and automatically pull down any updated translations from transifex.

**Comment by bhollis** [comment]
Oh, that's exciting!

**Comment by delphiactual** [comment]
As I have currently pushed the Google Drive translations to Transifex, this needs to wait until after #1662 is merged

**Comment by delphiactual** [comment]
#1769
