### ISSUE TITLE
Weapon Rating should ignore elemental damage node for building roll

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#1760]
Why do these `Stellar Vestige`s not have the same rating, when the `QUANTIPLASM~`s do?
![screenshot 2017-06-20 10 02 21](https://user-images.githubusercontent.com/4798491/27343314-b1e08550-559f-11e7-915e-5faa4c9d397a.png)

![screenshot 2017-06-20 10 02 39](https://user-images.githubusercontent.com/4798491/27343318-b4a4d296-559f-11e7-9ec0-6b181fdf2bcd.png)
EDIT: Both guns have static rolls with a random element... Both QUANTIPLASM~'s show the same reviews, so this is very confusing.

**Comment by kyleshay** [comment]
Guessing because the burns are different (if we're not, we should probably ignore the burn.)

**Comment by delphiactual** [comment]
The QUANTIPLASM~'s are different burns tho, hence the question

**Comment by kyleshay** [comment]
oh right, strange...! didn't notice that since it wasn't on the perk tree.

**Comment by 48klocs** [comment]
@delphiactual in the web dev console's network tab, could you capture the data being sent to (api URL)/reviews for those two disjointed items?

If you could get me the request and response payload, that'd be super.  There could be a quirk in the way that we generate and communicate rolls to the API.

**Comment by delphiactual** [comment]
```
InstanceId: "6917529130527361220"
referenceId: 2968802931
roll: "00,2421244048;10,597127202;22o,839929915;30o;50,2868044506;60o,2868044506;70;80;90;a0,1563623317;b0"
selectedPerks:"22o;3;6"
```
```
instanceId:"6917529129838628482"
referenceId:2968802931
roll:
"00,2421244048;10,597127202;21o,233596484;30o;50,2868044506;60o,2868044506;70;80;90;a0,1563623317;b0"
selectedPerks:"21o;3;6"
```

```
{"perkHash":233596484,"displayIcon":"/img/misc/missing_icon.png","perkIdentifier":"PERK_THERMAL_DAMAGE","isDisplayable":false,"perkGroups":{"weaponPerformance":0,"impactEffects":0,"guardianAttributes":0,"lightAbilities":0,"damageTypes":4},"hash":233596484,"index":0,"redacted":false}
```

the other is `20o,3614988247`
so we just need to filter those out of the roll some how...
`22o,839929915`, `21o,233596484`, `20o,3614988247`

**Comment by 48klocs** [comment]
@delphiactual I discussed this problem case with the API folks.

We'll continue to compute and send the roll the same way we have been, they're ignoring non-random (think: exotic weapons and the WotM legendaries, where the perks are all fixed) and element-based perks when looking up reviews.

This should be fixed moving forwards.  I'm not 100% sure whether or not they went ahead and merged pre-fix reviews or not.
