### ISSUE TITLE
Supporting DIM - button missing

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#1761]
Noticed the button is missing to become a backer-

<img width="845" alt="screen shot 2017-06-20 at 9 38 54 am" src="https://user-images.githubusercontent.com/424158/27344782-5bae1696-559c-11e7-8170-844e17225a42.png">

**Comment by jflayhart** [comment]
Looks like in the README too? I could pick this up as an easy re-entry task... anything special about this button besides just looking through the commit history to see how it was originally done?

https://github.com/DestinyItemManager/DIM/commit/abe40e3674a6557bf2dd409b72bf9e8a89305282

**Comment by bhollis** [comment]
Yeah, should just be a link. Thanks!

**Comment by jflayhart** [comment]
Hope this is what we want: https://github.com/DestinyItemManager/DIM/pull/1780
