### ISSUE TITLE
Cache ratings to item instances

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#1762]
We should eventually consider caching the item ratings to each item instance so that DIM shows the rating without the lag from fetching the ratings from Destiny Tracker. After the data comes back it can update.

**Comment by 48klocs** [comment]
Could you clarify a bit?  reviewDataCache does client-side caching, but with some intentional (and unintentional) limitations.

**Comment by bhollis** [comment]
I think he means persistent caching in IndexedDB so we can quickly restore ratings while freshening them up via the API in the background.

**Comment by kyleshay** [comment]
They seem to come back fast enough now. I don't think it's worth the overhead of adding the code/storage for this
