### ISSUE TITLE
I can not see the configuration control?

### ISSUE THREAD

**Issue by MAF-6** [DestinyItemManager/DIM#1779]
Good afternoon.
Friend DIM developer, follow in attached print of the screen of my Smartphone.
Why in Smarthphone the web version of DIM I can not see the configuration control?
![a2df974f-b76e-4110-92c0-7479e6950a88](https://user-images.githubusercontent.com/29663875/27494285-926af274-5823-11e7-95c1-818d0aed8e2f.jpg)

**Comment by delphiactual** [comment]
What smartphone and webbrowser are you using?

**Comment by MAF-6** [comment]
Lumia 1320, Windows 8.1, internet Explorer

**Comment by delphiactual** [comment]
can you try in chrome?

**Comment by MAF-6** [comment]
In Chrome This OK, the problem is on my cellphone.

**Comment by delphiactual** [comment]
http://alternativeto.net/software/firefox/?platform=windows-phone

Understand can you try in Opera on your phone

https://www.microsoft.com/en-us/store/p/opera-mini/9wzdncrdmtk6

**Comment by bhollis** [comment]
I'm afraid we don't support Internet Explorer (mobile or desktop). Nor do we support that version of Opera Mini. You'll have to use a different device.
