### ISSUE TITLE
TrackerErrorHandler: $q of undefined

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#1798]
See these errors in the console.

![image](https://user-images.githubusercontent.com/984608/27513736-da456e66-5937-11e7-8e39-2eff79367450.png)

**Comment by bhollis** [comment]
@48klocs they appear to happen when the reviews API is throwing 500s, as it is now.

**Comment by bhollis** [comment]
BTW, this is why I generally prefer capturing dependencies in a closure rather than assigning them to properties in a class - then you never have to worry about what `this` gets bound to at any given moment.
