### ISSUE TITLE
Changelog doesn't show for prod website

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#1800]
I think the problem is that we're firing the toaster before there's a toaster control in the view hierarchy (we're running it from "run").

**Comment by delphiactual** [comment]
Actually I think I ran into this with `DidYouKnow` during the Template transistion.

https://github.com/DestinyItemManager/DIM/pull/1766#issuecomment-309930800
https://github.com/DestinyItemManager/DIM/pull/1766/commits/f7efc0e5677deb266732a383e482c55c13af6318
body: does not seem to like imported templates

**Comment by bhollis** [comment]
Maybe you need `bodyOutputType: 'trustedHtml'`?
