### ISSUE TITLE
[bug] Locking in Loadout builder doesn't work in Chrome extension

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#1810]
Select the loadout builder, click Lock Equipped.

With the Chrome extension locking equipment doesn't change the filter.  With the beta website it does.

Chrome extension: Version 4.1.2 (release), built on 2017-6-26 08:47:07

![image](https://user-images.githubusercontent.com/25425159/27526187-5b01dbba-5a83-11e7-887f-e29da4338404.png)

Beta website: Version 4.1.2.1010 (beta), built on 2017-6-26 14:56:00

![image](https://user-images.githubusercontent.com/25425159/27526210-736b5c58-5a83-11e7-8a3e-13d05529c5b3.png)

**Comment by bhollis** [comment]
Hmm, it's working OK for me with the release extension version:

![screen shot 2017-06-26 at 12 25 00 am](https://user-images.githubusercontent.com/313208/27528583-f3872558-5a05-11e7-93e5-5aeae14b3bce.png)

Could you check the console to see if something's throwing a specific error? Also, could you open up the "Advanced Options" on beta, there?

**Comment by philkernick** [comment]
And now I can't replicate it!  Since posting the bug I've quit and restarted Chrome and now it works as expected.  The "Advanced Options" were the same on both.

Looking in the console on both I don't see any errors thrown.

I don't know what happened, but if it happens again, I'll check the console and reopen this bug.

**Comment by bhollis** [comment]
Cool, thanks!
