### ISSUE TITLE
Beta Web app android/Chrome browser crash

### ISSUE THREAD

**Issue by adamksib** [DestinyItemManager/DIM#1817]
In the new beta Web app I'm getting an "oh snap" chrome error message. 

Currently can't use beta app on phone but could before the weekend. 

One plus 3t

Chrome 58.0.3029.83

Android 7.1.1

Works fine for me on Chrome on Windows 7.

**Comment by adamksib** [comment]
Additional info: background, top menu text, logo and icons appear before crash occurs.

**Comment by adamksib** [comment]
Example of behaviour https://youtu.be/lbmeSWAzLTk

**Comment by bhollis** [comment]
This is probably your browser crashing on web assembly. What browser version and OS version and device are you using?

-Ben

**Comment by bhollis** [comment]
Oh, I see your versions. Yeah, WebAssembly is definitely enabled on that browser, but may be buggy. I wonder how widespread this is. 

-Ben

**Comment by bhollis** [comment]
I've disabled wasm for now, it apparently doesn't play well with Chrome for Android.
