### ISSUE TITLE
Where are my loadouts?

### ISSUE THREAD

**Issue by edmiller47** [DestinyItemManager/DIM#1818]
Tried the web version today. It looks great!

But where are the loadouts I have built on my Chrome version? They don't appear in the web app.

**Comment by bhollis** [comment]
The website uses different storage, so nothing transfers over. Next week we're launching an import feature so you can copy them over. 

-Ben

**Comment by edmiller47** [comment]
May be a silly question, but instead of implementing an import feature, why not revise the Chrome version to use the same storage as the website?

**Comment by kyleshay** [comment]
#1797 will make the migration to the website easier for users with saved configurations from the extension.

**Comment by edmiller47** [comment]
So the chrome extension will be retired and replaced by the web app?

On Jun 26, 2017, at 5:50 PM, kyle shay <notifications@github.com> wrote:

#1797 will make the migration to the website easier for users with saved configurations from the extension.

**Comment by bhollis** [comment]
That's correct! It'll stay around as just a button that loads the website (and helps you migrate your data into the website).
