### ISSUE TITLE
dimStoreService has a hardcoded pointer to beta site

### ISSUE THREAD

**Issue by 48klocs** [DestinyItemManager/DIM#1819]
dimStoreService.factory.js line 47:

      // In dev, use a local copy of the JSON for testing
      const url = ($DIM_FLAVOR === 'dev')
              ? '/data/classified.json'
              : 'https://beta.destinyitemmanager.com/data/classified.json';

When using app.destinyitemmanager.com, this leads to both a CSP error and a "couldn't load classified info" error.

**Comment by bhollis** [comment]
Yep, that's intentional, and the CSP will be fixed in next week's release. 

-Ben

**Comment by 48klocs** [comment]
OK!
