### ISSUE TITLE
Wrong icon for Android?

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#1827]
I saw in a couple Android screenshots that we are using the iOS icon instead of the Android one. According to [our manifest](https://app.destinyitemmanager.com/manifest-webapp.json) we should be using the right one, but Chrome for Android may not be respecting our manifest `link` element. See [the Add to Homescreen docs](https://developer.chrome.com/multidevice/android/installtohomescreen).

iOS:
![](https://app.destinyitemmanager.com/apple-touch-icon.png)

Android:
![](https://app.destinyitemmanager.com/android-chrome-192x192.png)

**Comment by kyleshay** [comment]
Looks like the manifest file is missing from the web app, though it does exists on the server.

https://app.destinyitemmanager.com/manifest-webapp.json

Maybe it wants to be called `manifest.json`?

<img width="1144" alt="screen shot 2017-06-27 at 9 33 52 am" src="https://user-images.githubusercontent.com/424158/27600538-265dfaa8-5b21-11e7-9685-ee026cb13b4d.png">

**Comment by bhollis** [comment]
I managed to fix this by adjusting the CSP and mime type.
