### ISSUE TITLE
Bug with writing reviews

### ISSUE THREAD

**Issue by SublymeRick** [DestinyItemManager/DIM#1829]
Not a big deal but I figured I would mention it. I wrote a review on two guns, now every time I look at the reviews of those guns, it does not show the reviews, it only shows my review with a submit / cancel button.... again... I've already submitted it, if I click cancel I see the reviews and I see my review there. If this is your way of allowing us to edit our review its strange to say the least... just put an "edit review" link in the review or at the top to show that screen again or something, idk.

**Comment by delphiactual** [comment]
@48klocs

**Comment by 48klocs** [comment]
Good point - I'll have to revisit this workflow. It should be reasonably easy to promote a user review to emulate a retrieved review on a temporary basis.
