### ISSUE TITLE
Bug - item popups do not display, settings menu shows up half off screen.

### ISSUE THREAD

**Issue by Pbixy** [DestinyItemManager/DIM#1830]
Using the beta.destinyitemmanager.com, Version 4.1.2.1023 (beta), built on 6/27/2017, 3:20:09 AM.
Clicking on items doesn't bring up a popup (at least not visibly). After trying to get an item popup, if clicking the loadouts dropdowns, they appear where the item popup should have (i.e. under that item). This behavior was reproduced with multiple items. The Settings menu also appears to move around depending on what item popup last failed to open, though not directly underneath, rather off to the side and down, as if it were using the failed popup's location instead of the top left corner of the screen.
Moving items by dragging seems to function normally,
I've already troubleshooted by reloading the page, along with signing out and back in to Bungie.

**Comment by delphiactual** [comment]
Browser, and OS?

**Comment by Pbixy** [comment]
Using Chrome Version 58.0.3029.110 on Windows 7.

**Comment by Pbixy** [comment]
I guess we'll have to wait until the Destiny Server Maintenance ends. All I'm getting now is the Bungie.net Error that states that it can't find a Destiny account.

**Comment by Pbixy** [comment]
Last night post-server maintenance, this issue persisted. This morning, it's apparently gone. Currently using the beta.destinyitemmanager.com site, Version 4.1.2.1029 (beta), built on 6/28/2017, 12:59:31 AM, on Chrome Version 58.0.3029.110 on Windows 7.

I'll close this out, if no one minds.
