### ISSUE TITLE
Loadout builder not comprehensive

### ISSUE THREAD

**Issue by JAMeador13** [DestinyItemManager/DIM#1831]
Some way or another the loadout builder isn't providing all of the possibilities for loadouts when trying to put them together. I'm not sure if it's an issue with the Bungie API returning incorrect values (because they have been listed incorrectly on their website before) or if it's an issue with the logic in the plugin.

**Comment by kyleshay** [comment]
Hi @JAMeador13! Could you please provide some more detail? We only show you the best options available. If you have a helmet that is 46 intellect and 46 strength, we don't bother showing you a helmet with 44 intellect and 46 strength, even if it would still give you a T12 loadout. We do that just because we want to limit the options on the page. If you don't like that 46/46 helmet, you can shift click it and it will exclude it. Otherwise, drag the 44/46 helmet to the 'lock' section.

Also on the loadout builder page, click the 'advanced options' and make sure to have 'full mode' selected.

**Comment by bhollis** [comment]
Linking #1475 for previous discussion on this.

**Comment by kyleshay** [comment]
Please comment and re-open if you have any thoughts or what you were experiencing isn't what I described, thanks!

**Comment by JAMeador13** [comment]
Ok, then it's not so much a bug as it would be a feature request. It would be great to be able to have a complete return, so that I could make loadouts with different armor pieces. As it is now, I have several builds I like to run for different purposes, but a lot of them include armor that is used in other builds. If I do the "equip on current character" option, it will immediately equip all of the armor, but because it can't change node selection, I have to go into the menu, and figure out which nodes to select. If I had sets of completely different armor, that wouldn't be a problem, or even if there was a way to display all of my loadouts with the correct node selections. I don't even use the loadout feature because of that. It's faster to just remake the loadout every time than save the loadout and go through and try to figure out which nodes to use. 

All of that said, I guess it's actually 2 feature requests. 

1. Option to display all possible combinations for different builds.
2. Option to display all saved loadouts with which nodes to select.

I know that all seems very niche, but if I want to switch loadouts in the middle of a league match, I don't really have time to sit and tinker with my gear while my teammates need me to shoot people. I <3 DIM and only want it to get better.

**Comment by kyleshay** [comment]
Cool, thanks for the write up. We can consider those options.

I was also thinking -- what about an option to save loadout builder configurations? That way your loadouts are always dynamic. Another setting we could add is to make the loadout builder prefer currently set nodes (or sort by the least number of nodes required to swap,) that way you don't need to figure out what to switch out.

For D2, if possible, I would like to eventually merge the two ways that users can build, save, and apply loadouts. Having it just simplified in general without losing functionality would be great.

**Comment by JAMeador13** [comment]
That's a good idea. Having a way to see your loadouts from the builder with the node selection would be so nice.

Another idea, could be to make it where you put in all of the different loadouts in like a "wishlist," then have it generate as many of them as possible, with as little node swaps and what not as possible. Though, for that, I'm not sure how practical it is because the only solution that comes to mind now uses recursion. Though it wouldn't be dealing with massive data inputs...

I haven't downloaded the stuff for the dev environment to play with it at all, so I'm not really sure how it's all structured and if that would not stuff down too much.
