### ISSUE TITLE
LF Guardians that play destiny to play with!!

### ISSUE THREAD

**Issue by SublymeRick** [DestinyItemManager/DIM#1835]
LOL! Dont mean to turn the issue tracker into an LFG but being a web application developer my self I thought it would be cool to meet other developers that play destiny... and this strikes me as a good place to find some ;)

Anyway if this is not cool, just delete it or close it....

Otherwise, add me on PSN digitsix
My coder background, is that I've been working with PHP for about 17 years HTML / CSS longer and javascript for about 10 years. Been mostly a jQuery dev on the front end of things but recently started to rethink my whole life when I found reactjs so I'm getting into that now. I also use CraftCMS as my go-to cms for client sites and I'll be starting a new music player site for underground rock bands that works similar to pandora. I'm going to use Craft for the back end and I'm going to do the whole front end in reactjs. I'm pretty excited for it as its gonna be a fun project.

**Comment by kyleshay** [comment]
Hi @SublymeRick! We'd like to keep the issue tracker clean for issues related to DIM. 

Reach out to us on twitter at https://twitter.com/ThisIsDIM - a couple other developers are also active on twitter and it may be a better way to find people to play with! Unfortunately, I'm on xbox though :(
