### ISSUE TITLE
Color-Blind Settings?

### ISSUE THREAD

**Issue by Kyle-Simpson** [DestinyItemManager/DIM#1838]
I was just looking at the new version of DIM and while I really like the implementation of the element-based color-coded triangles on each weapon, as a color blind person, the arc and void triangles look identical.  It's not a huge issue since there's still the option to add the icons for the damage type, but it would still be nice to have the option to see the entire page in color-blind modes.

**Comment by bhollis** [comment]
We added a setting a while back specifically to help with this - look for "show element icons"

-Ben
