### ISSUE TITLE
Loadout Transfer Errors

### ISSUE THREAD

**Issue by nki2bpz** [DestinyItemManager/DIM#1846]
As of the last couple of builds Loadout transfers have been producing more and more errors that there are no slots open to move items to while leaving entire empty sections on alternate characters. ie during transfer, vault is now full, but alt character heavy has 6 empty slots

**Comment by bhollis** [comment]
What are the steps to reproduce this problem?

**Comment by nki2bpz** [comment]
Fill up your inventory till you only have a couple free spaces,  then equip a loadout with a lot of guns to move around? Something changed about two release builds back where it used to just move items back and forth till it got everything moved. Now it just seems to forget where the empty spaces are?

-------- Original message --------

**Comment by bhollis** [comment]
I'm asking for specific instructions because I created some loadouts myself and tried moving them, and everything was OK.

**Comment by delphiactual** [comment]
http://www.screentogif.com/ is great for capturing what is happening

**Comment by nki2bpz** [comment]
how many free spots did you have in your weapon inventory? Including vault? I usually only have 4 to 6 empty slots between all characters and vault. I've always been a hoarder this is probably why I noticed the difference. I'll see if u can reproduce it reliably.

-------- Original message --------

**Comment by nki2bpz** [comment]
![dim errors](https://user-images.githubusercontent.com/15946723/28249758-ccd69108-6a29-11e7-9133-de1590bd06d2.gif)

This is an extreme case of only having 2 free weapon slots. I figured I'd force it to error then back off till it doesn't?

**Comment by bhollis** [comment]
Great! Looks like some calculation is off. It's been months since we changed anything relating to that, so it might be a while before it gets fixed. 

-Ben

**Comment by nki2bpz** [comment]
It's weird cuz it will start with primary, throw the errors, then move to secondary, get a couple moves in then throw the errors again, then heavy.

-------- Original message --------

**Comment by bhollis** [comment]
@nki2bpz have you still been seeing this?

**Comment by nki2bpz** [comment]
I can not say for certain as i haven't played on D1 since D2 came out and my d2 vault and characters haven't been that full yet.

-------- Original message --------
