### ISSUE TITLE
Filter logic seems to have flipped from "and" to "or"

### ISSUE THREAD

**Issue by javalasers** [DestinyItemManager/DIM#186]
Attaching screenshot using the example query from the help text [is:arc is:solar]. As the help text says, this should highlight no weapons (no weapon is both arc and solar). But instead it highlights all arc weapons and all solar weapons. Same thing seems to happen for other filter combinations, e.g., [is:legendary is:unlocked]

Thanks for all your work on DIM!

DIM version: 3.0.13
Chrome version [on OSX]: 43.0.2357.134 (Official Build) (64-bit)

![screen shot 2015-07-25 at 12 02 19 pm](https://cloud.githubusercontent.com/assets/1702322/8890851/3998d51a-32c5-11e5-9055-b9591e0eb472.png)

**Comment by SunburnedGoose** [comment]
I'll look at that. There was a contribution the refactored the code so I'll
look it up.

**Comment by kyleshay** [comment]
can we close this with v3.0.17?
