### ISSUE TITLE
Guided search

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#1876]
Right now our search has autocomplete and is very powerful, but some folks don't know how to use it. We should implement a "guided" search where properties can be chosen from menus, like the Bungie.net gear manager does.

**Comment by kyleshay** [comment]
Just playing around with some ideas... https://jsfiddle.net/dqerzjgw/

😇 I'm not trying to re-introduce jquery, but their autocomplete library is easy to prototype with.

**Comment by kyleshay** [comment]
Just playing around with some UX ideas around all of the features we have out there for filter/search... https://jsfiddle.net/dqerzjgw/3/

😇 I'm not trying to re-introduce jquery, but their autocomplete library is easy to prototype with.

Think that it would still be cool if things were tokenized. For the saved searches, maybe a gear icon on the same line that when clicked shows options to lock/tag/equip/create notification alerts/auto apply on page load/etc.

**Comment by kyleshay** [comment]
Open to other ideas, just throwing some initial thoughts out there. Is maybe a little awkward to have those select dropdowns inside of a dropdown, but maybe it could work.. Would be nice to think about mobile as well, maybe it could just go full width of the screen.

Also maybe it could track searches (just locally, not to a server) and we could auto suggest saved/recent/popular searches.

**Comment by kyleshay** [comment]
Should maybe track this elsewhere but, we could also consider supporting grouping of searches and split them on `or` so we could build things like:

`(impact:>90 is:handcannon) or (impact:<30 is:pulserifle)`... etc.

**Comment by kyleshay** [comment]
Partially inspired by slacks search functionality - 
<img width="310" alt="screen shot 2017-07-26 at 9 23 02 am" src="https://user-images.githubusercontent.com/424158/28729694-2d68d6c8-7382-11e7-96bc-0cade78565fb.png">

**Comment by bhollis** [comment]
+1 to all that. I'm planning on having a dropdown under search at some point, so maybe we don't want to overload that though.

**Comment by CodeBeast357** [comment]
I'd like to suggest having those filters shown in the item popup. The item's corresponding filters could be hinted at what could be used to select it.

**Comment by bhollis** [comment]
I think between the autocomplete and the new searchable filter help, we have close enough to this.
