### ISSUE TITLE
Options to disable pop-ups like new version or new items

### ISSUE THREAD

**Issue by dhinged** [DestinyItemManager/DIM#1878]
I play Destiny just several times a week now and so it's more often I see pop-ups like the "new version" one that gets in the way of my vault each time I open the app unless I click the check box to hide it... very annoying.

While I enjoy the new-item shine, I don't care for the "Clear New Items" pop-up also in the way of vault items, which requires scrolling or clicking it to get to items it obscures.

I'm seeing no options to disable these or just have them in a different place out of the way, like a little dedicated spot up at the top or something like that. Would be really nice to have these in noticeable places that don't obscure inventory items or anything else. There's plenty of empty space in the top bar.

My specific request is to just have a grayed out icon or text for these notifications, so that they turn brighter when activated and allow clicking to view or perform an action etc.

**Comment by bhollis** [comment]
#1044
