### ISSUE TITLE
Icons obscured by dialogs

### ISSUE THREAD

**Issue by Funktion29** [DestinyItemManager/DIM#1882]
In the latest build 4.2.4 (release and beta) when you click an item it’s dialog covers up the icon so you can’t clear the dialog, unless you click a different icon, etc.

I’ve seen this on iPhone in Safari and Chrome, iOS v. 10.3.2
I’ve seen this on iPad in Safari and Chrome iOS v. 11.0

Not sure if this was present in older DIM versions as I’ve not used it in a couple weeks.

Thanks
![image](https://user-images.githubusercontent.com/22829473/27841685-5bf68648-60b8-11e7-9357-a28bc60115bf.jpg)

**Comment by Funktion29** [comment]
I'm also seeing this on Chrome59.0.3071.115 (Official Build) (64-bit) with the extensions, (beta and regular)

**Comment by bhollis** [comment]
Thanks for the report. We'll have a fix available by this Saturday's release.
