### ISSUE TITLE
Xur not visible in beta website

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#1893]
This weekend in the beta website Xur is not visible, either in the top menu, or in the vendors screen.

Might be because it's also Iron Banner.

It is visible in the release chrome extension.

**Comment by bhollis** [comment]
A quick bisect fingers 8f65ff130d7be1f5948c1b4bd9d1f757c773d005 as the bad commit - that's the one that re-introduced weapon ratings into vendors. I'll comb through that code.

**Comment by bhollis** [comment]
Fixed!
