### ISSUE TITLE
Language setting not applying for gear in the website

### ISSUE THREAD

**Issue by miguelveraleon** [DestinyItemManager/DIM#1900]
Hello, I have DIM set to english language (screenshot 1), and as such it shows the menus and section titles in english, but all the gear and the character titles are in spanish (screenshot 2). My OS language is spanish, so I'm guessing it could have something to do with it.

Screenshot 1
![image](https://user-images.githubusercontent.com/30012372/27990594-b79b36a0-6429-11e7-95af-a617344b0a30.png)

Screenshot 2
![image](https://user-images.githubusercontent.com/30012372/27990578-4d607cbe-6429-11e7-8d93-05f113bbae7d.png)

**Comment by delphiactual** [comment]
after changing the language you must refresh (f5)

**Comment by miguelveraleon** [comment]
It is refreshed.

**Comment by delphiactual** [comment]
I'll change my OS language and try to reproduce to debug. Thank you for the report.

**Comment by miguelveraleon** [comment]
No problem. It's a recent issue too, just in case. I've used the site before, usually in english, and it's the first time I encounter this.
