### ISSUE TITLE
Import export  on iOS 

### ISSUE THREAD

**Issue by Funktion29** [DestinyItemManager/DIM#1905]
When trying to export the settings on iOS, it just takes you to another webpage with the prefix blob:
blob:https://beta.destinyitemmanager.com/630ea04a-dc16-44d1-9ac9-eceaba4f57d4

This page then has what I assume are all the settings in plain text, but there doesn’t seem to be a way to save this file. Which I then assume would be imported, the dialog works for importing, but again no idea what to import. (File type, etc.)

iOS 10.3.2 and 11.0 beta, Safari, beta and regular DIM.

**Comment by SunburnedGoose** [comment]
For the near term, I don't believe this feature will work on mobile platforms because of the file type that is being used to move the data.  You'll have to use a desktop client.

**Comment by bhollis** [comment]
I'll see about disabling it on iOS. Not sure how Android handles it, and iOS 11 should bring changes here...

**Comment by delphiactual** [comment]
Works fine on Android
