### ISSUE TITLE
Change Google Drive Account

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#1907]
Clicking `Log out of Google Drive` and subsequently clicking `Log in to Google Drive` will log back into the previously logged in google drive instead of allowing for an account change.

**Comment by bhollis** [comment]
Thanks, Google.

**Comment by JStuve** [comment]
I believe this is invalid. Just tested and was able to switch to different Google accounts.

**Comment by delphiactual** [comment]
Nope still auto logs in to previous account.
![peek 2019-01-13 16-08](https://user-images.githubusercontent.com/4798491/51091844-97e81200-174d-11e9-8ce4-4de13b069030.gif)

**Comment by bhollis** [comment]
This is obsoleted by #4418.
