### ISSUE TITLE
Bad reviews on meta-disturbing weapons

### ISSUE THREAD

**Issue by lookitsluc** [DestinyItemManager/DIM#1908]
There are plenty of "reviews" being published on DIM that are abusing the great system you guys are trying to build. People chastising those who use the gun, or generally letting their opinions getting in the way of giving objective reviews.  Take a look at Universal Remote, for example. There are _several_ users whining with their personal biases after getting shot killed one-too-many times that are bringing the general average rating of the gun down substantially.  I think it'd be great if there was some sort of peer-review or reputation system where you can up- or down-vote reviewers themselves so those who are problematic don't ruin the experience for everyone else who continue to write informative responses.  Attached is a screen-grab of some knee-jerk reviewers who don't contribute positively, in my opinion. Thanks for your time. Keep up the great work.
![universal whinings](https://user-images.githubusercontent.com/30014591/27991347-9fdff1c8-6441-11e7-99bb-e2f811a98411.PNG)

**Comment by SunburnedGoose** [comment]
Agree on some of the peer reviewing, slackoverflow style maintenance of these reviews.

**Comment by 48klocs** [comment]
I was hoping for better behavior, but this is the internet.

Reporting will be coming. I think I'll want to compile a list of people that the user has reported locally, so that we automatically hide other reviews that they wrote (because I'm not trying to enable any slapfights).

**Comment by bladefist** [comment]
That's a good idea. Both of them.  What about like reddit? Sort by score.  0 through -2 will be at the bottom ... -3 and beyond we hide it from the UI.

**Comment by 48klocs** [comment]
Reporting's live, so this can be closed.
