### ISSUE TITLE
Keep transfer options in Item Popup close to the Item

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#1926]
When I open the popup when clicking on an item, the transfer options are far away.  I often have to scroll which is notorious on small screens.

Keep the move options closer to the item so they are always on screen.

**Comment by bhollis** [comment]
Definitely agree! This guy needs some redesigning

-Ben

**Comment by Robert-Roppo** [comment]
![image](https://user-images.githubusercontent.com/12192908/28143625-6d0e20f8-671b-11e7-96ef-243919c661ad.png)

Are you talking about something like this?

**Comment by bhollis** [comment]
Something like that. I think it'll want to be part of a bit of a redesign, since that looks kinda awkward.

**Comment by kyleshay** [comment]
Linking the other move popup ticket #1129 for if we want to tackle the redesign in a consolidated issue.

**Comment by delphiactual** [comment]
During this redesign we should also remove text from the buttons for `equip`, `store`, `vault`, `take`, and `split`. When translated these words are normally longer than 7 or 8 characters, we should look for icons to use instead.

**Comment by kyleshay** [comment]
Sounds good! If we have the bandwidth we could also consider designing some icons. 

Could also explore things where a single tap only opens move dialog, and a long tap opens the full details. Desktop could do something different, like always open both on click, or just show move popup on hover and details on click....

May be worth waiting for D2 launch for some of this redesign because we'll also need to incorporate weapon mods, and possibly other things.

**Comment by Nahcc** [comment]
I know this is an old thread but would like to help in any design areas. This was a quick ps I can code this as well if needed.


![guncreen_s](https://user-images.githubusercontent.com/5158989/29246023-865e51ba-801e-11e7-802d-1b66fbfed89f.png)

**Comment by bhollis** [comment]
Thanks! This is coming up soon, as part of our mobile responsive work. 

-Ben

**Comment by shockthealien** [comment]
I think it looks kinda cluttered. How about adding another tab next to Overview and Reviews for the transfer options? that way is easily accessible without scrolling for small screens and its neat and cleanly implemented

**Comment by Nahcc** [comment]
I totally agree on clutter.

I will mock that up, I have some ideas on flattening the design of the icons to allow easier use/ recognition of function on a mobile device as mentioned above as well.

**Comment by Nahcc** [comment]
![mockup](https://user-images.githubusercontent.com/5158989/29256410-cc7968ce-80dc-11e7-8b20-0f4200b89241.png)

Excuse my spelling and omission of details from top banner, slightly ruff and fast mockup 
(n.b. stay at home dad with two kids under 3)

Based of a iPhone 7 screen.
Design cues are taken from the apple screen, the change to circles throughout iOS made it easier for my fingers to locate button presses.
Letters for the icons allow 
- flatter design
- the argument of icons slowing load times
- but with letters the language issue would be a problem? 
- (labels underneath could fix that? example provided for the tabs)

Icons do however allow a somewhat universal understanding
Colour change of icons was to show look of buttons with different colours not a design element.

I can work on those other screens for this popup, with this design if there is merit in this style fo flat design.

**Comment by Nahcc** [comment]
![screen shot 2017-08-14 at 10 57 55 am](https://user-images.githubusercontent.com/5158989/29256791-91cc8712-80df-11e7-934e-2be693a253d2.png)
Excuse my spelling and omission of details from top banner, slightly ruff and fast mockup
(n.b. stay at home dad with two kids under 3)

Based of a iPhone 7 screen.
Design cues are taken from the apple screen, the change to circles throughout iOS made it easier for my fingers to locate button presses.
Letters for the icons allow

flatter design
the argument of icons slowing load times
but with letters the language issue would be a problem?
(labels underneath could fix that? example provided for the tabs)
Icons do however allow a somewhat universal understanding
Colour change of icons was to show look of buttons with different colours not a design element.

I can work on those other screens for this popup, with this design if there is merit in this style fo flat design.

**Comment by shockthealien** [comment]
Thats cool, however at this point in the life of D1 DIM I would avoid changing the style and stick with the elements we have. I would leave the new ideas and style for D2 DIM for the next version to be a surprise and refresh and have the impact it deserves

**Comment by kyleshay** [comment]
![sc](https://user-images.githubusercontent.com/424158/94483003-0e7dab00-018f-11eb-96ad-cf4cf572b4be.jpeg)
