### ISSUE TITLE
Mobile graphics diplaying incorrectly

### ISSUE THREAD

**Issue by makhren** [DestinyItemManager/DIM#1929]
When viewing the record books on my phone via the beta site the icons for the nodes are all different shapes. Some are the correct circle shape but most are oval shapes like they've been squished. Not all the same width either. It looks like the record book entries are auto sizing cells in a table but the icons don't have their size ratios locked. Don't see how to attach a screenshot or I'd show what I mean

**Comment by SunburnedGoose** [comment]
I don't think we've touched the record book view for mobile yet.

**Comment by makhren** [comment]
I figured it's probably low priority, but thought you'd like to know about it.
