### ISSUE TITLE
Clear new items button errors and doesn't work

### ISSUE THREAD

**Issue by chrismcenteer** [DestinyItemManager/DIM#1931]
This started a few days ago, before 4.3.0. Clicking the "Clear new items" button doesn't stop the shine animation, and the button doesn't go away. May have started on 4.2, not positive though. Causes a JS error when clicked:
![dim-error](https://user-images.githubusercontent.com/482637/28046937-29495854-65b5-11e7-97f1-2c6c45c194aa.png)

**Comment by bhollis** [comment]
Thanks for the report! This should be working again in Beta already, and it'll make it out to the release app in this Saturday's release.
