### ISSUE TITLE
Loadouts class selector broken

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#1934]
The dropdown for loadouts doesn't show anything

**Comment by delphiactual** [comment]
@bhollis on https://github.com/DestinyItemManager/DIM/blob/master/src/scripts/loadout/dimLoadout.directive.html#L11 vm.showClass is no longer being set for some reason...

**Comment by bhollis** [comment]
Ah - that's not the bug I was talking about - that's another bug! The one I was talking about was where the dropdown is there, but empty.

**Comment by delphiactual** [comment]
Still seeing this as of .1138 beta

**Comment by delphiactual** [comment]
it appears to be intermittent as it is no longer happening...
