### ISSUE TITLE
Infuse Dialog Errors

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#1943]
- [ ] Infuse Dialog now shows all costs as exotic shards
- [x] Also has an unneeded horizontal scrollbar #1950
- [x] Could possibly use some spacing near the button #1950

![screenshot 2017-07-11 02 07 30](https://user-images.githubusercontent.com/4798491/28057683-f9644846-65dd-11e7-9aa0-5fa0c507f3a3.png)

**Comment by Robert-Roppo** [comment]
I can fix this with two lines but for some reason I cannot get the project to build locally.

**Comment by delphiactual** [comment]
@Robert-Roppo what errors are you experiencing trying to build locally?

**Comment by Robert-Roppo** [comment]
@delphiactual When I run "npm run server" it's having an issue loading any of the .scss files

**Comment by delphiactual** [comment]
just as a troubleshooting idea. delete the `package-lock.json`, rerun `npm install`, then try `npm run server`

**Comment by Robert-Roppo** [comment]
@delphiactual yep that worked, it actually compiles now. Just have to get the URL it's giving me to work. Sorry first time I've used this, noobing it up.

**Comment by delphiactual** [comment]
use localhost:8080 instead of 0.0.0.0:8080 on windows

**Comment by Robert-Roppo** [comment]
@delphiactual sweet, just changed the webpack config to local host and I am good. Now I'll fix the actual issue lol thanks for your help

**Comment by Robert-Roppo** [comment]
@delphiactual is there a certain way you are supposed to login on the local host?

**Comment by delphiactual** [comment]
screenshot

**Comment by Robert-Roppo** [comment]
![image](https://user-images.githubusercontent.com/12192908/28094647-d31e7826-6652-11e7-8df9-e7b88b9de0af.png)

**Comment by Robert-Roppo** [comment]
so basically I start the local host, it say's it needs authorization to access stuff

**Comment by delphiactual** [comment]
Join the Discord. https://discord.gg/qAgCJB and I can help you more quickly and remove clutter from the github

**Comment by kyleshay** [comment]
Hi @Robert-Roppo 👋 😃 - please note anything that isn't obvious in any docs/developer page in DIM so we can streamline future first-time contributors :) Thanks delphi for helping him debug.

**Comment by Robert-Roppo** [comment]
![image](https://user-images.githubusercontent.com/12192908/28095932-1895513e-665a-11e7-9f81-d78db0c7e1fd.png)

**Comment by delphiactual** [comment]
@kyleshay @bhollis Maybe we should change the wording from `Show infusable items across all characters and vault` to `Show all infusable items`
