### ISSUE TITLE
New Dev setup skips /developer landing

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#1949]
After running `npm run server` for the first time; DIM immediately goes to the Bungie requires Authentication without going to the developer landing page first.

EDIT: This can currently be circumvented by navigating directly to https://localhost:8080/#!/developer

**Comment by bhollis** [comment]
Hmm, I wonder why. It should be redirecting to developer if you don't already have the right local storage values set: https://github.com/DestinyItemManager/DIM/blob/master/src/scripts/oauth/oauth.module.js#L11

I wonder if it's something else like the route controller in `shell.module.js` that's redirecting to login instead.

**Comment by delphiactual** [comment]
it is pretty easy to test just open chrome in incognito mode
