### ISSUE TITLE
Responsive Layout Scaffolding

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#195]
We need a CSS layout tool that supports a flexbox implementation.  The reason for this is that we need the rows for each item group to resize vertically when one column grows too large vertically.  

**I'm looking at the player that puts 36 primary weapons in their Vault.**

At the moment, whenever there is an update to an item in a store, we refresh the columns and rows.  This invokes javascript that calculates the tallest column in a row and then sets the height of every column in the row to that height.  It's slow, clunky, and doesn't always work for all items.  DIM needs a solution that relies upon the feature of the implementation, ie Flexbox.

**Comment by SunburnedGoose** [comment]
Just googling for a flexbox based responsive layout.

https://github.com/kristoferjoseph/flexboxgrid

**Comment by SunburnedGoose** [comment]
http://caniuse.com/#feat=flexbox

**Comment by jflayhart** [comment]
Looking into using [SASS](http://sass-lang.com) and [Grunt](http://gruntjs.com) to support the responsive layout architecture.

I have also considered using [Bootstrap](https://angular-ui.github.io/bootstrap/) as well with Angular...

**Comment by SunburnedGoose** [comment]
http://www.getmdl.io/

**Comment by jflayhart** [comment]
Regarding item image sizes, specifically the bounties section, would like to incorporate a better scaling mechanism so it doesn't look like it's too small for its container. For example, setting background-position: center; and size to 53px to bounties makes them look more full and clear, but think SASS and implementing this responsive layout will require resizing all items appropriately.

**Comment by ritcheyer** [comment]
I have made liberal use of `flexbox` @ in my career as a web developer. Since this is a chrome extension first and foremost, you needn't worry about any sorts of compatibility issues with other browsers. Chrome's flexbox support is fantastic.

If you would like, I can be available for code reviews and such.

**Comment by SunburnedGoose** [comment]
We're moving to phones soon so it's became relevant.  I'd love to have more eyes over the code during development :)

Thanks :+1:

**Comment by ritcheyer** [comment]
@SunburnedGoose that mean this is becoming a full-fledged web-app or a native app and not a chrome extension?! I :heart: this decision!

**Comment by SunburnedGoose** [comment]
Hybrid app.

**Comment by ritcheyer** [comment]
fantastic. can't wait. :)

**Comment by jflayhart** [comment]
Another thing to consider is Foundation's a le cart download option: http://foundation.zurb.com/develop/download.html

However, I really like http://flexboxgrid.com/ in the V4 branch.

**Comment by spentacular** [comment]
let me +1 @jflayhart with the flexboxgrid.com. I've never used it as the full scaffold, but it's used a lot of parts and ideas from it. The problem with the big frameworks is they can create a lot of bloat quickly, and I think flexboxgrid solves the problem of being a tool that does one job really well.

I'd be happy to help/code/review as well.

**Comment by SunburnedGoose** [comment]
Just wished it has responsive hide classes of Bootstrap. Going to look at
Bootstrap 4 Alpha.

**Comment by spentacular** [comment]
[Here](http://v4-alpha.getbootstrap.com/layout/responsive-utilities) they are. Looks like the grid isn't available to download from the main downloads page just yet. It would be nice if it was a bower/npm module too.

**Comment by SunburnedGoose** [comment]
Emailed ya.

**Comment by Shawful** [comment]
I like bootstrap and material design.  Both use easy to use grids that are responsive and clean.

It shouldn't take much to try that out at all.

I'm surprised that with the tech stack that <a href="http://yeoman.io/">yeoman.io</a> wasn't used, which offers bootstrap out of the box and the capability to plug in material design or other tools.  It even works with sass, grunt/gulp.

Just a tangential suggestion.  I know a refactor would probably be overkill, but probably improve organization for new eyes on the project.

**Comment by SunburnedGoose** [comment]
Look at the v4-dev branch.  We used a modified yeoman webapp generator to
make our builds.  'grunt gsd' is how we kick it off.

**Comment by Shawful** [comment]
nice

**Comment by Shawful** [comment]
hmm... `grunt serve` gets an error right out of the box:

Cannot read property 'getAll' of undefined.   Hmm...

**Comment by SunburnedGoose** [comment]
At the moment, it's just 'grunt gsd', 'grunt build' and 'grunt
build:dist'.  You have to add the /app folder as an extension to run/test
the app.  It won't work with the browser sync web server.

**Comment by kyleshay** [comment]
fixed in #601!
