### ISSUE TITLE
Improve review ordering

### ISSUE THREAD

**Issue by 48klocs** [DestinyItemManager/DIM#1954]
Reviews that the user submitted should be most prominent (to make editing easy).

Then highlighted reviewers.

Then reviews sorted by descending score (to make high score reviews easily visible and put the nasty comments out of sight (because the community rating already lets people know to avoid it)).

Then by date (to make newest high ratings visible).

**Comment by delphiactual** [comment]
@48klocs maybe user review should always be top, ease of editing and all...

**Comment by 48klocs** [comment]
And review submission is catching a 500 now (platform service's membership info changed a little).

So that'll be fixed in the same branch (I needed to test submitting to make sure order worked like I wanted it to).

**Comment by 48klocs** [comment]
And I fixed the edit region.  It got a bit tighter with some git merge madness.
