### ISSUE TITLE
missing i18n strings

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#1958]
On the Storage Page there are two hardcoded strings that I cannot locate.
`Choose File`, `No file chosen`

![screenshot 2017-07-11 22 33 40](https://user-images.githubusercontent.com/4798491/28101958-2d977f92-6689-11e7-810d-8c31b8ca8581.png)

**Comment by Robert-Roppo** [comment]
The problem with this is that both those strings are automatically part of the <input type="file"> in html and a little hard to change. I'm trying to find a way around it right now. Seems like there are a few ways around it but none that I have tried have worked.

**Comment by bhollis** [comment]
Yeah, they're built in to the browser. I'd assume on a host with a different language, they'd already be localized.
