### ISSUE TITLE
Responsive Item Store Selection

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#196]
In the desktop environment, we can show all the stores at once.  As the viewport width is reduce, we need a means to show fewer stores and let the user transition between each of them.

The question is how do we transition between stores that is similar on desktop/tablet/phone resolutions?  Do we only show more than one character when there is horizontal space available?  How do we choose the character?  Is the vault always present if space is available?

**Comment by kyleshay** [comment]
FWIW - DIM looks good on my phone when I zoom out and am in landscape mode. I can drag + drop between everything which is nice.
