### ISSUE TITLE
i18n Automation Bot

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#1963]
Upon merge of #1960, a bot service could be used to automatically:
 - clone DIM:master
 - download i18n files `grunt download_translations`
 - prettify i18n json
 - submit a PR against DIM:master (https://github.com/github/hub)

Branch should be labeled as i18n-<date>
PR message should just be i18n updates as of <date>

Should be run once a week, with the option to re-run whenever necessary.

**Comment by bhollis** [comment]
Sounds good - should be very similar to https://github.com/DestinyItemManager/dim-release-bot

**Comment by delphiactual** [comment]
https://github.com/delphiactual/dim-i18n-bot

just needs rsa tokens

**Comment by bhollis** [comment]
Is this current for the new translation service?

**Comment by delphiactual** [comment]
yes, just really need to automate running `grunt download_translations` and commit it

**Comment by bhollis** [comment]
Sorry for the delay on that. I've set up the repo with keys in it and given you permissions, and set a weekly schedule. My suggestion would be to try and get it to run daily, and both upload and download translations and make direct commits instead of a PR.

**Comment by bhollis** [comment]
Oh, I see we're already uploading on every master build. Nice!

**Comment by bhollis** [comment]
(The actual bot needs some tweaking - Hub can't work with just an SSH key)
