### ISSUE TITLE
Add Sticker Promotion to DIM Popup

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#1964]
https://twitter.com/thisisdim/status/885261823884361728

Want to add the contents of this tweet to a popup in the app to notify players not using twitter. 

There is an issue with popup slot staying dismissed right now. :/

**Comment by kyleshay** [comment]
It would be nice to have a general purpose remote update to appear in DIM, could be if we add a specific hashtag or something to the tweet. Or if it wasn't even from twitter, could be from our site or something.

**Comment by bhollis** [comment]
> There is an issue with popup slot staying dismissed right now. :/

What's the issue?
