### ISSUE TITLE
Suggested Feature: Loadouts by raid

### ISSUE THREAD

**Issue by InstaSteve** [DestinyItemManager/DIM#1966]
Always thought it would be cool to have "Raid" loadouts. A predetermined loadout specific to each raid, that would grab any/all items pertaining to that raid. Select "Vault of Glass" under "Loadouts"; grab all of the users VoG gear/weapons/shaders/ships, etc.  I understand you could just create 4 different loadouts, plus a main loadout, etc. But that's no fun! =)

Just my two cents. I have been playing Destiny since September 2014, so I'm probably crazy.

**Comment by SunburnedGoose** [comment]
I thought activity based loadouts would be an interesting direction for DIM to take.  Now that we have an activity screen, we could do something like this.

**Comment by kyleshay** [comment]
Under the hood it could use the work that is done in #1875

**Comment by kyleshay** [comment]
Could be implemented by work done in #1875 and possibly #1967

**Comment by InstaSteve** [comment]
Is it alright if I check those out? Maybe I can come up with something to
present to y'all

**Comment by bhollis** [comment]
Closing out D1-specific stuff that isn't going to make it.
