### ISSUE TITLE
Responsive Move Item Dialog

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#197]
The desktop experience has a popup dialog that lets the user move items between stores or equip an item on a character.  A mobile client will not have the screen space to use this behavior so we should look to use a bottom drawer similar to instagram's filter choice UI.  

Tablets will continue to use the popup menu most likely.

**Comment by jflayhart** [comment]
I was thinking this might be cool: http://tympanus.net/Development/FullscreenOverlayStyles/index8.html

**Comment by kyleshay** [comment]
track this in https://github.com/DestinyItemManager/dim-mobile-client
