### ISSUE TITLE
Visualize ratings on item

### ISSUE THREAD

**Issue by 48klocs** [DestinyItemManager/DIM#1976]
I'm thinking that a horizontal bar graph would be a good way to visualize the breakdown of rating scores that a given item has received.

Maybe make it current rating overview "(4.9) based on 19 ratings" click to expand/contract, leave it hidden in the overview and expand by default when you click over to reviews?  I wouldn't want to have it bury the item overview by default.

**Comment by kyleshay** [comment]
like this sort of deal?
<img width="232" alt="screen shot 2017-07-14 at 9 26 59 am" src="https://user-images.githubusercontent.com/424158/28221056-b4f0395e-6876-11e7-9df2-9791233db5d9.png">

**Comment by 48klocs** [comment]
@kyleshay yeah, that's what I was thinking.

If someone has a neater visualization, that's cool too.

**Comment by 48klocs** [comment]
This got closed in advance of the PR getting merged?

**Comment by bhollis** [comment]
Yup. Easier to just track it in the PR where we've got code. 

-Ben
