### ISSUE TITLE
Saved loadouts won't show in beta

### ISSUE THREAD

**Issue by tcurtin** [DestinyItemManager/DIM#1977]
I was able to use the Storage page to import my setting from the chrome extension.  I also turned on google drive.  All now show 17 loadouts and 126 tagged items.

However, no amount of reloading the page, etc gets the loadouts to show under any character on the inventory page.

Same procedure on the non-beta site works fine, all loadouts show.

(There's a thread on this over on reddit as well: https://www.reddit.com/r/DestinyItemManager/comments/6mn0wh/lost_loadouts_using_beta_website/?st=j545zvne&sh=9e178857)

**Comment by bhollis** [comment]
After a change in beta, we were accidentally messing up the code where we filter out loadouts that don't match your class. They should be back now.
