### ISSUE TITLE
GetDestinyAccountSummary callback

### ISSUE THREAD

**Issue by v-fedorov** [DestinyItemManager/DIM#198]
Not sure if you are aware of the new public API callback
```
/Destiny/{membershipType}/Account/{destinyMembershipId}/Summary/
```

This returns all characters, equipped,stored, and vault items in a single request.
Unfortunately the item data is very minimal and doesn't contain node info so it was useless to me but i thought maybe it was perfect for DIM.

Unfortunately, the only big issue is that theres no way to determine which items are in the vault.
![screen shot 2015-08-18 at 4 52 12 pm](https://cloud.githubusercontent.com/assets/1764879/9342417/84749800-45c9-11e5-9d7a-7dea2f8cbc7b.png)

Just thought id let you know if you havent already tried it, its a shame because it would have saved you two callbacks per account request :/

**Comment by SunburnedGoose** [comment]
Thanks, I just heard about it today but didn't know the new signature.  I should keep my ears closer to the ground :)

**Comment by SunburnedGoose** [comment]
@v-fedorov, nice work on the Trials Report site btw.  Any piece of code you're proud of that I could look at?  Always interested in learning something new.

**Comment by v-fedorov** [comment]
@SunburnedGoose thanks! likewise :)
My code still needs heavy refactoring and I actually really like the way you have your service factories set up.
Your manifest script has saved our ass when we found out about how talent node definitions get updated randomly.

If you have any code in mind that you think can help us let me know.
In our new redesign (http://beta.destinytrialsreport.com) we started using touch events to slide between characters. I noticed you are planning on adding in responsiveness so im not sure if you ever considered doing the same.

p.s. I noticed that your image urls are still pointing to bungie but your manifest saves all the images to teh project. are they being used for something else?

**Comment by SunburnedGoose** [comment]
If Bungie updates their manifest, they remove images from their server. To
avoid having broke images, we make a local copy.

If a img request errors, we will reference a local copy. Unintuitively, it
is slower to load images in a chrome extension locally.

**Comment by SunburnedGoose** [comment]
We are adding gestures to the mobile app.

**Comment by SunburnedGoose** [comment]
Github doesn't like email attachments.

http://i.imgur.com/a103lRR.png

**Comment by v-fedorov** [comment]
awesome!
Ive been itching to contribute in here so once my schedule clears up you should see me around here.

If you want i can submit where i left off with that new API call, if they ever make changes to it then youd have a reference lying around

**Comment by bhollis** [comment]
I dug into this, and sadly it doesn't provide enough info for us to populate our full item data.
