### ISSUE TITLE
Nepal Shader and Emblem

### ISSUE THREAD

**Issue by justinchmura** [DestinyItemManager/DIM#200]
I haven't been able to get the Nepal shader or emblem to show up.

**Comment by SunburnedGoose** [comment]
Need to update the manifest.

**Comment by kyleshay** [comment]
still an issue?

**Comment by flameofzion** [comment]
No. It is fixed with the manifest update.

**Comment by justinchmura** [comment]
Saw it pop up yesterday. Thanks!
