### ISSUE TITLE
Stable - Chrome Extension

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#2003]
Still showing the old icon in the upper left corner, could also use some new screenshots of the extension as those shots are really old.

![screenshot 2017-07-16 00 37 18](https://user-images.githubusercontent.com/4798491/28245225-3a79a698-69bf-11e7-90e1-6879840939e8.png)

**Comment by bhollis** [comment]
I updated the icon. I tried to update some screenshots, but it wants me to pay $5 to change them. @kyleshay I can give you the new screenshots if you want to try:

![dim-official-1](https://user-images.githubusercontent.com/313208/28250133-e80b9fa8-6a16-11e7-84bb-f492f663fadd.png)
![dim-official-2](https://user-images.githubusercontent.com/313208/28250132-e80b3b76-6a16-11e7-8906-8cb9484e96a4.png)

**Comment by kyleshay** [comment]
Looks like it updated! Thanks Ben!
