### ISSUE TITLE
settings.collapsedSections

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#2011]
Should save per view (Inventory, Record Books, Activities, Vendors)

Currently there is a bug in the Vendors collapsedSection where it is using a mutable hash to hide the section currently 0-33 depending on where it falls for the subheading.

**Comment by bhollis** [comment]
Agreed. I keep meaning to build a directive/component for this (that enforces a better key structure) though making a component that handles all the current cases is a bit tricky.

**Comment by delphiactual** [comment]
and first bug report https://www.reddit.com/r/DestinyItemManager/comments/6nusyv/bug_collapsingexpanding_on_the_vendors_tab/

**Comment by kyleshay** [comment]
For the sake of fixing forward, I think it is fine to wipe all current collapsed states.

**Comment by jeserkin** [comment]
Could author or anyone else, who is aware of this issue post steps to reproduce it? From the description provided here it is not clear, how and where could one find views mentioned in the this issue and image/link for reddit is not viable as well. After additional information I could try and give it a go.

**Comment by duckmanBR** [comment]
Can't help on this other than point that this bug is for D1.

**Comment by jeserkin** [comment]
That helps.

**Comment by delphiactual** [comment]
This is how the meetings are saved in the settings json file and applies to both D1 & D2.

**Comment by jeserkin** [comment]
Then there should be a label for D2 in this issue or now Destiny version label at all as before, correct?

**Comment by duckmanBR** [comment]
I didn't label as D2 because we still don't have other views with collapsable sections.
But yeah, a fix would affect both.
