### ISSUE TITLE
Slow drag / drop

### ISSUE THREAD

**Issue by slipSTREAM68** [DestinyItemManager/DIM#2017]
Following up from my message on twitter. I use a lower spec (1.4ghz, 4gb, safari) macbook air and since the update drag and drop doesn't seem to function as well. I have to drag and hold item until I see the box light up, wait 2 seconds and the item will move. In most cases I have to try several times before it works. Realize this is an issue with my mac not having enough ram / cpu but wanted to share the issue all the same.

**Comment by slipSTREAM68** [comment]
Also seeing issue in chrome too

**Comment by bhollis** [comment]
This is on https://app.destinyitemmanager.com?

**Comment by slipSTREAM68** [comment]
Yes https://app.destinyitemmanager.com/

**Comment by bhollis** [comment]
Hmm, a recent-ish change to our drag and drop library may be implicated: https://github.com/angular-dragdrop/angular-dragdrop/issues/113

**Comment by bhollis** [comment]
@slipSTREAM68 would you mind taking a look at https://beta.destinyitemmanager.com ? I think I've improved dragging performance.

**Comment by slipSTREAM68** [comment]
I use DIM all the time and recently I have noticed a big improvement Ben. Really appreciate your help with this. Hope you enjoy your weekend!
