### ISSUE TITLE
Per Character/Vault Refresh

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#202]

**Comment by Mulchman** [comment]
This is a great feature proposal. I have a private branch of TGfD where I made it so I can click the player emblem and it refreshes everything on that character. In the TGfD world, where loading all the knockout templates and such cause such a huge delay, it's been super awesome/fast to just dump items (but keep the templates all built) then repopulate the items.

**Comment by SunburnedGoose** [comment]
Angular will reuse views afaik.

**Comment by bhollis** [comment]
Why not just make reloading everything fast?

**Comment by bhollis** [comment]
Nowadays refresh is pretty fast. We should do this in v4, but not v3.

**Comment by kyleshay** [comment]
can consider this for the mobile version (so we're keeping the payload smaller if they're on a cellular connection) 

https://github.com/DestinyItemManager/dim-mobile-client/issues/11
