### ISSUE TITLE
Add setting to define minimum # of reviews

### ISSUE THREAD

**Issue by 48klocs** [DestinyItemManager/DIM#2027]
Basically, I'd like to hide the rating for items that have one lonely review on them, because it's not all that helpful to know that one rando added a rating.

I figure I should make it a setting (I'm thinking a dropdown letting them choose from 0-10) so that people can choose to hide ratings on the inventory view unless the item has more than however reviews.  The search filter that @kyleshay added is there if people want to go beyond that.

This wouldn't hide ratings/reviews on the item view.

This also wouldn't apply to featured reviewers. There aren't a ton of them and we shouldn't be hiding their ratings/reviews.

**Comment by kyleshay** [comment]
We do try to keep as few settings as possible. Since we do have this as a filter I'm less inclined to want it as a setting. Especially with something like Saved Searches #1874, we could maybe include a "default" saved search that always triggers on load?

**Comment by 48klocs** [comment]
This was resolved with the merge of #2039.
