### ISSUE TITLE
Storage view loses $ctrl.destinyVersion

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#2032]
![destinyversion](https://user-images.githubusercontent.com/4798491/28494183-67d31ad2-6ee4-11e7-9f85-f90116855921.gif)

**Comment by bhollis** [comment]
That's correct, storage is not specific to Amy version of Destiny or any particular account. 

-Ben

**Comment by delphiactual** [comment]
This causes a weird navigation for the end-user, especially if they do not know that the DIM icon is used to return to the previous view.

**Comment by bhollis** [comment]
Yup, I thought about it, but I don't know how to work around it - these states aren't children of the destiny1 or destiny2 states, so they don't have access to the destiny version or account.

**Comment by bhollis** [comment]
And yeah, Xur should definitely be removed.

**Comment by kyleshay** [comment]
should it just live in a modal/tab in settings (settings would also not be tied to an account.)

**Comment by bhollis** [comment]
I'm actually planning on moving most stuff out of modals, at least on mobile. I have a solution for this though
