### ISSUE TITLE
DIM filter box autocomplete stopped working

### ISSUE THREAD

**Issue by jerrycarlson** [DestinyItemManager/DIM#2036]
I am running two Windows 10 boxes; one is 32-bit and the other is 64-bit.  I am running Google Chrome on each box (32-bit browser on the 32-bit machine, 64-bit browser on the 64-bit machine).  I am running DIM on both machines.  All Windows, Chrome, and DIM software is the latest/current version.

Within the past few days -- I'm sure it's been less than a week -- the autocomplete function in the DIM filter box stopped working.  The autosuggestion popup still works, but I just can't hit Enter or Tab any more to make the autosuggestion commit.  Hitting Enter has no visible effect, and hitting Tab simply moves the focus from the filter box to the account selector.  In short, even with autosuggest popping up I still have to manually type the entire filter keyword (#firstworldproblems).

Anyway, I didn't see this functionality change listed in any of the last two DIM release notes, so I wanted to bring it to your attention.  And just to clarify: this issue appeared simultaneously on both of my DIM installs even though one uses the 32-bit OS/browser and the other uses the 64-bit OS/browser.  I don't have any privacy/adblock extensions enabled for the DIM site/page, nor do I have any script-blocking extensions enabled.

Thanks to the entire team for all your hard work on this very, very essential piece of software!

**Comment by bhollis** [comment]
Yup, I noticed this too. We switched which library new use for autocomplete and it must have lost that capability then. 

-Ben

**Comment by kyleshay** [comment]
was possibly fixed in https://github.com/DestinyItemManager/DIM/commit/a5ed5541c3766c21182bf93e863d4ce47f72a941

are you still seeing this issue in production @jerrycarlson ?

**Comment by jerrycarlson** [comment]
@kyleshay yes i'm still seeing it in 4.5.0.

for what it's worth, i also tried the beta web app (Version 4.5.0.1235 (beta), built on 7/27/2017, 2:10:30 AM) and still have the same issue.

is there something i can/should do to force a local refresh of any relevant files?

**Comment by bhollis** [comment]
We switched to a different autocomplete library, and lost that behavior. I'm restoring it now.

**Comment by jerrycarlson** [comment]
I just now tried it and the issue remains.  I then cleared Chrome's cache and restarted it and the issue remains.  Is there something else I can do to force my browser to use your restored library?

**Comment by bhollis** [comment]
app.destinyitemmanager.com releases every Saturday. beta.destinyitemmanager.com releases after every change. So try it out on the beta.

**Comment by jerrycarlson** [comment]
Just tried the beta site and it works!  Thank you for the information and all your other help, @bhollis!
