### ISSUE TITLE
Error message in console for undefined filters

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#205]
Looks like we have a console error for filters if you do a search for a filter that does not exist (or for a filter that is `is:primar`, `is:primary` though works fine.)
![Image of error](http://i.imgur.com/VPF2iwk.png)

**Comment by flameofzion** [comment]
uh oh... missed that during testing. I'll try to get that fixed and open a
PR by the weekend.

**Comment by kyleshay** [comment]
issue fixed in #206
