### ISSUE TITLE
OpenCollective Sponsors

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#2052]
The OpenCollective Sponsors are not showing correctly in both the README.md and `Backers` Popup

**Comment by kyleshay** [comment]
I reached out to Open Collective. It's because:
> it only returns active sponsors whereas the collective page also shows past sponsors

I'm guessing backers work the same way. If you donate $120 once you'll show up for that month, but if you donate $10 a month over the span of a year, you'll be in the popup for a year.

**Comment by kyleshay** [comment]
If you _ever_ donate to be a backer/sponsor, you'll always show up on the Open Collective page.
