### ISSUE TITLE
Wiki edit for broken CONTRIBUTING link

### ISSUE THREAD

**Issue by Lingnik** [DestinyItemManager/DIM#2057]
The CONTRIBUTING.md file seems to have moved, but the wiki footer wasn't updated.

Since PRs aren't possible for wikis, here's a commit on a fork:
https://github.com/Lingnik/DIM-wiki/commit/c3be1549d9bff73dba625e8c10d848cf6f5abbb5

**Comment by bhollis** [comment]
Fixed, thanks!
