### ISSUE TITLE
Filtering can hard lock DIM

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#2060]
Current beta on Chrome 59 on Windows 10.

This is very easy to trigger.

In the filter box, type: is:leg[return]

In fact you can type any filter name fully and then press return and DIM will hard lock, requiring Chrome to be quit and restarted.

If you type: is:leg[space] it works correctly.

**Comment by bhollis** [comment]
Already fixed in beta. It'll go out with Saturday's release. 

-Ben

**Comment by philkernick** [comment]
Not fixed in the public beta.

Just tested again:
Version 4.6.0.1255 (beta), built on 02/08/2017, 15:40:35

**Comment by bhollis** [comment]
Try a force refresh

-Ben

**Comment by philkernick** [comment]
Thanks.  That fixed it.
