### ISSUE TITLE
400 Bad Request on Token

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#2063]
I'm getting an error starting up DIM.  It's been a while on this machine.  I have a token from the old pattern for authentication which used auth/refresh tokens.

I'm getting a 400 Bad Request when starting the app.  Looks like it isn't being handled by the app.  Might be related to the change in the API key?  The Refresh Token is within the window of 90 days.

![image](https://user-images.githubusercontent.com/984608/29081294-cfc8f68e-7c27-11e7-9645-fc3416f3ebc7.png)

![2017-08-08_104500](https://user-images.githubusercontent.com/984608/29081199-7be84682-7c27-11e7-95d4-c2d84991edc5.png)

![2017-08-08_104437](https://user-images.githubusercontent.com/984608/29081202-7e6abaac-7c27-11e7-8244-730a26c8f548.png)

**Comment by bhollis** [comment]
We have some code that should consider those old tokens to always be expired. I can check to make sure thats still true.
