### ISSUE TITLE
Opening DIM from Beta shows empty screen.

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#2064]
Cached version of DIM was stuck on opening with a blank page.  I had to clear cache/hard refresh to get it to load finally.  Might be an issue with service worker not getting latest?  

![2017-08-08_105825](https://user-images.githubusercontent.com/984608/29081626-ac5c49ac-7c28-11e7-93bc-721dbe710db4.png)
![2017-08-08_105801](https://user-images.githubusercontent.com/984608/29081628-ac5e3884-7c28-11e7-8848-58c0365cea24.png)
![2017-08-08_105754](https://user-images.githubusercontent.com/984608/29081627-ac5cd99e-7c28-11e7-952d-2cc1bdc72f77.png)

**Comment by bhollis** [comment]
Should be fixed now that you hard refreshed. I changed the caching strategy a bit ago but couldn't retroactively fix a bad cache. 

-Ben

**Comment by bhollis** [comment]
Here's the PR: https://github.com/DestinyItemManager/DIM/pull/2059

Reopen if you keep seeing this on the same browser.
