### ISSUE TITLE
Opera browser tagged as unsupported

### ISSUE THREAD

**Issue by GhostOfYars** [DestinyItemManager/DIM#2065]
I am using the latest stable version of Opera (46.0.2597.57) and it is being tagged as unsupported.  Please add Opera to the testing routine so we don't have to see the big red bar.

**Comment by eifeldriver** [comment]
Tut! Now Opera browser (V 58.0.3xxx) is gain marked as unsupported. Please fix this. Thanks a lot.

**Comment by bhollis** [comment]
Still not up to us. Please bother the browserslist project.

**Comment by eifeldriver** [comment]
Ok - thx for advice.
