### ISSUE TITLE
Vivaldi browser not detecting correctly

### ISSUE THREAD

**Issue by kulinp** [DestinyItemManager/DIM#2067]
Error message (red bar) at bottom of site saying browser is not supported, however the site works just fine.

![image](https://user-images.githubusercontent.com/720506/29244482-9e49f614-7f86-11e7-873f-5df6104892da.png)

"Your browser is not supported by DIM. Some or all DIM functionality may not work. Please upgrade to a supported browser."

Using the just-released Vivaldi 1.11.917.39 (Stable channel) (32-bit)

**Comment by bhollis** [comment]
Sorry, Vivaldi is not one of our supported browsers. We support lots of other browsers, though.

**Comment by kyleshay** [comment]
Maybe we could we consider an ignore & dismiss button for the red banner, it could possibly reset each release (as each release browser support may change?)

**Comment by bhollis** [comment]
That would be fine. Could somebody send a PR? The only tricky part is that the browser check JS needs to be ultra simple and be extremely failure tolerant.
