### ISSUE TITLE
mobile view not displaying menu

### ISSUE THREAD

**Issue by shockthealien** [DestinyItemManager/DIM#2068]
It was working great but for the last few days the menu has disappeared and its not possible to look at anything other than the inventory

![photo 14-08-2017 12 53 15](https://user-images.githubusercontent.com/2083273/29270941-fae42b2c-80f0-11e7-991c-50b5c414ce1d.png)
![photo 14-08-2017 12 53 23](https://user-images.githubusercontent.com/2083273/29270942-fb0a48a2-80f0-11e7-8dba-a40694ebc37e.png)

**Comment by bhollis** [comment]
Hmm, are you still seeing this? I still see the menu. My guess is that the fontawesome font wasn't loading for you. Make sure any content blockers are ignoring DIM (I know some block custom fonts). We should really use SVG instead of fonts but that's a bigger project.

**Comment by shockthealien** [comment]
Yeah I just tested it and still the same. Not sure how to whitelist in iOS. I'll look into it to see if it makes a difference

**Comment by bhollis** [comment]
A quick test is to hold down the reload button and choose "reload without content blockers".

**Comment by shockthealien** [comment]
Yes that does the trick. Didn't know that was an option
