### ISSUE TITLE
Sorting by Weapon/Gear type

### ISSUE THREAD

**Issue by Anakros** [DestinyItemManager/DIM#2071]
Hi. At the current moment it is a bit hard for me to find a specific weapon across my almost full vault with the current DIM sorting options (all of them). I think it would be very useful to have sorting by gear/weapon type option, so it will look like `<all hand cannons> - <all auto rifles> - <all pulse rifles>` and very easy (for me at least) to find what you want. Maybe some sort of subsorting by element type/light/name after main sorting by weapon type would be useful too.

Although, what I think would be better instead of the current sorting system in DIM is the sorting by weapon types by default and the possibility for the user to choose subsorting option (light, name, rating, element, etc).

**Comment by kyleshay** [comment]
Thanks for the suggestion @Anakros! I'm going to close this and link #647 as we have started to think about this a little. Please feel free to add to the discussion there.

Here is an example mockup from that thread:
![0014 sorting mock](https://cloud.githubusercontent.com/assets/21060251/19526204/b2944dce-95f1-11e6-8bc9-c2dc06f10c4f.gif)
