### ISSUE TITLE
PVP vs PVE Markup?  Suggestion. 

### ISSUE THREAD

**Issue by matthew-b-payne** [DestinyItemManager/DIM#2073]
It would be great to have a simple personal icon or markup to mark a gun as pvp or pve.  Often it would help with a quick visual eye scan of which crytic dragon or xyz to load up.

**Comment by bhollis** [comment]
Thanks for the suggestion. Something you can do right now is add "pvp" or "pve" to the notes for items, and then search "notes:pvp"
