### ISSUE TITLE
Custom Character Order

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#208]
https://www.reddit.com/r/DestinyItemManager/comments/3gi3b1/released_v3016_character_order_more_items_and/cuhyi6g?context=3

User would like to be able to define the order of characters.

**Comment by jflayhart** [comment]
What do you think about this: https://github.com/angular-ui/ui-sortable

**Comment by kyleshay** [comment]
I think we have enough options between:
 - By Most Recent Character 
 - By Most Recent Character (Reversed) 
 - Fixed (By Character Age)

I suppose if removed all of those options, we could simply allow the user to drag and drop the columns by clicking and dragging on the header/emblems.

**Comment by kyleshay** [comment]
https://www.reddit.com/r/DestinyTheGame/comments/4rut6w/dim_v38_a_big_update/d54i7q6?context=3

could also let the vault be drag + droppable

I'm starting to lean more in the direction of just letting people customize their order instead of making a radio option for every option.

**Comment by bhollis** [comment]
Well, some of the orders are by their nature dynamic (by most recent). We could do most recent, least recent, and user-defined though.

**Comment by kyleshay** [comment]
good point! maybe if it was most/least recent AND they could put the vault on far left or right... as well as fully user defined "fixed" for any of the stores.

just something to think about, i suppose.

**Comment by bhollis** [comment]
Do we still care about this now that we have so many sort options for characters?

**Comment by SunburnedGoose** [comment]
I still like the recent, reversed, and fixed (user defined).  I run reversed because I like the current character to be next to the vault.
