### ISSUE TITLE
Cordova-based apps for iOS and Android

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#2083]
We'll use [Apache Cordova](https://cordova.apache.org/) to build native-app wrappers for the DIM website, so that we can have better access to system APIs and distribute through the platform app stores. At least initially, to reduce management overhead, these wrappers should load the live DIM website rather than bundling the website into the app.

Tasks:

* [ ] [Finish making DIM's design phone-friendly](https://github.com/DestinyItemManager/DIM/issues/2081).
* [ ] Make sure DIM can work without browser chrome (back button, reload)
* [ ] Build a starter Cordova app with iOS and Android targets that can load the DIM website and login (in a separate repo).
* [ ] Add an extension that lets us tap into native SQLite instead of our WASM client.
* [ ] Publish to iOS App Store.
* [ ] Publish to Google Play Store.
* [ ] Publish to Amazon App Store.

**Comment by aidan2129** [comment]
I think the app and play store may have rules about just loading a web view inside an app and publishing it on the play store, It may not get through cert might be worth double checking though.
