### ISSUE TITLE
Stop using icon fonts

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#2089]
Our use of icon fonts (Fontawesome) ends up wasting a lot of bandwidth on icons we don't use, as well as messing up when the font doesn't load or is blocked (which many mobile browser content blockers will do). Instead, we should use SVG icons which are properly images. 

See https://css-tricks.com/icon-fonts-vs-svg/ for more reasons.

**Comment by duckmanBR** [comment]
Really don't know how this affect bandwidth or blocking (since even our/bungie scripts can be blocked as well), but Font Awesome is now available as SVG...
https://fontawesome.com/how-to-use/svg-with-js

**Comment by bhollis** [comment]
Nice! It'll definitely help as we rewrite the app to switch to SVG. We need to use a webpack plugin or something to help us inline them. 

-Ben

**Comment by bhollis** [comment]
As we move to React, we should switch to https://www.npmjs.com/package/@fortawesome/react-fontawesome, the Fontawesome 5 React SVG components.

**Comment by liamdawson** [comment]
Phew, 142 results for `fa-` in `src/app`. No time like the present, I guess? 😆

**Comment by delphiactual** [comment]
Remaining:
- [ ] D1 Loadout Builder
- [ ] Item Review
