### ISSUE TITLE
Auto refresh if stackable item isn't found

### ISSUE THREAD

**Issue by PonsAsinorem** [DestinyItemManager/DIM#209]
Example: I have 2 Etheric Lights in the Vault. I transfer them to one character. I use 1 in game, leaving me with 1, but DIM still sees me as having 2 since it hasn't refreshed. So I try to move it back to the vault, and it gives me an error saying it cannot be found. Pretty obvious since DIM says I have 2 when in reality I have 1. Refresh DIM, and it now correctly says I have 1 which can be moved successfully.

So when DIM cannot find something, it should auto refresh to see why it cannot find said item.

**Comment by SunburnedGoose** [comment]
I've thought about this...  it's not something I'm sold on complete yet with regard to resume.  Too many things can change.  I've thought about auto refreshing and just erroring out.

**Comment by SunburnedGoose** [comment]
@bhollis did the refresh update take this issue into account?  If there is a stack of items, and one is removed, will the refresh occur and still move the smaller stack?

**Comment by bhollis** [comment]
No, this is different.

**Comment by SunburnedGoose** [comment]
Remains open... for now. :)

**Comment by kyleshay** [comment]
Haven't tested this recently, is this still an issue @bhollis ?

**Comment by bhollis** [comment]
Yeah. This is specifically for mismatched stack sizes, not missing items.

**Comment by delphiactual** [comment]
Verify stack size before any move

**Comment by kyleshay** [comment]
could we push something back onto the action queue, do the refresh, and try again?

or is there something else here

**Comment by bhollis** [comment]
We don't need to do anything with the action queue - just refresh and try again, like we do with non-stackable items.

**Comment by bhollis** [comment]
Closing, as we're removing inventory auto refresh on moves.
