### ISSUE TITLE
Weapon ratings should give hints about which perks to pick

### ISSUE THREAD

**Issue by 48klocs** [DestinyItemManager/DIM#2094]
If you have detailed weapon ratings enabled, we should be able to give the user a hint about which perks people love.

My rough heuristic: find the highest-rated perk per column available on a weapon that has more than one review attached to it. If that exists, give the user a little thumbs up icon or something. Maybe apply the new item moving glint to the node if they don't have it selected? Ideally the hint should be unobtrusive.

**Comment by bhollis** [comment]
Closing in favor of #2112.
