### ISSUE TITLE
No Items on Load/Refresh for Destiny 2

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#2095]
When loading the page, it seems that there is a binding issue or timing issue where the items are not associated with the UI.  Items are in the stores, but they are not making it down the bindings to the directives.

![image](https://user-images.githubusercontent.com/984608/30105965-b15d4b06-92bf-11e7-87f3-e9c9f243f7ec.png)

**Comment by bhollis** [comment]
Yeah I think something just isn't applying. 

-Ben

**Comment by bhollis** [comment]
I believe this is fixed.
