### ISSUE TITLE
DIM Auto Refreshing the Page on Load

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#2096]
When working with DIM tonight locally, the app would refresh not long after load.  I can't see why from the commits.  Keep an eye out for this and see if it can be replicated.

I couldn't even enter an API key since the page kept reloading.

**Comment by bhollis** [comment]
If you're using the npm server, it has an annoying "hot reload" thing that's broken but I haven't figured out how to disable. I just run a simple HTTP server against the build directory. 

-Ben
