### ISSUE TITLE
Only Destiny 1 items showing in DIM

### ISSUE THREAD

**Issue by jollyrogerwilco** [DestinyItemManager/DIM#2098]
Logged into the following on my laptop: DIM and DIM Beta. Logged into DIM on my phone. Only one view was available:

Destiny 1 Guardians with Destiny 1 armor, weapons, etc. 

If there's a way to switch to D2, I'm not seeing it.

Thanks,
JRW

**Comment by wein3967** [comment]
You should see a little drop down in the top right. It is just the the right of the DIM search bar. You'll see your gamertag , version of Destiny, and your platform. Click the small triangle to select Destiny 2.
![profile switch](https://user-images.githubusercontent.com/11590326/30131079-06c74564-9311-11e7-840c-2bacd6a72ec4.png)

**Comment by jollyrogerwilco** [comment]
Wow, that's really small. Maybe make a toggle on the scale of the icons for
"Refresh" "DIM Storage" and "Settings"?

Regardless, great job on making D2 work so quickly, and for getting back to
me so fast. I depend on DIM so much and really appreciate all your work.

-JRW

**Comment by wein3967** [comment]
Heh, I'm most definitely not one of the ones that make DIM great ;) I suspect a setting type option will eventually get added to let you default to a particular profile. The majority of DIM users are likely not to care to much about their D1 stuff going forward.

**Comment by bhollis** [comment]
I agree that it's hard to figure out, but it's not small. You can tap anywhere on your username to open the menu. 

Soon I'll also add a full page account selection screen. 

-Ben

**Comment by kyleshay** [comment]
DIM will now try and load D2 the first time you spin it up and will remember your preference in the future. Could iterate on the account select dropdown, but eventually we can add a bigger account selection screen.
