### ISSUE TITLE
Weapon Transfer

### ISSUE THREAD

**Issue by JRich217** [DestinyItemManager/DIM#2100]
First off thanks for the great work on D1 and having this up and running already for D2. Just an issue that I am running into, I'm sure others are experiencing it too but just wanted to share it. When transferring a non equipped weapon from one character to my active character I am getting the error "Cannot read property 'id' of undefined".

**Comment by JRich217** [comment]
After trying it again it worked. This has been something that has been popping up over the course of the afternoon though. Just wanted to bring it up to you guys. Keep up the great work!!

**Comment by doktor5000** [comment]
I also get this for quite a few items. Also it seems some of the items that I've put in my vault ended up on my other characters, and now there's no way to move them anywhere else from DIM.

**Comment by bhollis** [comment]
This should be fixed now.

**Comment by doktor5000** [comment]
Hmm, got this today again when trying to move directly from one character to another.
> Martyr's Make
Cannot read property 'id' of undefined
I moved it then to vault manually, then to other character and that worked fine.
