### ISSUE TITLE
DIM thinks the vault is full

### ISSUE THREAD

**Issue by PetrifiedWing** [DestinyItemManager/DIM#2102]
When I try to drag a drop one item from a character to the vault, a bunch of items are automatically transferred from my vault to my character.

Thanks for all the hard work! DIM is awesome!

**Comment by bhollis** [comment]
Could you try this out again with DIM v4.13.0 (the latest)? Unless you actually have 200 things in your vault, in which case, yeah, it'll make room.

**Comment by PetrifiedWing** [comment]
Issue resolved! :)
