### ISSUE TITLE
Only D1 characters available to transfer to under D2 profile

### ISSUE THREAD

**Issue by NavyCryptoVet** [DestinyItemManager/DIM#2104]
While in D2 profile, I am only able to select D1 characters to transfer to. As you can imagine, this errors out when selecting any D1 character.
![dim](https://user-images.githubusercontent.com/31804470/30242593-d91d126a-955e-11e7-9e9f-850b15d4c164.jpg)

**Comment by bhollis** [comment]
Thanks for reporting! This should already be fixed at https://beta.destinyitemmanager.com. Note that drag-and-drop should also work fine.

**Comment by NavyCryptoVet** [comment]
It is, thanks! Love DIM and great support!
