### ISSUE TITLE
can't use DIM

### ISSUE THREAD

**Issue by Gamerciado** [DestinyItemManager/DIM#2110]
I can't use Destiny Item Manager, it says that "we were unable to find your destiny account information. if you have a valid Destiny account, let us know", is that something wrong with my account ?

**Comment by Gamerciado** [comment]
Destiny 2

**Comment by bhollis** [comment]
Could you try again with the new version of DIM (v4.13.0)?

**Comment by Gamerciado** [comment]
Now i can see the characters after selecting the item i want to transfer but still the same error :s

**Comment by bhollis** [comment]
Do you have a Destiny 1 account?

-Ben

**Comment by Gamerciado** [comment]
honestly ? I had but I played on a ps3 with CFW and I was banned from the destiny and never again could I play destiny 1 on my account ... But luckily they allowed me to play destiny 2 on my account, so taking into account that the profile of destiny 1 has been banned maybe it is as if it did not exist?

**Comment by Gamerciado** [comment]
There's no solution right ? ...

**Comment by kyleshay** [comment]
linking #2118 as it may be a similar issue

**Comment by kyleshay** [comment]
We'll track this in #2127 - thank you for the report!
