### ISSUE TITLE
"Your browser is not supported by DIM" on Chromebook Pixel 2 laptop

### ISSUE THREAD

**Issue by BWrecks** [DestinyItemManager/DIM#2114]
DIM is showing a banner now along the bottom. Displays in Destiny 1 or Destiny 2 DIM. This was not present before Destiny 2 game release. 

![screenshot 2017-09-10 at 9 53 49 am](https://user-images.githubusercontent.com/31822777/30249673-d20dd0bc-960e-11e7-85e3-0622f799d386.png)
![screenshot 2017-09-10 at 9 58 49 am](https://user-images.githubusercontent.com/31822777/30249675-d4efc600-960e-11e7-8374-427059c80bac.png)

**Comment by k5cents** [comment]
Wow, I came to submit this _exact same_ issue. Great to see another Chromebook Pixel user.

I can verify I'm still getting this alert. I get to the authorize page and nothing shows up.

![screenshot 2017-09-12 at 11 44 28 am](https://user-images.githubusercontent.com/18021678/30335241-c802686a-97af-11e7-9d1f-be69b2a0b12d.png)
![screenshot 2017-09-12 at 11 44 14 am](https://user-images.githubusercontent.com/18021678/30335242-c809a166-97af-11e7-8dc8-0e7d78fa35ef.png)

**Comment by kyleshay** [comment]
@k5cents looks like bungie is currently down for all users. I have a chromebook at home and I'll give this a whirl. 

All the red popup does is check your browser and lets you know that some features *might* not be supported. We use a 3rd party library to check compatibility and it is possible that their checks might be misleading.

One work around that we could add in until that 3rd party library has better browser detection is that we could add a dismiss/close button to that red popup so it's at least out of your way. 

Thanks for the report @BWrecks - it's on our list, but we're trying to get better parity for D2 first. 

@bhollis - maybe we could temporarily add a similar CSS fade that hides this after a minute or so?

**Comment by bhollis** [comment]
I like the idea of fading it away. What version of chrome do you both have on those? I wonder if they're old (we only support latest two versions) or if our detection is wrong. If you open dev tools it should print some details. 

-Ben

**Comment by k5cents** [comment]
I'm using Chrome OS Version 60.0.3112.112 (Official Build) (64-bit)

**Comment by bhollis** [comment]
Chromebook users, could you paste your user agent string here? Find it from http://useragentstring.com/

**Comment by bhollis** [comment]
I'm going to close this for now, but if somebody can paste in the user agent for their Chromebook's browser, please reopen.

**Comment by BWrecks** [comment]
Is this what you are looking for?

Mozilla/5.0 (X11; CrOS x86_64 9592.94.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.114 Safari/537.36

**Comment by bhollis** [comment]
@BWrecks yes! Are you still seeing the warning? If I change my user agent to be that string, I don't get the warning.

**Comment by BWrecks** [comment]
K5cents - I figure there can't be that many destiny obsessed Pixel 2 laptop owners. Nice to know there is at least one. 

bhollis - It appears to be fixed now. No red banner for me.

**Comment by bhollis** [comment]
Great. Thanks!
