### ISSUE TITLE
I cant load my destiny 2 characters  

### ISSUE THREAD

**Issue by Shannonl894** [DestinyItemManager/DIM#2118]
I link my account on the bungie.net account and it says im on a legacy platform. But im not anymore I did play destiny on the 360 but I did not buy destiny one on the one. But it still says im on legacy console.

**Comment by SublymeRick** [comment]
If you did not own D1 or play D1 on the one, then its probably defaulting to the only linked account for destiny 1 which is a legacy account. In dim, in the top right corner where it says your name, try changing that to "Destiny 2" and see if that fixes anything.

**Comment by Shannonl894** [comment]
No it still says its still linked to the legacy consol even when i click on destiny 2 xbox

**Comment by Shannonl894** [comment]
So I move my xbox account from one account to another and try and load that and it still says its a legacy console

**Comment by kyleshay** [comment]
We'll track this in #2127 - thank you for the report!
