### ISSUE TITLE
Missing Items

### ISSUE THREAD

**Issue by SublymeRick** [DestinyItemManager/DIM#2121]
Honestly, I'm sure you guys already know this, but I didnt see an issue for it so I figured I would create one.

Bunch of guns missing from the DB, and thus cannot move them.

![image](https://user-images.githubusercontent.com/3813238/30299723-9e202b16-9716-11e7-8851-59f8c7204ca9.png)

**Comment by wein3967** [comment]
I think these may be "classified" items. For example, I got a DO pulse from a Cayde chest and it doesn't show up in any 3rd party app or even the Bungie app. Basically, I'm betting these items don't really exist outside the game yet.

**Comment by kyleshay** [comment]
We'll have to update our https://github.com/DestinyItemManager/DIM/blob/master/src/data/classified.json file and add them there manually. If you/someone could open the browser console and match the items up with the item names, we could add them in but they still won't be transferrable unfortunately.

**Comment by kyleshay** [comment]
They are classified by the bungie/destiny API, but now they are transferrable with #2126

**Comment by SublymeRick** [comment]
Nice! Has bungie gave any indication as to when the API will have all item info?

**Comment by kyleshay** [comment]
Unfortunately not, we had the same issue in D1 (celery from D1 is still classified...) 

We have chatted publicly with the API devs at bungie and even they don't know when things will be declassified (it's up to another internal team.)

In the meantime we can manually build out a list of the classified items. To do so we need the information printed out in the console and we need the name of the weapon that it maps to in game.

**Comment by kyleshay** [comment]
I'm going to close this for now. We had the same issue in D1 and our solution is to de-classify items manually if they are classified for too long.
