### ISSUE TITLE
Players with Legacy Destiny 1 Characters can't load DIM

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#2127]
Player has a PS3 Destiny 1 character.  When loading DIM, he gets this error message and can't see any characters.  Are we doing something that blocks the app when we encounter legacy characters?

![image](https://user-images.githubusercontent.com/984608/30384672-93426b3c-986a-11e7-925d-0f2a45c9d22a.png)

**Comment by kyleshay** [comment]
linking - #2118 #2110

**Comment by bhollis** [comment]
I've confirmed that I can call `GetProfile` for that character. So either the problem is with calling `GetMembershipsById` (and I don't know their B.net membership ID) or the `GetProfile` response is different when it's your character.

@SunburnedGoose can you find their Bungie.net membership ID?

**Comment by Gamerciado** [comment]
My ID: 6083385

**Comment by bhollis** [comment]
@Gamerciado, it turns out your problem is different.

**Comment by bhollis** [comment]
@SunburnedGoose I still need a Bungie.net membership ID for that person. I extracted their Destiny membership as 4611686018454963271 but I can get their info with `GetProfile` no problem. Actually, with some mild tweaks to DIM, I'm able to load their inventory just fine (for D1 and D2).

**Comment by badm11** [comment]
Have the same problem 
My ID is 6665157

**Comment by bhollis** [comment]
Track final resolution in the bungie-net issue. We improved our error message if it happens again.
