### ISSUE TITLE
Some Filters Broken for Destiny 2

### ISSUE THREAD

**Issue by grahamers2002** [DestinyItemManager/DIM#2128]
Filters for an item type or slot incorrectly return zero results while filters for damage type return accurate results.

e.g. "is:scoutrifle" or "is:primary" return zero results even if you have 1 or more scout rifles in your inventory.  While "is:solar" and "light:>270" work fine.

**Comment by jerrycarlson** [comment]
On what I think is probably a related matter, I'm experiencing the filter becoming "undone" when the page refreshes.  The end result is that even though the filter term shows in the filter box, all inventory is shown and the only way I have found to reset the filter functionality is to refresh the page and re-enter the filter.

p.s. - I'm using the latest Google Chrome 64-bit browser on update-to-do Windows 10 64-bit platforms.

**Comment by kyleshay** [comment]
thanks for the report, should be fixed now. if not please let us know which are still broken!

**Comment by jerrycarlson** [comment]
For what it’s worth, the DIM refresh heartbeat still disables any filtering (on both the beta and release version of DIM) while leaving the filter text intact.  At least, it still did when I tested it last night.

**Comment by bhollis** [comment]
Give it another try now? (In beta)


-Ben

**Comment by jerrycarlson** [comment]
Just tested it (beta) and it seems to work!   I set a filter and waited 5 minutes and the filter is intact.

 

Thanks so much for all the work you all put into the site!
