### ISSUE TITLE
DIM2: Make Room for Postmaster Broken

### ISSUE THREAD

**Issue by grahamers2002** [DestinyItemManager/DIM#2136]
Expected behavior when clicked: Any item slots (kinetic, energy, helmet, etc.) that is full for the selected character has at least one item moved form the character to the vault.

Observed behavior: Clicking on this link in a character;s drop-down doesn't appear to do anything.

Using latest Chrome on Windows X

**Comment by paulharman** [comment]
Isn't the expected behaviour as such that e.g.

Situation
- 2 Helmets in postmaster
- Full helmet slots
_____
Press Make Room
____
- 2 helmets are moved out of slots to vault
- No other items will be moved

**Comment by bhollis** [comment]
You're confusing "Make Room For Postmaster" which moves items so you can pick up everything that's currently at the Postmaster, with "Farming Mode" which constantly keeps one slot open so items don't go to the Postmaster in the first place. 

-Ben
