### ISSUE TITLE
Consumables are overflowing the page

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#2138]
We're not wrapping consumables.  Users can't see all of their items.

![screen shot 2017-09-15 at 3 47 32 pm](https://user-images.githubusercontent.com/984608/30502845-96a10666-9a2d-11e7-8b61-9205ea74384d.png)

**Comment by kyleshay** [comment]
https://github.com/DestinyItemManager/DIM/issues/2137
