### ISSUE TITLE
Consumables have a lot of eye travel when rendered horizontally

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#2139]
You have to scan a long, skinny line of items when looking at your consumables on desktop.  It might be good for the user to limit the length of the items in these buckets to 6-10 items to make it easier to scan the items.

![screen shot 2017-09-15 at 3 47 32 pm](https://user-images.githubusercontent.com/984608/30503033-504e3fca-9a2e-11e7-855d-c5c5e2fd4af1.png)

![image](https://user-images.githubusercontent.com/984608/30503284-4a454668-9a2f-11e7-9d20-1c05b36b901f.png)

**Comment by kyleshay** [comment]
Hmm, we could just show it under the characters and not into the vault section

**Comment by pfp-az** [comment]
Also when using chrome on mac they only have one row and require horizontal scrolling.
