### ISSUE TITLE
Subclass has a number under it.

### ISSUE THREAD

**Issue by Cake12356** [DestinyItemManager/DIM#2145]
Hello DIM,
I was looking at my subclasses and they have a one next to them.
![unknown](https://user-images.githubusercontent.com/19882283/30516227-beac5552-9af5-11e7-9701-63b06682319e.png) I hope you can find the reason for this.
Thanks.

**Comment by thezoggy** [comment]
is that how many upgrade points you have to use?

**Comment by Cake12356** [comment]
No, I have spent all of my points.

**Comment by thezoggy** [comment]
can confirm I see the same thing as well:
![dim](http://zoggy.net/firefox_2017-09-16_18-02-53.png)

**Comment by bhollis** [comment]
It's weird, right? For some reason subclasses have a "primary stat" defined.

**Comment by thezoggy** [comment]
now this brings up the question, does DIM show how many upgrade points you have anywhere? (not a huge deal as these dont usually last long)
