### ISSUE TITLE
Item Left in Bounty Slot after Completing Exotic Bounty

### ISSUE THREAD

**Issue by lbobbitt-Personal** [DestinyItemManager/DIM#216]
I am seeing the item "Golden Age Shotgun Magazine" (http://db.destinytracker.com/items/195340509-golden-age-shotgun-magazine) in my bounty slot after completing the Exotic bounty for invective. I only see this in DIM as it has no purpose after completing the bounty. 

![dim_v3](https://cloud.githubusercontent.com/assets/5232528/9643361/ad996dd0-517e-11e5-8ea1-d4148e71238f.png)

**Comment by Empereol** [comment]
I too am seeing the "Golden Age Shotgun Magazine" bounty after I have completed the bounty for Invective.

**Comment by SunburnedGoose** [comment]
I've added code to try and fix this.  Let me know how it goes w/ v3.1.4
