### ISSUE TITLE
Save inventory for offline access

### ISSUE THREAD

**Issue by Lexcess** [DestinyItemManager/DIM#2164]
I actually thought this was already a feature but noticed that DIM didn't have my items in the latest maintenance window. It would be great if when the Destiny Servers are down or the client is disconnected from the internet we could browse our last known inventory. I'm sure there are a few people who would enjoy poking around their inventory while they are waiting for the servers to come up, or to get signal back.

Obviously you'd probably have to lock management features and perhaps display a date/time of when the cache was taken. As a bonus it would be great to be able to create and edit load-outs during these times.

**Comment by bhollis** [comment]
I built an offline mode with Service Worker once, but for some reason not all the Bungie APIs would cache.

**Comment by Lexcess** [comment]
Would it be possible to just hold the last known inventory in something like local storage?

**Comment by bhollis** [comment]
Yup, that'd be a good way to do it. The harder bit is making sure the user knows the data is offline, and disabling transfers. Not super hard. 

-Ben

**Comment by DHager** [comment]
This issue may have some renewed interest after the latest 3-4 day Bungie API outage.

**Comment by bhollis** [comment]
Yes, I'm picking this up again.

**Comment by DHager** [comment]
🥳

**Comment by Revadike** [comment]
This is not working for me
![image](https://github.com/user-attachments/assets/3a07d9e0-8d65-4cc2-9cd1-e139b9d7e95b)
