### ISSUE TITLE
Item tile decoration showing applied Mods

### ISSUE THREAD

**Issue by Lexcess** [DestinyItemManager/DIM#2165]
Item mods are a new thing in Destiny 2 but there is no obvious way to see at a glance that they've been applied. It would be great to have some visual indication that firstly, a mod has been applied and secondly that it has affected the items Power (light) level.

I don't want to be prescriptive on the visualization, but as a starter how about:

- Use the gold border that in D1 signified an item was fully leveled
   - Perhaps use a Blue/Purple border instead of gold to indicate rarity.
- Change the item Power Level font color.

I'm sure there are other options as well. It would certainly make working out infusion decisions and spotting un-modded gear a lot easier.

**Comment by kyleshay** [comment]
thanks Lexcess! --

Ben had the idea of putting a gold border on items that have a mod applied:
https://github.com/DestinyItemManager/DIM/pull/2160

**Comment by Lexcess** [comment]
Yeah that is similar. Peaking at the PR it looks like @bhollis is basing that on the power level being different to the base level. That does mean that highlighting would skip out on blue and non power enhancing mods. 

I guess Power enhancing mods are the most important for people, but it'd be nice to see blues. I'd also wonder if we might see mods that offer a variable level of power one day, rather than only +5.

**Comment by bhollis** [comment]
Follow along in #2160
