### ISSUE TITLE
D2 - exotic armor perk -- double title

### ISSUE THREAD

**Issue by thezoggy** [DestinyItemManager/DIM#2168]
the title for the exotic armor perk is shown again as the first line of the description in all uppercase (which does not look good or that readable).

![dim2](http://zoggy.net/firefox_2017-09-18_12-48-56.png)

**Comment by bhollis** [comment]
This is a Bungie data issue. For only some items, the perk description includes its name. 

-Ben

**Comment by thezoggy** [comment]
I can file a report on bungie api for it, until that is fixed on bungie's you could just strip it out like:

https://github.com/DestinyItemManager/DIM/blob/master/src/app/move-popup/press-tip.directive.js#L17

from
> title = `<h2>${$attrs.pressTipTitle}</h2>${title}`;

to
> title = `<h2>${$attrs.pressTipTitle}</h2>${title.replace(/^${$attrs.pressTipTitle}\s+/)}`;

**Comment by thezoggy** [comment]
posted issue to bungie: https://github.com/Bungie-net/api/issues/145
