### ISSUE TITLE
Option to show item Power Level minus Legendary Mod

### ISSUE THREAD

**Issue by lightmaster** [DestinyItemManager/DIM#2169]
Can we get the option to show the power level of items minus the bonus power level of a legendary mod if there's one attached to it? If I have a shotgun that's 285 but has a legendary mod on it, then a new shotgun that is 285 with no legendary mod is better than it since I can add a legendary mod to get it up to 290. Also, it seems that the level that engrams drop at is based on you power level without including any bonus from legendary mods. Seeing your light level minus mods would help to ensure you don't accidentally dismantle a new item with a base power level that's higher than your currents base power level.

**Comment by thezoggy** [comment]
perhaps, show it like `290 (+5)` so you know that its a 285 item but has +5 applied?

**Comment by lightmaster** [comment]
I was thinking more like `283/288`. Not everyone's good enough with math to quickly subtract 5 from numbers that don't end in 5 or 0.

**Comment by bhollis** [comment]
Follow along in #2160
