### ISSUE TITLE
WHAT? THis is an angular APP!?!

### ISSUE THREAD

**Issue by Shawful** [DestinyItemManager/DIM#217]
I might just contribute!

**Comment by flameofzion** [comment]
The more the merrier!!!!

**Comment by SunburnedGoose** [comment]
When you're ready, let's introduce you to our slack channel.

**Comment by Shawful** [comment]
Is slack free?  Also, where are you guys getting the API info from bungie?  will the items.json be updated prior to ttk? or do we have to wait for bungie to release a new items.json file?

**Comment by Shawful** [comment]
After an API key is issued, there has to be documentation on their API, but I'm not finding it...

Bungie API Key
https://www.bungie.net/en/User/API

**Comment by kyleshay** [comment]
haha. not really, unfortunately. the trick when i originally developed this was reverse engineering the calls that they make. since then we've figured out some of it.

a great resource now is the [bungienetplatform](https://www.bungie.net/en/Clan/Forum/39966) group on bungie.net

**Comment by SunburnedGoose** [comment]
We can still chat, it just isn't an open issue :)
