### ISSUE TITLE
IOS App hanging on "Initializing Database"

### ISSUE THREAD

**Issue by Andrew135790** [DestinyItemManager/DIM#2170]
As the title says, the app is hanging on the DIM splash screen with Initializing Database.

**Comment by azleb** [comment]
Yes I am having the same issues too. This is on the iPad Pro 10.5" running IOS 11

**Comment by bhollis** [comment]
Hmm, I haven't upgraded to iOS 11 yet, but when I do I'll take a look.

**Comment by bhollis** [comment]
Wait a sec, DIM doesn't have a message like "Initializing Database". This wouldn't happen to be an app you got off the App Store and you're stuck on a white screen, would it?

**Comment by Andrew135790** [comment]
im assuming this isnt the same dim and should stop using it asap? lol

**Comment by bhollis** [comment]
Yeah, that's not DIM. Somebody's got a broken App Store app up with our name. DIM is a web app, just visit it in your browser: https://destinyitemmanager.com
