### ISSUE TITLE
Suggestion - Profile add and remove

### ISSUE THREAD

**Issue by azleb** [DestinyItemManager/DIM#2174]
Can you build in the app the ability to add and remove destiny profiles? As in if we want to see our blizzard and destiny 1 accounts in the tabs. It starts to get in the way when viewing DIM via browsers. 

Cheers

**Comment by bhollis** [comment]
You can link multiple accounts to the same Bungie.net account, and they'll show up in the dropdown in DIM.

**Comment by azleb** [comment]
Yes thats what I have done however I dont want to see the accounts im not using. On the iPad every time it sleeps I have to reselect destiny 2. I thought it would be a good idea to hide/disable the accounts not used.

**Comment by kyleshay** [comment]
Hmm, curious... it should remember the account you had last selected. Are any of your settings working? Maybe try changing something after you click the gear icon and reload the app and see if the settings stick.

**Comment by azleb** [comment]
The app isn't working on the iPad at the moment. I am using Safari to use this fantastic app :-). I would be lost without it. I have cleared the cache, closed the app and rebooted the device. Thanks for you help

**Comment by bhollis** [comment]
Make sure to not use private browsing. DIM can't save anything if you do. 

-Ben

**Comment by azleb** [comment]
Yeah definitely in private mode.

**Comment by azleb** [comment]
![unnamed](https://user-images.githubusercontent.com/11970599/30618728-d5ed6a8e-9dda-11e7-988e-908cac28e877.jpg)

**Comment by bhollis** [comment]
Did you bookmark the D2 screen, or the D1 screen?

**Comment by azleb** [comment]
I booked marked D2. All good I’m using chrome and it works it’s just a
safari issue. Thought I would let you guys know anyway.

I still think it would be good to disable/enable it in some capacity though.

Keep up the awesome work.

Cheers
