### ISSUE TITLE
When dragging equipment sometimes icon separates from mouse cursor

### ISSUE THREAD

**Issue by mcdonamw** [DestinyItemManager/DIM#2179]
I'm not sure how to best explain it, but I just started using the web version of DIM with D2 recently.  For some reason when I'm dragging equipment, the icon separates from the mouse cursor entirely (upwards and to the left) so there's a 1-2 inch diagonal gap between the icon and the cursor.  This makes dragging difficult sometimes as intuitively my mind wants to put the icon where it needs to go, but the app needs me to put the mouse cursor where it needs to go instead.

It doesn't happen always and I notice sometimes it happens mostly with the upper right most piece of equipment in a given slot.  E.g. the primary slots are 3x3 and the top row, right most icon usually gives the issue.

It's totally bizarre.  I'm trying to replicate it now on my work PC but I cannot.  I'm mainly using the app on my home PC where I run into it daily.

**Comment by bhollis** [comment]
Which browsers are you using?

**Comment by mcdonamw** [comment]
Chrome

**Comment by bhollis** [comment]
Ah, that's helpful. I never have those turned on. Let me see.

**Comment by bhollis** [comment]
OK, should be fixed up in a few minutes on beta.
