### ISSUE TITLE
Mobile version changing to desktop version

### ISSUE THREAD

**Issue by duckmanBR** [DestinyItemManager/DIM#2180]
When I open the keyboard (to enter a search or an note) the app changes to the desktop version (wider area with smaller icons, vault side by side and wide header).  If I close the keyboard the app reverts back to mobile.
It's impossible to add a note, because when the app resizes to desktop, the item window closes, then the keyboard closes and the app reverts back to mobile.

May be related to #2176...
Using the 4.15.0.1375 beta on Android (Nougat with SwiftKey)

**Comment by bhollis** [comment]
Is this in beta, or the release version?

**Comment by duckmanBR** [comment]
Beta

**Comment by duckmanBR** [comment]
Just to be clear:
Portrait / Portrait with keyboard open / Landscape
![screenshot_20170922-090214](https://user-images.githubusercontent.com/32077894/30743807-9913e196-9f75-11e7-9aa8-b01900504a70.jpg) ![screenshot_20170922-090224](https://user-images.githubusercontent.com/32077894/30743815-9eef9f88-9f75-11e7-879c-166f501d77e4.jpg) ![screenshot_20170922-090234](https://user-images.githubusercontent.com/32077894/30743817-a17b9694-9f75-11e7-8ea3-20c74363d150.jpg)

**Comment by bhollis** [comment]
@kyleshay since you have a Pixel to test with, could you take a look at this?

**Comment by duckmanBR** [comment]
I forgot to add this before, but it's also almost impossible to handle stackable items in portrait.

@bhollis, can I comment the ` input.focus(); ` on line 22 of move-amount.directive.js?

**Comment by bhollis** [comment]
@duckmanBR could you explain more? Would it still be a problem if we fixed this issue?

**Comment by duckmanBR** [comment]
It would be only a nuisance (like it is when in landscape) because the focus opens the keyboard. So in landscape I need to click the mod/shader, close the keyboard, then move/split/etc

In portrait I need to try to be faster than the keyboard to click store/vault, if I'm too slow the keyboard will open, triggering the page resize to landscape. With the resize the item window will close, which will close the keyboard, triggering the page resize back to portrait.

I really need to find a way to capture this, it would be a funny gif...

**Comment by bhollis** [comment]
https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/Tr43oT4DQoY/XRxLWmrrEQAJ

**Comment by bhollis** [comment]
https://www.chromestatus.com/feature/5656077370654720

**Comment by bhollis** [comment]
https://stackoverflow.com/questions/8883163/css-media-query-soft-keyboard-breaks-css-orientation-rules-alternative-solut

**Comment by bhollis** [comment]
I've just pushed an update to Beta that may help. @duckmanBR can you check it out, and @kyleshay  can you try this with your super-zoomed-out Pixel? I'm going by the metrics at https://material.io/devices/

**Comment by bhollis** [comment]
@kyleshay does the thumbs-up mean it works good on your phone? 😆

**Comment by kyleshay** [comment]
ah, sorry. i thumbs up and checked it but forgot to reply back. beta looks great!
