### ISSUE TITLE
D2 - max light incorrect

### ISSUE THREAD

**Issue by thezoggy** [DestinyItemManager/DIM#2181]
looks like the calculation for max light is incorrect as max light is lower than current light?
![dim](http://zoggy.net/firefox_2017-09-19_14-05-20.png)

version: DIM 4.15.0

**Comment by delphiactual** [comment]
Is one of your currently equipped items classified?

**Comment by thezoggy** [comment]
yes, one item is.. the head piece. 
![dim3](http://zoggy.net/firefox_2017-09-19_23-35-43.png)

**Comment by bhollis** [comment]
Yeah, DIM can't read the defense value for that.
