### ISSUE TITLE
Add search keywords for mods

### ISSUE THREAD

**Issue by nki2bpz** [DestinyItemManager/DIM#2185]
example is:mod is:modded

**Comment by kyleshay** [comment]
try is:powermod or is:haspowermod

https://github.com/DestinyItemManager/DIM/pull/2160/files#diff-d8d0aa7162a9aba8d15e9b234bcaabd7R100

**Comment by brailsmt** [comment]
I would like to highlight the mods themselves, not pieces of gear that have them applied.

**Comment by nki2bpz** [comment]
How would this save time or make things easier to identify?


-------- Original message --------

**Comment by brailsmt** [comment]
You're joking right?  I would like to do things like "is:mod is:blue" to move all my blue mods to the vault so they don't clog up my inventory.  Clicking on each one and moving it to the vault is a pain.

**Comment by paulharman** [comment]
Try is:modifications is:blue

**Comment by paulharman** [comment]
Then click the down arrow on vault and click where it says Items = "is:modifications is:blue" and it will move all your blue mods to the vault

**Comment by nki2bpz** [comment]
Sorry, I just didn't understand what you had meant. I had closed this because what I originally requested was achieved but it sends clear there is still more work to do here.  is:modifications returns no result, adding is:blue to it I just tried to send everything blue to the vault and DIM is very angry with me

**Comment by brailsmt** [comment]
Maybe this wasn't the right issue for my comment.  I would like a way to search for the mods themselves to help manage them.  I guess as a user story it'd be:

As a DIM user
I'd like an is:mod/is:modification search keyword
So that I can easily manage mods in DIM

**Comment by duckmanBR** [comment]
@brailsmt , this was implemented in the last beta.  Now you can search for the name of all the subsections, so `is:modifications`, `is:shaders`, etc are all valid. And we are finishing the `stack:`.  Soon we'll be able to do `is:modifications is:blue stack:>=3`

**Comment by kyleshay** [comment]
yup `is:modifications` is now in the beta

**Comment by brailsmt** [comment]
+1

Very cool!

**Comment by joshminnie** [comment]
Linking https://github.com/DestinyItemManager/DIM/issues/2263

**Comment by nki2bpz** [comment]
Tested in beta this time and it works. Sorry I only tested release version earlier
