### ISSUE TITLE
Correlate border colors to rarity of the mod

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#2188]
Players are asking to have purple borders for purple mods, and yellow borders for exotic mods.

**Comment by bhollis** [comment]
We aren't even really looking at that. The border means "this item's power is higher because of mods"

-Ben

**Comment by pfp-az** [comment]
This would be a nice feature (border color based on mod type)

**Comment by klemm89** [comment]
A better idea would be to make mods filterable. Similar to is:dupe have a is:mod that only returns +5 mods, or extend it to be has:modNULL, has:mod0, has:mod5, has:mod10

Then you could build a is:dupe AND (has:modNULL OR has:mod0) to show whats safe to dismantle

**Comment by bhollis** [comment]
Right now you can type "is:dupe not:powermod"

-Ben

**Comment by klemm89** [comment]
Yea that's a great search, I deleted my comment when I found it earlier.

**Comment by bhollis** [comment]
Closing because we're having some active discussion on how to best display mods in a new item design.
