### ISSUE TITLE
Move the subclasses out of the weapons category 

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#219]
We should move the subclass transfers out of the weapons category. The general section may be a better fit for it.

Otherwise, right above the ghost shells?

I'm guessing people don't use DIM to change their subclasses as much, so it really shouldn't be taking up precious real estate at the top of the page.

**Comment by jonasschmeing** [comment]
I switch my subclasses really often via DIM. Moving it to the general slot wouldn´t fit well for me

**Comment by SunburnedGoose** [comment]
Add type order to the settings.

**Comment by kyleshay** [comment]
linking: #267
