### ISSUE TITLE
Add base power level to character banner

### ISSUE THREAD

**Issue by spiffomatic64** [DestinyItemManager/DIM#2191]
It looks like there is a currently undocumented value "1885944937" in the character stats, that is your current powerlevel, minus mods. This would be useful to some, and should be fairly simple to add as the data is already in an api call the tool is making anyway.

Thanks!

**Comment by kyleshay** [comment]
thanks for the suggestion, please continue discussion in https://github.com/DestinyItemManager/DIM/pull/2150
