### ISSUE TITLE
Vaulted Weapon Mods appear with non-vaulted ones

### ISSUE THREAD

**Issue by HighHowDoIPlay** [DestinyItemManager/DIM#2193]
Today, I was looking in my weapon mods for my hunter ones. I couldn't find it in game, but in DIM they were showing up. It took me a second to realize that both the mods in my vault and not were being grouped together on DIM.

In addition, if the mods are able to be moved, is it possible we could get the ability to move them to and from our vaults?

**Comment by wahrendt** [comment]
This would be great! I noticed the drag drop wasn't working for mods, and then I saw this bug. 
Thanks!
