### ISSUE TITLE
Saved items notes/tags removed on vaulted items when vaulted items failed to load

### ISSUE THREAD

**Issue by DenL** [DestinyItemManager/DIM#2194]
Sometimes when loading/refreshing items the vault would return empty, presumably because destiny server is busy so endpoint didn't return any vaulted items (or some other reason; have no idea).

In this case all the user saved items notes and tags would be remove when vaulted items loads the next time.

**Comment by bhollis** [comment]
Good point, this would delete info for those items. Let's track it over in #2195 and hopefully we'll learn how to identify this failure case.
