### ISSUE TITLE
Make filter/search tooltip case-insensitive 

### ISSUE THREAD

**Issue by duckmanBR** [DestinyItemManager/DIM#2197]
Right now only works if everything is lowercase...

**Comment by bhollis** [comment]
Could you explain in more detail what you're doing and what isn't working?

**Comment by duckmanBR** [comment]
is:a / Is:a / is:A
 ![screenshot_20170922-081850](https://user-images.githubusercontent.com/32077894/30742772-0dace7aa-9f71-11e7-8672-e47b136c2176.jpg)  ![screenshot_20170922-081836](https://user-images.githubusercontent.com/32077894/30742714-d49571d0-9f70-11e7-81a6-15f6bc855b2e.jpg) ![screenshot_20170922-081859](https://user-images.githubusercontent.com/32077894/30742781-15b4fc58-9f71-11e7-9f34-6514c3057362.jpg)

**Comment by bhollis** [comment]
Ah, the autocompleter. Got it. I'll have a fix asap. 

-Ben
