### ISSUE TITLE
is:xpcomplete Filter Not Functioning Properly

### ISSUE THREAD

**Issue by jflayhart** [DestinyItemManager/DIM#220]
Per this post: https://www.reddit.com/r/DestinyItemManager/comments/3jmwgt/bugisxpincomplete_no_working_as_before/

I have verified that the filter "is:xpcomplete" is only showing weapons that have little to no progress. I assume the appropriate behavior should be that this filter highlights gear that has completed nodes.

Will update this ticket as I find out the cause of this behavior...

**Comment by jflayhart** [comment]
https://www.reddit.com/r/DestinyItemManager/comments/3kljxd/filterxpincomplete_is_not_working_for_me_is_this/

**Comment by bhollis** [comment]
See #371.

**Comment by CathyMacars** [comment]
Bumping, because this is important. We often want to pull out guns that need XP when turning in bounties.

**Comment by bhollis** [comment]
The fix is already in #382 and will be merged soon.

**Comment by bhollis** [comment]
Closed since #382 got merged.
