### ISSUE TITLE
Max light isn't always max possible light

### ISSUE THREAD

**Issue by nanisean** [DestinyItemManager/DIM#2202]
Maximize light shows a light level lower than current light.

![screen shot 2017-09-22 at 1 34 50 pm](https://user-images.githubusercontent.com/16326108/30763581-bf96e900-9f9b-11e7-821c-e5d7d56ab29d.png)

**Comment by bhollis** [comment]
Could you try on the beta?

-Ben

**Comment by nanisean** [comment]
Same result.

![image](https://user-images.githubusercontent.com/16326108/30764451-e52fd3b2-9f9f-11e7-8f32-d1e48c34fef7.png)

**Comment by delphiactual** [comment]
Do you currently have an equipped classified item?

**Comment by nanisean** [comment]
Ah, in fact I do.

**Comment by nanisean** [comment]
I'll close this then since it appears to be a limitation of the api.

**Comment by SunburnedGoose** [comment]
@bhollis What do you think about adding an asterisk to the max light value with a tool tip when the player has classified items? Would cut down on this feedback.

**Comment by bhollis** [comment]
Yeah I was thinking I should do that. Hard to put in the Loadout menu though

-Ben

**Comment by delphiactual** [comment]
if (classifiedEquipped) {
  if curMaxLight < calcMaxLight {
     calcMaxLight === curMaxLight;
  }
}

**Comment by bhollis** [comment]
@delphiactual that's a good idea! It doesn't help with the case where you don't have the classified item equipped though, but it's still the highest power.
