### ISSUE TITLE
Duplicate Weapon mismatch

### ISSUE THREAD

**Issue by BWaySimon** [DestinyItemManager/DIM#2207]
I have "A Single Clap" & "Botheration Mk.28" showing as duplicate weapons with the "is:dupe" filter.
Just thought you ought to know.
![image](https://user-images.githubusercontent.com/24623454/30771342-66b25d7c-a03d-11e7-8e34-c65f1f249ff3.png)

Thanks

**Comment by bhollis** [comment]
If you reload the page and immediately do "is:dupe" does it still happen? I'm trying to figure out if it's some stuck state, since I can't get it to happen for me.

**Comment by thaloun** [comment]
I filed a dupe today.  Turns out there was another copy at the postmaster.  I bet that's it.

**Comment by kyleshay** [comment]
please re-open if you're still running into this issue.
