### ISSUE TITLE
Add Alexa Support

### ISSUE THREAD

**Issue by JustMaier** [DestinyItemManager/DIM#2213]
It'd be awesome to be able to switch loads, move weapons, and toggle a few key settings via voice assistants like Alexa. No more fumbling with a phone or whatever to make some quick changes. Initially, I was thinking about building the whole thing from scratch, but DIM has a lot of the functionality already built and adding voice assistant support would just be a matter of adding an endpoint with Alexa intention handling.

Like the idea? What are some things you guys would like to be able to do via voice?

**Edit:** I just realized that DIM is purely clientside code... That's awesome, but kind of throws a wrench in my plan... With no backend server, there's no way to accept requests from Alexa. So **no way to do this as part of DIM without significant infrastructure changes**. Closing this idea.

**Comment by bhollis** [comment]
Follow https://github.com/DestinyItemManager/iot for our Alexa/Cortana effort.

**Comment by JustMaier** [comment]
Awesome, is there more discussion about these efforts happening somewhere?
