### ISSUE TITLE
Infuse Fuel Finder miscalculation

### ISSUE THREAD

**Issue by duckmanBR** [DestinyItemManager/DIM#2215]
It's not considering the full value of a rare/blue item, only half the difference between powers when used as fuel
The item being fused is a 235 legendary
![screenshot_20170923-201546](https://user-images.githubusercontent.com/32077894/30777935-0c6ec3e0-a09d-11e7-8e91-642905cf3a35.png)

**Comment by bhollis** [comment]
What happened when you infused it?

**Comment by duckmanBR** [comment]
This specific weapon I didn't (yet), but yesterday I had the same situation and got the full difference instead of the value DIM gave. And there was no mods involved (not in this weapons nor yesterday).

**Comment by bhollis** [comment]
Hmm. In that case, Bungie's giving us bad info :-)

**Comment by bhollis** [comment]
Here's the rules we're following: https://bungie-net.github.io/multi/schema_Destiny-Definitions-Items-DestinyItemTierTypeInfusionBlock.html#schema_Destiny-Definitions-Items-DestinyItemTierTypeInfusionBlock

The item database reports a `baseQualityTransferRatio` of 0.5 for blue items. But I guess that's not what actually happens. I haven't personally infused anything.

**Comment by duckmanBR** [comment]
Now you're making me doubt myself, but I'm not using legendaries as fuel unless is a dupe and I'm sure I didn't have one yesterday when I infused my Merciless...

**Comment by duckmanBR** [comment]
Just checked with a legendary and a exotic using blues as fuel. In both cases the amount was 100%...
Looks like it's a bug on Bungie side...
