### ISSUE TITLE
Inspecting Ghosts and Bonds

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#222]
Ghosts and Bonds can still be drag and dropped, but realized in 2.0, they have a bug upon click referenced in this line of code: 

https://github.com/DestinyItemManager/DIM/blob/e0e5c8dc4301034153e0bd78e76f5668840bdaa6/app/scripts/move-popup/dimMoveItemProperties.directive.js#L79

I guess the .value call on it is breaking. Maybe because it does not have a light level?

might need to inspect what the vm.item.stats array looks like for that particular item type.

**Comment by SunburnedGoose** [comment]
The stats array is empty but the function assumes not. Put a check around it for size.
