### ISSUE TITLE
Ignore mod in Infusion Fuel Finder

### ISSUE THREAD

**Issue by duckmanBR** [DestinyItemManager/DIM#2220]
When searching which items could be used for fuel, the mod value of the infusee needs to be ignored/discounted. I had a exotic 265 (natural mod +5) and a blue 262
The finder should show this blue as possible fuel with a new value of 267... Right now is returning no items available

**Comment by bhollis** [comment]
Oh, great catch. I was considering mods for the increase calculation, but not the search!
