### ISSUE TITLE
Destiny Inventory Manager Icons Shrinking

### ISSUE THREAD

**Issue by Penix08** [DestinyItemManager/DIM#2222]
DIM has consistently shrunk all of my icons. I've set setting to maximum icon size; However it will only enlarge to the largest shrunk size it has set to. Almost unable to read icons at this point.

**Comment by bhollis** [comment]
Hmm, I'm not sure exactly what you mean. Can you post screenshots? What browser are you using?

-Ben

**Comment by Penix08** [comment]
Fixed.
