### ISSUE TITLE
Mod Searching

### ISSUE THREAD

**Issue by wein3967** [DestinyItemManager/DIM#2224]
Using the current beta there seem to be the following weirdness around searching for Mods:
1. When searching "mod" in the search bar, most Mods are highlighted, but some are left out (see image)
2. Searching "Arms Armor Mod" or "Amor Mod" or similar variations does not identify those items in the Inventory
![capture](https://user-images.githubusercontent.com/11590326/30783717-516a1632-a10d-11e7-9519-0ce08d749f6b.PNG)

**Comment by duckmanBR** [comment]
The current beta is still only searching for item names, the mod/perk search should be up on the next beta or any time soon (up to the devs)

**Comment by bhollis** [comment]
Should be better in beta now.
