### ISSUE TITLE
Unit Tests?

### ISSUE THREAD

**Issue by fishfacemcgee** [DestinyItemManager/DIM#223]
I noticed the Karma config file in the repo, but there doesn't appear to be any tests scripts and we're not including Karma in the dev dependencies. Do we want to start running tests? Just thinking it'd be a good way to contribute and I also personally wouldn't mind getting my hands dirty with Angular 1.4.x.

**Comment by SunburnedGoose** [comment]
I wrote some I. The past for the promises but pulled them out. Look at the
v4-dev branch and feel free to make a PR with a test it two on the Bungie
services.

If you want to talk about it, let me know and I'll set up a time.

**Comment by jflayhart** [comment]
I am Josh and I approve this message. I am ALL for unit testing. Test, test, and test some more. Would love to put our heads together and start implementing unit tests as well as some form of standardization (i.e. precommit-hook) for code style.

**Comment by fishfacemcgee** [comment]
@SunburnedGoose Sounds good. I'll take a crack at that hopefully sometime this week. Maybe this is better suited for a call but do you have any preferences w/ Testing frameworks? Most of my experience is with Jasmine + Karma but I wouldn't be opposed to trying out something new if you have a strong preference.

**Comment by SunburnedGoose** [comment]
I'm most familiar with those too, but the scaffolded grunt task uses mocha.  If you are comfortable reaching in there and pulling it out, and replacing it with karma+jasmine, be my guest... but I'm also fine with using Mocha.  I know it will work just fine for this project and it's well integrated.

**Comment by SunburnedGoose** [comment]
http://mochajs.org/#asynchronous-code

**Comment by jflayhart** [comment]
I echo @SunburnedGoose. Haven't used anything else with node except Mocha and while I am not familiar with Jasmine, open to whatever suites our needs the best...

**Comment by bhollis** [comment]
We've made it this far without tests - at this point it's up to somebody to submit a PR.
