### ISSUE TITLE
Improve CSV export

### ISSUE THREAD

**Issue by duckmanBR** [DestinyItemManager/DIM#2231]
DIM need to enclose the item name in the export by " or ' or change the comma to tab/anything else because we have items like **First In, Last Out** which "breaks" the export...

**Comment by bhollis** [comment]
This'd be a good first PR for somebody :-)

**Comment by duckmanBR** [comment]
Here goes nothing...

**Comment by duckmanBR** [comment]
I did the change in my fork, looks like it's not the way to do it (or am I missing anything else?) doing the change on master...

**Comment by projektir** [comment]
@duckmanBR if you go to your fork, Github should offer you to make a pull request to the main repo. If that doesn't show up for some reason, this page might help: https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by duckmanBR** [comment]
@projektir thanks! I'll try this in the next PR.
