### ISSUE TITLE
Bungie.net error

### ISSUE THREAD

**Issue by xBacKsTeRx** [DestinyItemManager/DIM#2233]
Hi after the new patch i cant see my Charackters anymore and i have this error please help 
![screenshot 52](https://user-images.githubusercontent.com/32280795/30833357-d6ae7c24-a24e-11e7-90d3-378932fb56a9.png)

**Comment by SunburnedGoose** [comment]
Can you press ctrl+shift+i and see what the message you're getting in the developer tool?

**Comment by xBacKsTeRx** [comment]
![screenshot 53](https://user-images.githubusercontent.com/32280795/30833572-de4f4ee4-a24f-11e7-9e61-d30bfd3f3dd9.png)

**Comment by xBacKsTeRx** [comment]
![screenshot 54](https://user-images.githubusercontent.com/32280795/30833714-798f7c94-a250-11e7-957b-82dcc04d0545.png)

**Comment by projektir** [comment]
Similar issue here as well, both Chrome and Firefox.

![dim](https://user-images.githubusercontent.com/16269746/30834112-99b299ba-a206-11e7-96ef-2960c49e00e0.PNG)

**Comment by xBacKsTeRx** [comment]
d1 is working for me but d2 dont work on chrome, firefox same issue "Cannot read property ID of undefined"

**Comment by SunburnedGoose** [comment]
@xBacKsTeRx Do you have the same issue in both app.destinyitemmanager.com and beta.destinyitemmanager.com?

**Comment by xBacKsTeRx** [comment]
Yes i have this issue in both. but the app frome bungie on my handy works same withe the vault app for android......

**Comment by xBacKsTeRx** [comment]
and und bungie.net i have this 
![screenshot 55](https://user-images.githubusercontent.com/32280795/30836212-f519595a-a25c-11e7-8df8-4c782df1052a.png)
and this 
![screenshot 56](https://user-images.githubusercontent.com/32280795/30836229-0c8a215a-a25d-11e7-890e-36ad07657d94.png)

**Comment by SunburnedGoose** [comment]
@bhollis The code is looking up a vaultBucket.  The object doesn't have one.  The bucket is being set here.

![screen shot 2017-09-25 at 6 53 30 pm](https://user-images.githubusercontent.com/984608/30836299-daccc508-a222-11e7-8d6a-47f936832a9c.png)

**Comment by SunburnedGoose** [comment]
Can you test https://beta.destinyitemmanager.com and let me know if it fixes the issue?

**Comment by xBacKsTeRx** [comment]
now it works on the beta for me :)

**Comment by xBacKsTeRx** [comment]
![screenshot 57](https://user-images.githubusercontent.com/32280795/30837880-741b6c4c-a268-11e7-9cc6-0ae19d85f103.png)

**Comment by SunburnedGoose** [comment]
Do you have an engram in your vault?

**Comment by xBacKsTeRx** [comment]
2 on my warlock
![screenshot 58](https://user-images.githubusercontent.com/32280795/30837938-d5b4ee4c-a268-11e7-83f5-f61422be9190.png)

**Comment by bhollis** [comment]
Looks like @SunburnedGoose got a fix out!

**Comment by SunburnedGoose** [comment]
This issue resurfaced @bhollis.  The vaultBucket isn't being set for some users.  I don't know why.

https://github.com/DestinyItemManager/DIM/blob/24c353384583d73fac766f6f193f0ee77dc1d3ae/src/app/destiny2/d2-buckets.service.js#L152

https://github.com/DestinyItemManager/DIM/blob/master/src/app/inventory/store/d2-store-factory.service.js#L196

**Comment by bhollis** [comment]
@SunburnedGoose this is actually a different one. Looks like you got it, but my general mistake was using `bucket` instead of `location`.
