### ISSUE TITLE
D2 - 4.16.0 // undefined error if item already produced error

### ISSUE THREAD

**Issue by thezoggy** [DestinyItemManager/DIM#2235]
tried to move over a legendary ghost to a new character to equip, saw the error it couldnt due to level requirement. then tried to move it to just that characters inventory (not to equip it, just to store for later) while the previous notice was up.. throws:
![dim](http://zoggy.net/firefox_2017-09-25_18-47-45.png)

can repeat this by trying to move it item to something that tosses up an error then try to move the object again

**Comment by thezoggy** [comment]
moving an exotic around to another character that has an exotic also does this,
![dim2](http://zoggy.net/firefox_2017-09-25_20-49-32.png)

**Comment by SunburnedGoose** [comment]
I can't repro.  Can you use licecap to record what you're doing?

**Comment by thezoggy** [comment]
sure, here is a easy reproducible example. drag exotic from one char to another with an exotic equipped. 
you get first error.. then drag that failed item from the vault to somewhere else and you see the next error.
![dim_bug](http://zoggy.net/dim_bug.gif)

**Comment by bhollis** [comment]
Hmm, I still can't reproduce on FF 55.0.3 on OS X.

I *think* what's happening here is actually that you have a completely empty General vault, and that's causing the vault counts to not get populated. See how you don't have a "G" count under the vault column? Put some stuff in the vault, reload, and see if this still happens.

**Comment by bhollis** [comment]
Also, try it out on beta. I pushed a speculative fix.

**Comment by thezoggy** [comment]
I assume to run the  beta I need to do:
https://github.com/DestinyItemManager/DIM#developer-quick-start

~ opened GI for related comments

**Comment by duckmanBR** [comment]
@thezoggy just access https://beta.destinyitemmanager.com

**Comment by thezoggy** [comment]
seems like the beta update fixed it. unable to reproduce.
