### ISSUE TITLE
Feature Request: Allow blank slots in loadouts

### ISSUE THREAD

**Issue by jmichas** [DestinyItemManager/DIM#224]
Rather than just stacking and moving things out of a character when running large load outs it would be nice to have loadouts include intentional blank spaces. This way the character isn't jammed up with gear. I find myself moving thing off manually all the time to maintain a few blank spots to pickup stuff when Im playing or grab items out of the post office or whatever.

**Comment by SunburnedGoose** [comment]
We can handle this in v4.

**Comment by nessus42** [comment]
Hi. I'm curious as to the status of this feature. I've been eagerly awaiting it since I first started using DIM many months ago. (Thanks again for such a great tool!)

**Comment by nessus42** [comment]
I'd like to chime in to request this feature. I would find this **_extremely_** useful, and it would make DIM an even more awesome tool than it already is.

The current status quo of having to manually clear up room on a character after applying a loadout is something of a chore.

**Comment by bhollis** [comment]
This'll take a pretty significant rework of how loadouts ui works.

**Comment by nessus42** [comment]
Personally, I'd be happy with a simple checkbox that would indicate that any slot not specified by the loadout should be emptied upon application of the load-out.

Alternatively, in the load-out drop-down, there could be an additional icon for each loadout. Currently there is a trash icon and an edit icon. The additional icon could mean, "Apply this loadout and empty all unspecified slots".

**Comment by nessus42** [comment]
Hi. Are there any plans to implement this feature anytime soon? This is the **_one_** feature that I've missed most in DIM since I've been using it. I love the loadouts feature, but then I always have to spend the next five minutes manually moving my other crap off of the character that I applied the loadout to. It would be incredibly awesome to have this manual labor automated for me!

**Comment by bhollis** [comment]
Closing in favor of #2230, which is closer to the solution I like.
