### ISSUE TITLE
Add "Fuel" tag

### ISSUE THREAD

**Issue by deurk** [DestinyItemManager/DIM#2241]
I use DIM a lot and usually plan ahead my infusing moments offline for when I can go back online.

Trouble is that more often than not, I will start by tagging items to infuse with the tag "infuse" and the fuel items with "junk", items I dismantle when I log in before realizing that I wanted to keep them as fuel... It would really be helpful to be able to distinguish between "To be dismantled" and "To be used as infusion fuel".

Thanks.

**Comment by bhollis** [comment]
Hmm, the intention was that "infuse" was for the fuel, and "keep" or "favorite" was for stuff you wanted to keep around and infuse.

**Comment by deurk** [comment]
I see. I suppose if nobody already asked for such a tag is that people mostly use the way you describe. I'll convert my way to yours then.
