### ISSUE TITLE
Client Secret revealed through POST

### ISSUE THREAD

**Issue by tda0909** [DestinyItemManager/DIM#2242]
I may be wrong in my understanding of OAuth.  However, I think the call to /platform/app/oauth/token/ should be migrated server-side.  Currently that POST reveals the client secret.  If this is accurate, please remove this issue to prevent any abuse.

![dim github issue](https://user-images.githubusercontent.com/5675919/30848666-cd17cb7e-a26d-11e7-8796-403052043be7.png)

**Comment by bhollis** [comment]
Thanks for bringing this up. We're aware of this, but don't have any plans to change what we're doing - we don't want to maintain servers.
