### ISSUE TITLE
Items with Classified Faction Shaders are Missing in DIM

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#2247]
> DIM can't seem to find items that have faction shaders on them, is this due to item classification in the API?

https://twitter.com/DatIbby/status/912764454105907200

**Comment by SunburnedGoose** [comment]
https://www.reddit.com/r/DestinyItemManager/comments/72m8le/bug_on_my_screen_the_character_on_the_left_isnt/

**Comment by bhollis** [comment]
It's looking like I won't get to play Faction Rally or work on DIM at all this week (too busy). I hope we can figure this one out.

**Comment by duckmanBR** [comment]
@bhollis / @SunburnedGoose  it was a API bug, not DIM, Bungie already solved the problem (at least people who complained said that now it's working).

**Comment by bhollis** [comment]
🙏🙏🙏🙏🙏
