### ISSUE TITLE
Request:  Add search term for D2 factions

### ISSUE THREAD

**Issue by paulharman** [DestinyItemManager/DIM#2249]
Hi,

Not sure if the info is in the API, but it would be useful to be able to search for faction gear.
e.g. is:FWC, is:DO, is:NM

Thanks

**Comment by bhollis** [comment]
We'll have to take a look - most of that sort of info isn't in the D2 database yet. Those keywords work for D1 though.

**Comment by thezoggy** [comment]
also to add to this, there is faction shaders

**Comment by chrisfried** [comment]
I also want this, but for all factions. I want to be able to search for Vanguard Tactical and see all of the loot I have that dropped from one of Zavala's engrams.

Looks like the engram definitions contain gearset lists. My assumption is that the hashes within correspond to appropriate items: https://destiny.plumbing/2/en/items/Engram.json

As an example, here's the gearset for the Vanguard Research Engram:

```      "itemList": [
        4248632159,
        4224076198,
        385045066,
        3741528736,
        555828571,
        4081859017,
        1490387264,
        2682045448,
        185326970,
        89175653,
        2615512594,
        3081969019,
        868792277,
        1532009197,
        4285708584
      ]```

**Comment by bhollis** [comment]
Linking #2363 since they'll have to use the same dataset.

**Comment by bhollis** [comment]
Rolling this into https://github.com/DestinyItemManager/DIM/issues/3031.
