### ISSUE TITLE
Increase Number of consumable and materials a guardian can hold

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#225]
I believe the new number of both is up from 15 to 20. Someone may need to confirm in game (am at work)

Should be a single line change here:

https://github.com/DestinyItemManager/DIM/blob/adf72a5007c9fe3fa1cbd46de481135c7e289e70/app/scripts/services/dimItemService.factory.js#L378

**Comment by Mulchman** [comment]
It is indeed 20 for consumables and materials.

**Comment by SunburnedGoose** [comment]
Nice.  I still haven't been able to play. :/

**Comment by SunburnedGoose** [comment]
I've fixed this, just can't push atm...

**Comment by SunburnedGoose** [comment]
![2015-09-09_104750](https://cloud.githubusercontent.com/assets/984608/9766759/42625d44-56e0-11e5-9183-7d7cfcebf30e.jpg)

**Comment by kyleshay** [comment]
fixed in https://github.com/DestinyItemManager/DIM/commit/bef40b6d82387bf07839ea2af8ae54a71850aabd
