### ISSUE TITLE
Loadout - Unable to remove item

### ISSUE THREAD

**Issue by duckmanBR** [DestinyItemManager/DIM#2250]
I (probably) dismantled a weapon that was in a loadout.  Now I can't remove it.
![screenshot_20170927-102615](https://user-images.githubusercontent.com/32077894/30916161-138be4b2-a36f-11e7-9615-53df61c597cf.jpg)
It's simple to just recreate the loadout, but would be nice to be able to remove the item.

**Comment by bhollis** [comment]
Good point! We shouldn't call them vendor items either.

**Comment by coffeyk** [comment]
This also fixes #2302
