### ISSUE TITLE
Armor Stats - Equipped items bug

### ISSUE THREAD

**Issue by duckmanBR** [DestinyItemManager/DIM#2253]
It's a bug on the API (https://github.com/Bungie-net/api/issues/171) not DIM, but just to be clear, I noticed that for armor, all Warlock items return with +1 Resilience (looks like Hunters have +1 Mob and Titan +1 Resist).
Also, on Legendary/Exotics, the item shows value for both the perks instead of only the selected.
It appears to only affect equipped items (can't be sure because I only have one helmet (exotic), and only exotics to put on other slots).

**Comment by bhollis** [comment]
Good to know, thanks!
