### ISSUE TITLE
beta.dim - changelog link invalid

### ISSUE THREAD

**Issue by thezoggy** [DestinyItemManager/DIM#2254]
when clicking on the about link on beta.dim it takes you to:
https://github.com/DestinyItemManager/DIM/blob/dev/docs/CHANGELOG.md#next

which is invalid as there is no 'dev' branch.

it should point to:
https://github.com/DestinyItemManager/DIM/blob/master/docs/CHANGELOG.md#next

**Comment by bhollis** [comment]
Good catch. Should be an easy fix if somebody wants to grab it.

**Comment by thezoggy** [comment]
while this looks like it was fixed... I just had a DIM update.. clicked on the about link and it tried to take me to:
`https://github.com/DestinyItemManager/DIM/blob/dev/docs/CHANGELOG.md#next`

so looks like the fix was reverted?
