### ISSUE TITLE
Organize mods command

### ISSUE THREAD

**Issue by mattsigal** [DestinyItemManager/DIM#2255]
I know a lot of players are organizing their mods by rarity: keeping legendary (purple) mods in their character inventory and putting all the rare (blue) mods in their vault. Then when there are rare stacks of 3+ in the vault, transferring them to their character to give to the gunsmith.

It would be awesome if we could add a button or two to DIM that would automate this -- transfer all blue mods to the vault and transfer all stacks of size 3+ from the vault to the active character.

**Comment by bhollis** [comment]
Search "is:blue mod", click on the vault header, and use that to transfer. This'll be better when we have an is:mod keyword. 

-Ben

**Comment by duckmanBR** [comment]
so **that** is what the magnifying glass do!

**Comment by duckmanBR** [comment]
@bhollis just a comment, it doesn't transfer all the items.  looks like there's a limit in quantity of items in each transfer.

**Comment by mattsigal** [comment]
Yeah, the search works but I figured it was such a common task that it would be nice to have a convenient button that did the transfer to the vault and from the vault for you.

**Comment by thezoggy** [comment]
prob would be nice to have a 'farming' mode for mods where it puts all the character mods to the vault and pulls in blue mods across all character. which that way you can just go to the gunsmith to trade in / dismantle for glimmer

**Comment by bhollis** [comment]
@kyleshay I can think of two ways to do this - one is to make it an option for "Farming Mode" and just do it continuously. One is to have an "Auto layout" like the old "gather engrams" that's "organize mods" or something. Any preference?

**Comment by JeffHowden** [comment]
See #2295 for possible ways to address this via menu items for the least clicks possible to:

1. Move all blue mods to the vault automatically.
2. Stop auto-move of blue mods to the vault and move blocks of 3 blue mods to current character for trading in for purple mods.

**Comment by WegDamit** [comment]
2c:
I'd like to be able to search for mods for a particular class of items, like only chest or warlock bond mods.
Like: "is:chestmod" i"s:warlockbondmod" or "is:mod is:chest", or "is:warlock is:mod is:bond"

Or is something like that already there....?
