### ISSUE TITLE
[nitpick] The strange coin package technically goes in the "Special Orders" section of "Post Master" not "Messages"

### ISSUE THREAD

**Issue by Mulchman** [DestinyItemManager/DIM#226]
The package we got for having a valid email addresses on Bungie dot net technically shows up in the "Special Orders" area of the "Post Master". In DIM, it's showing up under the "Messages" section of the "Post Master".

Example:
![1](http://i.imgur.com/9xh7ghS.png)

**Comment by Mulchman** [comment]
One of these is the itemHash of the package (the other is Focused Light): 2910404660, 2537120989

**Comment by SunburnedGoose** [comment]
Thanks.  I'll change it.  Hard to know what you don't have :/  Would be nice to get that QA resource in here ;)

**Comment by SunburnedGoose** [comment]
Fixed.
