### ISSUE TITLE
Add searching for power mods to be similar to other items.

### ISSUE THREAD

**Issue by joshminnie** [DestinyItemManager/DIM#2263]
Searching in DIM is a powerful tool, with the introduction of power mods, it would be nice to include their properties within the search.

For example the search string:

```
is:powermod is:arc is:leg is:hunter
```

Would result in only showing powermods matching that criteria. This would make it easier to find power mods that we want to trade in or see what's available to equip where.

**Comment by kyleshay** [comment]
it could be cool if you clicked a weapon and it showed you which mods you could apply to it, kinda like infusion fuel finder..

otherwise, if you click on a mod it could show you what you could apply it to.

**Comment by duckmanBR** [comment]
@joshminnie until then, #2335 should help a little...

**Comment by bhollis** [comment]
I'm gonna take #2335 as the solution to this until the manifest has more info on what mods are what. Otherwise we'll have to maintain a mapping by hand.
