### ISSUE TITLE
Add a search for stackable items

### ISSUE THREAD

**Issue by joshminnie** [DestinyItemManager/DIM#2265]
Similar to the behavior of level and light add a search flag for stacked items.

**Examples**
```
stack:<3
stack:>3
stack:>=3
stack:<=3
```

**Comment by kyleshay** [comment]
currently we have `is:stackable`, what would be the use in knowing if you have >/=/< a certain amount?

**Comment by duckmanBR** [comment]
@kyleshay because in D2 you can exchange 3 equal blue mods for a purple one.  So people are moving all blue mods to vault and then moving back only the stacks with 3 (or more)...

**Comment by kyleshay** [comment]
Linking #2255

**Comment by duckmanBR** [comment]
I implemented that but I messed my fork so it could take a little longer...
