### ISSUE TITLE
Exporting items with a comma in name messes up that line of the CSV when opening in excel

### ISSUE THREAD

**Issue by elsnoir** [DestinyItemManager/DIM#2266]
Not a huge issue because the only example I have is on the shotgun 'First In, Last Out' which may be  the only weapon or armor in the game with a comma in it's name.  Essentially though when you open excel it causes the name to get split putting:
Name = First In
Tag = Last Out

Then shifting everything to the right one column.

Attached is a screenshot showing this.
![screen shot 2017-09-28 at 1 15 56 pm](https://user-images.githubusercontent.com/24308915/30980556-79012286-a44f-11e7-83cb-244c8866be81.png)

For Excel if you use double quotes around a value it ignores any commas in the quotes.  So the line would need to look like:
`"First In, Last Out",,Legendary,Shotgun,285,Void,Vault,0,false,false,undefined,27,70,71,60,60,50,6,50,,`

It would probably be simplest to throw double quotes around all the weapon/armor names than try to fix just this one weapon.  It would also ensure that if any other items are released with similar naming that the CSV would be able to be opened in Excel without issue.

Anyway, I am not good enough with JS to tell you exactly what needs to be done to fix this but just wanted to make you aware.  I love what you guys do though and think it's the best inventory app for Destiny.

**Comment by kyleshay** [comment]
hey! nice catch - could you try it in the beta version? there was a fix that went out yesterday that should have fixed this.

https://github.com/DestinyItemManager/DIM/pull/2252

https://beta.destinyitemmanager.com

**Comment by elsnoir** [comment]
Yep, it works correctly in the beta version.  Sorry, I searched for the issue but did not see it.  I think I was only searching in Open issues though.

Thanks!

**Comment by kyleshay** [comment]
No problem, glad to hear it's working :)
