### ISSUE TITLE
D2 - max light level

### ISSUE THREAD

**Issue by thezoggy** [DestinyItemManager/DIM#2269]
max base power shows out of 300:
![dim](http://zoggy.net/firefox_2017-09-28_16-44-57.png)

but max power with mod is actually 305.
http://heavy.com/games/2017/09/destiny-2-how-to-raise-your-light-level-to-305-engrams-powerful-fast-best/

then 350 if you do raid gear.

**Comment by pastuleo23** [comment]
Base power says w/o mods. It's working as intended.

**Comment by thezoggy** [comment]
I read the tooltip as max base power without mods / with mods.
Which would mean 300 is wrong... but I guess the true issue is that I dont know what 300 is saying.
Is that my max power with mods for my stuff or the actual 'max' per the game allowed (out of).

I've always heard that the actual max is 350,
http://www.eurogamer.net/articles/2017-09-26-destiny-2-power-level-265-300-350-level-cap-4747

**Comment by bhollis** [comment]
It's your max *base* power, which does not include mods. This governs the level your drops will be at. Full max power is shown next to the max power loadout  

-Ben
