### ISSUE TITLE
Quickly pick the right ghost shell

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#2270]
It would be nice if it was possible to quickly pick the right ghost shell

Maybe in the section with ghosts we instead (or in addition) show a 'ghost selector' your ghosts could be abstracted away and you just could press some buttons to pick the 'right' ghost.

If you could equip the ghost by knowing what perks you'd want.

https://www.reddit.com/r/DestinyItemManager/comments/730mcr/please_add_iconsoverlays_on_ghost_shells/

**Comment by bhollis** [comment]
That'd be cool!

**Comment by MistaTwist** [comment]
Should this be split into two tasks, one for the logic and one for the iconography/display of perks in the UI?

Perhaps circles matching planet colours to represent them, with icons/lettering (i.e: "XP") to denote the perk? Is there a known list of perks yet?

**Comment by JeffHowden** [comment]
I'd think separating ghosts by planet (with crucible being treated as a planet) and then icons to show the modifiers available.

Based on the 20 unique ghosts I've collected, these are the modifiers I'm aware of so far:

- [Planet] Cache Detector
- [Planet] Resource Detector
- [Planet] Experience Log
- [Planet] Glimmer Scavenger
- Crucible Experience Log
- Crucible Scanner
- Arc Weapon Analyzer
- Solar Weapon Analyzer
- Void Weapon Analyzer
- Kill Tracker

**Comment by philkernick** [comment]
It would be great it this could be somehow tied into the item compare items pane.

At the moment, all it does is shows the ghost name.  None of the perks are visible.

**Comment by DHager** [comment]
Could this be implemented by creating named loadouts and applying them in-order?

For example, suppose I have the following named loadouts:

* "My PvE loadout"
 * Weapons
 * Equipment pieces
 * Preferred default ghost
* "My Crucible loadout"
 * Weapons
 * Equipment pieces
 * Crucible-tracking ghost
* "My Earth Loadout"
 * Ghost with EDZ cache locator
* "My Mercury Loadout"
 * Ghost with Mercury resource detector

I sit down to play, my inventory is a mess, and I want to do is to complete some EDZ bounties.

1. Apply "My PvE loadout"
2. Apply "My Earth Loadout" (replacing just the ghost)

Then I decide to do some crucible stuff

1. Apply "My Crucible Loadout" (replacing everything including the ghost)

**Comment by kyleshay** [comment]
I like that idea @DHager - we would need to keep things somewhat generic to deal with internationalization, but we have something similar to this outlined in #2959 - basically an "active play mode" for DIM that helps you while you're playing. I'll link that request to this one so we have a reference to your comment, but we'll continue the discussion over there.

Also linking #3369
