### ISSUE TITLE
Dismissing keyboard (from search field) on iPad requires tapping a tappable button

### ISSUE THREAD

**Issue by barrettj** [DestinyItemManager/DIM#2274]
It would be nice if we could also tap on the gray background to dismiss the keyboard.  Currently you need to tap the dismiss button on the keyboard itself or tap on a tappable item (like a character emblem or weapon)

**Comment by bhollis** [comment]
I can tap on anything except for the grey space next to the character headers - that has a touch handler for dragging so it doesn't trigger the dismissal.

**Comment by bhollis** [comment]
@barrettj is this still the case now that there's a clear button on the search?
