### ISSUE TITLE
Move Popup Wraps with Long Text

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#228]
https://www.reddit.com/r/DestinyItemManager/comments/3kd0lg/released_v311_fixed_class_items_and_ghost_move/cuwt3rw?context=3

I'm having some funky pop-up behavior. Some items have a two row popup with icons wrapping down to the second line. Also the Show Details text missing when this happens. Seems to be happening if there's too much text on the popup title bar.

![](https://i.imgur.com/7pGV3l1.png)

![](https://i.imgur.com/zeMXlmn.png)

**Comment by jflayhart** [comment]
Somewhat related to this issue, I don't like how cramped the title bar is for this popups... especially when "Show Details" hangs off the side. Should we consider using an icon instead? http://fortawesome.github.io/Font-Awesome/icon/info-circle/

**Comment by kyleshay** [comment]
should we remove the int/dis values since those are in the popup now? maybe keep the def value though?

**Comment by jflayhart** [comment]
Yes.

**Comment by SunburnedGoose** [comment]
If you do, can you make sure that touch screens work with detail popup?

**Comment by SunburnedGoose** [comment]
And before you make too many changes, look at Luke's PR about the hover text

It might be easier to take the PR (after review) and then make the changes for this issue.

**Comment by jflayhart** [comment]
Good call.

**Comment by jflayhart** [comment]
Committed: https://github.com/DestinyItemManager/DIM/commit/6b3a5b6fed8850d69f8755edcd16bdfa668e4778
