### ISSUE TITLE
Highlight weapons of the same type

### ISSUE THREAD

**Issue by geevensingh** [DestinyItemManager/DIM#2280]
Often I'll get a weapon and wonder if it is as good - or at least as high in power - as the weapons of the same type I already have.

What if clicking on the weapon's type name immediately applied a filter for that type?

**Comment by bhollis** [comment]
Do you know about the compare feature?

**Comment by geevensingh** [comment]
No, I can compare items?  Side-by-side?
Even so, that's still not quite what I want.  What I'm looking for is roughly akin to the opposite of the infusion finder - I want to see if there is a better item around that I could infuse my new item into.  But "better" is fairly subjective, so it would be nice to highlight all the things I *could* infuse an item into.  Which also happens to be the same as the weapon type.

**Comment by kyleshay** [comment]
hmm, until we add something like that, you could try using search filters. for example if you have a handcannon that is 275 you could do a search that looks like `is:handcaonnon light:>275`

**Comment by geevensingh** [comment]
Yeah, that's roughly what I do.  But it seems like making those weapon types clickable would be helpful in my scenario, and probably others too.

**Comment by bhollis** [comment]
I think this is really handled by the compare feature, since it lists out all the items of the same type and lets you compare all their stats at once. It's the little double-box icon in the item popup.
