### ISSUE TITLE
Double tap to equip function not working as intended on Android? 

### ISSUE THREAD

**Issue by heavyghost** [DestinyItemManager/DIM#2286]
Hi guys,

Thanks for working on this awesome app. It has been a massive time saver when playing Destiny. 

I wanted to check if anyone else has had issues when trying to use the 'double tap to equip' (now abbreviated to DTTE) function on the mobile app? When I attempt DTTE, the item status screen appears instead of equipping the item. I can drag and drop the item in to the active inventory slot no problem.

I haven't been able to test on more than a single phone (Sony Xperia XA1 running Android 7), sorry about that. 

I have tried signing out of app, rebooting the device, deleting and recreating the shortcut with no change in status of this issue. 

I've been able to define the following unique behaviors of the issue below:

* The DTTE function works as intended on the desktop browser app, across all inventory classes.
* The DTTE function works consistently on the Android DIM app (v4.17.0) when equipping from the following inventory classes : Character Sub-classes, Ghosts, Emblems, Emotes.
* The DTTE function works inconsistently on the Android DIM app (v4.17.0) when equipping from the following inventory classes : Sparrows, Ships. 
* The DTTE function does not work at all on the Android DIM app (v4.17.0) when equipping from the following inventory classes : Weapon slots (Kinetic, Energy, Power), Armor Slots (Helmet, Gauntlets, Chest, Leg, Character Class specific item ).

Hope this helps, please let me know if I can provide anything else.

**Comment by heavyghost** [comment]
Not sure if its worth noting, but using the 'tap and hold' function on an item (hold finger on item for approx 1s, short vibrate is triggered), then tapping on the active item slot works for weapon and armor slots just fine.

**Comment by duckmanBR** [comment]
Did you try to use the app on landscape mode? It should work.
Anyway, it's not a Android problem, asked some friends on iPhone and they also have the same problem.  I believe it's related to the size of the item popup. If it cover the item icon, DTTE won't work.

**Comment by heavyghost** [comment]
Hey DuckmanDR, no joy trying out Landscape mode on my end. It seems like the timing for the double-tap needs to be tweaked or something.

**Comment by kyleshay** [comment]
Hi @heavyghost - it's on the list and I'm able to reproduce it myself. Haven't had time to look at this particular issue, but anyone is welcome to pick it up

**Comment by bhollis** [comment]
I'd actually like to remove this feature on mobile. @kyleshay @SunburnedGoose what do you think? At the very least it interferes with the default double tap to zoom feature on iOS.

**Comment by SunburnedGoose** [comment]
We can disable zoom.  We shouldn't need zoom. I would at least like to measure its usage, and then to measure its error rate by tracking an item being unequipped within 30s after being equipped with double tap.

**Comment by bhollis** [comment]
We actually cannot disable zoom, at least since iOS 10.

**Comment by kyleshay** [comment]
currently seems to be working as expected on android. if you're still seeing an issue, please let us know. thank you!
