### ISSUE TITLE
support ! for search

### ISSUE THREAD

**Issue by thezoggy** [DestinyItemManager/DIM#2287]
lets say I want void items..
`void`, `is:void` work.

now lets say I want anything but void...
`not:void` works.
`!void` does not.

using ! seems way more logical to me to use than changing `is` to `not`.
especially on mobile where you can insert `!` before the term way easier than changing out a word..

**Comment by kyleshay** [comment]
the negative expression to `is:void` would currently be `not:void` in DIM - to a programmer an exclamation mark might make sense, for others maybe a negative sign: `-is:void`? I think that using `not:` reads well. 

Being said, I am open to adding it as another option.

**Comment by thezoggy** [comment]
corrected `isnot` -> `not` in example. 

you have  `is:` and `not:` to inverse the result.
but for the term by itself, `void`, you have no inverse.. so it just seems logical to support `!`. 
especially since your using other programming related comparison.

**Comment by duckmanBR** [comment]
the notation is "a:b", "!b" would be off.  "!a:b" could be an option, or "-a:b" like @kyleshay said.  but I believe that the main problem is that "not:b" it's not clear enough to the user in the cheat sheet.

**Comment by bhollis** [comment]
I think it's easier for us to just stick with one way of querying. Agreed with @duckmanBR that we should do better in explaining how queries work in the help.

**Comment by kyleshay** [comment]
What would be the case to match the inverse of the string `void` by itself? `!void` would then match any item that doesn't have the word "void" in it's name/perks

What problem are you trying to solve, maybe there could be another way? Is this related to mods?

**Comment by thezoggy** [comment]
I wanted to quickly see what items I had that were void then I wanted to see what wasnt void. 
so I typed in `void` and saw those.. then I did `!void` and it didnt work.. so I then went and found `is:void` then tried `isnot:void` and that didnt work.. then found `not:void`. 

I still think the use case is valid on a phone when you just need to do something quickly.. `!void` is faster to do than `not:void`.

**Comment by thezoggy** [comment]
another use case.. 
there is no 'crucible' tag when looking for a ghost that gives you that perk. you can however just type in `crucible` and get them.. and if you wanted to exclude crucible related ones.. there is no way to do it (`not:crucible` isnt valid)

**Comment by duckmanBR** [comment]
@thezoggy, `void` and `is:void` doesn't return the same items.
`void` would bring an armor with a void mod, or even items with shaders with Void in the name. `is:void` won't.

Now I understood that what you really want is to negate a word search, and not having a different way to negate a predicate.

**Comment by thezoggy** [comment]
Yes, wanting to just do a simple word search and being able to inverse that is the goal.

**Comment by thezoggy** [comment]
this somewhat ties into: https://github.com/DestinyItemManager/DIM/issues/2270
