### ISSUE TITLE
[Feature] Add weapon collection and armor collection pages

### ISSUE THREAD

**Issue by DesktopMan** [DestinyItemManager/DIM#2288]
The game doesn't have collections for legendaries, but now that we have set rolls we could.

This suggestion is about having two new tabs (somewhere) that shows you all the weapons and all the armor in the game colored if you have it or grayed out if you don't, or something to that effect.

This page would also be a nice place to sort and filter gear to read user reviews of gear you don't have.

Yes, we don't have vault space for everything (yet), but I still think it would be a great tool for collectors (Collecting all scout rifles? Or all exotics? This page has got your back) as well as the previously mentioned review purpose.

Thoughts?

**Comment by paulharman** [comment]
I like this idea

**Comment by bhollis** [comment]
This is something we prototyped back in D1, but there were just so many sets that it was impractical. I'm hoping D2 will be the same?

**Comment by DesktopMan** [comment]
The main inventory screen of DIM already shows hundreds of items, wouldn't this be very similar in display scope? One tab for weapons, one for armor, sorted in categories based on primary, helmet, and so on.

**Comment by bhollis** [comment]
Closing in favor of #2363
