### ISSUE TITLE
Header Feature Icons

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#229]
Replace text-based links in the header with icons using font-awesome.

![screen_shot_2015-09-10_at_11 12 22_am_960](https://cloud.githubusercontent.com/assets/984608/9794028/72622096-57ae-11e5-9659-8e3c0c4b853f.png)

**Comment by SunburnedGoose** [comment]
To install font awesome, use 

    bower install --save components-font-awesome

**Comment by jflayhart** [comment]
On it.

**Comment by SunburnedGoose** [comment]
Next to the icon, add 'DIM'.  The version info is in the 'about' box.
