### ISSUE TITLE
Pay attention to stat direction

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#2291]
https://www.reddit.com/r/DestinyItemManager/comments/73up2f/when_comparing_fusion_rifles_the_system_assumes/

The manifest tells us if "lower is better" and we should choose colors based on that.

**Comment by kyleshay** [comment]
Oh sweet, didn't know there was a direct linear correlation between the stat and its charge time.

I'd almost say we should add that info in there!

**Comment by coffeyk** [comment]
Where in the manifest does this live? I looked around the Stats and StatsGroup and couldn't find anything about ordering like this.

**Comment by bhollis** [comment]
Hmm, I think I confused it with https://bungie-net.github.io/multi/schema_Destiny-Definitions-DestinyObjectiveDefinition.html#schema_Destiny-Definitions-DestinyObjectiveDefinition

**Comment by bhollis** [comment]
Closing, I don't think this is available.
