### ISSUE TITLE
In Japanese, the character name(warlock) becomes 2 lines.

### ISSUE THREAD

**Issue by shige-t** [DestinyItemManager/DIM#2296]
Original.
<img width="780" alt="2017-10-03 13 27 18" src="https://user-images.githubusercontent.com/12743278/31110048-2d297f2c-a83f-11e7-8813-2fcafaa57232.png">

Modified to 18px.
<img width="782" alt="2017-10-03 13 28 11" src="https://user-images.githubusercontent.com/12743278/31110052-2f8e5e0e-a83f-11e7-9a72-2220735ef0ce.png">

**Comment by delphiactual** [comment]
@shige-t Join us on crowdin to translate more of DIM into Japanese as well
