### ISSUE TITLE
Loadout - Save as New and Save should be different

### ISSUE THREAD

**Issue by duckmanBR** [DestinyItemManager/DIM#2297]
Right now both do the same, rename/override the original layout.
SaN should only be enabled if the user change the loadout name, or always, but if pressed would create a new loadout with a (1) suffix.

**Comment by nki2bpz** [comment]
On D1at some point the naming behavior changed. Originally if you editted a LO and saved it with a different name it created a new LO like a typical file save. Later builds, if you opened, edited, and gave it a new name it would overwrite the old LO with the new name. When I questioned this behavior the save as new was suggested to allow you to make several changes give it a new name and have both the new and old loadout
