### ISSUE TITLE
URL link obscures stat description 

### ISSUE THREAD

**Issue by maviza67** [DestinyItemManager/DIM#2301]
![754a62dd-c4fa-4b75-9ae0-2c98d7f6b87b](https://user-images.githubusercontent.com/32501204/31155061-8d3e6d34-a879-11e7-9932-49cceb5b7c96.png)

**Comment by bhollis** [comment]
Thanks Safari 👀 

I'll look into whether there's a way to suppress this.

**Comment by bhollis** [comment]
Hmm, I'm trying to reproduce this on my own iPad (iOS 11) and I can't get that popup to show up. What version of iOS are you using (and is that Safari, or Chrome?)

**Comment by bhollis** [comment]
OK, this is fixed in beta for Chrome.

**Comment by maviza67** [comment]
Yep.  I just logged back on to check.  Works perfect on chrome. Thanks.
