### ISSUE TITLE
Items still showing after in game deletion

### ISSUE THREAD

**Issue by DLCGNinja** [DestinyItemManager/DIM#2302]
![image](https://user-images.githubusercontent.com/32501226/31155110-bfc13a1e-a8a3-11e7-89e5-f9005a5e74bf.png)
Items that have been deleted still show in 'sets' and can't remove it from the sets.

**Comment by coffeyk** [comment]
This was fixed in https://github.com/DestinyItemManager/DIM/pull/2289

**Comment by kyleshay** [comment]
Correct, @DLCGNinja we'll run a release this weekend, but it should be fixed at https://beta.destinyitemmanager.com
