### ISSUE TITLE
Consider adding "name then primary stat" to sort order options

### ISSUE THREAD

**Issue by jerrycarlson** [DestinyItemManager/DIM#2303]
This is more an enhancement/QoL request than an issue.

My suggestion/request is to improve the base user experience by causing the "sort by name" option to secondarily sort by primary stat (descending, of course).   Alternatively, it would be nice to add a "name then primary stat" option to the sort options list.

This way, when viewing a cluster of the same named item, the first item in the cluster will be the one with the highest attack/defense value, on down to the lowest attack/defense value.  No more scanning the cluster each time to make sure you're dealing with the highest/lowest/whatever value.

It's a small QoL improvement that hoarder-gatherers like myself can really appreciate.

**Comment by joshminnie** [comment]
With static rolls on all guns this becomes less prominent, but yes, I've wished for something like this as well.

**Comment by kyleshay** [comment]
We currently do have a sort by "name", the secondary sort should be by primary stat.

FYI have you tried the `is:dupe` and `is:dupelower` filter? A lot of the time that we find people sorting by name is because they're trying to find item duplicates to dismantle. 

Lets track sorting in: #647

**Comment by jerrycarlson** [comment]
(I rely heavily on the dupe/dupelower filters -- they're awesome)

Regarding the statement that sorting by "name" should result in a secondary sort by primary stat -- that isn't how it works for me.  See the attached screenshot for an example.  In it, I am sorting by name and am filtering on one weapon name.  As you can see, the items in the filtered cluster are not arranged from high to low primary stat.

<img width="176" alt="example" src="https://user-images.githubusercontent.com/9376071/31236361-7d8f5bfa-a9b9-11e7-83bd-800a1671f46d.PNG">

**Comment by kyleshay** [comment]
ah, just looked at the code. you're right, it seems that it sorts name then primary stat. 

we'll track #647 for the change so users can build any custom sort they want.

**Comment by kyleshay** [comment]
curious, what is the usecase for having so many duplicates of that weapon?

**Comment by jerrycarlson** [comment]
I’m only keeping them for use in the MIDA quest on my second and third guys (the “dismantle 6 scout rifles” part).

 

Can’t wait to knock it out and get rid of them!

**Comment by kyleshay** [comment]
ahh, makes sense!
