### ISSUE TITLE
getLight has floating point issues in Destiny 2

### ISSUE THREAD

**Issue by coffeyk** [DestinyItemManager/DIM#2305]
**Summary**:
The getLight function does not calculate the light of a 305 loadout properly. This is due to floating point errors that accumulate as the items are summed.

**Expected Behavior**:
A 305 loadout should display as 305

**Actual Behavior**:
304.9 is displayed

**Proposed Fix**:
Scale the fractional weights (`3/21, 5/42, 2/21`) to all have the same denominator (`6/42, 5/42, 4/42`), then multiply each item by the numerator (`6, 5, 4`) and divide the total once at the end by `42`.

**Example**:
```javascript
(305*(3/21)) + (305*(3/21)) + (305*(3/21)) + (305*(5/42)) + (305*(5/42)) + (305*(5/42)) + (305*(5/42)) + (305*(2/21))
304.99999999999994
((305*(6)) + (305*(6)) + (305*(6)) + (305*(5)) + (305*(5)) + (305*(5)) + (305*(5)) + (305*(4))) / 42
305
```

**Comment by kyleshay** [comment]
Thank you!
