### ISSUE TITLE
D2 - store shader?

### ISSUE THREAD

**Issue by thezoggy** [DestinyItemManager/DIM#2310]
Moving a shader from one player to another player doesnt refresh the player vault correctly (pointless to do this, but still a usability bug).

how to reproduce:
Put a shader in the player vault. Click on a shader, and click 'store' for another character.
You see the shader gets moved to the global vault then is gone.. (it moves back to the player vault.. you just dont know it until you tell DIM to refresh).

So in the end, moving a shader to a specific person is pointless (same with split and take actions). Its either player vault or actual vault.

**Comment by kyleshay** [comment]
should be cleaned up in the beta, thanks for the report

**Comment by thezoggy** [comment]
ty!
