### ISSUE TITLE
Inventory Popup w/ take/split options

### ISSUE THREAD

**Issue by JeffHowden** [DestinyItemManager/DIM#2312]
D1 DIM seems to have had the info popup on inventory items removed making it no longer possible to see more info about an item in inventory or use the "take" or "split" options. Clicking an item in your inventory does nothing.

Interestingly, inventory items in D2 DIM have a popup with icons for any other characters you have, vault, and "take" and "split" options.

![image](https://user-images.githubusercontent.com/6680532/31214998-ba3dce4e-a962-11e7-9351-37bae50ebe36.png)

Is it possible that changes related to inventory management were accidentally done to D1 DIM code and not D2 DIM code?

**Comment by kyleshay** [comment]
Thanks for the heads up. I just pushed a fix for being able to click on items in D1, will look into issues w/ the stackable items in move popup.

https://github.com/DestinyItemManager/DIM/commit/2180c1a9b7833144c9572199e5cd8447944930cd

**Comment by kyleshay** [comment]
thanks for the report, should be fixed #2319
