### ISSUE TITLE
Google Drive login bug - iOS 11

### ISSUE THREAD

**Issue by edmiller47** [DestinyItemManager/DIM#2313]
Two (probably related) issues: 
1) On my iPhone 7 (running iOS 11.0.2), DIM logs me out of Google Drive at least daily. DIM does not do this on Google Chrome on my PC.

2) When I do press the "Log into Google Drive" button on my phone, it turns yellow and stays that way until I close the app. If I then reopen DIM and go to the DIM Storage page it shows "Log out of Google Drive".

I've searched through Google/Google Drive settings to see if there's some kind of setting specific to mobile that might affect this, and didn't find anything.

**Comment by bhollis** [comment]
I have a suspicion that Safari's new ban on third-party "advertising" cookies may have broken things here. I'll try to figure out what's up and what options we have.

**Comment by bhollis** [comment]
https://github.com/google/google-api-javascript-client/issues/297

**Comment by bhollis** [comment]
@edmiller47 is this fixed in DIM 4.19? I've switched to a new auth mechanism.

**Comment by edmiller47** [comment]
I’ll have to let you know tomorrow. When I started DIM this morning I got the update and still had to re-log in to google drive

**Comment by edmiller47** [comment]
Just to be clear, item 2 of my original post seems to be fixed, won’t know about item one until later today or tomorrow.

**Comment by edmiller47** [comment]
I've been opening and closing DIM throughout the day today. Had to hit the "log into Google Drive" this morning before Bungie started their mantentance period, and again just now, some time after maintence was completed.

DIM on my PC has remained logged into Google Drive the entire time.

**Comment by bhollis** [comment]
Back to the drawing board. Wish the Google API client wasn't so bad. Might have to write our own. 

-Ben

**Comment by edmiller47** [comment]
Your users appreciate the effort you folks put in to making this great app even better. Kudos.

**Comment by edmiller47** [comment]
Odd. Just opened DIM on my phone and am still logged into GD

**Comment by edmiller47** [comment]
Don't know if this belongs here or in https://github.com/DestinyItemManager/DIM/issues/2223 - would like to see some sort of confirmation that the **Force sync data** action has been completed. And perhaps there should be an option to enable Google Drive sync only - i.e. disable local browser storage? Just a thought

**Comment by bhollis** [comment]
Rolling this into a bigger tracking issue #2713.
