### ISSUE TITLE
bug(quest): completed Relics of the Golden Age objectives are "incomplete" in green

### ISSUE THREAD

**Issue by sbolel** [DestinyItemManager/DIM#2314]
### Expected Behavior

- the labels for individual objectives of the "Relics of the Golden Age" quest step change from "Incomplete" to "Complete" when the green bar fills to the end and the objective is met

### Current Behavior

- individual objectives of the quest step are labeled as "Incomplete" even though the green bar is filled and the objective criteria are met

### Screenshot

![image](https://user-images.githubusercontent.com/1915925/31227085-9a394652-a9a6-11e7-9ae8-a8c56b94d4b6.png)

**Comment by bhollis** [comment]
Good catch. We were reading the wrong property for completion.

**Comment by sbolel** [comment]
Sweet! Glad it helped. Have a nice day.
