### ISSUE TITLE
Tagged items not saving across devices - Google Drive enabled on both devices

### ISSUE THREAD

**Issue by SGTCSLAUGHTER** [DestinyItemManager/DIM#2315]
I have done this from a couple different computers and it just doesn't seem to work.  

Gaming PC - Win 10 - Browsers Chrome/Firefox
Home laptop - MacBook Pro - 10.12.6 (Chrome/Firefox/Safari)
Work laptop - MacBook Pro - 10.12.6 (Chrome/Firefox/Safari)

My first attempt was on my gaming PC.  I tagged all my items, force synced, etc.  Then I tried to view it on my home laptop and there were no tags.

Last night I retagged everything again on my home laptop and I'm on my work laptop now and there are no tags at all.  

All computers have Google Drive enabled.  I asked in Discord today if I should see a file in Google Drive and I was told that I would not...which seems odd to me, because if something is being stored on my Google Drive then I'd like to be able to see that file and know where it is saved. 

Suggestions on trying to get this to sync up across multiple devices?

**Comment by duckmanBR** [comment]
It's a know bug.  Check #2223 and try some of the workarounds there, on my post and also on @Sleepydragn1

**Comment by bhollis** [comment]
Hmm, I'm not sure this is the same as #2223. @SGTCSLAUGHTER, can you take a look at the storage page for each of the machines and see what it says? Plus, which version of DIM are you using?

**Comment by SGTCSLAUGHTER** [comment]
Version 4.18.0 (release), built on 10/2/2017, 12:56:28 AM

What do you want me to check on the Storage page?  Both say that Google Drive is Enabled, Local Browser Storage is also enabled.

**Comment by bhollis** [comment]
What data does it say it has in Google Drive?

**Comment by greggtavares** [comment]
I have a similar concern, I noticed on my iPhone the tagged items don't sync although it states sync with google drive i do not ever remember logging to drive for this on my mobile or PC (just a thought). So then I checked the beta and regular version and the beta is acting like i've never used the application. Nothing is synced there at all just like iphone.

**Comment by Sleepydragn1** [comment]
@greggtavares Just so you know, the beta version is completely separate from the normal version of DIM. Beta clients will only sync with beta clients, and login information doesn't transfer.

**Comment by greggtavares** [comment]
I did realize that last night and switched all devices. Things are great now. Ty.

Sent from my iPhone please excuse spelling.
________________________________
