### ISSUE TITLE
Minor Layout Adjustments

### ISSUE THREAD

**Issue by jflayhart** [DestinyItemManager/DIM#232]
There are some minor layout changes that should be addressed:

1. Padding and margin adjustments (i.e. "show detail" view)
2. Increase the width of the header content to the stores

**Comment by kyleshay** [comment]
for the free addl column it should just be adjusting:

https://github.com/DestinyItemManager/DIM/blob/dev/app/styles/main.css#L442

from 310px to 312px

**Comment by kitsunekyo** [comment]
# Polished regular and condensed Layout
![layout-update-01](https://cloud.githubusercontent.com/assets/8297816/9828690/a966e038-58f1-11e5-8225-08ca266c9a55.JPG)

* fixed vertical alignment in header
* fixed subpixel (blurry text) issue whenever the loading animation is displayed
* improved readability for character cards
* updated loadout button to be in line with header icons
* added transparent background for loadout button to make it stand out more as interactive element
* consistently aligned UI elements for a more clean and structured view
* fixed negative margin issues on storages

![layout-update-loadout](https://cloud.githubusercontent.com/assets/8297816/9828691/ac2071ea-58f1-11e5-87e7-a2281f841e9f.JPG)

* fixed issue where hover state was not properly shown for loadout sets
* replaced the copy focused buttons with icons to be inline with the rest of our interactive elements
* adjusted colors of loadout element to fit the rest of the design
* fixed several margin and padding issues
* replaced fixed width values of loadout buttons with percentage values to allow flexible width

**Comment by kyleshay** [comment]
looks so awesome @kitsunekyo 

Unrelated, but what about updating the header (where all the links, username, and icons are) background to match that darker gray that you're using in loadouts, or even the highlight color you're using in that edit button? 

Could look a bit better, since that head right now is so light, and with the white text on it, it is a little harder to read. Limiting our color pallet also will make things flow a bit better?

**Comment by SunburnedGoose** [comment]
There are tools to measure contrast ratios. I don't think the header passes
:)

**Comment by Mulchman** [comment]
Something else layout related- the Post Master "Messages"/"Special Orders"/"Lost Items" sections aren't having the 'setHeight' function called on them.

Something like:
>       setHeight('.sub-section.sort-messages');
>      setHeight('.sub-section.sort-specialorder');
>      setHeight('.sub-section.sort-lostitems');

**Comment by kyleshay** [comment]
closing for now since we've applied many of these updates. feel free to continue commenting here, or creating a new issue for other suggestions.
