### ISSUE TITLE
Android landscape zoom focus

### ISSUE THREAD

**Issue by nki2bpz** [DestinyItemManager/DIM#2321]
When using the search bar if I zoom in to see what I'm typing, or the search suggestions, the window resets focus to center as I'm typing causing me to type a couple letters, drag back to the search bar to see suggestions, type a couple more letters reseat to search bar.  I don't know if I'm the only one experiencing this. On samsung gs6, with android 7.0 and chrome browser.

**Comment by bhollis** [comment]
Could you try out the latest beta and see how it looks?

**Comment by nki2bpz** [comment]
Yes. in latest beta, same issue. When zoomed on the search bar and typing it moves out of view

-------- Original message --------

**Comment by nki2bpz** [comment]
It happens as soon as you get to is:    As soon as the dropdown appears for filter suggestions. Hitting the android back arrow snaps it back into view and closes keyboard. This isn't app breaking, just makes it annoying enough that I keep going back to laptop

**Comment by nki2bpz** [comment]
Upon closer inspection the the content window doesn't change the top bar moves right out of screen as the dropdown happens, the dropdown then floats up and down with the content window as opposed to being anchored to the top bar with the search bar.

**Comment by duckmanBR** [comment]
@nki2bpz I'm on a G4Plus on Android 7 and Chrome 61.0.3163.98, but can't zoom in or out on DIM... The same on Chrome Beta (62.0.3202.38).
I'm also trying to reproduce the other issues but no luck.  I use SwiftKey.
The only thing that I can confirm is that yes, the autocomplete popup is not anchored on the search bar, it's on your inventory, so if you scroll the window the popup will also scroll...
![screenshot_20171006-101156](https://user-images.githubusercontent.com/32077894/31279405-5834ef16-aa7f-11e7-9aa0-558269ab6204.jpg)

**Comment by nki2bpz** [comment]
In portrait I see the same thing you do, no problems there. It's in landscape and zooming where you will see the issue. Portrait zoomed is the only way I can use the app on the phone without reading glasses.

-------- Original message --------

**Comment by nki2bpz** [comment]
![dim landscape zoom](https://user-images.githubusercontent.com/15946723/31303763-d0262be6-aae0-11e7-88f8-a9c6b7265324.gif)

**Comment by nki2bpz** [comment]
Fixed with latest built
