### ISSUE TITLE
Visual identifier for shaders on the items which have them applied

### ISSUE THREAD

**Issue by joshminnie** [DestinyItemManager/DIM#2326]
With shaders being consumables now, it seems important to provide some sort of visual identifier to the item (before opening up the details) to show which items have shaders applied.

There are various different details that we could emphasize, but the key is really to make it easy to discover and easy to make quick decisions.

**Comment by kyleshay** [comment]
shaders can just be grabbed from the collection now. we'll keep this in mind when working on item tiles in the future.
