### ISSUE TITLE
Power mod detail pop up doesn't match selected mod

### ISSUE THREAD

**Issue by joshminnie** [DestinyItemManager/DIM#2327]
All the properties seem right, but when I click on a legendary mod, the icon in the detail popup is blue.

![screen shot 2017-10-06 at 2 55 30 pm](https://user-images.githubusercontent.com/117469/31293870-c56c864e-aaa6-11e7-916e-a2a95dbae401.png)

**Comment by bhollis** [comment]
Yup, that’s a bug in the Bungie data. We’ve reported it to them. 

-Ben
