### ISSUE TITLE
Calculate Light As Items Change

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#233]
https://www.reddit.com/r/DestinyItemManager/comments/3kg3z1/suggestion_recalculate_light_value_as_items_are/

So, when equipping/unequipping items of varying ATK/DEF, the Light value doesn't appear to be calculated on the fly, but refreshing does pull the new number.
Considering it's a mathematical average of those values, would it be possible to offload that to the browser itself to run a quick calculation after an item is equipped?
Disclaimer: I have no idea how Chrome extensions work, so if it's un-implementable, I'll quietly go away.

**Comment by chrisfried** [comment]
I was contemplating this. Would it be preferred to
A. locally calculate the average as items are equipped, or
B. auto-refresh the light value every time an item is equipped.

**Comment by chrisfried** [comment]
If option A is preferred, some research into how Destiny handles rounding that value is in order.

**Comment by SunburnedGoose** [comment]
A is preffered.

**Comment by sargonas** [comment]
Here is a really good breakdown of light calculations and weighting each item type has. Hopefully it helps!

https://www.reddit.com/r/DestinyTheGame/comments/3kwmvh/how_overall_light_level_is_calculated/
