### ISSUE TITLE
Ability to empty character

### ISSUE THREAD

**Issue by Jayyface** [DestinyItemManager/DIM#2331]
Hoping for the ability to empty a character of everything not equipped in Weapons and Armor

or a locked farming mode that only moves items acquired prior to activating farming mode, to allow me to dismantle anything new I don't want without needing to transfer it back to my character.

**Comment by duckmanBR** [comment]
The closest you can achieve is "is:equippable not:equipped" and clicking the magnifying glass on the vault drop down.  But that would move from all chars.

**Comment by bhollis** [comment]
I don't think we'll add a function specifically for emptying your character. Try out searches like the ones @duckmanBR suggested, or include "is:new" to select only new items (ones you haven't clicked before). Transferring back and forth using searches is really fast.

**Comment by Jayyface** [comment]
That's unfortunate, thank you both though, I've used both methods before but they are somewhat inefficient for how I use DIM. Perhaps I use it incorrectly. Thank you though for getting back to me.
