### ISSUE TITLE
Display Icon of applied Armor Mods

### ISSUE THREAD

**Issue by DaoFerret** [DestinyItemManager/DIM#2333]
Hi,

First off, thanks for all your wonderful work.  I tried looking in the opened and closed list and didn't see anything, so I apologize if this might be a duplicate of another Enhancement request idea.

Currently there is no way to see what mod has been applied to armor, without clicking on each piece of armor.  It would be useful when trying to figure out which piece you want (where did I put that Arc Ordnance mod?).  Yes, I know you can search for it (which is nice as heck, and thank you!) but it might be more useful if a visual indicator was displayed, maybe in the upper left of the icon, the same as the elemental mod indicator on weapons?

**Comment by bhollis** [comment]
We're discussing a complete refresh of the item display in DIM that may include this. Stay tuned!

**Comment by bhollis** [comment]
<img width="48" alt="screen shot 2017-10-09 at 11 23 19 pm" src="https://user-images.githubusercontent.com/313208/31372083-e5a5acac-ad48-11e7-8ede-9e76fba20bf9.png">

For reference, here's what a "fully loaded" D1 item looked like... we gotta do better on using the space, and there's a lot of info to pack in before you even get to displaying shader and mod! We've got some neat new ideas we're gonna try out, though.

**Comment by bhollis** [comment]
Linking #2326

**Comment by kyleshay** [comment]
linking this comment: https://github.com/DestinyItemManager/DIM/pull/1646#issuecomment-302930230
