### ISSUE TITLE
Organize mods by type

### ISSUE THREAD

**Issue by Dave-Choi** [DestinyItemManager/DIM#2334]
There are a lot of mods that have identical icons that can only be slotted into particular armor or weapon types.  e.g. Arc Ordnance mods can be either for leg armor or chest armor.

Currently, mods are displayed in a big pool, with no way to visually differentiate between a leg armor mod and a chest armor mod without click/tapping for detail, which makes them difficult to manage.

I'd suggest separating them by what slot they go into, the same way that armor is currently separated.

Short of that, some sort of search filter like is:legmod(ification), would help.

**Comment by bhollis** [comment]
In beta, they're now organized by type. We also now allow you to search the item's type, so "is:modification leg" should do what you want.

**Comment by Dave-Choi** [comment]
This is a partial screenshot from the current release:
<img width="1362" alt="screen shot 2017-10-14 at 2 20 46 pm" src="https://user-images.githubusercontent.com/1098357/31578235-01234e9e-b0eb-11e7-9413-03a1a4ec9c42.png">

Compare to the beta site:

<img width="1363" alt="screen shot 2017-10-14 at 1 55 52 pm" src="https://user-images.githubusercontent.com/1098357/31578067-ace5f44c-b0e7-11e7-9ff8-6bb25860cd14.png">

(I keep my purples in the vault, along with any transmat effects)

They are, in fact, ordered by type, but I still can't visually differentiate between which mods I have available for what without applying a filter.  The filter certainly helps, but when you're trying to plan a loadout, it would be nice to see what's what at a glance, and think about the whole loadout together.

Something like this would make it much easier to consider your build options:

<img width="1362" alt="dim mod sections mock" src="https://user-images.githubusercontent.com/1098357/31590602-1e7ea56e-b1e1-11e7-8d14-a771831e05ad.png">

**Comment by bhollis** [comment]
Linking #573

**Comment by kyleshay** [comment]
Mods are much simpler now. Can come back to this if needed.
