### ISSUE TITLE
'items' undefined

### ISSUE THREAD

**Issue by isamandathere** [DestinyItemManager/DIM#2336]
When i try to create a load out...I get a message ( cannot create load out as 'items' are undefined. I use chrome with the DIM extension version 4.19....any help appreciated

**Comment by bhollis** [comment]
What exactly are you doing to cause this to happen? I'm trying to create some loadouts but not getting that.

**Comment by isamandathere** [comment]
Ben....I am trying to do a weapon/armor loadout for my characters. I have
used this awesome feature on destiny 1. I'm using the same process as
before. It is like the weapons and armor are not recognized. I am a huge
fan of this app. Your teams do great work. I have no problems moving gear
ect. It's probably something really simple...but haven't figured it out
yet. I have the latest version of chrome and DIM. I use the chrome
extension. Thanks Brian

**Comment by duckmanBR** [comment]
AFAIK the extension now should be only a redirect to the app, but could you try using https://app.destinyitemmanager.com/ to see if this also happens there?

**Comment by bhollis** [comment]
Hi Brian, 

I understand the high level problem, but I'm unable to make it happen. More detail would really help me figure this out. For example, are you talking about Destiny 1 or Destiny 2? What version of DIM are you using (click "About" in the header). Does it happen when you create a new empty loadout and you add the first item, or something different? 

-Ben

**Comment by isamandathere** [comment]
Ben...I am currently using 4.19.1...and I get the message when I try and
create a new load out. I am using it for destiny 2. I used the link you
provided me and the same error message occurs. Thanks Brian

**Comment by bhollis** [comment]
Like this? Where do you see the error message? Is anyone else able to see an error doing this?

![loadout](https://user-images.githubusercontent.com/313208/31577622-370cbd98-b0c7-11e7-82b1-cfedbc5b3886.gif)
![loadout2](https://user-images.githubusercontent.com/313208/31577623-3735201c-b0c7-11e7-93f4-4a9537055f45.gif)

**Comment by isamandathere** [comment]
Ben....that's it....I even tried using create from equiped. Brian

**Comment by isamandathere** [comment]
Ben....sorry...It shows the message on the right under the DIM icon on tool
bar

**Comment by bhollis** [comment]
I'm afraid I have no idea how to make that error happen.

**Comment by isamandathere** [comment]
Ben...dude I really appreciate all your help in this matter. I took a photo
of the message with my camera phone...but can not get the file size any
smaller than a little over 6 mb. And you email will not take a file that
big...ugh ....Brian lol

**Comment by bhollis** [comment]
I'm sorry, I'm going to have to close this. Without any other reports and a clear way for one of us to reproduce the problem, I'm afraid we're not close to a fix at all. If you are able to find a way to provide more info, feel free to reopen.

**Comment by isamandathere** [comment]
Ben ...this is the copy of the source of the error...do not know if this
helps

<html lang="">

<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>DIM</title>
<meta name="description" content="">
<meta name="viewport" content="width=device-width, initial-scale=1,
user-scalable=no, viewport-fit=cover">

<link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
<link href="https://www.bungie.net" rel="preconnect">
<link href="https://apis.google.com" rel="preconnect">
<link href="https://ssl.google-analytics.com" rel="preconnect">
<link href="https://www.google-analytics.com" rel="preconnect">
<link href="https://accounts.google.com" rel="preconnect">
<link href="https://ssl.gstatic.com" rel="preconnect">

<link href="https://fonts.googleapis.com/css?family=Open+Sans:200,400,700"
rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Roboto:300" rel="
stylesheet" type="text/css">

<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png
<https://app.destinyitemmanager.com/apple-touch-icon.png>">
<link rel="icon" type="image/png" href="/favicon-32x32.png
<https://app.destinyitemmanager.com/favicon-32x32.png>" sizes="32x32">
<link rel="icon" type="image/png" href="/favicon-16x16.png
<https://app.destinyitemmanager.com/favicon-16x16.png>" sizes="16x16">
<link rel="manifest" href="/manifest-webapp.json
<https://app.destinyitemmanager.com/manifest-webapp.json>">
<link rel="mask-icon" href="/safari-pinned-tab.svg
<https://app.destinyitemmanager.com/safari-pinned-tab.svg>" color="#434444">
<meta name="theme-color" content="#404141">


<meta name="apple-mobile-web-app-status-bar-style" content="
black-translucent">

<link href="styles-5814dc.css
<https://app.destinyitemmanager.com/styles-5814dc.css>" rel="stylesheet">

</head>

<body>
<app>
<div class="notloaded">
DIM hasn't loaded. Something may be wrong with it, or with your browser
(maybe you have a content blocker, or have disabled JavaScript). Try force
reloading to make sure (Ctrl-F5 or Cmd-R).
</div>
</app>
<div id="browser-warning" class="hidden">Your browser is not supported by
DIM. Some or all DIM functionality may not work. Please switch to a
supported browser.</div>

<script async src="https://www.google-analytics.com/analytics.js"></script>
<script src="https://apis.google.com/js/api.js"></script>

<script type="text/javascript" src="manifest-24111c.js
<https://app.destinyitemmanager.com/manifest-24111c.js>"></script>
<script type="text/javascript" src="vendor-ded29c.js
<https://app.destinyitemmanager.com/vendor-ded29c.js>"></script>
<script type="text/javascript" src="main-c31d2c.js
<https://app.destinyitemmanager.com/main-c31d2c.js>"></script>
<script type="text/javascript" src="browsercheck-64644f.js
<https://app.destinyitemmanager.com/browsercheck-64644f.js>"></script>
</body>
</html>

**Comment by bhollis** [comment]
I'm sorry, that doesn't help. If you could open the developer tools there should be some red text that would help. 

-Ben
