### ISSUE TITLE
Show Recoil Direction stat

### ISSUE THREAD

**Issue by DenL** [DestinyItemManager/DIM#2343]
Currently DIM shows hidden stats such as Aim Assist and Zoom, however Recoil Direction is not shown. This would be especially helpful while using the weapon compare feature.

**Comment by kyleshay** [comment]
We've considered showing it, but struggle since it is hard to decipher- especially for users who may not be familiar. Maybe if we added a tooltip that explained how it worked?

**Comment by DenL** [comment]
Hmm, I think that explaining the stat should be out of scope for DIM.

Plus it's a simple higher is better stat, and no more complex than "Handling" or "Zoom". In fact I think "Handling" needs a tooltip more than "Recoil Direction". I had no idea what it does until I did a google search while I could make an educated guess on "Recoil Direction" just based on the name alone.

**Comment by kyleshay** [comment]
linking #923

**Comment by nki2bpz** [comment]
+1  I was just going to request this. I'm constantly having to open the weapon in destiny tracker to check recoil direction. I agree it is a pretty straight forward stat.
