### ISSUE TITLE
Quick search from an item popup

### ISSUE THREAD

**Issue by joshminnie** [DestinyItemManager/DIM#2344]
DIM's searching utility is such a powerful tool, it would be helpful if we could utilize it by clicking on some link within the item popup to perform a quick search similar to what the compare tool does, but strictly as a search.

When you are playing with DIM in front of you on your computer or mobile device, it's helpful to not have to type everything, so you can quickly move items around.

**For example:**
I click on a MIDA Multi Tool, it shows the weapon popup, and I can click on something like what I see in the comparison tool to do a search by Archetype or all items of that type.

Here's a very rough mockup:

![search-from-item-dim](https://user-images.githubusercontent.com/117469/31454325-14d946a6-ae83-11e7-9a45-13ba6e47255e.png)

**Comment by kyleshay** [comment]
archetype is currently just a function of impact. For example, If you did `is:scoutrifle stat:impact:=60`, you'd see all scouts of that archetype. We can reconsider this as we work on a new design for the modal popup.

**Comment by duckmanBR** [comment]
Its actually from RPM, but for the majority of the items, those walk together.
