### ISSUE TITLE
D1 Quest banners showing up for D2 Milestones in Progress section

### ISSUE THREAD

**Issue by Trekoid** [DestinyItemManager/DIM#2347]
Destiny 1 quest banners are showing up for Destiny 2 Milestones.

O Captain is rendering with the Black Garden quest banner from D1
![screen shot 2017-10-11 at 12 06 58 pm](https://user-images.githubusercontent.com/2205894/31461151-7f72a3dc-ae7d-11e7-8efd-9dbb7fe9362c.png)

The following are rendering with the D1 Generic Quest Banner:
* Data Requisition
* Initial Consultation
* Premeditation
![screen shot 2017-10-11 at 12 07 38 pm](https://user-images.githubusercontent.com/2205894/31461218-b5d5ad84-ae7d-11e7-8288-dc0dc988bb6d.png)

**Comment by duckmanBR** [comment]
It's coming from Bungie API.  There're some issues open there about this.

**Comment by Trekoid** [comment]
Ah, okay.
