### ISSUE TITLE
Fix Bounty Progress Status

### ISSUE THREAD

**Issue by jflayhart** [DestinyItemManager/DIM#235]
Since Destiny 2.0, Bounties are not showing progress status any more and since @chrisfried's enhancement in #234, we can add progress tracking for bounties to the new toggle setting.

**Comment by SunburnedGoose** [comment]
I've fixed the completed status.

**Comment by SunburnedGoose** [comment]
In fact, it fixes it for Gunsmith weapons, Quests, and Bounties

**Comment by jflayhart** [comment]
Committed: https://github.com/DestinyItemManager/DIM/commit/81e6a61583aafb7ae139f29f3ecb17aa0ac77814

**Comment by SunburnedGoose** [comment]
We're missing the progress value in the move popup.  That should always be there.  Can we get that back?

**Comment by jflayhart** [comment]
Yes, just figured we didn't need it any longer... Also, I would like to take the information icon off bounty, as it serves no purpose and creates empty space around the description

**Comment by SunburnedGoose** [comment]
Have progress in move popup is helpful when users don't show stats on the icons.  Always how the progress in the move popup, even if they don't show stats on the icons.  

Eventually, we should show the details of the bounty/quest, and what they progress means so the detail screen will be useful.  Until then, remove the icon.

**Comment by jflayhart** [comment]
Ok then let me take that check out for the movepopup progress, since it will always show no matter what. Then I think we are done with this issue

**Comment by SunburnedGoose** [comment]
Tag the issue in your commit and close it :)

**Comment by jflayhart** [comment]
Committed: https://github.com/DestinyItemManager/DIM/commit/619b209066e329f2504ad42e36141611fbe796bb
