### ISSUE TITLE
Multi-Select

### ISSUE THREAD

**Issue by Tbrown082488** [DestinyItemManager/DIM#2358]
I have been using DIM for a little now and truly enjoy it. I do have a question, is there a way to multi-select items to tag? I know you can batch move tagged items from one place to another. I am curious is there something I am missing where I can search "not:tagged" and then tag them all the way I want? Or manual select multiple items like you can with windows by holding down control? 

Thank you all for the help!

**Comment by bhollis** [comment]
There isn't today, but we expect to have this when we expand search: #397

**Comment by kyleshay** [comment]
FYI this was added to the search filter. When you create a search, the searchbox shows a tag icon. When you use that it will apply that tag to all items that match your search.
