### ISSUE TITLE
Clear search button not visible on Firefox

### ISSUE THREAD

**Issue by chrismcenteer** [DestinyItemManager/DIM#2360]
Super minor problem, on Chrome when entering a search you are given a button to clear the search:
![2017-10-16 11 57 09 am](https://user-images.githubusercontent.com/482637/31622019-3a7420d6-b269-11e7-86b0-f89084872bd8.png)
This button does not appear on Firefox:
![2017-10-16 11 56 38 am](https://user-images.githubusercontent.com/482637/31622037-44c1320e-b269-11e7-8f60-ed7d1b3bb51d.png)
No rush, just nice to have.

**Comment by chrismcenteer** [comment]
So I looked into it myself and it looks like it's just Chrome doing it when you use "input type=search".

**Comment by bhollis** [comment]
Duplicate of #2273.

Yup, we were relying on the input field to do it, but we should really do it ourselves.
