### ISSUE TITLE
Allow alternate delimiter for item search (for soft keyboard users)

### ISSUE THREAD

**Issue by Scuzzlebuttt** [DestinyItemManager/DIM#2361]
I put this on reddit...  Hope it's OK to post same here again...

On all of my tablets (android and windows) you have to access the symbol keyboard to type a colon (is:handcannon).  Would be super nice if you could alternately use a period (or some other equally easily accessible delimiter) instead of a colon.  Would make searching a lot easier/faster on  us tablet users.  Thanks for your consideration.

**Comment by rubenmachuca** [comment]
incluir :1st_place_medal: Adobe sesión Mejora Contrato E-firmas para clientes de Salesforce

**Comment by bhollis** [comment]
Hmm, I'm not sure what character would be good for that. On my phone's soft keyboard (iOS) only letters are available without hitting the symbol button.

**Comment by bhollis** [comment]
I've updated the search (on beta) to autocomplete without typing is: - does that help?

**Comment by Scuzzlebuttt** [comment]
Yea I think that would work just fine.  Now I have to figure out how to try the beta.  Thanks!

**Comment by Scuzzlebuttt** [comment]
That works freaking awesome!  Hope it makes it's way in to the main release.  Thank you so much!
