### ISSUE TITLE
Multi-Console Handling

### ISSUE THREAD

**Issue by M4V3R1C8** [DestinyItemManager/DIM#2365]
When swapping between consoles, it lists that I've got a Destiny 1 account on PlayStation when I don't. If I accidentally click on Destiny 1 PlayStation then the webpage needs to be reloaded as the option for Destiny 2 PlayStation is removed. Ideally, this would be fixed so that if the account doesn't have any items it doesn't show up in the list. If this is more difficult then hopefully you can fix the bug as is and allow us to swap to the other consoles without having to re-load the page.

**Comment by bhollis** [comment]
Yup, I get the same thing. I didn't want to do the extra account loads every time - unfortunately the Bungie API doesn't tell us up front when the account has no characters.

**Comment by M4V3R1C8** [comment]
Alright, maybe an alternative would be to allow us to hide the accounts we don't want to see. I'm not sure how difficult this would be considering that you're not actually having us log into the site itself.
