### ISSUE TITLE
Horizontal scrolling on mobile

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#2369]
Something changed recently and the character headers on mobile now scroll slightly, which makes swiping between characters difficult.

**Comment by duckmanBR** [comment]
On portrait?  I'm having no difficulties (on Android).
I just compared 2 screenshots (one from last month and another from today), the headers are in the same place/size.
Anything specific?

**Comment by duckmanBR** [comment]
On Android (at least on my Moto G4+) it's not exactly a smooth transition, but I can't notice any elasticity...
