### ISSUE TITLE
Manage/View/Organize item sets

### ISSUE THREAD

**Issue by chelor** [DestinyItemManager/DIM#2371]
Hey guys, just started downloading the code and tomorrow I'll deep dive into it. 
But one feature that Im thinking of doing is a section/separate page, where a user can see the defined armor sets that exist for each class (even if right now I need to hardcode them in some way).
In other words (and using an example) getting the full raid gear set (including weapons) and trials, might be straight forward. But there are certain gears that correspond to planets/vendors/events that are not as easy to remember if you have that in among your items or not.

So my idea is that.

Let me know what you think! :)

**Comment by kyleshay** [comment]
Hi @chelor ! Are you thinking of something like a "collection" type of page?

We do have something tracking that ask (#2288), but no developers are currently working on it. Would be fantastic to have some help! :) We're happy to answer any questions.

If #2288 is what you thinking, please close this task and track your ideas over there. 

Thanks ^_^

**Comment by chelor** [comment]
It is! with minor tweaks. I'll track them there and have a chat with you tonight if you can!
