### ISSUE TITLE
Mod Transfer - Always moving full amount

### ISSUE THREAD

**Issue by duckmanBR** [DestinyItemManager/DIM#2379]
I first noticed that yesterday on beta when I was trying to split some rare mods to test #2375 and couldn't (I had to split on 4.20.1, but 4.21 have the same problem), and today when I regrouped those splitted items I got the error message "**Looks like you requested to move more of this item than exists in the source**"

**Comment by kyleshay** [comment]
Hey - are you still seeing this in the beta? I'm unable to reproduce. 

Steps:
 - Look for a stack of items with > 5
 - Drag that item to another bucket while holding shift
 - Move only 2
 - Go back to the original stack and hit 'take'

?

**Comment by duckmanBR** [comment]
Sorry @kyleshay , forgot to add that I'm on mobile.
If I drag and hold over drop zone (on landscape) and chooses a <max value, after the transfer (after the refresh icon stops spinning) I get a "**The item request was not found**" error, but the items are split as it should.
But if I use the slider in the item popup (landscape or portrait) and choose vault/active char, all the items are transferred.

Anyway I can't reproduce the original error message when regrouping.

**Comment by duckmanBR** [comment]
#2388 fixed the main issue.  I'll open a new issue to the "**The item request was not found**" error
