### ISSUE TITLE
3x3 Inventory with Expanded Vault

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#238]
User on reddit would like to keep the 3x3 inventory but would like the expanded 6-column vault.

**Comment by Subject22** [comment]
I'd like to keep the 3x3 inventory space, but have a 9-column expanded Vault (scavenging the three extra columns back from the inventory).

**Comment by chrisfried** [comment]
I wonder if paging in the Vault is worth investigating.

**Comment by Mulchman** [comment]
Paging makes it hard to see everything at a glance. I can't even use the
Vault in game because of the pagination and awkwardness of the control
input for using and navigating through it. If a pagination system were
rolled out, I would want an option to not use it.

**Comment by SunburnedGoose** [comment]
I'm fine investigating.  Chris, have you seen the v4 comps for items?
Check it out.

**Comment by SunburnedGoose** [comment]
The idea I'll probably go with is just two settings.  We let the user decide how many columns they want for their character inventory, and as a separate setting, now many columns they want for the vault.

**Comment by Subject22** [comment]
Cool. Sounds great. Would this allow for an arbitrary number of Vault columns? My screen could easily take more than 9 total.
