### ISSUE TITLE
Character Transfer Icons - The First Wave bug

### ISSUE THREAD

**Issue by duckmanBR** [DestinyItemManager/DIM#2380]
I've noticed this strange behavior last week but only yesterday I had the time to look further.
Don't know if it's only this emblem, but for the 7 I have in my Warlock, "The First Wave" is the only one "bugged".

4.20.1 (from yesterday)
![screenshot_20171022-223733](https://user-images.githubusercontent.com/32077894/31898294-90c3c872-b7f7-11e7-9cdb-de9d2750e7b5.jpg)

Beta (since at least last week)/4.21
![screenshot_20171022-223812](https://user-images.githubusercontent.com/32077894/31898295-90ec3af0-b7f7-11e7-9d58-1d88f38ba7c7.jpg)

**Comment by bhollis** [comment]
What’s the bug?

-Ben

**Comment by duckmanBR** [comment]
After you asked, I analyzed the images... Is there now a border on the icon?
For the other 6 emblems looks like the border is in a unique color (so almost imperceptible), but the beta emblem border is kind of shaded from a dark blue to white/light grey... So it looks more like a resize artifact (I actually thought it was a slightly rotate) than a border...
