### ISSUE TITLE
Applied mobility/resilience/recovery mods are counted for all equipment

### ISSUE THREAD

**Issue by deurk** [DestinyItemManager/DIM#2385]
On each equipment piece, where stats bars are displayed (Mobility/Resilience/Recovery), there is a bug where each +1 legendary mod will be added to ALL the armor pieces rather than only the one where the mod was applied.

Example: 
Base Helmet is 1/1/1
Base Legs are 1/0/2

If I apply a Recovery mod to the legs, they become:
Helmet is 1/1/2 <---- should be 1/1/1
Legs are 1/0/3

If I also apply a Recovery mod to the helmet, they become:
Helmet is 1/1/3 <--- should be 1/1/2
Legs are 1/0/4 <--- should be 1/0/3

**Comment by deurk** [comment]
Seems like it might be an API bug, not a DIM one :)

**Comment by bhollis** [comment]
Yeah, unfortunately :-(
