### ISSUE TITLE
Loadouts not restricted by platform

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#2387]
Somebody on Twitter claimed their loadouts were not properly being restricted to a single platform. D2 I assume.

**Comment by duckmanBR** [comment]
Related
https://www.reddit.com/r/DestinyItemManager/comments/7r0oqu/loadouts_not_working_with_2_accounts/

**Comment by bhollis** [comment]
@SunburnedGoose would you want to take a look at this? I can guess but I don’t have multiple accounts.

**Comment by bhollis** [comment]
@duckmanBR do you know of anyone on the Discord who has multiple accounts who could check this?

**Comment by duckmanBR** [comment]
No.  But I'll ask if anyone can help.

**Comment by ericleone** [comment]
XB1 & PC Destiny 2. Just tried creating Loadout on each and they do not cross platforms.
Version 4.42.0.1889 (beta), built on 3/5/2018, 12:29:43 PM

**Comment by bhollis** [comment]
Closing as we haven't seen this.
