### ISSUE TITLE
Feature Request: Move current load out to another character

### ISSUE THREAD

**Issue by jmichas** [DestinyItemManager/DIM#239]
Move all weapons on a character to another character including blank space.
Many times for the weekly heroic / nightfall strikes you have a tweaked load out just for that strike / burn combo, it would be a nice convenience to be able to move the current weapons on a character to another character in one or two clicks.

**Comment by SunburnedGoose** [comment]
When you apply a loadout, you want the character to only have the items in the loadout on the character?  If you added a ghost for example to a loadout, then we will need to move all the ghosts off that character when we apply a loadout?

**Comment by jmichas** [comment]
No, I figure this really would only be for weapons. The benefit is when you have a hand tweaked load out for a particular burn and strike you can easily move that entire weapon load out to another character.

I think most people run the weekly/nightfalls all at the same time, so everyone in the fireteam switches characters and moves weapons, they hook up and run them again. So, this would make it easier to move the current loaded weapons to another character.

**Comment by SunburnedGoose** [comment]
You're asking to be able to move the currently equipped weapons on a character to another character, and then make room in the new character's inventory to match the available space in the original character?

**Comment by jmichas** [comment]
Yes, make room in the weapon inventory, so match it exactly to what the first character had including empty slots.

**Comment by SunburnedGoose** [comment]
Move their inventory too?

**Comment by jmichas** [comment]
Yeah, think of it this way. Behind the scenes you create a temp load out of weapons currently on the character, then you apply that load out to the character you are moving to, then you delete the temp load out. 

This sort of ties in with my other feature request to allow load outs to have intentional blank slots #224.

**Comment by SunburnedGoose** [comment]
Here's why I haven't implemented that feature.

That's up to 60 item transfers (10 items per type, 3 types, 2 characters), which is around 132 API calls.  There is a 1 second throttle per call, which is a little more than 2 minutes for the whole operation.

It doesn't sit well with me.

**Comment by jmichas** [comment]
But isn't that possible now?
If I have a character that is full in each weapons slot, and I have a load out that is full, aren't we at the same number of API calls?

I have a few load outs that are full and I don't think its unreasonable to wait for everything to move. I just run around the tower and do other stuff while items keep popping in to my inventory.

**Comment by SunburnedGoose** [comment]
Yes, but there very few loadouts have more than 60+ items. They are outliers and that's okay.  If I make it an easy function to swap gear between characters, then it use becomes much more common to see large sets being moved.  Next thing we will hear are users who want to move their armors, artifacts, and ghosts.  That's 10 types.  ~7 1/2 min worse case.  It's a terrible case.

We do plan on supporting selecting adhoc loadouts (multi-select) in v4 but I imagine users will be discriminating on what they choose and won't move entire characters back and forth.

**Comment by jmichas** [comment]
Yeah, I see your point. I guess Im an outlier ;)

**Comment by SunburnedGoose** [comment]
The idea just doesn't play well.  I need to put a feature into the app that notifies the user if their transfer will take longer than 30 seconds.

**Comment by Subject22** [comment]
Also remember that Nightfalls and Weeklies will be a once-a-week affair after this evening.

**Comment by jmichas** [comment]
Yeah, I guess we should wait to see what TTK brings. I have purposely been avoiding info on how everything works because part of the fun is playing blind and discovering stuff.

Thanks for a really useful app / plugin.

**Comment by bhollis** [comment]
Post-TTK, burn isn't as much of a thing, and we don't tend to run strikes on all characters, so I'm hoping this feature isn't as urgent. Plus, in the next version we're going to have "create loadout from equipped" which should help move items between characters. So I'm going to close this, but feel free to reopen if you think this would still be a really useful feature.
