### ISSUE TITLE
Comparison - No AA in Merciless causes misalignment

### ISSUE THREAD

**Issue by duckmanBR** [DestinyItemManager/DIM#2391]
Since Merciless have no AA, the comparison values misalign

![image](https://user-images.githubusercontent.com/32077894/32136996-a7098164-bbf6-11e7-8dd7-dc46db1b14f3.png)

This should also happens on any weapon that don't have a stat like the others of the same type...

**Comment by duckmanBR** [comment]
@KyleLilly I don't know if I ever tested this when it went live, but just went to compare Main Ingredient with Merciless and the stats are still misaligned...

**Comment by KyleLilly** [comment]
@duckmanBR when I run locally using master or using the webapp this is what I'm seeing:
<img width="415" alt="dim_stats" src="https://user-images.githubusercontent.com/3723216/33407966-ca8d1f6a-d541-11e7-942c-5d1782fb5208.png">
I don't have Main Ingredient so I can't test that specific scenario - do you see N/A at all or is the stat just missing still?

**Comment by duckmanBR** [comment]
I'm having problems to upload a screenshot to github, but the behavior is the same.  If Merciless is not the first weapon in the list, its recoil dir/zoom/magazine info appear one line up (as in the image I posted when opened the issue).  And if Merciless is the first (that I didn't check before, but it's the situation in your image) there's no aim assistance header but the weapons that have AA will show the info for it, so their list will have a "extra line" without header...  I'm on mobile (Android/Chrome) and tested on stable and latest beta.

**Comment by KyleLilly** [comment]
What version of Android and Chrome? This is what I see on mobile
![screenshot_20171130-081846](https://user-images.githubusercontent.com/3723216/33432825-6e7af7ae-d5a7-11e7-916c-8383de60ae44.png)
![screenshot_20171130-081846](https://user-images.githubusercontent.com/3723216/33432818-6a592d62-d5a7-11e7-97c4-062c08a16545.png)

**Comment by duckmanBR** [comment]
Android 7.0
Chrome Beta 63.0.3239.71
Chrome 62.0.3202.84
Edge 1.0.0.1267

**Comment by duckmanBR** [comment]
So, it's something on my account (or something on my items)...
I checked on my notebook (WIndows 10 / Chrome 62.0.3202.94 and Edge 41.16299.15.0) and its also not working... And on edge I'm not syncing so it's not any saved information.

I'll try to debug on the weekend.
