### ISSUE TITLE
Mobile Portrait - Store pager narrower than window

### ISSUE THREAD

**Issue by duckmanBR** [DestinyItemManager/DIM#2393]
I'm only 99% sure, but looks like the change in store-pager.scss to fix #2369 caused this.

On Oct 18 (on Beta)
![image](https://user-images.githubusercontent.com/32077894/32170073-47fbef58-bd5a-11e7-8eea-2b6248bf058a.png)

Yesterday (on Beta and 4.21.x)
![image](https://user-images.githubusercontent.com/32077894/32170079-4c7ad652-bd5a-11e7-8488-c03544b41662.png)

**Comment by bhollis** [comment]
Looks like an Android-only issue. Can somebody who has an Android phone take a look?

**Comment by duckmanBR** [comment]
@bhollis I reproduced on chrome PC 
![image](https://user-images.githubusercontent.com/32077894/33033545-d6bb77f6-ce0b-11e7-905a-fdc25a45ae61.png)

the settings for the device is 360x568 and 3 pixel ratio

**Comment by duckmanBR** [comment]
Actually you can reproduce it even if only resizing the window, no need to emulate device...

![image](https://user-images.githubusercontent.com/32077894/33033778-c8a770a6-ce0c-11e7-808b-a91c8fb60ce7.png)

I'm not trying to fix it because since I believe it was the fix to the problem on iOS that caused this, I won't be able to test if a fix will broke swiping in iOS again...
