### ISSUE TITLE
Transfer - Mobile landscape drag & hold error - Split Items

### ISSUE THREAD

**Issue by duckmanBR** [DestinyItemManager/DIM#2394]
If I drag and hold over drop zone (on landscape) and chooses a <max value, after the transfer (after the refresh icon stops spinning) I get a "**The item request was not found**" error, but the items are split as it should.

If I only transfer the item I get no error.  Splitting using the (now fixed) slider in the item popup, no error.

Can't test on desktop.

**Comment by bhollis** [comment]
This should have been fixed in #2388

**Comment by duckmanBR** [comment]
#2388 only fixed the "always moving full" part of #2379

**Comment by bhollis** [comment]
How can I reproduce this?

**Comment by duckmanBR** [comment]
Transfer (by drag & drop) any inventory item (consumable/modification/shader) to or from vault. But use the "hold on target" way (on mobile you need to hold until the tooltip helper turns green).
On the popup choose a value lower than max (transfer 2 of 3+ items).
Part of the stack will be transferred as expected/desired, but the "was not found" error message will appear.

If you transfer all the items (using this method) the transfer happens but no error shows up.
If you transfer any amount using the item popup transfer without error.

**Comment by bhollis** [comment]
That’s not what happens at least when I try on desktop. I wonder what could be mobile-specific about it?

-Ben

**Comment by duckmanBR** [comment]
I just tested using the "request desktop version" option on chrome and worked fine...
Unchecked the box and the transferred the same item (just for the sake of it).  Error message.

**Comment by bhollis** [comment]
Landscape or portrait? Screenshot?

**Comment by duckmanBR** [comment]
Landscape (afaik it's the only way to do drag&drop transfer on mobile...)

Pre-transfer
![screenshot_20171114-100555](https://user-images.githubusercontent.com/32077894/32779303-5576385c-c924-11e7-837a-d1d7107b591c.jpg)

Transferring Alkane Dust (stack of 11) to vault
![screenshot_20171114-100605](https://user-images.githubusercontent.com/32077894/32779305-57d7d3c6-c924-11e7-8fd2-dd3380640b43.jpg)

Choose less than total
![screenshot_20171114-100857](https://user-images.githubusercontent.com/32077894/32779307-5a16589c-c924-11e7-8b2d-3f48fcad4e7b.jpg)

Transfer done, error message shown
![screenshot_20171114-100904](https://user-images.githubusercontent.com/32077894/32779308-5bd8078e-c924-11e7-9159-5c8c0d60254d.jpg)

**Comment by bhollis** [comment]
Can you confirm which version of DIM you’re on?

**Comment by bhollis** [comment]
Oddly, on iOS I can’t get the move amount pop up to show up on drag at all.

**Comment by duckmanBR** [comment]
Beta 4.24.1.1595 (but I found this bug 23 days ago on #2379)

I usually have to wait 2-3 seconds hovering on the target area before the tooltip turns green.

**Comment by bhollis** [comment]
Try it now? It should be fixed by #2512.

**Comment by duckmanBR** [comment]
Sorry but didn't work, and I'm not sure, but looks like that the number of error messages increased, I'll test more later.

**Comment by duckmanBR** [comment]
Just tested again. Error message still there (but now I only got one message per transfer, 3 days ago I was receiving 2-3 for each transfer, don't know what happened).

**Comment by duckmanBR** [comment]
Just tested this and it's working.  Maybe it was fixed on #2581?
