### ISSUE TITLE
[Suggestion] Add support for vault sections (columns)

### ISSUE THREAD

**Issue by DesktopMan** [DestinyItemManager/DIM#2397]
Right now the vault view shows all gear for a certain slot grouped together. This suggestion is about adding support for sections that group related gear together in columns to make the vault easier to manage.

Default sections (if enabled) for weapons could be one for each type (auto rifle) etc. Default sections for armor would be one for each class. If disabled the vault behaves like it currently does.

If a user has tagged gear then there could be a section for each tag in use.

Thoughts?

**Comment by kyleshay** [comment]
Columns are a neat idea - we do have some ideas around grouping items in #573. We'll use that issue to track this idea by linking it
