### ISSUE TITLE
The left emote equippables are able to be stored in the vault, but there is no section for them in DIM.

### ISSUE THREAD

**Issue by Randactyl** [DestinyItemManager/DIM#240]
Maybe you guys are tracking this internally already, but this might be something to add just for completeness. I'm not sure what we'll be getting in the way of emotes besides TTK CE ones.

http://i.imgur.com/xe9PLjT.png

**Comment by SunburnedGoose** [comment]
I should have bought TTK CE it seems :/

**Comment by SunburnedGoose** [comment]
I'll be adding it soon, with the next update of DIM, v3.1.3.

**Comment by Randactyl** [comment]
Cool. According to the destiny tracker database the TTK CE emotes are all that exist for now.

http://db.destinytracker.com/items/emotes/emote
