### ISSUE TITLE
vault gather rep items

### ISSUE THREAD

**Issue by GotNoSkill** [DestinyItemManager/DIM#2401]
i clicked collect rep items under the vault tab didnt get the engrams you would get for leveling up the weapon dealer nor did it seem like i had extra weapons popping up in the bank or anything it went thru 700+ tokens also didnt feel like i got any extra weapon mods either

**Comment by bhollis** [comment]
It only moves reputation tokens.

**Comment by GotNoSkill** [comment]
so it just moved all my rep tokens to the bank? didnt even kno that was possible thanks for the answer problem has been solved
