### ISSUE TITLE
[Request] Item Search for items you don't own but are interested in learning about.

### ISSUE THREAD

**Issue by KalilaViolette** [DestinyItemManager/DIM#2404]
Since I can't really own every item in the game, I think it would be a really nice feature if it would be possible to do something like

lookup:"item name"

which could open an overlay window with search results, letting you click on each opening the information window just like in the main DIM window with the inventory you currently have. This would let users browse for items they wish to learn about and see reviews/ratings for weapons they don't have yet.

As it is currently, the user would have to know about the item first, then do the grind to obtain the item just to get access to that information, to which they could discover the item isn't very good for x reason(s) and people prefer something else (which might actually have been a lot easier to get).

Also, personally I'd like to be able to do something like

lookup:autorifles

which would display all auto rifles and would let users do a comparison for everything just like in your inventory, and would help users discover new weapons they might not have known about (like a blue weapon most people overlook and instantly destroy, but with the perks it has it makes it a good alternative).

I know I know, this isn't as easy as flipping a switch and adding a few lines of html, but it would be something I would love to see from DIM and I'm not able to really do this anywhere atm, as every database I can find is lacking someway or another whereas your site already gathers all the useful information, just is currently limited to items you own.

**Comment by joshminnie** [comment]
https://destinysets.com/ does something like what you are asking.

**Comment by KalilaViolette** [comment]
@joshminnie Thank you for that link, it actually has a lot of nice information. Definitely bookmarked.

**Comment by bhollis** [comment]
Merging into #2363
