### ISSUE TITLE
The progress target for bright engrams is extremely small

### ISSUE THREAD

**Issue by joshminnie** [DestinyItemManager/DIM#2407]
The mouseover target for checking your progress towards your next bright engram is extremely small and very hard to actually hit with your mouse, touch seems a lot better, but not sure why.

![dim](https://user-images.githubusercontent.com/117469/32447023-c4d196c6-c2d8-11e7-8c17-b67b75324b62.png)

**Comment by SunburnedGoose** [comment]
It feels like there is just 1px high element that you hover for the text :/

I don't want to make it larger, but I like the information.

**Comment by joshminnie** [comment]
2px - 3px might be enough to make that target a little easier to hit.

**Comment by joshminnie** [comment]
Actually according to this inspect, it's 2px already... 

![screen shot 2017-11-06 at 12 53 25 pm](https://user-images.githubusercontent.com/117469/32455870-a5ac4c14-c2f1-11e7-9b92-7492a87e35f5.png)

**Comment by bhollis** [comment]
Closing in favor of #2619.
