### ISSUE TITLE
Search - is:inloadout not working

### ISSUE THREAD

**Issue by duckmanBR** [DestinyItemManager/DIM#2410]
I have some loadouts, but is:inloadout match 0 items
Tried beta and stable (here I created a loadout just for the test)

**Comment by bhollis** [comment]
FWIW looking at the code I don't see how is:inloadout would ever have worked. It gets set when you load loadouts, but the next item refresh will overwrite it.

**Comment by bhollis** [comment]
We should probably remove the filter for now.
