### ISSUE TITLE
Search - overlapping predicates

### ISSUE THREAD

**Issue by duckmanBR** [DestinyItemManager/DIM#2411]
is:power - power weapons
is:power - items that contribute to your power level

But then, I couldn't find if the "items that contribute to you power level" is properly implemented...  Also, I couldn't find the D1/light version either...

**Comment by bhollis** [comment]
It’s is:haslight. I thought I got rid of is:power

-Ben

**Comment by bhollis** [comment]
Just checked again, there's no overlap. There's `power:` (search by power level) and `is:power` (is a power weapon).

**Comment by duckmanBR** [comment]
So this confirms that there's no implementation for **items that contribute to your power level**.
Should we remove [this on filters.html](https://github.com/DestinyItemManager/DIM/blob/d136fb8041495dee6549f6b10ff29ce3cce658d7/src/app/search/filters.html#L113) then? Also, as I didn't find the D1 version ([is:light](https://github.com/DestinyItemManager/DIM/blob/d136fb8041495dee6549f6b10ff29ce3cce658d7/src/app/search/filters.html#L107)), should we remove both?

**Comment by bhollis** [comment]
There is an implementation for those. Is:has power and is:haslight

**Comment by duckmanBR** [comment]
So the problem is on the cheat sheet...  There is no "has" on either versions.
