### ISSUE TITLE
Search - weapon type not filtering green/white

### ISSUE THREAD

**Issue by duckmanBR** [DestinyItemManager/DIM#2415]
Looks like (un)common weapons are not being filtered by weapon type filters, like is:sidearm / is:autorifle.

I can only test with the starter weapons, but since their description is classified, don't know if anything else on them is different.

beta/stable return the same.

source: https://www.reddit.com/r/DestinyItemManager/comments/7bwykf/searching_green_and_white_items/

**Comment by bhollis** [comment]
Classified items won't be filterable since they don't have a type. But the others should work? I don't have any greens.

**Comment by florianmientjes** [comment]
The categories property of an item is determined by infusionCategoryName.infusionCategoryName. This value is empty on whites and greens since you can't use them for infusion. 

typeName is appears to be set correctly for those items, maybe it can be used as a fall-back?

**Comment by bhollis** [comment]
Good catch. We should probably not rely on those, and use the itemCategories instead

-Ben

**Comment by duckmanBR** [comment]
There's a issue open on the Bungie API for empty itemCategories...
