### ISSUE TITLE
Browser not supported - Firefox user.js

### ISSUE THREAD

**Issue by Marc05** [DestinyItemManager/DIM#2419]
Can't seem to track down which one of these settings prevents DIM from working:

https://github.com/ghacksuserjs/ghacks-user.js/blob/master/user.js

I realize it's not necessarily a DIM issue, so any help is appreciated.

**Comment by kyleshay** [comment]
Could you provide a little more information about what this is, and what specifically isn't working?

**Comment by Marc05** [comment]
The user.js file is a configuration file for Firefox. It can control specific java features and API's available for Firefox, as well as more typical settings like the homepage.

As is, DIM doesn't run - it gives a "browser unsupported" warning, and says 'r function not defined' or something along those lines. I think it may have to do with some of the JavaScript settings that get changed within user.js, but I am unsure.

**Comment by bhollis** [comment]
Could you reload and try again? We had a bug.

**Comment by Marc05** [comment]
Hey, it loads now! However, I still get the warning message that the browser is unsupported. What checks is DIM doing; what needs to be enabled that is being disabled in user.js?

**Comment by bhollis** [comment]
If you’re changing the user agent so we can’t recognize the browser, we’ll report it as unsupported. We have a list of browser versions that we DO support. 

-Ben

**Comment by Marc05** [comment]
The useragent stuff is commented out though.

**Comment by bhollis** [comment]
Sorry, this isn't something we have time to help support.
