### ISSUE TITLE
Make is:dupelower smarter

### ISSUE THREAD

**Issue by weborican** [DestinyItemManager/DIM#2421]
is:dupelower would be much better with the following tweaks:

1. When comparing items with the **same** attack value, favor the item with:
- locked status
- has power mod
- tag is "favorite" or "keep"
- is not at postmaster

If I have 3 Nightshades at 298 attack, I will most likely want to delete the one that isn't locked, and/or doesn't have a power mod.

**Comment by deefstes** [comment]
I would also like for is:dupelower to compare base power levels, not modified power levels. Or alternatively, have a is:dupebaselower or some such tag.
