### ISSUE TITLE
Search - is:power naming conflict

### ISSUE THREAD

**Issue by cosmosgu** [DestinyItemManager/DIM#2423]
is:power is used for both "items that contribute to your power level" and "power weapons". Searching is:power on both app.destinyitemmanager.com and beta.destinyitemmanager.com returns "power weapons".
![Imgur](https://i.imgur.com/DWISyBW.png)
![Imgur](https://i.imgur.com/PJUYK9S.png)

**Comment by duckmanBR** [comment]
The correct predicate to "items that contribute to your power level" is is:haspower
The cheat sheet is incorrect

**Comment by cosmosgu** [comment]
@duckmanBR I tested "is:haspower" on both app.destinyitemmanager.com and beta.destinyitemmanager.com. It returns items with a power level (i.e. all weapons and armors), not "items that contribute to your power level".

**Comment by bhollis** [comment]
What would you expect the difference to be?

-Ben

**Comment by duckmanBR** [comment]
I believe I understand his doubt because I had it once.  I too expected this search to return "items that are being used to calculate max base power" or even just the armor/weapons equipped...

Maybe we could change the search text to "items that CAN contribute to your power level"?

**Comment by bhollis** [comment]
That’d help make it clearer, yeah!

-Ben

**Comment by cosmosgu** [comment]
@duckmanBR Thank you for clearing up the confusion! "Items that are being used to calculate max base power" was exactly what I was thinking about when I saw "items that contribute to your power level" in the cheatsheet.
