### ISSUE TITLE
Search - is:haspower getting quest items

### ISSUE THREAD

**Issue by duckmanBR** [DestinyItemManager/DIM#2424]
is:haspower is incorrectly getting quest items, maybe also check for primStat/basePower?

**Comment by duckmanBR** [comment]
I was going to fix this but then stepback.  Why this filter is by bucket? My idea was to simply put a `item.primStat &&` on [search-filters.js line 730](https://github.com/DestinyItemManager/DIM/blob/0d8168f5247a611ab5e8fa5e89acba7d2bb28256/src/app/search/search-filters.js#L730) but then I don't know if this would break something on D1...

**Comment by bhollis** [comment]
Sparrows don't contribute to light, for example.
