### ISSUE TITLE
Trouble loading in Microsoft Edge

### ISSUE THREAD

**Issue by corsairmarks** [DestinyItemManager/DIM#2425]
Beginning this week, DIM seems to have trouble loading properly in Microsoft Edge.  I tested this on two different PCs I own.  I get this error message:

> DIM hasn't loaded. Something may be wrong with it, or with your browser (maybe you have a content blocker, or have disabled JavaScript, or your browser is too old). Try force reloading to make sure (Ctrl-F5 or Cmd-R). 

If I clear the browser cache, I then get this screen (force-refreshing again then gets me the above message):

![2017-11-17_0122](https://user-images.githubusercontent.com/5559092/32976731-a2d3ccbc-cbeb-11e7-9b9b-16469dd10976.png)

Repeatedly clearing the cache sometimes fixes it for an hour or so, then it reverts to the "unable to load" message above.  I checked the debugger and there seem to be a lot of "out of memory" messages in the console.  DIM appears minified, so there isn't much in the way of identifying info.

Both PCs are using the most up-to-date version of Windows 10 Pro.

**Comment by roland46** [comment]
I also have the same issue at about the same time, tried a few different PC's and also in Internet Explorer compatibility mode, still get the same issue as described above.

**Comment by corsairmarks** [comment]
This issue is still present in 4.26.0

**Comment by bhollis** [comment]
Do you have any extensions? What version of Edge? I'm able to load DIM in Edge via BrowserStack. Edge 16.16299. 15.15063 works too.

I do think Chrome or Firefox would perform better overall though.

**Comment by SunburnedGoose** [comment]
No extensions here.

Microsoft Edge 40.15063.674.0
Microsoft EdgeHTML 15.15063

![image](https://user-images.githubusercontent.com/984608/33306331-b9c43f94-d3d7-11e7-832d-3524c6793cac.png)

**Comment by SunburnedGoose** [comment]
The crash is severe.  I can't even get the debugger to work when the crash occurs.

**Comment by SunburnedGoose** [comment]
Looks like there is an issue with asm.js and sql.js on Edge.  When the debugger is present, it prevents asm from loading and DIM works.  Disabling the debugger causes the error since asm loads.  I had to clear my cache from settings, close edge, and reauth to get it to work.

![image](https://user-images.githubusercontent.com/984608/33306564-b2720dba-d3d8-11e7-9545-6029cc70b1ea.png)

![image](https://user-images.githubusercontent.com/984608/33306586-c508c4aa-d3d8-11e7-973d-7d23a8731141.png)

**Comment by SunburnedGoose** [comment]
@bhollis Is there a way to disable asm.js for Edge in the app?  Should I look for a away?

**Comment by bhollis** [comment]
I'm a bit confused. We have a way to fall back from WASM to asm.js, but asm.js is the fallback case - we always try WASM if it's available. If asm.js is unavailable too, we're just screwed.

It may bean that it's not able to use asm.js optimized mode (Firefox used to do that) but there's no way to flip that bit from our side as far as I know.

I'm surprised that we're not able to get WASM mode working though (chunk-0-sqlLib shouldn't even be loading!) since WebAssembly is supposed to be supported in Edge 16/17.

The other option is to try recompiling sqlite with a newer emscripten in case there's an Edge-specific bug that's been fixed, but I'm not hopeful.

**Comment by bhollis** [comment]
FWIW over BrowserScope I was able to load the site without the debugger / F12 tools attached.

**Comment by roland46** [comment]
Hi, i am not technical, but still get the issue, see below.

No extensions installed and PC has 16GB of memory and the issue happens with just edge running or edge and other apps, so i think the out of memory is not really true, I have tried this on a windows 10 edge pc with 8GB of ram and get the same issue.

![image](https://user-images.githubusercontent.com/20575117/33309603-8bc8fad2-d416-11e7-94fb-e03384fa8b96.png)

**Comment by bhollis** [comment]
@SunburnedGoose the other weird thing is we haven’t changed anything about the SQLite stuff in quite a while. I don’t know why it would’ve just started happening. 

I wonder if one of our other dependencies has introduced a bug, or maybe some of the reviews stuff triggers an Edge-specific memory leak.

**Comment by corsairmarks** [comment]
@SunburnedGoose I agree that Chrome or Firefox generally perform better.  As a workaround, I've been running a since Chrome tab with DIM and the rest of my browsing in Edge.  I've been trying to live in Edge so I can fully appreciate the default experience for Windows 10 users (I'm also a web and also C# application developer).

I also was running into the issue where the debugger wouldn't even load in Edge.  It did seem that opening another site (e.g. google.com), then the debugger, and finally browsing to DIM does allow me to safely load the site after clearing the "cached data and files" as Edge describes it.

**Comment by corsairmarks** [comment]
A quick search about WASM and Edge revealed this blog post: https://blogs.windows.com/msedgedev/2017/04/20/improved-javascript-performance-webassembly-shared-memory/

I've enabed the "Experimental JavaScript features" that includes WASM in Edge and we'll see how that goes.

**Comment by duckmanBR** [comment]
It may be a version thing...

![image](https://user-images.githubusercontent.com/32077894/33348207-95da5db6-d47c-11e7-9d29-df73c14efd0c.png)

**Comment by bhollis** [comment]
A quick `git bisect` would find the commit that broke things quite easily. I’d do it myself but I can’t easily reproduce the issue.

**Comment by corsairmarks** [comment]
After enabling the WASM features in Edge, I'm not seeing any further issues (yet).  Do we know if WASM is enabled by default in version 41.whatever?

@duckmanBR is that version (41.whatever) only available on the fast ring of updates?  I run both my laptop and home PC on the standard RTM updates for Windows 10 (both are using Win 10 Pro).  There are no updates pending and both seem to be at version 40.whatever.

@bhollis As much git wizardry as I've done before, I've never used the `bisect` function.  Docs look straightforward.  Do you have recommendations for what hash I could start with for a known "good" commit?

**Comment by bhollis** [comment]
Hmm, maybe start with the tag from the last version that worked for you-maybe a couple releases back?

**Comment by roland46** [comment]
Non technical,  Where is WASM enable option in edge, I am using this version Microsoft Edge 40.15063.674.0.

Thanks for any help and guidance

**Comment by duckmanBR** [comment]
@corsairmarks afaik that notebook is on RTM too, because my wife is the main user  (I use that less than once a week). Sunday/Monday my wife said that something updated when she turn the note on, so probably was this version 1709...

**Comment by bhollis** [comment]
Microsoft is doing a very slow rollout of new versions, so the latest may not be offered to you for months. 

-Ben

**Comment by SunburnedGoose** [comment]
I'll pull tonight and see how it goes @bhollis

**Comment by corsairmarks** [comment]
After I installed update 1709, I now have (these versions match with duckman):

* Microsoft Edge 41.16299.15.0
* Microsoft EdgeHTML 16.16299

I'm satisfied that between the updated version and enabling WASM everything is working.  I can re-open if I continue experiencing issues.

@roland46 - here's how to enable those features.  WASM stands for Web Assembly, and its a new feature that developers can leverage to help script-heavy browser applications run faster.

1. Browse to `about:flags` in the address bar (note the lack of the http:// protocol)
2. Scroll down to the "Standards Preview" section
3. Ensure the checkbox for "Enable experimental JavaScript features" is checked
4. Close the `about:flags` tab
5. (optional) Open the ... menu in Edge, select "Settings," select "Choose what to clear," then check only "Cached data and files," and finally press "Clear"
6. Close all Edge windows (you can safely save your tabs for later using the "Set these tabs aside" button)
7. Re-open Edge and browse to https://app.destinyitemmanager.com/
8. (optional) Restore your previous tabs from "Tabs you've set aside"

**Comment by SunburnedGoose** [comment]
I've pulled every tag since 4.21 and I can't replicate with dev buildsm @bhollis

**Comment by bhollis** [comment]
Weird. Can you repro on the tip of master though?

**Comment by roland46** [comment]
@corsairmarks 

Nick,

Thanks, just making that change has it working again.

Roland.
