### ISSUE TITLE
Not saving loadouts on chrome

### ISSUE THREAD

**Issue by RoDubbs** [DestinyItemManager/DIM#2426]
I've just started using DIM and it seems like whenever I close the browser my loadouts are lost. I've tried logging into chrome and syncing it that way, but the problem persists. I do use incognito mode.

Is there any way to keep the loadouts saved? So far it seems like I have to restore them from a backup every time.

**Comment by bhollis** [comment]
Using incognito mode disables local storage. You should have gotten a pop up saying we don’t support incognito, and the storage page should have a red banner saying your data may not be saved. You can log in to Google Drive, but you’ll be logged back out every time you close your browser. That’s kind of the point of incognito mode.
