### ISSUE TITLE
Transfer - Mobile landscape drag & drop error - Join Stacks

### ISSUE THREAD

**Issue by duckmanBR** [DestinyItemManager/DIM#2429]
Probably related to #2394 and #2409 but since it's not exactly the same way to reach the same error, I'll open a new issue (but probably the 3 will be closed in the same PR)...

The scenario is simple, you have a stack of a stackable item (consumable/mod/shader) split on chars x vault (how they got split doesn't seem to care, split by drag & hold, split on popup or even just getting a new one from game when the rest is on vault).

Now drag & drop (on mobile landscape) from char to vault or vault to char.  After the transfer is completed, get a **"The item request was not found"** error.

Can't test on desktop, but I'm getting this on Chrome and Edge on Android

**Comment by bhollis** [comment]
Can you all still reproduce this? I can't on iOS or Chrome desktop.

**Comment by duckmanBR** [comment]
Yes, Chrome on Android.
Tested the same scenario, got the error message after completing the transfer.

**Comment by bhollis** [comment]
Try it now? It should be fixed by #2512.

**Comment by duckmanBR** [comment]
Still bugged.

**Comment by duckmanBR** [comment]
Just tested this and it's working.  Maybe it was fixed on #2581?
