### ISSUE TITLE
API for this?

### ISSUE THREAD

**Issue by Fgcoffee** [DestinyItemManager/DIM#2432]
Im looking to do a project involving DIM,
a little bit of voice recognized item switching. 
this would involve some Voice regognition sevice, and allow you  to say, vigilance wing (for example) and it would switch your current weapon to this automatically, where possible.
Thanks, Coffee

**Comment by bhollis** [comment]
DIM uses the Bungie APIs that are available to all: https://github.com/Bungie-net/api/

Follow along with our voice recognition efforts (and help out!) at https://github.com/DestinyItemManager/iot
