### ISSUE TITLE
I've lost Lincoln Green. Twice.

### ISSUE THREAD

**Issue by RinniethePooh** [DestinyItemManager/DIM#2434]
When transferring Lincoln Green between two characters it disappeared. I thought the first time I dismantled by accident but it happened again just a few minutes ago. Happened when I clicked and dragged to the other inventory.

**Comment by duckmanBR** [comment]
How many chars do you have?  Did the target char (or vault) was full?  If it was full, DIM tries to make room and if you transferred more than one item the next item may have been sent to another char.

Reload the page (the bug could be that DIM simply lost track of the item, but it's there).

DIM can't delete items (Bungie simply doesn't have a delete action, so it's basically impossible).

**Comment by RinniethePooh** [comment]
I have two characters. I dragged from inventory to the other, neither were full, nor the vault. After it was gone I checked inventory and vault of each character in game and nothing. I'm not sure what happened but it randomly vanished.

**Comment by SunburnedGoose** [comment]
Contact Bungie. DIM uses their services to transfer items.
