### ISSUE TITLE
I have to Re-Select my account all the time to use DIM

### ISSUE THREAD

**Issue by MrZmario** [DestinyItemManager/DIM#2435]
Its not that horrible, but an annoying bug for me, everytime I enter DIM I got an error that there is no account linked in battle.net, and I have to re-select my account again to make it work, 

Doesn't affect on the usage of the app, just log-in issues.

![dgij7gm](https://user-images.githubusercontent.com/34044909/33294676-fdf036c4-d3d1-11e7-8d60-5fdcf870223c.png)

**Comment by bhollis** [comment]
Hmm, do you visit DIM from a bookmark? These days we won't even put D2 in the menu for a Blizzard account.

**Comment by MrZmario** [comment]
90% of times yes

**Comment by bhollis** [comment]
Ok. It’s possible your bookmark is deep linking into the wrong page. Can you modify your bookmark to point to just app.destinyitemmanager.com without any of the rest of the URL?

**Comment by MrZmario** [comment]
Still the same

**Comment by MrZmario** [comment]
Alright Ive just seen, it looks like its always trying to grab the Destiny 1 Inventory

https://app.destinyitemmanager.com/#!/4611686018467382075-4/d1/inventory

I guess its that

**Comment by MrZmario** [comment]
Just changed the link to d2 inventory, and its done, but weird it was detecting as D1 on battle net
