### ISSUE TITLE
Blank items in loadout.

### ISSUE THREAD

**Issue by MysthLS** [DestinyItemManager/DIM#2436]
Hello, apparently there is no way to remove a "blank" item in a loadout.
It seems when you delete an item which was part of a loadout, you're stuck with a blank icon taking a lot of space on this loadout.
Creating a new loadout fixes the issue, but it would be much more convenient if clicking the "X" on the blank item would just remove it.

![mobi bug](https://user-images.githubusercontent.com/34065465/33324157-1689c646-d44f-11e7-85f9-608c19817bce.JPG)

**Comment by duckmanBR** [comment]
Yes, it's a bug.  In the end #2289 didn't worked as expected.  But if you simply save the loadout those invalid items won't be saved and will be removed from the loadout.
