### ISSUE TITLE
View subclass perk tree when we click on the subclass icon.

### ISSUE THREAD

**Issue by kohum** [DestinyItemManager/DIM#2437]
Can we please be able to see the subclass tree when we click on the subclass icon in DIM? I realise there is a link to DestinyTracker, however DestinyTracker currently doesn't show the perk tree properly, they are all shown in columns like they did in D1.

**Comment by bhollis** [comment]
We'd likely show the same thing :-)

**Comment by bhollis** [comment]
Figured it out! Check beta.
