### ISSUE TITLE
Google Drive-stored loadouts, tags, etc. seem to have been cleared

### ISSUE THREAD

**Issue by javalasers** [DestinyItemManager/DIM#2440]
If there's anything in particular I can look at in Drive to help diagnose, I'd be very happy to provide more information. [Would ideally love to get my tags and loadouts back, of course, but mainly offering to help debug if possible...]

Thanks!

**Comment by melange396** [comment]
copypasta'd from my reddit comment, hope this is helpful:

my hypothesis: this seems to happen to me when i move between different browser instances after some time has passed. when i come back to an open tab of an old session, i think it causes some corruption in the sync to gdrive because of diffs or whatever. ive been trying to close all DIM tabs as soon as im done with them, and i havent seen the problem since.
also, i periodically download the current DIM setting state (the json file you get from "back up DIM data" at https://app.destinyitemmanager.com/#!/storage ), so if i lose data, i can go back to a somewhat recent copy of my notes and tags and such. the loadouts are also included in that file.

**Comment by FyzxNerd** [comment]
I have also experienced this as recently as last night. 

I decided to change my loadouts, and while I was able to make them last night and save them to the relevant JSON file. When I went to check my Google Drive synchronization I noticed all my load outs were gone. 

Now when I try to create a new loadout I get the following error 
"**ERROR SAVING LOADOUT** Unable to save loadout : Cannot read property "Items" of undefined."

I do not believe these are unrelated as i'm getting them on chrome for Android, Windows and Apple. 

![2018-01-05_14-31-10](https://user-images.githubusercontent.com/29414295/34625222-dff93450-f225-11e7-8077-8b0b01b2959c.png)

**Comment by bhollis** [comment]
@melange396 that’s my hypothesis as well, and I’ve been meaning to make a fix soon. 

@FyzxNerd I think that’s a related but separate issue - could you file a separate bug?

**Comment by edmiller47** [comment]
@melange396 See "Google Drive login bug - iOS 11 #2313".
I have also gotten into the habit of closing DIM when I'm done with it. I still get logged out of Google Drive after some time has passed, whether or not I leave it open on my iPhone (in Safari). Gonna try installing Google Chrome on my phone and see if the problem occurs there.

**Comment by edmiller47** [comment]
Well that was a fail. All my loadouts have been wiped out. Should have backed up before trying this.

**Comment by edmiller47** [comment]
![image](https://user-images.githubusercontent.com/13838005/35813143-dd110396-0a60-11e8-8cdf-81b45ac4c571.png)
![image](https://user-images.githubusercontent.com/13838005/35813184-f988b0fa-0a60-11e8-9eb4-42851f2763f6.png)
On Chrome now: DIM STORAGE shows loadouts for Drive and local browser storage, but they aren't showing up on the inventory screen

**Comment by FyzxNerd** [comment]
@edmiller47 This is exactly what I am experiencing as well.

**Comment by edmiller47** [comment]
@bhollis So... just wondering if there's a fix on the way for this or do I need to start recreating my loadouts? The data seems to be in the dim-dat.json files (I opened one with Notepad to take a pek) but just isn't getting loaded into DIM.

**Comment by bhollis** [comment]
I wouldn't expect a fix soon. If you have that file you can just import it into DIM to restore your stuff.

**Comment by edmiller47** [comment]
The whole point is that I do have the file, but importing it into DIM
doesn't restore the loadouts I have built since the start of D2.
No matter, I just went ahead and rebuilt most of them anticipating this.

**Comment by edmiller47** [comment]
Don't know if this helps, but just wanted you all to know that I did start using Google Chrome on my iPhone and am finding after more than a week that it is persistently remaining logged into Google Drive - including across device restarts and force quitting the browser.

Using DIM in Safari on the same device still behaves as I've reported previously with it failing to remain logged into Drive.

**Comment by bhollis** [comment]
Rolling this into a bigger tracking issue #2713.
