### ISSUE TITLE
Changelog toaster does not show items after first bullet group

### ISSUE THREAD

**Issue by cha5on** [DestinyItemManager/DIM#2443]
As can be seen at [src/views/changelog-toaster-release.html for v4.27.0](https://github.com/DestinyItemManager/DIM/blob/a42dd1884c4f45037f9b703d02bf98690dbc4c75/src/views/changelog-toaster-release.html), the generated changelog toaster only shows items in the first set of bullets, so anything after an unintentional extra blank line gets dropped.

The raw text in CHANGELOG.md is this for v4.27.0:

```
# 4.27.0
* Added setting to pick relevant platforms for reviews.

* Fix review area not collapsing in popup.
* Fix display of option selector on reviews tab when detailed reviews are disabled.
```

and here's what it looks like; note the second two bullets are missing:
![4 27 0 changelog](https://user-images.githubusercontent.com/1630923/33551376-1102c938-d8a6-11e7-9384-09a263e86268.PNG)

I'm assuming this is generated by @dim-release-bot, but not certain.

**Comment by bhollis** [comment]
Yeah, it's just a simple regex, but not all PRs format the changelog correctly. I usually go back through before release and fix it up, but didn't get around to it this time. Fortunately not much was new.
