### ISSUE TITLE
Enhanced Tooltips

### ISSUE THREAD

**Issue by peabeu** [DestinyItemManager/DIM#2444]
As per discord chat:
When you hover your mouse over an icon, it displays the name of the weapon. Could it also display the type of weapon? I can't remember all names and what they are plus some icons look very similar. For instance Morrigan-D kinda looks like Somerled-D. So it would say Somerled-D Shotgun and so on.
![tooltip](https://user-images.githubusercontent.com/34254703/33582558-e485e138-d9a9-11e7-8a07-eb147d9e310c.png)

**Comment by jmrodriguesgoncalves** [comment]
I could give this a shot! Looking to get more experience contributing to projects

**Comment by kyleshay** [comment]
Hi @jmrodriguesgoncalves! Check out the Developer Quick Start guide in the readme:
https://github.com/DestinyItemManager/DIM/blob/master/README.md#developer-quick-start

Once you have the project running locally, you'll need to find where we set the title/hover text for the item and add in the item type to that string. Let me know if you get stuck anywhere along the way!

**Comment by jmrodriguesgoncalves** [comment]
Hey @kyleshay, yeah I was able to run it locally! I am just struggling when it comes to finding where that title is assigned to the hover

**Comment by kyleshay** [comment]
the dimStoreItem directive has the title attribute:
https://github.com/DestinyItemManager/DIM/blob/master/src/app/inventory/dimStoreItem.directive.html#L4

should be able to just slap the `+ '\n' + itemType` in there and be good to go! 🚀

**Comment by jmrodriguesgoncalves** [comment]
Added it in, let me know if you'd like me to do any changes!

**Comment by peabeu** [comment]
I've had a look in beta, fantastic work. Thankyou
