### ISSUE TITLE
Need a way to limit string searches

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#2445]
The use case is "which ghost shells have perks when on IO".

the obvious search - is:ghost IO

This doesn't do as expected as the IO matches anywhere in any of the text of the shell, including:
"Chance to obtain addit**io**nal fact**io**n consumables".

Note that for every other planet, it does mostly work because the names are distinct:

is:ghost edz
is:ghost nessus
is:ghost titan (with the exception that the Titan Shell also matches!)

Suggested approaches include options like:
"io"  /  'io'  / +io  / @io / (io)

Either bracket or mark the string that you want to not substring match.

Interestingly testing shows that both " io" and "io " (with a space before or after inside the quotes) do work, but it isn't clear that this isn't just some sort of edge case, or will consistently continue to work in the future.  In either case, it's definitely not obvious.

**Comment by melange396** [comment]
i write in the note section and put the relevant keyword in there, then i can search on 'notes:titan' or whatever.  it takes manual input for each one though.

**Comment by kyleshay** [comment]
When you search for a keyword it looks at item and perk names. If you wrap the string in double quotes, it matches everything inside the string, which means the following should work:
`is:ghost "Io Resource Detector"`
