### ISSUE TITLE
Can't see Infuse Fuel anymore?

### ISSUE THREAD

**Issue by CorneliusGT** [DestinyItemManager/DIM#2448]
Unable to see the Infuse Fuel option anymore.  Is this a feature that has been removed as of the new expansion?

**Comment by CorneliusGT** [comment]
![capture](https://user-images.githubusercontent.com/34291383/33640782-36257ce4-d9f8-11e7-995d-a314f2f2d2ea.PNG)
I missed your twitter post.  Sorry guys, I jumped the gun.  Keep up the good work!

**Comment by kyleshay** [comment]
Thanks for reporting, we'll keep this issue open to track so we can get it working again.

**Comment by kyleshay** [comment]
This is related to https://github.com/DestinyItemManager/DIM/issues/2458

Fixing one thing will resolve the other.
