### ISSUE TITLE
Search feature for items with two words is malfunctioning.

### ISSUE THREAD

**Issue by KSCooke** [DestinyItemManager/DIM#2450]
Previously the is:scoutrifle or is:autorifle would return you all of the respective items. A new change since 12/4 has made this malfunction in some way. You may still look for is:scout rifle but it returns all that have "rifle". 

I'm not sure if this is on Bungie's end or DIM but it just started happening as of 12/5.

**Comment by robotboy655** [comment]
none of the is:<weapontype> stuff works. ```is:handcannon, is:sidearm, is:shotgun```, etc.

**Comment by robotboy655** [comment]
Also may I suggest ```is:smg``` instead of ```is:submachine```

**Comment by KSCooke** [comment]
is:hand cannon will work for the is keyword but is:handcannon will not.

**Comment by kyleshay** [comment]
We'll track this in https://github.com/DestinyItemManager/DIM/issues/2458

Thanks for the report!
