### ISSUE TITLE
All tags disappeared after CoO launch

### ISSUE THREAD

**Issue by emerilnut** [DestinyItemManager/DIM#2451]
I only played a little bit yesterday of the Curse of Osiris launch, but I went into DIM this morning and ALL my tags are gone.  I'm not sure if this is related to the previous tag problems so I'm creating a new issue.

**Comment by bhollis** [comment]
It’s the same issue

-Ben

**Comment by kyleshay** [comment]
https://github.com/DestinyItemManager/DIM/issues/2440
