### ISSUE TITLE
Crimson not appearing in inventory.

### ISSUE THREAD

**Issue by sirdoombox** [DestinyItemManager/DIM#2453]
I've only got one exotic weapon so far, Crimson, however it doesn't appear at all in the browser based version of DIM. I am unsure of whether or not this affects only Crimson or all new exotic guns.

DIM Version: 4.27.1
Browser: Firefox Quantum 57.0 (x64)
Full Error (Only error I receive and only one Item isn't present, must assume this is the problem)
```
Error processing item 
Object { itemHash: 3437746471, itemInstanceId: "6917529045713404974", quantity: 1, bindStatus: 0, location: 1, bucketHash: 1498876634, transferStatus: 0, lockable: true, state: 0 }
 
TypeError: e.itemCategoryHashes is undefined
Stack trace:
b/t<@https://app.destinyitemmanager.com/main-d37e36.js:1:54243
b@https://app.destinyitemmanager.com/main-d37e36.js:1:54187
c@https://app.destinyitemmanager.com/main-d37e36.js:1:51176
l/</<@https://app.destinyitemmanager.com/main-d37e36.js:1:47329
_.forEach@https://app.destinyitemmanager.com/vendor-0503ab.js:1:4019
l/<@https://app.destinyitemmanager.com/main-d37e36.js:1:47288
u@https://app.destinyitemmanager.com/vendor-0503ab.js:1:469008
l/<@https://app.destinyitemmanager.com/vendor-0503ab.js:1:469454
```

**Comment by Zone-Ghost** [comment]
Other exotic guns are showing up, but my Crimson is missing as well.

**Comment by WallyZambotti** [comment]
Confirmed.  The crimson (exotic CoO hand cannon) refuses to appear in the inventory.

**Comment by robotboy655** [comment]
Same here.

**Comment by mikevb1** [comment]
Having same issue with all Trials weapons. Tried reloading DIM, hard refresh, changing inventory in-game then reloading.

**Comment by Arkhaeon** [comment]
Having the same issue with Crimson and Ophidian's Aspect as well.

**Comment by kyleshay** [comment]
I don't have the item so I don't really have a way of testing this. I can try logging in and try to work for it, unless anyone could provide any additional information. I'm guessing it's a very simple fix but without more detail I can't dig deeper.

**Comment by duckmanBR** [comment]
Could you check again? 4.29 should have a fix for Crimson

**Comment by sirdoombox** [comment]
Crimson now appears for me.

**Comment by Arkhaeon** [comment]
Crimson and Ophidian's are appearing now!  Thank you.
