### ISSUE TITLE
Weapons & Armor not displaying after CoO launch.

### ISSUE THREAD

**Issue by Tyridius** [DestinyItemManager/DIM#2454]
![image](https://user-images.githubusercontent.com/34316128/33677382-6d70fd48-da6d-11e7-8208-f95a324f7ab6.png)

After the CoO launch I am unable to get weapons and armor to display.  All the other mods/inventory/etc appear as usual.

**Comment by kyleshay** [comment]
Hmm, strange. A fix should have gone out for this yesterday. Could you try refreshing?

**Comment by Tyridius** [comment]
I've tried refreshing several times and they still won't display.  Also logged out and logged back in to no avail.  I've also cleared history/cookies and restarted the PC.

**Comment by kyleshay** [comment]
strange. could you open your console and let me know if you are seeing any errors?

> To open the dedicated Console panel, either:
> Press Ctrl+Shift+J (Windows / Linux) or Cmd+Opt+J (Mac).

**Comment by Tyridius** [comment]
![image](https://user-images.githubusercontent.com/34316128/33678624-1abf2b02-da71-11e7-82e1-ce69c99a238b.png)

**Comment by Tyridius** [comment]
Downloaded and installed Google Chrome and was able to get DIM to work properly.  Still does not work on Firefox for some reason.

**Comment by DAOWAce** [comment]
Yeah it's totally broken in my older chrome now, spewing hundreds of errors messages, rip.

All the more reason to get my Cent switch done..
