### ISSUE TITLE
Feature Request:Auto Backup

### ISSUE THREAD

**Issue by per1970** [DestinyItemManager/DIM#2455]
An auto Backup options would be lovely.
Just a simple one,

-  backup every X hours/days
- Number of Backups to keep 

oh, and make the file name contain the date/time of the backup.

**Comment by kyleshay** [comment]
What information would you like backed up and what would be the use case? 

This would require a bit of infrastructure work. As of right now you can go to the settings and manually export your settings or items.

Is this ask to solve some other problem?

**Comment by per1970** [comment]
Yes I know, I want what the manual backup does..basically just an automated version of the manual backup.

Currently I'm hacking on a small grease monkey script to do this,, but it's...nasty

A looong time since I coded properly :D

**Comment by bhollis** [comment]
I'd prefer to just fix the Google Drive sync :-)
