### ISSUE TITLE
Search is:<weapon type> returns no results

### ISSUE THREAD

**Issue by edmiller47** [DestinyItemManager/DIM#2458]
e.g. is:shotgun, is:sniperrifle shows nothing in the weapons grid:
![image](https://user-images.githubusercontent.com/13838005/33717959-d6107394-db29-11e7-8811-12f0cbe5cca1.png)

**Comment by deefstes** [comment]
I can confirm this. It seems to have stopped working with the release of 4.27.1

**Comment by kyleshay** [comment]
Related issue: https://github.com/Bungie-net/api/issues/324

**Comment by joshminnie** [comment]
Looks like https://github.com/Bungie-net/api/issues/324 closed their ticket. Sounds like the resulting change is a name change to the comparison field.
