### ISSUE TITLE
Weapons No Longer Show Community Rating

### ISSUE THREAD

**Issue by automationstn** [DestinyItemManager/DIM#2461]
Destiny DIM for Chrome.. Guns and armor used to show the rank... 4.6, 4.9, 5... did that get turned OFF or how do I turn that back ON? I seem lost without it.

**Comment by esibun** [comment]
destinytracker is actually throwing 502's from the API:

```
HTTP/2.0 502 Bad Gateway
date: Sat, 09 Dec 2017 04:15:39 GMT
content-type: text/html; charset=UTF-8
expires: Thu, 01 Jan 1970 00:00:01 GMT
cache-control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
pragma: no-cache
x-frame-options: SAMEORIGIN
set-cookie: __cfduid=d260206b1b87c144e87ba3176ccf67ce01512792924; expires=Sun, 09-Dec-18 04:15:24 GMT; path=/; domain=.destinytracker.com; HttpOnly
cf_use_ob=0; expires=Sat, 09-Dec-17 04:16:09 GMT; path=/
server: cloudflare-nginx
cf-ray: 3ca524a35e9e2a13-SEA
X-Firefox-Spdy: h2
```

**Comment by bhollis** [comment]
Destiny Tracker is having issues. They’re working on restoring service.

**Comment by Dayotll** [comment]
I have this issue too.  with beta and non beta  dim on chrome browser.  no ratings at all   selected xbox one also.  any ideas?  i really liked them too :(
