### ISSUE TITLE
drag and drop on PC = item requested not found

### ISSUE THREAD

**Issue by nki2bpz** [DestinyItemManager/DIM#2462]
probably related to #2409 as its the same behavior with a false error. moving item from char to char shows error but actually is moving the item correctly

**Comment by bhollis** [comment]
Similar to that issue, how can I reproduce this? Is there anything interesting about how your gear is arranged (full or empty areas, for example)? I haven’t seen this error myself.

**Comment by duckmanBR** [comment]
@bhollis I reproduced it with empty areas (more than two slots free) in all chars/vault.
Also, this is not only happening on drag & drop, choosing the store option on the popup also triggers a "not found" **after** the successful move.
the error message only appear when moving between chars.

**Comment by nki2bpz** [comment]
@bhollis There's nothing remarkable in my setup, 20 slots free in vault, multiple slots free on characters, shaders are full in inventory. The only thing I can tell you for certain is it doesn't give the false error on a single part move going from char>vault or vault>charcter but every time on character>char. Curious if it's a timing issue?  As in the item is being verified out of sync with the move? I'm assuming it works like this; verify item on char A, move to vault, verify item in vault, move to char B. Could this have anything to do with bungie instituting the throttling to 1 move per second and then removing it again? If there's anything else I can do please let me know.

**Comment by SunburnedGoose** [comment]
Fixed.
