### ISSUE TITLE
XP bars?

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#247]
I see that bounties have progress information, and I think XP information is available for weapons/armor. Would it be a good idea to add completion progress bars on items/bounties like we see in the game UI?

**Comment by SunburnedGoose** [comment]
Having XP bars on all the items would make the screen crazier than it is now...  We can try it and see how it looks but confidence is low.  We still need to be able to accurately measure the XP information for armor/weapons.

**Comment by bhollis** [comment]
See #382.
