### ISSUE TITLE
Weapon type filter not working

### ISSUE THREAD

**Issue by SirLugash** [DestinyItemManager/DIM#2470]
It would appear that weapons don't have a weapon type associated with them anymore as using filters like is:autorifle, is:rocketlauncher etc yield no results (no items are highlighted).
DIM version 4.28.0 webapp used in Chrome Version 62.0.3202.94.

**Comment by duckmanBR** [comment]
It's a know bug (#2458).  Simply searching for the type name will work (Auto Rifle) but may highlight more items than expected (because this way will also search on item descriptions/perks).

**Comment by SirLugash** [comment]
Did a quick search looking for filter and didn't find this, so thanks for the heads up.
