### ISSUE TITLE
Classified Plugs for Crimson

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#2475]
https://github.com/DestinyItemManager/DIM/blob/master/src/app/inventory/store/d2-item-factory.service.js#L560

There are classified mods now for items.  ATM, DIM will ignore them and show it as undefined in the app.  We need to find the plug for classified and add it.

![2017-12-12_191934](https://user-images.githubusercontent.com/984608/33917171-4dd5b8c0-df72-11e7-9c1b-7eb25322c7a6.png)

![image](https://user-images.githubusercontent.com/984608/33917182-588f537a-df72-11e7-8280-613f6bbaa012.png)

**Comment by ericleone** [comment]
Just an FYI:  
These perks are no longer Classified in the official app or in DIM. All the perks are now shown in DIM.   
![crimson2](https://user-images.githubusercontent.com/297690/34073584-68746de8-e26a-11e7-80dc-2431955d7634.PNG)

**Comment by bhollis** [comment]
Nice! We should make sure our plug handling can deal with classified plugs though, for the next update.
