### ISSUE TITLE
Merciless aim assistance stat is missing

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#2476]
If you view the item, there is no aim assistance value shown.

![image](https://user-images.githubusercontent.com/25425159/33917932-c6439532-e000-11e7-892b-751b8fddc971.png)

If you compare all the fusion rifles, the lack of an aim assistance value messes up the alignment.

![image](https://user-images.githubusercontent.com/25425159/33917951-d88b27b4-e000-11e7-9b6c-ef634d4e961a.png)

**Comment by duckmanBR** [comment]
DIM doesn't show AA to Merciless because bungie doesn't return this value for this weapon.

But in #2391 we tried to fix the comparison problem, it solved to some people but not to everyone.

I still couldn't debug why is not working for me (and now for you).

Don't know if @KyleLilly can help.

**Comment by KyleLilly** [comment]
I've got a friend who was able to reproduce this so I'll be able to take a closer look this weekend.
