### ISSUE TITLE
is:weapontype no longer works

### ISSUE THREAD

**Issue by mcdonamw** [DestinyItemManager/DIM#2477]
In the past 3 versions or so, the is:weapontype filtering stopped working, at least for me.  I've seen posts by others as well.  For example:   is:autorifle

Is this expected?

A workaround can be done by removing the 'is:" keyword and just filter on "auto rifle" (with quotes) and it seems to work that way.  Using "auto rifle" seems to be a logical OR search between "auto" and "rifle" so other "rifle" types are also pulled.

**Comment by duckmanBR** [comment]
It's a know bug (#2458)
