### ISSUE TITLE
Not enough gratitude

### ISSUE THREAD

**Issue by nki2bpz** [DestinyItemManager/DIM#2485]
With all the new changes happening daily with D2 there are simply bound to be so many more issues lately. I simply want to remind everyone that works on and contributes to this app how deeply grateful I and everyone in my clan are for how much time and hard work you all have put into this amazing tool. This tool has single handedly changed the way we play destiny and has saved me countless hours. I wish there was a metric of how many hours put into development vs total hrs saved every day by players world wide. Thank you all, and I hope you all have an amazing holiday. Eat well, drink well, be well, so you can do well.

**Comment by tcurtin** [comment]
This.  So many times this.

**Comment by SunburnedGoose** [comment]
Thanks!  I'll make sure everyone who helps build DIM see this.
