### ISSUE TITLE
Cannot npm run server without first installing es-to-primitive

### ISSUE THREAD

**Issue by FindingNamo** [DestinyItemManager/DIM#2487]
Looks like strictly following the readme.md leads to a failure on launching the server.

> $ npm run server
> 
> > dim@4.29.0 server xxxxxxx\repos\dim
> > webpack-dev-server --config ./config/webpack.js --env=dev
> 
> module.js:538
>     throw err;
>     ^
> 
> Error: Cannot find module 'es-to-primitive/es6'

Need to also install es-to-primitive

Probably can be solved by adding to package.json?

**Comment by FindingNamo** [comment]
This ended up being specifically a git bash issue on Windows.

It looks like, even if run as admin, git bash is not going to npm install correctly all the modules required leading to several modules missing, specifically es-to-primitive and is-regex.

Using any other shell seems to work as intended :(.

Thank you to @48klocs who helped investigate.

**Comment by bhollis** [comment]
It'd be nice to update the README for windows users.

**Comment by FindingNamo** [comment]
Submitted: https://github.com/DestinyItemManager/DIM/pull/2492
