### ISSUE TITLE
is:<type> does not work

### ISSUE THREAD

**Issue by randalla0622** [DestinyItemManager/DIM#2491]
I haven't seen this elsewhere, but in both stable and beta doing a is:<type> does not result in anything found. For example, is:scoutrifle does not show me any of my scout rifles.

**Comment by duckmanBR** [comment]
Are you sure you're on the latest version?  Because since CoO launch those weren't working but it was fixed this week and 4.30 have it (I just tested).

**Comment by nivshah** [comment]
I was having this issue. I had to refresh DIM 2 times, and now these filters work again!

**Comment by randalla0622** [comment]
It's now working for me in both. Wasn't yesterday. Had to reload it multiple times to get it working, fwiw.

**Comment by SunburnedGoose** [comment]
Fixed.
