### ISSUE TITLE
Level Requirement

### ISSUE THREAD

**Issue by elmic11111** [DestinyItemManager/DIM#2493]
Is it possible to list level requirement so when your leveling a second character you can see what level you need before you can pass gear?

**Comment by bhollis** [comment]
We'll try to address this when we redesign the popup - it's too busy now as it is and you don't need the info once you're leveled up (just a few hours). Note that you can search for items by level: "level:<=12" for example.

**Comment by bhollis** [comment]
Yup that’s always been the problem. Food thing we’re coming up on a redesign of the popup...

**Comment by SunburnedGoose** [comment]
Destiny dims items your current character can't use

**Comment by inexorableAce** [comment]
Can restructure the current popup pretty easily to accommodate this, has the added benefit of grouping action buttons together on the right. fun fact till I mocked this up in the browser console I didn't even realize the lock button was actionable.  This should help it become more visible.

![image](https://user-images.githubusercontent.com/29002828/46247592-a4816e00-c3db-11e8-9864-29bbd7b7adcc.png)

**Comment by duckmanBR** [comment]
Probably best to the right of ratings below tag?

**Comment by sundevour** [comment]
@inexorableAce i had the same late realization the lock was interactive
one thing i'd note about the move though, is that it (a game/functional button) ends up grouped with DIM/display buttons

**Comment by bhollis** [comment]
I’m actually in the middle of redesigning the popup and will probably move all that stuff out of the header.

**Comment by delphiactual** [comment]
Possibly closed by Shadowkeep
