### ISSUE TITLE
Feature Request: Vault Count

### ISSUE THREAD

**Issue by ammartist** [DestinyItemManager/DIM#2496]
I would like to Request Vault Count on the top right side of the bar in the vault section, just like the one use to be in D1 DIM. It is really useful for switching items around and knowing the amount of space we have left in the vault.

**Comment by duckmanBR** [comment]
It may be confusing, but under the vault "title", only G is related to the vault and it shows how many items you have up to 200, the size of our tiny vault.
C/S/M (Consumables, Shaders and Modifiers) are for the shared inventory used by all your characters.

**Comment by ammartist** [comment]
Ahhh.. Just realized it ;-) it was confusing... Thank you so much!
