### ISSUE TITLE
feature request: add tooltips

### ISSUE THREAD

**Issue by alessioalex** [DestinyItemManager/DIM#25]
Some weapons look really similar to me, especially the image being small.

In my opinion tooltips would help a lot.

**Comment by cstauf2** [comment]
We could add Destiny Database tooltips! http://www.destinydb.com/tooltips

**Comment by pthrasher** [comment]
Looks like all you need is a valid destinydb link... However, that means having their ids. I wonder if there's an easy way to map a bungie item id to a destiny db id.

**Comment by kyleshay** [comment]
semi-implemented with #190 we can iterate on this idea as we start considering a responsive UI
