### ISSUE TITLE
Inconsistency in Ratings

### ISSUE THREAD

**Issue by MasterDevice** [DestinyItemManager/DIM#2502]
So, when I look at the ratings for just about any item I get different values depending on where I log in.  To be more specific, If I poke around my inventory while I'm at work, I might see a 3.7 on a particular helmet or gun.  However, when I check the same item from home, the score would show a 1.6.  I'm dealing with two different PCs on two different networks.  Has anyone else noticed this?  it appears to affect every item.  meaning, every single item has a different rating work vs home.  And no, this isn't happening because reviews are changing the score between the time it takes me to get from work to home.  I know this because the example 3.7 usually stays the same for several days.  likewise for the other score on the same item when seen from home.

**Comment by duckmanBR** [comment]
Are you sure you weren't using different rating filters?  Example: Red Mamba shows 1.9 with "All Consoles" but 2.8 with "Show All" and 4.3 with "PC Only".

**Comment by MasterDevice** [comment]
Ah, didn't know that was a feature.  I bet that's my issue.  Thank you!
