### ISSUE TITLE
Feature Request: UX Suggestion Transfer search items not clear

### ISSUE THREAD

**Issue by 0sanity** [DestinyItemManager/DIM#2503]
I discovered via discord that the Magnifying glass on the drop down transfers items
I was totally unaware of this really useful feature

Improve the text in the drop down to better indicate the functionality

Current
Items = "is:modifications helm"

Improvement Suggestion
Transfer Search "is:modifications helm"

**Comment by kyleshay** [comment]
https://github.com/DestinyItemManager/DIM/commit/567eec2c53a59049dfa4d21c80c78714db5a42f3#diff-b05880a97bec0a40dc1f02d4c3941822
