### ISSUE TITLE
Feature Request: UX Suggestion Infusion Fuel Finder mystery button

### ISSUE THREAD

**Issue by 0sanity** [DestinyItemManager/DIM#2504]
I only discovered this button existed after making a suggestion for this feature in discord

It is currently the only button on the item info popup without text.

I think simply adding a word like "Upgrade" would go a long way to making this great feature more obvious.

I think another possible solution would be to create a right click menu similar to google docs. It would be pure text for the various options instead of mystery buttons. It would be easier to have more context to the various options. 

I'm not a UX designer though so maybe there is an even better way to improve it.

**Comment by duckmanBR** [comment]
I believe that the infuse finder uses the same icon as the game, so it shouldn't be so mysterious...
But if this is the only icon that doesn't have a popup text this should be fixed.

DIM is also a mobile app, so the "right click" approach even as good as it sounds would need a counterpart on mobile.
