### ISSUE TITLE
Feature Request: Fuel Finder Duplicate With Legendary Notice

### ISSUE THREAD

**Issue by 0sanity** [DestinyItemManager/DIM#2506]
It would be good if the fuel finder warned you if you have a duplicate item you are finding fuel for that has a legendary mod.

Example:
I wan to upgrade my 222 simulator mask so I open fuel finder for it
Fuel finder sees that I also have a 220 simulator mask with a legendary mod.
It then notifies me that I may want to upgrade the 220 mask instead as it will give me a higher resulting item level due to the legendary mod in it.

**Comment by duckmanBR** [comment]
To that the "workaround" we already have is to use the "is:dupelower" search that highlights only the lower dupe (but it's still not perfect as stated in #2421).

**Comment by 0sanity** [comment]
To clarify, the filter does not work inside the fuel finder, it will list non dupe items even if you have filtered dupe on the main search

**Comment by bhollis** [comment]
Filters now work inside the Infusion Fuel Finder.
