### ISSUE TITLE
Masterworks - mw shadow is bleeding out on iOS

### ISSUE THREAD

**Issue by duckmanBR** [DestinyItemManager/DIM#2515]
iOS (from @inexorableace)
![image](https://user-images.githubusercontent.com/32077894/34410331-923a9864-ebb6-11e7-8697-a82b9965e65d.jpg)

Android
![pixlr](https://user-images.githubusercontent.com/32077894/34410415-4933b2f8-ebb7-11e7-8460-235cf127ce31.jpg)

**Comment by bhollis** [comment]
Should be a pretty easy fix, I’ll look tonight. 

-Ben
