### ISSUE TITLE
Masterwork style missing from Loadouts and Item Comparison

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#2521]
![2017-12-31_102200](https://user-images.githubusercontent.com/984608/34462973-99621b20-ee14-11e7-9350-01cc763a4ac5.png)
![2017-12-31_102228](https://user-images.githubusercontent.com/984608/34462974-996f7996-ee14-11e7-8d3c-4d49848bf4f2.png)

**Comment by bhollis** [comment]
Looks like it was added to dimStoreItem but not dimSimpleItem. 

-Ben
