### ISSUE TITLE
Masterworks outline missing when you turn a weapon masterworks and hit "Refresh Destiny Data"

### ISSUE THREAD

**Issue by capito27** [DestinyItemManager/DIM#2522]
If you inspect the actual gun, you can see the masterworks badge and perk in the weapon's "pop-up".
it fixes itself if you full refresh the page (no screenshot available, as i refreshed before being able to take one).

the exact reproduction steps are : open DIM -> turn a weapon into Masterworks in game -> hit refresh destiny data.
You'll see that there is no masterworks outline for the gun.
This bug was present in the beta site.

**Comment by bhollis** [comment]
Yeah, I noticed that when the code went in. We’re using a bind-once expression so we never update. Unfortunately there’s a trade off between keeping updated and performance of the app, and masterworks are still kinda rare. When we switch the main display to React we can update this stuff with much more detail and less performance impact. 

-Ben

**Comment by 48klocs** [comment]
The same bug exists for moving mods around to create complete stacks of mods, but I wasn't going to go changing that either.
