### ISSUE TITLE
Error on load

### ISSUE THREAD

**Issue by bt100421** [DestinyItemManager/DIM#2527]
Both safari and chrome appear to not be able to open DIM at all now. This was working previously. 
![7850673f-8f78-46df-adfc-1699cf78508f](https://user-images.githubusercontent.com/35154488/34632981-994807ca-f23e-11e7-8457-b89b26696b17.png)
![1ffbb33c-c367-463e-8562-3a1ee5df5754](https://user-images.githubusercontent.com/35154488/34632982-996171e2-f23e-11e7-9a39-4e31a34d9a41.png)

**Comment by ghostwich** [comment]
This happens with both the beta (4.32.0.1713) and regular (4.32.0) applications.

**Comment by bhollis** [comment]
What version of iOS are you using?

**Comment by ghostwich** [comment]
11.2.5 (15D5049a)

**Comment by bhollis** [comment]
Isn’t that still in beta? Looks like it has some bugs. Perhaps we should file a radar.

**Comment by ghostwich** [comment]
This has resolved itself after the weekly reset.  It might not have been an issue with iOS, then.

**Comment by bhollis** [comment]
We actually did a bunch of work to fix it ;-)
