### ISSUE TITLE
Need an Inventory tab now that we have Progress tab

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#2528]
In the D1 side of DIM, you can always get back to your inventory from the Loadout Builder/Vendors/etc tabs.

In the D2 side of DIM, with the progress tab, there is no obvious way to get back to your inventory.  Clicking the DIM icon works, but is not intuitive.

I suggest adding an Inventory tab next to the Progress tab to take you back.

**Comment by bhollis** [comment]
Good call, I forgot we had added that for D1
