### ISSUE TITLE
Move tags from top left to bottom left corner

### ISSUE THREAD

**Issue by peabeu** [DestinyItemManager/DIM#2530]
When you tag an item that already has an icon in the top left corner, such as Curse of Osiris or The Dawning. It is harder to see items that have been tagged. Could you move the tag to the bottom left had corner. Or move the CoO and other similar identifiers to the bottom left had corner. Thanks. The image attached looks ok because it is larger than in DIM
![taglocation](https://user-images.githubusercontent.com/34254703/34659016-351dce1e-f488-11e7-92bd-4698be2c03d0.png)

**Comment by delphiactual** [comment]
Closed in #3194
