### ISSUE TITLE
Corrupted settings

### ISSUE THREAD

**Issue by wmxp** [DestinyItemManager/DIM#2531]
Been using DIM for a long time now without issue, up to release 32. Saw the new features posted for release 33 and wanted to update, but no matter how many times I refreshed the page, it would not detect the update and stayed on 32. Decided to do a complete browser cache clear, cookies, the works. DIM downloaded version 33, but doesn't finish loading, ending up like the screenshot shows. Tried wiping all cache again and then reinstalling chrome - nada, will not load. It does load correctly in Firefox for me.  

Google Chrome Version 63.0.3239.132 (Official Build) (64-bit)
![dim_broken](https://user-images.githubusercontent.com/30638431/34699389-de7755c6-f491-11e7-8db7-5dbdf3431c1c.png)

**Comment by wmxp** [comment]
Okay, managed to fix it. Had a manually made backup of the DIM settings which I imported. Still doesn't explain the root cause though, so other people might be in the same boat.

**Comment by doktor5000** [comment]
FWIW, cannot reproduce. I'm also on Win7 with Google Chrome Version 63.0.3239.132 (Official Build) (64-bit).

**Comment by bhollis** [comment]
It sounds like this is a sync bug where your settings got corrupted somehow, preventing load. A screenshot of the developer tools would help if it happens again.
