### ISSUE TITLE
suggestion: display masterworks perk/bonus and distinguish regular and crucible more obviously

### ISSUE THREAD

**Issue by doktor5000** [DestinyItemManager/DIM#2533]
Maybe I'm missing something or I'm blind, but it seems the "flavour" or the masterworks perk (handling, stability,reload speed, etc.) is not displayed currently. Or is it that it's not offered via the API?
But it seems in a comparison that bonus is already included in the stat.

Would also be nice to make it slightly more obvious (maybe via additional text where the number of kills are) whether it's a regular or crucible masterwork.

Apart from that, just wanted to tell you: Keep up the fantastic work, guys :1st_place_medal:

**Comment by bhollis** [comment]
Thanks! I'm not sure if this info is available, but if it is we'd love to show it.

**Comment by doktor5000** [comment]
For reference, Ishtar Commander seems to show this stat, maybe it helps. Although it seems it's not opensource, though :-\

**Comment by duckmanBR** [comment]
I'm working on it.  Still looking for how to find the stat being affected by the MW but already found how to differentiate Vanguard x Crucible MW...

**Comment by bhollis** [comment]
Resolved in #2553.
