### ISSUE TITLE
Add XP Progress Post 40 to Character

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#254]
![image](https://cloud.githubusercontent.com/assets/984608/9982585/f327c3ac-5fa6-11e5-8739-0a3c636340da.png)

**Comment by bhollis** [comment]
Is this information available? In the character hash, all the level/exp progression stuff seems to just top out at 40.

**Comment by SunburnedGoose** [comment]
I haven't been able to find it.

**Comment by kyleshay** [comment]
function getGuardianProgressionRequest(token, platform, membershipId, character) {
      return {
        method: 'GET',
        url: 'https://www.bungie.net/Platform/Destiny/' + platform.type + '/Account/' + membershipId + '/Character/' + character.id + '/Progression/?definitions=false',
        headers: {
          'X-API-Key': apiKey,
          'x-csrf': token
        },
        withCredentials: true
      };
    }

and then for getting the progressionHash for prestige:

    function processProgressionResponse(response) {

      // could theoretically process all of the progressions (factions, etc) this is just prestige.
      // https://github.com/TrackerNetwork/DestinyStatus/blob/master/app/destiny/Character/ProgressionCollection.php
      var payload = _.findWhere(response.data.Response.data.progressions, {progressionHash: 2030054750});

      console.log('progression', payload);

      return $q.when(payload);
    }

    function rejectProgressionResponse(error) {
      $q.reject(new Error('The store progression was not available.'));
    }

and the response looks like this: 

    {
      "dailyProgress": 0,
      "weeklyProgress": 0,
      "currentProgress": 3965090,
      "level": 158,
      "step": 0,
      "progressToNextLevel": 15090,
      "nextLevelAt": 25000,
      "progressionHash": 2030054750
    }

not sure where we want to throw it, `getDestinyInventories`?

**Comment by kyleshay** [comment]
closing in favor of #533
