### ISSUE TITLE
Multiple wrong items are being tranferred

### ISSUE THREAD

**Issue by Soulfurix** [DestinyItemManager/DIM#2541]
The last month i’ve experienced that everytime I transfer any item to any location, other random items (mostly two) are «magically» being added to the transfer, but the opposite direction - back to my toon. So Im not able to free up the inventory on my toons because random items are being transfered straight back. Eg. transferring a power weapon to the vault triggers an autmatic random transfer of any power, energy or kinetic straight back to my toon, often more than two random weapons. The scenario is the exact same regarding transferring armor. This happens on both Safari and Chrome.

/Soulfurix

**Comment by duckmanBR** [comment]
DIM only does that when the place you're transferring to is full... 
Below the Vault, what says on the G number?

**Comment by Soulfurix** [comment]
Thanks alot duckmanBR, that was it, appreciate your help!
