### ISSUE TITLE
D1 character order is broken

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#2547]
This changed sometime in the last week. 

I have sort by character age, which should be Hunter/Warlock/Titan, but it is now showing Hunter/Titan/Warlock. 

However the order in the item move seems to be in the right order, or it’s moving to the wrong character.

**Comment by bhollis** [comment]
Was this on Beta?

**Comment by bhollis** [comment]
We made a change to fix the order for D2 but I guess it doesn’t work for all D1 accounts. No idea if it really works for D2 either (besides knowing that our D1 fix doesn’t work either). The API doesn’t really give us creation time. Maybe we should rename that setting “arbitrary but fixed order”.

**Comment by bhollis** [comment]
I pushed a fix to beta, can you check?

**Comment by philkernick** [comment]
Yes, it was the beta.  And your current fix has fixed it.
