### ISSUE TITLE
DIM has just stopped working in Chrome. Says 'not connected to internet'.

### ISSUE THREAD

**Issue by Skyssx** [DestinyItemManager/DIM#2550]
Midway through today DIM started acting this way. I hadn't changed anything on my computer in months. Restarting the browser, the game, the Blizzard loader, and the PC haven't helped. Windows 10 and Chrome 63. I logged into the site with Edge, and it works there. What's going on here?

![dim bug](https://user-images.githubusercontent.com/9385834/34971958-4e253a5e-fa4c-11e7-8089-2be526439f73.PNG)

**Comment by bhollis** [comment]
Do you have an adblocker or Privacy Badger extension installed? Sometimes they update and block bungie.net.

**Comment by bhollis** [comment]
Bungie.net was also down for a portion of the day.

**Comment by Skyssx** [comment]
Still broken.

**Comment by duckmanBR** [comment]
In your screenshot I can see uBlock, check if destinyitemmanager.com and bungie.net are green. If still doesn't work, check if you have any other adblocker/privacy extension.
Like bhollis said, they usually are the culprit.

**Comment by Skyssx** [comment]
![ublocko](https://user-images.githubusercontent.com/9385834/35046375-ccf85474-fb64-11e7-9466-13cdcf64c2b1.PNG)

**Comment by duckmanBR** [comment]
So it's not uBlock.  The one to the right looks like Privacy Badger, the problem is that I don't use it so can't help you through (but post here anyway), but it's the next suspect...
