### ISSUE TITLE
Settings not working for D1 

### ISSUE THREAD

**Issue by inexorableAce** [DestinyItemManager/DIM#2554]
Item sorting, character sorting, and show ratings don’t seem to be working for the D1 side of the app.

**Comment by bhollis** [comment]
Could you be more specific about what doesn't work? I assume you're talking about Beta? I tried changing each of those settings and they affected my D1 inventory as I would expect.

**Comment by inexorableAce** [comment]
It’s in prod. Checking options has no effect. If you choose an item sort, nothing happens. If you choose to show ratings nothing happens (or if you had them shown and uncheck that option, they are still there) the options just don’t seem to work for D1

**Comment by inexorableAce** [comment]
Well now that I went to get screen shots, I tested and it still wasn’t working but then I checked a setting and was screen shotting / marking up and in the time it took me to do that the setting had worked... perhaps it’s just a delay? Now they work without a delay though. Not sure but the definitely had no effect last night when testing a report from the discord. I was and am testing on iOS so maybe it’s just the new update causeinf slowness?

**Comment by bhollis** [comment]
Does it work in Beta? Since we changed everything ipretty much only care if the new page works.

**Comment by inexorableAce** [comment]
Yeah they seem to. Was still a bit odd like rating weren’t shown when I loaded, I went to settings ratings was already checked, but I unchecked and rechecked and they were there 👍

**Comment by bhollis** [comment]
Ratings take a while to load in once they're enabled.

**Comment by inexorableAce** [comment]
Yeah the more I’m testing the more I’m seeing most of this is just lag time. D1 just seems to take significantly longer for things to take effect than D2. Even just loading up takes more time. I think we are good to close this. It’s working. Thanks!
