### ISSUE TITLE
Exotic Class Item Conflicts with Armor Items

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#256]
In Year 2, you can wear an exotic class item with an exotic armor item.  DIM doesn't agree with this proposition and will unequip the exotics when equipping an exotic.

**Comment by Randactyl** [comment]
It's not any exotic class items, just ones with "The Life Exotic" node in column 0. So far I've only found this to be for the exotic faction class items.

"Circle of War" - FWC: http://i.imgur.com/7WAbQQT.png

**Comment by SunburnedGoose** [comment]
Thanks, that helps out quite a bit.

**Comment by jorgebsa** [comment]
Came here to create this issue, glad to see that you are already tracking it!

**Comment by SunburnedGoose** [comment]
Fixed.
