### ISSUE TITLE
Something broke

### ISSUE THREAD

**Issue by ghost** [DestinyItemManager/DIM#2561]
![screenshot_2018-01-20-02-08-16](https://user-images.githubusercontent.com/35622479/35181075-245b496c-fd89-11e7-88fa-ca567538ad95.png)

**Comment by izzy1045** [comment]
Please tell me how to fix

**Comment by bhollis** [comment]
Try reloading?

**Comment by marcomarotta** [comment]
sooo...that's not just me. Tried to connect g drive and that's the page i got.

**Comment by bhollis** [comment]
Thanks for providing info on what you were doing. I assume this is in Beta?

**Comment by bhollis** [comment]
Should be fixed in a few minutes.
