### ISSUE TITLE
Feature Request: Show Time and Options 

### ISSUE THREAD

**Issue by ZzCoderzZ** [DestinyItemManager/DIM#2567]
Show the time the page was last refreshed and the time since last refresh. Give options for inventory AND full page refresh intervals. 

Track XP gained in interval (possibly using emblem level bar changes if necessary). Glimmer and shards potentially.

Auto-move postmaster to vault. Leaving PE chests unopened to save time for PE double dipping is a huge boost to farming efficiency (if glimmer is not desired). If too many are done, drops get deleted from the postmaster.

**Comment by bhollis** [comment]
> Show the time the page was last refreshed and the time since last refresh. Give options for inventory AND full page refresh intervals.

How would this help you? Can you describe more about what you want DIM to help you achieve?

> Track XP gained in interval (possibly using emblem level bar changes if necessary). Glimmer and shards potentially.

What would you do with this information?

> Auto-move postmaster to vault.

We'll be doing this as part of Farming Mode pretty soon.
