### ISSUE TITLE
is:inloadout filter not working

### ISSUE THREAD

**Issue by M-a-i-a** [DestinyItemManager/DIM#2570]
The "Browser screenshot" shows that the "test" loadout contains the Jade Rabbit, but you can see that the Jade Rabbit is equipped on the Hunter, yet it is grayed out (not highlighted by the is:inloudout filter).
Chrome version and OS version screenshots also attached.

![browser screenshot](https://user-images.githubusercontent.com/35671699/35200465-7b2b6870-fed4-11e7-9faf-ac331c5a1031.JPG)
![os version](https://user-images.githubusercontent.com/35671699/35200466-7b3b2292-fed4-11e7-916c-a2e438790fa9.JPG)
![chrome version](https://user-images.githubusercontent.com/35671699/35200467-7b4c7196-fed4-11e7-823a-f36d4feb54e7.JPG)

**Comment by duckmanBR** [comment]
Yes, it's a know bug (#2410)

**Comment by M-a-i-a** [comment]
​Sorry about that... I'll try to do a better job of searching for open
issues to avoid opening an "is:dupe"! :-)​
