### ISSUE TITLE
Feature Request: Filter items that give bright dust when dismantled.

### ISSUE THREAD

**Issue by QuixoticWolf** [DestinyItemManager/DIM#2573]
There are some items that give dust when dismantled, for example, some shaders give you dust while others give you shards.

This would be a nice feature to have for anyone that is trying to buy stuff from Eververse/keep vault tidy without guessing which stuff gives dust or not.

Thanks.

**Comment by bhollis** [comment]
This would be super cool. We'll have to source the data from somewhere other than Bungie's API though, and I'm wary of maintaining data like this by hand.

**Comment by kyleshay** [comment]
Are there items other than Eververse gear that give you bright dust?

**Comment by duckmanBR** [comment]
Not sure if sparrows that we get from strikes/factions gives dust when dismantled.

**Comment by SunburnedGoose** [comment]
No

**Comment by delphiactual** [comment]
Closed by #3300 `source:eververse`
