### ISSUE TITLE
Consistency of D1 Activities vs D2 Progress

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#2574]
In the D1 side of DIM, there is an Activities tab, showing what you have to do.
In the D2 side of DIM, there is a Progress tab, showing what you have to do.

They should have the same label as they reflect the same information.

**Comment by bhollis** [comment]
Hmm, in this case we're trying to align with the terminology used by each game. In D2 this is called "Progress", while in D1 it's more of a checklist of activities you could do each week.
