### ISSUE TITLE
Infuse UI

### ISSUE THREAD

**Issue by lukefx** [DestinyItemManager/DIM#258]
What about a dialog that, when you select an armor or a weapon, will prompt a popup with a UI similar to the one in game that let you choose which item you want infuse and show you the result...
The math is simple...should be simply [(target-current)/.80]+current where: target = item with more light, current = item to infuse

**Comment by dheif** [comment]
There seems to be a slight variation when the item you use for infusion is fully unlocked. It seems like it's 100% and not 80%.

**Comment by flameofzion** [comment]
80% of the difference between the two weapons, yes. 



Simeon Berns

**Comment by dheif** [comment]
It's not always 80%:
https://www.reddit.com/r/DestinyTheGame/comments/3lddka/infusion_calculator/cv5vnbb

Happened to me as well.

**Comment by flameofzion** [comment]
Ah. Good to know! I will have to remember to use notes of light on the weapon before infusing. 



Simeon Berns

**Comment by SunburnedGoose** [comment]
I'm fine just showing users weapons that can be infused, and leaving the between the user and Destiny.

is:infusable is a way to show what purples you own that have higher light weapons available to infuse as a filter.

**Comment by dheif** [comment]
Mock for fun:
![image](https://cloud.githubusercontent.com/assets/8069361/10046898/5c93cdca-61d9-11e5-96f5-6607d452a54f.png)

**Comment by kyleshay** [comment]
thanks for the tip @dheif 

Infused a blue (leveled, didn't purchase the perks) into a purple and it upgraded the purple to the same level as the blue. I'm glad they did it this way.

**Comment by lukefx** [comment]
@dheif This is the actual UI not completed...super simple, your mock is awesome...nice touch the suggest at the bottom!

![image](https://cloud.githubusercontent.com/assets/28878/10047906/a93237d4-6210-11e5-96eb-f64b3c34dfe3.png)

**Comment by dheif** [comment]
The UI should give you the possibility to select multiple items... at least this is want I'd like to have. Calculating 80% of something is easy, but 80% of 80% of 80%... that's where this window could be handy.

**Comment by SunburnedGoose** [comment]
Can you change the checkbox to numbers so we can show them order?  If they
uncheck we just adjust the numbers above it down.

**Comment by lukefx** [comment]
@kyleshay Actually not always you get the max from infusion... https://www.reddit.com/r/DestinyTheGame/comments/3m546p/there_is_an_exception_to_the_80_infusion_rule/

**Comment by lukefx** [comment]
@dheif I implemented some of yours suggestions, now you can click on multiple items. The UI is still in WIP...like sorting items and so on...

![infusion](https://cloud.githubusercontent.com/assets/28878/10135998/482548a6-65f2-11e5-9e48-2766da5284ca.gif)

**Comment by dheif** [comment]
Pretty cool @lukefx, I like it!

I just had an idea regarding infusion. I don't think it's the optimal way of displaying it, but I wanted to share the raw idea:

![image](https://cloud.githubusercontent.com/assets/8069361/10146531/6d001a48-65f7-11e5-9fe3-82f4a446fda7.png)

It would enable a user to test different infusion scenarios quickly and foresee the output.

**Comment by wein3967** [comment]
It took me a minute, @dheif, but I see what you are doing there. I like it. I am certainly struggling planning the optimal multiple infusions on stuff.

**Comment by lukefx** [comment]
@dheif Maybe it was not clear...but the code do that already, we should only fix the UI to show it properly. What do you think like this?

![infusion](https://cloud.githubusercontent.com/assets/28878/10157043/d3b704f6-6686-11e5-8b44-4c74b9c49969.gif)

I really like your mock but maybe it's a little bit complicated...
Any suggestion is super welcome...just an idea here

**Comment by dheif** [comment]
@lukefx I really dig this! Well done! :)

**Comment by SunburnedGoose** [comment]
Looks good.  

How solid is the calculation?
How should this be integrated?  Item popup?  Distinct area of the app dedicated to infusion calculations?

**Comment by matthubb** [comment]
It seems that there are subtleties to infusion that aren't well understood. It appears that the difference between tiers and / or item levels adjusts the infusion amount up or down depending on whether the sacrificial item is higher or lower than the recipient item. It appears that Rare to Exotic yields less than 80% the difference and Exotic to Legendary yields more than 80%.

**Comment by dheif** [comment]
Other relevant information: https://www.reddit.com/r/DestinyTheGame/comments/3m863v/actual_infusion_rates/

**Comment by lukefx** [comment]
@SunburnedGoose the button for infusion is in the item popup, we should add the infusion icon maybe...one for armors and one for weapons

**Comment by lukefx** [comment]
> How solid is the calculation?
I wrote a message to the creator of this (http://infusioncalculator.hamnation.com) just to know how many exceptions he knows about.

Meanwhile I think that we're good to go, the final result is this:

![infusion_2](https://cloud.githubusercontent.com/assets/28878/10191441/3e7b80c6-6774-11e5-8b60-e48ba5dcd762.gif)

**Comment by SunburnedGoose** [comment]
Looks solid. Would love a 'pointer' on the infusion icon.

**Comment by jflayhart** [comment]
Brilliant! This would save me many mistakes and figure out a better upgrade path.

**Comment by lukefx** [comment]
> Looks solid. Would love a 'pointer' on the infusion icon.

@SunburnedGoose Done! 40f160b1551d6443cdb4e10e4595b88a372de4f3

**Comment by SunburnedGoose** [comment]
Something isn't right with your calculations.  In the last animated gif, you show...

271->274->275->284->285
the results are
271->273->275->282->284
but it should be
271->**274**->275->282->**285**

And then at the end of the gif, you add a 284 to a 285 which isn't allowed.

You need more validation and we need to double check the math here.

**Comment by flameofzion** [comment]
Is infusing always a mathematical equation? Someone told me there is an RNG
factor as well?

**Comment by lukefx** [comment]
> And then at the end of the gif, you add a 284 to a 285 which isn't allowed.

@SunburnedGoose The result was 282...so you can infuse a 284. The code is there...and it speak itself. Checkout the code and try yourself :smile:

**Comment by lukefx** [comment]
> Is infusing always a mathematical equation? Someone told me there is an RNG
> factor as well?

@flameofzion it's possible, on reddit users report strange behaviour sometimes, but it could depends on the xp in the weapon/armor.

**Comment by SunburnedGoose** [comment]
Yes I see.  I'm was blind to the running total. What about the other question?  The math seems off.

**Comment by lukefx** [comment]
274-271 = 3
3 * 0.8 = 2.4
round(2.4) = 2
271 + 2 = ***273***

This is the math...we should check, and I'm already working on it, if the gear has some XP sometimes you get the full value...so yes may be ***274***, but it should be confirmed.

**Comment by dheif** [comment]
Upgraded a 300 shotgun with a fully upgraded Black Spindle, got 308. My friend didn't upgrade it, got 307.

**Comment by SunburnedGoose** [comment]
<=6 is 100% for Rare and Legendaries.

**Comment by lukefx** [comment]
you infused a 310 into a 300? Other users have reported a 70% for exotics...

**Comment by SunburnedGoose** [comment]
I think I got 7 for my Spindle too..

**Comment by lukefx** [comment]
yepp, already done the check for legendary/exotics infusion.

**Comment by dheif** [comment]
Yeah but I unlocked all perks AND upgraded them all. My friend didn't upgrade it.

![image](https://cloud.githubusercontent.com/assets/8069361/10228075/f74e386c-683e-11e5-801f-ac919e4eaf71.png)

**Comment by SunburnedGoose** [comment]
@lukefx rares and legendaries that are within 6 points infuse at 100% is the difference in our math.

**Comment by lukefx** [comment]
Hey...now it's dinner time here (Switzerland, 7:33PM), give me 30 minutes and then we modify the math... :+1:

**Comment by SunburnedGoose** [comment]
:)

**Comment by lukefx** [comment]
Can we assume this? Infusing an exotics is always 70% even if the difference is minor than 7?

````js
// rares and legendaries that are within 6 points infuse at 100% is the difference
if (!tier === 'Exotic' && (target - source > 7)) {
  result = target;
}
````

**Comment by lukefx** [comment]
Ok 2402d2097d3df1c3a10ddc345218e330e91eeea9 now the math should be fine...we should put a test version somewhere so that everybody (in this chat) can test it out with actual game.

**Comment by kyleshay** [comment]
merged in to dev! thanks @lukefx !!!

**Comment by lukefx** [comment]
Yay!!! Thx to you guys. Anyway I'm ready to tweak the math if needed...

**Comment by dheif** [comment]
You're the man! :+1:

**Comment by SunburnedGoose** [comment]
I'm going to work on the UI a bit and push an update tonight.

**Comment by lukefx** [comment]
Yepp, the UI could be more simple and reusable if we use a css framework like Bootstrap. But this is another PR... :smile:

**Comment by kyleshay** [comment]
one thing we did not necessarily consider in the calculation is detecting if an item is fully leveled (nodes not unlocked), as pointed out by @dheif:
> Upgraded a 300 shotgun with a fully upgraded Black Spindle, got 308. My friend didn't upgrade it, got 307.
This is something we can add in a future release, unless we get the numbers down before then. I'm guessing it's different for exotics/legendaries?

**Comment by dheif** [comment]
Maybe there a random factor also, which would be sad for a calculator :)

**Comment by kyleshay** [comment]
maybe we should add a disclaimer/margin of error to the popup. haha.

**Comment by lukefx** [comment]
add a check if user put some xp into weapons/armors is easy...we should use it in real world and report wrong results...

**Comment by lukefx** [comment]
Guys, some thoughts about the infusions math? Have you tried it?

**Comment by kyleshay** [comment]
seems to be fairly accurate, there was one user who reported an issue:

https://www.reddit.com/r/DestinyTheGame/comments/3nzbr1/dim_v3112_new_infusion_calculator/cvsouf8

maybe it's user error?
