### ISSUE TITLE
DIM Freezes when moving a mod from my vault to my character with full mod slots

### ISSUE THREAD

**Issue by JonnyOThan** [DestinyItemManager/DIM#2582]
If I have 50/50 mods on my character inventory and I try to use DIM to move a mod from my vault to the character, it freezes and I have to reload the page.

**Comment by bhollis** [comment]
Just merged some code into Beta that should help with that. Can you try and let me know how it goes?

**Comment by JonnyOThan** [comment]
Seems to work, thanks!
