### ISSUE TITLE
Missing Icons for Masterworks in Edge

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#2585]
There is some issue with the relationship between the .item-img rule and the .item-img.masterwork:after rule.

![image](https://user-images.githubusercontent.com/984608/35471377-b890b928-031f-11e8-8518-8c26adf63051.png)

**Comment by SunburnedGoose** [comment]
@duckmanBR Did you work on this area?

**Comment by duckmanBR** [comment]
HI goose, no, I didn't (although I have a PR with @inexorableace code on it).

The problem is, I can't reproduce the error...
![image](https://user-images.githubusercontent.com/32077894/35473364-9b6aee26-0366-11e8-8de4-617538e2a213.png)

**Comment by inexorableAce** [comment]
Weird... just missing images? My code was just a css tweak to the existing pseudo :after element. Nothing that would cause this to my knowledge. Just changing it from a filter to a background gradient.

**Comment by SunburnedGoose** [comment]
I'm using EdgeHTML v15.  I haven't upgraded to v16.  We should be supporting N-2 with is EdgeHTML 14.

**Comment by bhollis** [comment]
Looks like Edge has a bug with rendering transparent radial gradients

**Comment by inexorableAce** [comment]
Could just make it a solid bottom to top gradient. Though in the screen shot the gradient seems to render just fine.

**Comment by SunburnedGoose** [comment]
I think there is an order issue with the CSS and another due to the mathematics using calc.  Use --var-size instead of 100%.

**Comment by duckmanBR** [comment]
At least by our [own checking,](https://github.com/DestinyItemManager/DIM/blob/a99c2a9944348b08ce9eccee20fb20dbb2694ffc/src/app/settings/settings.component.js#L100) Edge still doesn't support css vars...

**Comment by SunburnedGoose** [comment]
I think 14 didn't.  15 and above does.

https://caniuse.com/#feat=css-variables

**Comment by duckmanBR** [comment]
Can't test it right now, but I'm almost sure that 16 have no item size or column number in settings...

**Comment by bhollis** [comment]
My guess is because while it supports CSS vars, it may not support `@supports` which we use to detect var support.

**Comment by delphiactual** [comment]
![screenshot 2018-05-20 21 54 22](https://user-images.githubusercontent.com/4798491/40289932-6d50e4ee-5c78-11e8-8d41-47c4be5fa7b1.png)
Working on beta (Version 4.52.0.2103 (beta), built on ‎5‎/‎20‎/‎2018‎ ‎9‎:‎22‎:‎33‎ ‎PM) in:
Microsoft Edge 42.17134.1.0
Microsoft EdgeHTML 17.17134
