### ISSUE TITLE
Keyboard shortcuts on different language setting than english

### ISSUE THREAD

**Issue by t6photo** [DestinyItemManager/DIM#2589]
Hi, 

Keyboard shortcuts, to tag items as trash/keep/fav/infuse, only work if you have english keyboard configuration. Well, to be more accurate, ! and $ work as in spanish keyboard you type them by shift+1 and shift+4 respectively, but # and @ are done using altgr button so they dont work. I guess that if instead of using # and @ for shortcuts another combination of shift+something was used, it would work. The shortcut is really helpful and doing it with mouse is really slow... so different shortcuts or possibility to set your own shortcuts would be awesome. Hope this can be added on future releases! Thanks!

**Comment by bhollis** [comment]
Great point. We’ll make them localized. What would be good keys to use?

**Comment by bhollis** [comment]
Cool, this should be better in Beta. Let us know!

**Comment by t6photo** [comment]
I guess shift+1, 2, 3, 4 would be also perfect. In spanish keyboard is !"·$ respectively.

Thanks!

**Comment by t6photo** [comment]
By the way, just realized now that shortcut for full item info (¡) is also not working, and I think also that moving through the inventory using arrrow keys would be a great improvement also, so it's easier to move and tag everything. 

Thanks!

**Comment by t6photo** [comment]
working great on DIM beta, just the shortcut fot opening help is a bit more hidden now than before (before it was shift+' (where we have question mark) and now / should be shift+7 but it's not working. Only wai I could open it is using / from numeric keypad.

Thanks!

**Comment by duckmanBR** [comment]
Wow, the spanish layout is **really** different...
![image](https://user-images.githubusercontent.com/32077894/35566067-332bf7e0-05a7-11e8-822f-da6cf1696942.png)

**Comment by 48klocs** [comment]
Oh yikes - i took a shot in the dark on changing the help shortcut and it sounds like I made it worse. 

I’ll revert my change on the help pop up shortcut tonight (but leave the updated shift+1-4 changes in place).

**Comment by duckmanBR** [comment]
The thing is, how the `?` is working and the `@` wasn't?

**Comment by delphiactual** [comment]
Angular-hotkeys probably isn't taking into account for different keyboards...

**Comment by 48klocs** [comment]
You can set a key (it was and will be ‘?’); I changed it to ‘shift+/‘ based on the faulty assumption that this would map across all keyboards properly. 

I’ll do a little research and see if there are known conventions to swap around ?.

**Comment by t6photo** [comment]
haha yes, it's really different spanish keyboard on symbols location...

it's weird shift+/ works only on the numeric keypad, but ? was working well so it's good if it's stays

about known conventions, for example a software I use, uses H as "help" which makes a lot of sense. Maybe mapping shortcuts into single letters or numbers would make it all easier around any languages. You already use R, F and X so, why not?

Also, just to mention, chrome has this shortcut mapping option for extensions, that having a chrome extension for dim, maybe would be good to use in the future.

(example of another app on chrome that uses shortcuts)
![image](https://user-images.githubusercontent.com/35928036/35581617-99ab3a5e-05ec-11e8-800d-0a3e2dfbbbbe.png)


by the way, do you want me to open another issue to suggest using keypad arrows to move accross inventory?

**Comment by 48klocs** [comment]
@t6photo full item info's hotkey is the english lowercase I (i) - what you pasted in is, I think, an inverted exclamation mark?

This has been closed, but I created #2601 to get comments from folks from other countries about expected conventions around keyboard shortcuts.

**Comment by t6photo** [comment]
for me it's clear is a lowercase i and not inverted exclamation mark

thanks for fixing it, by now everything works perfectly

sorry to insist on this, but how about adding arrow keys navigation?

**Comment by duckmanBR** [comment]
I believe it's not as nearly simple to implement as it may appear...  Anyway, create an issue asking for this feature so we can further talk about it.
