### ISSUE TITLE
Collect from Postmaster until Inventory Type is Full

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#2594]
I don't know if this is the case, but I want to test the scenario as it relates to #2577.

If the postmaster has > 10 items of a single type (primary), and I click on "Collect Postmaster", would it be useful to only take 10 items and let the player process them?  If there are more, leave them in the postmaster until the player clicks on "Collect" again?

It seems like a good QoL feature to avoid dispersing items across the other stores and forcing the player to hunt for new items.

**Comment by SunburnedGoose** [comment]
#2577

**Comment by bhollis** [comment]
FWIW with only 20 items possible in the postmaster, it's hard to get 10 of a single type.
