### ISSUE TITLE
Move Postmaster to the Top of the Inventory

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#2595]
It's a QoL update to help players be aware that they have items in the postmaster to process.  I hear of complaints about always scrolling down to manage it.  Players spend most of their time at the top of their inventory, and this forces them to go to the bottom regularly.

**Comment by kyleshay** [comment]
Yeah, what if it was at the top, and if there is nothing there it just disappears? Maybe have an easy 'withdraw all' button right near it (instead of in the dropdown menu.)

**Comment by duckmanBR** [comment]
I would prefer a "custom sort" to the buckets or an option to something like kyle said, of disappearing buckets when empty (but that would probably works best on mobile, where we treat each column independently).

Why I'm against it without any improvement of how buckets work:
normal view / view with postmaster on top
![image](https://user-images.githubusercontent.com/32077894/35565283-16586b42-05a4-11e8-94f3-ca9b966c9f2c.png) ![image](https://user-images.githubusercontent.com/32077894/35565479-ccdfc658-05a4-11e8-9770-e83514d2d987.png)
And before anyone reply with a "but you could collapse the bucket", collapsing/expanding everytime would be more cumbersome than a simple "hard scroll" and letting the page go to the end.

**Comment by jllawrence** [comment]
Perhaps draggable sections would please everyone?

**Comment by bhollis** [comment]
We’ve talked about that idea a bunch, but its a bunch of complexity when only a few customizations really make sense. We’re justbwaiting for a few structural changes to how we handle items, then we’ll move postmaster to the top but only if it has contents.
