### ISSUE TITLE
Beta site won't load starting today

### ISSUE THREAD

**Issue by epiccelt** [DestinyItemManager/DIM#2596]
Suddenly I am getting the error below when loading the beta site. The standard release site works fine still. Still present as of 4.37.0.1803

> 
> Bungie.net Error
> Bungie's services currently have a bug that prevents DIM from loading info for your Destiny 2 account if you played Destiny 1 on a last-gen console. Bungie will fix this soon, but until then you must play Destiny 1 on a current-gen console to be able to access your info.

**Comment by duckmanBR** [comment]
If you are using a bookmark, remove everything after the `#!` and try again.

**Comment by bhollis** [comment]
I think I know what’s different. Let me dig into it.

**Comment by epiccelt** [comment]
Tried going directly to https://beta.destinyitemmanager.com/ and still have the same issue. Also refreshed to 1814 build and still seeing this issue.

**Comment by bhollis** [comment]
I just pushed something I think should fix it. Give it 5 minutes to deploy then check it out.

**Comment by epiccelt** [comment]
This is resolved for me in 1821
