### ISSUE TITLE
Links to Chrome and Firefox Addons

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#2600]
How do users find out about these addons from destinyitemmanager.com or from within the app?

**Comment by bhollis** [comment]
We can link them from the brochure sute. I’m not sure we need more prompting than that, theyre super inessential

**Comment by bhollis** [comment]
There's some stuff in here: https://developer.chrome.com/webstore/inline_installation?csw=1

**Comment by kyleshay** [comment]
FYI- from that article: 
> As of 06/12/2018, inline installation is deprecated.

We could add a link in the about page, readme, or website?

**Comment by kyleshay** [comment]
I suppose if we wanted we could add it to the website, feature  it as a quicker way to get to your gear?
