### ISSUE TITLE
RFC - i18n and keyboard shortcuts

### ISSUE THREAD

**Issue by 48klocs** [DestinyItemManager/DIM#2601]
Issue #2589 brought up the fact that some keyboard shortcuts don't map well across other keyboard layouts.
For example...
- changing '?' to 'shift+/' is fine on English keyboards, but 'shift+/' requires serious contortions on Spanish keyboards)
 - a suggestion in that case was made to use 'H' instead of '?' as a convention, but I'm guessing that would cause further confusion in other languages we support
- the letter 'i' (English lowercase I) can be mistaken for an inverted exclamation mark ('¡') pretty easily since they're practically homoglyphs

I'm not sure how far into the rabbit hole we want to dive with this, but if we want to address it, comments from folks from non-English speaking countries about what conventions exist for pulling up help menus would be helpful.

**Comment by bhollis** [comment]
@48klocs what do you want to do with this?

**Comment by 48klocs** [comment]
@bhollis this can get closed since I don't think it's going to pick up any movement at this point.
