### ISSUE TITLE
Masterwork Armour Heiro Camo not displaying in DIM

### ISSUE THREAD

**Issue by joshhunt** [DestinyItemManager/DIM#2603]
I had two Masterwork Armor Heiro Camo's drop for me, and they're not showing up in DIM, with an error in the console.

```
console.js:32 Error processing item {itemHash: 3629447000, itemInstanceId: "6917529050696767066", quantity: 1, bindStatus: 0, location: 1, …} TypeError: Cannot read property 'displayProperties' of null
    at k (d2-item-factory.service.ts:947)
    at l (d2-item-factory.service.ts:608)
    at d2-item-factory.service.ts:374
    at Function.w.each.w.forEach (underscore.js:153)
    at d2-item-factory.service.ts:371
    at u (angular.js:17160)
    at angular.js:17208
    at d.$digest (angular.js:18343)
    at d.$apply (angular.js:18640)
    at angular.js:18943
    at i (angular.js:6419)
    at angular.js:6698
    at r (raven.js:360)
```

It looks like it can't find the right stat? https://github.com/DestinyItemManager/DIM/blob/54da0ef/src/app/inventory/store/d2-item-factory.service.ts#L947

Issue happening on Beta and Prod.

**Comment by joshhunt** [comment]
<img width="203" alt="screen shot 2018-01-30 at 11 58 42 pm" src="https://user-images.githubusercontent.com/46142/35598141-87f40b74-0619-11e8-929f-b959229224fc.png">


statHash is undefined - it never finds masterworkStat on the sockets.

**Comment by SunburnedGoose** [comment]
We struggle with testing undefineds and nulls.

**Comment by joshhunt** [comment]
At least it just hides the item than crashing the entire app!

**Comment by bhollis** [comment]
TypeScript should help with this but that particular code was written in a way that confuses TS.

**Comment by bhollis** [comment]
It doesn't help that the bungie service definition files tend to be inaccurate about what can be null...

**Comment by bhollis** [comment]
I merged @duckmanBR's refactoring, but I think #2607 will be required to fully fix this. @joshhunt  can you tell me if it's fixed now?

**Comment by bhollis** [comment]
Well, I've merged my fixes so it should be good.

@SunburnedGoose I'm thinking we should do a release tomorrow (Wednesday) assuming everything in beta is OK, so that masterworks and the well-rested XP both get fixed.

**Comment by joshhunt** [comment]
Yup, fixed on beta.
