### ISSUE TITLE
Masterwork Raid Gear not showing up in DIM (web app)

### ISSUE THREAD

**Issue by Luffy1757** [DestinyItemManager/DIM#2613]
![raid masterwork armor bug](https://user-images.githubusercontent.com/35998513/35623769-bdd1adaa-065a-11e8-907d-5d4d905ff55d.png)

1 MW mark
1 MW chest
2 MW arms

**Comment by duckmanBR** [comment]
Hi, we already have an issue about it (#2603).
Could you check on beta.destinyitemmanager.com if those items are showing up?
