### ISSUE TITLE
Navigating from About (or Backers) back to Inventory fails

### ISSUE THREAD

**Issue by 48klocs** [DestinyItemManager/DIM#2614]
Testing on the beta site, I clicked over to About (since I made a minor text change I was double-checking) and then tried to go back to inventory. It failed on both Chrome and Firefox. Clicking the DIM image in the left of the header works to get me back to my inventory, but clicking "Inventory" or "Progress" fails from those pages.

`Transition Rejection($id: 0 type: 6, message: The transition errored, detail: Error: Param values not valid for state 'destiny2.inventory'. Invalid params: [ membershipId, platformType ])`

`Error: Param values not valid for state 'destiny2.inventory'. Invalid params: [ membershipId, platformType ]
    at r (invalidTransition.ts:15)
    at transitionHook.ts:153
    at t.invokeHook (transitionHook.ts:153)
    at Function.t.invokeHooks (transitionHook.ts:107)
    at t.run (transition.ts:706)
    at t.transitionTo (stateService.ts:371)
    at t.go (stateService.ts:261)
    at stateDirectives.ts:78
    at angular.js:20557
    at i (angular.js:6419)
    at angular.js:6698
    at r (raven.js:360)`

**Comment by bhollis** [comment]
Ah, this is from the routing stuff i changed around. I can fix it up easily but I’m traveling for a bit. 

-Ben
