### ISSUE TITLE
Loadouts with exotic ghosts, sparrows, or ships fail to equip.

### ISSUE THREAD

**Issue by slombardo** [DestinyItemManager/DIM#2618]
I believe the problem is in or around [this block of code](https://github.com/DestinyItemManager/DIM/blob/10093de00de8e6738af4df0738c5c5757ad20fb2/src/app/inventory/dimItemService.factory.ts#L367-L373).  

From what I can tell, when a loadout contains an equipped exotic armor piece and/or an equipped exotic weapon and/or an equipped exotic ghost/sparrow/ship when equipping that loadout to the character, you get the error message 
>We don't know how you got more than 2 equipped exotics!

Maybe you should exclude exotic ghosts/ships/sparrows from the filter.

**Comment by duckmanBR** [comment]
Hi, just tested (on beta) and got them equipped without problem
My only caveat is that I don't have a spare sparrow so my loadout only equip a ghost and a ship (all 3 are exotic)

Can you send some screens?

**Comment by slombardo** [comment]
Sure, ok So I have 2 hunters. I am trying to equip is this:
![image](https://user-images.githubusercontent.com/1529389/35686913-76d0355c-073b-11e8-9d51-7eeedb91b9f9.png)

| Hunter 1 (works) before equipping loadout  | Hunter 2 (broken) before equipping loadout |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1529389/35686839-40a55656-073b-11e8-846d-811e14e5b336.png) | ![image](https://user-images.githubusercontent.com/1529389/35686873-591faa9c-073b-11e8-8e6e-1b9474a8f3a1.png) |

Here is the error message:
![image](https://user-images.githubusercontent.com/1529389/35687033-abbb9c70-073b-11e8-9041-d371d560704b.png)

**Couple of things to note.**
1) The hunter that cannot equip the loadout previously has an exotic ship AND sparrow equipped, the other has no exotic ship nor sparrow.
2) Notice in the loadout the exotic ghost is equipped.  If I unequip it in favor of my legendary ghost, both hunters can equip the loadout without issue
3) I am able to reproduce this bug shown in the following table:

| Exotic Ship Previously Equipped | Exotic Sparrow Previously Equipped | Can Equip Loadout with Exotic Ghost |
| :---: | :---: | :---: |
| :heavy_check_mark: | :x: | :heavy_check_mark: |
| :x: | :heavy_check_mark: | :heavy_check_mark: |
| :heavy_check_mark:  | :heavy_check_mark: | :x: |

**Comment by bhollis** [comment]
Bungie actually made it way easier to do this logic in D2 - one of my next tasks was to look at this code and make it use the new techniques!

**Comment by bhollis** [comment]
In case anyone wants to take a crack at this while I'm out this week, there's a new property called `equippingLabel` on [DestinyEquippingBlockDefinition](https://bungie-net.github.io/multi/schema_Destiny-Definitions-DestinyEquippingBlockDefinition.html#schema_Destiny-Definitions-DestinyEquippingBlockDefinition) that we can check to see if any two items can't be equipped at the same time. To do this correctly, we need to switch all the "exotic" logic everywhere to use this new property, *and* backfill D1 to populate an appropriate fake equippingLabel for exotics (but being sure *not* to fill it in for exotics with "The Life Exotic" perk). Then we can get rid of the `hasLifeExotic` method and generally clean up everything. This logic should be centralized in a single shared function, too!
