### ISSUE TITLE
Prestige Level displayed on Progress page

### ISSUE THREAD

**Issue by peabeu** [DestinyItemManager/DIM#2619]
Currently the prestige level is displayed as a thin blue line under each characters emblem. To see progress you have to hover your mouse over the line. the tooltip only displays if you hover over the blue progress but not the entire line. When using on your phone, the tooltip is not as easy to view, especially with big fingers. 

Could you have a more detailed view of the Prestige Level on the Progress Page? Perhaps as a progress bar with the data that is shown in tooltips, permanently displayed?

**Comment by bhollis** [comment]
Seems like it'd be cool to have a "Illuminated Engram" fake milestone, like we do for "Well Rested". What do folks think?
