### ISSUE TITLE
Version selector off screen on 10.5" iPad Pro in landscape

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#2620]
If the screen width isn't large enough, the tabs across the top are supposed to collapse into a menu on the left.

On a 10.5" iPad Pro in landscape mode, they don't.  When Xur isn't there, the version selector is just visible on the far right.  When Xur is there, the version selector is completely off the screen, and it's not possible to change version except by editing the URL.

![img_0129](https://user-images.githubusercontent.com/25425159/35775079-ce15be20-09d1-11e8-8d96-48433d3e112f.PNG)

**Comment by bhollis** [comment]
Bless you Phil, for being the last one testing D1 :-)

I’ll get it fixed!

**Comment by bhollis** [comment]
(BTW, I see what's happening - it's the "Report an Issue" link we added in beta that's new)

**Comment by duckmanBR** [comment]
For some reason this wasn't closed automatically with #2699 merge...
