### ISSUE TITLE
On Firefox for iOS, can't check the "Send reputation items to the vault" option.

### ISSUE THREAD

**Issue by QuixoticWolf** [DestinyItemManager/DIM#2622]
This issue is present when using FF on an iPad mini 4. When I activate the "Farming mode" the modal that appears in the lower part of the screen shows the "Send items" option, I can't toggle it, I tap it but it doesn't toggle the checkbox, this happens both in portrait and landscape modes of the iPad.

Thanks.

**Comment by bhollis** [comment]
Can you still reproduce? This isn't the case in Safari for iOS, and they use the same engine.

**Comment by bhollis** [comment]
Can you reproduce it in Safari? I don't have Firefox for iOS but everything works in Safari.

**Comment by bhollis** [comment]
Has this gotten any better? I made some changes.
