### ISSUE TITLE
can't move INVENTORY items to\from vault

### ISSUE THREAD

**Issue by githubDemoAccount-SD** [DestinyItemManager/DIM#2625]
might be a duplicate of issue #2624, but when I try to move items from the INVENTORY section (mods \ transmat effects \ shaders) to \ from vault, I get the errors:

"... mod - Vendor data is unavailable"
"<transmat effect name> - Bungie.net message - the item requested was not found"
"<shader name> - Vendor data is unavailable"

**Comment by duckmanBR** [comment]
yes, it's a duplicate.  bungie should release an update to the api today

**Comment by duckmanBR** [comment]
Bungie released a hotfix today. It's fixed.
