### ISSUE TITLE
Legendary Mod border bug (for all weapons and some armors) 

### ISSUE THREAD

**Issue by duckmanBR** [DestinyItemManager/DIM#2626]
Since the API update DIM isn't showing the gold border for legendary mods on weapons.
Armor is ok.

**Comment by duckmanBR** [comment]
https://github.com/Bungie-net/api/issues/399

**Comment by deefstes** [comment]
This bug doesn't just manifest for weapons. While it seems to be consistent with weapons, it's not exclusive. Some armor items also lack the yellow border despite having a legendary mod applied. And they also don't show up with the is:powermod filter.

Screenshot attached showing two Warlock Bonds that have legendary mods applied and lack the yellow border. The equiped bond has a power level of 335, which obviously would only be possible with an applied legendary mod.
![2018-02-14 09 01 06](https://user-images.githubusercontent.com/20295990/36210956-7d7724ca-11a8-11e8-9764-02df897ea50a.png)

**Comment by duckmanBR** [comment]
API Bug Fixed
