### ISSUE TITLE
Can't lock/unlock gear in vault

### ISSUE THREAD

**Issue by thebrimborion** [DestinyItemManager/DIM#2627]
Seems to apply to weapons and armor, and only in vault. If I move gear to a character slot, it does work properly.

**Comment by duckmanBR** [comment]
It's a bug on the API.
We opened an issue there.

**Comment by duckmanBR** [comment]
Yeah it did. I completely forgot to close this. Thanks.

**Comment by philkernick** [comment]
And the bug is back.  I'm guessing they busted the API again in 1.1.4.

**Comment by duckmanBR** [comment]
Actually no, this time is on us.

**Comment by duckmanBR** [comment]
Since (looks like) the source now is different from this one, I'm opening a new issue.
