### ISSUE TITLE
Calculation error on "Max Base Power"

### ISSUE THREAD

**Issue by duckmanBR** [DestinyItemManager/DIM#2628]
It's returning values higher than 330, as reported on
https://www.reddit.com/r/DestinyItemManager/comments/7w5mo1/max_base_power_bug/

Looks like the cause is the same of #2626

**Comment by bhollis** [comment]
Yeah that's likely the cause.

**Comment by philkernick** [comment]
Seems to be fixed this morning.

**Comment by duckmanBR** [comment]
API Bug Fixed
