### ISSUE TITLE
Bug: Can't Equip Exotic Class Item with Exotic Armor

### ISSUE THREAD

**Issue by jmichas** [DestinyItemManager/DIM#263]
I have the dead orbit titan mark (obtained from level 25 faction quest) which is an exotic but has a perk that allows it to be equipped with another exotic armor at the same time. When creating a load out I cannot set both exotics to be equipped, it toggles between the two. You need to look for the existence of that perk and allow it to be equipped.

Thanks!

**Comment by SunburnedGoose** [comment]
Tracking this on #256.
