### ISSUE TITLE
Long vault-box title breaks down the markup

### ISSUE THREAD

**Issue by Igor-Gribanov** [DestinyItemManager/DIM#2630]
I saw this issue in the russian UI. Vault-box wrapper can hold a title about 93px width without affecting the layout. If the width is greater than 93px, then the Vault-box looks like this:

![vault1](https://user-images.githubusercontent.com/15327771/36062645-707a6144-0e81-11e8-94d6-fdb15da16e3b.png)
![vault2](https://user-images.githubusercontent.com/15327771/36062646-70989bdc-0e81-11e8-9c6f-c1c8ddef692e.png)

**Comment by bhollis** [comment]
Thanks for letting us know! I've fixed it up in beta.
