### ISSUE TITLE
Editing loadouts with missing items and then saving no longer removes them from the loadout.

### ISSUE THREAD

**Issue by wmxp** [DestinyItemManager/DIM#2631]
If you deleted an item in Destiny that belonged to a DIM loadout, you could easily remove that item from the loadout by simply editing said loadout, and then saving it. Now it's permanently stuck with "these items cannot be equipped" empty placeholders which cannot be removed. Clicking the delete cross box in the top right does nothing.

**Comment by bhollis** [comment]
https://sentry.io/destiny-item-manager/dim/issues/445286059/ could be related

**Comment by wmxp** [comment]
Thank you! <3
