### ISSUE TITLE
Pulling items from postmaster does not remove them from the postmaster

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#2635]
When I click on "store" to remove an item from the postmaster, the item is transferred, but it is not removed from the postmaster collection in DIM, and the popup remains.  When I click on 'store' again, I get an error from Bungie because the item has already been transferred.  

When I refresh my data, the item is then removed from the postmaster collection in DIM, and appears in the correct category.

**Comment by bhollis** [comment]
I bet i know why... I had to test with the actual transfer disabled so i didnt have to keep farming 


-Ben
