### ISSUE TITLE
Issue with basepower:<330 in v4.40.0

### ISSUE THREAD

**Issue by Fenris-uy** [DestinyItemManager/DIM#2637]
I have an weapon with basepower 329 and a legendary damage mod making the final power of the weapon 334. But the search with basepower:<330 isn't highlighting that weapon.

![image](https://user-images.githubusercontent.com/787160/36262954-b02d3cde-1247-11e8-8e53-ec20a67d2878.png)

I have a glove with power 334 and a helmet with power 333 that are correctly highlighted

**Comment by duckmanBR** [comment]
This is caused by the same bug in the api that is causing #2626.
Since we can't correctly identify a legendary mod we can't correctly calculate the basepower, so this filter is receiving the power instead (for the filter your item is 334 and not 329).

**Comment by Fenris-uy** [comment]
Closing as duplicate of #2626

**Comment by duckmanBR** [comment]
No need to close.  It's not a duplicate, since this is a different problem.
Only the cause is the same as #2626 and #2628
