### ISSUE TITLE
dupelower does not consistently break the tie when items are of the same power

### ISSUE THREAD

**Issue by joshhunt** [DestinyItemManager/DIM#2638]
This is kind of related to this https://github.com/DestinyItemManager/DIM/issues/2421

 - I have two "Does Not Compute" weapons (lets call them weaponA, and weaponB) in my inventory, both 330 power.
 - is:dupelower highlights weaponA
 - I transfer weaponA to my character, leaving weaponB in the vault
 - I refresh the page, or even just click the little refreshy button thing next to settings
 - weaponB is now highlighted as the dupelower

This makes it hard to verify that I've correctly transferred all lower dupes to my character because DIM keeps changing its mind about what's lower or not.

This occurs on both beta and prod.

If helpful, I can give you a copy of all my API responses...

**Comment by SunburnedGoose** [comment]
Sounds like it is defaulting to items in the vault.  Could use some state to track items identified previously if no changes have been made.

**Comment by joshhunt** [comment]
My assumption is that it's defaulting to items _not_ on your character maybe? I noticed that it would never pick the one on my character, regardless if the other dupe was on another character or in the vault.

I'm thinking maybe you just break the tie using the item instance ID. If they're 'equal' (and I guess that's up to https://github.com/DestinyItemManager/DIM/issues/2421) you don't really care which one, as long as it's consistent. If item instance ID doesn't change that seems like a good tie breaker maybe?
