### ISSUE TITLE
Infusion calculation ignores [+5] mods 

### ISSUE THREAD

**Issue by Wh1rledPeas** [DestinyItemManager/DIM#2640]
These screenshots should illustrate the problem...

https://imgur.com/a/rABml

**Comment by bhollis** [comment]
Could you explain what you expected to see? It's not clear to me what you expected to see in those screenshots.

**Comment by Wh1rledPeas** [comment]
I'm sorry Ben.

In one screen I have a 335 weapon with a [+5] mod and it's showing me that
I can infuse it into some 330 weapons. Obviously that won't work because
the weapon is only 330 itself and the mod does not get infused.

The other screen shot shows the opposite... Showing me that I can infuse a
bunch of 335 weapons into a 330.

The infusion tool just needs to use the base power (without mods) when
deciding what is infusable...

**Comment by bhollis** [comment]
I see. We actually do use basePower in the infusion calculator, but a Bungie API bug (Bungie-net/api#399) is causing us to miss that certain items have a legendary mod. It'll be fixed in the next Bungie API deployment. You can tell because those items don't have a yellow border.

**Comment by Wh1rledPeas** [comment]
Okay. Great! Sorry to give you extra stuff to worry about.

-Peas

**Comment by duckmanBR** [comment]
API Bug Fixed
