### ISSUE TITLE
Moving items to vault drops different item into a character

### ISSUE THREAD

**Issue by Joonpark13** [DestinyItemManager/DIM#2642]
This is a strange bug that I'm having trouble reproducing formulaically, but it seems moving some items to the vault from my characters moves a different item from the vault to one of my characters (sometimes current, sometimes not).

For example:

Currently playing Hunter, moved Transverse Steps (leg armor) from my Titan to the vault, resulting in Aeon Safe being moved from the vault to my Hunter.

Currently playing Hunter, moved Jade Rabbit from my Warlock to the vault, resulting in Karnstein armlets being moved from the vault to my Hunter.

Currently playing Titan, moved Prometheus Lens from my Hunter to the vault, resulting in Lucky Raspberry being moved from the vault to my Hunter.

Currently playing Titan, moved Lucky Raspberry from my Hunter to the vault, resulting in Hard Light being moved from the vault to my Titan.

It seems the problem does not occur if I move an item from my current character to the vault, or move items across characters.

I would do some more digging around in the code myself but unfortunately I'm more of a React dev than an Angular dev...

Observed on FF 58.0.2 on Windows, Chrome 63.0.3239.132 on Windows, and 64.0.3282.140 on OS X.

**Comment by bhollis** [comment]
Is your vault full? If so, DIM will move an item out of the vault so you can put something into the vault. It'll move off to another character.

**Comment by Joonpark13** [comment]
Ha, can't believe I didn't think of that option. My vault was at 199/200. Thanks!
