### ISSUE TITLE
Attempting loadout results in popup: "Your loadout of 0 items have been transerred..."

### ISSUE THREAD

**Issue by HaloDiehards** [DestinyItemManager/DIM#2644]
I had similar trouble before, and just stopped messing about with loadouts, but saw a post recently in the DIM Discord that convinced me to try again. Here is what is happening: 

1. I create loadout by hitting the dropdown on my character, choosing current gear, setting it to all characters and saving it with a name.
2. I go to dropdown of a character that does not have those weapons equipped, choose said loadout, and get the attached popup, which says, "(Name of Loadout) Your loadout of 0 items have been transferred to your (race)(sex)(character)", and nothing happens.

Love the app, by the way, use it every single time I'm in Destiny 2.
![unable to use load out dim](https://user-images.githubusercontent.com/3395014/36355271-925ba3f8-1495-11e8-9893-3a0d0f8fc01c.png)

**Comment by bhollis** [comment]
Hmm, I haven't been able to reproduce this? Could you make a video or more detailed description?

**Comment by HaloDiehards** [comment]
Sorry for late reply; a few days later I tried it, all ready to document the issue, and it started working. So weird it fixed after I finally decided to report it, but all is good now.

**Comment by duckmanBR** [comment]
Yeah, looks like #2666 also fixed this.
