### ISSUE TITLE
D2 Vendors

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#2647]
I'm working on adding back vendors roughly as we had them before in D1:

* A single page to see all vendor inventories.
* Individual per-vendor pages we can use to preview engram contents or link for Xur, etc.

**Update**: This is now in Beta, along with a "Collections" page. I'll track TODOs here:

* [ ] Support selecting the character you're viewing as. Right now it's always current.
* [ ] Support search filtering.
* [x] Show currency totals per vendor a la D1 vendors page.
* [x] Highlight items you don't already own (or dim out the ones you do).
* [x] Add item details popup instead of DTR link.
* [x] Add community ratings to vendor items.
* [x] Add links to preview the engrams produced by vendors (requires Bungie API change).
* [x] Show item primary stat.
* [x] Show engram links from progress page even when you don't have engrams available.
* [x] Add links to preview the contents of engrams in your inventory (requires Bungie API change, https://github.com/Bungie-net/api/issues/417).

**Comment by chuckreynolds** [comment]
Yasss... mentioned on twitter but to have in here inline....
```Knowing when a vendor starts having 330’s available would be nice. Pretty sure that’s not available in the API but the crowd sourced @VendorEngrams just isn’t useful that often.```

**Comment by bhollis** [comment]
Progress screens:
<img width="868" alt="screen shot 2018-02-18 at 2 27 53 pm" src="https://user-images.githubusercontent.com/313208/36358749-439db76e-14c8-11e8-8444-719b72ca9dd6.png">
<img width="645" alt="screen shot 2018-02-18 at 4 25 13 pm" src="https://user-images.githubusercontent.com/313208/36358753-5a6b8110-14c8-11e8-9181-277009b869ce.png">
<img width="243" alt="screen shot 2018-02-18 at 4 25 21 pm" src="https://user-images.githubusercontent.com/313208/36358754-5a7e01dc-14c8-11e8-9217-2755c7aac3fc.png">
<img width="345" alt="screen shot 2018-02-18 at 4 25 24 pm" src="https://user-images.githubusercontent.com/313208/36358755-5a90c024-14c8-11e8-9481-f46810a94899.png">

**Comment by bhollis** [comment]
It's worth noting that the APIs I'm using are "in beta" and are returning some real garbage for some vendors. So currently I'm limiting this to engram previews and Xur, as shown in the screenshots above.

**Comment by bhollis** [comment]
@chuckreynolds no, the API does not provide that yet. https://github.com/Bungie-net/api/issues/414

**Comment by bhollis** [comment]
This fixes #2400 and gives me basically all I need for #2288.

**Comment by duckmanBR** [comment]
My two cents:
- on engram preview, can we only show the armor for the class?
- on time of refresh, do you plan on convert time somehow? If not, you should put the UTC/PST/BRT/whatever...

**Comment by bhollis** [comment]
The date display is placeholder. 

The vendor page is done in terms of a particular class, but I haven't yet intelligently wired that up. It'd be neat to restrict armor to class armor.

**Comment by philkernick** [comment]
Firstly, this is awesome work.

A couple of suggestions/comments.
- The links to the engram screen are only there if you have any engrams to collect
- The links feel like they should also (or possibly only) be on the vendor screen and linked to the vendors.
- There aren't any other places that we show links as underlines, so this feels more like it should be using some other approach like icons

**Comment by bhollis** [comment]
https://github.com/DestinyItemManager/DIM/pull/2719
https://github.com/DestinyItemManager/DIM/pull/2718

**Comment by bhollis** [comment]
I'm likely to punt searching until later - I essentially need to rewrite a large part of vendors in order to make them work, and I'll just roll that up into some other work I have pending.
