### ISSUE TITLE
DIM stuck

### ISSUE THREAD

**Issue by D2XBOX** [DestinyItemManager/DIM#2650]
When loading DIM in Microsoft Edge on a laptop running Windows 10, it completes authorizing with Xbox live through Bungie.net ( the bowser has the token for both Xbox.com and Bungie.net as I show as logged into both sites after this step ), but the DIM site hangs at https://app.destinyitemmanager.com/return.html?code= (approx. 40 characters) and displays " authorizing..." and does not load further. Thank you in advance for checking on this.

**Comment by bhollis** [comment]
Sorry about that, we accidentally used a feature that's not supported in Edge. You can use another browser until then, but we'll push a fix for Edge soon.

**Comment by bhollis** [comment]
Let me know if this fixes things in beta!

**Comment by D2XBOX** [comment]
Hello,

It is working again. Thank you for creating the app as well as fixing it so rapidly. I imagine that there is someone you talk to at Bungie when getting the app to work with their software. It would be great if they would change pvp activities to match average kd ratios ( the average of all kd ratios of the players on a team ) to the same level on the other team, within an certain error. It would also be nice if they had match making for Trials. The match making Trials could be called "Trials Random" for instance and would only let you go in as a single player, and be available as a separate event - button to hit in Crucible. Using the average kd ratio idea on this would allow regular players the chance to play with the pros more often resulting in teams that are close to the same level facing off, instead of the blow outs that happen currently. I understand that DIM is not a Bungie product, but was hoping you could pass along the  feedback to the Bungie people that could change Destiny in a way that may increase the player base. Raid match making in which there was another button to select that would take 2 people that have completed the raid fewer than 10 times and put them in a team with 4 people that have completed it more than 10 times might also get more people playing. Thank you for taking the time to read the above.

________________________________
