### ISSUE TITLE
basepower: filter appears to be broken

### ISSUE THREAD

**Issue by corsairmarks** [DestinyItemManager/DIM#2652]
Could be related to #2640.

Basepower filter is not highlighting items correctly.  For example, I have a 334 (thus 329 base) power MIDA Multi-tool, but it is not highlighted with `basepower:<330`.  Also, must items at 335 (330 base) are highlighted with `basepower:>330` - that shouldn't highlight any items because the maximum base power is 330.

![dim-filter-broken](https://user-images.githubusercontent.com/5559092/36403134-ec098eb2-15b0-11e8-89fa-fdb658c9edf2.png)

[edit] Tested DIM v4.41.1 in Edge (41.16299.248.0) and Chrome (64.0.3282.167)

**Comment by bhollis** [comment]
Yup, if you don't see a yellow border, it won't work right because of the API bug.

**Comment by duckmanBR** [comment]
API Bug Fixed
