### ISSUE TITLE
Long initial load time for rating data from DestinyTracker

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#2655]
When loading the app for the first time, the rating data from destiny tracker takes about 12 seconds to load.  This corresponds to the loading time for images.  If we could get the destiny tracker loading before the images, the UI would be more responsive to the user.  Right now, all the images for all the times (even those off screen) are loading in before the ratings data.  It only takes a few moments for ratings data to load so it shouldn't affect user experience.

![screen shot 2018-02-20 at 2 32 28 pm](https://user-images.githubusercontent.com/984608/36448301-cb4e114c-164c-11e8-9f8b-681892305c4a.png)
![screen shot 2018-02-20 at 2 30 31 pm](https://user-images.githubusercontent.com/984608/36448302-cb624202-164c-11e8-8b2a-798c78bbe7d5.png)

**Comment by bhollis** [comment]
What do you mean by images? As far as I know, the ratings load is decoupled from the items load, so we'll show items without ratings, then update them with ratings when they come in.

**Comment by bhollis** [comment]
We're now caching this, which is about the best we can do.
