### ISSUE TITLE
Manifest has been updated with Malice and Spindle

### ISSUE THREAD

**Issue by v-fedorov** [DestinyItemManager/DIM#266]
We were just adding the placeholders for trials report and noticed the change lol

**Comment by kyleshay** [comment]
yup!! thanks, we've updated the manifest with the latest commit: https://github.com/DestinyItemManager/DIM/commit/d77c565d14831bb67ba936a0ee0585f41651f569

manifest was updated after an hour of us going live with our placeholders haha >_<

**Comment by v-fedorov** [comment]
hahah yeah thats why I opened this issue :)
