### ISSUE TITLE
Ghost Info Improvements

### ISSUE THREAD

**Issue by Wh1rledPeas** [DestinyItemManager/DIM#2661]
So far, we've only seen ghosts which apply to one planet or activity. Making the assumption that this will always be the case,  it would be nice to see some sort of indicator, noting the planet or activity the ghost is related to.

I am able to locate ghosts by searching for "nessus", for example, but that's a clunky way to find the right ghost. It would be easier if there was a visual indicator. Perhaps use the same spot where you show elemental damage for weapons?

This attribute of the ghosts perks could also be used as one method of comparison on the pop-up, giving users a tool for sorting and cleaning their inventory of ghosts.

**Comment by Wh1rledPeas** [comment]
It seems obvious, but I should probably point out the perk information should be shown  on the compare panel if the location/activity comparison is added for ghosts.

**Comment by joshminnie** [comment]
I've started adding notes to the ghosts to help me better find them (especially in the case of Io), but this definitely isn't an ideal solution. So a lot of my notes look like the following

```
Planet:IO - Caches/Resources/Glimmer
```

Is the information available in the API to provide at least what planet the ghost is for?

**Comment by Wh1rledPeas** [comment]
@joshminnie I've started tinkering with my search criteria and have discovered ways to search for what I'm looking for.

For example:

 is:ghost "on nessus" cache

Notice I included "on" with the planet name and surrounded the string with quotes. This ensures the whole string "on nessus" exists in the description. This is especially helpful for "on titan", as it excludes anything related to the class "titan".

If you think about the way the descriptions are written, you can usually find exactly what you want.

I just wish these details were shown in the compare dialog, all ghosts were shown, and we could tap on the field we wanted to sort on... 

Location: (planet)/Crucible
Faction: Y/N
Resource: (distance)
Cache: (distance)
Glimmer: (%)
XP: (%)
Telemetry: (¿energy type¿)

**Comment by bhollis** [comment]
<img width="989" alt="screen shot 2018-05-20 at 6 58 06 pm" src="https://user-images.githubusercontent.com/313208/40289376-c8831e4c-5c6c-11e8-9723-933da36ea8c5.png">

This is gonna take some work, but it's the beginning of something like that.

**Comment by philkernick** [comment]
We now have the perk: filter, so if you want nessus ghosts with cache detector you can use this:

is:ghost perk:nessus perk:cache

**Comment by delphiactual** [comment]
closed by #4086
