### ISSUE TITLE
Support for `OR` vs. `AND` searches

### ISSUE THREAD

**Issue by joshminnie** [DestinyItemManager/DIM#2668]
It appears most, if not all, of the search queries become `AND` queries. It would be nice to support the `OR` behavior as well. I like the `AND` behavior for the most part, but there are occasional times when I would like to find two different things.

For example:
```
(tag:junk OR tag:infuse) // to find all the items I want to get rid of one way or another
```

I'm curious to see if other people might find this useful.

**Comment by bhollis** [comment]
You can now do this!
