### ISSUE TITLE
User Defined Item Type Ordering

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#267]
Users would like to do away with the current grouping if items and instead rely upon a user defined order of types and categories, as well as choosing which type should be shown on screen.

**Comment by kyleshay** [comment]
one consideration for this is moving the vault fill counts to the top in the fixed bar under the vault section (similar to how intellect/discipline/strength is now under the characters)

**Comment by kyleshay** [comment]
with collapsable sections, i don't think that we need to implement this. we're following the order (mostly) of how it's displayed in game. haven't heard anyone with this ask in a while. can reopen if we want to add it in.
