### ISSUE TITLE
Weekly account progress items are missing

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#2673]
Current beta.

On the progress page, the weekly account progress, showing which faction engrams are available, is missing and just shows 0.

![image](https://user-images.githubusercontent.com/25425159/37084101-85b849da-2241-11e8-8dc2-3eb5e8ac9cfc.png)

**Comment by duckmanBR** [comment]
Same thing happening here.
Hey @bhollis, looks like something was missing on #2670.

**Comment by bhollis** [comment]
Sorry about that, still getting used to the React conditional rendering idioms.
