### ISSUE TITLE
Underlines showing where they weren't previously in filters

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#2674]
In the filters, all of the filter targets are now underlined.

![image](https://user-images.githubusercontent.com/25425159/37084212-cd0bcc6c-2241-11e8-8762-91510849d720.png)

**Comment by duckmanBR** [comment]
This was caused by #2648 (on src/scss/_style.scss).
/cc @bhollis

**Comment by bhollis** [comment]
Yeah, this is why I don't like those global styles. I took out the underline for now.
