### ISSUE TITLE
Nightfall challenge cards show 100%

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#2675]
This is probably related to how the new progress emblems were showing, but the nightfall challenge card shows a green border on the top and has 100% on the icon.

![image](https://user-images.githubusercontent.com/25425159/37086255-07ba1f6c-2247-11e8-8086-9a0f31c65bb6.png)

**Comment by duckmanBR** [comment]
That's not the only problem with the challenge card.  Somehow Singe descriptions are all wrong.

**Comment by bhollis** [comment]
Oh interesting, I don't have one of those. I can tweak the logic for "complete" - in this case it has both an integer and a regular objective, and I hadn't seen that before.

**Comment by duckmanBR** [comment]
Yeah, you need to finish a Prestige Nightfall to get this one.

**Comment by duckmanBR** [comment]
![image](https://user-images.githubusercontent.com/32077894/37118255-6c4060b4-2232-11e8-8e59-43dfc7848793.png)
