### ISSUE TITLE
Multi stacks are unsorted

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#2676]
I have 3056 gunsmith parts, but this is showing as 999 / 999 / 56 / 999.

![image](https://user-images.githubusercontent.com/25425159/37086392-5f2c373a-2247-11e8-8081-71869fc397a7.png)

This used to be 999 / 999 / 999 / 56.

If I take the 56 and put them in the vault, and then pull them back it now shows as 999 / 56 / 999 / 999.

![image](https://user-images.githubusercontent.com/25425159/37086586-d2f11b86-2247-11e8-9a51-d8b6fdd0b992.png)

But then if I refresh, it goes back to 999 / 999 / 56 /999.

**Comment by duckmanBR** [comment]
I only have 2 stacks of gunsmith, and have no idea on how they used to be, but this may be caused by #2672, that (if I'm not mistaken) changed how dim sees stacks, so we probably need to review how we order them.

**Comment by bhollis** [comment]
I think we just need to add an amount sort to itemSort in dimAngularFilters. They're unsorted now because they were always unsorted, they just happened to fall in the correct order.
