### ISSUE TITLE
Settings Page Content Blank

### ISSUE THREAD

**Issue by Qwikly1** [DestinyItemManager/DIM#2677]
Using Beta Page.  Received update request at approximately 1300 on 7 Mar 18.  Went ahead and refreshed page as normal.  Upon refresh, I went to Settings page to load previous days config for Armor sets.  Attached is what I saw.

Attempted to reload page for rest of evening thru 1130 today EST.  Still receive same Settings page as attached image.
![settings](https://user-images.githubusercontent.com/37187781/37162988-a732f802-22c4-11e8-88f6-6db9a5e073f4.PNG)

**Comment by duckmanBR** [comment]
Reproduced.
Can't debug right now, but tried to look our last commits without luck.
My best guess is that one of the changes in dimStoreItem broke the fake items we create.

**Comment by Qwikly1** [comment]
Thanks Brother,

Just good to know it wasn't a fever-hazed induced D2 dream I was having!

Jim
