### ISSUE TITLE
The "Glory to the Emperor" emblem is showing a progress stat and bar which don't make sense for this emblem.

### ISSUE THREAD

**Issue by sB0bP0sVJp** [DestinyItemManager/DIM#2678]
Hi there, the "Glory to the Emperor" emblem is showing a '75%' number in the lower-left corner and the  details view seems to have a progress bar. 
That emblem tracks the number of Prestige Raid completions, and the progress % and bar don't make sense to me.

**Comment by ericleone** [comment]
![image](https://user-images.githubusercontent.com/297690/37190899-8f5fc06e-232a-11e8-9933-cc3367c0bb83.png)
75% is correct since the last 25% appears to be Prestige Eater of Worlds Lair that is not available until May.

**Comment by duckmanBR** [comment]
Thank's @ericleone.  We also have to check how to correctly format that date/time...
