### ISSUE TITLE
Quick presets

### ISSUE THREAD

**Issue by dheif** [DestinyItemManager/DIM#268]
Have the ability to quickly select "Consumables" from the main UI. Could be displayed as an hard-coded list of consumables, or configurable (like a speed dial UI).

Idea from /u/Rooksarii

**Comment by kyleshay** [comment]
i like that. user defined quick dial: heavy ammo, relic iron, etc.

maybe keyboard 1 - 9 could be mapped 

hit 1 to transfer heavy ammo, then popup appears/hit a/s/d to send it to char 1/2/3

linking: #399

**Comment by kyleshay** [comment]
closing in favor of #967, as it provides this solution while you're farming.
