### ISSUE TITLE
Gunsmith engram icon is broken

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#2683]
If you click through the "engrams available" on the Progress page for the Gunsmith you get this:

![image](https://user-images.githubusercontent.com/25425159/37237255-1a0b68b2-2461-11e8-8a33-8f3811dfd671.png)

I've checked all the others, and their engram icons are correct.  It's just the gunsmith.

**Comment by duckmanBR** [comment]
Like it's said on the top of the page, this feature is still a preview.  Not only on DIM side, the API is still not fully done.
But since gunsmith is not a faction per se, it may be a bug on our side.

**Comment by bhollis** [comment]
https://github.com/Bungie-net/api/issues/442
