### ISSUE TITLE
is:dupelower highlights 'Inventory' items

### ISSUE THREAD

**Issue by joshhunt** [DestinyItemManager/DIM#2684]
I use a combination of is:dupelower and the 'transfer search' functionality to clean up all my dupes after a session.

Recently, is:dupelower has started highlighting items other than weapons and armour, like shaders, consumables, and reputation items. This isnt really desired as once you transfer the search all the extra junk would come with you.

As 'lower' only makes sense in the context of weapons and gear, I would suggest that the is:dupelower only highlights them.

**Comment by delphiactual** [comment]
`is:dupelower is:equipment not:emotes`
