### ISSUE TITLE
Chrome Canary no longer works with DIM

### ISSUE THREAD

**Issue by Max9R** [DestinyItemManager/DIM#2686]
Hi there, 

I typically use Chrome Canary for my gaming related browsing and Chrome for everything else.  Recently DIM quit working with it.  Being Canary is in development, I expect to have issues but though I would let you know. The issue started a few weeks back, and now I keep getting the following:

Error Loading Destiny Info:
Error while reading the zip file:
Reload to retry.

Anyone have any ideas?  I've tried clearing the cache, history etc... deleted basically everything in the browser, no success.

Thanks!

**Comment by duckmanBR** [comment]
Could you try beta.destinyitemmanager.com?
You probably will get the same error, but there we may get more info.

Also, could you please check if there is any error message on console (F12)?

**Comment by Max9R** [comment]
Hi there, 

Below is what I'm seeing for errors:

setting IndexedDBStorage Object
console.js:35 Using WASM SQLite
console.js:35 Manifest loading error Object Error while reading zip file.
t.(anonymous function) @ console.js:35
console.js:35 Error: Error while reading zip file.
    at manifest-service.ts:118 "Possibly unhandled rejection: {}"
t.(anonymous function) @ console.js:35

Thanks!

**Comment by bhollis** [comment]
If Canary isn't working, that usually means Canary has a bug.

**Comment by bhollis** [comment]
I downloaded Canary and don't have any problem with it. Must have been a bug on their side. It's called "Canary" because it's supposed to be the first indicator that they've broken something ;-)
