### ISSUE TITLE
Collections - Community Ratings on Exotics

### ISSUE THREAD

**Issue by peabeu** [DestinyItemManager/DIM#2688]
Can you show the community rating on the exotics displayed on the Collections page. I dismantled almost all exotics to make room for armour. I recently deleted a lot of the planetary armour as its easy now to get back. So i have space to purchase exotics again from my vault collection. Having the community rating will make it easier and cheaper to decide which to get. Thanks

**Comment by bhollis** [comment]
Absolutely, we intend to have this!
