### ISSUE TITLE
"Transfer search" functionality to transfer legendary mods to vault is not working

### ISSUE THREAD

**Issue by kohum** [DestinyItemManager/DIM#2691]
- Search "is:modifications is:legendary"
- Click on Vault emblem and click on Transfer search "is:legendary is:modifications"
- I see success message but the items are not moved.

![dim_search_loadout_bug](https://user-images.githubusercontent.com/6478196/37553535-d91331b8-2a2e-11e8-9188-1aa22505c2f4.gif)

**Comment by bhollis** [comment]
Hmm, there must be something more complicated going on, because this works for me. What version of DIM Beta do you have?

**Comment by kohum** [comment]
Version 4.43.0.1911 (beta), built on 3/18/2018, 1:37:54 PM

I tried it with both chrome and firefox. Still having the same issue.  I am not using the plugin.  I am going directly to the website - https://beta.destinyitemmanager.com

**Comment by kohum** [comment]
Also, it seems like it's only with mods.  The search move seems to work fine for weapons and armor.

**Comment by delphiactual** [comment]
Your mods are at 48/50

**Comment by bhollis** [comment]
I'd expect it to move two more mods though, if that were the case.

**Comment by bhollis** [comment]
No, even then, he's moving them to the vault.

@kohum just FYI, all the extension does is open the website in a tab, it's no different.

**Comment by bhollis** [comment]
So, it should be able to transfer up to 200 mods to the vault (assuming it doesn't run out of total space, in which case you'll get a red popup).

**Comment by bhollis** [comment]
I've tried a bunch of things but still can't quite reproduce this. I wonder if there's a miscalculation and it's getting confused because you have more than 200 individual mods, not 200 *stacks* of mods? Could that be it?

**Comment by bhollis** [comment]
I don't think that's it.

@kohum the popup says it moved 51 items. Do you have 51 stacks of purple mods, or 55?

**Comment by bhollis** [comment]
OK I figured it out. It's actually a bug I'd fixed earlier for the "gather reputation items" loadout.

The basic semantics of loadouts are for regular loadouts. So when you add three "three of coins" to a loadout (the original use case for stackables), it'll make sure you have *at least* three on the destination. But if you already have three or more, it doesn't have anything to do!

The problem with the search loadout is that it wasn't adding up the stacks correctly, so it would have more than one stack of the item (in different places) but only try to move one of them, and when it did that, it'd see that there was already enough moved. The solution is the same as for the other bugs - add up all stacks ahead of time, so you're always requesting the full amount.

**Comment by kohum** [comment]
Hey sorry, I was away from my computer and only saw your questions now.   Glad you figured it out :)
