### ISSUE TITLE
Search autocomplete does not suggest ":=" syntax

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#2692]
The basepower filter has lost it's equals comparison.

This is no longer a valid filter - basepower:=330

![image](https://user-images.githubusercontent.com/25425159/37557408-067182b6-2a54-11e8-99ce-9b3f18d083cd.png)

The power: filter still works.

**Comment by bhollis** [comment]
I’m not sure that ever worked, equals was always “basepower:330”

**Comment by philkernick** [comment]
That's strange.  Because power:=330 works.  And stack:=3 works.

Maybe I'd assumed that the equals operator worked on all the numerical filters.  And if for some reason it doesn't, can it please be implemented.

**Comment by bhollis** [comment]
Ah, I see what it is. The autocomplete doesn't show it (for anything), but the underlying code does support it. "basepower:=330" works for me.
