### ISSUE TITLE
Collections Improvements

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#2706]
- [ ] Armor shows Resilience, Mobility & Recovery on a 100 point bar graph instead of 5.
![screenshot 2018-03-18 18 47 09](https://user-images.githubusercontent.com/4798491/37573399-22e2dbd2-2add-11e8-83cc-b764e199c969.png)
- [ ] Classified Items Show up as belonging to Titans.
![screenshot 2018-03-18 18 51 44](https://user-images.githubusercontent.com/4798491/37573440-9060ce1c-2add-11e8-8233-867ddb450b88.png)

**Comment by bhollis** [comment]
The first one is basically a Bungie API bug. I'll look at the second one...
