### ISSUE TITLE
Searching Specific Perks Only Working When Perk Is Selected

### ISSUE THREAD

**Issue by kcsn-kh52** [DestinyItemManager/DIM#2708]
Searching for a specific perk in the search bar only works if the item both has the perk you are searching for AND that perk is currently selected.  For example, if you have High-Caliber Rounds currently selected on your Uriel's Gift instead of Steady Rounds and you search "Steady Rounds" in the search bar - Uriel's Gift won't come up with your search even though it does indeed have Steady Rounds.

**Comment by bhollis** [comment]
Good catch. Pretty sure it's always been this way.
