### ISSUE TITLE
does clearing cookies delete loadouts, etc?

### ISSUE THREAD

**Issue by githubDemoAccount-SD** [DestinyItemManager/DIM#2709]
so... I logged into DIM today (after about a week away from D2), and ALL my metadata is gone (tagging, loadouts, settings ...everything)

I remember that I cleared ALL cookies earlier today, due to another browser issue I was encountering

Did the clearing of my cache cause me to lose all my DIM info? Or is this coincidental?

If it's the former, I know there's nothing you can do while a user clears his cookies, but within the app you should consider adding a warning somewhere in the settings not to clear ALL cookies

**Comment by bhollis** [comment]
Clearing cookies shouldn't, but clearing ALL data, including IndexedDB will clear them, unless you have GDrive set up.

I'm not sure where we'd put a warning to not delete your browser data... in settings?

**Comment by bhollis** [comment]
I *am* planning on adding a warning whenever you haven't set up GDrive.

**Comment by githubDemoAccount-SD** [comment]
it's weird. All of my loadouts, labels, etc are gone, but I *do* have "GOOGLE DRIVE  ENABLED" [see screencap]. Is it Enabled by default? (cuz I wouldn't have _disabled_ it)

The screencap shows "52 items with tags or notes" because I re-tagged them

It also says "0 loadouts" - _that's_ the thing I'm really bummed about

![screen shot 2018-03-20 at 9 10 24 am](https://user-images.githubusercontent.com/25690089/37656588-d7430b00-2c1e-11e8-86f4-f4cdd7badfbf.png)

**Comment by githubDemoAccount-SD** [comment]
I'm stumped... I even restored ~/Library/Application Support/Google/Chrome/Default/IndexedDBhttps_app.destinyitemmanager.com_0.indexeddb.*_ from a backup and the loadouts are still missing. 

Anything else I should try before simply rebuilding them manually?

**Comment by bhollis** [comment]
There’s a problem we haven’t figured out where all storage gets erased. I’m working on a tool that’ll at least let you restore from an older version of tge Google Drive data, since I don’t know what’s happening.

**Comment by githubDemoAccount-SD** [comment]
ok sounds great. Will I hear of this tool's availability by monitoring this issue? If not, what should I monitor please? (Twitter, Release Notes, etc)

**Comment by bhollis** [comment]
Here, release notes, twitter, the works.

**Comment by philkernick** [comment]
Just noted that with the latest beta all of my GDrive data is gone.

**Comment by bhollis** [comment]
I’m sorry to hear that - there’s definitely a bug but I haven’t been able to find it. It’s not related to releases of the app though. I don’t know what triggers it.

**Comment by bhollis** [comment]
I can’t rule out that GDrive itself is losing the data...

**Comment by bhollis** [comment]
Rolling this into a bigger tracking issue #2713.

**Comment by bhollis** [comment]
The tool is available in Beta - it'll be in the main app on Sunday.
