### ISSUE TITLE
SyncService / Google Drive can lose data

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#2713]
This is a meta-issue covering some of the persistent problems I've been seeing with the Sync service, specifically around Google Drive storage. We've seen that there are some cases where the storage systems can lose all your data, and that is awful, but we don't yet know what could be going on. This issue is to help track the various parts of that problem and attempted solutions.

* [x] Until we can figure out what's going on and fix it, we need a tool that can restore state from previous revisions. The GDrive API allows this, so it should be pretty straightforward.
* [ ] We have a check for empty data, but it's pretty simple. We should beef it up to look for other kinds of empty response. One theory is that the GDrive API is returning an error response that gets passed back as if it were our data.
* [ ] Another theory is that when there's an error retrieving Google Drive data, and Local Storage has been emptied, we still enable and set the Google Drive data. We should consider disabling the adapter for `set` if we can't `get`, and making sure the fallback logic to create the file can't overwrite an existing file.
* [ ] There may be race conditions where we overwrite loaded data with smaller payloads (like just settings). We need to audit everywhere that could happen.
* [ ] We should build a testing harness that can save and load data in various states until it breaks. That could help with the number one problem fixing this, which is that it can't be easily reproduced, so it's hard to find the bugs or verify that they're fixed.
* [ ] We don't ever expire the local cache for sync'ed data - so after it's been loaded it never gets reloaded, only saved. We should put a TTL on that cache, but only after the other problems have been solved (otherwise we'll load too frequently and trigger the other bugs often.
* [ ] We should figure out a conflict resolution process that can help resolve the case when two storage adapters have different views of data. So far this hasn't seemed to be too important, because it solves the problem of two clients updating data at once, and there are lots of other problems before we get there.
* [ ] GDrive has an annoying API and may actually be causing some of the problems on their side. The GDrive API JavaScript client also blocks loading DIM fairly frequently. We should think of rewriting our own client based on directly using the REST API and handling our own auth.
* [ ] We should also look at other storage solutions like Firebase, which costs money but may be a lot more reliable.

**Comment by delphiactual** [comment]
https://www.npmjs.com/package/react-native-google-drive-api-wrapper

**Comment by sdholden** [comment]
Still have this issue both on my phone and samsung table, where I click 'login to google drive', get a pop-up and click OK, then...nothing.  Phone is running Android 6.0 (kernel 3.18.19) and table is running 7.1.1 (kernel 3.10.49-12562000) Oct 1, 2017 security patch.  Been this way for about a year.

**Comment by sdholden** [comment]
Still cannot login to google drive on 3 separate android devices.  Over a year now this bug has plagued me.

**Comment by delphiactual** [comment]
Do you have something possibly blocking cookies?

From Discord
```
Found out why it wasn't letting me set up sync with Google Drive. I had to enable all third party cookies in Chrome. Usually it's set to block all third party cookies. I noticed in the address bar the icon that says the web page was prevented from setting cookies, so I set up an exception but it didn't go away. Enabling third party cookies removed the icon and allowed me to set up Drive sync.
```

**Comment by michabbb** [comment]
@bhollis for me personally it´s very important to get the gdrive sync running on mobile, but i cannot find the word "mobile" anywhere here, so i just wanted to mention that in case it has been overlooked ;)

**Comment by perierat** [comment]
Just wanted to mention that I've been having problems with this for some time and assumed that it was related to two tracker blockers I use (Cookie Autodelete and Privacy Badger).  I've had some time to test and configure things and reached the conclusion that even once whitelisted, these weren't the source of the problem.  Testing builtin Chrome settings showed that the default settings for blocking 3rd party access to cookies was the source of the problem and could be mitigated by adding destinyitemmanager.com and google.com to the "Allow" list.

![image](https://user-images.githubusercontent.com/12759445/41190765-fdd5e3e0-6be4-11e8-8da1-7d45e796cfad.png)

**Comment by michabbb** [comment]
@perierat you made my day 😁👍that's the reason Google drive sync did not work all the time on my android chrome. For everybody else, who does not want to allow 3rd party cookies: just use a different browser for Chrome, where you don't care about tracking, because u use that browser only for DIM

**Comment by delphiactual** [comment]
https://github.com/takamin/gdrive-fs/

**Comment by mistral13** [comment]
I thinke it could help if the devs add more info about the google drive connection in the „DEVELOPER DIAGNOSTICS“

**Comment by delphiactual** [comment]
or possibly https://github.com/sheetbase/sheets-server

**Comment by bhollis** [comment]
This is obsoleted by #4418.
