### ISSUE TITLE
If inventory is full, attempt transfer, and if successful, refresh inventory state.

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#272]
User has a full inventory.  They delete an item in the game to free up a slot in their inventory.
User attempts to move an item in DIM but get an error message that inventory is full.

We should, in this case, attempt the transfer, and if it fails, then show the message.  If it is successful, refresh inventory state.

**Comment by bhollis** [comment]
This was fixed in #367.
