### ISSUE TITLE
Loadouts should treat D2 items as fungible

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#2729]
Loadouts always refer to specific instances of items. However, if we detect that you no longer have that item, in D2 we should just silently grab another copy of the item if possible (breaking ties using the dupelower algorithm). Since items always have the same roll, this should keep the integrity of your loadout over time.

**Comment by duckmanBR** [comment]
Same roll, but not same perks selected, so we should at least mark the loadout or put a toaster up to inform the user that something changed.
At least until AWA is available to us, then we could make loadouts change perks...

**Comment by bhollis** [comment]
We should definitely give a popup when we do this. I figured that we'd swap automatically (and notify) when the loadout is applied, and when the loadout is edited we could swap and highlight the swapped items. Same perks would be great but we don't save that and I'd rather have a matching item than none at all.

A side bit of this is that if we apply a loadout and one of the items is missing, and we can't replace it, we should alert on that too.

**Comment by duckmanBR** [comment]
Agree on the "better a different one than none", but we should add to the warning message something like "the perks on the new item may be different from the original item"
And when AWA is available we must save perks to apply them.

**Comment by delphiactual** [comment]
Should we change this to be (year1 || not:randomrolls) items only?

**Comment by Wh1rledPeas** [comment]
> Should we change this to be (year1 || not:randomrolls) items only?

I don't think so. Every time I get a new drop, I'm always evaluating which perks I prefer and I play with them and compare them on my character in-game. When I'm done, I have the item(s) configured in what I feel are the best configurations for each, then I discard or infuse as is appropriate.

I do this on almost every drop, so my Loadouts will change often until I have mostly the perks I want. This especially applies to armor. I keep different armor sets configured with perks based on my play style. For example, my Gambit armor is stacked with perks that apply to the weapons and play style I normally use in Gambit. My Iron Banner armor is stacked to support my crucible play style. Etc... So when a piece of armor is replaced by the same piece with different perks, I would definitely want it swapped.

**Comment by bhollis** [comment]
Yeah, I think we should have a picker/compare UI for selecting replacements.
