### ISSUE TITLE
DIM stuck "Authorizing..." on my ios devices

### ISSUE THREAD

**Issue by dannyc211** [DestinyItemManager/DIM#2735]
I've tried everything from clearing all history and cache to changing browsers. However, every time I try to login to DIM it asks me to Authorize with Bungie.net then it just takes me to a white screen that says "Authorizing..." and nothing happens. 
I tried this on both my iPhone 7 and my iPad Pro. They both end up stuck in the same place. The thing is i can pick up any other ios device and everything works fine. 
Please any help would be greatly appreciated. Its very frustrating not being able to use DIM and stuck with the Destiny App.

![safari](https://user-images.githubusercontent.com/32078316/38339298-61d860f8-3822-11e8-8edc-5e58beee80c4.png)

![chrome](https://user-images.githubusercontent.com/32078316/38339292-5cc51386-3822-11e8-8c8e-dd5102405aa5.png)

![image](https://user-images.githubusercontent.com/32078316/38339252-32def17c-3822-11e8-95ea-12f50e93b6dc.png)

**Comment by bhollis** [comment]
What version of iOS are these devices running?

**Comment by dannyc211** [comment]
Both ios9 and ios10



-----Original Message-----

**Comment by bhollis** [comment]
Hmm, both are pretty old. Do you know exactly which iOS 10 version it is? I think we only support 10.1 and later or something like that. 

-Ben

**Comment by dannyc211** [comment]
They were both working perfectly fine up to last month when all of a sudden it stopped. The iOS 10 version is 10.1.1

**Comment by bhollis** [comment]
Gotcha. As we upgrade the libraries and tools we use, older OSes will drop off support. I’ll try this out this weekend and see if there’s something simple we can fix.

**Comment by dannyc211** [comment]
Thank you so much!!

**Comment by dannyc211** [comment]
Thank you so much! Working on ios10! Will check the iPad when I get home! Thank you again

**Comment by bhollis** [comment]
No problem. We will be dropping support for those older iOS soon though, so I’d recommend upgrading to at least 10.3.

**Comment by dannyc211** [comment]
Yea, I'm waiting for a new Jailbreak to be released so I may upgrade both. I'm kinda stuck until then. I will enjoy as long as I can. Thanks again!
