### ISSUE TITLE
Setting to disable auto refresh.

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#274]

**Comment by jflayhart** [comment]
why?

**Comment by jflayhart** [comment]
Maybe a on/off toggle? Want to be careful before we have more settings than we know what to do with.

**Comment by SunburnedGoose** [comment]
Data Caps, User Choice, Performance.

**Comment by kyleshay** [comment]
closing issue, if we want to add this check out the work that's already been done in #324
