### ISSUE TITLE
Moving mods from postmaster doesn't work correctly

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#2744]
Note: This almost certainly applies to shaders and anything else that is account based and not character based.

If I move a mod from the postmaster on my **current** character, the logic says "move the mod to the character".  This works as expected.

If I move a mod from the postmaster on any other character this is not my current character, the logic says "move the mod to the character that has it, then move the mod to the vault, then move the mod to the current character".  This actually works, but shows an error because DIM lost the location of the mod.  The act of moving the mod to the character that has it is enough as it is account based.

**Comment by philkernick** [comment]
I knew when I wrote it that I wasn't explaining it very well, so I'd done a screen recording.

https://drive.google.com/file/d/1UoTiVgLL-a60xKg75DVQmYevTebiLs69/view

When I transfer the arc mod from the hunter (currently logged on) post-office it works as expected.

When I transfer the arc mod from the warlock (not logged on) post-office it shows a "looks like you tried to transfer more of this item than exist" error.  After refreshing you can see that the transfer did work.  It's the error that's wrong.

This happens every time you try to transfer a mod from the post-office of a not logged on character.

**Comment by philkernick** [comment]
Here's another version of the same thing.

https://drive.google.com/file/d/1yWbetmsQE2AIFylK2Fzk1hOJDS3Y06ds/view

I try to move the impact absorption mod from the warlock (not logged in) post-office.  DIM shows that the mod has been put into the vault and shows an "item not found" error.  If I refresh you can see that the mod really went to the character.

**Comment by bhollis** [comment]
Thanks. I think I have a fix (it's not what I originally thought!) but I'll need to get some mods to test.
