### ISSUE TITLE
Add message to notify Vault is full

### ISSUE THREAD

**Issue by andradei** [DestinyItemManager/DIM#2747]
As of _Version 4.47.0 (release), built on 4/8/2018, 11:07:49 PM_, when user requests a transfer to a full Vault, an item gets transferred from the Vault into inventory so a slot is freed for the transfer to work.

This is confusing if you don't realize Vault is full. So a notification would be nice.

**Comment by duckmanBR** [comment]
Yeah, that's something that is on our to-do list.  The thing is, if we do for vault we should do for every bucket, and then things get a little complicated on how to show this to the user...

**Comment by bhollis** [comment]
This behavior has actually been part of DIM for many years :-)

**Comment by andradei** [comment]
I just gave it a try, and made sure I reset all notifications and messages that I chose to hide. There are no messages that say an item had to be transferred into a character's inventory to make room in the Vault.

**Comment by bhollis** [comment]
Sorry, I miscommunicated. The message is not there. The behavior of moving things aside has been there forever.

**Comment by kyleshay** [comment]
We're starting to shy away from using toast messages. we highlight the vault count in red when the vault is full. We don't want to spam users as many people have full vaults and this message would be fired often.
