### ISSUE TITLE
Show class on the armor items

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#275]
Lots of new items in the game. Hard to remember if an armor part is for a hunter or for a warlock.... 

Not sure exactly where we would like to put this. Somewhere on the move dialog? Should it be text, an icon?

## Example

Maybe we could remove the INT: DIS: STR: stuff and instead show the class there, since we now have the stat information available on the item?

### Before
![before](http://i.imgur.com/GNfsFvR.png)

### After
![after](http://i.imgur.com/1A2QUES.png)

**Comment by dheif** [comment]
Where did the Def go? :)

**Comment by kyleshay** [comment]
Interesting, great eye. We actually have a bug in master that means... Light level is actually mistakenly labeled as DEF

**Comment by kyleshay** [comment]
Also *facepalm* `DEF` isn't even a thing... it's `Discipline`, haha.

**Comment by SunburnedGoose** [comment]
Light Level is the average of the attack and defense.

**Comment by SunburnedGoose** [comment]
Also the DEF on the icon is not guaranteed.  Need to show it on the popup somewhere.

**Comment by kyleshay** [comment]
Good point. Should still show it on the header bar, for those who don't always expand the dialog to see the detailed stats?

**Comment by SunburnedGoose** [comment]
I would.  Just double line it

**Comment by dheif** [comment]
I would as well.

**Comment by 1ricca** [comment]
Nice one. That's perfect. Redundant info cleaned up as a bonus. Good eye ;P
