### ISSUE TITLE
Enhance is:dupe to show blue/purple mods as the same

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#2755]
It would be very useful to be able to answer the question: "which blue mods do I also have purple mods for?"

**is:dupe** doesn't tell me, as a blue kinetic munition loader chest mod is different from a purple kinetic munition loader chest mod.  I'm suggesting enhancing is:dupe so that blues and purples show as the same for mods.

If this can work, then is:dupelower could be used to show the blues for which you already have purples.

If that really isn't feasible given the way it's currently coded, then can we have an is:moddupe filter (or something like it).

**Comment by philkernick** [comment]
Is there something that we can take out of the image from the tooltip?

This is the purple:
![image](https://user-images.githubusercontent.com/25425159/38850697-ad517cac-4251-11e8-903f-bb58b91f3fdc.png)

This is the blue:
![image](https://user-images.githubusercontent.com/25425159/38850716-c4f2ac14-4251-11e8-90cb-9cc407542dfc.png)

In both cases the icon in the tooltip is the blue version.

**Comment by philkernick** [comment]
What about root.perks[0].perkHash?  This is identical for the blue/purple versions.

It's really a questions as to whether is:dupe should remain a check of identical hashes, or whether it should be relaxed to consider identical perks.  Same as #2737

**Comment by kyleshay** [comment]
no more blue/purple variants, closing for now
