### ISSUE TITLE
Allow tags and notes on mods, shaders and consumables

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#2757]
It isn't possible to put tags on account based items - mods / shaders / consumables.

**Comment by duckmanBR** [comment]
On D2, DIM only let the user tag items that can be locked, and the "can be locked" comes from the API.

**Comment by bhollis** [comment]
In general we haven't let you tag any item that doesn't have an instance (so, most stackable items) because we track the tag by instance ID.

**Comment by kyleshay** [comment]
https://github.com/DestinyItemManager/DIM/pull/5497
