### ISSUE TITLE
Suggestion: Include ratings in CSV export

### ISSUE THREAD

**Issue by JTF195** [DestinyItemManager/DIM#2758]
Preferably all combinations of platform and game mode at once, but at least the currently selected combination.

Semi-related, it would also be nice if we could somehow view/export historical ratings after they've been cleared for a new patch.

**Comment by duckmanBR** [comment]
Improving the CSV content is on my list, and the rating was one of the things I wanted to add.

But I believe it won't be possible to add all the combinations. The same for the historical rating.

**Comment by JTF195** [comment]
Will it still be possible to export the various combinations separately with multiple exports?

**Comment by duckmanBR** [comment]
Yes. Change the setting and export it again.

**Comment by JTF195** [comment]
Some additional suggestions that probably don't warrant their own issue:

An option to export equipment the player does not own. (a full data dump, basically)

Min and max stat ranges are still relevant for D1 and may be coming to D2 eventually. Can they be exported? (Separately?)

Both of these would help with "massive breakdown"-style theorycrafting

**Comment by 48klocs** [comment]
Exporting ratings + rating count is in. I have no interest in building for historical data (but we welcome PRs with it) and I kind of don't see it fitting in with what DIM normally does?

If you want other things added to the spreadsheet, please add separate issues for each of those.
