### ISSUE TITLE
Filtering broken in dev

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#277]
Commit 6e90672d9ce8e3d7a122780f57eaa88c8b976334 broke filtering.

**Comment by SunburnedGoose** [comment]
Yeah. I'm still working on it. Quick eye :)

**Comment by SunburnedGoose** [comment]
Still trying to reduce the number of watchers on items. We're at ~9k right
now, and I can get it down to 3k.

**Comment by SunburnedGoose** [comment]
I removed the binding to visibility at the moment. I'm working on the
ability to turn the watchers on and off based on when we need them.

**Comment by bhollis** [comment]
Sounds great!

-Ben
