### ISSUE TITLE
"Restore Old Versions" reporting current state regardless of file age

### ISSUE THREAD

**Issue by bhjohnny** [DestinyItemManager/DIM#2770]
This might be connected to issue #2713.

I accidentally set all my tags to "Infuse". Upon discovering my mistake I went to Settings>DIM Storage>Google Drive>Restore Old Versions to load a previous state. Clicking "Restore" shows a message saying the action was successful, but no changes are made. In fact, every revision shows the same "X# of load outs. XXX# of items with tags" values regardless of age.

Steps to reproduce:

1. Check the number of tags reported in "Restore Old Versions"
2. Add a new tag to a new item
3. All versions show same number of tagged items

**Comment by bhollis** [comment]
Wow, great catch! This was completely broken. I went ahead and fixed it.
