### ISSUE TITLE
D1 DIM Beta: Transfer function returning error "item needs a 'sort' field"

### ISSUE THREAD

**Issue by fitzyface** [DestinyItemManager/DIM#2774]
In the Version 4.49.1.2024 (beta), built on 27/04/2018, 04:21:52 transferring an item returns an error "item needs a 'sort' field" as seen in the clip below. 

Thank you very much for looking into this!
![dim beta transfer error](https://user-images.githubusercontent.com/37505704/39353899-477c86aa-4a09-11e8-8677-8f4f7d42656a.gif)

**Comment by duckmanBR** [comment]
Working on D2

**Comment by fitzyface** [comment]
My pardon, I should have been more specific.

**Comment by duckmanBR** [comment]
Don't worry.  You were.  On subject and screenshot!
My comment was only to make it clear that this bug is affecting **_only_** D1 (as some of DIM code is used for both versions)
