### ISSUE TITLE
Mobility / Resilience / Recovery not showing anymore

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#2775]
The mobility / resilience / recovery stats that are normally shown under the character emblem are all blank at the moment.  If you hover over one of them (for example mobility on my Hunter) it says 5 / undefined.

![image](https://user-images.githubusercontent.com/25425159/39371408-c2888020-4a80-11e8-8fc3-218a491435f9.png)

**Comment by duckmanBR** [comment]
may be related to #2772 (cc: @delphiactual )

**Comment by duckmanBR** [comment]
You're right, but for some reason it only trigger the error on your commit.  If I checkout to the typepocalypse from @bhollis , everything is "fine".

But yeah, the typepocalypse is the culprit , sorry.
