### ISSUE TITLE
DIM desktop app

### ISSUE THREAD

**Issue by lukefx** [DestinyItemManager/DIM#278]
Only an idea...but with Electron (aka Atom shell) we can wrap the current app and have a desktop, multi platform app. The only problem will be the authentication...

https://github.com/atom/electron

**Comment by bhollis** [comment]
I actually got pretty far down this path a couple months ago, but got distracted...

**Comment by bhollis** [comment]
This'll hopefully be done in v4. Closing this issue until we're closer to that.

**Comment by SunburnedGoose** [comment]
Want a bucket to put content I find about running apps in electron.  Keep this in the beyond v4 milestone.

**Comment by delphiactual** [comment]
Don't know if this helps, but https://www.xplatform.rocks/2016/07/02/using-augury-inside-of-your-electron-apps/

**Comment by SunburnedGoose** [comment]
That's pretty interesting. Interesting how they are able to get the dev tools to start in electron.

**Comment by delphiactual** [comment]
https://github.com/zalmoxisus/crossbuilder

**Comment by bhollis** [comment]
Closing in favor of web strategy.
