### ISSUE TITLE
D1 Activities: Skull Hash

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#2788]
![spomsbu8](https://user-images.githubusercontent.com/4798491/39557022-e01d65b4-4e41-11e8-952d-fb6740e7ae80.jpg)
Sentry issue: [DIM-198](https://sentry.io/destiny-item-manager/dim/issues/530106048/)
Should also probably not make the call to sentry.io from app.destinyitemmanager,com
This only appears to affect languages other than english.

**Comment by delphiactual** [comment]
Sentry issue: [DIM-198](https://sentry.io/destiny-item-manager/dim/issues/530106048/)

**Comment by delphiactual** [comment]
Should also probably not make the call to sentry.io from app.destinyitemmanager,com

**Comment by bhollis** [comment]
Ah, the sentry.io thing is from the CSP reporter. Probably should serve a different `.htaccess` file for prod.
