### ISSUE TITLE
Feature - Filter by Light/Level of Armor and Weapons

### ISSUE THREAD

**Issue by Denifia** [DestinyItemManager/DIM#279]
I am wanting to add a filter to the search function so that I can find all my weapons and armor by its "light" level (aka, primary stat).

I was thinking the following filters:
* "light:250" finds all armor and weapons with primary stat of 250
* "level:250" does the same thing as above
* "light:=250" does the same thing as above
* "light:>250" finds all armor and weapons with primary stat GREATER than 250
* "light:<250" finds all armor and weapons with primary stat LOWER than 250

I can add >= and <= as well. No issue there.

So, I wanted to know, will anyone else use this feature? Has this already been accounted for (I couldn't see it in the list of issues)? Is there anything else you'd add? Does the filter look OK?

I already have a working prototype working but haven't uploaded the code yet. The filter currently works with other filters using AND like the existing filters.

* "light:>280 is:arc" works just fine. Filters out armor but that is expected.

**Comment by kyleshay** [comment]
Filter syntax looks great. May as well throw in the >= and <= just for completeness. 

One thing to note is check out the filter button in DIM. 

If you click on the 'filter by name' a popup comes up to allow user input. Could be a nice place to add the number input for people used to filtering by the modal.

With v4, we'll be re-working the filter UI, but for now what you've suggested is perfect.

Thanks for creating the issue ticket, we did not have one and I don't think anyone else has touched that code recently. 

Personally I'm really excited for the feature and will use it all the time!! :D

**Comment by Denifia** [comment]
Perfect. I'll finish up the code and have the PR in by the end of the weekend. I don't need to touch a lot of code so it should be a small one :)

**Comment by Denifia** [comment]
During testing I realised I can do this to find a set of weapons in a range.
* is:arc light:<=200 light:=>150


Added description and examples to the Filters popup. When selected, it asks for a light value and populates the search box.

PR incoming soon.

**Comment by SunburnedGoose** [comment]
Did you do a null check on the prompt results?

**Comment by kyleshay** [comment]
added that in my 'tweaks' branch.
