### ISSUE TITLE
Add Tyra Karn To Vendors Screen (For Drang Info)

### ISSUE THREAD

**Issue by jamieisboss** [DestinyItemManager/DIM#2796]
Not necessarily as a new block, tweaking Rahool would be just as useful. 

Whatever the simplest implementation is, It'd just be nice to be able to see what level Drang is being sold at the way we can for the MIDA Mini-Tool and Man 'o War

**Comment by bhollis** [comment]
As far as I can tell, she isn't available in the API once you get to the tower (spoilers?).

**Comment by bhollis** [comment]
https://github.com/Bungie-net/api/issues/481
