### ISSUE TITLE
Hide PS4-exclusive gear from Collection tab

### ISSUE THREAD

**Issue by tyresoflaherty** [DestinyItemManager/DIM#2797]
Borealis shows up in my Exotic collection for my Xbox One account. 

Can we hide Borealis for Xbox/PC accounts for the time being? Thanks!

**Comment by bhollis** [comment]
Thanks for bringing it up. We won't taunt you anymore.

**Comment by tyresoflaherty** [comment]
**Thank you!!!** Now can you figure out how I can get Polaris Lance? ;)
