### ISSUE TITLE
Infusion Calculator enhancements

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#280]
Two asks from users at reddit:

> In addition, can the infusion UI show which items are locked and which aren't? I keep infusion-fodder unlocked so that'd be an easy way for me to see which things I'm willing to part with.

For that, maybe we could add a checkbox on the infuse UI to show/hide locked items.

> The calculator only shows possible infusible items that are on the same character the calculator was opened on.

A way to see all infusible items across characters and the vault.

Tasks:

- [x] Verify math with community
- [x] Add a checkbox for view all your items, even in vault
- [x] Show/hide locked items
- [x] Use math.round instead of math.ceil, it's the correct way
- [x] Ghost and artifact infusion icons do not show the infuse icon, but the blue circle is there and is still functional.

Infuse v3 features:
- [ ] Dialog won't close when you click outside of it. Right now, you must click the X button
- [x] Show 'locked' icon on items that are locked in the infuse window.
- [ ] Calculate "best upgrade path" (take checkboxes into account, eg. if show locked items are checked, include the locked items in the best upgrade path) [code here](https://www.reddit.com/r/DestinyTheGame/comments/3n6pox/python_infusion_calculator/) will calculate:       
* Best light with least marks
* Least marks with best light

**Comment by lukefx** [comment]
Can you assign this issue to me? I want to do a checklist and keep this issue open for future improvements.

**Comment by kyleshay** [comment]
I'll get that set up.

one other thing: https://github.com/DestinyItemManager/DIM/pull/260/files#diff-5481d33a4b271866be8c233f05dd1316R29

**Comment by kyleshay** [comment]
more information:

https://www.reddit.com/r/DestinyTheGame/comments/3nzbr1/dim_v3112_new_infusion_calculator/cvspkqn

 > the infusion calculator is somewhat off when it comes to infusing legendaries and exotics. The community believes legendaries will infuse at least the difference up to 6 and exotics, 4. DIM believes this is value is 6 for both rarities.

**Comment by kyleshay** [comment]
https://www.reddit.com/r/DestinyTheGame/comments/3n6pox/python_infusion_calculator/

seems to be the most reliable source.

**Comment by kyleshay** [comment]
updated maths to what's in the python calculator in v3.1.12.1

**Comment by lukefx** [comment]
Added with eccc5bc

![infusion_3](https://cloud.githubusercontent.com/assets/28878/10387479/f96f178c-6e61-11e5-9043-aef98169a179.gif)

**Comment by kyleshay** [comment]
amazing work luke! could you address the icon not showing up for ghosts/icons?

we can save

     Dialog won't close when you click outside of it. Right now, you must click the X button

for another time.

**Comment by SunburnedGoose** [comment]
There is a directive for this. Something like click anywhere else.

**Comment by lukefx** [comment]
> There is a directive for this. Something like click anywhere else.

yepp but we can't use it, some code explanation will follow :) the problem is that I remove some items from the view and the dialog will close everytime you want to infuse a gear

**Comment by SunburnedGoose** [comment]
Probably because the items have code to close all dialogs on click. Need to
add a signal to root scope to know that the item is in a dialog and
shouldn't try to close all.

**Comment by lukefx** [comment]
The solution could be much more simple...using
$(event.target).parents(".ngdialog") will find if the item is in a
dialog...otherwise we ha clicked out a dialog.

**Comment by SunburnedGoose** [comment]
There ya go :) ship it.

**Comment by kyleshay** [comment]
@SunburnedGoose what's involved with adding the blue popup modal? 

we've "beta" tested the feature with users on reddit, but a typical user is transparent to the updates. Once infusion is right where we want it to be (and passed the reddit test) I want to post a small gif that shows people how to access/use it that's linked inside the 'click to never show again' toaster

**Comment by SunburnedGoose** [comment]
Code is commented out in app.config.js. Just change the cookie name.

**Comment by kyleshay** [comment]
sweeeet. thanks. ^__^

@lukefx ... I wonder if we should display the locked icon on the weapon since we have the toggle there.

@SunburnedGoose there is a toggle to lock/unlock items right? Maybe that's something we could consider adding in the future so that the calculator is easier to use (they have something locked, but still want to use it in the calculator, but not see ALL locked items...) lower priority. Maybe i'll create an issue ticket for it.

**Comment by Mulchman** [comment]
http://bungienetplatform.wikia.com/wiki/SetItemLockState

**Comment by geck0s** [comment]
I would recommend caution about having DIM lock/unlock items, I don't want a mis-click to unlock something that I meant to keep because one of the perks that isn't in the item compare window.  

Also, there are two calculation discrepancies reported on Reddit, possibly because of the rounding method still being Math.ceil in DIM/app/scripts/infuse/dimInfuse.factory.js ?
https://www.reddit.com/r/DestinyTheGame/comments/3o48e2/infusion_data_collection_request/cvu9w22
https://www.reddit.com/r/DestinyTheGame/comments/3o48e2/infusion_data_collection_request/cvu8hs5

**Comment by kyleshay** [comment]
correct @geck0s . I'm going to go ahead an push a fix for that shortly. I'll then eventually take the PR from @lukefx, but I really want to get that fix out asap.

**Comment by kyleshay** [comment]
I just pushed the bugfix to the production build. now that the calculator math is correct, i'll take a look at the v2 infusion version and some of the other PR's so that we can push 3.1.13 - just wanted to get that out to maintain credibility with the tool.

**Comment by lukefx** [comment]
> I just pushed the bugfix to the production build. Now that the calculator math is correct, i'll take a look at @lukefx v2 infusion version, and some of the other PR's so that we can push 3.1.13 - just wanted to get that out asap to maintain credibility with the tool.

I created the infusion_v2 pull request to keep the work there but, to speed up the development, can I commit directly to dev?

**Comment by kyleshay** [comment]
Hey @lukefx we like to try and keep dev a a sort of 'staging' environment. For most of the changes that I even personally make: I create a branch, test the changes, and then make a PR. This way if we ever needed to go to master with DEV, we can be sure we have everything tested and ready for the master push.

**Comment by kyleshay** [comment]
Creating a new infusion issue, since this one has been mostly implemented.
