### ISSUE TITLE
Broken since new release

### ISSUE THREAD

**Issue by cliffaddy** [DestinyItemManager/DIM#2800]
DIM was working after Warmind went live, but as soon as the newest DIM release went live it broke ...

![image](https://user-images.githubusercontent.com/39105619/39787845-6c188c8a-52f5-11e8-8c41-12fc429b348f.png)

On Chrome and Firefox, multiple different accounts, on MacOS.

**Comment by wein3967** [comment]
Try signing into each of your characters (in-game) and then re-launch DIM. This is what worked for me.

**Comment by cliffaddy** [comment]
That did it, thank you!
