### ISSUE TITLE
Can't see Progress section with Mozilla Firefox

### ISSUE THREAD

**Issue by Adnan008** [DestinyItemManager/DIM#2801]
when i click progress section with mozilla firefox 59 nothing happens, it opening like its gonna load in few seconds, then blank. im using opera 52 just for this. i have this issue about 2 weeks.
Tried turning on browsers safe mode on, logging out and in, clearing cache, disabling privacy protection, nothing works
using x64 win 8.1 and firefox

**Comment by duckmanBR** [comment]
But only the progress page is blank? The rest of DIM works?
Could you check if there's any error on console? (F12 to open the window then refresh the page just to be sure).
Also looks like Firefox released 60.0 yesterday, could you check if the problem persists?

**Comment by Adnan008** [comment]
yes only progress wasn't working even i updated mozilla to 60, i fixed it tho, it was giving "RangeError: invalid language tag:  main-b60b40.js:1:413788" error, i remembered i deleted language selection on my browser so i set it to turkish and english, it fixed.
still, i haven't encoured any errors with language with any website except this progress page

**Comment by duckmanBR** [comment]
Yeah, that's the culprit.  We use the browser language to format the values right.
But I didn't understand, you removed all languages from the browser language selection?

/cc @bhollis

**Comment by Adnan008** [comment]
yes i removed all languages because when i use vpn i want to use that country's language, so far i had no problem with languages removed, but why **only** progress page gives error?

**Comment by delphiactual** [comment]
https://github.com/DestinyItemManager/DIM/blob/master/src/app/progress/milestone.tsx#L291
