### ISSUE TITLE
Masterworks doesn't work since Warmind update

### ISSUE THREAD

**Issue by Adnan008** [DestinyItemManager/DIM#2802]
there isn't to tell about, like title say i cant see which of my weapons are masterworks since warmind update, otherwise its working fine (except firefox mozilla issue)

**Comment by bhollis** [comment]
A fair bit changed around sockets and plugs. I haven’t had a chance to download Warmind but maybe somebody else could poke into it soon?

**Comment by duckmanBR** [comment]
At first I believe the problem is only on Bungie side.  The API isn't the correct state for those MW items (as stated on Bungie-net/api#469).
