### ISSUE TITLE
New - Vendors Seasonal Reputation 

### ISSUE THREAD

**Issue by duckmanBR** [DestinyItemManager/DIM#2805]
With season 3, looks like Bungie created a new "Seasonal Reputation" on Vendors, that's not what we're displaying on the progress page.

Have no further info other than some tweets about it.

**Comment by bhollis** [comment]
Nice. I released a new version of the API bindings that include that stuff but havent had a chance to start using them.

**Comment by bhollis** [comment]
I checked through and currently no vendor has a seasonal rank associated with it. May be a bug.
