### ISSUE TITLE
DIM Storage is not displayed correctly

### ISSUE THREAD

**Issue by QuixoticWolf** [DestinyItemManager/DIM#2820]
Using FF 60 x64 and Win10, DIM doesn't display correctly the amount of storage used in GDrive
![clipboard image](https://user-images.githubusercontent.com/6894845/40015206-1d28f574-5778-11e8-989f-321f9e6ac63b.jpg)

**Comment by bhollis** [comment]
I couldn't reproduce this on macOS, but I at least added some code that'll protect against a bad storage estimate.
