### ISSUE TITLE
Opera Support

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#2822]
Any reason to flag Opera as an unsupported browser?  A player reports that they can use it with DIM.

https://twitter.com/XiaoLin555/status/996228481125056512

**Comment by bhollis** [comment]
Shouldn't be a reason. It's basically just Chrome, back a few versions.

**Comment by bhollis** [comment]
(Also I'm not going to install it just to debug things)

**Comment by bhollis** [comment]
Oh, actually, we declare Opera support, and have for a while. Looks like browserslist is just out of date with what the most recent Opera version is.

**Comment by bhollis** [comment]
I pushed a change that should recognize newer versions of Opera again.
