### ISSUE TITLE
DIM won't load in Firefox

### ISSUE THREAD

**Issue by dxkota** [DestinyItemManager/DIM#2826]
DIM will load fine on Google Chrome, but will not load in Firefox even after starting in safe mode, incognito, clearing cache/cookies.
Firefox Safe Mode
![firefox safe mode](https://user-images.githubusercontent.com/37290527/40152166-20971e8a-5952-11e8-8104-39ee7cecac7f.png)
Firefox Regular
![firefox normal](https://user-images.githubusercontent.com/37290527/40152167-20a79fa8-5952-11e8-89f3-6a71951a8a4e.png)

**Comment by duckmanBR** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

![image](https://user-images.githubusercontent.com/32077894/40178885-2a8770f4-59b9-11e8-8fdc-3663a78a78ed.png)
Got this on `shift+f2` (developer toolbar) and command `security csp`

/cc @bhollis

**Comment by bhollis** [comment]
The CSP warnings are unrelated. The issue is that IndexedDB isn’t working, but I don’t see enough details to know what’s happening. Do you have enough free disk space?

**Comment by dxkota** [comment]
Yes almost 100gb free on the drive Firefox is installed it.

**Comment by dxkota** [comment]
I know it was previously allowed. I cleared up some more stuff off my drive and refreshed Firefox again and DIM seemed to start working again. Thank you for all the help.
