### ISSUE TITLE
Loadouts don't show on first click

### ISSUE THREAD

**Issue by byamj** [DestinyItemManager/DIM#2827]
When clicking on the arrow on the right side of my character emblem, the dropdown appears but my created loadouts don't populate. When I click off the menu to hide it, then toggle the dropdown again my loadouts are present. 

STR: 
1. Create a loadout
2. Reload the page
3. Click down arrow on character emblem to toggle dropdown menu
4. Observe missing loadout
5. Hide dropdown menu by clicking elsewhere on the page
6. Click down arrow on character emblem to toggle dropdown menu again
7. Observe previously created loadout

**Comment by bhollis** [comment]
Thanks for the report. I just pushed a fix to beta.
