### ISSUE TITLE
Challenges associated with heroic strikes playlist

### ISSUE THREAD

**Issue by joshminnie** [DestinyItemManager/DIM#2828]
I'm not sure if the API makes this possible, but would it be possible to show the current challenges for the heroic strikes under the Progress tab with their challenges?

Right now, the only way to see the challenges is to drop into the strike or if the **Strike Challenges** is an active milestone for the day. This means I may end up having to change my loadout at the _beginning_ of the strike, rather than before while I'm still flying in.

Here's a little mockup of what I was hoping for, if it's possible:

![heroic-strike-challenges](https://user-images.githubusercontent.com/117469/40251915-a5d3288a-5aa8-11e8-9780-890f99a35ea8.png)

**Comment by bhollis** [comment]
Filed https://github.com/Bungie-net/api/issues/490 on behalf of the API.
