### ISSUE TITLE
DIM does not work on Android Tab. 

### ISSUE THREAD

**Issue by HeavyD1710** [DestinyItemManager/DIM#2829]
Hello, DIM does not work on my Android Tab! Is coming constantly only the circle. It works on my laptop. Why is that?

**Comment by duckmanBR** [comment]
Could be a lot of things.
Are you using chrome? what version? and the android version?

**Comment by HeavyD1710** [comment]
Galaxy Tab S2 7.0
Chrome 66.0.3359.158

**Comment by HeavyD1710** [comment]
15Gb and 1,5GB ram.
