### ISSUE TITLE
Crucible Rank value incorrect

### ISSUE THREAD

**Issue by peabeu** [DestinyItemManager/DIM#2844]
Minor bug. The visual rank suggests I am close to my next rank up level. However the numbers would suggest that I am already over the required rank up mark of 300. My rank is displayed as 327/300. See attached image
![rank](https://user-images.githubusercontent.com/34254703/40345876-44e2738a-5dde-11e8-9bf6-41f9056beb67.png)

**Comment by bhollis** [comment]
Whoops, I bet I know what that is. I haven’t made it that far myself...

**Comment by bhollis** [comment]
Fixed in beta!

**Comment by peabeu** [comment]
Thanks
