### ISSUE TITLE
cannot change equipped weapon of characters

### ISSUE THREAD

**Issue by armando1793** [DestinyItemManager/DIM#2847]
When changing the loadout of characters you are not logged in to, the api gives an error 

> Bungie.net servers are down for maintenance

This may be a bug with bungie's api but I'm filing this here to be sure! :)

**Comment by wein3967** [comment]
Bungie recently "turned off" the ability to change equipped item(s) outside of the game. You can transfer items, weapons, armor, etc., but you can't equip or de-equip anything. This effects all 3rd party managers and Bungie.net.
