### ISSUE TITLE
ratings at vendor page not visible

### ISSUE THREAD

**Issue by michabbb** [DestinyItemManager/DIM#2849]
page: `/d2/vendors`

![25-05-2018-07-32-09](https://user-images.githubusercontent.com/3524595/40558019-51237b14-6052-11e8-9afb-e0d6b157878d.png)

**Comment by bhollis** [comment]
@48klocs any ideas? Could be due to your recent changes or mine.

**Comment by 48klocs** [comment]
Weird - reviews are being loaded, we’re just failing to render the component. 

I’ll be back home Monday night to take a peek.

**Comment by michabbb** [comment]
fix confirmed
