### ISSUE TITLE
Item details for swords messed up

### ISSUE THREAD

**Issue by vincchan** [DestinyItemManager/DIM#285]
I was working on a feature that I'm about to make a PR for but I noticed this 

<img width="466" alt="image 2015-10-09 at 8 32 39 pm" src="https://cloud.githubusercontent.com/assets/868272/10402468/e1851e64-6ec5-11e5-92b5-132645030e51.png">

It's only affecting swords and it's happening not only in my branch. Could somebody verify if this is happening for them as well? Not sure if I'm just too dumb to clear caches though...

**Comment by kyleshay** [comment]
This is why:

https://github.com/DestinyItemManager/DIM/blob/dev/app/scripts/services/dimStoreService.factory.js#L327

We're not loading the stat names from a JSON file created from the bungie manifest as we should be. If we were to load from the manifest file... any new stats created by bungie will automatically populate on the move popups.

Thanks for the report. Definitely something we need.
