### ISSUE TITLE
Include kiosk unlocks in vendor checkmarks

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#2850]
Vendors should show ownership with the green check mark instead of highlighting the item... (e.g. Xur inventory)

![Screenshot_20180525-191310](https://user-images.githubusercontent.com/4798491/54875475-ac87fc80-4dc5-11e9-82a1-ba9bb04ff3c6.png)

**Comment by bhollis** [comment]
Hmm, I'm not sure what you're suggesting. In that screenshot I see two things:

1. All four of Xur's items are purchase-able, and thus are lit.
2. Two of those items are currently owned by you, so they have a green check mark.

**Comment by delphiactual** [comment]
I own 3 of those items

**Comment by bhollis** [comment]
Not sure what that's about. We literally go through every item in your inventory on all characters + vault and collect that into a set, then check it to see what you have.

**Comment by delphiactual** [comment]
Its because green check mark means I have it somewhere in my inventory, and lit up means I have acquired it on the collections page. The Foetracer is the item in question ...

![screenshot 2018-05-26 06 27 16](https://user-images.githubusercontent.com/4798491/40576098-1a9db3fa-60ae-11e8-9bbb-69ce6dd72936.png)

**Comment by bhollis** [comment]
That’s right- we indicate tgat you can get something with it being lit, and green check for inventory. Are you suggesting that we consider items that are available from kiosks to be part of your inventory for the purpose of the green check? I suppose that’s possible, though it means the definition of the check would be different on different pages. Perhaps we need a different icon for when you actually have it vs it just being in the kiosk?

**Comment by delphiactual** [comment]
I am because if i look at Xur without verifying what is in the kiosk I could potentially be buying something that I have already unlocked. We could use the check mark with a tealish background ala Prismatic Matrix to show what is unlocked but not in inventory.

**Comment by delphiactual** [comment]
![Screenshot from 2019-03-23 23-35-34](https://user-images.githubusercontent.com/4798491/54875426-bceba780-4dc4-11e9-973b-cd524fdaf328.png)
![Screenshot from 2019-03-23 23-35-47](https://user-images.githubusercontent.com/4798491/54875427-bf4e0180-4dc4-11e9-9242-d5fea2afcc92.png)

In DIM, at a glance I cannot tell that I already have unlocked `Gemini Jesters`.

**Comment by bhollis** [comment]
That's right, just need to include the collections data. Just haven't gotten around to it.
