### ISSUE TITLE
Filter to find items below basepower

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#2854]
While grinding the levelling up process a key test is "are there any items that could be infused by random blue drops?"

The way to test this is to note your current basepower, then look for any items where power < basepower.

In my case, my Titan is basepower = 362.8, so blue drops will be 357.  I have a class item that is 356+5, so it's possible to get a drop that will raise this to 357+5.

However on my Warlock basepower = 364.4 and Hunter is 362.7.  The point is that the basepower is different for each character.

This can be done manually with power:<362 or power:<364, but I'm suggesting a filter that does it across all characters so I can answer the question "what should I go and grind blue drops to upgrade".

I suggest a filter either like **power:<max**
or if that's difficult because those filters only take numerical arguments, then like **is:upgradeable** (to be similar to the filters for D1).

**Comment by duckmanBR** [comment]
I just couldn't understand if your goal is to show for each character what would be grindable items.
Because on your hunter a 363 item wouldn't be grindable, but on your warlock it would be.
That I believe it wouldn't be possible.
Or I'm seeing too much and you just want to see items below you max basepower on all chars?

**Comment by philkernick** [comment]
My original thought is that it would be:
  (is:titan && power:<362) || (is:warlock && power:<364) || (is:hunter && power:<362)

While I understand that the filter logic that you can enter in the search box doesn't support an OR operator, I didn't know if it was possible in the construction of an internal filter.  Ref #2668 

If OR is impossible in any context, then the filter could be (assuming Titan is current):
  is:incurrentchar power:<362

It would still have to determine the maxbasepower for the currentchar and use this.

This answers the "what do I grind for, at least on my current character" question.

Abstracting it one step further, given there already is an is:incurrentchar filter, then all we really need is the power:<max where max = maxbasepower of currentchar.

**Comment by stephenross** [comment]
Would you want weapons to use the basepower of the character that they are currently on, or the character with the highest to check for upgrading in the scenario where you can return results for all of them?

**Comment by philkernick** [comment]
For weapons it would make most sense to use the highest basepower, since they are transferable.
