### ISSUE TITLE
DIM not loading in iOS 10.3

### ISSUE THREAD

**Issue by martyn05** [DestinyItemManager/DIM#2858]
When Destiny update 1.2.1 was deployed, all 3rd party apps stopped working for a short while but the following day they were ok. Every time I try to load DIM in Safari on my iPad it fails to load, it says my browser is not supported or too old. I use DIM a lot when I play Destiny 2 and would really like to carry on using it. Tried it on the wires iPad and same result. It works on my iPhone and iMac.

Any ideas on how to fix it ? Many thanks in advance.

**Comment by SunburnedGoose** [comment]
Need to be on iOS 11.

**Comment by martyn05** [comment]
The iPad is up to date but its only on IOS 10.3.3.there are no further updates for it.  It was working fine before Tuesday's update so has DIM been changed ? Thanks for the reply.

**Comment by philkernick** [comment]
Up to last week DIM worked on iOS 9.3.3.  Now it doesn't.  I assume some component change in the back-end stopped it working.

**Comment by martyn05** [comment]
Maybe there will be a fix so it can be used on pre IOS 11 devices because I am not buying a new iPad just to use DIM, other 3rd party apps work but I liked the way DIM was laid out, easy to use.

**Comment by bhollis** [comment]
The actual requirement is iOS 10.3 or newer. We announced the change on Twitter a week or so ago. 

If it’s not working on iOS 10.3 we can get that fixed.

**Comment by martyn05** [comment]
@bhollis Thanks for the reply. I play Destiny 2 every evening and always use DIM on my iPad, I have other apps but I prefer DIM. Like I said earlier, my iPad is on IOS 10.3.3 so if you could fix it then that would be awesome. May I ask how long it will take to sort out ? Many thanks.

**Comment by bhollis** [comment]
Probably will be fixed by Sunday, if we can figure out a fix.

**Comment by martyn05** [comment]
@bhollis Many thanks for your help and support

**Comment by hacks78** [comment]
I have the same problem with the best app for destiny (DIM), in iPad with iOS 10.3.3 Firefox, Crhome and safari 😭

**Comment by bhollis** [comment]
This has been fixed in Beta and will go out to app tonight.

**Comment by martyn05** [comment]
All working now, thank you so much.
