### ISSUE TITLE
Search for Exotics with Catalyst objectives.

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#2859]
Players are asking for the ability to search for these specific exotics that have work that needs to be done to them to advance the objective and earn the catalyst for Masterworks.

I thought maybe is:exotic has:objective would be an option.

![image](https://user-images.githubusercontent.com/984608/40801725-47ca3266-64d9-11e8-9252-6a18ef6c190e.png)

**Comment by bhollis** [comment]
The weird part is that the plug has an objective, not the item.

**Comment by doktor5000** [comment]
On a related note, would also be nice to have a filter or another kind of way to display collected catalysts

**Comment by bhollis** [comment]
This is especially tricky because catalysts don't have a special item category - they're just "Mods"

**Comment by duckmanBR** [comment]
Until we get a this working, the workaround to search for items with just the catalyst or "masterwork in progress" is to use `is:exotic not:masterwork upgrade` where as the `upgrade` is a text search, so it should be localized.

**Comment by bhollis** [comment]
Does the display we have on the Collections page satisfy this need?

**Comment by doktor5000** [comment]
@bhollis Sure, it also satisfies the original issue BTW ;)
