### ISSUE TITLE
Use DIM without enabling ALL 3rd party cookies?

### ISSUE THREAD

**Issue by sdholden** [DestinyItemManager/DIM#2867]
Hi All.  Any way to get DIM to work (firefox 60) without having to allow ALL 3rd party cookies?  Have tried allowing the site (https://app.destinyitemmanager.com/*) but only alowing 3rd party cookies 'always' will let it function.  Really don't want to leave 3rd party enabled....any workaround?

**Comment by bhollis** [comment]
You’ll want to enable cookies for bungie.net too
