### ISSUE TITLE
Images won't load

### ISSUE THREAD

**Issue by lonhok** [DestinyItemManager/DIM#2869]
When I sign in to DIM the icons for all weapons and vendors never load. This happens on both home PCs as well as mobile.  Not sure what my deal is!
![image](https://user-images.githubusercontent.com/29546337/41123442-e5fcaf68-6a5b-11e8-9306-cf279d1eb751.png)

**Comment by duckmanBR** [comment]
On mobile, it happens when you are on 3/4g and wifi?
If you go to destinysets.com (on desktop) the icons load or the same thing happens?

**Comment by lonhok** [comment]
Loads on 4g. So I'm assuming network issue?

**Comment by lonhok** [comment]
Destiny Sets does load.
[image: image.png]

**Comment by duckmanBR** [comment]
Yes, my bet is something on your network.

Check for any error messages on the browser console (usually F12) and send them to us.
