### ISSUE TITLE
Sleeper Simulant Icon

### ISSUE THREAD

**Issue by v-fedorov** [DestinyItemManager/DIM#287]
Not going to have time until tomorrow to make a PR but in case you get around to it before i do.

itemHash `3774437926` has the same icon that the sleeper simulant uses,
http://www.bungie.net/common/destiny_content/icons/9be72c64fdd81ccd068e766365cd38c6.jpg

But it might get patched back into the manifest any minute now so who know if its worth updating :)

**Comment by kyleshay** [comment]
wow. nice find. how on earth did you come across that?

**Comment by v-fedorov** [comment]
I did a bunch of datamining before the quest opened up. I also have the talentNodeHash but im not sure if it matters since the api isnt returning the nodes
