### ISSUE TITLE
iPad layout needs optimization

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#2872]
From this Twitter thread: https://twitter.com/Do_Not_Argue/status/1005835943054635009

Looks like our iPad layout is not as optimized as our phone portrait layout is, especially if people change the item size. We should figure out how to auto-scale the items to the perfect size for iPad (portrait and landscape) the same way we do for phone. I'm open to making iPad portrait be single-character.

**Comment by duckmanBR** [comment]
Have no idea if it's possible, but maybe a layout with all 3 characters on a page/column and vault on the other?

And don't forget that we don't auto-scale items on landscape mode...  We actually even don't do it when portrait.  We just check the width of the window.  And increasing this check to include the iPad size (have no idea on how much we would need) may have side effects for desktop users...

**Comment by kyleshay** [comment]
think between the 2 item unequipped column and single character modes, we're good here? unless we wanted to detect device and set defaults?

**Comment by bhollis** [comment]
Yeah I think the idea would be to set defaults / enforce some choices
