### ISSUE TITLE
Can't log out for the purpose of logging back in?

### ISSUE THREAD

**Issue by twotrident** [DestinyItemManager/DIM#2873]
Am I dumb or is the button for logging out completely absent from my settings menu?

Screenshots of both the app.destinyitemmanager.com screen and my Settings menu:
> https://imgur.com/a/AqkAAJb

**Comment by bhollis** [comment]
Hmm, it's supposed to be up here: 
<img width="160" alt="screen shot 2018-06-10 at 10 54 11 pm" src="https://user-images.githubusercontent.com/313208/41214655-41b0ba50-6d01-11e8-9106-e313d3d77e2a.png">

But I bet you're having trouble fetching the list of accounts in the first place. I'll think on it, but I bet I can make it so the log out button is still there. It's weird though - most login issues should automatically log you out. Can you open developer tools and see if there are any errors in there that might have any more information you can expand?

**Comment by twotrident** [comment]
Is this what you wanted to see?
![destinyitemmanager4developertools](https://user-images.githubusercontent.com/26743855/41216617-578632d6-6d12-11e8-9517-34784710771c.JPG)

**Comment by bhollis** [comment]
Thanks! It looks like you have an ad blocker or something that is blocking our calls to bungie.net.
