### ISSUE TITLE
Duplicate Curse of Osiris Milestones

### ISSUE THREAD

**Issue by bresnick** [DestinyItemManager/DIM#2874]
On the progress page, I see the Curse of Osiris milestone twice. The same does not happen for Warmind milestones on another character.

![image](https://user-images.githubusercontent.com/16613510/41209362-0347a8b2-6cf9-11e8-966b-b12ceddc3f82.png)

**Comment by bhollis** [comment]
https://github.com/Bungie-net/api/issues/539
