### ISSUE TITLE
Can't drag items out of the postmaster to the vault (or other characters)

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#2875]
This is a general limitation we put in because the item move logic isn't quite smart enough to pull from postmaster then follow up with the correct move. We should fix that!

**Comment by kyleshay** [comment]
I just tried this and it seems to have worked?!

The first time I tried it was on dev, and it hard crash dim... I tried it with an item on stable and it worked.

**Comment by bhollis** [comment]
Right, the bug is that you can only drag to same character, not directly to vault or another character.

**Comment by delphiactual** [comment]
Closed by #3685
