### ISSUE TITLE
Popup won't show up

### ISSUE THREAD

**Issue by SvenNold** [DestinyItemManager/DIM#2876]
It seems Popup is no longer loading/showing. So you cannot tag and see details anymore.

On console it shows:

sql-wasm-0edda1.js:28 POST https://sentry.io/api/279673/csp-report/?sentry_key=1367619d45da481b8148dd345c1a1330 403 (FORBIDDEN)

angular.js:14940 
TypeError: Function.prototype.bind.apply(...) is not a constructor
    at Object.instantiate (angular.js:5101)
    at angular.js:11097
    at ngDialog.js:645
    at angular.js:17318
    at angular.js:17366
    at c.$digest (angular.js:18478)
    at c.$apply (angular.js:18867)
    at HTMLDivElement.<anonymous> (angular.js:28028)
    at Re (angular.js:3795)
    at HTMLDivElement.n (angular.js:3783) "Possibly unhandled rejection: {}"

( 
{ua: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWeb…ML, like Gecko) Chrome/67.0.3396.79 Safari/537.36", browser: {…}, engine: {…}, os: {…}, device: {…}, …}
browser
:
{name: "Chrome", version: "67.0.3396.79", major: "67"}
cpu
:
{architecture: "amd64"}
device
:
{vendor: undefined, model: undefined, type: undefined}
engine
:
{name: "WebKit", version: "537.36"}
os
:
{name: "Windows", version: "10"}
ua
:
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.79 Safari/537.36"
)

**Comment by xmysterymantax** [comment]
I just did a full system cleanup, malware scan, and removed all my cookies, extensions, etc I thought I removed something. I'm glad I saw this!

**Comment by inexorableAce** [comment]
![capture](https://user-images.githubusercontent.com/29002828/41228149-4ffb0572-6d45-11e8-8654-e33bb2c8545d.PNG)
this is the click error when clicking an item.

**Comment by Obzer** [comment]
use old angular version to resolve this

**Comment by bhollis** [comment]
All good now, thanks for reporting.

**Comment by bhollis** [comment]
For reference this was broken in Angular 1.7.1 and theyll release 1.7.2 to fix: https://github.com/angular/angular.js/issues/16594
