### ISSUE TITLE
Item Size slider missing in Edge browser

### ISSUE THREAD

**Issue by wmxp** [DestinyItemManager/DIM#2877]
Been using DIM on the Xbox One built in Edge browser. Very convenient when you need just single moves, as you never need to drop the controller. For whatever reason, the Item Size slider in the DIM settings menu is missing when using the Edge browser. I confirmed the same is true for Edge on Windows 10.  

As a work around, I used the Google Drive option to port my config file from Chrome on PC to Edge but the issue still stands.

**Comment by bhollis** [comment]
Older versions of Edge don’t support the feature (CSS variables) that make that slider work. So we hide the setting on that browser. When you copy over the configs did it actually affect the item size?

**Comment by wmxp** [comment]
![img_20180611_222058](https://user-images.githubusercontent.com/30638431/41271623-7b3a9d70-6dc6-11e8-9b6c-759ac90b3230.jpg)
vs
![img_20180611_222255](https://user-images.githubusercontent.com/30638431/41271627-819932c6-6dc6-11e8-9aca-3724c2ff5284.jpg)

So yes, it affects it considerably.

**Comment by bhollis** [comment]
Interesting. In that case, Edge is just reporting whether or not it supports CSS variables incorrectly.

**Comment by bhollis** [comment]
This should be fixed in Beta now!

**Comment by wmxp** [comment]
Cool beans dude, thanks! :D
