### ISSUE TITLE
When I click an item in Firefox, I no longer see ratings and overview... nothing happens

### ISSUE THREAD

**Issue by DunkelheitVZ** [DestinyItemManager/DIM#2878]
Problem persisting for a few days now

**Comment by bhollis** [comment]
We had a bug yesterday - can you try reloading and see if it works now?

**Comment by diana-lee** [comment]
This was still an issue last night.
Firefox v60.0.2 on Windows 10.

Ratings and overview working as expected on beta DIM.

**Comment by MelonSquid** [comment]
Same here. Problem still is present for me on firefox.

**Comment by bhollis** [comment]
Can you go to "About" and tell me what version of DIM you're on? You should see "Version 4.56.5".

**Comment by diana-lee** [comment]
v4.56.0

I've tried refreshing but there's no change.  I didn't see an option to update on DIM either.

**Comment by 48klocs** [comment]
Try a hard refresh of the page - ctrl + F5 is the combo for Firefox on Windows, Google for the particulars if that doesn't do it.

**Comment by bhollis** [comment]
Firefox seems to have some trouble updating sometimes. Give it a hard refresh like @48klocs says and you'll be good to go.
