### ISSUE TITLE
DIM can't handle Valor rank after passing Legend (but before reset)

### ISSUE THREAD

**Issue by errera** [DestinyItemManager/DIM#2879]
When you cross the 2000 Valor Point barrier, you're offered a reset option; there seems to be a buffer (I wasn't offered the reset after the game that caused me to cross the 2000 point level, but the game after that), and DIM can't handle it.  Screenshot attached.

![crucible_rank_bug](https://user-images.githubusercontent.com/2791571/41451069-f670a934-701f-11e8-84d5-54b739216164.png)

(Issue taken care of as soon as the reset happens.)

**Comment by bhollis** [comment]
What version of DIM are you on? Version 4.56.5? It's shown in the "About" screen.

**Comment by bhollis** [comment]
Gotcha - thought I’d nailed that earlier but looks like there’s another issue.

**Comment by errera** [comment]
To be honest, I only reported it because last time Goose yelled at me for not reporting something. :) The time at which this is active is super-short (literally one game), and most people won't even be looking at DIM in that interval. :)

**Comment by bhollis** [comment]
Should be fixed in Beta in a couple minutes, and in release tonight. Thanks for reporting!
