### ISSUE TITLE
Infusion Calculator GetStores

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#288]
we should refactor the calculator to not get all of the items again each time the checkbox is clicked; more info: https://github.com/DestinyItemManager/DIM/pull/283#discussion_r41704698

also when you click the checkbox, the items are re-populated, even if you've already applied them in your calculation:

![issue](http://i.imgur.com/1FRU4w7.gif)

**Comment by bhollis** [comment]
Fixed in #377.
