### ISSUE TITLE
search: rating not working at vendors view

### ISSUE THREAD

**Issue by michabbb** [DestinyItemManager/DIM#2880]
![15-06-2018-07-09-49](https://user-images.githubusercontent.com/3524595/41480738-ad988aa0-70cf-11e8-8d0b-15528c548f84.png)

**Comment by duckmanBR** [comment]
yeah, it's not implemented yet (#2647)

**Comment by michabbb** [comment]
strange, i am pretty sure that already worked in the past 🤔

**Comment by bhollis** [comment]
It worked in D1 :-)

**Comment by bhollis** [comment]
Closing in favor of #2890.
