### ISSUE TITLE
Improve Subclass node display

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#2888]
If I look at the details of subclass, I get this:

![image](https://user-images.githubusercontent.com/25425159/41513926-b5c00bea-72e1-11e8-8db5-eb048df6ab8a.png)

I can see that the panel is trying to replicate what is seen in game, but...

- There is no background
- There is no detail on the name of the upper and lower trees
- There is no indication of which tree is selected
- There the barricades are in grey, where every other node is blue

**Comment by bhollis** [comment]
Yup, this is the only holdover from the okd talent grid system from D1, and while it’s nice that it sorta works, it isn’t pretty. Unfortunately as far as I can tell this is what we’ve got to work with from the game - no backgrounds, no good data about active nodes, etc. I’d be interested if somebody wanted to submit a PR though.

**Comment by bhollis** [comment]
To be specific, the panel is not "trying" to replicate what's in game - that's actually the talent grid (same structure as the perks in D1!) that gets sent back for the item. It even has all the positioning in there, done up with empty columns and rows.

**Comment by delphiactual** [comment]
https://github.com/Bungie-net/api/issues/787#issuecomment-441337240

**Comment by bhollis** [comment]
Yup, that’s what we’re currently using to
display them.

**Comment by delphiactual** [comment]
Except for activated, hidden, and unlocked.

https://github.com/DestinyItemManager/DIM/blob/master/src/app/inventory/store/d2-item-factory.service.ts#L947-L965

vthorn said (emphasis mine)

> You can then check which nodes are **activated** by checking the "talent grid" properties returned for the item. (Fun fact: subclasses are the only remaining part of the game that uses Talent Grids. In Destiny 1, that was how "perks" on items worked. In Destiny 2, that moved to "Sockets" and Talent Grids were abandoned as a concept by everything except for Subclasses!)

It doesn't appear that we are actually checking the live data and only using the definitions.

**Comment by bhollis** [comment]
Awesome, thanks. I was able to fix this so we show the activated path.
