### ISSUE TITLE
Select character on Vendors page

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#2890]
Right now the Vendors page shows you vendors from the perspective of your active character, but we should allow you to switch characters on this page. See #2647.

**Comment by kyleshay** [comment]
see `src/app/character-select/CharacterSelect.tsx`

**Comment by kyleshay** [comment]
https://github.com/DestinyItemManager/DIM/blob/master/src/app/character-select/CharacterSelect.tsx
