### ISSUE TITLE
unable to open/unzip files within Android tablet.

### ISSUE THREAD

**Issue by Xzelian** [DestinyItemManager/DIM#2903]
I have been using DIM on tablet for some time, however recently I suddenly cannot unzip the current library. for a split second the screen flashes something regarding authorization or browser at the top of the screen, however after giving permission to Bungie.net this no longer happens.
Please note that I am able to use DIM on my computer (which is a desktop and not viable for in game use) via the same Google account, so security should not be an issue.

I have tried exporting from the PC and importing to Tablet the configuration file but did not resolve the issue.
I have also set the tablet back to factory, run all updates and reinstalled both stable and beta versions.
This is game crippling.

**Comment by Xzelian** [comment]
Thank you for your response and I apologize for not including this
information in my original report.
Android version 5
Kernal 3.10.54
Google version: 67.0.3396.87

I will in the meanwhile double check site permission although I do not
think this is the issue.

**Comment by bhollis** [comment]
Can you screenshot the error? Unfortunately from your description it's hard to tell what's going on.
