### ISSUE TITLE
iPad Safari Issues

### ISSUE THREAD

**Issue by wmxp** [DestinyItemManager/DIM#2905]
Two issues.

1) Latest release of DIM, 4.58, is causing browser window lockups for me on Safari iOS (11.1.2), specifically when clicking items where the "amount to move" slider pops up, such as armor mods. The popup opens, but DIM is completely unresponsive after; Safari is still functioning though, and allows me to interact with URL bar, close the window, etc. Issue does not exist when using Firefox on IOS.

*Edit*: Played around with this a bit more, and the lockup happens when clicking outside of the popup window to close it rather than interacting with the box. If I click either the Store or Take buttons, it closes properly and there's no issue. Also, while I said Safari is technically responsive, it does in fact bring the device to a crawl getting to the URL bar to close the tab, like the CPU is chugging hard. Again, this only happens when opening items with the "amount to move slider".

2) A long standing issue for me, though I can't be certain it has anything to do with DIM - Safari loses the Google Drive login within DIM after a certain amount of time. Clicking login within the DIM settings pops up a "failed to authorize" message on the Google splash. Closing safari and dumping all the website data within the IOS storage settings for Safari restores functionality again for a set period, after downloading DIM and signing back into everything.

I do my best to exhaust every possible angle on my end before filing these reports. I could provide a vid clip if needed, as this description is somewhat vague.

*Update* For the record, I actually loath Apple products, but this tablet was a gift so I made the best of it. The reason I use Safari over the other browsers is two fold: 
1) It's the only browser that stays loaded fully in the background while switching apps. I can interact with the Xbox app for instance, shoot a couple messages, then switch back to Safari with DIM, and it's still right where I left it without having to reload the whole site again. 
2) It's the only browser with support for addons/extensions on iOS (sorta)

**Comment by IONready** [comment]
Having the same issues on my iPad Pro. It freezes when you get an _inventory full_  pop-up and sometimes when you view overlays of certain items.

**Comment by bhollis** [comment]
Thanks, we’ll get a fix out before this sunday’s release. This is app.destinyitemmanager.com, not beta, right?

**Comment by IONready** [comment]
I experience it on both the beta and stable release.

**Comment by wmxp** [comment]
It has now been locking up in the same fashion on even ghost shells, so I don't know what to think anymore.

**Comment by bhollis** [comment]
On Beta? It should be fixed there.

**Comment by wmxp** [comment]
Yep, seems to be playing nice now. You're a saint. :)
Any ideas about that loss of Google Drive access? It's working right now, but I assume Safari will crap out again soon.

**Comment by bhollis** [comment]
That’s a separate issue we have tracked. The basics are that Safari has implemented “tracking protection” that breaks Google Drive. We have some options but haven’t had a chance to try them.

**Comment by IONready** [comment]
Still freezing up for me on the beta.

**Comment by bhollis** [comment]
@IONready what exact version do you see when you go to the "About" page?

**Comment by IONready** [comment]
4.58.0.2192

**Comment by bhollis** [comment]
Can you walk through exactly what causes it to lock up?

**Comment by wmxp** [comment]
Yep, you're right. Item comparison still has major issues.

**Comment by IONready** [comment]
Also clicking on the "no more items left to move" message when your vault full also results in a major freeze.

**Comment by bhollis** [comment]
Yup, we’re aware of it, which is what this open issue represents. It’s not a quick or easy fix, but it will be fixed in time.
