### ISSUE TITLE
Sleepers image not found

### ISSUE THREAD

**Issue by vincchan** [DestinyItemManager/DIM#292]
The image path tries to point to bungie instead of loading it from resources.

<img width="844" alt="screen shot 2015-10-11 at 20 31 25" src="https://cloud.githubusercontent.com/assets/868272/10418280/184a7790-7057-11e5-8513-3a27d667e796.png">

**Comment by kyleshay** [comment]
ahhh. shoot. thanks for the report. i'm just going to continue using the default icon for classified images.

**Comment by kyleshay** [comment]
ooook. just pushed an update. if you have a minute to check 3.1.13.1 let me know. I haven't had a chance to grab it yet. :(

**Comment by vincchan** [comment]
@kyleshay Looks good :thumbsup:

**Comment by kyleshay** [comment]
:beer:

**Comment by vincchan** [comment]
@kyleshay oh! maybe I misunderstood you. I pulled it from repo and not from the chrome extension store :O #295
