### ISSUE TITLE
Sorting Collections Tab

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#2920]
The Exotic Collections should be sorted such that they are easier to browse. The weapons should be broken down into: Kinetic, Energy, and Power. The armors should be broken down by class and the sorted by slot.

Ornaments should be sorted the same as armors.

**Comment by bhollis** [comment]
A reasonable request, though it’ll also make the page much taller.

**Comment by delphiactual** [comment]
Maybe we could take some of this from forsaken early
![collections-destiny-2](https://user-images.githubusercontent.com/4798491/42196502-8300b172-7e3b-11e8-893a-ce7843dd2952.png)

**Comment by duckmanBR** [comment]
I believe that for now we could just sort them.  It would improve QoL...

**Comment by bhollis** [comment]
Sure. Right now they’re sorted by name, we could easily change that.
