### ISSUE TITLE
Show postmaster size

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#2921]
We should show the postmaster size and how many items there are in it, like we do for vault.

**Comment by duckmanBR** [comment]
But postmaster are per character.  Going to put that info with mbp/mob/res/rec?

**Comment by bhollis** [comment]
I was thinking of putting it in the postmaster header.

**Comment by inexorableAce** [comment]
In the recent mock up I added these in as sub headers of the post master with counts.
![image](https://user-images.githubusercontent.com/29002828/48809831-45154f80-ecf4-11e8-99f1-4037085fae91.png)
