### ISSUE TITLE
Search for infuse targets

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#2925]
I'm imagining a new search for "infuse targets" - items that are masterworks or modded, and which have duplicates that are higher power. These tend to slip through the cracks of "is:dupelower". Thoughts?

**Comment by duckmanBR** [comment]
I've being using the *Infuse Fuel Finder* a lot for this (even with that annoying #2895 bug).

But then, for this search you should consider not only dupes but also higher power items of the same type (in this case maybe only blues and dupelowers).

**Comment by bhollis** [comment]
This might be just how I do it, but I’m not looking to infuse otger items of tge same type. It’s just an alternate way of handling duplicates. If I want to maximize something’s power I’ll use the infusion fuel finder.
