### ISSUE TITLE
DIM Debug page

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#2926]
I'm thinking of making a "debug page" people can go to in order to help provide info for bug reports. Some ideas for info to show:

1. Whether they can connect to Bungie.net
2. Account info (account ID, platforms, characters)
3. A way for them to copy their access token and send it to us, so we can impersonate them in order to reproduce bugs. I'd probably want to encrypt this with a public key where only certain DIM developers have access to the private key.

Any other bits that'd be useful?

**Comment by duckmanBR** [comment]
Console errors?  Since mobile don't have console it would be the only way to get this info.

**Comment by 48klocs** [comment]
I'd put the pinned message from the Discord #support channel up top on it.

> 1. CTRL+F5 to hard refresh your browser.
> 2. Try incognito mode / private browsing - if this works, you likely have an extension/plugin that is interfering and you need to figure out which it is. Privacy Badger is frequently the culprit.
> 3. Try a different browser.
> 4. If using https://app.destinyitemmanager.com/, try https://beta.destinyitemmanager.com/, and vice versa
> If DIM doesn't work after you try all 4 'fixes', report here with any error messages.

**Comment by liamdawson** [comment]
I've started working on this one 😄
