### ISSUE TITLE
Long delays when trying to compare items on IOS

### ISSUE THREAD

**Issue by stephenwilletts** [DestinyItemManager/DIM#2930]
I have been experiencing long delays of about 20 seconds when attempting to compare items in Safari and Chrome on IOS. I haven't tested any other browsers, so may not be browser specific. 

Steps to reproduce the issue:
- Click on an item (such as a weapon) in character inventory or in the vault
- Click on the 'double square' icon to compare the item with other similar items.

It now takes about 20 seconds to open the item comparison section in the browser.

Interestingly, in Chrome if I select the option to "Request Desktop Site" then there are no delays at all and the comparison section opens quickly.

I think this issue began around DIM version 4.58 and I have seen it in 4.59 and now 4.60 in both Stable and Beta releases.

(Note I'm having no issues with the desktop site on my computer this problem only seems related to mobile site or IOS?)

Any help to resolve this issue is much appreciated. 
Thanks!

**Comment by bhollis** [comment]
Acknowledged, this is only an iOS issue, and only in the landscape mode. Not sure yet how to fix it. Weirdly, in the performance timeline, it says it spends all that time in layout. We may have overconstrained the layout of that panel.

**Comment by stephenwilletts** [comment]
I have seen the delays in portrait mode as well as landscape.

**Comment by mruncieman** [comment]
<a href="https://github.com/DestinyItemManager/DIM/issues/2930" class="u-in-reply-to"></a>I also have this issue on Safari on my iPad, however, Firefox on the iPad doesn't seem to have the issue. The compare sheet comes up immediately.
