### ISSUE TITLE
Transfer search to vault doesn't transfer all items from search result

### ISSUE THREAD

**Issue by kohum** [DestinyItemManager/DIM#2933]
This is happening on the latest Beta version - Version 4.60.0.2205 (beta), built on 7/11/2018, 2:30:26 PM

- Search for "is:modifications is:legendary"
- From vault emblem click Transfer search "is:modifications...
- Only some items are transferred to the vault

**Comment by duckmanBR** [comment]
Question:  The items that aren't being transferred are the ones that you already have an stack on vault?

If yes, the root of the problem is probably the same as #2932.
