### ISSUE TITLE
Help overlay no longer popping up

### ISSUE THREAD

**Issue by 48klocs** [DestinyItemManager/DIM#2938]
A bug report came in from Discord - the angular-hotkeys overlay (that popped up when you hit '?') is no longer working.

**Comment by duckmanBR** [comment]
An user on discord reported that `x` also isn't working.  `f` is and the `shift+number` to change the tag are working.

**Comment by inexorableAce** [comment]
This was asked about again today in discord (x specifically), I presume with the react build if these were angular based they will need to be rebuilt anyway in react?
