### ISSUE TITLE
Completed Exotic Catalysts Not showing in Collection

### ISSUE THREAD

**Issue by errera** [DestinyItemManager/DIM#2948]
Not sure this is actually a bug, but I'm definitely seeing different behavior on my two accounts (Xbox and PS4), mostly due to the timing of catalyst completion. On the Xbox, no Exotic whose catalyst was actually complete when the Catalysts section of the Collections page was added is showing in that list. All I'm seeing on Xbox are Catalysts in progress. On the PS4, on the other hand, I see ALL the Catalysts I've earned, including the one I've finished (which happened AFTER that section was added).

The PS4 screenshot shows ALL the Catalysts I've earned - including D.A.R.C.I., which is now complete.

The Xbox screenshot shows only the incomplete Catalysts - it's missing all of my finished ones (Crimson, D.A.R.C.I., Tractor Cannon, Vigilance Wing, Graviton Lance, Polaris Lance) - all of which were finished before that section was added to DIM.

![ps4_catalysts](https://user-images.githubusercontent.com/2791571/43309526-db8804b0-9139-11e8-9d14-37c14520276e.png)
![xbox_catalysts](https://user-images.githubusercontent.com/2791571/43309527-db9b7c0c-9139-11e8-9ab8-7237e8dd3621.png)

**Comment by errera** [comment]
Followup - looks like it has nothing to do with when the catalysts are finished. Just earned, then completed, the catalyst for Coldheart on the Xbox - as soon as it was done, it disappeared from the list. Seems to be a platform difference, rather than a time one.

**Comment by bhollis** [comment]
I'm gonna chalk this one up to an API issue. I'm sorry we couldn't help more!
