### ISSUE TITLE
3.1.13.1 Missing dependencies

### ISSUE THREAD

**Issue by vincchan** [DestinyItemManager/DIM#295]
@kyleshay  https://www.reddit.com/r/DestinyItemManager/comments/3od7i0/help_the_extension_opens_a_page_with_nothing_on_it/

**Comment by kyleshay** [comment]
thanks for posting it here. had no idea this was happening otherwise. patched. waiting on chrome store to push it out to users...

![oops](http://i.imgur.com/7rqT1.gif)
