### ISSUE TITLE
owned-icon overlay on Collections tab

### ISSUE THREAD

**Issue by caiobrentano** [DestinyItemManager/DIM#2951]
When you inspect an item, on Collections tab, all `owned-icon` are being displayed over the box that opens with item's details.

Noticed the bug on Firefox (61.0.1). On Chrome, it doesn't happen.

**Comment by kkirigaya** [comment]
Just noticed this too, and looked to see if there was an open issue on this (which is yours apparently).

Possible solution: Quickly opening my element inspector shows changing the z-index of `.ngdialog` from `3` to something larger than `10` (which is the z-index of the `.owned-icon` elements), like `20`, puts it above the icons.

**Comment by bhollis** [comment]
Would someone want to make a PR? I suspect adjusting the z-index of the owned-icon would be easier than modifying the popup.
