### ISSUE TITLE
Move all items not included in loadout to vault.

### ISSUE THREAD

**Issue by SahandJ** [DestinyItemManager/DIM#2955]
I have many different loadouts I like to use. Some loadouts are rather large, which forces me to move some items from my character to vault manually so that there is room for the new loadout. 

I'd like to suggest an option that moves all items not included in the loadout to the vault. I would like to do it myself, but I've never worked on a project like this, and I have no idea where to start.

**Comment by delphiactual** [comment]
@0sanity is:inleftchar not:equipped not:shaders not:ghost not:vehicle not:ships not:engrams not:consumables not:modifications could be replaced with is:inleftchar not:equipped is:haspower

**Comment by kyleshay** [comment]
Thanks for reporting - FYI we do have another issue tracking this in #2230
