### ISSUE TITLE
Activity Monitor

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#2959]
I would like DIM to be more aware of what is occurring with my accounts and characters. Having knowledge of the state of the character as they interact with the game opens up new opportunities to react to those changes in ways that the player can automate, or be notified of to take action manually. Activity monitor would operate while the player is online, or offline, in anticipation of the Advanced Write Actions support in the future.  

Examples that could be interesting are:

1. Auto-locking items that drop with preferred perks like Outlaw. 
2. Equipping a ghost or emblem that is favorable to the activity/location.
3. Reminding players to get bounties, or apply boons, medalions, and other buffs when starting an activity.

**Comment by ckhicks** [comment]
Oh man...this would be amazing. Do you already do polling to see if the user is online via platform-specific API data or would you use the DIM open/active app state as the trigger for regular updates?

**Comment by kyleshay** [comment]
We could have it as a separate tab at the top that loads a view for your active character:
- Hide other characters, show other items "in the vault" (even if they aren't)
- Hide armor in the "Vault" that is a different subclass than active character
- With the added horizontal real estate from hiding other characters, we could show active pursuits, etc.

**Comment by kyleshay** [comment]
@LongLiveCHIEF - we do already have a 'farming mode', maybe we could repurpose this and #3052?

**Comment by SentryTheDefiant** [comment]
I feel like a lot of this would be difficult to implement, but automatically equipping favorited ghosts with applicable Planetary Perks when turning on farming mode would be a huge improvement

**Comment by delphiactual** [comment]
https://gist.github.com/delphiactual/78c37032af38fac25c7d26a183b082e7

**Comment by Revadike** [comment]
Any progress on this? It would be amazing if we could automatically equip the ghost that's most favorable for the current world or activity you're in.

**Comment by Revadike** [comment]
For Steam players, you could use this "API" (not really): 
https://steamcommunity.com/miniprofile/82699538

![image](https://user-images.githubusercontent.com/4411977/76432459-4d930d00-63b3-11ea-8b6b-94c72fe37db9.png)

It uses steamid3 format and requires profile to be public.

**Comment by Revadike** [comment]
https://github.com/Revadike/userscripts/blob/master/DIM%20-%20Auto%20Ghost%20Switcher.user.js

**Comment by kyleshay** [comment]
Concept  
![foo](https://user-images.githubusercontent.com/424158/94849796-cf439a00-03da-11eb-8107-8b6ad51ed467.png)

**Comment by wein3967** [comment]
@kyleshay That's a nice looking interface idea.
