### ISSUE TITLE
Add filter for Raids

### ISSUE THREAD

**Issue by SahandJ** [DestinyItemManager/DIM#2962]
Would it be possible to add a filter for the raids?

For instance:

raid:Leviathan - raid:Lev
raid:EeaterOfWorlds - raid:Eater - raid:EoW 
raid:SpireofStars - raid:Spire - raid:SoS

**Comment by bhollis** [comment]
This will hopefully be possible once Forsaken releases!

**Comment by bhollis** [comment]
Rolling this into https://github.com/DestinyItemManager/DIM/issues/3031.
