### ISSUE TITLE
Clear Search Button is too small on Mobile/Tablet Devices

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#2965]
Fat fingers need a bigger target.  Can we move it outside of the input box and make it bigger?

https://twitter.com/MeefJ/status/1029939853029519361

**Comment by SunburnedGoose** [comment]
![image](https://user-images.githubusercontent.com/984608/44186784-0c584f80-a0e1-11e8-8cc0-48c74af87410.png)

**Comment by duckmanBR** [comment]
I believe that the problem is not the size, but that the "mass tag" is too close to it.  At least that is my usual problem.  And since you can't "undo" the turn-to-combobox of the mass tag, it's kind of a annoyance if you misclick the clear button.

**Comment by bhollis** [comment]
@duckmanBR has it - the button position and size are normal for iOS at least (take a look at the Safari address bar for example) but it’s getting crowded.
