### ISSUE TITLE
Please add CM Browser to list of supported browsers 

### ISSUE THREAD

**Issue by michabbb** [DestinyItemManager/DIM#2972]
Hi, I am using CM a while now, and I can verify, that everything is working fine, even the Google drive connection.

https://play.google.com/store/apps/details?id=com.ksmobile.cb

So it would be nice to remove the warning at the bottom of the screen for this browser.

Thanks

**Comment by bhollis** [comment]
I'm sorry, but we can't maintain a list of all of these extra browsers. We'll support the major browsers only.

**Comment by michabbb** [comment]
@bhollis do you support opera ?

**Comment by SunburnedGoose** [comment]
I know we support the desktop browser.  I haven't tried the mobile version.

**Comment by michabbb** [comment]
if i may explain:

i checked some browsers:

android opera installations: 100.000.000+
android cm browser: 50.000.000+
android firefox: 100.000.000+
android samsung browser: 500.000.000+

the biggest problem for me personally is:

to use gdrive sync with DIM on chrome mobile, it won´t work until you allow 3rd party access for/to cookies, as mentioned [here](https://github.com/DestinyItemManager/DIM/issues/2713#issuecomment-395960183). on android chrome mobile this access is disabled by default, and it´s not possible to enable this for some specific urls (as far as i was able to debug this). so in my case, i am forced to use another browser, i only use for DIM - for nothing else - because i don´t want to enable this in general - i fully understand that you cannot support every little fork of every browser.

but maybe you understand this case and maybe CM has enough installations, that you might consider to add it.

thanks

**Comment by bhollis** [comment]
It’s not quite as simple as that. We yse a separate browser database that itself would need to be updated to support CM.

**Comment by michabbb** [comment]
is this database managed by someone else, an external project ?

**Comment by bhollis** [comment]
Yes, https://github.com/Fyrd/caniuse/

**Comment by michabbb** [comment]
Interesting, good to know and now I fully understand, thanks. May I ask which check(s) u are doing to decide to display the red browser warning?

**Comment by bhollis** [comment]
The code is in browsercheck.ts if you want to check it out.

**Comment by michabbb** [comment]
it´s interesting , this library is great, makes things more easy (in general). CM browser is based on chrome, so i am really curious what kind of string is checked here 😏  i will check this out, thanks for your help!
