### ISSUE TITLE
Sort Characters by Id

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#2980]
https://github.com/DestinyItemManager/DIM/blob/62138ad066e039f6f5a761a05b354497d349440a/src/app/inventory/d2-stores.service.ts#L240

With the character sort being broken, V told us that the Id value is incremental so if we sort on it, we're guaranteed to have a baseline sort based on creation date.  Is this a good spot to apply a sort function @bhollis?

**Comment by bhollis** [comment]
As far as I remember The reason we haven’t done this in the past is because when they migrated characters from D1 to D2, that order wasn’t preserved, so sorting by ID won’t work. Probably worth confirming with vthorn. Wish we could just have a creation date.

**Comment by doktor5000** [comment]
Didn't see a separate issue for the broken character sort, so asking here:

Would it be possible, maybe as sort of a interim workaround to allow fixed/custom sort order,
so you can directly decide which character shows in what position?
