### ISSUE TITLE
Filters not working since Forsaken

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#2981]
The following filters no longer match anything:

is:submachine
is:grenadelauncher

**Comment by bhollis** [comment]
https://github.com/DestinyItemManager/DIM/pull/2645 would fix it but we never came to an agreement on the categories.

**Comment by philkernick** [comment]
With the change to weapon infusion in Forsaken, I think it's time to merge #2645 as originally proposed.

**Comment by bhollis** [comment]
Merged.
