### ISSUE TITLE
Progress, Vendors,  and exotics under collections not showing after Foresaken Update

### ISSUE THREAD

**Issue by TKESuperDave** [DestinyItemManager/DIM#2982]
When going to Progress I get a Bungie.net error stating "Bungie.net Servers are down for maintence. Get status update on twitter." I have not seen this mention on the ThisisDim twitter account or even acknowledging this is a problem.

When selecting Vendors it appears as though it will load but never does. Instead it continues the DIM loading animation. I've sat on this page for 10-15 minutes and not had it load. 

When visiting Collection's page, I am able to see the Ornaments, Catalysts, and Emotes.  I am not longer able to see exotic guns and armour. They aren't even an option.

**Comment by TKESuperDave** [comment]
I should also note that after asking several of my clan members they are having the same issue as well.

**Comment by bhollis** [comment]
I've got a fix going out for the vendors and progress page. Vendors are unavailable completely until after Forsaken. Exotics are now under a different API so they won't be available until we do some extra work.
