### ISSUE TITLE
Triumphs

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#2995]
How should we display Triumphs?

**Comment by ckhicks** [comment]
DIM has always been my favorite place to view large amounts of data because of its simplicity. Maybe a pattern like nested expanding sections by "[bucket](https://i.ytimg.com/vi/mknW-koQI2I/maxresdefault.jpg)" with the option to fuzzy-search like your normal UI for Inventory?

**Comment by philkernick** [comment]
I'd start with the Record Books section from D1 and work forward from there.  It feels like the same concept.

**Comment by ckhicks** [comment]
Yeah, very similar in terms of the user path.
