### ISSUE TITLE
Search Filtering for Randomized Weapons

### ISSUE THREAD

**Issue by swable** [DestinyItemManager/DIM#3004]
I would like to see a filtering option added for separating Randomized and Non-randomized weapons. 48klocs mentioned that there is a property that may be used for has:randomperks. Would be great to see the functionality added to the search bar.

Thanks for your time~

**Comment by bhollis** [comment]
@48klocs what’s the propery?

**Comment by 48klocs** [comment]
Down on `DimSocket`, I added a `hasRandomizedPlugItems` property (needed to support the DTR API).
