### ISSUE TITLE
Sorting by character age not working correctly.

### ISSUE THREAD

**Issue by GitHype** [DestinyItemManager/DIM#3007]
In both the beta and the stable version of DIM, my characters are sorting incorrectly when sorted by character age.

![image](https://user-images.githubusercontent.com/6767465/45250521-aa5ac680-b2e9-11e8-9dcc-be71e247b6cb.png)
![image](https://user-images.githubusercontent.com/6767465/45250526-b8104c00-b2e9-11e8-89b9-0d49c45c0bde.png)

**Comment by SunburnedGoose** [comment]
Which platform? PC will not be in order.

**Comment by GitHype** [comment]
It is on PC, sorry. Is it just a bug on Bungie's end? Do we know if it's going to be permanent?

**Comment by SunburnedGoose** [comment]
It most likely is. We have an issue out for it.
