### ISSUE TITLE
Elemental searches stopped working on Y1 weapons

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#3009]
Current beta.  Try the following filter:  not:arc not:solar not:void

The element for all Y1 legendary weapons can no longer be filtered for.  Y1 exotic weapons and all Y2 weapons can still be filtered for.

**Comment by bhollis** [comment]
Oh wait, you're saying Destiny 2, Year 1 weapons, not D1 weapons. 

This appears to be a bug in the manifest (or maybe a change in the game)? The same results appear in the companion app. I'm away from the game right now, but I assume these weapons still have elemental properties? They have a deprecated mod for the element, but the API isn't taking that into consideration.

**Comment by bhollis** [comment]
https://github.com/Bungie-net/api/issues/662
