### ISSUE TITLE
Move subclass out of 'weapons'

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#302]
Really, no reason for it to be in there. Can't move these things to the vault either.

maybe something like this:
![sample1](http://i.imgur.com/Fur8QwS.png)

or this?
![sample](http://i.imgur.com/RgFzgzU.png)

opens up the possibilities of putting some character specific information there. maybe custom buttons that users can assign? like have a button there that is 'Move heavy ammo to this character' or 'move engrams to vault from this character'. loadouts can move from the dropdown to there? then the dropdown can be how to access things like weekly status/reputation ranks?

the empty vault space doesn't look quite right though. could similarly add account wide information/actions there, if it makes sense.

or we can go the simple route for now, and just go with image no. 1 

thoughts?

**Comment by jflayhart** [comment]
Good catch. Agreed, definitely should be moved out of weapons section, no idea why I didn't catch that myself...

Just throwing this out there, but what if we centered the subclasses under the character block there to the effect of a section carousel:

http://www.pocketmagic.net/wp-content/uploads/2013/06/android_carousel_gallery_view_01.jpg

OR

![screen shot 2015-10-12 at 12 47 04 pm](https://cloud.githubusercontent.com/assets/6808172/10434675/adcc4b70-70e0-11e5-855b-9b42984e9663.png)

**Comment by SunburnedGoose** [comment]
I'm classifying them out of weapons. I wouldn't resize them or add the
carousel pattern. People can click on them to add them to loadouts.

**Comment by kyleshay** [comment]
true true, ok. so basically image 1?

**Comment by Iamtoni** [comment]
I like this idea. By the way, may I suggest to show progress information in the gray area like below? 

![idea](https://cloud.githubusercontent.com/assets/9489714/10448466/44d4ba4e-71b7-11e5-8230-7eb7d9e9e52d.png)

**Comment by jflayhart** [comment]
That's not a bad idea, something probably should go there, but I am afraid that adds a lot of complexity and "business" to what should be a simple item manager. That's my opinion.

**Comment by SunburnedGoose** [comment]
It doesn't all belong on one screen. We could/should add a navigation
feature.

**Comment by dheif** [comment]
My vote goes with the simplest solution: Image #1.

**Comment by kyleshay** [comment]
Fixed with #308 as we're rendering buckets differently anyway.

<img width="1032" alt="screen shot 2015-10-29 at 2 00 46 am" src="https://cloud.githubusercontent.com/assets/424158/10811311/e759ab0a-7de0-11e5-833e-e3774a1659aa.png">
