### ISSUE TITLE
Highlight Discounted (Glimmer-Only) Infusions in Fuel Finder

### ISSUE THREAD

**Issue by adamjford** [DestinyItemManager/DIM#3022]
Related to #2994, but should be doable without new API data, I'd think. Main tricky part is new versions of Year 1 items (i.e. infusing a Year 2 random rolls Main Ingredient into a Year 1 static roll Main Ingredient isn't discounted, and vice-versa), but I assume they can be differentiated.

Some possible options on how to implement this:

* Put discounted options to beginning of both lists
* Keep the lists sorted by Power, but put discounted options before non-discounted options of the same Power
* Separate each list into two sections, with discounted options in the first section of each list (might be problematic for mobile views as it would increase the vertical real estate it takes?)

**Comment by bhollis** [comment]
Help me out, I haven't had a chance to play a bunch. Are you saying that infusing two of the same items together is discounted?

**Comment by SunburnedGoose** [comment]
Yes. Infusing two items with the same item hash only costs glimmer.
Otherwise, it costs planetary materials, masterwork cores, legendary marks
and glimmer.

**Comment by per1970** [comment]
Glad I deceided to browse through as I was about to ask for the same feature! 👍
