### ISSUE TITLE
Auto-collect from Postmaster while Farming

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#3026]
While farming mode is enabled, items can still potentially go to the postmaster.  Now that we have the capability to retrieve items, we can attempt to move them from the postmaster and put them into the vault.

Some items cannot be moved from the postmaster and they should be identified at runtime (failure to move), and excluded from future attempts during that session.

**Comment by bhollis** [comment]
Closing since I'd rather not add another farming option, and we already have a quick button for pull from postmaster, and things hitting the postmaster when farming mode is on is pretty rare (basically only when opening engrams).
