### ISSUE TITLE
Infusion Data/Inaccuracies

### ISSUE THREAD

**Issue by Apsu** [DestinyItemManager/DIM#303]
This is Apswny from Reddit. Following up on discussion in #289, there are still a few inaccuracies in the algorithm I've been working on figuring out. I made a post https://www.reddit.com/r/DestinyTheGame/comments/3o48e2/infusion_data_collection_request/ to try to collect more data in a spreadsheet https://docs.google.com/spreadsheets/d/1PRLjEjzrNu00KrNu6__V-SUUqmHD6l1E1fJQCRIhg_8/edit#gid=0 and I've gotten a few dozen entries so far, about half of which I gathered myself or from comments on various other posts, and about half of the data has the item XP provided.

Looking at the data as a whole, I've discovered a couple of things:

* The algorithm is slightly more complex than it needs to be with the current threshold idea. I can achieve even more matches with no thresholds and a slightly different penalty % for Rare targets (78%) -- when not taking XP into account.
* The algorithm isn't quite complex enough around XP because how leveled base and target items are matters. The discrepancies for items with XP data indicate that base XP is a penalty and target XP is a reward. Exactly how much and what the tipping point is probably requires more data.

Given that it's proven difficult to get a lot of complete data, I'm wondering if there's any possibility you'd be willing to add a 'Report' or similar button to the infusion dialog to allow someone to submit their item data if the calculator differs from the in-game result. That way we could capture how much XP is in the items (at the very least, if not other potentially relevant data).

I realize this would require a little UI work and also a backend somewhere to pipe data into, but honestly I can setup a server/app to collect it if that's beyond your team's resources. Could even just send an e-mail with a JSON attachment and I can automate the parsing. I've already written a test system to try out new algorithms on the data points I have with XP to rapidly check accuracy, so I can easily handle that part. I just need some way to easily let users give me that data now!

Thoughts?

**Comment by dheif** [comment]
Update:
https://www.reddit.com/r/DestinyTheGame/comments/3pmown/update_from_roger_wolfson_on_my_infusion/

**Comment by Apsu** [comment]
Indeed, I've been in discussions and working on the new information this provided to us since they posted, and believe I and the few other folks working on the algorithm now have solved it. Here's my summary post: https://www.reddit.com/r/DestinyTheGame/comments/3pmown/update_from_roger_wolfson_on_my_infusion/cw8a61e

**Comment by kyleshay** [comment]
Closing per #320
