### ISSUE TITLE
Loadout panel appears under the inventory

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#3035]
With the redux update, the Loadouts drop-down panel is sliding under the inventory panel. You cannot access Loadouts ATM.

**Comment by duckmanBR** [comment]
It's not exaclty that.  The drop-down is opening inside the header area.  At least on mobile.

**Comment by bhollis** [comment]
I think I fixed it but the API went down for maintenance just as I was about to test the last bit. I pushed, but I have to head to work now.

**Comment by bhollis** [comment]
Fixed.
