### ISSUE TITLE
Beta Mobile: Inventory not using full height of the window

### ISSUE THREAD

**Issue by duckmanBR** [DestinyItemManager/DIM#3037]
![image](https://user-images.githubusercontent.com/32077894/45362031-208d5080-b5aa-11e8-8281-a85eb7f25750.png)

The item popup works
![image](https://user-images.githubusercontent.com/32077894/45362057-300c9980-b5aa-11e8-850e-57691d73030a.png)

**Comment by bhollis** [comment]
Fixed.
