### ISSUE TITLE
Beta Mobile: Scroll bar not fading anymore

### ISSUE THREAD

**Issue by duckmanBR** [DestinyItemManager/DIM#3038]
Before (or on prod) the scrool bar was subtle and faded away after a few seconds after the scroll.
![screenshot_20180911-101200](https://user-images.githubusercontent.com/32077894/45362588-9ba33680-b5ab-11e8-82dd-a08af0cc2d9e.png)

Now it's always on and it's not that subtle...
![image](https://user-images.githubusercontent.com/32077894/45362374-0bfd8800-b5ab-11e8-86ae-06f9115a5912.png)

**Comment by bhollis** [comment]
Fixed.
