### ISSUE TITLE
DIM hasn't loaded error

### ISSUE THREAD

**Issue by ckaviking** [DestinyItemManager/DIM#3040]
Hello, I have been having this issue for a long time now on my ipad. Ive checked the forums but havent found a solution. plus i cant really force a reload with ctrl-f5 or cmd-r since its an Ipad)

screenshot of the error:
https://imgur.com/gallery/dox7FDB 

I have also tried:
- updating ipad OS
- updated chrome to latest version
- hard reboot & and powering down the device normally

funny thing is that my DIM works fine on my iphone and on my PC. I really miss using DIM on my ipad, iphone is just too small. 

thanks!

**Comment by bhollis** [comment]
Hi there! What version of iOS are you on?

**Comment by ckaviking** [comment]
sorry was out of the office and could not check your answer. will check tonight and will post back! thanks for the reply!

**Comment by bhollis** [comment]
Also, can you try in Safari?

**Comment by ckaviking** [comment]
10.1.1
havent tried safari, will do now

**Comment by ckaviking** [comment]
same error, and iit says browser not supported

**Comment by delphiactual** [comment]
#2858

**Comment by bhollis** [comment]
That's right - I'm sorry, but unfortunately we no longer support iOS 10.1.

**Comment by ckaviking** [comment]
that was it, works again thanks!
