### ISSUE TITLE
DIM continuosly triggering 'Triumph Completed' messages 

### ISSUE THREAD

**Issue by Jaggid1x** [DestinyItemManager/DIM#3042]
Nearly every time I use DIM, the 'Triumph Completed' messages for every planet in which I've done all of the Lost Sectors (Nessus, Mercury, Titan, and Io) appear on the bottom of my screen, one after the other.

Edit: I'm using a PS4 Pro, with Destiny 2 downloaded from the PS Store.
Edit 2: And I forgot to mention that this happens when using DIM on both the newest Firefox and Chrome.

**Comment by ckhicks** [comment]
This is happening in-game as well: https://github.com/Bungie-net/api/issues/644

**Comment by duckmanBR** [comment]
It's not DIM fault.  The error is on Bungie side.
