### ISSUE TITLE
Remove sort options and only show custom sort

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#3047]
No major reason to have both

<img width="370" alt="screen shot 2018-09-12 at 1 59 49 pm" src="https://user-images.githubusercontent.com/424158/45452925-28c1ba80-b694-11e8-8f90-8bcf7c2ee9a2.png">

**Comment by bhollis** [comment]
Hmm, my thought initially was that folks would mostly use the presets, rather than the more complicated custom sort. Do you think a lot of people use the custom version?

**Comment by kyleshay** [comment]
I'm not sure. I'm thinking the majority keep it as the default, then people who are really interested in making something tailored to their needs, learn how to use the settings.

**Comment by kyleshay** [comment]
Could we add a feature flag to try removing a feature? 😂 Suppose the major work would be to map existing sorts to the new custom. We'd also maybe want to have a little (?) icon, docs files, or text below to explain what a secondary sort is.
