### ISSUE TITLE
Update Item Tiles to show attributes of the Item

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#3048]
Enhance the existing item tile to give the user more information about their item in a way that lets them quickly identify the particular item that they desire.  A couple of targets that we want to hit are:

1. High visibility for the Icon
    1. Remove layers over the icon to let Bungie's artwork shine.
    2. Avoid covering information in the icon such as the release icon (Warmind, Forsaken, Osiris)
2. Make the power/light level of the item more visible. Currently it is black on a light grey which is okay but could be better.
3. We want to show items that users can identify their items easily such as shaders, masterwork value, and mods.  We know that perks are desired, but there are many which are hard to show in small spaces.

Todo:

- [ ] Ratings
- [ ] Lock
- [ ] Show Percentage Indicator in lieu of Power
- [ ] Tag
- [ ] Ammo

**Comment by SunburnedGoose** [comment]
Rating data is in the app, but it doesn't show up in the item tile until I cause a digest to occur.

**Comment by bhollis** [comment]
There's no more digesting in the React world - just updates to state and props. Take a look at `StoreInventoryItem.tsx` and `InventoryItem.tsx` to see how it works now.

**Comment by bhollis** [comment]
For reference:

Stuff that we show currently:
1. Icon
2. Power
3. Tag Icon
4. Element
5. Rating (or quality for D1)
6. "Completeness" (gold border)
7. "Power mod" (gold border)
8. Masterwork (glow)
9. Stack size
10. Progress bar
11. Percentage completion (for bounties/quests/some consumables)
12. Whether the item is new

Stuff we may want to add:
1. Mod
2. Shader
3. Ornament
4. Masterwork Type
5. Masterwork Level / Item Level (1-10)
6. Lock status
7. Rarity
