### ISSUE TITLE
Infusion Enhancement - Shortest Path/Most Efficient Route to Highest Obtainable Value?

### ISSUE THREAD

**Issue by Mulchman** [DestinyItemManager/DIM#305]
I've been trying to figure out the best/shortest path to get my Black Spindle back to 310. One calculator I've found online has the capability of showing the shortest path to the max given a set of inputs.

I'm wondering if the DIM infusion GUI could have this functionality as well? In this screenshot, you'll see DIM and the other calculator. In the background on the other calculator, it's showing I can get the max (from this set of inputs) of 298 in 3 steps rather than 4. Perhaps DIM could do something similar, like a visual indicator showing that a gun isn't needed in the chain to still get the highest obtainable value from a set of inputs?

![example](http://i.imgur.com/pBkBJ2H.png)

**Comment by kyleshay** [comment]
Just linking to #314

**Comment by bhollis** [comment]
The implementation for this was merged for the next beta.
