### ISSUE TITLE
Leveling Recommendation Engine

### ISSUE THREAD

**Issue by LongLiveCHIEF** [DestinyItemManager/DIM#3052]
One of the top reddit posts in DTG today was a pretty good leveling guide for Forsaken. See: [/r/DestinyTheGame - Leveling Guide - Forsaken](https://www.reddit.com/r/DestinyTheGame/comments/9fh2li/leveling_guide_forsaken/)

The author describes a pretty good algorithm that I think could be used to create an automatic "Leveling Recommendation Engine" feature, that would take in your current gear/max power, and spit out a "recommended activity and order". 

This should probably be a project/milestone instead of a single issue. I'm thinking MVP would have following features:

- [ ] Allow users to select whether the recommendation is based on Max Leveling across all characters, or a single character
- [ ] Allow a user to specify how much time they are going to spend playing today/tomorrow/_n_ days before next weekly reset) The recommendation would be different if you only plan on playing for 3 hours before the reset of the next highest tier activities you need to power level

Non MVP features could include:
- [ ] allow users to factor out activities from specific expansions (eg... I don't care if I can get powerful gear from Y1 Raids, I only want to do new raids)
- [ ] others?

**Comment by bhollis** [comment]
This is a super cool idea! I’d love to see some sketches of how we’d present this.

**Comment by ckhicks** [comment]
Love, love, love this.

**Comment by wein3967** [comment]
Yeah, this would be super helpful with new "different" kinds of Powerful Gear.

**Comment by LongLiveCHIEF** [comment]
I think an important aspect of this would be some kind of Legend or Visual Guide to the different activities and what "Tier" they fall into, as well as an identifier for each of your characters for their current Tier.  Just that at a quick glance would be a good start, allowing people familiar with how the tiers work to do the mental math in their head and choose an appropriate activity. (Maybe _this_ could be the MMP for this feature?)

**Comment by riannucci** [comment]
Oops, I think I linked to my copy of the sheet instead of the original: https://docs.google.com/spreadsheets/d/1tg1uDdsudOP-3he2-kqtOKVBr-iF6tbV4XzIGrPPkus/edit#gid=2139564447

**Comment by LongLiveCHIEF** [comment]
We decided that this feature would have limited usefulness, and may not even be useful by the time it would be released.

**Comment by riannucci** [comment]
Makes sense; would it make sense to JUST port the 'powerful engram level' table? So that DIM could show which activities are +1 vs +5? That would be a lot less work, and may continue to be generally useful as more stuff comes out (e.g. prestige raid, other... weekly surprise missions :))
