### ISSUE TITLE
Update Contribution Guide

### ISSUE THREAD

**Issue by LongLiveCHIEF** [DestinyItemManager/DIM#3053]
I suggest moving contribution instructions to a standard `CONTRIBUTING.md` and updating the content from README.md. The current information about obtaining an api key still references the old chrome extension based build, and should be updated to include new instructions about creating your own test app and getting your oauth credentials and providing them to your development instance.

Requirements for PR:
- [ ] include docs on scopes needed/used by DIM
- [ ] include docs about using a publicly available IP for your development env callback url
- [ ] document where/how to provide your api credentials to app config in your dev env
- [ ] add link to discord server for collaboration questions https://discord.gg/UK2GWC7

*Note: I am planning to work on #3052 and will prepare a PR for this issue as I set up to start on that.*

**Comment by LongLiveCHIEF** [comment]
What scopes does DIM currently use? I'll want to make a note of that in the updated Contribution Guide.

**Comment by 48klocs** [comment]
The last time I went through a fresh install, it auto-nav'd to the `/dev` route (hopefully still working) which is where you copy/paste keys & creds in.

But it is easy to screw up, so having that noted in case you need to get back there would be a Good Thing.

**Comment by bhollis** [comment]
I'd definitely welcome any improvement to our documentation!

**Comment by LongLiveCHIEF** [comment]
Should I add `git-lfs` to the list of dependencies in the setup docs?

**Comment by bhollis** [comment]
I don’t think so, what do we use it for?
