### ISSUE TITLE
WIP: Create docker dev environment

### ISSUE THREAD

**Issue by LongLiveCHIEF** [DestinyItemManager/DIM#3054]
For projects like this, I have found it is often useful for contributors to be able to use docker compose to quickly deploy a development environment of the app so they can look around without having to worry about setting up a server or dev machine with the versions of node and such that are best for this project.

This also ensures that there is a standard platform for which all tests can be run, and helps eliminate parity in development environments, making it easier for contributors to ask about problems with their setup (by being able to eliminate external host-based environmental factors)

I plan to work on this as part of #3053 and have already begun this work.

Proposed PR acceptance requirements:
- [ ] document how to provide api auth to container
- [ ] update Quick Start/Contribution Guide docs with `docker-compose` option or link to using docker to set up your dev environment
- [ ] speak with org/project members about setting up a publish to a public registry for tagged releases and rolling master latest builds

**Comment by delphiactual** [comment]
#2992

**Comment by LongLiveCHIEF** [comment]
closing in favor of #2992
