### ISSUE TITLE
Search doesn't work for Heroic Resistance gear

### ISSUE THREAD

**Issue by KsaRedFx** [DestinyItemManager/DIM#3056]
Unable to search for gear that uses "Heroic Resistance" instead of Void, Solar, or Arc. 
It appears to be a very rare type of resistance available to random-rolled gear 

https://i.imgur.com/TKjXuIt.png
https://i.imgur.com/jnibDZl.jpg

**Comment by bhollis** [comment]
How did you try to search for it? I don't have any of this gear...

**Comment by KsaRedFx** [comment]
I tried "Heroic" or "Heroic Resistance", just looking up "Resistance" highlights all gear.

**Comment by KsaRedFx** [comment]
I also tried is:heroic as similar things like is:void filters based on armour resistance. Unless there's another specific way for me to look it up, I think it's just an edge case that was missed.

**Comment by delphiactual** [comment]
I do not think search checks masterwork text fields just yet.

**Comment by delphiactual** [comment]
#3041 @kyleshay
