### ISSUE TITLE
Move engrams category to above weapons when engrams are present

### ISSUE THREAD

**Issue by ArkahnX** [DestinyItemManager/DIM#3064]
With prime engrams being very relevant, and receiving them typically at least one a day, I think moving engrams to the top when you have one would be beneficial, similar to how postmaster now appears at the top when there is items lost (in the beta channel)

unsure if we would want a header for engrams, since that could look crowded with postmaster and engram headers
![Suggested change](https://i.imgur.com/VX9hcas.png)

**Comment by bhollis** [comment]
I like this idea, but I'm inclined to wait until after I experiment with adding per-bucket headers, so it's clear this isn't actually in the postmaster.

**Comment by bhollis** [comment]
Though, I dunno, it's pretty nice having it up there. @kyleshay @SunburnedGoose what do you think?

**Comment by SunburnedGoose** [comment]
This is a great idea. These are high actionable items.

**Comment by bhollis** [comment]
Yeah I played around with this yesterday and it’s real nice.
