### ISSUE TITLE
yarn start is failing (due to missing certs)

### ISSUE THREAD

**Issue by 48klocs** [DestinyItemManager/DIM#3065]
```
yarn run v1.9.4
$ webpack-serve ./config/webpack.js --no-reload
fs.js:113
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'key.pem'
```

I moved my self-generated `key.pem` and `cert.pem` (self-signed certs) in to the root DIM folder and that fixed it. I'd commit mine, but I don't know what the right way to go about including throwaway certs is. I guess webpack could be smartened up to generate certs if they don't exist?

**Comment by LongLiveCHIEF** [comment]
We could take a look at doing some dynamic [let's encrypt](https://letsencrypt.org/) generation in the dev setup.

**Comment by LongLiveCHIEF** [comment]
The official module was recently renamed to `greenlock` https://www.npmjs.com/package/greenlock

**Comment by LongLiveCHIEF** [comment]
It should also be mentioned that this is a benefit of docker-based development setup. PR https://github.com/DestinyItemManager/DIM/pull/2992/files takes care of this problem nicely, and already has a command to generate a self-signed cert as part of the dev environment creation.

**Comment by bhollis** [comment]
We could also just autogenerate certs whenever you need them. It's not like anyone's actually going to serve anything from the dev server.
