### ISSUE TITLE
For/In with Arrays

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#307]
https://github.com/DestinyItemManager/DIM/blob/dev/app/scripts/move-popup/dimMoveItemProperties.directive.js#L155

MDN does not recommend using For/In w/ Arrays.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in#Array_iteration_and_for...in

Refactor to use _.each

**Comment by kyleshay** [comment]
http://jsperf.com/angular-foreach-vs-underscore-foreach/25

![perf](http://i.imgur.com/thafXxs.png)

**Comment by SunburnedGoose** [comment]
:/

**Comment by SunburnedGoose** [comment]
I went to the same place yesterday and saw that graphic.

**Comment by kyleshay** [comment]
just sayin... vanilla is yummy

**Comment by kyleshay** [comment]
haha

**Comment by kyleshay** [comment]
we could use this: `_.filter(items, function(item){ return item.equipped && item.type === vm.item.type; });`

could even put that logic on a property when the item is created. would offload the move popup strain to init page load...

**Comment by bhollis** [comment]
This is super out of date, but relevant: http://benhollis.net/blog/2009/12/13/investigating-javascript-array-iteration-performance/

Still, raw `for` loops or `_.each` and other Underscore methods are faster.

**Comment by kyleshay** [comment]
fixed in `perf` branch #308
