### ISSUE TITLE
may i ask: where does this text come from ?

### ISSUE THREAD

**Issue by michabbb** [DestinyItemManager/DIM#3070]
![16-09-2018-07-47-51](https://user-images.githubusercontent.com/3524595/45599297-65214d80-b9e9-11e8-8115-5306a065dc96.png)

i wasn´t able to find that 😕 
*THANKS*

**Comment by kyleshay** [comment]
It actually comes from the bungie manifest.
 
There are is some documentation about how that works here:
http://destinydevs.github.io/BungieNetPlatform/docs/Manifest

DIM automatically pulls the latest manifest in, and then we build items in `d2-item-factory.service.ts`

The data is formatted specifically for DIM, but the manifest data for that specific item looks something like this:
https://data.destinysets.com/i/SandboxPerk:3116717848
