### ISSUE TITLE
Masterwork counts on armor can be out of order

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#3073]
In in the item details section of an armor piece it shows the masterwork type and the current masterwork level.  Beneath it it shows more options.

![image](https://user-images.githubusercontent.com/25425159/45606365-ce559f00-ba83-11e8-87af-87d4483c9ced.png)

For example this armor is currently masterwork 3, but below it shows 2 and 4.  It is the case for all armor at masterwork 3.

![image](https://user-images.githubusercontent.com/25425159/45606528-f85b9100-ba84-11e8-86c0-9c61055772f3.png)

When it's masterworked to 4, it shows 2, 3, 5.

I suggest suppressing all the other options for the masterwork plug, because unnecessarily increases the vertical size of the item details box, and gives no useful information anyway.

**Comment by philkernick** [comment]
Just checked one that is masterworked to 5, it shows 3, 4, 6.

**Comment by bhollis** [comment]
Fixed in #3090.
