### ISSUE TITLE
Loadout not applying

### ISSUE THREAD

**Issue by 1RuneKing** [DestinyItemManager/DIM#3075]
This happens occasionally and it's really frustrating, but every so often my loadouts will stop applying, I will get a green notification saying 0 items were transferred to warlock, but nothing gets moved around in inventory. Am I doing something wrong or is there a quick fix?

**Comment by kyleshay** [comment]
Thanks @1RuneKing ! Sorry to hear it isn't working. Would you be able to provide some more information? Is this a custom loadout that you've made? What are the contents of the loadout and how are you applying it? Beta or stable version? Web browser? Are there any errors in the developer console, by chance?

**Comment by 1RuneKing** [comment]
Its a custom loadout yes, using the tool where I throw it together in inventory and save loadout on your tool. It used to work properly but now I just get the green "transferred 0 items to your awoken male warlock" message. I would tell you the info in console if I could find where it sends info to.

**Comment by bhollis** [comment]
1. Could you send a screenshot of your loadout?
2. Are you using app.destinyitemmanager.com, or beta.destinyitemmanager.com?
3. Does it say "0 items transferred" every time, or just sometimes?

You may want to hop on our [Discord](https://discordapp.com/invite/UK2GWC7), there are some folks that can help you get more information.

**Comment by 1RuneKing** [comment]
1: http://prntscr.com/kxjr14 and in the site: http://prntscr.com/kxjrgt http://prntscr.com/kxjsfi http://prntscr.com/kxjsiw
2: app, will try to do it on beta if you'd like
3: as of lately, yes

**Comment by bhollis** [comment]
Sorry, I think you'll need to head over to Discord and talk to somebody.
