### ISSUE TITLE
Masterwork does not have a useful description.

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#3077]
https://www.reddit.com/r/DestinyItemManager/comments/9ftlg9/could_we_get_the_masterwork_stat_description_when/?utm_source=reddit-android

**Comment by K-Davis1** [comment]
Changing the description header from
> Tier 1 Weapon  

to  

> Tier 1 Range  

should do the trick.

I don't think the mod description needs to be changed.

**Comment by delphiactual** [comment]
We won't change the description from what bungie provides us...
