### ISSUE TITLE
Cannot read property 'classType' of null - on /d2/progress

### ISSUE THREAD

**Issue by michabbb** [DestinyItemManager/DIM#3079]
![17-09-2018-06-40-03](https://user-images.githubusercontent.com/3524595/45636830-176c1a00-baa9-11e8-82e1-785e1bd4645c.png)

**Comment by bhollis** [comment]
I’m not seeing this, which means you must have a different item than I do (probably a classified pursuit).

**Comment by bhollis** [comment]
A screenshot of the developer console would go a long way!

**Comment by bhollis** [comment]
This should be fixed - can you confirm?

**Comment by michabbb** [comment]
confirmed ! 👍 thanks !
