### ISSUE TITLE
DIM Performance

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#308]
Looking through the code tonight for the move popup to see why it is taking so long to show the dialog on screen, and to open a new one.

Couple things...

We're building the ordered stores every time we load the page.  That should be done once and updated if settings change, or the stores change.

--------- 

The following changes are being made in the `perf` branch.

### Remaining tasks

- [x] [This code is generating a LOT of garbage collections.](https://github.com/DestinyItemManager/DIM/blob/dev/app/scripts/move-popup/dimMoveItemProperties.directive.js#L155-L165)  It wants to get the currently equipped item for a type in a store, and then iterate the current item's stats collection and assigns the equipped items stats to a value on the current item.  That's causing digests to occur I believe.
- [x] Postmaster section.
- [x] Make sure the compare stats works in move popup.
- [x] Missing Complete Border (yellow) on items.
- [x] Add the vertical space between type groups to separate them.
- [x] Row headers for sections [like this (unfinished)](http://i.imgur.com/3MrisMZ.png)
- [x] Add vault category counts to vault header.
- [ ] User select number of inventory/vault columns.
- [ ] Items with no 'equip slot' should span into that column. (materials, etc)
- [ ] Polish styling:
 * Restore the vault column background color (lighter).
 * Vault banner header layout.
 * Bucket headers.
 * ![pasted_image_at_2015_10_29_12_33_pm_1024](https://cloud.githubusercontent.com/assets/424158/10828445/9dd3ff70-7e4a-11e5-97f4-4bed4ad5562f.png)

**Comment by bhollis** [comment]
I've also noted in my own profiling that copying large values in watches (like the whole of an item) is taking the majority of our time (you can see it as `angular.copy`). Fewer and more fine-grained watchers would help there. There are also a few places where we update things in reaction to watches (wuch as in `dimStoreItem.directive.js`), which ends up with cascading digests.

**Comment by SunburnedGoose** [comment]
The only place we copy is in the loadouts afaik when we clone items.

**Comment by SunburnedGoose** [comment]
A good place to start that would save us a few seconds is to move the loading of the JSON files from the manifest file to a webworker to get it off the mainthread.

**Comment by bhollis** [comment]
That seems a bit drastic. I'd try just loading them in parallel first.

The angular copies in talking about happen internally while angular is saving the previous state of a watched expression so it can compare to detect changes later. 

-Ben

**Comment by SunburnedGoose** [comment]
Talents and Items are loading in parallel.  It's about 1 1/2 - 2 seconds to load the JSON files.  That's 20% of the total initial load time for DIM.  They are big lifts.  If I can get those off the thread and start working on loading the 6 calls to Bungie, that would be nice...  extremely nice.

There are ~28 digest cycles on load.  Is that a lot?  Dunno yet...

**Comment by SunburnedGoose** [comment]
btw @bhollis pull the perf branch to see the latest work on that effort.

**Comment by kyleshay** [comment]
there is also the `move-popup` branch that touches a couple of things.

**Comment by kyleshay** [comment]
move-popup merged in to the perf branch.

**Comment by SunburnedGoose** [comment]
- [ ] We need to add the vertical space between type groups to separate them.
- [ ] Restore the vault column background color (lighter).
- [ ] Add vault category counts to vault header.

**Comment by bhollis** [comment]
I'm closing this because we're good on performance, but there's always performance work to do.
