### ISSUE TITLE
broken: /about

### ISSUE THREAD

**Issue by michabbb** [DestinyItemManager/DIM#3080]
![17-09-2018-06-47-48](https://user-images.githubusercontent.com/3524595/45637204-2c957880-baaa-11e8-8737-303cec01868c.png)

but i guess this is only because of https://github.com/DestinyItemManager/DIM/issues/3079

**Comment by bhollis** [comment]
Not related, but it’s a bug that accidentally escaped to prod.

**Comment by bhollis** [comment]
Thanks, this has been fixed.
