### ISSUE TITLE
Border between the items (beta on ipad)

### ISSUE THREAD

**Issue by mistral13** [DestinyItemManager/DIM#3085]
The distance or border between the items in the beta (4.70.1) is too large on my ipad.
This makes the items very small

Old Style
![f184b575-9e73-4818-aa53-b53bc87ce04e](https://user-images.githubusercontent.com/5049663/45652981-a9d6e280-bad6-11e8-8539-e115bb5166c6.jpeg)

Beta:
![56e63b3b-818c-46b6-82ec-7159ecc0f417](https://user-images.githubusercontent.com/5049663/45652982-aa6f7900-bad6-11e8-82b7-00ba18c56cc9.jpeg)

**Comment by philkernick** [comment]
The border between items is also too wide on desktop Chrome.

**Comment by bhollis** [comment]
Fixed in #3090.
