### ISSUE TITLE
First thoughts on item tiles

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#3087]
It's a big change.

1. The item images need a border.  The gold border for masterworks is good.  No border for non-masterworks makes it look very, very busy and hard to read.  I suggest a white border the same as it's rendered in-game.

2.  Tile size needs work.  I had to increase the size in options up to maximum to even be able to read them.  The size seems scaled based on the original image, but really need to be scaled up by 30% so the image is the same as it was, with the tile details added to that.

3.  The subclasses don't need the tile treatment.  Nor does anything in the inventory (consumables, pursuits, shaders, etc). They look strange and the tile layout adds nothing of value.

4.  Related but emblems and ships also don't feel like they need the tile treatment.  I'm ambivalent about sparrows.

5.  Mousing over one of the 3 tile details on the right hand side of each tile should tell you what that tiny icon means.  At the moment you just get the item name.

**Comment by philkernick** [comment]
More thoughts.

6. Not sure what value there is in having the shader as one of the tile items.

7. Would be better to have the ammo type in one of the small tile details, removing all overlays.

**Comment by philkernick** [comment]
Moving on to other page.

10. Icon size has shrunk for everything in pursuits.  It look like the same size as the image (without the tile details) from inventory.

11. If you scale up the icons in inventory to make them readable, everything in vendors and collections is now super-sized!   Scaling needs to be aware of whether there is tile detail or not.

**Comment by ItsCrocoSwine** [comment]
May I also add that there should be an setting to turn the tiling off, perhaps even a hotkey to toggle it on and off. I really do like the idea, but I find it too cluttered for quick use.

**Comment by bhollis** [comment]
Some of this was addressed in #3090. The rest is under active discussion, but keep the feedback coming :-)

**Comment by SunburnedGoose** [comment]
Thanks @philkernick for the great feedback.
