### ISSUE TITLE
Borealis catalyst in postmaster breaks DIM

### ISSUE THREAD

**Issue by Ryan-Sharp** [DestinyItemManager/DIM#3088]
Hi all!

my DIM kept crashing when trying to open the app in all major web browsers. As soon as it tried to load the inventory, the entire app would crash to a blank gray screen. opening the console, i saw the following errors:

(click to enlarge):
https://gyazo.com/4e4dec4bffc0bae535a46de6d72ecd4b

I saw that it was having an issue with a certain item in the postmaster, and so I removed all postmaster items one by one and relaunched DIM after each. The item that was the problem child was a borealis catalyst in my hunter's postmaster. Removing it from the postmaster fixed the problem.

**Comment by bhollis** [comment]
Can you please try the app again? I think I fixed it.
