### ISSUE TITLE
Add a new Tag for weapons

### ISSUE THREAD

**Issue by ckaviking** [DestinyItemManager/DIM#3094]
hey! 
would it be possible to have a new tag category for weapons that need testing. something like "try out".

im currently using all the other tags as intended but this would help manage my random rolls a little bit better 

thanks!

**Comment by delphiactual** [comment]
Notes are here to help

**Comment by kyleshay** [comment]
Thanks @ckaviking - I'm going to lump this in with #3050

**Comment by ckaviking** [comment]
thanks man! I really love the tag system and I think it can have a lot more potential. its really differentiating from other apps like DIM
