### ISSUE TITLE
is:randomroll not matching anything?

### ISSUE THREAD

**Issue by javalasers** [DestinyItemManager/DIM#3098]
In 4.70.2, a search for is:randomroll matches no items, and a search for not:randomroll matches all items. I recall that the same search last week returned results more in line with what I'd expect (year 2 weapons and armor were showing as randomroll, and I believe all exotics were as well; everything else was showing as not a random roll). I don't know if this is a regression in DIM itself, or a change or regression in the Bungie API DIM is using. :-/

**Comment by delphiactual** [comment]
API is currently operating at a reduced capacity
