### ISSUE TITLE
Switiching loadouts with different exotics

### ISSUE THREAD

**Issue by Hypnoatic** [DestinyItemManager/DIM#31]
When you try to switch loadouts that have different exotics ie. exotic primary > exotic secondary, depends on how the DIM actually processes the switching of items. A majority of times, it will say that the loadout is on your character is loaded but in-game the exotic primary switched to the other primary but the original secondary will not switch to the chosen exotic

**Comment by kyleshay** [comment]
closing. reopen if this is still an issue.
