### ISSUE TITLE
Organize Quests and Bounties

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#310]
Either separate them or give them more organization.

**Comment by kyleshay** [comment]
is this covered automatically in the #308 `perf` branch, since every bucket is rendered separately?

**Comment by kyleshay** [comment]
Handled in the #308 `perf` branch, since every bucket is rendered separately.

<img width="1360" alt="screen shot 2015-10-29 at 1 58 36 am" src="https://cloud.githubusercontent.com/assets/424158/10811280/9fb40df4-7de0-11e5-8de8-ff87764cc806.png">
