### ISSUE TITLE
Ability to searching in one perk

### ISSUE THREAD

**Issue by Titus-s** [DestinyItemManager/DIM#3102]
I would be nice to have ability to search items that have all entered words in one perk. 
Right now when I'm want to find armor that increases the amount of grenade launcher ammo I can carry I enter "**grenade launcher reserves**". It highlight armor that have perks with "grenade", "launcher" and "reserves" at all. So in highlighted items I have items that not interest me but have perks like: 
"Causing damage with a **grenade** reduces your melee cooldown." 
"Faster reload for Rocket **Launcher**, **Grenade** **Launcher** and Shotguns."
"Shotguns get bonus **reserves** when you pick up Special ammo."

**Comment by kyleshay** [comment]
If you use quotes around your search term it works as expected (searches as a full phrase.)

`"grenade launcher reserves"`
