### ISSUE TITLE
inventory vs progress page character order different

### ISSUE THREAD

**Issue by onching** [DestinyItemManager/DIM#3103]
i have it set on order by character age. the inventory page order is warlock titan hunter but progress page order is titan hunter warlock. It makes it confusing for me when the order between the two pages doesn't match. Can we fix this? Thanks

**Comment by onching** [comment]
ps4 console

**Comment by philkernick** [comment]
I saw the same thing last night on Xbox.  But weirdly it was the wrong order on my iPad, but the correct order on my Chrome desktop.
