### ISSUE TITLE
UX: Highlight Comparisons

### ISSUE THREAD

**Issue by dhazelett** [DestinyItemManager/DIM#3106]
While comparing a few items in my inventory, I didn't realize I had dupes of some items showing in the menu, and was struggling to find them. I it might be helpful to highlight them a slightly, or possibly a mix of highlighting and dimming out items not in the compare menu.

![baseline](https://user-images.githubusercontent.com/9557399/45789537-0fd97c00-bc35-11e8-8795-8d6f60acdf2e.png)
> baseline

![highlight](https://user-images.githubusercontent.com/9557399/45789767-3f3cb880-bc36-11e8-8ada-232b42e3c47f.png)
> highlighting

![highlight dimmable](https://user-images.githubusercontent.com/9557399/45789783-4a8fe400-bc36-11e8-8ab6-096b5c8821b3.png)
> highlighting + dimmable

Probably a different colour would be ideal since the random yellow i chose resembles masterwork too closely, which could induce more confusing ux.

Thoughts?

**Comment by dhazelett** [comment]
I definitely agree about the opacity, too.

I'm worried about adding another icon though, were very overwhelmed with them as is. I've also heard concern on other tickets about covering the expac indicator too.

I think it might be right to use a bolder, un-used color for a border.

**Comment by duckmanBR** [comment]
To "find" a item already on the compare tool, just click on their name.
Only works on desktop though.

**Comment by bhollis** [comment]
I think the whole compare feature is due for a refresh :-)
