### ISSUE TITLE
Max Power - Search variable to show gear used in calculation

### ISSUE THREAD

**Issue by boktai1000** [DestinyItemManager/DIM#3108]
I love the Max Power calculation, but I was wondering is there a way to display what gear is being used in this calculation? Clearly it's already scraping the best gear, I just want a quick way to view it all!

Ideas include something like "is:maxpower" which would highlight your maximum power gear, and you could further refine it with "is:maxpower is:warlock" or something to that affect to display it on a per class basis. Otherwise, maybe making the Max Power icon you can hover over in DIM a clickable icon that will display your max power gear.

Whatever way makes the most sense to implement I would be alright with, just though I'd propose some ideas and thoughts I've had regarding it!

**Comment by kyleshay** [comment]
I've wanted this a few times as well. Useful for Iron banner where you want to equip your highest armor, but still keep your favorite weapons / armor exotics.

**Comment by boktai1000** [comment]
I tested it and it works great! One thing I noticed, not sure if you're including all search variables there - but in the ( ? ) help section for the filters on the site when you click it, there isn't a reference to `is:maxpower` listed for reference.
