### ISSUE TITLE
Missing Some Vendor Bounties on mobile

### ISSUE THREAD

**Issue by IceNizzle** [DestinyItemManager/DIM#3109]
I am using the android mobile app or DIM on my mobile phone.  I have tested this with the regular version and also the beta version.  I have noticed that the vendor bounties for "Petra Venj" and "Suraya Hawthorne" are missing.  There could be more missing but a quick glace and I can see all the other vendor's bounties but not these.

Now if I use DIM on my pc I see all these bounties.

If you need more details just let me know.

**Comment by bhollis** [comment]
https://github.com/Bungie-net/api/issues/677

Closing since this is a bug on Bungie's side.
