### ISSUE TITLE
Recommended VS Code extensions for workspace don't cover react

### ISSUE THREAD

**Issue by liamdawson** [DestinyItemManager/DIM#3121]
Current recommendations:

```
"eg2.tslint",
"Angular.ng-template",
"mkaufman.htmlhint",
"gamunu.vscode-yarn",
"esbenp.prettier-vscode"
```

Expected ones to do with React syntax/intellisense etc.

**Comment by bhollis** [comment]
Got any suggestions? TypeScript/React are pretty well supported out of the box.

**Comment by liamdawson** [comment]
`tslint` immediately comes to mind, shall check what other ones I'd suggest when I get home.

**Comment by liamdawson** [comment]
Yeah, that was my mistake, I forgot how much was covered out of the box. Only other thing I'd recommend is the editorconfig extension.

**Comment by bhollis** [comment]
Cool, we'll consider it, though we're already using prettier to autoformat all the code.
