### ISSUE TITLE
is:randomroll not working on class items

### ISSUE THREAD

**Issue by duckmanBR** [DestinyItemManager/DIM#3124]
Can't debug, so don't know if the fault is on the API, but none of my Warlock forsaken bonds are highlighted when I use is:randomroll

**Comment by philkernick** [comment]
Just checked mine.  None of the Warlock or Titan class items are highlighted.

Most strangely, the only class items that do highlight are Hunter Prodigal Cloak and Hunter Tangled Web Cloak.  All the other Hunter class items do not highlight.

**Comment by irons** [comment]
It does appear to affect all armor, not just class items. I tried searching for `is:blue not:randomroll`, to find the easiest decisions for deletion. DIM versions 4.71.0 and 4.71.0.2393 highlight all of my blue armor items with this query (all of which is post-forsaken). E.g., Atonement Tau, Farseeker's Reach, Prophet Snow, all of which have random perks but are identified in DIM as if they don't.

**Comment by bhollis** [comment]
This should be fixed on Beta now.
