### ISSUE TITLE
Item details pop up Samsung S7 Edge issue

### ISSUE THREAD

**Issue by inexorableAce** [DestinyItemManager/DIM#3129]
Reported from discord, I can’t test this myself. 
New update cuts off the edge of the popup on my Samsung S7 Edge, it's worse in landscape mode.
![649b8e90-5fa6-40c5-b51f-58848ed36fa2](https://user-images.githubusercontent.com/29002828/45979612-94554180-c01d-11e8-9563-37ff80785c1a.jpeg)

**Comment by bhollis** [comment]
Pushing a fix to beta, can you take a look?

**Comment by inexorableAce** [comment]
I can’t myself but I’ll ask in the discord and report back.

**Comment by duckmanBR** [comment]
I was having a similar problem but with tooltips.  Fixed now.
