### ISSUE TITLE
Some icons (perks) not displaying in iOS 12.0 safari

### ISSUE THREAD

**Issue by inexorableAce** [DestinyItemManager/DIM#3133]
Not sure when this started but noticed it today. 

![2b25bb37-5841-408f-afe8-9746d6e565bd](https://user-images.githubusercontent.com/29002828/46037770-39802080-c0d7-11e8-848e-4bfa7439a9c7.jpeg)

**Comment by bhollis** [comment]
Still happening? I'm not seeing it.

It may be the new safari tracking protection though...

**Comment by inexorableAce** [comment]
Yeah it’s still happening for me. I’ll check some safari settings today and see if that’s it.

**Comment by inexorableAce** [comment]
Clearing history and website data under safari settings fixed this. So cache issue I guess. Closing it out.
