### ISSUE TITLE
search for items without a specific tag

### ISSUE THREAD

**Issue by lightmaster** [DestinyItemManager/DIM#3136]
I tag all my favorite items with the favorite tag. Now I'd like to look at all duplicate items, excluding ones tagged favorite. I tried !favorite, not:favorite, not:tag:favorite, !tag:favorite. Unless I'm missing something, doesn't seem to be a way to search for all items except a certain tag.

Also, why doesn't ! mean not? Took me the better part of a week to figure out you could search for not:. Assuming this feature gets added, I think !tag:[tag name] would be the cleanest syntax for it. not:tag:[tag name] seems a bit clustered to me. Then again having both would be even nicer, an easier way for anyone with any coding experience to search for items.

**Comment by lightmaster** [comment]
I tried the not:tagged, but I use the junk tag as well as favorite and infuse and keep. Mainly looking at a way to remove favorites items from the search, but keep junk tag so I can compare rolls for duplicate items while ignoring items that I have already decided to keep.

And yeah, I figured not: is easier for Average Joe, but don't get why both aren't supported.

**Comment by kyleshay** [comment]
https://github.com/DestinyItemManager/DIM/pull/3190
