### ISSUE TITLE
Clean up vendors broken Armor display

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#3137]
With the changes to the API in Forsaken there are a bunch of placeholder items on the Vendor page that should be suppressed.  Each vendor has an Armor category with nothing in it.

![image](https://user-images.githubusercontent.com/25425159/46122018-bf29da80-c255-11e8-8be0-0c390da35c84.png)

I can see nothing in the Bungie-net/API issues tracker that even mentions it.

**Comment by bhollis** [comment]
I was actually hoping to just link to the armor set in collections.
