### ISSUE TITLE
could you please extend the img-src CSP of the app domain ?

### ISSUE THREAD

**Issue by michabbb** [DestinyItemManager/DIM#3139]
background: there are so many tools out there to modify the CSS of an existing website. i would love to use my own background inside DIM, because of the CSP (content secure policy) this is getting tricky:

```
Refused to load the image 'https://xxxxxxx.jpg' because it violates the following Content Security Policy directive: "img-src 'self' data: https://www.bungie.net https://ssl.google-analytics.com https://www.google-analytics.com https://csi.gstatic.com https://opencollective.com https://syndication.twitter.com https://platform.twitter.com https://*.twimg.com/ https://beta.destinyitemmanager.com".
```

if you could add:

flickr: `https://*.staticflickr.com/`  
google photos: `https://*.googleusercontent.com/`  

we wouldn´t be forced to upload the image to twitter because you allow *.twimg.com 😏 

thanks !

**Comment by bhollis** [comment]
Hi Michael,

I feel for you, but our CSP is for our protection, and we won’t maintain exceptions for content that’s not part of the app.

**Comment by michabbb** [comment]
I understand, but then you need to remove twimg too. So right now everybody can use external images that are not part of your app anyway, Twitter is not part of your app, not really,but you allow it for advertising, that's okay of course. But adding Flickr would break anything because you already allow Twitter images. That would give us a hughe benefit in styling

**Comment by bhollis** [comment]
We use twimg because we have a twitter feed widget on the “what’s new” page. We never do any advertising.
