### ISSUE TITLE
How to get it up and running locally?

### ISSUE THREAD

**Issue by melanieseltzer** [DestinyItemManager/DIM#3141]
Hi! I've forked and cloned this repo to try get set up locally just to play around. I'm a Docker newbie and I might not be understanding the instructions in the contributing doc.

After running `docker-compose up` I get the following output:

<img width="1052" alt="screen shot 2018-09-27 at 5 10 40 pm" src="https://user-images.githubusercontent.com/17421347/46180983-51db7100-c278-11e8-85ad-8ba644081b4d.png">

And the container seems to be running:

<img width="1268" alt="screen shot 2018-09-27 at 5 11 15 pm" src="https://user-images.githubusercontent.com/17421347/46181003-60298d00-c278-11e8-8523-2e162a03c504.png">

But how to access the site locally, after doing that?

`https://localhost:8080` from the Webpack output doesn't load.

Followed a Youtube guide and tried this:

<img width="918" alt="screen shot 2018-09-27 at 5 16 30 pm" src="https://user-images.githubusercontent.com/17421347/46181178-1e4d1680-c279-11e8-82d8-aa013c71a50e.png">

`https://localhost:46753/` doesn't load.

Help? 🤔

**Comment by delphiactual** [comment]
Did you try https://localhost:8080 like it states in your output?

**Comment by delphiactual** [comment]
@longlivechief @0sanity

**Comment by SunburnedGoose** [comment]
They said they did in the email.

**Comment by melanieseltzer** [comment]
Yup. After running `docker-compose up` and getting the Webpack output (_Compiled successfully._ etc), navigating to localhost:8080 produces:

<img width="680" alt="screen shot 2018-09-27 at 5 29 27 pm" src="https://user-images.githubusercontent.com/17421347/46181503-10989080-c27b-11e8-8914-2b45611fcdc7.png">

**Comment by LongLiveCHIEF** [comment]
go ahead and assign to me.

**Comment by kyleshay** [comment]
Hmm, sorry you're not able to get it up and running @melanieseltzer! We've just pushed an update in the past week to use docker so there must not have been a lot of people able to test it out yet. 

I just noticed that our [developer quick start](https://github.com/DestinyItemManager/DIM/blob/master/docs/CONTRIBUTING.md#developer-quick-start) steps don't include running `yarn start`... that's how I run things locally:

clone, `yarn install`, `yarn start`

**Comment by LongLiveCHIEF** [comment]
> I just noticed that our developer quick start steps don't include running yarn start... that's how I run things locally

@kyleshay they're at the bottom. I should probably clean things up a bit though, since I can see how it's confusing as is.

@melanieseltzer I have a PR with a fix for this issue in #3142

**Comment by 0sanity** [comment]
The `docker-compose up` command will automatically run `yarn start`

The http service was removed from the compose file in this commit
https://github.com/DestinyItemManager/DIM/commit/55358db06b22409d136d562ca2e80ae735f9c201#diff-4e5e90c6228fd48698d074241c2ba760

I'm making an assumption that an http service is now included in the `yarn start` command and bound to port 8080 which means a port mapping directive needs to be added to the compose file to expose the port so it is accessible by the host

This pull request does just that https://github.com/DestinyItemManager/DIM/pull/3142/files

Thanks @LongLiveCHIEF for taking care of that

**Comment by melanieseltzer** [comment]
Thank you everyone! #3142 fixes it for me and I'm up and running locally 🎉
