### ISSUE TITLE
feature request: upload background image + edit some basic styles like title

### ISSUE THREAD

**Issue by michabbb** [DestinyItemManager/DIM#3144]
so everybody could be able to personalize his DIM like this:

![28-09-2018-01-15-46](https://user-images.githubusercontent.com/3524595/46205364-9c182d00-c320-11e8-8080-23c5e5c76979.png)

**Comment by SunburnedGoose** [comment]
#3139.

**Comment by SunburnedGoose** [comment]
There is no plan to host these images, or to proxy images into the app.

**Comment by michabbb** [comment]
hosting:

there is no need for hosting, as i can already use twitter images, so why not flickr or google photos or imgur, for you it´s only some words in the CSP but for the whole destiny community it would be a hugh benefit, i cannot understand why you guys have such a rejective attitude to that 😢 

title: 

we talk about two form fields inside the settings that change two css rules

the point is, it´s not a big deal and you know that, a pity.
