### ISSUE TITLE
is:hasmod filter doesn't seem to catch all modded weapons (Beta)

### ISSUE THREAD

**Issue by Neurosion1** [DestinyItemManager/DIM#3145]
There are a few modded weapons in my inventory that aren't included with the hasmod filter. The two weapons that have jumped out at me (because they're my go-to weapons these day) are a Bygones with a "Minor Spec" mod and a Badlander with a "Major Spec" mod.

From what I can tell, all of my armor mods have been detected correctly.

**Comment by Neurosion1** [comment]
Apologies for being a nosy bastard, but it looks like the issue is that these mods (minor spec, major spec, and boss spec) are categorized under v400.weapon.mod_damage but hasMod() is looking for (v400.weapon.mod_guns|enhancements). Presumably the fix is simply to change that to (v400.weapon.mod_guns|v400.weapon.mod_damage|enhancement). Not sure where to check if there are other v400.weapon.mod_ categories.

**Comment by bhollis** [comment]
Thanks for digging in! That change makes it work a bunch better.
