### ISSUE TITLE
Perks fail to display on exotic gloves

### ISSUE THREAD

**Issue by mistral13** [DestinyItemManager/DIM#3148]
Hi

The second row of perks fail to display on exo gloves.
![7cd5d946-8b4f-424e-83e5-512effb49ee4](https://user-images.githubusercontent.com/5049663/46242075-1d74cb80-c3c4-11e8-8561-28de8b199fe8.jpeg)

**Comment by bhollis** [comment]
What should it look like?

**Comment by mistral13** [comment]
Sorry column not row
![44037c03-deca-405b-ab3b-12785176a5e1](https://user-images.githubusercontent.com/5049663/46250269-4aae9180-c437-11e8-8cd4-1b7584b7c067.jpeg)

**Comment by mistral13** [comment]
Sorry. Wrong button
