### ISSUE TITLE
connection issues

### ISSUE THREAD

**Issue by githubDemoAccount-SD** [DestinyItemManager/DIM#3149]
Firstly, LOVE the app! Could not play D2 without it. 

I use the chrome extension [app v4.71.0 on Chrome v 69.0.3497.100] on macOS 10.13.3

Lately, I've been getting a LOT of connectivity issues from DIM. Errors like:

```
Bungie.net Error
Bungie.net servers are down for maintenance.
Get status updates on: Twitter 


Bungie.net Error
Bungie.net message: Time out during communication with the game servers. 
Please try again later
```

I know it's not my internet connection. Everything else is fine, and I get a steady 50mB/s over a wired connection

I this a known issue?

Thanks

**Comment by bhollis** [comment]
Bungie servers have been down for maintenance a lot recently.
