### ISSUE TITLE
daily gambit milestone not showing on progress page

### ISSUE THREAD

**Issue by onching** [DestinyItemManager/DIM#3150]
today daily gambit milestone was reset. it shows on ps4 destiny 2 director but not on the milestones & challenges section of the progress page.

**Comment by onching** [comment]
just checked companion app on iphone. It shows the daily gambit milestone. The daily heroic story was also listed in the companion app, but missing from the dim progress page as well.

**Comment by bhollis** [comment]
Hmm, I see what's happening - we filter out milestones that have no reward, and these don't for some reason (a bug in the data).
