### ISSUE TITLE
on docker-compose up: error Couldn't find a package.json file in "/"

### ISSUE THREAD

**Issue by Lalo-ATX** [DestinyItemManager/DIM#3151]
Fresh debian 9.5 install, docker-compose version 1.23.0-rc1, I get this error when I run docker-compose up:

```Starting dim-webpack ... done
Attaching to dim-webpack
dim-webpack | yarn install v1.9.2
dim-webpack | [1/4] Resolving packages...
dim-webpack | success Already up-to-date.
dim-webpack | Done in 0.11s.
dim-webpack | yarn run v1.9.2
dim-webpack | error Couldn't find a package.json file in "/"
dim-webpack | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I asked about this in #development-questions in discord and someone there suggested I open an issue for it.

**Comment by delphiactual** [comment]
@LongLiveCHIEF @0sanity

**Comment by LongLiveCHIEF** [comment]
Very strange. I wonder if this has anything to do with 1.23-rc1? I ran it with 1.22 and 1.21.  Let me do a little testing to see if I can reproduce.  My gut says it has to do with user/permissions, but I'd like to repro to be sure.

**Comment by LongLiveCHIEF** [comment]
Works perfectly on my machine (always does right?), so I'm spinning up a Debian 9.5 droplet and going to test from there using compose 1.23-rc1. I'm assuming you were using Docker 18.06.1-ce? Anything else about your setup I should know?

**Comment by LongLiveCHIEF** [comment]
Confirmed. I just repro'd on a fresh Debian 9.5 install, exactly as reported above, using compose `1.23.0-rc1`. Moreover, it errors with `1.22.0` as well.

The differences I can see at glance between my droplet and my local machine are just permissions. The droplet I'm logged in as root, and all the files in the `/DIM` dir are also owned by root, whereas on my local machine files are owned by a non-root user.

**Comment by LongLiveCHIEF** [comment]
I just created #3154 to help avoid some of the things that were confusing some first-time contributors. This bug has a low priority for now, and a fix won't be immediately incoming as I need to do some research on it. The particular scenario needed to encounter it is going to be very low, and we only ran into it because of some confusion created by the ordering of info in our contributing docs.

**Comment by 0sanity** [comment]
@LongLiveCHIEF try adding `working_dir: /usr/src/app` before the `command:` in the docker-compose.yml file.

Also in other projects I've had to change `npm install` to `npm install --unsafe-perm=true --allow-root` not sure if that applies to yarn but it might help you find a solution

**Comment by kyleshay** [comment]
Is this still an issue @Lalo-ATX - were you able to get this up and running?
cc @LongLiveCHIEF @0sanity

**Comment by 0sanity** [comment]
I made some improvements in this pull request to possibly address these issues
https://github.com/DestinyItemManager/DIM/pull/3370

Please make sure you are using the latest version of docker

**Comment by kyleshay** [comment]
Thanks 0sanity!
