### ISSUE TITLE
Proposed new filter count:

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#3157]
We can currently search for duplicates with is:dupe.  I'm proposing an extension of this to be a number filter called count: which will return true if there are the number of duplicate items.

So:
count:=1  is the same as not:dupe
count:>1 is the same as is:dupe

But it would become possible to ask which items I have more than 3 of the same:
count:>3

**Comment by kyleshay** [comment]
I think the best way to deal with > 2 dupes is to use the compare tool, as it automatically populates with all dupes. That way you can do `is:dupe`, click an item, hit compare, then tag things for deletion.

Unless there is a different problem you're trying to solve?

<img width="1030" alt="screen shot 2018-10-01 at 7 47 33 pm" src="https://user-images.githubusercontent.com/424158/46326704-e9abc880-c5b2-11e8-8fcd-248f83684dd2.png">

**Comment by philkernick** [comment]
I’m trying to solve the problem that happens before I use the compare tool!

Specifically which weapons do I have a bunch of that need cleaning up. Just using is:dupe requires me to check each individual item in the compare tool.
