### ISSUE TITLE
Loadout Builder enhancements

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#3164]
This issue is for tracking minor/general enhancements or bugs to the Loadout Builder

If you'd like to test the loadout builder on the beta client, manually change your URL from `/inventory` to `/loadoutbuilder`

- [x] Ammo icon perk in the perk selector to show color on the armor, since all icons are the same 
- [x] Option for picking burn modifier
- [x] Show power level with minimum power level filtering

**Comment by philkernick** [comment]
It would be good if each loadout showed its effective power level.  In addition and in the same theme, next to the build tier selector we could use minimum power filter to limit the displayed loadouts to ones that are above a threshold.  As the game has recommended end-game activity power tiers of 500/520/540/560/580/590 these seem like obvious choices.

**Comment by kyleshay** [comment]
good idea! I was thinking about doing it two different ways. 
1) pull your highest power weapons and use them to figure out your max-light for that armor set
2) have a version that is your power level that excludes items. 

The new way of computing light level is just a straight average of your items, so either way would be simple. just not sure what would make the most sense. definitely think that it would be important to show and have a filter for! Right now we sort the sets generated by light level so we already have the info.
