### ISSUE TITLE
DIM Background or Lettering

### ISSUE THREAD

**Issue by SenICEMAN** [DestinyItemManager/DIM#3167]
"When I do Comparisons (button provided), the RED is very dim/blurred. I tried to use the Color Blindness setup, but when I select Compare all Scouts, the RED is very hard to read. Contrary though, IF I Manually compare by selected each Weapon, i can read the Numbers fine using the color blindness setups. Can the background of the APP be changed ? Any suggestions ? "

**Comment by SenICEMAN** [comment]
Where is that done ?

**Comment by inexorableAce** [comment]
We do that. 
here is the proposed background change to #222;
![image](https://user-images.githubusercontent.com/29002828/46443009-b778a300-c739-11e8-8f8b-b30b7beed8a6.png)

I also just noticed the red is actually partially transparent...
![image](https://user-images.githubusercontent.com/29002828/46443033-c9f2dc80-c739-11e8-8f71-058a4fa6ab14.png)

we should likely change that too: here is the red lettering on the number 60 changed to rgba(255,0,0,1)
![image](https://user-images.githubusercontent.com/29002828/46443102-13432c00-c73a-11e8-82cd-66ac5811fb3f.png)
