### ISSUE TITLE
Multiple negative exact match filter problems

### ISSUE THREAD

**Issue by joshhunt** [DestinyItemManager/DIM#3177]
there appears to be problems when you have multiple negative match filters

e.g. `is:rocketlauncher -"cluster"  -"tracking module"` While you would expect this to  return rocket launchers that don't have cluster bombs or tracking, it in fact only matches rocket launchers with tracking module

`is:rocketlauncher  -"cluster"  -'tracking module'` this however, works as expected.

`is:rocketlauncher  -"tracking module"` works as expected

**Comment by bhollis** [comment]
All terms are  always AND. We haven’t implemented OR yet.

**Comment by bhollis** [comment]
It's because our regex for extracting terms is busted: https://regex101.com/r/IAvMAQ/1
