### ISSUE TITLE
Loadouts "missing" after using beta loadout builder

### ISSUE THREAD

**Issue by ArkahnX** [DestinyItemManager/DIM#3188]
I'd like to be able to recreate this, but for now what appears to have happened, was I had some loadouts I had created, I then created something using the loadout builder and clicked "equip on character"

Since then, previous loadouts no longer show up, and creating a new loadout from the inventory screen also does not appear to save

Now I'm going to see if I can reproduce this

**Comment by ArkahnX** [comment]
Looking at the console for a local build of the master branch as of October 7, it looks like the "platform" property isn't being set, but the loadout is indeed being saved

Perhaps because of the undefined platform it simply isn't showing up in the UI?

**Comment by bhollis** [comment]
Thanks for the info!

The error you posted is unrelated (a bug in Loadout Builder itself). I'll take a look at why `platform` isn't being set, though.

Don't forget that if you had GDrive set up, you can go back and restore earlier versions of your data, so you should be able to get back your old loadouts.

**Comment by ArkahnX** [comment]
Yeah sorry, this ended up being a couple issues in one.  Good advice on the Google drive backups, didn't consider that! Gave me an excuse to update my loadouts anyways though

**Comment by bhollis** [comment]
OK, I think I've fixed it in beta - let me know if it still isn't working right.

**Comment by ArkahnX** [comment]
Looks like its fixed on the master branch for new loadouts at least. As far as I can tell this build hasn't made it's way to the beta website yet; loadouts still don't show up

**Comment by bhollis** [comment]
Yeah, I don't think it'll make your old loadouts show up... you'll have to restore data in order to do that.

**Comment by ArkahnX** [comment]
For reference I'm using v4.72.0.2430 from 10/7/2018 3:30:35 and new loadouts don't show up

Old ones I would expect to be missing since they have a platform of "undefined"

**Comment by bhollis** [comment]
OK, new loadouts not showing up is a new thing to me. Can you export your dim-data.json and send it to me as a gist or something?

**Comment by ArkahnX** [comment]
[Here is the gist](https://gist.github.com/ArkahnX/69792473f393726457d4f7bdda328c36) for the beta website

[This is what I have from my local copy of the master branch](https://gist.github.com/ArkahnX/2f450b652b201440c56818a6a1068089) (up to date as of 11 minutes ago)

**Comment by bhollis** [comment]
Oh, the build was broken. A real build is going out now.

**Comment by ArkahnX** [comment]
Confirmed that it works again! Thanks a bunch
