### ISSUE TITLE
DIM Fails to Load Items

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#319]
There is a condition where DIM will load slowly in a way that prevents an event from firing to kick off the downloading of a players gear.

**Comment by bhollis** [comment]
Any extra info on what causes this?

**Comment by SunburnedGoose** [comment]
I think it results from parts of the app missing an event from the services because they load too quickly.  The behavior is ephemeral.

**Comment by SunburnedGoose** [comment]
Fixed this error by adding flag to capture the change in platform that might occur before dimStore is loaded.
