### ISSUE TITLE
Editing Loadouts

### ISSUE THREAD

**Issue by johnnyphive** [DestinyItemManager/DIM#3192]
When attempting to edit a loadout, the "name" field is not populated, prompting to "Please fill in this field".  I've attempted doing this a couple of times, but even upon trying to edit again, it still fails to pull the previously set name.

Chrome OS 69.0.3497.95

**Comment by bhollis** [comment]
That's a bummer. I'll take a look tonight!

**Comment by bhollis** [comment]
I was able to fix this - going out to beta and release now!
