### ISSUE TITLE
Issue with "Manifest version mismatch" on beta website

### ISSUE THREAD

**Issue by ArkahnX** [DestinyItemManager/DIM#3197]
I've included the full console log, but essentially I updated to the latest version of the beta website, and it started throwing character not found errors.

Cleared all application data for beta.destinyitemmanager.com from the devtools application tab, then the following gallery is the result.

[Gallery](https://imgur.com/a/3kV0teN)

**Comment by bhollis** [comment]
Take another look? There was an issue that got fixed.

**Comment by ArkahnX** [comment]
The latest build "Version 4.73.0.2448 (beta), built on 10/8/2018, 10:47:37 PM" still has this issue, unless I have yet to get a new update

**Comment by ArkahnX** [comment]
Spoke too soon. now using "Version 4.73.0.2450 (beta), built on 10/8/2018, 11:23:17 PM", cleared all of my application data again and the same issue still persists

**Comment by bhollis** [comment]
Hmm, in that case it may be caused by clearing data. I’ll have to investigate more. Lotss of stuff changed on beta today.

**Comment by ArkahnX** [comment]
To be clear I used the Application tab clear storage option, with everything selected

Let me know if there is anything else I can provide!

**Comment by bhollis** [comment]
Gotcha, that didi it.

Fix is going out in this build: https://travis-ci.org/DestinyItemManager/DIM/builds/439012277
