### ISSUE TITLE
Pull from Postmaster Enhancements

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#3199]
- [x] Items that `haveSideEffects: true` should have an overlay to indicate that. #3209
- [x] Make room for Postmaster should still make room for item that `haveSideEffects: true` #3487

**Comment by bhollis** [comment]
Good ideas. How do you think we should communicate that something isnt pullable?

**Comment by kyleshay** [comment]
Maybe in place of the move icons, so if you click it you see?

**Comment by inexorableAce** [comment]
We have these grouped in the postmaster section already, just labeling those groups would go a long way.

**Comment by bhollis** [comment]
We don’t have them grouped, which doubly suggests we should label the groups.

**Comment by inexorableAce** [comment]
oh.. what are the two groups now then? I assumed they were pullable and non? is it engrams and other?

**Comment by duckmanBR** [comment]
Yeah, engrams and postmaster

**Comment by inexorableAce** [comment]
ahh yeah that's confusing since some engrames end up in the postmaster. Engrams that are just chilling should be somewhere else they aren't even in your postmaster...

**Comment by bhollis** [comment]
We decided to move them up to postmaster because they’re something you’ll want to remember to grab. It’s essentially just another postmaster bucket.

**Comment by inexorableAce** [comment]
yeah that makes total sense, just need to label them, but also you could do something like this. excuse the crude MS paint mockup. 
![image](https://user-images.githubusercontent.com/29002828/46961837-ac920c80-d06f-11e8-87bc-47b14a9785de.png)

**Comment by SentryTheDefiant** [comment]
Kind of a tangent to the discussion, but still a postmaster enhancement. I think shaders could use some love. I feel like when I pull a shader from the postmaster, it would be more efficient if it automatically consolidated that type of shader to where you are already storing the majority of that shader. 

Example: new shader or one you carry many of on character, it stays there. If you stockpile it in the vault, automatically move the shaders pulled from postmaster to vault.

Its a small QOL improvement, but it would keep shaders from going to postmaster by not having shaders all willy-nilly in two places.
