### ISSUE TITLE
Occasionally unable to apply loadouts using Loadout builder

### ISSUE THREAD

**Issue by joshhunt** [DestinyItemManager/DIM#3200]
Occasionally, I get "error applying loadout: unable to equip item to dequip blah" when applying loadouts using the new Loadout Builder (which is great FYI).

It was happening pretty consistently before, and now its not happening, but i thought i would make this issue just to give it some visibility. Ill comment with more details if I get some :)

**Comment by bhollis** [comment]
This was definitely a bug but it’s been fixed - let me know if it still happens.

**Comment by joshhunt** [comment]
I get a variation of this now every now and then when it'll instantly say "successfully transferred loadout of blah items" except it wont actually transfer / equip them. I think all the items were on my character, but not all were already equipped.

**Comment by joshhunt** [comment]
I still get this. 
<img width="1440" alt="screenshot 2018-10-13 at 10 42 55" src="https://user-images.githubusercontent.com/46142/46903959-f2669d80-ced4-11e8-8af3-37a59d6786f4.png">

I created a loadout from this, and switch to inventory screen and it would show the same error messages when applying it. After refreshing the browser page i could apply it.

**Comment by kyleshay** [comment]
I was seeing this as well, hasn't happened in a while. Re-open if it's still happening, thanks for reporting!
