### ISSUE TITLE
Vendors page shows incorrect number of packages obtainable with tokens 

### ISSUE THREAD

**Issue by inexorableAce** [DestinyItemManager/DIM#3202]
![image](https://user-images.githubusercontent.com/29002828/46731674-4feeb600-cc59-11e8-86d4-230dd76cc4a7.png)

I believe this is due to the changes with forsaken, but I was only able to get 2 packages not 3. Probably just need to adjust the number of tokens it costs for a package now.

**Comment by duckmanBR** [comment]
All our math is based on data from the API.  Unless the math changed it shouldn't be off.
Are you sure you didn't forget some tokens/materials in the vault?

**Comment by bhollis** [comment]
3 is your rank with the faction, not how many engrams you can get.

**Comment by duckmanBR** [comment]
This issue comes from discord (without numbers/examples).  I'll try to find if the user did the same mistake as Ace... :sweat_smile:

**Comment by inexorableAce** [comment]
haha yep, that makes sense... maybe a design opportunity then to reduce ambiguity :P

**Comment by bhollis** [comment]
We should add the actual number of engrams you can get, and change the faction rank to a circle or something.

**Comment by inexorableAce** [comment]
Think we determined this wasn’t an issue. We can loop back to the packages display design talks later.
