### ISSUE TITLE
Armor Inventory Export Missing Columns

### ISSUE THREAD

**Issue by m-s-y** [DestinyItemManager/DIM#3206]
Everything in the | Int | Disc | Str | columns in an armor export is a zero.  Accurate as of Version 4.73.0.2454 (beta)

**Comment by 48klocs** [comment]
@m-s-y to double check since I'm unclear, you are not seeing any values being exported in beta when exporting Destiny 1 armor? D2 doesn't have those stats (but we still show those headers and I guess zeroes in those columns).

**Comment by bhollis** [comment]
@m-s-y could you clarify your request?
