### ISSUE TITLE
Loadouts: Create loadout from currently equipped

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#321]
It'd be nice to be able to create a new loadout that's already populated w/ the items that character has equipped.

**Comment by kyleshay** [comment]
Maybe a select to include just armor, just weapons, or both... and eventually to include consumables (and how many) of each.

When we save it, be able to name it and apply to just characters of that class, or all.

could start simple and add functionality as we build it out.

**Comment by bhollis** [comment]
Heh, I forgot that I'd asked for this. I also implemented it :-)
