### ISSUE TITLE
Loadout Builder Error with Characters that have no Items

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#3219]
I have a titan that has very few items.  In fact, it only has equipped items.  When I open Loadout Builder, and try to lock an item, I get a hard error.

![screen shot 2018-10-14 at 8 28 46 pm 2](https://user-images.githubusercontent.com/984608/46925137-ffc47a80-cfef-11e8-8a71-c95929652d88.png)

**Comment by SunburnedGoose** [comment]
![screen shot 2018-10-14 at 8 28 46 pm](https://user-images.githubusercontent.com/984608/46925168-19fe5880-cff0-11e8-9cfc-a1575495e5ee.png)

**Comment by SunburnedGoose** [comment]
Items is undefined.

![screen shot 2018-10-14 at 8 32 19 pm 2](https://user-images.githubusercontent.com/984608/46925210-4ca85100-cff0-11e8-901c-2d36073d5388.png)

**Comment by kyleshay** [comment]
Resolved in #3260 as we now have an option to include all items in an expanded search.
