### ISSUE TITLE
Mouse Over Blue Popup Spawns Many Digest Cycles

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#322]
This is not good :/

![image](https://cloud.githubusercontent.com/assets/984608/10688161/f6bad680-7937-11e5-8ddf-30c95e679cc6.png)

**Comment by cdacamar** [comment]
Hmm, [this](https://www.binpress.com/tutorial/speeding-up-angular-js-with-simple-optimizations/135) might be relevant in speeding this up.  Looking and AngularJS-Toaster it looks like the callback to reset the timer is using a `ng-mouseover` callback:

in `https://github.com/DestinyItemManager/AngularJS-Toaster/blob/master/toaster.js#L448`
```javascript
'<div ng-repeat="toaster in toasters" class="toast" ng-class="[toaster.type,toaster.stopTimerClass]" ng-click="click(toaster)" ng-mouseover="stopTimer(toaster)" ng-mouseout="restartTimer(toaster)">'
```

They could have used `ng-mouseenter` instead, that would save a lot of $digest() calls if the user runs the cursor all over the dialog.  That's the first thing that stands out to me.

**Comment by SunburnedGoose** [comment]
I'm pretty sure I wrote that :/

**Comment by cdacamar** [comment]
@SunburnedGoose I'm pretty sure it's like that in the main repo too :)

`https://github.com/jirikavi/AngularJS-Toaster/blob/master/toaster.js#L461`

At any rate, once I switch to `ng-mouseenter` and `ng-mouseleave` respectively a lot of those `$digest()` calls went away.

**Comment by SunburnedGoose** [comment]
Whew :)

**Comment by bhollis** [comment]
Looks like this got fixed to use ng-mouseenter and ng-mouseleave, so it's not an issue anymore.
