### ISSUE TITLE
Character Drop-down Not Scrollable

### ISSUE THREAD

**Issue by ViPER-XEd** [DestinyItemManager/DIM#3221]
I'm not exactly sure when this started (recently, though), but at least in firefox the character drop down menu where the loadouts, etc. are listed cannot be scrolled. Every other item in the list can be properly clicked and used, except for the scroll bar or scroll arrows. When those are clicked, it closes the drop-down as if you clicked outside of it. The scrollbar does highlight on mouseover, but it appears to fail to see it as a clickable object and instead results in closing the menu.

**Comment by bhollis** [comment]
Thanks for the report! The fix should be available shortly.
