### ISSUE TITLE
403 When attempting to access DIM App

### ISSUE THREAD

**Issue by Saucermote** [DestinyItemManager/DIM#3232]
# **Admin note:** DIM is down due to our hosting provider getting overwhelmed. We are waiting for them to re-enable our account.

When attempting to access the DIM app in my chromium browser it just gives me the 403 page (launching through the extension or the webpage), where it previously worked.  I've tried clearing my DIM/bungie cookies, but it only increases the time before it cycles back to the error. 

"It appears you don't have
permission to access this page.
403 Error. Forbidden."

Edit: Anyone browsing here randomly after finding a non-working app/extensions, see this reply by delphiactual:

[https://github.com/DestinyItemManager/DIM/issues/3232#issuecomment-430038671](https://github.com/DestinyItemManager/DIM/issues/3232#issuecomment-430038671)

**Comment by NoahLitwiller** [comment]
Same issue here, using stock chrome browser. Log in/sign in options are not visible on destinyitemmanager.com

**Comment by evmike** [comment]
I also am currently have the same issue. I noticed at the bottom of the Battle Net launcher there was a message claiming Battle Net was "currently investigating reports of issues connecting to and using various social features." I contacted Battle Net via chat and got the message cleared up, but I'm still receiving the 403 message when trying to launch DIM in any browser.

**Comment by delphiactual** [comment]
app.destinyitemmanager.com is currently down, you can use beta.destinyitemmanager.com until app is restored.

**Comment by Saucermote** [comment]
Thanks, will do.

**Comment by edmiller47** [comment]
Same problem with Chrome on my iPad and iPhone, but it's working fine on my laptop.

Beta site works fine on all three.

**Comment by delphiactual** [comment]
https://twitter.com/ThisIsDIM/status/1051963358654681097

**Comment by edmiller47** [comment]
And all of my loadouts have vanished...

**Comment by delphiactual** [comment]
loadouts do not persist between app.destinyitemmanager.com and beta.destinyitemmanager.com

**Comment by edmiller47** [comment]
So is it safe to assume that whenever this is resolved, my loadouts will return?

**Comment by bhollis** [comment]
They are on app.destinyitemmanager.com. So when that is back, your loadouts will also be there.

**Comment by edmiller47** [comment]
Great, thanks for the response
