### ISSUE TITLE
Inform users when parts of the API are unavailable

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#3238]
- [x] Place a banner on the item popup when perks/mods are not available. #3442

- [ ] Vendors subpage should be disabled or place a banner on vendors.html when vendors is down.

**Comment by inexorableAce** [comment]
Yeah this would be nice now that they aren’t shutting the whole api off anymore. The whole bungie alert thing just isn’t cutting it. But then again... this probably won’t either XD

**Comment by bhollis** [comment]
This would be great! I don’t know if we get specific info about them being missing though. They’re just... not there.

**Comment by duckmanBR** [comment]
Can't we ask bungie for a flag on one of their ends?

**Comment by delphiactual** [comment]
We could "assume" if globalalert exists and no perks that perks is down, same for vendors...

**Comment by duckmanBR** [comment]
I was going to say that, since other than (some) emblems, all instanced items have perks. So we would need to check an item.

**Comment by 48klocs** [comment]
https://github.com/Bungie-net/api/issues/731#issuecomment-430832702 - from follow-up with vthorn, more endpoints are going to start to return error codes (`503`) during maintenance/high load windows.

I can't speak to when that will land in BNet, but it's on the horizon.

**Comment by bhollis** [comment]
Closing since we didn't get complaints in the last update since I merged the missing socket warning.
