### ISSUE TITLE
Filter for rewards on Progress page

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#3240]
With all the pursuits and daily/weekly tasks the progress page is starting to suffer from information overload.

My use-case for the page is "what do I need to do to level up".

I propose a reward tier drop-down filter for the page with the options: All / Legendary / Powerful / Luminous.  This would hide all the items that didn't meet the minimum reward tier.

So I could say "what do I need to do that drop at least Powerful rewards" and it would show me only that.

Before anyone says it, I fully understand that not all Milestones return their reward class in the API (example "Guardian of All"), but I think this should be raised as an API bug.

**Comment by philkernick** [comment]
We can always raise those with @vthornheart-bng.  :-)

**Comment by philkernick** [comment]
Instead of a filter, now that we have multilevel lists (like in Triumphs), how about a multilevel list of pursuits.

**Comment by Tsothoga** [comment]
I'd like to add my vote to this Feature Request.

Being able to filter by "Powerful Rewards" or "Enhancement Cores" would be great for hiding the mountain of bounties that are only worth tokens, glimmer, Infamy, etc.

**Comment by vthornheart-bng** [comment]
What I'd really love to do if we have the time would be to change the API from returning these dummy items/in addition to returning those items to returning something more useful - because I know that, even within the bounds of "powerful rewards" there's a wide range.  Like some rewards give items with 5 light higher than your current level, while others 1 or somesuch.  Unfortunately we don't have a good way to automate that, but there's a small enough subset that it might be worthwhile to make our own configuration to return that sort of data.

The sad part about the current situation though is that we don't have the time or resources to make/continue to maintain such a change on the API side at this time.  But if that situation ever changes, this would certainly be a quality of life benefit that I think would potentially be significant.

**Comment by Tsothoga** [comment]
Funny that you should mention that. A while back, I built a spreadsheet that tracked the difference between a +1 and a +5 reward, so you could optimize which powerful rewards you sought out at any given time, based on the soft cap of the activity and what your light level is. It was quite accurate, up until Bungie started fudging things in Black Armory. That was when they started tweaking the rules for some rewards: all +1s turned into +2s, the Clan XP reward typically gives +3 all the way to max light, and raid rewards that you are under the soft cap for give about a 7.5 reward, etc.

Right now, as of 2.2.0, items are back to giving +1 or +5, respecting the soft caps, but almost all Weekly and Daily Milestones seem to be soft capped at 650, which Bungie has indicated may be a bug, in which case, those could change to 690 on Tuesday with 2.2.1.

Anyways, take a look here, if you want to see what a non-developer's take on a tool like this looks like:
https://docs.google.com/spreadsheets/d/1tg1uDdsudOP-3he2-kqtOKVBr-iF6tbV4XzIGrPPkus/edit?usp=sharing

**Comment by vthornheart-bng** [comment]
Aye, that shifting of bonuses is the kind of nasty little tweak that makes me nervous about signing up to return it as part of the official API info.  The secret sauce that is this reward data is unfortunately opaque enough that we don't have a good way to automate returning this information, and thus if the people tweaking those rewards don't keep in close contact with us something's bound to fly under the radar.  Yuck. :(  However, if we had more resources to devote to the API someday(tm), then signing up for such work would be more palatable.  Or perhaps even spending the time to try and mine out/interpret the reward data - though I don't know how deep that rabbit hole goes.

This may be one of those things that the community itself will have to curate until we get more resources to work on it.  I'd hate for it to end up being one of those things that we sign up to do and then don't have the time to properly maintain (*cough* activity modes *cough*) ;)

**Comment by philkernick** [comment]
It's a new season and there are even more ways to level up now, so I'm just quietly bumping this one again.

**Comment by kyleshay** [comment]
could link up quest hashes with rewards in the d2-additional-info project

**Comment by bhollis** [comment]
We have `is:powerfulreward` which I think hits the rewards most people care about, and we've added extra details as well like what bonus each engram is. I'm not sure we still need search terms for this?

**Comment by philkernick** [comment]
We now have is:powerfulreward and is:pinnaclereward that work on the progress screen, and that is a great solution to what I was really looking for when I opened this PR.
