### ISSUE TITLE
Beta not loading on iPad iOS 10.3.3

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#3247]
The titlebar loads, then the spinner in the titlebar starts, then the titlebar disappears and nothing else renders. 

Fully reset the safari cache, but it still won’t load.

**Comment by bhollis** [comment]
![](https://files.slack.com/files-pri/T0417CH7T-FDGB9M55K/screen_shot_2018-10-17_at_10.06.56_pm.png)

**Comment by bhollis** [comment]
Sentry issue: [DIM-4YJ](https://sentry.io/destiny-item-manager/dim/issues/719932111/)

**Comment by bhollis** [comment]
I'd expect our support for iOS 10.3 to be spotty going forward - there are a lot of bugs in that version of Safari, and we don't have a great way to test it continuously.

**Comment by philkernick** [comment]
With the latest updates the beta isn't loading on 10.3.3.

I think with the release of DIM 5, it might be time to end support for iOS 10.3.

**Comment by bhollis** [comment]
Hmm, testing it in the simulator it actually does load.
