### ISSUE TITLE
Festival of the Lost items do not appear in DIM

### ISSUE THREAD

**Issue by asiansteev** [DestinyItemManager/DIM#325]
Masks and consumables aren't appearing in DIM.
in this case, each character has a mask in the inventory and the far left character is wearing a mask.
![screen shot 2015-10-26 at 1 55 49 pm](https://cloud.githubusercontent.com/assets/20084/10737566/561e5256-7be9-11e5-91c6-6aa1dd2fb92a.png)

here, each character is missing all their goodies including glimmer chews, flight of shadows and one tiny box of raisins for each character
![screen shot 2015-10-26 at 1 55 49 pm](https://cloud.githubusercontent.com/assets/20084/10737606/83e4c92c-7be9-11e5-8e8f-51e69003944d.png)

**Comment by kyleshay** [comment]
If someone could open their developer console and provide us with with any logging information, please do!

**Comment by SunburnedGoose** [comment]
I looked into this and the items are not being sent from the endpoint.  It's as if they don't exist at all for DIM now.

**Comment by kyleshay** [comment]
We're looking in to it... thanks for the report :)

:+1:

**Comment by kyleshay** [comment]
fixed with v3.1.16! :+1:
