### ISSUE TITLE
is:DupePerks

### ISSUE THREAD

**Issue by SentryTheDefiant** [DestinyItemManager/DIM#3255]
It would save users a good deal of time, especially when sorting Ghosts to introduce a Is:DupePerks that compares only the functional parts of gear, so they can quickly sort out if they have gear that is identical except for visual appearance.

**Comment by philkernick** [comment]
Also in #2737

**Comment by bhollis** [comment]
https://github.com/DestinyItemManager/DIM/pull/3024

**Comment by inexorableAce** [comment]
Problem is, as was mentioned in one of the other attached issues, this does not happen often. Even in ghosts, 2 items with the exact same perks is very rare. In weapons and armor it's SUPER rare because of masterworks. 

Anecdotally, I Have 65 ghosts, I went through each. Not a single one had the exact same perk set. 

That said, perk searching still needs work in general, too many have similar name for string searching to be viable. Maybe porting over the perk search from the loadout builder for easier perk matching?

**Comment by duckmanBR** [comment]
@inexorableAce that's the funny part about random...
I have 41 ghosts and 2 with Tangled Shore Combo Detector / Tangled Shore Glimmer Scavenger.  A Vestian Shell and a Quondam Shell.

While I agree that if you put mw in the mix the amount of matches would be incredible low, and that this would be better handled on a improved compare tool, don't know if a predicate comparing only selected perks (not including mw/mod), wouldn't help somehow.

**Comment by kyleshay** [comment]
Even still it's very low odds that the roll will be the same.. Not convinced the search filter would be that useful.

I wonder if with the compare tool we instead added a "compare similar items with this perk" then used a dropdown/autoselect that adds all items with that same perk?

Could be useful for comparing items other than ghosts as well.

**Comment by wein3967** [comment]
Something in the middle might be asking the users to put in their desired search terms (e.g., perks), and then allow the compare tool to grab the highlighted items. So you could do something like 'is:ghost "Tangled Shore"' and then send just those items to the compare screen. That would also work really well for armor and allow users to find "partial dups."
![image](https://user-images.githubusercontent.com/11590326/48520410-1439a400-e836-11e8-8df5-10072f956e9d.png)

**Comment by inexorableAce** [comment]
that would work... except the same perks can be on weapons that aren't comparable with one another. same with many many searches.

**Comment by wein3967** [comment]
True. It would put the onus on the user to only put together search strings that make sense. I guess you could require a type first (e.g., is:ghost, is:gauntlets, is:scoutrifle).

**Comment by delphiactual** [comment]
except we have no precedent for requiring an order on search strings.

**Comment by wein3967** [comment]
Yeah, someone is bound to get confused. It could certainly skew more towards a power-user type feature. I'd love to be able to sort through my armor this way though ... it is out of control.

**Comment by inexorableAce** [comment]
only thing I can think of is having some indicator on the search bar (like the tag icon on the search bar) that is greyed out until you have a qualifying search e.g. one that says is:autorifle, :is:gauntlets, etc. Then we can at least give them an explanation when the click (mobile) or hover (desktop the greyed out icon. 

and if they do have a qualifying search param (wherever it is in the search) we light up the icon and allow the comparison.

**Comment by wein3967** [comment]
Seems reasonable to me. I like it.

**Comment by philkernick** [comment]
I don't think we've really determined what the use-case is.

He's my take on it.  Ghosts have activity dependent perks, and activity independent perks.  This was the basis for #2270 and also mentioned in #2959.  Most of us want to have the "best" shell for each activity.  So I think the use-case is "which activity do I have duplicate shells for".

This is reflected in-game, as the perks are greyed out for a ghost if you aren't in the relevant activity.  This is also reflected in DIM (at least visually) as the activity dependent perks are greyed out.  The IO perk (the activity dependent one) is greyed out, the activity independent perk is bright.

![image](https://user-images.githubusercontent.com/25425159/48928325-c277d480-ef2d-11e8-9467-21f356d42aaa.png)

So I think what we really want is an is:dupeactivity filter that only considers the activity dependent perks.

**Comment by bhollis** [comment]
I think I'd prefer solving the ghosts problem more specifically: https://github.com/DestinyItemManager/DIM/issues/2661. I have a ghost labeler on a branch somewhere...

**Comment by SentryTheDefiant** [comment]
I suppose I posted this based on my own experience where I had a good 5 or 6 duplicates, and I hadn't run the numbers to see how probable this was, so maybe this wasn't the most necessary feature, but I do feel like ghosts could use some love compared to where we are with weapons and armor. 

I think Wein3967 probably suggested the best approach by giving the compare tool the ability to narrow the ghosts based on the search term. It would be the quickest way to sort through your inventory base on individual activities or spaces.

Alternatively as Philkernick stated, it's mostly just a matter of finding the best shell for the activity. If shells were included in the load out builder it would push users to lean on load outs more heavily. It would be better for getting the right shell to your character, but not as good for just cleaning ou/sorting inventory.

**Comment by DHager** [comment]
This situation may be rare for folks who've been playing for a long time, but I'm definitely encountering it with rare/blue equipment.

My use-case is:

* I want to make sure I have a selection of perks available for the Crucible,
 * So power-level differences are merely a tiebreaker between two pieces of equipment.
 * If they did matter, they'd probably outweigh the perk-comparison, and I wouldn't need to look at perks.
* Part of safely dismantling stuff is ensuring that I don't get rid of my "last copy" when I have three helmets with fastball or something like that.

**Comment by inexorableAce** [comment]
Your use case sounds perfect for the comparison tool. Which exists today.

**Comment by wein3967** [comment]
I may be wrong, but initially, @DHager in his use-case indicated he doesn't care what the model/appearance is, just the perk. Which doesn't work with the comparision tool currently. But, in his Example, he is referencing a specific leg armor model.

**Comment by inexorableAce** [comment]
You can see different leg armors together in the comparison tool. Even different guns as long as they are the same archetype.

**Comment by wein3967** [comment]
True, but it is a little unwieldy if you actually have a lot of items. And you still can't refine the comparison down to perks of interest. You'd have to "compare" all leg armor and then manually remove each one without the perk you want. That can be tedious. I'll use my hoarding self as an example. Let's say I'm interested in the Dynamo perk. This is all my leg armor:
![image](https://user-images.githubusercontent.com/11590326/49088131-36f88f00-f21e-11e8-9c02-5466ae69d0f5.png)
 If I click compare on some Scatter Horn Greaves (11 items), I'll get a long list that goes off the screen.
![image](https://user-images.githubusercontent.com/11590326/49088235-6d360e80-f21e-11e8-8641-bda5c51baf6e.png)
If I click Leg Armor Comparisons (85 items), the list will get even longer. Now, I'd have to go through each one and close out those without the Dynamo perk.
If I could send the filtered screen to the comparison tool, it gets much more manageable very quickly.
![image](https://user-images.githubusercontent.com/11590326/49088690-6bb91600-f21f-11e8-9fd6-65c5c64081bd.png)
DIM has a great search/filter feature and it would be super convenient to be able to leverage that with the comparison window.

**Comment by inexorableAce** [comment]
I guess I’m not understanding your use cases then. You’re saying you want to compare items. There are a lot of them. You can use search to your advantage now... search for the perk you want and add them to the comparison tool as you want by clicking them. 

Or better yet use loadout builder and let it find the best gear with the perks you want and ditch the rest. 

The act of comparing items at the level you’re talking about is tedious... it’s always going to be tedious :p

**Comment by kyleshay** [comment]
We could show the compare icon button in the search bar if the current search matches a single item type/the type currently being compared and on click it adds then all matching ones

**Comment by inexorableAce** [comment]
Yeah we suggested something like that up there a ways. And seemed like we all agreed that was the way to go :p

**Comment by SentryTheDefiant** [comment]
Kyleshay's idea actually seems like a really simple thing that pushes the user in the direction of using existing tools, and makes it a bit easier to get to the desired end result. My only worry now is how crowded that bar gets on small screens

**Comment by kyleshay** [comment]
#3369

**Comment by DHager** [comment]
> You can use search to your advantage now... search for the perk you want

Unfortunately it's not just *one* perk of interest, it's going through *all* the perks. That means a lot of re-typing perk names, and the chance of a serious error if you write `perk:"rifle targeting"` which matches both `perk:"scout rifle targeting"` and `perk:"auto rifle targeting"`.
