### ISSUE TITLE
Classified Mask (Skull) info

### ISSUE THREAD

**Issue by v-fedorov** [DestinyItemManager/DIM#326]
Item Name: 'Skull Mask'
Item Hash: 3678707177

I attached the image if you want to use it
![Skull Mask](https://cloud.githubusercontent.com/assets/1764879/10743785/bbb37264-7c0b-11e5-8ee6-1647595d0a3c.jpg)

**Comment by SunburnedGoose** [comment]
Should be available in v3.1.16.

**Comment by SteffanLong** [comment]
This mask is classified. It's not in the manifest. That's why we're sharing the hash/icon with you, so you can add an override for it. :)

**Comment by v-fedorov** [comment]
Attached a pic of 3.1.16 while i have it equpped
![screen shot 2015-10-26 at 6 32 08 pm](https://cloud.githubusercontent.com/assets/1764879/10744398/099af8fe-7c10-11e5-98d6-9d7019cec77a.png)

**Comment by SunburnedGoose** [comment]
Thanks. The issue is clearer :)

**Comment by SunburnedGoose** [comment]
We have some automation that helps us with this but it takes about 8 hours to give us actionable data.  Any other items missing aside from the skull?

**Comment by v-fedorov** [comment]
Skull seems to be the only item found and also the only classified item of that type we could find in the manifest.

So afaik its the only item for this event

**Comment by v-fedorov** [comment]
btw quick suggestion regarding these overrides.

Instead of checking all requests for the hash we have been adding them to the definitions instead.

https://github.com/DestinyTrialsReport/DestinyTrialsReport/blob/develop/manifest.js#L101

I can try to make a quick PR for you if you want

**Comment by geck0s** [comment]
Can we get a classified or unknown icon so that you can still have something to see in DIM and something to click on to manipulate?  

This would help improve managing the skull or any future items not in the manifest.  Currently DIM is undercounting the armor section of my vault by one when the skull mask is in there.  This sort of thing will happen from time to time, so I think it would be worth implementing better handling of items not on the manifest as a stop-gap until we get an update to them.

**Comment by v-fedorov** [comment]
Yeah there should be a fallback item, source already contains the an icon bungie uses for missing images.
https://github.com/DestinyItemManager/DIM/blob/dev/app/img/misc/missing_icon.png

**Comment by SunburnedGoose** [comment]
We've been using the exotic quest icon because it's prettier. It is coming
with the perf update. We are changing how we build the items.

**Comment by v-fedorov** [comment]
fixed in v3.1.17
