### ISSUE TITLE
Collections not showing collected Blue/Green/Whites correctly.

### ISSUE THREAD

**Issue by gbravery** [DestinyItemManager/DIM#3261]
This is a nice feature by the way - much easier to work with than inside Destiny.

Looking under the collections tab, at (for example) Primary weapons, I can see that the blues/green/white weapons don't have a green tick (on top right), unlike the purples.

When I click on a weapon, it shows a tick that i have it - but I am unsure if this is accurate as it says I have one blue submachine gun (Sondok-C) which the Destiny web app is showing I haven't.

**Comment by bhollis** [comment]
The green tick means you have it in your inventory, not just in your collection. Does that help?
