### ISSUE TITLE
Loadout Builder Crashing 

### ISSUE THREAD

**Issue by mistral13** [DestinyItemManager/DIM#3269]
Hi
Loadout Builder Crashing on my 2 warlock at 97% (generation of builds) on iOS.
For my Titan it work fine.
I konw i have a lot of items for my warlock.
How can I help locate the bug?

**Comment by kyleshay** [comment]
Thanks for the report! If you could send a screenshot of the developer tools with the error they would be really helpful.if you scroll to the top where you see the first bit of red text, that would be what we need

http://anti-code.com/devtools-cheatsheet/

**Comment by mistral13** [comment]
Can I do this on iOS as well or does it only work on a pc/mac?

**Comment by mistral13** [comment]
Hi
 
I found a PC to test the Problem.
On the PC it works, but it takes a very long time.
I have noticed that it takes a lot of memory with my warlock. I could imagine that this is a problem on iOS.
 
This data copied from Chrom:
Console
Titan:
  found 268371 sets after processing 348075 combinations in 2281.300000000556
Warlock:
  found 1363634 sets after processing 1603008 combinations in 10493.099999999686
 
Memory
Select Java Script VM instance
  Titan 300MB
  Warlock > 1200MB
 
Can I help you any more?

**Comment by kyleshay** [comment]
Ah yeah. The process is pretty intensive.  
We could potentially lower the `50000` number so that there are more breaks... but there are probably some better things we can do for caching results and then doing the processing on that.

https://github.com/DestinyItemManager/DIM/blob/master/src/app/d2-loadout-builder/process.ts#L105

**Comment by mistral13** [comment]
Or could it be that the html-code is rendered for too many combinations ?

**Comment by kyleshay** [comment]
Hmm, I believe we do limit the number of combinations to 10, then there is a 'show more' button to load an addition 10.

**Comment by mistral13** [comment]
This is what is showed on the screen.  But when are the HTML elements created for all combinations?

**Comment by bhollis** [comment]
DOM elements are only created for visible elements.

**Comment by mistral13** [comment]
@kyleshay 
If it's limited to 50000 what needs so much memory and why are the values in the console for my warlock so much higher?

**Comment by delphiactual** [comment]
50000 is how many it processed per batch...
