### ISSUE TITLE
clear character inventory feature

### ISSUE THREAD

**Issue by know1ne** [DestinyItemManager/DIM#3271]
Forgive me if there's another issue listed for this or if it's already in the app & I'm just unaware, but it would be cool if I could do some action to clear all items in a characters inventory by sending them all to the vault. It would leave a character with it's currently equipped items only. The use case is organizing items. I like to clear out all items, then transfer over (in bulk) lots of items I want to analyze for dismantle or save.

**Comment by delphiactual** [comment]
`is:incurrentchar not:equipped is:haspower` -> Vault Dropdown -> Transfer Search

**Comment by know1ne** [comment]
> `is:incurrentchar not:equipped is:haspower` -> Vault Dropdown -> Transfer Search

now I know, thanks!
