### ISSUE TITLE
"Update DIM" doesn't update DIM

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#3278]
This has been happening a lot lately.  The "Update DIM" item in the menu appears, so I click it, and it comes back.  It never appears to actually update DIM.

So Alt-F5 or shift-reload, and it still comes back asking for an update.

**Comment by bhollis** [comment]
This is still happening? It was a bug on beta but it should be fixed now. 

You may need to fully close the tab and reopen it if you were on the bad version.

**Comment by philkernick** [comment]
On beta today.  Closed all tabs and restarted Chrome.  

I'll keep an eye on it and try and track down which versions are still buggy.

**Comment by bhollis** [comment]
Cool, please reopen if it's still not working.

**Comment by philkernick** [comment]
It's doing it again.  Desktop Chrome.

Version 4.75.0.2539 (beta), built on 30/10/2018, 15:15:31

No amount of reloading or closing the tab or browser seems to get it out of this state.

**Comment by philkernick** [comment]
Finally got it resolved.  I needed to go into Chrome's cookie and site data section and delete anything to do with DIM.
