### ISSUE TITLE
Vendor Engrams stuck on DIM Loading Screen when Clicked.

### ISSUE THREAD

**Issue by Pheelix** [DestinyItemManager/DIM#3281]
In the Vendor section when you click on a Engram to see what that vendor can give you via packages.  All that is happening is the DIM Loading Screen.  I have cleared Cache/Data on both Chrome and Firefox.  Guessing something changed after the Forsaken update or on my end.

Screenshot: [Loading Screen](https://beta-static.photobucket.com/images/f334/Pheelix/0/77865386-59cd-4c04-8403-08585a70c785-original.png?width=1920&height=1080&fit=bounds)

**Comment by bhollis** [comment]
Thanks for the report! A fix is going out to Beta.
