### ISSUE TITLE
Update the header bar

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#331]
Some restyling. Add [twitter](http://fortawesome.github.io/Font-Awesome/icon/twitter/)/[reddit](http://fortawesome.github.io/Font-Awesome/icon/reddit/) links.

![pasted image at 2015_10_28 12_51 pm](https://cloud.githubusercontent.com/assets/424158/10797849/02768464-7d7b-11e5-987f-506efd206f27.png)

Thanks @dheif !

**Comment by bhollis** [comment]
I'm going to punt design stuff like this to v4, which is probably going to have a very different layout.
