### ISSUE TITLE
tabs for other views per character

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#332]
similar to destinystatus. we don't need parity with destiny status, but it would be good to (at least) have tabs to separate quests and bounties from items.

anything else could be considered. would maybe want to lazy load some of the data on different tabs, so that the initial page load isn't too intense.

![screen shot 2015-10-29 at 11 02 13 am](https://cloud.githubusercontent.com/assets/424158/10822205/8f2abb44-7e2c-11e5-9222-e321b824ca05.png)

**Comment by bhollis** [comment]
I think we should stick with being an item manager, and leave this sort of thing to other tools or Bungie.net. Feel free to reopen if you want to discuss more, though. I'm just trying to clean things up.
