### ISSUE TITLE
Vendors: Swipe between characters

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#3321]
Now that we can select the character for vendors, it'd be nice to swipe between them on mobile instead of having them stacked up.

**Comment by SentryTheDefiant** [comment]
I love this idea. Players who use all three classes regularly would surely benefit.
I also wonder if being able to sorting vendors, or favoriting them might also save mobile users some scrolling too. I know I often forget to collapse them, so the next time I want to check Banshee (which I do most days), I have to scroll a bit, and I wish he and Xur were always first. 

If it weren't for several vendors using the same Icon, I'd go as far to suggest mobile use a collapsed-by-default view that uses rows of icons similar to the d1 progression panel.
