### ISSUE TITLE
Mass transfers not working in Edge. 

### ISSUE THREAD

**Issue by inexorableAce** [DestinyItemManager/DIM#3324]
mass transfer issue in edge, beta and prod. This applies to gather rep items, loadouts, and search / transfer. 

I tested in Microsoft Edge 42.17134.1.0

Prod console logs:
`SCRIPT5007: Unable to get property 'props' of undefined or null reference
react-dom.production.min.js (21,62)`

Beta console logs:
` SCRIPT5007: Unable to get property 'props' of undefined or null reference
helpers.ts (79,14)`

nothing happens in game or in app no failure toaster just the console error.

**Comment by bhollis** [comment]
Manage to figure out what's going on here?

**Comment by inexorableAce** [comment]
I think @48klocs was looking into this one, I’ll do some testing when I can though the errors are... less than helpful.

**Comment by bhollis** [comment]
Yeah, that's just Sentry catching and logging the error. The real error is higher up.

**Comment by bhollis** [comment]
I believe this is https://github.com/Microsoft/ChakraCore/issues/4663, fixed in Edge 18 (which is the last ever Edge release AFAIK).

**Comment by bhollis** [comment]
Upgrading `@babel/preset-env` should fix it.

**Comment by bhollis** [comment]
Actually, we need https://github.com/babel/babel/pull/9060, which hasn't been released yet.

**Comment by bhollis** [comment]
OK, I pushed a change to beta - does it work now?

**Comment by inexorableAce** [comment]
Yes! loadout transfers seem to be working in edge on beta now!
