### ISSUE TITLE
Infusion calculations, the postmaster, and scroll bars

### ISSUE THREAD

**Issue by geck0s** [DestinyItemManager/DIM#333]
Can we also have the "Show infusable items across all characters and vault" checkbox in the infusion calculator check the postmaster on each character or maybe have another checkbox for that?

I'm sure most don't leave many items at the postmaster, but it might be a nice addition for items that haven't been picked up or those of us who are out of vault space.

Also, the infusion calculator in DIM 3.1.17.2 can be opened for items in the postmaster in but it doesn't work quite right because it assumed everything in the postmaster slots can be infused instead of comparing item type.  The locked items checkbox does work properly.

Additionally, the scroll bar doesn't work as the infusion calculator portion expands to match the height of the contents thus leaving the inner scroll bar non-functional.  The main window's scroll bar doesn't help either because it only moves the background items as the infusion calculator window stays in place.  In the screenshot below (browser is Chrome 46), there is no way to read the result or even the light on the sidearm I selected as infusion fodder:

![image](https://cloud.githubusercontent.com/assets/12294244/10836922/0b7eb65c-7e8a-11e5-8711-c70b96dde4f2.png)

**Comment by nki2bpz** [comment]
Bump for all of this

**Comment by bhollis** [comment]
In 3.3 I've fixed it so you can't infuse from the postmaster, and the sizing of the infusion box is bigger so it shouldn't scroll as much. Take a look and tell me what you think.

**Comment by kyleshay** [comment]
The scroll seems functional as expected now, along with the postmaster fixes we're good to close this. @geck0s feel free to let us know if you're still running into any quirky things.
