### ISSUE TITLE
PowerLevel isn’t accurate

### ISSUE THREAD

**Issue by mistral13** [DestinyItemManager/DIM#3335]
PowerLevel isn’t accurate
 
there is a difference between the power level in the app of Bungie and DIM/Ishtar
 
2 Example:
 
https://imgur.com/a/HTJre0F

Bungie App: 440
DIM/Ishtar: 433
 
Kinetc: 600
Energy: 580
Power:377
Helmet: 380
Gauntlets: 378
Chest: 380
Leg: 380
Class: 391
 
 
 
Bungie App: 262
DIM/Ishtar: 231
 
Kinetc: 600
Energy: 600
Power:600
Helmet: 10
Gauntlets: 10
Chest: 10
Leg: 10
Class: 10

**Comment by mistral13** [comment]
I will compare the values in the game today. Maybe the bug is in the Bungie IOS-App and not in DIM

**Comment by bhollis** [comment]
The star means we can’t figure it put exactly because you have a classified item (Thunderlord).

**Comment by mistral13** [comment]
the values in the game are the same as in DIM. the bug is in the Bungie IOS-App and not in DIM. Sorry
