### ISSUE TITLE
loadouts not auto applying to character

### ISSUE THREAD

**Issue by koopachii** [DestinyItemManager/DIM#3336]
I spent a very large amount of time on loadouts and now I cant seam to auto apply them. its normally just click the loadout and it transfers to character ingame. not anymore

**Comment by delphiactual** [comment]
What browser, what version of DIM... Etc

**Comment by koopachii** [comment]
using windows edge. unsure what version om DIM

**Comment by delphiactual** [comment]
Dupe #3324
