### ISSUE TITLE
Classified item overlay tag status and filter response is inconsistent

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#3337]
The screenshot below shows the result of the not:locked filter.  The 3 classified items are Thunderlord.

![image](https://user-images.githubusercontent.com/25425159/48812762-d41d7880-ed83-11e8-8374-67c034900f14.png)

The issue is that the classified items are highlighted as not locked, but they have the lock icon on them.

I suggest that all classified items have no tag or lock ornamentation, and that all classified items are excluded from all filter results.

**Comment by bhollis** [comment]
Classified items can be locked - in this case those are really locked. But they are not "lockable" according to DIM because they can't be locked and unlocked via the API.

**Comment by philkernick** [comment]
That makes sense.  But in this specific case, if I change the filter to is:locked, they deselect, even though they show the lock overlay.

I think the point I'm trying to make is that the is:locked filter and the lock overlay are not using the same data source.
