### ISSUE TITLE
Infusion finder does not show tags or ratings or the new damage icons

### ISSUE THREAD

**Issue by inexorableAce** [DestinyItemManager/DIM#3346]
infusion finder seems to have some half way tiles between the old and new. Most notable is that ratings, tags and the elemental icon are missing (though it still has the elemental triangle in the top left.)

![image](https://user-images.githubusercontent.com/29002828/48917410-9f2d2680-ee54-11e8-8669-50a027dc17f5.png)

**Comment by bhollis** [comment]
Yup it's still in the Angular world. Soon...
