### ISSUE TITLE
Beta: New Layout problem

### ISSUE THREAD

**Issue by duckmanBR** [DestinyItemManager/DIM#3347]
Probably caused by #3343

![image](https://user-images.githubusercontent.com/32077894/48923678-d3760680-ee97-11e8-9dec-1335ed5772cc.png)

**Comment by philkernick** [comment]
Here's another one.  The border around equipped items should be removed if there is a filter and the filter does not include the item.

![image](https://user-images.githubusercontent.com/25425159/48924778-d579ad00-ef0b-11e8-92d6-89692c42c6f2.png)

**Comment by bhollis** [comment]
Good catch on the equipped thing. It definitely looks odd, thought I had imagined the border as denoting the equipped "slot" rather than the item inside it.

**Comment by delphiactual** [comment]
This looks like a `Canary` issue. Looks fine on `Chrome Version 71.0.3578.30 (Official Build) beta (64-bit)`

**Comment by mistral13** [comment]
Here's another one. On my ipad the items have become some bigger. 
With the smallest size setting I see only 4 items left in the vault. In the app there are 6.
That the border and margins have become smaller I find very good.

Both pictures were taken with the smallest size. 
![5bf12908-a05e-4b6e-81c3-d1ca05fec5d7](https://user-images.githubusercontent.com/5049663/48973570-4622e580-f042-11e8-99d3-eefd7df4990c.jpeg)
![f58665ed-0e6f-4851-a96b-bfe42cd5b3a9](https://user-images.githubusercontent.com/5049663/48973571-4622e580-f042-11e8-8dce-f01c39869c85.jpeg)

**Comment by bhollis** [comment]
Yes, that’s intentional, we’re setting a larger minimum size now.

**Comment by mistral13** [comment]
Please set the smallest size setting a liitle bit smaler, so that you can at least see 5 items left in the vault.

**Comment by bhollis** [comment]
You can now fit 5 items in the vault on iPad.

Folks, thanks for pointing this stuff out! In the future it's more helpful if each independent problem is its own issue.
