### ISSUE TITLE
Switching between D2 and D1 and back causes an unending animated DIM

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#3351]
Ok.  I get it that the description isn't great.

Here's how to reliably replicate it.  Current Beta on Chrome on Windows 10.

Start DIM in a new tab.  You are looking at your D2 inventory.
Wait for the loading spinner to stop to ensure all async loads are done.
From the drop down menu top right, select D1.  You are looking at your D1 inventory.
Wait for the loading spinner to stop to ensure all async loads are done.
Select the Vendors tab.  You are looking at D1 vendors.
Wait for the loading spinner to stop to ensure all async loads are done.
From the drop down menu top right, select D2.

Now what you are looking at is the animated DIM logo in the middle of the screen.  I've waited 2 full minutes and it doesn't go away.  Clicking the refresh spinner does make the page load.

**Comment by bhollis** [comment]
Thanks! I know about this - it’s caused because the interface between our old inventory code and the new Redux state isn’t quite perfect. Long term this’ll get solved by moving that state fully into Redux, but I can also patch it up in the meantime.
