### ISSUE TITLE
FotL gift bag items not shown, not counted

### ISSUE THREAD

**Issue by geck0s** [DestinyItemManager/DIM#336]
I was under the impression the work for issues #325 and  #326 might have addressed this but it has not. 

Two consumables for Festival of the Lost are not showing up in DIM 3.1.17.2

"Bag of flimsy masks" 
data-itemhash="3836534493"
![image](https://www.bungie.net/common/destiny_content/icons/5783e7a778dec73d396e88fea02bb5ff.jpg)
https://www.bungie.net/en/Armory/Detail?type=item&item=3836534493&itemname=Bag%20of%20Flimsy%20Masks

"Gifts of the Lost"
data-itemhash="3836534495"
![image](https://www.bungie.net/common/destiny_content/icons/5783e7a778dec73d396e88fea02bb5ff.jpg)
https://www.bungie.net/en/Armory/Detail?type=item&item=3836534495&itemname=Gifts%20of%20the%20Lost

When these items are in the vault, the count is incorrect where DIM says "GENERAL 34/36" because the general tab of my vault has all 36 slots used.

Can we at least put that exotic quest icon in and count unrecognized items like these the same as classified items are handled (what I saw with the flaming skull before it was manually defined in the manifest under #327?  That would be useful for future items that are not recognized until some other manual changes are made to DIM.  

EDIT: I found another entry in the armory web pages:
https://www.bungie.net/en/Armory/Detail?type=item&item=3836534492&itemname=Gifts%20of%20the%20Lost
I don't know how that one would be obtained.  Completing a quest and turning in a sack of candy both gave me the 3836534495 items which stacked.

**Comment by bhollis** [comment]
There's a general problem with missing data, but since Festival of the Lost is over, I'm going to close this. If they haven't fixed it by the time this event rolls around again, we can take another look. Thanks for the report, though!
