### ISSUE TITLE
Google Drive Sign In

### ISSUE THREAD

**Issue by tttgary** [DestinyItemManager/DIM#3368]
Hi,

I have been having issues with the google drive sync for the last week or so, with it either not signing in, not syncing changes, not showing the list of previous revisions. So in an attempt to fix it i've cleared the DIM app data from google drive and the browser cache on both my Windows 10 Chrome Browser and Android Phone Chrome Browser.

I now attempt to login to google drive on a clean Chrome browser on Windows 10 and the following errors are thrown in the console log.

`google-drive-storage.ts:254 Error: GoogleDriveStorage: No files!
    at Object.getFileId (google-drive-storage.ts:227)`

and

`Uncaught Error: To re-authorize google drive, you must restart your browser.
    at Object.getFileId (google-drive-storage.ts:255)`

I've taken a look at the code and it looks like the changes put in 8 days for the async changes have broken this. In google-drive-storage.ts it now throws an exception at line 227 when no files are found, totally skipping the attempt to even create the initial file at line 240.

Thanks

**Comment by bhollis** [comment]
Thanks for the info!

In a2c75d7076471c8fb680a8e8a0fc5acf1ba86164 I changed to async, but the problem is not the `throw` (which was there before). The problem was I'd forgotten to add an `await`, so we were inspecting the promise, not the result of the promise.

**Comment by tttgary** [comment]
Hi,

Doesn't seem to be fully resolved. On sign in to google drive I now get this error thrown.

`TypeError: Cannot read property 'id' of undefined
    at Object.getFileId (google-drive-storage.ts:252)`

Thanks
