### ISSUE TITLE
Also sort items by collection

### ISSUE THREAD

**Issue by pylaligand** [DestinyItemManager/DIM#337]
If you choose to sort items by rarity, it seems that they are ordered alphabetically. An alternate and potentially more useful secondary sort would be to use collections: group items that drop from the same activity together.

I believe this would be more visually pleasing and would make spotting items much faster, as items from the same collection tend to share a theme.

Let me know if you agree, and I can probably take a stab at implementing this. Not sure you guys have a concept of collections for items, but putting together canonical collection definitions should not be too hard.

**Comment by Mulchman** [comment]
I disagree. I want tier then alpha, ie. how 'rarity' sorts things.

**Comment by SunburnedGoose** [comment]
I think the secondary sort should be attack/defense.  Could be an option too...

**Comment by bhollis** [comment]
We've got an option to sort by atk/def as a second option now. I don't think we need too many of these.
