### ISSUE TITLE
Ghost Fragments wrongly appear transferrable

### ISSUE THREAD

**Issue by DHager** [DestinyItemManager/DIM#3373]
With a quick search through the code I'm guessing this is actually an issue with incorrect metadata supplied by Bungie,  but even if so it might be possible to catch it and put in a better exception until they fix their metadata.

## Context

I noticed that my Ghost Fragments (redeemed at Spider) were at "MAX", and wondered if I could move some to the vault to "make room" on the character. (As a fairly new player, this seemed worth a try.)

## What happened

* Clicking on the Ghost Fragments shows a quantity-slider with the "Vault" and "Take" buttons.
* Attempting to use the "Vault" command gives a very friendly but not-quite-correct error message:

> Bungie.net message: You can only have one of the thing you're trying to do/activate/equip. Man, this error is way too general. Listen, whatever you did... you can only do it once, or have one item, okay? ¯\\_(ツ)_/¯

## What I think should have happened

* The Ghost Fragments should act like Radiolarian Cultures or Rasputin Armory Codes, and *not* display a slider or Vault/Take buttons.

**Comment by bhollis** [comment]
Thanks for the great bug report by the way!
