### ISSUE TITLE
Item rating and power on tiles does not align

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#3374]
Screenshot to demonstrate.

![image](https://user-images.githubusercontent.com/25425159/49132660-14a16700-f32d-11e8-9644-ec3ec3835689.png)

The item rating is a smaller font than the item power, which is fine, but it is neither top nor centre aligned with the item power.  Instead the rating top line is a few pixels higher than the power top line.  Look at the right-hand most weapon for the clearest example.

Also related to the tile details, at least in some cases the rating, the element and the power level overlap a little.  Screenshot at 400% to demonstrate.  It's most noticable with void as it's wider/fuller/uses-most-of-the-bounding-box.

![image](https://user-images.githubusercontent.com/25425159/49132795-98f3ea00-f32d-11e8-9196-6341f373b9c7.png)

**Comment by bhollis** [comment]
https://github.com/DestinyItemManager/DIM/pull/3376
