### ISSUE TITLE
When leaving a review, a user should know it is for the specific roll on that item

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#3378]
When leaving a review, a user should know it is for the specific roll on that item. Currently there isn't way to know that reviews are based on your rolls. 

<img width="287" alt="screen shot 2018-11-28 at 11 30 48 am" src="https://user-images.githubusercontent.com/424158/49177069-1f460700-f301-11e8-9025-90652541526d.png">

**Comment by duckmanBR** [comment]
Maybe show the active perks?

**Comment by 48klocs** [comment]
I cover the mechanics of it in `ratings.md` (hopefully it's still up to date?).

It gets a bit more complex as you get deeper in to it - we do send the roll + selected perks, but rating/review fetches are a bit fuzzy in how they return (pending a back-end change).

I don't see a whole lot wrong with people crowing about perk combos they love/find useless; is that what you're looking to address here?

**Comment by kyleshay** [comment]
I've seen many reviews that talk about perks that don't match what I have on my instance. I'm also assuming that people thumb up/down without knowing that it is for the specific roll on that item.

**Comment by 48klocs** [comment]
So there's a couple of things going on there - one, perk matching isn't as accurate as it was in D1 (I have a proposal to help solve that with the back-end folks).

Two - people like to crow about how good/bad perk combos are. I don't see this as a terrible thing, but I understand why it can feel pretty useless. A second-order concern I have is that more verbiage might discourage folks from making a review. The reason I have this concern is that currently, DIM weights ratings with reviews more heavily than a rating without a review.

**Comment by kyleshay** [comment]
It's fine that people talk about good and bad perks, but it's just strange when they seem to leave a review for the general weapon and it seems like they have one with a great roll but maybe left the review on an item with the same hash that has a terrible roll.

If anything maybe it will encourage people to leave more reviews for different rolls on the same weapons instead of just one general review for that hash?

**Comment by slate0** [comment]
I have seen both ways in the previous review system.  I can have different rolls with different perks with different stars, yet the reviews will talk about various perks.  Sigh, I don't envy you guys trying to find the balance between too many options and useless information.

**Comment by bhollis** [comment]
Can we just add some help text?

**Comment by kyleshay** [comment]
yeah, help text / placeholder text were my initial thought. do like @duckmanBR idea of showing what the significant active perks are, but not necessary.
