### ISSUE TITLE
Add Visual indicator for google drive status

### ISSUE THREAD

**Issue by mistral13** [DestinyItemManager/DIM#3381]
Hi
I think its a good idea to have a visual indicator for google drive and the status of this connection. So that problems e.g. as in #3323 can early detected.

My suggestion is to make this about the color of the icon for the setting:
White: local stored
All other color if data stored in google drive:
Green: connencted and all changes are correctly stored in the cloud
Orange: connencted but changes couldn‘t stored in the cloude or zero data are loaded from the cloude
Red: can‘t connect to the cloudr

**Comment by bhollis** [comment]
This would be great. It'd probably be easiest if we just threw the status of the sync adapters in Redux.

**Comment by bhollis** [comment]
This is obsoleted by #4418.
