### ISSUE TITLE
DIM can transfer locked items.

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#339]
If an item is locked, it can be transferred.  After the transfer, it is still marked as locked.

https://www.reddit.com/r/DestinyItemManager/comments/3s1069/bug_item_stays_locked_without_refresh/

**Comment by Marc05** [comment]
Issue seems to be on bungie's side as shown here:
https://www.youtube.com/watch?v=6Li1T6jwtAE

**Comment by bhollis** [comment]
Resolving as this is a Bungie issue - we don't change lock status or do anything with it.
