### ISSUE TITLE
Consider turning season into a numeric filter

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#3390]
At the moment we have is:season1 up to is:season5 and we don't really know where this is going to end.  It will get to at least is:season8 and perhaps beyond.

Before we head futher down this path, I think we should consider changing the filter to: 
season:num just like the rest of the numeric filters.

Then we could do interesting filters like:
What do I have from year 1?  season:<4

**Comment by delphiactual** [comment]
is:year1
