### ISSUE TITLE
Loadout Builder - Filter Ornaments

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#3393]
![screenshot from 2018-12-01 10-07-44](https://user-images.githubusercontent.com/4798491/49330794-02077780-f551-11e8-8b4c-7fe0705845ba.png)

**Comment by kyleshay** [comment]
I need some armor with an ornament 😬

**Comment by duckmanBR** [comment]
Other than exotics, some Legendary Y1 armors had some.  Iron Banner, Factions...

**Comment by delphiactual** [comment]
https://data.destinysets.com/i/InventoryItem:447258238

https://data.destinysets.com/i/InventoryItem:447258238/ItemCategory:1742617626

@kyleshay
