### ISSUE TITLE
Engrams take two lines at 1366x768

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#3399]
![screenshot from 2018-12-01 14-46-44](https://user-images.githubusercontent.com/4798491/49333221-190d9000-f578-11e8-8b44-eb5b826a60f6.png)

Decrease engram size to 21x21?

**Comment by bhollis** [comment]
It should actually be a function of the configured item size...

**Comment by bhollis** [comment]
Pushed a fix - please test on a few browsers, I used some dark magic.
