### ISSUE TITLE
Displaying Armor/Recovery/Agility for each subclass would be nice to have

### ISSUE THREAD

**Issue by geck0s** [DestinyItemManager/DIM#340]
I think it would be nice to eventually add a stats display for Armor, Recovery, and Agility when you click on a subclass in DIM.  It would be analogous to the in-game tool-tip on the character page but with actual numbers and perhaps comparison like the weapons have.

**Comment by kyleshay** [comment]
looks like that data comes back on our first call:

`https://www.bungie.net/Platform/Destiny/TigerXbox/Account/[membershipId]/`

on the property: 

`Response.data.characters[0].characterBase.stats`

which looks like this:

    {  
        "STAT_DEFENSE":{  
         "statHash":3897883278,
         "value":0,
         "maximumValue":0
        },
        "STAT_INTELLECT":{  
         "statHash":144602215,
         "value":217,
         "maximumValue":0
        },
        "STAT_DISCIPLINE":{  
         "statHash":1735777505,
         "value":221,
         "maximumValue":0
        },
        "STAT_STRENGTH":{  
         "statHash":4244567218,
         "value":167,
         "maximumValue":0
        },
        "STAT_LIGHT":{  
         "statHash":2391494160,
         "value":309,
         "maximumValue":0
        },
        "STAT_ARMOR":{  
         "statHash":392767087,
         "value":3,
         "maximumValue":0
        },
        "STAT_AGILITY":{  
         "statHash":2996146975,
         "value":8,
         "maximumValue":0
        },
        "STAT_RECOVERY":{  
         "statHash":1943323491,
         "value":6,
         "maximumValue":0
        },
        "STAT_OPTICS":{  
         "statHash":3555269338,
         "value":79,
         "maximumValue":0
        }
    }

**Comment by rabruce** [comment]
Did some digging, as far as I can tell we can only pull the active subclass stats (previous post) or we can pull the stats of the new subclasses (Nightstalker, Stormcaller, Sunbreaker). The older subclasses stats come up null for some reason.

Will explore some more tonight.

**Comment by bhollis** [comment]
I think you can figure it out from the talent grid info. I'm reworking that
now so maybe I'll look into it.

I played around with showing current subclass stats in a branch, but I
haven't decided where to display them. Any ideas?

**Comment by SunburnedGoose** [comment]
We were refactoring that information into a sidebar.

**Comment by SunburnedGoose** [comment]
Look at the /DTR branch, https://github.com/DestinyItemManager/DIM/tree/dtr

**Comment by rabruce** [comment]
Sidebar idea sounds nice, I'm drawing some inspiration from DestinyTrialsReport as far as user information; it's very cleanly set up. I'll pop open that branch at home and take a peek around.

**Comment by SunburnedGoose** [comment]
The code is stale so expect some chop while using it.

**Comment by SunburnedGoose** [comment]
This is the screenshot I made from that branch.

![image](https://cloud.githubusercontent.com/assets/984608/13013860/e60b64de-d176-11e5-98b9-0ca7d33161ac.png)

**Comment by bhollis** [comment]
Just a heads up that I'm working on a big set of changes to item info,
including full talent grid info. So it might be tough to fit everything
into that design exactly.

**Comment by SunburnedGoose** [comment]
Xorth and DTR are going to bring more data into DIM for items. Where is the gap?  Got a screenshot to share?  Sketch?

**Comment by rabruce** [comment]
Maybe by default show the active character information in the sidebar, and the expanded item info opening up into the sidebar?

**Comment by bhollis** [comment]
See #382 for the talent rework. It'd be nice to have some info about what extra info DTR could provide.

**Comment by kyleshay** [comment]
some discussion on this on the bungienetforum https://www.bungie.net/en/Clan/Post/39966/190153251/0/0

**Comment by kyleshay** [comment]
Here is a static Y3 Chart: http://imgur.com/a/x0WC8

**Comment by kyleshay** [comment]
Also, we should just show agility/armor/recovery in the same move popup where the perks are. just like weapons + armor.

really wish the API let us update those nodes :(

**Comment by kyleshay** [comment]
With D1 coming to a close and this possibly changing with D2 I'm going to close this.
