### ISSUE TITLE
The "Tag Items" menu overlaps the character select menu

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#3402]
Makes it quite hard to click the X to clear the filter.

![image](https://user-images.githubusercontent.com/25425159/49335765-f6e14400-f643-11e8-8726-9ba46b0dd4e5.png)

**Comment by bhollis** [comment]
What browser is this? What screen size?

**Comment by philkernick** [comment]
Chrome on Windows 10.  Screen size 2560x1440.
