### ISSUE TITLE
can't drag / drop from to lock items from top of D1 loadout builder

### ISSUE THREAD

**Issue by inexorableAce** [DestinyItemManager/DIM#3405]
reported in discord with this video. this also does not work in chrome. you can still drag / drop to lock from the items in the created sets.
![ezgif-5-fc07cef51a42](https://user-images.githubusercontent.com/29002828/49341774-31d18080-f620-11e8-948e-892b67d9e872.gif)

**Comment by bhollis** [comment]
Oh holy cow, I never knew that section even existed.
