### ISSUE TITLE
new item overlay looks bad on some items and eats cpu

### ISSUE THREAD

**Issue by inexorableAce** [DestinyItemManager/DIM#3406]
example of it over engrams. 
![](https://cdn.discordapp.com/attachments/333464468241514497/518613623258742801/Screen_Shot_2018-12-01_at_8.23.59_PM.png)

Possibly just adding a red circle to the top right of new items would suffice to mark new items. something like this without the number. 
![image](https://user-images.githubusercontent.com/29002828/49341818-cfc54b00-f620-11e8-852d-f0dc381a6974.png)

discord also does this just by using a white circle inside the red one: 
![image](https://user-images.githubusercontent.com/29002828/49341827-eb305600-f620-11e8-8ed9-25667246f716.png)

**Comment by kyleshay** [comment]
We also have a similar dot for the "what new?" Button to our changelog

**Comment by inexorableAce** [comment]
Yeah! Good point.
