### ISSUE TITLE
Copying loadouts

### ISSUE THREAD

**Issue by billwert** [DestinyItemManager/DIM#341]
It would be really nice if I could make a copy of an existing loadout. The scenario is easy: I've got a ton of weapons that I use for PVP, and specific class items / artifacts per class. Instead of creating a new loadout for each and dragging everything around (which is errorprone) I could make it, copy it, and just change the couple things.

**Comment by nki2bpz** [comment]
actually if you could just edit the loadout then save as new name. I thought it used to work that way but the last time i tried it overwrites the original save name.

**Comment by bhollis** [comment]
We've got a new feature coming in the next beta where you can make a loadout from your currently equipped items. Would that work to save enough time? (Load your loadout, create from equipped).

**Comment by nki2bpz** [comment]
That will be a huge time saver.  I do foresee one issue, currently when creating a loadout  you can only pick 9 of the 10 possible items to save in any one slot. I figured most people wouldn't notice cuz they're not gun hoarders like myself.So when copying currently equipped items  It will probably error on the 10th item.

**Comment by nki2bpz** [comment]
Ok, now that I see the create loadout from equipped in execution i take it back this saves no time at all I was thinking it would create it from all weapons on this character not just equipped. I think billwert has the simplest solution. load loadout, make changes, save as new name.

**Comment by SunburnedGoose** [comment]
The issue is finding a spot in the UI to squeeze a copy button.

**Comment by nki2bpz** [comment]
Understandable. OK, No copy button needed. Change the behavior when saving with a new name to saving as a new instance. This way if a user had a base loadout, they could make their changes and just save as a new name. If the user was just renaming the file they can delete the old one with original name after. Please understand i have no coding experience so I may be oversimplifying this.i hope i'm helping in some way. I really just love this app and I love the changes in the latest version. Cant wait to see the android version!

**Comment by bhollis** [comment]
I think we could just add a "save as new" button on the loadout popover.

**Comment by bhollis** [comment]
I have PR to add a "Save as New" button over in #410.
