### ISSUE TITLE
SyncService / Google Drive concept?

### ISSUE THREAD

**Issue by mistral13** [DestinyItemManager/DIM#3416]
Hi
I know this isn‘t an issue, but I don't know where else to ask the questions.
What is SyncService / Google Drive concept?

If an element (e.g. tag) changes:
Do you save all data from all item at the same time? 
Or per group (e.g. All weapons or helmets)?
Or every change per element?
Is every change synchronized immediately or just once in a while?

What is the size of the data stored per item?
At the moment I already have almost 500 items tagged.

I ask all this questions to understand how it is realized and perhaps to identify causes for the problems.

**Comment by bhollis** [comment]
The sync service persists data to one or more adapters. There's a local storage (IndexedDB) adapter, and a Google Drive adapter. Tags are implemented on top of this. Whenever a tag changes, we write it into a big map and save the entire thing back to storage. They're synchronized immediately. Each tag is an entry in the map that looks like:

```json
{
  "1231512851": {
    tag: "favorite"
  }
}
```

Size isn't really a big deal for Google Drive, though it does have a quota of how many operations you can do at a time, so we do have some minor debouncing of the update.

**Comment by bhollis** [comment]
Tags are mostly implemented here: https://github.com/DestinyItemManager/DIM/blob/master/src/app/inventory/dim-item-info.ts

It all needs a bunch of work - this was all implemented back before we used Redux, and before we even had Google Drive or IndexedDB, so there was a lot done to work around limitations in other things like the LocalStorage API and the Chrome Extension Storage API (DIM used to be a Chrome extension).
