### ISSUE TITLE
DIM cant recognize Iron Banner ghost shells

### ISSUE THREAD

**Issue by nki2bpz** [DestinyItemManager/DIM#342]
ghost shell from iron banner "iron shell" does not appear in my DIM inventory.

**Comment by depraved22** [comment]
Same. I noticed this as well. It seems to work in the bungie app.

**Comment by SunburnedGoose** [comment]
I just earned mine so I can verify it.

**Comment by nki2bpz** [comment]
I got two characters to rank 5 and I have 9 of them? 317 was the highest so far.



-------- Original message --------

**Comment by SunburnedGoose** [comment]
Nice.

**Comment by nki2bpz** [comment]
This appears to be fixed and could be closed. Items are showing up in DIM and can be moved between characters and vault
