### ISSUE TITLE
Samsung tab not updating

### ISSUE THREAD

**Issue by Forsaken412** [DestinyItemManager/DIM#3421]
DIM automatically updated on PC & phone, but gets stuck in loading screen while unzipping Destiny data. I've dumped all history and cache files, but no dice.

**Comment by delphiactual** [comment]
Chrome Version, etc.

**Comment by bhollis** [comment]
Have you tried the beta? That might at least send us the appropriate crash report.

**Comment by Forsaken412** [comment]
On Friday the beta started working. No idea why, I hadn't touched it in
days, but everything is good now. 🤷‍♂️

On Dec 10, 2018 1:08 AM, "Ben Hollis" <notifications@github.com> wrote:

Have you tried the beta? That might at least send us the appropriate crash
report.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/DestinyItemManager/DIM/issues/3421#issuecomment-445698576>,
or mute the thread
