### ISSUE TITLE
Compare view can’t scroll

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#3424]
With the new sheet UI, the compare view can’t scroll horizontally.

**Comment by bhollis** [comment]
Hmm, actually it can scroll, it's just... touchy. I'm not sure what's up.

**Comment by bhollis** [comment]
This really needs a redesign for mobile...

**Comment by Wh1rledPeas** [comment]
While you're looking at compare view, would it be possible to make the item icons "tappable" so tapping one of the item icons in the compare view would pull up the item information dialog?

**Comment by bhollis** [comment]
Yes, that's in the plans.

**Comment by kyleshay** [comment]
is this still an issue? hoz scrolling works as expected on my android. is it device specific?

**Comment by bhollis** [comment]
Yeah it's mostly iOS. You gotta use two fingers.
