### ISSUE TITLE
Enable "user-select" for certain content areas

### ISSUE THREAD

**Issue by renzy** [DestinyItemManager/DIM#3428]
i like to look at the progress page and often try to select some of the text to copy & paste into a search engine to find more information about what i need to do to complete the task if its unclear to me. 

right now the src/scss/_style.scss has #content set with "user-select: none;" that prevents text from being selected everywhere. totally understand the reasoning behind setting this & locking it down, but i think allowing some specific areas to have selectable text will be beneficial to your users. 

the following is a sample, or what i would like to see, have text i can select without disrupting the web application functionality:

```
diff --git a/src/app/progress/progress.scss b/src/app/progress/progress.scss
index 031da96..a43e86f 100644
--- a/src/app/progress/progress.scss
+++ b/src/app/progress/progress.scss
@@ -2,6 +2,7 @@
 
 .progress-page {
   margin: 16px auto !important;
+  user-select: text;
 
   .progress-characters {
     display: flex;
diff --git a/src/scss/_ngdialog.scss b/src/scss/_ngdialog.scss
index 0f30be6..e208ab4 100644
--- a/src/scss/_ngdialog.scss
+++ b/src/scss/_ngdialog.scss
@@ -30,6 +30,7 @@
       max-width: 80%;
       background-color: #222;
       border: solid 1px #3e3e3e;
+      user-select: text;
 
       @media (max-width: 800px) {
         max-width: 100%;
```

hope this helps, appreciate all the work that you guys have done with this!

**Comment by bhollis** [comment]
Totally reasonable. I’ll look into it.
