### ISSUE TITLE
loadout icons are broken

### ISSUE THREAD

**Issue by nki2bpz** [DestinyItemManager/DIM#343]
When viewing or editing loadouts the icons and text are no longer readable. 
eg.  ![Example ](http://i.imgur.com/4yLatzq.jpg)
FWIW The perc images from destinytracker have a similar problem causing me to think it was an issue with my copy of chrome. I've reset chrome and DIM with no change. looking at perc images from other databases does not produce the same problem

**Comment by nki2bpz** [comment]
i tried loading  v3.1.14 from local to test if it was related to most recent build but cant seem to get it to connect and update inventory so I'm of no help there.

**Comment by nki2bpz** [comment]
this appears to have been sorted out?

**Comment by SunburnedGoose** [comment]
Yep, v3.1.19 restored it .
