### ISSUE TITLE
Compare view icon touch field

### ISSUE THREAD

**Issue by mistral13** [DestinyItemManager/DIM#3433]
Please increase the icon (top right) for compare items and/or increase the margin for the icon.
With the new banshee icon, it is  not easy to tab the correct icon on mobile and ipad.
![043465bf-4241-4065-a1a5-dfe32fbe5c30](https://user-images.githubusercontent.com/5049663/49904953-3f7ed580-fe6c-11e8-8aec-69af896cb360.jpeg)

**Comment by mistral13** [comment]
and/or change the order (compare icon left)

**Comment by philkernick** [comment]
Also add more space between the lock icon and the name for the same reason.

**Comment by bhollis** [comment]
The whole thing is getting redesigned
