### ISSUE TITLE
Feature: Filter for passive power-leveling items

### ISSUE THREAD

**Issue by DHager** [DestinyItemManager/DIM#3435]
New feature, willing to take a stab at implementing it if there's agreement on the need.

**Use case:**

* I've already decided what items I really want to keep because they are unique or useful to my current character(s).
* I am also planning ahead for starting another character *in the future*, who will almost certainly be a different class.
* I want to ensure the new characters' level progression is swift, by taking advantage of the game's "best equip-able power level" code used for loot-drops. 
* I want to *minimize* how many of these items I keep in the vault.
* While I *may* equip those items on my new character, I don't necessarily plan to -- it's OK if they have terrible perks or don't fit my playstyle, because I'm keeping them for their passive effect.

**Proposal:**

A new specialty filter that highlights which weapons are "best" to keep around for a passive "better loot" progression boost. Unfortunately, I can't think of a name which is both self-explanatory and concise. Since these items push the power envelope within their group, perhaps call it `is:powerenvelope` for a working title.

A basic JS algorithm would be:

1. Create an empty `Map`
2. Loop through all the user's items where `is:haspower not:hunter not:warlock not:titan`
3. Create a key string from the item's minimum-level and loadout slot (ex: `43_kinetic`)
4. If the item's power-level is greater than the item already stored at that key (or nothing is stored yet) then write the key+item into the map.
5. Return all items stored in the map

**Other thoughts:**

* It might be possible for an lower-requirement item to "overtake" your best item at a higher level, making the latter superfluous. However, it isn't likely, and that optimization could cause problems if the user adds a `level:` filter which cuts across the boundary.
* I mainly see this as a filter for "catching" items that the user was already considering scrapping, helping the user realize that they have an alternate use.

**Comment by philkernick** [comment]
Has there been some change to the "best equipable power level" calculations because there doesn't seem to be a need to do any of this.  The drop power level calculation has never in D2 required you to have the items on your character (like it did in D1).  They can be equipped on other characters and it still works.

**Comment by philkernick** [comment]
From TWaB 18APR2018:  https://www.bungie.net/en/News/Article/46754

_Remember that all drops are calculated using your Best Possible Power, regardless of if you have the gear equipped or not. It can even be in the vault or on another character!_

**Comment by DHager** [comment]
@philkernick  Yes, I know. This is about deciding which gear to *keep in your vault*, and has nothing to do with moving the gear to a particular character:

> While I may equip those items on my new character, I don't necessarily plan to -- it's OK if they have terrible perks or don't fit my playstyle, because I'm keeping them for their passive effect.

**Comment by bhollis** [comment]
I don't think this one is above the line. Keep the suggestions coming though!
