### ISSUE TITLE
exotics released in 12-8 update do not show in inventory

### ISSUE THREAD

**Issue by nki2bpz** [DestinyItemManager/DIM#344]
I only have mida multi tool but i'm assuming the rest are buggered as well. armors show up fine

**Comment by SunburnedGoose** [comment]
What do you have in your developer console?

**Comment by nki2bpz** [comment]
3.1.20 I can't seem to get everything running right when running from file in developer mode

-------- Original message --------

**Comment by iBotPeaches** [comment]
```
please contact a developer to get this item added.
Missing Item Definition:

 ObjectartRegions: ObjectbindStatus: 0canEquip: falsecannotEquipReason: 0damageType: 0damageTypeHash: 0damageTypeNodeIndex: -1damageTypeStepIndex: -1equipRequiredLevel: 0isEquipment: falseisEquipped: falseisGridComplete: falseitemHash: 2639994641itemInstanceId: "6917529073235685487"itemLevel: 0location: 1lockable: falselocked: falsenodes: Array[0]objectives: Array[0]perks: Array[0]qualityLevel: 0stackSize: 1state: 0stats: Array[0]talentGridHash: 0transferStatus: 2unlockFlagHashRequiredToEquip: 0useCustomDyes: false__proto__: Object 
```

Yeah, Y2 Dragons Breath the same. I assume just a manifest update whenever it comes out.

**Comment by SunburnedGoose** [comment]
Press F12 if you're on Windows, or alt-command-i on mac and give me the
data from the console nki.

Bungie has to update the manifest for classified items...  Dunno when that
will happen.

**Comment by nki2bpz** [comment]
Missing Item Definition:

 Object 

please contact a developer to get this item added.
dimStoreService.factory.js:464 Missing Item Definition:

 Object 

please contact a developer to get this item added.
chrome-extension://apghicjnekejhfancbkahkhdckhdagna/images/Postmaster.png Failed to load resource: net::ERR_FILE_NOT_FOUND
dimStoreService.factory.js:464 Missing Item Definition:

 Object 

please contact a developer to get this item added.
dimStoreService.factory.js?v=3.1.21:464 Missing Item Definition:

 Object {itemHash: 1346849289, bindStatus: 0, isEquipped: true, itemInstanceId: "6917529075395109939", itemLevel: 49…} 

please contact a developer to get this item added.

**Comment by nivshah** [comment]
Here are my three, I have yr 2 MIDA, yr 2 Dragon's Breath, and a third one that I can't figure out what it is :)

artRegions: Object
bindStatus: 0
bucket: 1801258597
canEquip: false
cannotEquipReason: 0
damageType: 0
damageTypeHash: 0
damageTypeNodeIndex: -1
damageTypeStepIndex: -1
equipRequiredLevel: 0
isEquipment: false
isEquipped: false
isGridComplete: false
itemHash: 2996283228
itemInstanceId: "6917529072041367766"
itemLevel: 0
location: 1
lockable: false
locked: false
nodes: Array[0]
objectives: Array[0]
perks: Array[0]
qualityLevel: 0
stackSize: 1
state: 0
stats: Array[0]
talentGridHash: 0
transferStatus: 2
unlockFlagHashRequiredToEquip: 0
useCustomDyes: false
__proto__: Object

artRegions: Object
bindStatus: 0
bucket: 1801258597
canEquip: false
cannotEquipReason: 0
damageType: 0
damageTypeHash: 0
damageTypeNodeIndex: -1
damageTypeStepIndex: -1
equipRequiredLevel: 0
isEquipment: false
isEquipped: false
isGridComplete: false
itemHash: 2090751421
itemInstanceId: "6917529070611715040"
itemLevel: 0
location: 1
lockable: false
locked: false
nodes: Array[0]
objectives: Array[0]
perks: Array[0]
qualityLevel: 0
stackSize: 1
state: 0
stats: Array[0]
talentGridHash: 0
transferStatus: 2
unlockFlagHashRequiredToEquip: 0
useCustomDyes: false

artRegions: Object
bindStatus: 0
bucket: 1801258597
canEquip: false
cannotEquipReason: 0
damageType: 0
damageTypeHash: 0
damageTypeNodeIndex: -1
damageTypeStepIndex: -1
equipRequiredLevel: 0
isEquipment: false
isEquipped: false
isGridComplete: false
itemHash: 2496477295
itemInstanceId: "6917529060938020061"
itemLevel: 0
location: 1
lockable: false
locked: false
nodes: Array[0]
objectives: Array[0]
perks: Array[0]
qualityLevel: 0
stackSize: 1
state: 0
stats: Array[0]
talentGridHash: 0
transferStatus: 2
unlockFlagHashRequiredToEquip: 0
useCustomDyes: false
__proto__: Object

**Comment by nki2bpz** [comment]
sunburnedgoose had it right, they are still listed as classified by bungie and are not view-able on their companion app nor their gear manager so nothing to do but wait

**Comment by JosephBono** [comment]
This issue has been fixed via manifest update - can we close?

**Comment by nki2bpz** [comment]
Yes, sorry. I should have come back and closed it.

-------- Original message --------
