### ISSUE TITLE
Rearrange compared items

### ISSUE THREAD

**Issue by MyrHerder** [DestinyItemManager/DIM#3444]
Ability to rearrange items (left-right) in Compare Items interface. I know there are sort-by-stat options, but drag-to-sort would be nice.

**Comment by bhollis** [comment]
Thanks for the suggestion! I don't think we'll be adding this feature, though - it'd add a lot of complication to an already-complicated feature, and the sort by stat should be enough. Look forward to some general improvements to this tool soon, though.
