### ISSUE TITLE
Search for perks via inventoryItem hash "perk:<plugHash>"

### ISSUE THREAD

**Issue by ArkahnX** [DestinyItemManager/DIM#3446]
Related to issue #3431 in that searching for certain perks is more difficult than it should be.

This is a bit more of a power user feature, but we do have custom wishlists which is also a power user feature, so it wouldn't be unprecedented in my opinion.

With a local copy of DIM, all I needed to do was duplicate [Line 1075](https://github.com/DestinyItemManager/DIM/blob/e5ae8f4e7139ba7d005efca1c93677a064e7ac97/src/app/search/search-filters.ts#L1075) and then the boolean afterwards to include `plug.plugItem.hash` in addition to the name and description checks.

This allows you to try `perk:1812356167` in the search bar to find all armor pieces with rocket launcher reserves as an example.

**Comment by bhollis** [comment]
That's pretty obscure - I'm not sure how people would remember/discover what to put into the search.

I'd rather have a search autocomplete that lets you actually choose a particular perk to search for.

**Comment by 48klocs** [comment]
Expert mode wish lists basically let you do this.

**Comment by 48klocs** [comment]
Consider: a wish list with a single item.

Which admittedly isn't a great use case, but neither is searching by perk hash.

**Comment by wickles** [comment]
Agree with @bhollis. Example of why *perk-specific* search is necessary (and neither fixing the bug nor enforcing search from beginning of words is sufficient) is that searching for "fusion rifle" perks collides with "linear fusion rifle" perks. You can negate `-"linear fusion"` but then you miss any gear with both fusion and linear fusion perks.
