### ISSUE TITLE
Add non-equippable items to loadouts

### ISSUE THREAD

**Issue by shawly** [DestinyItemManager/DIM#345]
I use loadouts to quickly switch all the gear I need to the character I currently play.
But the thing that really bothers me is, that I always forget to switch ammo synthesises and Three of Coins to my current char and most of the time I notice that when it's too late and then I miss out the chance to get an exotic engram or I am left without special ammo when I really need it.

Why are non-equppable items not allowed in loadouts? Where is the problem with that feature?
Could you add it, or atleast tell me the line in your validation service where the item is checked for being equippable or not, so I can replace it myself?

As alternative it would be really cool if you could just specify the amount of items you want to switch, so I can split all the synths, materials and coins to all my chars evenly.

**Comment by nki2bpz** [comment]
one of the most useful features of the companion app is that you can choose how many consumables you want to transfer , With dim working so well i rarelty use the companion app

**Comment by bhollis** [comment]
Resolving in favor of #398, which is my full plan for consumables.
