### ISSUE TITLE
Feature Request: Filter to Highlight Items that will Dismantle to Enhancement Cores

### ISSUE THREAD

**Issue by boktai1000** [DestinyItemManager/DIM#3452]
Use-case: Since Enhancement Cores are still in high demand in the game (and with the current economy, probably will be into the foreseeable future) going through your Vault to cleanup old gear in hopes of reclaiming Enhancement Cores is something I've found myself doing ever since Forsaken released, and even now well into Black Armory, and is something I don't see changing.

Since there are "Tiers" of masterworking both Armor and Weapons, it appears that the masterwork level required and amount you'd reclaim from each level is static, but there's a lot more to consider now than just an "is masterworked" and "isnt masterworked" since there's some variance of inbetween that nets Enhancement Cores.

The proposal would be some sort of filter that could highlight all gear that would result in an Enhancement Core from a dismantle. Maybe even a way to tier your search based on how many cores you're looking for (such as 7 cores from a fully masterworked weapon).

Thank you for taking the time to listen to my suggestion and keep up the great work!

**Comment by delphiactual** [comment]
`masterwork:>= {tierNumber} is:{armor/weapon}`

**Comment by boktai1000** [comment]
@delphiactual thank you! and apologies for this open issue. have a good one!
