### ISSUE TITLE
Compare armor/ghosts based on perks

### ISSUE THREAD

**Issue by koinu** [DestinyItemManager/DIM#3458]
It'd be great if there was a way to open a comparison of armor for a given class/slot (ignoring name/set) that has a given perk by clicking on that perk node when looking at an item that has it (in the single-item view/popup).

I found myself wishing #3369 was implemented because my workflow for cleaning out armor rolls is search-based currently (for search's ability to ignore name/set), but realized this would be a better UX/workflow on its own.

The specific problem this would _really_ help with is: "oh, new helmet with Heavy Lifting and Heavy Ammo Finder" -> click on Heavy Lifting when looking at the item -> "oh, I already have three helmets that I only kept because of that combo, I can junk a couple of those and keep this one (or vice-versa)".

There might be additional utility in opening comparison based on combinations of perks, but being able to launch the comparison view based solely on (class, slot, one specific perk), which can be inferred from what item the clicked-on perk node was on, would be >90% as useful as perk-combination comparison at a fraction of the design and implementation effort.

**Comment by wein3967** [comment]
I feel your pain. I struggle more with managing armor than weapons. Until something like #3369 or your suggestion is implemented you can ... it is kinda rough, mind you ... use the wishlist feature currently in the DIM beta. If you want to test those waters the instructions are here: https://github.com/DestinyItemManager/DIM/blob/master/docs/COMMUNITY_CURATIONS.md

**Comment by bhollis** [comment]
#4781
