### ISSUE TITLE
New popup taller than it should

### ISSUE THREAD

**Issue by duckmanBR** [DestinyItemManager/DIM#3467]
At least on Android
![image](https://user-images.githubusercontent.com/32077894/50514529-e6c35580-0a85-11e9-93e0-0cf08c7ab603.png) ![image](https://user-images.githubusercontent.com/32077894/50514537-f04cbd80-0a85-11e9-9b67-cbbd570ad3b6.png)

**Comment by bhollis** [comment]
That’s actually intentional - I gave it a ton of padding because otherwise Safari will cover the move buttons with the navigation bar. I need to screw around in the simulator and see if I can find a better solution.

**Comment by bhollis** [comment]
Fixed this up a bit especially on Android where the Safari workarounds aren't necessary.
