### ISSUE TITLE
Loadout Builder filtering wrong items

### ISSUE THREAD

**Issue by duckmanBR** [DestinyItemManager/DIM#3468]
![image](https://user-images.githubusercontent.com/32077894/50514719-2fc7d980-0a87-11e9-917f-ec398e0eefd4.png)
I have only one chest piece with Enhanced Unflinching Sniper Aim, so any further locking shouldn't change the loadout.

Hand Cannon Reserves - changed the class/bond
![image](https://user-images.githubusercontent.com/32077894/50514744-6aca0d00-0a87-11e9-8165-8f6de51e5750.png)

Riven's Curse Mod changed Head/Arms/Legs/Class
![image](https://user-images.githubusercontent.com/32077894/50514747-73bade80-0a87-11e9-9204-cd90b1595296.png)

It's not a mobile bug because I reproduced it on desktop.
Tried to debug further but had no time to do it.

**Comment by kyleshay** [comment]
It looks like it is looking for Riven's Curse on all items when you only applied it to the chest?

**Comment by duckmanBR** [comment]
Yes. The same for the hand cannon reserves, affecting Chest and Class.
