### ISSUE TITLE
Mark of a Kellslayer Displayed as War Numen's Mark

### ISSUE THREAD

**Issue by wein3967** [DestinyItemManager/DIM#347]
Not a big deal, of course. I noticed that the thumbnail in DIM for my Mark of a Kellslayer is being displayed as the same graphic as the War Numen's Mark (v3.1.23).
![image](https://cloud.githubusercontent.com/assets/11590326/11799814/de8affde-a29c-11e5-8b26-01f6121f5d53.png)

**Comment by SunburnedGoose** [comment]
Bug in the meta data we get from Bungie.

**Comment by bhollis** [comment]
Closing since this is a Bungie bug - it'll either get fixed when they fix it, or not. I don't know that we'd know the right graphic to grab for it.
