### ISSUE TITLE
Infuse option not working in latest beta

### ISSUE THREAD

**Issue by AccessIT** [DestinyItemManager/DIM#3472]
The UI for infusible items does not appear when clicking on the "Infuse" option for weapons. Have tried both the installed app an in chrome with the same result

**Comment by bhollis** [comment]
Thanks, I just fixed this.

**Comment by AccessIT** [comment]
Thanks Ben, I am a C# dev and do a bit of cross platform. If I can be of assistance let me know as I love your app and use it all the time

**Comment by bhollis** [comment]
Feel free to check out our issues list, tgere are a few tagged as “need help”. Thanks!
