### ISSUE TITLE
Pursuits quick view

### ISSUE THREAD

**Issue by Markyb0y** [DestinyItemManager/DIM#3473]
It would be amazing to have a tiny section at the top of the pursuits section to show weekly completed progress per character towards Clan XP, Dreaming City Bounties and now ADA Bounties. having to look down each column for each type of bounty then count them to see if I have done enough XP yet, how many of Petras 8 daily bounties I have done or ADA's 7 bounties. Also I know people who now get a head start on next weeks bounties so that at reset they hand on the weeklys etc to start on the following week. something as simple as this under each character column would be amazing.

Clan: 3000 | DC: 4\8 | ADA: 3\7

keep up the great work!

**Comment by bhollis** [comment]
Hmm, that should be the "Milestones & Challenges" section. Clan XP definitely shows there, I'll have to check whether Dreaming City bounties do.
