### ISSUE TITLE
Remove Xur link from Account Milestones

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#3476]
There really doesn't seem to be a good reason to keep it in account milestones.

**Comment by bhollis** [comment]
I dunno, it's a "thing to remember to do". And weirdly enough it really is a milestone.

**Comment by philkernick** [comment]
I'd be really interested to know how many people have actually clicked on the link, given Xur doesn't sell any Y2 exotics.

**Comment by bhollis** [comment]
It's not a huge amount, maybe 1% of visits in the last week.

**Comment by philkernick** [comment]
If keeping it, consider merging with the ideas in #3473.

**Comment by bhollis** [comment]
Xur's going to be useful again in Season of the Drifter.
