### ISSUE TITLE
Search by specific perk

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#3486]
I'd like to make it so we autocomplete known perks, and when you select from the autocomplete it just searches for the exact hash you're looking for.

**Comment by DHager** [comment]
This is necessary when you want to find all helmets with `Fusion Rifle Targeting`  rather than `Linear Fusion Rifle Targeting`, and you want to *include* ones that have both.

**Comment by delphiactual** [comment]
or `Frenzy` and `Feeding Frenzy`

**Comment by DHager** [comment]
FWIW  my workaround is `perk:"being in combat"` for `Frenzy`. 

Since the ticket was filed I believe `perkname:` was added, but unfortunately it uses the same non-exact matching, so `perkname:"Frenzy"` still contains false positives.

**Comment by bhollis** [comment]
The idea here would be to have a search like `perkHash:2779035018` for Feeding Frenzy, and have the autocomplete show this as `perk:"Feeding Frenzy"`. This'd require some work on the search system to show something different from the actual input (though it'd also allow things like showing perk/item icons inline in the search string).

Another option is to just have an `exactPerkName:"Feeding Frenzy"`.

**Comment by DHager** [comment]
Personally I prefer the latter like `exactPerkName`. I'm guessing the hashes are for people generating wishlists, or perhaps using data from other services?

**Comment by Revadike** [comment]
> or `Frenzy` and `Feeding Frenzy`

This specifically is quite annoying. I want to search for frenzy rolls, but I get feeding frenzy rolls.
