### ISSUE TITLE
Include mod/perk effects in displayed stats

### ISSUE THREAD

**Issue by spnkr** [DestinyItemManager/DIM#3488]
The forsaken Antiope-D (2561659919) w/ a counterbalance mod shows the wrong recoil direction. It should be 100, not 90.

![image](https://user-images.githubusercontent.com/11250/50557823-dcd46900-0cb6-11e9-80c5-ba34396ffed5.png)

According to https://db.destinytracker.com/d2/en/items/2561659919-antiope-d the base recoil of this gun is 90.

Banshee-44 does apply a +10 (out of the max +15 from a counterbalance mod), turning 90 into 100.
![image](https://user-images.githubusercontent.com/11250/50557716-c679dd80-0cb5-11e9-802f-705a199a70cb.png)

The zoom numbers don't match on banshee-44 and DIM, don't know if that's related. but who cares about zoom!

**Comment by bhollis** [comment]
Yeah, I’m pretty sure we have never applied stat bonuses from perks/mods.

**Comment by duckmanBR** [comment]
It may be an API bug? Since perk/mw effects are already returned by the API.

**Comment by delphiactual** [comment]
closed by #4159
