### ISSUE TITLE
Tagging via keyboard shortcuts no longer working

### ISSUE THREAD

**Issue by TheAardwolf** [DestinyItemManager/DIM#3489]
Since recent update, shortcuts (shift+1/2/3/4) no longer tag items.
Tested in Vivaldi, Chrome, Firefox.

**Comment by bhollis** [comment]
Good catch, I can put that back.

**Comment by delphiactual** [comment]
Closed by https://github.com/DestinyItemManager/DIM/commit/07b2ce284fd2b6063880c7c4c29268aba498e448
