### ISSUE TITLE
Item popup partially hidden on mobile

### ISSUE THREAD

**Issue by GregSawin** [DestinyItemManager/DIM#3490]
On my S9 android the item popup in portrait mode shows only the top of the popup, at the bottom of the screen and it's not scrollable.  So it's impossible to transfer items via item popup.  If I rotate my phone to landscape I can at least scroll down to see the transfer buttons.

**Comment by bhollis** [comment]
We’re trying to figure this out. It’s pretty weird as it only happens for some Android phones.

**Comment by Wh1rledPeas** [comment]
I was just coming to report this. DIM is unusable for me right now.

I've not worked with your framework, but if you need any debugging, I'm very familiar with web technologies. 

![screenshot_20181231-151404](https://user-images.githubusercontent.com/3685437/50567124-539d5080-0d0f-11e9-9c11-a3c10f7946b5.png)

**Comment by Wh1rledPeas** [comment]
In case this makes a difference... 
![screenshot_20181231-152948](https://user-images.githubusercontent.com/3685437/50567274-04f0b600-0d11-11e9-97fb-70ff2fc3dfc4.png)

**Comment by delphiactual** [comment]
Fixed by https://github.com/DestinyItemManager/DIM/commit/6365d39be2c3ead0cf4c24d15af049bfa5bfea67

**Comment by Wh1rledPeas** [comment]
@delphiactual Any chance this will be patched in production any time soon? We're kind-of dead in the water out here.

**Comment by delphiactual** [comment]
@Wh1rledPeas it was 5.8.1 is live on production

**Comment by Wh1rledPeas** [comment]
@delphiactual I see that Rob. Thanks for jumping on this so quickly (on new years eve day of all days) so that your users aren't left flailing! 😊 You rock!

**Comment by delphiactual** [comment]
It was a team effort
