### ISSUE TITLE
Tag state can persist across selection of untagged items

### ISSUE THREAD

**Issue by irons** [DestinyItemManager/DIM#3491]
Steps to reproduce:

• Click on an item with a tag.
• Click on an untagged item. The tag popup menu will show the same tag as the first item, instead of the expected "Tag Item" null state.
• Click somewhere in the background to hide the item info display, then click on the same untagged item again. The tag popup menu now says "Tag Item", as expected.

Sequentially selecting items with tags does update correctly; I'm only noticing a problem when going directly from a tagged item to an untagged item. 

I'm using DIM 5.8.1, on Chrome 71.0.3578.98, on macOS 10.13.6. Thanks for your time.

**Comment by delphiactual** [comment]
Closed by #3495
