### ISSUE TITLE
Infusion Fuel Finder Column Caption display discrepancies

### ISSUE THREAD

**Issue by Wh1rledPeas** [DestinyItemManager/DIM#3499]
The column caption on the left only appears when choosing to show locked items. Pretty minor, I know... Just here so you can fiddle with it whenever you're working on the Infusion Fuel Finder

![screenshot_20190101-232055](https://user-images.githubusercontent.com/3685437/50580429-82551d00-0e1c-11e9-88c1-908818c6ea40.png)
![screenshot_20190101-232103](https://user-images.githubusercontent.com/3685437/50580453-c7794f00-0e1c-11e9-9380-22163ce9b4d5.png)

**Comment by bhollis** [comment]
This whole thing is getting redesigned soon.

**Comment by bhollis** [comment]
Closed now that this has been redesigned.
