### ISSUE TITLE
Search by item ID

### ISSUE THREAD

**Issue by SaahilNZ** [DestinyItemManager/DIM#3500]
When searching for items, being able to search for a specific item by its instance ID could be useful. Having a 'id:' filter would let external tools generate a list of item IDs to filter in DIM (i.e. "id:6917529068726458536 or id:6917529084949166388 or ...").

**Comment by bhollis** [comment]
Could you go into more detail about how exactly this would be used?

**Comment by SaahilNZ** [comment]
So, let's say that I have a tool that would find all my items that have either have bad perks or I have an item with similar, but better perks, and could spit out a list of the IDs of all of those items. Having an 'id:' filter in DIM would let you search for those exact items, which you could then mass tag as junk, and then dismantle.

**Comment by bhollis** [comment]
Do you have a tool like that? Could we buikd that functionality into DIM?

**Comment by SaahilNZ** [comment]
I'm currently in the middle of writing such a tool. So far it can compare armour pieces to find which ones have bad perks or an item that has similar/better perks.
![image](https://user-images.githubusercontent.com/25736070/50615820-e8d85900-0f4a-11e9-9fbe-7816f31887d6.png)
Whether or not a perk is good, as well as what upgrades that perk has are currently stored in a spreadsheet, though the goal is to eventually let users pick what perks they consider good.

**Comment by wein3967** [comment]
As far as the original filter request goes, an id: or hash: is just generally useful for developers of all levels since many use the spreadsheet export as a starting point. From there, for whatever they are doing, identifying the item(s) of interest would be easier with a filter vs. searching the Chrome/developer tools/elements console for the same hash number. In the end, this would be a more developer/power user level feature. I don't see a normal user knowing or even using the item hashes. (@dasilva333)

**Comment by bhollis** [comment]
Sure, I could see it being used, but I'd prefer to build in this sort of functionality into DIM than to not know about it and have people using janky workarounds to try and import data from other tools.

**Comment by tcurtin** [comment]
I was just looking for this ability (the id based item search) while digging into #3513.  Add my vote for it as a great capability for development.  (Speaking of which, @SaahilNZ, are you starting your tool working from the csv export?  I was also starting to create some tools to do deletion suggestions — how are you handling the perks?)

**Comment by SaahilNZ** [comment]
I did start from the CSV export, but in a pretty roundabout way. I set a breakpoint when exporting the armor CSV, and used some JavaScript in the Console to build up an array of objects from the data, then printing that to the console as JSON.

**Comment by tcurtin** [comment]
Strong work!  Mind bouncing me the javascript you used?  I’m wondering if it would help me with trying to improve the export function...

**Comment by bhollis** [comment]
It sounds like you guys just want to build an app so you can get directly at the data...

**Comment by SaahilNZ** [comment]
@bhollis should I open up a new issue for my item rating system? I'd be more than willing to try and integrate it into DIM.

**Comment by SaahilNZ** [comment]
@tcurtin sure thing.
```javascript
JSON.stringify(
    e.flatMap(e => {
      perks = [];
      if (e.sockets) {
          perks = e.sockets.categories[0].sockets.map(s =>
              s.plugOptions.map(po =>
                po.perks.length > 0 ? po.perks[0].displayProperties.name : ""
              )
            );
      }
      console.log(perks);
      return [
        {
          id: e.id,
          item: e.name,
          class: e.classTypeName,
          tier: e.tier,
          type: e.typeName,
          tag: e.dimInfo.tag,
          power: e.basePower,
          perks: perks
        }
      ];
    })
  );  
```
I set a breakpoint in the settings script at the foreach in the "Armor" case.

**Comment by wein3967** [comment]
@tcurtin I was kind of doing it the same way as @SaahilNZ. I shortcircuited the csv export in the dimCsvService.factory.ts right inside the for loop (line113). From there you can send whatever you want to test to the console. I pushed single items first by id, so I could try to figure out where the perks were located in the object model. Then I just started testing different vintages of armor to look for consistent patterns.

**Comment by bhollis** [comment]
@SaahilNZ that would be great!

**Comment by tcurtin** [comment]
Back to the original request, my personal two use cases are as developer and as user with a csv export in front of them they want to act on.

As a Dev, when getting into the specific details of different items and their perks and trying to understand perks and columns, etc there have already been several instances when I just wanted to find the item in question and see what it looked like in the GUI.  The GUI does such a good job of showing the info, and being able to get that quickly to compare against a dump in a csv is way easier than digging through twisties in the developer Console.

As a user with the csv export, regardless of how that's being used, its not hard to image wanting to act on an item found in it.  Say I have 10 of the same boots, and prowling the csv I'm able to come up with one of them to delete.  DIM is pretty much the only way to find it at all.  Possible by a combined search for item name, power, perk, yes.   But search by id is immediate and easy.

**Comment by bhollis** [comment]
Here's a PR to add `hash:` and `id:` searches. They won't be documented but they'll work. @tcurtin I also shipped CSV import, which is probably the right way to do what you're talking about.
