### ISSUE TITLE
Vault count does not match in-game

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#3501]
![screenshot from 2019-01-01 21-48-57](https://user-images.githubusercontent.com/4798491/50580702-3485e800-0e0f-11e9-877c-8607ad3c55b9.png)

**Comment by bhollis** [comment]
Gonna need more info on this.

**Comment by 87c120aa** [comment]
As DIM shows:
![vault-count-in-dim](https://user-images.githubusercontent.com/46359360/50664285-88611000-0f7a-11e9-9890-9bc637546923.png)

As the game shows:
![vault-count-ingame](https://user-images.githubusercontent.com/46359360/50664296-9020b480-0f7a-11e9-97ca-92c6f7572305.png)

**Comment by bhollis** [comment]
Any idea which three items are extra?

**Comment by 87c120aa** [comment]
I had hoped to avoid a tedious manual reckoning :)

However, it looks like its these:

![what-are-these](https://user-images.githubusercontent.com/46359360/50673996-6e422480-0fb0-11e9-957f-fe679a128a7c.png)

These items are sorted as if they're mods. Every other item in my vault has been accounted for within DIM.

**Comment by bhollis** [comment]
Makes sense. They're in the vault, but DIM doesn't know exactly what they are because everything about them is classified. When they're unclassified, this will be corrected. Unfortunately there's not a lot we can do about it.

**Comment by 87c120aa** [comment]
But they're *not* in my vault. There's noting in the vault in-game that corresponds to them.

**Comment by delphiactual** [comment]
in-game they actually have icons. or are you saying that classified items are being counted as in the vault when they are on your person?

**Comment by bhollis** [comment]
They are classified "items" that are in your "profile inventory". All kinds of things can be items - these could, for example, be classified account-wide quest steps! We don't know what they are, because they're classified, so we have to put them somewhere.

**Comment by 87c120aa** [comment]
Ok, however this causes DIM to treat the vault as 500-$number_of_classified_items.

**Comment by 87c120aa** [comment]
For the record, this is two 998352072 and a 2485376619

**Comment by bhollis** [comment]
Well, usually they correspond to real items in the vault. In this case I bet they’re quest items or something. 

We have an ask out to Bungie to avoid classifying *everything* about an item so we at least know where it belongs.

**Comment by bhollis** [comment]
https://github.com/Bungie-net/api/issues/138#issuecomment-451605542

**Comment by bhollis** [comment]
@87c120aa did today's manifest update fix this?

**Comment by 87c120aa** [comment]
> @87c120aa did today's manifest update fix this?

No, unfortunately not.

**Comment by bhollis** [comment]
Closing since we can't do anything until Bungie provides more info on redacted items.
