### ISSUE TITLE
Item popup transfer buttons extend off screen on mobile.

### ISSUE THREAD

**Issue by Wh1rledPeas** [DestinyItemManager/DIM#3502]
The new layout for transfer buttons in the item popup forces the Infusion Fuel Finder off the right side of the screen.

I realize this is most likely because I use a display size of [Larger] and I also realize the area is horizontally scrollable, but it used to work just fine. Keep in mind there are older players out here that use the operating system's built-in features to make things more readable. 🧐🤓

There seems to be a fair amount of padding between the images. Perhaps you can configure the padding so that the buttons are spread across the dialog evenly, shrinking down to zero padding before the dialog resorts to horizontal scrolling?
![screenshot_20190101-234250](https://user-images.githubusercontent.com/3685437/50580752-9e5abd80-0e20-11e9-8faf-7df72bb4a98f.png)

**Comment by bhollis** [comment]
How wide in pixels is your screen? The buttons are not dynamically sized, but were made larger to be easier to tap on a typical screen size (iPhone 375px). 

This is all getting redesigned quite soon and these buttons will be moved elsewhere.

**Comment by Wh1rledPeas** [comment]
I have a Google Pixel XL. The display resolution is 2,560 x 1,440 (534 ppi). So I doubt it has anything to do with display resolution.

Android has a setting that allows the entire display to be made smaller or larger, depending on your preference.

(Small, Default, Large, Larger, or Largest)

Mine is set to Larger because my eyesight isn't what it used to be. 

The icons used to fit just fine and I think they still would if it wasn't for the padding between them. I was wondering if the horizontal padding could be made dynamic, with 0 being the minimum, so they would shrink up on displays where they would be too wide. Perhaps their parent "box" set to a width of 100% and the icons padded evenly so each of them take up 1/7 of the width. (Invisible placeholders on the right so there are always 7 boxes, would make it feel the same from layout to layout, but that's a bit more work) 


I've attached screenshots of DIM in each of those display modes for your reference. You'll notice that the icons for the items scale properly and remain laid out according to the width of the screen. The action buttons don't.

*SMALL*
![screenshot_20190102-142845](https://user-images.githubusercontent.com/3685437/50608671-4f9e3980-0e9b-11e9-8457-f48bba84a7de.png)

*DEFAULT*
![screenshot_20190102-142925](https://user-images.githubusercontent.com/3685437/50608698-647acd00-0e9b-11e9-8cda-9f41bf05813f.png)

*LARGE*
![screenshot_20190102-143021](https://user-images.githubusercontent.com/3685437/50608725-76f50680-0e9b-11e9-9d54-82900db54637.png)

*LARGER*
![screenshot_20190102-143101](https://user-images.githubusercontent.com/3685437/50608748-8a07d680-0e9b-11e9-9381-6eff96f67e3a.png)

*LARGEST*
![screenshot_20190102-143649](https://user-images.githubusercontent.com/3685437/50608886-f08cf480-0e9b-11e9-86ed-a3f345f58a12.png)

**Comment by bhollis** [comment]
Right, my suspicion is that the scaling modes present a different "virtual" screen size. 

We can definitely make these dynamically sized, but I'm very close to just replacing them at this point.

**Comment by Wh1rledPeas** [comment]
Understood Welk, I can certainly muddle through for a little bit. It's just annoying having to scroll horizontally to tap the [Infuse] button.

At least you have some screenshots for a point of reference, so you can make educated decisions on how to layout your new design.

**Comment by bhollis** [comment]
Yeah, everything in the new design is more oriented around mobile.
