### ISSUE TITLE
Item popup retains expanded/collapsed state between uses. 

### ISSUE THREAD

**Issue by Wh1rledPeas** [DestinyItemManager/DIM#3503]
Steps to reproduce:

1. UNCHECK option to "Always show expanded item popup". 
2. Tap on any weapon/armor/item. 
3. Tap [down arrow] to expand. 
4. Tap [X] to close. 
5. Tap another item.

RESULT: All subsequent Item Popup Dialogs open in expanded mode.

EXPECTED RESULT: Subsequent Popup Dialogs should open according to the CHECKED/UNCHECKED state of the setting.

**Comment by duckmanBR** [comment]
We changed the behavior of the popup on 5.8.0 (2018-12-30) with PR #3465
_"Popup expanded/collapsed is based on the setting now, and toggling it saves in settings."_

**Comment by Wh1rledPeas** [comment]
This is a terrible design choice in my opinion. I elect to set that setting because 99% of the time I just want to tap on the item and tap a button to move it somewhere.

Every once in a while, I want to see the details.... But very rarely...

**Comment by Wh1rledPeas** [comment]
Perhaps the setting should have been changed to a tristate instead of boolean, to accommodate users who prefer things the way they were?

**Comment by bhollis** [comment]
This is by design - it will simply remember how things were. The popup is getting more drastically redesigned soon to not even have the option to collapse very soon.

**Comment by Wh1rledPeas** [comment]
@bhollis That would be a shame for those of us on the mobile platform. We already have such limited screen real-estate. 😕

**Comment by duckmanBR** [comment]
I think you didn't realize that it works both ways... If you collapse a pop up the subsequent ones will also be collapsed.
Bhollis just did a quick toggle

**Comment by Wh1rledPeas** [comment]
I understand how it works. It adds one extra step every time I want to view details of an item

PREVIOUS PROCESS:
===
1. Tap item
2. Expand details
3. Tap anywhere other than the dialog (or even scroll) to close

RESULT:
===
Subsequent Item info Dialogs did not show details, allowing an quick, 2-Tap to move/infuse any other items.

NEW PROCESS:
===
1. Tap item
2. Expand details
3. Collapse details
4. Tap ONLY the X to close

RESULT:
Same, but only if the extra step 3 is performed. If I forget to minimize the dialog before closing it, subsequent items require a slower Tap+Scrolldown+Tap operation to move/infuse an item. Either that or a Tap+Minimize+Tap. Either way you look at it, there's an additional step with the new process. Scrolling and sliding are slow and clunky on the mobile platform. I'd rather keep it to a two-step process, not add an additional step.
