### ISSUE TITLE
Scrolling back to the top of content in the Item Popup causes it to close. 

### ISSUE THREAD

**Issue by Wh1rledPeas** [DestinyItemManager/DIM#3504]
When viewing the Item Popup on a screen which forces a vertical scroll, scrolling back up to the top after viewing content lower in the dialog, causes it to close.

I'm assuming this is due to the "swipe down to close" being attached to the entire dialog instead of just the title bar. 

Steps to reproduce:

1. Use the mobile platform to restrict screen size.
2. If required, increase the device's display size to force a scrollbar to be displayed. 
3. Tap on a weapon. 
4. Scroll down (swipe up). 
5. Scroll back up (swipe down) to the top of the content.

RESULT: Popup closes.

EXPECTED RESULT: Scrollbar should reach the top. Popup should remain open.

![screenshot_20190102-002632](https://user-images.githubusercontent.com/3685437/50581181-48d4df80-0e25-11e9-89e7-c6bd209a9085.png)

**Comment by Wh1rledPeas** [comment]
Yes. I tested both multiple times to make sure I was doing what was required to cause the issue. It consistently closed in production, but not in beta. I think you squashed that one! 😊

**Comment by bhollis** [comment]
Great, thanks for the help in reproducing it!
