### ISSUE TITLE
Character background shading isn't consistent

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#3505]
It isn't at all clear why some character columns get a background colour, nor how the colour is selected.

![image](https://user-images.githubusercontent.com/25425159/50583054-f93ef400-0eb6-11e9-9490-65db14a7ac7a.png)

The Hunter column has a redish background colour that appears to come from the currently equipped emblem.  The Warlock and Titan don't have background colours, despite their emblems being green and blue respectively.  The Warlock is the current character.

**Comment by Wh1rledPeas** [comment]
While we're discussing this "feature", I find it to be more of an annoyance on the mobile platform. We can't see more than one column at a time, so it appears more like an abnormality than something that's related to each character.

The darker the background, the cleaner the interface looks (and the less battery it uses 😉)

If I had the option this would only be active on displays large enough to display more than one column.

**Comment by bhollis** [comment]
Many of the emblems have dark or muted backgrounds specified by the API. This is meant to be a subtle effect, and that's just how it is. A few have really bright colors which is what you're seeing. This is all working as designed.

**Comment by bhollis** [comment]
Looks like this is actually driven in some parts by a bug where certain browsers can't handle fractional colors.

**Comment by Wh1rledPeas** [comment]
Do you have an easy way to convert it to "web safe"?

**Comment by bhollis** [comment]
I don’t think anybody still uses a 256-color display.

**Comment by Wh1rledPeas** [comment]
They never did. (well, LONG before the web came around) 256 was a limitation of browsers. If you make the color "web safe", then all browsers will display things the same. 🤔

**Comment by delphiactual** [comment]
https://websafecolors.info/
https://websafecolors.info/learn

**Comment by Wh1rledPeas** [comment]
I'm sorry. Perhaps I shouldn't have used the term "web safe" so loosely. I wasn't referring to the limited 216 color web pallette, I was referring to the 65,536 colors that are representable in whole integer numbers (0-255) or hexadecimal numbers (00-FF) for Red, Green, & Blue

Based on Ben's description of "fractional colors", I assumed that the RGB numbers were not whole numbers. Hence my suggestion to convert them.

@delphiactual - That article you provided is a little off. Probably someone's personal opinion. XGA monitors with the capability to display 65,536 colors became available around 1990 and the very first web site ever built was launched on August 6th, 1991. It did not contain images or color. Just black text and blue hyperlinks. The first version of the Mosaic web browser wasn't even released until 1993. Computers were capable of displaying more than 256 colors long before the "web safe" pallette was defined. It had to do with the size of image files as well as capabilities of the browser software.

Anyway... I was just suggesting to round the RGB values to whole numbers, not fractions.

**Comment by bhollis** [comment]
Never mind, it was a bug I had already fixed (by rounding the values).
