### ISSUE TITLE
Include a "Gather Dupes" button on item popup actions

### ISSUE THREAD

**Issue by Wh1rledPeas** [DestinyItemManager/DIM#3506]
Based on the following comment from @bhollis, I've been using the Infusion Fuel Finder to transfer duplicates locally for comparison and review...

https://github.com/DestinyItemManager/DIM/issues/2834#issuecomment-390446906

When you added the feature to group duplicates at the top, that helped immensely! Unfortunately, there are two instances where duplicates are not grouped at the top or even shown in the list at all.

1. When their power level is an exact match.
2. When one of the items is a year 1 item. 

With regards to (1), I realize that they technically aren't infusable, but they still need to be brought locally for comparison and determining which to dismantle.

With regards to (2), I know it's been discussed before, but in this case I have a fully masterworked year 1 weapon that's cheaper for me to infuse than to fully masterwork the new item, so I'll want to keep that around. Additionally, when searching for duplicates, I want to know if I have a year 1 item, so I can dismantle it when I get a newer version. They should at least show up with is:dupe

Here's a recording that illustrates the pain involved with this situation on the mobile platform... 

[![DIM - Infusion Fuel Finder - Duplicate Items Missing](https://img.youtube.com/vi/U-0MG1Vd8XM/0.jpg)](https://youtu.be/U-0MG1Vd8XM)

**Comment by bhollis** [comment]
This just isn't meant to be a "gather duplicates" or "find duplicates" feature, it's for finding infusions. We are redesigning the move popup and compare features, and it'll be much more reasonable to just add new buttons there.

With regard to item 2, there has been some conflicting information about whether or not Year 1 versions of weapons can be infused by Year 2 versions. In the item database they are entirely separate items. Can you confirm that they can be infused like that?

**Comment by Wh1rledPeas** [comment]
Hi Ben.

I understand it's not supposed to be a "find duplicates" feature, but you suggested we use it that way when we requested a "gather duplicates" button and 99.9% of the time, it fits the bill just fine. Especially since you started grouping duplicates at the top. 

When you tap [Infuse] it shows all duplicate year 2 items that are higher in power and lower in power, just not matching power levels. I realize they technically can't be infused, but even if they're the same power level the user still needs to decide which one to keep. If the dev team can come to accept that rare occurrence, it would work 100% of the time and leave the application leaner than building separate functionality and adding more buttons.

I also feel like the infusion process is a lot different now with random rolls and requires a fair amount of user preference that wasn't a consideration in year 1.

I think most users avoid keeping more than one version of a weapon around, albeit for testing to see which they like better and would consider the "infuse vs dismantle" decision one in the same. Especially with random rolls. Quite often I get higher power duplicates that I choose to dismantle rather than infuse because they're only a few levels higher.

But I still bring them local to the character using the infusion finder, so I can compare them using the console. We can't flip perks on/off in DIM, so comparing anything visually in DIM requires flipping them from the console then refreshing DIM.

I do remember infusing a few year 1 items for Glimmer only, but I haven't seen it possible since shortly after Forsaken launch. However... Isn't it up to the user to decide whether to infuse, dismantle, or keep duplicates? 

I'm a software architect myself, so I completely understand why it's like nails on a chalkboard to think of making an exception for a very small use case, but I don't feel that rare occurrence warrants completely new functionality. You guys can spend your time on much more needed things.

**Comment by kyleshay** [comment]
Can this just be solved with a search/transfer search?

**Comment by bhollis** [comment]
Yeah, definitely. I do have this implemented on a branch but it's awkward - like, do you always gather to the active character? To the character that owns the item you clicked on?

**Comment by kyleshay** [comment]
It also sounds like this problem will be helped out a bit with the mobile search results sheet https://github.com/DestinyItemManager/DIM/pull/5978 -- It sounds like the issue here was that is:dupe was difficult to use because it required tabbing through all of the characters (same goes for most other searches on a phone.) The results sheet puts them all in 1 spot with easy move/tag/compare buttons right there.

**Comment by bhollis** [comment]
Closing this - I just don't think it makes enough sense as a top-level action.
