### ISSUE TITLE
Perk search no longer working Russian/Korean

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#3507]
After #3484
Reports from Reddit and Discord

https://www.reddit.com/r/DestinyItemManager/comments/ab7lje/perk_search_doesnt_work_in_korean/

EDIT: this probably affects all non-latin based languages

**Comment by delphiactual** [comment]
수집가 - scavenger    /  비축량 -  reserves    / 핸드 캐논 수집가 - hand cannon scavenger

**Comment by bhollis** [comment]
Makes sense, they don't have traditional word boundaries. I'll change the regex for CJK languages.
