### ISSUE TITLE
spreadsheet export: "perks" muddied by masterwork, shaders

### ISSUE THREAD

**Issue by tcurtin** [DestinyItemManager/DIM#3513]
I was thinking I'd come up with some complicated personal script tools to comb through my armor list, and I see that perks are now in the beta export!  But -- I'm hoping its still a work in progress, because it seems inconsistent.

Three sample gauntlets:
Name,Hash,Id,Tag,Tier,Type,Equippable,Power,Masterwork Type, Masterwork Tier,Owner,Locked,Equipped,Year,Season,Event,DTR Rating,# of Reviews,Mobility,Recovery,Resilience,Notes,Perks

"Reverie Dawn Gauntlets","2503434573",6917529085349656273,favorite,Legendary,Gauntlets,titan,625,Solar Damage Resistance,5,Titan(648),true,false,2,4,,N/A,N/A,1,0,2,,Mobile Titan Armor*,Plasteel Reinforcement Mod*,Restorative Mod,Riven's Curse*,Masterwork*,Burnished Dreams*,Enhanced Impact Induction,Enhanced Grenade Launcher Loader,Enhanced Hand Cannon Loader*,Rocket Launcher Scavenger*,Sniper Rifle Scavenger
(11 perks columns)

"Iron Fellowship Gauntlets","3856697336",6917529086394623061,,Legendary,Gauntlets,titan,500,Solar Damage Resistance,1,Titan(648),false,false,2,5,,N/A,N/A,1,0,2,,Mobile Titan Armor*,Plasteel Reinforcement Mod*,Restorative Mod,Tier 1 Armor*,Iron Strength*,Hand Cannon Loader*,Impact Induction,Sniper Rifle Scavenger*,Machine Gun Scavenger
(9 perks columns)

"Tangled Web Gauntlets","42219189",6917529085682088446,,Legendary,Gauntlets,titan,634,Arc Damage Resistance,1,Titan(648),false,false,2,4,,N/A,N/A,0,1,2,,Restorative Titan Armor*,Plasteel Reinforcement Mod*,Restorative Mod,Tier 1 Armor*,Shotgun Loader*,Fastball,Shotgun Scavenger*,Sword Scavenger
(8 perks columns)

I **think** this is what could be there and the order:
Armor type ("Mobile Titan Armor")
Col 1 Mod 1 ("Plasteel Reinforcement Mod")
Col 1 Mod 2 ("Restorative Mod")
Mod slot - optional ("Riven's Curse")
Masterwork level - optional ("Masterwork" or "Tier 1 Armor")
Shader - optional ("Burnished Dreams")
Column 1 and Column 2 perks in order, but no column specified ("Enhanced Impact Induction", etc)

Having multiple optional columns like shader, and no indication of which columns are perks, means short of a lot of hardcoded lists etc being added, no script can use the perks values in the sheet...

Any chance we could have separate columns for optional mod, masterwork level, and shader?  (Best would also be maybe 4 columns for possible column 1 perks, 4 for possible column 2, and just leave blank when one isn't found.)

I recognize that its very difficult to translate data with a changeable standard (how many columns are there in an item?  how many rows per perk column?  how many perk columns?) into another exportable format...

I unfortunately don't have a ton of time to work on the code involved, but if someone would be willing to handhold me a bit to get to the code involved, I could probably poke around and help...

**Comment by bhollis** [comment]
Here's the code: https://github.com/DestinyItemManager/DIM/blob/master/src/app/inventory/dimCsvService.factory.ts

It's pretty simple - feel free to submit a PR to clean up the export.

**Comment by tcurtin** [comment]
I've started crawling around the DIM code for the first time now, and I have some questions, specifically around armor items:

(Please forgive and redirect me if this is the wrong method or place to be asking these...  DIM GitHub kinderguardian here.)

If I'm looking at a specific item in the debugger, what's the easiest way to find that item in DIM?  I feel like I should be able to query id: in the DIM window, but that doesn't do anything.  This feels like too valuable a debugging tool, so I must be missing something.

Is there a place within item.sockets.sockets.plug.plugItem that I should be able to figure what column that perk is in (specifically looking at p.plugItem.itemTypeDisplayName = 'Armor Perk' where you can have varying numbers of them in multiple columns)

When item.sockets.sockets.plug is a masterwork level (plugItem.displayProperties.name="Tier XX Armor" both plugItem.itemTypeAndTierDisplayName and plugItem.itemTypeDisplayName are blank - bug or intentional?

**Comment by wein3967** [comment]
@tcurtin So, I was looking at this not too long ago as well. From as far as I got, I'd recommend accessing the various "perks" via `sockets.categories[0].sockets[0].plugOptions[0].plugItem.displayProperties.name`. Now the issue I ran into was that most perks were in consistent array locations across year 1, year 2, and exotics (e.g., intrinsic perk, mod 1, mod 2, perk, C1R1, perk C1R2 ...). However, the custom mod, masterwork tier, and shader were not in the same array locations.

With regards to finding a specific item in DIM, as you know #3500 you can't directly use the DIM filter. However, you can use the Chrome Developer Tools window. Once you open the Developer Tools, you can select the elements tab. From there you can manually drill down visually, or Crtl+F and search for a specific hash/id (shown).
![untitled](https://user-images.githubusercontent.com/11590326/50672722-79408900-0f9f-11e9-9720-fb3cf3b821c2.png)

**Comment by bhollis** [comment]
Check out https://github.com/DestinyItemManager/DIM/blob/master/src/app/inventory/item-types.ts - it explains the entire structure of DIM items. `item.sockets.categories` is a list of the "categories", the first of which is perks, the second is mods.

I've been developing DIM for years and years and I've never once wanted to highlight a particular item instance - I'm still a bit confused as to how that would help debug anything. Most of the time I just add `console.log` statements to the code. DIM is pretty easy to get up and running on your own machine and hack around with, see our [Contributing Guide](https://github.com/DestinyItemManager/DIM/blob/master/docs/CONTRIBUTING.md).

**Comment by tcurtin** [comment]
Thank you for the pointer to item-types.ts, that definitely helps!  There's a **ton** of great info available through the data structures here!

The problem I'm having is the standard issue when working with vendor data we don't fully control: in order to have the csv export be useful, we need to make each column **always** mean the same thing for all rows in that export.  I may need some clever suggestions for finding consistent locations in the data structures for all the elements I want to output.

I like the idea of using the item.sockets.categories, but I've found multiple instance of categories having only a single item (any scorched solstice gear, so maybe that's a bug) -- in this case there's no perks list, so mods is in position 0.  Would it be better to use categories.length-1 index to get to mods and only look for perks if categories size > 1?
![image](https://user-images.githubusercontent.com/979464/50678537-27165c80-0fcd-11e9-9159-fbc5589f0c45.png)


Shaders, for example: most armor has the option for a Shader, and it seems like we'd definitely want that in our csv export.  If I can't count on both categories **always** existing and/or know what position within a category or socket list a shader will **always** be (neither of which is true), I need to search all sockets.  But I also don't know how to 100% recognize the Shader socket, because sometimes its itemTypeDisplayName is "Restore Defaults" and sometimes its "Shader".  And "Restore Defaults" can also be on things that aren't shaders, like Glows on Solstice gear.  (Maybe by filtering on the last of the plugOptions' itemTypeDisplayName? Hmm.)


I suspect either this is out of our control and has to be managed via some hardcoded conditional code, or this just isn't a thing the data structures were designed to anticipate.  Hopefully there's a clever way to find these things that is going over my head.

**Comment by bhollis** [comment]
@tcurtin unfortunately you have found The Problem With Sockets. You've kind of got what you've got. Our sockets are a filtered/massaged version of what Bungie returns, so you can feel free to look at the types for the original Bungie data as well (just open up DIM in VSCode and you can navigate through the types pretty easily and get inline documentation and autocomplete).

**Comment by bhollis** [comment]
I'd welcome any improvements to the spreadsheet export - let us know if you need any more help to submit PRs!
