### ISSUE TITLE
Sync to GDrive on Chrome

### ISSUE THREAD

**Issue by gbravery** [DestinyItemManager/DIM#3514]
DIM (normal DIM and beta DIM) doesn't seem to want to connect to GDrive from Chrome.
When I click the button to connect, I just get told it can't and offered a link to return to DIM.

DIM is allowed to do popups, add cookies, and all ad blockers are turned off for DIM.
I have cleared site information for DIM, and that hasn't helped.

I am on Chrome Version 72.0.3626.28 (Official Build) beta (64-bit)

**Comment by bhollis** [comment]
Can you open the developer console and see if it says anything?

**Comment by bhollis** [comment]
Hmm, I'm afraid email replies don't preserve attachments.

**Comment by gbravery** [comment]
Sorry ☹ - suspected that might happen.

 

gdrive init complete

content_script_bundle.js:13 Uncaught (in promise) ReferenceError: currentURL is not defined

    at then.catch.e (content_script_bundle.js:13)

 

Although the first time I saw something slightly different…

 

Gdrive init complete

Unchecked runtime.lasterror: The message port closed before a response was received     (gdrive-return.html:1)

 

The errors turn up a little bit after the screen comes back saying “We were unable to set up Google Drive.”

**Comment by bhollis** [comment]
What platform is this? Windows? It looks like something might be messed up with your browser.

**Comment by gbravery** [comment]
I'm sorry, I replied to this Saturday, but it seems to have not sent.
Yes, its Windows. Also, FWIW, its a beta version of Chrome (not sure if that is also a factor).

I can probably try to replicate on another PC if you wanted?

Gavin

**Comment by gbravery** [comment]
Interesting - based on another post here, I just logged in via an incognito window, and that's worked totally fine. I can login to Google Drive and see all my settings.
