### ISSUE TITLE
Fill stack option missing when there are multiple destination stacks

### ISSUE THREAD

**Issue by matthubb** [DestinyItemManager/DIM#3515]
Using desktop Chrome Dev and DIM Version 5.8.3.2817 (beta).

I was just making some space in my consumables, when I noticed there was an exceedingly helpful `Fill Stack` button (Dusklight Shards in the pictures). I'd used the drag-drop interface and using the shift modifier as prompted.

Then I tried to do the same thing with Baryon Boughs which had one full and one partial stack in my vault and the `Fill Stack` option wasn't there.

Is it possible to have a `Fill Stack` button when there are multiple destination stacks?

Stacks in the vault:
![image](https://user-images.githubusercontent.com/76093/50644795-cace2100-0f69-11e9-9854-ba32653255fe.png)

Dialogue for single destination stack:
![image](https://user-images.githubusercontent.com/76093/50644824-e1747800-0f69-11e9-85f3-3c9de557f0e0.png)

Dialogue for multiple destination stacks:
![image](https://user-images.githubusercontent.com/76093/50644844-f18c5780-0f69-11e9-915c-785b1720e157.png)

**Comment by bhollis** [comment]
Good eye! It’s been like that for years. I fixed it in a PR yesterday that hasn’t merged yet :-)
