### ISSUE TITLE
Perk-based item comparisons/rating

### ISSUE THREAD

**Issue by SaahilNZ** [DestinyItemManager/DIM#3519]
I've working on a tool that can compare armour-pieces based on their perks, and filter which ones can be safely dismantled. I think this could be a helpful addition to DIM, and so I would be more than willing to try and integrate it.
![image](https://user-images.githubusercontent.com/25736070/50674300-d55fe780-1049-11e9-8ca7-acba8aeb3838.png)

**Comment by bhollis** [comment]
Nice! Can you explain a bit how it works?

**Comment by SaahilNZ** [comment]
At the moment, it takes in a list of armour perks, with information such as name, upgraded versions of the perk, and whether or not the perk is good (this information is currently supplied through a CSV file). It also takes a list of all armour pieces a player has, with information such as name, class, type, power, and perks (this information is currently supplied through a JSON file).
The tool then maps all the perks in each of the items to that perk's data from the CSV. After this, the tool calculates all the possible configurations of 'good' perks each item has.

The tool then compares each item to every other item, with a variety of different outcomes and stores the comparisons in a list for each item:
- If item 1 isn't of the same type or class as item 2, then the two are considered incomparable
- If every good perk configuration in item 1 is contained in item 2, and vice-versa, the two items have the same possible good configurations, and so the two are considered equivalent
- If every good perk configuration in item 1 is contained in item 2, but item 2 contains a larger number of good perk configurations, then item 2 is considered better than item 1
- If every good perk configuration in item 2 is contained in item 1, but item 1 contains a larger number of good perk configurations, then item 2 is considered worse than item 1
- If all of item 2's good perk configurations are the same as item 1's, but contain a perk that is an upgraded version of one of item 1's good perks, then item 2 is considered better than item 1
- If all of item 1's good perk configurations are the same as item 2's, but contain a perk that is an upgraded version of one of item 2's good perks, then item 2 is considered worse than item 1
- Otherwise, the two items don't share enough similar perks to compare, and as such the two are considered incomparable

After these comparisons are made, all of the incomparable comparisons are filtered out, and each item is displayed as shown in the screenshot above. If an item is worse than the current one, its ID is highlighted in red. If it's better, its ID is highlighted in green, and if its equivalent, then its ID is highlighted in grey.

As an example, I have a helmet that is considered bad by my tool, as it has an item that is better than it:
![image](https://user-images.githubusercontent.com/25736070/50674958-9e8cd000-104f-11e9-9132-dce4a5360790.png)
The item that is better is this:
![image](https://user-images.githubusercontent.com/25736070/50674984-cbd97e00-104f-11e9-9a5f-76bd7136f87a.png)
The tool sees this item as better, because it contains all of the same good perk configurations (Pump Action + Rocket Launcher Reserves), but it also contains an extra good perk configuration (Pump Action + Shotgun Reserves).

**Comment by joshhunt** [comment]
> As an example, I have a helmet that is considered bad by my tool, as it has an item that is better than it:

I'm curious - is the item that it has considered better a duplicate?  Is it also a Ancient Apocalypse Hood?

I've been thinking a lot about how armour comparisons could be easier, but less on the side of making value judgements (this is a good perk, this is a bad perk) and focusing more on identifying gear with similar perks

**Comment by SaahilNZ** [comment]
The 'better' item in this case isn't considered a duplicate. It's a Tangled Web Hood. The comparisons that the tool makes, apart from the first one to check if they're both of the same class and type, are all perk-based.

**Comment by tcurtin** [comment]
I love and want this as a power tool - I'm wanting to create something similar myself.

That said, I have concerns that making this easy/clear for the masses is going to be... tricky.  This is a serious power tool with a very high amount of tailoring to a specific user's tastes and desires.  @SaahilNZ I wish you luck good sir - this is likely to be both fantastic and a larger-than-expected task.

**Comment by wein3967** [comment]
This is in the same vein as a tool that @dasilva333 has been working on. I'd recommend checking out the stand-alone tool (https://github.com/dasilva333/dedupe-armor) or the DIM filter version (https://github.com/dasilva333/DIM). It utilizes a config file so users can ignore perks and/or perk combinations they don't care about. It also has some community driven optimizations for some perks (e.g., pulse rifle loader vs. rifle loader).

**Comment by Jacobknew** [comment]
Has anyone looked into this recently? I attempted to use either of the linked approaches by @dasilva333  and unfortunately neither is in a working state for me (the script fails on undefined value, and the DIM fork highlights every purple armor piece I have when the filter is applied). If anyone has a working fork, or has encountered similar issues and has tips on how to fix, that would be very much appreciated!

**Comment by SaahilNZ** [comment]
Work on the tool I initially provided the screenshot of is being done here:
https://github.com/SaahilNZ/DestinyItemRater
The goal is still to try and integrate it into DIM, but at the moment we're not quite sure how to generalise it enough for it to be useful, as the way it works is heavily opinionated.

**Comment by twistof8** [comment]
Any chance this can used exclusively to compare armor with identical perks, regardless of armor "name" ie.. prodigal hood and wing theorem hood are different armors, but have identical perks, It would be a great benefit to get rid of some armor that stacks up in the vault,. Let the user mark as junk if they want but they can pick which one they want to keep without having a ton of the same perks on different armor if they don't want it.

**Comment by bhollis** [comment]
See #3621. I'd love to see this built into the new Vault Organizer!

**Comment by bhollis** [comment]
The Vault Organizer is launching today, but the landscape of how armor works has changed significantly. At this point, the Loadout Optimizer and the Vault Organizer should be enough to let you narrow in on which armor to keep and which to toss.
