### ISSUE TITLE
new pull from buttons don't update unless the sheet is closed

### ISSUE THREAD

**Issue by inexorableAce** [DestinyItemManager/DIM#3521]
If you click the kinetic pull from button then click the energy pull from button, the items in the sheet do not update, this goes for any pull from button. The sheet only updates id you close the sheet before clicking another pull from button. 

the example below is with a lower level warlock and kinetic weapons.
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/29002828/50699198-25708700-1015-11e9-8b1b-5d5ff02919c9.gif)

**Comment by inexorableAce** [comment]
i think may also be beneficial to auto focus the search bar in the sheet, definitely for desktop on mobile it's a tough call because that would cause the keypad to take up a lot of screen space. may still be beneficial though

**Comment by bhollis** [comment]
Also auto focus search
