### ISSUE TITLE
CSV Import not updating tags/notes

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#3526]
Steps to reproduce
 - Export csv
 - Edit csv file to include a tag and a note
 - Import csv file
 - Check item (tag and notes are not applied)

https://www.reddit.com/r/DestinyItemManager/comments/aczmrp/import_dim_data_from_file/

**Comment by bhollis** [comment]
@delphiactual can you give more detailed repro info? I just tried it with ghosts and it worked great.

**Comment by bhollis** [comment]
Just tried it with weapons and it worked there too.

**Comment by delphiactual** [comment]
libreoffice is saving the id as `6.91752907917072E+018`
