### ISSUE TITLE
Lost tags

### ISSUE THREAD

**Issue by iameec** [DestinyItemManager/DIM#3529]

**Comment by delphiactual** [comment]
Dupe #2713

**Comment by iameec** [comment]
I was about to cancel it, didn't knew it was already live/posted. I use a Chromebook for info, so data 'DIM) was in Chrome TAB.

I managed to get almost all tag back from my DIM Export at 2am, using Google sheet where i put in a sheet the new export, the same in other sheet without """ in ID, the old one (this night backup) in another one and i did in another one a vlookup to get back what tag had already been put.

As i was about to write in description : thanks for your work and i would have probably stopped playing Destiny 2 without DIM being so usefull to manage this chaos ^^
