### ISSUE TITLE
Moving Items Silently Fails when Inventory is Full

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#353]
You get no feedback when moving items into an inventory that is full.

https://slack-files.com/T0417CH7T-F0J4BPSCX-ea5dd78dc8 

https://slack-files.com/T0417CH7T-F0J4BP742-25f25a7c55

**Comment by bhollis** [comment]
Hmm, not sure which change is causing this. It'll take a bit to dig into.

**Comment by bhollis** [comment]
Ah, it turned out to be just the commit I thought it was (yay `git bisect`!). I pulled some stuff from `perf` that I didn't fully understand, and I bet it required some other changes.
