### ISSUE TITLE
is:inloadout hard crashes DIM

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#3531]
Current beta, Chrome on Windows 10.

Put is:inloadout into the filter bar and the page goes unresponsive.

**Comment by delphiactual** [comment]
how many loadouts do you currently have?

**Comment by philkernick** [comment]
None.

**Comment by bhollis** [comment]
I can't easily see why that would happen, and I'm not seeing anything in Sentry. Could you show me the devtools output?

**Comment by bhollis** [comment]
Never mind I think I figured it out.

**Comment by philkernick** [comment]
Load stores: 4331.447998046875ms breadcrumbs.ts:155
{dimItemInfo-m4611686018453367228-p1-d2: {…}}  breadcrumbs.ts:155
{dimItemInfo-m4611686018453367228-p1-d2: {…}}
Skip save, already got it

Nothing else in the logs.  Completely repeatable hard lock.
