### ISSUE TITLE
Notes input not updating when you click on a different item while popup is still open

### ISSUE THREAD

**Issue by patchm00** [DestinyItemManager/DIM#3533]
In addition to the issue of Notes not "sticking" after you type and leave the area, now it seems, if I click on an item (i.e. Helmet with the Notes "PVP") and then click on another piece of armor, it has the same NOTE listed as the initial click.  So, no matter what piece of armor i click on next "PVP" shows up in Notes and continues to until i click out of the field (like on blank area on page or on the armor a second time).

**Comment by bhollis** [comment]
> In addition to the issue of Notes not "sticking" after you type and leave the area

Nobody has ever mentioned that. Can you go into more detail?
