### ISSUE TITLE
Bug: "Show full item details in item popup" unreliable

### ISSUE THREAD

**Issue by DHager** [DestinyItemManager/DIM#3537]
Something keeps resetting "Show full item details in item popup" to false/unticked, even if I don't refresh the page.

At first I thought this was some kind of javascript or CSS break introduced in a recent update, but then I discovered that I can _temporarily_ get the normal display (stats, perks) back by using the settings page.

**Comment by duckmanBR** [comment]
Since 5.8.0 "Popup expanded/collapsed is based on the setting now, and toggling it saves in settings."
Any chance of this being the cause of the "unreliability"?

**Comment by bhollis** [comment]
Just tap the expand icon on the popup.

**Comment by kyleshay** [comment]
The move item popup is going to be changed soon. The accepted fix is to use the in-modal toggle to show/hide all details

![image](https://user-images.githubusercontent.com/424158/50988172-b1c0f500-14c0-11e9-9b14-247ef6a9f7ed.png)
