### ISSUE TITLE
Curated rolls data not saved across sessions

### ISSUE THREAD

**Issue by dtanner** [DestinyItemManager/DIM#3538]
When using the curated rolls feature (#3348), at least on firefox, the curated rolls data isn't saved across sessions.  Upon reloading DIM, the curated data is gone and I need to re-upload the file.
I also tried google drive state integration, but same result.  Maybe persistence of the text file isn't implemented yet?

**Comment by duckmanBR** [comment]
Not implemented yet.  But it is on the horizon, as #3539 states...

**Comment by dtanner** [comment]
thanks @duckmanBR - closing this then.
