### ISSUE TITLE
Moving Items Popup Sticks Remains on Screen Too Long

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#354]
When moving items through the popup, the move item popup remains on screen until the item has moved to the final location or errored out.  The move item popup should disappear after the transfer has been initiated to make room for a new item to be selected and moved.

https://slack-files.com/T0417CH7T-F0J4BK6N5-02e8fc8a84

**Comment by bhollis** [comment]
Should be quick to fix.
