### ISSUE TITLE
Loadout builder visually identify which finder is selected

### ISSUE THREAD

**Issue by mindsurfer-ok** [DestinyItemManager/DIM#3541]
Loadout builder has no visual for ammo finders after they have been selected
screenshot attached has heavy and special finders ##
![image](https://user-images.githubusercontent.com/46573673/50988007-37e93580-14d9-11e9-9f46-b9623420a646.png)

**Comment by kyleshay** [comment]
should be able to reuse the logic we have in the popup picker
