### ISSUE TITLE
Show Progress towards titles

### ISSUE THREAD

**Issue by lasdem** [DestinyItemManager/DIM#3542]
Feature Request
It would be nice to have a titles tab that shows your percentage progress to all titles. if you click on one it should show all the related activities that needs completion and their individual progress.

Also add markers to time-gated activities, like a specific nightfall that needs to be completed and is currently available or unavailable.

This would help Players who want to archieve specific titles to plan their activities and track their progress.

**Comment by bhollis** [comment]
That'd be nice! In the meantime check out https://braytech.org/ which is great about this stuff.

**Comment by bhollis** [comment]
@sundevour added seals and badges, I think that gets it done.
