### ISSUE TITLE
Duplicated Comments Different Items

### ISSUE THREAD

**Issue by shaneosan** [DestinyItemManager/DIM#3551]
I am seeing an issue where the comments of an item are getting copied to the empty comment field of new items. Additionally I am seeing a similar issue when locking 1 item ... other items of the same type are getting locked.
Using Version 5.9.0 (release)

**Comment by bhollis** [comment]
By comments do you mean item reviews?

For the locking issue, do the other items of the same type lock right away or later?

**Comment by shaneosan** [comment]
By comments I am referring to “Add notes to this item” box and for the
locking issue I will need to test it out but I believe it happens later..
since looking at my inventory now I do see some items being locked while
others are not for some weapons. However when the issue occurs then all
items of that particular weapon will get locked.

**Comment by delphiactual** [comment]
irt `locking` items it is a Bungie API bug https://github.com/Bungie-net/api/issues/764

**Comment by delphiactual** [comment]
The notes bug was fixed in https://github.com/DestinyItemManager/DIM/commit/8d87670b1394a0cb94c13fa6a70d2cc46d0b30f9 and
https://github.com/DestinyItemManager/DIM/commit/f60a2fb9d3f3330de2ff04401b785c8e16de986a
which will be in 5.10 upon release this evening

**Comment by shaneosan** [comment]
This definitely sounds like what may be occurring. Thank you for being it
to my attention.
