### ISSUE TITLE
Exported weapons CSV got masterwork type column back but now Notes column is empty

### ISSUE THREAD

**Issue by jerrycarlson** [DestinyItemManager/DIM#3554]
Exported weapons CSV got masterwork type column back but now Notes column is empty.  ;)

I tested this using the beta site since production doesn't have the masterwork column fix yet.  However, upon closer inspection I realize that the beta site is not showing any of my notes (so, no wonder the exported weapons CSV wasn't showing them).

Thus raising the question: does the beta site not share the same (local) notes data as the production site?

**Comment by delphiactual** [comment]
no the do not share data

**Comment by jerrycarlson** [comment]
Awesome.  Thanks so much to the DIM team for all you do.  Y'all are the true Iron Lords.
