### ISSUE TITLE
Allow custom icon and search term in wish list definition file

### ISSUE THREAD

**Issue by chrisfried** [DestinyItemManager/DIM#3559]
I want my wishlist to respond to `is:shitlist` and to display a 💩 icon on items instead of a 👍 icon.

https://twitter.com/guardtheater/status/1086703195462619136

**Comment by chrisfried** [comment]
Oh, I know. That doesn't give me a 💩 icon, though.

**Comment by bhollis** [comment]
I love this suggestion, but I'm not inclined to actually do anything about it. @48klocs do you want to add some special syntax for this in wishlists?
