### ISSUE TITLE
moving an item from the loadout builder works, but show an error

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#3563]
If I create a loadout in the loadout builder like this one:

![image](https://user-images.githubusercontent.com/25425159/51457014-a367b880-1d9f-11e9-9e67-a38e178951e0.png)

I then noticed that one of the items was tag:infuse, so I wanted to put it back in the vault.  I selected the item, and clicked the transfer to vault icon.  The item moved, but then there was a red error saying "looks like you tried to move more of the item than exists".

**Comment by bhollis** [comment]
Whoops, I didn't mean for those controls to even be there on the loadout builder. But it should work...

**Comment by kyleshay** [comment]
Very strange. I move an item, and it does move.. but then I try to move it again and I get:
<img width="319" alt="screen shot 2019-02-07 at 10 31 54 pm" src="https://user-images.githubusercontent.com/424158/52462528-4a7e7b00-2b28-11e9-9417-275aba27a720.png">
Then if I try to move it again after that I get:
<img width="317" alt="screen shot 2019-02-07 at 10 33 04 pm" src="https://user-images.githubusercontent.com/424158/52462546-5cf8b480-2b28-11e9-81c0-90f15be1ab20.png">

**Comment by bhollis** [comment]
This actually works in the new loadout builder. It doesn't give much feedback, but it works.
