### ISSUE TITLE
Angular to React

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#3566]
- [x] Item Reviews - #3510 
- [x] Toaster - #3604
- [x] Hotkeys - #3598
- [x] D1 Loadout Builder #3594
- [x] Infuse Dialog - #3583
- [x] Farming Mode - #3543 
- [x] Item Popup - #3495 #3465 
- [x] About - #3430 
- [x] D1 Vendors - #3330 
- [x] D1 Activities - #3267 
- [x] D1 Record Books - #3223 
- [x] Search Filtering - #3217 
- [x] Compare - #3196 
- [x] Loadouts - #3174 
- [x] Settings - #3152 
- [x] New Item Button - #2946
- [x] Header - #2699
- [x] Press Tip - #2665
- [x] D2 Progress - #2520

**Comment by bhollis** [comment]
I'm currently working on the Infuse Dialog.

**Comment by bhollis** [comment]
I'm writing our own toaster system, since there's stuff I want to do in the future that'll be easier if we control our fate.

**Comment by delphiactual** [comment]
`Guardians make their own fate.`
