### ISSUE TITLE
Mutate DestinyInvenotryItemDefinition on manifest load.

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#3569]
Based off of https://github.com/DestinyItemManager/DIM/pull/3300#issuecomment-437638266

We could mutate the table on load by adding `season` and `event` properties directly to the table after manifest load, then unloading `d2-seasons.json` and `d2-events.json` from memory.

Edit: Generate a md5 hash on d2-seasons.json if hash matches already applied json, do nothing, else mutate DestinyInventoryItemDefinition again.

**Comment by bhollis** [comment]
I think I'd prefer not to do this. The memory savings would be minimal, but it'd make it difficult to keep track of what we've done to the manifest.
