### ISSUE TITLE
Feature request: Move all common/uncommon/rare items for dismantle

### ISSUE THREAD

**Issue by azjthomasfamily** [DestinyItemManager/DIM#3574]
Now that we are all 650 and still get blue drops it would be nice to be able to request all common/uncommon/rare to be moved into the selected character for dismantle.

**Comment by delphiactual** [comment]
`not:purple not:yellow` character drop-down -> `Transfer search...`

**Comment by kyleshay** [comment]
`is:equipment` `is:weapon etc also to narrow.

**Comment by Dragonfire80** [comment]
I also think having the dismantle option would be great. I thought about it and guessed maybe they didn't want to do that initially in case you delete something by accident by leaning on the keyboard or something? Just guessing.

**Comment by Dragonfire80** [comment]
Nevermind. Just noticed this is closed. Sorry. First time user. ;p

**Comment by kyleshay** [comment]
no problem! unfortunately, the dismantle action isn't possible to do through the web. if bungie does open the action to us then we'll definitely make it available in DIM!
