### ISSUE TITLE
Can’t log into Google Drive on iOS 12

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#3575]
Authorizing Google Drive...
We were unable to set up Google Drive.

Go back to DIM

**Comment by bhollis** [comment]
Beta?

**Comment by philkernick** [comment]
Yup.  Current beta on iPad Pro iOS 12.2.

**Comment by philkernick** [comment]
Sorry 12.1.2. My mistake.

**Comment by towidev** [comment]
I'am not an expert, but maybe Safari and a content blocker like adblock plus will instant delete the authentication token.

**Comment by bhollis** [comment]
That's definitely one of the things that can happen.

**Comment by Wh1rledPeas** [comment]
I had never been able to sync to drive and finally got around to debugging it today. On Chrome for Android I had to enable third-party cookies for it to work. Once I had the token, I was hoping I could turn third-party cookies off. Unfortunately not.

I've had third-party cookies turned off for years, with very few issues. It's unfortunate that GDrive Sync requires it. I'll have to evaluate whether it's worth the exposure...
