### ISSUE TITLE
Allow customizing the UI per-user & store local settings to keep changes

### ISSUE THREAD

**Issue by txgraycat** [DestinyItemManager/DIM#3578]
Sometimes a user doesn't want to see the item's description & stats, just the perks and transfer icons. Other users may want to see the item's Power level (Light level in D1) more than the name of the item. There are as many different ways to tailor a User Interface as there are users x roles. DIM is open-source, so why not make tinkering a bit more....available?

Put a new option into the Settings menu under a show/hide frame for a little GUI editor. Just add a button that reads "Edit Interface", warn the user that changes have to be stored on THEIR computer or device--and could even break something--and let them 'go to town', so to speak.

This approach, I hope, would let all the folks that have one little problem or another with the user interface alter it to their hearts' content. I know it sounds like something Firefox or Chrome would pull--and it could get so complicated that it turns DIM into a standalone app or worse--but I think it's a worthy feature to put in.  I promise to open a new Git fork if, say, 50 others reply showing interest (and offering help!) before May 2019 (deadlines help me prioritize). 

The last thing I want is to cause a problem for the hardworking DIM devs over a notion that turns out to be just my own little pet peeve. If nobody else likes it, maybe one day when I'm finished with other projects, I'll dust this idea off and start playing around with it on my own just to see if I can make it work the way I always wanted it to.  At least the idea is out here for consideration, anyway.

Thanks for reading all this ramble. I hope to hear from someone soon.
--TX GrayCat

**Comment by bhollis** [comment]
One of our guiding principles for DIM is to minimize the number of options and settings we expose. We’re actually working hard to remove as many options as possible. I’m afraid this sort of thing would go in the opposite direction.

**Comment by kyleshay** [comment]
We're going to be releasing a new popup redesign that will be much cleaner and easier to navigate.
