### ISSUE TITLE
Beta: Collapsible headers only collapsing on text click

### ISSUE THREAD

**Issue by duckmanBR** [DestinyItemManager/DIM#3579]
Maybe an unintended bug from #3545, but you can't collapse a header if you click on the header space, only if you click on the text.
However, the chevron turns yellow.

This is only happening on the inventory page.  Progress/Vendors/etc are working as intended.

**Comment by bhollis** [comment]
Not a bug, I intentionally switched them back to only collapsong on text click because people were accidentally collapsing a lot.

**Comment by bhollis** [comment]
Fixed the hover effect to only happen over the text.
