### ISSUE TITLE
all items stuck in postmaster if one items is at max in inventory

### ISSUE THREAD

**Issue by s-diniro** [DestinyItemManager/DIM#3584]
Potential bug:

I've got some modulus report items in my postmaster. However, there is no space in my inventory to collect them from the postmaster because  I'm at maxed out in my inventory with  modulus reports already

However, there are _other_ items in my inventory that I _do_ have space for (armor)

The entire transfer operation is blocked because one item cannot be moved. To me, it seems like the transfer of the armor should succeed, while just the modulus reports are held back

![postmaster](https://user-images.githubusercontent.com/42945903/52099982-8ef79d00-25a3-11e9-9965-74bf8127bf67.jpg)

**Comment by bhollis** [comment]
Gotcha, I think I know exactly why this is happening. Just some modifications to the "is everything full" logic. It's not that it gives up because there's no space, it gives up because it's an error. If I fix the space-finding logic it'll just skip over that item.
