### ISSUE TITLE
misaligned CSV fields

### ISSUE THREAD

**Issue by s-diniro** [DestinyItemManager/DIM#3586]
Whenever Bungie revamped the perk system, they made it impossible to compare items, to determine which ones to keep. They show you only the ACTIVE perk; not the other options in that perk "tree".

I was hoping to use DIM's CSV export to compare my items, especially based on items that have the same perks, or even overlap.

Unfortunately, I can't do that, because the "perk" fields don't line up. Several items throw the alignment of fields off. Specifically:
- if the item has a shader (see yellow below)
- if the item has a mod in the armor socket (see red below)
- if the item's "tree" has more than 2 options; some armor pieces have THREE options in the tree (see green below)

Here's a screenshot that shows the misalignment:
![csv-current](https://user-images.githubusercontent.com/42945903/52166713-b2733280-26de-11e9-8c5b-c632d897a9f6.jpg)

Two of the issues can be fixed by moving the socket and shader (and tier) info, so they are grouped together, separate from the group of "true" perks.

Addressing the "three option" tree for the 2nd armor perk might be tricky. Still, the following proposed alignment would improve the CSV's usability for comparing perks:

![csv-proposed](https://user-images.githubusercontent.com/42945903/52166734-1564c980-26df-11e9-87d1-5c05c5fc8070.jpg)

**Comment by delphiactual** [comment]
Dupe #3513
