### ISSUE TITLE
Loadout Builder (Mobile) Needs Height Limitation with Background Scrolling

### ISSUE THREAD

**Issue by Wh1rledPeas** [DestinyItemManager/DIM#3587]
The Loadout Builder has some sizing issues on the mobile platform. If you can limit its maximum height to make sure there's enough room to see 1-2 rows of items in the background, that should be efficient enough. The background also needs to be scrollable to avoid having to save the Loadout every time you need to scroll to add another item.

Here's a video that shows the problem. Note that I started with a Loadout that was quite large and used to be editable before recent changes.  

[![screenshot_20190202-131436](https://user-images.githubusercontent.com/3685437/52167753-f15cb480-26ed-11e9-9560-0f38cfac1d57.png)](https://youtu.be/93CED9uBxbI)

**Comment by bhollis** [comment]
Absolutely, the loadout editor is due for a refresh (it was just stuck as-is into the sheet).
