### ISSUE TITLE
Pull From Dialog (Mobile) Needs Several Changes - Default to Move - Focus Search Box - Search History - Item Preview

### ISSUE THREAD

**Issue by Wh1rledPeas** [DestinyItemManager/DIM#3588]
I've been trying to use the new "pull from..." dialog instead of manually searching for items. It has the advantage of automatically filtering by item slot and class (armor). So it saves a little typing in the search box. There are a couple issues I keep encountering. Each of these things may require their own issue and I'll be happy to create them, but I have one recording that illustrates all of these, so initially I'm submitting them together. 

- [DEFAULT TO MOVE] - I seem to always be doing this when my character isn't able to equip items. So I tap on the item, only to get an error and have to re-enter everything. If you don't consider some of the other options below, I'd like to see the default action changed to Move, instead of Equip. 

- [ITEM CONFIRMATION] - When searching for items, I don't always recognize items by their icon. Would it be possible to put a Move/Equip button at the top, just like the Infusion Tool, so there's a preview and the name of the item shown before tapping move/equip? (Actually I just noticed the new infusion dialog doesn't show the name of the item anymore. I've always depended on the item name as confirmation that I've selected the right one. So I guess I'd have to request that be added back into the infuse dialog as well.)

- [FOCUS TEXT INPUT FIELD] - When using the search box, it scrolls off screen as soon as the keyboard pops up on the mobile device. I know this sort of thing is hard to predict, but perhaps a hook that moves the input box back into view if it scrolls away. Perhaps something on a timer after onfocus(), with keystrokes into the input box canceling out as well? Not sure... But this is also an issue for many other text input fields in the app (writing a review, entering a quantity of items to move, etc). I have some recordings of those instances that I haven't had a chance to submit as issues yet. So perhaps something applied to text input more globally would be better.

- [SEARCH HISTORY] - When searching for items, I find I'm usually repeating searches. It would be nice to have a drop down of previous searches, filtered by what's already typed into the search box. A blank textbox simply providing an unfiltered dropdown of the past few searches, so re-searching wouldn't require so much manual typing.

- [ITEM PREVIEW] - My memory isn't what it used to be, so quite often I need a little reminder to make sure I'm grabbing the right item. When I used to do this from the regular search dialog, I could pull up the item details and read the perks on different items before choosing the one I wanted. Would it be possible to provide a way to bring up the item details before choosing to transfer? Perhaps long-press on an item?

Those are the basic issues on the mobile platform. Here's a video of me attempting to find an exotic that was <650 so I could infuse it with a duplicate maxlevel drop I just received. Notice after my initial search and forgetting that I needed to select [move], I had to type the same search in again... If I had wanted it equipped and forgotten to select that option, it's rather simple to equip in-game, as opposed to the move being canceled and having to search again. 

[![screenshot_20190202-140346](https://user-images.githubusercontent.com/3685437/52169101-08f16880-2701-11e9-9247-51249b5cb293.png)](https://youtu.be/7nB_14Re0b8)

**Comment by bhollis** [comment]
> [DEFAULT TO MOVE] - I seem to always be doing this when my character isn't able to equip items. So I tap on the item, only to get an error and have to re-enter everything. If you don't consider some of the other options below, I'd like to see the default action changed to Move, instead of Equip.

The idea here is that this tool is mostly for grabbing an item quickly, and so equipping should be the default. We should strive to not have errors, instead. https://github.com/DestinyItemManager/DIM/issues/3592

> [ITEM CONFIRMATION] - When searching for items, I don't always recognize items by their icon. Would it be possible to put a Move/Equip button at the top, just like the Infusion Tool, so there's a preview and the name of the item shown before tapping move/equip? (Actually I just noticed the new infusion dialog doesn't show the name of the item anymore. I've always depended on the item name as confirmation that I've selected the right one. So I guess I'd have to request that be added back into the infuse dialog as well.)

I want this to be as fast as possible, so making it an extra button would be a bummer, though I have thought about it. What I might do instead is switch to showing the item names in the list, at the expense of not being able to show as many items at once. https://github.com/DestinyItemManager/DIM/issues/3590

The original infusion finder didn't show the name of the item selected for fuel either, btw (you can check on prod). It only showed the name of the item you start with, which is still displayed in the new design.

> [FOCUS TEXT INPUT FIELD] - When using the search box, it scrolls off screen as soon as the keyboard pops up on the mobile device. I know this sort of thing is hard to predict, but perhaps a hook that moves the input box back into view if it scrolls away. Perhaps something on a timer after onfocus(), with keystrokes into the input box canceling out as well? Not sure... But this is also an issue for many other text input fields in the app (writing a review, entering a quantity of items to move, etc). I have some recordings of those instances that I haven't had a chance to submit as issues yet. So perhaps something applied to text input more globally would be better.

This is a bummer. I didn't autofocus because on iOS, if you autofocus it'll resize the viewport in a weird way that is both undetectable and pushes the dialog offscreen. Sounds like something similar happens on Android (which I can't realistically test beyond Chrome's simulated Android experience). This is something I'd need somebody with an Android phone to submit a PR for to fix. Can you file a separate, general issue?

> [SEARCH HISTORY] - When searching for items, I find I'm usually repeating searches. It would be nice to have a drop down of previous searches, filtered by what's already typed into the search box. A blank textbox simply providing an unfiltered dropdown of the past few searches, so re-searching wouldn't require so much manual typing.

This will be added to all search fields soon (when I get to it). https://github.com/DestinyItemManager/DIM/issues/1874

> [ITEM PREVIEW] - My memory isn't what it used to be, so quite often I need a little reminder to make sure I'm grabbing the right item. When I used to do this from the regular search dialog, I could pull up the item details and read the perks on different items before choosing the one I wanted. Would it be possible to provide a way to bring up the item details before choosing to transfer? Perhaps long-press on an item?

Yeah, I have been intending to make long-press bring up the full item details, basically everywhere an item tile is shown. https://github.com/DestinyItemManager/DIM/issues/3591

**Comment by Wh1rledPeas** [comment]
> > [DEFAULT TO MOVE] ...
> 
> The idea here is that this tool is mostly for grabbing an item quickly, and so equipping should be the default. We should strive to not have errors, instead. #3592

Sounds like a good compromise. Although, there is rarely an instance I would equip something directly. Whenever I'm using this, it's always in-world as opposed to tower/orbit. As long as there's no error and I don't have to search all over again, that's wonderful! 

> > [ITEM CONFIRMATION] ... 
> 
> I want this to be as fast as possible, so making it an extra button would be a bummer, though I have thought about it. What I might do instead is switch to showing the item names in the list, at the expense of not being able to show as many items at once. #3590

I understand. I figured you had the implementation from the Infusion Finder that could be copied to do the trick and provide a little consistency across the dialogs. 

> The original infusion finder didn't show the name of the item selected for fuel either, btw (you can check on prod). It only showed the name of the item you start with, which is still displayed in the new design.

In production, both item names are shown. One at the top. The other at the bottom. I always use that as a confirmation that I've tapped on the correct icon. 

![screenshot_20190202-180526](https://user-images.githubusercontent.com/3685437/52170271-714a4500-2715-11e9-8d22-a8388274a75e.png)

> > [FOCUS TEXT INPUT FIELD] ... 
> 
> This is a bummer. I didn't autofocus because on iOS, if you autofocus it'll resize the viewport in a weird way that is both undetectable and pushes the dialog offscreen. Sounds like something similar happens on Android (which I can't realistically test beyond Chrome's simulated Android experience). This is something I'd need somebody with an Android phone to submit a PR for to fix. Can you file a separate, general issue?

Sure! No problem. 

> > [SEARCH HISTORY] ... 
> 
> This will be added to all search fields soon (when I get to it). #1874

Yes. That would be a welcome addition.

> > [ITEM PREVIEW] ...
> 
> Yeah, I have been intending to make long-press bring up the full item details, basically everywhere an item tile is shown. #3591

This would definitely make navigation easier and open the tool up for many different methods of use. The item-compare tool for example... Being able to compare a bunch of snipers, find one with the range/impact/burn you need, then select the one you want and tap of the move/equip buttons.

**Comment by Wh1rledPeas** [comment]
> > [FOCUS TEXT INPUT FIELD]
> 
> This is a bummer. I didn't autofocus because on iOS, if you autofocus it'll resize the viewport in a weird way that is both undetectable and pushes the dialog offscreen. Sounds like something similar happens on Android (which I can't realistically test beyond Chrome's simulated Android experience). This is something I'd need somebody with an Android phone to submit a PR for to fix. Can you file a separate, general issue?

I created Issue #3596 for this.

**Comment by bhollis** [comment]
Closing in favor of individual issues.
