### ISSUE TITLE
Display only user defined items

### ISSUE THREAD

**Issue by pasadinhas** [DestinyItemManager/DIM#359]
I never use the quests section of the items. I rarely move a ship or a horn. I don't really care about Mission Items (is that what they're called?).

So, a nice feature (imo) would be to let the users check/uncheck what sections they want to see. Checkboxes in the Settings. If a user unchecks the Ships, then ships are not displayed in the Manager.

**Comment by kyleshay** [comment]
linking: #267

**Comment by SunburnedGoose** [comment]
Follow this on #267.
