### ISSUE TITLE
Infusion Fuel Finder Missing Legitimate Duplicates

### ISSUE THREAD

**Issue by Wh1rledPeas** [DestinyItemManager/DIM#3595]
Sorry to keep coming back to this, but I encountered an instance yesterday where a duplicate appeared in the compare window, but not in the Infusion Fuel Finder.

I'll let the video speak for itself...

I had just spent time cashing in a bunch of IO Tokens and had inventory/postmaster to sift through. Please note how much trouble it is to track down duplicates on the mobile platform. It's a long, tedious process when the duplicate doesn't show up in the Infusion Fuel Finder. 

[![image000000](https://user-images.githubusercontent.com/3685437/52353684-09d61300-29fd-11e9-864f-e21b512c790d.png)](https://youtu.be/duFPqt2J-bk)

**Comment by duckmanBR** [comment]
On DIM you went on the 631 version and clicked infuse.  In this case the tool will show you weapons that you can use as fuel.  A 380 item can't be used as infuse fuel for a 631 one.
If then you click on the **Switch** button, the 631 item will them be used as fuel for the items listed below.  If you do that, the 380 dupe will even show up on the first line, alone.

**Comment by Wh1rledPeas** [comment]
Okay. I see now. In the previous version of the Infusion Fuel Finder, it displayed both options in two columns. I've been used to all options being available with two taps.

Is there a reason why you chose to implement it the way you did? I have to say that the method of infusing shown in this video is the way I use the tool 100% of the time.

<pre>
1. Get a new drop
2. Do I have a lower level version?
    NO: Do I want to keep the item?
        NO: Dismantle it.
        YES: Lock it and move it to the vault.
    YES: Pull the other item locally (current character) for comparison
        1. Are the perks better on the new item?
            NO: Infuse new drop into old item.
            YES:
                1. Dismantle old item.
                2. Lock new item and move to vault. 
</pre>

I may be wrong, but I would imagine this is pretty similar to how most people use this tool. The power level of new drops on our current character, are typically moving higher. This means our lower power items are most likely going to be on other characters or in the vault. Assuming this, it would reduce the average amount of taps if the default view was the opposite.

**Comment by bhollis** [comment]
Unfortunately as we've discussed in the past, this isn't a duplicate finder tool. I understand your workflow, but the infusion fuel finder was primarily built for deciding what to use as fuel to improve a particular item that you're looking to infuse.

I think there are improvements we're going to make to the item popup and compare tool that fit your workflow better than trying to make the infuse tool serve that need.

That said, I think it's reasonable to remember which "direction" you last left the tool in. We can make an issue for that.

**Comment by Wh1rledPeas** [comment]
> Unfortunately as we've discussed in the past, this isn't a duplicate finder tool.

Yes. I understand. It's just with random rolls and duplicate items requiring only Glimmer to infuse, the "infusion process" has become a little more complex than simply comparing power levels. I always have to move items locally for comparison, before deciding which one to keep and whether to infuse or discard one.

Now that I understand the [switch] functionality, I find this isn't as big of an issue. The only time it doesn't work is when power levels are identical or Y1/Y2 decision making. 

> I think there are improvements we're going to make to the item popup and compare tool that fit your workflow better than trying to make the infuse tool serve that need.

I will try to be patient. 😉 Seriously though, you guys do a great job and playing Destiny isn't even fun without DIM. So thank you for all of your hard work. 

> That said, I think it's reasonable to remember which "direction" you last left the tool in. We can make an issue for that.

That's a good idea actually. When a new level cap comes along, most infusion decisions are going to be one direction until a user maxes his power level, then will likely be the opposite.
