### ISSUE TITLE
Text Input Fields Scroll out of View (Mobile)

### ISSUE THREAD

**Issue by Wh1rledPeas** [DestinyItemManager/DIM#3596]
When using the search box of the pull item dialog, it scrolls off screen as soon as the keyboard pops up on the mobile device.

The places this happens are:
* Search box on the Pull Item dialog (video #*1*)
* Search box on the Infusion Fuel Finder
* The input box on the [Review] tab of the item details. (video #*2*)
* The input box on the Move Inventory Dialog when quantity is needed. 

In the first two instances, the top of the dialog actually scrolls off screen, so perhaps something in the style that would prevent the dialog from scrolling up past the bottom of the header, would be appropriate. Although, if the header of the dialog is too large, that could effectively prevent the text input box from scrolling into view. 

In the other cases, the dialog needs to be scrolled until the text box is visible to the user.

I know this sort of thing is hard to predict, but perhaps a hook that scrolls the input box back into view if it scrolls away. Perhaps something on a timer after 
`onfocus()`, with keystrokes into the input box or `onblur()` canceling out of the timer. That way it would start watching the position of the input box when someone starts to edit, and stop doing anything about it after the user starts typing. Not sure... Just an idea. 

Since this is an issue for several text input fields in the app perhaps something applied to text input more globally would be better.

###  Pull From Dialog Needs Focus
[![screenshot_20190202-140346](https://user-images.githubusercontent.com/3685437/52364417-254c1880-2a13-11e9-959e-9f4c2cfbb005.png)](https://youtu.be/7nB_14Re0b8?t=42) 

### Text Input For Review Needs Focus
[![screenshot_20190206-140613](https://user-images.githubusercontent.com/3685437/52366723-6eeb3200-2a18-11e9-9715-ea4ce8624ac8.png)](https://youtu.be/lC_dFsCUMYQ)

**Comment by bhollis** [comment]
I went through about a half dozen fixes for this whike I was building it, but didnt get anything that worked in all cases. This is somewhere that I’d love some help.

**Comment by Wh1rledPeas** [comment]
> I went through about a half dozen fixes for this whike I was building it, but didnt get anything that worked in all cases. This is somewhere that I’d love some help.

Okay. It's been 10-12 years since I've done any Javascript/CSS and I don't get on my laptop all that often, but I'll see if I can tinker with this sometime soon. Unless someone else beats me to it.

**Comment by kyleshay** [comment]
Would it help if we put the search bar at the bottom, so that when the keyboard pushes up it stays in view?

**Comment by bhollis** [comment]
No, the problem is that the sheet is pinned to the bottom of the screen (`position: fixed`) but when the keyboard comes up, if the box has focus (or is focused later, the sheet stays pinned to the bottom of the screen (above the keyboard) but doesn't recalculate its maximum height. So there's no way to know that it should be shorter now.
