### ISSUE TITLE
Efficiency is very much lower than previous version

### ISSUE THREAD

**Issue by cuicuocua** [DestinyItemManager/DIM#360]
the extension is using way much more cpu power for the same activities.

**Comment by SunburnedGoose** [comment]
Can you share your profiler?  I don't see a spike or significant change on my hardware.

**Comment by cuicuocua** [comment]
i'm using a macbook pro 13''. the usage seems to have subsided after first launch on this machine. i signed out and back in on bungie.net and it had a brief spike again. i downloaded it on 3 more machines just to make sure and they all had a brief spike at the beginning of usage and after signing in. seems all good now. will update with more info if i notice any more strange activity

**Comment by SunburnedGoose** [comment]
It’s not unusual for it to spike when it’s doing a lot of work processing the data at the beginning of session.  As long as it isn’t sustained, I’m okay with it.

**Comment by bhollis** [comment]
I think we've fixed this with 3.2. Let me know if there's still an issue.
