### ISSUE TITLE
Add setting to loadout builder to disable automatic recalculate

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#3601]
We should consider adding a setting that disables/enabled automatic recalculate on the loadout builder. 

If the automatic recalculation is disabled, we should show a button `CALCULATE` that triggers the process step.
> ... could we fit in a manual update button/selector? Because on mobile (at least) I need to wait some seconds to the build generator finishes so I can select another perk. - @duckmanBR

**Comment by bhollis** [comment]
In the D1 loadout builder rewrite I made the calculation process cancelable so when you chose something new it would quit the current calculation. We can also move this all to a web worker. Better than having a checkbox for disabling recalculation IMO.
