### ISSUE TITLE
dım isnt showing any of my weapons (except postmaster)

### ISSUE THREAD

**Issue by Hunterorc12** [DestinyItemManager/DIM#3605]
the title explains it DIM doesnt show any of my weapons doesnt show the one in vault and in my character's loadout only shows in postmaster. what can i do?

**Comment by delphiactual** [comment]
You collapsed the weapons section. Click on the word `Weapons` to expand it.

**Comment by Hunterorc12** [comment]
oh thanks i feel like a noob that doent know what is he doing XD
