### ISSUE TITLE
Aim Assist and doesn't reflect targeting adjustor mod. Same for counterbalance mod/recoil

### ISSUE THREAD

**Issue by spnkr** [DestinyItemManager/DIM#3608]
# targeting adjustor example

https://banshee-44.com/?weapon=568515759&socketEntries=1458010786,839105230,2420895100,1168162263,1645158859,4248210736,3228611386,4283235141,0,2285418970

aim assist should be 76, not 71, because of the targeting adjustor mod.

![image](https://user-images.githubusercontent.com/11250/52682831-d3bdf500-2f0e-11e9-8546-1418663ef377.png)

## counterbalance mod example:

https://banshee-44.com/?weapon=93253474&socketEntries=1636108362,3433396027,1561002382,3275789089,1683379515,3650581584,1588595445,518224749,0,2285418970,0,3876796314

recoil direction should be 84, not 69, because of the counterbalance mod

![image](https://user-images.githubusercontent.com/11250/52682888-01a33980-2f0f-11e9-8d5d-8f9bd84c0599.png)

**Comment by delphiactual** [comment]
Dupe #3488
