### ISSUE TITLE
Loadout Builder out of memory

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#3610]
Current beta, Chrome on Windows 10.

How to replicate:
1. Select Loadout Builder
2. Wait for the "No Generated Builds Found" spinner to finish.
3. Uncheck "Exclude Mod Bonus"

It gets to 99% Generating Builds and then crashes the tab with "Aw, Snap!".

**Comment by philkernick** [comment]
With the debug console up, there are no errors logged and it doesn't crash the tab, but the tab becomes completely unresponsive.

**Comment by duckmanBR** [comment]
Can't reproduce on mobile.
But I don't know if the "No Generated Builds Found" should appear on open...

@kyleshay

**Comment by philkernick** [comment]
This needs to be reopened, because it is still 100% reproducible on Chrome on Win10 with the current beta.

It now only gets to about 45% before crashing the tab.

**Comment by delphiactual** [comment]
@philkernick post logs from console please

**Comment by philkernick** [comment]
Here's a video capture.  https://drive.google.com/file/d/1a9QFATyPZj2yO9kduPVDeHdmDfm1pIki/view

Console says: Paused before potential out-of-memory crash.

In process.ts line 52.

Stack trace:
e (process.ts:52)
(anonymous) (process.ts:108)
r (helpers.ts:84)
requestAnimationFrame (async)
(anonymous) (trycatch.ts:40)
e (process.ts:107)
(anonymous) (process.ts:108)
r (helpers.ts:84)
requestAnimationFrame (async)
(anonymous) (trycatch.ts:40)
e (process.ts:107)
(anonymous) (process.ts:108)
r (helpers.ts:84)
requestAnimationFrame (async)
(anonymous) (trycatch.ts:40)
e (process.ts:107)
(anonymous) (process.ts:108)
r (helpers.ts:84)
requestAnimationFrame (async)
(anonymous) (trycatch.ts:40)
e (process.ts:107)
(anonymous) (process.ts:108)
r (helpers.ts:84)
requestAnimationFrame (async)
(anonymous) (trycatch.ts:40)
e (process.ts:107)
(anonymous) (process.ts:108)
r (helpers.ts:84)
requestAnimationFrame (async)
(anonymous) (trycatch.ts:40)
e (process.ts:107)
(anonymous) (process.ts:108)
r (helpers.ts:84)
requestAnimationFrame (async)
(anonymous) (trycatch.ts:40)
e (process.ts:107)
(anonymous) (process.ts:108)
r (helpers.ts:84)
requestAnimationFrame (async)
(anonymous) (trycatch.ts:40)
e (process.ts:107)
(anonymous) (process.ts:108)
r (helpers.ts:84)
requestAnimationFrame (async)
(anonymous) (trycatch.ts:40)
e (process.ts:107)
(anonymous) (process.ts:108)
r (helpers.ts:84)
requestAnimationFrame (async)
(anonymous) (trycatch.ts:40)
e (process.ts:107)
(anonymous) (process.ts:108)
r (helpers.ts:84)
requestAnimationFrame (async)
(anonymous) (trycatch.ts:40)
e (process.ts:107)
(anonymous) (process.ts:108)
r (helpers.ts:84)
requestAnimationFrame (async)
(anonymous) (trycatch.ts:40)
e (process.ts:107)
(anonymous) (process.ts:108)
r (helpers.ts:84)
requestAnimationFrame (async)
(anonymous) (trycatch.ts:40)
e (process.ts:107)
(anonymous) (process.ts:108)
r (helpers.ts:84)
requestAnimationFrame (async)
(anonymous) (trycatch.ts:40)
e (process.ts:107)
(anonymous) (process.ts:108)
r (helpers.ts:84)
requestAnimationFrame (async)
(anonymous) (trycatch.ts:40)
e (process.ts:107)
(anonymous) (process.ts:108)
r (helpers.ts:84)
requestAnimationFrame (async)
(anonymous) (trycatch.ts:40)
e (process.ts:107)
(anonymous) (process.ts:108)
r (helpers.ts:84)
requestAnimationFrame (async)
(anonymous) (trycatch.ts:40)
e (process.ts:107)
(anonymous) (process.ts:108)
r (helpers.ts:84)
requestAnimationFrame (async)
(anonymous) (trycatch.ts:40)
e (process.ts:107)
(anonymous) (process.ts:108)
r (helpers.ts:84)
requestAnimationFrame (async)
(anonymous) (trycatch.ts:40)
e (process.ts:107)
(anonymous) (process.ts:108)
r (helpers.ts:84)
requestAnimationFrame (async)
(anonymous) (trycatch.ts:40)
e (process.ts:107)
(anonymous) (process.ts:108)
r (helpers.ts:84)
requestAnimationFrame (async)
(anonymous) (trycatch.ts:40)
e (process.ts:107)
(anonymous) (process.ts:108)
r (helpers.ts:84)
requestAnimationFrame (async)
(anonymous) (trycatch.ts:40)
e (process.ts:107)
(anonymous) (process.ts:108)
r (helpers.ts:84)
requestAnimationFrame (async)
(anonymous) (trycatch.ts:40)
e (process.ts:107)
(anonymous) (process.ts:108)
r (helpers.ts:84)
requestAnimationFrame (async)
(anonymous) (trycatch.ts:40)
e (process.ts:107)
(anonymous) (process.ts:108)
r (helpers.ts:84)
requestAnimationFrame (async)
(anonymous) (trycatch.ts:40)
e (process.ts:107)
(anonymous) (process.ts:108)
r (helpers.ts:84)
requestAnimationFrame (async)
(anonymous) (trycatch.ts:40)
e (process.ts:107)
(anonymous) (process.ts:108)
r (helpers.ts:84)
requestAnimationFrame (async)
(anonymous) (trycatch.ts:40)
e (process.ts:107)
(anonymous) (process.ts:108)
r (helpers.ts:84)
requestAnimationFrame (async)
(anonymous) (trycatch.ts:40)
e (process.ts:107)
(anonymous) (process.ts:108)
r (helpers.ts:84)
requestAnimationFrame (async)
(anonymous) (trycatch.ts:40)
e (process.ts:107)
(anonymous) (process.ts:108)
r (helpers.ts:84)
requestAnimationFrame (async)
(anonymous) (trycatch.ts:40)
e (process.ts:107)
(anonymous) (process.ts:108)
r (helpers.ts:84)
requestAnimationFrame (async)
(anonymous) (trycatch.ts:40)
e (process.ts:107)
(anonymous) (process.ts:108)
r (helpers.ts:84)
requestAnimationFrame (async)
(anonymous) (trycatch.ts:40)
e (process.ts:107)
(anonymous) (process.ts:108)
r (helpers.ts:84)

**Comment by bhollis** [comment]
Without a substantial rewrite to how the loadout builder works, we’re just going to run out of memory if you have a lot of armor and not enough memory. @kyleshay

**Comment by philkernick** [comment]
I don't think I have a lot of armor - certainly the vault is not full.

At to memory, I have 16GB on the laptop I'm typing this on, and Chrome crashes the tab when it gets to 2.5GB used.  So I'm not out of memory.

**Comment by bhollis** [comment]
The memory Chrome will give the tab is not directly related to the amount of physical memory you have. That “Paused before” thing is some heuristic Chrome has where they try to predict if you will run out of memory and stop the tab before that happens. 

The loadout builder is a pretty naive algorithm - it goes through every possible combination of items you have and calculates their sets, and then sorts and displays them. Often this is millions of combinations. Without some changes to not do all that work, it’s going to exceed the hidden limits placed on websites.

**Comment by philkernick** [comment]
I agree it's a Chrome issue.  I tried doing the same thing in Microsoft Edge, and it peaks at 4GB, but doesn't crash.

That said, given the popularity of Chrome, I think we need a solution that doesn't crash the browser.

**Comment by philkernick** [comment]
Without a complete rewrite, we need to filter before generating the sets, rather than filtering after generating the sets.  My suggestion from #3571 could help reduce the number of sets.

**Comment by philkernick** [comment]
After trying a number of things, I've found a partial workaround.

Go to chrome://flags
Enable Memory coordinator

It uses less memory, so I can now uncheck the bonus mod tab and it doesn't immediately crash.  I can still reliably get it to crash by doing anything more complicated.

**Comment by philkernick** [comment]
Reference from the Chrome developers that there is a hard limit of 2GB per tab.

https://groups.google.com/a/chromium.org/forum/#!msg/chromium-dev/IKZvzuBP9QE/otSY-jc-FAAJ

**Comment by bhollis** [comment]
:thumbsup: I’d love some help with all that.

**Comment by philkernick** [comment]
The underlying problem is that in process.ts you are creating a set of all possible armor configurations.
`const setMap: ArmorSet[] = [];`

Inherently this is fine, even though after iterating through all the armor it has 2M armor sets in it, and doesn't cause the crash.

So you save it:
`this.setState({
      processedSets: setMap,
      processRunning: 0
    });`

However when you click the the exclude mod bonus tab, or click on another character, even though you unreference the existing map, the garbage collector doesn't have a chance to free it.  When you finally generate the new set, you now have two sets resident in memory.  And if at this point memory is exhausted, the tab crashes.

LoadoutBuilder.tsx:
`// re-process all sets
    this.setState({ lockedMap, processRunning: 0, processedSets: [], processError: undefined });
`

You can see this by watching the memory used by the tab.

**Comment by philkernick** [comment]
The changes in #3730 definitely help.  Chrome uses about half the memory it used to.

But the root of it is creating a very large memory object that never gets freed.

Here are a few data points on memory used:

1. Start DIM fresh (436M)
2. Go to Loadout Optomizer (836M)
3. Uncheck Exclude Mod Bonus (1214M)
4. Change character (1776M)
5. Go back to Inventory (1892M)
6. Bring up the debug console and click the Collect Garbage button lots of times (1850M)
7. Go to Loadout Optomizer again (2226M)

Every time a new loadout set it generated it uses an additional 400M (transitions above 1-2, 2-3, 3-4, 6-7), and this is never freed.  Going back to the Inventory screen should free the memory.  Creating a new loadout set should free the memory.  As the garbage collector can't reclaim it, it's definitely still referenced somewhere.

**Comment by bhollis** [comment]
Part of this seems to be React - it keeps old props around sometimes even after they're unmounted as some sort of optimization. For sure, we're simply sending too much info over.

The good news is I've designed a drastically different approach to loadout optimizer (as I mentioned would be needed) which avoids having to generate a huge list. It'll require some changes to the workflow, so it may be a while before I can land it.

**Comment by bhollis** [comment]
There also appears to be an interesting leak in the HTML5Backend of our React drag and drop library. Curious.
