### ISSUE TITLE
Spacers between item types in vault

### ISSUE THREAD

**Issue by parnmatt** [DestinyItemManager/DIM#3613]
I like to sort *via* Type first. It would be nice to have a small spacer between each type of weapon/armour.
It probably shouldn't be as larger as the class ones for armour; just a thin line with a little space; or even a centred dot or diamond (there's plenty of ascii symbols to choose for that).
Just something such that it's easier to see by eye the divisions.

**Comment by Wh1rledPeas** [comment]
Agreed! I sort this way too.

**Comment by Wh1rledPeas** [comment]
Could also be used to separate items that are already in the character's inventory, from items that are on another character or the in the vault, on the [+] Grab Item search dialog. #3639

**Comment by bhollis** [comment]
<img width="619" alt="Screen Shot 2019-03-23 at 6 55 28 PM" src="https://user-images.githubusercontent.com/313208/54873871-412a3480-4d9d-11e9-93ab-60e28d825928.png">

Here's an idea of what this would look like. I'm not sure it helps a lot, though, and it only applies in this one particular sort order that isn't even one of our presets. It's probably not worth the additional complication - it's the sort of thing that's likely to break because it's such a rarely-used option.

**Comment by Wh1rledPeas** [comment]
Oh... I was envisioning a horizontal line. When I view inventory, it is only 4 columns wide. If you have the option to apply certain layout features for only specific layouts, I can see a horizontal separation line as helpful in the mobile interface.

<img src="https://user-images.githubusercontent.com/3685437/54873965-49dc3400-4db8-11e9-9c58-1394fda0b7e9.png" width="300" />

**Comment by bhollis** [comment]
I don't think we want to do horizontal separators - the vault will get really tall that way.

**Comment by bhollis** [comment]
<img width="267" alt="Screen Shot 2019-03-30 at 3 24 52 PM" src="https://user-images.githubusercontent.com/313208/55282372-04f85600-5300-11e9-8b46-b86cac2b703d.png">

**Comment by bhollis** [comment]
Actually maybe that's not so bad...

**Comment by Wh1rledPeas** [comment]
If it's annoying for other's, it can be added as an additional setting in the sort configuration, as a sub-item of the item type.

Also, I'm not sure about @parnmatt, but for me, this is primarily a mobile thing. So it could be implemented as part of a mobile-only layout.

**Comment by parnmatt** [comment]
for portrait displays such as mobile, the horizontal line spacers seem appropriate.

I use DIM via a browser and alt-tab whilst gaming (quite frequently); for landscape displays like that of a computer monitor, vertical line spaces would be best (though with more horizontal padding than in the example above).
In my opinion that is.

**Comment by bhollis** [comment]
You can't add horizontal padding without misaligning the grid.

**Comment by kyleshay** [comment]
If you're organizing by type first, we could add the svg icons for weapons (similar to what we show in the organizer) between the types (so it would look similar to how armor splits up by class?)

**Comment by assasinitachi123** [comment]
> <img alt="Screen Shot 2019-03-30 at 3 24 52 PM" width="267" src="https://user-images.githubusercontent.com/313208/55282372-04f85600-5300-11e9-8b46-b86cac2b703d.png">

I likey this. Even I had something like this in mind. Hopefully this gets picked up. (This could be an additional preference for people who want to enable it at least)
