### ISSUE TITLE
Cant connect DIM to account

### ISSUE THREAD

**Issue by nmlssn** [DestinyItemManager/DIM#3615]
Trying to log into my Battle.net account on PC and Android and I can't, just get this error.

![screenshot 2019-02-20 16 27 35](https://user-images.githubusercontent.com/47833796/53125680-8a802d80-352c-11e9-87ae-e352d3719e24.png)

**Comment by bhollis** [comment]
This appears to be a Bungie.net problem - you’ll have to contact them.

**Comment by bhollis** [comment]
https://twitter.com/BungieHelp/status/1098377830792974336
