### ISSUE TITLE
Double-clicking on web does not transfer to inventory

### ISSUE THREAD

**Issue by TheAardwolf** [DestinyItemManager/DIM#3617]
When on patrol or in a mission, used to be double-clicking an item would at least transfer it to your inventory. Now we simply get a message saying the action is not possible.

While DIM cannot, of course, equip an item while we're not in orbit, it was a quick way to at least transfer an item so it could be equipped in-game.

**Comment by bhollis** [comment]
I just tried this, and it will still transfer the item (and give you an error about how it can't be equipped).

One time this doesn't work is if we can't de-equip an exotic in order to equip the item you want - then we won't even move. Is that what you were seeing?
