### ISSUE TITLE
Perk-based armor recommendation tool

### ISSUE THREAD

**Issue by DHager** [DestinyItemManager/DIM#3621]
This is a similar goal to #3519 but I think the approach is a little different.

### What is the problem?

Players who are hoarding pack-rats -- like myself -- have trouble deciding what armor to shard/keep, often skirting with the vault being full. The main pain-point isn't power-level or enhancement-cores, but vault slots.

I want to maximize the "capabilites" provided by my choices of armor-items, while minimizing how many items I need. For example, recognizing that the helmet (precision-targeting + sniper-scavenger) may render multiple other helmets (e.g. sniper-targeting + sniper+scavenger) as obsolete.

Trying to do this manually -- even with the great "exploration" mechanics of the Loadout Builder tool -- is a pain.

### What would it look like?

In a nutshell, the tool analyzes the user's armor-items and recommends which ones to keep or junk, based on how "valuable" the perks are on that armor. I'd like to control expectations by noting that this boils down to a [set covering problem](https://en.wikipedia.org/wiki/Set_cover_problem), which one way or another is "NP" difficult. 

1. Beginning of wizard dialog
1. The user chooses a particular class and slot for analysis, e.g. "Hunter helmets"
1. The user is presented with series of optimization options, such as:
   * Ignore all exotics
   * Ignore low-benefit perks (ex: "kinetic targeting")
   * Assume nobody will equip two "special" ammo weapons at once (e.g. shotgun+sniper)
   * Always keep "favorite"-tagged items
   * Ignore armor mobility/resilience/recovery
1. The user chooses a "goal" for how many of those items are to be kept, and kicks off the analysis.
1. The user sees progress information and a cancellation button.
1. The user is presented with a ranked display of recommended items, also showing the ones which are beneath the cutoff.
1. The user is given the option to automatically (or manually) re-tag items. Items must be inspect-able.
1. User is returned to regular interface.

### How would it work?

1. Collect all items of the given type (e.g. Hunter Helmets) which are not exotic
2. Create a bidirectional bipartite graph of items versus perk-combinations
    * For example, n dreaming-city chest-piece with perks (A,B,C) and (X,Y) will have connections to 6 perk-combos, (A,X) , (A,Y), (B,X), etc.
3. For perks which "dominate" others, generate new perk-combos with the dominated versions.
    * Enhanced perks dominate regular perks (Enhanced Bow Targeting > Bow Targeting) 
    * Broad-perks can dominate specific perks  (Precision Targeting > Bow Targeting)
    * This gets more complicated if we want to support "all kinetic" or "all energy" perks, because then we need an even finer-grained set of perk-combos.
4. Filter the graph, removing perk-combos which are impossible or impractical, ex:
    * Machine-gun Targeting with Rocket Launcher Reserves. (Impossible.)
    * Shotgun Targeting with Sniper Rifle Reserves. (Possible, but unlikely.)
5. Apply a greedy set-cover algorithm, which iteratively selects the armor-item which has the most outgoing edges and then removing the perk-combos it covers.
6. Stop when the desired number of items have been picked.

### Additional possibilities

* Assigning weights to certain weapon-categories
* Assigning weights to individual perks
* Special logic for players who only play straight PvE

**Comment by DHager** [comment]
I'm confident I could prototype the model/algorithm guts of this thing as a stand-alone application with demo data, but I could use some pointers on how best to trigger or integrate it to DIM. 

I suppose another alternative would be to ask the user to export all their DIM data, read that in  completely separate application, and then write out a modified "backup", but that doesn't seem like a very friendly workflow.

**Comment by wein3967** [comment]
Just as a heads up in the spirit of duplicate effort, I'd point you to @dasilva333's report-based version (https://github.com/dasilva333/dedupe-armor) or the DIM-based version (https://github.com/dasilva333/DIM). Both of these use a config file that can be modifed by the user to identify specific perks or perk pairs that are wanted or unwanted. I already has the basic preferences for impractical perks and targeting/loading/unflinching ... type stuff. The DIM version is the "latest."

**Comment by bhollis** [comment]
The Vault Organizer is launching today, but the landscape of how armor works has changed significantly. At this point, the Loadout Optimizer and the Vault Organizer should be enough to let you narrow in on which armor to keep and which to toss.
