### ISSUE TITLE
Searching for `perk:` includes mods

### ISSUE THREAD

**Issue by DHager** [DestinyItemManager/DIM#3622]
**Scenario:** Looking for armor with fundamentally "weak perks" in order to junk it, using `perk:slightly`.

**Expected:** `perk:term` will only search for `term` inside "blue circle" perks for armors.

**Actual:** `perk:term` will also search within the elemental-resistance masterwork description. Unlike the regular perks, that aspect can be upgraded, so it isn't the same kind of "irredeemable weakness" I'm looking for in junk items.

Example: `perk:slightly` will match all "Tier 2" armors (but not Tier 1) which contain the text "Slightly improved".

**Comment by sundevour** [comment]
suggested title: "Searching for `perk:` includes all sockets & plugs"
in this user's case/complaint, the masterwork slot.

this *could* be filtered with the information in
`sockets.sockets.plugOptions.plugItem.plug.plugCategoryIdentifier`
but relies on maintaining an identifier whitelist/blacklist, and would require maintainer decision that `perk:` is only meant to search specific sockets.

**Comment by sundevour** [comment]
it's 2019
