### ISSUE TITLE
Item Details are less sexy for equipped items

### ISSUE THREAD

**Issue by chrisfried** [DestinyItemManager/DIM#363]
Unequipped:
![screenshot 2016-01-13 08 54 41](https://cloud.githubusercontent.com/assets/422381/12297866/cf968706-b9d4-11e5-8c91-0a538d40a48b.png)

Equipped:
![screenshot 2016-01-13 08 54 48](https://cloud.githubusercontent.com/assets/422381/12297868/d28f2f3a-b9d4-11e5-89d6-e1b7e2f9ed2c.png)

**Comment by kyleshay** [comment]
the unequipped item is compared to the equipped item, if it's equipped not sure what we would compare it with

**Comment by chrisfried** [comment]
Duh. I'm an idiot. I thought it was doing... Something else.

**Comment by chrisfried** [comment]
Good start to the day. I think I'll go back to sleep.
