### ISSUE TITLE
Collect Postmaster: Skip unmovable items.

### ISSUE THREAD

**Issue by bradende** [DestinyItemManager/DIM#3630]
Reporting against version 5.17.0:

Sometimes the postmaster holds items that cannot be collected, for example:
Modulus reports
Some Dreaming City drops
Rarely, some quest rewards

In these cases, the "Collect Postmaster" button no longer works - it aborts on the first
failure. I can individually collect eligible items, but in cases of full inventory buckets, the
individual collect operations can move items I'm pulling. For example.

I have a full Kinetic Weapons character bucket. In my postmaster are two kinetic weapons,
and some modulus reports.
I cannot use "Collect Postmaster", due to the modulus reports.
I pull the items individually. The first pull moves a kinetic weapon out of the character bucket
to make room, then moves the item out of postmaster into the recently vacated spot.
The second pull consistently moves the item I just collected to the vault to make room, though
I'd intended to interact with it. Now I need to manually move an item out of the bucket, and
retrieve the first postmaster item from the vault.
If, instead of performing that second postmaster fetch, I make room in game (by dismantling
an item, for example), I need to wait for an API refresh to use the bucket.

I'd like the Collect Postmaster command to skip items that cannot be moved, and continue on
to eligible items - preserving the behaviour of making room for as many items as possible in
the applicable character buckets.

**Comment by delphiactual** [comment]
Dupe #3584

**Comment by bhollis** [comment]
Thanks for the detailed report!
