### ISSUE TITLE
Better handling of Google Drive outages

### ISSUE THREAD

**Issue by ericleone** [DestinyItemManager/DIM#3634]
https://www.google.com/appsstatus#hl=en&v=issue&sid=4&iid=082ee9e7a232740761ef507d7ac31eb2
During this outage many users were unable to load DIM (app. or beta.) or it loaded intermittently. There was no indication of an issue and the icon in the corner would just endlessly animate to indicate loading.

**Comment by delphiactual** [comment]
https://twitter.com/bhollis/status/1105699224912519168

**Comment by bhollis** [comment]
Yeah, I worked on this and I really wish I could have helped, but Google’s client has a bug that doesn’t correctly report errors. It just hangs. 

Our options are to write our own Google Drive client or abandon Google Drive for a better storage solution. We’re going to pursue the latter, and if we can’t make that work for financial reasons I’ll write my own Drive client.
