### ISSUE TITLE
QOL: UI Layout & Behavior tweaks for clarity and efficienciels

### ISSUE THREAD

**Issue by Wh1rledPeas** [DestinyItemManager/DIM#3639]
As I've been playing this past week I've come across a couple things I find myself doing repetitively. There are a few tweaks I think will help reduce the amount of interaction with the app that's required in order to do these tasks.

#### _ACTION BUTTONS_

1. Whenever I pull up the item details sheet to Tap a button and perform an action, I always have to scroll down to find the buttons. (mobile)  
  
   Since the entire sheet is scrollable (including the buttons), would it be possible to move the action buttons up abive the [Overview]/[Reviews] tabs? Even if that's a mobile-only tweak... That would reduce a ton of down-swipes for me every day.

2. With the larger icons, I always have to left-swipe when I get to the bottom too. Granted, I'm an old man with less than optimal eyesight, so I have my accessibility settings set to show larger items. It would be very helpful if you could reduce the padding around each of the buttons, so they scrunch up slightly. Optimally, it would be nice if they were automatically sized to fit within the sheet.`((sheet.width - (padding * 8)) / 7)`, but a slightly smaller padding between them would do the trick for me.

#### _INFUSION FUEL FINDER_

1. I rarely ever infuse items that aren't duplicates. So when searching for infusion fuel, the only items I'm interested in are duplicates. Would it be possible to automatically [switch] so the duplicate item is visible when the sheet is initially shown? (when one exists)

2. When there *IS* a duplicate item, I *ALWAYS* have to tap it to select it. Even though it's shown at the top of the list, the item underneath it, (the first item in the non-duplicate list), is the one that's automatically selected. Would it be possible to tweak the "initial item selected" process and have it set to any duplicate, if one exists?

#### _GRAB ITEM DIALOG_

1. Currently, the items that are already in that character's inventory show up in the search list. Would it be possible to designate them in someway? (Dimmed or partially opaic perhaps?)

EDITS: Formatting
    (mobile GitHub doesn't have a preview mode. Sorry... )

**Comment by delphiactual** [comment]
> As I've been playing this past week I've come across a couple things I find myself doing repetitively. There are a few tweaks I think will help reduce the amount of interaction with the app that's required in order to do these tasks.
> 
> #### _ACTION BUTTONS_
> 1. Whenever I pull up the item details sheet to Tap a button and perform an action, I always have to scroll down to find the buttons. (mobile)
>    Since the entire sheet is scrollable (including the buttons), would it be possible to move the action buttons up abive the [Overview]/[Reviews] tabs? Even if that's a mobile-only tweak... That would reduce a ton of down-swipes for me every day.

#1926 

> 2. With the larger icons, I always have to left-swipe when I get to the bottom too. Granted, I'm an old man with less than optimal eyesight, so I have my accessibility settings set to show larger items. It would be very helpful if you could reduce the padding around each of the buttons, so they scrunch up slightly. Optimally, it would be nice if they were automatically sized to fit within the sheet.`((sheet.width - (padding * 8)) / 7)`, but a slightly smaller padding between them would do the trick for me.
> 

#3502
> #### _INFUSION FUEL FINDER_
> 1. I rarely ever infuse items that aren't duplicates. So when searching for infusion fuel, the only items I'm interested in are duplicates. Would it be possible to automatically [switch] so the duplicate item is visible when the sheet is initially shown? (when one exists)
> 2. When there _IS_ a duplicate item, I _ALWAYS_ have to tap it to select it. Even though it's shown at the top of the list, the item underneath it, (the first item in the non-duplicate list), is the one that's automatically selected. Would it be possible to tweak the "initial item selected" process and have it set to any duplicate, if one exists?
> 
> #### _GRAB ITEM DIALOG_
> 1. Currently, the items that are already in that character's inventory show up in the search list. Would it be possible to designate them in someway? (Dimmed or partially opaic perhaps?)
> 
> EDITS: Formatting
> (mobile GitHub doesn't have a preview mode. Sorry... )

**Comment by Wh1rledPeas** [comment]
> #### _ACTION BUTTONS_
>    Since the entire sheet is scrollable (including the buttons), would it be possible to move the action buttons up abive the [Overview]/[Reviews] tabs? Even if that's a mobile-only tweak... That would reduce a ton of down-swipes for me every day.

Or move the action buttons below the scrollable area, so they're permanently attached to the bottom of the sheet, as part of the "footer". Either would work.

**Comment by Wh1rledPeas** [comment]
> #### _GRAB ITEM DIALOG_
> 1. Currently, the items that are already in that character's inventory show up in the search list. Would it be possible to designate them in someway? (Dimmed or partially opaic perhaps?)

I didn't see this item referenced in your cross-references or tags. Just want to make sure it wasn't missed.
