### ISSUE TITLE
What happened to weapon and armor reviews?

### ISSUE THREAD

**Issue by edmiller47** [DestinyItemManager/DIM#3648]
They are not appearing now in the item detail. Confirmed in Chrome on PC, iPhone, iPad.

**Comment by bhollis** [comment]
Maybe DTR was down for a bit? I see them now.

**Comment by edmiller47** [comment]
Still not showing for me. DTR is up and showing everything I normally see there.

**Comment by edmiller47** [comment]
Just to be clear, I'm talking about this:
![image](https://user-images.githubusercontent.com/13838005/54563274-258aec80-499f-11e9-8566-098ef7dd9ecb.png)

**Comment by bhollis** [comment]
What browser?

**Comment by bhollis** [comment]
Anything in the console? Here's what I get:

<img width="653" alt="Screen Shot 2019-03-18 at 2 42 45 PM" src="https://user-images.githubusercontent.com/313208/54565672-20707200-498c-11e9-81e7-cfac0ac3bdc2.png">

Do you have reviews enabled in settings?

**Comment by edmiller47** [comment]
Using Chrome as stated in original post.

**Comment by edmiller47** [comment]
What you are getting is what I'm expecting. I haven't changed my settings and reviews have always been turned on.

**Comment by edmiller47** [comment]
Toggled reviews off then back on. Working now. 

Thanks for the rapid responses. Love this app.

**Comment by bhollis** [comment]
Glad to hear it’s working. Super weird that it broke. @48klocs any ideas?

**Comment by 48klocs** [comment]
My best guess is that the DTR API had a hiccup. I've seen that sort of thing when it has a blip (or when I screw things up locally).
