### ISSUE TITLE
ESLint caching

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#3651]
```
Caching:
  --cache                        Only check changed files - default: false
  --cache-file path::String      Path to the cache file. Deprecated: use --cache-location - default: .eslintcache
  --cache-location path::String  Path to the cache file or directory
```

Instead of running eslint on the entire project for every PR (~60s) we can cache the results on Travis...

**Comment by bhollis** [comment]
That’d be cool!

**Comment by bhollis** [comment]
https://docs.travis-ci.com/user/caching/

**Comment by delphiactual** [comment]
currently eslint caching using file mtime but there is an open PR for md5 checksums

https://github.com/eslint/eslint/pull/11487

**Comment by delphiactual** [comment]
Will leave this open until eslint merges #11487 or some other way for md5 hashes

**Comment by delphiactual** [comment]
#3697 until #11487 merged
