### ISSUE TITLE
Modulus Report MAX in first postmaster slot prevents moving anything else to vault

### ISSUE THREAD

**Issue by gimoda** [DestinyItemManager/DIM#3657]
I'm maxed out on Modulus Reports in inventory, and it's showing as first (to the left-most) in DIM for my character, but clicking Collect Postmaster always says "there are no item slots available to move this inventory" even though I have other items in there that can be moved.

If I go to the postmaster in the game, the Modulus Report is not in the left-most slot.

**Comment by delphiactual** [comment]
Dupe #3633 
Closed by #3653

**Comment by gimoda** [comment]
This is not a dupe of #3633 nor #3653... I'm not reporting a problem with max power calculation. Please read what I wrote.

I'm reporting a problem with the Collect Postmaster button not being able to move ANY items in the postmaster if the first item (left-most) is a Modulus Report at MAX capacity. It doesn't matter what items are after that or if I have room for them (blue items, shaders that I have room for, etc).

If the first item showing in the postmaster in DIM cannot be moved, then it prevents ALL other items from being moved. 

![image](https://user-images.githubusercontent.com/48866340/55159820-83e66680-5127-11e9-8b48-d08cc0ccc7c4.png)

**Comment by bhollis** [comment]
This was fixed in 5.20.2

**Comment by delphiactual** [comment]
Sorry I meant 
Dupe #3630
Closed by #3668 & #3669
