### ISSUE TITLE
BETA: Height of comparison window is too small

### ISSUE THREAD

**Issue by knaylomo** [DestinyItemManager/DIM#3664]
Beta Version 5.19.0.3002 (beta), built on 3/24/2019, 2:09:04 PM

Something changed recently in beta where now when I go to compare items I only see about 60% of it before having to use the comparison scrolldown. This is with a smaller laptop display resolution (1366x768). This makes it very difficult to use when comparing multiple items. Non-beta DIM works fine.

Tested this on another machine with higher resolution, and you need about 1000 pixels height on a Chrome browser window (including tabs/toolbar) or it will cut off the bottom of the comparison.

![DIM-main](https://user-images.githubusercontent.com/48895537/54888587-8a40be00-4e5b-11e9-8abe-795e1d38d767.png)
![DIM-beta](https://user-images.githubusercontent.com/48895537/54888588-8b71eb00-4e5b-11e9-9a19-66e8ae3fd245.png)

**Comment by bhollis** [comment]
Thanks, I just pushed out a fix.
