### ISSUE TITLE
Handle out of date inventory during moves

### ISSUE THREAD

**Issue by Wh1rledPeas** [DestinyItemManager/DIM#3666]
I have a suggestion for handling inventory discrepancies more gracefully and reducing the need for users to refresh their data as often.

### *_BACKGROUND:_*
      
* I am often using DIM to collect duplicates to my current character, comparing them, then either infusing or dismantling them. After infusion/dismantle, the item still shows up in DIM even though it's not there anymore in-game. Many times, my character's inventory is full of items that I use regularly and I have one or two empty spots for transferring duplicates over for comparisons.
   
   If DIM still sees that item spot as full, it will automatically move something out of the way when transferring the next item over for comparison. That's all fine and dandy, but when I'm done infusing/dismantling, then I have to go hunt down those items that I use regularly and move them back to my character.
   
   To make matters a bit more frustrating, when it comes to armor, I always sort my armor sets in inventory, so that spot 1 in each armor slot is my crucible gear, spot 2 is my raid gear, etc. That makes it really easy to manually switch to an armor set in-game. So when DIM thinks all the helmet spots are full, it moves a piece of armor out to make room, completely messing up my ordered set. I then have to go hunt that piece down, move it back to the character, then re-order that inventory spot back to the way it was. This is frustrating when I know for a fact that there's an empty spot there. 
   
   I used to handle this by manually refreshing inventory in between each infuse/dismantle operation. This took a lot of time and required traffic to/from Bungie that wasn't needed, but it was the only way to get DIM to update. With the new search implementation, this isn't even possible anymore, without canceling out of search, tapping refresh, waiting for the refresh to actually go through, then going back to search and typing your search query all over again.
   
   This is very tedious and time consuming when you're trying to clear 10-15 legendary items out of the postmaster. 
</h3>

### *_PROPOSED SOLUTION(s):_*

1. Instead of assuming it needs to move an item out of the way, to make room for an incoming item, attempt the move to see if there's an error and only "make space" if the move fails.

2. If the user attempts to interact with the phantom item (move it, lock/unlock, etc) and it comes back with an error that the item doesn't exist, immediately remove the item from the local dataset 
   
   In the screenshot below, the 679 "Go Figure" has been dismantled in-game. I know this, but DIM doesn't. Even refreshing the inventory didn't clear it out because of the cache refresh intervals.
   
   <img src="https://user-images.githubusercontent.com/3685437/54939560-41dadc00-4eff-11e9-8a21-e9dadb2d0306.png" width="200" />
   
   I tried to move it to the vault, hoping that DIM would realize it wasn't valid and remove it. It detected the "item not found" condition, but left the item there in the inventory.
   
   If you simply update the error handling for the "item not found" error so it also removes that item from the local dataset, a user would only need to attempt to interact with it to get the local inventory rectified.
   
   That would be much quicker than waiting around for the next data refresh interval and would require less round-trip data with Bungie as well. I'm pretty sure users would easily learn to take advantage of this, as I'm sure waiting for dataset refreshes is fairly high on the struggle list for most users.

**Comment by inexorableAce** [comment]
This honestly sounds like you just need to make some loadouts instead of the laborious task of custom sorting your character inventory per set. 

There’s not a ton we can do about refresh and bungie caching iirc. If you want new cache typically just equipping a weapon via the api will get you a fresh cache and avoid this.

**Comment by bhollis** [comment]
Thanks for the suggestion. What you're saying makes sense, and we've talked about these ideas internally a bunch. Unfortunately, it just isn't super easy to actually implement them. There are a lot of edge cases that get exposed that are even harder to deal with. 

The way item movement works today is that if you try to move an item into a bucket that doesn't have space, we *automatically* perform a full inventory refresh before attempting the move. Unfortunately, Bungie.net can be quite out of sync from the game, especially in D2 (and especially in the tower). We'll continue to investigate ways to make this better, but in the meantime we're kind of stuck.

**Comment by Wh1rledPeas** [comment]
@inexorableAce: Yes. In regards to armor I probably do, but until this most recent refresh of the Loadout Builder, it was unusable on the mobile platform. That still doesn't help when weapons I'm currently using/evaluating get thrown off into the vault and I have to hunt them down again. That isn't always easy because I rarely remember what they were. Many times I have several weapons with different rolls that I'm just playing with for testing.

@bhollis: How difficult would it be to remove the item from the current dataset when a, "not found" error is encountered?

I assume that when this error occurs, that specific item no longer exists in the user's inventory on Bungie's end, right? If so, there's no reason to keep it in the current dataset.

I understand it might not be that simple. Just asking.

**Comment by inexorableAce** [comment]
Hmm yeah, perhaps try using notes or a favorite tag on your favorite / most used weapons so you can search for them easier sans a name. 

@bhollis I know bungie keeps a record of every action the API performs and you can see it on bungie.net, is there a way for us to pull that list and keep maybe like the past 50 or so actions for people to review in app? That could help with this as well as a few other problems people have with “losing” things.

**Comment by Wh1rledPeas** [comment]
@inexorableAce: I do use favorites and notes, but when you're infusing virtually every drop you get, those things get lost. Additionally, I'm also talking about weapons that I've only recently gotten and have several in my inventory that I'm playing with, to see if I like them. 5 or 10 that I may have only gotten today. It's not practical or worth the time to try and tag them all. I'm most likely going to get rid of them. Regardless, the way I choose to keep my inventory organized really isn't something I care to change.

It's frustrating when DIM moves an item to the vault when there is already an empty spot available.

Honestly, I'd love to have a setting that told DIM to *never* "make room" and only move items when there's an empty space available. But then I'd still need a way to force DIM to remove the ghosted items.

**Comment by bhollis** [comment]
> How difficult would it be to remove the item from the current dataset when a, "not found" error is encountered?

Pretty difficult, because the next refresh will likely bring the item back. If we had a reliable way to update Bungie.net's view of things, we could try that, but just removing it won't really help. Somebody mentioned that successfully moving an item will make things update - if that's reliable then maybe I can make something work. I think it's easier to at least try to move things even when inventory is full, but even then there's stuff that will break if you have 11 items in a bucket that holds 10, since we do a lot of logic based on how full the bucket is.

> I know bungie keeps a record of every action the API performs and you can see it on bungie.net, is there a way for us to pull that list and keep maybe like the past 50 or so actions for people to review in app? That could help with this as well as a few other problems people have with “losing” things.

We've talked about keeping a log of actions for people to undo. It's just kind of a niche feature and it would only capture moves made in DIM, not in game. If somebody wants to prototype something that'd be neat.

> I'd love to have a setting that told DIM to never "make room" and only move items when there's an empty space available.

That's just not really how DIM is designed to work. DIM is designed to do what you ask it to do. If your inventory is full and you choose to move something into it, then DIM will do what you asked ("move this item") and it may have to move something else to do that. If you don't want a random thing moved, you need to make space yourself. If you have already deleted something and want to move it with DIM, then manually refresh until DIM knows it's gone, otherwise you're guaranteed to have something move away (though we also automatically refresh every 30 seconds).

**Comment by bhollis** [comment]
I’ll also add that since this is an issue that’s difficult to reproduce, it’s also difficult to test that we’ve gotten it right.

**Comment by Wh1rledPeas** [comment]
> > How difficult would it be to remove the item from the current dataset when a, "not found" error is encountered?
> 
> Pretty difficult, because the next refresh will likely bring the item back.

Ahh... Yes. That makes sense. Thank you for explaining.

I have an idea that might work. What if you created a "blacklist" of items that had been "not found", then filter them out of the dataset when it's reloaded? When they're not found in the dataset any longer, remove them from the blacklist, to keep it short and only perform the filter when that list contains 1+ items.

In practice, I would think the blacklist would very rarely contain any items. Only when someone tried to interact with an item that didn't exist in-game any longer. 

> We've talked about keeping a log of actions for people to undo. [...snip...]

This isn't necessary. It's a nice thought, but it would be just as irritating to go find inadvertent moves on that list as it would be to search through the vault.

What I've done in the past is fly to the tower, where I can sort the vault by newest and see the last few items that were moved there. 

> [...snip...] If you don't want a random thing moved, you need to make space yourself. [...snip...]

Yes. I do that constantly. It was just waiting for DIM to see the empty space that got me to thinking about the "not found" being a trigger to manually remove it before Bungie sent an up to date dataset.

**Comment by bhollis** [comment]
> What if you created a "blacklist" of items that had been "not found", then filter them out of the dataset when it's reloaded?

I've thought of that too, but I don't think I can distinguish between an item that is missing because it's been deleted, and one that has been moved elsewhere.

**Comment by Wh1rledPeas** [comment]
> I've thought of that too, but I don't think I can distinguish between an item that is missing because it's been deleted, and one that has been moved elsewhere.

Ahh... Yes. I didn't think about it being somewhere else. I was thinking Bungie just didn't have the item in the dataset at all. I tested that just now. Moved an item onto the vault in-game, unbeknownst to DIM, and tried to move it from my character to another using DIM. It reports the same "not found" error. I was thinking the items had a unique id/hash and the location didn't matter. Sort of like an inventory.all("itemId).

**Comment by inexorableAce** [comment]
Yeah the api history list would at least make it easy for you to see what was moved, you’d said things become difficult to find because you may not know the name or have tagged / noted it. 

The history list would at least show you what we moved so you can find it / revert the action without having to find it. 

Just trying to offer viable options that might help.

**Comment by bhollis** [comment]
If you’re interested in new items you might also want to enable the new item dot and use the `is:new` filter.

**Comment by bhollis** [comment]
To move forward on this issue, I need confirmation that moving an item with the API will "unstick" stale inventory results.

**Comment by inexorableAce** [comment]
I don’t believe it’s a guarantee. Just more likely to clear your bungie cache than the normal refresh method. As you stated from what I’ve seen if you are in a vendor or near one in the tower there is seemingly no way at all to get fresh data.

**Comment by bhollis** [comment]
Yeah, that was my understanding, that it's a bug between the game servers and the B.net servers.

**Comment by Wh1rledPeas** [comment]
Also... I do a lot of inventory management and infusion decision making while I'm flying in for the next strike/crucible match/etc. So equipping an item to update the data set isn't an option.

Since this is something that doesn't happen unless someone attempts to interact with a phantom item, it's not going to happen very often. It already displays an error, so it interrupts flow. A little extra processing isn't out of the question.

If you keep a small array of phantom items, each with an expiration of 60 seconds or so, and filtered the rendered objects by it, that would give the user some time to move a new item (using infuse for example) without DIM "making room".

It would become "learned behavior" after a while.  Phantom object? Attempt to move it to the vault and it'll disappear for a minute so you can do your thing.

If the item shows up in that bucket again, after the filter entry expires, I wouldn't mind if there was an extra item in that bucket, throwing off the layout a bit. I would understand that DIM was a little confused because I was messing with inventory. <i>Actually, I think I've seen that happen a time or two anyway.</i> I just need DIM to recognize an empty space is available, so I can continue with my inventory management in spite of how stale the API data is.

If you track the bucket it was found missing from and only filter it from that bucket, the item would reappear when the data set got current data. 

You can also remove the item from the filter, anytime a successful interaction with an item occurs and the item is found in the filter. So if it does show up elsewhere and the user moves it back to that spot, it will show, regardless if the filter entry has timed out or not.

**Comment by Wh1rledPeas** [comment]
Since this is something that would potentially get called for every item on the page, I wondered if it was feasable to implement and how much overhead it would add. So I spent some time last night, cobbling together a JavaScript object that handles all of this logic internally. After instantiating an instance of the object, the following three changes will facilitate everything I discussed.

1. Any time an "item not found" error occurs, call `itemFilter.add(item, bucket);` and re-layout the items in that bucket.

2. While looping through items to display, set `item.style.display = itemFilter.displayStyle(item, bucket);` (or modify per your integration needs)

3. Anytime a successful move/equip occurs on an item, call `itemFilter.remove(item);` before re-layout, to make sure it's not being filtered.

I threw together a test harness to throw some serious load at it and flush out any performance overhead. I'll include it below.  When I ran it on my laptop, the code ran for 7m 40s, refreshing 100 items on the screen, every 250ms. It returned the following stats:

> The getDisplayStyle() method was called 176100 times.
> The total time spent evaluating display styles was 0.32900000000000024 seconds.
> The purgeExpiredItems() method was called 122482 times.
> The list was evaluated for purges 91 times.
> 100 items were purged from the list.
> The total time spent purging was 0.002 seconds.

So I'm happy with the performance of what I put together. I think it's efficient enough to be used when filtering 100+ objects on a page during a refresh.

I do realize it seems like a lot of effort to put into something that is a small annoyance, but I've done most of the heavy lifting, so perhaps you can evaluate it.  I did not test it on older browsers.

## Source Code
<details>
   <summary><b><i>FilterListObject.js</i></b></summary>

```javascript
/// <summary>Maintains a list of items to filter out of results due to
/// not-found errors</summary>  
class FilterList {

    constructor() {
        this.filterList           = new Map();
        this.lastpurged           = 0;
        this.CACHE_TIME           = 60000; // ms to keep items filtered
        this.PURGE_INTERVAL       = 5000;  // ms to wait between purges
        this.DEBUG                = false;
        this.GetDisplayStyleCalls = 0;
        this.GetDisplayStyleTime  = 0;
        this.PurgeMethodCalls     = 0;
        this.PurgeEvaluations     = 0;
        this.PurgedItems          = 0;
        this.PurgeTime            = 0;
        this.StartTime            = Date.now();
    }

    /// <summary>Returns the number of items in the list</summary>
    get size() {
        return this.filterList.size;
    }

    /// <summary>Returns the amount of time the object has been alive</summary>
    get upTime() {
        let totalSeconds  = (Date.now() - this.StartTime) / 1000;
        let days          = Math.floor(totalSeconds / 86400);
        totalSeconds     %= 86400;
        let hours         = Math.floor(totalSeconds / 3600);
        totalSeconds     %= 3600;
        let minutes       = Math.floor(totalSeconds / 60);
        let seconds       = totalSeconds % 60;

        let timeString = 
            days + "d " + 
            hours + "h " + 
            minutes + "m " + 
            Math.round(seconds, 3) + "s";
            
        return (timeString);
    }

    /// <summary>Adds an item to the list and associates it with a bucket.
    /// Items can only belong to one bucket, so adding an item twice will
    /// overwrite any predecessors</summary>
    /// <param name="item" type="Object">The item who's id shoud be added
    /// to the list</param>
    /// <param name="bucket" type="Object">The bucket who's id should be
    /// associate with the item</param>
    add(item, bucket) {

        if (this.DEBUG) {
            console.log("Adding %s to %s", item.value, bucket.value);
        }

        // Create our object to hold the information about the item 
        // we need to process
        var itemInfo = {
            timeStamp: Date.now() + this.CACHE_TIME,
            bucketId: bucket.id
        }

        // Add it to the map
        this.filterList.set(item.id, itemInfo);
    }

    /// <summary>Removes an item from the list</summary>
    remove(item) {
        if (this.filterList.has(item.id)) {
            if (this.DEBUG) {
                console.log("Removing %s", item.value);
            }
            this.filterList.delete(item.id);
        }
    }

    /// <summary>Returns a display style based on whether this
    /// object should currently be filtered from the user's view</summary>
    /// <param name="item" type="Object">The item who's id we're looking for</param>
    /// <param name="bucket" type="Object">The bucket who's id
    /// is associate with the item</param>
    getDisplayStyle(item, bucket) {
        let start = Date.now();

        this.GetDisplayStyleCalls += 1
        let style = "inline";

        // Only process if our item is somewhere in the cache.
        // This minimizes overhead for any other items.
        if (this.filterList.has(item.id)) {

            // This seems like the best place to kick off a purge.
            // We have to do it at some point and this is one of the rare
            // items that was identified as "not found". 
            this.purgeExpiredItems();

            let filteredItem = this.filterList.get(item.id);

            // Make sure it came back and wasn't removed by the purge.
            if (filteredItem) {

                // If the item is filtered from the bucket
                // we're interested in
                if (filteredItem.bucketId === bucket.id) {

                    // And the expiration time hasn't passed
                    if (filteredItem.timeStamp >= Date.now()) {
                        // don't display it
                        style = "none";
                    }

                    if (this.DEBUG) {
                        style += " - cached for " + 
                            ((filteredItem.timeStamp - Date.now()) / 1000) +
                            " seconds.";
                    }
                }
            }
        }

        let seconds = (Date.now() - start) / 1000;
        this.GetDisplayStyleTime += seconds;
        if (this.DEBUG) {
            console.log("Evaluation Time: %f", seconds);
        }
        return style;
    }

    /// <summary>Cleans up stale entries</summary>
    purgeExpiredItems() {

        this.PurgeMethodCalls += 1;
        let start = Date.now();

        // Throttle the purge process
        if (this.lastpurged < Date.now() - this.PURGE_INTERVAL) {

            this.PurgeEvaluations += 1;
            this.lastpurged = Date.now();

            if (this.DEBUG) {
                console.log("Purging...");
            }

            // Only if there are items in the list
            if (this.filterList.size > 0) {

                let oldItems = [];
                let cutoffTime = Date.now();

                // Build a list of expired items
                this.filterList.forEach(
                    function(value, key) {
                        if (value.timeStamp < cutoffTime)
                            oldItems.push(key);
                    }
                )

                this.PurgedItems += oldItems.length;
                if (this.DEBUG) {
                    console.log("Found %d items to purge", oldItems.length);
                }

                // Remove expired items from the inner map object.
                for (let i = 0; i < oldItems.length; i++) {
                    if (this.DEBUG) {
                        console.log("Purging id '%s'", oldItems[i]);
                    }
                    this.filterList.delete(oldItems[i]);
                }
            }
            
            let seconds = (Date.now() - start) / 1000;
            this.PurgeTime += seconds;
            if (this.DEBUG) {
                console.log("Purge Time: %f", seconds);
            }
        }
    }
}
```
</details>
<details>
    <summary><b><i>TestHarness.js</i></b></summary>

```javascript
// ==============================================================
// == A crude implementation to test the FilterList() object with
// ==============================================================

// Helper function
function makeHash() {
    return Math.random().toString(36).substr(2, 9);
}

// Helper function
function createItem(name) {
    var obj = {};
    obj.id = this.makeHash();
    obj.value = name;
    return obj;
}

// Helper function
function createItems() {
    for (var i = 1; i <= 20; i++)
        this.items.push(this.createItem("Item #" + i));
}

// Helper function
function createGroups() {
    for (var i = 1; i <= 5; i++)
        this.groups.push(this.createItem("Group #" + i));
}

// This builds a display of the data, simulating items in buckets
// and calls itself repeatedly to keep the display up to date until
// no items are left in the filter list.
//
// It repeatedly calls the getDisplayStyle() method for each of
// the 100 items on the page. This also tests the throttling of the
// operation that purges expired items. Every time the getDisplayStyle()
// method is called, there's a chance that a purge will be run, but
// it has throttling built in.
//
// This was done to simulate any performance impact of calling that
// method hundreds of times, when rendering the display of hundreds
// of items on a page.
function showCache(exitFlag) {

    var cacheContents = "<font size='1' face='Courier New, Monospace'>";

    // 
    itemFilterList.filterList.forEach(function addToList(value, key, map) {
        cacheContents += key + ":" + value.bucketId + ":" + value.timeStamp + " | ";
    })

    cacheContents += "<hr noshade size='4' />";

    for (var g = 0; g < groups.length; g++) {
        cacheContents += "<H3>" + groups[g].value + "</H3>"
        for (var i = 0; i < items.length; i++) {
            cacheContents += items[i].value + ":" + 
                itemFilterList.getDisplayStyle(items[i], groups[g]) + 
                "<BR />";
        }
    }

    window.document.getElementById("output").innerHTML = cacheContents;

    if (exitFlag && exitFlag === true) {
        console.log("The process ran for %s.",
            itemFilterList.upTime);
        console.log("The getDisplayStyle() method was called %f times.",
            itemFilterList.GetDisplayStyleCalls);
        console.log("The total time spent evaluating display styles was %f seconds.",
            itemFilterList.GetDisplayStyleTime - itemFilterList.PurgeTime);
        console.log("The purgeExpiredItems() method was called %f times.",
            itemFilterList.PurgeMethodCalls);
        console.log("The list was evaluated for purges %f times.",
            itemFilterList.PurgeEvaluations);
        console.log("%f items were purged from the list.",
            itemFilterList.PurgedItems);
        console.log("The total time spent purging was %f seconds.",
            itemFilterList.PurgeTime);
        return;
    } else {
        if (itemFilterList.size > 0)
            window.setTimeout(showCache, 250);
        else
            window.setTimeout(showCache, 250, true);
    }
}

// This is the entry point and simply facilitates a methodical
// addition of items to the filter over a period of time.
function addNextItem(i, g, wait) {

    itemFilterList.add(items[i], groups[g]);

    if (++i >= items.length) {
        i = 0;
        if (++g >= groups.length) {
            return;
        }
    }

    // Implemented as a recursive timeout loop to simulate
    // a delay between items being added, giving them time to expire.
    window.setTimeout(addNextItem, wait, i, g, wait);
}

// Set up some local stuff
var itemFilterList = new FilterList();
var items = [];
var groups = [];

// Initialize items
itemFilterList.DEBUG = true;
createItems();
createGroups();

// Start adding items in 4 second intervals
addNextItem(0, 0, 4000);
// Start refreshing the display
window.setTimeout(showCache, 1500);
```
</details>

<details>
   <summary><b><i>TestHarness.htm</i></b></summary>

```html
<html>
    <head>
        <title>TEST PAGE</title>
    </head>
    <body>
        Cache Contents:<BR />
        <p id="output">
        </p>
    
        <script type="text/javascript" src="FilterListObject.js"></script>
        <script type="text/javascript" src="TestHarness.js"></script>
    </body>
</html>
```
</details>

**Comment by bhollis** [comment]
That’s OK - I’m not worries about the implementation or performance impact of maintaining such a filter. I’m concerned with how this would actually impact the experience of using DIM. As we’ve learned recently, messing with the logic and assumptions that we use to handle item movement can cause serious ripple effects. At this point the only way to make progress on this would be if someone else wanted to submit a working PR in DIM and can show that the resulting behavior makes sense and that it doesn’t trigger any other bugs. I’m not personally going to work on it.
