### ISSUE TITLE
Add equipped to loadouts should respect class restriction or set class type on the loadout

### ISSUE THREAD

**Issue by NoCodeLeftBehind** [DestinyItemManager/DIM#3670]
When you use the new Loadout Creator dialog and have it set to "any class," it doesn't make sense for the "Add equipped" option to add equipped Armor and subclass to that loadout. Armor is class specific. It should only add equipped weapons and, perhaps, ghost.

**Comment by inexorableAce** [comment]
I think it makes sense... adding equipped is adding equipped. We should likely update the selector to the appropriate class though. (Pretty sure we do that anyway if you submit it with class specific things we save it as class specific regardless of the class selector.) @bhollis can confirm that. 

But yeah if a button says add equipped I expect it to do just that regardless of anything else.

**Comment by NoCodeLeftBehind** [comment]
No, it definitely saves it as an any class loadout and will transfer and try (and fail) to equip that armor when you select that loadout on another class. I cannot imagine a scenario where it makes sense to include class-specific armor in an "any class" loadout. You just ended up transferring 5 armor pieces you can't use on the other classes.

**Comment by inexorableAce** [comment]
Oh, that’s no good. That should definitely be smarter and more transparent in the UI if you add class locked things 👍
