### ISSUE TITLE
tooltip on mouseover

### ISSUE THREAD

**Issue by ausfestivus** [DestinyItemManager/DIM#3671]
Being a new DIM user im finding it difficult to get up to speed with using it like a pro.

I have only been playing D2 regularly since Forsaken so my knowledge about a lot of terms and mechanics isn't super strong. I feel like i'm not understanding a lot of the terminology and stats information that DIM surfaces and thats probably partly due to my newness with Destiny in general.

However, what I have found myself doing on many occasions is mouseover-ing an item in the desktop GUI in the hope fo reading a small explainer about what the button/item/widget is/does/means.

It would be neat to get something like this.

**Comment by bhollis** [comment]
Could you give some examples of things you didn’t understand?

**Comment by bhollis** [comment]
I'm going to close this for now - unfortunately it's infeasible to add tooltips to every part of the app. If there are specific things you find confusing, let us know and we can figure out a way to make them clearer.

**Comment by ausfestivus** [comment]
![dim-tooltips](https://user-images.githubusercontent.com/40222285/55142008-c2177080-518f-11e9-9d52-e1e53e5f94a4.gif)

Focusing on the new loadout optimiser for a second, when I look at the buttons available, it's not immediately clear to me what the meaning/purpose of the button is. Perhaps it's obvious to a regular DIM user or power user? eg the "Equip on <RACE> <GENDER> <CLASS>" buttons purpose is self explaining. The "New Loadout" button less so.

I have had a couple of incidents in earlier DIM use where I have clicked a thing and it has moved things around when I didn't want it to because I wasnt sure what would happen.

Reflecting on my earlier uses of DIM I guess I felt that there is a lot going on at first glance and its not immediately obvious as a new users where to go and what to do.

Even if there was something in the readme that listed some new user tips/steps I think it would smooth out the experience on first use.

**Comment by bhollis** [comment]
What help tip text would make the "New Loadout" button clearer?
