### ISSUE TITLE
Optimize loadouts based on weapon archetypes

### ISSUE THREAD

**Issue by ausfestivus** [DestinyItemManager/DIM#3672]
After a quick q in Discord about how to use the Loadout Optimiser I realised that it would be super double+ useful if we could somehow make it also optimise based on selected weapon archetypes.

You could have a dropdown at the top of the screen for each weapon slot that displays weapon archetypes available in each slot. You select the three you want and then click Build and it displays the list of builds best suited for maximising power.

Feasible?
Hopefully its not already there and ive just missed it.

**Comment by bhollis** [comment]
What would it mean for a build to be best suited to a weapon archetype?

**Comment by ausfestivus** [comment]
As a D2 player who likes using Kinetic hand cannons, energy auto rifles and heavy grenade launchers, I would like to optimise my armour loadout to use the pieces that have the best perks for my selected archetypes.

That explain it sufficiently?

**Comment by delphiactual** [comment]
What defines best for you may not be best for someone else who likes the same loadout... Scavenger vs. loader, etc

**Comment by bhollis** [comment]
Sorry, what I meant was, if I select “auto rifles”, what perks are best for auto rifles?

**Comment by ausfestivus** [comment]
Yea, best perks are very subjective but I would argue that there are some perks that are more useful in PvP vs PvE for example. Are some perks more suited for use with weapons with godrolls?

Consider a player who has the above mentioned weapon loadout. 
If the Optimiser displayed a recommended armour loadout to make the best use of the selected weapon archetypes this may mean the player PL can only get to ~640.
I can then remove the weapon archetype selection and see that actually, I can get my character PL to ~680 if I change
At that point I have enough information to make a decision about what gear I will run and what infusion choices give me the best bang for my core.
I can stick with my weapon choices but have a lower PL or I can change my weapon loadout to maximise my PL.

I totally accept there may be something about gear in Destiny I still havent full got my brain around so perhaps my ideas are not based on real or plausible circumstances. I dont know, feel free to correct.
