### ISSUE TITLE
DTR API causing DIM to look like it's taking forever refreshing

### ISSUE THREAD

**Issue by scorp508** [DestinyItemManager/DIM#3673]
The app loads once in Chrome, may refresh once, then any subsequent refresh hangs and the refresh button arrows stay white and spinning forever. To refresh my inventory I must refresh the whole webpage. The Android app is also affected. I must force quit the app and reload it to refresh my inventory.

**Comment by bhollis** [comment]
Can you open the developer tools page and screenshot what's there? Does your inventory show up at all?

**Comment by scorp508** [comment]
I assume you mean the F12 dev tools in the browser and not something else. Which area of the dev tools would you like? Elements, something else? DIM loads the inventory normally the first time and I can interact with it normally. It's later when DIM tries to refresh the inventory that DIM's white refresh arrows just spin endlessly. 

I just took the update to version 5.20.2.3026 and at this moment it isn't doing it. :) I'll keep an eye on it as I get some play time in tonight/tomorrow.

**Comment by 87c120aa** [comment]
I'm also using 5.20.2.3026, and the refresh button still begins to spin endlessly after a couple of minutes.

It seems like there are a pair of 502's for "https://db-api.destinytracker.com/api/external/reviews/fetch?platform=0&mode=0" and then a CORS error "No 'Access-Control-Allow-Origin' header is present on the requested resource".

If I manually refresh by clicking the already-spinning button it does refresh, but never stops spinning.

Here's a screenshot of the window, which I filtered to hide the repeated "Missing Item Definition:" errors I get. I can supply a saved log if you would like.

![endless-loading1](https://user-images.githubusercontent.com/46359360/55123692-f0d30f80-50d9-11e9-8684-472d2f65dd42.png)

**Comment by bhollis** [comment]
Ok that confirms what I was thinking. Inventory is refreshing fine, but then ratings are taking forever. It’s an issue with DTR.

**Comment by 48klocs** [comment]
It seems to be an intermittent problem with the ratings endpoint; I've reached out to the DTR people and they're looking in to it.

**Comment by bhollis** [comment]
Turns out it was a problem with our promise tracker that was triggered by the DTR failures. It's fixed now!
