### ISSUE TITLE
Blank page loadouts

### ISSUE THREAD

**Issue by Piratebnny** [DestinyItemManager/DIM#3675]
I get a blank page when I go to loadouts page. Was working earlier now it loads a blank grey page. Have to close window to get back to dim. Refreshing doesn’t work.

**Comment by Piratebnny** [comment]
I moved an item using inventory pages and tried using loadouts page afterwards and it worked again.

**Comment by Piratebnny** [comment]
Still having issues. Doing the above was not a permanent solution

**Comment by bhollis** [comment]
Hi @Piratebnny, can you open the developer console and let us know what you see there? I'm hoping there's an error or something that can help us track down what's happening.

**Comment by bhollis** [comment]
Any luck?

**Comment by Piratebnny** [comment]
[image: image.png]

**Comment by Piratebnny** [comment]
[image: image.png]

**Comment by delphiactual** [comment]
@Piratebnny no pics came through

**Comment by Piratebnny** [comment]
Terek Cope• Quality & Safety NorCal

tcope@vivintsolar.com • C: 301.646.8727• 

quality is not an act. it is habit • Vivint Solar

2510 Dean Lesher Dr, Concord, CA 94520

**Comment by Piratebnny** [comment]
Anyway you can check this reply through email? Not sure why my images aren’t coming through. I’ll have to copy paste when I get home otherwise.

**Comment by bhollis** [comment]
We cannot. Also I’ll remove your personal info from that comment.

**Comment by Piratebnny** [comment]
![unnamed](https://user-images.githubusercontent.com/49010660/55364305-00b17180-5495-11e9-9a1b-54e59be9f494.png)

**Comment by Piratebnny** [comment]
![Console error Loudout Optimizer page](https://user-images.githubusercontent.com/49010660/55364579-08bde100-5496-11e9-8ed6-fa1a09d93009.png)

**Comment by delphiactual** [comment]
D1 loadout optimizer

**Comment by Piratebnny** [comment]
What can I do to fix this?

**Comment by delphiactual** [comment]
Nothing notes for me for when I get home

**Comment by Piratebnny** [comment]
Looks like most of the loadouts optimizer page is working now except when you use the dropdown menu to select  Chest or ghosts. 

![Chest1](https://user-images.githubusercontent.com/49010660/55595991-5ab37080-56fb-11e9-8b20-bc15024f6376.png)
![chest2](https://user-images.githubusercontent.com/49010660/55595996-62731500-56fb-11e9-9d7f-1ab47ef825ad.png)
![Ghost](https://user-images.githubusercontent.com/49010660/55596002-67d05f80-56fb-11e9-9418-5990521ba3e9.png)

**Comment by Promehteus4th** [comment]
Clicking Loadout optimizer on the D1 manager still results in a blank screen.

**Comment by bhollis** [comment]
Should be fixed in Beta now.

**Comment by Piratebnny** [comment]
Loadout Optimizer page is working but now when trying to use the dropdown menu for the armor you want to select it blanks out.
![Drop Down list All classes](https://user-images.githubusercontent.com/49010660/55741666-af4c3980-59e2-11e9-9cb7-d3448dad52d8.png)

**Comment by delphiactual** [comment]
Click on the `Update DIM` notification and then report back

**Comment by delphiactual** [comment]
@Piratebnny ?

**Comment by Piratebnny** [comment]
Working Like a Charm. Thanks so much. :)
