### ISSUE TITLE
Let us have sub-vaults

### ISSUE THREAD

**Issue by MrSoundless** [DestinyItemManager/DIM#3676]
I've seen another issue similar to this but it seems to have ended with sorting features etc (this one: https://github.com/DestinyItemManager/DIM/issues/573)

**The problem**
I like to have 1 of each item in my vault. I don't use them, I just want to have them. There are also some items that I want to use often. Currently there is no way to separate those visually. It looks messy having everything in 1 vault.

**The solution**
Basically what I'm requesting is the ability to make 'sub-vaults'. It would look as if there is another vault (so another column with items).

- Sub-vaults can be renamed
- Sub-vaults can be created
- Sub-vaults can be deleted. When deleting, you can pick another sub-vault where you can move all items to.
- Sub-vaults can be reordered
- There is always 1 sub-vault that is the default. This one can't be renamed or deleted.

I hope I've been clear in my explanation. Thanks for reading.

**Comment by Mijago** [comment]
"Currently there is no way to separate those visually"
- Well, you can mark the items you use often using the tags and then filter them out:
![image](https://user-images.githubusercontent.com/3903469/55277064-248d7f80-52fc-11e9-9ceb-5d56d2b68782.png)

Also, you can filter out any duplicates:
![image](https://user-images.githubusercontent.com/3903469/55277069-33743200-52fc-11e9-9f53-4fd2a8c54205.png)

**Comment by MrSoundless** [comment]
That's not the same. It looks messy. Also: no custom tags. This is more of what I meant:
![image](https://user-images.githubusercontent.com/770063/55277223-e85b1e80-52fd-11e9-8752-3e5ee7e1f024.png)

**Comment by MrSoundless** [comment]
Maybe a dropdown to switch vaults even:

![image](https://user-images.githubusercontent.com/770063/55277605-881aab80-5302-11e9-991a-49fd1fa5ba76.png)

So basically like loadouts, but instead of selecting/equipping items, your vault shows different items. There would also be an option with'All' so that you can just ahve all items on screen, which would be like how it is currently.

**Comment by bhollis** [comment]
Hi @MrSoundless, thanks for the suggestion and all the additional detail. Unfortunately this isn't the direction we want to take DIM in, so we won't be implementing this particular suggestion. Please feel free let us know if you have any other ideas for DIM!
