### ISSUE TITLE
Life Exotic Perk not recognized in Loadouts.

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#370]
https://www.reddit.com/r/DestinyTheGame/comments/41lbrt/dim_v32_released/cz3ciul

**Comment by SunburnedGoose** [comment]
Item hashes w/ the perk 
"2300914894", "2300914893","2300914895",
           "2820418555","2820418553","2820418552",
           "2122538505","2122538506","2122538504",
           "2300914892", "2122538507", "2820418554"

**Comment by bhollis** [comment]
Might as well just look for the perk itself.

**Comment by SunburnedGoose** [comment]
Some have it as a hidden perk :/

**Comment by bhollis** [comment]
😤
