### ISSUE TITLE
Loadouts not showing

### ISSUE THREAD

**Issue by Alkouzne** [DestinyItemManager/DIM#3701]
All loadouts not showing after the update. They are there (have the GoogleDrive sync on)  coz when i try to create a loadout with the same name as the one that is not showing ,it tells me  that loadout with that name exists and I can edit the loadout that's not showing! I've fount them on my phone but they disappeared as soon as I updated the app on my phone as well.  Tried relogging, reloading the app, rebooting the PC, clearing all cache and data, IE is not supported so i couldn't check other browsers.

**Comment by kyleshay** [comment]
#3703
