### ISSUE TITLE
Lightweight & Aggressive Burst Pulse Rifles end up in same comparison

### ISSUE THREAD

**Issue by darkelement1987** [DestinyItemManager/DIM#3702]
**Steps to reproduce:**

1. Click any aggressive/lightweight pulse rifle
2. Click compare button
3. Click archetype

![image](https://user-images.githubusercontent.com/21128187/55339204-84258f80-54a2-11e9-969c-d6671ed01859.png)

I think archetype comparison should be based of intrinsic perk

**Comment by bhollis** [comment]
It really should. Right now it’s just by RPM.

**Comment by duckmanBR** [comment]
The problem on doing by intrinsic perk is that it will exclude exotics (that could have the same rpm/impact of the archetype).

**Comment by kyleshay** [comment]
Hmm, good point— we could do it by the intrinsic perk, unless it's exotic (fallback to rpm)
