### ISSUE TITLE
Suggestion: Better CSV Exports

### ISSUE THREAD

**Issue by Korrasera** [DestinyItemManager/DIM#3705]
The CSV exporter dumps all of an items perk-like attributes into a single unordered perk list. The perks listed in the CSV report include the type of armor, the stat modifier perks, shader, ornament, and even the mod alongside the perks themselves. Furthermore, it doesn't differentiate between items that can roll enhanced perks and thus have three choices for column one perks and those that don't. As a result, the perk fields are disorganized and you can't filter on column two armor perks, like scavenger and resources, without editing the CSV.

My suggestion is to update the CSV exporter to break out all of these items out into their own planned columns.

Instead of this:

Perks 0,Perks 1,Perks 2,Perks 3,Perks 4,Perks 5,Perks 6,Perks 7,Perks 8,Perks 9,Perks 10,Perks 11,Perks 12

It should look like this:

Armor Type,Masterwork Rating,Shader,Ornament,Mod,Stat Mod 1, Stat Mod 2,Perk 1A,Perk 1B, Perk 1C,Perk 2A,Perk2B

I haven't reviewed the code for the CSV exporter myself, but I'm guessing that the current state is due to the API dumping out this data in an unorganized way. Since DIM already interprets the API data and can differentiate between perks and shaders and mods and what not, this seems like a reasonable change request.

**Comment by delphiactual** [comment]
Dupe #3513

**Comment by Korrasera** [comment]
@delphiactual, thanks, I hadn't found #3513 because I was focused on looking for CSV stuff.
