### ISSUE TITLE
Cannot Load Inventory or any other page

### ISSUE THREAD

**Issue by Piratebnny** [DestinyItemManager/DIM#3706]
DIM doesn't seem to be working right now. 
![DIM not loading](https://user-images.githubusercontent.com/49010660/55452280-cc6cac80-558b-11e9-8583-fded5437bbc6.png)
![DIM not loading](https://user-images.githubusercontent.com/49010660/55452299-ee662f00-558b-11e9-8fe9-17348bfe6222.png)

I have tried logging into my characters individually and going to tower and checking vault manually. Is this a bungie.net issue Ishtar legacy not working either?

**Comment by bhollis** [comment]
The API is down for Destiny 1 right now. We don't know when it'll be back.
