### ISSUE TITLE
Pulling material from postmaster locks up Chrome

### ISSUE THREAD

**Issue by patchm00** [DestinyItemManager/DIM#3708]
This has happened since the latest update.  I have tried it on two computers with same result.  I know it happens when Baryon Bough is in the postmaster, not seen any other mats in there yet to try.  If i click on that material in the postmaster in DIM and click Store (or Vault) the page freezes and i have to close it and reopen.  FYI, pulling other items from the postmaster (weapons/armor) work fine.

**Comment by wein3967** [comment]
This happened to me as well when trying to pull Iron Banner medallions from the Postmaster (regardless of the destination location, store/vault).

**Comment by Promehteus4th** [comment]
Locks out on Chrome and Microsoft Edge, idk the workaround other than manually going to postmaster.
![DIM_PostmasterPull_bug](https://user-images.githubusercontent.com/49326366/55660381-0a5c1180-57d4-11e9-8285-1370ac8d49b1.JPG)

**Comment by bhollis** [comment]
I'm afraid I need more info to reproduce this. Can you show a screenshot of your postmaster AND your consumables inventory AND vault?

**Comment by bhollis** [comment]
For reference, I've tried pulling Iron Banner tokens, into a consumables bucket that already has some, which is also full. It worked OK, so there must be some other trigger condition.

**Comment by Promehteus4th** [comment]
Zip file attached with several screenshots of my DIM page.

**Comment by bhollis** [comment]
Sorry, you can't attach files from email to GitHub.

**Comment by Promehteus4th** [comment]
[DIM_Bug.zip](https://github.com/DestinyItemManager/DIM/files/3051109/DIM_Bug.zip)
 hope this works

**Comment by bhollis** [comment]
Great, that's helpful. Now, exactly what do you click that that makes it lock up?

**Comment by bhollis** [comment]
And just to confirm, what version of DIM are you using?

**Comment by Promehteus4th** [comment]
Version 5.22.0
Im clicking on 'Collect Postmaster' under my warlock tab 
![postmasterrrr](https://user-images.githubusercontent.com/49326366/55677727-f6d7a600-58ba-11e9-811e-5e5a786ae17b.JPG)

**Comment by bhollis** [comment]
Hmm, I've replicated those conditions and it works OK for me.

**Comment by bhollis** [comment]
OK awesome, I've got it reproduced. I'll be able to fix it now.

**Comment by bhollis** [comment]
Go ahead and give it a shot in Beta in about 5 minutes.

**Comment by Promehteus4th** [comment]
Works in the beta, thanks man!
