### ISSUE TITLE
Best path infusion doesn't always pick a great path

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#372]
![image](https://cloud.githubusercontent.com/assets/313208/12505948/e5711c68-c09f-11e5-8248-c8066943ba25.png)

Check it out - it decided I should infuse a 299 after a 300.

/cc @cdacamar

**Comment by bhollis** [comment]
Also, I had a lot more infusable items available, but after clicking "maximize defense", they're all gone. Clicking on the selected helmets to deselect them results in all kids of weirdness.

**Comment by cdacamar** [comment]
To answer your first question. The order of the 300 and the 299 doesn't matter in this particular case since it will make the 4 point jump to 303 if it was 299 or 300. The fact that it decided to infuse in that order is because of when the algorithm saw the 303 helmet.

To answer your second question. What kinds of weird behavior are you seeing? Could you post a gif?

**Comment by bhollis** [comment]
The behavior I was seeing was "random" items reappearing each time I clicked to remove an item from the infusion path. This was me not understanding the UI - it's removing anything that's too low-light to be used, and putting them back when the light goes down. I think I'm going to try some different options for disabling items rather than removing them, so this behavior is clearer.

**Comment by cdacamar** [comment]
A really quick way of making it so that items aren't removed from the view would be to change [this](https://github.com/DestinyItemManager/DIM/blob/dev/app/scripts/infuse/dimInfuse.factory.js#L98) from:

```javascript
          _data.view       = []; // there are no other options
          _data.targets    = max.path;
          _data.infused    = max.light;
          _data.difference = _data.infused - _data.source.primStat.value;
```

to:

```javascript
          _data.targets    = max.path;
          _data.infused    = max.light;
          _data.difference = _data.infused - _data.source.primStat.value;
```

ie, remove the view changes and keep all the same items in view.
