### ISSUE TITLE
Filter dropdown items cannot be selected in Chrome

### ISSUE THREAD

**Issue by M-a-i-a** [DestinyItemManager/DIM#3728]
It used to be possible to select (by clicking) filter items from the "?" dropdown. Has not worked for some time in Chrome. I can select the filter text and then pasted it in the filter box, but that is not convenient and does not help if I want to combine several filters
My Chrome version: Version 73.0.3683.86 (Official Build) (64-bit)

**Comment by delphiactual** [comment]
Dupe #3295
