### ISSUE TITLE
mods don't change hidden weapon stats

### ISSUE THREAD

**Issue by spnkr** [DestinyItemManager/DIM#3738]
if you have a targeting adjustor mod on a weapon, the aim assist stat doesn't change. if you have a counterbalance mod on a weapon, the recoil direction doesn't change.

I took a look at `d2-item-factory.service.ts`, where on line 645 it says `// only aim assist and zoom for now`, and I think this is where to start on this. Anyone have any ideas on how to fix this?

**Comment by philkernick** [comment]
I think that the effect of mods should be shown in a different color (a bit like how masterwork is shown).

**Comment by bhollis** [comment]
When you say mods, do you mean mods, or mods and perks?

**Comment by philkernick** [comment]
Mods.  For example Counterbalance is +15 to recoil direction.  This isn't shown anywhere in DIM.  If I look at my Erentil is shows recoil direction of 70 (which is the weapon base), not 85 which is the effect of the mod.

**Comment by bhollis** [comment]
Got it. That seems possible!

**Comment by delphiactual** [comment]
closed by #4159, enhanced by #4193
