### ISSUE TITLE
Compare tool can't highlight item when item is on out-of-view character

### ISSUE THREAD

**Issue by NoCodeLeftBehind** [DestinyItemManager/DIM#3745]
The item finder option that comes up in the compare tool used for comparing multiple rolls of the same gun does not properly locate and highlight/popout weapons that are not on the currently in-view character/vault on Chrome for Android phone (on phone screen portrait mode only one character/vault is in view at once, have to scroll over to others). Instead, each time you press the finder option for a roll not on that character/vault, it just jumps the view to some random place farther down the same character view (i.e. in armor). It seems like it isn't changing the view to the correct character/vault where that weapon exists. I believe it does work correctly on my iPad.

**Comment by bhollis** [comment]
Hmm, I’m not sure I understand- the compare tool doesn’t have an item picker yet. Could you send a screenshot or video of what you’re looking at?

**Comment by duckmanBR** [comment]
@bhollis , he's referring to the :mag: 
It doesn't work on mobile, because it does't change the column/store.

**Comment by bhollis** [comment]
Oh, right. That’s true.

**Comment by NoCodeLeftBehind** [comment]
Yep, the magnifying glass thing is what I mean. If the weapon roll you select that for is on the character column (?) That is currently displayed on screen, then it moves the view to that weapon and highlights it by making it pop out briefly. But for rolls elsewhere (not on the current column in view), it just kinda freaks out and moves the view somewhere else within the same character column. It will be keeping moving it every time you press the magnifying glass but never actually find the weapon and show it to you in the other character/vault column that is off screen.
