### ISSUE TITLE
DIM Beta stopped working (Grey screen) on both mobile/pc

### ISSUE THREAD

**Issue by darkelement1987** [DestinyItemManager/DIM#3758]
Google Chrome | 73.0.3683.103 (Officiële build) (64-bits) (cohort: Stable)
-- | --
Revisie | e82a658d8159cabbd4938c1660f9bb00b4a82a23-refs/branch-heads/3683@{#902}
Besturingssysteem | Windows 10 OS Build 17134.706

Problem only occurs on BETA atm.

![image](https://user-images.githubusercontent.com/21128187/56132073-5e5fb680-5f89-11e9-93ce-066c6306cc84.png)

![image](https://user-images.githubusercontent.com/21128187/56132095-66b7f180-5f89-11e9-8a58-ca891c43fff9.png)

![image](https://user-images.githubusercontent.com/21128187/56132107-6ddeff80-5f89-11e9-99c2-f0c1fb1ab36f.png)

**Comment by duckmanBR** [comment]
https://sentry.io/organizations/destiny-item-manager/issues/985897700/?project=279673
