### ISSUE TITLE
Missing items on Collections

### ISSUE THREAD

**Issue by duckmanBR** [DestinyItemManager/DIM#3766]
Reported on Discord and I reproduced.

We aren't listing all the items on the collections page.  It's not the API because the official companion and other sites are showing them ok.

Companion x DIM
![image](https://user-images.githubusercontent.com/32077894/56298494-9e997300-6108-11e9-9370-f6fbdbdb1771.png) ![image](https://user-images.githubusercontent.com/32077894/56298566-bc66d800-6108-11e9-8b46-94b96aa4e6e6.png)

PS: I could swear that yesterday Beta was showing more items than prod (but still far from complete), but I didn't save a screenshot.  Today both are equally wrong.

EDIT: 
Huge guess, but I think that we're showing only not collected and collected with random rolls.  If a item collected doesn't have random rolls we don't show.
How I got this:
- On the exotic weapons I'm seeing only what I don't have.
- On "normal" sidearms, I can see 18 Kelvins as not collected, but Vestian Dynasty, a y2 weapon **without** random rolls (that I have on my inv right now waiting to be dismantled), doesn't show up...

**Comment by bhollis** [comment]
I think you’re right. I fixed a crash that happened after the latest manifest that must have also removed those.

**Comment by bhollis** [comment]
Hmm, and now they're showing again. I'm going to chalk it up to Bungie releasing a bad manifest and then fixing it in an update.
