### ISSUE TITLE
Add 'Source' column to export spreadsheets

### ISSUE THREAD

**Issue by rowanbrendan** [DestinyItemManager/DIM#3769]
Year, season, and event are included but I'd also like to see the source of the gear as well, e.g. Iron Banner, Eververse. Currently you can filter through items with the 'source:' filter in the app itself, but I'd like to see that extended to the spreadsheets as well.

**Comment by delphiactual** [comment]
Source would be exported as a hash, not something readable...

**Comment by rowanbrendan** [comment]
That works too

**Comment by rowanbrendan** [comment]
Worth doing the conversion if possible though? https://github.com/DestinyItemManager/DIM/blob/acb8c0cc37e57bb6db467ab22fa46605984fa964/src/app/search/search-filters.ts#L469

**Comment by delphiactual** [comment]
I know where it is, that is my section of code... I do not want to maintain this list in multiple locations...

**Comment by bhollis** [comment]
We could invert that map in code at the point of generating the spreadsheet to provide readable labels. I was hoping this was a PR and not an issue though ;-)

**Comment by sundevour** [comment]
![image](https://user-images.githubusercontent.com/31990469/58761176-16273400-84f6-11e9-9a15-bc9163da4757.png)
this is preliminarily implemented, but involves relocating `D2Sources` from `search/search-filters` to `inventory/d2-source-info`

does this sound reasonable?

**Comment by delphiactual** [comment]
@sundevour you should exclude `raid` as a source, and show the correct raid source, `Bladesmith's Memory Vest` comes from Scourge, which it should have as a source as well
