### ISSUE TITLE
Option to hide year 1

### ISSUE THREAD

**Issue by pasadinhas** [DestinyItemManager/DIM#378]
It would be great if we there was a checkbox that allowed us to hide/show Year 1 weapons and armour. I'm keeping a lot of Year 1 stuff that I don't really want to move around but they make me slower when looking for items from Year 2.

**Comment by bhollis** [comment]
In search, type "is:year2"

**Comment by bhollis** [comment]
You can also choose to sort by primary stat, and year 1 stuff will sort to the bottom.

**Comment by pasadinhas** [comment]
I do have primary stat sort but it didn't solve it for all items (for example the Hothead has a really low attack). I activated the option to hide unfiltered items (which I didn't have active before) and now the is:year2 does the trick! Thanks!
