### ISSUE TITLE
Firefox Collections Incomplete

### ISSUE THREAD

**Issue by hollandwl** [DestinyItemManager/DIM#3780]
In Firefox, selecting Collections -> Exotic -> Weapons (or Armor) only shows a small portion of possible items.  In Edge all possible items are shown.

**Comment by duckmanBR** [comment]
Beta (blue icon) or Prod (orange icon)?
Are you sure you have the last version on both?

**Comment by hollandwl** [comment]
Orange icon v5.25.0 (release) on Firefox
Orange icon v5.25.0 (release) on Edge

Updating to 5.25.0 on Edge broke it

**Comment by duckmanBR** [comment]
Yes, prod is broken.  
It's fixed on Beta (beta.destinyitemmanager.com).  It should go to prod on monday.

**Comment by hollandwl** [comment]
Thanks
