### ISSUE TITLE
Safari iOS Safe Areas not being respected - Side menu

### ISSUE THREAD

**Issue by davidc14** [DestinyItemManager/DIM#3794]
When viewing DIM on an iPhone X, in landscape mode, the notch cuts into side menu. 
[https://imgur.com/qHsyGIV](url)

To repro:
- Launch app on iPhone X/Xs Max/Xr
- Auth if required
- Rotate to landscape such that the notch is on the left of the screen
- Open the sidebar menu 
- Observe the menu options are obscured by the notch

Expected result: the side menu should be positioned in such a way that it does not intersect with the notch.

Not tested: notches/cutouts on Android devices.

**Comment by bhollis** [comment]
Ah, fair enough. I never use landscape mode.
