### ISSUE TITLE
"Refresh Destiny Data" blocks entire UI

### ISSUE THREAD

**Issue by berkus** [DestinyItemManager/DIM#3797]
* The "Refresh Destiny Data" button works automatically (I do not know what triggers it, but most of the time it's spinning doing some updates).
* While "RDD" is updating, the entire UI is blocked and unresponsive.

This makes using DIM very hard - any action has to wait 5-10 seconds for RDD to stop refreshing, then i click the button and wait again, because it's refreshing something else.

Browser: Firefox Nightly 68.0a1 (2019-04-27)

**Comment by bhollis** [comment]
It refreshes data automatically every 30 seconds, but I’ve never seen that cause it to hang. Does this also happen on release Firefox or Chrome?

**Comment by berkus** [comment]
It happens less on release DIM, in beta.DIM it seems worse. Will check with release Chrome.

**Comment by berkus** [comment]
In Release Chrome the background update is happening in background and does not block the UI.

Will test with release Firefox now.

**Comment by bhollis** [comment]
Cool. Let me know if it continues to be a problem in release browsers.
