### ISSUE TITLE
Refresh Timer

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#380]
Users are asking why the refresh timer was removed.  DIM will refresh when the tab has focus, but what happens if you never leave the tab for a match or two?  You have to manually sync by pressing the button.  

I recall it being mentions, but what was the reason for removing the sync interval and timer?

**Comment by bhollis** [comment]
There should still be a refresh timer, it wasn't removed. The tab switch
refresh was in addition.

**Comment by bhollis** [comment]
I did a quick check and the code is still there and being called: https://github.com/DestinyItemManager/DIM/blob/dev/app/scripts/shell/dimAppCtrl.controller.js#L218

**Comment by bhollis** [comment]
I've verified that the timer is still working - those users are probably getting hit by the inactive-user detector, or they expect it to refresh more often than every 6 minutes, which is what it's set to.
