### ISSUE TITLE
keyboard shortcuts for labeling failing on second item

### ISSUE THREAD

**Issue by javalasers** [DestinyItemManager/DIM#3806]
Steps to reproduce:
  * Click on a weapon. [that weapon's info popup appears]
  * Press # to mark as junk.
  * Click directly on a different weapon. [that second weapon's info popup appears as expected]
  * Press # to attempt to mark as junk. <-- Does not work

In order to reactivate the label-marking keyboard shortcuts, I appear to need to click elsewhere to get rid of the first item's info box. Then, clicking on any item and attempting to use labeling shortcuts will work again. I first noticed this perhaps 1-2 months ago. Thanks as always!

**Comment by bhollis** [comment]
Thanks for the report! This'll be fixed in tomorrow's release.
