### ISSUE TITLE
Weapon ornaments and Ghost projections don't get marked as collected

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#3811]
In the Eververse vendor section, neither ghost projections nor weapon ornaments get the blue "in collections" tick.  Instead they are faded.  This is inconsistent with the emotes, where they are both faded and get the blue tick.

![image](https://user-images.githubusercontent.com/25425159/58002434-852b8280-7b1d-11e9-967e-46273388e8c5.png)

**Comment by duckmanBR** [comment]
They're not present in the Collections so our method of cross checking fails.

I'm not familiar with the code for this, but if the image comes faded from the api (with no flag/parameter to inform this difference) we couldn't do nothing.
But if the API returns some kind of info, we could (and I'm just conjecturing) mark with the blue :white_check_mark: if faded.

**Comment by bhollis** [comment]
Yeah, unfortunately this is just what the API returns - we get a collectible state for some items, but apparently not these others.

**Comment by bhollis** [comment]
I found these - they're in profile/character plugsets.
