### ISSUE TITLE
Loadout optimizer not loading

### ISSUE THREAD

**Issue by Dvnoten** [DestinyItemManager/DIM#3813]
Hi guys, 

First question ever asked on Github. But I started using DIM especially for the Loadout Optimizer. 
Unfortunately whatever browser I use (Edge, Chrome, Firefox) it keeps loading and even after hours of loading screen I still cannot do anything. I tried to empty cache in all these browsers, tried to use incognito, sync with google drive... Nothing is really helping. Somebody here with some more advise? 

Kinds regards,
Dieter

**Comment by duckmanBR** [comment]
Our loadout optimizer is far from perfect, but we just (today actually) released a new version of it on beta.destinyitemmanager.com.

**Comment by Dvnoten** [comment]
Hey! Yes works like a charm now (loading is very fast now).
Great work, thank you!
