### ISSUE TITLE
Y1 masterworked armor showing multiple mobile/heavy/restorative options

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#3815]
I know you can change the masterwork on Y1 armor, but:
(a) it only ever shows 2 options, not 3;
(b) it isn't consistent, because some masterworked armor shows only 1.

I think it should only show the current armor type (like all Y2 armor does).

Examples:

![image](https://user-images.githubusercontent.com/25425159/58068764-d5fcb300-7bd1-11e9-9115-4d8b196d38be.png)

![image](https://user-images.githubusercontent.com/25425159/58068780-e6ad2900-7bd1-11e9-9b20-d0c876c9ba59.png)

![image](https://user-images.githubusercontent.com/25425159/58068797-05abbb00-7bd2-11e9-9768-2e16bb99444c.png)

![image](https://user-images.githubusercontent.com/25425159/58068806-0e9c8c80-7bd2-11e9-9d7d-0f504ba0a6fd.png)

**Comment by bhollis** [comment]
Sorry, I'm not quite following what you're showing me in that screenshot. What exactly isn't correct?

**Comment by philkernick** [comment]
First column under armor perks.

Boots of Sekris are showing as both restorative armor and heavy armor.  Seems random whether it shows one or two options (not consistent for boots, not consistent for warlock, etc).
