### ISSUE TITLE
Loadout Optomizer layout doesn't flow correctly

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#3817]
I have a Y1 Solstice armor piece that has only 1 selectable perk.  In loadouts this gives a base power of 624.  When I slide the minimum power slider to 700, this piece is replaced by a Y2 armor piece that has 3 selectable perks.

This causes the ghost to be wrapped down into the next row.

https://drive.google.com/file/d/1ij5PlMB11xylMSI2nPyhGGdvyIQjBQaM/view

**Comment by bhollis** [comment]
Unfortunately this is tricky since it's not a normal layout - it's a special virtual scroller where each row needs to be precalculated ahead of time. I'll see what I can do. In the meantime, what's your screen size?

**Comment by philkernick** [comment]
Screen is 2560x1440.

**Comment by philkernick** [comment]
Confirmed this now fixed in Chrome on Windows 10.
