### ISSUE TITLE
Loadout Optimizer choose an item picker should sort by power then armor slot

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#3819]
The item picker is sorted only by power, This makes it hard to easily see the items to select.

I suggest either:
(a) slot then power (all helmets by power, then all arms by power...);
(b) power then slot (all 700 by slot ...)

**Comment by bhollis** [comment]
It's actually sorted by whatever you've chosen items to be sorted by. But I understand that may not always be appropriate for this.
