### ISSUE TITLE
suggestion: move item from compare screen

### ISSUE THREAD

**Issue by michabbb** [DestinyItemManager/DIM#3833]
![image](https://user-images.githubusercontent.com/3524595/58313191-42afc180-7e0d-11e9-96c2-4a33e3786bd2.png)

it would be amazing if i could move an item from the compare screen , finding the item by the "
magnifying glass" icon works, but if i want to move more than one item, it´s not usability friendly.
i cannot intertact with an item as long as i am in the compare screen.

so ususally you compare your items, pick one you love most and move it to your actitve char.
would love to see that !

so, something like this:

![image](https://user-images.githubusercontent.com/3524595/58313553-23fdfa80-7e0e-11e9-891a-a113641bfaf9.png)

thanks!

**Comment by bhollis** [comment]
Folding this into Vault Organizer

**Comment by michabbb** [comment]
@bhollis pardon, I don't understand your comment
