### ISSUE TITLE
Loadout Optimizer: Left-hand perk menu bugs

### ISSUE THREAD

**Issue by DHager** [DestinyItemManager/DIM#3842]
There's some bug involving selecting exotic perks for multiple slots, and then de-selecting them from the left-hand sidebar. The exotic-perk icon is removed but gets replaced by something else, which has allowed me to amass a selection of 8 Fusion Rifle Scavenger perks.

**Comment by bhollis** [comment]
I'm afraid you'll have to give me more to go on than that. You might also want to wait until #3841 lands since it drastically changes how perk selection works.

**Comment by bhollis** [comment]
Take a look at Beta and let me know if this still happens.
