### ISSUE TITLE
Feature Request: Vault "Pages"

### ISSUE THREAD

**Issue by SahandJ** [DestinyItemManager/DIM#3845]
Hi. I was wondering if it would be possible to add "Vault Custom Pages". Obviously we have Loadouts and a pretty decent search bar, however I feel like having dedicated pages which we can have items in would be very handy.

For instance, the first page could be "All", which would be the same as it is now: All available items. I click "Create new page"<sup>1</sup>  and enter the name "Gambit & Reckoning". Now I can "copy" the items over to the new page and whenever I click on it, only those items are visible to me. No need to search and have it highlight / darken all other items. I could also make a page dedicated for PvP. So I can see all of my favorite PvP items in my vault without having to check loadouts or actually equipping them.

As mentioned, this would be different from loadouts as it in essence is just a pre-made filter with custom items. 
I do work as a developer, however I only have experience with back-end and python for ml/ai, and couldn't figure out where I should start to even add such a functionality.

Thanks for reading my post. Please tell me what you think.

Footnotes:
1: Another option instead of creating pages at will, each user would have 5 pages in total, where 4 of them are empty until they are populated.

**Comment by bhollis** [comment]
Hi @SahandJ, thanks for the suggestion! We've discussed very similar requests before, and ultimately decided that we didn't want the complexity this would bring to the app. Keep us in mind if you have any other ideas though.

**Comment by SahandJ** [comment]
:( Okay... 

I mean, if it's done well it shouldn't make the UI any more complex than it already is. 
I would do it myself, but I don't know TypeScript and its so hard for me to understand where to start and what to change just to add a simple button to test things with...
