### ISSUE TITLE
errors Equipping armor from loadout builder

### ISSUE THREAD

**Issue by jbanks6711** [DestinyItemManager/DIM#3851]
every time I try to pick the perks and equip in either beta or normal I get error pops that say can't find a piece of gear to unequip. sometimes it's what was in the loadout builder all charters no matter what. 
<img width="1680" alt="Screen Shot 2019-05-30 at 2 18 19 PM" src="https://user-images.githubusercontent.com/16421153/58662106-a3943980-82e6-11e9-84af-a31b6b6fa95e.png">

**Comment by delphiactual** [comment]
Press F12 and post the console logs too

**Comment by jbanks6711** [comment]
nothing to post app is not crashing. just not equipping. it did before the latest update.

**Comment by bhollis** [comment]
I think this is related to the stores not reloading. I can dig into it this weekend.

**Comment by jbanks6711** [comment]
Thank you
