### ISSUE TITLE
please remove those intrusive ads/aids

### ISSUE THREAD

**Issue by clutchmaster420** [DestinyItemManager/DIM#3861]

**Comment by clutchmaster420** [comment]
im sick and tired of having to block them each time i launch the freaking app u dont need money with these pornographic ads u keep puttting in this

**Comment by kyleshay** [comment]
This is a short-lived promotional campaign running up to GuardianCon that will be ending June 26th. We've updated the graphic to flow better with the DIM UI. Thanks for your support and understanding.
