### ISSUE TITLE
bug? chrome: install dim as app, app-updates are not permanent

### ISSUE THREAD

**Issue by michabbb** [DestinyItemManager/DIM#3863]
hi there,

it seems like, this is chrome "thing", but i don´t know, maybe it has something todo with the app itself. when i install DIM as app (windows chrome or android chrome) - i permanently get the info to "update DIM", if i do, close the app, start the app, i see the old version and the notice again to update. 

it looks like, when chrome installs an app, the app data does not get updated permanently,
it´s more like using a docker container, you can do what you want, after a restart, you have
your initial app state 😕 

thanks for any help!

**Comment by bhollis** [comment]
The chrome extension is nothing more than a link to the public website. There’s no difference from just typing in the URL.

**Comment by inexorableAce** [comment]
I think they referring to installing it as a desktop PWA from chrome.

**Comment by michabbb** [comment]
@bhollis i don´t think so. i don´t really know what happens, when you "install that app". maybe it´s like @inexorableAce says: there gets really something stored on your device, and this store **does not** get updated, when you click on "update DIM".

on windows, you get a new symbol in your taskbar, on android, you get the app-icon on your homescreen. when you start both, you don´t see your full chrome, you see only the framework of chrome as a runtime-engine. 

i don´t know where chrome stores its data in that case and why it does not get updated 😕

**Comment by bhollis** [comment]
It's storing its data in the same place as other apps. Generally if you can't update, it means you have a tab open somewhere else. Make sure to close all tabs.

**Comment by michabbb** [comment]
Nope, no other tab (with dim), I will make a video to proof.

**Comment by michabbb** [comment]
@bhollis what you see here: open the "installed as app" dim from my android home screen, do an update, wait, close (and kill) the app/chrome, start the "installed as app" dim again. As you can see, it shows me again, that an update is available.

Before you ask, I use the canary version of Chrome, because, whyever, the connection to Google drive is not working for me in the regular one. 

https://youtu.be/j2qDVqKUeFI

**Comment by bhollis** [comment]
I’ll have to take your word for it since I don’t have an Android phone. If service workers or caches don’t update on Chrome Canary for installed apps, that sounds like a bug report against chrome is in order.

**Comment by michabbb** [comment]
@bhollis to be sure, i will test this with the stable chrome, too (updates will follow)

**Comment by michabbb** [comment]
@bhollis may i ask: what exactly happens when i "do the update" ? i understand that the browser caches a lot of stuff. is your "update" nothing more than a "forced reload" or does there happen something more special in the background ?

**Comment by bhollis** [comment]
It activates the new service worker that has installed and cached new files in the background, then reloads the app.

**Comment by michabbb** [comment]
It seems to be related to Chrome canary version, I tested the last update on Android, stable Chrome, and the update notice is gone. I still need to test on windows, will let you know.

**Comment by bhollis** [comment]
That’s right, DIM is not supported on beta or canary browser versions. If there’s any issue in those browsers it’s best to file a bug against the browser.

**Comment by michabbb** [comment]
some stupid chrome extension seems to make problems with the gdrive connection, i am not able to connect, it will take awhile to find out, which of my 25 extensions causes this problem 🙈  the reason why i use canary (without any extension) only for DIM. i close this for now, because i believe this is really a canary only problem. sorry for the inconvenience. 😕
