### ISSUE TITLE
Bounty based Loadouts

### ISSUE THREAD

**Issue by CTOverton** [DestinyItemManager/DIM#3868]
Getting back into destiny 2 has been nothing short of overwhelming, but in a good way. With so many bounties it's often hard to sort through them and pick what to do. Something I thought might be useful though is just simply having DIM suggest which items or classes you should run based on your current bounties. 

For example: If you had a bounty for getting hand cannon kills DIM could suggest using a hand cannon.

Then just taking into account more and more bounties so it can give you a full list of possible loudouts and related bounties.

----
As a developer myself I might have some extra time on my hands so let me know if anyone finds this idea useful or if anyone more experienced with DIM would like to work on it. I'd be happy to help or potentially work on it myself.

**Comment by bhollis** [comment]
Thanks for the suggestion!

The tough part here is that DIM has to work for all languages. So you can't just go by whether the description contains "hand cannon" or something. We'd need to have a job that builds a mapping from the pursuit and perk item hashes to what things they apply to.

**Comment by CTOverton** [comment]
Mmmhhh true... But when getting the data from the api can't you specify a language? 

I.e. you could get the data from say english and use that to determine the recommended loadouts.

**Comment by bhollis** [comment]
No, that's not how it works. The live API data gets cross referenced with a big database of items, which is only in one language. We wouldn't want to load the database in both the local language and English.

**Comment by CTOverton** [comment]
Ahh okay I gotcha

**Comment by CTOverton** [comment]
@bhollis how would I get the database of progressions so that I can use the hash codes to get the actual bounties and their requirements? First time using the bungie api and I'm confused on where I get the actual data to cross reference the hash code with.

**Comment by kyleshay** [comment]
@CTOverton, checkout the discord channel for dev questions: https://discord.gg/UK2GWC7
