### ISSUE TITLE
Mods appear to be breaking B-44 wish list items

### ISSUE THREAD

**Issue by 48klocs** [DestinyItemManager/DIM#3871]
As reported over on Discord (and I can see in beta), it appears that having a mod equipped is breaking wish lists for Banshee-44 items.

It's supposed to be intentionally ignoring perks thought to be associated with cosmetics, mods, and masterworks.

**Comment by bhollis** [comment]
What does it mean to be breaking wish lists?

**Comment by 48klocs** [comment]
It's not crashing or returning any console errors, it's just not marking an item that it should (in the case when there's a mod attached).

I haven't had time to see if B-44 lookups for items without mods are failing to mark results as well.

Wish list lookups for expert mode wish list items still appear to be working normally.
