### ISSUE TITLE
Ratings are not showing ps4 destiny 2

### ISSUE THREAD

**Issue by mainardgcrebs** [DestinyItemManager/DIM#3875]

**Comment by bhollis** [comment]
Ratings were reset for the Season of Opulence.

**Comment by mainardgcrebs** [comment]
I can no longer drag items around as I could before. I even changed to
updates Firefox?



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
06/09/19,
6:24:43 PM
