### ISSUE TITLE
Request: "Ignore Mobility/Resilience/Recovery" option in loadout builder

### ISSUE THREAD

**Issue by DHager** [DestinyItemManager/DIM#3883]
Even when fully specifying perks, the result-set is full of combinations which are identical except for how MRR is set. These are difficult to browse and can push other combinations the user may be more interested in off the end of the page.

Personally, I seldom try to micromanage MRR, and would appreciate being able to "opt out" of that aspect.

**Comment by bhollis** [comment]
The stat mix is actually the core of how the loadout optimizer is designed and built. If we were to remove that, you'd end up with just a single row and that wouldn't be super helpful.

I think you're probably using the loadout optimizer for something slightly different from what it's intended for, and some other features in the pipeline will be more useful to you.
