### ISSUE TITLE
Single digit ItemCategoryHash not working when importing wish lists

### ISSUE THREAD

**Issue by jpennell** [DestinyItemManager/DIM#3889]
eg. Hand Cannons with Outlaw
```
dimwishlist:item=6&perks=1168162263
```

![image](https://user-images.githubusercontent.com/318994/59163950-1a92b480-8ad5-11e9-9360-9ea92afac611.png)

Result is "No wish list information found"

However if I try
Shotguns with Full Choke
```
dimwishlist:item=11&perks=1047830412
```

![image](https://user-images.githubusercontent.com/318994/59163942-08187b00-8ad5-11e9-9fa4-73562ac3c603.png)

Result is: "Wish list loaded with information about one roll"

I tested the following `ItemCategoryHashe`s 

|Name|ItemCategoryHash|Result|
| -- | -- | -- |
|Weapon|1|❌ |
|Kinetic Weapon|2|❌ |
|Energy Weapon|3|❌ |
|Power Weapon|4|❌ |
|Auto Rifle|5|❌ |
|Hand Cannon|6|❌ |
|Pulse Rifle|7|❌ |
|Scout Rifle|8|❌ |
|Fusion Rifle|9|❌ |
|Sniper Rifle|10|✅|
|Shotgun|11|✅|
|Machine Gun|12|✅|
|Rocket Launcher|13|✅|
|Sidearm|14|✅|
|Armor|20|✅|
|Helmet|45|✅|
|Bow|3317538576|✅|
|Trace Rifle|2489664120|✅

I tested all the above on both https://app.destinyitemmanager.com and https://beta.destinyitemmanager.com/index.html on Windows 10 using Chrome.

**Comment by delphiactual** [comment]
@48klocs
