### ISSUE TITLE
Auto tag items with farming mode

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#3891]
Spin on an idea from the discord server:

While farming mode is on:
- Option to automatically tag items in curated wishlist as "Keep"
- Option to automatically tag items less than X light or is:blue...etc as "Junk"

Button to automatically filter to the number of items that were auto-tagged in the farm popup.

Makes it useful later on to simply apply a filter "tag:junk" and move to a character to trash (instead of writing a more complex filter query)

**Comment by bhollis** [comment]
Couldn’t those just be saved searches? Wishlist items are effectively tagged already, and the second thing is an easy search.

**Comment by kyleshay** [comment]
Hmm, yeah I suppose it could eventually be folded in to saved searches.
