### ISSUE TITLE
Change to Progress tab

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#3892]
Last night there was a change to the Progress tab to make it look like the new Vendors tab.  I cannot find a PR that implemented it, but it is the awesome.

![image](https://user-images.githubusercontent.com/25425159/59236055-a15da380-8c33-11e9-9e59-ca03a711105b.png)

For some reason I can't see this layout on all of my devices.

**Comment by delphiactual** [comment]
Pretty sure this is a WIP branch by @bhollis that got commited by accident

**Comment by bhollis** [comment]
Yup, accidentally built from the wrong branch while trying to get the site back up. Glad you liked it.
