### ISSUE TITLE
item source map updates

### ISSUE THREAD

**Issue by sundevour** [DestinyItemManager/DIM#3897]
dual purpose issue: a to-do i'm happy to handle, and also a question:

• **some currently "sourceless" items as far as DIM is concerned**
https://data.destinysets.com/i/Collectible:1561962824
(earned through crimson days event)
https://data.destinysets.com/i/Collectible:753635605
(comes from raid-related triumph. probably just `raid` and `crownofsorrows`)

to-do: filter through manifest and find missing sources that aren't general loot pool

• **regarding that 1st shell & sources in general**
question: is there a place for an `event` source? or should it just be crammed into general eververse?
`quest`?

**Comment by delphiactual** [comment]
For events: d2-events.json which comes from https://github.com/delphiactual/d2-seasons-redis
I probably just missed them as this is mostly curated by hand with the exception of season data

For itemhash 753635605 just add it to itemhash for `raid` and crownofsorrows in d2-sources.json
