### ISSUE TITLE
Loadout Optimizer doenst use Traction Perk on Leg Armor properly

### ISSUE THREAD

**Issue by aroldmi** [DestinyItemManager/DIM#3899]
If you filter for the Traction Perk on Leg Armor in the Loadout Optimizer, it does filter correctly, but it doesnt use the first Armor Perk anymore like "Mobility Enhancement Mod" or "Restorative Mod".
Because of that, the Min or Max Stat-Filter can not be used correctly.

**Comment by delphiactual** [comment]
closed by #4159
