### ISSUE TITLE
Dedicated Loadout Panel

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#390]
At the moment we interact with loadouts via the character heading. It might be beneficial to create a panel that can be toggled that allows the user to manage loadouts.

Using a vertical panel on the left hand side would allow us to create a mock guardian that the user could populate with gear similar to the way they move gear now, via drag and drop and the move popup. 

Items can be moved around the loadout to change the equipped item or to remove them from the loadout. 

There is much more room in a panel to manage loadouts, select a loadout for modification, or apply a loadout to a character. I still think it is useful to have the loadout drop down near the character to keep it simple for users to quickly apply a loadout. 

Just some thoughts while relaxing. I'll elaborate more later.

**Comment by kyleshay** [comment]
Eventually, it would be nice to merge the two loadout builder interfaces into one single interface.

**Comment by kyleshay** [comment]
We'll consider this for the next DIM, current version works as-is for now.
