### ISSUE TITLE
Heroic Adventure missing in Progress after 1 character completes

### ISSUE THREAD

**Issue by sundevour** [DestinyItemManager/DIM#3902]
The Heroic Flashpoint Adventure is tracked by pursuits, and appears under `Milestones & Challenges`

Once completed on one character, it is disappearing from all three characters' to-do lists.

The API formatting for this pursuit is kind of weird and DIM's display logic has me confused, I am waiting on getting a sample of "all 3 characters still to-do" API response to troubleshoot. In the mean time opening this issue to track the bug.

**Comment by bhollis** [comment]
It’s worth noting that this can come from two places - there’s an item version that we don’t use, and a milestone version that we do use. The items are sort of a legacy remnant from D1 where all quests were items. I wouldn’t be surprised if this is an API bug though- milestones in general are apparently difficult to manage from the bungie.net side.

**Comment by bhollis** [comment]
AFAICT this is moot post-Shadowkeep.
