### ISSUE TITLE
Emblems/transmat/ornaments don't have collection info

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#3903]
This is what Eververse looks like with "only show uncollected items" unchecked.

![image](https://user-images.githubusercontent.com/25425159/59411301-14b11200-8dfa-11e9-926d-e2281e156827.png)

This is what Eververse looks like with "only show uncollected items" checked.

![image](https://user-images.githubusercontent.com/25425159/59411344-2c889600-8dfa-11e9-8982-cb20ccb5b6e4.png)

These are not at all consistent.

**Comment by bhollis** [comment]
We don’t get collection state for things like emotes and ornaments, as I recall. See how they don’t have blue check marks?

**Comment by philkernick** [comment]
I know about that for emotes and ornaments, but there is much more than that.

- in the bright dust section, the tokens are missing
- in the seasonal offerings section, the transmat effects are missing
- in the consumables section, the tokens is missing

Also as a general approach, if we can't tell that something is collected (like emotes, ornaments, ghost projections) we shouldn't hide it when "only show uncollected items" is checked.

**Comment by bhollis** [comment]
OK I found a fix for transmat effects and shaders. The rest are going to stay gone because they don't appear in collections.

**Comment by bhollis** [comment]
Just to clarify, the intent of the feature is not "hide collected", it's "filter to uncollected". So anything that can't be unlocked in collections is ineligible.
