### ISSUE TITLE
On firefox I am not able to use the normal application.

### ISSUE THREAD

**Issue by bmak757** [DestinyItemManager/DIM#3905]
I keep seeing this message 
"
DIM hasn't loaded. Something may be wrong with it, or with your browser (maybe you have a content blocker, or have disabled JavaScript, or your browser is too old). Try force reloading to make sure (Ctrl-F5 or Cmd-R).
Your browser is not supported by DIM. Some or all DIM functionality may not work. Please switch to a supported browser. "

However I am able to run the beta version of the application just fine.

Environment information
Windows 10 Home (set to dark mode)
Firefox (v67.0.2)
addons in use
- uBlock origin
- https everywhere
- privacy badger

confirmed it still does not work with addons disabled

**Comment by bmak757** [comment]
![image](https://user-images.githubusercontent.com/6164033/59468231-7fb11780-8dff-11e9-8b22-fea842db9d2a.png)
Debug for posterity

**Comment by 13DavidG** [comment]
I am having the same problem in Chrome. It started on the same day I updated it to the latest version, however this seems like a coincidence considering you are getting the same issue. 

It seems like a cache related problem. Every time I open a new tab of the normal app, it gives me the same error as you. To make it work I refresh my cache and the page (CTRL+F5 on chrome), it might work for you as well.

Notes:
-I am not using adblock on app.destinyitemmanager.com/* 
-I have also tested it with adblock completely disabled
-Running release version of Chrome: Version 74.0.3729.169

**Comment by bmak757** [comment]
I tried wiping my cache, and it did not do anything,

**Comment by inexorableAce** [comment]
A lot of people have had this issue with FF since our server went down. A Ctrl + f5 has worked for everyone.

**Comment by bhollis** [comment]
How's it doing now?

**Comment by 13DavidG** [comment]
It hasn't been doing it at all in the past week so I think it's fixed. The problem only lasted a couple of days
