### ISSUE TITLE
Other site links are not consistent

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#3908]
On the new progress page there are links to other sites.

The styling is consistent.  The first two have some sort of engram icon before the name, but the last one doesn't.

![image](https://user-images.githubusercontent.com/25425159/59548436-aa7da600-8f8e-11e9-8d1d-3c7948da25fb.png)

**Comment by bhollis** [comment]
The broken links are supposed to be their logos. We should probably download and serve our own copy since your browser doesn’t seem to like the hotlink. Lowlines site doesn’t have a logo.

**Comment by philkernick** [comment]
It really wasn't clear at all to me that they were supposed to be logos.  Why not get rid of the logos and put the glyph at the end (box with an arrow to the top right) at the beginning instead.

**Comment by 48klocs** [comment]
This was resolved with #3918
