### ISSUE TITLE
Some of these quotes are not like the others

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#3909]
We use double quotes to allow searches that contain spaces.

There is an implicit expectation in the regexp that implements this that the double quote mark is &quot; [0x22].  This is true on a PC.
`perk:"unflinching"`

But on an iOS device (specifically iPad Pro iOS 12.3.1) that isn't the case.  Instead the quote mark that gets entered from the onscreen keyboard is &rdquo; [0xE2 0x80 0x9D].
`perk:”unflinching”`

As a result of this, quoted searches don't work at all.

**Comment by delphiactual** [comment]
Turn off smart quotes

**Comment by philkernick** [comment]
That would be solving the wrong problem.

**Comment by philkernick** [comment]
While I accept that turning off smart punctuation (that's what it's called in iOS 12) would be a functional workaround, I don't think it's the right answer, for a few reasons.

1.  It's the default.
2.  Asking people to turn off a feature (that is 3 levels deep in the settings) to get DIM to work is feels wrong.
3.  We don't publish a guide to "getting DIM to work on your device".  It just works.
4.  Unicode is standard, and assuming US-ASCII is very old school.

**Comment by kyleshay** [comment]
https://github.com/DestinyItemManager/DIM/blob/master/src/app/search/search-filters.ts#L515
