### ISSUE TITLE
Hunger Loadout

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#391]
Now that we have a firm grasp on the xp quality of the items in the inventory, I would like to create a new dynamic loadout called "Hunger".  It will be used by users when they want to turn in bounties and wish to spend the xp on gear that they would want to keep.

* Clicking on this loadout will create a dynamic loadout of the existing equipped and unequipped items to restore the players state on demand.  A new button will appear next to the loadout that is called "Restore Items".
* The loadout will search for items that are 'xpIncomplete' and pick the items that are the highest light, and if there are several items that have the same light, pick the one with the least amount of XP remaining.
* The selected items will be added to a dynamic loadout and applied to the character.
* When the user is finished with their task, they can click on the "Restore Items" button and the previous items will be returned to the character.  
*The "Restore Items" button will be removed.

**Comment by wein3967** [comment]
I like the idea.

**Comment by bhollis** [comment]
Awesome. I was actually just about to start on something just like this. A couple additions:

1. I think it should prefer locked items to unlocked.
2. It should leave an item equipped if it's xpincomplete.
3. We already have the "revert last loadout"/restore items functionality, so there's no extra effort required there.

**Comment by SunburnedGoose** [comment]
Sensible ideas @bhollis
