### ISSUE TITLE
Elgato Stream Deck integration

### ISSUE THREAD

**Issue by GeekyEggo** [DestinyItemManager/DIM#3916]
### Background
The [Elgato Stream Deck](https://www.elgato.com/en/gaming/stream-deck) is a "USB peripheral providing several dedicated, programmable keys. Each key operates as a separate graphics display that can show the key's function, status, or title."

Earlier this year, the [Elgato Stream Deck SDK](https://developer.elgato.com/documentation/stream-deck/sdk/overview/) [ESD SDK] was made publicly available, with plans for "A developer portal [being made] available later this year to let third party developers submit their plugin to the store.".

### SDK Capabilities
At it's core, the ESD SDK communicates with plugins via web sockets. Plugins can take the form in any executable, in _any_ language. It is also possible to write plugins in JavaScript. There are a variety of events that occur during communication, including key down / up, key will appear / disappear, etc. Plugins may also provide "profiles", which can define a complete set / screen of plugin buttons.

#### Functionality
It would be nice if there were integration with DIM, and the Elgato Stream Deck. This could include a variety of actions, including:
* Transfer loadout to character.
* Maximize Power.
* Make Room for Postmaster.
* Gather Repuation Items.
* Farming Mode (toggle).
* Transfer item to current character / Vault view (via ESD profile)

#### Possible implementation
Fundamentally, DIM functionality should be re-used (DRY). A similar approach could be taken to that of the ESD SDK, whereby a web socket is used. The ESD plugin could provide a local web socket server, to which an open instance of DIM could connect to. This would then enable for a set of actions to be "triggered", which would act as a wrapper for pre-existing DIM functionality.

**Comment by GeekyEggo** [comment]
#### Optional reading
Over the past several months, I have created a variety of plugins for the ESD, all of which utilise a lightweight .NET Standard framework I have written. The framework provides functionality that acts as a wrapper for the communications between plugins and the ESD. The framework is written in C# and aptly named [SharpDeck](https://github.com/geekyeggo/sharpdeck), although not restricted to WIndows as it utilises the .NET Standard framework.

**Comment by bhollis** [comment]
Would it be possible to do this through key bindings instead of having specific support for the StreamDeck? I'd prefer not to have to have something specific to this niche hardware, and to instead offer quick functionality for everyone.

**Comment by kyleshay** [comment]
keybinding route makes sense... linking #399

**Comment by lassevk** [comment]
I really like this idea, but it would need something more than mere keyboard shortcut support. Keyboard shortcuts would require either the StreamDeck application to quickly alt-tab to DIM, which means it will have to identify *where* DIM is currently running, which would not be an easy task. Or, the player would first have to activate and focus DIM before hitting the StreamDeck button, which sort of defeats the niceness of the whole thing. Though, if this is all you got, I'd take it, but then we would need a way to set up keyboard shortcuts in DIM.

Adding a way for DIM to contact a generalized local backend server (security-wise, is it even allowed to do this?), that the StreamDeck plugin sets up, would solve this, and it wouldn't have to be StreamDeck specific either, just document the way the communication works and StreamDeck would just be one implementation, there could be many others.

**Comment by SunburnedGoose** [comment]
Want to bump this. 

https://twitter.com/LucasFigg/status/1262576437275561984?s=20

We could solve this if DIM supported a URI for each loadout, and attempt to trigger the loadout with a GET request to that URI.

**Comment by kyleshay** [comment]
Closing in favor https://github.com/DestinyItemManager/dim-api/issues/16 as this will require use of the DIM api.

**Comment by GeekyEggo** [comment]
In light of the DIM API, I wanted to ask if this could be re-opened? I would be happy to implement the bulk of the work on the Stream Deck side of things, going by the assumption it’s possible to leverage the API.

**Comment by inexorableAce** [comment]
you'll have to leverage both the DIM API and Bungie API I'd assume. DIM api is only letting you get at the items in the loadouts. you'd need to use the bungie API to then move / equip them.

**Comment by bhollis** [comment]
@GeekyEggo it's closed here because the majority of the work requires adding support for moving items and applying loadouts using DIM's logic to the DIM API. Once that's done, we can reopen this for the much smaller work to enable on Stream Deck.

Alternately you could write something that directly uses the Bungie.net API to move items and use the DIM API to just load the loadouts information, but that could be an independent project and not part of DIM.

**Comment by GeekyEggo** [comment]
My apologies @bhollis, I wasn’t sure of the progress of the DIM API.

I’d be happy to look into a plug-in that incorporates both the DIM API and Bungie’s. How would I go about gaining access to DIM’s?

**Comment by bhollis** [comment]
You can get a development token from the DIM developer page if you run it locally, and you can use that for other localhost stuff. I can get you prod tokens later if you ping me on Discord.

**Comment by GeekyEggo** [comment]
Thanks @bhollis, that would be great, I’ve sent you a request on Discord. Appreciate your time!

**Comment by Mechrior** [comment]
any updates on this as I just got my streamdeck XL and looking for game integrations.

**Comment by fcannizzaro** [comment]
Hi, for anyone interest in this topic I'm working on a plugin to connect the Stream Deck to DIM / Destiny 2 (I use this plugin when I play D2). The repository is https://github.com/fcannizzaro/com.dim.streamdeck, any suggestion / issue / contribution is welcome 😄 At the moment it works only with `beta` version of DIM thanks to the class names not randomized.
