### ISSUE TITLE
Multiple instances of DIM opening

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#392]
Clicking the DIM icon in Chrome opens multiple instances instead of jumping to an already opened tab.

**Comment by SunburnedGoose** [comment]
Chrome v49 will change the 'tabs' permission in that we can't query the tabs without that permission.  People hated that we asked for that when we released v3 so it's a non-starter.  If we can't query to see if DIM is already open then we just open new tabs and hope the user understands what they are doing and break that habit.
