### ISSUE TITLE
Replace [Weapon Type] with Icon for Progress Objectives

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#3929]
Using `destiny-icons` we can replace the `[Weapon]` text with the in-game icon by doing a little manipulation of the objective descriptions.

@justrealmilk did something like this on [Braytech](https://github.com/justrealmilk/braytech.org/blob/05116ff4fca153b9f99fb8bae9e68160e560610a/src/utils/destinyUtils.js#L474)

But instead of hardcoding the string replacements, which does not work with i18n, we can provide an autogenerating list based on hashes from `DestinyObjectiveDefinition`

| DestinyObjectiveDefinition Hash | String Replacement (en) | Icon |
| ------------------------------------------- | -------------------------------- | -------| 
| 3287913530  | headshot| <img src="https://raw.githubusercontent.com/justrealmilk/destiny-icons/master/weapons/headshot.svg?sanitize=true" height="32"> |
|2994623161 | solar kill| <img src="https://raw.githubusercontent.com/justrealmilk/destiny-icons/master/weapons/damage_solar.svg?sanitize=true" height="32"> |
|2178780271 | arc kill| <img src="https://raw.githubusercontent.com/justrealmilk/destiny-icons/master/weapons/damage_arc.svg?sanitize=true" height="32"> |
|695106797  | void kill | <img src="https://raw.githubusercontent.com/justrealmilk/destiny-icons/master/weapons/damage_void.svg?sanitize=true" height="32"> |
| 3527067345 | sniper rifle| <img src="https://raw.githubusercontent.com/justrealmilk/destiny-icons/master/weapons/sniper_rifle.svg?sanitize=true" height="32"> |
|635284441 | shotgun| <img src="https://raw.githubusercontent.com/justrealmilk/destiny-icons/master/weapons/shotgun.svg?sanitize=true" height="32"> |
|2152699013 | grenade launcher| <img src="https://raw.githubusercontent.com/justrealmilk/destiny-icons/master/weapons/grenade_launcher.svg?sanitize=true" height="32"> |
|532914921 | auto rifle| <img src="https://raw.githubusercontent.com/justrealmilk/destiny-icons/master/weapons/auto_rifle.svg?sanitize=true" height="32"> |
|2161000034 | pulse rifle| <img src="https://raw.githubusercontent.com/justrealmilk/destiny-icons/master/weapons/pulse_rifle.svg?sanitize=true" height="32"> |
|2062881933 | scout rifle| <img src="https://raw.githubusercontent.com/justrealmilk/destiny-icons/master/weapons/scout_rifle.svg?sanitize=true" height="32"> |
|53304862 | hand cannon| <img src="https://raw.githubusercontent.com/justrealmilk/destiny-icons/master/weapons/hand_cannon.svg?sanitize=true" height="32"> |
|299893109 | sidearm| <img src="https://raw.githubusercontent.com/justrealmilk/destiny-icons/master/weapons/sidearm.svg?sanitize=true" height="32"> |
|2722409947 | smg| <img src="https://raw.githubusercontent.com/justrealmilk/destiny-icons/master/weapons/smg.svg?sanitize=true" height="32"> |
|3296270292 | fusion rifle| <img src="https://raw.githubusercontent.com/justrealmilk/destiny-icons/master/weapons/fusion_rifle.svg?sanitize=true" height="32"> |
|2923868331 | linear fusion rifle*| <img src="https://raw.githubusercontent.com/justrealmilk/destiny-icons/master/weapons/wire_rifle.svg?sanitize=true" height="32"> |
|3080184954 | trace rifle| <img src="https://raw.githubusercontent.com/justrealmilk/destiny-icons/master/weapons/beam_weapon.svg?sanitize=true" height="32"> |
|2203404732 | rocket launcher| <img src="https://raw.githubusercontent.com/justrealmilk/destiny-icons/master/weapons/rocket_launcher.svg?sanitize=true" height="32"> |
|989767424 | sword| <img src="https://raw.githubusercontent.com/justrealmilk/destiny-icons/master/weapons/sword_heavy.svg?sanitize=true" height="32"> |
|1788114534 | machine gun | <img src="https://raw.githubusercontent.com/justrealmilk/destiny-icons/master/weapons/machinegun.svg?sanitize=true" height="32"> |
|1242546978 | bow|  <img src="https://raw.githubusercontent.com/justrealmilk/destiny-icons/master/weapons/bow.svg?sanitize=true" height="32"> |

For `zh-*` this is as simple as checking `objective[hash].description[0]`

For the other languages we just need to:
```
      // const start = objective[hash].description.indexOf("[") - 1;
      // const stop = objective[hash].description.indexOf("]") - 1;
      // obj[key].substring = objective[hash].description.substring(start,stop)
```
*Linear Fusion Rifle will have 2 bracketed substrings, one is headshot, so headshot needs to be checked first and eliminated from the LFR string prior to setting its replacement string.

https://github.com/justrealmilk/destiny-icons/tree/master/weapons

EDIT: This also will continue working when/if bungie has typos in the weapon names e.g. `[Rocker Launcher]` or extra spaces inside the brackets such as: `[ヘッドショット ]` and `[Helmtreffer ]`

**Comment by delphiactual** [comment]
I did make a manual list if that is wanted

https://gist.github.com/delphiactual/754a45d867b138548b9c3c009b40eb74

**Comment by delphiactual** [comment]
working test implementation of locating substrings automatically
https://github.com/delphiactual/d2-additional-info-redis/commit/cfa18b9e806e0799ff71ea2bfe9912d75994d537

**Comment by twistof8** [comment]
Please leave the text despriptions, they are a lot faster to read.
