### ISSUE TITLE
Add Lock/Unlock Action for Items

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#393]
Lockable items can be locked and unlocked via an api call.

**Comment by SunburnedGoose** [comment]
Need to make the icon have the action cursor.  Also block the action if there is a promise currently running to prevent multiple clicks.

**Comment by SunburnedGoose** [comment]
Searching for is:locked provides results but when I unlock the items, they are still visible.

**Comment by kyleshay** [comment]
somewhat related (uses the same api call, at least), but it could be nice to have a checkbox to auto unlock all things that were transferred for infusion via the calculator.
