### ISSUE TITLE
Display height of account wide quests causes clipping

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#3930]
This is an implementation issue after #3910 and #3927.

Almost all of the quests have their last line of text clipped.

![image](https://user-images.githubusercontent.com/25425159/59971049-24c3b100-95b3-11e9-8c38-1fa9dcab187f.png)

**Comment by sundevour** [comment]
to clarify, this predates that issue&pull.
here it is without those commits:
![image](https://user-images.githubusercontent.com/31990469/59972416-919f6280-9543-11e9-9cf9-4c5c983ed73f.png)

if the concern is the clipped stems, the little pixel or two dots, that can be resolved by setting container height with `em`. if the concern is text being cut off, afaik this is a sacrifice to compactness.

**Comment by bhollis** [comment]
Yeah, the idea here is to restrict descriptions to two lines, like in game, so they correctly display in a grid. Some of these have very long descriptions. I’d prefer if they could have an ellipsis but multi line text is hard to ellipsize.

**Comment by sundevour** [comment]
considering the current 3em sizing, and extra space, maybe this is intended to show 3 lines?

if you set a `1.2` line height instead of relying on useragent's default, a `3.6em` box height fits 3 lines neatly.
![image](https://user-images.githubusercontent.com/31990469/59972686-7c790280-9548-11e9-81ad-2278369252db.png)

i would love to make this 3 lines and get closer to not worrying about wrapping.

**Comment by bhollis** [comment]
Three lines would be great!  Whatever I had set it to originally was based on icons that didn’t yet include the percentage (and they won’t in the future).

**Comment by philkernick** [comment]
The changes in #3932 have fixed the clipping issue, but in the process have removed all of the detailed tracking information which is now only available in item popups.

![image](https://user-images.githubusercontent.com/25425159/60076639-3948aa80-9767-11e9-841e-8186cd677a10.png)

This might be the right choice, but I'm calling it out in case it wasn't intended.

**Comment by bhollis** [comment]
Yup, it’s intentional. These were not meant to have the objectives displayed in full.
