### ISSUE TITLE
Horizontal scrolling no longer works in the new Progress layout

### ISSUE THREAD

**Issue by Wh1rledPeas** [DestinyItemManager/DIM#3933]
On the mobile platform, there is only one column visible at a time. If you want to swipe left<->right to view an alternate character, you have to scroll all the way to the top and use the character header.

I noticed this when attempting to compare the faction levels between my characters. This was always possible until the Progress rewrite.

**Comment by Wh1rledPeas** [comment]
[<img src="https://user-images.githubusercontent.com/3685437/60791844-7aab6380-a132-11e9-9b69-a2f84a0ead81.png" width="200">](https://youtu.be/1x5YqILci0g)

**Comment by bhollis** [comment]
Yup, your original report was clear.
