### ISSUE TITLE
Declare support for Edge Chromium

### ISSUE THREAD

**Issue by jkewley** [DestinyItemManager/DIM#3936]
I run DIM on Edge Chromium and it works well, other than the Clear New Items call to action which doesn't work. Is official support being considered? I'd be willing to help test.

**Comment by bhollis** [comment]
It’s unofficially supported since it’s just Chrome, but the script we use for detecting supported browsers doesn’t yet know about it.

**Comment by delphiactual** [comment]
https://github.com/browserslist/browserslist/issues/373

**Comment by bhollis** [comment]
Can you please check DIM beta? It shouldn't show a "not supported" banner on Edge Chromium anymore.

**Comment by jkewley** [comment]
Still seeing it on https://beta.destinyitemmanager.com even after cache dump and cntrl+F5

**Comment by bhollis** [comment]
Can you go to https://www.whatismybrowser.com/detect/what-is-my-user-agent and tell me what your user agent is?

**Comment by jkewley** [comment]
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3837.0 Safari/537.36 Edg/77.0.211.3

**Comment by bhollis** [comment]
I see, that's just a newer version of edge than browserslist knows about.

**Comment by jkewley** [comment]
New versions tend to push weekly. It'll stabilize once they're out of preview.
