### ISSUE TITLE
Perk search returning things it shouldn't

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#3938]
I'm interested in armor with enhanced perks.

`perk:enhanced` should return only those with enhanced perks, but for reasons I cannot determine it also returns Knucklehead Radar and Young Ahamkara's Spine,

![image](https://user-images.githubusercontent.com/25425159/60153795-876fb380-9824-11e9-923f-1e743c537ef1.png)

Neither have enhanced perks.  Neither have the word "enhanced" anywhere in their text description, or mods, or shaders, or ornaments.

I've even checked with the data explorer in DestinySets and the word enhanced really isn't there.

**Comment by sundevour** [comment]
i feel your pain

![image](https://user-images.githubusercontent.com/31990469/60172288-3aa6c100-97c1-11e9-89a4-bf76347c7c00.png)
![image](https://user-images.githubusercontent.com/31990469/60172228-206ce300-97c1-11e9-9b37-608c5afca0b6.png)

**Comment by bhollis** [comment]
What I plan on doing is making the bits that matched in search highlighted in the item popup, so at least you’ll understand why it matches.

**Comment by philkernick** [comment]
The really strange bit for me is that the text i have displayed both in DIM and in the game UI doesn't include the word "enhanced".

![image](https://user-images.githubusercontent.com/25425159/60230798-518b0780-98d6-11e9-8973-913abbe2b6cd.png)

![image](https://user-images.githubusercontent.com/25425159/60230851-77b0a780-98d6-11e9-927a-b2c0482f60e8.png)

**Comment by delphiactual** [comment]
But it is there just not shown

https://data.destinysets.com/i/InventoryItem:4284305242/InventoryItem:481860150/SandboxPerk:1307898536

**Comment by sundevour** [comment]
yeah this is entangled with #3622 and deciding which sockets actually get searched

**Comment by philkernick** [comment]
Searching things which are not exposed in game isn't really helpful.  To the point by @bhollis above, there would be nothing to highlight to even show why the filter matched.

At least in my usecase, I want the perk: filter to match only on the perk name.  I accept that my usecase isn't the same as everyone else.

**Comment by philkernick** [comment]
Fair point. I do think that people who use the perk: filter rather than just "enhanced" probably are a small subset, and have a more specific usecase.
