### ISSUE TITLE
Custom names for items

### ISSUE THREAD

**Issue by jaredharbour** [DestinyItemManager/DIM#3940]
I was watching KingGothalion this morning and he mentioned that it might be cool to be able to name an item.  I think in his case he would like to name his new favorite shotgun "The Mother Fucker".  

I imagine a feature like this would be something stored in browser local storage to begin with. A simple string value paired with the items id and could be searchable by the custom name.

If that sounds like something that fits in line with direction of DIM I'd be interested in doing the work and tossing a PR your way.

**Comment by kyleshay** [comment]
The unfortunate thing with local storage is that space limited and shared between many things including notes and loadouts. 

One way that you could currently achieve this is by actually using the notes section in the move popup. You'd then be able to search for your named gear by using the search box and typing `notes:Vooper`
