### ISSUE TITLE
Remove is:curated search term

### ISSUE THREAD

**Issue by 48klocs** [DestinyItemManager/DIM#3941]
I called wish lists "community-curated rolls" early on in its development life cycle.

The search term `is:curated` is a vestigial piece of that, and given that items have Bungie-curated rolls, it's understandably confusing.

`is:wishlist` should stay, `is:curated` should no longer be an alias for that.

**Comment by delphiactual** [comment]
`is:curated` might be able to be sourced from the API with a slight massage of data

curated rolls exists for a select few weapons, we can maintain this list by hand. [list](https://docs.google.com/spreadsheets/d/1_yqFd9lSUtH6k3MzuXodCDZKkwm7oj5Io0Craz08Q7k/edit#gid=619155124)
The curated roll is what is shown `sockets.socketEntries[#].singleInitialItemHash`

We will need to ignore some of the other sockets such as shader, etc

**Comment by delphiactual** [comment]
https://gist.github.com/delphiactual/9a1fb840a116ff632c59a5a73962ecc3
