### ISSUE TITLE
"Tag item" dropdown in comparison view triggers the move/dismiss action

### ISSUE THREAD

**Issue by phillipspc** [DestinyItemManager/DIM#3942]
[![Image from Gyazo](https://i.gyazo.com/71fe7955b8c3599b6768c9f30cd1f447.gif)](https://gyazo.com/71fe7955b8c3599b6768c9f30cd1f447)

When I make a "tag" selection on an item in the comparison view, it looks like it's also interpreting that click as if I'm moving the comparison view down toward the bottom of the screen (another click is then needed to stop it from resizing).

**Comment by duckmanBR** [comment]
By any chance you're using Chrome on full screen?  This week we had a report from a user that complained that DIM was equipping any item he tried to inspect. In the end he found out that Chrome on full screen was sending double clicks to dim after some time.
We couldn't reproduce, so couldn't look further.

**Comment by phillipspc** [comment]
@duckmanBR this was on safari (12.1.1)
It does appear to be browser specific though... tried it on chrome and didn't see it. I didn't think to try multiple browsers before creating the issue and assumed it was app-wide.

**Comment by bhollis** [comment]
Probably just need to swallow touch events coming from the select element.
