### ISSUE TITLE
Feature request: give user the option to switch between destiny tracker and light.gg

### ISSUE THREAD

**Issue by michabbb** [DestinyItemManager/DIM#3943]
Because the tracker always shows item infos in English, light gg is much better for people using a different language than English, because light offers a simple way to switch languages, at tracker I always have to change the url, which is very annoying. If there is a easy way, please let me know. Thanks.

Update:

Pardon, even my dim is German, I need to see the names (sometimes) in English, so yes, it's good that tracker shows me infos in the same language as I use in dim, but very often I have to switch to English and back, that switch is way easier with light.gg, that's why I am asking. Thanks.

**Comment by bladefist** [comment]
Hey this is xorth from Destiny Tracker, we're gonna add a language picker, and might even try to match the language in DIM.

**Comment by michabbb** [comment]
@bladefist would be nice, maybe you can also add the info, where to get the item, if i am not wrong, this info is only visible in gg ;(

**Comment by bladefist** [comment]
@michabbb indeed.  We are planning on doing lots of big changes for the Fall update.

**Comment by michabbb** [comment]
@bladefist okay, would be happy. maybe you can also add a "show in manifest" button, that would be very helpful for developers ;)

but anyway, i don´t know if tracker has "exclusive rights" here or not, if not, i would love to see it anyway to give the user a choice, to use the external source he prefers ;)

**Comment by bhollis** [comment]
Thanks folks! I'm going to close this as it's effectively a feature request for DTR. We don't want to switch to linking anywhere else as of right now.
