### ISSUE TITLE
Charge Time in comparison tool incorrectly highlights high (worse) numbers as blue

### ISSUE THREAD

**Issue by tcurtin** [DestinyItemManager/DIM#3951]
Fusion rifle stat Charge Time is an instance of higher = worse, but in comparison tool both blue/green/yellow/red coloring ("best" stat) and sorting treat it as though higher is better.

![image](https://user-images.githubusercontent.com/979464/60404168-21f92b00-9b74-11e9-87cb-ecbb3ca19aa8.png)

(In this image, the Crooked Fang with Backup Plan and Charge Time masterwork is clearly the fastest of the bunch, but sorts as worst and doesn't get the blue stat color.)

**Comment by sundevour** [comment]
happy wednesday and thank you for the bug report!
#3957 should address this issue
