### ISSUE TITLE
Convert Catalyst Collection Display to using Records

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#3970]
For `Insert the Catalyst` Objective
```
0/2 - Catalyst not acquired
1/2 - Catalyst acquired
2/2 - Catalyst inserted
```
When at `0/2` we should identify where the catalyst drops.

We should highlight when users are in state `1/2` because they cannot advance the catalyst until it is completely inserted.

https://data.destinysets.com/i/Record:1962727403/Objective:681553759

**Comment by bhollis** [comment]
I was actually just going to remove the Catalysts display and fold Collections into the progress page, unless we can think of a nice way to use the records.
