### ISSUE TITLE
High CPU usage in Google Chrome

### ISSUE THREAD

**Issue by Symbiotx** [DestinyItemManager/DIM#3975]
I noticed chrome was running at 30-50% CPU usage while running Destiny 2 and DIM in chrome.  Chrome's task manager showed that it is the DIM tab causing it, specifically:
`Service Worker: https://app.destinyitemmanager.com/service-worker.js`
Maybe it's an issue with javascript running on my PC or something, but I just thought it was odd, and it had been running really slow for me sometimes as well.

**Comment by bhollis** [comment]
That's a bummer. All the service worker does is pre-download and cache all the scripts and content for the app in the background. Should only take a few seconds and then it gets out of the way. What version of Chrome are you on?

**Comment by Symbiotx** [comment]
Gotcha, yeah it doesn't seem to be happening to anyone else.

Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by delphiactual** [comment]
@datSkiba remove the clarity extension
