### ISSUE TITLE
Move search help button

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#3981]
I have a constant UX frustration when using DIM on an iPad.

Type something into the search field and the very right hand side of the search bar turns into the "clear the search X" button.  So far so good.  Press the X, and because the device is slow wonder whether I actually hit it and press the same spot again, by which times it's turned into the "give me help on search ?" and now I'm on the search help page.

If we move the ? to the beginning of the search help bar, then this user pattern never happens and I am a happy boy.

**Comment by bhollis** [comment]
I don't really like the idea of having it on the left, before your typed search.

Some things that should be addressed to help with this:

1. Clearing search shouldn't be slow.
2. We should finally do the search revamp, wherin the help will be moved to a different place.
3. The search help page should have an easy dismiss button (really just a back button) or maybe be placed in a sheet.
