### ISSUE TITLE
DIM not loading on Windows 10 laptop

### ISSUE THREAD

**Issue by D2XBOX** [DestinyItemManager/DIM#3983]
Hello, 

Got error message " DIM hasn't loaded. Something may be wrong with it, or with your browser (maybe you have a content blocker, or have disabled JavaScript, or your browser is too old). Try force reloading to make sure (Ctrl-F5 or Cmd-R). " . Checked alpha and beta apps, same result . Windows 10 using edge. Worked in the am. after lunch failed to load.

Thanks

**Comment by bhollis** [comment]
Can you hit F12 and see what errors show up in the console?

**Comment by Tyler-Duckworth** [comment]
Hi! I was running into what I think is a similar issue on a Windows 10 Desktop with Microsoft Edge. The funny thing is, I got it working on a Windows 10 Laptop running Chrome. Here a screenshot of the console. 
![Screenshot (4)](https://user-images.githubusercontent.com/25271900/60850576-fdc5cb80-a1bd-11e9-826c-05cad8a13f58.png)

If you need any more info, please let me know.

**Comment by D2XBOX** [comment]
Hello,

 HTML1300: Navigation occurred.
app.destinyitemmanager.com (1,1)

 CSP14304: Unknown source ''report-sample'' for directive 'script-src' in Content-Security-Policy - source will be ignored.

 CSP14309: Unknown directive 'manifest-src' in Content-Security-Policy - directive will be ignored.

 CSP14304: Unknown source ''report-sample'' for directive 'script-src' in Content-Security-Policy - source will be ignored.

 CSP14309: Unknown directive 'manifest-src' in Content-Security-Policy - directive will be ignored.

 SCRIPT1028: SCRIPT1028: Expected identifier, string or number

thanks

**Comment by D2XBOX** [comment]
again

**Comment by D2XBOX** [comment]
Sorry, did not mean to close the issue.

**Comment by bhollis** [comment]
What version of Edge are you using?

**Comment by D2XBOX** [comment]
Microsoft Edge 42.17134.1.0
Microsoft EdgeHTML 17.17134

**Comment by SunburnedGoose** [comment]
Another user on twitter reported an error with Edge.

**Comment by bhollis** [comment]
I see the issue
