### ISSUE TITLE
Keyboard accessibility

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#399]
I'd like to figure out a way to have more robust keyboard accessibility for DIM. Some things that could benefit from keyboard shortcuts:
- [ ] Applying a loadout.
- [x] Focusing the search box.
- [ ] Selecting a character/action from the move popup.
- [ ] Scrolling to a particular bucket of items.

**Comment by kyleshay** [comment]
toggling settings?
for example: 

- [ ] toggle primary stat
- [ ] toggle elemental icon
- [ ] toggle advanced stat quality

**Comment by bhollis** [comment]
Definitely!

**Comment by TheHandsomeCoder** [comment]
Would [keymaster.js]([https://github.com/madrobby/keymaste) be of any use? It gets used on [Dillinger](http://dillinger.io/) and seems to work ok. No updates for the last 2 years though, so possibly abandonware

**Comment by bhollis** [comment]
We already have some hotkeys, just need to expand on them.

**Comment by TheHandsomeCoder** [comment]
I did a quick run through to see what's already in place which I've listed below. I've pulled in the suggestions from above and put in preliminary keys to map. Are there any suggestions for the black keys?

- [x] ~~`f` -> focuses the filter input~~
- [x] ~~`esc` -> escapes the filter input~~ 
- [x] ~~`r` -> reloads DIM~~
- [x] ~~`i` -> expands item info when inspecting~~

------------------------------------------------------

- [ ] `↑` -> Scrolls to previous bucket 
- [ ] `↓` -> Scrolls to next bucket 
- [ ] ` ` -> toggle primary stat
- [ ] ` ` -> toggle elemental icon
- [ ] ` ` -> toggle advanced stat quality 
- [ ] `1, 2, 3` -> Selects the appropriate action from the move popup
- [ ] ` ` -> Apply loadout

**Comment by bhollis** [comment]
I wouldn't try to rebind the arrow keys. They're already used to scroll. Primary stat isn't an option anymore.

Move popup can have up to 7 options in it...

**Comment by geck0s** [comment]
Yes, the move popup can have up to 7 of 8 options in it, but I think we could map them to always do the same thing.  If the user presses a number key corresponding to an option that is not available in the current move dialog, then simply ignore it.  

1 - equip on leftmost character
2 - store on leftmost character
3 - equip on middle character
4 - store on middle character
5 - equip on rightmost character
6 - store on rightmost character
7 - vault
8 - infusion fuel finder

and why not add two more for showing/hiding stats
9 - expand details
0 - shrink details

I think this is the most useful way to map the number keys and the best way to map such move/equip commands.

**Comment by mistahj67** [comment]
In terms of accessibility, adding a 'z' button for undo 1 gear move would help immeasurably. I personally may accidentally move a weapon or piece of armor and then I have to look through the list to find it again to undo that move. Another option would be to be able to free up a space for a bit say decoding an engram and then being able to undo that move when I need to free up a different armor or weapon type. Things like Post master, quickly move a piece of armor, delete item from postmaster, and then move that piece back with undo would also help.

**Comment by deefstes** [comment]
The feature here that I would most prefer is if your loadouts could be applied with a simple key press. I was thinking the numeric keys 1 through 9 for your first 9 loadouts (or even just 1-4 or whatever). That way you could be in the middle of a battle when you realise that you rather wanted your Auto Rifle, Scout Rifle, Rocket Launcher loadout and by reaching over to your laptop, simply hitting the corresponding key for that loadout makes it happen and you continue with the battle almost seamlessly.

**Comment by kyleshay** [comment]
It would be neat if after performing a search you could hit `TAB`/`SHIFT-TAB` to cycle through the filtered options. You could hit 1, 2, 3, 4, to send the selected item to the character or vault in that "column". Could hit `ENTER` to toggle the item popup

**Comment by bhollis** [comment]
We're going to continue to add keyboard shortcuts, but let's file issues for individual features if we feel like they still need keyboard accessibility.
