### ISSUE TITLE
Clicking on Bad Juju closes Chrome

### ISSUE THREAD

**Issue by patchm00** [DestinyItemManager/DIM#3990]
My Bad Juju is in vault.  When i click on it using DIM in Chrome, the app goes to blank screen.  Only does this for Bad Juju.  Also just checked when Bad Juju is on a character it happens as well not just in vault

Just an FYI:  Lumina works fine.  I noticed they both received icons the same time (no longer the unknown)

**Comment by duckmanBR** [comment]
Could you please check if you are on the latest version?  We pushed a fix for a bug on Bad Juju some hours ago.
Latest prod is 5.36.2

**Comment by patchm00** [comment]
yes working now thanks
