### ISSUE TITLE
bulk operation confirmation

### ISSUE THREAD

**Issue by sundevour** [DestinyItemManager/DIM#3993]
per discord user report, and i absolutely agree with this,
it's surprisingly easy to irreversibly bulk tag even hundreds of items without an apply/confirm button.
it's just a dropdown, and then an "oh i guess they're all tagged" realization.

proposal for some intermediate step, or at least a warning if it's a lot of items?

**Comment by bhollis** [comment]
The way I'd like this to work is that you get a notification that everything's been tagged, but there's an "undo" button on the notification. Kinda like how Gmail does when you archive an email.

**Comment by sundevour** [comment]
a la 
![image](https://user-images.githubusercontent.com/31990469/61102878-a70dfb00-a424-11e9-99b4-a0a0fb135551.png)
?

**Comment by bhollis** [comment]
Yeah exactly!
