### ISSUE TITLE
Anyway to scale without huge space or gap in between?

### ISSUE THREAD

**Issue by hwoarang5** [DestinyItemManager/DIM#3999]
when i stack two browser side by side the scaling has massive empty space or gap between the loadout, may i know is it design on purpose or there is an option to scale it properly via browser? thx

[https://ibb.co/Jsn1YKP](url)

**Comment by delphiactual** [comment]
Screenshot?

**Comment by bhollis** [comment]
Ah, I see. Because you have a lot of stuff in the vault, when you squeeze the browser horizontally the vault takes up a lot of vertical space. Unfortunately there's no good way around that without hiding the vault.

**Comment by hwoarang5** [comment]
i see thanks for the reply
