### ISSUE TITLE
Mark items as "junk"

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#400]
It'd be nice to be able to mark items in DIM as "junk" (infusion fuel), or maybe some other statuses like "sentimental value" (for all those year 1 raid items). We could store the mapping from item ID to status ourselves. Then we could use those statuses for searches, or the infusion calculator, or whatnot.

**Comment by kyleshay** [comment]
I was thinking along the same lines. Would be nice to have an option to "archive" an item on the move dialog. 

Once archived:

* Item will be moved to the vault
* Item won't show up on the UI
* Item won't show up in search results
* Item won't be used in the infusion calculations
* Item won't be used in the minmax calculations

To unarchive: 

We'll need a dialog that shows a condensed view of archived items. Clicking an item will remove it from the archive list and make it appear in the vault on the main UI.

**Comment by nessus42** [comment]
It would be nice to have an option for the infusion calculations that would tell it to include archived items. Much of what I want to archive I keep only as infusion fuel.

**Comment by Mulchman** [comment]
What Douglas Alan said.

I don't see the point of marking something as 'junk' only to never
see/use/interact-with it again in the app (?).

**Comment by kyleshay** [comment]
yea, fair enough, was just suggesting an alternative idea. other filters can produce similar to results to what I was saying. marking items as infusion fodder is certainly useful.

**Comment by nessus42** [comment]
kyleshay, I like your suggestion. I think the only change I would make is to have the option I proposed to include "archived" items in infusion calculations. (Or maybe one could tag items as "infusion fuel", and those items would be included in infusion calculations, regardless of whether they are archived or not.)

**Comment by kyleshay** [comment]
could we merge this idea with #471 (Tags and notes on items)?

**Comment by wein3967** [comment]
My two cents ... I basically use an Excel spreadsheet to keep track of what I want to save, trash, or infuse. The reason I wanted to export from DIM was to 1) compare armor items, and 2) "label" items. Currently, I import my DIM armor/weapons in to Excel and then match item IDs to lookup my previously assigned labels. I "store" year 1 sentimental items, "keep" items to be infused, and "trash" items I can outright discard or use as infusion fuel.

I do think there is some value to many users to have tags that are searchable/filterable in DIM. I wonder if there should be a set selection of tags, or let users pick their own. The benefit of custom labels would let users determine how the label is used (e.g. archive means different things to different people, even in this thread).

**Comment by bhollis** [comment]
My plan is to have a set of "standard" tags, but also let people make their own.

I agree that this issue is just a subset of #471.
