### ISSUE TITLE
Implementing the old design or an extended version of the new polished design

### ISSUE THREAD

**Issue by chaos234** [DestinyItemManager/DIM#4005]
Well, I tried to solve this over discord but if a developer means to tell me "its just not something we want to do" he/she is not a developer in my eyes because a developer should never ever say such a sentence if he/she also says that he/she acknowledge and accept what was requested, so here is my request:

Ok, I realy love DIM and how it makes live easier but with your new polish (refereing to https://github.com/DestinyItemManager/DIM/pull/4003) it isn't that, what it was for me in the past.
This means, that the now missing extended view that, what in my eyes made DIM great but now I must click on e. g. a quest to see what todo and how far my progress is and this isn't that, what I want todo since I can then use the ingame screen.

I am not sure, why there will be no option to switch between the new polished layout and an extended layout, like it was before but only because the argument that "multiple layouts make testing much harder", is not enough for me, since you can use CSS 3 and responsive declarations to don't let it look urgent.

And normaly, when new items/quests/etc. are added, they should automaticly fit into the desinge if all is done over e. g. collecting them all in an array and displaying them over iterating with foreach through the array. Means that only a few templates are needed (assuming one for each category) which must only recive the correct variables and CSS declarations and the designe is done. Now simply alter the templates a bit and add a option check like "show_extended ? true:false" and if it's true, let it be displayed like in the old version and if it's false, show the polished version.

I don't know, why this should be do any trouble but forcing all users to use the polished version if they normaly liked the old ones it isn't a good decision and the wrong way. So please add such an option to the settings page, thanks.

Well, if there will definitly no intention to add such a little option even if a small amount of DIM-Users would using it, than I must drop DIM not only while I don't like to make more clicks then needed, no. Because I can't accept it as an developer!

I hope, that you can understand me and think over it, please.

**Comment by bhollis** [comment]
It is not a question of it being difficult. We don’t like to have a bunch of options, and the extended display no longer works given how many bounties people have to deal with now. We’ll continue to consider additional ways to make the display useful.

**Comment by chaos234** [comment]
Yeah, the amount is big and will get even bigger, when the new DLC goes live.
I hope, that there will be a solution to this :)
