### ISSUE TITLE
Vendors\Spider - display all consumables so we know what to buy

### ISSUE THREAD

**Issue by peabeu** [DestinyItemManager/DIM#4016]
Currently the displayed consumables are just those used for purchasing the items for sale, (glimmer, shards, ghost frags & planetary mats). As a quick reference point, could this vendor also display all items and totals that are available for purchase in the section Material Exchange.

E.g today i can buy Datalattice for 1 legendary shard. I have to navigate back to the Inventory page to find out if I need to buy more or not. Perhaps on the LHS of this page you could display totals and icon. This may result in double up such as glimmer, so maybe just add the unique items to the RHS with existing totals and icons

**Comment by bhollis** [comment]
Good idea! I like it.

**Comment by bhollis** [comment]
Unfortunately, we don't really have the data for this. We don't have a correspondence between the "Purchase X" item and the actual currency they produce. e.g.: https://data.destinysets.com/i/InventoryItem:3664001560

**Comment by peabeu** [comment]
Perhaps you and I were thinking of 2 different things. 
As i normally have the planetary vendors collapsed, I didn't realise the individual totals were already displayed on the Vendors page as they were always hidden by me. This will be easier to see what I should buy than navigating to and from the Inventory page however if the totals could be displayed as per image under the Spider section it even better. The data is already available and displayed in DIM just not in the section I suggested.
![Spider](https://user-images.githubusercontent.com/34254703/61610609-f82bb380-ac9c-11e9-8b95-ca0ea958b0e1.jpg)

**Comment by bhollis** [comment]
Those items aren’t the same as the actual material icons, and we don’t have a good way to figure that out.

**Comment by bhollis** [comment]
Fixed by https://github.com/DestinyItemManager/DIM/pull/4050
