### ISSUE TITLE
DIM Beta PWA constantly says update DIM even though no update is available.

### ISSUE THREAD

**Issue by iawhd** [DestinyItemManager/DIM#4017]

**Comment by bhollis** [comment]
Can you provide some more details about what you did?

**Comment by iawhd** [comment]
Sadly I don't really know what steps are required to reproduce, but every time I open the PWA I have a prompt to update, if I click update the app immediately reopens and still prompts to update.

I believe I have fixed it now by removing the PWA and reinstalling it, so it could possibly be an issue with the service worker caching configuration?

**Comment by bhollis** [comment]
It may have been! Hopefully the reinstall gets it. I don't know what we can do to fix already-installed versions.
