### ISSUE TITLE
Show average light across weapons/armor

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#402]
Not sure how useful this would be, but I've always thought it'd be nice to show the average light across my equipped weapons and my equipped armor, separately. Since I can always move the same weapons across to any character, seeing the average light for their armor (even when the set of "good weapons" is on another characters) seems like it would be a nice way of gauging how far each of my characters is in armor progression.

**Comment by kyleshay** [comment]
we have a formula now (it would need to be slightly modified.)

where would we want to put this, header of each section? would that confuse people? open to ideas, think it could be cool

**Comment by SunburnedGoose** [comment]
I would argue against putting this into the UI.  We don't have account/character screens where we can show analytics.  It's not a useful datapoint either as it just shows how good you are at infusing items.
