### ISSUE TITLE
Cannot type "r", "f", "m" in search bar

### ISSUE THREAD

**Issue by thomaskchan** [DestinyItemManager/DIM#4040]
Version 5.37.1.4106 (beta), built on 7/20/2019, 3:45:01 PM" 

Noticed this when trying to search for is:infuse and f did not work.  Tried this on Chrome and Firefox.

Tried other keys, and "r", "f", and "m" do not work either.

"m" triggers a left sidebar with "Inventory", "Loadout Optimizer", etc.

**Comment by ChadAlanJackson** [comment]
Verified. Triggering shortcut keys.

**Comment by bhollis** [comment]
Thanks for testing it out! I'll have a fix in a minute.
