### ISSUE TITLE
inconsistency in other weapons selected, when comparing archetypes

### ISSUE THREAD

**Issue by archived-2f4dd0** [DestinyItemManager/DIM#4056]
![image](https://user-images.githubusercontent.com/31990469/62007760-4fe77600-b106-11e9-885a-f39485239c91.png)

i've definitely run into other cases where starting archetype comparison from A compares B C D,
but B doesn't compare A C D

**Comment by kyleshay** [comment]
Hmm we compare by the intrinsic perk, but if the item is exotic we fallback to using RPM: more details @ https://github.com/DestinyItemManager/DIM/pull/3724

**Comment by radar3301** [comment]
![image](https://user-images.githubusercontent.com/767328/62102080-d90cc300-b254-11e9-9a65-900fa4acd8a2.png)
Found additional example.

**Comment by bhollis** [comment]
Kyle’s got it - because exotics don’t have an intrinsic perk that defines their archetype, we have to fall back to comparing by RPM.

**Comment by kyleshay** [comment]
i guess if we're comparing a non-exotic by the intrinsic perk, we could also look at the RPM and add any exotics that match that RPM so that results are more consistent.

**Comment by duckmanBR** [comment]
The archetype of Deadpan Delivery is different from the others.  The description is different, so the hash should be different.
Deadpan says "High Damage, High Recoil" while the Y2 says "Hard-hitting, high recoil. Increases rof after kill".

And Acrius didn't appear on the imperial decree/toil and trouble because he probably started the comparison with the 60 RPM version of the weapon (probably from Assault Mag that increases ROF/RDM).

I don't have rose, but I bet the cause is the same: Rose doens't pull the other legendaries (and vice versa) because it's not the same hash.

**Comment by radar3301** [comment]
Rose's description is "Lightweight Frame: Superb handling. Move faster with this weapon equipped.", same as the others. Hash may be different. I wish I knew how to check that...

But you bring up a valid point regarding Deadpan and Imperial Decree. Additionally I confirmed the behavior is as you expect between the 60 RPM and the 55 RPM.

**Comment by delphiactual** [comment]
Rose: https://data.destinysets.com/i/InventoryItem:2429822976/InventoryItem:2189829540

Midnight Coup:
https://data.destinysets.com/i/InventoryItem:1128225405/InventoryItem:1458010786

**Comment by delphiactual** [comment]
I think d2ai can be setup to handle these exceptions...

**Comment by duckmanBR** [comment]
And what about the other part?  Interpolation to find the base RPM of the weapon?

**Comment by delphiactual** [comment]
We can manually tell d2ai where each exotic belongs...

**Comment by delphiactual** [comment]
https://github.com/DestinyItemManager/d2-additional-info/issues/39

**Comment by radar3301** [comment]
Calus Mini-tool fails to compare with Mida Mini-tool.

**Comment by delphiactual** [comment]
Not until we actually start using that data
