### ISSUE TITLE
Loadout Optimizer says "No builds found" even after de-excluding key items

### ISSUE THREAD

**Issue by DHager** [DestinyItemManager/DIM#4069]
Seen on Version 5.39.0 (release), built on 7/28/2019, 10:48:53 PM

### Repro steps:

1. Create a build that relies on a singular key item
2. Shift-click that item to exclude it
3. It says "No builds found"
4. Click the "corner x" on the excluded item icon in the sidebar to "re-allow" it
5. Still says "No Builds found"
6. Go to "Select Perk" popup and choose "Select perks" button to leave it with no changes
7. Now shows the same builds as step no. 1

### Expected Behavior:

Should not require steps 3-6. Should immediately recognize/recalculate that the pre-exclusion builds are possible again.

**Comment by bhollis** [comment]
It's because the allowed light slider gets adjusted. You need to reset that.

**Comment by philkernick** [comment]
I thought we fixed this with #3818.  Has there been a regression?
