### ISSUE TITLE
keyword search for "enhanced" no longer returns all items with keyword in item description

### ISSUE THREAD

**Issue by bobreidx** [DestinyItemManager/DIM#4071]
Greetings also **THANK YOU** FOR THIS PROJECT!!!

I have discovered that, in Chrome on Chrome OS, a keyword search in inventory for the word "enhanced" no longer returns all matches, only some.

Let me know what I could / should do to help or clarify. Cheers!

**Comment by bhollis** [comment]
Could you provide some examples of items you expect to match that don’t?

**Comment by bobreidx** [comment]
> Could you provide some examples of items you expect to match that don’t?

Apologies; traits seem to drop out during Bungie maintenance, so I cannot use DIM to evaluate which items have this trait. As it stands, it seems like it is armor items in DIM after gauntlets that have "enhanced" in the trait description.

**Comment by bobreidx** [comment]
After waiting for Bungie to finish maintenance, it seems like all is back to normal with keyword searches. 1K apologies for the noise.
