### ISSUE TITLE
store.name locale dependent

### ISSUE THREAD

**Issue by rentalhost** [DestinyItemManager/DIM#4082]
Can be `store.name` locale dependent?

https://github.com/DestinyItemManager/DIM/blob/c5f00a07d5cda0ac378dff014452d08304cbe1af/src/app/inventory/store/d2-store-factory.service.ts#L201

Because in portuguese, we should read class name then race. Instead of "Desperta Caçadora" (Awoken Hunter) we should read "Caçadora Desperta" (Hunter Awoken). And too because the class ir normally more important than race, in general. So we should ask for character class before the race.

_I believe that we have some portuguese contribuitors here, so please tell me if my point of view is overrated here._

**Comment by bhollis** [comment]
Great point! I've updated this to be a localized string so you can switch them around.
