### ISSUE TITLE
is:reaquireable only highlights items your current character can equip

### ISSUE THREAD

**Issue by inexorableAce** [DestinyItemManager/DIM#4087]
currently is:reaquirebale search will only highlight items that your current character can equip. 

**examples**
current character is warlock:
![image](https://user-images.githubusercontent.com/29002828/62415032-a155a080-b5f1-11e9-9a4f-f8661cea553a.png)

current character is Titan: 
![image](https://user-images.githubusercontent.com/29002828/62415044-bd594200-b5f1-11e9-9806-57af69c39a72.png)

this may be an API limitation, not too sure haven't looked too deeply into it yet.

**Comment by bhollis** [comment]
Hmm, we're merging together all the collections data from all characters, so this shouldn't be missing anything. It's likely an API thing.

**Comment by bhollis** [comment]
Closing as `is:reacquirable` has been removed
