### ISSUE TITLE
Ios splash screens still not working in beta

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#4096]
I reinstalled my home screen icon and everything. Not sure what’s next to try.

**Comment by chrigi** [comment]
Hey, what a coincidence, I thought I would try my luck at this next and what do I see, you already did the hard work 😄 nice!

I tried it on my 6S as well, no luck. I guess you have seen [this post](https://blog.expo.io/enabling-ios-splash-screens-for-progressive-web-apps-34f06f096e5c)? There he says that it won't work without setting `"mobile-web-app-capable"` to `"yes"`. Which we tried to avoid in #3992 as it would break "Add to Homescreen" for iOS prior to 12.2. You could try adding that meta tag again and see if it works then. Or did you already try that?

**Comment by bhollis** [comment]
That was gonna be my next try. I think it’s OK to turn that on.
