### ISSUE TITLE
Recoil direction stat feedback

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#4102]
We now show recoil direction as a half-circle that hints at direction and spread. This issue is for feedback on that display!

Stuff we know we need to do:

* [x] put this in the compare view
* [ ] figure out how to compare two recoil directions
* [ ] factor in the effect of mods and some perks

Besides that, we want to hear whether this is useful, and how accurate it is.

**Comment by CodyFitzpatrick** [comment]
Hey @bhollis, very cool to see this implemented into DIM. I honestly did not know much about how the value of how this vaguely-defined (from Bungie) weapon stat can affect true accuracy until I came across a YT video from Fallout explaining it.

With that said, I am not seeing this half-circle you are mentioning. Where can I check this out Attached below is what I can currently see from my desktop:

![Austringer in DIM](https://user-images.githubusercontent.com/5438023/62585993-9157ee00-b889-11e9-9696-88ed7aa2d7e7.png)

P.S. While I don't personally think the following (see attached below) should be included/displayed for every weapon, it'd be very valuable to players like my former self that do not know how this stat affects true accuracy. Not sure where this could be implemented into DIM without tucking it away in some obscure place.

![Destiny 2 - Recoil Stat Effect on Shots](https://user-images.githubusercontent.com/5438023/62586265-d892ae80-b88a-11e9-8ea9-d3fb93557a91.png)

**Comment by delphiactual** [comment]
@CodyFitzpatrick are you using https://beta.destinyitemmanager.com

**Comment by CodyFitzpatrick** [comment]
@delphiactual I had no idea that existed -- checking it out now! Thank you

**Comment by bhollis** [comment]
Hmm, the idea was that the display would alleviate the *need* for such an explanation. It's supposed to be a clear pictorial representation of what'll happen when you pull the trigger.

**Comment by knilob** [comment]
I like this idea quite a bit. Hopefully it will only improve once you're able to include the effects of a Counterbalance Mod or different barrels like Arrowhead Break, Chambered Compensator, and Extended Barrel.
