### ISSUE TITLE
Enhancement: Clicking a Perk Adds Perk to Current Search Filter

### ISSUE THREAD

**Issue by m-s-y** [DestinyItemManager/DIM#4109]
Would be super convenient to be able to click on an item's perk and have that perk added to the current search filter.  Being able to quickly see at a glance how many other items share the same perk is key in quickly deciding whether to keep/infuse/shard especially when you've got a loaded-up vault after farming.

**Comment by bhollis** [comment]
That'd be neat, but we have plans for other things to happen when you click a perk. I think this is better suited to a new tool specifically for making keep/shard decisions.
