### ISSUE TITLE
Loadout: Filter excludes the matched items

### ISSUE THREAD

**Issue by michaelnemtsev** [DestinyItemManager/DIM#4114]
Hi, 

Hi, found an interesting issue with the Loadout Optimiser. It seems that there is a bug that excludes the matched items.
For example, I have the following perks filter - Hand Cannon Targeting, Shotgun Scavenger, Unflinching Hand Cannon, Traction, Rocket Launcher Scavenger. I also set the mobility and resilience to be minimum 6. 
The result shows me 3 sets with max mobility+resilience  as 7+6.
 ![image](https://user-images.githubusercontent.com/32570088/62820461-f53f2700-bba7-11e9-8129-3ab04fdf9c51.png)

In these 3 results I have the following Vigil of Heroes hunter's helmet suggested
![image](https://user-images.githubusercontent.com/32570088/62820591-d3df3a80-bba9-11e9-846d-b5aff656817b.png)

However, if I go back to my inventory, and apply a filter "is:hunter is:helmet perk:"hand cannon targeting" I get the following Tangled Web Mark helmet selected, which wasn't a part of Loadout Optmiser result set
![image](https://user-images.githubusercontent.com/32570088/62820504-667eda00-bba8-11e9-88d1-5d433b2004d9.png)
I could not find anything specific in this helmet that might not match my criteria, but it wasn't a part of the Loadout Optimiser for some reasons (a bug?)
Equipping this helmet increases my guardian stats from 7+6+0 to 9+6+0, which is better than the suggested Vigil of Heroes. So it's indeed a better option that the suggested Vigil of Heroes and it must be in the result set 
![image](https://user-images.githubusercontent.com/32570088/62820523-a47bfe00-bba8-11e9-8b10-0d41b9c7291a.png)

Question: why this Tangled Web Mark helmet that I discovered manually, is not appearing in loadout optimiser?
There might be some intelligence in place (I assume) that takes into account other perks that I use (in my case I try to select items with hand cannon targeting + shotgun scavenger) and which might impacts the helmet selection. But it's actually very contextual and I believe all options should be presented to the user. 
 
In my case, I'm building a PvP loadout and the "Shotgun Reserves" perk that this suggested Vigil of Heroes has is aligned with my "Shotgun scavenger" perk for other items, but it's completely irrelevant for PvP, because power ammo is always scarce in PvP and you won't get to maximum. So it's not very relevant perk. 
At the same the Tangled Web Mark perks of Sniper Reserves/Sword Reserves are not applicable in PvP either with the helmet that has Hand Cannon perk.

So it's not clear why the Tangled helmet is not a part of the result set. It has at least a better mobility stat. 

Any insights? 
PS: This is a broad issue that applies to all other items. The same is happening for helmets with Pule Rifle Targeting

**Comment by bhollis** [comment]
Could it be because you've got a mod applied? We try to take into account that you could select different perks, and I wonder if the code that handles that somehow is missing the mod.

**Comment by inexorableAce** [comment]
I think it’s likely there in one of the stat mixes just need to hit the swap button to get it. Equipping a 700 helmet doesn’t take your max power to 700, so the power slider is likely accurate. Since the 700 helm without the mobility mod is the same stat mix as the first row there.

**Comment by bhollis** [comment]
We should be considering the mod though...

**Comment by bhollis** [comment]
Yeah I think this is the general bug we have with stats - I have some pending work I'll finish that should clear this up, once my laptop's back from the shop.

**Comment by michaelnemtsev** [comment]
Hi, the missed Tangled Web Mark indeed has the mobility mod. But without this mod it still matches the required mobility 6. I tried to set mobility 5 in the filtering but this mask isn't appearing either
![image](https://user-images.githubusercontent.com/32570088/62829191-9e832d00-bc3b-11e9-92ba-aa715c99bf95.png)

**Comment by michaelnemtsev** [comment]
> Could it be because you've got a mod applied? We try to take into account that you could select different perks, and I wonder if the code that handles that somehow is missing the mod.

It would be nice to have an option to turn on/off mod consideration in the result set. Because sometimes you need to get the maximum base perks, and then you enhance them with the mods. Depending on the game (PvE/PvP quickplay/PvP Comp) you apply different mods to your armour. So considering mods at the ultimate rule might not be the best option if you cannot have a switch to turn in on/off for resultset

**Comment by bhollis** [comment]
This was fixed in the stats cleanup.
