### ISSUE TITLE
Loadout optimizer minimum power locked to 750 when no perks are selected

### ISSUE THREAD

**Issue by doktor5000** [DestinyItemManager/DIM#4117]
Seen this in the past after loadout optimizer was changed to this 2.0 thingie. Minimum power is locked at 750 for me, and it's neither changeable via the slider nor via the input box. When inspecting the elements, this is what it starts with:

```
<input aria-labelledby="minPower" type="range" min="750" max="750" value="750">
<input aria-labelledby="minPower" type="number" min="750" max="750" value="750">
```

This is the same in regular version and in the beta.

**Comment by doktor5000** [comment]
On a related note, I saw the comment from @bhollis 
 https://github.com/DestinyItemManager/DIM/issues/4069#issuecomment-516276187 although I didn't understand how the light slider gets adjusted and how to reset it ...

**Comment by delphiactual** [comment]
screenshot of your loadout optimizer

**Comment by doktor5000** [comment]
@delphiactual this is what it looks like:
![image](https://user-images.githubusercontent.com/7667040/62827783-2edb5680-bbd7-11e9-81d5-c522b5d8364a.png)

Seems until you select any perk the minimum light level stays locked to 750 ...

**Comment by bhollis** [comment]
The code just updates the range of the slider to be the range of light available in loadouts shown to you. Do you have any suggested loadouts that are less than 750 light?

**Comment by doktor5000** [comment]
> Do you have any suggested loadouts that are less than 750 light?

No, all suggested loadouts are at 750 only, and I haven't even selected anything, that is definitely a bug. To clarify, I just click on loadout optimizer, and don't select anything else. Power is locked at 750, all suggested loadouts are at 750 only. That is definitely wrong.

Once I select any perk, e.g. hand cannon targeting, I can also decrease the power level (to the average power level of the suggested loadout including a piece with that perk).

My primary use case for the loadout optimizer is to look at armor stat distribution first, perks are secondary as I might want to target a certain stat mix and then build the rest around that stat mix. But the issue with the locked power level doesn't allow for that. With the old loadout builder this worked just fine.

**Comment by bhollis** [comment]
I'm not sure that's necessarily wrong. How much stuff do you have at 750? If it can make every stat mix with 750, then that's all it will show...

**Comment by doktor5000** [comment]
Well quite a lot of armor is at 750, but I don't think that it would cover all stat mixes, although I could be wrong.

Hmmm, asking the other way around - is there some small description or video or whatever how the new loadout optimizer is supposed to work? When I scroll down through the various stat mixes, and then select other items for particular slots I can manually select other items.

But is there an option, that the user is able to see all (or most combinations) for a given stat mix? It's quite tedious to select a stat mix, and then clicking on "choose another item" for most slots just to get an idea what perk combinations would be available for a given stat mix ...

**Comment by bhollis** [comment]
I definitely owe everyone a tutorial video. I suspect you don't have any stat mixes that can *only* be made with items under 750 power.

There isn't an option to look at all combinations for a mix - you can see that for many mixes, there are millions of combinations. The intended workflow is for you to narrow down the combinations by locking the perks you want via the menu on the left.
