### ISSUE TITLE
Ghost 'useful location' text issue

### ISSUE THREAD

**Issue by sdholden** [DestinyItemManager/DIM#4119]
![Annotation 2019-08-12 174031](https://user-images.githubusercontent.com/14812533/62900515-542baa00-bd28-11e9-84fe-9028e88b18cc.jpg)

Text on ghost with multiple 'useful locations' displays outside icon boundaries, making neighbours un-readable too...see attached screen shot

**Comment by sdholden** [comment]
But this new feature is something I was just wishing for last week, when I was trying to remember where that d@mn tangle shore ghost got to!  Many thanks!

**Comment by sundevour** [comment]
hi, what platform & browser are you experiencing this on?
normally these can run off the edge but the extra is hidden
![image](https://user-images.githubusercontent.com/31990469/62918675-3e80a980-bd55-11e9-98fb-0bfe22db6f18.png)

**Comment by sdholden** [comment]
Windows 10 with latest Firefox.

**Comment by sundevour** [comment]
cool, thank you for the report! was able to duplicate this issue and i am merging a fix for it.
