### ISSUE TITLE
Sass Support

### ISSUE THREAD

**Issue by ritcheyer** [DestinyItemManager/DIM#412]
Just wondering if converting to Sass is on the roadmap or even desired. I would be interested in helping set this up possibly (if i could find time).

Thoughts?

**Comment by SunburnedGoose** [comment]
v4 is written with SASS.  v3, I leave that up to @bhollis if he wants to add a task runner and create the build step to support SASS.

**Comment by ritcheyer** [comment]
cool. sounds good. I can wait. :)
