### ISSUE TITLE
Dim has not worked for me and many others in the past 24 hours 

### ISSUE THREAD

**Issue by magzzzz** [DestinyItemManager/DIM#4120]
**video for the devs** - https://www.youtube.com/watch?v=_cD8wV_-br0

no ad block
i5-8600k
gtx 1080 
32 gb ram
google chrome
appears for like one frame then goes black

THEY FIXED it use this link  https://beta.destinyitemmanager.com/

**Comment by SunburnedGoose** [comment]
What version of Chrome?

**Comment by magzzzz** [comment]
> What version of Chrome?

newest Version 76.0.3809.100 (Official Build) (64-bit)

**Comment by delphiactual** [comment]
Press `F12` and paste the console logs here

**Comment by magzzzz** [comment]
> Press `F12` and paste the console logs here

sync.service.ts:49 Sync: Storage will not be cleared except by explicit user action.
sync.service.ts:57 Sync: DIM is using 40.95 MB total out of 15.49 GB in storage quota (0%).
Index.tsx:47 DIM v5.40.0 (release) - Please report any errors to https://www.github.com/DestinyItemManager/DIM/issues
react-dom.production.min.js:198 TypeError: Cannot read property 'itemHash' of undefined
    at reducer.ts:17
    at _baseAggregator.js:16
    at _createBaseFor.js:17
    at e.exports (_baseForOwn.js:13)
    at _createBaseEach.js:17
    at e.exports (_baseAggregator.js:15)
    at _createAggregator.js:19
    at reducer.ts:17
    at index.js:70
    at index.js:30
ca @ react-dom.production.min.js:198
n.callback @ react-dom.production.min.js:210
ta @ react-dom.production.min.js:193
ea @ react-dom.production.min.js:193
Fa @ react-dom.production.min.js:217
(anonymous) @ react-dom.production.min.js:220
(anonymous) @ react-dom.production.min.js:250
t.unstable_runWithPriority @ scheduler.production.min.js:18
Tu @ react-dom.production.min.js:250
ku @ react-dom.production.min.js:249
Su @ react-dom.production.min.js:248
Cu @ react-dom.production.min.js:250
notify @ Subscription.js:23
t.notifyNestedSubs @ Subscription.js:65
n.notifySubscribers @ Provider.js:59
t.handleChangeWrapper @ Subscription.js:70
v @ redux.js:220
(anonymous) @ index.js:11
dispatch @ redux.js:636
(anonymous) @ reducer.ts:75
async function (async)
(anonymous) @ reducer.ts:74
(anonymous) @ index.js:8
(anonymous) @ redux.js:475
componentDidMount @ RatingMode.tsx:66
Fa @ react-dom.production.min.js:216
(anonymous) @ react-dom.production.min.js:220
(anonymous) @ react-dom.production.min.js:250
t.unstable_runWithPriority @ scheduler.production.min.js:18
Tu @ react-dom.production.min.js:250
ku @ react-dom.production.min.js:249
Su @ react-dom.production.min.js:248
Cu @ react-dom.production.min.js:250
notify @ Subscription.js:23
t.notifyNestedSubs @ Subscription.js:65
n.notifySubscribers @ Provider.js:59
t.handleChangeWrapper @ Subscription.js:70
v @ redux.js:220
(anonymous) @ index.js:11
(anonymous) @ platform.service.ts:130
M @ platform.service.ts:58
(anonymous) @ platform.service.ts:75
async function (async)
(anonymous) @ platform.service.ts:66
(anonymous) @ platform.service.ts:43
async function (async)
(anonymous) @ platform.service.ts:25
m @ platform.service.ts:22
componentDidMount @ AccountSelect.tsx:88
Fa @ react-dom.production.min.js:216
(anonymous) @ react-dom.production.min.js:220
(anonymous) @ react-dom.production.min.js:250
t.unstable_runWithPriority @ scheduler.production.min.js:18
Tu @ react-dom.production.min.js:250
ku @ react-dom.production.min.js:249
Su @ react-dom.production.min.js:248
bu @ react-dom.production.min.js:245
Ga @ react-dom.production.min.js:243
Du @ react-dom.production.min.js:253
Ru @ react-dom.production.min.js:253
Lu.render @ react-dom.production.min.js:261
(anonymous) @ react-dom.production.min.js:264
Pu @ react-dom.production.min.js:251
Fu @ react-dom.production.min.js:264
render @ react-dom.production.min.js:266
(anonymous) @ Index.tsx:51
Promise.then (async)
(anonymous) @ Index.tsx:37
i @ bootstrap:89
r @ bootstrap:45
t @ bootstrap:32
(anonymous) @ main-9f293a.js:1
react-dom.production.min.js:198 TypeError: Cannot read property 'itemHash' of undefined
    at reducer.ts:17
    at _baseAggregator.js:16
    at _createBaseFor.js:17
    at e.exports (_baseForOwn.js:13)
    at _createBaseEach.js:17
    at e.exports (_baseAggregator.js:15)
    at _createAggregator.js:19
    at reducer.ts:17
    at index.js:70
    at index.js:30
ca @ react-dom.production.min.js:198
n.callback @ react-dom.production.min.js:210
ta @ react-dom.production.min.js:193
ea @ react-dom.production.min.js:193
Fa @ react-dom.production.min.js:217
(anonymous) @ react-dom.production.min.js:220
(anonymous) @ react-dom.production.min.js:250
t.unstable_runWithPriority @ scheduler.production.min.js:18
Tu @ react-dom.production.min.js:250
ku @ react-dom.production.min.js:249
Su @ react-dom.production.min.js:248
Cu @ react-dom.production.min.js:250
notify @ Subscription.js:23
t.notifyNestedSubs @ Subscription.js:65
n.notifySubscribers @ Provider.js:59
t.handleChangeWrapper @ Subscription.js:70
v @ redux.js:220
(anonymous) @ index.js:11
dispatch @ redux.js:636
(anonymous) @ reducer.ts:75
async function (async)
(anonymous) @ reducer.ts:74
(anonymous) @ index.js:8
(anonymous) @ redux.js:475
componentDidMount @ RatingMode.tsx:66
Fa @ react-dom.production.min.js:216
(anonymous) @ react-dom.production.min.js:220
(anonymous) @ react-dom.production.min.js:250
t.unstable_runWithPriority @ scheduler.production.min.js:18
Tu @ react-dom.production.min.js:250
ku @ react-dom.production.min.js:249
Su @ react-dom.production.min.js:248
Cu @ react-dom.production.min.js:250
notify @ Subscription.js:23
t.notifyNestedSubs @ Subscription.js:65
n.notifySubscribers @ Provider.js:59
t.handleChangeWrapper @ Subscription.js:70
v @ redux.js:220
(anonymous) @ index.js:11
(anonymous) @ platform.service.ts:130
M @ platform.service.ts:58
(anonymous) @ platform.service.ts:75
async function (async)
(anonymous) @ platform.service.ts:66
(anonymous) @ platform.service.ts:43
async function (async)
(anonymous) @ platform.service.ts:25
m @ platform.service.ts:22
componentDidMount @ AccountSelect.tsx:88
Fa @ react-dom.production.min.js:216
(anonymous) @ react-dom.production.min.js:220
(anonymous) @ react-dom.production.min.js:250
t.unstable_runWithPriority @ scheduler.production.min.js:18
Tu @ react-dom.production.min.js:250
ku @ react-dom.production.min.js:249
Su @ react-dom.production.min.js:248
bu @ react-dom.production.min.js:245
Ga @ react-dom.production.min.js:243
Du @ react-dom.production.min.js:253
Ru @ react-dom.production.min.js:253
Lu.render @ react-dom.production.min.js:261
(anonymous) @ react-dom.production.min.js:264
Pu @ react-dom.production.min.js:251
Fu @ react-dom.production.min.js:264
render @ react-dom.production.min.js:266
(anonymous) @ Index.tsx:51
Promise.then (async)
(anonymous) @ Index.tsx:37
i @ bootstrap:89
r @ bootstrap:45
t @ bootstrap:32
(anonymous) @ main-9f293a.js:1
reducer.ts:17 Uncaught (in promise) TypeError: Cannot read property 'itemHash' of undefined
    at reducer.ts:17
    at _baseAggregator.js:16
    at _createBaseFor.js:17
    at e.exports (_baseForOwn.js:13)
    at _createBaseEach.js:17
    at e.exports (_baseAggregator.js:15)
    at _createAggregator.js:19
    at reducer.ts:17
    at index.js:70
    at index.js:30
(anonymous) @ reducer.ts:17
(anonymous) @ _baseAggregator.js:16
(anonymous) @ _createBaseFor.js:17
e.exports @ _baseForOwn.js:13
(anonymous) @ _createBaseEach.js:17
e.exports @ _baseAggregator.js:15
(anonymous) @ _createAggregator.js:19
(anonymous) @ reducer.ts:17
(anonymous) @ index.js:70
(anonymous) @ index.js:30
(anonymous) @ index.js:84
(anonymous) @ index.js:30
(anonymous) @ index.js:80
(anonymous) @ index.js:30
(anonymous) @ index.js:80
(anonymous) @ index.js:30
(anonymous) @ index.js:80
(anonymous) @ index.js:30
Object.forwardRef @ SearchFilter.tsx:67
r @ wrapMapToProps.js:41
(anonymous) @ selectorFactory.js:44
(anonymous) @ selectorFactory.js:63
n @ connectAdvanced.js:247
t.handleChangeWrapper @ Subscription.js:70
(anonymous) @ Subscription.js:25
Cu @ react-dom.production.min.js:250
notify @ Subscription.js:23
t.notifyNestedSubs @ Subscription.js:65
n @ connectAdvanced.js:260
t.handleChangeWrapper @ Subscription.js:70
(anonymous) @ Subscription.js:25
Cu @ react-dom.production.min.js:250
notify @ Subscription.js:23
t.notifyNestedSubs @ Subscription.js:65
n @ connectAdvanced.js:260
t.handleChangeWrapper @ Subscription.js:70
(anonymous) @ Subscription.js:25
Cu @ react-dom.production.min.js:250
notify @ Subscription.js:23
t.notifyNestedSubs @ Subscription.js:65
n.notifySubscribers @ Provider.js:59
t.handleChangeWrapper @ Subscription.js:70
v @ redux.js:220
(anonymous) @ index.js:11
dispatch @ redux.js:636
(anonymous) @ reducer.ts:75
async function (async)
(anonymous) @ reducer.ts:74
(anonymous) @ index.js:8
(anonymous) @ redux.js:475
componentDidMount @ RatingMode.tsx:66
Fa @ react-dom.production.min.js:216
(anonymous) @ react-dom.production.min.js:220
(anonymous) @ react-dom.production.min.js:250
t.unstable_runWithPriority @ scheduler.production.min.js:18
Tu @ react-dom.production.min.js:250
ku @ react-dom.production.min.js:249
Su @ react-dom.production.min.js:248
Cu @ react-dom.production.min.js:250
notify @ Subscription.js:23
t.notifyNestedSubs @ Subscription.js:65
n.notifySubscribers @ Provider.js:59
t.handleChangeWrapper @ Subscription.js:70
v @ redux.js:220
(anonymous) @ index.js:11
(anonymous) @ platform.service.ts:130
M @ platform.service.ts:58
(anonymous) @ platform.service.ts:75
async function (async)
(anonymous) @ platform.service.ts:66
(anonymous) @ platform.service.ts:43
async function (async)
(anonymous) @ platform.service.ts:25
m @ platform.service.ts:22
componentDidMount @ AccountSelect.tsx:88
Fa @ react-dom.production.min.js:216
(anonymous) @ react-dom.production.min.js:220
(anonymous) @ react-dom.production.min.js:250
t.unstable_runWithPriority @ scheduler.production.min.js:18
Tu @ react-dom.production.min.js:250
ku @ react-dom.production.min.js:249
Su @ react-dom.production.min.js:248
bu @ react-dom.production.min.js:245
Ga @ react-dom.production.min.js:243
Du @ react-dom.production.min.js:253
Ru @ react-dom.production.min.js:253
Lu.render @ react-dom.production.min.js:261
(anonymous) @ react-dom.production.min.js:264
Pu @ react-dom.production.min.js:251
Fu @ react-dom.production.min.js:264
render @ react-dom.production.min.js:266
(anonymous) @ Index.tsx:51
Promise.then (async)
(anonymous) @ Index.tsx:37
i @ bootstrap:89
r @ bootstrap:45
t @ bootstrap:32
(anonymous) @ main-9f293a.js:1
Show 16 more frames
d2-stores.service.ts:282 Load stores: 1929.3662109375ms

**Comment by delphiactual** [comment]
@48klocs

**Comment by 48klocs** [comment]
I’ll monkey around with stuffing impossible values in in a bit and see if I can reproduce this. Other folks have seen it, but I haven’t been able to trigger it yet.
