### ISSUE TITLE
Long loading...

### ISSUE THREAD

**Issue by et-nat1995** [DestinyItemManager/DIM#4121]
Takes a pretty long time for DIM to load.
Looked through the network tab in the chrome developer tools and its taking ~19s for Manifest/ and about ~40s for the ?component=... request
And It is not my internet speed.
Links are to screen shots of my internet speed and Network tab in chrome developer tools.
[Internet Speed](https://www.dropbox.com/s/w39d50jkbzbfo76/Screen%20Shot%202019-08-13%20at%2012.31.39%20PM.png?dl=0)

[Water Fall](https://www.dropbox.com/s/f3ntc57lzdl7dap/Screen%20Shot%202019-08-13%20at%2012.38.44%20PM.png?dl=0)

Cleared my browser cache, restarted my laptop, and still takes a while to load.

**Comment by delphiactual** [comment]
https://twitter.com/ThisIsDIM/status/1161348196616101889

**Comment by et-nat1995** [comment]
OHHHHH my bad, I don't follow their twitter. Makes sense, sorry bout that.
