### ISSUE TITLE
Search with accents

### ISSUE THREAD

**Issue by timothe** [DestinyItemManager/DIM#4130]
When using a language with accents (for instance, French), and running a filter with an accent, it doesn't take non-accentuated words in account. 
e.g: "ether" won't find the "Docteur d'éther" weapon.

That kind of search is called accent folding ([info here](https://alistapart.com/article/accent-folding-for-auto-complete/)).

Can we implement that improvement into DIM?

**Comment by delphiactual** [comment]
https://www.npmjs.com/package/shoetest
