### ISSUE TITLE
Live App Does Not Load Anything.  Beta Works Fine.

### ISSUE THREAD

**Issue by jbriggs71** [DestinyItemManager/DIM#4132]
After the 8/13 reset of Destiny 2 the live version of DIM does not load anything on my screen.  This includes the menus.  All I see is the background color.  The beta version is working fine.

**Comment by inexorableAce** [comment]
Yep, there is a fix in beta that Prod does not have yet. It will go to prod on Monday or earlier. We’re discussing that now. 

Thanks.
