### ISSUE TITLE
Countdown timer of how many days are left in a Season

### ISSUE THREAD

**Issue by DeFlanko** [DestinyItemManager/DIM#4136]
It would be nice so that we can better time management to know how many days are left in a season.  If this is possible to do i think it could benefit a lot of things.

**Comment by bhollis** [comment]
@sundevour what do you think about this? The info isn't in DestinySeasonDefinition, so it'd have to be maintained by hand.

**Comment by sundevour** [comment]
extremely easy & happy to maintain, but this just branches off into a "today in destiny" type featureset that it feels like we avoid.

give me a fresh tab and i'd do this, dailies, nightfalls, everything else, but so do some other great websites.

**Comment by sundevour** [comment]
i think @delphiactual is maintaining basically this info by hand already anyway?

**Comment by delphiactual** [comment]
Yes I curated dates from any source with some guesses thrown around based on historical data.

**Comment by bhollis** [comment]
This appears to be both more important, and easier to achieve, in Shadowkeep.

**Comment by justrealmilk** [comment]
Why does it need to be manual?

![image](https://user-images.githubusercontent.com/156681/66663178-8bb5c480-ec8d-11e9-9398-fdb81afbc643.png)

**Comment by delphiactual** [comment]
This wasn't provided pre-Shadowkeep

**Comment by delphiactual** [comment]
Closed by #4385
