### ISSUE TITLE
Enhancement: Change "Back Up Data" on settings tab to "Import or Back Up Data"

### ISSUE THREAD

**Issue by CodyFitzpatrick** [DestinyItemManager/DIM#4145]
As a fast reader (truly just a skimmer), it took me a bit to realize that the JSON file I exported all my notes, loadouts, etc to could be used to re-import this same data into DIM.

I suggest changing the title of this section, because prior to me reading every word on the settings tab/page, I thought the only format possible for import was CSV, as that was what I noticed at the very bottom.

Silly, I know, so not sure how others feel about this.

Would be a quick change since it's just text -- honestly wanted to add this issue here so I can add it to my PR when I finally get some time to add/modify code to this amazing app.

**Comment by bhollis** [comment]
We phrased it as a "backup" that you could use to restore your data - could you go into a little more detail about what was unclear or how the wording could be improved?

**Comment by CodyFitzpatrick** [comment]
@bhollis I think it'd enhance UX to change "Back Up Data" to "Back Up Data or Import Data" / "Back Up or Restore Data" / "Back Up or Import Data" here, at the bottom of the settings tab:

![Back Up Data - DIM - 08 20 2019](https://user-images.githubusercontent.com/5438023/63320807-eb769b80-c2ec-11e9-8352-dda0d53604cf.png)

I did not know that you could import until reading the text within the drag-and-drop upload area. It doesn't help that there is no button for importing, like there is for downloading a backup. 

Typically the titles of sections indicate their purpose, so I didn't know until reading every word on the settings tab that I could import a previous JSON export. Perhaps the drag-and-drop area should have a title of its own, e.g., "Import Data"? Just some thoughts.

I absolutely love this app and just want to improve it, especially for skim readers like myself, as to more easily find desired functionality within it. 😃

**Comment by kyleshay** [comment]
Maybe if the two buttons looked more alike? 
`MANAGE DATA`
`[ v Back up DIM data ]` `[ ^ Import DIM data ]`

**Comment by CodyFitzpatrick** [comment]
@kyleshay This is what I'm thinking as well. While I completely understand the drag-and-drop section, unless there's a title above it saying it's for importing, it seems to fall under the Back Up title. Just some minor UI stuff.

**Comment by bhollis** [comment]
Check out https://github.com/DestinyItemManager/DIM/pull/4160 and let me know what you think.
