### ISSUE TITLE
Accidentally clicked shift+2

### ISSUE THREAD

**Issue by LZRDLEG** [DestinyItemManager/DIM#4148]
Clicked shift+2 after dropping my mouse and accidentally selecting a weapon mod.  Now, every single shader, mod, consumable, transmat effect, ornament, etc. is tagged as (insert shift+# here).  I have gone through and tried shift 2,3,4 etc.

Is there a shift+ ? to undo a tagging? Is there a cheat sheet of all DIM shortcut codes?

edit:  Cannot undo the tagged as, since these items do not have the tagging feature drop down.
edit: Yes, I went in and restored from Google Drive.  

Thanks

**Comment by bhollis** [comment]
Wow, that's a fun bug. Shouldn't have been able to tag those (yet).

To unset a tag you can hit shift+2 again (the same one). 

The cheat sheet is accessed by hitting "?"

**Comment by LZRDLEG** [comment]
Thank you.  I could have sworn I went through and hit all of the shift numbers again trying to clear this.  By cheatsheet, I meant more shortcuts, inserts, etc. that are not in the ? help file, such as shift+? for tagging.

**Comment by bhollis** [comment]
I think all those hotkeys are in the cheat sheet: 
![image](https://user-images.githubusercontent.com/313208/64070054-496c8280-cc0d-11e9-81d1-0478fc6bbf9c.png)
