### ISSUE TITLE
Character column is highlighted red

### ISSUE THREAD

**Issue by LZRDLEG** [DestinyItemManager/DIM#4165]
Any idea here?
![Screen Shot 2019-09-01 at 9 04 13 PM](https://user-images.githubusercontent.com/54189418/64086153-32588e00-ccfc-11e9-9552-db25132861a6.png)

**Comment by LZRDLEG** [comment]
For some reason, the emblem I have on is doing it.  ??

**Comment by bhollis** [comment]
The background color is tinted based on what emblem you equip. You equip a red emblem, get a red background. The colors are provided by Bungie, but we use a desaturated/darker version.
