### ISSUE TITLE
stats oddness roundup

### ISSUE THREAD

**Issue by sundevour** [DestinyItemManager/DIM#4174]
all RPMs capped at 100
`stat:rpm:=100`
![image](https://user-images.githubusercontent.com/31990469/64207189-ff73de80-ce50-11e9-94d8-97fb378bdf92.png)

bows have charge time, displayed as bar (in addition to draw time)
![image](https://user-images.githubusercontent.com/31990469/64207476-917be700-ce51-11e9-9237-5d0ac9f40738.png)

some bows have drawtime capped at 100
![image](https://user-images.githubusercontent.com/31990469/64207558-b6705a00-ce51-11e9-81b3-e40c259a30dc.png)

**Comment by sundevour** [comment]
threat level (7 natively) shows a mag of 9(+2) with appended/extended mag. this should be only a +1 for all of: appended("increases")/extended("greatly increases")/tactical("slightly increases")

![image](https://user-images.githubusercontent.com/31990469/64211703-d4db5300-ce5b-11e9-8204-cfc391c254db.png)

**Comment by sundevour** [comment]
per twitter report https://twitter.com/k0hum/status/1168853908657074176

![image](https://user-images.githubusercontent.com/31990469/64213695-a01eca00-ce62-11e9-8f02-b862f6fd9b38.png)

**Comment by bhollis** [comment]
![image](https://user-images.githubusercontent.com/313208/64222577-732fde80-ce85-11e9-820c-479816369f40.png)

This bow is missing Accuracy and Inventory Size...

It also has charge time which is really a stat on this bow... https://db.destinytracker.com/d2/en/items/3410721600

**Comment by sundevour** [comment]
no complaints here
