### ISSUE TITLE
Compare class items not working.

### ISSUE THREAD

**Issue by gbravery** [DestinyItemManager/DIM#4180]
On the beta version of DIM on Chrome 77.0.3865.65 (Official Build) beta (64-bit) , I am trying to compare Class items (Titan marks in my case).

When I click the Compare Item icon, no window appears as it does for everything else.
The functionality then start to not work for other items - I have to move from Inventory to another section to make it work again.

**Comment by duckmanBR** [comment]
I don't have a titan, but can reproduce on my warlock.
Compare works fine until I try to compare a class item. Then it stop working.

I'm on mobile so I can't investigate more.

**Comment by inexorableAce** [comment]
I had a report of this on Discord today as well, this was the console. Also talked to @bhollis about it and I think he has an idea about it. 
![image](https://user-images.githubusercontent.com/29002828/64375406-df305500-cff3-11e9-8aed-ddf553efe856.png)

**Comment by thomasrussellmurphy** [comment]
I've got the same behavior with `DIM (Destiny Item Manager)
Version 5.66.0 (release), built on 1/20/2020, 6:01:22 AM`.

Steps to reproduce:

1. Baseline: click an item, get a pop-up with item details
1. Search to filter items, e.g. `"threat level"` or `is:warlock is:helmet devotion` to have a nice, short set of results to compare
1. Press the "Compare filtered items" in the search bar, get no comparison dialog
1. Click an item, get no display of item details

Workaround: don't use "Compare filtered items" button; if UI stops working on the Inventory tab, change to another tab and return to Inventory to re-enable pop-up with item details.

Question: does the comparison dialog depend on external scripts from any of `content.googleapis.com`, `raw.githubusercontent.com`, `tracker.gg`, or `vendorengrams.xyz`? My allowed scripts while accessing DIM are `destinyitemmanager.com`, `bungie.net`, `google.com`, and `gstatic.com`.
