### ISSUE TITLE
Postmaster count is lower than the actual item count it holds.

### ISSUE THREAD

**Issue by scorp508** [DestinyItemManager/DIM#4182]
I've recently noticed my postmaster often has more items than DIM is reporting even though DIM is properly showing all of the icons. My hunch is any item with the label "You must go to the tower to retrieve this item." is not being counted towards the total. 

As I type this I have 9 items in the postmaster and DIM shows all 9 item icons and all of their detail. However beneath the icons it shows "7 Collect Postmaster."

Two of the items have the "You must go.." note when you click them.

I completely understand DIM can only collect 7 of the 9 items via the API, however the # in front of "Collect Postmaster" is something I glance at quickly to decide if it is safe to start new activities without cleaning out the postmaster.

**Comment by inexorableAce** [comment]
The button is telling you what that action is going to do, you’re going to pull 7 items from postmaster if you click it. The counts is a different issue entirely. You can follow the discussion on that in this PR #4073
