### ISSUE TITLE
Drag and drop not working since yesterday afternoon ..

### ISSUE THREAD

**Issue by directnrg** [DestinyItemManager/DIM#4183]
Hello!

So I already tried to load DIM in other browsers and it haves the same problem. I tried also to copy the link from another browser as a user did according to what he said on Reddit. His method was to copy the link to chrome (updated) or prefered browser and and still not working.

Any ideas on how to fix the issue? Drag and drop is such a usefull tool. Thanks for your amazing work.

**Comment by delphiactual** [comment]
What browsers, what versions, console logs from any of them....

**Comment by directnrg** [comment]
browsers tested:
Chrome and edge last versions up to date.

UPDATE: somehow it is working right now.. I did nothing and it seems that was not loading properly.
checking the log in the chrome console I got no errors this time.

CHROME VERSION |   | 76.0.3809.132
OS VERSION |   | Windows NT: 10.0.18362
DIM v5.44.2
