### ISSUE TITLE
DIM shows multiple weapons having > 100 recoil

### ISSUE THREAD

**Issue by jerrycarlson** [DestinyItemManager/DIM#4187]
I'm using the very latest Windows x64, Google Chrome x64, and DIM.

I have 13 weapons in inventory that DIM indicates as having a recoil direction of more than 100.  Some are exotics and the rest are legendaries.  Some have catalysts/mods/masterworks and the rest are plain.  There are multiple different weapon types represented.  Also, not all members of a particular weapon model show the same error (e.g., I have multiple Trust hand cannons but only one shows the error).

I don't when this behavior first appeared; I just noticed today.  I have attached a couple of screenshots showing examples of this glitch, as well as a screenshot showing how my multiple Trust hand cannons show up in the compare panel).

FWIW, here is the list of my affected weapons:

1. Spare Rations (hand cannon)
2. Trust (hand cannon)
3. Smuggler's Word (sidearm) (two of mine show the error)
4. Pillager (submachine gun)
5. Lonesome (sidearm)
6. Sturm (sidearm)
7. Bug-Out Bag (submachine gun)
8. Riskrunner (submachine gun)
9. Vestian Dynasty (sidearm)
10. Skyburner's Oath (scout rifle)
11. Sunshot (hand cannon)
12. D.A.R.C.I. (sniper rifle)

![example 1](https://user-images.githubusercontent.com/9376071/64587125-ec3aa480-d363-11e9-99ca-2856bb4639cd.PNG)
![example 2](https://user-images.githubusercontent.com/9376071/64587131-f0ff5880-d363-11e9-868a-d937e21cb1d9.PNG)
![comparison of trust HCs](https://user-images.githubusercontent.com/9376071/64587135-f5c40c80-d363-11e9-83c3-bd3a536dcf6b.PNG)

**Comment by jerrycarlson** [comment]
Note: the DIM beta site shows the exact same errors.

**Comment by delphiactual** [comment]
closed by #4200
