### ISSUE TITLE
item count is unintuitively vacuuming up everything

### ISSUE THREAD

**Issue by sundevour** [DestinyItemManager/DIM#4195]
![image](https://user-images.githubusercontent.com/31990469/64852375-1ee7d580-d5ce-11e9-9c67-fd8d6d8540bb.png)

the item count includes my traveler's chosen sidearm on this page, plus it's string matching a socket's text in 2 characters' copies of FALLEN TRANSPONDER over in `progress > quest items`

**Comment by bhollis** [comment]
Yup. They’re items in inventory, they’re just not shown on this page. This is one of those features that seems simple but is really difficult to get right and keep performant...
