### ISSUE TITLE
can't expand bottom vendor on mobile

### ISSUE THREAD

**Issue by sundevour** [DestinyItemManager/DIM#4197]
![image](https://user-images.githubusercontent.com/31990469/64907168-ef0b0180-d6a3-11e9-8b52-42577d2d6d40.png)

once the bottom vendor shaxx is collapsed, i can't uncollapse it on beta/app mobile

i can get the yellow collapse arrow hover effect on all collapsibletitles but that one, so i think taps aren't reaching the title bar element. maybe something to do with recent mobile css layout adjustments?

**Comment by inexorableAce** [comment]
Those aren’t in app yet I don’t think, won’t go till Monday.

**Comment by sundevour** [comment]
lmao pretty sure  it's the "browser unsupported", invisible, blocking click events

**Comment by sundevour** [comment]
![image](https://user-images.githubusercontent.com/31990469/64907693-b6225b00-d6aa-11e9-8c6d-60a5d2385944.png)

the animated display:none is not actually applying, it's just opacity 0 and sitting on top of page content.

**Comment by inexorableAce** [comment]
Ahhh if it has an animation on opacity (since display can’t be animated) and we want to keep that animation, we just need to add `pointer-events: none` to then end state of that animation.

**Comment by sundevour** [comment]
well pointer events none could be turned on all the time anyway, or `visiblity:hidden` can just replace the unanimatable display property
