### ISSUE TITLE
Show subclass on classes

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#4201]
This would require some mapping, but it'd be great to show which subclass is active on the class icon. 

@inexorableAce do you know what icons we could use? I guess we could use text as well.

**Comment by sundevour** [comment]
there's perk icons for sub-path branch upgrades, so you could just curate a (probably super-related) one from each

**Comment by inexorableAce** [comment]
I see you guys found the “way of” icons. I’d go with those if this is something you’re interested in doing. 👍

**Comment by bhollis** [comment]
This is wonderfully implemented in https://github.com/DestinyItemManager/DIM/pull/4292
