### ISSUE TITLE
enhancement request for randomizing loadout

### ISSUE THREAD

**Issue by s-diniro** [DestinyItemManager/DIM#4206]
I really like the randomizing feature. I especially like the granularity to randomize _just_ the weapons.

Can you take it 1 step further by allowing us to randomize not only weapons, but specifically weapons we've tagged as "favorite"? i.e.:

- Randomize (all)
- Randomize - weapons only
- Randomize - Favorite weapons only

Thanks!

**Comment by bhollis** [comment]
Thanks for the suggestion! Unfortunately we have limited space for buttons - we're already pushing it with the "weapons only" button.
