### ISSUE TITLE
5.46.0.4740 (beta) layout looks to be broken

### ISSUE THREAD

**Issue by thomaskchan** [DestinyItemManager/DIM#4231]
Version 5.46.0.4740 (beta), built on 9/17/2019, 8:53:01 PM

![Screen Shot 2019-09-17 at 9 16 52 PM](https://user-images.githubusercontent.com/13026069/65111440-edd22100-d990-11e9-9d8b-ea65f3304b91.png)

The layout seems to be broken after the latest update.

**Comment by thomaskchan** [comment]
Tested in both Chrome and Firefox.  Noticed #4221 has some CSS grid changes?

**Comment by bhollis** [comment]
Yup, we're working on it.
