### ISSUE TITLE
Review is unavailable

### ISSUE THREAD

**Issue by rentalhost** [DestinyItemManager/DIM#4246]
It seems broken, I guess.

![image](https://user-images.githubusercontent.com/421851/65365810-0d688400-dbf3-11e9-89b8-cb4acfaec972.png)
![image](https://user-images.githubusercontent.com/421851/65365811-15282880-dbf3-11e9-84b2-cdec5a45c268.png)

**Comment by delphiactual** [comment]
https://twitter.com/ThisIsDIM/status/1171988684977201153?s=19
