### ISSUE TITLE
Loadout optimizer fails to find optimal loadouts (D1)

### ISSUE THREAD

**Issue by quetschke** [DestinyItemManager/DIM#4252]
Currently the beta fails to find the top tier loadouts for Destiny 1. It finds:
![image](https://user-images.githubusercontent.com/5354403/65378366-fbcbbe80-dc7c-11e9-8f74-0b80d602c0a2.png)

But it misses (for example):
![image](https://user-images.githubusercontent.com/5354403/65378380-1b62e700-dc7d-11e9-8833-700d5a0bc3d3.png)

**Comment by bhollis** [comment]
When did this start happening?

**Comment by bhollis** [comment]
I think I'll need more info to be able to figure this out - I haven't played D1 since D2 came out, and this old Loadout Optimizer is the one bit of code I really don't understand. Can you identify anything interesting about the items that are missed? What are their stats? What perks do they have?

**Comment by quetschke** [comment]
I don't know exactly when it started, but I used the loadout optimizer either two or three weeks ago and it worked just fine. So, the bug is three weeks old at max.

**Comment by delphiactual** [comment]
https://github.com/DestinyItemManager/DIM/commit/f89afdd9a19d5c6dfe347cef2c35383a94488126

**Comment by bhollis** [comment]
I’d be more suspicious of the changes to stats, but I couldn’t see anywhere that’d matter. The LB code does a lot of wacky stuff though, so it’s hard to tell.

**Comment by bhollis** [comment]
@quetschke I just pushed a change to beta - wait 10 minutes for it to deploy, then give it a try and let me know if it works better. I can't really repro this myself.

**Comment by delphiactual** [comment]
after this commit I went from `5/5/0` to `5/5/2`

**Comment by quetschke** [comment]
> 
> @quetschke I just pushed a change to beta - wait 10 minutes for it to deploy, then give it a try and let me know if it works better. I can't really repro this myself.

Yes, it works! I'm back to tier 12. Thanks
