### ISSUE TITLE
Lost new item from post master 

### ISSUE THREAD

**Issue by jsiZZLE7X7** [DestinyItemManager/DIM#4269]
DIm glitched out when I was trying to pull my sole survivor with 4th times the charm and firing line. It was the last weapon I got and it was wiped out of post master. For some reason it thought it was the first thing I got. Something glitched and I have been beating myself up over this pretty badly

**Comment by jsiZZLE7X7** [comment]
So sequence of events
got sniper from reckoning
attempted to pull, it looked like it was loading
-went to orbit
all items in reckoning went to post master, 
if this was normal, anything already in post master would have been pushed out and sole survivor would have been there since it was the last unlock and only like 10 items went in there, but somehow, it still got pushed out (I think) because now it's gone

**Comment by jsiZZLE7X7** [comment]
My battle tag is Jsizzle7x7#1248

**Comment by kyleshay** [comment]
Hmm, DIM doesn't have any way of deleting items. Are you sure the item didn't pull and is in your vault? Sometimes the pull from postmaster button will move items around to make space. 

There isn't a way for us to delete or return items so I'm not sure how much a help we can be :(.

Thank you for the report. We'll keep an eye out for similar reports in the future to see if we can make it happen again. If so we'll figure out how to repro and forward the issue to Bungie to see if it is something that they can fix on their end.

**Comment by jsiZZLE7X7** [comment]
Like I said, I don't think it was "deleted" I think the fact that I tried pulling it into my inventory and going to orbit somehow glitched it where the item got put back in the post master? and the other items on the floor pushed it out when they went to my post master. I heard that it was possible to retrieve lost items, it is good to know that it is not possible. It is no worries. I will eventually grind for a new one.. Thanks for the quick reply.
