### ISSUE TITLE
DIM is not colorblind friendly

### ISSUE THREAD

**Issue by Mulchman** [DestinyItemManager/DIM#427]
Apparently these colors are different (boy it's fun being colorblind): ![its so fun being colorblind](http://i.imgur.com/TmUm9Wh.png)

As they show in the item view, a colorblind person still can't tell the difference: ![yay so fun](http://i.imgur.com/yiarjQr.png)

Personally, I'd love it if the element icon was on an item somehow, instead of using a title bar background fill, or primary stat background fill, or tiny triangle fill when primary stat is not turned on.

**Comment by TheHandsomeCoder** [comment]
I'm wondering could this be of some use?

https://github.com/btholt/postcss-colorblind

**Comment by Mulchman** [comment]
If a build was made that supported the protanopia mode that's mentioned, I
could certainly help test.

Alternatively, drawing the element icon on more places might be enough to
help differentiate without adding explicit color blind support.

**Comment by Mulchman** [comment]
Reddit user *jaycarozzi* mentions this about the armor grading % colors

> yeah, I used that too, but I mean regarding item quality. Orange and red and green look the same to me :(

**Comment by bhollis** [comment]
That's fair, but there are numbers, right? What would be better?

**Comment by Mulchman** [comment]
Yeah... I don't know.  I'm cool with the numbers but I guess other
colorblind people aren't...?

**Comment by Mulchman** [comment]
I ran postcss-colorblind and for my type of colorblindness (protanopia), I don't really see a difference.  Album here: http://imgur.com/a/nBUuV

Here's normal (http://imgur.com/7ZU66W6):
![normal](http://i.imgur.com/7ZU66W6.png)

Here's protanopia (http://imgur.com/u2gMCQL):
![protanopia](http://i.imgur.com/u2gMCQL.png)

Here's tritanopia (http://imgur.com/0uAfyAq):
![tritanopia](http://i.imgur.com/0uAfyAq.png)

Can any other colorblind users chime in? (Or does anyone actually care/is this worth pursuing?)

**Comment by Mulchman** [comment]
And I guess to be thorough (http://imgur.com/a/waRNR)-

Here's deuteranopia (http://imgur.com/x6RI1HS):
![deuteranopia](http://i.imgur.com/x6RI1HS.png)

Here's achromatopsia (http://imgur.com/uweOk8t):
![achromatopsia](http://i.imgur.com/uweOk8t.png)

**Comment by bhollis** [comment]
You probably can't see it, but the colorful stat roll bars aren't changing in those screenshots, because postcss can't affect the colors that are applied at runtime. So this isn't representative of what a colorblind person sees.

**Comment by bhollis** [comment]
Let's approach this from a different angle. Color-blind folks, what stuff in DIM is still hard for you to distinguish, now that the elemental icons have been added?

**Comment by SunburnedGoose** [comment]
https://twitter.com/ThisIsDIM/status/762922771152273409

**Comment by bhollis** [comment]
What is there to do? We added the element icons specifically to address
this.

**Comment by SunburnedGoose** [comment]
Glancing support.

We've added a lot of color to the UI.  atm, we're asking users to focus on icons and numbers when color separation would support glancing, which is useful for mentally narrowing down content.

**Comment by bhollis** [comment]
I think I commented before but those screenshots aren't accurate - we set
the colors directly so postcard can't modify them.

**Comment by themacguy2k** [comment]
My son is color blind and I had him look at the interface. Same situation for him with the blue and purple looking the same. He did say that the purple that is used in the weapon icons (behind the icons that represent legendary) is darker and stands out more then the purple used for void coloring. He could tell the difference between the darker purple and the arc colored square on a legendary arc weapon.

Now with keyboard shortcuts coming maybe you can use a toggle to display a large letter over the weapon (A, V, S) by holding a key down or tapping it to toggle on/off for quick spotting weapons. Something big like the "new item" overlay that is being used now so its obvious to see.

**Comment by SunburnedGoose** [comment]
@bhollis I've generated some.  Here's protanopia for example...

![screen shot 2016-08-09 at 11 34 38 am](https://cloud.githubusercontent.com/assets/984608/17524717/537cb140-5e25-11e6-83ef-a91783c3bfa7.png)

![screen shot 2016-08-09 at 11 34 48 am](https://cloud.githubusercontent.com/assets/984608/17524756/719f1eb0-5e25-11e6-848f-5f0f9367a015.png)

**Comment by SunburnedGoose** [comment]
Here's what I can make in Photoshop

![screen shot 2016-08-09 at 11 40 48 am](https://cloud.githubusercontent.com/assets/984608/17524934/2d1ae976-5e26-11e6-9aa3-7ccef8d84744.png)

**Comment by themacguy2k** [comment]
Not sure how convenient this is but there is an app that we use on the iPhone called CVSimulator to show us real time how things look using the iPhone camera. Might be worth checking out for experimenting. I am sure there are android apps as well that do the same thing.

**Comment by bhollis** [comment]
@themacguy2k thanks for the feedback. As far as the A/V/S display - are the icons not enough?

**Comment by bhollis** [comment]
I think I put some links to alternate color palettes in the original item quality PR, but it's probably worth revisiting - IMO those are the biggest offenders. Maybe check out http://colorbrewer2.org/ ?

**Comment by bhollis** [comment]
Would it be possible to resolve this in favor of targeted issues ("item quality colors are not distinguishable", for example?) I'm still not sure what's actionable here.

**Comment by Mulchman** [comment]
I haven't had an issue since elemental icons were added. I'm fine if this
is closed... but I'm just one colorblind guy out of many.
