### ISSUE TITLE
Bug: items becoming locked after being moved to character

### ISSUE THREAD

**Issue by phillipspc** [DestinyItemManager/DIM#4271]
Was clearing out a bunch of armor in preparation for shadowkeep when I came across this. Only seems to happen with gauntlets, and doesnt happen _every_ time, but pretty darn often. I'll move an item (individually or by moving a search selection) and after being moved to my character, it becomes locked.

Video of issue: https://streamable.com/5q8ir

This was in Chrome Version 76.0.3809.132, DIM 5.45.0

**Comment by sundevour** [comment]
see https://github.com/Bungie-net/api/issues/764

**Comment by sundevour** [comment]
tldr lockedness spreads from locked items in your vault, to items that pass through with the same name

**Comment by phillipspc** [comment]
@sundevour gotcha. thanks for the info 👍
