### ISSUE TITLE
Can't drag items on Android/Chromebook touchscreens

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#4276]
Got some reports that non-masterworks can't be dragged on certain platforms. This points to an issue with switching to real images instead of background-image divs. We could try `-webkit-user-drag:none` on images and see if that fixes.

**Comment by bhollis** [comment]
Just pushed a tweak to beta - @delphiactual @sundevour @inexorableAce do you have the ability to test this on Android?

**Comment by kyleshay** [comment]
Looks good on beta with my Android Pixel 1. Can long press and the context menu doesn't open. 

Confirmed my phone was also seeing the issue by trying it on prod, where it is still bringing up the menu.
