### ISSUE TITLE
Show effect of perk/mod on stats on hover

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#4278]
When you hover a perk or mod, we should show what it'd change on the stat bars

**Comment by ryan-rushton** [comment]
I might pick this up if no one else is working on it.

**Comment by bhollis** [comment]
I was mostly waiting for perks to show up again so this could be tested. It'd be kind of theoretical right now. But feel free to grab it once they're back and #4513 has landed.
