### ISSUE TITLE
Shadowkeep: Armor 2.0 

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#4280]
https://github.com/Bungie-net/api/wiki/2.4.0-(Shadowkeep)-API-Changes

* [x] Show energy available and energy used
* [x] Show energy type requirement
* [x] Show new stats
* [x] Make stat-modifying mods show the correct modifications
* [ ] Add new stats to CSV

**Comment by cmamatey** [comment]
Apologies if this belongs elsewhere or is already mentioned elsewhere: at first glance, it looks like 2.0 armor may show up as 'masterworked' when energy level is 5 instead of waiting until 10.

**Comment by bhollis** [comment]
That’s right. We have that in another issue but I suspect it’ll be solved by general Armor 2.0 support

**Comment by bhollis** [comment]
https://github.com/DestinyItemManager/DIM/issues/4333

**Comment by sundevour** [comment]
https://github.com/DestinyItemManager/DIM/pull/4398
item popup underway here

**Comment by sundevour** [comment]
potentially plan ahead in
`Make stat-modifying mods show the correct modifications`
for the possibility of comparing minus mods

mods are transitory now, comparing armor is going to rely on being informed about the armor's base stats
