### ISSUE TITLE
Move XP bar from character tile to Milestones

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#4296]
Since Shadowkeep doesn’t worry about levels, we should move the XP progress bar into a synthetic milestone like we have with well rested. Ideally the icon should be whatever engram a level up provides, though I’m not sure we can get that programmatically.

**Comment by melanieseltzer** [comment]
Would love to take a crack at this... do you think this is a beginner friendly issue?

**Comment by bhollis** [comment]
Yeah! After getting to play for a bit, it looks like this is the same issue as https://github.com/DestinyItemManager/DIM/issues/4326 as the XP/bright engrams stuff has been replaced with the Seasonal Rank track. 

We could either choose to have a whole new section in Progress for Seasonal Rank, or we could do a single fake milestone that just shows progress to the next unlock, in Milestones. I’m not sure which would be nicest.

**Comment by bhollis** [comment]
Here's how the Companion displays it. Might be overkill for our Progress page though.

![Image from iOS](https://user-images.githubusercontent.com/313208/66089061-82608580-e532-11e9-8e22-d0c039f6a873.png)
