### ISSUE TITLE
D2 Ratings - the return of highlighted reviewers

### ISSUE THREAD

**Issue by 48klocs** [DestinyItemManager/DIM#4297]
Highlighted reviewers will be returning to D2 with Shadowkeep.

- [ ] solicit a list of reviewers - we'll need to get them to the DTR masterminds in order for them to be active (gamertag would be good, membershipId/membershipType would be better)
- [ ] update fetch to accommodate wherever highlighted reviewers will be returned
- [ ] make sure that review display continues to surface highlighted reviewers up top and display them with a little shine
- [ ] make sure that highlighted reviewers are factored in to the raw votes -> score algorithm

**Comment by kyleshay** [comment]
Could we somehow link wishlists and highlighted reviewers on the dtr side, would that make sense?

**Comment by 48klocs** [comment]
DTR doesn't have any direct dealings with wish lists - I'm planning to build out support for their new item database interface when it goes live, but otherwise reviews and highlighted reviewers live on their side (highlighted reviewers are manually added on their end) and will be fed to us in ratings/reviews calls.
