### ISSUE TITLE
Wish lists - presenting suggested mods/masterworks

### ISSUE THREAD

**Issue by 48klocs** [DestinyItemManager/DIM#4299]
Wish lists, in their current incarnation, ignore certain perks (shaders, cosmetics, mods, masterworks) and focus on things baked in to an item, instead of those things that you can plug in to an item whenever.

That said, mods and masterworks are part of the game economy, and if we can figure out a design for dealing with cases where a wish list has expressed a desire to see (for example) an Icarus mod and a stability masterwork on a Waking Vigil with this and that perk, that we can highlight the fact that you've got that mod/masterwork already (which is easy) or that this is the mod/masterwork that's been suggested.

**Comment by Kalus** [comment]
What do you think about adding a second state to to the thumbs-up icon? In my mock, the outline thumb is meant to be analogous to an unselected perk. Clicking/Tapping the mod would bring up the mod tray as usual, with the green thumb on the desired mod.
![issue_4299-mock1](https://user-images.githubusercontent.com/137438/69652913-5fd57f00-1040-11ea-9815-a4e50a68ffc6.png)

**Comment by bhollis** [comment]
@48klocs still think this is a thing?

**Comment by 48klocs** [comment]
My thought on it was that adding masterworks to a list kind of pushes things further into lottery odds.

There's probably a select few people that would scrap an item with all the perks they want but the wrong MW, but I'm definitely not one of them.

If we want to go that route, I'd suggest baking it in to the upcoming wish list format, with a few notes.

- masterwork should be treated as an optional perk
- you shouldn't be able to specify the MW level, simply that you're targeting `Impact` or what have you
  - otherwise a level 1 `Impact` MW wouldn't light up because the list called for levels 5-10 or what have you

**Comment by bhollis** [comment]
Linking to https://github.com/DestinyItemManager/DIM/issues/10313.
