### ISSUE TITLE
Invalid Cookie

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#43]
On load, we might encounter a state where the browser provides us with a cookie to Bungie.net, but that cookie is invalid.  

How does the application resolve that state?

**Comment by kyleshay** [comment]
still an issue, @SunburnedGoose? i haven't run into this condition (maybe I do, but I just re-login to b.net)

**Comment by SunburnedGoose** [comment]
This was an issue while I was working v3, between March-April'15.  I think Bungie was making changes to their cookies and making my life hard. :/

Can be closed.
