### ISSUE TITLE
Internals - continue auditing for uses of "curated rolls" when we mean "wish list rolls"

### ISSUE THREAD

**Issue by 48klocs** [DestinyItemManager/DIM#4304]
Knowing that ontogeny recapitulates phylogeny doesn't make for a particularly great reason that we still call wish list rolls curated rolls throughout (in types, functions, and param names).

I'll probably leave the `CURATED_ROLLS.md` file name alone though, because it's been linked to.

**Comment by bhollis** [comment]
Is this all done?
