### ISSUE TITLE
Sneaky Updates

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#4315]
We badge the menu when there's an update available, but we rely on users to actually hit that button to update. We see a decent uptake on that, but some people do get stuck on old versions. One idea I had was to force a full page reload if there is an update available and somebody navigates to a different page (i.e. from Inventory to Progress), or if they leave DIM running in the background (page visibility hidden / idle timer). That way we could auto-update without interrupting people.

**Comment by sundevour** [comment]
small reminder on this, that i don't think idle detection really works properly

**Comment by bhollis** [comment]
@sundevour can you elaborate? I'm not aware of any issues currently.

**Comment by sundevour** [comment]
my DIM constantly frequently itself idle and stops refreshing inventory, even if i click around, even if i transfer an item. can look into eventually just reminding while idleness was on my mind.
wouldn't really be the end of the world if DIM force refreshed itself while i was doing stuff. just edge cases of people storing their master's thesis in an unsaved notes field

**Comment by bhollis** [comment]
Hmm it'd be interesting to find a repro for that behavior, I thought I'd fixed all the idleness issues.
