### ISSUE TITLE
Clicking on Scorched Hunter Cloak crashes DIM

### ISSUE THREAD

**Issue by Lalo-ATX** [DestinyItemManager/DIM#4323]
I can mouseover my common Scorched Hunter Cloak, but when I click on it, all icons/etc on the screen go away and I'm left with a black screen.

DIM v5.48.1

Windows 10, Chrome 76.0.3809.132 (Official Build) (64-bit)

Console:

![image](https://user-images.githubusercontent.com/19268864/66008965-1d4b5800-e47e-11e9-90fc-043927b4b7ee.png)

[edit] Screenshot showing mouseover. I notice that the power level bar below the icon is missing. This screenshot is right before clicking on the icon.
![image](https://user-images.githubusercontent.com/19268864/66009200-0d804380-e47f-11e9-92eb-a865284ae34e.png)

**Comment by bhollis** [comment]
Thanks, looks like @48klocs update to point to the new DTR path didn't account for socketless items.
