### ISSUE TITLE
DIM not working with the Steam move

### ISSUE THREAD

**Issue by zjjordan** [DestinyItemManager/DIM#4325]
Are there plans to get this working with the move to Steam?  Dim is my goto, going back to the tower for each loadout seems soooooo tiresome now.

**Comment by bhollis** [comment]
You'll have to provide more info about what's not working. Your browser, the version of DIM, what exactly isn't working, etc.

**Comment by zjjordan** [comment]
Browser, IE and Chrome, and the downloaded app on PC.

I had singed in with my steam accout, but as soon as I get in all I see is a message that shows the following:

I would have thought it would be connecting to Steam and not bunjgie.net:

![2019-10-01 22_01_54-Microsoft Edge](https://user-images.githubusercontent.com/12719660/66015454-38c35c80-e498-11e9-9859-6821c3763b74.png)

Maybe this  is just a server side error.   If it should work with the steam account I'll keep trying.

**Comment by bhollis** [comment]
That message means that the Bungie.net API is still throttling requests. There are too many people playing Destiny :-D

**Comment by zjjordan** [comment]
Cool, as long as I know it will work at somepoint I can wait.  Thank you!
