### ISSUE TITLE
I want smash my pc off your head

### ISSUE THREAD

**Issue by snapjd** [DestinyItemManager/DIM#4330]
I used app without issue for 3 years backed you company now I move to pc and try to log in and I get error too many attempts. I see a bunch a photos and everyone having a good time but I got junmp 30 hoops to try to log in and then I get denied access. I want to file a claim with the better business buerue it should not be this hard for a supporter of 3 year to log in to your fucking app! l glad everyone has time to pose picture but no one is can help me log in to you app.

**Comment by DHager** [comment]
Calm the fuck down, dude. You're getting mad an independent volunteers running a fan-made program.

**Comment by inexorableAce** [comment]
The api is being throttled by bungie so the game can have more resources. Thanks for the support though! Have a good one.

**Comment by snapjd** [comment]
I had a bad day please accept my apology.

________________________________

**Comment by snapjd** [comment]
Oh ok, hey sorry fella I apologize and thanks for you prompt replay.
________________________________
