### ISSUE TITLE
DIM not loading

### ISSUE THREAD

**Issue by SirBigTasty** [DestinyItemManager/DIM#4331]
Every time I try to start up DIM it will always give me this error message
![Error Message](https://user-images.githubusercontent.com/56080707/66055999-bd64b800-e536-11e9-9df5-88d6b194baa8.PNG)

Curious if its a problem on my end or a know issue 
V/R 
Mason

**Comment by joshminnie** [comment]
@SirBigTasty All 3rd party APIs are disabled currently by Bungie https://twitter.com/BungieHelp/status/1179323814821400576

**Comment by inexorableAce** [comment]
As noted above bungie has 3rd party apps disabled at the moment. You can still use the companion app for out of game transfers.
