### ISSUE TITLE
Mobile: Header looses stick/float when item popup is open

### ISSUE THREAD

**Issue by duckmanBR** [DestinyItemManager/DIM#4332]
![image](https://user-images.githubusercontent.com/32077894/66068312-be401e80-e523-11e9-88ef-57b047b16ffd.png)![image](https://user-images.githubusercontent.com/32077894/66068332-c7c98680-e523-11e9-9d96-8993ae8caf76.png)

**Comment by bhollis** [comment]
I don't see this happening on iOS Safari or desktop Chrome.

**Comment by duckmanBR** [comment]
Still bugged on Android Chrome on 5.51.0.5358 
I'll check on windows desktop later today.

**Comment by duckmanBR** [comment]
Can't reproduce it either on Windows Chrome
