### ISSUE TITLE
Shadowkeep: Armor 2.0 blues shouldn't be masterwork

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#4333]
![image](https://user-images.githubusercontent.com/313208/66069678-b755e380-e504-11e9-9928-34a83f8055e1.png)

I think we have some logic that assumes a tier 5 item is masterwork, but in Armor 2.0 it's just energy.

**Comment by G4te-Keep3r** [comment]
if you have any pre-sk blue armor still, it shows the same way
