### ISSUE TITLE
Old loadouts created on Blizzard don't work when account is migrated to Steam

### ISSUE THREAD

**Issue by DuMAc9l** [DestinyItemManager/DIM#4337]
I tried to download the old version from Google Drive. There must be 5 loadouts. But not one is displayed.

![image](https://user-images.githubusercontent.com/56096902/66088276-32f67580-e583-11e9-992b-0e7513bef349.png)

**Comment by inexorableAce** [comment]
can you go to settings and screen shot your google drive section for me please

**Comment by DuMAc9l** [comment]
![image](https://user-images.githubusercontent.com/56096902/66088540-24f52480-e584-11e9-910a-6c7ec7698170.png)

**Comment by inexorableAce** [comment]
cool thanks for reporting, we'll take a look

**Comment by bhollis** [comment]
What platform are you on? Did you switch platforms with Cross Save?

**Comment by DuMAc9l** [comment]
PC. I did a transfer from Battle.net to Steam.

**Comment by bhollis** [comment]
OK. I think I know what’s going on. I thought I’d handled this but maybe not. I’ll look at this tonight.

**Comment by DuMAc9l** [comment]
Thank you. You work great!

**Comment by bhollis** [comment]
Should be fixed on beta in a few minutes.

**Comment by DuMAc9l** [comment]
New bug. If you click "edit loadout".

![image](https://user-images.githubusercontent.com/56096902/66142616-6c27f780-e60e-11e9-94e3-033ca96f76de.png)


![image](https://user-images.githubusercontent.com/56096902/66142538-439ffd80-e60e-11e9-8d83-80ec46a9843b.png)
