### ISSUE TITLE
Engrams in the postmaster have a count on them

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#4339]
Each of the engrams in the postmaster has a "2" count on them.

![image](https://user-images.githubusercontent.com/25425159/66105296-42fd6c00-e5fa-11e9-839a-06ba3807c011.png)

**Comment by delphiactual** [comment]
What level is your seasonal artifact?

**Comment by philkernick** [comment]
Level 11.

**Comment by bhollis** [comment]
Huh, that's really odd. I wonder what the API is trying to tell us by saying the amount of the engram is "2".

**Comment by bhollis** [comment]
I have a bunch of engrams from last season and they show the proper amount. I wonder what the factor is.

**Comment by philkernick** [comment]
Update. It was 2 when I screen capped it.  I'm now 3 and when I checked just now it's showing a 3 on every engrams in DIM. Sorry about the confusion.

**Comment by bhollis** [comment]
Weird. So maybe it is the same as your artifact level? Why would that set the amount?
