### ISSUE TITLE
add randomperk or have randomroll also grab the new random perks

### ISSUE THREAD

**Issue by G4te-Keep3r** [DestinyItemManager/DIM#4342]

**Comment by bhollis** [comment]
Can you provide more info on what you want to see happen?

**Comment by G4te-Keep3r** [comment]
Didn't realize this earlier, but ignoring y1/y2 armor, weapons have random rolls and armor has random perks. Either perk and roll need to be clumped together into random/"cant get from collections" or perks needs to be added. I would prefer adding perks as it would give more fine control over searches. Just pointing out that it needs to be added to the list of "new armor system new problems".

**Comment by bhollis** [comment]
is:reaquireable is the search for whether you can get something from collections or not.

For is:randomroll... Armor 2.0 doesn't have perks at all anymore. It does roll with random stats, though. At this point I'm not sure how useful is:randomroll is as a search.

**Comment by bhollis** [comment]
I think I'm going to close this - "is:armor2.0" is the same as a hypothetical "is:randomstats", and "is:reaquireable" is still the right place to go for collections-related stuff.
