### ISSUE TITLE
Loadouts being cleared

### ISSUE THREAD

**Issue by koush** [DestinyItemManager/DIM#435]
My loadouts are randomly being cleared. This did not happen until I started playing on both Xbox and PS4. I suspect it has something to do with Loadout items not being found on one platform vs another, and those loadout items are being deleted from the loadout.

Can't get exact repro steps at the moment, but I figured I'd drop a note in case it's an obvious problem.

Basically
create a loadout for a PS4 character.
create a loadout for a Xbox character.

Use DIM for a while, and one or both of those loadouts get cleared of all items.

**Comment by SunburnedGoose** [comment]
Yeah...  That's a thing.  Loadouts are not bound to the accounts...

We need to modify loadouts to also know which platform when we save them so you don't have this issue.

**Comment by bhollis** [comment]
See #413. I can take a look at this when I'm messing around w/ loadouts that include materials.

**Comment by kyleshay** [comment]
http://www.bungie.net/Platform/Destiny/2/Account/4611686018428939884/Character/2305843009221011538/Inventory/6917529064353753348

actually returns `data.talentNodes[].materialsToUpgrade`

it would be rather intense to have to call that for every item though. suppose it could make the call when the move dialog is opened, but i'm not sure if it's actually worth it.
