### ISSUE TITLE
Stat sum filter

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#4352]
It'd be nice to have a search for the sum of all of an armor piece's stats. That way you could trash all the armor that doesn't pass a certain bar.

**Comment by ryan-rushton** [comment]
@bhollis, mind if I pick this one up next?

**Comment by ryan-rushton** [comment]
To add, I checked it out and the stat:total search is there but it includes the modded values. This would need to be done for all stats or create new filter like stat:baseTotal

**Comment by delphiactual** [comment]
#4517

**Comment by bhollis** [comment]
@ryan-rushton sorry I just forgot to close this. It's already implemented as `stat:total:>55`.
