### ISSUE TITLE
[Suggestion / Improvement] Enable visibility of DIM info in GDrive via toggle switch (or similar)

### ISSUE THREAD

**Issue by CodyFitzpatrick** [DestinyItemManager/DIM#4356]
Title says it all. I've noticed that multiple devices do not have the same info saved on items. I can fix this on my laptop since I can export and import. On mobile, I'm stuck. I wish I could replace the DIM data (assuming it's JSON or similar) in GDrive with the most recent version. 

Honestly a bit confused as to why if all devices are using the same GDrive login that there is different information. How can you tell which of your devices is the "leader" in terms of what is saved there, is what becomes the master data on GDrive?

**Comment by bhollis** [comment]
Export/import should work on mobile. But the plan of record is to abandon GDrive in favor of our own API.

**Comment by duckmanBR** [comment]
It's working on Android.
If nothing changed last time I had this problem, DIM simply uploads a blank file to gdrive.  You just need to recover an earlier copy and everything should work fine from now on.

**Comment by bhollis** [comment]
This is obsoleted by #4418.
