### ISSUE TITLE
Hard to tell if a character stat tier is full.

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#436]
I saw an image of a user's stats for a character and it was hard to tell if a tier was full when it gets really close.  Could we color a full tier for the stats so it's very clear when they are full?

Here, I've marked items with 100% width on the .progress class with a .full class so they are colored in with the orange (not a preference).

![screen shot 2016-03-04 at 4 43 29 pm](https://cloud.githubusercontent.com/assets/984608/13542417/43b96dbc-e228-11e5-8021-829414637dfa.png)

**Comment by kyleshay** [comment]
yeah that works. i think even in-game it shows them as different shades?

**Comment by bhollis** [comment]
The orange is a bit loud though - maybe we could use three shades of grey, or a slightly off-grey for the partially-filled one?

**Comment by bhollis** [comment]
This went out in 3.3.3.
