### ISSUE TITLE
Only 1 item in Vault per line if browser just on half screen

### ISSUE THREAD

**Issue by IevgenSobko** [DestinyItemManager/DIM#4360]
Only 1 item in Vault per line if browser just on half screen.
It would be nice to have 3 or 4 items in a row if there is still space like on characters.
The same issue I have noticed when tried to open DIM on tablet that has inverted orientation in comparison with desktop.
![DIM_on_half_screen](https://user-images.githubusercontent.com/14232100/66252971-52032c00-e76a-11e9-96e9-ebd33a2043a8.png)

**Comment by bhollis** [comment]
I'm unable to reproduce this - are you on the latest version of DIM?

**Comment by IevgenSobko** [comment]
Yes, I'm on the latest stable version.
Could you please attach your screenshot for me to check?

**Comment by IevgenSobko** [comment]
And here also screensbot from tablet Samsung Galaxy Tab S5e
![Screenshot_20191017-071124_Vivaldi](https://user-images.githubusercontent.com/14232100/66977362-50acfa00-f0ae-11e9-9844-a8c63c38010d.jpg)

**Comment by delphiactual** [comment]
See that arrow in the upper left? It means you have an update available.

**Comment by bhollis** [comment]
![image](https://user-images.githubusercontent.com/313208/67137521-a20ed380-f1eb-11e9-8c88-31f86588ce9f.png)

**Comment by bhollis** [comment]
I think I see the issue - you have the item size jacked up to maximum. I can reproduce with that setting.

**Comment by IevgenSobko** [comment]
@bhollis is it possible to use all space awailable and fill all 4 columns? 
For characters all 4 used but for wault only 3.
![Screenshot_20191116-103540_Brave](https://user-images.githubusercontent.com/14232100/68990550-3016c200-085d-11ea-9812-c25b7c5c8755.jpg)
