### ISSUE TITLE
Trash Advisor  for Inventory

### ISSUE THREAD

**Issue by WegDamit** [DestinyItemManager/DIM#4367]
My tresor is full. Always. (like 499 of 500...) 
So, i'd like to see something like a Trash Advisor (or Garbage Collector) in DIM.
This Advisor does stuff like marking item i haven't used (like wasn't transferred to any character) in 10/50/100 Days as neglected,
or this item has very low ratings, 
or is from three years back, 
or ...
No idea what a good set of criteria would be. 

But perhaps some people here have some good ideas.

**Comment by TheHandsomeCoder** [comment]
Anything from Year 1 that has the same roll as what can be pulled from collections would be a good start. These all can be safely deleted afaik

**Comment by delphiactual** [comment]
This is what our search feature is for, as no one will agree on what is considered `trash`

**Comment by bhollis** [comment]
Plan is to handle this via #4377.
