### ISSUE TITLE
Upgrade Workbox

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#4372]
We use Google Workbox to manage our service worker, and we're stuck on version 3. Version 5 is about to be released! We should really update, but I'm honestly scared to do it because service workers are such a nightmare.

https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-v3

**Comment by bhollis** [comment]
Workbox itself has been upgraded! We should also switch our custom code to using `workbox-window`. I'm investigating....

**Comment by delphiactual** [comment]
closed by #4582
