### ISSUE TITLE
Vault Organizer (Inventory Table View)

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#4377]
One of the things people look to DIM for is to answer the question "What should I keep and what should I shard?" We have offered several tools to help with that - Search, Compare, and to some extent Loadout Optimizer, but each have downsides - search is hard to discover, compare is showing its age, and loadout optimizer is complicated and only used for armor. I'd like to introduce a new tool that effectively replaces Compare which is targeted specifically at the use case of looking at your items and tagging them or deciding to delete them.

My idea is to have a table UI - think spreadsheets but with the full value of DIM's display. The initial choice would be what type of item you want to look at - for example shotguns, or helmets, or ghosts. I don't think there's much value in comparing all your hand cannons to your sniper rifles.

Once you choose a type, we'd show a big table of all the items of that type. Search would continue to work to filter them, though this might be a good place to start playing with buttons for search. We'd be able to show our enhanced display for things like stats, perks/mods, etc. Maybe we'd have to offer people the ability to select which columns they want to see, maybe not. The table would be sortable by clicking any heading, and there would be bulk operations (checkboxes w/ range select and check-all) for tagging, locking, moving to vault, etc.

Another thing that'd be amazing here is to have a "tip" column which gives advice like "these perks are redundant" but that can wait until later.

This would be amazing on big screens, but would need work on mobile. I'm intending to do try some dark Hive rituals using CSS grid to try and make something usable on mobile, but this is really intended for sitting down with a big screen and going over everything.

I'd love help designing the UI and understanding what would be important to folks.

This also would provide a natural home for the "spreadsheet download" function.

**Comment by Volk379** [comment]
This is a great idea.
At this time,I'm simply using is:duplicate filter and moving all the lower level / redundant items to my character for deletion.

On a side note, and this may have been already addressed, is there a way to chain filters like is:pulserifle & is:maxpower?

**Comment by bhollis** [comment]
Yup, just type "is:pulserifle is:maxpower"

**Comment by inexorableAce** [comment]
for what it's worth you can make scalable tables with just some css and data-attributes. Won't be spectacular on mobile like a table on a desktop but it will scale and work a lot better I think. https://glitch.com/edit/#!/responsive-table
