### ISSUE TITLE
Allow opening menu with touch interaction from left screen edge

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#4378]
A common mobile pattern is to have a swipe from the left side of the app open a menu. We should replicate that by allowing the menu to be dragged out from the side of the app from the left edge.

**Comment by duckmanBR** [comment]
We use the swipe to change columns.  Would we keep both with the menu coming only if swipe from edge?

**Comment by bhollis** [comment]
Yes

**Comment by kyleshay** [comment]
'gesture navigation' on android 10 makes this a bit tricky (swiping from the left side of a device triggers the 'back' action.)

should have a gesture for swiping to close, but to swipe open-we may need to do something else.

**Comment by bhollis** [comment]
I'm giving up on this - the built in edge gestures are too dominant, and the web platform doesn't have a good hook into edge swipe.
