### ISSUE TITLE
Search Triumphs and Collections

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#4379]
When a search is entered on the Progress or Collections page, we should filter down to records or items that match that search. Rather than expanding the tree and highlighting, I'd like to see those sections simply replace themselves with a stripped-down search results view.

**Comment by sundevour** [comment]
this bumps up against a gripe i have: switching to vendors with an item search already populated, and there being nothing on the page.
this would potentially have the same problem, intersecting with #4195 

i'd like to see this implemented after some kind of barrier comes up between pages search-wise
