### ISSUE TITLE
Estimate new stats for infused item 

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#438]
Someone has figured out a way to estimate the stats for a infused item

https://www.reddit.com/r/DestinyTheGame/comments/499lij/heres_how_intellect_discipline_and_strength/

**Comment by bhollis** [comment]
Cool! We should totally do that.

**Comment by SunburnedGoose** [comment]
from /u/iihavetoes:

> Alright, just so you know, you can calculate the infused stats after the fact within +/-1. After infusing a bunch of things, I noticed that it must be the case that Bungie stores stats as floats/doubles/reals/whatever. They have decimals. (see row 46 here. 33/33 base stats became 34/35 base after infusion). The bonus stat value is deterministic though
You'll want this: https://docs.google.com/spreadsheets/d/1YyFDoHtaiOOeFoqc5Wc_WC2_qyQhBlZckQx5Jd4bJXI/edit#gid=0
It's the most accurate table for "Stat Bonus" nodes that we have so far

and this...

> Oh and /u/cvsppf implemented a stat estimator here using the data from today: https://github.com/CVSPPF/Destiny
You could consult him as well

**Comment by rowanbrendan** [comment]
"Row 46" references this spreadsheet: https://docs.google.com/spreadsheets/d/1LmfQASaU209eIGHX4gaP-XBjh_OwQ6JjLsFT88Z-s7I/edit#gid=1740655688

**Comment by bhollis** [comment]
I wonder how this will work after the April update...
