### ISSUE TITLE
Filter Progress by Activity

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#4380]
Using the d2ai data, we should be able to have a dropdown of activity types (crucible, strikes, Nessus patrol, etc) and filter available pursuits to only those pertinent to that activity. Bonus points for also showing vendor pursuits that match the activity.

**Comment by kyleshay** [comment]
resolved w/ the bounty guide? or did you want to add on to it?

**Comment by bhollis** [comment]
Feels pretty dang resolved
