### ISSUE TITLE
Auto-load recommended wishlist

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#4382]
We should load a recommended wish list (voltron?) automatically if people haven't already set up a wish list. We can do this for existing users as well as new users. The only thing to make sure of is that if somebody has removed the wish list that it stays removed.

**Comment by 48klocs** [comment]
A setting for a URL is in.

Loaded files / external sources are mutually exclusive - choosing one unsets the other. Clearing wish lists (in settings) clears both.

**Comment by michabbb** [comment]
does DIM regularly check if the file at the URL has changed and reloads its content automatically?
or do I have to RESET the wishlist by myself by deleting the list and putting the same URL in?

**Comment by bhollis** [comment]
Yes it checks.
