### ISSUE TITLE
Replace item icon with ornament icon

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#4387]
I had hoped that Bungie.net would send down an `overrideStyleItemHash` with the ornament icon for ornamented items, but it was not to be. So we should do it ourselves by looking at the item's sockets and plugs.

https://github.com/Bungie-net/api/issues/1077

**Comment by sundevour** [comment]
actually seems like bungie didn't do this, but i would still love it since the ornament icons were reworked to look right
