### ISSUE TITLE
Using compare on DIM beta 5.49.0

### ISSUE THREAD

**Issue by yzpmpgq** [DestinyItemManager/DIM#4389]
When selecting an item and using "compare", it shows the same perks for all items.  In the screen attached, the hand cannons don't show perks, but shows all with tactical mag, which they don't all have..  The hammerhead compare screen shows both having Rampage and Feeding frenzy when in fact, the 902 has Feeding Frenzy and High Impact Reserves, while the 750 has Dynamic Sway and Rampage.
![ScreenHunter_75 Oct  07 09 24](https://user-images.githubusercontent.com/13834937/66320707-f610e280-e8e4-11e9-919c-66d166e9dfaa.jpg)
![ScreenHunter_76 Oct  07 09 27](https://user-images.githubusercontent.com/13834937/66320711-f90bd300-e8e4-11e9-8169-5185b949a072.jpg)

**Comment by wein3967** [comment]
I am pretty sure this is a Bungie thing at the moment. All same weapons have the same perks on the Bungie companion app. Additionally, I see the following in DIM when viewing a single item.:
![image](https://user-images.githubusercontent.com/11590326/66321519-50f70980-e8e6-11e9-9981-1073064ea358.png)

**Comment by yzpmpgq** [comment]
Ah, guess I missed that.  Thanks for the info.  I guess a stupid post is
allowed every once in a while. :-)
