### ISSUE TITLE
Generation and storage of test data

### ISSUE THREAD

**Issue by Spawnbroker** [DestinyItemManager/DIM#4390]
I'm at the point where the classes I'm testing need certain objects. Normally, I would create dummy objects and pass those in with fake data. These specific objects, however, are very deeply nested objects that are used by a lot of classes. They inherit from the DIMStore interface, and it looks like each DIMStore object contains about 10 MB worth of data.

Question 1: How should I generate these DIMStore objects for testing? My initial thought was to grab my character data during debugging and stringify it, then store it in a file for all tests to use later.

Question 2: Where should we store these test object files? I believe creating a new folder at DIM/src/data/tests would be good, that way all test files that need to access these test objects have a single place.

Let me know! I'll see what I can come up with in my next pull request and will post any changes here.

**Comment by kyleshay** [comment]
I think anywhere we can test with a small subset of data in memory would be preferable.

We may need to set up some functions that generate mock DIMStore data (that way we can also test for edge cases that any given static inventory may not have.)

**Comment by kyleshay** [comment]
Thanks for taking a look at our tests! Is a bit of a gap and we do have some really complicated logic around searching for and moving items.

**Comment by Spawnbroker** [comment]
OK, I will work on writing up some functions that create mock DIMStore objects by consuming static text files in our solution instead of Bungie's API.

**Comment by Spawnbroker** [comment]
Current working example is in #4408

**Comment by Spawnbroker** [comment]
As per conversations with @bhollis , I'll steer away from mocking when possible with our tests. We may still need a way to generate fully-formed DimStore objects in the future.
