### ISSUE TITLE
Loadout Optimizer: Unable to select min/max tiers for main stats. All locked at 10.

### ISSUE THREAD

**Issue by lainverse** [DestinyItemManager/DIM#4393]
Nothing to add, actually. Every time I attempt to select any value from min and max tier drop-downs it is immediately reset back to 10. Even changing by directly modifying .selectedIndex propery of the field is reset on selecting any other value or "Load stores" operation (in the console log).

Tested in: Steam in-game overlay and Google Chrome 77.0.3865.90

**Comment by Rafael-Vieira** [comment]
Had the same problem as you and just wanted to add some info, if you download the .csv file with the information for your equipment you'll possibly find your data lacking the values for Mobility/Recovery/Resilience on their respective columns, which are all set to 0. This specific piece of information, which most definitely explain our problem, may not be clear on the Loadout Optimizer tab but it's observable using the Inventory tab. In the Inventory tab, just click on any piece of armor and you'll see that all the stats are set to 0, you'll also see this message:

>Perk and mod details are unavailable while Bungie is updating their services. It will return when they are done, usually in a few hours.

So hey, could this be a problem that is not on their end?

**Comment by lainverse** [comment]
Ah, I see. That is the most likely reason and LO is pointless without stats anyway.
Details on eqp. are still missing, though.

**Comment by lainverse** [comment]
Ok, armor stats are back, but I still can't set change min/max filters and they all stuck at 10.

**Comment by bhollis** [comment]
We're gonna wait for the API to be fully back before we do anything with Loadout Optimizer.

**Comment by lainverse** [comment]
@bhollis Looks like something is missing on DIM's side with item stats as well. I have 3 "TANGLED WEB GRIPS" and can see stats for 2, but for the third one DIM shows me only recovery stat at 10. I can see stats of all 3 in the official D2 app.

**Comment by Rafael-Vieira** [comment]
@bhollis , by now most of the stats properties seem to be working but, at least for me, each piece of armor with Recovery Mod had its values (besides the +10 to Recovery) zeroed, so every equipment  with it looks like this:

![fsagsagsafdsa](https://user-images.githubusercontent.com/21353850/66686337-8177d400-ec55-11e9-8bea-3c2486e51b95.jpg)

**Comment by bhollis** [comment]
Sorry, this issue has become a bit confused with multiple reports. Please update to the latest beta and file individual issues if there's anything remaining.
