### ISSUE TITLE
Year 1 & 2 sources do not include armor 2.0

### ISSUE THREAD

**Issue by TheHandsomeCoder** [DestinyItemManager/DIM#4397]
Was looking to equip all my black armoury gear via `source:blackarmoury` and noticed that the helm doesn't get selected. Screenshot below.

![image](https://user-images.githubusercontent.com/1569604/66383071-4014c980-e9b4-11e9-97c5-e417ca2eac77.png)

Delving in a little deeper with the react dev tools show that the `source` param isn't populated

![image](https://user-images.githubusercontent.com/1569604/66384987-9df6e080-e9b7-11e9-8f87-f97bd14e8f5f.png)

**Comment by sundevour** [comment]
thank you very much for the report.

as you may see in the screenshot, it also thinks it's season 8. many new items were "re-added" as duplicates to turn them into armor2.0, and their info is a little messed up right now. we'll investigate this.

**Comment by sundevour** [comment]
in retrospect this is because you are not spelling 'armory' the US way
check filter help or type "black" and check out the filter autocomplete

**Comment by sundevour** [comment]
sorry, i took what you typed literally, the screenshot does say armory.

**Comment by TheHandsomeCoder** [comment]
I don't think that's correct, I used the autocomplete in the filter for the `source:blackarmory` 

This is still an issue using the autocomplete in the latest DIM

![image](https://user-images.githubusercontent.com/1569604/66644779-b23a1800-ec19-11e9-94d9-621f7969ab54.png)

**Comment by TheHandsomeCoder** [comment]
Ah sorry I missed the above messages

**Comment by sundevour** [comment]
no worries it is my bad. i am fixing up season and source data for y3 armors and will respond to this as soon as the fix is in beta
