### ISSUE TITLE
Loadouts Equipped by Default

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#440]
When a user adds an item to a loadout, it is not equipped by default if there is no item of that type.  This has been a usability issue for new users as the behavior isn't obvious, and when you apply a loadout with this feature, it feels broken.  

We should change the behavior when items are added to loadouts so that they are equipped by default.

What do you guys thing @kyleshay and @bhollis?

**Comment by bhollis** [comment]
I fixed this a couple versions back. The first item of any type you add to a loadout is equipped by default. If you remove an equipped item, another one will be promoted to equipped.
