### ISSUE TITLE
Perk and mod details are unavailable while Bungie is updating their services. It will return when they are done, usually in a few hours.

### ISSUE THREAD

**Issue by davewhiffen** [DestinyItemManager/DIM#4400]
"Perk and mod details are unavailable while Bungie is updating their services. It will return when they are done, usually in a few hours."

It's been saying this since Shadowkeep launched.  Is there a fix for this?
![DIM error](https://user-images.githubusercontent.com/19539249/66401900-ead7b880-e9b1-11e9-9395-d4a91ffad645.png)

**Comment by sundevour** [comment]
yes. the fix is bungie being done updating their services.

**Comment by melange396** [comment]
https://github.com/Bungie-net/api/issues/1070
:( i miss my unselected perks
