### ISSUE TITLE
portrait to landscape to portrait item size 

### ISSUE THREAD

**Issue by inexorableAce** [DestinyItemManager/DIM#4403]
When on mobile (iOS 13.1.2 but also happened on 12) if you have your item tiles set to something greater than the default (3 items) and you rotate your phone into landscape mode, then back again your tiles switch back to the 3 items default. 

to fix you can go into settings and swap to 3 items, then back to 4, or close your app and restart it. 

![ezgif com-resize](https://user-images.githubusercontent.com/29002828/66434276-34df8f00-e9f0-11e9-94b3-a177c9081a82.gif)

**Comment by duckmanBR** [comment]
Can't reproduce this on Android 7
