### ISSUE TITLE
Data backup downloads do not work in Safari

### ISSUE THREAD

**Issue by nchase** [DestinyItemManager/DIM#4412]
I'm in MacOS with Safari 12.1.2

When I try to download a data backup from the Settings screen, I see this message:

```
Safari can’t open the page “blob:https://app.destinyitemmanager.com/6ceff620-02b9-4b3b-bec9-08ccb3e6cb6d”.

The error is: “The operation couldn’t be completed. (WebKitBlobResource error 1.)” (WebKitBlobResource:1)
```

**Comment by bhollis** [comment]
I'm unable to reproduce on Safari 13.0.1. Can you try upgrading? It looks like it's probably this bug: https://bugs.webkit.org/show_bug.cgi?id=190351

**Comment by nchase** [comment]
Looking at the bug and knowing that you can't reproduce, sounds very likely that the upgrade will fix. I'll deal with this until I have the guts to upgrade to Catalina. Thanks for the fast response!
