### ISSUE TITLE
Maximum Values for Overall and Individual Armor Stats

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#4413]
Armor Quality is a feature that users expect from DIM. Players use armor quality to understand items and remove the anxiety of deleting an item.  With Destiny 2 Shadowkeep, armor items are clean slates with regard to perks.  The only focus is on the stats, and how good they are for the player.

DIM's focus will be on the overall stat quality of the armor item. A secondary focus will be on how good an individual stat value is for the armor item.

Determining these values will be an effort that will be shared between DIM and DTR.  

**Workflow**

1. On startup, DIM will retrieve the current max stat values from an endpoint on DTR's website.
2. Once the characters are loaded, DIM will look for armor items that have greater overall stat values, or greater individual stat values per armor type based on the static JSON stat data.
3. Player that have an item that is better than anyone else in the community (congratulations player!) will need to report that data to DTR to update the static JSON stat data.
4. The improved item will need to be equipped onto a character, that character ID will need to be sent to DTR, and DTR will make a request to return the item stats from the API.  This method ensures that the data is accurate and not tampered with by the player.
5. Once the data has been saved, the is returned to its original location.

The likelihood of this operation occurring will become low after the initial weeks of launch. 

- If the item needs to be equipped onto the current online character due to class affinity, then we need to notify the player that we have to update their character for a moment. 
- If the item can be equipped onto a character that the player is not using or the current character is offline, we will automatically perform the action for the player.
- We need to remove the affect of mods on the stats.

**Comment by bhollis** [comment]
Why does the item need to be equipped?

**Comment by SunburnedGoose** [comment]
@bhollis, DTR can only see the equipped items on characters.

**Comment by bhollis** [comment]
Ah, makes sense. Perhaps we should be more passive and only look at currently-equipped items.

**Comment by delphiactual** [comment]
Also #4418 could alleviate the need to equip

**Comment by SunburnedGoose** [comment]
That would be the dream @delphiactual.

**Comment by bhollis** [comment]
Anyone willing to take this on?

**Comment by bhollis** [comment]
Given what we know about armor rolls now - do we think this is still useful?

**Comment by SunburnedGoose** [comment]
Probably not.  Close?  Close.
