### ISSUE TITLE
Blast Radius and Velocity are missing in exported weapons spreadsheet (D1)

### ISSUE THREAD

**Issue by quetschke** [DestinyItemManager/DIM#4414]
This is a Destiny 1 issue. In the exported weapons spreadsheet blast radius and velocity are missing.

A welcome fix would be to export these values under "Impact" and "Range" as Rocket Launchers always have 0 for those columns.

**Comment by wghilliard** [comment]
Since Blast Radius != Impact and Range != Velocity, does it make sense to 
- combine these stats into the same column?
- create new columns for the missing stats?

**Comment by quetschke** [comment]
Thanks, great! I was going to say: Whatever is easier for you. "Create new columns" was the better solution as different stats should have different columns.
