### ISSUE TITLE
DIM API

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#4418]
This is a proposal [to replace Google Drive data storage with our own custom API](https://docs.google.com/document/d/17Qn2PtA05EuOfb3-9jxZ8KX6MabPs_JJDiLF2N-jQR8/edit?usp=sharing). Development will happen in a separate repo - this issue exists mostly to dupe old sync issues into.

**Comment by CodyFitzpatrick** [comment]
Big proponent of this here (not that comments are even necessary)! 😃

**Comment by CodyFitzpatrick** [comment]
Big proponent of this, not that comments are even necessary! 😃
