### ISSUE TITLE
Not so secret triumphs 

### ISSUE THREAD

**Issue by duckmanBR** [DestinyItemManager/DIM#4426]
This on Beta.  Can't check on prod at the moment.
![image](https://user-images.githubusercontent.com/32077894/66663978-18c33400-ec22-11e9-9408-22ebc8bf3329.png)

**Comment by bhollis** [comment]
This suggests either there's a new property we're not checking, or that they literally named the triumph "Secret Triumph" in the data.

**Comment by duckmanBR** [comment]
If I check the "reveal redacted" it shows the proper name and description, so it's not the latter.  And I think it may be the first secret triumph with a not true/false objective, or even with an objective.

**Comment by sundevour** [comment]
maybe an api bug? can't duplicate.

reveal redacted:
![image](https://user-images.githubusercontent.com/31990469/66705383-cdb92780-ecda-11e9-9758-b512112a7c6a.png)

unchecked:
![image](https://user-images.githubusercontent.com/31990469/66705385-d578cc00-ecda-11e9-9f9f-5519fa810b98.png)

might need someone with 0 rice cakes to test/troubleshoot

**Comment by bhollis** [comment]
never fear, I have not played the game much
