### ISSUE TITLE
Show sum of total armor stat values, in armor view and compare view. 

### ISSUE THREAD

**Issue by johyphenel** [DestinyItemManager/DIM#4429]
DIM now show the values for Mobility, Resilience, Recovery, Discipline, Intellect, and Strength — which is insanely helpful!! 

It would be nice to have another row for total point value for an armor set to help get a general idea of how good a drop is in general, eg. 49 vs 54 vs 60. 

Would love to see this in individual item view and in compare view so we can sort by best total stats when deciding what to keep or shard.

**Comment by duckmanBR** [comment]
Will be fixed when #4423 is merged.
Not sure about the comparison view, but I think it will work there too the way @bhollis did it.

**Comment by johyphenel** [comment]
Awesome :D
