### ISSUE TITLE
Include energy type in duplicate calculations

### ISSUE THREAD

**Issue by GHOSTJR12** [DestinyItemManager/DIM#4435]
Hey guys great idea in putting the energy on all the armor. I think it would be a great idea to also include them when I am comparing all duplicate items in the "compare items" so I know what I should trash... 

thanks for listening and please keep up the good work!

**Comment by sundevour** [comment]
will implement right after #4423

**Comment by sundevour** [comment]
this and #4435
deal with elemental affinity in armor 2.0 energy capacity, and item comparison.
it seems like either way you consider "duplicates", with or without energy, will thwart someone's intention when they say "duplicate"

my opinion is, spawn the sheet without dupes, and provide enough buttons for the user to express their intention clearly
compare all:
[hood of the great hunt] [y3 + hood of the great hunt] [y3 + hood of the great hunt+void]
