### ISSUE TITLE
empty vendors tab

### ISSUE THREAD

**Issue by qqshka** [DestinyItemManager/DIM#4436]
Hi, my vendor tab is completely empty, any tips how to fix it?

![image](https://user-images.githubusercontent.com/543612/66703568-b438cf80-ed1c-11e9-8e13-256fae4624cb.png)

Character was made with new light.

Browser console:
`sync.service.ts:49 Sync: Storage will not be cleared except by explicit user action.
sync.service.ts:57 Sync: DIM is using 31.66 MB total out of 77.84 GB in storage quota (0%).
Index.tsx:47 DIM v5.49.1 (release) - Please report any errors to https://www.github.com/DestinyItemManager/DIM/issues
6A cookie associated with a cross-site resource at <URL> was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at <URL> and <URL>.
d2-stores.ts:282 Load stores: 2661.484130859375ms
index.html#/4611686018490319523/d2/inventory:1 [Intervention] An <img> element was lazyloaded with loading=lazy, but had no dimensions specified. Specifying dimensions improves performance. See https://crbug.com/954323
d2-stores.ts:282 Load stores: 804.942138671875ms
d2-stores.ts:282 Load stores: 1044.27099609375ms
d2-stores.ts:282 Load stores: 842.262939453125ms
d2-stores.ts:282 Load stores: 779.188720703125ms
d2-stores.ts:282 Load stores: 946.341796875ms
d2-stores.ts:282 Load stores: 778.97216796875ms
d2-stores.ts:282 Load stores: 1560.837158203125ms`

**Comment by bhollis** [comment]
Seems to be an API bug.

**Comment by samyjwv** [comment]
It's Bungie API Bug.

I have the same problem, for 1/3 of my chars.

This is not exclusive to DIM if you try d2checklist.com for example it's same problem.

**Comment by samyjwv** [comment]
I debug the request and the problem is something with Privacy Setting, because the vendors groups comes empty and with the flag privacy 2.

Don't understand why only apply to some chars and not to all chars of the same account. For example, for me only happen to 1/3 of my chars.

I already check bungie.net privacy settings and all it's checked.

Logs:
{"Response":{"vendorGroups":{"data":{"groups":[]},"privacy":2},"vendors":{"data":{

**Comment by criscofats** [comment]
> 
> 
> I debug the request and the problem is something with Privacy Setting, because the vendors groups comes empty and with the flag privacy 2.
> 
> Don't understand why only apply to some chars and not to all chars of the same account. For example, for me only happen to 1/3 of my chars.
> 
> I already check bungie.net privacy settings and all it's checked.
> 
> Logs:
> {"Response":{"vendorGroups":{"data":{"groups":[]},"privacy":2},"vendors":{"data":{

Was one of your characters created after the migration? A "New Light" character?  I believe it has something to do with the migration from Battle.net to Steam.  I only have new light characters after the steam migration and mine are not working.

**Comment by qqshka** [comment]
> I believe it has something to do with the migration from Battle.net to Steam. I only have new light characters after the steam migration and mine are not working.

Same, migrated account (zero characters) from Battle.net to Steam and made caracter with new light and it affected by this issue.

**Comment by samyjwv** [comment]
It's fixed. You can close the issue.
