### ISSUE TITLE
Break out gear level vs. artifact level

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#4445]
> i would love to see hover or expand values show gear+artifact values because it's not intuitive as is, for understanding what level your gear drops will be

Agreed!

**Comment by KsaRedFx** [comment]
I really liked before when DIM showed your max possible was before artifact in the small subtext below your character emblem, as it was an easy way to see what your drops would be at on each character.

**Comment by bhollis** [comment]
Yes, that’s what this issue is for. We were getting constant complaints that the max light was “wrong” so we fixed it, but we should further enhance it to break out artifact level.

**Comment by KsaRedFx** [comment]
I figured as much, I was just adding to it.  
Keep up the good work!

**Comment by sgtlaggy** [comment]
I made commit ef9bbca780585a10b883a6647cb841bba25c5e82 that resolves this, but I'm not experienced enough with CSS to figure out how to fix the `+ X` being a line below the gear power.
The commit itself doesn't really add any new code, just moves the logic that adds artifact and max power to other locations, under the emblem and in the emblem dropdown, giving `power + artifact`.

**Comment by bhollis** [comment]
Thanks @sgtlaggy I'll start from that
