### ISSUE TITLE
Refresh often doesn't do anything but works after moving inventory

### ISSUE THREAD

**Issue by thomaskchan** [DestinyItemManager/DIM#4461]
Version 5.49.1.5210 (beta), built on 10/13/2019, 9:38:50 AM

I noticed that recently that often when I click the refresh button (to show new drops on my character), it does not find the new items.  However, if I move an item to or from the character in DIM, then clicking the refresh button afterwards will actually work.

Not sure if this is a DIM or Bungie issue.

**Comment by bhollis** [comment]
It's a Bungie.net issue, unfortunately.

**Comment by bhollis** [comment]
https://github.com/Bungie-net/api/wiki/FAQ:-Cache-times,-in-game-interactions,-and-busting-the-cache
