### ISSUE TITLE
Items with German Umlauts cannot be searched

### ISSUE THREAD

**Issue by KBanause** [DestinyItemManager/DIM#4467]
Hi,

I'm using DIM in German Language. However, when I try to find an item that has Umlauts (äöüÜÄÖß) then the search can't find anything.

For example:
The "Persuader" is called "Überredungskünstler" in German. See screenshot.

![persuader_search_german](https://user-images.githubusercontent.com/999719/66734699-629b5c80-ee64-11e9-9a0c-658856e846eb.png)

**Comment by michabbb** [comment]
should this be fixed in "5.50.1" ? because it´s not, i have this problem, too.

**Comment by delphiactual** [comment]
![Screenshot (11)](https://user-images.githubusercontent.com/4798491/66962290-d9d01c80-f02d-11e9-8973-47ba2db8e572.png)
