### ISSUE TITLE
Exclude armor 2.0 mods in loadout optimizer

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#4470]
There’s only a few armor 2.0 mods that change stats, but they should probably be excluded when comparing. Armor 1.0 should still consider mods/perks.

**Comment by johyphenel** [comment]
Would be nice if Total display and `stat:total:` search would separate out mods as well. If I'm looking for godrolls it's important to be able to find `stat:total:>60` without the influence of mods. ie. 61 is a great roll, 51+10 isn't.

**Comment by ryan-rushton** [comment]
Is this currently being worked on? If not I would be happy to pick it up and make a contribution.

**Comment by bhollis** [comment]
@ryan-rushton Go for it!

@johyphenel it's helpful to file separate requests in separate issues so they can be worked on independently.

**Comment by ryan-rushton** [comment]
No worries should have something done soonish

**Comment by johyphenel** [comment]
Moved my suggestion to #4541
