### ISSUE TITLE
Loadout Optimizer says I can't have T0 Mobility

### ISSUE THREAD

**Issue by Nutley99** [DestinyItemManager/DIM#4471]
In game I can have 0 mobility with 2mob in every slot but the loadout optimizer shows only T1 or higher. All other stats show that there are no builds available for T0 but I can only confirm that I have the rolls for T0 mobility.

**Comment by bhollis** [comment]
Can you send some screenshots? I'm having trouble determining what exactly you mean. The optimizer simply adds up your stats and divides by 10 rounding down, so I'd have to see some examples to understand how this is happening.

**Comment by bhollis** [comment]
nm, I figured it out
