### ISSUE TITLE
Add option to toggle display of ornaments in inventory tiles

### ISSUE THREAD

**Issue by tomcorke** [DestinyItemManager/DIM#4474]
I've got used to recognising guns by their normal inventory icon - ornaments come and go, and it was surprising to see them appear in my inventory on DIM!

I'd like the option to toggle this back to the previous behaviour please!

**Comment by lrpebler** [comment]
I'll third this request: option to turn off, please/thank you. 

Neat idea in theory, but in practice it hampers my ability to organize when my DIM tiles don't match my in-game tiles.

**Comment by scousino** [comment]
I think I'm going to try and tackle this as my first PR in the repo. Wish me luck!

**Comment by lrpebler** [comment]
Good luck, thank you so much!
    On Friday, October 18, 2019, 06:16:06 PM CDT, Spencer Cousino <notifications@github.com> wrote:  
 
 
I think I'm going to try and tackle this as my first PR in the repo. Wish me luck!

**Comment by bhollis** [comment]
We've reverted using ornament icons for universal armor ornaments. We won't accept any PR that adds an option for turning this on or off.
