### ISSUE TITLE
Loadout Optimizer impossible to use when owning too many items

### ISSUE THREAD

**Issue by KiaArmani** [DestinyItemManager/DIM#4478]
I am currently running into an issue when wanting to use the Loadout Optimizer. I have around 400 pieces of armor in vault. When I try to open the Loadout Optimizer my Browser first tells my that "a website is slowing down your Browser" (Firefox), shows a portion of the page and then turns grey with "Out of Memory" errors in the Developer console (the tab takes up to 4 GB of RAM at this point).

It would be great if no combinations would be loaded when loading the page and if there was a dedicated "Filter" button which only starts filtering through my items when I press it, instead of having it change when I change one of the filters.

Specs: i7-6700k, 16 GB RAM

**Comment by delphiactual** [comment]
Dupe #4466
