### ISSUE TITLE
searchForSimilarItem fails with similar times.

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#448]
User on reddit [reported an error](https://www.reddit.com/r/DestinyItemManager/comments/49okxy/error_when_transferring_a_loadout/) moving items with loadouts.  He shared his screen and I was able to debug it.  Here's my repo:

![error-like-item](https://cloud.githubusercontent.com/assets/984608/13710855/1ec4971c-e781-11e5-8f38-6b7ecfc9b76e.gif)

Looking at the code there are a couple of issues.

1. The rewrite of searchForSimilarItems introduced an overly restrictive filter on items in the inventory.  If a user has multiple items with the same hash.  This prevents swapping between two instances of an item.
2. The rewrite of searchForSimilarItems doesn't consistently return null.  The [previous implementation](https://github.com/DestinyItemManager/DIM/blob/1724990645b9bd77e81c71a217549b3f2103dcf7/app/scripts/services/dimItemService.factory.js#L132-L156) relied on underscore chaining to get a null value as a return type.  The [chain now](https://github.com/DestinyItemManager/DIM/blob/a90221b7ba0b83093244134a0117dd22c8bb7db3/app/scripts/services/dimItemService.factory.js#L139-L154) can return an undefined value.  There is a [check](https://github.com/DestinyItemManager/DIM/blob/a90221b7ba0b83093244134a0117dd22c8bb7db3/app/scripts/services/dimItemService.factory.js#L121) in getSimilarItem for null which is now failing and prevents the search for an item within the vault, or other characters.

**Comment by SunburnedGoose** [comment]
The item can be swapped now.

![fixed-like-item](https://cloud.githubusercontent.com/assets/984608/13711286/5b7ee7e6-e783-11e5-9d72-80fd19697cc2.gif)

**Comment by bhollis** [comment]
Thanks for fixing this!
