### ISSUE TITLE
Custom Context Menu On Inventory Page

### ISSUE THREAD

**Issue by Estenoor** [DestinyItemManager/DIM#4480]
I was wondering about adding a custom context menu for the inventory page so you can right click on an item and mark it with a label / infuse it / move to vault or move to character. This would only be available for PC, because I'm not sure it's possible to do on different platforms

**Comment by kyleshay** [comment]
To that extent, maybe a long-press on mobile to expand/show something similar.

**Comment by bhollis** [comment]
This sorta dovetails/is redundant with the proposed new item popup design on desktop that displays actions more like a menu near the cursor. 

@Estenoor what specifically is driving your desire to do this?

**Comment by Estenoor** [comment]
When I'm managing stuff in my inventory, I'm used to right clicking items to manage them. I tend to do a lot of work in file systems and other similar setups, so being able to have a custom context menu would be very useful. I did forget to mention in the issue description that this is mostly asking for suggestions, because I was planning on making a pull request for it.

**Comment by justrealmilk** [comment]
If this was implemented, I’d prefer as a user, and suggest as a designer, to make it optional and off by default. 

Context menu hijacking is very 90s 😜

**Comment by bhollis** [comment]
@justrealmilk I tend to agree. The old Bungie gear manager used to do it though, and it worked pretty well.

We will of course not accept making this an option - it should either be there or not. @Estenoor I might suggest holding off on implementing this until our new item popup design lands.
