### ISSUE TITLE
armor2.0 element should need to match to be considered dupe

### ISSUE THREAD

**Issue by Ragnarok96** [DestinyItemManager/DIM#4481]
With solar, arc and void on armour pieces now I think is:dupe should not highlight pieces if they is only 1 with the same name and element

**Comment by bhollis** [comment]
Duplicate of #4435, I think?

**Comment by sundevour** [comment]
my understanding is
"armor2.0 element should need to match to be considered dupe"

**Comment by bhollis** [comment]
Right, isn't that also what #4435 was saying?

**Comment by sundevour** [comment]
i thought #4435 requested element+capacity to be shown in the comparison popup, but i can see now it could be interpreted differently, we'll fold this in either way.
