### ISSUE TITLE
color blind settings and firefox

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#4483]
turning on colorblind settings in firefox causes blank renders

![unknown (1)](https://user-images.githubusercontent.com/4798491/66914382-ee7fc680-efd3-11e9-9387-2e76c8cb0a2c.png)

**Comment by delphiactual** [comment]
Until this can be properly fixed
pasting `document.querySelector('html').style.removeProperty('--color-filter');` into the console allows the render to occur and allows changing the colorblind setting back to `-`

**Comment by bhollis** [comment]
Might be time to retire this - it's a cool idea but it seems to expose a lot of browser rendering bugs, and as a non-default option it rarely gets tested by us developers.
