### ISSUE TITLE
Search autocomplete first suggestion is now always [whatever you've typed so far]

### ISSUE THREAD

**Issue by javalasers** [DestinyItemManager/DIM#4487]
Until a couple of weeks ago, I could type (e.g.):
  tag:ju
...and then hit [enter] since the first search-box autocomplete was for "tag:junk"

Now, the first autocomplete suggestion is whatever I've typed so far ("tag:ju" in the example above), but the suggestion that I actually want is still there ... it's just a second option below.

I can certainly retrain myself to type a prefix, then hit the down arrow, then press enter... But having a default autocomplete suggestion that's identical to what you've already typed seems like it's not very useful in any situation, so I suspect this is actually a bug and wanted to report it.

[And fwiw, if the change is intentional, I definitely prefer the old way and don't understand the purpose of the new, but I'll happily adapt if that's the good word]. Thank you as always for this amazing tool!

**Comment by sundevour** [comment]
@bhollis isn't this how it's always been? i feel like when i was going through search stuff i complained about similar

@javalasers you'd be annoyed if you had put "jun" in a bunch of things' notes fields, tried to search "jun" then hit enter and it changed to "tag:junk". each has its downsides and interesting interactions with user intention

**Comment by javalasers** [comment]
Fwiw, I'm 99% sure this isn't how it's always been. Iirc, autocomplete
suggestions also seemed to trigger only on exact prefix match, which seemed
to minimize the downside you mention. Pressing space to reject the
autocomplete is also easier than pressing down arrow to select the
autocomplete.

If nothing else, just considering consistency with other auto complete UIs
in other search boxes (Google search etc) it's surprising/counterintuitive
to see an "autocomplete" UI element that's just a copy of exactly what
you've already typed.

**Comment by sundevour** [comment]
it's worked this way for at least a year and six days, going by git history.
`term` (what you've typed so far)
is added to the top of `words` (the list of suggestions)

![image](https://user-images.githubusercontent.com/31990469/67147253-30b13e00-f248-11e9-8fd5-9fae829379af.png)
https://github.com/DestinyItemManager/DIM/blob/7a83c8cc493cd4fea6de81331b2bff745dd60fb1/src/app/search/SearchFilter.tsx#L317

**Comment by sundevour** [comment]
nevermind this may be more like 4 months old. i will fix it.

**Comment by sundevour** [comment]
et voilá
