### ISSUE TITLE
Error splitting stackables if there are stacks in the vault.

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#449]
Having stackables in the vault causes DIM to attempt to stack items into the vault which causes a vault-to-vault transfer.

![error-split](https://cloud.githubusercontent.com/assets/984608/13712474/72c6934e-e789-11e5-9e50-84a2ef5ea354.gif)

Source:

https://twitter.com/KilllgoreTrout/status/708336212361105410

https://twitter.com/KilllgoreTrout/status/708336765631770624

**Comment by bhollis** [comment]
Ha, I had definitely tested that, but then didn't re-test it when I changed my strategy.

Is there a reason vault-to-vault transfers are an error rather than a no-op? The code is there to treat it as a no-op, but then `isValidTransfer` specifically checks for vault-to-vault.

**Comment by SunburnedGoose** [comment]
I'm just rejecting the promise.  It happens to make it to the client.

**Comment by SunburnedGoose** [comment]
I silently failing a good idea?

**Comment by bhollis** [comment]
I don't know if it's failing if you ask it to move something from the vault, to the vault, and it stays in the vault.

**Comment by SunburnedGoose** [comment]
You won me over :)
