### ISSUE TITLE
New ornament icons do not appear on titan gauntlets or marks.

### ISSUE THREAD

**Issue by Shophaune** [DestinyItemManager/DIM#4491]
When applying a universal ornament to a titan gauntlet item, the icon does not update and the ornament is displayed as "classified" when inspecting the gauntlets in DIM. 
![image](https://user-images.githubusercontent.com/31856537/67016141-a2c23f80-f0ef-11e9-90bf-a574310b0775.png) All five of these items have ornaments applied.
![image](https://user-images.githubusercontent.com/31856537/67016220-be2d4a80-f0ef-11e9-9f03-016c07feca88.png) Screenshot showing that warlock gloves work as intended.
![image](https://user-images.githubusercontent.com/31856537/67016266-d69d6500-f0ef-11e9-91ea-73cf1bb8edaf.png) Screenshot showing the issue with titan gauntlets.

Edit: And now I just noticed the same thing applies to titan marks (class items) too. But I'll save you the death by screenshot, it's the same story - the ornaments show up as Classified and don't update the icon.

**Comment by kyleshay** [comment]
Until they are declassified we won't have the additional information that we need to render the ornament. We could consider making a mod icon that better represents a classified item.

**Comment by bhollis** [comment]
Universal ornament icons have been reverted.
