### ISSUE TITLE
Error on Collections page

### ISSUE THREAD

**Issue by MilleXIV** [DestinyItemManager/DIM#4493]
Getting an error when trying to view the Collections page. It loads through mods then presents the error "Cannot read property 'plugItemHash' of undefined".

Relevant Stack Trace:

```
TypeError: Cannot read property 'plugItemHash' of undefined
    at PlugSet.tsx:52
    at Array.some (<anonymous>)
    at PlugSet.tsx:52
    at Array.map (<anonymous>)
    at k (PlugSet.tsx:47)
```

**Comment by bhollis** [comment]
Try the beta? I believe this is fixed there.

**Comment by MilleXIV** [comment]
Just tested and it does seem to work on beta. Thanks.
