### ISSUE TITLE
Wishlist not flagging newly obtained gear as is:wishlist

### ISSUE THREAD

**Issue by TableSalts** [DestinyItemManager/DIM#4496]
Hi,

I have been using the wishlists curated by 48klocs for a couple of seasons and have been loving them. With the release of shadowkeep, the weapons that I obtain _since shadowkeep_ that should be flagged as part of the wishlist (is:wishlist) are either not being flagged at all, or require me to move the item between characters multiple times before I get the thumbs-up icon.

An example of this is a Wizened Rebuke received on October 16. The gun I got from a drop was identical to a wishlisted Wizened Rebuke received in a past season. The past season's gun was flagged as a wishlisted item, but the new one was not flagged _until I had moved the item between characters several times_. After doing this, the new gun was appropriately shown as wishlisted, including the thumbs-up on the bottom left of the thumbnail. 

This appears to be the case for any weapon that I have gotten since the release of Shadowkeep.

I love using wishlists to help me sort out new gear that I am unfamiliar with, but it seems to be slightly malfunctioning.

This problem occurs on both the regular and beta versions of DIM on Firefox and Chrome and persisted with different versions of wishlists.

**Comment by delphiactual** [comment]
Are the correct perks selected in-game? Because as of shadowkeep on currently selected perks are returned by bungie.net, a fix is being worked on by bungie to start returning all the stats again but until that happens, this is what we have.

**Comment by TableSalts** [comment]
In the example of the Wizened Rebuke, all the same perks were selected as the other wishlisted roll.

**Comment by delphiactual** [comment]
@48klocs ?

**Comment by 48klocs** [comment]
I haven't seen anything like this on my end, but I can try to keep an eye out for it.
