### ISSUE TITLE
Vendors: Include unlocked PlugSet items in "Only show uncollected items"

### ISSUE THREAD

**Issue by peabeu** [DestinyItemManager/DIM#4500]
When I select "Only show uncollected items" on the Vendors page, I would expect to see all the items (including bounties) that have neither a Green or Blue tick in top right hand corner of the items thumbnail. 

The action of selecting "Only show uncollected items" currently hides a lot more than what I think is intended. See attached pdf
[Collected.pdf](https://github.com/DestinyItemManager/DIM/files/3746258/Collected.pdf)

**Comment by bhollis** [comment]
No, it will only show the list of things you could collect that you haven't collected. Bounties are not collectible. It's meant for people who are filling out their collections.

**Comment by peabeu** [comment]
Ok fair enough about bounties but my image is trying to display a stack of items sold by Tess that I have not purchased (collected) such as ornaments, emotes and ghost projections that should definitely be displayed after you click "Only show uncollected items". It's clearly not working. Go try for yourself and reopen please.

What about Ascendant Shards or Mods from Banshee are they considered the same as bounties? Shards maybe but Mods are more a collectable or is the tick system adequate enough?

**Comment by sundevour** [comment]
peabeu has a bunch of stuff, that is not owned, that disappears when that checkbox is checked. worth investigation and some attempts to duplicate

**Comment by bhollis** [comment]
Maybe the issue is that items that come only from plug sets (emotes, projections, ornaments) aren't being counted in the filtering criteria for that?

Bounties wouldn't be included because they're not collectible by any sense.

**Comment by sundevour** [comment]
sure but compare my
![image](https://user-images.githubusercontent.com/31990469/67280528-38f4bd80-f482-11e9-8c8d-4200a1194cac.png)
to
![image](https://user-images.githubusercontent.com/31990469/67280557-43af5280-f482-11e9-88d0-de0ef384b031.png)
and something is wrong i do not own all the stuff that disappears. needs investigating.

**Comment by bhollis** [comment]
Yeah I think the stuff that's disappearing are emotes, ghost projections, and ornaments.
