### ISSUE TITLE
Spider no longer shows all planetary material amounts

### ISSUE THREAD

**Issue by peabeu** [DestinyItemManager/DIM#4501]
Recent changes to display a total number of planetary materials that we have for Spider on the Vendors page are no longer there.

This will need to be updated to reflect the extra items we now have of course.

**Comment by bhollis** [comment]
Linking #4050 and #4016 because I don't have issue numbers memorized.

**Comment by peabeu** [comment]
Here's some more information. 4050 (see attached) is an issue raised by @sundevour and it's what I suggested and originally raised in 4016. I believe it has been broken since Shadowkeep was launched, so no longer "Awesome!" Can you please reopen one of these issues (take your pick) and resolve. Thanks in advance.

![image](https://user-images.githubusercontent.com/34254703/67151938-7be75180-f319-11e9-9284-9364b671b9cd.png)
