### ISSUE TITLE
The total stat field in the item popup doesn't indicate if mods are included.

### ISSUE THREAD

**Issue by ryan-rushton** [DestinyItemManager/DIM#4504]
In the following panel the total is inclusive of a stat increasing mod.

![image](https://user-images.githubusercontent.com/7344652/67146609-8d5c3980-f2d8-11e9-88a6-f9380b271729.png)

I was thinking it would be clearer to  display the base stat value with a +10 (or whatever the mod total is) next to it in the same blue as the stat bars have.

Thoughts?

**Comment by delphiactual** [comment]
https://github.com/DestinyItemManager/DIM/pull/4479

**Comment by ryan-rushton** [comment]
@delphiactual, there wasn't an issue for that PR so I figured I would make one. It would make sense to do them at the same time.

**Comment by bhollis** [comment]
I think what @ryan-rushton is asking is slightly different, but it makes sense. One confusion is that I believe in-game the total will include mods. So we'd just need to be consistent about how we displayed them to make sure we're always showing the base, mod value, and true total.

**Comment by ryan-rushton** [comment]
Since I did some stuff in the area I will do something for this post up some shots to get opinions

**Comment by ryan-rushton** [comment]
What are the thoughts on this?

![image](https://user-images.githubusercontent.com/7344652/67152685-91637800-f327-11e9-8400-d33e35c7f05f.png)

I have partly done the masterwork side of things, basically it would display a plus with an orange number after the mod value if it is non zero. I am just not sure how the new values are calculated and I haven't masterworked a piece of armour yet to figure this out.

**Comment by bhollis** [comment]
That looks good! I think @sundevour was telling me a masterwork gets +2 in all stats.

**Comment by sundevour** [comment]
i like this a lot!
masterworks right now are a fixed +2 bonus, in all 6 stats.

**Comment by ryan-rushton** [comment]
Cool, I will raise a PR for this today some time.
