### ISSUE TITLE
Translation: context for ItemMove.MovingItem_male

### ISSUE THREAD

**Issue by rentalhost** [DestinyItemManager/DIM#4519]
Please, could someone help me with this context? There are two versions `ItemMove.MovingItem_male` and `ItemMove.MovingItem_female`, but I don't know if I should apply the article to each one.

Eg. _Transfer to the [male article] {{target}}_ and _Transfer to the [female article] {{target}}_, respectively.

**Comment by delphiactual** [comment]
apply the male article to the `_male` and the female article to `_female`

**Comment by bhollis** [comment]
Target is a character or store, so it would end up like “Transfer to Awoken Female Hunter”, or “Transfer to vault”.

**Comment by rentalhost** [comment]
Thanks guys! I will apply the article in this case.
