### ISSUE TITLE
Click stat a second time to sort by lowest first in comparison view

### ISSUE THREAD

**Issue by phillipspc** [DestinyItemManager/DIM#4524]
This may be less helpful once the loadout optimizer is fully functional, but in the mean time, I'm finding myself using the comparison tool a lot to try to find the best armor. While most of the time you want to see which piece has the highest of a particular stat, occasionally its nice to sort by lowest. For example if I've decided I really dont care about resilience, some optimal armor pieces for me would be ones with _low_ resilience stats.

So I was thinking maybe with the first click, we keep the existing behavior, sort highest to lowest. Clicking on that stat again sorts lowest to highest. Might be helpful to throw in up/down arrows as a visual indicator as well. 

I'm happy to work on this if approved, but wanted to create an issue to see what people thought.

**Comment by bhollis** [comment]
Sure, sounds good! That'll be the default behavior in https://github.com/DestinyItemManager/DIM/issues/4377 btw.

**Comment by phillipspc** [comment]
Cool, the vault organizer™️ sounds amazing! @bhollis 
I'll hopefully have a PR for this sometime this week
