### ISSUE TITLE
Loadout Builder builds are not being sorted correctly

### ISSUE THREAD

**Issue by ric20007** [DestinyItemManager/DIM#4528]
The generated builds follow the chosen stat priority but are being sorted in the opposite order.
They follow the total tier and the first stat correctly and have a descending sort, but the other 5 stats have an ascending sort.  

Fix: All stats should use the same sort, so the higher value comes first.

Example: with Recovery first and Mobility second on the stat priority I will have builds with 4 Recovery and 2 Mobility higher on the list than the 3 and 4 Mobility ones.   

![image](https://user-images.githubusercontent.com/1295638/67169823-d0381300-f3a5-11e9-8274-46f35d5927f1.png)  

Possible culprit: https://github.com/DestinyItemManager/DIM/blob/27521c17ef9e50e82abdd7724c88363f440434ec/src/app/loadout-builder/generated-sets/utils.ts#L80  
I'm not familiar with the codebase so it could be a completely wrong guess.

**Comment by bhollis** [comment]
That line means "sort in descending order". But it is also the bug - it's supposed to sort on tier, not stat value. Give it a try on beta in 5 minutes.
