### ISSUE TITLE
Loadout transfers unsuccessful with characters/vault at near capacity

### ISSUE THREAD

**Issue by pylaligand** [DestinyItemManager/DIM#453]
Here's the situation:
- I have character A whose weapon slots are pretty much full;
- Character B has a set of weapons referenced in loadout X, and some available slots;
- The vault has 1 or 2 spaces available for weapon transfer.

If I try to transfer loadout X from B to A, I always get "vault full" errors after one or two weapons are transferred. The pattern I observe is the following:

1. Move a weapon from A to vault to clear some space in his inventory;
2. Move a weapon from B to vault, then vault to A as part of the loadout transfer.

The problem is that the weapon transferred in step 1 remains in the vault, and nothing seems to be moving it back to a character in allow for other weapon transfers to proceed. Consequently the vault fills up and the rest of the loadout transfer fails.

It seems that earlier versions of DIM did a better job at handling this situation.

**Comment by bhollis** [comment]
It's possible it's gotten worse - some things changed in this version. But
in the next version I'm specifically fixing things so the vault being full
won't be a problem.

**Comment by bhollis** [comment]
I'm back in town and I have a repro. I'll fix.

**Comment by bhollis** [comment]
I have a fix for this, but it was already incorporated in #451 (which fixes a lot more besides). I'll just release that!
