### ISSUE TITLE
Sorting sets with equal total tier level in loadout optimiser.

### ISSUE THREAD

**Issue by ryan-rushton** [DestinyItemManager/DIM#4533]
For example if I have 20 combinations with an overall tier of T22, it would be nice to sort them by discipline tier or intellect tier.

**Comment by delphiactual** [comment]
Grab the stat on the right side and move it to the sort order you want

**Comment by delphiactual** [comment]
![Screenshot (13)](https://user-images.githubusercontent.com/4798491/67172748-c7314c80-f379-11e9-9b14-97141c90842c.png)

**Comment by ryan-rushton** [comment]
Thanks mate, wasn't aware of that.
