### ISSUE TITLE
Translate DTR DB URLs

### ISSUE THREAD

**Issue by 48klocs** [DestinyItemManager/DIM#4534]
DTR's DB has been spiced up and lets you build out rolls; its format is a whole lot like banshee-44's is (item hash + CSV'd perk hashes).

Should build in a regex to allow us to import 'em.

**Comment by bhollis** [comment]
Can we remove the Banshee icon then?

**Comment by 48klocs** [comment]
@bhollis do you mean the gift icon on the item details pop-up? I was thinking about maybe pointing to DTR's DB with that; I've heard a few people who make their own wish lists say that they use that to jump to their roll (plus b-44 hasn't been all the way updated for Shadowkeep).

That said, I suspect it's a small fraction of people that use it, and I don't have any strong feelings about removing a relatively obscure piece of flair from the UI.

**Comment by bhollis** [comment]
If we're already linking to their roll in DTR in the header, I don't think we should keep the present icon with a link to a separate site.
