### ISSUE TITLE
Infusion Tool is missing some items. 

### ISSUE THREAD

**Issue by Wh1rledPeas** [DestinyItemManager/DIM#4539]
Yesterday I got a higher drop of a Gunnora's Axe and tapped [infuse] only to find that my 750 masterworked version didn't show up. I'm not sure what's happening, but you can see from the screenshots that it shows up in the item compare grid, just not the Infusion tool.

Oh... And the update icon in these screenshots won't go away. I've tapped update multiple times. 

![Screenshot_20191021-002811](https://user-images.githubusercontent.com/3685437/67211619-0e0a5b00-f3e9-11e9-82f1-106f8a282f0d.png)
 
![Screenshot_20191021-002958](https://user-images.githubusercontent.com/3685437/67211642-182c5980-f3e9-11e9-9dc3-d8aede185580.png)
![Screenshot_20191021-003228](https://user-images.githubusercontent.com/3685437/67211667-211d2b00-f3e9-11e9-839d-cde7579e245a.png)
![Screenshot_20191021-100006](https://user-images.githubusercontent.com/3685437/67212119-d819a680-f3e9-11e9-95bd-f145f052e690.png)

**Comment by bhollis** [comment]
@sundevour changed the definition of "dupe" such that the compare tool includes items that are really separate items but have the same name and categories. Can you confirm that you're actually able to infuse these two weapons into each other in game?

**Comment by sundevour** [comment]
you can see from these screenshots that the items have different expansion icons and are therefore considered different guns by the game. different hashes. the chalice one is random rolls the eye is not. it's been so long since i was using y1 guns that i have no idea whether they infuse for just glimmer in the game.

**Comment by bhollis** [comment]
Sounds like it's working as intended, then.
