### ISSUE TITLE
Exclude armor 2.0 mods in `stat:` searches, and in armor stat display.

### ISSUE THREAD

**Issue by johyphenel** [DestinyItemManager/DIM#4541]
Would be nice if stay display, totals, and search separated out the armor base from the +10 a mod gives.

Justification: If I'm looking for godrolls it's important to be able to find stat:total:>60 without the influence of mods. ie. 61 is a great roll, 51+10 isn't.

Separation in display would be helpful as well (could be similar to how masterwork effect is shown?).

**Comment by ryan-rushton** [comment]
Looks similar to #4352 as well. I just commented on that one looking to pick it up but all stats should have some kind of base stat filter now or mods could be universally ignored. I think I prefer a stat:base* option meaning I can see both.

**Comment by ryan-rushton** [comment]
Were you planning on working on this issue @johyphenel? I'm keen to look into this if no one minds.

**Comment by ryan-rushton** [comment]
Actually I just noticed @sundevour is working on base stat mods as per the discussion in #4495

**Comment by delphiactual** [comment]
#4517
