### ISSUE TITLE
Add `stat:any:` search operator

### ISSUE THREAD

**Issue by johyphenel** [DestinyItemManager/DIM#4542]
Proposal: add `stat:any:` search operator

When deciding what armor to keep, my personal rule is keep anything with `stat:total:>58`, and to keep any item that has >=18 in a single stat. 

For example: I'd like to be able to search for `stat:any:>17` and have it match an item with 20 mobility, and an item with 18 intellect.

**Comment by sundevour** [comment]
already done just waiting to merge basestat stuff

**Comment by johyphenel** [comment]
Woohoo! :)

**Comment by sundevour** [comment]
closed by #4549
