### ISSUE TITLE
Display Armor 2.0 attribute "tiers" for efficient breakpoint planning

### ISSUE THREAD

**Issue by Lingnik** [DestinyItemManager/DIM#4543]
I wrote a whole doc, and will drop that below, but here's the gist. I'd love to hear feedback on implementing something like this in DIM, and would be happy to collaborate on the design. The underlying concept is a bit complex, and I'm happy to answer any questions.

Armor 2.0 attributes don't provide benefit until you reach breakpoints at the 10s mark on your character. So if you're at 29 Resilience, you won't derive any more benefit than being 20 until you reach 30. The rolls you choose to keep can have a dramatic impact on your builds, but vault space is limited. To minimize the number of pieces of armor you keep and maximize the amount of gain you get from your armor, a maximization strategy can be employed whereby you only keep armor with stats ending in 8s, 9s, and 10s. By doing so (post-masterworking), each piece has a higher likelihood of contributing to overall attribute breakpoint-crossing.

There is some nuance to this. I still don't have a piece with all 8s, for example, but pieces like that are my white whale. So by keeping pieces with "as many things ending in 8 as possible" and also accounting for individual attributes that cross the breakpoint boundary themselves (e.g. counting 18 as 2, 28 as 3, 38 as 4...), I have a simple heuristic to think about each drop. BUT, I don't have a way to analyze my existing inventory.

There's more in this doc, which is the product of a few peoples' ideas in the Destiny slack/community I'm in. https://docs.google.com/document/d/11bebYgDxly_z3x6CWyoLRmDvC6_o_LsoeoQ9p_rE5vY/edit#

Here's a copy of the spreadsheet I referenced in the doc which I'm using to manually assess armor today:
https://docs.google.com/spreadsheets/d/1ANiI319at77KS9ocCoOf7EVVls1CcmFEkagwdMg-Xxg/edit?usp=sharing

**Comment by delphiactual** [comment]
In your doc you mention something is wrong with exotics in DIM. What is wrong with exotic stats in DIM?

**Comment by kyleshay** [comment]
Thanks for the writeup! We've started to think through a table view that would have some rules & logic to help people find their best gear (and possibly explain why it's good.)

https://github.com/DestinyItemManager/DIM/issues/4377

Any help on that would be appreciated.

**Comment by Lingnik** [comment]
> In your doc you mention something is wrong with exotics in DIM. What is wrong with exotic stats in DIM?

@delphiactual I can't reproduce it now, but a few days ago while I was doing data entry for the spreadsheet I linked, stats on (some? maybe all?) exotics were underrepresented on DIM compared to in-game. I can't reproduce it now, but I'll be sure to file a bug if I notice it again.

**Comment by kyleshay** [comment]
I've linked this issue to the Vault Organizer issue above. I'm going to close this in favor of that, because what it sounds like, this idea could be part of that new view/tool. 

If you're imagining something totally separate we'd be into it, but would need some more concrete flows and to know how it would be different from our other tools. 

The end goal of the existing Loadout Optimizer is to make a loadout based on some of your personal criteria and tastes. 

The goal of the new Vault Organizer is to have DIM help you find the stuff you need to mark as junk and scrap in-game.
