### ISSUE TITLE
Loadout Optimizer not falling back to blues

### ISSUE THREAD

**Issue by inexorableAce** [DestinyItemManager/DIM#4546]
If a user doesn't have purple items in one of the applicable LO slots, they get no possibilities returned (even if the only purple slot they are missing is the ghost).
![7631C4EB-E748-46A2-8229-47309786661D](https://user-images.githubusercontent.com/29002828/67320914-dc72bc00-f4dc-11e9-8838-e9b25762ab4c.png)

**Comment by ryan-rushton** [comment]
Something that is likely related is that if you click to change an item with similar stats, you don't get the option to choose blue or green items. E.g. I have the green generalist ghost shell and I can include that in a loadout.

**Comment by inexorableAce** [comment]
Yeah blues and under are excluded on purpose, this aims to use them as a fallback if necessary.

**Comment by bhollis** [comment]
Hmm, I'm not able to understand from the code how this could happen, nor could I reproduce it by filtering out items from the candidate item sets. Any other ideas of how to get this to happen?

**Comment by bhollis** [comment]
For reference this is what I see: 
![image](https://user-images.githubusercontent.com/313208/67363958-6776a500-f523-11e9-8a84-27202bbf92a1.png)

**Comment by ryan-rushton** [comment]
It could be item specific? I can get it to happen with the green generalist ghost shell I have. It is fine for blue armour, as in I get the try sub-legendary message.

**Comment by bhollis** [comment]
Can you list out the very specific steps you use to get this to happen?

**Comment by ryan-rushton** [comment]
I'm trying to get some photos uploaded but github can't process the files.

1. In loadout optimiser, click on Exclude item in the bottom left.
1. In the drawer that opens select a ghost
1. repeat until all available ghosts are gone (note my green one doesn't show up here)
1. Expected, loadouts to be available with green ghost. Actual, No Builds Found message is displayed.

**Comment by bhollis** [comment]
But the initial screenshot doesn't have any filters selected. I think you're describing something else, which is also broken but perhaps in a different way.

**Comment by ryan-rushton** [comment]
No I don't just trying to simulate it without deleting all my gear haha. I did notice the original screen shot had T10 -> T10 in each stat filter slot which would remove everything.

**Comment by bhollis** [comment]
Your green ghost doesn't show up because we filter items with no sockets (we don't need to, but everything but green armor/ghosts will have sockets).

The T10/T10 filter thing is because there's no builds - it's not filtering anything. I will fix that because it confuses people.

**Comment by ryan-rushton** [comment]
Yeah, now you say that I get that same behaviour when there are no builds (T10 everything).

**Comment by ryan-rushton** [comment]
It would be nice to be able to load dim with test data, to simulate this kind of thing.

**Comment by inexorableAce** [comment]
The only thing different with the user that reported this are.

They only have a blue ghost, no purples. 
The character was made with new light. 

That’s about all the info I got, I assumed it was just that they only had a blue ghost since that makes more sense than new light.

**Comment by inexorableAce** [comment]
The ghost they have is indeed green 😭

Still seems like this could be better, ghosts aren’t really necessary for making a load out.

**Comment by quetschke** [comment]
> They only have a blue ghost, no purples.

That was me, sorry. Indeed, the only ghost I have is the initial green "Generalist Shell".
