### ISSUE TITLE
Queue Moves

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#455]
We should queue move operations to avoid issues where we have multiple moves trying to process at the same time.  We have a throttle on the API requests, but it doesn't stop some of the move logic from erroring out for instance when the vault is full.  Even with the aggressive move, I still get errors.

**Comment by bhollis** [comment]
Yeah, the problem is not that we're not queueing moves, it's that when we're doing sequences of moves, we're using outdated information in parallel. What we need to do is queue all "actions" where actions are loadout-applications, individual drag-transfers, and equips. I'll look at adding that.

**Comment by bhollis** [comment]
Alternately, I could disallow moves/loadout-applications while something is going... but that doesn't seem fun.

**Comment by SunburnedGoose** [comment]
Agree.

**Comment by bhollis** [comment]
OK, PR is at #465.
