### ISSUE TITLE
[Feature Idea] "Postmaster cleaning" mode

### ISSUE THREAD

**Issue by DHager** [DestinyItemManager/DIM#4551]
I'm willing to take a crack at this if it seems like a desirable feature...

## Problem 

You want to dismantle a lot of junk inside the postmaster queue, but you don't want to have to travel to the Tower to do it, nor do you want to withdraw it all *en masse* to your character/vault. In some cases this *has* to be done before going to the Tower, because unloading the zone will place all items on the ground into the postmaster, overflowing it before you can groom it.

## Feature 

A mode, similar to Farming Mode, where DIM will attempt to fill any free spot on your active character with an item from the postmaster that has already been tagged as Junk.

## Usage scenario

1. User applies the Junk tag to items in postmaster (possibly with a custom search)
1. User enables Post-cleaning Mode
2. DIM begins opportunistically sending junk items to empty spots on the user's current character 
3. User goes through and dismantles items from the inventory screen, most of which will be "obvious" like blue/rare non-random-roll weapons.
4. Steps 2 and 3 repeat.
5. User disables the mode or it automatically cancels because no more transferrable Junk items are left in the postmaster for that character.

## Quirks to consider

* Should probably be mutually-exclusive with Farming Mode.
* Is this feasible given usual refresh-rates, so that it recognizes players have just "made space" on the character's inventory?
* Should ignore any items that require direct Tower retrieval, and not count them when deciding whether there's more work to do.
* Should it ignore non-equipment items, like consumables or the rare quest?
* There may be desire for a time limit on activation, most people probably won't want to leave it running.
* Currently the example filter will consider Armor 2.0 as `not:randomroll`, but that's a separate issue.

**Comment by bhollis** [comment]
I think the "Pull from Postmaster" button is already sufficient for this - we've discussed this in the past, and we're not specifically looking to support the "postmaster as extra vault space" case where people leave things in the postmaster for a long time.

Consider also that "Farming Mode" has as its goal to not let things get into the Postmaster in the first place.

**Comment by DHager** [comment]
Suppose we agree that the goal is to empty the postmaster entirely. 

There's still an issue with how junk items from the postmaster will displace existing character-bound items and overflow into the vault. The user then has to notice that it occurred, spend time grooming the vault, and perhaps spend time putting certain items back onto the active character.

Instead, what about a button/option where get-from-postmaster is still indiscriminately choosing on the "source" side, but does *not* try to forcibly make room for the item when it encounters problems?

Ex:  

* The postmaster contains 1 helmet and 1 chestpiece
* The active character only has an empty chestpiece slot
* The helmet remains in the postmaster

**Comment by bhollis** [comment]
https://github.com/DestinyItemManager/DIM/pull/4632#issuecomment-548848466
