### ISSUE TITLE
CVS Export loss of informations

### ISSUE THREAD

**Issue by iameec** [DestinyItemManager/DIM#4557]
Hi,

It may be already knowed as i don't see these informations in DIM : when you export weapons you loose the Sights/Barrels and Magazine choise. Same loss when you use the "is:wishlist" command in DIM : it only looks at default perks (Had the case with a "The last danse" weapon where i have the 4 rights perks but one was not "equipped" (my source is from an extract of r/sharditkeepit that i imported in DIM, had that in a google sheet splitted in 2 tab (PVE&PVP)) so it was not recognized in a wishlist weapon.
Will that change or should i manually check all the Sights/Barrels and Magazine perks when the 2 last ones are good ones in my Google Sheet? 

Thanks for your work on this wonderfull tool (i would have stopped playing the game without it ^^, hope they will do weapon 2.0 too :D )

**Comment by duckmanBR** [comment]
Yes, it's know.
Bungie is currently only providing us (and all the other 3rd party apps) with the selected perks of the items.  This may change in the near future but there's nothing set in stone yet.

**Comment by iameec** [comment]
Thanks and sorry for the time, was back for Shadowkeep and at first thought it was some new issue since the update. Don't know if i'll still play as i tend to keep one PVE and one PVP version of each Weapon i get ^^ hark to keep inventory clean then :D maybe if i clean more armor and keep only few pieces of armor 2.0 (don't like the link per element thing)
