### ISSUE TITLE
Loadout Optimizer: Ignore total tier

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#4559]
https://twitter.com/iihavetoes/status/1187104989715390464

This user is interested in maximizing specific stats, even if it doesn't yield the maximum total tier. One idea would be to add a filtering option for ignoring total tier.

**Comment by rowanbrendan** [comment]
These all sounds like different things (that's fine)

Twitter post: yes to total tier priority first, but wants to ignore certain stats when calculating that total

Ben's example: total tier could be ignored, which would give greedy builds based on stat priority

Ryan's example: let total tier have any position in the stat priority

If we were to support all of these ways of exploring gear, we'd (1) add total tier to the priority list and (2) let any item in the priority list be ignored. Though it would need to be clear that ignoring stats a la item (2) means they aren't part of the total tier (the only reason ignoring an item in the priority list is different than just lowering priority).

**Comment by bhollis** [comment]
Let's do just the one where you can ignore stats' contribution to the total. I'm not clear on how you'd use the ability to change where total tier is in the sorting list. Given that folks already have trouble understanding this page, I don't think we should overcomplicate it.

**Comment by ryan-rushton** [comment]
I'm working on ignoring the stat tier atm, as I agree with @bhollis that this page is not overly obvious to people. I only discovered the moveable stat feature last week.

For reference, I can see myself using the the moveable total tier stat in the following manner. For a PVE build lets say I care about Recovery and Intellect as my primary stats. Then I would order the stats, Recovery, Intellect, Total, and then the rest. This would ensure I had the highest Recovery possible, the the highest Intellect with that recovery and a maximised combined allocation across the other 4 stats. 

I see this as ensuring I have the biggest benefit possible from my armour stats while prioritising Recovery, and Intellect as a secondary, as they make the most impact to my build. The other 4 are obviously better being higher, but I don't care as much how they are distributed.

The downside to this is I am using it as a total of the rest stat field, which is not actually what it is. It just happens to give a close enough result that I would use it that way. Maybe there would be a better way to achieve this result than making total a draggable stat. It hasn't dawned on me yet though.
