### ISSUE TITLE
Translation: "Wish List" normalization

### ISSUE THREAD

**Issue by rentalhost** [DestinyItemManager/DIM#4561]
There is a bunch of strings using capitalized term like "Wish List", other lowercase like "wish list". Could we normalize it into or capitalized or lowercased-version?

I prefer lowercased.

**Comment by delphiactual** [comment]
I am pretty sure the feature should be Title Cased as it currently is, and when referring to the feature it is `Wish Lists` but when referring to a specific wish list item, lower case is correct. @48klocs would know better though.

**Comment by rentalhost** [comment]
Currently we have this terms:

* **Capitalized:**
  * Wish List
  * Wish List Notes: {{notes}}
  * Load Wish List Rolls
  * Clear Wish List
* **Lowercased:**
  * {{num, number}} rolls in your wish list
  * Wish list loaded with information about {{count}} rolls.{{titleAndDescription}}
  * Wish list loaded with information about one roll.{{titleAndDescription}}
  * No wish list information found.
  * Shows wish listed items whose notes match the search.
  * Shows duplicate items where at least one of the duplicates is on your wish list.
  * Shows items that match your wish list.

I think that is valid use Lowercase in all cases, except the first capitalized once that it is the header.

**Comment by 48klocs** [comment]
Good eye - from a distance, I can see how the slightly inconsistent casing (treating Wish List as a proper noun sometimes, as just two words others) is a little crazy-making, but the capitalized/proper noun forms are in use on the settings page (where the buttons tend to Capitalize Every Word), and the `Wish List Notes: {{notes}}` shows up on the item popup, where it also seems to be consistent with the rest of the dialog ("Random Perks" is treated as a proper noun there).

That said, I don't have terribly strong feelings about it, and if you like how they look lowercase, I'm fine with it.
