### ISSUE TITLE
[Featrue idea] Mark equipped item in LO

### ISSUE THREAD

**Issue by tanglueyi** [DestinyItemManager/DIM#4564]
<img width="191" alt="Group 64" src="https://user-images.githubusercontent.com/3315564/67447268-ea901c00-f645-11e9-9429-60718e34f486.png">

**Comment by bhollis** [comment]
What’s the use case for doing that?

**Comment by tanglueyi** [comment]
How to say hmmmm, sometimes I use it to compare armors... so I'd like to know if the one shows is already equipped... just a little wish~

**Comment by kyleshay** [comment]
Thanks @tanglueyi ! Its an interesting idea but may be confusing for users. We're planning on building out a better compare tool that should hopefully help this problem! In the mean time, if you click an item you'll see which character it is on by looking at what move options are available
