### ISSUE TITLE
is:reacquirable is almost exactly wrong about armor 2.0 exotics

### ISSUE THREAD

**Issue by sundevour** [DestinyItemManager/DIM#4568]
`is:reacquirable` should check against collections'
• armor element
• base stats

**Comment by EffortlessFury** [comment]
Question: if is:reacquirable were to check against the armor element _and_ the base stats, wouldn't that just limit the search to only the versions in your inventory that are exactly the same as the one in your collection?

Should there be a distinction between items that can be reacquired (with potentially different stats) vs items that are directly equivalent to collection version? Theoretically it might also be useful to check against the armor element but not the base stats.

**Comment by EffortlessFury** [comment]
If I could ask what the User Story is for this filter and if we want to introduce any other filters for other similar User Stories?

Right now the description of the filter is: "Shows items that can be reacquired from Collections."

This bug suggests that it should be items that can be reacquired exactly as they are.
The current behavior is items that can be reacquired by name only.

**Comment by EffortlessFury** [comment]
Update: is:reacquirable is meant to match the exact roll in the collection. Investigating filters for the other scenario(s).

**Comment by joe7dust** [comment]
> Update: is:reacquirable is meant to match the exact roll in the collection. Investigating filters for the other scenario(s).

Will this ever be implemented? The element isn't much of an issue any longer, but I still see no way to tell which exotics you have with the collection roll. (stats)
