### ISSUE TITLE
Filter by "notes" property

### ISSUE THREAD

**Issue by starkeblue** [DestinyItemManager/DIM#4569]
It is not currently possible to filter for only items that have notes (or do not). This could previously be accomplished using the search strings "notes: " or "-notes: ", respectively, but it appears this was not intended.

It was suggested by a contributor on Discord to add a property to filter by, e.g. "is:hasnotes".

Thanks

**Comment by duckmanBR** [comment]
Yes, this changed recently but you still can search it using `notes:""` or `-notes:""`, but yeah, a `is:hasnotes` would be nice.
