### ISSUE TITLE
Support DIM page

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#457]
Looks like something caused the Support page to look a bit off. Guessing it's a mismatched tag, or something.

<img width="861" alt="screen shot 2016-03-24 at 10 38 26 am" src="https://cloud.githubusercontent.com/assets/424158/14020212/914d1608-f1ac-11e5-94bd-ae52c3c4b8ed.png">

**Comment by bhollis** [comment]
That's weird. I rewrote all that stuff to use flex on but I checked that it
looked good. I'll investigate.
