### ISSUE TITLE
Bungie auth broken in beta?

### ISSUE THREAD

**Issue by thomaskchan** [DestinyItemManager/DIM#4584]
Not 100% sure as I am using a computer that I don't often use for DIM, but I can't get past the auth prompt in beta:

We need your permission...
Allow DIM to view and modify your Destiny characters, vault, and progression.
Authorize with Bungie.net

I click the Authorize and I get the same screen again.  I can log in with a different account and get the playstation prompt and the bungie auth page.  It's just this final page that never goes through.

app.destinyitemanager.com works fine.

I'm on a Mac running Mojave.  Tested with the latest Firefox/Chrome/Safari.

Weirdly I can get to beta on a phone (in a new incognito tab) but the computer doesn't work.  

I don't have another computer to test this on right now.

**Comment by bhollis** [comment]
I've just pushed an update that might help with that. Try again in 10 minutes - if that doesn't work I'll have to dig deeper.

**Comment by thomaskchan** [comment]
Version 5.51.0.5500 (beta), built on 10/27/2019, 1:54:06 PM

Updated DIM beta (assuming that this build is the updated one), and looks to be the same behavior.

**Comment by thomaskchan** [comment]
It gets past the auth now using Version 5.51.0.5508 (beta), built on 10/27/2019, 2:31:29 PM

However, I now get the a new error which I've opened a ticket in #4599
