### ISSUE TITLE
Compare sheet tag dropdown does not expand on click

### ISSUE THREAD

**Issue by vivekhnz** [DestinyItemManager/DIM#4585]
The item tag dropdown in the compare sheet does not display items when clicked. `git bisect` is blaming the **react-spring** upgrade from #4576. This is currently only impacting DIM Beta.

![dim-compare-tag-dropdown-broken](https://user-images.githubusercontent.com/17512262/67631617-9a42e380-f8fd-11e9-99fb-f20fa227f236.gif)

**Comment by bhollis** [comment]
Thanks, I'll take a look at it.
