### ISSUE TITLE
Enhancement: Custom tags

### ISSUE THREAD

**Issue by dartiss** [DestinyItemManager/DIM#4587]
I love the tag feature and, to ensure I know exactly what I'm doing with everything, I like to have everything tagged with something relevant. However, there are times where there simply isn't a tag for what I want - e.g. a weapon that I want to try out.

I'd like to add the suggestion of allowing for user-custom tags, maybe selecting from a built-in list of icons to accompany each.

**Comment by delphiactual** [comment]
Notes

**Comment by DHager** [comment]
@delphiactual Notes aren't really a substitute, since you can't add/remove them except in an extremely tedious manual "click and edit and click and edit" manner.

**Comment by bhollis** [comment]
https://github.com/DestinyItemManager/DIM/wiki/Frequently-Requested-Features#add-more-tag-values

**Comment by dartiss** [comment]
Please don't take this the wrong way, but it feels as if we're being told HOW to use DIM. If people want more tags, why there is a push-back not to do so? In my case, I feel this is a good balance - keep the standard ones but allow people, if they want, to add their own custom ones. That way, if the tags become confusing only the individual user is to blame for that.

For my own use, I'm not imagining a crossover, where I need multiple tags for the same item - right now, I have things I want to try "in the field" and would like to easily identify them with a tag, which shows visually as an icon (unlike, for example, notes).

It's frustrating to find a genuine request just dismissed so quickly and closed off with a one word answer (yes, extra tags have been requested but I can't see anything for them to be customised).

**Comment by DHager** [comment]
> We've chosen the tag values we support based on a workflow of organizing your gear and identifying what to keep and what to get rid of, not what each item is best at.

... Except the *reason* players decide what to to keep/get-rid-of is *because* of how it stacks up in certain role or usage.

**Comment by slate0** [comment]
> https://github.com/DestinyItemManager/DIM/wiki/Frequently-Requested-Features#add-more-tag-values

"We've chosen the tag values we support based on a workflow of organizing your gear and identifying what to keep and what to get rid of, not what each item is best at."

This is such a bizarre thing to read, it sounds like a contractor who is more interested in limiting their required effort than delivering a useful product and it feels out of touch.  It would be easier to accept this if there was a DIM alternative that DOES support "what each item is best at" but who in their right mind is going to break away from DIM to use two systems in parallel?  And if another system were as good as DIM but allowed me to "track what each item is best at" then I wouldn't use DIM.

It's an absurd bifurcation to make.  

Beyond that, I think the added value of the convenience more tags would offer has not been given enough weight.  Consider that many of your users are using mobile devices and not sitting at a workstation.  Mobile devices are considerably slower and more difficult to type on, and I'm running on the top hardware.

Notes are not as good as tags for many reasons, including easy enumeration (ie: I don't have to make up a code word system and try to be consistent, and type it in on mobile) and readability: the green icons markers on the inventory screen make sorting out items at a glance easier by an order of magnitude.

**Comment by slate0** [comment]
Furthermore, if you're worried about feature creep maybe talk to the team that implemented the loadout creator...

**Comment by bhollis** [comment]
Linking https://github.com/DestinyItemManager/DIM/issues/7208 and https://github.com/DestinyItemManager/DIM/issues/7205

Also just a note - every time someone gets hostile at us about this, the priority of doing anything about it drops by a few months.

**Comment by slate0** [comment]
Such an immature developer.  Just dogwhistling here.  Such an immature baby using the "don't be mean or we'll take our ball and go home".  I don't really care, continue to be incompetent I'm not going to lick your boots because you finally think you have some power.
