### ISSUE TITLE
Highlight +2 Masterwork stats in Tooltip.

### ISSUE THREAD

**Issue by JpDeathBlade** [DestinyItemManager/DIM#4597]
Currently, if an item has a Mod equip that changes it's stats the tooltop gets a blue highlight (as seen here - https://pbs.twimg.com/media/EHo1-ixWkAE9-6w?format=png)

Would it be possible to get the same highlight, but in yellow, for the +2 stat that Masterworking gives to be consistent with Mods and the game?

**Comment by delphiactual** [comment]
Did https://github.com/DestinyItemManager/DIM/pull/4512 not work for the masterwork display as well?

**Comment by delphiactual** [comment]
@ryan-rushton

**Comment by JpDeathBlade** [comment]
Not for me. I'm on the latest version of the application (I think 5.51.0, no option to update). Here is an example of an item I have using this version. - https://i.imgur.com/dgMOCne.png

The Masterwork header image shows up, but the stat bars don't separate any of the stats.

**Comment by delphiactual** [comment]
Try on https://beta.destinyitemmanager.com

**Comment by JpDeathBlade** [comment]
I'm having the same issue as #4584 on Desktop and Mobile.

**Comment by sundevour** [comment]
well fwiw here is beta
![image](https://user-images.githubusercontent.com/31990469/67640579-ad7f9000-f8b8-11e9-9444-a121303344d2.png)

**Comment by ryan-rushton** [comment]
Sorry, only just saw this issue. I didn’t do the stat bars, only the number down the bottom. I know what needs to be done though. Give me a day or two and I’ll fix it.
