### ISSUE TITLE
DIM Inventory page overlapping

### ISSUE THREAD

**Issue by D2XBOX** [DestinyItemManager/DIM#4611]
Hello,

At the top of the inventory page the info for the vault tab "vault space used / total vault space" and other fields / values are overlapping and are not legible. Windows 10 / Edge machine. Checked Alpha and Beta pages, same result. The information is there, just seems to be a formatting issue.

Thank you for your attention

**Comment by bhollis** [comment]
Can you attach a screenshot?

**Comment by wiseman-tex** [comment]
@bhollis.  I opened a second ticket on this same issue (didn't see this one), see #4623 a screenshot is attached.

**Comment by bhollis** [comment]
Duplicate of #4623 (which has more detail)
