### ISSUE TITLE
Stats bar disappears when scrolling

### ISSUE THREAD

**Issue by melange396** [DestinyItemManager/DIM#4619]
There was a recent change that made it so the stats bar near the top of the page is no longer anchored when scrolling.  Specifically, it is the one that has maxpower & mob/res/rec/dis/int/str sums for character columns, and gimmer/shards/dust/silver counts & vault/consumables/shaders/mods capacity for the vault column.  It is located just below the emblem banners and just above the postmaster and engrams display.

This behavior makes total sense when using a mobile device with limited screen real estate, but a computer screen can spare the space.  I find that information extremely helpful in normal daily usage.  Could you change this for non-mobile clients?

**Comment by melange396** [comment]
it looks like this was introduced in #4526

**Comment by delphiactual** [comment]
yes we know https://github.com/DestinyItemManager/DIM/pull/4612

**Comment by melange396** [comment]
awesome, thanks

**Comment by bhollis** [comment]
Out of curiosity, can you explain *how* you make use of that information? It’d help u ls make decisions like this in the future.
