### ISSUE TITLE
Vault details display incorrectly on MS Edge

### ISSUE THREAD

**Issue by wiseman-tex** [DestinyItemManager/DIM#4623]
Prior to DIM release ver 5.52.1 on 10/27, MS Edge was properly displaying the AMOUNT totals for glimmer, legendary shards, bright dust and vault items.   Now they are all mushed together and illegible.   This happens in both the production and beta versions of DIM.  I have adjusted the size of the window and get same results.   See attached image.

![dim](https://user-images.githubusercontent.com/34490144/67861975-45ff5580-faef-11e9-906d-3d3bff807626.png)

**Comment by bhollis** [comment]
I don't have a Windows machine, so if somebody else can take a look at this it'd be great. I suspect there's something we're using that isn't supported (either `display: contents` or some grid property).

**Comment by SunburnedGoose** [comment]
Problems with other parts of IE too.

![image](https://user-images.githubusercontent.com/984608/68002701-2889d300-fc38-11e9-9539-3da0d401cfd0.png)

**Comment by inexorableAce** [comment]
edge doesn't like `display: contents`

here is edge as it stands today
![image](https://user-images.githubusercontent.com/29002828/68021950-3ad83100-fc79-11e9-88b1-6a3ced8d1124.png)

here is chrome if you disable `display: contents`
![image](https://user-images.githubusercontent.com/29002828/68021974-4c213d80-fc79-11e9-8ae7-e4498e281fba.png)

I don't know of a work around form edge off the top my head unfortunately.

**Comment by bhollis** [comment]
OK, I can rework those without display: contents. I'm surprised people were only reporting the vault header and not the popup stats...
