### ISSUE TITLE
Collapsible subsections

### ISSUE THREAD

**Issue by fdge** [DestinyItemManager/DIM#4634]
In addition to all weapons and armor being collapsible, can the subsections also be collapsible? (kinetic weapons collapsible, Helmet armor collapsible, etc...)

(Can the character subclass icons be moved out of the weapons section?)

**Comment by bhollis** [comment]
We think what we have now strikes the right balance between allowing customization, but not cluttering things up with too many collapsible items and headers. In the past when we had this, people frequently got confused when they collapsed a single row.
