### ISSUE TITLE
Enhanced Objectives no longer replacing first Unicode Character, with icon if more than 1 Unicoded Character exists in description

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#4637]
Bungie have been repurposing unicode emoji characters in-game.  When rendered in DIM they are amusing.  Note this is the current beta on an iPad running iOS 13.2.  Same beta on Chrome on Windows 10 desktop just show box characters.

![image](https://user-images.githubusercontent.com/25425159/68066702-36e90380-fd8c-11e9-91c3-92fafb6c4f3f.png)

Toilet abilities or melee kills!

![image](https://user-images.githubusercontent.com/25425159/68066707-49fbd380-fd8c-11e9-947f-3cd5d861b955.png)

Post box final blows!

**Comment by sundevour** [comment]
delphi handled this
