### ISSUE TITLE
April Update

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#464]
This is a meta-issue to collect changes to DIM that'll be required as a consequence of the [April Update](https://www.bungie.net/en/pub/AprilUpdate). Please add on to it. I haven't had time to watch the videos now, so I'm going off what I've heard on Twitter.

* [x] Remove infusion calculator, since infusions now bring items up to the level of the infusion material directly. Probably no reason to keep things around just to move materials over.
* [x] Update the store capacity functions to reflect the bigger vault (how much bigger is it?)
* [ ] Update talent grid code to handle chroma nodes, and display them differently. This'll require us seeing how these are represented by the API.
* [ ] Manifest refresh.

**Comment by SunburnedGoose** [comment]
108 for the vault I think for armor and weapons.  72 for general I believe...

**Comment by designker** [comment]
I asked Bungie and they told me that yes the sizes are 108/108/72. They also recommended not hardcoding the values and getting them from the manifest. The next version of Ishtar grabs the sizes from the vault endpoint with
...
var weaponsVaultHash = "4046403665"
        var armorVaultHash = "3003523923"
        var generalVaultHash = "138197802"
        var weaponsVaultSize = Int(jsonBlob["Response"].definitions.buckets[weaponsVaultHash].itemCount)
        var armorVaultSize = Int(jsonBlob["Response"].definitions.buckets[armorVaultHash].itemCount)
        var generalVaultSize = Int(jsonBlob["Response"].definitions.buckets[generalVaultHash].itemCount)
...

**Comment by bhollis** [comment]
Fantastic, thanks!!

**Comment by bhollis** [comment]
Hmm, we request with definitions=false to keep things slim, so we don't get that info. We can do it when we process manifests offline...
