### ISSUE TITLE
Loadout Optimizer error on loading page: "Cannot read property value of undefined"

### ISSUE THREAD

**Issue by gitrulez** [DestinyItemManager/DIM#4640]
When I open the Loadout Optimizer I get error "Cannot read property value of undefined" with Chrome (beta). In Firefox the error is "t[i] is undefined". 
I cleared cache and cookies but no change.
Only beta.destinyitemmanager.com has the issue.
Attached browser console logs from Chrome and Firefox.
[firefox-console-export-2019-11-2_10-25-42.txt](https://github.com/DestinyItemManager/DIM/files/3800477/firefox-console-export-2019-11-2_10-25-42.txt)
[chrome-beta.destinyitemmanager.com-1572686354460.log](https://github.com/DestinyItemManager/DIM/files/3800478/chrome-beta.destinyitemmanager.com-1572686354460.log)

**Comment by bhollis** [comment]
Fixed, thanks for the report.
