### ISSUE TITLE
Can't pull gambit synths directly from the postmaster to the vault

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#4652]
Current beta.  Chrome on Windows 10.

If you have synths in the postmaster and attempt to transfer them directly to the vault, it transfer them to the character and then throws an error.

Console log below:
```
POST https://www.bungie.net/Platform/Destiny2/Actions/Items/TransferItem/ 500
breadcrumbs.ts:117 error moving item Sentry Synth to Vault Error: Bungie.net message: There was an unexpected problem decoding the input data.
    at d (bungie-service-helper.ts:86)
    at p (bungie-service-helper.ts:211)
    at async f (bungie-service-helper.ts:42)
    at async O (item-move-service.ts:419)
    at async Object.L [as moveTo] (item-move-service.ts:973)

```

**Comment by bhollis** [comment]
Is this still happening? Sounds like an API bug but I'm not sure.

**Comment by philkernick** [comment]
Yup.  100% reproducible.

**Comment by bhollis** [comment]
Are you pulling it from the current, or a non-current character?

**Comment by philkernick** [comment]
Current character.

**Comment by bhollis** [comment]
I can't see this happening in Sentry. Closing, feel free to reopen if it still reproduces, keeping in mind Gambit Synths only have a couple more months of relevance.
