### ISSUE TITLE
maxbasestatvalue isn't modified by additional query terms

### ISSUE THREAD

**Issue by irons** [DestinyItemManager/DIM#4658]
In 5.52.1, `maxbasestatvalue:recovery` highlights 20 items for me, 19 of which are armor 1.0 items, which were retconned to 20 recovery. 

I expected `maxbasestatvalue:recovery is:armor2.0` to display the highest-recovery-stat items in each slot that could accept 2.0 mods. Instead, the existence of higher recovery stats on armor 1.0 gear excludes all but one item (which is Masquerader's Hood, because of a [different bug](https://github.com/DestinyItemManager/DIM/issues/4657)). 

It would be useful to have a way to ask for the highest stat value after taking other factors into account, like character class or armor type. `maxbasestatvalue` can't yet do that.

Thanks for your time.

**Comment by sundevour** [comment]
### re: Y2 armor:
you say retcon but those are in fact the armors' effective stats.
they're weirdly minmaxed but they are as advertised.
the `max` filters were meant as a convenience for finding exactly what they find, exactly what those Y2 armors represent: stat peaks.
you can probably use their stat toggle in the game to stop them from being so weird. 

over time, with enough rolls, y3 armor rolls will overtake these anyway if you're optimizing for recovery. 20 isn't groundbreakingly high.

### re: expected filter behavior
no search filter currently does
[set of filters]->[calculations based on what's left]
this is a feature of the loadout optimizer.

additionally, if an armor has 1 high stat and a bunch of terrible ones, again that's not something you can search for exactly. that's something the loadout optimizer is made to figure out for you.

### that said,
i'm not against it, it just isn't part of existing search behavior so there was no system in place for it for me to hook into. i shoehorned it in using the exact same thing as `is:maxpower`. that doesn't obey other filters either right now.

**Comment by bhollis** [comment]
I think you're looking for the Loadout Optimizer. Replicating all the functionality of LO within search isn't likely to happen.

**Comment by irons** [comment]
For posterity's sake, the reason I don't use the Loadout Optimizer is that it's built to answer the question, "What's the best outcome I can reach from all the stuff I've got?", while the question that I nearly always want to answer is, "Will I regret getting rid of this particular piece of gear?"

`maxbasestatvalue`, if it could operate in conjunction with other search terms, would be useful to me in evaluating gear quality from a bottom-up perspective. The top-down perspective offered by the Loadout Optimizer isn't practical for helping to clear vault space.

**Comment by billwert** [comment]
I hit a derivation of this the yesterday. I wanted to know what my highest total stat base arc helmet was, so I tried `maxbasestatvalue:total is:arc`. It didn't work for similar reasons.

The loadout optimizer might get me there (though it's not immediately obvious how) but it definitely feels like a pretty big hammer for such a simple question. (I also don't see a way to say "show me the highest stat total thing" there.)

**Comment by bhollis** [comment]
Thanks for all the examples folks. I think this can be summarized as the expectation that the maxbasestatvalue queries are operating based on the other filters, when in reality they’re just global. I don’t see that being fixed anytime soon because it’ll be very difficult to do so, though of course PRs are welcome. If this proves to be too confusing, maybe we should just remove this search.

**Comment by NevanNedall** [comment]
I might be being presumptuous, but would this not simply be an order of operations issue? Or is it more complicated than that?

**Comment by bhollis** [comment]
It is, in fact, more complicated than that.
