### ISSUE TITLE
Recommended perks for rated items not displaying

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#4662]
The new sockets logic changed a lot - I suspect that they have broken roll-based ratings and community recommended perks.

**Comment by 48klocs** [comment]
I looked, and we're getting almost no data back outside of fixed rolls (I can find just one non-exotic, non-curated weapon that has any rating data for it which is... not great).

I reached out to the DTR folks to see if we need to make some changes post-perkpocalypse.

**Comment by bhollis** [comment]
Any updates on this? Should we disable ratings?
