### ISSUE TITLE
Close button in new mod selector doesn't work

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#4666]
The new mod selector panel is excellent.

However once popped up, the X close button in the top right corner doesn't do anything.  And in this state clicking anywhere else doesn't do anything either.

The only way to close the mod popup and the equipment popup is to press ESC.

**Comment by thomaskchan** [comment]
I have the same issue.

Version 5.55.1.5660 (beta), built on 11/5/2019, 1:10:29 AM

**Comment by bhollis** [comment]
Fixed!
