### ISSUE TITLE
Beta: Weapon mod mouseover is missing description 

### ISSUE THREAD

**Issue by thomaskchan** [DestinyItemManager/DIM#4669]
Version 5.55.1.5660 (beta), built on 11/5/2019, 1:10:29 AM

When inspecting a weapon, mousing over the mod or masterwork no longer pops up the box above with the description of the mod or what the masterwork is.

The name of the mod or the "Masterwork"/"Tier 3 Weapon" name does show in a box below after a second or two, but all that does is make it feel sluggish.

**Comment by bhollis** [comment]
Give it a little click and see what happens

**Comment by thomaskchan** [comment]
I did see that a click goes to the new mod menu, but I think it's a lot faster to quickly sweep over the installed mods to see what they are rather than have to click on each one (or wait for the lower name popup).  Could we keep the previous description mouseover and still have the click to see mods?

For that matter, the mod menu could also benefit from the same mouseover descriptions.  It's a nice reference to see what mods are available, but having to click on each one is pretty slow.

**Comment by wickles** [comment]
Shaders and ornaments too. I appreciate the click-thru menu showing what can be slotted in, but I definitely prefer seeing what's currently applied to mods/cosmetics with a quick hover.
