### ISSUE TITLE
Can’t move items to a full category

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#4673]
If all weapons are full and the vault is full, but there’s armor space on characters, I cannot move a weapon to the vault. It should squeeze out an armor. Something is subtly wrong with the new move logic.

**Comment by sundevour** [comment]
while you are at this, user reported that shaders are no longer being shifted vault->character, to make vault space. this seems like extremely free vault space and i'd swear it used to happen.

**Comment by bhollis** [comment]
Yeah I'd expect that's the same issue.
