### ISSUE TITLE
feature request: sort by stats total

### ISSUE THREAD

**Issue by cnf** [DestinyItemManager/DIM#4675]
Make it so we can sort by stat total for armor.

![image](https://user-images.githubusercontent.com/252949/68426190-e0266400-01a7-11ea-9f46-e2836311a306.png)

so sort it by the 61 here.

**Comment by kyleshay** [comment]
Think this may be resolved by #4377

**Comment by bhollis** [comment]
Which sort are you referring to? In the compare view?

**Comment by DHager** [comment]
@bhollis 

I suspect they mean the "Item Display" configuration settings where you can set a custom sort order by character, power-level, tag, etc.

**Comment by cnf** [comment]
Sorry, I quickly filed this request just before starting a raid.

Finding the armor with the best/highest stats is rather hard atm, as @kyleshay mentioned, having looked at it, #4377 might indeed solve it...

My original request was for adding stats total here:
![image](https://user-images.githubusercontent.com/252949/68551898-9f318800-0411-11ea-944e-d53c122f9296.png)

But in the end, finding the gear with the best stats is what I am after, whatever UI gets me there.

**Comment by DHager** [comment]
IMO the difference between armor with base-stat-total of 54 versus, say, 57 is unimportant compared to *where* those stats are allocated. It's not like power-level where more is always measurably better.

If you're trying to apply a single cutoff for "terrible" (or "great") perhaps a filter-term instead? Ex: `not:exotic is:armor2.0 basestat:total:<55`

**Comment by cnf** [comment]
To me, DIM _IS_ the external tool...
(and my cutoff is <=60)

**Comment by bhollis** [comment]
I think you're best served by a search, or the upcoming vault organizer, than by sorting inventory.
