### ISSUE TITLE
Non-Armor 2.0 Class Items Only Showing Selected Perks

### ISSUE THREAD

**Issue by wein3967** [DestinyItemManager/DIM#4676]
While we can now see/filter on non-selected perks for weapons and armor, I noticed that class items (at least for my titans) only shows the selected perk instead of the whole perk set.
![image](https://user-images.githubusercontent.com/11590326/68431893-e4875880-0178-11ea-8765-47686712e58f.png)

**Comment by delphiactual** [comment]
Yep,

https://github.com/Bungie-net/api/issues/1123
