### ISSUE TITLE
Add option / toggle to exclude ghost from loadout optimizer

### ISSUE THREAD

**Issue by doktor5000** [DestinyItemManager/DIM#4680]
Currently when switching to loadout optimizer, seems it randomly picks some ghost and as this is part of the default loadout, it will also be applied. So if you try out a few loadouts, after a few times you end up with your ghost slot filling up, even though the ghost does not change anything on those loadouts regarding stats.

I'd like to have a toggle or an option to exclude ghosts from loadout optimizer or make it opt-in to have the ghost excluded by default.

**Comment by johyphenel** [comment]
+1, it's worse for me cuz I have 3 or the same ghost for my characters, so I can't even tell which one to pick manually to stop it from messing with my ghost distribution.

**Comment by bhollis** [comment]
If you create a loadout you can just X out the ghost.

**Comment by doktor5000** [comment]
> If you create a loadout you can just X out the ghost.

Totally aware about that, but that adds two extra steps when using the optimizer and directly equipping stuff (what people usually do before creating loadouts, trying them out) - you have to create the loadout, then edit it and X out the ghost.


Another possibility would be to simply select the currently equipped ghost as default, maybe that would be easier to implement. I don't even understand why it always selects a different ghost ...

**Comment by bhollis** [comment]
That’s a good idea, I can change that. The idea is you can select ghost by perks, just like all the other items. By default it just picks based on tier.
