### ISSUE TITLE
Add option for Loadout Optimizer to assume that all items are fully masterworked

### ISSUE THREAD

**Issue by KyoukanGG** [DestinyItemManager/DIM#4682]
Fully masterworking an armor item adds 2 to each stat, but it's difficult for a player to determine when an item is worth masterworking.

When combined with minimum tier targets on individual stats, if we assume that all armor is masterworked we can potentially allow for better overall stat distributions. This would effectively allow a user to figure out which pieces they _should_ masterwork.

Having this as an option would allow for users who want to find the best current loadout, and then toggle to find the best loadout to masterwork.

**Comment by ryan-rushton** [comment]
I will check this out

**Comment by HotCoolAid** [comment]
I really hope this will enter Loadout Optimizer so we can start min-maxing our builds. Following this.

**Comment by ryan-rushton** [comment]
@HotCoolAid, I've been a bit busy lately but I have some time coming up to look at this and hopefully sort something out.
