### ISSUE TITLE
clicking 'compare filtered items' or 'compare items' sometimes returns wrong results

### ISSUE THREAD

**Issue by jerrycarlson** [DestinyItemManager/DIM#4685]
I'm using the latest Google Chrome browser and DIM.

I enter any armor 1.0 or armor 2.0 search term in the inventory filter box.  The inventory highlights the correct item(s) but clicking the "compare filtered items" button in the search box OR clicking the "compare items" button in a highlighted item sometimes returns an incorrect list of items.  All items in the incorrect list are of the same/"correct" element, though.  Also, this problem does not appear to occur with weapons.

Example 1 (see image).  I clicked the "compare filtered items" button in the search box and these are the results.  I got the exact same results when I clicked the "compare items" button from the (properly) highlighted item's stats detail window.

The bug is not universal.  For example, dreambane robes (armor 2.0) in my inventory work just fine, whether clicking compare items from the filter box or from any of the dreambane robes in inventory.  Same with vigil of heroes robes (armor 1.0) -- they work just fine in DIM for me.  Some exotics work just fine, too, even if I have both 1.0 and 2.0 versions of a piece in inventory, and regardless of whether I clicked the compare box from either a 1.0 or a 2.0 piece.

In contrast to the above exceptions, my dreambane gloves DO NOT work just fine and return the long incorrect comparison list.

Example 2 (see image).  Same problem as in Example 1, but this comes from a blue item.

<img width="905" alt="example 1" src="https://user-images.githubusercontent.com/9376071/68522127-60fb6380-026d-11ea-9e39-a287840a392f.PNG">
<img width="946" alt="example 2" src="https://user-images.githubusercontent.com/9376071/68522131-6789db00-026d-11ea-8521-121bdf458157.PNG">

**Comment by jerrycarlson** [comment]
FYI this bug also appears in the beta DIM site.

**Comment by sundevour** [comment]
this is because these searches have only 1 result, what are you trying to compare?

**Comment by jerrycarlson** [comment]
Ah, I see now.  My "gameside companion" device used for DIM has a smaller screen and the keyboard can be awkward to use as compared to using the mouse, so I often use the compare items button as a shortcut to entering an item's name in the filter box when searching for duplicates.  It's a faster workflow: click any given item in inventory and then click the compare button on the popup.  I don't recall this search result behavior in previous iterations of DIM, so it was unexpected to see a "full" list of different items when searching for like-only items.

**Comment by sundevour** [comment]
i understand where the confusion comes from, the behavior has changed. it's understandable it misled you.

now that "sameness" is narrower than ever (armor element really matters, armor 2.0 vs 1.5)
if you start a comparison with just 1 item, DIM looks for the narrowest sameness category with multiple items, and compares that.

the narrowest category to compare your single stormdancer to in this case, is "arc chest armor".

**Comment by DHager** [comment]
I'm suffering confusion from the same... uh... bug/feature. 

My workflow is searching within particular categories, then clicking "Compare filtered items", then looking at the nice side-by-side armor stat numbers.

However when there is just one result, it returns all items of the same "model". This can be extra-confusing when some items have ornaments so that they *appear* to be different.

**Comment by sundevour** [comment]
i'm fine with changing this behavior. filter compare does seem like a different intention.

**Comment by G4te-Keep3r** [comment]
The element being considered when comparing is why thees 2 give diff results instead of each other, right?

![1](https://user-images.githubusercontent.com/15348093/69207537-be1cd200-0b15-11ea-995a-07469417f20d.PNG)
![2](https://user-images.githubusercontent.com/15348093/69207538-be1cd200-0b15-11ea-83cf-b4a22f14af41.PNG)

**Comment by G4te-Keep3r** [comment]
or related to postmaster vs inventory where it worked?

![3-odd](https://user-images.githubusercontent.com/15348093/69208158-2ec4ee00-0b18-11ea-9f29-5bae24bbc869.PNG)
