### ISSUE TITLE
GoS raid progress tracking is not working properly.

### ISSUE THREAD

**Issue by subject17** [DestinyItemManager/DIM#4688]
It seems that once a character has completed the final boss encounter, the GoS encounter tracking will complete disappear from the UI.

<img width="981" alt="Screen Shot 2019-11-10 at 03 19 08" src="https://user-images.githubusercontent.com/17754103/68531727-9be2c180-0369-11ea-90d1-ba06f7ce0e6a.png">

As you can see here, one of my character only completed the boss encounter and no other encounters in GoS. The GoS progress is nowhere to be found in the UI. Meanwhile my other two characters who have not done the raid can see the GoS tracking in UI just fine.

<img width="970" alt="Screen Shot 2019-11-10 at 03 29 35" src="https://user-images.githubusercontent.com/17754103/68531806-5bd00e80-036a-11ea-9395-aa9f2d026174.png">

**Comment by sundevour** [comment]
i am dissatisfied with this too.
the API is treating this raid differently from the others.
the information just stops showing up after you clear the ![image](https://user-images.githubusercontent.com/31990469/68539907-e6027d80-033e-11ea-9172-dd35a0e88f36.png) symbol from it

gonna file a bungie issue but don't expect a fix soon/ever.
