### ISSUE TITLE
Armsday Rolls

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#469]
> Long press those Armsday packages in your inventory to see all 3 roll that are waiting for you in the Tower.
> 
> You no longer need to fly to the tower and fight the stupid in-game interface that keeps reseting back to the first weapon when you want to see the rolls on the 2nd or 3rd purchase.

Here's a new feature from Ishtar Commander.  Something to consider.

**Comment by kyleshay** [comment]
cool! riffing on this, would be cool to set up an toaster that alerts you when perks that you manually set are on an armsday weapon. would require quite bit of UI work though. not a priority, but something to consider if something is looking for something to work on.

**Comment by kyleshay** [comment]
#809 link
