### ISSUE TITLE
Feature request: Auto-updating wishlists with GitHub

### ISSUE THREAD

**Issue by LukePeltier** [DestinyItemManager/DIM#4697]
As someone who is very thankful for the voltron.txt wishlist, it would be awesome if I could give DIM a link to the file to use instead of a downloaded copy. This way, when the file is updated through git, I don't have to keep track of it myself and manually update it.

**Comment by bhollis** [comment]
Linking #4382 and #4418

**Comment by 48klocs** [comment]
New setting is in.
