### ISSUE TITLE
Update React version to 16.11

### ISSUE THREAD

**Issue by gaspardip** [DestinyItemManager/DIM#4698]
The main idea is to update React to at least 16.8.6, so hooks become available, but since there are no breaking changes between that version and 16.11, bumping to the latter should be no problem.

Motivation: react community seems to be moving to functional components since hooks were released as stable. Although I don't think the React team will ever remove class based components, it's better to stay up to date with current practices. There's only one case that can't be refactored into hooks as today and that is Error Boundaries, these still need to be classes, until they figure out a `useBoundary` hook or similar. This would be a pretty good opportunity to update react-redux to be able to use hooks like `useSelector`, `useDispatch`, etc (instead of `connect`).

Some benefits of functional components + hooks are:

* less code
* reusable state logic through custom hooks
* easier to read, understand and test
* potential performance boost in the future (according to the React team)

The refactors would be incremental, all new code should be written using hooks, old code would be slowly refactored.

Is this something you would be interested in?

**Comment by bhollis** [comment]
We are already on the latest public React release, and we use hooks extensively.
