### ISSUE TITLE
Inventory error when Tag is included in a custom sort order

### ISSUE THREAD

**Issue by cproscia** [DestinyItemManager/DIM#4699]
When Tag is included in a custom sort order, the Inventory can fail to load with error:

> Cannot read property 'sortOrder' of undefined.

**Workaround:**
Open settings and uncheck Tag under "Sort items by:"

**Repro steps:**
1. Somehow, have an inventory item with an invalid tag
2. Open settings and check Tag under "Sort items by:"
3. Open Inventory

In filters.ts, the error happens on the second line below:
```
const tag = getTag(item, store.getState().inventory.itemInfos);
return tag ? tagConfig[tag].sortOrder : 1000;
```

**Additional information:**
In getTag(), I somehow have an item with {tag: "Tag item"}

If you want to see which item has the invalid tag, it also appears this way in the exported inventory spreadsheet.

**Comment by delphiactual** [comment]
Sentry issue: [DIM-FDG](https://sentry.io/organizations/destiny-item-manager/issues/1327149817/?referrer=github_plugin)
