### ISSUE TITLE
modslot:outlaw does not work

### ISSUE THREAD

**Issue by DoctorVanGogh** [DestinyItemManager/DIM#4702]
Currently of the four available `modslot` filters `outlaw` does not work (in beta)

While `forge`, `opulent` & `undying` all correctly highlight their respective armors, `outlaw`does *not* seem to work. Should filter Reverie Dawn gear, but it doesn't :(

**Comment by sundevour** [comment]
cool, i will take a look. i think i can guess why and it's because of riven's curse not technically being an outlaw mod

**Comment by sundevour** [comment]
@DoctorVanGogh this should be fixed at beta.destinyitemmanager.com

please let me know if it is working right for you, i don't have reverie dawn armor handy.

**Comment by DoctorVanGogh** [comment]
Yay - looks fixed 👍 

![image](https://user-images.githubusercontent.com/324067/68989607-73ffcc00-0849-11ea-9288-b00988a2f350.png)

Thanks!
