### ISSUE TITLE
Unable to set up Google Drive (Safari)

### ISSUE THREAD

**Issue by bystritskiy** [DestinyItemManager/DIM#4703]
<img width="292" alt="Screenshot 2019-11-12 at 16 47 36" src="https://user-images.githubusercontent.com/16685049/68676932-22ff8780-056c-11ea-95cb-ef1c9ed213d3.png">

**Comment by delphiactual** [comment]
Ensure you have enabled third party cookies as those are disabled by default and required for using Google drive...

**Comment by gbravery** [comment]
I'm not sure if its relevant - i am seeing the same issue in a chrome beta (on beta dim, and normal dim).

I see this repeating in my console:
A cookie associated with a cross-site resource at <URL> was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at <URL> and <URL>.

I don't believe i have a 3rd Party Cookie blocker running to stop this functioning.

**Comment by delphiactual** [comment]
Nothing to do with this issue. You may have not enabled a 3rd party cookie blocker, but Safari has one built-in that you have to opt-out of

**Comment by bystritskiy** [comment]
Thank you so much!

**Comment by bystritskiy** [comment]
Thank you so much!
