### ISSUE TITLE
DIM won't update character data

### ISSUE THREAD

**Issue by VirtualValtyr** [DestinyItemManager/DIM#4704]
I've been wanting to use DIM since I came back to Destiny 2, so when I checked it wouldn't updatre, it only had old info. I asked around and I was told Bungie revoked 3rd party data access during launch. 
I said ok and waited. 
Some friends told me that it was working today, so I go and check and the info is still old. Max character at 750 when I'm over 940. 
Why isn't my info updating? I cleared all info in temp and used CCleaner to clean all browser info. I even removed the browser extension and re-added it. Same thing. 
How do I get it to update so I can start using it?
thanks

**Comment by delphiactual** [comment]
Screenshot please

**Comment by VirtualValtyr** [comment]
> Screenshot please

![image](https://user-images.githubusercontent.com/57686820/68773667-d6a25f00-05e0-11ea-8632-414816687e1d.png)

**Comment by delphiactual** [comment]
Click on the menu icon, and verify you are on the correct platform

**Comment by VirtualValtyr** [comment]
> Click on the menu icon, and verify you are on the correct platform

fk me. I was looking for that. It used to be at the top. 
Thank you lol

**Comment by VirtualValtyr** [comment]
For those that have this problem, he meant this: 
![image](https://user-images.githubusercontent.com/57686820/68774355-d8b8ed80-05e1-11ea-96f6-c2b294a8889f.png)
