### ISSUE TITLE
Unable to authenticate to Google Drive (chrome beta)

### ISSUE THREAD

**Issue by gbravery** [DestinyItemManager/DIM#4708]
Not aware of any third party cookie blockers that I am running.

Working fine on my mobile and on my ipad - so assuming it relates to the Chrome Beta I am running (79.0.3945.29).

I am seeing this when I attempt to re-connect:
Authorizing Google Drive...
We were unable to set up Google Drive.

Go back to DIM

I see 12 instances of:
A cookie associated with a cross-site resource at <URL> was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at <URL> and <URL>.

No idea if this relates... but its the only messages I see in the console at the time.
Other than a final "gdrive init complete".

**Comment by bhollis** [comment]
We won't be investing any more in Google Drive: #4418

**Comment by gbravery** [comment]
FWIW, I have managed to install a policy that reverts the SameSite cookie change that is in the beta of Chrome to a legacy state.
https://www.chromium.org/administrators/policy-list-3/cookie-legacy-samesite-policies
and the google drive functionality now works again.

So whatever is going on, does relate to this:
https://www.chromium.org/updates/same-site

I'm not sure if this is something that you need to prepare for, or that google's cookies will fix?
but thought since I found a work around and possible cause I should report it.

**Comment by bhollis** [comment]
We will simply delete Google Drive integration.
