### ISSUE TITLE
suggestion: sort items by element type/affinity (armor and weapons) setting

### ISSUE THREAD

**Issue by mc711** [DestinyItemManager/DIM#4711]
title

**Comment by DHager** [comment]
For the purposes of such sorting, I'd suggest Armor 1.0 pieces should be considered their own single "legacy" element.

That will avoids "false positives" when people are looking for armor that can support a certain 2.0 mod setup.

**Comment by bhollis** [comment]
This'll be a feature of the Vault Organizer. In general we won't be adding more sort types for the inventory page, since organizing them is better done in the Organizer.
