### ISSUE TITLE
All Inventory moved by Changing Loadouts

### ISSUE THREAD

**Issue by Keule-81** [DestinyItemManager/DIM#4733]
Hey there ...
Warning - German Guy writes in English😬
I have since yesterday the Problem, that when i changed  a loadout all stuff that i have in my Inventory would be moved in the Vault!?
Do i something wrong now ... I have already looked in the settings if i changed something there, but i cant find anything 😕
Thanks in advance for your Help

**Comment by delphiactual** [comment]
In your loadout did you select `Move other items away`?

**Comment by Keule-81** [comment]
No, thats the Poin^^ I set the Marker in No one of my Loadout^^ That's why i'm so confused though 😅

**Comment by delphiactual** [comment]
Are you using `app.destinyitemmanager.com` or `beta.destinyitemmanager.com`?

**Comment by delphiactual** [comment]
Can you try again on version 5.57.0.5832?

**Comment by bhollis** [comment]
Not sure I can reproduce this one. Can you describe exactly how to reproduce this issue?

**Comment by Keule-81** [comment]
Hey there ... Sorry for the Late Answer ....
This was not the only Issue..
I have Generell Issues with my PC this time and after a complete new Setup
from Windows and all that stuff, my PC and the DIM aswell now working
Perfectly for me!!!!
Thanks for all your help and Tipps so fast!!! I appreciate that
Regards Dirk aká Keule

Am Do., 28. Nov. 2019 um 03:43 Uhr schrieb Ben Hollis <
notifications@github.com>:
