### ISSUE TITLE
Object(...X...).flat is not a function

### ISSUE THREAD

**Issue by RafaG** [DestinyItemManager/DIM#4734]
I received this error when I try to load my equipement from inventory.

**Comment by delphiactual** [comment]
can you post the logs from the console please?

**Comment by delphiactual** [comment]
Sentry issue: [DIM-FHV](https://sentry.io/organizations/destiny-item-manager/issues/1345029165/?referrer=github_plugin)

**Comment by delphiactual** [comment]
Sentry issue: [DIM-FJ0](https://sentry.io/organizations/destiny-item-manager/issues/1345571143/?referrer=github_plugin)

**Comment by Jaysterlo** [comment]
I have the same problem

**Comment by pjtarheel** [comment]
same here,  can't transfer more than one item at a time (search results, max power, loadouts).

**Comment by tpihl** [comment]
same issue here

**Comment by n3k027** [comment]
Same issues, it seems to affect the maximum light button too.
![Screenshot_20191120-231429_Chrome](https://user-images.githubusercontent.com/58024557/69315516-8f712b00-0beb-11ea-9ddb-8289f7fce945.jpg)

**Comment by Bhold353** [comment]
Have the same problem. Have yet to see a solution.

**Comment by Bhold353** [comment]
Loadout transfer works on my Ipad, but not on y Laptop.

**Comment by delphiactual** [comment]
Browser versions please

**Comment by RafaG** [comment]
Google Chrome 78.0.3904.108

**Comment by WittyyXD** [comment]
Also having this same issue. No transferring loadouts at all, on my Win 10 Insider Preview tablet, or my 2 Desktops with DIM Beta App and Browser versions. Normal DIM seems to work, but cannot load my Google Drive cloud-saved loadouts to that app.

**Comment by tpihl** [comment]
DIM is currently useless so i hope this get merged soon. But there is other item manager, so maybe best to switch

**Comment by Bhold353** [comment]
Google Chrome 69.0.3497.100 (Official Build) (64bit)

Bill

**Comment by n3k027** [comment]
> Browser versions please

**Windows PC**
Google Chrome Version 78.0.3904.97 (Official Build) (64-bit)

**Galaxy S10**
Google Chrome Version 78.0.3904.108

**Comment by bhollis** [comment]
Fixed, sorry about that.

**Comment by bhollis** [comment]
Also just for reference, Beta is where we test things out (so thanks for reporting bugs!) but you can always go back to the release version. Settings/loadouts can be exported and re-imported between versions.

**Comment by n3k027** [comment]
You are awesome @bhollis

**Comment by Bhold353** [comment]
Seems like this has not been fixed.  If so, please advise what to do.

**Comment by delphiactual** [comment]
@Bhold353 did you click on `Update DIM`?

**Comment by Bhold353** [comment]
Working now w/o needing update...thanks.

Bill

**Comment by RafaG** [comment]
Working! Great!!! Thanks a lot!
