### ISSUE TITLE
Feature request: toggle to show all weapons as masterworked in the comparison dialogue

### ISSUE THREAD

**Issue by jerrycarlson** [DestinyItemManager/DIM#4735]
Just saw in the upcoming changes section on the beta site: "Option to pretend all Armor 2.0 items are masterworked in the Loadout Optimizer."

My feature request?  PLEASE let us toggle this display for WEAPONS in the comparison dialogue.  A surprising number of times, I find myself comparing duplicates with close stats but incomplete masterworks: "Maybe this one's handling bump from full masterworking makes it better than that one's range bump.  What to do??", etc.  I used to end up jumping over to banshee-44 to see masterwork effects but that functionality was removed from DIM a while back.  Either way, having the functionality in-app would be vastly superior anyway.

Thank you all VERY MUCH for the hard work you've put in to making DIM such an essential part of the Destiny gameplay experience.

**Comment by bhollis** [comment]
To be really specific, you mean "pretend all items are masterworked given their existing masterwork type"?

**Comment by bhollis** [comment]
Also, in DIM you can click on the masterwork and select other tiers to see what it'll do (just like Banshee-44 used to do).

**Comment by jerrycarlson** [comment]
Yes: “Pretend all weapons are masterworked given their existing masterwork type.”

 

I didn’t extend the feature request to cover “all items” (i.e., including armor) because I assumed it would be simpler to code for just weapons in the comparison dialogue.

**Comment by jerrycarlson** [comment]
I wasn’t aware of that feature – pretty neat.

**Comment by bhollis** [comment]
This'll be a feature in the Vault Organizer - specifically the ability to display base stats instead of
