### ISSUE TITLE
DIM won't download

### ISSUE THREAD

**Issue by killaflowerz** [DestinyItemManager/DIM#4738]
Please help me!

DIM was having some issues with pathways so i uninstalled it and chrome, then reinstalled chrome and now i cannot download DIM

**Comment by delphiactual** [comment]
How are you trying to access DIM?

**Comment by killaflowerz** [comment]
im trying to download it as the desktop app

**Comment by delphiactual** [comment]
So again, how are you trying to access it

**Comment by killaflowerz** [comment]
im not quite understanding your question

**Comment by delphiactual** [comment]
Go-to https://app.destinyitemmanager.com or https://beta.destinyitemmanger.com click on the menu in the upper left and select `Install DIM`

**Comment by killaflowerz** [comment]
when i do that it i click the other install button and nothing happens, it doesnt download anywhere and it doesnt open up as if it were downloaded

**Comment by delphiactual** [comment]
Check your desktop

**Comment by killaflowerz** [comment]
no DIM there either

**Comment by delphiactual** [comment]
![image](https://user-images.githubusercontent.com/4798491/69381189-65fae280-0c71-11ea-85cd-665d326f52e5.png)
what about here? DIM is not a download. DIM is a PWA...

**Comment by delphiactual** [comment]
![image](https://user-images.githubusercontent.com/4798491/69381345-cab63d00-0c71-11ea-8d97-f5104e22b9d4.png)
What about here? DIM is not available as a download, but as a PWA.

**Comment by delphiactual** [comment]
Do you have PWA's enabled in chrome?

**Comment by killaflowerz** [comment]
yes i enabled them

**Comment by killaflowerz** [comment]
i tried installing it again but the same thing happens, nothing

**Comment by killaflowerz** [comment]
![Capture](https://user-images.githubusercontent.com/58050693/69383466-b11ff000-0c87-11ea-89f7-29925b1a0b5d.PNG)

**Comment by killaflowerz** [comment]
the last time i had DIM installed this was enabled as well but this time for some reason it wont let me install it

**Comment by delphiactual** [comment]
Have you restarted chrome after enabling?

**Comment by killaflowerz** [comment]
yes

**Comment by delphiactual** [comment]
Can you try edge chromium?

**Comment by killaflowerz** [comment]
what is that?

**Comment by delphiactual** [comment]
https://support.microsoft.com/en-us/help/4501095/download-microsoft-edge-based-on-chromium

**Comment by killaflowerz** [comment]
okay so i got it to install from edge chromium but why wont it download from google chrome?

**Comment by delphiactual** [comment]
Try these steps:

https://medium.com/@dhormale/install-pwa-on-windows-desktop-via-google-chrome-browser-6907c01eebe4

**Comment by killaflowerz** [comment]
i have also tried that, i would click the 3 dots then click install then it would tell me to click install from the little plus sign in the right side of the search bar and i do then nothing would happen

**Comment by delphiactual** [comment]
This appears to be a Chrome problem on your computer

**Comment by killaflowerz** [comment]
what do u recommend i do? i already uninstalled and reinstalled it
