### ISSUE TITLE
DIM shows Destiny 1 rather than Destiny 2

### ISSUE THREAD

**Issue by YourNemesis** [DestinyItemManager/DIM#4741]
When I open DIM, it is showing my Destiny 1 account. How do I view my Destiny 2 account?

**Comment by delphiactual** [comment]
click on the menu in the upper left and look at the lower left for accounts

**Comment by YourNemesis** [comment]
> click on the menu in the upper left and look at the lower left for accounts

I did that, however, it is only showing my Destiny 1 Xbox account and not my Destiny 2 steam account.

**Comment by YourNemesis** [comment]
The Bungie website says some services are down, so this might be the reason I'm having this problem.
