### ISSUE TITLE
Feature Request: Filter Quests by Season

### ISSUE THREAD

**Issue by Kalus** [DestinyItemManager/DIM#4742]
The search bar should be able to filter by season on the Progress tab, similar to on the Inventory tab. Since the search bar appears to function identically regardless of tab, it's confusing that that filter doesn't apply. 

E.G. Search: `season:undying` should highlight Field Testing, Survivalism, Ghosting, etc.

**Comment by Kalus** [comment]
Excellent, thank you!

**Comment by Kalus** [comment]
Hi @delphiactual, I noticed that the quests Let Fly and Desperate Measures both show up when a search is done for "season:undying". Not sure why. Other than that, working as expected.

**Comment by delphiactual** [comment]
Those both became quests when season of undying was released, season information is gleaned by when an item (or quest in this instance) is added to the manifest. I will fix them manually
