### ISSUE TITLE
Last version to support iOS 10.3.3 is 5.57.0

### ISSUE THREAD

**Issue by piyo** [DestinyItemManager/DIM#4756]
Thanks for this app, I've been using it since the D1 days.

A couple of days ago, I was no longer able to use DIM on my iOS 10.3.3 iPad (which I realize is not supported by DIM). The page does not render anything and the background is gray, as if the CSS has loaded. Not even the unsupported block at the bottom is visible. My Windows 10/Chrome system on the same network is able to use DIM. 

After easily installing the Dockerized local dev environment (which btw was my first time to use Docker), I was able to determine tag 5.57.0 (17efbca54) is probably the last commit that I can load and use on my device. Also I reconfirmed that a commit close to 5.58.0 (9895b293f) did not work.

I want to keep using this iPad for DIM. I am going to attempt to git bisect to find the true upper bound and maybe backport newer commits, haha. I should be working on my Titles/Seals, though.

Another fellow 10.3.3 user, separated by time... #3247

**Comment by bhollis** [comment]
That's unfortunate, but we have officially dropped support for iOS 10.3 and will not be testing on it. Good luck keeping it alive!
