### ISSUE TITLE
vendor Visage of Calus is missing

### ISSUE THREAD

**Issue by TeeTeeHaa** [DestinyItemManager/DIM#4757]
In the "Vendors" tab on the left under "Destinations" there is no more "Visage of Calus". It had been there and is dearly missed.

Version 5.58.0 (release), built on 11/25/2019, 6:55:49 AM
Firefox 70.0.1 (64-Bit) on Windows 7
PC user logged in via Steam

**Comment by bhollis** [comment]
Filed a bug with Bungie: https://github.com/Bungie-net/api/issues/1154
