### ISSUE TITLE
Feature Request: Have Loadout Optimizer pretend that your pieces are masterworked

### ISSUE THREAD

**Issue by tehtrav** [DestinyItemManager/DIM#4758]
So Masterworking armor pieces makes a huge difference in what combinations will let you achieve high tier builds... The problem is that until you Masterwork an armor piece, DIM will only consider it's current stats. I would love a feature that would let me toggle masterwork on a piece even before I do it in game, to see if it will fit into any new builds. Or even toggle masterwork on ALL armor pieces, to find what my best possible build to fully Masterwork would be.

**Comment by duckmanBR** [comment]
Can't check right now, but since #4722 is from last week, prod should have the update that do what you're asking.  Make sure you are on the latest version, it should be 5.58

**Comment by tehtrav** [comment]
@duckmanBR well look at that. Thanks for the link!
