### ISSUE TITLE
The Traction Mod doesn't show up in the Loadout Optimizer perk search tool. 

### ISSUE THREAD

**Issue by tehtrav** [DestinyItemManager/DIM#4759]
The Traction perk from Armor 1.0 appears, but not the Armor 2.0 Mod version.
<img width="1368" alt="Screen Shot 2019-11-26 at 3 50 15 PM" src="https://user-images.githubusercontent.com/351975/69671672-860d1600-1064-11ea-8e47-a80eaa5f6449.png">

**Comment by ryan-rushton** [comment]
It appears in my one, have you actually unlocked it? It's not unlocked by default from my understanding.

<img width="409" alt="Screen Shot 2019-11-27 at 8 10 25 pm" src="https://user-images.githubusercontent.com/7344652/69709690-fba2e000-1151-11ea-9f4d-6c0f917d9f9c.png">

**Comment by tehtrav** [comment]
Yup, it's unlocked and I have it on a bunch of my leg armor pieces

**Comment by tehtrav** [comment]
Here's another user reporting a similar issue FYI: https://www.reddit.com/r/DestinyItemManager/comments/e1f02v/unable_to_select_traction_mod_in_loadout_optimizer/

**Comment by bhollis** [comment]
I don't doubt that it's happening, but we currently have no leads on how to reproduce it.

**Comment by tehtrav** [comment]
Understandable. Any way I can help? I could record a screen cap

**Comment by ryan-rushton** [comment]
I'm having a little look into it atm but I can't reproduce it with my inventory. I have one old armour piece but it's perks don't have this issue. It's kinda hard to debug and test without being able to reproduce it.

**Comment by tehtrav** [comment]
Looks like you may have figured it out but here's a screen cap if its helpful! https://youtu.be/SySEj67wU9s

**Comment by ryan-rushton** [comment]
I didn’t figure it out, had some help from someone who could reproduce it. The fix was easy once we could see the cause though 🙂

**Comment by AntiPants** [comment]
Has a solution been found to this problem? I am having this issue as well.

**Comment by AntiPants** [comment]
When will the bugfix be applied to DIM? I am still having the same issue as of today.

**Comment by duckmanBR** [comment]
Probably next sunday.  The fix isn't approved yet.
