### ISSUE TITLE
Show wishlist notes  for each item on the compare pane

### ISSUE THREAD

**Issue by rafigalbur** [DestinyItemManager/DIM#4762]
Would it be possible to add a line when you are comparing items that show "notes" on current wishlist? For example if I have a weapon with different rolls for pvp/pve noted on the wishlist file, It would be nice to show up when comparing.

![3xXmqHb 1](https://user-images.githubusercontent.com/46434351/69778042-d2457c80-1170-11ea-9d05-6e6f89c4ad1f.png)

**Comment by bhollis** [comment]
If we were to do that, we'd want to show your own notes as well. I think this is more for #4377 than the compare view.
