### ISSUE TITLE
Feature request: toggle to show compressed bar graphs alongside armor attribute stats in the compare dialogue

### ISSUE THREAD

**Issue by jerrycarlson** [DestinyItemManager/DIM#4763]
Currently, DIM displays only the numeric values of armor stats in the item comparison view.  It is helpful that DIM already indicates via colors whether a particular stat is the highest or near highest across all listed comparison items.  However, it would be even more helpful if DIM could display a narrowed version of the stat bar graphs shown in the regular item details popup 
**alongside** each item's numbers when in the item compare view.  To be clear, I mean the 6 mobility/resilience/recovery/discipline/intellect/strength stat values.

I say "narrowed" because for purposes of comparison, the actual width of the graph display doesn't matter much so long as the scale is consistently applied to all 6 stats and to all displayed comparison items.  Plus, a narrowed graph allows more compared items to be seen on-screen at the same time.

**Comment by bhollis** [comment]
We're already pretty cramped for space in that view - I don't know that we'd ever have space for the bars.

**Comment by jerrycarlson** [comment]
I understand.  It's just about making it easy to very quickly visually assess the relative strength of stats across the items being compared.  That kind of comparison easily gets lost when it's just a matrix of numbers.

**Comment by jerrycarlson** [comment]
Oh one more thing: what I envision doesn't require expanding each item's width at all.  I envision a horizontally compressed version of the stat bar graphs, is all.

**Comment by bhollis** [comment]
Thanks for the request, but I don't think we're going to implement this.
