### ISSUE TITLE
Feature request: indicator to show when we can use the "refresh destiny data" button and have DIM actually update

### ISSUE THREAD

**Issue by jerrycarlson** [DestinyItemManager/DIM#4764]
It is my understanding that the Destiny API has some sort of cooldown period (90 seconds? 
 longer?) that limits how often 3rd party applications can query or update player data.  The Destiny game itself has no such cooldown period, of course.

It can be very frustrating to take an action in-game -- such as deleting, infusing, or moving an item -- and then having to wait some unknown length of time before DIM can reflect the outcome of such action.  Sometimes the system can be queried immediately (i.e., hitting refresh immediately shows the change) and other times it seems to take minutes.

Maybe a countdown timer, or maybe a green/red color for the "refresh destiny data" button indicating API readiness, would be greatly appreciated and help keep some of us from spamming the refresh button out of frustration.  ;)

**Comment by bhollis** [comment]
There's unfortunately no way for us to know when it will work. The advertised cache period is not accurate - it can take quite a long time before data is updated - it's not a strict update and has to do with how the API servers interact with the game servers.
