### ISSUE TITLE
Mods are missing in collections

### ISSUE THREAD

**Issue by quetschke** [DestinyItemManager/DIM#4772]
Please check the two pictures below showing the available mods in collections.
The first is from MODS, the second from ITEMS->MODS->ARMOR.
As you can see, in MODS for HEAD "Precision Weapon Targeting" and "Scatter Projectile Targeting", and for ARMS "Large .." and "Light Arms Loader" and "Rifle Loader" are missing, while "Fastball" is there.
Those mods are all available under ARMOR MODS: HELMET and GAUNTLETS, but there the seasonal artifact mods are missing.

MODS:
![image](https://user-images.githubusercontent.com/5354403/69892164-45153b80-12c8-11ea-9cad-3149cd0e7549.png)

ITEMS->MODS->ARMOR:
![image](https://user-images.githubusercontent.com/5354403/69892171-58280b80-12c8-11ea-885b-d295ddabcab4.png)

The display under inventory/per item is correct:
![image](https://user-images.githubusercontent.com/5354403/69892224-f1572200-12c8-11ea-9692-12c6c4c296d4.png)

**Comment by sundevour** [comment]
yes but they are also missing in collections in the game itself
