### ISSUE TITLE
"Your browser is not supported by DIM" (Raspbian Chromium)

### ISSUE THREAD

**Issue by Snnackss** [DestinyItemManager/DIM#4779]
I use a Raspberry Pi plugged into my top monitor in PiP mode for DIM so I dont have to tab out. 

Here is my User agent string: Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Raspbian Chromium/74.0.3729.157 Chrome/74.0.3729.157 Safari/537.36
![c84c9690619f487976ce2bc3e361b51c](https://user-images.githubusercontent.com/58410628/69929380-69b61280-1484-11ea-96cd-53b309cf15b9.png)

**Comment by delphiactual** [comment]
Oldest Chrome supported is Chrome 77
```
and_chr 76
and_ff 68
chrome 81
chrome 80
chrome 79
chrome 78
chrome 77
edge 76
edge 18
edge 17
firefox 72
firefox 71
firefox 70
firefox 69
ios_saf 13.0-13.1
ios_saf 12.2-12.4
ios_saf 12.0-12.1
ios_saf 11.3-11.4
ios_saf 11.0-11.2
opera 62
opera 60
safari TP
safari 13
safari 12.1
```
