### ISSUE TITLE
Maximum Total Power and Equipable displays NaN

### ISSUE THREAD

**Issue by seg7** [DestinyItemManager/DIM#4795]
But it only happens on the only character logged this week.

Pulling JS console, shows 3 errors but are font loading related.

**Comment by CyborgShadow43** [comment]
I have the same issue on 1 character.  Second character does not have the issue.

**Comment by delphiactual** [comment]
https://github.com/DestinyItemManager/DIM/pull/4792

**Comment by arghblargh** [comment]
There's still a problem with this. No longer displays NaN but my Maximum Equippable power shows 1079.5 instead of the actual 959.5.

**Comment by bhollis** [comment]
We need to find and fix the rest of the bugged weapons before power level will show correctly

**Comment by sundevour** [comment]
resolved by #4792 and #4797
