### ISSUE TITLE
Power level being misreported

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#4800]
Current beta.  Chrome on Win 10.

This is only on my middle character, which is a warlock (not sure if either is relevant).

![image](https://user-images.githubusercontent.com/25425159/70841491-d52bb700-1e6a-11ea-891c-dad00251f38a.png)

Both character have all 960 gear, but the warlock is being reported as 1080 power.  I wish.

**Comment by lassevk** [comment]
Mine is reporting my warlock as "NaN = NaN + 5", might be the same issue. The other two characters seems OK though.

**Comment by dazedcrazy** [comment]
Same thing here
![image](https://user-images.githubusercontent.com/9027988/70849975-3bb9d080-1e7d-11ea-8f5d-055dd8bab7e0.png)

**Comment by willdrobins** [comment]
I've had this for a few days now.

**Comment by delphiactual** [comment]
@philkernick try beta and post logs if it is still reporting >960 + artifact
