### ISSUE TITLE
filtering based on modslot not working properly for new season 9 and also for modslot:outlaw

### ISSUE THREAD

**Issue by mike-seven** [DestinyItemManager/DIM#4804]
Filter based on modslots is not working properly, i.e.:
filter text: "modslot:none not:exotic is:arc is:warlock is:chest"
selects not only 3-slot generic armors but also armors from season 9 with "Season of down" slot like chest piece "Vigil of heroes" [id:6917529138214528146]
Also looking for armor pieces with "modslot:outlaw" do not select Dreaming City armor class item "Bond of the Great Hunt" [id:6917529123473258193] Warlock Bond which has the same slots as "Reverie Dawn Bond" [id:6917529122436084216] (selected properly, I assume)

If you need more debug info please let me know.

**Comment by sundevour** [comment]
what url is this at?

**Comment by sundevour** [comment]
these IDs you're pasting are completely unique ids that point to your own personal copy of that item, and since we aren't bungie we can't look up any information about those

please post a screenshot of the item details, for the Bond of the Great Hunt which is not detecting with `modslot:outlaw`

**Comment by mike-seven** [comment]
I've tried with modslot:outlaw for the bond but I cannot replicate it. I probably did something wrong there. Although the part of season 9 slot is replicable, do you need a SS?

**Comment by sundevour** [comment]
what url is this at?

**Comment by mike-seven** [comment]
https://app.destinyitemmanager.com/4611686018492098054/d2/inventory

**Comment by delphiactual** [comment]
Yes `modslot:dawn` is not in app yet, it is in beta though
