### ISSUE TITLE
getting a NaN error sometimes for power

### ISSUE THREAD

**Issue by jerrycarlson** [DestinyItemManager/DIM#4805]
I'm using the latest stable Google Chrome browser on Win10 x64, and latest DIM.  Testing shows the same error for me in Firefox, and also in the beta DIM site.

The error is: sometimes "maximum total power" and "maximum power of equippable gear" display a NaN error instead of the applicable numbers.

I haven't had this error before.  It only shows up on my highest-level toon (level 959.x).  See attached image for more information.
![Capture](https://user-images.githubusercontent.com/9376071/70858763-d7732d00-1ecd-11ea-99b0-9d6f1109fa8b.PNG)

**Comment by jerrycarlson** [comment]
Update: I just noticed that some of my Warlock helmets and chest pieces in the vault are not sorting properly (see attached images).  However, my Warlock gauntlets, legs, and class item categories in the vault *are* sorting properly.
<img width="258" alt="Capture3" src="https://user-images.githubusercontent.com/9376071/70861315-ac9ad000-1ef1-11ea-9263-61b2df89f737.PNG">
<img width="262" alt="Capture2" src="https://user-images.githubusercontent.com/9376071/70861316-ac9ad000-1ef1-11ea-8926-54e5ff6e6afb.PNG">

**Comment by delphiactual** [comment]
Please post dim version you are using as this has been fixed in beta but not pushed to app as of yet

**Comment by jerrycarlson** [comment]
I'm using Version 5.60.0 (release), built on 12/8/2019, 11:57:30 PM

That said, DIM is working properly again (!!!), both in terms of displaying power numbers and in terms of the vault sorting.  I hit power level 960 overnight -- I wonder if that had anything to do with it working again?

I suppose this issue can be closed?

**Comment by willdrobins** [comment]
This happened for me again when I received a 960 energy weapon to get to overall 960 base. It might have happened a few minutes later when I received the current season hand cannon The Old Fashioned.
