### ISSUE TITLE
Toggling off the auto-update feature of the Loadout Optimizer

### ISSUE THREAD

**Issue by CMartinez7** [DestinyItemManager/DIM#4809]
The loadout optimizer calculates all possible armor combinations automatically whenever there's a change in the left filters or when you open the optimizer. This also happens whenever I start typing or delete some conditions in the search bar. Would it be possible to turn this feature off and ask DIM to optimize manually after I've set all of the constraints?

**Comment by bhollis** [comment]
I assume you're asking because it's slow to update?

**Comment by CMartinez7** [comment]
Yes indeed, and it is not only slow to update but the browser and the filter bar do not respond while the page is updating. Moreover this happens whenever I delete the current filters to look for new loadouts, even if I delete a letter or two.

In the image below I show how much time it takes when I open the optimizer and start to type "is:armor2.0" and then "is:solar", which is what I want to check.

![image](https://user-images.githubusercontent.com/9254852/70989816-95600c00-20c4-11ea-9c8a-d3fd7dbfb157.png)

**Comment by bhollis** [comment]
Yup that's pretty slow. Probably not going to do a lot about it though, until React concurrent mode ships.
