### ISSUE TITLE
Feature Request: Collapsible Loadout Folders / Headers

### ISSUE THREAD

**Issue by a-waite** [DestinyItemManager/DIM#4819]
I'd first just love to thank everyone who's ever worked on DIM, I couldn't play this game with out it.

I play all 3 classes with full sets of armor for every raid and try to keep at least 1 god roll of every weapon in the game. I find myself using ever more convoluted sets of brackets / symbols / letters / numbers to keep my loadouts organized so I can find them as I scroll through the character drop down in DIM.

Would it be possible to add a drop down menu somewhere in the loadout create / edit page and you can then add that loadout to a "collection". So when you click on a character you can now click on this group header to either hide or display the loadouts it contains?

I.E. you can select a "parent" folder for your loadout when you save it

**Comment by bhollis** [comment]
Thanks for the suggestion! We've talked about this in the past, but in general we don't think the added complexity of building an extra layer of loadout management is worth it. I think what you're doing by adding text to the name to help organize them is the best way to do it.
