### ISSUE TITLE
Loadouts don't save subclass

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#482]
https://www.reddit.com/r/DestinyItemManager/comments/4f10hb/loadouts_arent_remembering_subclasses_when_the/

In the past, a subclass could be added to a loadout.  It seems that ability has been broken.

**Comment by bhollis** [comment]
I'm unable to reproduce this - I can create a loadout that includes a subclass, and that subclass gets equipped.

**Comment by SunburnedGoose** [comment]
Did you refresh the page and edit the loadout?  The subclass is missing.

**Comment by bhollis** [comment]
I see. Very weird.

**Comment by bhollis** [comment]
Fixed.
