### ISSUE TITLE
Login loop caused by Stadia+D1 issue

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#4842]
https://github.com/Bungie-net/api/issues/1151 has mutated, and now returns an error that can cause a bad login loop when people have logged in via Stadia. Gotta handle this new weirdness.

**Comment by mrmurb** [comment]
Has this been solved? I am still facing problems using DIM together with an account linked to Stadia and PSN.

**Comment by bhollis** [comment]
We’ve tried to solve it on our end but if it’s still happening with today’s build then I’ll need some logs to help diagnose. The real fix is on Bungie’s end though.

**Comment by mrmurb** [comment]
What logs would you like to have?
At the moment I managed to login when I chose to use PSN instead of Stadia during the auth with Bungie.

**Comment by bhollis** [comment]
The console logs - open dev tools, select preserve logs, and then see what happens when you enter the loop.
