### ISSUE TITLE
LO able to make beyond T10 sets

### ISSUE THREAD

**Issue by inexorableAce** [DestinyItemManager/DIM#4847]
In LO I guess if you're gear is good enough the selections and stat mixes will go above T10
![image](https://user-images.githubusercontent.com/29002828/71636862-b36d5680-2c04-11ea-9561-ce64545ef6cb.png)

![image](https://user-images.githubusercontent.com/29002828/71636867-b9633780-2c04-11ea-8e3d-c8fdf35c513e.png)

**Comment by bhollis** [comment]
I assume that doesn't really work?

**Comment by inexorableAce** [comment]
Correct cap is t10
