### ISSUE TITLE
Season 9 weapons are not supported by godroll list 

### ISSUE THREAD

**Issue by laflour** [DestinyItemManager/DIM#4855]
Hi,

There seems to be an issue with the voltron list, as the Season 9 weapons perks are not marked
For example, the Season 9 Patron weapon perks are not highlighted, but the same perks from the Night Watch rifle are 
https://imgur.com/a/gp995lM

**Comment by 48klocs** [comment]
DIM consumes wish lists; https://github.com/48klocs/dim-wish-list-sources is the proper repo for this.
