### ISSUE TITLE
Slow drag + drop

### ISSUE THREAD

**Issue by aaronransley** [DestinyItemManager/DIM#4858]
Noticing a slow "activation" when dragging an item to a new target area / character. If I drag and drop too quickly nothing happens. If I drag an item and then wait for the light grey highlight box to activate, I can release the mouse button and things transfer successfully.

For what it's worth, I attempted to replicate on Firefox 71, Win 10 and no lag was present. Drag + drop is snappy and the drop target highlight appears right away.

Issue is on Chrome 79, Win 10, with no extensions running, and occurs when using [the beta subdomain](https://beta.destinyitemmanager.com/) as well as [the production domain](https://app.destinyitemmanager.com/).

Here's [a small video illustrating the slowdown](https://imgur.com/a/2FD438S). It seems like it lags for longer depending on how many potential targets I hover before stopping mouse movement.

**Comment by bhollis** [comment]
Hmm, that's unfortunate. I haven't been able to replicate this on macOS - it's instantaneous on all browsers. Maybe some of our Windows-based developers could help.

**Comment by kyleshay** [comment]
@aaronransley - are you seeing improvements with some of the performance diffs that have landed?

**Comment by aaronransley** [comment]
All feels much better here. Good stuff!
