### ISSUE TITLE
WEB API for changing loadout over HTTP(s) Requests

### ISSUE THREAD

**Issue by pilo1337** [DestinyItemManager/DIM#4865]
Hi,

i think it would be nice if i can change my loadout or get functions like farm mode via http(s) requests.

This way you can easily build yourself a nice "one-button-loadout-changer" with as example a Elgato Streamdeck or Touch Portal remote control.

Is this possible?

**Comment by bhollis** [comment]
No, unfortunately it’s not possible. DIM is entirely client side.
