### ISSUE TITLE
source:ironbanner isn't working for the current season (Season of Dawn)

### ISSUE THREAD

**Issue by joshminnie** [DestinyItemManager/DIM#4870]
When using the `source:ironbanner` search, it's not detecting the current season's armor.

![Screen Shot 2020-01-09 at 3 59 36 PM](https://user-images.githubusercontent.com/117469/72104327-32474b00-32f9-11ea-97e5-d3bf1c19016f.png)

**Comment by sundevour** [comment]
known, typical, no new versions, of old items, come with any source info so we will need to manually correct
