### ISSUE TITLE
WishList notification shows on every load

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#4873]
We should show the notification only when the wish list is loaded/updated, not every load.

**Comment by bhollis** [comment]
Looks like we're actually re-fetching on every load. Maybe put in a minimum refresh time?

**Comment by 48klocs** [comment]
I didn't have access to the response headers (I was looking for `ETag` or `Content-Length`), so I punted on trying to detect changes on the other end and just load all the time.

A refresh throttle (and a button to tell it to get latest in settings) would be reasonable and not too terrifying to build in.
