### ISSUE TITLE
Ghost projection icon is too wide in collections

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#4875]
This is purely cosmetic, but the Ghost Projection icon in collections is more than twice as wide as any of the others, and it makes the text not line up.

![image](https://user-images.githubusercontent.com/25425159/72213129-49747b80-3539-11ea-916e-6abea9e87f77.png)

If there isn't a normal width icon, I'd remove it completely so it's like Badges.

**Comment by bhollis** [comment]
Unfortunately we get both the icon and the localized name from an item, and the item has a weird square icon.

**Comment by philkernick** [comment]
Can we raise it as an API bug?

**Comment by bhollis** [comment]
We can but it’s 100% never going to be fixed.

**Comment by kyleshay** [comment]
It's not perfect (the image isn't totally symmetrical), but another option could be to use the css property [`object-fit:cover`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit)
<img width="1018" alt="Screen Shot 2020-03-01 at 1 37 07 PM" src="https://user-images.githubusercontent.com/424158/75634346-e8c10100-5bc1-11ea-9e08-ed3dde95061e.png">
