### ISSUE TITLE
Artefact has a store button

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#4876]
The artefact has a store button when look at it.

![image](https://user-images.githubusercontent.com/25425159/72213176-f7802580-3539-11ea-82b0-c7222457961a.png)

There are two problems with this:
1.  It doesn't make any sense, since you can't actually do any inventory actions on it.
2.  If you try anyway, it shows an error.

![image](https://user-images.githubusercontent.com/25425159/72213166-e2a39200-3539-11ea-9364-957afa59341f.png)

Same exact issue happens with Finishers.

**Comment by bhollis** [comment]
Good catch. They're weird - they're equipped, equippable items but they can't be unequipped. That makes sense for the items that have no alternative to equip, but it's weird for finishers which are just generally a one-off.

Bizarrely, the bucket capacity for Seasonal Artifacts is 4, which suggests at some point they were going to let you keep them...
