### ISSUE TITLE
Loadout Optimizer use of shift-click is inconsistent

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#4878]
In Loadout Optimizer you use shift-click to **select** a perk, but to **exclude** an item.  This is both confusing and not obvious.

From a UI point of view, it would be more consistent to drag the perk into the select mod or perk area in the same way that dragging items to include or exclude them.

**Comment by bhollis** [comment]
We're not going to implement drag and drop for perks. I get that this isn't super consistent, but I'm not sure there's anything we'll do about it.

**Comment by philkernick** [comment]
Probably worth noting that I had no idea you could shift-click a perk at all until I watched @inexorableAce video.

**Comment by bhollis** [comment]
I believe it’s mentioned in the help text at the top of the page, but if not we can make sure to add it.

**Comment by inexorableAce** [comment]
Yep it’s up there, I mentioned it in one of my recordings that didn't get used.

**Comment by philkernick** [comment]
To break as little muscle memory as possible, can we make shift-click mean exclude, and ctrl-click mean include?  Or some variant thereof.

**Comment by bhollis** [comment]
There's no excluding perks, though.
