### ISSUE TITLE
Enhancement: Show suggested perks for non god-roll items

### ISSUE THREAD

**Issue by crafty35a** [DestinyItemManager/DIM#4884]
Currently, it looks like wishlist data is only displayed if the item is a "god-roll" (has 4 suggested perks). It would be extremely helpful to have this information show up for other items, to help decide which one to use before you actually have a god-roll. For example, It would be helpful to know which of my Breachlights have 3 suggested perks. I also think the wishlist notes would be helpful on all items as well.

Thanks!

**Comment by sundevour** [comment]
this is already a feature but currently not working great due to various factors and some major changes in shadowkeep. see/watch: https://github.com/DestinyItemManager/DIM/issues/4662
