### ISSUE TITLE
Collapse/hide characters

### ISSUE THREAD

**Issue by Revadike** [DestinyItemManager/DIM#4885]
I've looked into https://github.com/DestinyItemManager/DIM/issues/1015, but still can't find my desired feature. I don't think this has been properly implemented yet.
Like the rows (weapons/armor/general), I'd like to see a collapse functionality for characters (and vault), so I can hide the ones that I never use. This will waste less space and make it more efficient for me.
I only store class specific items on my other 2 characters that I don't use.
As suggested in the other issue, perhaps dragging an item in the collapsed bar/section and holding it for a few seconds, will expand the character.
Another way to go about this, is add the option to completely hide characters in the sort characters section in the options.

**Comment by delphiactual** [comment]
https://github.com/DestinyItemManager/DIM/wiki/Frequently-Requested-Features#hide-characters

**Comment by Revadike** [comment]
> We could figure out a way to do this (maybe by showing all that character's items as if they were in the vault)
I don't get it. That's the whole point, to hide the characters and it's items. I don't want to see those class items in my vault anyway. There's no need to get so complicated about this.

**Comment by Revadike** [comment]
If anyone is frustrated by this, like me. I wrote a small script that hides your desired columns:
```js
var columns = [2, 3]; // the ith columns you want to hide

for (var col of columns) {
for (var node of document.querySelectorAll(`.store-cell:nth-child(4n-${4-col})`)) {
node.style.display = "none";
}
}

for (var node of document.querySelectorAll(".store-row")) {
node.style.gridTemplateColumns = `repeat(${3-columns.length}, calc(6px + var(--character-column-width) + var(--column-padding))) 1fr`;
}```

**Comment by Revadike** [comment]
Why did nobody tell me this has been available in settings for idk how long!
