### ISSUE TITLE
Loadout Optimizer could use slot independent seasonal mod selection

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#4887]
I'm trying to build an armor set that includes at least two season 9 mods, one is general, one is void.  I don't care which piece takes them as long as one of them takes each.

Currently this is impossible.

I could filter for season:9, but I don't need every piece to be season 9.
I can select the "protective light" mod, but I have to choose when selecting it which armor piece it goes in, and at this stage I don't know or care.

My suggestion is that the seasonal mods not have a slot attached to them (as they can be applied anywhere).

**Comment by sundevour** [comment]
LO needs slot-independent a lot of things

**Comment by bhollis** [comment]
Sure - if somebody wants to tackle this I think it'd be great. It'll be hard though - today the logic is very tied to slots, and there's logic that keeps track of what slots have been used that would become significantly more complicated if it had to try to fit mods across different possible slots.

**Comment by ryan-rushton** [comment]
@bhollis I think this can likely be closed with that PR of mine, I didn't put a fixes on it as I wasn't sure how it would play out at the time.

**Comment by ryan-rushton** [comment]
I think we can close this now with what is in beta.
