### ISSUE TITLE
Loadout creator doesnt calculate all possible mixes

### ISSUE THREAD

**Issue by humandxp** [DestinyItemManager/DIM#4888]
i excluded all chest armors that i dont want
so in pic1 we have subsitutionals robes all with T25 as solar only, cos void like you see on list is excluded, but its missing arc
ok now as pic2 lets add that solar to exclude and modify nothing
magic now we have arc on T25 with 2 possibilities
and as pic3 same bug is in beta version of dim
![pic1](https://user-images.githubusercontent.com/24486599/72588374-0bd47180-38f0-11ea-8fec-494d48f5c426.png)
![pic2](https://user-images.githubusercontent.com/24486599/72588376-0bd47180-38f0-11ea-97c4-c4104eeb58df.png)
![pic3](https://user-images.githubusercontent.com/24486599/72588377-0bd47180-38f0-11ea-87d3-4c6df2a890b7.png)

**Comment by humandxp** [comment]
checked inside chrome so nobody will play smartass that i use waterfox. same results

**Comment by bhollis** [comment]
I'm sorry, I don't really follow what you're doing, and the screenshots are hard to make out. Could you be more specific about exactly what steps you took, and what you expected to see?

**Comment by humandxp** [comment]
i was trying to cleanup my vault, since i dont like look of some armor like those with leafs and from gos, i got only 3 of them so i wanted to check what points they give, if low then i remove them, so i started by excluding all those that are not subsitutional robes, so i ended with T25 as you can see on screenshot its all solar subsitutional robes, before last is T24, and here fun part begins, i could not find arc when i scrolled list, maybe far far away.
so i also added solar subsitutional robes to exclude list.
and as pic2 suddenly we have arc subsitutional robes as T25.
so there is a bug in algo calculating all mixes that it doesnt calculate and show arc with solar as T25 mix. probably there is some limit that doesnt allow to calculate all possible mixes. and that isnt good for us. cos we can remove armor due that bug, not cos its bad, but due bug
