### ISSUE TITLE
Feature Request: View wishlist items

### ISSUE THREAD

**Issue by sitch** [DestinyItemManager/DIM#4891]
First off just wanted to say that I love this product and it really saves me a ton of time so thanks a ton! 💯 👏 

## Rationale
So now that we have these awesome wishlists, I'm looking for an easy way to view the entries in wishlists themselves because taking something like `dimwishlist:item=1518042134&perks=2054312700,3177308360,1890422124,2846385770`
and looking it up on the destiny data sets site takes forever!

## Thoughts

1) Add an additional tab to the top level toolbar to view these
> `Inventory | Progress | Vendors |` **_Wishlists_** `| Collections | Loadout Optimizer`

2) Add the ability to view wishlist items in comparison mode.  In terms of layout i think some sort of split panel view works very nicely on desktop and on mobile probably just an additional tab.
> `Halfdan-D (4) | Kinetic Auto Rifle(20) |..|` **Wishlist Halfdan-D(5)** 

Thanks for all the work, I'd imagine this is a fairly easy implementation for someone familiar with the codebase, but I'm not above getting my hands dirty..

Thanks! 
Sitch

**Comment by 48klocs** [comment]
I include links in my wish lists back to the sources, where you can see what led to things being included.

I admit that the value of this is a bit lost on me.

**Comment by sitch** [comment]
So i'm trying to look at what are some of the rolls in these wishlist sources.  The current implementation only allows me to view the rolls matched against items I already possess.  Problem is that I just want to view/search entries of items that I do not yet possess.

The value to me is that when I need to delete a bunch of items, its very nice to know which specific rolls community members have rated as wishlist so that I can make a more informed decision about what to get rid of.

**Comment by 48klocs** [comment]
The wish list is already a lossy translation of recommendations that have been made. The wish list files often have links back to where the recommendations were made (so if you want to know, scroll up and open the URL). I've thought about extending the wish list format to allow for links back to the originating source, but I'm kind of lukewarm on that idea (I'm hesitant to do it and break back compatibility for such a borderline feature).

Visualizing everything that's in the wish list in an enhanced sort-of-collections tab is a bigger project than I have any desire to tackle.

If you think it'd be valuable and want to work on this, feel free to reopen it.

**Comment by sitch** [comment]
One thing that would be immediately helpful to me would be some way of inputing a text blob like:
```
dimwishlist:item=1518042134&perks=2054312700,3177308360,1890422124,2846385770\n
dimwishlist:item=1518042134&perks=2054312700,3177308360,1890422124,2846385770\n
dimwishlist:item=1518042134&perks=2054312700,3177308360,1890422124,2846385770\n
...
```
And simply rendering the items bc right now i have to look up code by code
