### ISSUE TITLE
request: please bring back manual refreshing as an option in settings

### ISSUE THREAD

**Issue by mc711** [DestinyItemManager/DIM#4892]
i have already requested manual refreshing in the past and the past few weeks with forced manual refreshing felt so great. i can always alt+tab while farming and only refresh when i need to instead of coming back to DIM but DIM has already auto refreshed and i have to wait for the refresh cooldown. PLEASE allow manual refreshing...

**Comment by bhollis** [comment]
There's not a refresh cooldown mechanism, and auto refresh is off. We've re-enabled a refresh whenever you switch back to DIM after having hidden the window, but that's it. We won't make this a setting.
