### ISSUE TITLE
Infuse tool not showing any options

### ISSUE THREAD

**Issue by ressu** [DestinyItemManager/DIM#4893]
When attempting to use the Infuse tool for my second character, there are no items found for infusion.

For example, here are my duplicates for Righteous Robes:
![Screenshot 2020-01-21 at 11 50 01](https://user-images.githubusercontent.com/468618/72803622-749c5080-3c46-11ea-9412-f7a2d8d248a0.png)

Selecting Infuse on the highest power one gives me this screen:
![Screenshot 2020-01-21 at 11 50 15](https://user-images.githubusercontent.com/468618/72803680-985f9680-3c46-11ea-8f21-cd9c928ba01f.png)

I've also checked ingame that these items are infusable to each other, so there is something funky going on here.

Tested with `Version 5.66.0.6318 (beta), built on 1/20/2020, 6:05:40 AM`

**Comment by bhollis** [comment]
No idea how that could happen. Does it happen on any other armor? Has anyone else seen his happen?

**Comment by ressu** [comment]
After a bit of head scratching, it turned out to be a case of having dupes only. So when infuser filters out the items array for dupes, it only checks if there are items in the items array and not in the dupes array when displaying the results. I'll send a PR for fixing this.
