### ISSUE TITLE
Ability to search for items that have ornaments on them applied

### ISSUE THREAD

**Issue by Tvangeste** [DestinyItemManager/DIM#4894]
`is:hasornament` or something like that?

The only thing I could find is `is:hasshader`, but I'd like to be able to search for those items that have ornaments on them applied.

**Comment by drocm** [comment]
Hi All,

currently have a working branch with this feature ready for PR if you will have me. Not really sure what I'm doing on the GitHub PullRequst side of things but seeing how this is labeled as "Good First Issue" perhaps you won't mind pointing me in the right direction in terms of rules and etiquette.

Thanks and All Best,
drocm

**Comment by bhollis** [comment]
Hi @drocm, sounds great! Check out https://github.com/DestinyItemManager/DIM/blob/master/docs/CONTRIBUTING.md, and https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by sundevour** [comment]
implemented in #4931
