### ISSUE TITLE
Feature request: Disable double click actions

### ISSUE THREAD

**Issue by bording** [DestinyItemManager/DIM#4895]
I would love to see a setting added to disable any sort of behavior on a double click. I quite often accidentally trigger an item move because of an accidental double click.

**Comment by kyleshay** [comment]
we err on the side of caution for adding additional settings, as to not overwhelm users. are you double clicking because the modal isn't coming up fast enough? is the double click timeout too short? just curious if there is an underlying thing causing double clicks to trigger unintentionally.

**Comment by bording** [comment]
It feels like the threshold to register a double click is too short. Things that I don't think should be double clicks often end up transferring an item. I often find that I have clicked on item and then clicked a different item, and then a transfer starts.

**Comment by bording** [comment]
A common scenario where I'll run into the problem is when I click on an item to view the tooltip, click away to dismiss the tooltip, and then click another item, all in quick succession. That has a tendency to make the second item clicked start a transfer.

**Comment by kyleshay** [comment]
interesting, so the click to close the modal is also the first click on an item before you click to open the modal on that one. it could be worth investigating ways to fine tune some of those interactions, thanks for the call out. we will note that and see what we can do to polish that up but I'm going to close this ticket to add a setting, as again we try every possible way to curate the best experience and reduce settings/configuration overhead as it can so easily get out of hand.

**Comment by bording** [comment]
I still would rather have a setting. I really never want double click to do anything, even if you do tweak it.

**Comment by dlee13** [comment]
My mouse has recently become broken in that it often double clicks by itself when I single click or hold click if I don't press hard enough. DIM has been very frustrating to use over the past week since items keep getting transferred unintentionally or even equipped if I'm not in an activity.
