### ISSUE TITLE
Loadout builder can't drag exotic ghosts if exotic locked

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#4896]
How to duplicate:

1. Lock any piece of exotic armor.
2. Attempt to drag an exotic ghost into the include box.  You get the "not allowed" symbol.

Presumably it's coded to not allow more than one exotic to be locked.  Which is true for armor, but not for ghosts.

There is a workaround.  From the build side of the screen select a ghost, then select the "choose" double arrow underneath it, and from that panel select the exotic ghost.  Then it will lock.

**Comment by m-s-y** [comment]
Curious why this would be necessary since ghosts can't change any of the character stats that Loadout Builder is designed to max/min on?

**Comment by philkernick** [comment]
If you are asking why the ghost is even in the loadout builder, I suspect it's because in D1 the ghost had a both light level and stats.

**Comment by bhollis** [comment]
No, it's there because ghosts have perks, and loadout builder is about crafting the best perks.

**Comment by ryan-rushton** [comment]
I can have a look into this.
