### ISSUE TITLE
Move popup detail redesign

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#491]
We've just been adding and adding to this, would it be a good time to consider a redesign of this move popup? We'll want to keep all of the content, but it would be nice to organize it a bit more. (for example, the light level and item type are being cut off in the title portion.)

![screen shot 2016-04-24 at 4 12 25 pm](https://cloud.githubusercontent.com/assets/313208/14771168/5dbfd976-0a37-11e6-9122-c5ade089bac3.png)

**Comment by bhollis** [comment]
I'm all into it. Making our own tooltip is super easy, probably don't need
a library. Anyone want to sketch up some designs?

**Comment by joshmedeski** [comment]
I'll spend some time redesign this portion and submit ideas here 😄

**Comment by kyleshay** [comment]
:) awesome. feel free to think outside the box. moving that date to a floating side-panel, show some information on hover, better arrange items on that page... etc. 

@bhollis has an open pull request that even pulls in some other neat info, like number of kills w/ a given weapon, etc. 

Users are used to seeing a lot of info in the move popup already. maybe having tabs to less interesting/detailed information in the popup? just thinking out loud. :)

**Comment by bhollis** [comment]
And I'm happy to implement whatever ideas folks come up with :-)

**Comment by joshmedeski** [comment]
Here's an idea. What do you think?

![screen shot 2016-05-10 at 8 20 10 pm](https://cloud.githubusercontent.com/assets/2036594/15167219/ab3caffa-16ec-11e6-8399-7964d22d6113.jpg)

**Comment by bhollis** [comment]
Nice! I like the reorganization to two lines. Are you imagining that this is still the header for the full popup?

One thing that might be nice is to replace the "i" icon with a disclosure arrow.

**Comment by dhinged** [comment]
The design is good, the problem is the box only pops up above or below the mouse pointer, when it could instead pop up to the right or left if will be truncated vertically. This would also allow the gun type and class restriction (stating that it's a Hunter-only class item for instance) to also show.

@joshmedeski's tooltip idea is good (shows the gun type) though the Attack number is redundant if it already shows on the weapon icon (as it does for me now), and that space would be better used to identify which class it's for (or Any class).

**Comment by joshmedeski** [comment]
Is there any useful information that we might want to include in the simplified dropdown?

I was thinking if it's class specifics and possibly damage type?

My other concern about the icons is if they're too close together, it could cause a poor user experience if they accidentally click the wrong icon.

p.s. @bhollis I like the disclosure arrow idea.

**Comment by dhinged** [comment]
Damage type on hover pop-up (simplified drop-down?) would be also good to add, but the attack/defense number can be colored as damage type and bolded if necessary, with damage type icon as additional signifier (as it shows on Destiny's item preview screen).
