### ISSUE TITLE
What is modslot:opulent?

### ISSUE THREAD

**Issue by irons** [DestinyItemManager/DIM#4912]
I was looking for a heuristic to identify armor 2.0 items in DIM's armor export, and thought that any value in the Seasonal Mod column might be a start. 

This uncovered four armor 1.0 items from Y2 menagerie which all respond to a "modslot:opulent" query. Since season 7/Opulence predates armor 2.0, this seems impossible. In which case, I don't know why this modslot value should exist.

**Comment by delphiactual** [comment]
screenshot an item in question

**Comment by irons** [comment]
Sorry, nevermind. The seasonal mod slot did start with opulence, just prior to armor 2.0; I was conflating them.
