### ISSUE TITLE
frequent scrolling issues, beta and stable, chrome os 79.0.3945.123

### ISSUE THREAD

**Issue by bobreidx** [DestinyItemManager/DIM#4913]
Greetings;

I have begun to experience scroll hitching issues in chrome os with both the beta and the stable releases of DIM. It started a few days ago.

**Comment by bhollis** [comment]
Nothing's changed in the last few weeks. Are you sure it's only DIM?

**Comment by bobreidx** [comment]
I suspect that it might be some weird caching on my Chromebook. I even tried the web app container for DIM, and it was fine for a few minutes, then it started hitching again. Are there logs I can get for you?

**Comment by bhollis** [comment]
You could try opening the developer console and seeing what it says. Do you have a video of this? Does it happen in Chrome on other computers? We really haven’t changed anything, but Chrome may have updated.

**Comment by bobreidx** [comment]
So, the console only revealed something minor going on (below), but, as soon as I opened the console, the hitching stopped, and so far has not returned. Go Figure.

Load stores: 18201.405029296875ms
inventory:1 [Intervention] An <img> element was lazyloaded with loading=lazy, but had no dimensions specified. Specifying dimensions improves performance. See https://crbug.com/954323

**Comment by bhollis** [comment]
Yeah, that's not important. Sorry you had that problem, but glad to know it's fixed.

**Comment by bobreidx** [comment]
update: this issue is ongoing, and I am still investigating after a hardware reset on my Toshiba Chromebook 2 (2015). Not suggesting a reopen of the ticket. I speculate that Bungie may have introduced some assets that require more compute resources to present, as evidenced by lags during item inspection I have been experiencing on my xbox one S.
