### ISSUE TITLE
Lord of Wolves/Black Talon Catalysts

### ISSUE THREAD

**Issue by ToddAtWSU** [DestinyItemManager/DIM#4915]
It appears the Lord of Wolves and Black Talon catalyst progress are bugged. They always show the same progress completed. The last time I played I only worked on Black Talon but both catalysts show made progress in DIM and DIM Beta. So it appears these are accidentally tied together?

**Comment by wein3967** [comment]
I think this may be weirdness on Bungie's end. When I "completed" the Lord of Wolves catalyst, I actually got an in-game banner for completing the Black Talon catalyst. However, the triumph and actual catalyst only unlocked for the Lord of Wolves.

**Comment by philkernick** [comment]
It's not a DIM problem.  The triumph's for both are tied to the LoW catalyst.  However you don't actually get the Black Talon completed.
