### ISSUE TITLE
Problem with "Loadout optimizer"

### ISSUE THREAD

**Issue by ObsidianChest** [DestinyItemManager/DIM#4922]
Hello,
So i want a **tier 9 Recovery**, **5 Resilience**, **6 Mobility** for my hunter, and made that the mods are locked on all mobility and recovering mods. it showed me some really good tiers but the problem is that it shows me Chest that has recovery mod and cloack that has mobility mod in it but the other armor parts don't have any mod put inside so i don't know how to put the mods in the correct order. I hope that i typed good and you understand it.
Thanks,

**Comment by ryan-rushton** [comment]
Mods are ignored in the stat calculations unless you specifically lock them to the item. Just consider those stats to be the value without the mods unless you particularly want to include it.

**Comment by ryan-rushton** [comment]
@ObsidianChest, sorry just to clarify as your last sentence mustn't have sunk in. The mods you see on the items are the currently equiped ones, not the ones inserted in the select mod or section. So disregard the ones you see there and just account for the ones you have locked.
