### ISSUE TITLE
RFC - embedding tags in wish lists

### ISSUE THREAD

**Issue by 48klocs** [DestinyItemManager/DIM#4929]
Wish lists currently support `#notes:blah blah` tags for URL-type lines, as well as `dimwishlist` (expert mode) lines. Other folks who are using wish lists have extended it to support tags for different modes (in one way or another).

To ease sharing lists between different apps (since we may make sharing via the DIM API in the future a thing), I'd like to try to keep them consistent.

A proposal is to extend `notes` to embed `tags` in them - `#notes:These are notes.|tags:pve,pvp` would carry along notes, as well as a couple of tags. `#notes:These are notes.` would be for notes alone, and `#notes:|tags:pve,pvp` would be for tags alone.

Along with that, might as well recommend a uniform set of known tags (to present how you want, or disregard).

- pve
- pvp
- raid
- gambit
- trash
- mkb
- controller

My workflow in creating wish lists doesn't really allow for me to recognize those cases where a roll crosses multiple tags without driving myself insane, so I'm probably not going to bake presenting tags in to DIM at this point, but I'd like to quietly drop tags so that a user's UI isn't cluttered up with them (and leave open the door to presenting them at some point if there's demand and lists generated with them).

**Comment by kyleshay** [comment]
love the idea of tags! would be really useful to filter on.

what about something like this, may feel more like tags on other media platforms? just look for words that have a hash preceding and trim all extra white space on the ends?

`#notes:this is useful for xyz. #pvp #pve` 

or simply without a note:

`#pvp #gambit` 

or even taking it somewhere further:

`#notes:this is generally a good weapon. #pvp:this is good for control, but that's about it. #pve:this is fun to use in patrols but isn't useful for much else.`

**Comment by philkernick** [comment]
If others already have a working schema for tags, then it makes sense to use the same system they already have, because this is about interoperability.

But if it's still in flux, then I'd suggest this approach:

```
#notes:These are notes. @pve @pvp
#notes:These are notes.
#notes:@pve @pvp
```

The suggestion from @kyleshay names the notes tag mean general notes, with other tags being notes applying to different game modes.

**Comment by bhollis** [comment]
Closing in favor of #7129
