### ISSUE TITLE
Dreadnaught bounties appear in quest bucket

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#493]
https://www.reddit.com/r/DestinyItemManager/comments/4g1aet/dreadnaught_missions_appearing_in_quests_section/

**Comment by bhollis** [comment]
For each of those items, could you right click on them, hit "inspect", and then in the console run `angular.element($0).scope().vm.item.hash` and paste in what you get? I can track them down that way.

**Comment by delphiactual** [comment]
4238929348
2560764544
4238929351
