### ISSUE TITLE
Hacked Destiny 2

### ISSUE THREAD

**Issue by Bemboss-Da-Man** [DestinyItemManager/DIM#4932]
How can I remove a player who has hacked my destiny 2 account and keeps deleting my characters, he has DIM account with my characters he deleted. I have his gamer name and email address, he told me if I don't pay him 125 EURO he would delete my account, he just keeps deleting my characters.
![DIM](https://user-images.githubusercontent.com/61068483/74574596-5244eb00-4fd8-11ea-9cad-042cbd3e2b8e.PNG)

**Comment by ryan-rushton** [comment]
Dim can't delete characters, he has the details of your playstation/xbox/steam/stadia account. You should contact the relevant one of those.

**Comment by Bemboss-Da-Man** [comment]
Why close this when he activated DIM and delete my warlock, I have unauthorised DIM through bungie and the hacker re-authorises it and deletes my characters.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kyleshay** [comment]
change your password to your bungie and platform (Xbox/PlayStation/etc) accounts. unfortunately this is out of DIMs control.

**Comment by Bemboss-Da-Man** [comment]
Don’t you think I’ve done that, changed it a few times. I get a notification saying DIM is active on my behalf. When this happens he deletes my character. You pay all this money for a game over the years but as soon as shit hits the fan and you need help, no one can help you. You get past on to the other.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
