### ISSUE TITLE
Untranslatable: "Create Loadout" and "Edit Loadout" at Loadout Drawer.

### ISSUE THREAD

**Issue by rentalhost** [DestinyItemManager/DIM#4936]
https://github.com/DestinyItemManager/DIM/blob/0689121d78bdff35660fe784c29e7195b3a70f83/src/app/loadout/LoadoutDrawer.tsx#L197

**Comment by delphiactual** [comment]
Closed by https://github.com/DestinyItemManager/DIM/commit/b51598fcb6f6caa2b7e3e82a13ca751298f1c708
