### ISSUE TITLE
Tactical mag does not add +1 magazine to Trophy Hunter

### ISSUE THREAD

**Issue by thomaskchan** [DestinyItemManager/DIM#4940]
Version 5.70.0.6471 (beta), built on 2/18/2020, 3:39:45 AM

Noticed this when rolling some weapons today.

Tactical mag on the Trophy Hunter shows 3 in the magazine in DIM, but in the game there are 4 in the magazine.  The mouseover for tactical mag doesn't show any + stats for magazine.

The perk looks like it works on other weapons like Arc Logic and Trust, but doesn't work on Bite of the Fox either.  Maybe a sniper issue?

Interestingly on Badlander when tactical mag was not selected, the mouseover for tactical mag did not show a +1 magazine, but it did after I selected the perk in-game and refreshed DIM.

**Comment by thomaskchan** [comment]
![tactical_mag](https://user-images.githubusercontent.com/13026069/74807627-c1069a80-529d-11ea-97f7-16e39226a412.png)

**Comment by bhollis** [comment]
Magazine is a very tricky stat, and DIM (or the official companion app) do not have the information to get it right all the time. Unfortunately the only 100% accurate magazine count is ingame, with the weapon equipped.

**Comment by bhollis** [comment]
More info about how we calculate stats: https://github.com/DestinyItemManager/DIM/wiki/DIM's-New-Stat-Calculations
