### ISSUE TITLE
"Assume Traction" in Loadout Optimizer

### ISSUE THREAD

**Issue by siema** [DestinyItemManager/DIM#4947]
As a gamepad user, I personally find it impossible to play without this mod slapped on just about any pair of boots I use.
While I understand the decision to ignore mods in general (also, flat 10's are easy to add in memory), Traction adding 5 Mobility really messes up the calculation.

Right now I have to search loadouts with 1 less Mobility than desired and check every result if Mobility ends with 5 or more (i.e 46, 77 etc.), so that Traction bumps it to desired amount.

Adding a checkbox to "Assume Traction" and add a flat 5 Mobility to results would be of great help.

**Comment by ryan-rushton** [comment]
Just lock the mod in the "Select Mod or Perk" section to the left.
