### ISSUE TITLE
Unable to move Dead Orbit tokens

### ISSUE THREAD

**Issue by blake403** [DestinyItemManager/DIM#4948]
As the title states, I'm unable to vault or move any Dead Orbit tokens from DIM.

**Comment by bhollis** [comment]
Yes, I believe those cannot be moved. Can you send a screenshot? Do we offer buttons to move it?

**Comment by blake403** [comment]
There are no buttons on there to move it. I wasn't sure if that was done on purpose or an oversight. I noticed other tokens like the old Trials tokens, Arcology and Nessus tokens can all be moved, but just this one Dead Orbit one can't. I don't have FWC or New Monarchy ones to see if they show the same behavior.

**Comment by delphiactual** [comment]
https://data.destinysets.com/i/InventoryItem:2959556799

`nonTransferrable:true`

**Comment by bhollis** [comment]
Yup, thanks for confirming. Those tokens have never been able to be moved by apps.

**Comment by blake403** [comment]
No problem. Thanks for checking on that, and confirming.
