### ISSUE TITLE
Compare items by base stats possible?

### ISSUE THREAD

**Issue by tcurtin** [DestinyItemManager/DIM#4949]
I love the comparison tool for armor, but since we can easily add mods to increase/decrease traits, when I'm looking to purge I want to get rid of pieces with lowest base stats.  Even if base total was a row, that would be helpful.  (Since showing all the base stats would add many rows.)

Or maybe a toggle setting in prefs to have comparison work off base stats?

**Comment by delphiactual** [comment]
search `basestat:total:<##`

**Comment by tcurtin** [comment]
Thanks @delphiactual -- that's possible yes, but doesn't help in this use case.

I have 26 armor 2.0 helmets for my Titan.  I want to only keep the ones with the highest BASE total stats.  There's a handy comparison tool I can use to see them all, but if I click to sort by total, I'm seeing total after any mods are applied.  However, since those mods are not only not permanent but cheap to switch, they're not true reflections on the long-term value to that armor piece.

I can indeed use the basestat:total or even maxbasestatvalue:total searches, but that requires several more interactions and quite a bit more thought to the user.

Current: 
click then type into search bar "maxbasestatvalue:total"
click a matching helmet, read its total value (its 61), click to close
click back to search bar, type "basestat:total:>59" ... nope, only the same single helmet.
click back to search bar, type "basestat:total:>58" ... ok, that shows several that I should keep.
click back to search bar, type "basestat:total:<55" ... these are candidates for removal?  maybe I should try lower.  Time to iterate!
(76 chars typed, 6+ clicks)

Proposed (notice no typing or iteration involved):
click a helmet
click the compare box
click "total" to sort by total
scroll right to see the worst
3 clicks, one drag

Honestly, it feels like the comparison tool for armor is not truly doing any good because it missed the beat with armor mods now being easy to swap around.

**Comment by delphiactual** [comment]
A new tool is being worked on you can see some of the progress here.
https://github.com/DestinyItemManager/DIM/pull/4826

**Comment by tcurtin** [comment]
Excellent - that seems like it will definitely fill the need.  (and probably also work better on smaller screens, also too.)

Thanks - will keep an eye out!
