### ISSUE TITLE
Incorrect percentage displayed on elder's sigil

### ISSUE THREAD

**Issue by techjoshua** [DestinyItemManager/DIM#495]
The elder's sigil High Score value can be greater than the required value.  For Example my current score is 42370 / 30000.  In spite of the fact that I've only run the Challenge of Elders once I appear to have it 94% completed.  The math on the two parts works out to this
``` ((42370 / 30000) * .5) + ((42370 / 90000) * .5) = .941555 ```

So the issue is that the first part produces a value that is greater than 1, which skews the total above the max for that part.  The math should be more like this:
``` (Math.min(42370 / 30000, 1) * .5) + (Math.min(42370 / 90000, 1) *.5) = .7353888 ```

**Comment by techjoshua** [comment]
I suspect this is the line which could be modified to resolve the problem

https://github.com/DestinyItemManager/DIM/blob/f1c6d18a236240cf34274f4b907e7518fd3222d1/app/scripts/services/dimStoreService.factory.js#L499

**Comment by bhollis** [comment]
Thanks, I'll take a look

**Comment by bhollis** [comment]
OK, all fixed up. Thanks for the report!
