### ISSUE TITLE
Show full stat number instead of tier in loadout optimizer

### ISSUE THREAD

**Issue by ahydronous** [DestinyItemManager/DIM#4950]
Hello

I've been trying to get the perfect setup for my character (100/60/100/40/40/30). I'm pretty close, the problem is: I can't see how close, or where wasted stats are. All I can see is my tiers.

Would it be possible to add a toggle so I can see the full loadout stats instead of just the tier level in the loadout optimizer? This would allow me to know what to look out for when farming.  
For example: I know that if I can get 1 more tier of mobility or resilience I can get the perfect stat split I mentioned. The 'easiest' place to get that is via farming Stompees since I only have the collection roll. The problem is I don't know if I need them to drop with 10 higher mobility, or if I just need 6 extra mobility, or perhaps I just need 4 extra resilience, etc. If I did, I can farm Stompees and if I see them drop with the stats mentioned I know I can celebrate a little.

Cheers

**Comment by bhollis** [comment]
No, unfortunately that's not how the Loadout Optimizer works. It works on tiers, not exact stats. If it worked on exact stats it would be unusably slow, and it would offer too many different sets that get the same result.
