### ISSUE TITLE
Destiny 1

### ISSUE THREAD

**Issue by MacDaddy616** [DestinyItemManager/DIM#4951]
Since enabling cross-save with Bungie, I have not been able to see the Destiny 1 in my list of Accounts in DIM.  Do I need to reach out to Bungie or is that something you can give me direction on resolving?

**Comment by delphiactual** [comment]
Did you link a Stadia account?

https://github.com/Bungie-net/api/issues/1151

**Comment by MacDaddy616** [comment]
I did.  Thanks for the to the existing issues.  I'll close this issue and watch for an update to the Stadia cross-save issue.  Thanks.
