### ISSUE TITLE
Cannot move weapon under certain circumstance

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#497]
https://www.dropbox.com/s/89ndpvogc38nm17/bug.gif?dl=0

If a bucket is completely empty and you try to move that equipped item to another character you get this error.

**Comment by bhollis** [comment]
Thanks! I'll take a look. It'll be tough to get any bucket that empty for me...

**Comment by delphiactual** [comment]
It should just be an order of operations error, currently DIM does the following in this situation

Move new item from vault to bucket
Attempt to equip item from character to character
Equip new item from vault

Steps 2 & 3 just need swapped...

**Comment by bhollis** [comment]
Yup, pretty simple. I have a repro.

**Comment by delphiactual** [comment]
This also happens if you have an exotic equipped and only exotics in the bucket...

**Comment by bhollis** [comment]
Yup, that's to be expected given the bug.

**Comment by bhollis** [comment]
OK, this is all fixed up. Thanks for pointing it out, I was able to make some significant improvements to the DIM codebase and how we choose what to move aside.

**Comment by delphiactual** [comment]
@bhollis doesn't appear to be fixed in 3.5.5.6542

https://www.dropbox.com/s/7n6shgttcdjkmjn/bug2.gif?dl=0

**Comment by SunburnedGoose** [comment]
@bhollis Was this pushed to dev?  I'm getting the negative infinity result from getSimilarItem.

**Comment by bhollis** [comment]
This was fixed in beffc8dd914e6c9a2442ee5bd0c0f1ca48f05826. Any "negative infinity result from getSimilarItem" would be a different bug.

**Comment by SunburnedGoose** [comment]
I’ve done it several times.  I'll get you a repo.

**Comment by bhollis** [comment]
Already fixed, I think. I introduced the bug in f0d2645, I always forget `_.max` behaves poorly on an empty list.

I can't test because I don't have enough vault space, but I'm confident it should work now.

**Comment by delphiactual** [comment]
@bhollis & @SunburnedGoose tested and working
