### ISSUE TITLE
Icon font causes misalignment in item move popup

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#4972]
![image](https://user-images.githubusercontent.com/313208/76150212-b8afad00-605c-11ea-9ada-e351673425f1.png)

@as-com in case you happen to know of a quick fix.

**Comment by as-com** [comment]
Might need to set font-size instead of width/height.

**Comment by sundevour** [comment]
![image](https://user-images.githubusercontent.com/31990469/76182048-8e571000-6180-11ea-9e07-bc5830378005.png)
this one looks weird still i think

**Comment by bhollis** [comment]
Ugh I hadn’t seen that one
