### ISSUE TITLE
Can not swtich to Destiny 1

### ISSUE THREAD

**Issue by Scalap77** [DestinyItemManager/DIM#4978]
Hello all, 

I don't know when exactly but I no longer have the option to switch on the D1 loadout/
It simply disappeared from the menu.

![Capture-DIM-issue](https://user-images.githubusercontent.com/61934886/76161338-d9e2cd00-6132-11ea-9cb0-c9be275d8a20.PNG)

I tried a lot of things (reinstall the plugin etc), but nothing has changed
An idea ?

**Comment by delphiactual** [comment]
Did you link stadia?

**Comment by Scalap77** [comment]
Yes that's right. I just read your redirect. I'm stuck with this :(
