### ISSUE TITLE
Colorblindness filter prevents drag and drop

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#4979]
Caused by the new dragging overlay.

cc @as-com

**Comment by as-com** [comment]
aaaaaaaaaaaaaaaa

**Comment by as-com** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=154671

Two possible solutions:
- Disable the performance fix when a filter is applied
- Make sure the overlay and :before overlays are in a separate stacking context independent of the filter

**Comment by bhollis** [comment]
Yup. We've hit this in the past. Firefox has its own set of bugs...

Probably best to just disable it when the filter is applied.
