### ISSUE TITLE
Unable to login via Stadia

### ISSUE THREAD

**Issue by robxu9** [DestinyItemManager/DIM#4994]
Trying to login via Stadia seems to put me into a login loop on any browser (Chrome, Firefox). After redirecting from Google, it just drops me back into DIM and the console shows that DIM receives a 401 from bungie.net still.

If I select Login with a different account, I can see myself logged in with bungie.net; if I hit approve, then I just go back to DIM still unable to load anything.

My accounts are cross-saved, and I've been able to login previously with any other credentials (Steam, Battle.net, Xbox Live all work).

**Comment by bhollis** [comment]
What happens if you select "Login with a different account", then log out and log in to Bungie.net with a non Stadia account, then link DIM?

**Comment by robxu9** [comment]
It loads fine on any other auth provider. Just seems to be the Stadia login option.

**Comment by bhollis** [comment]
Can you let me know exactly what you saw on the developer console?

**Comment by robxu9** [comment]
Here's the console error. My guess is that logging in through Stadia won't let DIM retrieve D1 characters, which is causing the whole thing to believe it is unauthorized... but given that it's just a login to Bungie.net, that seems odd:

```
authenticated-fetch.ts:54 GET https://www.bungie.net/D1/Platform/Destiny/1/Account/4611686018486763361/ 401
c @ authenticated-fetch.ts:54
async function (async)
c @ authenticated-fetch.ts:35
(anonymous) @ rate-limiter.ts:118
m @ bungie-service-helper.ts:43
d @ destiny1-api.ts:23
h @ destiny-account.ts:168
(anonymous) @ destiny-account.ts:158
(anonymous) @ destiny-account.ts:146
p @ destiny-account.ts:88
async function (async)
p @ destiny-account.ts:87
(anonymous) @ platforms.ts:60
(anonymous) @ platforms.ts:39
async function (async)
(anonymous) @ platforms.ts:21
(anonymous) @ util.ts:48
(anonymous) @ Root.tsx:26
Os @ Root.tsx:25
_o @ react-dom.production.min.js:135
Ga @ react-dom.production.min.js:175
Su @ react-dom.production.min.js:261
hs @ react-dom.production.min.js:230
ps @ react-dom.production.min.js:229
is @ react-dom.production.min.js:223
Zu @ react-dom.production.min.js:214
Us @ react-dom.production.min.js:279
(anonymous) @ react-dom.production.min.js:282
as @ react-dom.production.min.js:224
Gs @ react-dom.production.min.js:282
render @ react-dom.production.min.js:286
(anonymous) @ Index.tsx:66
Promise.then (async)
(anonymous) @ Index.tsx:57
a @ bootstrap:89
t @ bootstrap:45
r @ bootstrap:32
(anonymous) @ main-ded786.js?__WB_REVISION__=72f0124213e0fc1569e5:1
react_devtools_backend.js:6 Error getting D1 characters for {displayName: "DarkShadowKun", originalPlatformType: 1, membershipId: "4611686018486763361", platformLabel: "Xbox", destinyVersion: 1, …} Error: Please authorize DIM in order to use this app.
    at j (bungie-service-helper.ts:91)
    at M (bungie-service-helper.ts:198)
```

[Here's a video of the login flow. The link will expire in two days.](https://www.dropbox.com/s/kjm68kifprrikhz/2020-03-16%2001-01-42.mp4?dl=0)

**Comment by delphiactual** [comment]
This has been resolved
