### ISSUE TITLE
Show Upgraded Stat Value for Items

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#500]
User asked if we would show the upgraded stat value in the UI.

> Hi, sorry if I use private message, but I didn't see an email address to refer to and I don't know nothing about reddit! I would like to ask one thing: when I'm on PS4, if an item is not fully upgraded, I can see the max value this item can reach, for example, the "intellect" stat I see something like: Intellect 46 / 68 (68 if I upgrade the intellect node). When I inspect the item in DIM I just see "46". The same happens in bungie website...I would like to know if this is a limitation of the api or it's just a decision to not show this value. I find it useful to see what value an item/stat can reach. Thank you very much. Simone (sorry for my English!)

**Comment by kyleshay** [comment]
the problem with this is that 46 / 68.... the difference it the bonus/perk. we don't know if the player will eventually use the perk on their intellect, discipline, or strength stat.

basically we compute the base stats for each item, and know what the bonus perk will be limited to a minimum of a 280 light item.. below that there isn't enough data. we also know which perk they have applied ('increase intellect', etc.) 

this comes down to a display issue, and maybe we could address it with #491

**Comment by kyleshay** [comment]
i suppose if it's not an upgraded item, we could show it as destiny does until they pick a perk on it?

**Comment by SunburnedGoose** [comment]
Does Destiny show the upgraded stat in game for items less than 280?

**Comment by kyleshay** [comment]
yeah, they do. we don't have the data for that though. we'd need to crowd source how much the bonus is for data for items < 280 light

**Comment by SunburnedGoose** [comment]
I'll keep an eye out

**Comment by kyleshay** [comment]
technically we can pull the (amount a bonus provides) stat off of a specific endpoint, but it requires us to hit that endpoint for every single item. not sure if we want to go that route.

**Comment by kyleshay** [comment]
we can include this if we redesign the move popup. we have the data (it's just the value + bonus)

#491
