### ISSUE TITLE
Sort items by season

### ISSUE THREAD

**Issue by fdge** [DestinyItemManager/DIM#5002]
With weapon retirement on the horizon, the ability to additionally sort items by season.

**Comment by marheine** [comment]
If I understand what you're suggesting correctly, this is already possible with the `season` search string, using one of the following:
- redwar
- osiris
- warmind
- outlaw
- forge
- drifter
- opulence
- undying
- dawn
- worthy

**Comment by fdge** [comment]
Not exactly.
Settings >> Item Display >> Sort items by.

**Comment by delphiactual** [comment]
This depends on what Bungie decides to add to the API for weapon retirement, `season` is populated by our d2ai-bot and not provided by Bungie. I would rather support an official `MaxLightLevel` property than an arbitrary season number.

**Comment by bhollis** [comment]
I'm not sure we want to do this right now, but we'll revisit when weapon retirement rolls around.
