### ISSUE TITLE
Creating Loadouts issue

### ISSUE THREAD

**Issue by rekcluse** [DestinyItemManager/DIM#5015]
Currently when adding new weapons to a loadout I can't see the weapons being added - nothing changes with regards to the slots being take up although when I keep adding weapons it presents the prompt 'limit of 10' as you'd expect so it looks like they're being added.  
I have reinstalled DIM to my phone a few times. I'm using the Galaxy s10+ btw. 

Thanks.

**Comment by delphiactual** [comment]
App or beta?

**Comment by rekcluse** [comment]
App

**Comment by delphiactual** [comment]
Can you try on beta? I cannot reproduce this on my phone on either.

**Comment by rekcluse** [comment]
So I've been trying on beta. It seems to be adding some weapons but not others or adding them but I can't see they've been added. Also when I click on Any Class to choose class there's no option to choose a specific class

**Comment by rekcluse** [comment]
This is what I'm doing;

Create Loadout > Kinetic Weapons > Add random weapon (weapons shows) > + to add second weapon (weapon doesn't show)

**Comment by delphiactual** [comment]
Ok yep I can reproduce that
