### ISSUE TITLE
collection of sync issues that aren't data loss

### ISSUE THREAD

**Issue by sundevour** [DestinyItemManager/DIM#5016]
* [x] the sync checkbox not enabled by default (on login screen). i think you want it to be, but all my beta testing shows it isn't
* [x] every click of the refresh button (or hide/show page) adds another sync permission notification
* [x] Import skipped notification isn't clear
* [x] Delete all action prompt should say you MUST back up data before wiping it out

**Comment by sundevour** [comment]
re:
>Your old data wasn't imported because you already have settings, loadouts or tags saved in DIM Sync. If you want to replace that data, you can use the backup that was just saved, or from Settings.

- "old data" isn't immediately clear to me. stuff in sync might be older chronologically.
- "that data" is unclear because 2 different datas were mentioned.
- "that was just saved" might not be apparent enough to someone who was not expecting the sudden file download (which, for me in chrome at least, doesn't prompt for a save at all, just slides on into my dl folder)
- especially not sure what "or from Settings" means. like turn off Sync again? that doesn't always restore the local settings

my draft of this message, if i understand correctly, would look like
> Your local data was replaced because you already have settings, loadouts, or tags saved in DIM Sync. The local data was just saved to a backup file. If you want to replace DIM Sync's data with this backup, you can do so in the Settings menu.

**Comment by sundevour** [comment]
- delete everything, restart chrome, visit beta, (sync unchecked), complete bungie auth

- delete dim-api-enabled

- go to settings, go back to inventory

- every click of the refresh button adds another notification
![image](https://user-images.githubusercontent.com/31990469/77123068-64151600-69fc-11ea-96c0-d05758d4f975.png)

**Comment by sundevour** [comment]
if sync is disabled and i click the delete ALL data button:
![image](https://user-images.githubusercontent.com/31990469/77124132-4a290280-69ff-11ea-8cd0-9528d9d1630e.png)

if sync is enabled:
![image](https://user-images.githubusercontent.com/31990469/77124177-675dd100-69ff-11ea-8144-b4e6aae92711.png)

i took "should" to mean "should", but it turned out it meant "must or you aren't allowed to". this could be clarified in the verbiage

**Comment by bhollis** [comment]
Thanks, I took the liberty of updating the list in the initial issue comment, but let me know if I haven't captured them all.

Re: wording, I'm looking for some suggestions on what to call the data. Here's what we really have:

1. DIM Sync data that's stored in the cloud, in DIM API
2. Local data stored in IDB that's in the DIM Sync format, which will be kept up to date and synced with the API if and only if DIM Sync is enabled.
3. Local data stored in IDB that's in the old pre-DIM-sync format, which may optionally be synced with Google Drive, and which is kept up to date but not read from even if DIM Sync is enabled. If DIM Sync is disabled, this is the only data that is read from or modified.

When I say "old data" I mean #3. When you say "local data", I think #2, which isn't actually what most of that stuff controls.

**Comment by bhollis** [comment]
Fixed all these!
