### ISSUE TITLE
dim api possible data loss situations

### ISSUE THREAD

**Issue by sundevour** [DestinyItemManager/DIM#5017]
1. [x] Enabling sync on a clean browser shows "skipped sync" if you have existing data in DIM API.
2. [x] Import skipped dialog references a backup, but the backup isn't created when enabling from settings.
3. [x] Figure out a way to better explain that your old data isn't gone, but you're not gonna see it.
4. [ ] Explore merging data rather than skipping import?
5. [x] Turning sync off, old data (tags specifically) don't show up.

- delete all, restart chrome, visit beta, (sync unchecked), complete bungie auth

- import my tags and settings 
![image](https://user-images.githubusercontent.com/31990469/77017641-31a1e500-6938-11ea-97f0-358670471ed2.png)
(tags are there in inventory view)

- enable sync in settings. get this message
![image](https://user-images.githubusercontent.com/31990469/77017717-6877fb00-6938-11ea-8165-6554fc569b38.png)
**what i expected:** a file to download
**what happened:** a file didn't download

- check inventory
**what happened:** 6 tags that sync is storing for me, have been correctly applied to those items.
my other 500 items have become untagged
**what i was hoping for:** my existing information would be synced into dim sync like the name implies. merge i guess, into dim cloud's existing item information for me.

- turn sync off to try and get my data back
**what i expected:** from what bhollis described, maybe revert back to old info?
**what happened:** the 6 tags are still there, `dim-api-enabled` is `false`

**Comment by sundevour** [comment]
- delete all, restart chrome, visit beta, (sync unchecked), complete bungie auth

- **delete `dim-api-enabled`.
does this sufficiently simulate being an existing user who has newly downloaded the new sync update?
it certainly gets me the notification.**

- import my tags and settings 
![image](https://user-images.githubusercontent.com/31990469/77017641-31a1e500-6938-11ea-97f0-358670471ed2.png)
(tags are there in inventory view)
**(notification is prompting me to enable sync)**

- enable sync in settings. get this message
![image](https://user-images.githubusercontent.com/31990469/77017717-6877fb00-6938-11ea-8165-6554fc569b38.png)
**what i expected:** a file to download
**what happened:** a file didn't download

- **what i expected:** notif to go away
**what happened:** didn't until page refresh

same situation beyond that.
if people accept sync on their non-main device first, then on their main, they get their phone's tags or lack thereof etc.

**Comment by sundevour** [comment]
is there a difference in storage, between where settings go, if i select no sync, and then either

- import a json:
then enabling sync gives me "skipped data import" and seems to wipe the local data

- tag an item:
then enabling sync gives me no notification at all, and when i turn sync back off, the item i tagged gets its local tag back

are these meant to be such different behaviors?

**Comment by sundevour** [comment]
ok so the "enable sync" notification triggers a backup file download,
and enabling via settings does not

**Comment by sundevour** [comment]
re:
>Your old data wasn't imported because you already have settings, loadouts or tags saved in DIM Sync. If you want to replace that data, you can use the backup that was just saved, or from Settings.

- "old data" isn't immediately clear to me.
- "that data" is _slightly_ unclear.
- "that was just saved" might not be apparent enough to someone who was not expecting the sudden file download (which, for me in chrome at least, doesn't prompt for a save at all, just slides on into my dl folder)
- especially not sure what "or from Settings" means. like turn off Sync again? that doesn't always restore the local settings

my draft of this message, if i understand correctly, would look like
> Your local data wasn't imported because you already have settings, loadouts, or tags saved in DIM Sync. If you want to replace DIM Sync's data with your local data, you can use the backup file that was just saved.

**Comment by sundevour** [comment]
- made sure sync was OFF

- did ![image](https://user-images.githubusercontent.com/31990469/77122172-2e6f2d80-69fa-11ea-87ea-a3d06653a575.png)

- delete everything, restart chrome, visit beta, (sync unchecked), complete bungie auth

- delete dim-api-enabled.

- same import process
(notification is prompting me to enable sync)

- enabled sync via notification

- got "skipped import"
![image](https://user-images.githubusercontent.com/31990469/77122204-45ae1b00-69fa-11ea-9a18-cf8a7ef84355.png)

**Comment by sundevour** [comment]
- delete everything, restart chrome, visit beta, (sync unchecked), complete bungie auth

- delete dim-api-enabled

- go to settings, go back to inventory

- every click of the refresh button adds another notification
![image](https://user-images.githubusercontent.com/31990469/77123068-64151600-69fc-11ea-96c0-d05758d4f975.png)

**Comment by sundevour** [comment]
i get the feeling that ^ doesn't represent true legacy user, is the json import i do going into the new settings object or the old?

**Comment by bhollis** [comment]
Commented in Slack - it's a bit hard to respond to these all in one big line without threaded replies. I think everything but your last case is expected but unclear to the user, and the last one is unexpected and I'll have to understand what is going on.

**Comment by bhollis** [comment]
I think I've handled all of this - LMK.
