### ISSUE TITLE
Make room for the Postmaster

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#502]
https://www.reddit.com/r/DestinyItemManager/comments/4hnqfi/idea_make_room_in_my_inventory_for_shit_in_my/

> It would be nice to have a "make room for my shit in the postmaster" button that moved stuff from my inventory to somewhere else to make room in my inventory for everything currently in my postmaster, so that I can immediately grab everything in my postmaster (ex: detect that my postmaster has 4 primary weapons, 2 chestpieces, 3 class items, and 2 gauntlets so make room for all that stuff in my inventory).
> 
> Right now, the thing that takes me the most time with inventory management, is looking at everything in my postmaster, moving stuff away from my character to make room for it, then moving my original stuff back when I'm done deleting stuff that I got out of the postmaster. This would save me a huge amount of time, and make the unenjoyable task of emptying the postmaster more bearable. Any chance of something like this? Thanks.

User wants a feature that will remove items from their inventory that matches what is in the postmaster.  When they are done processing their postmaster gear, they would like to move the gear back.

**Comment by bhollis** [comment]
Yup I've been thinking about this. It's a pretty natural follow-on from the engram farming stuff. Unfortunately there's some tricky stuff around trying to make a bunch of space that'll take some work.

**Comment by delphiactual** [comment]
https://www.reddit.com/r/DestinyItemManager/comments/59x1rm/feature_suggestion_free_up_enough_space_to_unload/
