### ISSUE TITLE
Can't load app under Chrome

### ISSUE THREAD

**Issue by MaxFarabundo** [DestinyItemManager/DIM#5021]
Chrome 80.0.3987.132 under Win 7 Pro on the laptop.
5-10 second loading, then message: Failed to load page. And the only button - reload - with the same result.
Logout/login. Same.
Cleared cache. Same.

**Comment by bhollis** [comment]
Unfortunately that's not enough to go on to figure out what's happening. You could hop on our discord, maybe folks there can help dig into some details.
