### ISSUE TITLE
Unauthenticated xbox character appears and not PC characters

### ISSUE THREAD

**Issue by beedonic** [DestinyItemManager/DIM#5027]
So i messed up when adding on my xbox stuff during the migration and ended up linking his account to mine. I did not authenticate this on the bungie website, i did authenticate my pc account however. When  i log in to DIM the xbox one appears

**Comment by bhollis** [comment]
What shows up when you use the Destiny 2 Companion App or log in to Bungie.net?

**Comment by beedonic** [comment]
In the Destiny Comoanion app it shows my steam character, see attached for
screenshot from my phone. Same as on bungie.net.

**Comment by bhollis** [comment]
Did you check in the menu to see whether the other account is available?
