### ISSUE TITLE
is: vs source: for events

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#5036]
We have the following filters:

`is:dawning
is:crimsondays
is:solstice
is:fotl
is:revelry`

However, every other "where did this come from" filter is source: eg.

`source:gambitprime
source:menagerie
source:calus`

For consistency they should all be source:

**Comment by delphiactual** [comment]
Historically this is because `events` existed before `source` information in D2.

**Comment by delphiactual** [comment]
should this be its own keyword e.g. `event:` instead?
