### ISSUE TITLE
Items with Defense < 285 showed 100% quality but when infused, dropped to 98% and 96%

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#504]
I had two items that were 283 and 282 that showed 100% quality.  I infused them and the result was 98% and 96%.  Should we be showing quality data at that level if the result isn't very accurate?

**Comment by bhollis** [comment]
Linking #515

**Comment by JosephBono** [comment]
Relevant Reddit post trying to gather more precise data for slopes and such:

https://www.reddit.com/r/DestinyTheGame/comments/4iqgs7/now_that_armor_quality_is_a_thing_lets_review_and/

**Comment by JosephBono** [comment]
I think we can merge this with #528

**Comment by kyleshay** [comment]
fixed in #572
