### ISSUE TITLE
Can't find spider in vendors

### ISSUE THREAD

**Issue by arane9** [DestinyItemManager/DIM#5041]
I can't find spider in the vendors section. Am I the only one?

**Comment by delphiactual** [comment]
are you on a character that has not unlocked spider yet?

![image](https://user-images.githubusercontent.com/4798491/77271856-5cac7180-6c75-11ea-8b97-b64d8939758d.png)

**Comment by arane9** [comment]
I shop at him with all characters.  I can see all vendors but him.

![no spider](https://user-images.githubusercontent.com/62527908/77274494-64155e80-6cf9-11ea-90d3-c2916ff01c55.png)

**Comment by delphiactual** [comment]
https://app.destinyitemmanager.com or https://beta.destinyitemmanager.com

**Comment by arane9** [comment]
Logged in the beta version, same results. Not sure what I'm doing wrong.

![nospider2](https://user-images.githubusercontent.com/62527908/77276836-ee13f600-6cfe-11ea-8106-380c67abb86a.png)

**Comment by delphiactual** [comment]
try toggling between different characters on that page

**Comment by arane9** [comment]
same results for all 3 characters. no change

**Comment by arane9** [comment]
I think I know what the problem is. I don't have the forsaken dlc. I'm confident this is the reason why spider doesn't show up.
