### ISSUE TITLE
Reverie Dawn, Armor 2.0 pieces not correctly identified to have modslot

### ISSUE THREAD

**Issue by GosubGosub** [DestinyItemManager/DIM#5042]
When searching for items with say, modslot:any -- Reverie Dawn, Armor 2.0 pieces are not highlighted.

![image](https://user-images.githubusercontent.com/62539970/77298037-7b991b00-6cea-11ea-9db2-481b7f3b5b67.png)

![image](https://user-images.githubusercontent.com/62539970/77298223-e21e3900-6cea-11ea-90cf-1a7ac8b1379b.png)

If I inspect them, I can see that they have the outlaw modslot.

![image](https://user-images.githubusercontent.com/62539970/77298103-a2575180-6cea-11ea-884b-d03941719977.png)

**Comment by sundevour** [comment]
thank you for the report! i will get hold of some reverie armor and test this out.

**Comment by m-bruck** [comment]
This is from the csv for an affected item (generated in the Menagerie IIRC):

Name,Hash,Id,Tag,Tier,Type,Source,Equippable,Power,Masterwork Type,Masterwork Tier,Owner,Locked,Equipped,Year,Season,Event,DTR Rating,# of Reviews,Mobility,Resilience,Recovery,Discipline,Intellect,Strength,Total,Mobility (Base),Resilience (Base),Recovery (Base),Discipline (Base),Intellect (Base),Strength (Base),Total (Base),Seasonal Mod,Notes,Perks 0,Perks 1,Perks 2,Perks 3,Perks 4,Perks 5,Perks 6,Perks 7,Perks 8,Perks 9
Reverie Dawn Bond,1928769139,"""6917529118891675377""",,Legendary,Warlock Bond,,Warlock,1000,Void Energy Capacity,10,Warlock(1019),true,false,2,4,,N/A,N/A,2,12,2,2,2,2,22,2,2,2,2,2,2,12,,,Resilience Mod*,Better Already*,Absolution*,Taken Barrier*,Upgrade Armor*,Dragonfly Regalia Bond*,,,,

**Comment by delphiactual** [comment]
closed by #5071
