### ISSUE TITLE
cannot include Consumables in loadout

### ISSUE THREAD

**Issue by Korben85** [DestinyItemManager/DIM#5043]
Hi,
I don't really know if this is an issue or not, but I cannot add usable items to a loadout.
I would like to make a loadout which includes some usable items I sometimes transfer from my chars to vault. Since there is an option to also include usable items in the loadout editor I thought it would be possible, but I cannot select any item. Also filtering in the editor seems to be buggy. When I go to the vault and click create loadout and then click on usable items, nothing is shown. However when I do this on a char I can see the items, but cannot select them.

Any help is appreciated!

Korben

**Comment by delphiactual** [comment]
Just to be clear, you are referring to tokens etc?

**Comment by Korben85** [comment]
Hi,
Well, I should have been more precise. Yes, I mean everything that is shown under is:reptoken.
