### ISSUE TITLE
Google Chrome won't let me install DIM

### ISSUE THREAD

**Issue by dhgorigin** [DestinyItemManager/DIM#5057]
For some reason, my chrome doesn't allow me to install DIM on my PC. I have tried clearing my chrome cache, enabling some specific flags, restart my PC, and other things. Chrome just does nothing when I try to click install. I previously have had it installed, but had to delete it when I accidentally got malware on my pc. My anti-virus software deleted all the malware, but also took some other things with it (such as Corsair iCUE and DIM). The only thing I haven't done is do a fresh install of Google Chrome. Would I lose my bookmarks and other saved items if I do a fresh install of Chrome? Otherwise, any ideas why my chrome won't let me download DIM again??

Thank you for any and all help for this issue.

**Comment by bhollis** [comment]
Unfortunately I think this is more of a question for Chrome than for DIM. We've done the work to make DIM installable, but what happens after that is a Chrome issue.
