### ISSUE TITLE
Maximum power average is wrong

### ISSUE THREAD

**Issue by CyborgShadow43** [DestinyItemManager/DIM#5061]
My Titan was showing an average of 1003.8 when the total of the equipment was 8032 /8 = 1004.  The other characters are off also.

**Comment by bhollis** [comment]
Screenshot of your gear?

**Comment by CyborgShadow43** [comment]
I guess I should have taken a screenshot at the time.  Since then, DIM showed that it had an update and I have been playing Iron Banner with new higher gear dropped.  It looks the calculation is right now.  It was off by .2 per character before.  Very odd.
