### ISSUE TITLE
Error setting up local environment: "Error authorizing DIM"

### ISSUE THREAD

**Issue by pat-son** [DestinyItemManager/DIM#5062]
I tried to set up a local dev environment, but I got this error after trying to log in:

```
Error authorizing DIM: Unknown This might be a problem with DIM, or it might be an issue with Bungie.net or your browser.

Check DIM status on Twitter or let us know what error you're seeing.

Go back to DIM and try again
```

Not sure if I copy+pasted my API keys wrong, but I can't get back to that screen to try and fix it

**Comment by delphiactual** [comment]
https://localhost:8080/developer
or
https://127.0.0.1:8080/developer
