### ISSUE TITLE
DIM requiring code verification on accounts that do not have 2FA enabled

### ISSUE THREAD

**Issue by Deuce-Cuatro** [DestinyItemManager/DIM#5064]
This is a recent issue that has been happening. When I've tried to log-in via DIM lately I am met with a screen that says:

'It looks like you're trying to sign in to your account from a new device or browser.

A verification code has been sent to your e-mail address.

Enter the code that was sent to you in the field below, and then select [Verify].'

Why is this happening now? And how can I bypass it?

If the account owner doesn't send their code in a timely manner, then the next sign-in attempt is met with the message:

'An authentication error has occurred. Reset your password or contact customer support.'

I can provide more information if needed. Solutions I have tried: different devices (2 laptops and a tablet), different browsers (Chrome and Firefox), clearing browser caches/history, and enabling a VPN. None have changed the outcome.

Please help

**Comment by Deuce-Cuatro** [comment]
Why are these being closed without any replies or warning?

**Comment by delphiactual** [comment]
You can contact Bungie Support.

**Comment by Deuce-Cuatro** [comment]
Okay, will do, but still why would they be closed on a DIM help forum? It's
a DIM issue. Please explain a bit more.

**Comment by delphiactual** [comment]
It is not a DIM issue

**Comment by Deuce-Cuatro** [comment]
What makes you certain? Knowing that would help me tremendously in fixing
this.

**Comment by delphiactual** [comment]
We do not actually have any authentication, it all runs through Bungie

**Comment by Deuce-Cuatro** [comment]
Interesting, thank you
