### ISSUE TITLE
Selecting "Tactical Air Support" as a locked perk in the D1 Loadout Optimizer crashes the application

### ISSUE THREAD

**Issue by jbccollins** [DestinyItemManager/DIM#5065]
<img width="767" alt="Screen Shot 2020-03-28 at 6 24 23 PM" src="https://user-images.githubusercontent.com/8915552/77835327-f4043f80-7121-11ea-8589-b6557689f08b.png">
<img width="562" alt="Screen Shot 2020-03-28 at 6 28 02 PM" src="https://user-images.githubusercontent.com/8915552/77835329-f49cd600-7121-11ea-8054-d420ab1c3b18.png">

**Comment by bhollis** [comment]
It looks like you have some kind of item that I don't have in my test account...

**Comment by bhollis** [comment]
Fixed by https://github.com/DestinyItemManager/DIM/commit/5d9d3f762c9d2e11a58ee45444ecd690d2229b62
