### ISSUE TITLE
Loadout Optimizer "Max Power" field won't accept input

### ISSUE THREAD

**Issue by DHager** [DestinyItemManager/DIM#5066]
**Context:** In the Loadout Optimizer, there is a "Max Power" field on the far left, with a text-box containing the current value. Using Firefox 

**Expectation:** The text-box appears to be editable, so users should be able to enter an amount.

**Actual behavior:** Attempting to enter/overwrite existing numbers causes it to instead reset to either the minimum or maximum. 

**Proposal:** Allow entry of numbers, or else change the appearance so that it is clear that number-entry is not a possibility. (e.g. Making the input-box read-only, or changing it to regular text.)

**Comment by joe7dust** [comment]
Maxpower just shows you your highest in each slot so you know which gear pieces are affecting your total power calculation (and thus drops).

To search for a range use the Power: function like Power:>999
