### ISSUE TITLE
Compare Items modslot filter misses/miscategorizes items

### ISSUE THREAD

**Issue by m-bruck** [DestinyItemManager/DIM#5067]
1. Start 'Compare Items' from _Dreambane Hood_, Filter by _Undying Armor Mod_
Result: _Mask of Righteousness_ incorrectly omitted from results. Another _Mask of Righteousness_ is correctly included in the results though.

2. Start compare from the previously incorrectly omitted _Mask of Righteousness_
Result: incorrect filter option _Opulent Armor Mod_ is offered.

3. Start compare from the previously correctly included _Mask of Righteousness_
Result: correct filter option _Undying Armor Mod_ is offered.

4. Same happens for _Robes of Transcendence_ and _Iron Will Steps_ items, both incorrectly treated as having _Dawn Armor Mod_ this time.

5. modslots:undying correctly highlights all items.

**Comment by delphiactual** [comment]
@sundevour was this also fixed by #5267

**Comment by sundevour** [comment]
very very likely. unstated cause here, but worth a re-check from @m-bruck

**Comment by m-bruck** [comment]
fixed, thanks
