### ISSUE TITLE
Update 6.3.0 removes all armor from the D1 inventory view

### ISSUE THREAD

**Issue by jbccollins** [DestinyItemManager/DIM#5075]
<img width="1092" alt="Screen Shot 2020-03-29 at 9 27 22 PM" src="https://user-images.githubusercontent.com/8915552/77867164-179fb680-7204-11ea-9809-93afcd3290a2.png">

Armor is gone from the inventory view in D1 as of update 6.3.0 :(

**Comment by jbccollins** [comment]
FWIW Commit `3948367eb8dcaa65bf1331a9314c2e1856114394` works and is what I'm running locally to use DIM. I haven't run `git bisect` in a hot minute though so I'm not sure what commit actually broke this.

**Comment by bhollis** [comment]
https://github.com/DestinyItemManager/DIM/pull/5055 is likely the culprit

**Comment by bhollis** [comment]
FWIW I can't reproduce with my D1 account - you must have some item I don't.

**Comment by bhollis** [comment]
Can you please take a look in beta and verify that this is fixed?

**Comment by jbccollins** [comment]
Yep that seems to be working now :)
