### ISSUE TITLE
Destiny 1 "Vendors" tab crashes as of 6.3.0

### ISSUE THREAD

**Issue by jbccollins** [DestinyItemManager/DIM#5079]
Here is the error I get:

<img width="426" alt="Screen Shot 2020-03-30 at 9 58 28 AM" src="https://user-images.githubusercontent.com/8915552/77921410-c2988a80-726d-11ea-9165-d06873213d0b.png">

The page is completely blank.

**Comment by delphiactual** [comment]
We need more D1 users on [beta](https://beta.destinyitemmanager.com) so these don't get released to app

**Comment by jbccollins** [comment]
The "Record Books" tab is also crashing. For now I'm assuming it's for the same reason.

**Comment by jbccollins** [comment]
Ok looks like there are multiple (maybe related) errors here. The first one has to do with this invalid assignment in `d1-item-factory.ts`
<img width="421" alt="Screen Shot 2020-03-30 at 4 37 03 PM" src="https://user-images.githubusercontent.com/8915552/77959757-25594880-72a5-11ea-9d1c-4109d072d90e.png">

Which is called from `makeItem`. An example item hash that crashes is `2736415751`
<img width="566" alt="Screen Shot 2020-03-30 at 4 37 50 PM" src="https://user-images.githubusercontent.com/8915552/77959838-46ba3480-72a5-11ea-9b30-cd22c960faff.png">

But this error seems to be caught so maybe it's fine/expected for this to happen? In any case I'm pretty sure that leads to the error in the `D1VendorItems.tsx` screenshot above.

**Comment by bhollis** [comment]
Fixed by https://github.com/DestinyItemManager/DIM/pull/5083
