### ISSUE TITLE
Move Popup is obscured

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#508]
When opening a popup, it's easy for it to have content below the fold or clipped by the top of the page.  There is plenty of room on the left or right to present the popup so we should consider that.

![screen shot 2016-05-04 at 6 31 50 pm](https://cloud.githubusercontent.com/assets/984608/15032445/8e030a76-1226-11e6-9310-20a43f46aa9a.png)

**Comment by bhollis** [comment]
I imported jquery.ui.position for the Xur stuff, and I've been meaning to use that for normal item popups - it can consider when it's going to go off an edge and choose other positions.

**Comment by SunburnedGoose** [comment]
Reported today.

https://twitter.com/dustinnoe91/status/751289838997909504

![cm0d-qqueaemiah](https://cloud.githubusercontent.com/assets/984608/16678497/2e5942aa-44a5-11e6-96b3-5ac6f1a206dd.jpg)

**Comment by bhollis** [comment]
That's because we haven't merged this...

**Comment by bhollis** [comment]
Merged #658, that is.

**Comment by SunburnedGoose** [comment]
Here's a fun wrinkle.

I see this...

![screen shot 2016-07-19 at 8 16 52 pm](https://cloud.githubusercontent.com/assets/984608/16972015/f8352e08-4ded-11e6-8c78-613a81aeb865.png)

and I have to scroll down to see the popup.

![screen shot 2016-07-19 at 8 17 03 pm](https://cloud.githubusercontent.com/assets/984608/16972026/0a68b392-4dee-11e6-8f69-d0f57ab24ebe.png)

Can we give the popup some awareness so that it will attempt to stay visible below the header as the user scrolls?

**Comment by SunburnedGoose** [comment]
Error in Loadout Builder.

![screen shot 2016-07-21 at 2 01 37 pm](https://cloud.githubusercontent.com/assets/984608/17035214/b4695000-4f4b-11e6-9e2a-f34746862077.png)

**Comment by bhollis** [comment]
@SunburnedGoose the popup should be aware of the visible area and not pop outside it, though if there's not enough space on either side it'll prefer the top.

We could update position as people scroll, but that'd be weird, both from a performance standpoint (repositioning on scroll event) and because things would slide around.

I'm not sure about your last screenshot, I'll try to repro on my end.

**Comment by bhollis** [comment]
OK I see what happens when it's scrolling. I can look at fixing it.

**Comment by bhollis** [comment]
OK, fixed.
