### ISSUE TITLE
Fails to display on safari for iPad

### ISSUE THREAD

**Issue by Robbeh13** [DestinyItemManager/DIM#5082]
Previously, application worked fine on iPad. As of the enable sync feature, only the title bar and icons load.

The large loading manifest animation in the body does not appear, and the UI never finishes loading.

Note that it currently still works on iPhone safari.

**Comment by bhollis** [comment]
What version of iOS?

**Comment by Robbeh13** [comment]
iOS version 13.3.1

**Comment by bhollis** [comment]
Give it a try now - any luck?

**Comment by Robbeh13** [comment]
It's better, but not fixed.  I now see the animated loading squares in the center of the screen. The menus are populated: I see inventory, Vendors, Collections, Loadout Optimizer. I didn't see those before. However, the loading arrows and the loading squares animation never stop. I loaded DIM on my computer to verify that bungie's APIs are working, and they are, so there's probably some bug somewhere still.

Thanks for investigating this.

**Comment by Robbeh13** [comment]
I was able to attach a debugger to the iPad. Looks like all the sources are loading fine, but there's an Unhandled Promise Rejection. There's no link to where that fails in the source, so I can't be more specific to where the problem is.... But I am able to poke around in the developer web console, so if there's anything in timelines/source/storage/console that I can help identify for you, let me know. 

[Error] Unhandled Promise Rejection: null
	(anonymous function)
	rejectPromise
	promiseReactionJob

**Comment by Robbeh13** [comment]
Also, there are 3 other errors:
[Error] The source list for Content Security Policy directive 'script-src' contains an invalid source: ''strict-dynamic''. It will be ignored.
[Error] The source list for Content Security Policy directive 'script-src' contains an invalid source: ''report-sample''. It will be ignored.
[Error] The source list for Content Security Policy directive 'script-src' contains an invalid source: ''strict-dynamic''. It will be ignored.

**Comment by bhollis** [comment]
Unfortunately, none of those help much. We'd need to know what's actually failing.

**Comment by Robbeh13** [comment]
Well, as of 3 days ago it's working again. Two things changed: There was a DIM update, and I killed the safari app on my iPad. It now works again. I have no idea if it was a code issue or something specific to my iPad. But I'm glad it's working again.

Thanks for your attention.
