### ISSUE TITLE
Loadout Optimizer button in Edit Loadout should lock loadout items in LO

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#5084]
Pick a loadout in the Inventory screen and click the edit button.  This opens the Edit Loadout panel.

![image](https://user-images.githubusercontent.com/25425159/78104115-18b82a00-7436-11ea-822f-bfbd501f6898.png)

Click the Load Optimizer button.  The expected behavior is that the Loadout Optimizer window will open with this loadout selected, allowing it to be tweaked.

What actually happens, is you get a dialog pop up asking if you want to abandon the loadout.

![image](https://user-images.githubusercontent.com/25425159/78104199-43a27e00-7436-11ea-9ff8-ce64bc3b7850.png)

If you say yes, it does start the Loadout Optimizer, but the selected loadout is not there for editing.

![image](https://user-images.githubusercontent.com/25425159/78104289-81070b80-7436-11ea-9e6a-9d7393bd8c71.png)

**Comment by bhollis** [comment]
Ah, I think this is just mistaken expectations. The button just opens loadout optimizer.

**Comment by philkernick** [comment]
It would be great it if did what I expected it to do, as while you can build a loadout, there is no way to tweak it once built.

Otherwise I suggest removing the button from the edit panel if it doesn't offer anything more than selected Loadout Optimizer from the top menu, and can cause mistaken expectations!
