### ISSUE TITLE
Missing "Transfer reputation items" option

### ISSUE THREAD

**Issue by KenpachiFriedChicken** [DestinyItemManager/DIM#5085]
Since 6.1.0 (2020-03-22) ive been missing the option on the vault tab to transfer reputation items to vault:
![image](https://user-images.githubusercontent.com/62994740/78131118-cfa6ac80-741a-11ea-8d4e-da3f8883455c.png)

**Comment by delphiactual** [comment]
https://github.com/DestinyItemManager/DIM/blob/master/docs/CHANGELOG.md#5710-2020-02-23
