### ISSUE TITLE
Gear Export to Text List

### ISSUE THREAD

**Issue by knuxem95** [DestinyItemManager/DIM#509]
I made a Excel Workbook that tracks a players gear and it has support for a comma delimited text file that is generated using DIM. Link here: https://www.reddit.com/r/DestinyTheGame/comments/4f95gt/destiny_master_checklist_v21/

Thanks to [wein3967](https://www.reddit.com/u/wein3967) who created the original code to be used in Chrome's developer console, I was able to modify it to fit my needs. I'm wondering if it would be possible for you developers to expedite the process and make it an option to export this data in DIM itself. Thanks!

EDIT: Secondary to this, I'm wondering if DIM (through Bungie's API) has access to what shaders, ships, emblems, and sparrows a player has acquired as noted by the kiosks in the game. I'm guessing no, though, as it probably only has the functionality to see a players inventory.

**Comment by kyleshay** [comment]
great suggestion! thought we already do have a task for this.

closing in favor of #487, feel free to continue discussion over there!
