### ISSUE TITLE
Can Sterling Treasure be Moved?

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#510]
Users would like to move this in DIM between characters.

**Comment by Mulchman** [comment]
I'm able to move them in Ishtar Commander and also another app; it seems to
be a restriction DIM has placed on them.

**Comment by bhollis** [comment]
I can move Sterling Treasure through DIM... can you not?

I mean, I can't move them out of the Postmaster, but nobody can move stuff from the Postmaster through the API.

**Comment by JosephBono** [comment]
In 3.6.0 I cannot move Sterling Treasure from vault to character (or character to character). 
In 3.6.0.17144 I can move Sterling Treasure.

This is also true for Worn Sacks and Rotten Candy (won't move in 3.6, will in 17144).

**Comment by kyleshay** [comment]
maybe it was fixed somehow with pr #505 ?

**Comment by JosephBono** [comment]
@Mulchman Can you verify that you can move Sterling Treasure in 3.6.0.17144? If so, I think we can close out this issue.

**Comment by Mulchman** [comment]
Verifying I can move Sterling Treasure.

**Comment by kyleshay** [comment]
Thanks!
