### ISSUE TITLE
Manifest fails to load due to CORS error

### ISSUE THREAD

**Issue by as-com** [DestinyItemManager/DIM#5101]
> Access to fetch at 'https://www.bungie.net/common/destiny2_content/json/en/DestinySeasonDefinition-9e3c0093-e5a2-41ce-90e7-9f0ed825ac0c.json' from origin 'https://beta.destinyitemmanager.com' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'https://www.bungie.net' that is not equal to the supplied origin. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

This could be a Bungie.net and/or CDN caching issue, as it only seems to happen on the EWR Cloudflare colo on my end. It appears that Access-Control-Allow-Origin is set to `*` for every definition file except for DestinySeasonDefinition (where it is set to bungie.net), and the value of the header may be dependent on when/where the initial request was issued.

Proposed workarounds:
- append a DIM-specific static cachebuster query string to work around bad caching when 
something goes wrong
- temporarily proxy the manifest files through DIM servers until this is fixed on the Bungie.net side

**Comment by bhollis** [comment]
Definitely seems to be only certain CloudFlare pops. I can add a quick cachebuster.
