### ISSUE TITLE
Unable to load Destiny Profile

### ISSUE THREAD

**Issue by CyborgShadow43** [DestinyItemManager/DIM#5102]
After Destiny reset yesterday, one of my PCs cannot load my D2 PSN profile.  I can load my D1 profile.  I have cleared browser data.  I have logged out and back in.  Chrome version 81.0.4044.92.  DIM version 6.4.0.6782 (Beta). Incognito mode does not work either.
![DIMD2load](https://user-images.githubusercontent.com/58813317/78773301-06238080-7961-11ea-937a-066336e2a047.JPG)

**Comment by delphiactual** [comment]
Logs

**Comment by CyborgShadow43** [comment]
How do I create/get logs?

**Comment by CyborgShadow43** [comment]
[consolelog.txt](https://github.com/DestinyItemManager/DIM/files/4451438/consolelog.txt)

Console log inside of Chrome

**Comment by Karmac0de** [comment]
Having the same problem. Here's a link to my log: https://1drv.ms/u/s!As0vMiqjNFWmrmszkJD8gcfUG3EF?e=7ZGuyu

**Comment by as-com** [comment]
This is likely due to #5101

**Comment by CyborgShadow43** [comment]
Seems to be working today.
[consolelog2.txt](https://github.com/DestinyItemManager/DIM/files/4455662/consolelog2.txt)
