### ISSUE TITLE
Loadout Optimizer - use Linear/Integer programming solver for combos

### ISSUE THREAD

**Issue by sitch** [DestinyItemManager/DIM#5107]
Saw a warning notice using the Loadout Optimizer.  Said that 500k combinations was too much otherwise it would crash. Seemed awfully low so i briefly looked at the code and it seems like its doing 6 for loops (brute force?).  

Should be able to use a LP/IP solver for an efficient search this and remove the warnings.  There's a few libs but you can get the jist of it on the readme here: https://github.com/JWally/jsLPSolver

**Comment by bhollis** [comment]
PRs welcome!

**Comment by sitch** [comment]
Would look more-or-less like this:
```js
import {solver} from "javascript-lp-solver"

function castArmor(item) {
  return {
    // `type` here would be helm / gauntlets / chest / etc
    [item.type]: 1,
    strength: item.strength,
    intelligence: item.intelligence,
    discipline: item.discipline,
    resilience: item.resilience,
    recovery: item.recovery,
    mobility: item.mobility,
    statTotal: item.statTotal,
  }
}

function buildModel(armorPieces = [], opts = { optimize: "statTotal", opType: "max" }) {
  return {
    ...opts,
    constraints: {
      helm: {equal: 1},
      gauntlets: {equal: 1},
      chest: {equal: 1},
      legs: {equal: 1},
      classItem: {equal: 1},
    },
    variables: _.reduce(armorItems, (acc, item, index) => { 
      return {
        ...acc,
        [item.id]: castArmor(item)
      }
    }, {})
  }
}

function findItems(armorPieces = [], opts) {
  const model = buildModel(armorPieces, opts)
  const { feasible, result, ...solution } = solver.Solve(model)
  
  const items = _.reduce(_.toArray(solution), (acc, [k, v]) => {
    return v === 0 ? acc : [...acc, k]
  }, [])
  
  _.groupBy(solution, ((k, v) => ))
  return {
    feasible,
    items,
    statTotal: result,
  }
}
```

**Comment by bhollis** [comment]
I looked into this some more - it looks pretty easy to set up, but the tough part would be that the solutions generally yield a single optimal solution, while we display many top solutions that can arrive at the same or similar result in different ways. I'm not sure how to do that as just a straight lp solve.

**Comment by bhollis** [comment]
The other tough part is we're optimizing a nonlinear function - stat tier, not stat total.

**Comment by sitch** [comment]
Stat tier is just about as linear/simple/straight-forward as you could possibly have as its just `integer_div(sum(item), 10)`  -- nonlinear optimizations generally occur with dimensional smooth surfaces/manifolds, i.e. stuff that requires integrals/etc

Re: solving for multiple solutions, you can either:
1. Reframe the problem and optimize for a geometric covering, then just filter the collection with that
2. `reduce` over the items with a solution set as the `acc`, then just call the optimize fn each iteration, but use the existing solutions as non-matching constraints
3. Check for other tools that include this functionality out of the box
4. Request a feature from javascript-lp-solver
