### ISSUE TITLE
Scaled Stat Values for Single Stat Items

### ISSUE THREAD

**Issue by wein3967** [DestinyItemManager/DIM#511]
I've been updating my armor export script to include the new quality and stat improvement. This may or may not be a known issue, but single stat items don't show a reasonable number for the scaled stat value. I noticed that when looking at my Immolation Fists (single stat) the base value was 61, but the scaled value was 32. Turns out this occurs for every single stat armor item. Example file attached.
[SingleStatTest.xlsx](https://github.com/DestinyItemManager/DIM/files/250981/SingleStatTest.xlsx)

**Comment by bhollis** [comment]
Linking #515.

**Comment by JosephBono** [comment]
Issue #516 also touches on this - whatever we use for artifacts should be used here as well. 

My proposal is that the overall item Stat Quality be displayed out of the maximum stat (89 for Artifact, 112 for Boots, 122 for Chest, 82 for Gloves, 92 for Helmet, 50 for Ghost and Class Item), but in the item details the individual stats are shown as a percentage of the actual achievable stat for that piece of gear (half the cumulative stat for split stat Boots, Chest, Gloves, Helmets, Ghosts, and Class Items; 51 for Dis on Artifacts, 38 for Int and Strength on Artifacts; some TBD value for single stat items).

**Comment by SunburnedGoose** [comment]
Agree.

**Comment by kyleshay** [comment]
i believe this has been fixed. let me know if you'd like any other mods!
