### ISSUE TITLE
Add support / FAQ document

### ISSUE THREAD

**Issue by 48klocs** [DestinyItemManager/DIM#5115]
We have some helpful problem debugging/resolution steps pinned in our #support channel in Discord, but not everyone makes it in there.

We should extract them out to a document so we can point people to it (and amend it with more information).

**Comment by bhollis** [comment]
Here's the start of a wiki folks could fill out, starting with the desktop link advice: https://github.com/DestinyItemManager/DIM/wiki/Troubleshooting

**Comment by 48klocs** [comment]
I've put answers to a bunch of questions we see on Discord out there.

**Comment by bhollis** [comment]
Awesome, thanks!
