### ISSUE TITLE
Bug- is:reacquirable wrong about year 1 Eververse armor & masterworked armor

### ISSUE THREAD

**Issue by bresnick** [DestinyItemManager/DIM#5116]
I ran a search for "is:reacquirable"

Some armor that should be highlighted is not:
![image](https://user-images.githubusercontent.com/16613510/79187030-29c74a80-7de9-11ea-8acc-14203a6a23a9.png)

The following armor should be:
![image](https://user-images.githubusercontent.com/16613510/79187073-53807180-7de9-11ea-9fa5-2a55215c15df.png)

I believe the armor that is not being highlighted is either:
1) Eververse Year 1 armor (Optimacy sets, Omega Mechanos sets, Mihaylova's, Quiao's, etc.)
2) Masterworked (Heiro Camo set, etc.)

**Comment by bhollis** [comment]
Re-issues of armor are duplicated in the database.

This could be either:
https://data.destinysets.com/i/InventoryItem:2791527489
or 
https://data.destinysets.com/i/InventoryItem:2838060329

The first one (Armor 1.0) has a `collectibleHash` pointing to https://data.destinysets.com/i/InventoryItem:2791527489/Collectible:4126549934 - this indicates it's linked to a collectible.

See https://github.com/Bungie-net/api/issues/1088 for more details.

Can you actually pull the Armor 2.0 from collections?

**Comment by bresnick** [comment]
No, I can't pull Armor 2.0 items from collections.

But I did notice something odd... it seems like the API has trouble telling the difference between year 1 armor and reissued Armor 2.0 armor.

For example, all Shelter In Place armor (Vanguard Titan set originally in season 1, but since reissued in seasons 7 and 10, I believe) does weird things depending on which season it's from. Here are 3 different sets of arms:
![image](https://user-images.githubusercontent.com/16613510/81250631-715b8380-8fef-11ea-9628-b29f5c9091c9.png)

The game believes that two of them are from year 1 (One is actually from year 1 and pulled from collections, the other is from Season 7, I believe.):
![image](https://user-images.githubusercontent.com/16613510/81250687-93ed9c80-8fef-11ea-995f-28fadf3bed46.png)

But it thinks two of them (Seasons 7 and 10) are Armor 2.0:
![image](https://user-images.githubusercontent.com/16613510/81250761-c0a1b400-8fef-11ea-9a0d-bc36e1d15b67.png)
