### ISSUE TITLE
Install DIM

### ISSUE THREAD

**Issue by DLCGNinja** [DestinyItemManager/DIM#5119]
It doesn't work at all, i click it and nothing seems to happen. It used to work before i got a new driver but now its wont install. The last drive i had it on was wiped so there shouldn't be any previous downloads on it.

**Comment by delphiactual** [comment]
https://github.com/DestinyItemManager/DIM/wiki/Troubleshooting#did-you-install-dim-and-found-that-the-desktop-icon-has-disappeared
