### ISSUE TITLE
Candy Engrams being transfered.

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#512]
> I have a bug to report. Kinda. When gathering engrams to a single character the candy engrams from the festival of the lost get transferred too. I'm guessing that the program just searches for the word engram and transfers any item found to the requested character. Could this please be disabled for the candy engrams?

https://www.reddit.com/r/DestinyTheGame/comments/4i0949/dim_v36_updated_with_item_quality_and_engram/d2u7b0y?context=3

**Comment by bhollis** [comment]
lol

**Comment by bhollis** [comment]
Who still has those???

**Comment by Mulchman** [comment]
You're such a casual.

**Comment by bhollis** [comment]
I thought they all turned to rotten candy...
