### ISSUE TITLE
indicator item transfer window blocks transfer of others (mobile)

### ISSUE THREAD

**Issue by michabbb** [DestinyItemManager/DIM#5120]
when transferring an item the indicator window (with the spinning icon) lays over the char buttons, this blocks me from transferring another item in the meantime, so I am now always forced to way several seconds until the previous transfer has finished. in the past I was able to transfer several items without any waiting, because they got queued somehow and no Ui elements got blocked by any indicator windows. this might look nicer now, but it's usability got lost. I now need 20 seconds to transfer 3 items 😔 before that indicator window exist, I just started my transfers and the app took everything from the queue, did its job and I didn't have to wait for each item before transferring the next one.

I would be really really happy if the indicator window would be optional.

https://imgur.com/a/7FSyPoT

thanks a lot,
Micha

**Comment by bhollis** [comment]
You can just tap the notification to hide it.

**Comment by michabbb** [comment]
I noticed that, yeah... but anyway, it blocks the most important icons, so maybe you still can consider to add an option to the settings to make this optional. before that window exists, you were able to transfer fast and easily, now you have to do extra tapping and waiting. I fully understand the sense of "showing the user what's going on" and I also understand that on mobile there is not much place on the screen, but maybe there is a chance to show a spinner on top right (for example) instead of showing something that blocks the whole screen and prevent using the app. we all know that destiny is a game with a lot lot lot situations where you wait, like an idiot, wait wait wait.. but sometimes, for example, when you play pvp, and need 3 weapons, you get crazy, because you cannot transfer the second item because a indicator blocks a 4th of your screen 😔 tapping each time can work, but it's still extra tapping.
before, if I remember correctly, you only got a notification when a transfer failed, that made perfectly sense, because I only need to know when things failed. when everything works fine, I don't need anything that blocks me from using this great app 😏

**Comment by bhollis** [comment]
We already show a spinner on the top right of the screen, but people frequently didn't understand that we were transferring an item until it finished. I think for now you should tap the notification, and we'll keep iterating on the design to make it less obtrusive.

**Comment by michabbb** [comment]
thanks a lot for your understanding 👍
