### ISSUE TITLE
Reduce the size of the engram farming message.

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#514]
https://www.reddit.com/r/DestinyItemManager/comments/4i07tc/dim_v36_the_one_that_finally_landed/d2vf5gm?context=3

> Like the automatic transfer of engrams to the vault, but can we get that big image off the screen? Maybe something small on the left or right, but not in the middle of the all your stuff, unless you can hide it. Please.....
> PS. Keep up the great work,its simply amazing what your doing. Thank You

**Comment by bhollis** [comment]
I made it huge and obnoxious for a reason. Folks shouldn't be leaving it on all the time, (both because it hits Bungie services frequently, and without the normal protections for idle tabs, etc) and because it'll interfere with normal moves.

May I close this?

**Comment by SunburnedGoose** [comment]
I appreciate the sensitivity for the utilization of the API.  I'll relay back to the user.
