### ISSUE TITLE
Better weapon information (discussion task)

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#515]
Let's use this place to continue the discussion from #443. once we have made a decision we can close this issue and create new tasks as needed.

(start of original discussion was here: https://github.com/DestinyItemManager/DIM/pull/443#issuecomment-217482211)

Item's being discussed:

@delphiactual & @thesamprice 

> let the user decide the quality of the rolls per item type

@Mulchman 

> I think it's too subjective of a thing to put a number on.

@JosephBono

> If you are looking for ways to innovate in terms of weapon comparison, here are some ideas:
> - Calculating and displaying inventory size (including ammo capacity perks from armor)
> - Displaying how much ammo will be picked up from a Special/Heavy crate in PvP for a weapon
> - Displaying what the starting ammo will be for a Special Weapon in PvP
> - Allowing me to do a side by side comparison of all of my weapons of a certain type (e.g. show all Pulse Rifles, potentially grouped by impact/RoF archetype)
> - Calculate and display ideal Time To Kill for each weapon (source data for this may be gleanable from extrooper's TTK spreadsheet from Reddit. This would require frequent updates with each patch)

/u/suinoq from reddit also has some thoughts: 

> https://www.reddit.com/r/CruciblePlaybook/comments/4i1jpa/is_there_a_good_website_to_play_with_weapon_perks/d2vju1b

We do have a task for "compare duplicates" (#494)

But that also (partially) depends on "where are we going to put all of this information" (#491)

**Comment by kyleshay** [comment]
> Have 2+ of a thing? Rank them non-emotionally based on core metrics (range, key perks, etc.) that is user definable to some degree.
per @therarecommoner:

> Show attribute buff/nerf stats for each scope/barrel/perk as Reddit user here did for Grasp of Malok
https://www.reddit.com/r/CruciblePlaybook/comments/3pgnti/best_roll_grasp_of_malok_with_numbers_wall_of_text/?ref=search_posts

> User selects (and in doing so, ideally stores) their preferences in rank order 1-3 for each gun type

> DIM compares base stats of select weapon and determine closest to perfect roll per user inputs.

> Enables user a quick method to infuse, shard or keep.

**Comment by delphiactual** [comment]
Maybe take a look a mercules massive breakdown to figure out how to do this, or even invite him to this discussion... /u/mercules904 on reddit...

https://www.reddit.com/r/DestinyTheGame/comments/4hj3ne/merculess_massive_breakdown_of_massive_breakdowns/

**Comment by delphiactual** [comment]
More from /u/mercules904

https://www.reddit.com/r/DestinyTheGame/comments/55vnga/massive_breakdown_weapon_stats_spreadsheet/

**Comment by delphiactual** [comment]
https://www.reddit.com/r/DestinyTheGame/comments/5irtdj/all_weapons_by_archetype/

**Comment by delphiactual** [comment]
#1486

**Comment by rkingsla** [comment]
@delphiactual - Thanks for linking this to the right parent. I'll review these and provide any meaningful feedback. Good to see that the team is already thinking through this. Yep, subjective, and yep, every balancing patch has a major impact what was good and is now good. 

Two weeks ago my Shadow Price sucked and my Clever Dragon ruled (somewhat tongue in cheek), and on 2/14, that preference flipped on its head. ;)

**Comment by delphiactual** [comment]
Closed by #1646
