### ISSUE TITLE
modslot comparison changes depending on what season the loaded mod is from

### ISSUE THREAD

**Issue by paulv** [DestinyItemManager/DIM#5154]
Hi,

I've got a class item with a dawn modslot. When a worthy mod is loaded, the "Compare Items" feature shows comparisons to class items with worthy modslots, which I believe is incorrect. When the worthy mod is removed, "compare items" then shows comparisons to class items with dawn modslots.

Using the modslot search keyword does the right thing. I have not tried this with other armor pieces or with class items with modslots from other seasons.

Paul

**Comment by sundevour** [comment]
hi, this should be resolved in beta (beta.destinyitemmanager.com) now, and make its way to main (app.destinyitemmanager.com) within 2 days. please let me know if everything's working for you as it should be
