### ISSUE TITLE
Norton Security - Not allowing Steam login to DiM

### ISSUE THREAD

**Issue by bahnshaps** [DestinyItemManager/DIM#5155]
Cannot load up and use DIM via Chrome or via the APP as the login in section from steam gets blocked.

How can I get around this? PS I could use it find before, but it logged me out randomly.

![image](https://user-images.githubusercontent.com/64335383/80292695-1d7baf80-8750-11ea-8d6a-de2f4ae49c85.png)

**Comment by delphiactual** [comment]
https://community.norton.com/en/forums/steam-not-working-norton
