### ISSUE TITLE
Show Your Colors Triumph progress is per character

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#5159]
https://data.destinysets.com/i/Record:3996842932

Possibly `intervalInfo.isIntervalVersionedFromNormalRecord`:`false`

**Comment by dazedcrazy** [comment]
Was just coming to say it shows this in game
![image](https://user-images.githubusercontent.com/9027988/80751713-39050280-8b22-11ea-9281-8834f78903f2.png)
But this on the site
![image](https://user-images.githubusercontent.com/9027988/80751780-4b7f3c00-8b22-11ea-983a-ba642f8965c1.png)

**Comment by delphiactual** [comment]
Guardian Games is over, and this no longer matters
