### ISSUE TITLE
Displayed Aim Assist values do not account for scope modifications (Equip Speed also likely impacted)

### ISSUE THREAD

**Issue by JosephBono** [DestinyItemManager/DIM#516]
I noticed this when looking at two 1000-Yard Stares I have, one of which has the Shortgaze SLH10 scope selected and the other of which has the Longview SLR10 scope equipped. They both are shown to have a AA value of 56, which is the base AA value for the 1000-Yard Stare returned by the Bungie API, not the actual value of AA with the scope modifications taken into account (which would be 56 for the Shortgaze SLH10 and 61 for the Longview SLR10). This is inconsistent with the way DIM handles the stats exposed by the in game UI (RoF, Impact, Range, Stability, Reload) which are modified by the perks selected (e.g. the Shortgaze SLH 10 one has a Range stat of 68 while the Longview SLR10 one has a Range stat of 70). I would imagine that this holds true for the Equip Speed stat as well.

![image](https://cloud.githubusercontent.com/assets/10524305/15085573/feb5da40-138f-11e6-877d-4254052a0dde.png)

![image](https://cloud.githubusercontent.com/assets/10524305/15085577/0421b828-1390-11e6-925c-3d52d611834d.png)

This issue is likely due to the way DIM generates the stat values for guns - I would imagine that these values are coming directly from the Bungie API, which, in turn, is giving you the final values for the "in game" stats but only the base values for the "hidden" stats. Fixing this would entail calculating the final value for AA and Equip Speed using the base values and the bonuses/penalties generated by scopes, barrel mods, and perks, some of which are unknown or only theorized. If this is something you want to do I can round up a bunch of that data for you (off the top of my head the Sniper scope AA values are here: https://www.reddit.com/r/CruciblePlaybook/comments/4g56e0/sniper_scope_aa_values_post_patch_22/).

I'm mostly raising this issue to make sure the DIM team is aware of this data gap - fixing it adds to the complexity of the project and incurs a maintenance cost of having to update scope/mod/perk values as Bungie updates the game, instead of solely relying on data returned from the Bungie API, and so I understand if the ROI on correcting this doesn't meet the bar and you choose to Won't Fix this issue.

**Comment by kyleshay** [comment]
Thanks for the awesome report @JosephBono, though I think that scopes are only part of it. For example, quickdraw/snapshot also modify Equip Speed, and there are some AA perks usually in column 2 that also might change the AA.

We did already have an issue open for this (https://github.com/DestinyItemManager/DIM/issues/423) but I think I'll close that one in favor of this once since we have some more information here. 

Not 100% sure if this site has been updated with post-TTK values.

>  http://destinyscopes.com/

**Comment by JosephBono** [comment]
The site http://destinyscopes.com/ has only been partially updated with post-TTK values :(

I agree, there are other perks that affect Equip speed. As far as I know, only Barrel Mods and Scopes can affect Aim Assist. The perk Hidden Hand has had a lot of investigation into it and, I believe has been shown to not directly affect the Aim Assist stat, but instead to affect some of the sub stats that Aim Assist seems to increase/decrease.

I'm going to dig into my notes and try to pull all of the relevant perks/mods/scopes and list them here, since this seems like an area we might invest in.

**Comment by JosephBono** [comment]
This comment is where I am going to edit in the list of all perks, scopes, and barrel mods that affect the Equip Speed and Aim Assist stat.

##Sniper Scopes
Name | Equip Speed | Aim Assist
------------------------------------------
EagleEye SLR20 | ? | 5
SightSys SLS20 | ? | 7
LongView SLR20 | ? | 7
Hawkeye SLR15 | ? | 3
TacSys SLS15 | ? | 0
WildHawk SLS20 | ? | 0
LongView SLR10 | ? | 3
ShortGaze SLH10 | ? | 0
ViewTac SLH20 | ? | 0
Ambush SLH25 | ? | -25
ATD Raptor | ? | 0
ATA Scout | ? | 0
ATB Long Range | ? | 0
Yepaki SS2 | ? | 0
Condor SS2 | ? | 0
Corvo SS2 | ? | 0
Faucon SS1 | ? | 0
Aquila SS4 | ? | 0


##Other Scopes
Name | Equip Speed | Aim Assist
------------------------------------------


##Barrel Mods
Name | Equip Speed | Aim Assist
------------------------------------------


##Perks
Name | Equip Speed | Aim Assist
------------------------------------------

**Comment by kyleshay** [comment]
awesome work starting those tables @JosephBono!! thank you!

**Comment by kyleshay** [comment]
Hopefully this is fixed in D2
