### ISSUE TITLE
Since update 6.9.0, if you use your own Wishlist, the rolls will not be saved or remembered

### ISSUE THREAD

**Issue by ColonelPanda** [DestinyItemManager/DIM#5170]
Loading in your own custom wishlist doesnt show any of the rolls, and it seems that it doesnt save it either
![Loading in](https://i.gyazo.com/1abac6419c39457cb195ec089bcf5901.png)
![None are showing](https://i.gyazo.com/5c77e2166a0778cd8c79f1662d2500ae.png)
![Going back into settings afterwards shows that it hasnt saved the rolls](https://i.gyazo.com/40cc956b8700b1c34449d3941da1d7da.png)

This issue occurs on both the beta version as well as the base app version

**Comment by bhollis** [comment]
Thanks for the report - I'll have a fix on beta soon. I'd recommend hosting your wish list on GitHub though, both to make it easier to keep track of and to enable auto-update.
