### ISSUE TITLE
[Enhancement] Move unequipped weapons/armor to vault

### ISSUE THREAD

**Issue by JessMcAnally** [DestinyItemManager/DIM#5175]
When it comes to inventory management, I love to move everything to the vault before i start marking things as trash/keep/etc. It would be cool to be able to click the dropdown on a character, and click something like "move unequipped to vault". Another option could be to click dropdown on vault and click something like "move unequipped to vault".

**Comment by delphiactual** [comment]
Or `is:oncurrentchar is:haspower not:equipped` character drop-down -> move search...

**Comment by JessMcAnally** [comment]
looks like that works! added not:invault to the end to be more efficient
