### ISSUE TITLE
WishList not showing ratings on PC

### ISSUE THREAD

**Issue by DrFranks-n-Stein** [DestinyItemManager/DIM#5176]
Here is the copy/paste of devtool from Chrome (using the 'installed' desktop icon):

sync.service.ts:49 Sync: Storage will not be cleared except by explicit user action.
sync.service.ts:57 Sync: DIM is using 24.42 MB total out of 139.06 GB in storage quota (0%).
Index.tsx:68 DIM v6.9.0 (release) - Please report any errors to https://www.github.com/DestinyItemManager/DIM/issues
reducer.ts:99 Load accounts from IDB
actions.ts:118 globalSettings Object
5A cookie associated with a cross-site resource at <URL> was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at <URL> and <URL>.
actions.ts:395 [importLegacyData] Don't need to import, this legacy data has already imported
reducer.ts:53 Uncaught (in promise) TypeError: Cannot read property 'wishListAndInfo' of undefined
    at g (reducer.ts:53)
    at redux.js:459
    at reducers.ts:53
    at g (redux.js:213)
    at index.js:11
    at dispatch (redux.js:638)
    at wishlist-fetch.ts:117
    at async https:/app.destinyitemmanager.com/main-cdbcd1.js?__WB_REVISION__=ff2024cf544d41b6f8741f6ace9922c9:1
actions.ts:80 Saving profile data to IDB
manifest-service-json.ts:169 Load manifest: 9410.552001953125ms
d2-stores.ts:258 Process inventory: 1511ms
d2-stores.ts:262 Inventory state update: 3543.000244140625ms
inventory:1 [Intervention] An <img> element was lazyloaded with loading=lazy, but had no dimensions specified. Specifying dimensions improves performance. See https://crbug.com/954323
destiny-account.ts:212 Error getting D1 characters for Object Error: Bungie.net was too slow to respond.
    at p (bungie-service-helper.ts:98)
    at async m (bungie-service-helper.ts:43)
    at async d (destiny1-api.ts:23)
    at async g (destiny-account.ts:192)
    at async Promise.all (index 1)
    at async https:/app.destinyitemmanager.com/main-cdbcd1.js?__WB_REVISION__=ff2024cf544d41b6f8741f6ace9922c9:1
    at async f (destiny-account.ts:101)
    at async https:/app.destinyitemmanager.com/main-cdbcd1.js?__WB_REVISION__=ff2024cf544d41b6f8741f6ace9922c9:1

**Comment by delphiactual** [comment]
fixed in beta

**Comment by bhollis** [comment]
No, this is a new issue.

**Comment by bhollis** [comment]
Sentry issue: [DIM-H5V](https://sentry.io/organizations/destiny-item-manager/issues/1644665972/?referrer=github_plugin)
