### ISSUE TITLE
Feature Request: Highlight common quest (steps) with friends

### ISSUE THREAD

**Issue by kencieszykowski** [DestinyItemManager/DIM#5177]
Fantastic work on this.  I just discovered DIM and can't wait to leverage it in the coming weeks.

One thing that my friends and I have been eager to find is a tool that does this;

When we log on different people focus on different quest steps.  It would be wonderful to be able to scan the quest log of two players and see the overlap between the two.  Comparing with one specific person would be great-- but ideally a smaller group.  

Or if anyone knows of an existing tool like this, that'd be great.  Trying to figure out what steps you are on via the interface can be a lesson in patience-- and this would really make grinding/questing pretty efficient to be able to see this.

Thanks!

**Comment by bhollis** [comment]
Love this idea but it's probably best on another site/tool that uses the API (D2Checklist?).
