### ISSUE TITLE
Traction isn't included in the mobility stat on Loadout Optimizer anymore

### ISSUE THREAD

**Issue by KAdams91** [DestinyItemManager/DIM#5179]
It seems like since last update, the +5 added to mobility from the Traction mod isn't being applied anymore. I have a Warlock build that has 60 mobility in game but only shows as 55 mobility in DIM with the same exact gear.

**Comment by ryan-rushton** [comment]
@bhollis this will be fixed in that PR you merged of mine the other day

**Comment by delphiactual** [comment]
#5173
