### ISSUE TITLE
Maximum Call Stack error while transfering items.

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#518]
Been getting intermittent errors when moving items.  I'll get more data next time it happens.

https://www.reddit.com/r/DestinyItemManager/comments/4i07tc/dim_v36_the_one_that_finally_landed/d2we3on?context=3

**Comment by SunburnedGoose** [comment]
https://www.reddit.com/r/DestinyItemManager/comments/4ib7k9/dim_v360_maximum_call_stack_size_exceeded_bug/

> 100

 Heavy synth in vault. Trying to transfer them to my warlock. Always get the error "Maximum call stack size exceeded". Tried the drag/drop, click and partial transfer methods. None works.

**Comment by bhollis** [comment]
This is another one that I can't reproduce no matter how hard I try. I don't have 100 heavy synths though...

**Comment by JosephBono** [comment]
I encountered this error when I had all Consumables slots filled in game AND I had an expired Elder Cipher that showed up erroneously as a consumable. I will try to replicate it tonight.
________________________________

**Comment by SunburnedGoose** [comment]
That's good data.

**Comment by bhollis** [comment]
Oh, that is interesting. I'm also testing `dev`, which has my changes to correctly categorize everything.

**Comment by JosephBono** [comment]
Could not get it to repro by filling in all my consumables from vault to character, so either that isn't it or there's a confounding factor

Date: Sat, 7 May 2016 21:07:54 -0700

**Comment by SunburnedGoose** [comment]
I have an Expired Elder Sigil.  I filled my consumables using Gear Manager so that it's 20/20.  This makes DIM 21/20.  

I move an item into the consumable from another character.  

DIM tries to move an item away from the character to the vault, but in the screenshot, it's looping, and creates the error.

![screen shot 2016-05-08 at 1 43 32 am](https://cloud.githubusercontent.com/assets/984608/15096464/52fcf6f4-14be-11e6-8adf-e2e16543cd74.png)

**Comment by SunburnedGoose** [comment]
When Consumables is overfull, 

https://github.com/DestinyItemManager/DIM/blob/dev/app/scripts/services/dimStoreService.factory.js#L85-L90

this code will return a -1 when the app was expecting a 0 because even if there was no space, DIM things its 21/20 which is 20 - 21 = -1.

Problem with this is we're subtracting -1 from 0 which gives us 1 on this line

https://github.com/DestinyItemManager/DIM/blob/dev/app/scripts/services/dimItemService.factory.js#L426

So DIM thinks it has to move items and it loops forever...  

Changing the function spaceLeftForItem() to always return >= 0 fixes the issue.

**Comment by bhollis** [comment]
I'll add that guard.

Does this still happen on the dev branch? Digits should be in the correct
place.

**Comment by SunburnedGoose** [comment]
I'll check in a few.
