### ISSUE TITLE
Subclasses stuck with Loadouts

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#519]
https://www.reddit.com/r/DestinyTheGame/comments/4i0949/dim_v36_updated_with_item_quality_and_engram/d2wmoyd?context=3

> I am still having issues with the wrong subclass being loaded when I select load-outs.

> I select my PvP loadout (Gunslinger) and Bladedance comes up.
> I select my PvE loadout (Nightstalker) and Gunslinger comes up.
> I have 3 Hunters, so not sure if specific to someone like me, but this has only started happening a month or so ago.
> I have tried deleting the associated subclass, and re-adding the one I want, but still does not work.
> I posted about it in the dedicated Reddit for DIM, but never got an answer.

**Comment by bhollis** [comment]
I'd love some more help in making this happen, so I can fix it. So far I've tried making loadouts with various subclasses, but it always applies the right one!

**Comment by bhollis** [comment]
Please reopen if you figure out how to reproduce this.
