### ISSUE TITLE
Feature Suggestion: SEASONAL MOD DUPES

### ISSUE THREAD

**Issue by joe7dust** [DestinyItemManager/DIM#5190]
Instead of going down the list of all seasons like Season:=5 , Season:=8 etc you could add a search function similar to Is:dupe that intelligently shows which armor is redundant. 

Example: 

"season:dupe basestat:total:<50" would show you armor that accepts the same seasonal mods and has (likely) poor stats. I estimate I have dozens of these that I kept around simply for the ability to use certain mods, and they've since consolidated some of these so there is a lot of room to be had.

**Comment by bhollis** [comment]
Why not just search `modslot:worthy basestat:total:<50` to do that?

**Comment by bhollis** [comment]
Or even `holdsmod:worthy basestat:total:<50`

**Comment by joe7dust** [comment]
There might be a word for the seasons I wanted but numerical ranges didn't seem to work such as season:4-5 or season:>7<9. Maybe there's an existing Boolean whereby I could have done "season:4 OR season:5" or something... All a bit overly complex to the end user compared to the existing is:dupe.

What are the words for season 7-9, season 8-10 and season 9-11? Just looking at your example wouldn't that effectively be season:10 only? There's more than one type of mod slot that takes worthy. I've seen 8-10 and 9-11.

**Comment by bhollis** [comment]
In my example, `holdsmod:worthy` would match any item that has Dawn or Worthy mod slots. `holdsmod:dawn` would match any item with Worthy, Dawn, or Undying mod slots.

If you really want to select by season instead of mod compatibility, try `season:>=7 season:<=9`

**Comment by bhollis** [comment]
I'm going to close this as the requested features already exist.

**Comment by joe7dust** [comment]
An elegant and simple command like is:dupe doesn't exist actually for this. And that example matches by name only. 

Typing "season:=8 season:=9 season:10" for one search is pretty clunky.
