### ISSUE TITLE
D1 Loadout Optimizer does not properly calculate The Taken King exotic class items

### ISSUE THREAD

**Issue by jbccollins** [DestinyItemManager/DIM#5191]
The exotic class items that come with the special edition of The Taken King are unlike any other class item. They have a fixed roll of 47 intellect with the option of 10 discipline or 10 strength. DIM says that the best I can get when using these class items is a 5/5/1 split. This is not true.

The three class items affected by this are "Nightstalker Cloak", "Mark of the Sunforged" and "Stormcaller Bond".

<img width="735" alt="Screen Shot 2020-05-16 at 5 18 34 PM" src="https://user-images.githubusercontent.com/8915552/82130481-c2126f80-9799-11ea-8bb2-de9180ef5e15.png">

![IMG_0862](https://user-images.githubusercontent.com/8915552/82130527-377e4000-979a-11ea-91cd-8745f1fcf106.JPG)

**Comment by jbccollins** [comment]
This is my quick and dirty fix that I'm using locally to work around this. The scaling code was a little much for me to try and step through right now but that's probably a better location for the changes that will fix this. Right now the scaling thinks that the "scaled" intellect is 23 rather than the 47 that it is fixed at.

<img width="748" alt="Screen Shot 2020-05-16 at 6 34 16 PM" src="https://user-images.githubusercontent.com/8915552/82131536-20dce680-97a4-11ea-9fe5-2817da3d0b26.png">

<img width="602" alt="Screen Shot 2020-05-16 at 6 36 50 PM" src="https://user-images.githubusercontent.com/8915552/82131542-41a53c00-97a4-11ea-8fbf-d35b804fe3ac.png">

**Comment by bhollis** [comment]
Seems like a reasonable patch. Could you send a PR?

**Comment by jbccollins** [comment]
PR is up
