### ISSUE TITLE
MasterWorded item BaseStats should be +2 on every pice of stats in Organizer.

### ISSUE THREAD

**Issue by tanglueyi** [DestinyItemManager/DIM#5208]
![Group_14](https://user-images.githubusercontent.com/3315564/82401979-d4d4bf00-9a8d-11ea-8ca9-4e8b5a2b36ff.jpg)

**Comment by bhollis** [comment]
Base stats means stats not counting mods or masterwork.

**Comment by tanglueyi** [comment]
> Base stats means stats not counting mods or masterwork. 

It should counting masterwork,when masterworked,the +2 stat has merged in every pice of them permanently.

**Comment by bhollis** [comment]
That's not how we've chosen to define "base stats". We define base stats as the stats not counting mods or masterwork, since any piece of armor can be masterworked or modded. Thus, the base stats tell you how good the roll is.

**Comment by tanglueyi** [comment]
I think we can take it a step closer, I usually use this tool to filter out gears of CUSTOM TOTAL (Mobility + Recovery + Discipline) > 36, and if you follow your calculations, there's a chance that a Masterworked gear will result in a gear that's less than a none-Masterworded one. So, giving us the right to choose, adding an option allows the "+2 stats" to be added to the calculation.
