### ISSUE TITLE
Display Faction Progress for each Character

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#521]
Users have been asking for faction progression.  Can we feed them?

**Comment by bhollis** [comment]
Sure. Where should we put that?

My vote would actually be for a big dialog showing rep for each character.

**Comment by SunburnedGoose** [comment]
I like the idea of being able to view and compare characters to see where best to spend your marks for example, or decrypt engrams.

**Comment by kyleshay** [comment]
linking #254, has some info about the api call needed.

**Comment by kyleshay** [comment]
also linking #145, since it would use the same endpoint

**Comment by kyleshay** [comment]
in-game there is a gear page, as well as a separate page for faction ranks, mission, bounties.

maybe we could create another state in DIM that will keep the columns as is, but instead will just display other things?

imagining something similar to how http://destinystatus.com/ works... except if you click the 'reputation tab' it toggles to the rep view for everyone. maybe a button at the top to toggle (similar to going to the new armor comparison view?)

**Comment by bhollis** [comment]
Interesting, like an overlay almost? I could see that!

Or we could use the "sidebar" idea we've tossed around for item details.

**Comment by bhollis** [comment]
Closing in favor of #533
