### ISSUE TITLE
Loadout Manager - Armor 2.0 are INCLUDED in stat tier calculations

### ISSUE THREAD

**Issue by OcXs3** [DestinyItemManager/DIM#5216]
I had the feeling there was something wrong and I thought it was about masterworked items but it's about armor mod 2.0.

At the moment, Armor 2.0 are INCLUDED in stat tier calculations

**Comment by ryan-rushton** [comment]
Hey @OcXs3, can you give me a little more details in what you are seeing? I ask as I don't actually have all the seasonal mods myself so its's possibly an outlier I may not be able to see. So questions,

1. Are you seeing this happen with the general mods, i.e. the recovery, mobility and other mods that go in the first slot.
2. Are you seeing it with slot dependant mods, i.e. traction
3. Are you seeing it with seasonal mods that effect stats, if so which ones.

I will do some testing around this tonight as well and see if I can get to the bottom of it.

**Comment by OcXs3** [comment]
Hi @ryan-rushton 

Did you already fix it? I tried several tests with the general mods then I realized that it was gone. So, in my case, I had 5x +10 Mobility in the first slots + the +20 Mobility in the season slot (activated) the Loadout Manager showed the total in the Mobility column from my equipped loadout. I have no other specific case that I remember (because I have been unable to identify what was wrong).

**Comment by ryan-rushton** [comment]
Hey @OcXs3, 

A couple of things have changed in the last week as I have been trying to make the mods align more closely to what we have in game, so it is possible that was a side effect of that. We have isolated it until it is in a more complete state, so the old functionality should be completely restored next week until its ready to go.

I will give it a test this weekend to see if I can spot anything going on anyways.

**Comment by OcXs3** [comment]
Hi @ryan-rushton 

If I see any problem with this issue I'll come back to you asap
