### ISSUE TITLE
Reissued Armor showing as Season 1 in Organizer

### ISSUE THREAD

**Issue by GhostPirate101** [DestinyItemManager/DIM#5238]
Appreciate this may be an issue with the API rather than DIM (or maybe my own faulty assumptions about sunsetting!), but I came up with a search query for finding legendary gear being sunset prior to Season 12 and it is showing the reissued world drop armour as Season 1, even though it has Dawn or Worthy mod slots.

Query used:
`is:legendary is:haspower -source:lastwish -source:garden season:<9`

**Comment by GhostPirate101** [comment]
Apologies - I'm using the current beta version v6.12.0.
[destinyArmor.csv.txt](https://github.com/DestinyItemManager/DIM/files/4678206/destinyArmor.csv.txt)

"Simulator Hood" is an example of an item labelled as "Season 1" with a Worthy mod slot.

**Comment by delphiactual** [comment]
https://data.destinysets.com/i/InventoryItem:2538410394

the icon overlay indicates that it is correct in identifying as season 1

**Comment by delphiactual** [comment]
sunsetting will not be based on 'season' but rather an actual value in the API. season is all manually generated by https://github.com/DestinyItemManager/d2-additional-info and will only return the value based on which icon overlay it is assigned.

**Comment by bhollis** [comment]
https://destinyitemmanager.fandom.com/wiki/Item_Sunsetting
