### ISSUE TITLE
inconsistent perk values

### ISSUE THREAD

**Issue by cskujbus** [DestinyItemManager/DIM#5242]
Probably I miss something about how perk values are calculated, but the same perks show different values on different instances of the same weapon.
For example I have 3 Dukes with Ricochet Rounds with the following values:

- +5 range, +9 stability
- +4 range, +9 stability
- +4 range, +8 stability

light.gg shows +5 range, +10 stability for this perk. Anyone knows where these values are coming from? I also noticed that sometimes the RR perk name is followed by (stability) or (range) or nothing.

DIM 6.12.0,
Firefox and other Chromium based browser
Windows 10 LTSC

**Comment by delphiactual** [comment]
https://github.com/DestinyItemManager/DIM/wiki/DIM's-New-Stat-Calculations
