### ISSUE TITLE
D1 Fusion Rifle charge rate is shown with "ms" after it

### ISSUE THREAD

**Issue by jbccollins** [DestinyItemManager/DIM#5244]
**What version of DIM are you using?**
6.12.0

**What Browser and OS are you using?**
Chrome on macOS 10.14.6

**Describe the bug and how to make it happen**
Click on a Fusion Rifle in the D1 inventory and see the "ms" text in the tooltip

<img width="426" alt="Screen Shot 2020-05-22 at 10 12 13 AM" src="https://user-images.githubusercontent.com/8915552/83201961-9df94b80-a114-11ea-938a-23031be9c8d1.png">

I assume "ms" means "milliseconds" here. No D1 Fusion Rifle charges that fast tho. Is this a D2 thing that is affecting the D1 inventory tooltips?

**Comment by bhollis** [comment]
Yeah, I’ll need to make it conditional on D2. They made the charge stat actually meaningful in D2 and they share a stat hash.
