### ISSUE TITLE
Different source information in CSV export

### ISSUE THREAD

**Issue by EckiSausDO** [DestinyItemManager/DIM#5247]
**What version of DIM are you using?**
Version 6.12.0.7151 (beta), built on 29.5.2020, 12:42:36

**What Browser and OS are you using?**
Windows 10; Google Chrome Version 81.0.4044.138; DIM beta as app

**Describe the bug and how to make it happen**
In DIM items can be filtered by source (e.g. source:eow to highlight items from the Eater of Worlds raid).
For items from activities related to Emperor Calus there are these sources for filtering:

- leviathan
- eow
- sos
- menagerie
- crownofsorrow
and
- calus (also highlights all of the above)

When exporting my weapons to a CSV their only source information now becomes "calus", making it impossible to differentiate if they originated from a (and which) raid or the menagerie.

My only "Shadow's Gauntlets" (Armor 2.0) have no source at all, neither in DIM nor a CSV armor export even though they originate from the "Crown of Sorrow" raid.

My "Shadow of Earth Shell" however has in both DIM and the CSV export the source "crownofsorrow".

**Include devtools console logs**
If you can, open the devtools console (ctrl+shift+J on PC and cmd+option+J on Mac) and paste what you see in the window that pops up:

```
Paste console logs here
```

**Comment by delphiactual** [comment]
I'll see what we can do... No promises as this data is already heavily massaged
