### ISSUE TITLE
extra cruxes while moving between 3rd character and vault

### ISSUE THREAD

**Issue by cotto** [DestinyItemManager/DIM#525]
When moving my Crux of Crota between characters, it doesn't appear to be removed from DIM's display of my vault or my third character.  This means that every time I move the Crux around, an extra Crux ends up in the vault and/or my third character until I refresh.  This happens once for each time I move the Crux.  Curiously, the Crux is correctly removed from my first and second character.

This is obviously a minor bug that's easy to work around, but it's also surprising.  I tried to debug it but am new to Chrome extension debugging and didn't get too far.  It seems to have something to do with the Crux-in-transit's item.index not matching the item.index of the Crux in the vault or 3rd character.

**Comment by JosephBono** [comment]
Likely related to issues #79 & #506

**Comment by bhollis** [comment]
Did this get fixed with the latest release?

**Comment by kyleshay** [comment]
If you're still seeing duplicate cruxes please let us know! Closing for now.
