### ISSUE TITLE
Strings do not match between `Create Loadout` and `Vault Organizer`

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#5255]
![2](https://user-images.githubusercontent.com/4798491/83353459-f9dbf400-a30f-11ea-92f7-9c3267c90961.png)
![1](https://user-images.githubusercontent.com/4798491/83353460-fa748a80-a30f-11ea-8310-b9726352bafd.png)

**Comment by bhollis** [comment]
One is sourced from manifest (Organizer) and one from translations I'm guessing.

**Comment by bhollis** [comment]
Looks like loadouts uses bucket definitions, while organizer uses item category definitions.
