### ISSUE TITLE
Stat quality in excess of 100% for Int/Disc and Int only artifacts in BETA (v3.6.0.17144)

### ISSUE THREAD

**Issue by JosephBono** [DestinyItemManager/DIM#526]
It looks like calculation of stat quality for these artifacts is being done incorrectly. This is a regression that appeared today, and probably in the last few hours. This is impacting all Int/Dis and Int only artifacts I have. It does not appear to affect other artifacts

![image](https://cloud.githubusercontent.com/assets/10524305/15173821/1c1d772e-1713-11e6-8f55-93487bcb37fc.png)

**Comment by kyleshay** [comment]
correct int/dis are technically bugged artifacts. the dis part of it can roll 13 points higher than int or str. but only on int/dis artifacts. we have two options.. one is to show > 100% for int/dis artifacts, or we can detect if the artifact is int/dis, and then compare dis to the base of 51 instead of a base of 38.

If we do that though, it is technically right, but then artifacts that are int/str might actually have a higher percentage than int/dis artifacts... 

does that make sense?

**Comment by JosephBono** [comment]
I disagree that Int/Dis Artifacts are bugged - they have different stat maximums than other artifacts, but we don't know whether that is intentional or not. They do have the stat values they claim to have and we don't have any indication from Bungie that those values are changing, so I think of labeling them as bugged as incorrect or at a minimum a semantic red herring.

The reality is that different Artifacts have different stat maximums - single stat Artifacts have the smallest max, Int/Str and Dis/Str have the next largest, and Int/Disc have the largest, and we need to decide how to handle that. IMHO, how to handle these cases really should depend on the customer use case. 

I believe that customers are using the Stat Quality score as a way to compare items and decide which ones to use and upgrade. I think this is the 90+% use case. If this is true, we want to make sure that any artifact that has a higher combined stat score when upgraded to 335 light will also display a higher stat quality than an artifact that will have a lower stat score when upgraded. I believe this is consistent with your feelings (given that you champion option 1 or 3).

I specifically dislike options 1 and 3 in that they do not set the correct expectation for users - either users will see stat qualities over 100% and won't trust the product (and won't know what the true max is), or they will believe that their perfect or near perfect Artifact is worse than it is, and will potentially spend time trying to get a "perfect roll" that is actually unobtainable. 

How feasible would it be to calculate the individual stats against the highest value that they could roll (e.g. 38 for Int and Str, and 51 for Dis, for split stat artifacts) but show the overall stat quality as the sum of the two stats divided by 89? This way the user would be able to accurately decide which Artifact to improve upon, but the individual stat scores would be accurate. There is potential for customer confusion when specifically looking at Int/Str artifacts, since the average of the two stats will never equal teh overall stat quality, but there is going to be some customer confusion in any implementation (unless we add explanatory UI), and this is the least impactful confusion.

**Comment by JosephBono** [comment]
BTW, I appreciate how responsive everyone in this project is and how open you all are to having discussions about features.

**Comment by SunburnedGoose** [comment]
I'm fine with the last paragraph.  Only issue is should we discourage users to look for int/str or dis/str artifacts?  All of those items will be marked as inferior since they technically are so to the 'god' roll int/dis on artifacts.  I'll have to look at our statistics and see what the T12 users are using for their artifacts.

**Comment by JosephBono** [comment]
I would be shocked if more than 5% of T12 users had non-Int/Dis artifacts. If you use an Int/Dis artifact you only need to hit 720 out of 743 possible stat points, versus 720 out of 730 for a non-Int/Dis artifact - using an Int/Dis artifact gives you 130% more margin for error.

**Comment by JosephBono** [comment]
Looking at data is super good though - would definitely reconsider my stance if the data showed significant non-Int/Dis usage among T12 users

**Comment by SunburnedGoose** [comment]
Looking at the data, there are no characters that have equipped T12 builds without int/dis artifacts.  At the moment, there is no other option.

**Comment by kyleshay** [comment]
closed per #555
