### ISSUE TITLE
Items (armor) from Crown of Sorrow does not get highlighted with the "source:" filter

### ISSUE THREAD

**Issue by IlMollaz** [DestinyItemManager/DIM#5263]
**What version of DIM are you using?**
The version is Version 6.13.2.7189 (beta). The DIM icon is blue.
I tried to check also on the browser with the Version 6.13.2 (release) (orange icon)

**What Browser and OS are you using?**
My OS is Windows10 and the Browser is Chrome.

**Describe the bug and how to make it happen**
The bug does not "highlight", search correctly the armor that comes from the Raid Crown of Sorrow, see the image attached.
It does highlight just the emblem that comes from it.
Also the counter is buggy since it seems that doesn't count something
![Immagine](https://user-images.githubusercontent.com/66443443/83809679-2cdb0a80-a6b7-11ea-8c33-5acfa73662b6.png)

```
PS: Don't mind the mess in my vault
```

**Comment by delphiactual** [comment]
What are the armors you have highlighted in your picture so I can debug this in d2ai

**Comment by IlMollaz** [comment]
I have highlighted (thanks Paint lol) the "Penumbral Bond", the "Shadow's Boots" and the "Shadow's Gloves", all for the Warlock class.
I don't know if also other pieces of the armor have this problem and/or other classes armor
