### ISSUE TITLE
Do not grey out the inventories of any faction vendors in D1

### ISSUE THREAD

**Issue by jbccollins** [DestinyItemManager/DIM#5264]
Currently DIM will grey out the inventory of a faction vendor when none of your characters have that faction allegiance. This is an annoyance when checking faction vendors using dim for high stat rolls. Given that it's so easy to switch your faction allegiance this indication of allegiance is less than ideal imo. Can we instead just put some sort of icon next to the vendor name or find some other way to indicate this that does not involve greying out the inventory? 
![INVENTORY](https://user-images.githubusercontent.com/8915552/83825423-4d02cd80-a6a7-11ea-9fcd-6a883444420a.png)

**Comment by bhollis** [comment]
They’re greyed out because the API is telling us you can’t buy those items - we don’t know specifically that it’s because of faction alignment besides the localized reason string. I think it’s unlikely that we’ll do anything special for this.

**Comment by jbccollins** [comment]
:( Is it not true that the only reason why the API would be telling you that you cannot buy those items is because you do not have that faction allegiance?

**Comment by bhollis** [comment]
No, there are a bunch of reasons things can be un-purchaseable.
