### ISSUE TITLE
The client_id is always undefined when skip to https://www.bungie.net/en/OAuth/Authorize

### ISSUE THREAD

**Issue by nitudoudou** [DestinyItemManager/DIM#5265]
**What version of DIM are you using?**
The latest version.

**What Browser and OS are you using?**
Chrome 

I want to deploy dim on cloud server for myself.After I build-release and move dist folder to server,I can open the page of index,but when I want to login my account ,I find the client_id is undefind when the page skip to https://www.bungie.net/en/OAuth/Authorize.Am I missing the file of .env?How do I config it?
Tks.

**Comment by bhollis** [comment]
I'm sorry, we don't support deploying DIM yourself.
