### ISSUE TITLE
Share current loadout/build via link

### ISSUE THREAD

**Issue by 22samurai** [DestinyItemManager/DIM#5273]
**Proposed Change**

Easily share your builds with others.  Share a link that holds all your current build data, which includes equipped weapons, armor, mods, exotics, all subclass settings info. 

Get a link to that build by clicking “share this build.”  The dialog gives you the link and an optional description panel where you can write directions on how to use the build effectively (or a YouTube link to show it in action).

Opening the link takes you to a single-page preview, with all perks and mods displayed in “armor order” - helmet to boots, and the selected perks of guns, the subclass data, and notes, all in an easy-to-read and follow format. 

From there you can request DIM to equip your character as close as possible.  Options to match would include “match only mods and exotics”, “closest-match stats”, and  “match overall stats.”

**How does this fit into your workflow?**
Youtubers go through builds item by item and viewers have to pause to see what stats / mods they have configured.  Repeat that 5 times and then examining the weapons and perks, and it takes a lot of time to copy a build.  Imagine if they included a link in their comments and you could see all aspects of their build on one page. 

Then click a button, and DIM gives you the closest approximation to that build with the weapons / armor you have, so you can jump straight into an activity and try out that amazing build!

Other uses: sharing loadouts on reddit.  Instead of “I’m using x and y and killin it!”, someone can say “check this sick build out! <link>“ 

You can also share your build with your clan or your newbie buddy to give him an instant advantage.  

People could make build repositories for different activities.  This would be especially handy for special events where there is a time limit and efficiency is key: Best laurel farming builds, best verdant forest boss builds, etc.  And general activities: Best gambit builds.  Best Grandmaster Nightfall builds.  You get the idea. 

This would also encourage deeper analysis and experimentation with weapons and armor and focus on how to synergize various items.

**Comment by kyleshay** [comment]
linking #4373
