### ISSUE TITLE
Add a link to wiki that explains Quality Ranking

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#528]
Can we can include a link in the move popup next to the overall quality ranking for an item to a page in our wiki that explains the feature?  It would help with some of the confusion we're seeing with users.

**Comment by JosephBono** [comment]
I went to go stub out an entry in the Wiki for this feature and discovered that I can't edit it. After googling around I found that the default setting is that only Collaborators in a repo can edit the wiki. You can open it up to anyone that has a GitHub account via the steps [on this page](https://help.github.com/articles/changing-access-permissions-for-wikis/) if you want. I would be happy to write out this Wiki page and to generally clean up and enhance the Wiki, if that is something you would be interested in.

**Comment by SunburnedGoose** [comment]
Changed it.  I usually lock it down when we have a contest to prevent rules tampering.

**Comment by JosephBono** [comment]
Uploading some images for use in the wiki article: 
![image](https://cloud.githubusercontent.com/assets/10524305/15339883/73369eb4-1c3b-11e6-9a41-09f557157618.png)

![image](https://cloud.githubusercontent.com/assets/10524305/15339921/a3d23204-1c3b-11e6-8c91-16558b23bd8d.png)

**Comment by JosephBono** [comment]
Drafted an initial high level Wiki article about stat quality: https://github.com/DestinyItemManager/DIM/wiki/View-how-good-the-stat-(Int-Dis-Str)-roll-on-your-armor-is

Will follow up with a detailed article about how we calculate stats and what the gotchas are (including artifacts), and then a landing page article that we can link to from the Details/Move pop-up that references both of these

**Comment by kyleshay** [comment]
That's an awesome start @JosephBono, thank you for setting that up!! Once it's set we'll put it in to the app for people to reference!

:D
