### ISSUE TITLE
Items getting randomly moved from Vault to active character

### ISSUE THREAD

**Issue by nishantnahsin** [DestinyItemManager/DIM#5293]
Happened twice to me. Items got moved from my vault to my active character.
I ended up deleting some of them because i saw them as power level 750 copies of items I had in my vault.

DIM was open in chrome as an additional application.
Destiny2 was running full screen on the same machine.

**Comment by delphiactual** [comment]
DIM requires user interaction, except in `Farming Mode`.

**Comment by nishantnahsin** [comment]
> DIM requires user interaction, except in `Farming Mode`.

Gotcha. how does one see if it is in farming mode?

I've been using DIM quite regularly for over an year. This is the first instance of this issue. Two things have changed. The D2 client (possibly) with the release of the current season and DIM's most recent update with the data from the season.

Is there some way to collect information on actions initiated from DIM. Local logging?

**Comment by delphiactual** [comment]
Farming Mode Notification:
![image](https://user-images.githubusercontent.com/4798491/84509888-9a6fd380-ac81-11ea-9e48-6a595877ec49.png)

As far as action log that is located on Bungie.net @ https://www.bungie.net/en/Companion?bru=%252Fen%252FProfile%252FApplicationHistory%252F254%252F1065252

**Comment by nishantnahsin** [comment]
Ok. It's not done that again since. I see some suspicious activity (7 weapon and armor moves in 1 minute). But, I don't remember for sure that I wasn't doing them. So, I'll close this issue and I'll keep watch and bring more information if it happens again.
