### ISSUE TITLE
season:=11 matches nothing; season 11 gear incorrectly matching on season:=10

### ISSUE THREAD

**Issue by javalasers** [DestinyItemManager/DIM#5295]
**What version of DIM are you using?**
6.14.0. Orange icon.

**What Browser and OS are you using?**
Chrome on OSX.

**Describe the bug and how to make it happen**
Search for [season:=11]
Nothing matches.
Search for [season:=10]
Both Worthy and Arrivals gear matches.

Apologies for the extra noise if this is already fixed at HEAD.

**Comment by delphiactual** [comment]
Switch to `beta.destinyitemmanager.com` see #5294
