### ISSUE TITLE
Show powerlimit in spreadsheet exports

### ISSUE THREAD

**Issue by DHager** [DestinyItemManager/DIM#5296]
**Proposed change**

* Add a column to both the armor-spreadsheet and the weapon-spreadsheet, showing the item's power limit (e.g. 1060)
* I suggest the new column be placed immediately after the existing "Power" column, and be labeled "Power Limit".

I expect this to be a small change similar to #5137, using the same logic that drives the `powerlimit:` filter.

**How does this fit into your workflow?**

This would help users triage what equipment to keep or remove. In my particular case, I'm feeding the data into a custom script which scores armor, and I want to give higher scores to armor that has greater longevity.

Pinging @sundevour since this overlaps with some of their work. I'm willing to implement it myself if needed.

**Comment by DHager** [comment]
**P.S.:** How should the value for powerlimit-less exotics be shown? A blank string? Or a placeholder `9999` so that sorting is effective?

**Comment by sundevour** [comment]
right now it's going to be a blank cell, matching the missing-ness in-game and in DIM.

i'd rather not export misleading values, and having no limit can mean various things in the API, not just unlimited exotics, but like, all white/blue/green gear, any case where a max PL isn't appropriate. 

so by the time an item reaches the spreadsheet builder for processing, we've discarded the various weird numbers they use to represent not having a limit.
