### ISSUE TITLE
organizer: item location column

### ISSUE THREAD

**Issue by archived-2f4dd0** [DestinyItemManager/DIM#5298]
a user in discord brings up the excellent point that if we provide move functionality on the organizer page, we should really provide a column for where the item is currently located. seems only fair since that info is made relevant by the move option

**Comment by bhollis** [comment]
I'm torn on whether this means we should add the column or remove the move option. I'm not sure when you'd want to move in bulk from there - I added it at first because it seemed obvious but now I don't know.

**Comment by bhollis** [comment]
I figure we should probably just add the column.
