### ISSUE TITLE
Item Leveling not working

### ISSUE THREAD

**Issue by snurly7** [DestinyItemManager/DIM#530]
When I click the item leveling option, nothing changes despite having several pieces of gear that are unleveled in my inventory.

**Comment by bhollis** [comment]
Would you be able to open the developer console, try it again, and see if
you get an error?

**Comment by snurly7** [comment]
No error showing in the console.

**Comment by bhollis** [comment]
Would you be able to record a video or a GIF showing it not working? It'll
help to see what you have and what you expected to see happen.

**Comment by Mulchman** [comment]
Jing is an easy way to record your screen if don't have anything. (No
affiliation.).

https://www.techsmith.com/jing.html

**Comment by kyleshay** [comment]
@snurly7 still having the same issue?

**Comment by kyleshay** [comment]
please re-open if this is still an issue!
