### ISSUE TITLE
Guard resistance is shown as N/A depending on perks

### ISSUE THREAD

**Issue by quetschke** [DestinyItemManager/DIM#5304]
**What version of DIM are you using?**
6.14.0

**What Browser and OS are you using?**
Firefox/chrome on Windows, also app on android phone

**Describe the bug and how to make it happen**
In comparison view the guard resistance can be "N/A". See picture below. It is not always the case, as the comparison wit the other sword shows.

The sword with N/A in the comparison view does not show "Guard resistance" in the detailed view. See second picture below. 

![image](https://user-images.githubusercontent.com/5354403/84580312-70aacf80-ad9b-11ea-970e-9c90d4f5b762.png)

![image](https://user-images.githubusercontent.com/5354403/84580339-bf586980-ad9b-11ea-9a1b-8bea6d02c27a.png)

**Comment by quetschke** [comment]
As a follow up, when I switch from "Enduring Guard" to "Heavy Guard" a guard resistance value is shown. See below.
![image](https://user-images.githubusercontent.com/5354403/84580435-9dabb200-ad9c-11ea-870b-24655b685058.png)

**Comment by sundevour** [comment]
oh that's fun. ty for the detailed report

**Comment by thomaskchan** [comment]
I can confirm this behavior but it seems inconsistent between changing guard perks and refreshing DIM.  Sometimes you get all the stats but sometimes you are missing one.

Original state:
- Steel Sybil + Enduring Guard -> Missing Guard Resistance
- Honor's Edge + Enduring Guard -> Missing Guard Resistance
- Just in Case + Enduring Guard -> All stats present

First change:
- Steel Sybil + Burst Guard -> Missing Guard Endurance
- Honor's Edge + Burst Guard -> Missing Guard Endurance
- Just in Case + Burst Guard - > Missing Guard Endurance

Second Change:
- Steel Sybil + Enduring Guard -> Missing Guard Resistance
- Honor's Edge + Enduring Guard -> All stats present
- Just in Case + Enduring Guard -> Missing Guard Resistance

Version 6.14.0.7280 (beta), built on 6/14/2020, 4:33:02 PM

**Comment by quetschke** [comment]
I just checked in the latest release and beta version. Not as detailed as thomaskchan above, but there are still N/As. See picture for reference:
![image](https://user-images.githubusercontent.com/5354403/84792395-69610d00-afb9-11ea-984d-7b754a63430c.png)

**Comment by bhollis** [comment]
I don't think anyone did anything to try and fix it.

**Comment by sundevour** [comment]
![image](https://user-images.githubusercontent.com/31990469/85528613-fced9b80-b5c0-11ea-8ab1-bf33c79ed9b6.png)
in defs, some swords are missing efficiency or resistance, all swords are missing endurance

these get built by `buildInvestmentStats` with missing stats,
then `enhanceStatsWithPlugs` only creates the missing stats if they have blades/guards that affect that stat

**Comment by sundevour** [comment]
this is fixable by enforcing a minimum baseline for all stats swords are supposed to have, but i think there's different levels of base resistance stat, i think i see both 50 and 60. i think maybe endurance is baseline 20? so maybe this boils down to filing a bug against the missing stat. it merits more investigation but not a huge priority personally

**Comment by sundevour** [comment]
or just verifying against live stats? why don't we do that

**Comment by nev-r** [comment]
bungie (inadvertently?) fixed this by including all sword stats in the sword guards' investment stats.
this triggers DIM to calculate the stats properly with investment curves, even though they're missing from the base sword definitions.
