### ISSUE TITLE
"Arrivals" is missing as a category in armor comparison view

### ISSUE THREAD

**Issue by quetschke** [DestinyItemManager/DIM#5305]
**What version of DIM are you using?**
6.14.0

**What Browser and OS are you using?**
Firefox, chrome on Windows and android app

**Describe the bug and how to make it happen**
In the comparison view there is no category for the current season. See the two pictures below, there is a category for "worthy" armor, but not for "arrivals" armor.

![image](https://user-images.githubusercontent.com/5354403/84580531-57a31e00-ad9d-11ea-9acc-79f2feece4d6.png)

![image](https://user-images.githubusercontent.com/5354403/84580564-976a0580-ad9d-11ea-8699-3e1e67f45e29.png)

**Comment by bhollis** [comment]
Try Beta.

**Comment by quetschke** [comment]
Looks good in beta! Fixed.
