### ISSUE TITLE
Display item quality for items in Postmaster

### ISSUE THREAD

**Issue by JosephBono** [DestinyItemManager/DIM#531]
We have the Light Level and stat values for Int/Dis/Str for items in the Postmaster, so this should be calculable. Quality of Life improvement for users that have full vaults and use the postmaster as an extension of their vault.

**Comment by bhollis** [comment]
I'll be able to support this easily after some other changes I'm working
on. Assign to me.

**Comment by bhollis** [comment]
This is almost done - expect a PR next week.

**Comment by nki2bpz** [comment]
Excellent feature request!

**Comment by bhollis** [comment]
Closing in favor of #595.
