### ISSUE TITLE
Search should be season:arrivals instead of season:arrival

### ISSUE THREAD

**Issue by thomaskchan** [DestinyItemManager/DIM#5310]
Version 6.14.0.7254 (beta), built on 6/13/2020, 3:12:57 PM
Chrome on MacOS

Not super important, but noticed this.  It is the "Season of Arrivals", so the searches should be for season:arrivals not season:arrival.  This should also apply to modslot/holdsmod and anything else.

**Comment by delphiactual** [comment]
https://data.destinysets.com/i/InventoryItem:2263321585

itemTypeDispalyName: `Arrival Armor Mod`
