### ISSUE TITLE
Scrollbars in Vendor page overlap the content on Windows.

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#5316]
**What version of DIM are you using?**
6.14.0

**What Browser and OS are you using?**
Chrome on Windows 10

**Describe the bug and how to make it happen**
Scrollbars are overlapping content on the vendor page.

![image](https://user-images.githubusercontent.com/984608/84599457-ccc33180-ae37-11ea-91cd-c46d89a7a5c0.png)

**Comment by SunburnedGoose** [comment]
Need to inspect the implementation on MacOS and Windows to make sure they both behave similarly.

**Comment by sundevour** [comment]
https://github.com/DestinyItemManager/DIM/issues/5149

**Comment by et-nat1995** [comment]
@SunburnedGoose Inspected on a mac same issue.
<img width="455" alt="Screen Shot 2020-06-16 at 2 41 18 PM" src="https://user-images.githubusercontent.com/42855538/84831045-7d1f6a00-afdf-11ea-9981-c384ad116546.png">

**Comment by bhollis** [comment]
@et-nat1995 it depends on your scrollbar settings - for me, the scrollbar is invisible until scrolling

**Comment by bhollis** [comment]
<img width="474" alt="Screen Shot 2020-06-16 at 8 43 07 PM" src="https://user-images.githubusercontent.com/313208/84852564-0d76a280-b012-11ea-9755-279007fefb43.png">

**Comment by bhollis** [comment]
https://www.filamentgroup.com/lab/scrollbars/

**Comment by bhollis** [comment]
@kyleshay did you fix this?
