### ISSUE TITLE
[Android] inventory/vault scrollbar keeps reverting to top position when browsing

### ISSUE THREAD

**Issue by arane9** [DestinyItemManager/DIM#5319]
**What version of DIM are you using?**

6.15 orange

**What Browser and OS are you using?**

android brave and chrome, latest versions

**Describe the bug and how to make it happen**

Inventory Tab: While viewing items on my characters and the vault scrollbar reverts back to the top after I finish viewing weapons/armor. For example I will look at energy or power weapon rolls and then press back and the scrollbar will go back up to kinetic weapons. It always happens. I don't recall this happening before so it is very annoying.

**Comment by bhollis** [comment]
Is this still happening on beta?

**Comment by arane9** [comment]
> Is this still happening on beta?

Just tried blue beta version 6.15.1.7312 same issue.

**Comment by bhollis** [comment]
I know how to fix it but it’s a bit involved
