### ISSUE TITLE
Add subclass to Inleveled Items. 

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#532]
When a user is adding cp it items Using our loadout, it should pick unleveled subclasses too.

**Comment by bhollis** [comment]
Not 100% sure what you mean here, but if you're referring to the "item
leveling" loadout, it should also pick unleveled subclasses. It does for me
at least.

**Comment by SunburnedGoose** [comment]
https://www.reddit.com/r/DestinyItemManager/comments/4j2tqk/comment/d34doed

**Comment by SunburnedGoose** [comment]
This user PM'ed me about this issue.

**Comment by bhollis** [comment]
Ok. I'll test it again when I have a chance, but this has worked for me in
the past.

**Comment by bhollis** [comment]
I just re-confirmed - we do absolutely equip an unleveled subclass if one is available.

**Comment by SunburnedGoose** [comment]
yay!
