### ISSUE TITLE
Crash after switching characters (iPhone)

### ISSUE THREAD

**Issue by mannyrye** [DestinyItemManager/DIM#5321]
**What version of DIM are you using?**
Version 6.15.0 (release), built on 6/14/2020, 2:46:57 PM
Orange icon 

**What Browser and OS are you using?**
Safari, iOS 13.5 on an iPhone 8 Plus. 

**Describe the bug and how to make it happen**
After switching characters *in destiny* DIM crashes as I swipe to the new character. This didn’t happen a few weeks ago.

**Comment by bhollis** [comment]
Possibly related to https://github.com/DestinyItemManager/DIM/issues/5100

**Comment by mannyrye** [comment]
BTW the error I get is #185

**Comment by bhollis** [comment]
Sentry issue: [DIM-GYX](https://sentry.io/organizations/destiny-item-manager/issues/1615745749/?referrer=github_plugin)

**Comment by bhollis** [comment]
Closing as dupe of #5109
