### ISSUE TITLE
Can’t dismiss search field (iPhone)

### ISSUE THREAD

**Issue by mannyrye** [DestinyItemManager/DIM#5322]
**What version of DIM are you using?**
Version 6.15.0 (release), built on 6/14/2020, 2:46:57 PM
Orange icon

**What Browser and OS are you using?**
Safari, iOS 13.5 on an iPhone 8 Plus.

**Describe the bug and how to make it happen**
In the last few days I haven’t been able to dismiss the search field (by clicking the circle with an X). The workaround is to reload DIM.

**Comment by sundevour** [comment]
hi, thank you for the report! can you try beta.destinyitemmanager.com, accept the update and make sure your version number says at least `6.15.0.7289`, and please let us know if it's working

**Comment by mannyrye** [comment]
Aloha,

It does work on the beta 😀

Ramón


--
Dr. Ramón M. Figueroa-Centeno, Ph.D.
Associate Professor of Mathematics
University of Hawai‘i at Hilo
________________________________
