### ISSUE TITLE
Loadout Optimizer missing arrivals mods?

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#5324]
https://www.reddit.com/r/DestinyItemManager/comments/h9eiyp/season_of_arrivals_mods_in_loadout_optimizer/

**Comment by bhollis** [comment]
99% sure it's because these mods didn't make it into Collections

**Comment by ryan-rushton** [comment]
I can check this out later today.

**Comment by bhollis** [comment]
@ryan-rushton I still can't see Arrival mods in the picker, on the latest beta.

**Comment by ryan-rushton** [comment]
I will check it out

**Comment by ryan-rushton** [comment]
@bhollis I am seeing them show up. Can you see this one?

<img width="1087" alt="Screen Shot 2020-06-17 at 5 58 56 pm" src="https://user-images.githubusercontent.com/7344652/84871852-64d54b00-b0c4-11ea-84da-0f647c836c81.png">

**Comment by ryan-rushton** [comment]
Just had a thought that maybe they only show up when you have available on your account. I would have to check in game to see what I have to confirm.

**Comment by bhollis** [comment]
I see the issue, I see them in "Select energy or perk" but not "Select mod"

**Comment by ryan-rushton** [comment]
Sun merged a PR of mine for that today. I had to make the same change in the mod picker class as well.

**Comment by ryan-rushton** [comment]
@bhollis closing this as I believe it is sorted now. Feel free to reopen if there is something missing still.
