### ISSUE TITLE
Sort by Mod Slot & Power Level Limit

### ISSUE THREAD

**Issue by Nadiar** [DestinyItemManager/DIM#5328]
**Proposed change**
Add additional sort methods based on mod slot and power level limits

**How does this fit into your workflow?**
This would make comparing items much more usable.  Weapons would sort based on retired/retiring/refreshed status, and armor would be able to be sorted by mod compatibility.

**Comment by bhollis** [comment]
Check out the Organizer tab, that's what it's designed for.
