### ISSUE TITLE
Loadout optimizer does not respect non-energy aligned seasonal mod socket permissions

### ISSUE THREAD

**Issue by nabsltd** [DestinyItemManager/DIM#5329]
**What version of DIM are you using?**
6.15.1

**What Browser and OS are you using?**
Chrome 83.0.4103.97 (64-bit) on Windows 7

**Describe the bug and how to make it happen**
When using Loadout Optimizer, I lock in 5 pieces of "Arrival" armor, choose "Ignore" on all stats, then choose a mod like "Taking Charge", and get the "No builds found". This is caused by the Optimizer not realizing that the season 9 mod "Taking Charge" can be slotted into season 11 armor despite the fact that the armor says "season 10, 11, and 12 mods".
If you click on the seasonal slot on any of the armor pieces, "Taking Charge" is shown as an option, since it can be slotted there.
For season 9 mods and later, the restriction on seasonal mods seems to only apply to mods that have an elemental affinity, not general-purpose seasonal mods. This is handled correctly by DIM everywhere but the Loadout Optimizer.

**Comment by delphiactual** [comment]
https://github.com/DestinyItemManager/DIM/issues/5241

**Comment by nabsltd** [comment]
This is a completely different issue from #5241 
The issue is Loadout Optimizer doesn't think that the mods can be slotted, even though the rest of DIM knows they can be.

**Comment by bhollis** [comment]
You’re right. This is actually a duplicate of #5080.

**Comment by ryan-rushton** [comment]
The difference between the load out optimizer and the rest of DIM in this regard is that the rest of DIM just surfaces mods that are on an item, while LO needs to figure out which item can take which mods. 

If season 9 mods can in fact be slotted into season 11 armour we would need to change the data we are generating as we restrict it to season 10, 11, and 12. Do we know that this is intended and not a bug? I know there was issues with dawn armour (9) being able to slot season 11 mods that weren’t earned yet.
