### ISSUE TITLE
Feature request: Clickable perks in compare panel

### ISSUE THREAD

**Issue by jkewley** [DestinyItemManager/DIM#5336]
**Proposed change**
Make the weapon perks clickable in compare mode to allow real-time what-if adjustment of stats above.

**How does this fit into your workflow?**
This would allow us to visually compare item stats if different perks were selected - something that I typically do while playing when deciding to keep it / shard it

![image](https://user-images.githubusercontent.com/1148930/84784585-1df63100-afb0-11ea-9fe2-e2a69f9882d1.png)

**Comment by bhollis** [comment]
Effectively duplicate of https://github.com/DestinyItemManager/DIM/issues/4278
