### ISSUE TITLE
Show mod slot for mods in Loadout Optimizer mod picker

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#5342]
It'd be nice to be able to either filter mods in the mod picker by modslot, or show which modslot/season they come from. It'd help sort through the giant list of mods!

**Comment by ryan-rushton** [comment]
Is this in the perk picker or mod picker?

**Comment by bhollis** [comment]
I assume once mod picker is its own thing, it'd be in mod picker

**Comment by ryan-rushton** [comment]
In the mod picket they are already split by slot but I agree with the idea of separating them by season too. I would also like to sort them by (season -> energy type -> cost -> name) in all the different categories too. I think it would be a pattern people would easily notice.

**Comment by bhollis** [comment]
If you haven't seen it, https://destinysets.com/mods is a great presentation

**Comment by ryan-rushton** [comment]
Yeah I use that one for figuring out what I do and don't have, and you're right its great. Would we want a designer to have an input first or maybe we should build a modal and try to do something similar?

**Comment by ryan-rushton** [comment]
I think this is done now with the latest stuff. @bhollis reopen it if you want and we can chat about what needs to be done.
