### ISSUE TITLE
Organizer: Bounties Filter

### ISSUE THREAD

**Issue by Nekroze** [DestinyItemManager/DIM#5344]
**Proposed change**
A new filter for weapons in the organizer to list any weapon that can contribute to a currently held bounty on a character.

**How does this fit into your workflow?**
This would provide a quick way to put together an inventory of gear required to complete all current weapon/damage type based bounties on a character. I could then sort these by something like power level or a tag indicating it is a good weapon for farming. Doing this manually is feasible but tedious.

**Comment by bhollis** [comment]
If we do this, let's do it in #5647
