### ISSUE TITLE
Removal of BLM banner

### ISSUE THREAD

**Issue by OscarArango** [DestinyItemManager/DIM#5345]
Hello,

Can we remove the BLM banner at the bottom of the page.  I don't like political reminders when gaming.

**Comment by OscarArango** [comment]
why is this closed? banner is still there.

**Comment by OscarArango** [comment]
Not trying to be a pain, please, others also do not wish for this banner politics stuff.

**Comment by OscarArango** [comment]
I will open new issue tomorrow if it is still there.  Sorry but this cannot stand.

**Comment by OscarArango** [comment]
at least make it close-able, collapsible.

**Comment by SunburnedGoose** [comment]
It's closed because we will not make this change. You've ben heard. There is no need for a new issue. If you create a new one on this topic, it will result in a ban.
