### ISSUE TITLE
Sort inventory by season?

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#5346]
Many people have asked for us to add an option to sort gear by season.

I'm not sure exactly what this would be for. My best guess is they actually want to sort by the season an item will sunset.

**Comment by ryan-rushton** [comment]
It's something I would like, especially when ornaments are on armour items. If you are looking for something to take a certain mod then it would make life much easier as the ornament icon's hide that.

**Comment by bhollis** [comment]
Well, we fix that now and always show the correct icon. But even then, isn't that suggesting sort-by-modslot, not sort-by-season?

**Comment by ryan-rushton** [comment]
I kinda see sort by mod slot and sort by season as being the same thing, as the mod slots are tied to a season.

**Comment by sundevour** [comment]
season in DIM is not a reliable indicator of anything though, it's sort of collections-geared type of thing, whose goal is simply to identify when an item showed up

**Comment by bhollis** [comment]
Yeah that's why I'm trying to dig into what people really want instead of season sort.

**Comment by ryan-rushton** [comment]
> Well, we fix that now and always show the correct icon. 

Are you sure about this? I get the ornaments icon on both deployments.

**Comment by bhollis** [comment]
Another request came in to sort by power cap. I think folks really want to use the organizer and are using custom sort to achieve something similar in the main inventory screen?

**Comment by bhollis** [comment]
We couldn't come to a conclusion on this, and sorting by things that aren't visible on the tile is of questionable value.
