### ISSUE TITLE
Show CustomTotal stats on armor pop-up panel.

### ISSUE THREAD

**Issue by tanglueyi** [DestinyItemManager/DIM#5350]
Hello Devs!
I have an idea to display my focused custom total stats (eg. Mob+Rec+Dis) on the armor panel. This method can quickly make me distinguish the stats' quality of this armor. 
_(The UI interface I designed is as follows, of course, you may have a better one)_
![Frame 13](https://user-images.githubusercontent.com/3315564/84990227-6c096100-b177-11ea-842b-316db84f3154.jpg)
We can quickly (en)disable this function through the settings page, and set the preferences of each character (Hunter, Warlock, Titan)!
_(The UI interface I designed is as follows, of course, you may have a better one)_
![Frame 11](https://user-images.githubusercontent.com/3315564/84990810-4761b900-b178-11ea-8f65-af14d938b914.jpg)

**Comment by nomadjsdev** [comment]
As an addition to this (if that's allowed): including this custom stat total in search - something like `stat:customtotal:>=40`
