### ISSUE TITLE
No builds when select helmet+season mods(maybe)

### ISSUE THREAD

**Issue by tanglueyi** [DestinyItemManager/DIM#5351]
![CleanShot 2020-06-18 at 17 54 35@2x](https://user-images.githubusercontent.com/3315564/85006978-73d40000-b18d-11ea-8953-991b60f49252.png)
IDK why this happens, I DO have helmets can setup stack by stack mod.
![image](https://user-images.githubusercontent.com/3315564/85007237-d4fbd380-b18d-11ea-80f5-3cc7fadff94b.png)

**Comment by ryan-rushton** [comment]
That's a season of the dawn mod if I am not mistaken. Can you post a pic of that helmet after you have clicked it to show it's popup please.

**Comment by tanglueyi** [comment]
> That's a season of the dawn mod if I am not mistaken. Can you post a pic of that helmet after you have clicked it to show it's popup please.

![Uploading 85018298...]()

**Comment by ryan-rushton** [comment]
@tanglueyi I think you clicked the comment button before it finished uploading.

**Comment by tanglueyi** [comment]
> @tanglueyi I think you clicked the comment button before it finished uploading.

![image](https://user-images.githubusercontent.com/3315564/85018641-18f7d400-b1a0-11ea-8f56-fbfc85b95c3f.png)

**Comment by ryan-rushton** [comment]
Thanks I will have a dig through the data and see if I can come up with anything.

**Comment by tanglueyi** [comment]
thank you :D

**Comment by ryan-rushton** [comment]
I have been doing a little digging but I can't reproduce this with the items I have. Using a difference season of the dawn mod (precisely charged) and a different worthy helmet (iron remembrance casque) I don't see this happening. There might be some issue with those items specifically.

@tanglueyi out of interest, do you get the same issue if you use the seasonal mods picker section at the bottom rather then the helmet specific one? To figure that out lock all other items to be things that can't take a season of dawn mod. I locked everything to be from this season, other than the helmet.

**Comment by tanglueyi** [comment]
It'll not happen when I lock the dawn's mod as seasonal one. :D
![image](https://user-images.githubusercontent.com/3315564/85236149-baf01880-b44d-11ea-8687-83b121bee739.png)

**Comment by ryan-rushton** [comment]
@tanglueyi cheers, that might help me narrow it down.

**Comment by tanglueyi** [comment]
And another pic might help :)
![image](https://user-images.githubusercontent.com/3315564/85237291-4ec6e200-b458-11ea-923b-a80267cc68e1.png)

**Comment by ryan-rushton** [comment]
@tanglueyi could you check this for me in https://beta.destinyitemmanager.com/. I haven't been able to reproduce it and we have had a number of changes go into beta recently which may have fixed the issue.

**Comment by ryan-rushton** [comment]
I am going to close this as I haven't heard back. Let us know if you are still seeing the issue @tanglueyi

**Comment by tanglueyi** [comment]
seems no issue now， I will report if happened again， thank you！

**Comment by tanglueyi** [comment]
![CleanShot 2020-09-15 at 15 00 16@2x](https://user-images.githubusercontent.com/3315564/93177024-b72a1480-f764-11ea-8eed-f9b2a646849d.png)
<img width="225" alt="CleanShot 2020-09-15 at 15 02 42@2x" src="https://user-images.githubusercontent.com/3315564/93177027-b8f3d800-f764-11ea-8a7a-6713cc33d9be.png">
@ryan-rushton Another bug :D

**Comment by ryan-rushton** [comment]
I will look into it, thanks for the report

**Comment by ryan-rushton** [comment]
@tanglueyi I created a new ticket and a fix has gone in. Should be ready to test soon. Once you see an update for beta see if you can break it for me. New issue is #5805
