### ISSUE TITLE
Missing Links

### ISSUE THREAD

**Issue by TheLemurGod** [DestinyItemManager/DIM#5362]
**What version of DIM are you using?**
Version 6.16.0 (release), built on 6/21/2020, 7:59:06 PM
Orange Icon

**What Browser and OS are you using?**
Google Chrome and it is installed as an extension on Windows 10.

**Describe the bug and how to make it happen**

Up until about hour ago (1:34 AM EST) every time I would click on progress on the top menu it would load my three characters and several jump to sections and under all of those used to be links that would take you to external sites like D2 Checklist etc. Now those links are no longer available. 
Sorry if this is a repeat or an already addressed issue.

**Include devtools console logs**
If you can, open the devtools console (ctrl+shift+J on PC and cmd+option+J on Mac) and paste what you see in the window that pops up:

```
Paste console logs here
```

**Comment by delphiactual** [comment]
#5361
