### ISSUE TITLE
Do you have any documents for setting up Linux server?

### ISSUE THREAD

**Issue by xuanxiaoyu69** [DestinyItemManager/DIM#5366]
Do you have any documents for setting up Linux server?
请问有没有搭建在linux服务器的相关文档

I want to let my little friends access this project, that is, using nginx and domain name.
我想让我的小伙伴也使用这个项目，使用nginx与域名配置

I use the command of "yarn build release", put it on the Linux server, use nginx configuration, use domain name, and finally I can't access it
我使用“yarn build-release”，放到linux服务器上，使用nginx配置，使用域名，最终无法使用

**Comment by bhollis** [comment]
We don't support hosting DIM on a different server than our own.
