### ISSUE TITLE
Consider adding sunset filters

### ISSUE THREAD

**Issue by CanisLupus518** [DestinyItemManager/DIM#5370]
**Proposed change**
I would love to see a filter to show me what items are sunsetted or will be sunsetting in the current season. such as  is:sunsetting or is:finalseason  or is:powerlimit
**How does this fit into your workflow?**
This would help me identify what gear to de-prioritize and help me focus on newer items

**Comment by sundevour** [comment]
![image](https://user-images.githubusercontent.com/31990469/85626115-62717480-b621-11ea-8d54-e8576d7b0268.png)
??

**Comment by CanisLupus518** [comment]
Apologies, I missed this
