### ISSUE TITLE
Item filter count mobile

### ISSUE THREAD

**Issue by nitroinferno** [DestinyItemManager/DIM#5371]
**Proposed change**
Item count from filter if possible on mobile. Currently item count from filter is displayed on pc.

**How does this fit into your workflow?**
Helps focus how many items of a certain query I have, would assist with vault cleanup on mobile.

**Comment by bhollis** [comment]
I think what I'm going to do is switch mobile over to just showing all results, instead of filtering the inventory view like we do today.

**Comment by kyleshay** [comment]
we can resolve this as part of https://github.com/DestinyItemManager/DIM/issues/5669
