### ISSUE TITLE
All items from Benedict9940 are hidden as collected even if they don't

### ISSUE THREAD

**Issue by Horodep** [DestinyItemManager/DIM#5378]
**What version of DIM are you using?**
6.16.1 orange

**What Browser and OS are you using?**
Chrome 83.0.4103.106, Win 10

**Describe the bug and how to make it happen**
I don't have armor from raid and vendor is selling it right now. But if i select option **[ ] Only show uncollected items** this armor is hidden. I believe this is because I didn't complete raid this week and can't buy this armor right now, but I think this is still incorrect.

**Comment by bhollis** [comment]
What that means is that Bungie's data doesn't tie those items back to the collectible version. They are in fact different items - the version sold by Benedict is Armor 2.0, and the version in collections is Armor 1.0.

**Comment by Horodep** [comment]
Well. Shall we close this bug then or there is a way to transfer it to bungie?

**Comment by sundevour** [comment]
probably an argument in favor of fixing missing sources during item factory?

**Comment by bhollis** [comment]
I'd have to look, but the data we use for this is collectible hash, not source.

**Comment by sundevour** [comment]
yes that, sorry

**Comment by bhollis** [comment]
Here's the existing bungie.net API bug: https://github.com/Bungie-net/api/issues/1088
