### ISSUE TITLE
Loadout Optimizer is not ignoring stat penalties on seasonal mods

### ISSUE THREAD

**Issue by GhostPirate101** [DestinyItemManager/DIM#5381]
(Issue found on beta version 6.16.1.7400)

I noticed that the Loadout Optimizer is not ignoring seasonal mod stat penalties, and also is incorrectly calculating those values if the penalty is greater than the stat on the armour piece it is equipped to.

Here are my stats without any mods equipped - for reference my recovery stat here is 39/100
![image](https://user-images.githubusercontent.com/29430411/85918610-41e12e80-b85c-11ea-98e2-2c2396c376aa.png)

If I equip the 'Stacks on Stacks' mod (-10 recovery) on my helmet (base recovery +7) the recovery value in the optimizer doesn't change:
![image](https://user-images.githubusercontent.com/29430411/85918680-d51a6400-b85c-11ea-9e1f-651c5cefd2db.png)

However, if I switch the mod to my chest (base recovery +19), the recovery value in the optimizer changes:
![image](https://user-images.githubusercontent.com/29430411/85918708-0d21a700-b85d-11ea-9756-c9a32c48ea36.png)

I assume this is because DIM doesn't know that armour can potentially provide negative stat bonuses now in certain configurations (e.g. the helmet with Stacks on Stacks equipped is providing -3 recovery to the total stat).

In fairness the in-game interface is also pretty confusing with this - the totals are calculated correctly but the individual armour piece stats don't cope with the negative numbers properly.

Another strange behaviour I noticed is with the 'Charge Harvester' mod. The in game description says '-10 to the stat that governs your class ability recharge rate', but DIM is interpreting this as -10 to mobility, resilience and recovery:

![image](https://user-images.githubusercontent.com/29430411/85918836-0b0c1800-b85e-11ea-9c4b-5a434bba9390.png)

**Comment by delphiactual** [comment]
#4890

**Comment by ryan-rushton** [comment]
So the reason you see the difference is we currently 'strip' the mod values from of armour items to ensure that we get base stat values for the LO as mods can be removed easily. We have a minimum armour stat value of 0 so that helmet can never have a -3 value. 

We did this when negative stats first came out so if it would be more correct to let it fall into negative values then we can update that. I would just want to confirm that this is how we should be handled.

Regarding the charged harvester mod, we read the stats values directly off the mod itself, so the mod must indicate all 3 values. We might need to have special logic that figures out what the class is and deducts correct stat. That would be annoying to maintain though especially if bungie comes out with new combinations every season.

**Comment by GhostPirate101** [comment]
But why is the optimizer taking account of the stat penalties and bonuses of seasonal mods at all? Shouldn't it be ignoring them, as per the text "Armor 2.0 Mods are not included in stat tier calculations"?

(Note - in the examples above I hadn't locked the mods in the filter section, just slotted them on the armour in-game, so they shouldn't be contributing to the stats as I understand it)

**Comment by GhostPirate101** [comment]
Apologies - I think I've conflated two separate issues here. The main thing I was pointing out was that the optimizer is not ignoring the stat effects of certain mods despite saying it does, but I also noticed the negative stat issues while I was verifying the issue.

**Comment by ryan-rushton** [comment]
Yeah there are two issues here.

1. So the optimizer does ignore stats on mods unless you lock them. As soon as they are locked they are included in the stats calculations. I have been chipping away at a bit of work that will make all this more obvious but it is a couple of weeks away at least.
2. You are right, negative stats are not handled correctly. I plan on closing this ticket once I handle the negative stats issue, it's next on my list after a chunky bit of work I am doing.

**Comment by GhostPirate101** [comment]
The thing is - I didn't lock the mods in the examples above. The only thing I did lock was my equipped gear, to ensure it displayed in the optimizer while I swapped mods in and out in-game.

**Comment by ryan-rushton** [comment]
Ah ok, it should be ignoring those then. Negative stats weren't a thing when a lot of this was done so there could be something quirky with them. Once I am done with this thing I am currently working on I will look into it.

**Comment by ryan-rushton** [comment]
This is mainly just a note for myself but seasonal mods are not being included in the stat mix combination calculations. As they are all negative stats from my understanding I will fix it with this.

**Comment by ryan-rushton** [comment]
@GhostPirate101 a few changes have just gone into https://beta.destinyitemmanager.com/ that should fix this issue. If you have a change can you confirm for me that these fix your issue?
