### ISSUE TITLE
Opening loadout in LO doesn't select the correct character.

### ISSUE THREAD

**Issue by ryan-rushton** [DestinyItemManager/DIM#5383]
Steps to reproduce:
1. Open a loadout for a character that is in the second or third slot
2. Select to open the loadout in the LO

Expected: LO is opened with the items locked and the character selected

Actual: LO is opened with the items locked and the character from the first slot selected.

![image](https://user-images.githubusercontent.com/7344652/85950945-33515f00-b9a3-11ea-99a2-c5bb3615a8e6.png)

**Comment by anthony-kopczyk** [comment]
Wrote some code for this. I think it works now and accessing loadout optimizer other ways seems to work as well. I'm not super familiar with the loadout portion of DIM. Let me know if there's anything to change.

https://github.com/DestinyItemManager/DIM/pull/5438
