### ISSUE TITLE
Wrong tier calculation

### ISSUE THREAD

**Issue by rentalhost** [DestinyItemManager/DIM#5385]
**What version of DIM are you using?** 6.17.0 (Beta)

**What Browser and OS are you using?** Chrome 83.0.4103.116

**Describe the bug and how to make it happen**

Currently I am using a **T28** (5/5/5/6/4/3) set, but it is shown as **T24** (5/3/4/6/3/3).

* **Mobility** shows **T5**, that is right;
* **Resilience** shows **T3**, instead of **T5**;
* **Recovery** shows **T4**, instead of **T5**;
* **Discipline** shows **T6**, that is right;
* **Intellect** shows **T3**, instead of **T4**;
* **Strength** shows **T3**, that is right;

**In game:**

![image](https://user-images.githubusercontent.com/421851/86021280-4eea5300-b9ff-11ea-85e7-93605ac584d8.png)

**In DIM:**

![image](https://user-images.githubusercontent.com/421851/86021481-7f31f180-b9ff-11ea-940b-159f7999a927.png)

Seems that DIM receives the correct stats values, but calculates it incorrectly.

For instance, if we consider only the Resilience, we have (**3+24+24+8+0 = 59**, or **T5**):

![image](https://user-images.githubusercontent.com/421851/86021635-aee0f980-b9ff-11ea-9163-fad1539706a3.png)
![image](https://user-images.githubusercontent.com/421851/86021964-1c8d2580-ba00-11ea-8612-2e0e747c57c3.png)

![image](https://user-images.githubusercontent.com/421851/86021647-b43e4400-b9ff-11ea-9b99-b3af9d8c17fd.png)
![image](https://user-images.githubusercontent.com/421851/86022000-2747ba80-ba00-11ea-9113-25bf5884ba25.png)

![image](https://user-images.githubusercontent.com/421851/86021675-bb655200-b9ff-11ea-9606-2ed00c498817.png)
![image](https://user-images.githubusercontent.com/421851/86022010-2b73d800-ba00-11ea-9332-6c39448ba6f8.png)

![image](https://user-images.githubusercontent.com/421851/86021687-c02a0600-b9ff-11ea-911a-a2579488090d.png)
![image](https://user-images.githubusercontent.com/421851/86022026-329ae600-ba00-11ea-99a3-f59d569fa8a2.png)

![image](https://user-images.githubusercontent.com/421851/86021708-c4eeba00-b9ff-11ea-9bc1-68feeb4f9c08.png)
![image](https://user-images.githubusercontent.com/421851/86022057-3c244e00-ba00-11ea-9481-0ff12b2ce49a.png)

But it is calculated as **T3** for some reason. Even enabling "Assume Masterwork" it will be **T4** instead of **T5**.

**Comment by delphiactual** [comment]
Mods are not included unless locked

**Comment by rentalhost** [comment]
There is some reason to mods not to be applied? It seems a bit inconsistent, because if we sum all attributes we will get a different value from displayed tier.

**Comment by ryan-rushton** [comment]
Because they can easily be removed and added. The idea of the optimizer is to find the best possible base stats on a set. Then you can tweak it to what you want with mods.

**Comment by ryan-rushton** [comment]
@rentalhost I am going to close this as from what I am aware we have no intention of applying mod stats to items across the board. In the past we had a lot of request for these to not be included in these calculations.

There is some work coming up that will make it more obvious what is currently being applied. If after that we get enough community interest in adding something for it I might look back into it.
