### ISSUE TITLE
Vigil of Heroes doesn't show properly in the compare items panel

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#5386]
Current season Vigil of Heroes.  View the item and click the compare panel button.

![image](https://user-images.githubusercontent.com/25425159/86145602-447ea500-bb36-11ea-9849-5cb7c2b69907.png)

Note that it does say "Vigil of Heroes" in the selectors across the top.  Every other armor piece I've checked does include it's name in the selectors.

**Comment by delphiactual** [comment]
Is that the only season of arrivals vigil of heroes helmet you have?

**Comment by philkernick** [comment]
Yes, but I only have one Vigil of Heroes (season of arrivals) Titan Mark, and it looks like this.

![image](https://user-images.githubusercontent.com/25425159/86188435-c80fb480-bb7d-11ea-863f-faa6dc9ac28c.png)

**Comment by sundevour** [comment]
this is intended, you have (1) vigil of heroes and (1) solar arrival mod helmet so we skip some buttons to save space

**Comment by bhollis** [comment]
Seems like something is still wrong then, in the second example it shows "Vigil of Heroes (1)"

**Comment by sundevour** [comment]
in the second example, there is (1) vigil of heroes, and (2) arc arrival mod items. since their contents are different both are shown

**Comment by bhollis** [comment]
Ah, got it. So it sounds like this is working as intended then.

**Comment by sundevour** [comment]
i am happy to entertain that it's bad ui, just. it's also weird to have 2-3 buttons that all say (1) and lead to the exact same item

**Comment by philkernick** [comment]
I think it's inconsistent UI.  Bad is subjective. I accept that on small screens saving space makes sense, but on any reasonable sized screen it doesn't.

**Comment by sundevour** [comment]
i agree not much space is saved but since there's no animation or even (currently) button highlighting, i am more trying to avoid the experience of clicking a button and nothing apparently happening

**Comment by philkernick** [comment]
Fair enough.  I was confused by the lack of buttons to click on.

I use the comparison panel for more than comparison, and for armor the counts across the top are my primary use of the tool.  Answers the "how many of these" do I have questions without having to compose a query.
