### ISSUE TITLE
Feature Request: Customizeable or More Categories

### ISSUE THREAD

**Issue by unarj** [DestinyItemManager/DIM#5387]
I would like to mark stuff as PvE or PvP, possibly some other labels and don't really use other categories. would be nice to be able to set the category names, changing the icon would be a nice-to-have also.

thoughts?

**Comment by wein3967** [comment]
This request has come up many times in the past. The developers have provided their response [here](https://github.com/DestinyItemManager/DIM/wiki/Frequently-Requested-Features#add-more-tag-values).

**Comment by unarj** [comment]
thanks for the response.  I did search the issue DB before posting, guess I should have looked more.  shame, would be nice to find PvP loadouts by icons instead of using notes.  c'est la vie.

**Comment by wein3967** [comment]
Yeah, the search can be tricky. I have to remember to search all issues, not just "open" ones to see if a question has popped up before.
