### ISSUE TITLE
Can we have option to unwind all possible builds

### ISSUE THREAD

**Issue by humandxp** [DestinyItemManager/DIM#5388]
cos those arrows dont work, and why even they are there if there is only one option, cos i can only swap leg armor, but it shows that all pieces have different options.
![aaaa](https://user-images.githubusercontent.com/24486599/86189204-ce2f7200-bb38-11ea-9265-13d99de8e774.png)

next based on loadout i had an idea for useless parts removal, its easy to implement cos it uses loadout code.
for example right now based on setting it gives you list ot T31, then T30, then T29, but for example im not interested in keeping parts that are T28 and lower, so there is slider where you set min as T29, so it tags all pieces as trash, and then everything what is in T29,30,31 we remove trash tag. that way we marked all pieces that are below T29 and are not used in T29,30,31

**Comment by ryan-rushton** [comment]
> for example im not interested in keeping parts that are T28 and lower, so there is slider where you set min as T29, so it tags all pieces as trash

That's not really how this works. A single armour piece could be found in multiple builds so if you excluded it as trash you could suddenly lose a number of higher tier builds.

In general changes in this area are really difficult but we have a number of things in the works that hopefully make it easier to use.



> cos those arrows dont work, and why even they are there if there is only one option, cos i can only swap leg armor, but it shows that all pieces have different options.

Yeah the arrows are not overly intuitive as they can relate to one of two options. A single armour set had multiple pieces to make it up OR that stat combination had multiple armour sets that achieved it. I would like to do something to make these more obvious but it's not an easy thing to convey on screen.

**Comment by humandxp** [comment]
i dont talk about excluding, only tag every piece of armor as trash, then with every armor possible that fits into T29,30,31 we remove tag. so that simple method we taged all armor that is below T29 and isnt used in T29,30,31.
and now you can look into vault and search for armor pieces with trash tag, remove tag or remove armor.
