### ISSUE TITLE
Move popup location for duplicate items on page.

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#539]
If a view has two or more of the same items (basically the same exact element, not the same item hash), regardless of which is clicked, the move popup only ever appears above the first one added to the page.

<img width="471" alt="screen shot 2016-05-20 at 12 59 04 am" src="https://cloud.githubusercontent.com/assets/424158/15417668/71a4536a-1e26-11e6-8870-55d30f9ffdca.png">

This issue was found in, but does not block: #538

**Comment by bhollis** [comment]
I'm planning on rewriting the pop-up positioning, this'll force that to
happen.

**Comment by kyleshay** [comment]
ah, sweet!! thanks! :D
