### ISSUE TITLE
Dim do not loaded Intventory showing, cant open settings and other windows. I see black screen.

### ISSUE THREAD

**Issue by redoxz** [DestinyItemManager/DIM#5390]
Dim do not loaded Intventory showing, cant open settings and other windows. I see black screen.

I use Google chrome, Mozila, Edge. Problem only on my D2 account [https://skr.sh/s2wcQbEdosb?a](url)

**Comment by delphiactual** [comment]
Did you get the shader from twitch? if so, try https://beta.destinyitemmanager.com

@sundevour

**Comment by redoxz** [comment]
> 
> 
> Did you get the shader from twitch? if so, try https://beta.destinyitemmanager.com
> 
> @sundevour

very appreciate. im greatful. it is helped
