### ISSUE TITLE
Allow a user to view weapon perks, broken out by barrel, magazine, etc. in the "Organizer"

### ISSUE THREAD

**Issue by JustTooKrul** [DestinyItemManager/DIM#5394]
**Proposed change**
Have individual perk columns (e.g., barrel, magazine, Weapon Perk #1, Weapon Perk #2) in the "Enabled Columns" dropdown in the Organizer.

**How does this fit into your workflow?**
Right now, the "Perks, Mods, and Shaders" column is the only place to see weapon perks. However, where certain perks are displayed can vary greatly from weapon to weapon. Quickly comparing multiple weapons "at a glance" would be far easier with the weapon perks more uniformly displayed across multiple columns--especially when comparing multiple copies of the same weapon.

As it currently stands, it is faster to export weapons to a spreadsheet and compare them then use the Organizer.

**Comment by bhollis** [comment]
Try the "Weapon Traits" column, which is intended to be more of an "at a glance" view.

**Comment by JustTooKrul** [comment]
Oh snap, perfect! That's 99% of what I was looking for!

**Comment by bhollis** [comment]
Awesome, glad it helps!
