### ISSUE TITLE
Organizer enhancements

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#5396]
This is a list of some general ideas and enhancements to the new Organizer view. Ideally, we'd have each of these items split into their own pull requests. We'd also want to make sure that we [update the wiki](https://destinyitemmanager.fandom.com/wiki/Organizer) after some of the various changes land.

Hop over to the [discord](https://discord.com/invite/mtFqKbk) or leave a comment if you have questions.

- [x] Instead of showing `Weapon`/`Armor`/`Ghost` for the initial filters show `Weapon`/`Hunter`/`Titan`/`Warlock`/`Ghost`
- [x] Show the recoil direction graphic in the column (it's shown in the item popup) be considerate of horizontal space. (#6064)
- [ ] Ability to select/"pin" an item to compare others against (in relation to stats/perks/etc) It would also be neat to have a button on the item popup link to the organizer page with it pinned.
- [ ] #9200
- [ ] ~Select columns dropdown: Show the active/checked items at the top. They should be sorted by the column order they're displayed in. Use a line to separate the checked and unchecked. Unchecked items should sort a-Z in the dropdown.~
- [x] Add names to "icon-only" columns (lock icon, power icon, etc.) in dropdown. Only show the labels in the dropdown, columns should just show icon. (#8309)
- [ ] Split out toggles for perks/mods/shaders (maybe they all show in the same column but each can be shown/hidden.)
- [ ] If there is enough space, split the perk columns/mods/shaders horizontally, but still support grouping them vertically if space is tight.
![](https://paper-attachments.dropbox.com/s_2DC734861262C9D6116EF0006E7A7B03C9BCBDCB299388F4EB9B74C4E53F3BC7_1593632069453_Screen+Shot+2020-07-01+at+12.30.56+PM.png)

**Comment by Jacksonmills** [comment]
Started a branch for `Add names to "icon-only" columns (lock icon, power icon, etc.) in dropdown. Only show the labels in the dropdown, columns should just show icon.`

**Comment by Jacksonmills** [comment]
@kyleshay is this what you were thinking for the second to last checkbox?
![image](https://user-images.githubusercontent.com/19780885/163509801-5d324589-994a-4aaa-ad6a-ff8fa3a9af87.png)

**Comment by Jacksonmills** [comment]
also thinking the "Shaders" column might be better suited as the "Cosmetics" column
