### ISSUE TITLE
V3 screen space utilisation

### ISSUE THREAD

**Issue by Subject22** [DestinyItemManager/DIM#54]
Issue
--------
The V3 interface (while beautiful in every conceivable way) only uses about half of space available on a 1080p monitor. It would be great if it adapted to larger displays in some way.

Possible Solution
-----------------------
DIM could display two columns per character; starting with armour and weapons being side by side. Currently it displays one column per character and one for the vault, for a total of four columns, this way it would display seven columns total. This would necessitate better delineation between characters, perhaps with a vertical line. A very simple mockup of this idea is shown below.

Of course, this does make it harder to scan horizontally to compare items of the same type.

![screen shot 2015-04-26 at 6 14 30 pm](https://cloud.githubusercontent.com/assets/4090877/7336119/27561a1e-ec40-11e4-8544-408cfdee0ffd.png)

**Comment by the7egend** [comment]
I would probably consider setting a horizontal limit of 1280 Pixels, that seems to be a reasonable resolution to restrict the width to.  Not everyone is going to be using a 1920 Pixel wide monitor, it would be better if the design was responsive, but that in of itself is a huge undertaking.

**Comment by Senaxx** [comment]
Personally i'm using a 1920 pixel resolution and responsive would be the best solution, but requires a lot of work I presume. Limiting should never be an option I think.

While this solution seems a good option it should make it harder to scan horizontally. Isn't it possible to show more items depending on the resolution?

**Comment by SunburnedGoose** [comment]
I would limit it to 1+4 for guardians and five for vault space. That will
fill your 24" monitor easily.

**Comment by Subject22** [comment]
If you show more items then you lose the nice 3x3 + "one to the left" layout currently in place which mimics Destiny's own interface. I've actually tried it with more items in the horizontal direction and it's pretty terrible. It gets hard to tell what's equipped and what's not (because sometimes you just see a long line of icons with only a smaller separator to indicate that the first one is equipped).

**Comment by Senaxx** [comment]
V2 also used more verticale icons and I had totally no trouble with it being "readable" 

But whatever solution get's implemented I'm already happy with the current state :)

**Comment by Subject22** [comment]
It's a fair point that the current V3 layout is definitely good. I'd hate to see us tinker with it so much that it stopped being that way. 




I vote that it stays the way it is for now and that alternatives be considered for V4, once everyone's had plenty of time to use the new interface.

**Comment by Senaxx** [comment]
![](http://i.imgur.com/CeY50HD.png)

I made some changes to the layout and tried the 4 weapons on a row and made some spacings smaller and this fits nicely on a 1280 resolution and also works nice on a 1200 resolution and makes everything a bit more dense.

**Comment by Subject22** [comment]
Oh yep. Looks pretty good. I still really liked the direct parallel to Destiny's interface with the 3x3 grids. Either way, I'd like to see further delineating between equipped and unequipped items. At the moment it's just a slightly wider space.

**Comment by kyleshay** [comment]
we now have a condensed view. may be iterating on it as we roll out a more responsive UI.
