### ISSUE TITLE
Loadout dropdown for the vault showing extra options

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#5402]
We should consider hiding the "Equipped" button in the loadout dropdown for the vault, as well as the "Randomize" functionality in the vault. We should also hide the "class specific" loadouts - "Warlock only" loadouts shouldn't show as an option in the vault - only loadouts that are for "Any class". 

You should still be able to create a loadout - just not one from equipped in the vault.

**Describe the bug and how to make it happen**
1. Open the inventory screen
2. Click the vault dropdown to view loadouts
3. "Equipped" button is shown / "Randomize" row is shown

<img width="235" alt="Screen Shot 2020-07-02 at 12 49 37 PM" src="https://user-images.githubusercontent.com/424158/86403528-be13b180-bc62-11ea-97d2-45089f54b481.png">

**Comment by bhollis** [comment]
Good points! Actually, now that "add equipped" is in the loadout drawer, it's kind of redundant everywhere, though I still use it.

As far as the class-specific loadouts, they show up in the vault menu because people might want to move their class-specific loadout to the vault.

**Comment by kyleshay** [comment]
Ah, I had a loadout that was just to equip things in my warlock set. I can see the benefit of using it to store em in the vault.
