### ISSUE TITLE
LO: Inform user to finish filter selection in mobile 

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#5417]
From Discord:

![image](https://user-images.githubusercontent.com/4798491/86515551-e9b7a880-bdd6-11ea-96ba-522daaebfb23.png)

Transcription:
Loadout optimizer keeps showing 0 results on mobile anytime I lock or exclude any item on mobile. Is this a known issue? Didnt see anything pinned for it in this or known issues channels

![Screenshot_20200704-110652_Chrome](https://user-images.githubusercontent.com/4798491/86515479-58e0cd00-bdd6-11ea-91a4-a108fea3cc33.jpg)

Happens with any item, also in the exclude item slot. I used the ghost in above example to limit results with different ghosts. But it displays 0 results

Hmm I just got it to work for the first time ever! Solution: have to tap in the dark grey window area next to locked item -> then tap Filters to hide the filter menu. Only then does it display and allow scrolling

**Comment by delphiactual** [comment]
seems the webworker is waiting for you to finalize your selection on the filter before it processes anything, which it should do. So maybe make that more obvious somehow.

**Comment by ryan-rushton** [comment]
Ghosts aren't included anymore so I need to remove those from all the pickers.

As a side note I can't reproduce this on Safari for iPhone. It did almost catch me out as I selected a locked item with a stat lower than the minimum total stat setting. We should ignore that setting if an item is locked?

**Comment by ryan-rushton** [comment]
Figured it out with the help of @sundevour. The issue is when an item is locked the filter section becomes bigger than the screen and subsequently the user gets stuck in a scrollable css element. I will fix the CSS properly this week but I have added a little note on mobile to tell users to collapse filters for now.
