### ISSUE TITLE
The ability to tag shaders

### ISSUE THREAD

**Issue by GeekyEggo** [DestinyItemManager/DIM#5419]
**Proposed change**
The ability to tag shaders.

**How does this fit into your workflow?**
Every now and then I have a clear out of shaders, but it's tricky to keep track of which shaders I like; it would be great if we could...
1. Search for `is:shaders tag:keep`
1. Transfer search to Vault.
1. Safely dispose of remaining shaders in my inventory at Rahool.
1. Transfer search back.

**Comment by delphiactual** [comment]
Dupe https://github.com/DestinyItemManager/DIM/issues/2757

**Comment by GeekyEggo** [comment]
Thank you @delphiactual, I did a quick search but wasn't able to find this. Appreciate the tag. :)
