### ISSUE TITLE
Item stat display is "compressed" in build 3.6.0.32989

### ISSUE THREAD

**Issue by rudimentsofgruel** [DestinyItemManager/DIM#542]
Running Chrome Canary for Mac - hovering over any item (with "Always show item details", "Display primary stats", and "Enable advanced stats" all enabled) and the bars are all very narrowly compressed.  So, even something with a very high stat value is not using more than, say, 5% of the entire bar (the numerical display of each line stat is accurate).  

I do not believe this was present in the previous build, but possibly was...  

![screen shot 2016-05-22 at 7 28 45 pm](https://cloud.githubusercontent.com/assets/19522648/15457773/df849d98-205d-11e6-91ec-a5415b87ec46.jpg)

**Comment by kyleshay** [comment]
Thanks for the report, I think that @bhollis JUST fixed that, haha. Keep an eye out for `3.6.0.34189`, and let me know that if you're still seeing the issue.

**Comment by bhollis** [comment]
Yeah I think my fireteam did not appreciate me fixing that during a Challenge of Elders run...

**Comment by rudimentsofgruel** [comment]
Indeed, .34189 just pulled down this morning and appears to have fixed it!
