### ISSUE TITLE
Add PVP/PVE tags

### ISSUE THREAD

**Issue by MadMacs77** [DestinyItemManager/DIM#5427]
**Proposed change**
In the item tagging list, pease add "PvP" and "PvE", to add an additional level of organization for users

**How does this fit into your workflow?**
I like options in my organization

**Comment by delphiactual** [comment]
[We go in to reasons why we won't here](https://github.com/DestinyItemManager/DIM/wiki/Frequently-Requested-Features#add-more-tag-values).

Dupe  #5180
