### ISSUE TITLE
View stats on vendor items

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#543]
Can we expand the vendors we can view item quality beyond Xur?

https://twitter.com/DestinyGameFan/status/734702851650392065

**Comment by bhollis** [comment]
That PR is almost ready to go, but I'm traveling a lot. Maybe next week?

**Comment by bradchoate** [comment]
Oh this could be really interesting and helpful. On the Min/Max screen, you could include vendor items as potential gear you could equip and mark them as "you just need to buy this first".

**Comment by bhollis** [comment]
This is coming.

**Comment by bhollis** [comment]
I misinterpreted this - the PR I just submitted makes it totally possible, but doesn't include other vendors' inventory.

**Comment by ericnelson0** [comment]
I'm working on this.
