### ISSUE TITLE
Algorith still doesnt calculate all possible combinations

### ISSUE THREAD

**Issue by humandxp** [DestinyItemManager/DIM#5432]
1st picture is default view of loadout optimizer, where it shows that i can have max 6 resilience
2nd picture i lock in place head armor and now resilience jumps max to 7
3rd picture i choose min resilience 7 so as result i have that coda helmet and exotic karnstein
4th picture now lets lock just karnstein, now i suddenly can have resilience 8 as max
![aa](https://user-images.githubusercontent.com/24486599/86610800-bf681580-bfa5-11ea-8ced-0efa298f5cca.png)
![bb](https://user-images.githubusercontent.com/24486599/86610805-c0994280-bfa5-11ea-932f-f5b009918521.png)
![cc](https://user-images.githubusercontent.com/24486599/86613012-e7a54380-bfa8-11ea-83e6-486af710948d.png)
![dd](https://user-images.githubusercontent.com/24486599/86613016-e8d67080-bfa8-11ea-8edb-050ebfa4b421.png)

**Comment by ryan-rushton** [comment]
#5423 should fix this I think.

**Comment by ryan-rushton** [comment]
@humandxp can you please check the latest version of https://beta.destinyitemmanager.com/ (it it wants to update make sure to do it) and see if that is fixed for me.

**Comment by delphiactual** [comment]
Ensure you are on `6.19.0.7490`

**Comment by humandxp** [comment]
yes now shows 8, after assume masterworked 9 as max.
thank you
