### ISSUE TITLE
Loadout Optimizer Max Stats Issue?

### ISSUE THREAD

**Issue by bro-kass** [DestinyItemManager/DIM#5433]
**What version of DIM are you using?**
6.19.0

**What Browser and OS are you using?**
Chrome Browser & Windows 8.1

**Describe the bug and how to make it happen**
My max stat values plummeted for no real reason in the loadout optimizer.
I have a loadout saved with 7 recovery and now when I attempt to make a new loadout in the optimizer my max recovery is 4.
I did not delete any gear and I do not have any gear excluded or locked. 
This seems to have just popped up out of nowhere

**Comment by bro-kass** [comment]
Upon further inspection, the gear in my saved loadouts is no longer used to calculate stat mixes for some reason

**Comment by delphiactual** [comment]
So dupe #5432

**Comment by bhollis** [comment]
Hard to tell - #5432 isn't very clear. https://github.com/DestinyItemManager/DIM/pull/5423 probably fixes most of the issues folks are seeing.

**Comment by ryan-rushton** [comment]
As Ben mentioned #5423 is designed to widen the stat ranges to everything being process rather than the sets being displayed on screen.

**Comment by ryan-rushton** [comment]
I believe #5432 and #5431 are dupes but this one is the clearest.

**Comment by ryan-rushton** [comment]
@bro-kass can you please check the latest version of https://beta.destinyitemmanager.com/ (it it wants to update make sure to do it) and see if that is fixed for me.

**Comment by delphiactual** [comment]
Ensure you are on `6.19.0.7490`

**Comment by bro-kass** [comment]
@ryan-rushton @delphiactual 
it works!

**Comment by ryan-rushton** [comment]
Awesome thanks for the report.

**Comment by bro-kass** [comment]
thanks for the quick response!

**Comment by ryan-rushton** [comment]
Just trying to make gear management easier 😄
