### ISSUE TITLE
Loadouts: Add button to add all unequipped items

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#5434]
We have a button for equipped items, it'd be nice to do it for unequipped items.

Alternately we could allow creating a Loadout from a search, but that's a bit trickier from a UX perspective.

**Comment by johnpschmidt** [comment]
Hi, 

Newish developer and I'd like to try and take this on. This would be pretty much just grab what isn't currently in inventory for the selected load out, right? Like would this be used to add unequipped items just to the inventory to swap out? Just want to make sure I'm understanding correctly.

**Comment by bhollis** [comment]
When the loadout editor is open (the drawer at the bottom of the screen) we have a button that'll add all of the equipped items on a character to the loadout you're editing. This task is to ad another button that adds all the unequipped items currently on that character to the loadout. This lets people set up a character the way they like, and then "snapshot" that setup as a loadout.
