### ISSUE TITLE
Remove version from the Page Title

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#544]
https://www.reddit.com/r/DestinyItemManager/comments/4kn3go/req_remove_the_ver_from_the_title/

User wants to use automation, and has to redo their automation on each release because of the title changes.

**Comment by bhollis** [comment]
Why not just write better automation?

**Comment by SunburnedGoose** [comment]
It's easy enough to have a static title.  Version number is in the extension meta data; just a right-click away.

**Comment by kyleshay** [comment]
could also make it the title text for the DIM logo or something... it's nice to know what version people are running for debugging. maybe we always console.log it on page load? that way if we're asking for the dev tools msg anyway....?

**Comment by SunburnedGoose** [comment]
Even if the javascript just doesn't load, you just right click the icon for DIM, and manage extensions.  You won't get a version number in the mobile client for example.
