### ISSUE TITLE
Class Based Loadouts are broken in 3.6.3

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#545]
https://twitter.com/DragonVsKira/status/734929468888780801

**Comment by kyleshay** [comment]
What's the issue?

**Comment by SunburnedGoose** [comment]
Class specific loadouts when changed are showing up in other classes.

[T5iPRSMO8oW2jvDx8VNkHesI93XwAnwBnYuhOshG-iY.mp4.zip](https://github.com/DestinyItemManager/DIM/files/278684/T5iPRSMO8oW2jvDx8VNkHesI93XwAnwBnYuhOshG-iY.mp4.zip)

**Comment by SunburnedGoose** [comment]
Create from Equipped.  
Give it a name.  
Save it.

It should show up on all characters.

Create from equipped again.
Give it a name.
Assign it a class.
Save it.

Now you'll see the error.  It's showing up on all characters even though it's specified for just one class.
