### ISSUE TITLE
Loadout undo should not disappear if it was unsuccessful

### ISSUE THREAD

**Issue by paulv** [DestinyItemManager/DIM#5454]
**What version of DIM are you using?**

6.20.0 release.

**What Browser and OS are you using?**

Chrome on ChromeOS.

**Describe the bug and how to make it happen**

Create a loadout. Load it in orbit. Go to the tribute hall. Undo the loadout. It will say something about how many items were transferred but that there were errors (because the tribute hall is not orbit/social space). The option to undo the loadout is removed. I think that if there is an error the option to undo the loadout should not be removed so that you can go to orbit and try again.

**Include devtools console logs**

N/A

**Comment by GrimmiMeloni** [comment]
I assume by "the option to undo the loadout" you refer to the options menu item "Before <loadout name>" ?

![image](https://user-images.githubusercontent.com/5851977/101133008-3d3d5500-3608-11eb-96b6-7aa461f691ab.png)

If so, I cannot reproduce no Firefox 83,0 / Chrome 87.0.4280.88 / Win 10. 

With the tribute hall gone, I tested on the moon (at Eris). 
I **do** get the error notification in DIM, but I also have the undo option in the menu of my Character see screenshot above.

Maybe a problem specific to ChromeOS, but I have no such device available to check.
