### ISSUE TITLE
Add mods like Traction and Powerful Friends to Loadout Optimizer

### ISSUE THREAD

**Issue by maxwellcsutton** [DestinyItemManager/DIM#5455]
**Adding specialty mods to Loadout Optimizer**
Mods like Traction, Powerful Friends, and Radiant Light are critical to hitting desired stat totals and make using Loadout Optimizer a little unintuitive.  Sure, for Powerful friends you could set min and max mobility to t8, but there's no current support for Traction (since it is +15 and Loadout Optimizer tries to get as close to a tier as possible), and it is one of the most used boot mods.  If Traction support is added, the same logic could be re-used for Powerful Friends and Radiant Light so I figure they might as well be added as well.

Since I assume locking a mod/perk sets a flag somewhere, in the function that sums up the stat totals of armor you could just check for that flag and add 15 mobility if Traction is a locked mod, etc.  I'm sure this has been suggested before, and maybe this is more complicated than I think if it hasn't been selected for development.  Either way, thanks for all your hard work!

**Comment by ryan-rushton** [comment]
It already does that. If you lock traction it will add the stat value that is contained on the mods api data. From my understanding traction was +5 but it has been a while since I looked at that.

**Comment by maxwellcsutton** [comment]
Traction adds +5 visible, but also adds +10 hidden mobility.  Thanks for the response, I didn’t know that it already counted the +5.

**Comment by maxwellcsutton** [comment]
Just wanted to come back to say this; I was trying to use the Loadout Optimizer a month ago with adding mods/perks/locking items to achieve a specific set of stats for PvP and I couldn't get it to work the way I wanted it to.  Whether it was a combination of my lack of understanding and low number of Armor 2.0 armor after coming back from not playing since year 1 (more likely) or some kind of bug (less likely); I was unable to get the information I wanted.  After seeing your comment, I went back and re-tried it and was able to use the feature exactly as I hoped I would be able to.  So thank you for responding, and the only thing I would ask at this point is to change Traction to adding +15 mobility instead (and maybe a note saying that 10 of it is hidden and won't show up in game when it is moused-over).  If you are curious, you can check that Traction gives 10 hidden by equipping traction with an end result of 90-99 mobility, then Hunter dodging and the cooldown should be roughly 9.32 seconds instead of 11 seconds like Tier 9 mobility would have.  Thanks for your hard work!

**Comment by ryan-rushton** [comment]
Thanks! Glad you find it useful. 

The problem with adding those hidden sandbox updates is that we need to manually maintain them and keep an eye on them to see if anything changes. These are the kind of things that are not included in sandbox updates from Bungie, so unless Bungie starts adding a larger stat value to the mod itself it might just have to be community knowledge.

For the other mods, Powerful Friends ect, we need to update our handling of stats in a couple of scenarios. I am planning on dealing with this in #5381. 

If you want exact values unfortunately you have to remove any seasonal mods that have stat values associated with them (it is what I currently do). Bungie are aware of us wanting better handling of these stats.
