### ISSUE TITLE
Compare Items only compares exotic armour of the same element

### ISSUE THREAD

**Issue by flyzipper** [DestinyItemManager/DIM#5459]
Clicking Compare Items for an exotic piece of armour will only show other exotic armour which matches the element on the original.

Steps to reproduce

- have multiples of the same exotic armour, but with different elements
- select Compare Items on one of the pieces of armour
- exotic armour which matches the item, **including the specific element**, will be displayed in the compare list
- example - I have 3 Dunemarches, 2 solar, 1 void... selecting solar Dunemarchers and will compare the 2 solar element armour pieces, however selecting Compare Item on the void piece will only show that lone item.

Expected outcome

- comparing an exotic piece of armour should show all matches regardless of energy.

**Comment by sundevour** [comment]
![image](https://user-images.githubusercontent.com/31990469/87855447-4635c000-c8cd-11ea-87af-3c62ef601d2e.png)
see the first two buttons at the top here.
there should be options for both same element, and all elements.

if this isn't the answer, can you take a screenshot of your problem?

**Comment by flyzipper** [comment]
Thanks for posting this example.
It illustrates what I attempted to describe... the default view only shows matches of the same element type.

In your example, I'd expect all 5 Orpheus Rig pieces to be displayed, not just the void pair.
The UI would then have a tab to drill down into _each_ element (void, solar, arc).

As it is, the default view just shows a subset of the armour pieces you own. Clicking on the 2nd tab "Orpheus Rig (5)" shows all, and you can click on the 1st tab again to show just the void pair, but there's no tab to filter down to the arc or solar versions (if there's a "bug", I suppose this would be it... missing the ability to filter for each element).

From a usability standpoint, the current UI behaviour is inconsistent because the compare results are based on the element type you started the comparison with. It would be more intuitive if all armour pieces were shown, regardless of which element you clicked on, and the UI allowed filtering down for _each_ element.

It's not a bug, I'm suggesting an approach that feels more consistent, intuitive and usable (admittedly... to me).

**Comment by bhollis** [comment]
I personally think by default we should show only the item you started with, and then you can use the buttons to select other things to compare with.

**Comment by flyzipper** [comment]
I understand that perspective, but two things:

- to me, the "item I started with" is Orpheus Rigs... not _Void_ Orpheus Rigs. The analogy for weapons would be if the compare only showed the weapons which matched the masterwork of the item you clicked on... not all weapons of the same type, regardless of masterwork type.
- the issue with "you can use the buttons to select other things to compare with"... there are no buttons to allow the comparison to other elements of the same armour. Admittedly, you can use "Orpheus Rigs(5)", but you can only toggle back to the original void items (example above)... not to solar or arc versions of the same type. 

Not a big deal, and it's workable as-is, but it could be more consistent and intuitive.

I'll leave it here.

Have a good day, and thanks for everyone's work on the project.

**Comment by bhollis** [comment]
Closing in favor of #5834 and #5835
