### ISSUE TITLE
Users are missing rank icons in Faction panel.

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#546]
https://twitter.com/Phantom_Maestro/status/734916439019278336

**Comment by kyleshay** [comment]
They don't have display prim stat on... we should just remove that setting :/

**Comment by SunburnedGoose** [comment]
Yep, or make it the default.

**Comment by bhollis** [comment]
It should already be the default. We can remove the option though - post-TTK, primary stat matters so much we should always show it.
