### ISSUE TITLE
Add button / mode to move ALL unequipped items to Vault

### ISSUE THREAD

**Issue by KiaArmani** [DestinyItemManager/DIM#5461]
**Proposed change**
Add a button that allows a user to move all weapons and armor that are currently not equipped to the Vault.
Add a button that enables a clear mode which moves all drops to Vault by default.

Something like this:
![grafik](https://user-images.githubusercontent.com/3679543/87665164-c7267780-c766-11ea-9e5e-448ab18c34c6.png)

**How does this fit into your workflow?**
While playing Destiny you usually get a fair amount of drops from the game. While there is farm mode to prevent any item to get destroyed, I find it annoying that my inventory is cluttered with drops I'm likely to dismantle or deal with later. When I'm playing I just want the items I chose to be in my inventory and I think DIM can help with that.

**Comment by bhollis** [comment]
https://destinyitemmanager.fandom.com/wiki/Category:FAQ#How_can_I_clear_all_non-equipped_items_from_my_active_character.3F
