### ISSUE TITLE
Organiser doesn't show current slotted seasonal mods

### ISSUE THREAD

**Issue by ryan-rushton** [DestinyItemManager/DIM#5464]
If an item currently has a seasonal mod slotted it is not visible in the organisers columns but it is in the item popup.

The screenshot is from dev (please disregard some unusual things you can see) but I checked the main app and it is an issue there.

![image](https://user-images.githubusercontent.com/7344652/87845464-0b527d00-c90b-11ea-9702-cceabc77e4c6.png)

**Comment by sundevour** [comment]
bonus bug:
izanagi is showing way too many things in the Traits column
![image](https://user-images.githubusercontent.com/31990469/87855071-c0b11080-c8ca-11ea-8332-013f04c25300.png)

**Comment by sundevour** [comment]
![image](https://user-images.githubusercontent.com/31990469/87912033-78f0cd00-ca21-11ea-8ee0-f5c3242cc45b.png)
works with other stuff just not arrivals. a weird side effect of no collectibleHash. though, not sure why that is used as a condition

**Comment by bhollis** [comment]
At the time it was the best way to distinguish mods from other plugs
