### ISSUE TITLE
Auto Take out from Vault?

### ISSUE THREAD

**Issue by hollyywwoodd** [DestinyItemManager/DIM#5468]
**What version of DIM are you using?** v6.20.0.7539 beta
Find the version in "About DIM" from the menu (the button with three bars on the upper left of the screen). Is the DIM icon orange, or blue?

**What Browser and OS are you using?** app through chrome
It helps to know what type of browser and what version you're using. Have you installed DIM as an app through Chrome or Safari?

**Describe the bug and how to make it happen** yesterday everything was fine.. today i sign on and everytime i move a wepon to the vault, one gets put on the character im switching it from. ive used dim for awhile now so i know the exceptions for when it automatically does it. but i have several weps on this one and it just keeps giving my random weps from my vault everytime i move one to the vault.
Tell us what's wrong. A great format for bug reports is "I did X, and I expected Y, but instead Z happened." If it helps illustrate the issue, please add screenshots to help explain your problem.

**Include devtools console logs**
If you can, open the devtools console (ctrl+shift+J on PC and cmd+option+J on Mac) and paste what you see in the window that pops up:

```
Paste console logs here
```

**Comment by delphiactual** [comment]
How full is your vault?

**Comment by hollyywwoodd** [comment]
You win! Thread closed. 🤣
