### ISSUE TITLE
Title attribute not working for organizer headers

### ISSUE THREAD

**Issue by Revadike** [DestinyItemManager/DIM#5474]
This can be fixed by putting the title attribute on the container instead, like instead of
![image](https://user-images.githubusercontent.com/4411977/87865096-42f41000-c971-11ea-9ebe-43237d4096b3.png)
do it like this
![image](https://user-images.githubusercontent.com/4411977/87865102-543d1c80-c971-11ea-80a5-d6cab4cdbc8d.png)

Only then it works:
![image](https://user-images.githubusercontent.com/4411977/87865106-60c17500-c971-11ea-8020-57fd0d5f2d33.png)

**Comment by bhollis** [comment]
Unfortunately due to the way these are constructed, that isn't super easy. We need to wrap the image in a span or something so the touch suppression doesn't interfere with tooltips.

**Comment by Revadike** [comment]
> Unfortunately due to the way these are constructed, that isn't super easy. We need to wrap the image in a span or something so the touch suppression doesn't interfere with tooltips.

Yes, tell me about it. I originally wanted to make a PR instead, since it seemed so easy, but it's so much. I'd still appreciate it, since I doubt many know the icons by heart.

**Comment by bhollis** [comment]
Cool, I have a fix at https://github.com/DestinyItemManager/DIM/pull/5477

**Comment by Revadike** [comment]
Yup, that fixes it. Thanks!
