### ISSUE TITLE
single shot GLs mag too low

### ISSUE THREAD

**Issue by sundevour** [DestinyItemManager/DIM#5480]
@ryan-rushton 
changes to stat calcs did something weird to single shot GLs

they are showing 0 magazine in item popup
![image](https://user-images.githubusercontent.com/31990469/87916044-c6703880-ca27-11ea-86ee-e7359dd1dd59.png)

and -12 in compare
![image](https://user-images.githubusercontent.com/31990469/87916060-cc661980-ca27-11ea-8c9f-38b3a8f0bcd0.png)

before left, after right
![image](https://user-images.githubusercontent.com/31990469/87915801-742f1780-ca27-11ea-87b5-8c96e1ada6b9.png)

i am assuming they have their stat cranked super low, and rely on a cap that keeps mag at at least 1?

**Comment by ryan-rushton** [comment]
Will check this out

**Comment by ryan-rushton** [comment]
This seems to just be an issues with special breach grenade launchers. From my understanding it only effects mountaintop and the militia's birthright.

**Comment by bhollis** [comment]
We need some tests :-)

**Comment by sundevour** [comment]
https://github.com/DestinyItemManager/DIM/pull/5481
