### ISSUE TITLE
Put weapon type below name

### ISSUE THREAD

**Issue by dhinged** [DestinyItemManager/DIM#549]
Not sure if this is on the list of to-do, but I'm officially making a request if I can do that here (please shoot me down if I'm not supposed to), or I'll just do it myself when I find the time to finish learning how to edit extensions.

**Comment by bhollis** [comment]
Right now the type is beside the name, because we're running out of space for that popup. See #491.

**Comment by kyleshay** [comment]
can continue discussion in the issue @bhollis listed

**Comment by dhinged** [comment]
The font can be shrunk, and the pop-up has plenty of room if it's positioned properly; I've already seen it go off the screen vertically top or bottom (obscuring the name or buttons) when it can fit on the right or left, this is something I can look into.

Also the hover pop-up can contain the gun type below the name. There's many things I can add to the extension, I just need to learn how to do it.
