### ISSUE TITLE
“Sort items by” can’t be changed

### ISSUE THREAD

**Issue by maviza67** [DestinyItemManager/DIM#5491]
I’m been unable to change “sort items by” using a new criterion for several months. It seems locked when using iPad and pc.  I can’t deselect sort categories, select new ones or change the priority of the ones selected.

**Comment by bhollis** [comment]
You're right, the arrows/checkmarks don't seem to do anything. But you can still drag and drop.

**Comment by maviza67** [comment]
Thanks for the work around. Cheers.
