### ISSUE TITLE
Show stat effects in tooltips and loadout optimizer

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#5500]
I'm willing to be convinced that maintaining a table of sandbox values is too much trouble, but it'd be helpful especially in the loadout optimizer to understand what each tier actually means. We could do it only for stats that are explained in game (assuming they're accurate) or we could crowdsource: https://i.imgur.com/vzvBuza.png

**Comment by kyleshay** [comment]
linking https://github.com/DestinyItemManager/DIM/pull/6033
