### ISSUE TITLE
Table row highlight

### ISSUE THREAD

**Issue by Revadike** [DestinyItemManager/DIM#5503]
Sometimes I have trouble identifying the correct row in a table (like in organizer). Having it highlight on-hover would ensure I'm looking at the right row.

**Comment by bhollis** [comment]
https://github.com/DestinyItemManager/DIM/tree/table-rows-color for my own future reference

**Comment by bhollis** [comment]
We added zebra stripes. I'd prefer not to do a full hover highlight.
