### ISSUE TITLE
Progression for the Sleeper Stimulant mission.

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#551]
The current view of this mission in DIM only has a single item.

![image](https://cloud.githubusercontent.com/assets/984608/15507391/0a92c09e-2191-11e6-86b1-efd5c064221c.png)

Nigel at IC has found out that the mission steps are on a talent grid node within the entity.  This is what he found, 

![image](https://cloud.githubusercontent.com/assets/984608/15507426/309b650c-2191-11e6-9864-92c78f963142.png)

**Comment by TheHandsomeCoder** [comment]
I can pick this up if you like, Do we want to put nodes onto all the mission objects or do would you prefer a service that we can specify hash specific fields.

**Comment by SunburnedGoose** [comment]
Dunno.  How does the service we use parse the requirements for other bounties and quests?  This one is a little different, but it should be presented similarly as to the other items.

**Comment by TheHandsomeCoder** [comment]
We currently pass back objectives for the items. In the sleeper simulants
case we pass back the repaired objectives. The progression nodes themselves
are stripped in the getItem() function of the stores service. My initial
thinking is we have a service we can hit to see if we should add the nodes
to the item. Then update the item directive to show them if the progression
nodes exist. We can then control this for whatever items we want.

**Comment by bhollis** [comment]
We should just include talent grids on anything that has them. That's what
we do for objectives which lets weapons have objectives.

**Comment by kyleshay** [comment]
Guessing this is a duplicate (but more generic version) of #895
