### ISSUE TITLE
new power fractions are showing decimal fractions sometimes?

### ISSUE THREAD

**Issue by inexorableAce** [DestinyItemManager/DIM#5515]
**What version of DIM are you using?**
prod but presumably beta as well if you can get the situation the same?

**What Browser and OS are you using?**
Win 10 chrome and iOS, likely others 

**Describe the bug and how to make it happen**
the decimals in the fraction are causing text overlap as the fraction gets REALLY long. seems to happen when the character has all powerless items during that one part of the game, hard to say I cannot reproduce it myself. the user reported that the only titan gear is all white and powerless so I assume that's part of the issue. 
![image](https://user-images.githubusercontent.com/29002828/88494345-b4d8e480-cf83-11ea-863e-46aad018068a.png)

attn: @sundevour

**Comment by sundevour** [comment]
hahhhhh

**Comment by delphiactual** [comment]
Closed by #5516
