### ISSUE TITLE
A way to sort by armor set 

### ISSUE THREAD

**Issue by invrtd** [DestinyItemManager/DIM#5517]
**Proposed change**
A way to sort by armor set

**How does this fit into your workflow?**
It would make it easier to have one of each piece of armor for those who would like to save them for when transmog is released, especially for those items you cant get from collections

**Comment by bhollis** [comment]
Wouldn't sorting by name do this?

**Comment by invrtd** [comment]
that doesn't always work

**Comment by bhollis** [comment]
I think you probably want to use https://destinysets.com
