### ISSUE TITLE
cant press and hold perks if they start off screen on mobile view.

### ISSUE THREAD

**Issue by inexorableAce** [DestinyItemManager/DIM#5518]
**What version of DIM are you using?**
Version 6.22.1 (release), built on 7/27/2020, 12:03:08 PM

**What Browser and OS are you using?**
ios Chrome is the easiest to see it. but this also happens if you scale your window down on chrome for windows till you get the mobile view. It also happens on ios safari if you can get the conditions correct. 

**Describe the bug and how to make it happen**
when you click an item and the sheet pops up that shows the stats and perks, if the notes or wishlist notes or anything else causes the perks to be off screen, when you scroll to the perks and press / hold one to see the perk name / description nothing happens. the even seemingly does not even fire to create the tooltip

**Comment by TheBl4ckSh33p** [comment]
Same problem on Android. If you have to scroll to see perks there are no tooltips for them.

**Comment by TheBl4ckSh33p** [comment]
It seems to work with a long and strong press on the icons. But without scrolling  they appear with a simple light tap.

**Comment by bhollis** [comment]
Closing since item popups are shorter now

**Comment by bhollis** [comment]
https://www.reddit.com/r/DestinyItemManager/comments/jjbhd0/cant_view_perk_details_on_phone_if_i_have_to/

**Comment by bhollis** [comment]
iPhone 5S is shorter than you could imagine

**Comment by bhollis** [comment]
We're testing a new layout for perks on beta that doesn't rely on hover. Take a look and let us know how it is.

**Comment by bhollis** [comment]
Linking #7457

**Comment by bhollis** [comment]
This is still the case, but only affects mobile. I really need to create a repro code sandbox for popper.js
