### ISSUE TITLE
Score weapons to help players evaluate random rolls

### ISSUE THREAD

**Issue by banquin** [DestinyItemManager/DIM#5519]
Thanks for all the time and effort you all put into DIM. I am super proud to back the app and all of you!

**Proposed change**
Add scores to weapons that are calculated from crowd-sourced ratings on archetypes and perks to help me understand the quality of different weapons & rolls. I’ve written a more detailed proposal [here](https://docs.google.com/document/d/1tZw_hE6Hx8DB1ozybyiY5Apd0HXU4fbZ_4pnsDHqAcY/edit#). I realize I'm proposing a major feature, but hope even just a small part of this proves interesting to someone.

**How does this fit into your workflow?**
DIM’s role in my workflow makes it uniquely positioned to help me understand whether a weapon is good or not, based on a combination of my personal preference and what the community thinks is good.

I think the current answer to this type of request is the wish list feature, but most DIM users are using Voltron and might have trouble determining the relative quality of the dozens of wishlist weapons between their vault and fresh drops. Creating a custom wishlist with custom wishlist notes for every weapon would provide the level of control I’m looking for, but that feature geared toward power users (which I totally am), and I wrote this proposal with non-power users in mind. 

DIM's past weapon reviews feature did this to some degree. I think the proposal I linked above avoids many of the drawbacks of that feature that led to its removal after the introduction of random rolls.

Loadout Optimizer totally changed how I think about and interact with my armor. If this feature existed, it would do the same for how I interact with my weapons.

**Comment by scspriggy** [comment]
Some great ideas!  I always thought the "three-way 'thumbs up'/neutral/'thumbs down' evaluation of weapons" as you put it, was too simplified and DIM could provide better feedback on guns and rolls.  I think this enhancement would greatly help individuals make quick at-a-glance decisions.

**Comment by 48klocs** [comment]
The intention is good, but it feels like a long way to go to get back to where we are - someone else provides a list with a lot of data that people mostly agree with, except for a few odd cases where you don't (which will always be the case because good, well-informed opinions are still opinions).

In this hypothetical, who's recalculating the scoring for every archetype with every sandbox update?

**Comment by banquin** [comment]
There's nothing in Voltron (or any other wish list I've used) that I disagree with, so I don't really view this as solving that problem. I view it more as just going a step further by providing more data to the user (in the form of a useful number). Even if you reduced scope by removing user-level customization of scores, I think "scores you mostly agree with" is a meaningful improvement over the current UX for most users (which was itself a **major** improvement over most people not using wish lists).

To your point though, it is a large project to get there, so it's really entirely up to you & the team if you think the benefit is worth it.

I think there are a couple of options for updating the archetype scoring after a patch.
1. If the archetype scores are crowdsourced in the first place, just only consider user-generated scores updated_at after the patch. It will start rough but smooth out as more users update.
2. If the archetype scores are hard-coded (but overridable by users), ask a small group of trusted community members to maintain/update the list. 

There are probably other good approaches, but I think either of the above would get the job done. The point swing on scores in the most extreme case of an archetype goes from 10/10 to 1/10 in one patch (which I would argue has never happened), would be a maximum of 3 points. Most archetype adjustments would probably fall in the range of a 1-2 point adjustment on the final score, so the failure state for not updating these quickly is not that bad.

**Comment by 48klocs** [comment]
Ultimately, this seems pretty involved for what seems like a lateral move in functionality.
