### ISSUE TITLE
possibly incorrect ICH in isWeaponOrArmorOrGhostMod

### ISSUE THREAD

**Issue by nev-r** [DestinyItemManager/DIM#5521]
https://github.com/DestinyItemManager/DIM/blob/10ba1248949283bdb9e3d018fc9bc9cf7729cf25/src/app/wishlists/wishlists.ts#L84

could you please review this for intent/correctness? it doesn't appear to be an existing itemCategoryHash

**Comment by delphiactual** [comment]
Possibly https://data.destinysets.com/i/ItemCategory:4062965806

**Comment by 48klocs** [comment]
I know that was in there to filter out armor shaders and ornaments, it definitely seems like using the `Armor Mods: Gameplay` category hash would be a much cleaner way to accomplish it.

**Comment by delphiactual** [comment]
right now that hash matches nothing, because it is not ever included as an ich

**Comment by delphiactual** [comment]
Closed by #5535
