### ISSUE TITLE
possibly incorrect ICH in perk picker

### ISSUE THREAD

**Issue by nev-r** [DestinyItemManager/DIM#5530]
https://github.com/DestinyItemManager/DIM/blob/fd7476f76bbb187460c8202edc3e0713eb405372/src/app/loadout-builder/filter/PerkPicker.tsx#L206

had to jump back a blame or 2 but i think this line is yours?
can you confirm whether 56 (mainly ornaments) is intended? or maybe it should be 59 (generally, mods)?

can run on https://data.destinysets.com/ to check out matching items:
```js
$DestinyInventoryItemDefinition.filter(i=>(i.itemCategoryHashes||[]).includes(56)).show()
```
```js
$DestinyInventoryItemDefinition.filter(i=>(i.itemCategoryHashes||[]).includes(59)).show()
```

**Comment by delphiactual** [comment]
this line is filtering the ornaments out

**Comment by nev-r** [comment]
ok that is what i was leaning toward
