### ISSUE TITLE
Loadout optimizer can suggest invalid combinations for selected mods

### ISSUE THREAD

**Issue by AdamAlgaert** [DestinyItemManager/DIM#5532]
**What version of DIM are you using?**
Version 6.22.1.7682 (beta), built on 7/30/2020, 10:44:13 PM

**What Browser and OS are you using?**
Chrome Version 84.0.4147.105 (Official Build) (64-bit)

**Describe the bug and how to make it happen**
Select Oppressive Darkness, Special Finisher, and Powerful Friends mods and the loadout optimizer will show armor with an Arc class item and no other Arc pieces, but it's impossible to fit these 3 mods on a single class item because it would require 12 energy.

**Comment by ryan-rushton** [comment]
I am looking into this now but I am not sure its worth it to fix it for the current perk picker. It will definitely be in the new mod picker stuff I am readying though.

**Comment by bhollis** [comment]
Is this fixed on beta now?

**Comment by ryan-rushton** [comment]
No but it will be once we enable the new mod picker stuff. At that point I will be removing the old seasonal mods, so that will remove the issue. I will endeavour to get it ready for that this weekend.

**Comment by ryan-rushton** [comment]
This is now fixed and beta (potentially app soon), should we close?

**Comment by AdamAlgaert** [comment]
It looks fixed to me.  I like how it shows what slot to put each mod in too.
