### ISSUE TITLE
Loadout Bug?

### ISSUE THREAD

**Issue by H2OBigReese** [DestinyItemManager/DIM#554]
When using the pulldown menu for loadouts on my Warlock, all loadouts appear, while on other characters only allowed loadouts are appearing (as normal). The same is happening on the Vault when using that pulldown menu but im not entirely sure if that is a bug or not. 

https://gyazo.com/8267433734525adf3e269b08f8fefadf

I would think that the Vault needs its own subheading for loadouts so that Not every loadout appears in its menu

**Comment by kyleshay** [comment]
Thanks for the report, it's fixed in our development branch and should be going out live with the next update.

https://github.com/DestinyItemManager/DIM/issues/550

**Comment by bhollis** [comment]
It's intended for the vault. The problem for warlocks has been fixed and
the fix will be in the next release.

**Comment by kyleshay** [comment]
@bhollis FYI i'm branching master, cherry picking your fix and going to publish to chrome store
