### ISSUE TITLE
Armor spreadsheet headings no longer capitalized for stats

### ISSUE THREAD

**Issue by DHager** [DestinyItemManager/DIM#5541]
New issue in 6.23.0.

Previously the exported armor-spreadsheet would contain headings such as `Mobility (Base)`, now it has changed to `mobility (Base)`, with a lowercase first letter.

This breaks with the pattern of other headings... and incidentally caused an error in some scripts I use to rate armor.

**Comment by bhollis** [comment]
This is why I'm terrified to touch the Spreadsheets code... any little thing can blow up some workflow

**Comment by nev-r** [comment]
@DHager can you please confirm spreadheet exports are looking right?

**Comment by DHager** [comment]
Confirmed, thanks. (Version 6.23.0.7720 (beta), built on 8/3/2020, 2:16:58 PM)
