### ISSUE TITLE
Loadout Optimizer : Assume Masterwork EXCEPT EXOTIC

### ISSUE THREAD

**Issue by hh393** [DestinyItemManager/DIM#5543]
in Layout Optimizer "Assume Masterwork" checkbox already exists. If you can add another checkbox "Assume Masterwork EXCEPT EXOTIC" it will be very handy. 

Nobody simply dares to masterwork an exotic. Specially when you can get a better stat of that exotic armor. Currently exiting checkbox is useless for me. Because always also assume exotics as masterwork and it's useless. Everybody can masterwork regular armor but exotic masterwork is a rare case.

**Comment by ryan-rushton** [comment]
>Everybody can masterwork regular armor

<img src="https://user-images.githubusercontent.com/7344652/89381667-dd5b9e00-d73c-11ea-9689-e1cffc159e5d.png" width="400px"/>

**Comment by bhollis** [comment]
We could have a slider of "how many shards are you willing to spend".

**Comment by quetschke** [comment]
> 
> 
> We could have a slider of "how many shards are you willing to spend".

That would be awesome!

**Comment by hh393** [comment]
> We could have a slider of "how many shards are you willing to spend".

Good idea. It is more generic than my idea …

**Comment by ryan-rushton** [comment]
Closing, the new what are you willing to spend select just went into beta.
