### ISSUE TITLE
Loadouts drawer on mobile can cover inventory

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [DestinyItemManager/DIM#5547]
**What version of DIM are you using?**
6.23.0 Orange 

**What Browser and OS are you using?**
Chrome on Android 

**Describe the bug and how to make it happen**

When creating a new loadout I can't add a third item cause the pop-up at the bottom (loadout) is growing over the entire screen. Moving it down closes the loadout manager.

**Comment by bhollis** [comment]
It doesn't scroll for you?

**Comment by TheBl4ckSh33p** [comment]
The entire screen is covered and I can't add new Items after adding 2.

![Screenshot_20200804-183840_Chrome](https://user-images.githubusercontent.com/2725603/89320524-dde32e80-d681-11ea-90ef-2c369eed2ff1.jpg)
![Screenshot_20200804-183849_Chrome](https://user-images.githubusercontent.com/2725603/89320538-e20f4c00-d681-11ea-9cc1-d80b4c215475.jpg)

**Comment by bhollis** [comment]
Oh. Try using the labeled buttons.

**Comment by TheBl4ckSh33p** [comment]
It works with the buttons but it's much more complicated cause you have to find the item you are wearing in the huge list. Is it possible to lock the loadout manager in place to cover only half of the screen and allow scrolling on the main page and the manager?

**Comment by bhollis** [comment]
There's just not a ton of space to work with
