### ISSUE TITLE
Add the Challenge of Elders modifiers and character completion dots to the D1 Activities tab

### ISSUE THREAD

**Issue by jbccollins** [DestinyItemManager/DIM#5549]
Similar to how the modifiers and completion dots work for the Nightfall. If the D1 api allows for it I would like to see the Challenge of Elders be a part of the D1 activities page. I would be willing to work on this feature myself.

Currently I have to go to the D1 subreddit r/destinylegacy to see what the current Challenge of Elders modifiers are which is a bit annoying. Would be nice to have everything in one page on DIM.

**Comment by jbccollins** [comment]
Ah. Looks like this was included at some point and commented out: https://github.com/DestinyItemManager/DIM/blob/master/src/app/destiny1/activities/Activities.tsx#L159

Was this removed for a reason? Does it make sense to include the completion dots for Challenge of Elders? From what I can tell the API seems to return the completion state for both the 30k points requirement for the weekly weapon and the 90k points requirement for the weekly armor. Would it make sense to have two dots one for armor and one for weapon?

<img width="781" alt="Screen Shot 2020-08-04 at 4 05 43 PM" src="https://user-images.githubusercontent.com/8915552/89339781-b897f580-d66c-11ea-95a8-5825c1c809cc.png">

**Comment by bhollis** [comment]
Not sure why it was commented out, seems to work: 
![image](https://user-images.githubusercontent.com/313208/89698793-f2b8ff80-d8d7-11ea-8744-f4e707b834ab.png)

Feel free to improve it if you'd like - I can't even remember how Challenge of Elders worked.

**Comment by jbccollins** [comment]
<img width="819" alt="Screen Shot 2020-08-15 at 10 54 16 PM" src="https://user-images.githubusercontent.com/8915552/90325506-6d25f700-df4a-11ea-8c36-2ac485357678.png">

How do we feel about this? There are two main objectives per character, one for a cumulative score and one for a high score that award an armor piece and a weapon respectively. I feel like displaying both of these is more useful than a single dot. The data shown in these is dummy data as I'm away from my xbox for the weekend and can't run Challenge of Elders for a bit.

**Comment by bhollis** [comment]
That looks nice!

**Comment by jbccollins** [comment]
Coo coo. I'll do some testing with it now that I'm back in town and make a PR soon :)
