### ISSUE TITLE
Single line wishlist notes still get faded

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#5561]
Not sure how hard it would be, but it'd be great if we could only fade the wishlist notes if they were above a certain length:

![image](https://user-images.githubusercontent.com/313208/89699331-fef28c00-d8da-11ea-8cf4-f6794228337a.png)

**Comment by nev-r** [comment]
resolved in https://github.com/DestinyItemManager/DIM/pull/5565
