### ISSUE TITLE
Set Tiers in Beta missing some T12 possibilities. 

### ISSUE THREAD

**Issue by h3adache** [DestinyItemManager/DIM#557]
My warlock has a 5/5/2 loadout available and that shows up fine in v3.6.4.37170
But my hunter has both a 4/4/4 and a 3/4/5 that isn't showing up.

**Comment by ericnelson0** [comment]
The fix for this problem is discussed in #552.

**Comment by kyleshay** [comment]
@h3adache, could you check again now that we've made some changes per the #552 branch

**Comment by h3adache** [comment]
@kyleshay the work you guys have done is amazing. The new beta definitely picks up the tiers that were missing previously and is **so** much faster than TGD.

One issue that I'm seeing now though is that it isn't pulling "similar" gear. For example I have Spektar Aspriet Grips (0/57/40) and Sealed Ahamkara Grasps (0/57/39) which are close enough to be interchangeable. But only the Spektar shows up in a T12 setup until I lock in the Ahamkara. Not a huge deal but people might miss gear if they aren't looking at that.

This is really exciting. Thanks for putting the work into this!

**Comment by h3adache** [comment]
There is another discrepancy between the beta builder and TGD. One of the possible (not yet infused/leveled) setups I have gives me a 4/4/4 build on my hunter. On DIM even if I lock in all the pieces it shows me as 4/4/3. I'm guessing this is more to do with some difference in calculation since both are using theoretical 335 values?

**Comment by SunburnedGoose** [comment]
Yup.

**Comment by kyleshay** [comment]
i'm going to close this now, since the original issue is resolved. the other issue (theoretical 335 values) we're tracking separately and should eventually resolve what you're seeing.

**Comment by h3adache** [comment]
Seems the 3.7.1 release has broken this again. For example. I don't see my 4/4/4 on my hunter but its there on both TGD and DestinyTailor? (http://destinytailor.com/psn/gchen77/hunter)

**Comment by ericnelson0** [comment]
@h3adache 

If you lock in those gear pieces will it show 4/4/4?

Would you mind posting the closest sets in DIM and the sets from destiny tailor and TGD?

**Comment by h3adache** [comment]
Interestingly enough it does not. But it's because it misses the combination that makes it T12.
Sorry for the large files.
![screen shot 2016-06-04 at 6 34 46 pm](https://cloud.githubusercontent.com/assets/320283/15802773/09e23944-2a84-11e6-8bd0-905866b7d9bf.png)
![screen shot 2016-06-04 at 6 40 06 pm](https://cloud.githubusercontent.com/assets/320283/15802774/09e2bce8-2a84-11e6-8d81-ff3448ff61ed.png)
![screen shot 2016-06-04 at 6 40 25 pm](https://cloud.githubusercontent.com/assets/320283/15802771/09dfaada-2a84-11e6-8441-e8a3bc00aad6.png)
![screen shot 2016-06-04 at 6 41 08 pm](https://cloud.githubusercontent.com/assets/320283/15802772/09dfc68c-2a84-11e6-9068-10238f34980b.png)

**Comment by ericnelson0** [comment]
Hmm. The combination should have been generated, maybe it shows up in 3/4/4/ or 3/3/4 ... etc?

If that's the case maybe the scaled values are incorrect?

**Comment by h3adache** [comment]
yea you are right it showed up under 3/3/4.

![screen shot 2016-06-05 at 8 20 09 pm](https://cloud.githubusercontent.com/assets/320283/15809672/f7bd8fca-2b5a-11e6-95d9-7f95a228165a.png)

**Comment by ericnelson0** [comment]
Then it must be that our scaled values aren't correct? Anyone have any ideas?

**Comment by h3adache** [comment]
Sorry for the late response, I noticed it was already fixed in the new beta. Thanks @kyleshay and @ericnelson0 for fixing this!

**Comment by kyleshay** [comment]
awesome to hear, thanks for confirming!
