### ISSUE TITLE
Organizer: Phone landscape z-index issues

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [DestinyItemManager/DIM#5574]
**What version of DIM are you using?**
6.24.0 Orange

**What Browser and OS are you using?**
Chrome Android 

**Describe the bug and how to make it happen**
The move to char button is partially hidden and the drop down menu too. 

![Screenshot_20200811-202830_Chrome](https://user-images.githubusercontent.com/2725603/89934948-a4766a00-dc11-11ea-8653-5788258f073b.jpg)

**Comment by nev-r** [comment]
https://github.com/DestinyItemManager/DIM/issues/5502

**Comment by bhollis** [comment]
Yeah, this view is not designed for use on phones - you're not even supposed to be able to get to it, but I forgot about landscape view.

**Comment by TheBl4ckSh33p** [comment]
But it's very useful and I don't have a PC next to my console. Would be great if it can be optimized for mobile too. 👍
