### ISSUE TITLE
Organizer not showing reaquireable for Exotics 

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [DestinyItemManager/DIM#5575]
**What version of DIM are you using?**
6.24.0 Orange 

**What Browser and OS are you using?**
Chrome Android

**Describe the bug and how to make it happen**
I filtered by warlock helmet and the reaquireable column has no check for exotic items. But you can get them from collection.

**Comment by delphiactual** [comment]
That roll?

**Comment by bhollis** [comment]
Duplicate of #4568
