### ISSUE TITLE
Add hoverable (or otherwise) tooltip to preview wishlist notes/scores while in comparison view

### ISSUE THREAD

**Issue by Izumi88** [DestinyItemManager/DIM#5579]
**Proposed change**
In the comparison view, currently the "thumbs up" perks are identified from the wishlist data, however the actual note (which typically contains a summarized score for pve/pvp) is not visible in anyway without exiting the comparison view (and clicking on the individual item).  It would be nice to be able to hover over the wishlist notes in comparison view and quickly sort out which items are "better" and tag accordingly for next actions.

**How does this fit into your workflow?**
Currently, to view wishlist summary/scores for the items being compared, I typically used the magnifying glass icon to "seek" to where the item is in inventory, exit out of comparison and click on the item to open up the details which contains the wishlist notes (scores), then return to compare view and seek to the next one and rinse and repeat for each to make a decision on which dupe(s) of that item to keep. It would be very useful to be able to view the wishlist notes (scores) from within the compare view for a more efficient workflow.

Alternatively, if hovering an item (in the inventory, without modifying the comparison bar view UI) while in comparison view could surface such information, that could also be a means to accomplish this workflow objective as well.

**Comment by Izumi88** [comment]
Forgive my MS Paint skills, a (very) rough mockup of the idea: 
![DIM-compare-view-notes-mockup](https://user-images.githubusercontent.com/51433200/89967566-ce368d80-dc1f-11ea-91f3-d4a34a664faf.jpg)

**Comment by Izumi88** [comment]
Forgive my MS Paint skills, just a (very) rough mockup of the idea:
![DIM-compare-view-hover-notes-mockup](https://user-images.githubusercontent.com/51433200/89967704-23729f00-dc20-11ea-9aa1-7e629f6c9e4c.jpg)

**Comment by delphiactual** [comment]
Have you tried organizer?

**Comment by bhollis** [comment]
My longer term plan is to rebuild this view on the organizer code, so you'll get to select any of the columns from Organizer you want to see here, and it becomes your own responsibility to not select so much that you can't see anything.

**Comment by Izumi88** [comment]
@delphiactual Thanks! I hadn't realized that Wish List Notes was available in the column selection now. Certainly not as nice/convenient as the compare view (because it scopes down to the exact dupes so quickly), but definitely usable from scrolling through the overall weapon categories.

@bhollis Awesome, I definitely appreciate what the organizer has brought to the table since it was introduced (being a spreadsheet warrior myself, and manipulating the csv's in the past), but the "standard view" is what I gravitate to during "regular" usage during play and being the 500/500 type of player that I am ;-).

**Comment by kyleshay** [comment]
technically resolved w/ https://github.com/DestinyItemManager/DIM/pull/7007 now that you can view the item popup from compare?
