### ISSUE TITLE
Stat split overestimated at low light

### ISSUE THREAD

**Issue by billkunz** [DestinyItemManager/DIM#558]
Version: 3.6.4 (Production)

I had 281 light arms, estimated at a 99% roll. After doing a happy dance in my chair and infusing them to 335, they're now reported as a 95% stat split. My chair dancing game is on point, so I don't think that's the culprit. I understand the stat estimates at low light levels are expected to have a significant amount of error, but I was under the impression that such estimates would be of their minimum expected value at 335. Is my impression incorrect, or is there a possible issue? Thanks!

**Comment by kyleshay** [comment]
sorry to hear you didn't get what you expected :( 

we've just pushed an update out that will now show you the projected range of the stat value as it's infused to 335. #572

**Comment by billkunz** [comment]
That sounds awesome, thanks so much!
