### ISSUE TITLE
Season 2 Ghost not marked as reaquireable 

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [DestinyItemManager/DIM#5596]
**What version of DIM are you using?**
6.24.0 Orange 

**What Browser and OS are you using?**
Android Chrome 

**Describe the bug and how to make it happen**
In organizer the season 2 Ghost is not marked as reaquireable but I can get it from collection like any other ghost. 
Bug or did I miss something?
![Screenshot_20200814-135344_Chrome](https://user-images.githubusercontent.com/2725603/90246981-f4ce1180-de35-11ea-93a0-14f66dc27395.jpg)

**Comment by delphiactual** [comment]
Dupe #4568 #5116
