### ISSUE TITLE
Inventory: huge empty space between kinetic/energy/power weapons

### ISSUE THREAD

**Issue by arane9** [DestinyItemManager/DIM#5605]
**What version of DIM are you using?**
Find the version in "About DIM" from the menu (the button with three bars on the upper left of the screen). Is the DIM icon orange, or blue?
Orange 6.25

**What Browser and OS are you using?**
It helps to know what type of browser and what version you're using. Have you installed DIM as an app through Chrome or Safari?
Chrome Windows 10, Steam browser, Brave android

**Describe the bug and how to make it happen**
Tell us what's wrong. A great format for bug reports is "I did X, and I expected Y, but instead Z happened." If it helps illustrate the issue, please add screenshots to help explain your problem.
I'm not sure if it's a bug. Inventory tab showing all 3 characters. Below kinetic weapons is a huge empty space requiring me to scroll down a lot just to see energy weapons and power weapons. I have seen screenshots and videos of other people using DIM and their version does not have the huge empty space. I have checked the settings and am unable to remove the empty space between weapon types. 
![dim empty space](https://user-images.githubusercontent.com/62527908/90461159-86909400-e140-11ea-9d89-dbdf463a3f03.png)

**Include devtools console logs**
If you can, open the devtools console (ctrl+shift+J on PC and cmd+option+J on Mac) and paste what you see in the window that pops up:

```
Paste console logs here
```

**Comment by delphiactual** [comment]
your vault is full of kinetic weapons

**Comment by arane9** [comment]
Alright. I see now. Thanks
