### ISSUE TITLE
Organizer - item popup appearing behind toolbar

### ISSUE THREAD

**Issue by duckmanBR** [DestinyItemManager/DIM#5606]
On beta 6.25.0.7870
![image](https://user-images.githubusercontent.com/32077894/90519217-21d43a00-e13e-11ea-95b6-1d6f404a2e3b.png)
Probably just need some z-index adjust.

**Comment by nev-r** [comment]
just noticed this myself. ty.

**Comment by nev-r** [comment]
good in beta
