### ISSUE TITLE
Item tagging and notes

### ISSUE THREAD

**Issue by bradchoate** [DestinyItemManager/DIM#561]
Are individual inventory items given a unique ID that never changes? If so, it should be possible to have an offline bit of data related to that item. In particular, I'd like to tag items that I intend solely as infusion fuel. I suppose I could create an "Infusion" loadout and tag things with that, but for that to work, I'd need to be able to see at a glance which loadouts a given item is in to know whether it was tagged that way or not.

Per-item notes would be nice as well. I can't fully anticipate the utility for these, but I know they would be useful and I would use them.

**Comment by Mulchman** [comment]
Anyone ever play with this?

https://chrome.google.com/webstore/detail/destinychecklistnet-gear/feapilfcgikmmcdhledhnaefdjjfdomm

It's a DIM fork by the destinychecklist.net guy that lets you mark gear for
infusion/junk/whatever (+ probably some other things (I admittedly have
only used for a few minutes)).

**Comment by kyleshay** [comment]
closing in favor of https://github.com/DestinyItemManager/DIM/issues/471
