### ISSUE TITLE
Show cooldown times/percentage increases for armor stats

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#5614]
**Proposed change**
We should consider displaying the percentage increases/times for cooldown for each of the armor stats in the hover tooltip and in the loadout optimizer.

**How does this fit into your workflow?**
When adjusting builds in the loadout optimizer, these numbers would be helpful to know. We should show the numbers along side the 'tier', as the computed values are more meaningful. 

<img width="293" alt="d1" src="https://user-images.githubusercontent.com/424158/90693923-8e2d6700-e22c-11ea-9d20-c3bcdf9f66b1.png">
<img width="526" alt="d2" src="https://user-images.githubusercontent.com/424158/90693929-8f5e9400-e22c-11ea-9964-f22e07909933.png">

**Comment by delphiactual** [comment]
#5500 ?
