### ISSUE TITLE
Error on Min/Max beta with no legendary artifact

### ISSUE THREAD

**Issue by bradchoate** [DestinyItemManager/DIM#562]
Here's a stack trace I get when I try to view the beta Min/Max tool using my Hunter. She has two rare artifacts, but none that are legendary, so that may be the root cause here:

    Uncaught TypeError: Cannot read property 'sort' of undefined
        angular.extend.getTopSets	@	dimMinMax.controller.js:185
        step	@	dimMinMax.controller.js:269
        (anonymous function)	@	dimMinMax.controller.js:272

**Comment by bradchoate** [comment]
I now have a couple of legendary artifacts and my Hunter's MinMax page loads properly.

**Comment by kyleshay** [comment]
ah, thanks for the heads up on this. would be good to get some safety checks in there.
