### ISSUE TITLE
masterwork enemies defeated filter

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#5624]
With sunsetting coming soon, many people will want to delete all the weapons that can't increase power further.

However there might be some who want to keep masterwork weapons that have high kill counts on them as trophies.

I'd like a filter like this:
is:masterwork powerlimit:=1060 enemiesdefeated:<1000

**Comment by errera** [comment]
Seconding this request - I came here to add it, glad to find it already on the list. :)

**Comment by philkernick** [comment]
I've had a bit more of a think about how this could work, because my original suggestion is a bit simplistic.

Legendary weapons have both pve and pvp trackers.  I don't know if the they are both exposed at the same time, or only the one that is applied.  But that leads to something like this:

defeated:pvp:
defeated:pve:
defeated:

Exotic weapons only have one tracker for total kills.  Something like this:

defeated:

For exotics defeated:pvp: and defeated:pve: would have to return the same value as defeated: because the other option is for them to return zero, and that would not meet user expectations.

I thought about a subselector like defeated:total: (to match what we have in basestat:) but it makes no sense to require one where it's the only option for exotics.  And for legendaries it would be calculated to be the sum of pvp and pve.

**Comment by nev-r** [comment]
while (apparently?) a y2 masterwork weapon can keep two counts,
i tested this out a bit, the game & API only provides the number for the currently selected kill counter,
so this could have a pve/pvp specification, but it will only narrow the search by "current selection", not by statistics

enemiesdefeated and opponentsdefeated are really long, the adjective "defeated" looks strange out of context, i would really like to just label this "kills", which still matches the game's common term for defeating enemies.
so like

kills:
kills:pve:
kills:pvp:
?

**Comment by philkernick** [comment]
Looks good to me.
