### ISSUE TITLE
MinMax: sets processing does not cancel when clicking 'Back to DIM' and sometimes leads to blank/empty DIM

### ISSUE THREAD

**Issue by Mulchman** [DestinyItemManager/DIM#563]
* Click 'MinMax' button
* While sets are being processed, click 'Back to DIM'
* Wait around with the console open and you can eventually see the processing was not cancelled
* ~~You can also get it in a state where your items never show up (as also seen in the video if you watch long enough)~~ Separate issue for this here: https://github.com/DestinyItemManager/DIM/issues/566

http://screencast.com/t/WEEEYdr0mt

**Comment by ericnelson0** [comment]
Nice find! 

If you inject the $location dependency and use:

```
                    if((processed_count%5000) == 0) {
                        // If active gaurdian or page is changed then stop processing combinations
                        if(vm.active != activeGaurdian || $location.path() !== '/best') {
                            return;
                        }
                        //$scope.$apply(function () {
                            vm.progress = processed_count/combos;
                        //});
                        $timeout(step, 0, true, activeGaurdian, h,g,c,l,ci,gh,ar,processed_count);
                        return;
                    }
```

That will prevent the processing from continuing.

However, I don't believe the blank DIM issue is caused by this. It seems that the bug is present in the current release version and can be produced by clicking minmax, clicking 'back to dim', and going back to minmax.

**Comment by Mulchman** [comment]
> It seems that the bug is present in the current release version and can be produced by clicking minmax, clicking 'back to dim', and going back to minmax.

I'm going to create a separate issue for that, then.

**Comment by Mulchman** [comment]
```javascript

                    if((processed_count%5000) == 0) {
                        // If active gaurdian or page is changed then stop processing combinations
                        if(vm.active != activeGaurdian || $location.path() !== '/best') {
                            return;
                        }
                        $scope.$apply(function () {
                            vm.progress = processed_count/combos;
                        });
                        ...
                    }
```

Made those changes locally and it indeed cancels the loading. Do you want to submit a PR for this? Or me? Or hope @kyleshay @bhollis @SunburnedGoose pick it up?

**Comment by ericnelson0** [comment]
I added some safety checks and switched to using $timeout instead of setTimeout with $scope.apply. 

So I'll submit a PR with all of these changes.
