### ISSUE TITLE
New Search Bar: Search on "Enter"

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#5637]
Here's a thought that I'd like some feedback on - should we only search on enter/blur of the search field, instead of as you type? It'd reduce a lot of "thrash" but makes it harder to visually keep track of how your search is evolving as you build it up.

**Comment by philkernick** [comment]
I think we should search on enter or space.  space separates search terms.

**Comment by kyleshay** [comment]
i'm fine w/ enter or space for search terms, but for item names, etc. just a normal debounced search?

**Comment by bhollis** [comment]
Until React Concurrent Mode lands, I think we want the debounce no matter what, since it can feel really laggy to apply directly after a keystroke. Though at some point @nev-r had a really cool CSS based way of doing the search highlighting that was way faster.
