### ISSUE TITLE
Bounty Optimizer

### ISSUE THREAD

**Issue by zbalcom** [DestinyItemManager/DIM#5647]
**Proposed change**
I would like to create a bounty optimizer which examines your bounties and gives you the best game modes and weapons to use to complete them in as little time as possible. It would parse bounties using the pursuit info added [in this branch](https://github.com/DestinyItemManager/d2-additional-info/pull/92), find common game modes and weapons between bounties, and create a game plan to get them done easily. Possible optional feature to exclude certain bounties if you aren't prioritizing them right now (i.e. weeklies if you're only focused on dailies; Xur bounties, or others that you don't care about finishing ASAP but don't want to abandon).

**How does this fit into your workflow?**
Players would use it immediately after acquiring bounties in the tower. The ideal workflow would be to launch the game, load into the Tower, collect all weeklies and dailies you intend to complete, then run the bounty optimizer in DIM and do the activities it tells you to. At any time while doing the activities if you complete some bounties and aren't sure if you should keep playing that mode, simply refresh/run the bounty optimizer again and it will generate a new game plan based on the bounties you have remaining.

Any thoughts?

**Comment by bhollis** [comment]
I think this would be awesome! We were working towards something similar but decided to wait to see what changes with the bounty system in Beyond Light.

**Comment by zbalcom** [comment]
Ah, that makes sense. A few questions:

- Would it be alright if I picked it up and gave it a shot now, making sure to comment it thoroughly in case I'm not the one who ends up updating it for Beyond Light?
- Would it fit better as an extra section or button in the Progress tab? Or does it warrant its own tab like the Loadout Optimizer?
- Is there some existing work on this feature that I could find somewhere in the repo?

**Comment by kyleshay** [comment]
linking #2959

**Comment by bhollis** [comment]
You've found the work I had done to prepare the data for this - nothing more had been done. I think it's fine to take a crack at building something!

Whether it lives on the progress page or is its own tab really just comes down to what it ends up looking like. Personally I'd like to see it incorporated on the Progress page - we're going to be making some room in there soon anyway.

**Comment by bhollis** [comment]
We've added the Bounty Guide to the progress page that categorizes bounties - is there more you'd like to do here?

**Comment by kyleshay** [comment]
Please feel free to re-open if you have any ideas that you'd like to add on! Between the new bounty guide and active mode we cover a lot of cases. Though, there might still be some gaps, and we'd be happy to hear your thoughts! Feel free to also jump in the discord if you'd like to chat about some ideas there as well!

**Comment by dragoonz99** [comment]
Hi guys, sorry for necroing this thread but im pretty new here. I shared Z's idea and looked for a way to get it done but couldnt find much else so ill leave this here. The current bounty system is great but i think the original idea created more of a roadmap using the bounties. I would add on to it to include scanning the weapons in your vault to auto equip what you should use, or just put it in your inventory. maybe even as soon as the API detects the bounty is complete, that way you dont even need to follow your bounty progress. you know that if you're playing and a weapon is suddenly moved into your inventory then the current step is done. I have a bunch of ideas but i dont know where to put them and have no clue if its possible, just wanted to put them out there. LMK if this is the wrong place for it. Thanks
