### ISSUE TITLE
Add "masterwork:" to the Filters Help dialog

### ISSUE THREAD

**Issue by caswallon** [DestinyItemManager/DIM#5649]
6.25.0.7958(beta)
Chrome - W10 Pro

Filter Help dialog does not include the currently supported filters for weapons:

- masterwork:charge
- masterwork:impact
- masterwork:range
- masterwork:stabilty
- masterwork:reload
- masterwork:magazine
- masterwork:aimassis
- masterwork:handling
- masterwork:blastradus
- masterwork:recoildiection
- masterwork:velocity
- masterwork:drawtime
- masterwork:inventorysize

**Comment by bhollis** [comment]
Filter help is now generated automatically
