### ISSUE TITLE
Filter combinations sometimes don't highlight items they should

### ISSUE THREAD

**Issue by hythloday** [DestinyItemManager/DIM#565]
To repro:

Have Black Spindle
filter is:sniperrifle (BS is highlighted)
filter is:solar (BS is highlighted)
filter is:sniperrifle and is:solar (BS is not highlighted, but other solar snipers might be)

<img width="554" alt="screen shot 2016-05-31 at 23 02 20" src="https://cloud.githubusercontent.com/assets/933087/15691999/d3a240d4-2783-11e6-8dcb-e8ef49e6e445.png">

<img width="529" alt="screen shot 2016-05-31 at 23 02 08" src="https://cloud.githubusercontent.com/assets/933087/15691995/cdf4436c-2783-11e6-94a4-122f66dfe576.png">

<img width="532" alt="screen shot 2016-05-31 at 23 02 31" src="https://cloud.githubusercontent.com/assets/933087/15692001/d9def4e2-2783-11e6-89c6-8f0677843f88.png">

If someone wants to give me any clues as to where to look I'll debug and submit a PR.

**Comment by SunburnedGoose** [comment]
Remove the 'and'.  It's implicit.

**Comment by hythloday** [comment]
Hah, I should have realized. Thanks!
