### ISSUE TITLE
Engrams in my inventory are shown under "POSTMASTER"

### ISSUE THREAD

**Issue by danielmirchandani** [DestinyItemManager/DIM#5654]
**What version of DIM are you using?**
Find the version in "About DIM" from the menu (the button with three bars on the upper left of the screen). Is the DIM icon orange, or blue?

Version 6.26.0 (release), built on 8/23/2020, 8:03:11 PM
Orange icon

**What Browser and OS are you using?**
It helps to know what type of browser and what version you're using. Have you installed DIM as an app through Chrome or Safari?

Chrome: Version 84.0.4147.136 (Official Build) (64-bit)
No app installed at URL https://app.destinyitemmanager.com/xxxxx/d2/inventory

**Describe the bug and how to make it happen**
Tell us what's wrong. A great format for bug reports is "I did X, and I expected Y, but instead Z happened." If it helps illustrate the issue, please add screenshots to help explain your problem.

I am confused why engrams in my inventory appear under "POSTMASTER": ![open](https://user-images.githubusercontent.com/16217354/91085292-38d1cb00-e61b-11ea-9fa8-41a41c84b143.png). I initially thought these engrams were waiting for me to claim. However, when I visit the Postmaster, there was only one engram to claim, not 5 as shown. This is especially confusing when you collapse the "POSTMASTER" section: ![closed](https://user-images.githubusercontent.com/16217354/91085291-38d1cb00-e61b-11ea-85d4-064b456ed7b4.png).

**Include devtools console logs**
If you can, open the devtools console (ctrl+shift+J on PC and cmd+option+J on Mac) and paste what you see in the window that pops up:

```
Sync: Storage may be cleared under storage pressure.
sync.service.ts:55 Sync: DIM is using 118.96 MB total out of 30.25 GB in storage quota (0%).
actions.ts:116 globalSettings Object
platforms.ts:19 Load accounts from IDB
app.destinyitemmanager.com/:1 A cookie associated with a cross-site resource at http://www.bungie.net/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
app.destinyitemmanager.com/:1 A cookie associated with a cross-site resource at http://bungie.net/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
app.destinyitemmanager.com/:1 A cookie associated with a cross-site resource at https://www.bungie.net/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
Index.tsx:52 DIM v6.26.0 (release) - Please report any errors to https://www.github.com/DestinyItemManager/DIM/issues
actions.ts:78 Saving profile data to IDB
manifest-service-json.ts:142 Load manifest: 1010.464111328125ms
d2-stores.ts:256 Process inventory: 24.969970703125ms
d2-stores.ts:260 Inventory state update: 174.10205078125ms
d2-stores.ts:256 Process inventory: 25.655029296875ms
d2-stores.ts:260 Inventory state update: 56.64013671875ms
d2-stores.ts:256 Process inventory: 39.333251953125ms
d2-stores.ts:260 Inventory state update: 43.746826171875ms
d2-stores.ts:256 Process inventory: 27.912841796875ms
d2-stores.ts:260 Inventory state update: 36.2080078125ms
actions.ts:78 Saving profile data to IDB
reducer.ts:437 prepareUpdateQueue: 2.48291015625ms
actions.ts:279 [flushUpdates] Flushing queue of 1 updates
actions.ts:297 [flushUpdates] got results Array(1) Array(1)
actions.ts:78 Saving profile data to IDB
d2-stores.ts:256 Process inventory: 28.42919921875ms
d2-stores.ts:260 Inventory state update: 37.684814453125ms
actions.ts:78 Saving profile data to IDB
reducer.ts:437 prepareUpdateQueue: 1.1728515625ms
actions.ts:279 [flushUpdates] Flushing queue of 1 updates
actions.ts:297 [flushUpdates] got results Array(1) Array(1)
actions.ts:78 Saving profile data to IDB
d2-stores.ts:256 Process inventory: 53.645263671875ms
d2-stores.ts:260 Inventory state update: 40.916259765625ms
d2-stores.ts:256 Process inventory: 28.0068359375ms
d2-stores.ts:260 Inventory state update: 44.2099609375ms
actions.ts:78 Saving profile data to IDB
d2-stores.ts:256 Process inventory: 35.016845703125ms
d2-stores.ts:260 Inventory state update: 40.903076171875ms
```

**Comment by bhollis** [comment]
Yep that can happen. They're in your Postmaster in game too.

**Comment by danielmirchandani** [comment]
Can you help me understand what you mean? Here's a photo of what I see in-game:

![PXL_20200825_163351737](https://user-images.githubusercontent.com/16217354/91203447-1601ee00-e6d1-11ea-864a-066344b8d5a8.jpg)

When I refreshed DIM just now, I see the same thing as in the screenshots in my original post. I'm having difficulty understanding whether you meant I would see in-game the 4 other engrams in the Postmaster, or whether you meant Bungie's API is telling DIM that I have those 4 other engrams in the Postmaster.

**Comment by bhollis** [comment]
The other engrams are in a separate 10-slot engram inventory. You see them when you go to the Cryptarch.

**Comment by kyleshay** [comment]
I think thats what they were wondering: because claimed engrams show up in your inventory, they were wondering why they appear under the postmaster heading in DIM. I think it comes down to a similar issue w/ the sub-class being under weapons, there isn't an ideal category to fit them under.

Inventories are account wide, but claimed engrams are per character. Maybe we could move them to a non-collapsable row outside/above the postmaster? 

As an aside, I've thought about moving subclass to the "general" section (where ghosts/ships/etc live) as it's also something that you may typically not use DIM to swap around.

**Comment by danielmirchandani** [comment]
kyleshay@: yes, you are exactly correct why I'm confused; is there another bug for your moving subclass around that this issue could marked as a duplicate of?

**Comment by kyleshay** [comment]
While they're technically not in the postmaster, they are in a "items-to-process type bucket" There isn't really a great place to put it. I think we're going to leave it as-is for now, but we may revisit this in the future. We have some design changes coming, that it may or may not fit within. Thanks for the report!
