### ISSUE TITLE
New Search Bar: Home/End are used for navigating menu items, not moving text cursor

### ISSUE THREAD

**Issue by GotAudio** [DestinyItemManager/DIM#5659]
Version Version 6.26.0.7971 (beta), built on 8/24/2020, 11:30:50 PM.  In search bar, keyboard shortcuts Home, End, Shift+Ctrl Right/Left no longer work in search bar.   Can these navigation methods be (re)implemented?  I use them often.  Or can we get a switch in Settings to use the old behavior?

**Comment by kyleshay** [comment]
Thanks for checking out the new beta search bar and filing the report, it was not intentional to change the keyboard behavior, we'll track this issue to resolve. thanks again!
