### ISSUE TITLE
Organizer - apply note changes when field loose focus

### ISSUE THREAD

**Issue by duckmanBR** [DestinyItemManager/DIM#5666]
Make the note changes also be applied if the user clicks elsewhere not only when the user press `enter`

**Comment by nev-r** [comment]
i left the notes field as a textarea on blur, to give some leeway for browser tabbing away, using tab key, or copying text such as wishlist notes.
it currently saves your notes any time you click out of the item popup though, are there any issues with notes missing/not saving?

**Comment by duckmanBR** [comment]
I created this more because when organizing new items I sometimes get to 2-3 items with the notes open. But if it is saving when you click outside, it becomes just a nuisance.
Didn't have issue (that's why I created as enhancement) but I'll test it more and close if everything is ok.

**Comment by nev-r** [comment]
ok. i see where you're coming from definitely but i can also imagine getting frustrated when i have to repeatedly click open the same text field while i work on what to put there. not sure what the compromise is yet

**Comment by bhollis** [comment]
Maybe instead of closing on blur, it should close on ClickOutside?

**Comment by bhollis** [comment]
Anything we still want to do with this?
