### ISSUE TITLE
Organizer - disable "shift+click" to filter on notes fields when it's being edited

### ISSUE THREAD

**Issue by duckmanBR** [DestinyItemManager/DIM#5667]
Don't know if it's possible, but we should disable the `shift-click` to filter on the note field if a note is being edited.
It's really frustrating trying to select a phrase and making a filter by the item note.

**Comment by bhollis** [comment]
I've never heard of shift clicking to select text but it seems possible to prevent click events from propagating.

**Comment by duckmanBR** [comment]
Really?  I use all the time... 😅
Selects from cursor to where you clicked
