### ISSUE TITLE
Organizer - Linear Fusion Rifles listed when selecting Fusion Rifle

### ISSUE THREAD

**Issue by duckmanBR** [DestinyItemManager/DIM#5668]
When you select Weapons > Fusion Rifles we also list Linear Fusion Rifles.

Beta v6.26.0.7987

**Comment by bhollis** [comment]
Bungie's data believes a linear fusion rifle is a fusion rifle. We'd need to special case this.

**Comment by bhollis** [comment]
It's worth noting that our `is:fusionrifle` search also highlights linear fusion rifles, and I believe bounties for fusion rifles count kills from linear fusion rifles.

**Comment by nev-r** [comment]
i was thinking about all the complex workarounds and supporting functions you'd need to distinguish in various DIM components, then it hit me. we should just remove item category 9 from LFR DimItems
