### ISSUE TITLE
Search results sheet

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#5669]
I'd like to add a sheet, triggered by hitting Enter on an active search field, that shows all items that match the search without the structure of the Inventory screen. We can maybe still break them up by which character they're on, but generally it's about showing whatever matches. On mobile, I propose that this sheet be shown by default when searching (it can be dismissed). We can attach actions such as moving or tagging items to this sheet, in addition to having a search action menu in the search bar itself. 

I've attempted to build this a few times, and the main hangup is figuring put how to get desktop item popups to work when triggered from a Sheet - I want this to work a lot like the inventory screen rather than like the quick item picker.

**Comment by kyleshay** [comment]
https://github.com/DestinyItemManager/DIM/pull/5978
