### ISSUE TITLE
Show light level in calculated loadouts for MinMax

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#568]
https://www.reddit.com/r/DestinyItemManager/comments/4m741w/suggestion_max_possible_light_for_tier_based/

A user asked that we show the light level of the loadout too.  Here's a function to calculate light both above and below level 40.

https://www.reddit.com/r/DestinyTheGame/comments/3kwmvh/how_overall_light_level_is_calculated/

**Comment by ericnelson0** [comment]
The int/dis/str values on this page assume that the pieces are leveled up to 335 light. Does the user want to see what their light level would be with the current light levels of all the gear pieces?

**Comment by SunburnedGoose** [comment]
Probably...  They might want to know if it's worth wearing that gear in IB or Trials to level it up?

**Comment by kyleshay** [comment]
relates to #402, as we'll need the formula for that as well.

**Comment by kyleshay** [comment]
we can do this, but does it make sense? it depends on what character you would apply that loadout to, and what weapons that account has equipped.

**Comment by bhollis** [comment]
Now that loadout builder operates in the context of a selected character, we could do it.

**Comment by kyleshay** [comment]
Another option is we could look at the armor and compute it against the highest level weapons.

Forgot that this function exists:
https://github.com/DestinyItemManager/DIM/pull/993/files#diff-326858559561fafc0a3d7c9d43d3415aR212
