### ISSUE TITLE
in a vertically short sheet, search suggestion dropdown can go right off the bottom

### ISSUE THREAD

**Issue by nev-r** [DestinyItemManager/DIM#5698]
i just, don't have that many titan class items
![image](https://user-images.githubusercontent.com/68782081/91672707-cfebc680-eae4-11ea-94c7-8654e879487b.png)

**Comment by eet349** [comment]
Would an acceptable fix be to set a min-height (275px seems to give it just enough space) to the item-picker? Would it be better to increase the height when the input is focused?

**Comment by bhollis** [comment]
The [Visual Viewport API](https://developer.mozilla.org/en-US/docs/Web/API/Visual_Viewport_API) should help with this. We need to be able to set the correct height for all types of dropdowns to keep them within the visual viewport.
