### ISSUE TITLE
Roll Finder

### ISSUE THREAD

**Issue by jmichas** [DestinyItemManager/DIM#5708]
**Proposed change**
I like the wishlist stuff but what I would really like is to be able to enter in the roll for a weapon or piece of armor that I'm looking for and when I acquire that roll have DIM highlight the icon differently, lock it, notify me, something so that I know I found it.

**How does this fit into your workflow?**
I typically keep an evernote going that has my list of perks that I'm looking for in weapons and armor, so every time I get X weapon I consult my notes and see if I got the one I wanted since I don't commit all this stuff to memory. If DIM kept a better version of freeform notes by letting me select a weapon and setting the perks, then DIM could match the item it would be super useful. Many times the roll I'm looking for might not be the "wishlist" accepted god roll or whatever, or maybe I'm looking for something that fills a particular niche like a rocket launcher with autoloading holster and tracking, I'm not even sure which launchers do that. Anyway, I thought it would be a great feature addition.

**Comment by bhollis** [comment]
Currently our intention is for you to make your own wishlist for that: https://destinyitemmanager.fandom.com/wiki/Creating_Wish_Lists

**Comment by jmichas** [comment]
Oh cool, thanks. I looked at the wishlist stuff but didn't know how it worked exactly, I thought it was a community source for the rolls. Does this mean I can just keep a text file locally and wire it up to DIM so it uses my rolls? And do the wishlisted items show up highlighted differently in the item manager? Or just get the thumbs up icon like other wish list rolls?

**Comment by bhollis** [comment]
Check out the user guide I linked, it should have answers to all your questions.
