### ISSUE TITLE
Opening filter help does not work the second time

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#5715]
**What version of DIM are you using?**
Prod

**What Browser and OS are you using?**
Chrome

**Describe the bug and how to make it happen**
Click the Filters Help button in the search bar, close sheet. Click Filters help again and help does not re-open

**Include devtools console logs**
N/a

**Comment by nev-r** [comment]
changing input field value resets the unopenability. does downshift think it's already been "chosen" or something??

**Comment by bhollis** [comment]
Yeah that's the problem - downshift doesn't fire "onSelectedItemChanged" or whatever. I think we just need to hook into their reducer :-(

**Comment by GrimmiMeloni** [comment]
@bhollis I would like to take a stab at this. Can you mark this as "taken" or simply assign it to me?
