### ISSUE TITLE
Profile-less URLs

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#5721]
I'd like to expose URLs like https://app.destinyitemmanager.com/progress that will redirect to the profile-specific progress page, so they're suitable for linking from social media. I'm not sure I'm ready to get rid of the profile-specific URLs entirely.

**Comment by kyleshay** [comment]
Nice! I think originally the links were there for /inventory so that we could someday allow users to share their inventory?

**Comment by nev-r** [comment]
i have definitely wanted this a bunch, i can make good use of it in supporting users

**Comment by bhollis** [comment]
Yeah, originally it was to share inventory and/or have multiple profiles open at once. Unfortunately now inventories are private by default and cross-save means you don't need to have multiple open accounts.
