### ISSUE TITLE
Allow sub-grouping in vault

### ISSUE THREAD

**Issue by riannucci** [DestinyItemManager/DIM#573]
Concept is this: I have a bunch of stuff in the vault. Some of it is keepers (locked items), and some of it is just infusion fuel (including some duplicates of the keepers!). Right now it's all kind of blended together :/.

It would be double-cool if the unlocked item groups (i.e. junk) could be collapsed into a 'Unlocked (XX items)' line.

WDYT?

**Comment by kyleshay** [comment]
if you have a minute could you concept this with an image, i'm having a difficult time imagining it. i think i have it but am not 100%. 

BTW- you can type `is:locked` or `is:unlocked` in the filter box (not sure if that helps?)

**Comment by riannucci** [comment]
Yeah I knew about the filters :). This is more about a permanent separation between the two types of items (e.g. a display mode). Hopefully the attached images make sense?

<img width="1203" alt="before dim" src="https://cloud.githubusercontent.com/assets/133821/15801620/ff1e649e-2a4f-11e6-9c8c-f1159af4845f.png">

The red outlines indicate duplicates (which are unlocked items that I'm keeping for infusion fuel). There's a bunch of others locked/unlocked in here too, where the unlocked ones are infusion fuel, and the locked ones are keepers, but I highlighted these just to call your attention to them.

<img width="1203" alt="after dim" src="https://cloud.githubusercontent.com/assets/133821/15801745/892dfc00-2a53-11e6-9e36-249a8294952d.png">

As you can see in the second shot, all the unlocked items are now stashed away in an expandable sub-section. This removes visual clutter from the vault when trying to select weapons. Although it's possible to do a query like `ironwreath is:locked`, it would be convenient if the infusion-fuel versions of the weapon you're looking for were visually hidden (especially if you're trying to make a quick pick with the mouse as you load into a match or something like that). This is especially true if you need to grab a couple different weapons onto a character.

Does that make more sense?

**Comment by riannucci** [comment]
(and of course the font and silly `+` symbol would have to change to match the rest of the style of the UI, I was just sketching it up 😄)

**Comment by kyleshay** [comment]
I like that, sub-organization within each of the rows. Thanks @riannucci, those images helped a lot!

**Comment by kyleshay** [comment]
another person asking to sub-organize within each row. specifically: grouping armor by class.

>The vault,...sigh.
The only armor icon that is easily distinguishable by class is gauntlets. Hunter is left arm, Titan is right arm and Warlock is a diagonal left arm. All other armor isn't easily distinguishable by the class for which it is worn.
So, it would be wonderful to sort the armor vault, or ALL vaults by the most recent character class too and then by the user options selected...light, rarity,...etc.
Please, please.

https://www.reddit.com/r/DestinyItemManager/comments/4pygfp/please_pleaseone_complex_enhancement_suggestion/

**Comment by kyleshay** [comment]
With ROI coming and possible vault increases -- implementing sub-organization in (at least) the vault will be really useful.

**Comment by Dave-Choi** [comment]
There seems to be a lot of different use cases where people want to focus on some type of item or another, and needs might vary a lot from user to user.

I don't particularly feel like sorting order is that useful for a lot of these cases, like dupes first, or some type of mod first (#2334), etc.  In a bunch of these cases, it seems like you're more interested in whether or not something is in a particular set.

I think it might be useful to have something like pinned filters, where a user could search for a set that's repeatedly of interest to them, like `is:dupelower is:weapon`, or `is:modifications leg`, click a pin icon, and just have a section added for the items that match the filter that persists until they unpin the search.

For my use case in #2334, I could just add my own pinned filters for `is:modifications helmet`, `is:modifications arm`, etc. and it would be everything I need for planning a mod build at a glance, without having to impose extra interface complexity on everyone else.

**Comment by MyrHerder** [comment]
I like the ideas mentioned here and in the referenced issues. I would like to add my vote for splitting the vault column by tag or class, but as mentioned in the previous comment, there is more variety between users. Perhaps making it a toggleable option in settings: split vault by (a) class (b) tag or (c) pinned filter (or not split at all).

**Comment by crulplay** [comment]
Speaking for myself, I could really benefit from tag based grouping in my vault as it helps a lot to keep stuff organized.

As an actual use case: I regularly tidy up my vault from stuff that dropped for me while playing Destiny that is not obvious garbage (as I don't want to interrupt my team members, I just move it to the vault). Currently I have to juggle with various filters and switch between them to compare new (untagged) items with existing (tagged) ones. This can be quite tedious and complicated.
By grouping my vault based on the item tags, the filters would be a lot simpler respectively not needed anymore and I could directly see, if it is worthwile to invest time into tidying up my vault.

Moreover - again, I can only speak for myself here - the farming mode would heavily benefit of this feature

**Comment by delphiactual** [comment]
@crulplay Settings -> `Indicate new items with a red dot`

**Comment by bhollis** [comment]
I don't think we're going to do this.
