### ISSUE TITLE
Search bar in item picker when keyboard opens, goes off page on android

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#5730]
**What version of DIM are you using?**
~Beta~ Prod

**What Browser and OS are you using?**
Android / Chrome

**Describe the bug and how to make it happen**
When tapping the search bar in item picker on android, the sheet goes off the page. The keyboard is still usable, but you need to swipe down to see what your input is.

![Screenshot_20200903-121739](https://user-images.githubusercontent.com/424158/92157828-d37e9680-eddf-11ea-996a-daf48c99f735.png)

**Comment by bhollis** [comment]
Possible that the `freezeInitialHeight` changes to Sheet actually affected this. I don't have an Android to test with.

**Comment by kyleshay** [comment]
Just commented that out and am still seeing the issue. I'm seeing it on prod as well. I'll investigate + test more later tn

**Comment by kyleshay** [comment]
closing in favor of https://github.com/DestinyItemManager/DIM/issues/3596
