### ISSUE TITLE
Empty inventory slot

### ISSUE THREAD

**Issue by Revadike** [DestinyItemManager/DIM#5748]
**Proposed change**
Move everything from current slot to Vault.
![image](https://user-images.githubusercontent.com/4411977/92410736-550a5780-f145-11ea-8dc0-432dc6627b9f.png)

**How does this fit into your workflow?**
It will help me with inventory management. For example, if I need to discard a lot of items in that slot, emptying it first would be easier and faster.

**Comment by bhollis** [comment]
Search "is:chest -is:equipped is:incurrentchar", save that search, click the vault header, and select transfer search.
