### ISSUE TITLE
Replace title= with tooltip directive

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#575]
A nice thing would to include a better solution for tooltips instead of the browser native `title=`. the timeout on that is too long and we can't style it. http://720kb.github.io/angular-tooltips/ could be an option (or we can easily roll our own.)

Would be nice if the component had the following features:
- automatically positions itself within the bounds of the window
- hover _or_ click (tap on mobile) to hide/show
- does not pollute the DOM with an extra element for every item that has a tooltip. generates and cleans up after itself
- lightweight
- temptable (can use HTML in tooltip)

places we could use a better tooltip:
- perk name & descriptions
- hover text for items on the settings modal
- item hover text (show full name + prim stat)
- tooltip for int/dis/str text
- tooltip for explaining stat roll percentages
- tooltips on loadout builder page

quite a few others, basically a search + replace on `title=`

**Comment by delphiactual** [comment]
also search + replace on 'translate-attr="{ title:`
