### ISSUE TITLE
Show in Loadout Optimizer if items are already in a loadout

### ISSUE THREAD

**Issue by nomadjsdev** [DestinyItemManager/DIM#5752]
**Proposed change**
When using Loadout Optimizer, if a combination of gear is already in a loadout make that clear so that duplicate loadouts aren't created.
<img width="694" alt="2020-09-09 11_48_57-DIM" src="https://user-images.githubusercontent.com/58656026/92589857-1da9c100-f293-11ea-9f2a-58cd84cdc879.png">

**How does this fit into your workflow?**
This would streamline creating loadouts, and prevent someone creating several different loadouts with the same items and different names.

**Comment by bhollis** [comment]
I think that'd be cool! Check in with @ryan-rushton who's actively doing a bunch of stuff here to allow for round-trip editing of loadouts in LO.

**Comment by ryan-rushton** [comment]
Hey @nomadjsdev, I have a PR in at the moment to add a compare drawer for loadouts and optimiser sets. That is currently pulling in all the loadouts but we could pull them in the optimiser reducer and then they would be available for exactly this. I will leave this feature for you if you like but feel free to hit me up about anything, happy to help.
