### ISSUE TITLE
Insanely slow

### ISSUE THREAD

**Issue by DriftedColt4917** [DestinyItemManager/DIM#5753]
Version 6.28.1.8160 (beta), built on 9/8/2020, 7:49:10 PM

Chrome

Right now it is transfering insanely slow.  Ive restarted, reloaded cleared synch data, logged out and back in and still super slow.  Sometimes it just doesnt transfer at all.

**Include devtools console logs**
If you can, open the devtools console (ctrl+shift+J on PC and cmd+option+J on Mac) and paste what you see in the window that pops up:

```
Paste console logs here
```

**Comment by delphiactual** [comment]
Bungie.net issue
