### ISSUE TITLE
allowances for degraded API service

### ISSUE THREAD

**Issue by nev-r** [DestinyItemManager/DIM#5757]
a lot of ideas for reducing API usage boil down to "but it would reduce functionality",
but with another major expansion coming up, we can expect another period of high failure rates for API calls.
it's worth consideration what we can do to keep DIM running with reduced functionality in cases of majorly degraded service.

what thresholds should we place on request time and rate of failed requests?

#5756 should we just skip this check completely if requests are taking long enough?

what is the absolute bare minimum we can request, to show item icons so they're draggable, and so users can tell what's in their slots and postmaster?

can/does /Manifest/ failure allow DIM to fallback to whatever's in IDB for now?

**Comment by nev-r** [comment]
caching sockets and stats, and only requesting them for new instance IDs?

**Comment by kyleshay** [comment]
Just going to link https://github.com/DestinyItemManager/DIM/issues/2164
