### ISSUE TITLE
Chrome now saying DIM needs permissions to edit all bungie.net info

### ISSUE THREAD

**Issue by dhinged** [DestinyItemManager/DIM#576]
Just got this notice, not seeing in the commits why DIM needs edit info for bungie.net sites

**Comment by SunburnedGoose** [comment]
We've always had that permission.  We need it to access your cookie.

**Comment by dhinged** [comment]
Read and _edit_? I only noticed it had read before; I've had it installed on this laptop for months, Chrome said "Permissions have changed" and it now included _edit_ permissions. Accessing cookies is not the same as editing all bungie.net info.

**Comment by delphiactual** [comment]
Chrome does not let the developer specify between read and edit permissions
