### ISSUE TITLE
is:<class> no longer displays correctly

### ISSUE THREAD

**Issue by TheProfessorY** [DestinyItemManager/DIM#578]
I updated to v3.7.1 and now the is<class> filter does not align correctly the icons. In addition, where as before it would "grey out" those items not matching the filter now it no longer displays any other items then the class specific ones.

**Comment by kyleshay** [comment]
it sounds like you have this button checked in the settings

if you're seeing some other issue, please reopen this issue and if possible provide a screenshot?

hope this fixes it for you, thanks!

![screen shot 2016-06-07 at 10 30 05 am](https://cloud.githubusercontent.com/assets/424158/15861625/d8636d2a-2c9a-11e6-99ee-8d1d4719c30b.png)
