### ISSUE TITLE
Filter `masterwork:` no longer works with inequalties

### ISSUE THREAD

**Issue by DHager** [DestinyItemManager/DIM#5794]
**Affected Version:** `v6.30.0`

**Expectation:** It was possible (last week, roughly) to use filters like `masterwork:=9` to find gear which was at a given masterwork **progress level**, including using inequalities such as `masterwork:<5`.

**Actual:** The numeric (in)equalities are now ignored, and the filter instead highlights items which are at maximum masterwork level.

**Why it matters:** 

1. Armor masterwork level determines what mods can be slotted. Sometimes you just want to find a piece of `is:armor is:arc masterwork:>7` that will fit the mod-choice you want.

2. Sometimes you want to find gear which has (or hasn't) been enhanced to a particular level, especially when it comes to the resources that can be spent (or reclaimed by dismantling) at certain points in the progression. For example, someone near the glimmer-cap might want to find `tag:keep is:weapon masterwork:<4` to see if they can quickly spend it that way.

**Comment by bhollis** [comment]
We'll fix it, but in the meantime try `energycapacity:`
