### ISSUE TITLE
Hide items tagged as Junk/Infuse in Compare, Organizer or Loadout Optimizer

### ISSUE THREAD

**Issue by DanishAce** [DestinyItemManager/DIM#5798]
**Proposed change**
Hide items tagged as Junk/Infuse in Compare, Organizer or Loadout Optimizer

**How does this fit into your workflow?**
I am using DIM to deside what to delete, and sometimes it becomes hard to do, if I have many duplicate items, and when I am doing the cleanup, when I am not online in Destiny.
I mark things to delte with tag:Junk, and thing to use as Infusion fuel with tag:Infuse
I know that you could also use Infuse as a marker for items you want to Infuse, so I will let you deside on how to handle this.

Hope to see this feature in DIM, as I love it very much, and have been using it since the beginning.

**Comment by bhollis** [comment]
Type "-tag:junk -tag:infuse" into the search bar in the header.

**Comment by DanishAce** [comment]
Hi Ben

I know all about all the filter methods, and I am a big fan of those, and
am educating my friends on how to use it.

But it does NOT work for Compare, and I would really like to not see the
rolls that I decided to tag as Junk or Infuse, it would make it so much
easier to narrow down the best rolls.

Kind regards,
Bill

**Comment by kyleshay** [comment]
If you shift-click items in the organizer they will automatically be filtered down for you. I'm curious to know if the organizer is missing something that compare is? The idea behind organizer is that it's a more fully featured compare. Thanks for your feedback!
