### ISSUE TITLE
Mod assignment algorithm is off for Mod Picker.

### ISSUE THREAD

**Issue by ryan-rushton** [DestinyItemManager/DIM#5805]
Got a report by a user that mods assignments are off with the mod picker https://github.com/DestinyItemManager/DIM/issues/5351#issuecomment-692512011

I have messed around with this and I can get similar weird results as follows. Note that the last general mod never gets slotted.

![image](https://user-images.githubusercontent.com/7344652/93208399-dabe8080-f79f-11ea-882e-979c784d8076.png)

**Comment by ryan-rushton** [comment]
@tanglueyi I created a new ticket from that bug you found. Can you check it out for me in beta?

**Comment by tanglueyi** [comment]
![image](https://user-images.githubusercontent.com/3315564/93280727-db393480-f7fc-11ea-906d-cf2685f082b5.png)
seems working good now~

**Comment by ryan-rushton** [comment]
Awesome, thank you for the report. It is appreciated.

**Comment by tanglueyi** [comment]
It is my honor to be able to help you :D

**Comment by tanglueyi** [comment]
[new one？](https://youtu.be/HlUyOtLJ-Tc)

**Comment by ryan-rushton** [comment]
I think that latest issues is why I had it in the seasonal then general order. I think the solution to this might be to handle both seasonal and general at the same time. I will have a play with this later today and see how I go with it.

**Comment by ryan-rushton** [comment]
FYI I found another case that it breaks. I think we need to deal with both general and seasonal mods at the same time. I have some use cases to build tests from so I kept this open until I deal with that.
