### ISSUE TITLE
Vault Space Count only goes up

### ISSUE THREAD

**Issue by BenBeyond** [DestinyItemManager/DIM#5825]
**What version of DIM are you using?**
Version 6.30.0.8337 (beta)

**What Browser and OS are you using?**
Chrome - Version 85.0.4183.102 (Official Build) (64-bit)

**Describe the bug and how to make it happen**
Vault space, General Count (497/500) only goes up when moving an item between characters, but not down, so the count exceeds 500 eventually

![image](https://user-images.githubusercontent.com/5505883/93503301-dbf9c580-f8e5-11ea-8ccd-abc2eff93678.png)

**Include devtools console logs**
If you can, open the devtools console (ctrl+shift+J on PC and cmd+option+J on Mac) and paste what you see in the window that pops up:

Issues detected. The new Issues tab displays information about deprecations, breaking changes and other potential problems.Go to IssuesLearn more
instrument.ts:128 DIM v6.30.0.8337 (beta) - Please report any errors to https://www.github.com/DestinyItemManager/DIM/issues
instrument.ts:128 Load accounts from IDB
instrument.ts:128 globalSettings Object
manifest-service-json.ts:141 Load manifest: 1746.30224609375 ms
instrument.ts:128 Saving profile data to IDB
d2-stores.ts:195 Process inventory: 149.144775390625 ms
d2-stores.ts:199 Inventory state update: 827.206787109375 ms
instrument.ts:128 User initiated move: 1 An Insurmountable Skullfort Helmet to Vault from Awoken Female Titan
instrument.ts:128 Move 1 An Insurmountable Skullfort Helmet to Vault from Awoken Female Titan
instrument.ts:128 Saving profile data to IDB
reducer.ts:442 prepareUpdateQueue: 1.103759765625 ms
instrument.ts:128 [flushUpdates] Flushing queue of 1 updates
instrument.ts:128 [flushUpdates] got results Array(1) Array(1)
instrument.ts:128 Saving profile data to IDB
instrument.ts:128 Object
instrument.ts:128 Saving profile data to IDB
reducer.ts:442 prepareUpdateQueue: 0.655029296875 ms
instrument.ts:128 [flushUpdates] Flushing queue of 1 updates
instrument.ts:128 [flushUpdates] got results Array(1) Array(1)
instrument.ts:128 Saving profile data to IDB
reducer.ts:442 prepareUpdateQueue: 0.9169921875 ms
instrument.ts:128 [flushUpdates] Flushing queue of 1 updates
instrument.ts:128 [flushUpdates] got results Array(1) Array(1)
instrument.ts:128 Saving profile data to IDB
instrument.ts:128 User initiated move: 1 Scatterhorn Wraps Gauntlets to Awoken Female Titan from Vault
instrument.ts:128 Move 1 Scatterhorn Wraps Gauntlets to Awoken Female Titan from Vault
instrument.ts:128 User initiated move: 1 Scatterhorn Wraps Gauntlets to Vault from Human Female Warlock
instrument.ts:128 Move 1 Scatterhorn Wraps Gauntlets to Vault from Human Female Warlock
instrument.ts:128 Object
instrument.ts:128 Saving profile data to IDB
reducer.ts:442 prepareUpdateQueue: 1.9150390625 ms
instrument.ts:128 [flushUpdates] Flushing queue of 1 updates
instrument.ts:128 [flushUpdates] got results Array(1) Array(1)
instrument.ts:128 Saving profile data to IDB
reducer.ts:442 prepareUpdateQueue: 1.01806640625 ms
instrument.ts:128 [flushUpdates] Flushing queue of 1 updates
instrument.ts:128 [flushUpdates] got results Array(1) Array(1)
instrument.ts:128 Saving profile data to IDB
instrument.ts:128 User initiated move: 1 ACD/0 Feedback Fence Gauntlets to Awoken Female Titan from Vault
instrument.ts:128 Move 1 ACD/0 Feedback Fence Gauntlets to Awoken Female Titan from Vault
instrument.ts:128 Resetting lock status of ACD/0 Feedback Fence to false when moving to Awoken Female Titan to work around Bungie.net lock state bug
instrument.ts:128 Object
instrument.ts:128 Saving profile data to IDB
reducer.ts:442 prepareUpdateQueue: 0.711181640625 ms
instrument.ts:128 [flushUpdates] Flushing queue of 1 updates
instrument.ts:128 [flushUpdates] got results Array(1) Array(1)
reducer.ts:442 prepareUpdateQueue: 0.68603515625 ms
instrument.ts:128 [flushUpdates] Flushing queue of 1 updates
instrument.ts:128 [flushUpdates] got results Array(1) Array(1)
instrument.ts:128 Saving profile data to IDB
instrument.ts:128 User initiated move: 1 Young Ahamkara's Spine Gauntlets to Awoken Female Titan from Exo Female Hunter
instrument.ts:128 Move 1 Young Ahamkara's Spine Gauntlets to Vault from Exo Female Hunter
instrument.ts:128 Move 1 Young Ahamkara's Spine Gauntlets to Awoken Female Titan from Vault
instrument.ts:128 Resetting lock status of Young Ahamkara's Spine to false when moving to Awoken Female Titan to work around Bungie.net lock state bug
instrument.ts:128 Object
instrument.ts:128 Saving profile data to IDB
reducer.ts:442 prepareUpdateQueue: 1.05712890625 ms
instrument.ts:128 [flushUpdates] Flushing queue of 1 updates
instrument.ts:128 [flushUpdates] got results Array(1) Array(1)
instrument.ts:128 Saving profile data to IDB
reducer.ts:442 prepareUpdateQueue: 0.715087890625 ms
instrument.ts:128 [flushUpdates] Flushing queue of 1 updates
instrument.ts:128 [flushUpdates] got results Array(1) Array(1)
instrument.ts:128 Saving profile data to IDB
instrument.ts:128 User initiated move: 1 Terra Concord Fists Gauntlets to Awoken Female Titan from Vault
instrument.ts:128 Move 1 Terra Concord Fists Gauntlets to Awoken Female Titan from Vault
instrument.ts:128 Object
instrument.ts:128 Saving profile data to IDB
reducer.ts:442 prepareUpdateQueue: 0.604736328125 ms
instrument.ts:128 [flushUpdates] Flushing queue of 1 updates
instrument.ts:128 [flushUpdates] got results Array(1) Array(1)
instrument.ts:128 Saving profile data to IDB
reducer.ts:442 prepareUpdateQueue: 0.77099609375 ms
instrument.ts:128 [flushUpdates] Flushing queue of 1 updates
instrument.ts:128 [flushUpdates] got results Array(1) Array(1)
instrument.ts:128 Saving profile data to IDB
instrument.ts:128 User initiated move: 1 Boots of the Emperor's Minister Leg to Vault from Human Female Warlock
instrument.ts:128 Move 1 Boots of the Emperor's Minister Leg to Vault from Human Female Warlock
instrument.ts:128 User initiated move: 1 Boots of the Emperor's Minister Leg to Awoken Female Titan from Vault
instrument.ts:128 Move 1 Boots of the Emperor's Minister Leg to Awoken Female Titan from Vault
instrument.ts:128 Resetting lock status of Boots of the Emperor's Minister to false when moving to Awoken Female Titan to work around Bungie.net lock state bug
instrument.ts:128 Object
instrument.ts:128 Saving profile data to IDB
reducer.ts:442 prepareUpdateQueue: 0.449951171875 ms
instrument.ts:128 [flushUpdates] Flushing queue of 1 updates
instrument.ts:128 [flushUpdates] got results Array(1) Array(1)
instrument.ts:128 Saving profile data to IDB
instrument.ts:128 User initiated move: 1 Vesper of Radius Chest to Awoken Female Titan from Human Female Warlock
instrument.ts:128 Move 1 Vesper of Radius Chest to Vault from Human Female Warlock
instrument.ts:128 Move 1 Vesper of Radius Chest to Awoken Female Titan from Vault
instrument.ts:128 Resetting lock status of Vesper of Radius to true when moving to Awoken Female Titan to work around Bungie.net lock state bug
instrument.ts:128 Object
instrument.ts:128 Object
instrument.ts:128 Saving profile data to IDB
reducer.ts:442 prepareUpdateQueue: 0.628173828125 ms
instrument.ts:128 [flushUpdates] Flushing queue of 1 updates
instrument.ts:128 [flushUpdates] got results Array(1) Array(1)
instrument.ts:128 Saving profile data to IDB
reducer.ts:442 prepareUpdateQueue: 0.7119140625 ms
instrument.ts:128 [flushUpdates] Flushing queue of 1 updates
instrument.ts:128 [flushUpdates] got results Array(1) Array(1)
instrument.ts:128 Saving profile data to IDB
instrument.ts:128 User initiated move: 1 Wraps of the Emperor's Minister Gauntlets to Vault from Human Female Warlock
instrument.ts:128 Move 1 Wraps of the Emperor's Minister Gauntlets to Vault from Human Female Warlock
instrument.ts:128 User initiated move: 1 Wraps of the Emperor's Minister Gauntlets to Awoken Female Titan from Vault
instrument.ts:128 Move 1 Wraps of the Emperor's Minister Gauntlets to Awoken Female Titan from Vault
instrument.ts:128 Resetting lock status of Wraps of the Emperor's Minister to false when moving to Awoken Female Titan to work around Bungie.net lock state bug
instrument.ts:128 Object
instrument.ts:128 Saving profile data to IDB
reducer.ts:442 prepareUpdateQueue: 0.3779296875 ms
instrument.ts:128 [flushUpdates] Flushing queue of 1 updates
instrument.ts:128 [flushUpdates] got results Array(1) Array(1)
instrument.ts:128 Saving profile data to IDB
reducer.ts:442 prepareUpdateQueue: 0.48388671875 ms
instrument.ts:128 [flushUpdates] Flushing queue of 1 updates
instrument.ts:128 [flushUpdates] got results Array(1) Array(1)
instrument.ts:128 Saving profile data to IDB
instrument.ts:128 User initiated move: 1 Wraps of the Fulminator Gauntlets to Awoken Female Titan from Human Female Warlock
instrument.ts:128 Move 1 Wraps of the Fulminator Gauntlets to Vault from Human Female Warlock
instrument.ts:128 Move 1 Wraps of the Fulminator Gauntlets to Awoken Female Titan from Vault
instrument.ts:128 Resetting lock status of Wraps of the Fulminator to false when moving to Awoken Female Titan to work around Bungie.net lock state bug
d2-stores.ts:195 Process inventory: 212.005859375 ms
d2-stores.ts:199 Inventory state update: 240.459716796875 ms
instrument.ts:128 Saving profile data to IDB
d2-stores.ts:195 Process inventory: 149.889892578125 ms
d2-stores.ts:199 Inventory state update: 161.587158203125 ms
d2-stores.ts:195 Process inventory: 136.76904296875 ms
d2-stores.ts:199 Inventory state update: 213.32861328125 ms
instrument.ts:128 User initiated move: 1 True Prophecy Kinetic to Human Female Warlock from Awoken Female Titan
instrument.ts:128 Move 1 True Prophecy Kinetic to Vault from Awoken Female Titan
instrument.ts:128 Move 1 True Prophecy Kinetic to Human Female Warlock from Vault
instrument.ts:128 User initiated move: 1 True Prophecy Kinetic to Awoken Female Titan from Human Female Warlock
instrument.ts:128 Move 1 True Prophecy Kinetic to Vault from Human Female Warlock
instrument.ts:128 Move 1 True Prophecy Kinetic to Awoken Female Titan from Vault
instrument.ts:128 User initiated move: 1 Witherhoard Kinetic to Awoken Female Titan from Human Female Warlock
instrument.ts:128 Move 1 Witherhoard Kinetic to Vault from Human Female Warlock
instrument.ts:128 Move 1 Witherhoard Kinetic to Awoken Female Titan from Vault
instrument.ts:128 User initiated move: 1 Sweet Business Kinetic to Human Female Warlock from Awoken Female Titan
instrument.ts:128 Move 1 Sweet Business Kinetic to Vault from Awoken Female Titan
instrument.ts:128 Move 1 Sweet Business Kinetic to Human Female Warlock from Vault
instrument.ts:128 User initiated move: 1 True Prophecy Kinetic to Human Female Warlock from Awoken Female Titan
instrument.ts:128 Move 1 True Prophecy Kinetic to Vault from Awoken Female Titan
instrument.ts:128 Move 1 True Prophecy Kinetic to Human Female Warlock from Vault
instrument.ts:128 User initiated move: 1 The Old Fashioned Kinetic to Human Female Warlock from Awoken Female Titan
instrument.ts:128 Move 1 The Old Fashioned Kinetic to Vault from Awoken Female Titan
instrument.ts:128 Move 1 The Old Fashioned Kinetic to Human Female Warlock from Vault
instrument.ts:128 Resetting lock status of The Old Fashioned to true when moving to Human Female Warlock to work around Bungie.net lock state bug
d2-stores.ts:195 Process inventory: 204.693115234375 ms
d2-stores.ts:199 Inventory state update: 340.979736328125 ms

**Comment by bhollis** [comment]
So it does! Thanks for letting us know.

**Comment by BenBeyond** [comment]
Just noticed that it appear to affect consumables count as well, so maybe all vault related counts?
