### ISSUE TITLE
Loadout builder: "Missing legendary or exotic pieces to build a full set"

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#583]
Some users are reporting seeing this even when they do have legendary or exotic items. 

https://www.reddit.com/r/DestinyTheGame/comments/4miryf/dim_v37_the_minmax_loadout_builder_t12_with_ease/d3w2dcn?context=3

https://www.reddit.com/r/DestinyTheGame/comments/4miryf/dim_v37_the_minmax_loadout_builder_t12_with_ease/d3w3uya?context=3

**Comment by ericnelson0** [comment]
This is interesting. 

This will only occur when <code>highestsets == null</code>, and that only happens with the following code:

```
            var helms = bestArmor['helmet'] || [];
            var gaunts = bestArmor['gauntlets'] || [];
            var chests = bestArmor['chest'] || [];
            var legs = bestArmor['leg'] || [];
            var classItems = bestArmor['classItem'] || [];
            var ghosts = bestArmor['ghost'] || [];
            var artifacts = bestArmor['artifact'] || [];

            if(helms.length == 0 || gaunts.length == 0 || chests.length == 0 ||
                legs.length == 0 || classItems.length == 0 || ghosts.length == 0 || artifacts.length == 0) {
                return null;
            }
```

Hopefully this will help someone to debug this issue.

**Comment by ericnelson0** [comment]
Just wanted to say that it could have been possible that the legendaries or exotics these users thought they had were less than 280 light

**Comment by kyleshay** [comment]
haven't seen this in a while, can re-open if people are still running into this.

**Comment by SunburnedGoose** [comment]
https://twitter.com/FinlayJones/status/747885628738633728

This came through just now.

**Comment by kyleshay** [comment]
Looks like an error on the page.... hmmm.

**Comment by ericnelson0** [comment]
Yeah, maybe these reports are just an error on the page causing the static text "missing ..." to show.

Could we get a stack trace from someone with this error?

**Comment by SunburnedGoose** [comment]
They used the beta and it fixed the issue.

**Comment by ericnelson0** [comment]
looks like on line 352:

```normalizeBuckets: function(resetLocked = true) {```

We can't use default values as we aren't supporting ES6 yet.

This was my bad :(

**Comment by bhollis** [comment]
Ha, eslint is set to ignore `dimMinMax.controller.js` because it had too many warnings for me to clean up. Time to roll up my sleeves.
