### ISSUE TITLE
RFC: Change Compare to only show the item you start with

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#5834]
Today, clicking "compare" on an item pre-fills the comparison with all dupes. That's super useful, but it makes it incredibly hard to compare a few specific items, since you have to go and clear out the ones you don't want. 

I propose that we should just start with the item you clicked on, and have a "Dupes" button in the button bar.

**Comment by philkernick** [comment]
If we change it the way you are suggesting, you don't need a "Dupes" button as the first option in the ribbon is the current item, clicking will give you all dupes.
