### ISSUE TITLE
Clear new items button is covered by inventory-title

### ISSUE THREAD

**Issue by nomadjsdev** [DestinyItemManager/DIM#5840]
**What version of DIM are you using?**
6.30.0 (release)

**What Browser and OS are you using?**
Chrome

**Describe the bug and how to make it happen**
Have new items, "Indicate new items" selected, and scroll until `Armor`, `General`, or `Inventory` header div covers up the `Clear new items` button.

<img width="145" alt="clear-new-items" src="https://user-images.githubusercontent.com/58656026/93690331-f0e57d00-face-11ea-80b6-e01f249877a2.png">

**Comment by bhollis** [comment]
On Beta we've removed the "Clear New Items" button and relegated it to Settings.
