### ISSUE TITLE
Power Limit column missing from exported Armor spreadsheet

### ISSUE THREAD

**Issue by pcish** [DestinyItemManager/DIM#5850]

**Comment by bhollis** [comment]
Was it there before?

**Comment by pcish** [comment]
Yes, very certain it was there since early this season until very recently. I have a script that parses the exported csv and I've been using the column in the script.

**Comment by bhollis** [comment]
Cool, I can make sure it gets back in there. By the way, if you're scripting on top of the CSV, you should probably consider just going directly to the Bungie.net API instead. Our CSV is not an API contract, and can and will change.
