### ISSUE TITLE
Item source missing 

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [DestinyItemManager/DIM#5851]
**What version of DIM are you using?**
6.31.0 release orange 

**What Browser and OS are you using?**
Chrome Android

**Describe the bug and how to make it happen**
Item sources are missing in horizontal view. (Planer in German, don't know the English name) 
Like Apokalypse set or new iron banner items (hunter cloak in Screenshot, 2nd item ) . Or dead orbit armor in second screen. Found missing strike/crucible as source for the sets too. 

I found 2 items and the old one has a source. (screen 3)
![Screenshot_20200921-102553_Chrome](https://user-images.githubusercontent.com/2725603/93746429-62b7e680-fbf5-11ea-888f-e5d0352ef78c.jpg)

![Screenshot_20200921-103405_Chrome](https://user-images.githubusercontent.com/2725603/93746854-15884480-fbf6-11ea-935f-e987e119ea78.jpg)
![Screenshot_20200921-103715_Chrome](https://user-images.githubusercontent.com/2725603/93747132-8b8cab80-fbf6-11ea-89ad-778044548f0e.jpg)

**Comment by bhollis** [comment]
@delphiactual I changed around how seasons worked to compute them on demand, but it should be getting the same result. Can you take a quick look?
