### ISSUE TITLE
Toggling item lock status from Compare doesn't update Compare state

### ISSUE THREAD

**Issue by nomadjsdev** [DestinyItemManager/DIM#5852]
**What version of DIM are you using?**
Prod / beta

**What Browser and OS are you using?**
Chrome and Firefox, Windows

**Describe the bug and how to make it happen**
Compare an item and toggle the lock status - in the main app the lock state will be toggled successfully, but Compare lock state persists, meaning you can't toggle the lock state back again from Compare. An item that is locked from Compare will still appear unlocked, though it will show as locked in the main window.

**Include devtools console logs**
Other than the item object on the initial click, no other logs appear

![chrome_sF6L1yyMlj](https://user-images.githubusercontent.com/58656026/93769289-7f164c00-fc12-11ea-9c6d-1c0a93dbdb57.png)

**Comment by bhollis** [comment]
Item lock state is set as a redux action in the item state now. This could be happening if, in some place in Compare, the item was being copied. Is it?

**Comment by bhollis** [comment]
Ah, I see the problem - the items in Compare are captured and stored in state, and so when the original item gets updated (which produces a new item), the version in Compare is outdated. We are long overdue to redo this screen based on the Redux state. I'm planning on getting to that pretty soon - basically gutting Compare and replacing it with the Organizer code, but with roughly the same features and display.
