### ISSUE TITLE
Update the layout for Loadout Optimizer

### ISSUE THREAD

**Issue by nomadjsdev** [DestinyItemManager/DIM#5853]
**Proposed change**
Adjust the LO layout to remove dead space and item overflows from the set rows. There's a lot of dead space at small screen sizes, and for tablets the rows can overflow the screen width, and the stats row crushes the buttons.

<img width="311" alt="chrome_Q4iIXA2krh" src="https://user-images.githubusercontent.com/58656026/93770573-44adae80-fc14-11ea-87c1-b9f06cd68c25.png">
<img width="436" alt="chrome_QQBea4rSnR" src="https://user-images.githubusercontent.com/58656026/93770670-6444d700-fc14-11ea-92a6-8caf7b50b439.png">

**How does this fit into your workflow?**
It'll be prettier :)

**Comment by bhollis** [comment]
Can you sketch out the proposed layout?

**Comment by nomadjsdev** [comment]
No major changes, just slightly better use of space. Initial thoughts were along these lines:

<img width="722" alt="chrome_vcPW01UX2h" src="https://user-images.githubusercontent.com/58656026/93807105-12b34100-fc42-11ea-9061-7b4b0f110d14.png">
<img width="303" alt="chrome_prbJYbOknZ" src="https://user-images.githubusercontent.com/58656026/93807098-1050e700-fc42-11ea-9f2f-5c1de9a434f8.png">

**Comment by bhollis** [comment]
That looks great, I'm into it! grid away!
