### ISSUE TITLE
Search in pull-from sheet goes off screen on Android

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#5876]
**What Browser and OS are you using?**
Android/Chromium 

**Describe the bug and how to make it happen**
Open "pull from" sheet and click search bar

![Screenshot_20200924-172948](https://user-images.githubusercontent.com/424158/94213491-c4917e00-fe8b-11ea-91d2-08ad2f410114.png)

**Comment by bhollis** [comment]
Duplicate of #5730

**Comment by kyleshay** [comment]
thanks! wow, I even filed it haha
