### ISSUE TITLE
Emblem background colors no longer work on desktop

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#5908]
Current beta, Chrome on Windows 10.

![image](https://user-images.githubusercontent.com/25425159/94362545-3f140500-00fb-11eb-8341-2ee5bbea3046.png)

The current what's new says: On mobile, your equipped emblem no longer affects the color of your screen.

This is happening on desktop as well.

My desktop is portrait, but it definitely isn't a phone.

**Comment by bhollis** [comment]
Yes, that is intentional. Background colors are removed in the new design as people were consistently getting confused by them and not all emblems had good colors.
