### ISSUE TITLE
ClickOutside doesn't work when clicking outside content

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#5909]
Current beta, Chrome on Windows 10.

How to repeat.

- Go to the Progress tab
- Click on any Quest or Quest Item (say Chalice of Opulence)
- The detail sheet comes up
- Click anywhere else on that part of the page, and the sheet does not go away
- The only way to make it go away is to click on it again or to click in the left bar menu

This is different to the items in the Inventory tab, where clicking off them closes the detail sheet.  It's also different from what used to happen before the buttons were moved to the right rather than bottom of the detail sheet.

**Comment by bhollis** [comment]
I can't reproduce this. @delphiactual, @nev-r, are you seeing this?

**Comment by delphiactual** [comment]
Nope working as intended for me.

**Comment by nev-r** [comment]
can't duplicate. as far as i know there's no specific click zone (anymore?) to dismiss item popup, so

??

**Comment by philkernick** [comment]
This is absolutely repeatable for me.  How can I provide more debugging?

**Comment by delphiactual** [comment]
screen capture?

**Comment by philkernick** [comment]
Here's a link to a video in my OneDrive.  https://1drv.ms/u/s!AouyL45wUtcSgbAjrdsv6rLdMK_KTA?e=zKdb2W

You can see me clicking on the bottom of the window and the detail sheet does not go away.

**Comment by bhollis** [comment]
Ah yeah, that's actually a long standing bug, the click outside area is bounded to the part with content in it.

**Comment by bhollis** [comment]
For reference, any solution must pass the following test:

1. Open an item popup
2. Click a mod
3. Click a mod in the sheet that pops up from there
4. The popup should not close

**Comment by GrimmiMeloni** [comment]
I had a first look at this, but I am struggling with reproducing the issue as shown in the video.
For me the popup closes as expected when clicking anywhere outside of it.
I used the "Cryptolith Lure" for testing. 

Win 10
Firefox 83
Chrome Version 87.0.4280.66 (Official Build) (64-bit)

**Comment by kyleshay** [comment]
Repro steps:

1) On Desktop go to the "Progress" page
2) Collapse all sections except for the "Bounties".
3) Click on a bounty item to open the tooltip
4) Click anywhere below the collapsed "Tracked Triumphs" section.

**Comment by bhollis** [comment]
It's also easy to repro on the Organizer - search so you have only one item showing, and click that, then try to click on the big empty space below the item.
