### ISSUE TITLE
Husk of the Pit

### ISSUE THREAD

**Issue by mrphlip** [DestinyItemManager/DIM#591]
I think the "Item Levelling" auto-loadout should ignore Husk of the Pit, since it doesn't take experience from bounties and such...

**Comment by bhollis** [comment]
That's totally fair, but I'd rather not hardcode an exception for a weapon most people probably don't have anymore. Can you even still get it?

**Comment by Mulchman** [comment]
Yes. You can still get it.

**Comment by SunburnedGoose** [comment]
Easy fix is to mark it as xp complete when we create it. I'll look at it.

**Comment by kyleshay** [comment]
are there any other items that fall into this category? armsday test weapons?

**Comment by bhollis** [comment]
I'd have to see one of these and poke around at the item JSON, and I don't have one.

**Comment by bhollis** [comment]
Can these still show up after RoI?

**Comment by delphiactual** [comment]
I'll grind out a husk for an hour today, what info do you need once I have it?

**Comment by bhollis** [comment]
I need the item JSON - it's the "item". Variable in processSingeItem. How
are you getting husks?

**Comment by delphiactual** [comment]
Fist of Crota mission, kill `Sword of Crota` go to darkness zone at end, kill self, run back to `Sword of Crota`, go up the stairs, turn around kill him again.

**Comment by delphiactual** [comment]
Ok, it still drops, it took me ~1 hour to get it tho.

![screenshot 2016-10-01 16 22 49](https://cloud.githubusercontent.com/assets/4798491/19017350/7264b5ba-87f3-11e6-91fc-a6d69c8c7609.png)
