### ISSUE TITLE
Exotic masterworks not showing the right bar

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#5920]
https://twitter.com/QuixoticWolve/status/1310724543204528128

@delphiactual can you take a first pass at this?

**Comment by delphiactual** [comment]
digging in to it

**Comment by philkernick** [comment]
Have a look at #3160.  Exotics don't return the same values for masterwork as legendaries.

**Comment by delphiactual** [comment]
@philkernick this was fixed this morning by#5921, #3160 was fixed by #5911
