### ISSUE TITLE
Consumables should no longer be allowed in loadouts

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#5924]
Current beta, Chrome on Windows 10.

At some point recently it became possible to add consumables to a loadout.

![image](https://user-images.githubusercontent.com/25425159/94574841-bc35aa80-02b2-11eb-8c27-d36f2e8cbd38.png)

Even more strangely you can only add exactly one consumable, and the the 5 of swords.

![image](https://user-images.githubusercontent.com/25425159/94574972-e1c2b400-02b2-11eb-9866-5d3785808722.png)

Not that it matters, because adding consumables to a loadout has no meaning.  It might have in D1 when each character had their own consumables, but in D2 it doesn't.

**Comment by bhollis** [comment]
It's always been possible to add consumables to a loadout.

**Comment by philkernick** [comment]
Why?  What is the usecase?  And why is it possible to add exactly 1 consumable?

With the new sidecar view, adding the "Loadout" option to every consumable is going to cause confusion.

**Comment by bhollis** [comment]
People asked for things like making sure to pull crucible boons for their Crucible loadout. It's not as common as in D1 but it's still possible. You can add 1 stack, not just 1 item, and you can add any number of different items.

**Comment by philkernick** [comment]
Strange.  But even in this case it doesn't work as intended.

You can add 1 stack.  After that if you try and add another, the only item you will be able to add is the Five of Swords.  After that if you try and add another nothing is available.  If you do it in the opposite order, add the Five of Swords first, then you can add1 stack of any consumable, but after that nothing.

**Comment by bhollis** [comment]
Sounds like you're referring to the (+) menu, which does appear to have a bug. I'd been trying some of the other ways to add to loadouts, which work fine for multiple consumables.
