### ISSUE TITLE
Weapon Perk Tagging

### ISSUE THREAD

**Issue by SamCullin** [DestinyItemManager/DIM#5930]
**Proposed change**
I would like to be able to tag perks on weapons and have them show up similar to how the curator's recommended perks show up. 

![dim_perk_tag_example](https://user-images.githubusercontent.com/26313903/94631478-f67f6600-030b-11eb-89f3-bf3d129dbe86.png)

**How does this fit into your workflow?**
I would be able to tag perks on weapons I have and perks for weapons I don't have, potentially from in the collections menu. 
![image](https://user-images.githubusercontent.com/26313903/94634116-81fbf580-0312-11eb-958f-528c1c8d1268.png)

After tagging my favorite perks for a weapon I will be able to quickly see in DIM whether the gun is worth keeping.

**Comment by bhollis** [comment]
Thanks for the suggestion. Right now, our solution to this is custom wish lists - the one you get initially is just a default, you can make your own. Eventually we plan to make this easier, but until then here's the guide https://destinyitemmanager.fandom.com/wiki/Creating_Wish_Lists

**Comment by SamCullin** [comment]
Thanks @bhollis  for the info ill take a look and see how close it is.
