### ISSUE TITLE
Loadout Optimizer mobile issues

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#5934]
~1. It seems like there's some extra padding or something, the whole body can scroll back and forth a bit.~
2. It doesn't seem to load/recalculate right. For example I loaded and saw no builds, switched to Warlock and saw Warlock builds, switched back to Hunter and still saw Hunter builds. Changing filters and stuff didn't make it update.

**Comment by kyleshay** [comment]
Have you still been able to repro #2?

**Comment by bhollis** [comment]
Yep I can repro that every time

**Comment by bhollis** [comment]
@ryan-rushton could you take a look at this? It's still happening and it makes LO pretty hard to use on mobile.

**Comment by ryan-rushton** [comment]
Yeah can do.

**Comment by ryan-rushton** [comment]
@bhollis, what browser are you using? It is working fine in safari on my iphone. I am wondering if it is some browser issue with web workers.

**Comment by bhollis** [comment]
I'm using safari on iOS 14.2

**Comment by bhollis** [comment]
Installed to home screen, of course

**Comment by ryan-rushton** [comment]
Ok so I installed mine to the Home Screen too and I do get builds but I don't get the processing indication when I open it. I get builds eventually but I have to wait a bit for them to load.

On safari I do get the process icon.

Can you just check to see if you get that behaviour too.

**Comment by bhollis** [comment]
Ok yeah if I wait quite a while I see it. Still super odd that it doesn't clear immediately when switching characters

**Comment by ryan-rushton** [comment]
Yeah it is, I will have a dig a bit further this afternoon but it might be something to do with it being installed. I haven't had much to do with that kind of thing before so I am pretty keen to dive in and see if I can figure it out

**Comment by ryan-rushton** [comment]
@bhollis can you confirm if 2 is still an issue? I have a feeling it was the loading banner wasn't showing and we fixed that.

**Comment by bhollis** [comment]
Yep it works fine now
