### ISSUE TITLE
FR loadout builder should start with currently logged in character

### ISSUE THREAD

**Issue by nki2bpz** [DestinyItemManager/DIM#594]
I love all the new features and builds. You guys are doing amazing work and i believe by far have made this the single best destiny tool next to my ds4! This is more of an enhancement than issue but  I think it would be a great idea to have the loadout builder query which character you are signed in on and start with that one first. Since it starts auto building my warlock every time i open it i have to hit the drop down to choose the character i'm currently logged in on and start the process over.

**Comment by kyleshay** [comment]
fixed in PR600
