### ISSUE TITLE
Additional spacing between characters on inventory page

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#5944]
Current beta.  Chrome on Windows 10.

Today there has been an update which adds significant spacing between the characters.

Yesterday.

![image](https://user-images.githubusercontent.com/25425159/94919639-f3df6500-04f3-11eb-9646-191a70315fda.png)

Today.

![image](https://user-images.githubusercontent.com/25425159/94919685-05287180-04f4-11eb-9e3f-634d067ae1e3.png)

Notice the the vault has gone from 6 columns down to 4.  This significantly reduces usability.

**Comment by philkernick** [comment]
Some of us - or at least me - use DIM on a desktop with portrait monitor.  We should not assume the portrait means phone or tablet.

**Comment by kyleshay** [comment]
Bumped it to 1440px instead of 1080
https://github.com/DestinyItemManager/DIM/commit/35143eccebc4186961320d6320d752019a74be2b
