### ISSUE TITLE
Consumables in vault not sorted

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#5945]
Current beta.  Chrome on Windows 10.

The stacks of consumables in the vault are not sorted in any meaningful way.

![image](https://user-images.githubusercontent.com/25425159/94925192-f9da4380-04fd-11eb-81ef-e376a1b661b7.png)

There a 4 stacks of gunsmith mats on the first row, with black armory schematics in the middle.
Then another stack in the second row.
Then another stack in the third row.

All are full stacks of 9999.

**Comment by philkernick** [comment]
Also they aren't sorted in your inventory either.

**Comment by bhollis** [comment]
Ah yes, it's been like that for a very long time. It sorts properly if your sort preferences include "rarity" but not if you don't.

**Comment by philkernick** [comment]
If I add rarity to the sort preferences, it does put them together, but it doesn't actually sort by rarity.

![image](https://user-images.githubusercontent.com/25425159/95008225-720c4a80-065f-11eb-84e0-240070f9e3cb.png)

It does work for weapons, armor, ghosts, ships. but not consumables.

**Comment by bhollis** [comment]
That's right. For at least the last three years, Consumables have had their own sort order that isn't really correlated with the custom sort order that's used for all other items. This is to put "like items" together:

https://github.com/DestinyItemManager/DIM/blob/master/src/app/shell/filters.ts#L185-L195
