### ISSUE TITLE
Can't set Custom Total on iOS (iPhone or iPad)

### ISSUE THREAD

**Issue by goddess-eris** [DestinyItemManager/DIM#5946]
**What version of DIM are you using?**
6.32.2 (Release)

**What Browser and OS are you using?**
Safari, Installed as App
iPad OS 13.7, iPhone OS 13.7

**Describe the bug and how to make it happen**
I can't set the custom total on iOS (iPhone or iPad). I've tried both in the dropdown from the Organizer and the Settings.

**Comment by delphiactual** [comment]
Dupe #5937
