### ISSUE TITLE
Filter help window offscreen

### ISSUE THREAD

**Issue by Funktion29** [DestinyItemManager/DIM#5947]
**What version of DIM are you using?**  6.32.2 (release)
 Is the DIM icon orange, or blue? Orange

**What Browser and OS are you using?**
iOS 14.0.1 Installed as an App

**Describe the bug and how to make it happen**
When clicking Filters Help the Filters window opens below screen and is not movable. I tried it in horizontal and vertical modes and got the same result. 
The link to visit the User Guide still works as does the X to close the window. 
![FAA1A382-12AD-4775-91A8-8D29281A6996](https://user-images.githubusercontent.com/22829473/94985239-bf76a380-0509-11eb-847f-aaa39c9b26d5.png)

Thanks

**Comment by bhollis** [comment]
I think this can happen when the filter help contents haven't loaded. Can you try reloading the page?

**Comment by Funktion29** [comment]
I reloaded the page many times. I erased and restored my iPad. I deleted the bookmark from Home Screen and re-added it. It loads fine in Safari but not the “app”. 

Thanks

**Comment by bhollis** [comment]
I'm not sure then. Can you post your developer console output?
