### ISSUE TITLE
D1: Unable to specify the number of items to transfer

### ISSUE THREAD

**Issue by lmpater** [DestinyItemManager/DIM#5955]
Hi. Thank you for the great work.

After the recent UI change for the popup for stackable (like planet materials), I cannot specify the amount to transfer to a particular character.

DIM Version 6.32.2.8619 (beta)
Chrome Version 85.0.4183.121 (Official Build) (64-bit)
Destiny 1

![image](https://user-images.githubusercontent.com/64930576/95004768-bcd58600-05bd-11eb-8770-90998afb057c.png)

**Comment by bhollis** [comment]
This is an intentional change that's mentioned in the "What's New" section: https://github.com/DestinyItemManager/DIM/blob/master/docs/CHANGELOG.md

Can you help me understand why you need to move a specific amount of this item? Can you use the "Distribute Evenly" button to achieve the same purpose?

**Comment by lmpater** [comment]
Hmmm... I have to confess that my initial reaction was simply to say that it was how I've been using DIM, probably since DIM's day one - I am one of those proud to be a Beta player ;-)

Trying to rationalize, I'd like to hear your view on the following use case. Please feel free to point out something I am missing and even to suggest a new, improved way of managing the materials.

Imagine that I have 200 spirit blooms on each character and 100 in the vault - this is sort of a great distribution because I have one and only one stack of the material on each "place", maximized on the characters and with some space to spare on the vault - having all blooms on the vault would mean using 4 spots of the vault just for this material, which in D1 is really not a good idea. 

Now say that I use 22 blooms on my hunter to upgrade a weapon or armor right during an activity. At this point I have 178 on the hunter, 200 on the warlock, 200 on the titan, and the 100 on the vault.  Through all these years, DIM indulged my OCD, allowing me to transfer 22 blooms to my hunter, with the side benefit of using the current size of the stack on the vault as an indication of which material I have to buy or farm. 

With the new UI, I am not sure how I can top up my hunter without ending up with an extra stack of 28 blooms on each character - when I distribute the vault stack evenly among all characters, 22 blooms go to the hunter and the remaining 78 are split into as a stack of 28 on each character, which is not really what I want. Moreover, if the space for materials in one of my characters is full, DIM will probably move something else to the vault, which can be confusing.

Without hearing your opinion on the use case above, and assuming it's a valid use case... If putting back the UI to specify the number of items to transfer is not possible, would it be make sense to have a "top up" option that would be something like "distribute evenly but limit the transfer to have one and only one stack on each character"?

**Comment by bhollis** [comment]
Thanks for the explanation. That helps a lot. The reason we want to remove this is that this kind of fiddly stack management is really only a thing in D1, and we don't really like maintaining code just for D1, as none of the current maintainers play it. 

For the case you mentioned, here's an alternative - transfer the stack from vault to character, then transfer the "remainder" stack back to the vault. That'll make sure you have exactly one max stack on your character.

**Comment by lmpater** [comment]
Makes sense. Dead code is terrible and should be avoided.

As for your comment, indeed sometimes I use that trick from time to time, even with being able to precisely move x items.

I will close this bug.

Thank you so much for DIM. And, for me in particular, for keeping it working with D1! I have to confess that I really didn't like D2.
