### ISSUE TITLE
Double clicking an item in the D1 postmaster visually transfers that item to your character but the D1 API does not support this. 

### ISSUE THREAD

**Issue by jbccollins** [DestinyItemManager/DIM#5968]
**What version of DIM are you using?**
6.33.0

**What Browser and OS are you using?**
Chrome

**Describe the bug and how to make it happen**
Double click an item in the postmaster and watch as DIM "transfers" it to your character. It will even make space.

**Comment by bhollis** [comment]
Can you give some more info about what happens? The D1 API certainly supports moving items...

**Comment by jbccollins** [comment]
The D1 API does not support moving items from the vault to a character. You must manually go to the postmaster in game. With this bug dim visually transfers the item that was double clicked from the vault to your most recent character but that's not what actually happens. If you reload the webpage you'll see that item is actually still in your vault.

**Comment by delphiactual** [comment]
so when you say vault you mean postmaster?

**Comment by jbccollins** [comment]
Ugh I'm an idiot. Yes postmaster. 🤦
