### ISSUE TITLE
Farming Mode Postmaster Improvements

### ISSUE THREAD

**Issue by bmundt** [DestinyItemManager/DIM#5992]
**Proposed change**
Allow the user to configure being alerted when the postmaster is almost full. This alert could play a sound or something.
Automatically pull items from the postmaster in farming mode, this can happen when farming activities where things drop at the end (out of a chest) and you aren't there to pick them up.

**How does this fit into your workflow?**
I would use this when farming strikes and other activities, so that my postmaster doesn't get full and end up deleting items that may be saved there.

**Comment by bhollis** [comment]
Farming mode is already designed to keep your postmaster from filling up, by maintaining empty space in each bucket. Folks have very strong feelings about what should be pulled from postmaster and what should be left, so we've resisted making farming mode automatically do that.

**Comment by bmundt** [comment]
I get that farming mode is designed to keep your postmaster from filling up. But items can still end up going there, if they get left on the ground, or an activity ends before you can go pick them up. I get it that you might not want to move certain items, like engrams or materials that you were saving for next season. Maybe it be configurable to just be rare and legendary armor and weapons, maybe an option in settings?

**Comment by bhollis** [comment]
We generally avoid adding options for things: https://github.com/DestinyItemManager/DIM/wiki/Frequently-Requested-Features#add-an-option-for-it

**Comment by bmundt** [comment]
I can understand not wanting to add more options. What about just pulling armor and weapons from the postmaster?

**Comment by kyleshay** [comment]
We may extend farming mode in the future. I've thought about how to build it out and into the new upcoming 'active mode'. I think right now we may just recommend people to hit farming mode and have it running in the background. Use the 1 click 'Pull from postmaster' at the beginning or sometime during. Changes are it won't fill up before the next time DIM refreshes. 

We'll absolutely be circling back around to farming mode enhancements after beyond light drops.

For now, I'm going to link this task to the active mode ticket https://github.com/DestinyItemManager/DIM/issues/5976 and close this task. Thanks for your feedback!
