### ISSUE TITLE
In compare on mobile some perk imgs are out of line

### ISSUE THREAD

**Issue by rekcluse** [DestinyItemManager/DIM#5994]
**What version of DIM are you using?**
Version 6.34.0 (release), built on 12/10/2020, 01:07:10 Orange

**What Browser and OS are you using?**
DIM App from Play Store. (Andriod)

**Describe the bug and how to make it happen**
When clicking compare icon and bringing up compare tab some of the perk images are out of line as seen in img. 

Thank you

![20201012_175710](https://user-images.githubusercontent.com/62358799/95772301-68fd2800-0cb4-11eb-91db-a2a49153edd3.jpg)

**Comment by bhollis** [comment]
I think you're seeing the masterwork kill tracker for one item overlapping into the next. I can fix this.
