### ISSUE TITLE
Equations(feature request)

### ISSUE THREAD

**Issue by ModEngineer** [DestinyItemManager/DIM#5995]
**Proposed change**
Equation feature that allows the performing of mathematical operations on stats. An example of this would be `(stat:total-stat:strength):<50`. This would allow for finding all armor where everything but strength totals to less than or equal to 50.

**How does this fit into your workflow?**
This fits into my workflow by opening up more options for complex item filtration, weapon selection based on a mathematical formula such as something that calculates a weapon "score" based on its stats, and overall inventory management and automated item junk-tagging based on low stats. I currently have quite a bit of legendary armor that doesn't _quite_ make the cut and I would like to be able to systematically filter it out.

**Comment by kyleshay** [comment]
Would this work differently from how `stat:strength:<50` or `basestat:strength:<50` work today?

**Comment by kyleshay** [comment]
There is an option for setting a custom combination of stats in settings, would this work for most cases?
<img width="494" alt="Screen Shot 2020-10-12 at 4 44 04 PM" src="https://user-images.githubusercontent.com/424158/95799654-2e8e8d80-0caa-11eb-9500-65084b4511b6.png">
