### ISSUE TITLE
Destiny Exotics Listing No Longer in V3

### ISSUE THREAD

**Issue by brandonkboswell** [DestinyItemManager/DIM#60]
This was probably a conscious decision, but I wanted to bring it up just in case it was missed.

**Comment by robpoole** [comment]
Further to this it would be great if you can add Prison of Elders gear, Trials of Osiris gear, and Queens Wrath gear to the page. 

Also for the class items which cannot be upgraded it would be great if they showed as fully upgraded automatically.

Finally it would be great if there was a summary at the bottom of the page to say something like 180/200 items collected 90%.

**Comment by SunburnedGoose** [comment]
@kyleshay When do we want to push v3.1 w/ this feature?

**Comment by kyleshay** [comment]
should we consider just creating a link to a user's destinytracker collection page instead of an in-app solution?
