### ISSUE TITLE
Suggested Perks 

### ISSUE THREAD

**Issue by kellyrogers81** [DestinyItemManager/DIM#6004]
**What version of DIM are you using?**
6.34.0

**What Browser and OS are you using?**
 Chrome on computer, not home to check version, using the app on my phone. Issue is on PC and app. 

**Describe the bug and how to make it happen**
All my suggested Perks are gone. I must have hit something cause suddenly I had like 22k rolls in my wishlist! So I cleared that, however now no thumbs up on anything. Last night it was only that way on my PC. Now it's like that on my app too, so I can't see any of them.

**Comment by bhollis** [comment]
If you cleared your wish list, it'll be cleared everywhere. You can reapply it from Settings.

**Comment by kellyrogers81** [comment]
But I never created a wishlist. It used to be suggested Perks from y'all I
thought? Like when I logged on yesterday suddenly everything had thumbs up
perk with a white circle around them, which was way different than the day
before. drop down box with fav, junk, keep etc.. was gray, and the button
you used to hit to compare (looked kind of like 2 piece of paper laid over
one another kinda) is now a balance deal.

I did go to settings to try this wishlist but it goes to my files to find
it. I for sure have never saved a file I've not been using this long. I'm
sorry I'm probably just being totally dumb here.

When I joined DIM it automatically showed me if my weapons had suggested
Perks, with a thumbs up icon. Sometimes even a quick tip from players on
their thoughts and recommended masterwork. Typically it was pretty similar
to what is on light gg, but was nice I didn't have to use that site anymore
and could see right on the card. Now not so much. Any chance this makes
more sense to the type of issue I'm having?

I appreciate any direction as I'd like to see your suggested Perks, not a
wishlist I create on the side. I don't know enough to wishlist anything 😂

**Comment by kellyrogers81** [comment]
Omg nevermind, I finally found the premade link to put in. Now I'm just
confused why the appearance is different suddenly, but I'll shut up and
move on. 😂😂 Thanks for the help 👍

**Comment by kyleshay** [comment]
We'll make it easier in the future to 'reset' to the default and automatically load:

https://raw.githubusercontent.com/48klocs/dim-wish-list-sources/master/voltron.txt

in the box if you clear it- we'll track that in #5337 

Glad you got it working!

**Comment by kyleshay** [comment]
We moved from the green thumbs up to the new blue with circle as we're currently redesigning the item inspect sheet to be more clear. There are some additional changes on the way. It's all going to make sense really soon! Existing users should find it easier to use, and use users should be able to quickly jump in.

**Comment by kellyrogers81** [comment]
Can't wait, I absolutely love this site! I'm a data person and I love being
able to dig in and manage all the things. Thanks again!!
