### ISSUE TITLE
Tag overlay cut off.

### ISSUE THREAD

**Issue by ShiloTobin** [DestinyItemManager/DIM#6005]
![image](https://user-images.githubusercontent.com/43517942/95925055-d9747980-0d86-11eb-8e8f-8cf0104dbef2.png)

**Comment by kyleshay** [comment]
Thanks for the report! Technically this will be resolved as part of https://github.com/DestinyItemManager/DIM/pull/6014 because this view will be going away.

**Comment by kyleshay** [comment]
actually i'll keep this open as it may still be an issue on mobile for now.

**Comment by bhollis** [comment]
I don't think it's a mobile issue, it'll get pushed in by the screen edge.

**Comment by kyleshay** [comment]
ah yes, confirmed on mobile it's a non-issue
