### ISSUE TITLE
Autocomplete search should offer shortest unique match first

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#6009]
Current beta.  Chrome on Windows 10.

The order it presents, should be shortest match first.

Example search for "arm".

![image](https://user-images.githubusercontent.com/25425159/95946539-4b56cc80-0e34-11eb-991f-aa28d071fb8c.png)

Order should be:

- is:armor
- is:sidearm
- is:armor2.0
- is:armormod
- season:warmind
- source:blackarmory

Example search for "is:arm"

![image](https://user-images.githubusercontent.com/25425159/95946608-6de8e580-0e34-11eb-85da-b890bf7f2e7f.png)

Order should be:

- is:armor
- is:armor2.0
- is:armormod

This is fundamentally a reversion of the same issue as #4877 but it's now done automatically.

**Comment by nev-r** [comment]
i disagree that "arm" should suggest "sidearm" before "armor2.0",
but hopefully the changes in #6031 feel a little more right
