### ISSUE TITLE
Bring back keyboard shortcuts for page/section navigation

### ISSUE THREAD

**Issue by gflujan** [DestinyItemManager/DIM#6012]
**Proposed change**
I would like to have the keyboard shortcuts that navigate to "Inventory (I)", "Progress (P)", "Vendors (V)", etc. I'm not sure why you got rid of them in the first place but there are very helpful. 

**How does this fit into your workflow?**
It fit's into my workflow because I can navigate around and search for items quickly using just the keyboard. I tend to do this in between activities while in orbit.

**Comment by bhollis** [comment]
Hmm, we got rid of them because we didn't think anyone was using them and because it didn't seem like switching between views needed to be that immediate. What's your workflow that involves switching between views?

**Comment by bhollis** [comment]
No response.
