### ISSUE TITLE
Percentage roll range goes off the edge of the move popup

### ISSUE THREAD

**Issue by ericnelson0** [DestinyItemManager/DIM#603]
This normally happens when a 100% or higher is involved.

![image](https://cloud.githubusercontent.com/assets/4594931/16024354/0ed5cc90-3187-11e6-8b51-c83a9d6af372.png)

**Comment by bhollis** [comment]
The problem here is the "stats quality" text is stretching the bars.

**Comment by bhollis** [comment]
Fix is in #606.
