### ISSUE TITLE
How to enable the ActiveMode?

### ISSUE THREAD

**Issue by rentalhost** [DestinyItemManager/DIM#6046]
**What version of DIM are you using?**
Versão 6.35.0.8817 (beta), construído em 19/10/2020 07:11:10

**What Browser and OS are you using?**
Chrome 86 (stable)

**Describe the bug and how to make it happen**
Where can I found/enable the Active Mode? I am a translator, but I need see where the translation will be applied, but I really can't see the Active Mode working, even using the beta version.

**Include devtools console logs**

```
[loadout optimizer] found 200 stat mixes after processing 254898 stat combinations in 488.89999999664724 ms
[app] DIM v6.35.0.8817 (beta) - Please report any errors to https://www.github.com/DestinyItemManager/DIM/issues
[dim sync] globalSettings {dimApiEnabled: true, destinyProfileMinimumRefreshInterval: 15, destinyProfileRefreshInterval: 30, autoRefresh: false, refreshProfileOnVisible: true, …}
Load manifest: 1477.84814453125 ms
[dim sync] Saving profile data to IDB
Process inventory: 139.52587890625 ms
Inventory state update: 90.61083984375 ms
[swipe] 0
[farming] Started farming Caçador Desperta
```

**Comment by bhollis** [comment]
It hasn't been released to beta yet, it only shows up in local development.

**Comment by delphiactual** [comment]
@rentalhost When I get home I will take some screenshots for you and post them in Discord.

**Comment by rentalhost** [comment]
@delphiactual Thank you! I appreciate it!
