### ISSUE TITLE
Loadout Optimizer and Rasputin Mods

### ISSUE THREAD

**Issue by Baya86** [DestinyItemManager/DIM#6053]
Hi there,

I'm using DIM v6.35

When you're selecting mods in the Loadout Optimizer, all Rasputin mods have the same description: "Defeating a combatant...blabla." It would be more useful to see what they're doing :-)

**Comment by Baya86** [comment]
Wow, that was fast. Great work, thank you very much!

**Comment by bhollis** [comment]
Thanks to @krizp !
