### ISSUE TITLE
Loadout builder: What can we do to make it more accessible? UI/UX help needed.

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#607]
We just dropped the Loadout Builder page into DIM without giving users a real explanation on what it is for, or how to use it.

What can we do to make it more intuitive? Is it a UX issue?

Some users have also asked to have better filtering options for building a loadout, such as easily filtering things that have specific perks (more shotgun ammo, arc defense, etc...) How could something like that be added in without it becoming even more confusing? 

Would we be able to make this page look/feel/behave more like pages that deal with filter and sorting data based on multiple criteria? Maybe we can look to experiences on commerce/travel/etc sites?

<img width="913" alt="screen shot 2016-06-14 at 11 34 40 am" src="https://cloud.githubusercontent.com/assets/424158/16048971/05e3821a-3224-11e6-9db1-60169300eb59.png">

<img width="952" alt="screen shot 2016-06-14 at 11 36 46 am" src="https://cloud.githubusercontent.com/assets/424158/16049066/609e1fd0-3224-11e6-87e4-69f6ef182839.png">

<img width="1203" alt="screen shot 2016-06-14 at 11 32 47 am" src="https://cloud.githubusercontent.com/assets/424158/16048912/c8fa5950-3223-11e6-8a05-d3b8b72fc290.png">

**Comment by delphiactual** [comment]
One improvement that I see that could be made is if the `Intellect` node is specified and already chosen some way of indicating that on this page.

**Comment by kyleshay** [comment]
#629 fixes some of these issues, still can use some work, but we'll create an issue for em when we consider them.
