### ISSUE TITLE
Calculations rounding up? 

### ISSUE THREAD

**Issue by altaylor1123** [DestinyItemManager/DIM#6089]
**What version of DIM are you using?**
Find the version in "About DIM" from the menu (the button with three bars on the upper left of the screen). Is the DIM icon orange, or blue?

Version 6.36.1.8935 (beta)

**What Browser and OS are you using?**
It helps to know what type of browser and what version you're using. Have you installed DIM as an app through Chrome or Safari?

Firefox, Windows 10

**Describe the bug and how to make it happen**
Tell us what's wrong. A great format for bug reports is "I did X, and I expected Y, but instead Z happened." If it helps illustrate the issue, please add screenshots to help explain your problem.

Seems like the calculations are rounding up to the next tier. I removed the mods, like Recovery, to be sure. Still inaccurate. 

As an aside, you guys are awesome. Thanks for making DIM.  

![2020-10-29_21-21-23](https://user-images.githubusercontent.com/7553195/97652681-fa96c480-1a2c-11eb-9e73-1409efb886a1.png)
![2020-10-29_21-22-42](https://user-images.githubusercontent.com/7553195/97652691-02566900-1a2d-11eb-93dc-9863091e150e.png)

**Include devtools console logs**
If you can, open the devtools console (ctrl+shift+J on PC and cmd+option+J on Mac) and paste what you see in the window that pops up:

```
Paste console logs here
```
![2020-10-29_21-24-42](https://user-images.githubusercontent.com/7553195/97652765-303bad80-1a2d-11eb-8883-30ed3bdce9b2.png)

**Comment by kyleshay** [comment]
is it possible that you have assume masterwork checked?

**Comment by altaylor1123** [comment]
Welp, I did have it checked. I don't recall ever checking that, but it was checked. User error, sorry.

**Comment by kyleshay** [comment]
All good! I'm sure we could do something to better indicate it's active.
