### ISSUE TITLE
Display all character items / all items in MinMax

### ISSUE THREAD

**Issue by thesamprice** [DestinyItemManager/DIM#609]
When trying to clean up my inventory I like to see all items and destroy the the ones that have the worst roll.

**Comment by thesamprice** [comment]
![screen shot 2016-06-15 at 10 09 57 am](https://cloud.githubusercontent.com/assets/817712/16082871/05186a72-32e1-11e6-9c65-a3edb394642e.png)

**Comment by bhollis** [comment]
@thesamprice since I don't really use this screen, could you explain what makes this different from its normal state? It kinda always looks like that when I try it.

**Comment by kyleshay** [comment]
Thanks @thesamprice! Is this gaining us anything aside just seeing everything at once? Wouldn't tabbing through your different characters be enough? This page is pretty complex and I want to control the amount of features that go into it. If people are interested in something like this, I'd like to hear it.

**Comment by thesamprice** [comment]
When I am looking to destroy items, or to find infusible stuff I like to sort by all.
Mostly just use it for vault cleanup.  Though in sept we get inf vault space so that won't be an issue then.

**Comment by kyleshay** [comment]
I'm also not fully convinced that this feature is necessary, but am open to further discussion on this.

By the way: on the main DIM page there is a setting to be able to sort by the stat roll percent property, maybe that would help solve your use case? 

(`Enable advanced stat quality comparison` feature must be enabled to view this option)

![screen shot 2016-06-28 at 10 54 26 am](https://cloud.githubusercontent.com/assets/424158/16420279/b619be60-3d1e-11e6-8998-97f88dd5b459.png)

**Comment by kyleshay** [comment]
@thesamprice, thoughts on sorting by stat roll percent? does that help, or would having a separate page be better.

can anyone else comment?

**Comment by thesamprice** [comment]
Yea sorting by stat roll will be fine

On Thu, Jul 7, 2016 at 10:15 PM, kyle shay <notifications@github.com> wrote:

> @thesamprice <https://github.com/thesamprice>, thoughts on sorting by
> stat roll percent? does that help, or would having a separate page be
> better.
>
> can anyone else comment?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/DestinyItemManager/DIM/issues/609#issuecomment-231259188>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAx6MAFAF3jJz7jJ0pjaQD8yuZlE8xxuks5qTbKrgaJpZM4I15do>
> .
>



-- 
Thank you,

Sam Price
(707) 742-3726

**Comment by kyleshay** [comment]
Cool, thanks! Closing this until future notice then.
