### ISSUE TITLE
Lost my character tabs???

### ISSUE THREAD

**Issue by PlagueRiot** [DestinyItemManager/DIM#6090]
When clicking on a weapon there used to be an icon on the bottom for each of my characters that I could click on to send the weapon to that character. They are now gone. Did I screw something up or was this intentional? It was really handy and my most used feature, I would like it back please.

```
Paste console logs here
```

**Comment by delphiactual** [comment]
Look to the left or right

**Comment by PlagueRiot** [comment]
Thanks.
    On Friday, October 30, 2020, 06:40:16 AM PDT, Rob Jones <notifications@github.com> wrote:  
 
 


Look to the left or right
