### ISSUE TITLE
Safari: Tags dropdown not connected to button

### ISSUE THREAD

**Issue by blademan007** [DestinyItemManager/DIM#6091]
DIM 6.36.1
Safari 14.0

Click on inventory item on right side of vault, then clicked on tags, expecting tag options to display. Unexpectedly tag displays in a searate window, window disapears when mouse over. Only occurs on items at far right side of inventory, in vault.

![Screen Shot 2020-10-30 at 10 35 22 AM](https://user-images.githubusercontent.com/44634730/97739773-8b0ced80-1a9d-11eb-8bc8-70570cb8a7d6.png)

```
[Log] [dim sync] – "Saving profile data to IDB" (main-594819.js, line 1)
[Debug] Process inventory: 74.607ms (main-594819.js, line 1)
[Debug] Inventory state update: 72.081ms (main-594819.js, line 1)
[Log] [dim sync] – "Saving profile data to IDB" (main-594819.js, line 1)
[Debug] prepareUpdateQueue: 0.827ms (main-594819.js, line 1)
[Log] [flushUpdates] – "Flushing queue of" – 1 – "updates" (main-594819.js, line 1)
[Log] [flushUpdates] – "got results" (2) (main-594819.js, line 1)
[{action: "setting", payload: {sidecarCollapsed: false}, before: {sidecarCollapsed: true}}] (1)
[{status: "Success"}] (1)
[Log] [dim sync] – "Saving profile data to IDB" (main-594819.js, line 1)
```

**Comment by bhollis** [comment]
Can reproduce, looks to be an issue on Safari only
