### ISSUE TITLE
Mods for loadouts

### ISSUE THREAD

**Issue by ryan-rushton** [DestinyItemManager/DIM#6094]
I am starting a new issue for this rather than working off #5420 so everyone gets some visibility and because this probably has a couple of extensions from the original request. Happy to move it over to that issue though if people prefer.

I have started working on the first 3 but the way I see it the following need to be done. Please feel free to add anything I may have missed.

- [x] Save mods in dim-api
- [x] Display mods in loadout drawer
- [x] Save locked mods from optimiser builds
- [x] Ability to add and delete mods from the loadout drawer
- [ ] Only allow adding mods that meet energy/slot requirements (slot requirements are less of a concern with beyond light changes).
- [ ] Ability to compare mods to currently equipped mods on items
- [ ] Provide suggestion for cheapest way to apply all loadout mods

**Comment by bhollis** [comment]
Mods are already saved in DIM API when loadouts are created with Loadout Optimizer
