### ISSUE TITLE
6.37.0 weapon perk icons are too small on desktop

### ISSUE THREAD

**Issue by bording** [DestinyItemManager/DIM#6102]
**Proposed change**
While I like the changes made in 6.37.0 to emphasize the archetype info, I feel that the perk icons are now too small when viewing them on desktop. Can the size change either be reverted or made configurable in some way?

**Comment by bhollis** [comment]
Screenshot? They're roughly the same size as they used to be, at the default icon size setting. What do you have your icon size set to?

**Comment by kyleshay** [comment]
ah yeah the sizes are the same, may just appear smaller since they're all alone now. they were always 30px (can check on the main app). we have some upcoming iterations that should help balance things out.

**Comment by bording** [comment]
I have my item size maxed out to 66px, and the perk icons are noticeably smaller than they used to be. Were they being scaled with items size before and now they aren't?

![image](https://user-images.githubusercontent.com/753669/97949443-a445c080-1d61-11eb-9116-440ae746e082.png)

**Comment by bhollis** [comment]
They used to scale with the icon size, now they don't. I'd love to remove that icon size setting, it makes everything more complicated. Can you reset the icon size to 50px and just zoom the page?

**Comment by bording** [comment]
> They used to scale with the icon size, now they don't. I'd love to remove that icon size setting, it makes everything more complicated. 

I would really prefer that you not do that. The default icon size is way too small for me.

> Can you reset the icon size to 50px and just zoom the page?

That isn't remotely the same experience at all. That causes all the UI to scale up, but I really just want the item icons larger.
