### ISSUE TITLE
Loadout Builder doesn't refresh when I change platforms.

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#612]
I play on both Xbox and PS.  When I switch between platforms, my items do not refresh while in this screen.

**Comment by bhollis** [comment]
That's concerning. Ideally it should refresh whenever `dim-stores-updated` is fired.

**Comment by kyleshay** [comment]
@SunburnedGoose would you mind testing this again now that settings have changed a bit per #637?

**Comment by TheHandsomeCoder** [comment]
Looks like it can't refresh in general when it's on that page. I was trying to use it to see if I'd gotten tier12 on an exotic class item and ended up having to switch back and forth between inventory and comparison

**Comment by bhollis** [comment]
This is still an issue - dimMinMax.controller doesn't listen for `dim-stores-updated`.

**Comment by kyleshay** [comment]
Closing because it's a minor legacy issue.
