### ISSUE TITLE
Hide unfiltered items when searching

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#613]
'hide unfiltered items when searching' doesn't look so hot.

i'd like to see that option collapse as much as possible for sections that nothing is found. the idea is if you're searching for something, you shouldn't have to scroll.

current:
![screen shot 2016-06-15 at 1 49 49 pm](https://cloud.githubusercontent.com/assets/424158/16091091/2735b00a-3300-11e6-8aa5-493df0553bd4.png)

(somewhat) expected:
![screen shot 2016-06-15 at 1 57 08 pm](https://cloud.githubusercontent.com/assets/424158/16091329/247822e8-3301-11e6-9ba8-9c0edbba5d98.png)

**Comment by bhollis** [comment]
Fixed in #601.

**Comment by delphiactual** [comment]
Also on this note if that option is not selected the items that do not match aren't dimmed

![screenshot 2016-06-16 23 10 45](https://cloud.githubusercontent.com/assets/4798491/16141340/bd241300-3417-11e6-9880-a22bf4d6ce52.png)

**Comment by bhollis** [comment]
@delphiactual I've pushed a fix to that branch.

**Comment by delphiactual** [comment]
@bhollis awesome just test and can confirm.

**Comment by bhollis** [comment]
I've done some fixes for completely empty rows - they don't 100% collapse yet, but the "empty bucket" background is now gone.

**Comment by kyleshay** [comment]
i'm happy enough with that for now. at least things are properly aligning. we can revisit this feature in the future to modify/enhance/remove it
