### ISSUE TITLE
Gimme back my gender

### ISSUE THREAD

**Issue by yzpmpgq** [DestinyItemManager/DIM#6133]
I know it may be a politically correct decision or something, but why did you take away the gender?  I keep 2 screens open for my wife's account and mine and can easily tell them apart by "woken male", or "woken female", etc.  If you need to take it away, give us an option in the settings at least...

**Comment by delphiactual** [comment]
Bungie changed to `masculine` and `feminine`, which are too long to fit

**Comment by nev-r** [comment]
ask your wife to teach you how to switch emblems
