### ISSUE TITLE
Something went wrong: Cannot read property 'displayProperties' of undefined

### ISSUE THREAD

**Issue by ModEngineer** [DestinyItemManager/DIM#6134]
**What version of DIM are you using?**
Find the version in "About DIM" from the menu (the button with three bars on the upper left of the screen). Is the DIM icon orange, or blue?
6.38.0, stable

**What Browser and OS are you using?**
It helps to know what type of browser and what version you're using. Have you installed DIM as an app through Chrome or Safari?
Chrome Version 86.0.4240.193 (Official Build) (64-bit), Windows 10 version 2004, DIM is installed as a Chrome "App"

**Describe the bug and how to make it happen**
Tell us what's wrong. A great format for bug reports is "I did X, and I expected Y, but instead Z happened." If it helps illustrate the issue, please add screenshots to help explain your problem.
I clicked on <any navigation button either at the top or in the hamburger menu navbar>, I expected to be taken to the page, but instead, I'm met with:
![image](https://user-images.githubusercontent.com/43882205/98813048-35afd500-23e9-11eb-9e41-3a185f9482b3.png)
I'm able to load DIM and view one page, and if I try to navigate to any other DIM page, it gives me the above error. I can temporarily fix this per-page by refreshing, but it returns each time I navigate to a new one.

**Include devtools console logs**
If you can, open the devtools console (ctrl+shift+J on PC and cmd+option+J on Mac) and paste what you see in the window that pops up:

```
react-dom.production.min.js:216 TypeError: Cannot read property 'displayProperties' of undefined
    at Progress.tsx:118
    at ra (react-dom.production.min.js:157)
    at zu (react-dom.production.min.js:267)
    at ks (react-dom.production.min.js:250)
    at xs (react-dom.production.min.js:250)
    at Os (react-dom.production.min.js:250)
    at ps (react-dom.production.min.js:243)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
    at Ho (react-dom.production.min.js:122)
ou @ react-dom.production.min.js:216
log.ts:33 [DIM Code] TypeError: Cannot read property 'displayProperties' of undefined
    at Progress.tsx:118
    at ra (react-dom.production.min.js:157)
    at zu (react-dom.production.min.js:267)
    at ks (react-dom.production.min.js:250)
    at xs (react-dom.production.min.js:250)
    at Os (react-dom.production.min.js:250)
    at ps (react-dom.production.min.js:243)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
    at Ho (react-dom.production.min.js:122) Object
```

**Comment by ModEngineer** [comment]
For some reason it isn't happening anymore? Maybe DIM got updated or Chrome bugged out.

**Comment by qrdean** [comment]
I am having this issue as well but only when I try to select the Progress Tab. Here's an output from Firefox:
```
TypeError: s.PresentationNode.get(...) is undefined
    default https://app.destinyitemmanager.com/progress-f31bc9.js:1
    ra https://app.destinyitemmanager.com/vendors-main-347f03.js:2
    Ba https://app.destinyitemmanager.com/vendors-main-347f03.js:2
    zu https://app.destinyitemmanager.com/vendors-main-347f03.js:2
    ks https://app.destinyitemmanager.com/vendors-main-347f03.js:2
    xs https://app.destinyitemmanager.com/vendors-main-347f03.js:2
    Os https://app.destinyitemmanager.com/vendors-main-347f03.js:2
    ps https://app.destinyitemmanager.com/vendors-main-347f03.js:2
    Ko https://app.destinyitemmanager.com/vendors-main-347f03.js:2
    unstable_runWithPriority https://app.destinyitemmanager.com/vendors-main-347f03.js:2
    Ho https://app.destinyitemmanager.com/vendors-main-347f03.js:2
    Ko https://app.destinyitemmanager.com/vendors-main-347f03.js:2
    $o https://app.destinyitemmanager.com/vendors-main-347f03.js:2
    hs https://app.destinyitemmanager.com/vendors-main-347f03.js:2
    notify https://app.destinyitemmanager.com/vendors-main-347f03.js:2
    notifyNestedSubs https://app.destinyitemmanager.com/vendors-main-347f03.js:2
    handleChangeWrapper https://app.destinyitemmanager.com/vendors-main-347f03.js:2
    g https://app.destinyitemmanager.com/vendors-main-347f03.js:2
    r https://app.destinyitemmanager.com/vendors-main-347f03.js:2
    dispatch https://app.destinyitemmanager.com/vendors-main-347f03.js:2
    o https://app.destinyitemmanager.com/main-3ab23b.js:1
vendors-main-347f03.js:2:553982
```

**Comment by ModEngineer** [comment]
You mentioned that it's only when you select the Progress tab... I just noticed that if I launch DIM normally and then immediately switch to the progress tab, it gets stuck in the TypeError. From here, I can navigate to other pages but they also just display the same TypeError.

**Comment by ModEngineer** [comment]
Yup, the bug is probably with the "Progress" tab. No other tabs cause the error, but  the error stays on-screen and prevents other DIM pages from displaying if you navigate to them.

**Comment by bhollis** [comment]
Please try the Beta where this has been fixed since yesterday.

**Comment by bhollis** [comment]
Pushed to release.
