### ISSUE TITLE
Don't consider stackables pullable from postmaster if the stack is full

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#6137]
Specifically, I have 25 upgrade modules, but it still thinks I could pull these upgrade modules:
![image](https://user-images.githubusercontent.com/313208/98879030-61f34200-2439-11eb-9514-f8f6727b57f6.png)

**Comment by jaaneh** [comment]
This is still an issue on my end. 
![](https://jaany.xyz/i/cp3zy.png)

**Comment by delphiactual** [comment]
what version are you using, since you cropped that out?

**Comment by jaaneh** [comment]
Where would the version be displayed? There's no version anywhere on the inventory page for me.

What's New page latest shows 6.38.1

**Comment by delphiactual** [comment]
so orange icon? it is fixed in beta currently and the fix will go live to app tonight at ~5pm PST
