### ISSUE TITLE
FR: Duplicate weapon decision tool

### ISSUE THREAD

**Issue by therarecommoner** [DestinyItemManager/DIM#614]
Have 2+ of a thing? Rank them non-emotionally based on core metrics (range, key perks, etc.) that is user definable to some degree.

- Show attribute buff/nerf stats for each scope/barrel/perk as Reddit user here did for Grasp of Malok

https://www.reddit.com/r/CruciblePlaybook/comments/3pgnti/best_roll_grasp_of_malok_with_numbers_wall_of_text/?ref=search_posts

- User selects (and in doing so, ideally stores) their preferences in rank order 1-3 for each gun type

- DIM compares base stats of select weapon and determine closest to perfect roll per user inputs. 

Enables user a quick method to infuse, shard or keep.

**Comment by kyleshay** [comment]
hey @therarecommoner! thanks for the suggestion. this sound similar to (or a combination of) #494 and #515 

i'm going to copy your post to those and close this one. let us know if you have any other ideas in those tickets!
