### ISSUE TITLE
Add half tiers to loadout optimizer

### ISSUE THREAD

**Issue by wanton7** [DestinyItemManager/DIM#6144]
**Proposed change**
Now as of Beyond Light you have mods that adds +5 to a stat. So it would be very beneficial also if loadout optimizer would support .5 tiers.

**How does this fit into your workflow?**
To find most optimal loadout because 7.5 tiers is better than 7 tiers now that we have +5 stat mods that cost 1 point.

**Comment by bhollis** [comment]
Check out our User Guide for Loadout Optimizer: https://destinyitemmanager.fandom.com/wiki/Loadout_Optimizer

You don't need to calculate stats on you own - the point of Loadout Optimizer is that it calculates stats for you. Lock the mods you want, and it'll tell you what tiers you get from that.
