### ISSUE TITLE
I want to know which slots are below my base power level

### ISSUE THREAD

**Issue by kevinsmendes** [DestinyItemManager/DIM#6147]
**Proposed change**
Search filter to only show items at or above our power level (without the artifact), which changes automatically as our level increases. Helps a to knowing which slot we can improve by just looking at it an not checking every slot.

**How does this fit into your workflow?**
Very useful for leveling. Instead of checking our power level is 1207, for example and checking every slot if have a 1207 already, the filter would automatically do that for us. It would be the same as doing a `power:>=1207`, but automatically, like: `is:basepower` or something like that.

**Comment by delphiactual** [comment]
If we do add this we should also add softcap, hardcap, and pinnaclecap

**Comment by bhollis** [comment]
@kevinsmendes have you tried clicking your base power? You get a menu like this:
<img width="304" alt="image" src="https://user-images.githubusercontent.com/313208/99105704-d5ab6100-2597-11eb-8e1a-8fea502d31f7.png">
