### ISSUE TITLE
In settings, event applied before updating setting

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#615]
![settings](https://cloud.githubusercontent.com/assets/4798491/16168878/de82f41c-34d5-11e6-9c6c-21c4087c7a07.gif)

Easiest to see when changing character order, both radio buttons are selected until the function completes... Not a big deal, just something I noticed.

**Comment by bhollis** [comment]
I'm rewriting the settings stuff soon so I'll see with this then
