### ISSUE TITLE
The same exact loadout, but with different end stats values

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#617]
Check out the int between the two. The correct one is 242.

![screenshot 2016-06-18 21 40 49](https://cloud.githubusercontent.com/assets/4798491/16175034/bd0410a0-359d-11e6-9ed7-058364f41db1.png)

**Comment by SunburnedGoose** [comment]
What is wrong with the 243 INT loadout?

**Comment by delphiactual** [comment]
It's not possible, the max int I can get with those Bonuses is 242

**Comment by SunburnedGoose** [comment]
Can you equip, set the perks, and give me a link to DestinyTailor.com?

**Comment by delphiactual** [comment]
http://destinytailor.com/psn/delphiactual/hunter

**Comment by SunburnedGoose** [comment]
Destiny Tailor reports 243 INT is possible.  I did the math to get the 4/5/1 build that is documented in the screenshot.

**Comment by delphiactual** [comment]
Its the same nodes, being used in both loadouts... is it a rounding error?

**Comment by SunburnedGoose** [comment]
The loadouts have different ghosts.

**Comment by delphiactual** [comment]
lol, ok then im blind.. sorry for the hassle

**Comment by SunburnedGoose** [comment]
np.
