### ISSUE TITLE
Can the scrolling loadout menu be an option?

### ISSUE THREAD

**Issue by couldie** [DestinyItemManager/DIM#618]
I liked the way the design looked before, with all my loadouts being visable without having to scroll after already having to click the button to make them appear.

I don't want to just dismiss the work that has been done, some people will like that scroll feature, other won't. Can this become an option in the settings so it's up to the user how they want to display the loadouts?

**Comment by bhollis** [comment]
I can make this a bit more f we Bible so everyone is happy without an
option. Just give me a bit of time.

**Comment by bhollis** [comment]
Thanks gboard. I meant "flexible", not "f we Bible".

**Comment by bhollis** [comment]
Fixed in #635.
