### ISSUE TITLE
Mod energy cost covered by green check-mark in collection/mods

### ISSUE THREAD

**Issue by quetschke** [DestinyItemManager/DIM#6182]
**What version of DIM are you using?**
Version 6.39.1 (release), built on 11/16/2020, 1:58:15 PM

**What Browser and OS are you using?**
This is reproducible on PC and Android. 

**Describe the bug and how to make it happen**
The little green check-mark covers the energy cost when the mod is in the inventory. See screenshot from Chrome on Windows 10 below.

![image](https://user-images.githubusercontent.com/5354403/99314403-ae1df800-2826-11eb-80f9-8b169e6d66d8.png)

**Comment by johyphenel** [comment]
+1, also, clicking on the mod shows a different mod picture that doesn't have element affinity or cost.

**Comment by bhollis** [comment]
The picture we show in the popup is the perk icon, not the mod icon. A mod grants a perk, and the perk icon appears to be a picture of the mod, without overlays.

**Comment by quetschke** [comment]
Thank you! Just checked in beta, Works great - also on Firefox now.
