### ISSUE TITLE
Xur location not shown in German

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [DestinyItemManager/DIM#6183]
**What version of DIM are you using?**
6.39.1 orange

**What Browser and OS are you using?**
Chrome Android 

**Describe the bug and how to make it happen**
The vendor page does not show xurs location if lang is set to German

**Comment by bhollis** [comment]
Yeah, it's a bummer, right? For this expansion, Bungie forgot to populate place/destination info in the manifest for a lot of non-English languages.

**Comment by TheBl4ckSh33p** [comment]
Hmm is it possible to show the English info if no localized value is provided?

**Comment by bhollis** [comment]
Should display correctly now

**Comment by TheBl4ckSh33p** [comment]
Thank you very much!
