### ISSUE TITLE
Pull from Postmaster pulls selected item and item from vault

### ISSUE THREAD

**Issue by DBR64** [DestinyItemManager/DIM#6184]
**What version of DIM are you using?**
Find the version in "About DIM" from the menu (the button with three bars on the upper left of the screen). Is the DIM icon orange, or blue?

Orange - Version 6.39.1 (release), built on 11/16/2020, 2:58:15 PM

**What Browser and OS are you using?**
It helps to know what type of browser and what version you're using. Have you installed DIM as an app through Chrome or Safari?

Chrome - Version 86.0.4240.198 (Official Build) (64-bit)

**Describe the bug and how to make it happen**
Tell us what's wrong. A great format for bug reports is "I did X, and I expected Y, but instead Z happened." If it helps illustrate the issue, please add screenshots to help explain your problem.

On the inventory screen in Postmaster I select an item to open the item "card".  I click the icon under "Pull from Postmaster" for my character and the item is transferred to my character along with another item from my vault.  

**Include devtools console logs**
If you can, open the devtools console (ctrl+shift+J on PC and cmd+option+J on Mac) and paste what you see in the window that pops up:

```
Paste console logs here
```

**Comment by bhollis** [comment]
What likely happened is that you didn't have any space on your character to pull that item from postmaster. So DIM had to move an item *into* the vault to make room. But if you vault was also full, DIM had to move something else back *out* of the vault as well to make room, which is why you see an item come back to your character.
