### ISSUE TITLE
TypeError: Cannot read property 'getTime' of undefined

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#6186]
https://sentry.io/organizations/destiny-item-manager/issues/2029442597/?referrer=github_plugin

```
TypeError: Cannot read property 'getTime' of undefined
  at action (./src/app/vendors/actions.ts:32:84)
  at h (./src/app/active-mode/ActiveMode.tsx:63:5)
...
(11 additional frame(s) were not displayed)
```

**Comment by kyleshay** [comment]
looks like it was auto resolved in sentry, i'm working through some of the other ones, will keep an eye out for others.
