### ISSUE TITLE
Exported file has non numbered values in Season column

### ISSUE THREAD

**Issue by michaelnemtsev** [DestinyItemManager/DIM#6188]
**What version of DIM are you using?**
beta.destinyitemmanager.com

**What Browser and OS are you using?**
Chrome

**Describe the bug and how to make it happen**
I've exported Armor as CSV via settings, and then when I opened I found that Season column that usually contains a number as a season has a text

For example, this item

Mighty Rivalry Mark | 9.68E+08 | "6917529180547212325" | Legendary | Titan Mark | Titan | 1212 | 1310 | Arc Energy Capacity | 9 | Titan(1123) | TRUE | FALSE | TRUE | 0 | NaN | Guardian Games | 0 | 0 | 0 | 10 | 0 | 0 | 10 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | legacy |   | Discipline Mod* | Outreach* | Spirit of Competition* | New Age Black Armory* | Upgrade Armor* | Dragonfly Regalia Mark* | Lucent Blade*
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

it has "Nan" for Season column

**Comment by delphiactual** [comment]
Closed by #6213
