### ISSUE TITLE
Xur status is only updated by hard refresh of DIM

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#619]
The refresh destiny data button does not check the status of whether Xur is available or not.

![xur](https://cloud.githubusercontent.com/assets/4798491/16199700/d76def8a-36c7-11e6-9bb9-f94f739b558e.gif)

**Comment by bhollis** [comment]
What makes you think that? If you open the network console, you'll see that we request Xur info on every load.

**Comment by bhollis** [comment]
Note that Bungie.net does specify caching headers for the Xur data, and a hard refresh bypasses the cache. So perhaps you saw that?

**Comment by delphiactual** [comment]
Well if bungie is caching the data and on Sunday afternoon I;m still seeing Xur, maybe we should add a check if it is inside Xurs' timeframe...

because he is still showing for me right now, I dont normally close my DIM instances...

![screenshot 2016-06-20 19 57 03](https://cloud.githubusercontent.com/assets/4798491/16215663/551b6724-3721-11e6-98c5-78b7d06c32e5.png)

**Comment by bhollis** [comment]
OK, I found the issue. Fixed.
