### ISSUE TITLE
Trinity Ghoul catalyst not displayed

### ISSUE THREAD

**Issue by blademan007** [DestinyItemManager/DIM#6190]
DIM v 6.39.1. DIM orange icon.

Chrome 86.0.4240.198 on MacOS

Trinity Ghoul catalyst is not displayed in records > exotic catalyst.
I went to Records > Exotic Catalyst and didn't see Trinity Ghoul. I tried checking/unchecking "hide completed triumphs" and "reveal redacted triumphs" but still doesn't work.

**Comment by bhollis** [comment]
Does it show up in the Destiny 2 Companion App?

**Comment by blademan007** [comment]
Nope. I'll open a ticket with Bungie.
