### ISSUE TITLE
Old Last Wish armor not matching modslot:legacy

### ISSUE THREAD

**Issue by DHager** [DestinyItemManager/DIM#6191]
**Version**: 6.39.1.9108 (beta), built on 11/17/2020, 11:48:25 PM

**Issue:** As a player, I expect armor that shows a "Legacy Mod Slot" to match the filter `modslot:legacy`, but Last Wish raid armor is not doing so.

**Detail:** 

I would expect the following filter to have zero results, since pre-Beyond-Light armor should have the "Legacy" mod-slot, newer armor should have the "Combat" mod slot, and no other types have been introduced. (Or if there are, they are in raids I haven't done since launch.) The `-festival` is only needed to exclude FoTL masks, which are weird special cases.

```
is:armor not:Exotic not:rare -modslot:combatstyle -modslot:legacy -festival
```

Instead, I see "Mask of the Great Hunt" or "Robes of the Great Hunt" etc. These match `modslot:reveriedawn` but only display as "Legacy" in-game.

**Comment by DHager** [comment]
Pinging @nev-r as probably the most knowledgeable. I don't want to discount the possibility that this is a case where the in-game text is just misleading.

**Comment by nev-r** [comment]
intentional in the really technical sense that, the "legacy slots" in reverie/last wish, are different from the other legacy slots, because they seem to support a slightly different set of mods

but i am open to pretending they're normal legacy, it was kind of the plan from the start. rivens curse/transcendent blessing are annoying exceptions to every rule

**Comment by DHager** [comment]
At least for my own use-cases, they seem pretty irrelevant:

* The gear that comes with Riven's Curse in it is already sunset
* Compared to Transcendent Blessing, there's almost always something better/easier/non-consumeable to put into raid-gear

I suppose a workaround would be to implement `holdsmod:legacy`, but at that point it's not really about mod-types as much as about some kind of set-membership abstraction.

**Comment by bhollis** [comment]
Sounds like there's nothing to do?
