### ISSUE TITLE
The loadout optimizer can't find any loadout while any season mod and exotic armor were selected at the same time

### ISSUE THREAD

**Issue by OscarSheng** [DestinyItemManager/DIM#6192]
**What version of DIM are you using?**
Version 6.39.1.9108 (beta), built on 2020/11/18

**What Browser and OS are you using?**
Edge(chrome base)

**Describe the bug and how to make it happen**
The loadout optimizer can't find any loadout while any season mod and exotic armor were selected at the same time.

**Comment by bhollis** [comment]
Can you send a screenshot of your Loadout Optimizer configured in that way?

**Comment by OscarSheng** [comment]
> Can you send a screenshot of your Loadout Optimizer configured in that way?

**Comment by OscarSheng** [comment]
> Can you send a screenshot of your Loadout Optimizer configured in that way?

![2020-11-20](https://user-images.githubusercontent.com/36452729/99856408-eab75f80-2b56-11eb-9aaa-555709c62d7d.png)

**Comment by OscarSheng** [comment]
> Can you send a screenshot of your Loadout Optimizer configured in that way?

Though the exotic armor were display with the forth mod slot, but the optimizer seems don't know they can equip the combat style mods.(btw I suggest change those "seasonal mod" to "combat style mod" since Bungie already changed their name)
Also I think this issue may be caused by the change of limitation for the forth slot by Bungie. Because most of my armor are from last season, so maybe the optimizer didn't realize they are already compatible with the mods from season of dawn.

**Comment by JairusKhan** [comment]
Having a problem that may be related, can't find any loadout while two season mods are equipped at the same time. 

![image](https://user-images.githubusercontent.com/957108/99865009-c79ba880-2b74-11eb-8a05-1987e19860e9.png)

**Comment by ryan-rushton** [comment]
Yeah there a a bunch of issues that the new mod and socket system has introduced. I think I have covered most of them in the above PR. Once it is reviewed and merged these should be fixed
