### ISSUE TITLE
Unreduced fractions in power level

### ISSUE THREAD

**Issue by RickKukiela** [DestinyItemManager/DIM#6193]
**What version of DIM are you using?**
Find the version in "About DIM" from the menu (the button with three bars on the upper left of the screen). Is the DIM icon orange, or blue?

Beta

**What Browser and OS are you using?**
It helps to know what type of browser and what version you're using. Have you installed DIM as an app through Chrome or Safari?

Chrome Latest Release

**Describe the bug and how to make it happen**
Tell us what's wrong. A great format for bug reports is "I did X, and I expected Y, but instead Z happened." If it helps illustrate the issue, please add screenshots to help explain your problem.

Look at your power level

**Include devtools console logs**
If you can, open the devtools console (ctrl+shift+J on PC and cmd+option+J on Mac) and paste what you see in the window that pops up:

![image](https://user-images.githubusercontent.com/3813238/99741186-23dbcb00-2a96-11eb-9d5d-1410de174025.png)

This hurts my brain so bad. I have never seen unreduced fractions in the wild before haha it sticks out like a sore thumb :P Anyway, can we reduce these fractions? 2/8 should be 1/4 and 4/8 should be 1/2 There might be others as well, just the two I'm seeing right now.

**Comment by wein3967** [comment]
Personally, I don't see this as an issue. It makes sense to me to see 8 in the denominator as there are 8 items contributing to your power level. When I see 2/8, that easily tells me that I need to raise the total power count of one or more items by 6 points. Seeing 1/4 does not make it easy, at least for me, to do the same calculation at a glance.

**Comment by bhollis** [comment]
Yeah, this is in fact by design.

**Comment by RickKukiela** [comment]
@wein3967 If thats how the math actually works out in this case then I guess I can see it being intended or better this way. However I'm 100% sure the power calculation can be interpreted how you did. I'm not sure 2/8 is as simple of a deduction as "I need 6 points".

**Comment by RickKukiela** [comment]
After looking again you might actually be right.

**Comment by nev-r** [comment]
vault space `400/500` is an unreduced fraction too. the 8 denominator is the number of item slots you have

**Comment by bhollis** [comment]
It is!

**Comment by RickKukiela** [comment]
@nev-r maybe it is, but in the vault space indicator its not expressed as a numeric fraction in the way a portion of a point of the power level is. You need to know you are using 400 of 500 slots because you have 500 slots total. I mean I guess what you guys are doing with the power points is kind of the same, whereas you are 4 of 8 slots worth of a single power level until the next bump, but I guess the fact that proceeds a full whole number is what makes it look off to me. Either way I understand the intention now and it does make sense. I'm closing the issue. I just though it stuck out really weird to me since it directly followed a whole number, I assumed it was supposed to just indicate a literal fraction of a point, not serve as a "slot out of slots" indicator.
