### ISSUE TITLE
Beta Inventory mode improvement

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#6194]
There's one main reason (at least during power levelling) that I don't use the new beta inventory mode.

There is no way to get this popup.

![image](https://user-images.githubusercontent.com/25425159/99776491-d5dfc980-2b60-11eb-9907-af86ce331b31.png)

This would be good in the left menu space.

**Comment by kyleshay** [comment]
will be resolved in #6216 (active mode is going to use the same character tiles that we have in normal mode)
