### ISSUE TITLE
Link the weapon detail page to light.gg

### ISSUE THREAD

**Issue by OscarSheng** [DestinyItemManager/DIM#6196]
**Proposed change**
Change the perk pool detail page to light.gg instead of current destinytracker.

**How does this fit into your workflow?**
Light.gg weapon detail page have more info than destinytracker. It will be much more convenient to link the weapon to light.gg page from my perspective.

**Comment by bhollis** [comment]
Our plan is to provide that information ourselves.

**Comment by michabbb** [comment]
@bhollis your tool is amazing, but as most people on this planet are using light.gg it would be fair to link to light.gg *UNTIL* the days comes, where you really provide all that infos. the tracker website is useless compared to light.gg ......

**Comment by bhollis** [comment]
What info do you need from light.gg? The info about possible perks and their stat effects is the same on both.

**Comment by michabbb** [comment]
really ? 😃 there is a reason most people use light.gg. 
compare the reviews:

19 - https://www.light.gg/db/items/3281285075/posterity/
0 - https://destinytracker.com/destiny-2/db/items/3281285075-posterity#

light.gg offers different languages, very important for people not playing in English!
light.gg tells you, where to get the item.
light.gg tells you, which perks/rolls are good based on "most frequently equipped perks"
light.gg tells you, from which season the item is and its cap (yeah i know, DIM shows that too, but we are talking about light.gg vs tracker)....
light.gg shows you the database history

so everything marked as "red", i am missing: https://imgur.com/gallery/9ZE7jC3

to be honest, it´s sad that you still don´t accept the better choice for most destiny players.
every youtuber uses light.gg - not tracker - there´s a reason. people like what they see, the community, the extended infos there, the usability. everything is better than tracker.

in case you don´t earn any money with tracker, please give people the choice to use what they want. most people use light.gg anyway, doesn´t matter what DIM uses. 
so you can stay stubborn and trip people up or adapt, make dim better and save people a few clicks ;-)

as said... most use light.gg anyway, so for me there is no rational explanation for staying with tacker, except you make money with it or it´s your very very personal choice or irrational aversion against light.gg. 

if you would add the option in the config, people would be able to put in any URL they like, so total freedom for all. you can stay with tracker, and the rest of the world can use light.gg, everybody would be happy, even you ;-)

btw... I already had this discussion with you in the past, and one of your arguments was "i don´t know who runs the website" - but that a bad excuse the last time and still today for me, sorry ;) u do updates in DIM all the time, so when the day really comes, where light.gg is dead, you change one line of code and everything is fine again, so.... that is and never has been a real rational problem.

as said... u can do, what's best for most destiny players, and help them to save a few clicks, or you can stay with your tracker, but people will use light.gg anyway..... 

😏

**Comment by bhollis** [comment]
That response is way overboard, dude. I just asked what specific features were different.

**Comment by michabbb** [comment]
I guess I told you, even with Screenshot, you're welcome 😉

**Comment by delphiactual** [comment]
Responses like this are why features are often not built in free software

**Comment by michabbb** [comment]
"because it's free, you can't criticize it" - maybe you live in that world, the rest doesn´t - thank god. btw.. i´m donating to this project every month and this is not a "feature", it's a personal thing. light.gg is the best for a very long time now. hollis doesn´t like it, it´s personal, okay... we have to live that... it´s sad... but... the owner has the last word....

for everybody else, like @OscarSheng, here´s your solution:

install: https://chrome.google.com/webstore/detail/url-rewriter/gpbblpbcnjdnnjdcdclojoonfmpoionh

if URL matches: `https:\/\/(destinytracker.com\/destiny-2\/db\/)items/(\d+)?.*`
replace text in group number: 1
with: `https://www.light.gg/db/de/items/`

don´t know why, i have 2 rules, choose that one that fits best to you:

if URL matches: `(destinytracker.com/destiny-2/db/)items/(\d+)?.*`
replace text in group number: 1
with: `https://www.light.gg/db/de/items/`

and replace `/de/` with your preferred language.

**Comment by OscarSheng** [comment]
> https://www.light.gg/db/de/items/

The second one works for me, thank you so muck.

**Comment by OscarSheng** [comment]
> "because it's free, you can't criticize it" - maybe you live in that world, the rest doesn´t - thank god. btw.. i´m donating to this project every month and this is not a "feature", it's a personal thing. light.gg is the best for a very long time now. hollis doesn´t like it, it´s personal, okay... we have to live that... it´s sad... but... the owner has the last word....
> 
> for everybody else, like @OscarSheng, here´s your solution:
> 
> install: https://chrome.google.com/webstore/detail/url-rewriter/gpbblpbcnjdnnjdcdclojoonfmpoionh
> 
> if URL matches: `https:\/\/(destinytracker.com\/destiny-2\/db\/)items/(\d+)?.*`
> replace text in group number: 1
> with: `https://www.light.gg/db/de/items/`
> 
> don´t know why, i have 2 rules, choose that one that fits best to you:
> 
> if URL matches: `(destinytracker.com/destiny-2/db/)items/(\d+)?.*`
> replace text in group number: 1
> with: `https://www.light.gg/db/de/items/`
> 
> and replace `/de/` with your preferred language.

The second rule works for me. Thank you so much.

**Comment by OscarSheng** [comment]
> "because it's free, you can't criticize it" - maybe you live in that world, the rest doesn´t - thank god. btw.. i´m donating to this project every month and this is not a "feature", it's a personal thing. light.gg is the best for a very long time now. hollis doesn´t like it, it´s personal, okay... we have to live that... it´s sad... but... the owner has the last word....
> 
> for everybody else, like @OscarSheng, here´s your solution:
> 
> install: https://chrome.google.com/webstore/detail/url-rewriter/gpbblpbcnjdnnjdcdclojoonfmpoionh
> 
> if URL matches: `https:\/\/(destinytracker.com\/destiny-2\/db\/)items/(\d+)?.*`
> replace text in group number: 1
> with: `https://www.light.gg/db/de/items/`
> 
> don´t know why, i have 2 rules, choose that one that fits best to you:
> 
> if URL matches: `(destinytracker.com/destiny-2/db/)items/(\d+)?.*`
> replace text in group number: 1
> with: `https://www.light.gg/db/de/items/`
> 
> and replace `/de/` with your preferred language.

I need to refresh the page to get light.gg. Is it expected? I'm using chrome based edge.

**Comment by michabbb** [comment]
@OscarSheng yeah, I noticed that too, maybe it´s another hack to make life for us more difficult 😂 kidding....
anyway... pressing F5 is better than typing it all.... ;)
