### ISSUE TITLE
Bounty Helper

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#6208]
![image](https://user-images.githubusercontent.com/4798491/100036951-6b2bc980-2dbe-11eb-92d5-2f29a93c83cd.png)

FF Grenade Launcher not Heavy Grenade Launcher
and Special Ammo

should be added as pills

**Comment by bhollis** [comment]
I'm generating these off item categories and as far as I know they're all just "grenade launchers" :-(

**Comment by delphiactual** [comment]
I thought you were using d2ai and https://github.com/DestinyItemManager/d2-additional-info/blob/master/data/bounties/bounty-config.ts

**Comment by bhollis** [comment]
Yeah sorry what I meant was I'm assigning item categories to them, and there's no distinct item category for breech loading grenade launchers

**Comment by bhollis** [comment]
Duplicating into https://github.com/DestinyItemManager/d2-additional-info/issues/208
