### ISSUE TITLE
is:powerfulreward filter doesn't return all powerful rewards

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#6215]
Current beta on Chrome on Windows 10.

The only Milestones that are returned are Gambit/Nightfall/Crucible/Raid.

Looking through the others, if it's displayed as "+0 Powerful Gear (Tier X)" it does not get returned.

It should also return all pinnacle rewards (which there is no filter to return).

**Comment by bhollis** [comment]
Cool, I can fix the list of known powerful reward hashes. They have to be maintained by hand. In the meantime, know that basically all repeating milestones reward a pinnacle/powerful.
