### ISSUE TITLE
Searching for Weapon Perk "Tresh" shows no results

### ISSUE THREAD

**Issue by kokswijk** [DestinyItemManager/DIM#6219]
Using the search bar (top of the screen) I can search for weapons with specific weapon perks by typing in the name of the perk.

However when I search for the perk "Tresh" it does not show any results, even though I have two weapons with said perk.

Searching for **other perks** on those two weapons **does** highlight these guns in the results.

**Comment by 48klocs** [comment]
And if you try searching for `Thresh` instead?

**Comment by kokswijk** [comment]
> And if you try searching for `Thresh` instead?

Ah, thanks!

The missing **h** was indeed the problem;

Not a native English speaker, and I copy pasted the perk's name from an online guide.

_Problem existed between chair and keyboard._
