### ISSUE TITLE
Postmaster - font size in prime engrams

### ISSUE THREAD

**Issue by 48klocs** [DestinyItemManager/DIM#6220]
![prime engram power font size](https://user-images.githubusercontent.com/606888/100290170-af4ad580-2f48-11eb-9057-459177a563d7.png)

We're calculating the power level of prime engrams properly, which is cool! But the font used when it's in the postmaster is... vanishingly small.

**Comment by bhollis** [comment]
Yep I promised @delphiactual I'd work on the CSS
