### ISSUE TITLE
Legendary engrams in postmaster - level calculation issue

### ISSUE THREAD

**Issue by 48klocs** [DestinyItemManager/DIM#6221]
![legendary engram power display](https://user-images.githubusercontent.com/606888/100290306-0781d780-2f49-11eb-9a98-bd2831626f67.png)

As seen in this screenshot, the power level of this legendary engram sitting in the postmaster is `12010`. I think it's meant to be `1210`? I can grab more details if it'll help.

**Comment by bhollis** [comment]
maybe you're just really lucky

**Comment by delphiactual** [comment]
@48klocs please post screenshot from in-game

**Comment by 48klocs** [comment]
I'm lucky in that delphi beat me to the punch on fixing it!

Less so when it comes to a monstrously overpowered drop sitting in my postmaster.
