### ISSUE TITLE
Valor rank points negative overflow

### ISSUE THREAD

**Issue by Kurochi51** [DestinyItemManager/DIM#6227]
**What version of DIM are you using?**
Version 6.40.0.9168 beta

**What Browser and OS are you using?**
Chrome / Windows 10

**Describe the bug and how to make it happen**
If you have Light Reforged (the pvp intro quest for New Light 2.0), and already reset your valor once, the valor rank points field seems to overflow like so:
![](https://i.imgur.com/lhIXkMO.png)

**Comment by bhollis** [comment]
What does it show on the official companion app? Is this a DIM-specific bug or a Bungie bug?

**Comment by Kurochi51** [comment]
hm, it shows the same -999884/50 value

**Comment by delphiactual** [comment]
clamp between 0 and MAX_SAFE_INT

**Comment by bhollis** [comment]
Sure - that'd make it display better, but you'd still never be able to get above 0 :-D

**Comment by Kurochi51** [comment]
Funnily enough I can't progress the objective either, so quest bugged altogether I guess lol
