### ISSUE TITLE
Option to switch Vault location from right side to left side does not exist.

### ISSUE THREAD

**Issue by HaloKota** [DestinyItemManager/DIM#6254]
**What version of DIM are you using?**
6.40.0

**What Browser and OS are you using?**
Chrome tab, Windows 10

**Describe the bug and how to make it happen**
Under Inventory Display in settings there is no option to switch the Vault from location from the right side to the left side. I have reported this as a bug and not a requested feature because under the DIM user guide it states: 
Inventory Display
Sort character columns
Sort items by how recently they were used. Option to move the vault to the left or right side. Option to have an entirely custom static sort order. default: most recent character.
I do not know if this option existed under settings in the past and was lost at some point, or if it never made it in and was mistakenly added to the DIM user guide. I have also checked on the app version which I have on a Samsung device and the option does not exist there either, also version 6.40.0

**Comment by bhollis** [comment]
Thanks - I have fixed the user guide. This was never a feature, and we're not likely to add it.
