### ISSUE TITLE
Selecting perks in compare doesn't work on mobile

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#6257]
The perk PressTip interferes with selecting the perk by tapping it. You can do it sometimes, but it's very hard to do. We should either disable on mobile or come up with a different interface.

**Comment by kyleshay** [comment]
Maybe we could get the alternative perk display on mobile and do something along the lines of:
- Tapping the row/text expands details below ("slightly increases handling, +5 handling)
- Tapping icon tags selects the new perk

**Comment by bhollis** [comment]
That's the idea :-)

**Comment by bhollis** [comment]
We're trying a new design on beta that doesn't rely on hover for details. Check it out and let us know how it works.

**Comment by panza1370** [comment]
Still pretty difficult/inconsistent on beta. Easier to trigger than on main, but totally unclear what makes the nth tap successful (by which time I'm already on to the n+1th tap, which if I'm unlucky will trigger correctly :P).

**Comment by bhollis** [comment]
Compare doesn't use the new design.
