### ISSUE TITLE
There should be a way to remove/hide the Gamer2Give overlay

### ISSUE THREAD

**Issue by crshumate** [DestinyItemManager/DIM#6266]
**What version of DIM are you using?**
6.41.1

**What Browser and OS are you using?**
Win 10 version 2004 
Chrome 87.0.4280.66

**Describe the bug and how to make it happen**

There should be a way to dismiss or hide the Gamer2Give overlay. The overlay passive aggressively impedes, obscures UI and creates a bad UX. 

If you want to make it appear everytime we reload/fresh load the page that could be a good compromise.  

As it stands now, only those with some experience can easily go into dev tools and delete the element from the DOM. 

**How to fix**
Add an `x` to the upper right corner that hides or dismisses the overlay indefinitely or for the browser session of the tab.

**Comment by crshumate** [comment]
@kyleshay is there a reason this is closed with no explanation? Emotional feelings aside, the points I made are cogent. This is a classic example of bad web dev from a UI/UX perspective.

**Comment by kyleshay** [comment]
The banner will be removed after the fundraiser concludes. You're welcome to set up a userscript if you'd like to remove it locally from your instance.

**Comment by crshumate** [comment]
@kyleshay 

- I already assumed the banner would be removed when the fundraiser concludes. 
- I also assume even IF I donate I'd still see the banner. This is a bad UX all round. 
- **Please reconsider this practice in the future**. It is classic passive aggressive "see this ad" bad UX design I'd expect from a company that is more concerned with profits than providing a good user experience.

**I understand it's for a good cause**

BUT you can do things for a good cause w/o creating obstructing, un-dismissable elements that are perfect examples of what NOT to do in UI/UX. If anything it will just put a sour taste in people's mouths as to how "in your face" this is. 

Hence my compromise where you show it on **every** page load, but allow it to be dismissable. I know I _can_ setup a user script, etc for this, but 90%+ of users won't know how to do this and frankly shouldn't have to.

I'd be happy to create a PR for this, but something tells me that's not the issue here....

**Comment by kyleshay** [comment]
I appreciate your concern, but we made the intentional UX consideration for the banners we put in the app. 

Please appreciate that DIM is ad-free, profit-free, and straight up free outside of these very short events. I'm sorry, but it's not up for further discussion.
