### ISSUE TITLE
ItemSocketsWeapons in item-popup is too small and masterwork is hidden often

### ISSUE THREAD

**Issue by Riddim77** [DestinyItemManager/DIM#6301]
Issue:
ItemSocketsWeapons shows too much stuff to be restricted to one row (frame type, shader, ornament and masterwork). For me personally masterwork is the most important to see whereas cosmetical information about the ornament/shader is not important at all here. Unfortunately masterwork information is at last position in the row and thus is hidden or barely visible for most weapons.

This might be a i18n issue - I am using German where the frame type name might be longer than e.g. in English?

Proposed solutions:
Either
- make the row responsive to use two rows if there is not enough space in one row
- or increase the item-popup width (e.g. according to its content)
- or at least position the masterwork information at first (after the frame type information).

**Comment by bhollis** [comment]
What browser are you using? Mobile or desktop? Can you send a screenshot? The archetype is supposed to hyphenate. Putting the masterwork last actually should make it most prominent, since it's closes to the edge.

**Comment by Riddim77** [comment]
I am on FF 83 Desktop. Oh and I am using the BETA version of DIM.

Two friends of mine who also use DIM have the same issue.

Screenshot is here: [https://github.com/Riddim77/tmp/blob/main/Screenshot_2020-12-09_DIM.png](https://github.com/Riddim77/tmp/blob/main/Screenshot_2020-12-09_DIM.png)

**Comment by bhollis** [comment]
Looks like you also have the item size increased from default?

**Comment by kyleshay** [comment]
we made the popup a bit more narrow when we removed the move actions. I'd be fine with bumping it back up a little. may not solve every case though..

maybe the popup width should be proportional to --item-size?

**Comment by Riddim77** [comment]
Yes, item size is at max 66px since I have a high monitor resolution (3840x1600) and the default size is way too small.

I like the current solution:
![grafik](https://user-images.githubusercontent.com/10244781/101649670-737d3900-3a3b-11eb-82a2-4eb5b2d99263.png)

Thanks for the quick reaction and the overall great work on DIM!

From my point of view, this issue can be closed.

**Comment by bhollis** [comment]
Ha, we didn't change anything... you must have updated?

**Comment by Riddim77** [comment]
Oh my bad - FF must have updated without me noticing/restarting. Sorry for the false alarm.

Btw - I don't like the new vertical order of the perks in the popup. Before it was exactly as in the game and it was much easier to read. Now it is not only vertical but also in a different order as in the game. Pretty confusing.

Thanks again for the great work!
