### ISSUE TITLE
Powerful friends mod bonus not being highlighted as modded

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#6307]
My partner was showing me an 81-stat titan chest armor, and it was blowing my mind for a bit until I realized she had Powerful Friends slotted. We didn't show the +20 mobility bonus there as a mod bonus, I assume because we're no longer showing "conditional stats". We should probably try to figure out some (ugh) heuristics for this.

**Comment by delphiactual** [comment]
Linking https://github.com/DestinyItemManager/DIM/pull/6199

**Comment by bhollis** [comment]
I don't know how we'd do this without hardcoding all of the rules

**Comment by delphiactual** [comment]
we need a DIMscipting language that states what the conditions are... almost like bounty guide

e.g. `Powerful Friends` active: +arcModThisArmor || +cwlArcModNotThisArmor

**Comment by bhollis** [comment]
I wonder if we could parse out the rules from the English descriptions?

**Comment by bhollis** [comment]
I'll add that this is even more complicated when you consider stacking rules - if a mod says "this doesn't stack" we have to look not only at the mods on that piece but across all items. This'd make the Loadout Optimizer super complicated I think @ryan-rushton.

**Comment by ryan-rushton** [comment]
Yeah it could potentially. It would probably be used in a few places though so I would want to generate something when the stats are generated for items and interpolation is done. It could make the optimiser a bit easier if we had something well structured.

Also it's weird that powerful friends is not being picked up as modded. Charged harvester for example we see -10 from 3 stats no matter the class. It should be condition based on class. For that reason I would assume powerful friends should be showing the +20 as a mod. It might be a bug.

**Comment by bhollis** [comment]
The +20 is conditional on another arc mod being slotted, and we no loner include conditional stats.

**Comment by ryan-rushton** [comment]
Sounds reasonable. I must have missed the change where we ignore conditional mod stats. Makes sense though as they are a little painful.
