### ISSUE TITLE
Empire Hunt Challenges have no icon, but the unlocks from Variks do

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#6309]
![image](https://user-images.githubusercontent.com/4798491/101606161-48a1cf00-39c0-11eb-9eb1-06c5a7cbfd02.png)

![image](https://user-images.githubusercontent.com/4798491/101606253-65d69d80-39c0-11eb-9a97-c2ae6e93272d.png)

non-pinnacle challenge hash = 291895718

**Comment by nev-r** [comment]
these technically represent the quest/consumable that leads to the milestone being available, and they stand out strangely compared to any other milestone icon, so alternatively, a more repeatable process for milestones could be to dig through their associated activities, then those activities' activitymodes/activitytypes, to find some non-missing icon to display.

in the case of empire hunts, this eventually leads to
![image](https://user-images.githubusercontent.com/68782081/101691474-969bee80-3a23-11eb-91f8-4e6631ea1d51.png)
which, while sort of generic, does sort of embody the fact that you're replaying Story Missions for the milestone

**Comment by bhollis** [comment]
This got fixed in the manifest
