### ISSUE TITLE
Feature Request: disable double click actions

### ISSUE THREAD

**Issue by jacobcollier70** [DestinyItemManager/DIM#6312]
Hi, I saw an old issue for this back in January, but it was closed.

I love DIM, and use it repeatedly to periodically sort through my gear and delete all but the best weapon and armor rolls.

19/20 times that I perform a double click action, I didn't intend to. It's nearly always a case of clicking to view a tooltip, but the tooltip didn't show up, so I click again and it transfers the weapons instead.

> EDIT: upon returning to DIM, I've discovered that I actually am clicking between items. As follows:
> 1) I click on an item to open the tooltip, tooltip opens
> 2) I click on another item to open its tooltip. this does not open the tooltip, but rather closes the first one. 
> 3) I click on the second item again to open tooltip. This transfers the item, briefly opening but then immediately closing it's tooltip
> 
> Functionality to click between tooltips, or at least not treat the 'clicking-away-from-first-tooltip-click' as the first half of a double-click, would be great. This is in essence what is happening, and what I want to avoid :)

I would love an option to disable or reassign this functionality. I don't disagree that a shortcut to transfer gear to my current character is nice, but the ability to bind it to a keyboard + mouse press would be much better for me than a double click option that triggers when I don't want it to.

Thanks again for all of your work!

-J

**Comment by kyleshay** [comment]
hey! thanks for the report!

 there was recently a bug with dismissing the tooltips related to the number of clicks required that should be resolved now. hoping it decreases the amount of false positives you should be seeing. 

we do normally tend to shy away from adding options.. hoping that the bug resolution fixes most cases

**Comment by jacobcollier70** [comment]
Wow! that must have been just now: I was having issues as I wrote this, but just tried again and it didn't happen. dunno if it was me or if my dim just updated, but thanks!

**Comment by kyleshay** [comment]
we'll keep an eye on it! when its tured right it can be nice. thanks for the follow up
