### ISSUE TITLE
wishlist:>=, show me items in my wishlist with more than X wishlist perks.

### ISSUE THREAD

**Issue by jayproulx** [DestinyItemManager/DIM#6313]
**Proposed change**
Looking for perfect rolls, I'm not as interested in the wishlist items that have 2 desired perks, I want the ones that have 4.

**How does this fit into your workflow?**
Either looking for new loadouts with wishlist items, or getting new drops, I want to know if they're really good, or really really good.

**Comment by delphiactual** [comment]
they only show up in `is:wishlist` with a thumbs up if they exactly match the roll in the wishlist file, partial matches are not included.
