### ISSUE TITLE
[Improve] Details Windows, Z-Index needs adjusting.

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#632]
As shown here

![screenshot 2016-06-23 10 28 25](https://cloud.githubusercontent.com/assets/4798491/16311352/7a5e2248-392d-11e6-9462-fed692c4d25b.png)

**Comment by Mulchman** [comment]
https://github.com/DestinyItemManager/DIM/issues/508

**Comment by delphiactual** [comment]
Thanks didn't see that when I searched
