### ISSUE TITLE
Progress View - Mobile (i18n)

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#6327]
Languages other than English cause weird behavior on the progress page... see attached.
I tested in all locales 
es-es, es-mx, fr, it, pl, ja: behave as in these pictures
ko, pt-br, ru, zh-chs, zh-cht: no problems noted

| 1 | 2 |
|---|---|
|![Screenshot_20201213_095914_com android chrome](https://user-images.githubusercontent.com/4798491/102020798-a7f13d80-3d38-11eb-9432-2f2d7db506fc.jpg)|![Screenshot_20201213_100646_com android chrome](https://user-images.githubusercontent.com/4798491/102020800-a9bb0100-3d38-11eb-8411-26cc8e9fa314.jpg)|

**Comment by bhollis** [comment]
Even on the inventory screen, the character tile is stretched out horizontally by the longer text. @kyleshay I think your tile changes caused this.

**Comment by kyleshay** [comment]
interesting, I'll take a look
