### ISSUE TITLE
Equipped items show equip option on move popup

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#633]
notice there are equip and move options for all 3 characters even though the item is equipped. 

this pushes (overflow is hidden) the infuse button off of the movepopup though.

edit: it seems to only happen if the item may be equipped by any character (ex. weapons, ghost shells, shader, ship, etc) but not things specific to classes (ex. hunter helmet will properly not show equip option for the same character it's already equipped on.)

<img width="345" alt="screen shot 2016-06-25 at 12 52 41 am" src="https://cloud.githubusercontent.com/assets/424158/16354774/2d687c8e-3a6f-11e6-99b8-604db0b85e69.png">

**Comment by bhollis** [comment]
I can't reproduce this on the `dev` branch - no matter what I click, it works.

**Comment by kyleshay** [comment]
seeing it on beta v3.7.4.195, can anyone else confirm? seeing it on all items that are:

- actively equipped
- weapon/ghost shell/shader/etc (not armor)

**Comment by bhollis** [comment]
Whoops, now I see it. That's my bad. Fixed.
