### ISSUE TITLE
Dim mobile app bug

### ISSUE THREAD

**Issue by czyk-it** [DestinyItemManager/DIM#6333]
**What version of DIM are you using?**
Cant tell 
**What Browser and OS are you using?**
Chrome/newest android

**Describe the bug and how to make it happen**
"Dim hasn't loaded somw thing may be wrong with your browser force close" error. The app just won't load but if I use Chrome dim loads. 

**Include devtools console logs**
If you can, open the devtools console (ctrl+shift+J on PC and cmd+option+J on Mac) and paste what you see in the window that pops up:

```
Paste console logs here
```

**Comment by delphiactual** [comment]
https://twitter.com/ThisIsDIM/status/1338317916979212291
