### ISSUE TITLE
Search Highest Power of every weapon type

### ISSUE THREAD

**Issue by JG0078** [DestinyItemManager/DIM#6335]
**Proposed change**
I'm wondering if there could be a pre-defined search that will highlight the best available of every weapon type.  I'd like to quickly identify these so I can tag them to keep for doing Weapon Bounties.  Then the inverse, just tag the leftovers as dismantle (If you'd like)
Maybe this could also highlight if there is a weapon type that you do not have in your inventory ?

If I do this manually with each weapon type, there are a lot of weapon types to search through
is:autorifle
is:handcannon
is:pulserifle
is:scoutrifle
is:fusionrifle
is:sniperrifle
is:shotgun
is:machinegun
is:rocketlauncher
is:sidearm
is:sword
is:grenadelauncher
is:tracerifle
is:linearfusionrifle
is:submachine
is:smg
is:bow

**How does this fit into your workflow?**
I'd like to quickly scan my inventory since these days we are collecting so much trash.  This way, I can easily find the best of every weapon type so that I always have at least one weapon type on hand.  I had to search for a while for a linear fusion rifle and machine gun.  I don't want to dismantle these so I can't complete certain weapon bounties.

**Comment by bhollis** [comment]
Check out the Organizer, and click the Power heading to sort.

**Comment by JG0078** [comment]
Interesting.  I'm sorry, I hadn't explored the organizer yet.  This will work
