### ISSUE TITLE
iPad zoom lock?

### ISSUE THREAD

**Issue by tcurtin** [DestinyItemManager/DIM#6338]
On my iPad (using safari), I fight a constant battle with zoom.  Rotate the screen, reload the page, slide an item wrong, etc, and I am no longer looking at the full page and have to pinch zoom to see everything again.

I love DIM, I don’t play Destiny without it open, but this zoom thing kills me.

Is there any way to lock the interface size so the full page is the full page and it just stays that way?  The interface is so good that I almost never actually want to zoom in on anything.

**Comment by bhollis** [comment]
We've actually instructed Safari to disable zoom, but they don't always obey it. Have you installed the app to your home screen?

**Comment by tcurtin** [comment]
For what its worth, I hadn’t ever tried doing that, and didn’t realize it would set up the window the way it does... I’ll try it this way for a while and see what happens?

**Comment by tcurtin** [comment]
The interface works *much* better and more consistently as an installed full-screen app.  I’ll use it that way from now on.  Thank you!  Closing issue.
