### ISSUE TITLE
Log in to multiple account

### ISSUE THREAD

**Issue by dchiab** [DestinyItemManager/DIM#6339]
**Proposed change**
Explain what you'd like to see as a new feature or enhancement to DIM.

Having the ability to login to multiple account.

**How does this fit into your workflow?**
Tell us how you'd use this. It's very helpful to understand how a proposed change would fit into the way you play.

**The story was:**

My friend and I used to played D2 together, however he got a baby recently, he had less time to play the game, I want to help him rising the powerlevel so he can keep up with the mainstream player.

**The current workflow:**

I use an account switcher for steam account, and using the beta DIM for his account.

**The prefered workflow:**

In the current branch DIM, I can switch to his account without log out of my account.

**Sorry for my bad English!!**

**Comment by bhollis** [comment]
Thanks for the idea! We've thought about this, but it's a pretty uncommon case, so our recommendation has been to use different browsers or separate Chrome profiles to use other accounts.

**Comment by delphiactual** [comment]
Or app and beta
