### ISSUE TITLE
Assign shortcuts to search strings, clear search shortcut

### ISSUE THREAD

**Issue by tallpants** [DestinyItemManager/DIM#6345]
**Proposed change**
-  Ability to assign shortcuts to search strings (could limit to `ctrl+[1-9]` for example to keep options open for future shortcuts)
- Shortcut to clear search string (`` ctrl+` `` maybe to stick with the ctrl + number row theme)

**How does this fit into your workflow?**
It would be nice to use shortcuts to run and clear common searches. Some example workflows with this feature could be:
- Assign `ctrl+1` to run the search `tag:favorite` to quickly find your go-to equipment and `` ctrl+` `` after to clear it.
- Assign `ctrl+2` to run the search `tag:junk` to quickly find junk to dismantle and `` ctrl+` `` after to clear it.
- Assign `ctrl+3` to run the search `is:rare` to quickly find blues to dismantle once you hit powerful
- Assign `ctrl+4` to run the search `is:dupelower` to quickly find low power dupes to dismantle

I can take a shot at implementing if you can give me some idea of how you think it should be implemented at a high level.

**Comment by bhollis** [comment]
Hit "?" to see our current shortcuts - for example, Shift+F is already "clear search".

I don't think we want to assign shortcuts to searches - that's a bit too complicated a UX for a too-niche use case.

**Comment by tallpants** [comment]
Shift+F focuses the search box again though, instead of just clearing it. Fair enough about the complicated UX though.

**Comment by tallpants** [comment]
Would you be open to adding shortcuts for the default tags at least?

**Comment by bhollis** [comment]
Maybe, though Shift+1, Shift+2, etc are already bound to tagging. Overall I'm not convinced that super specialized keyboard shortcuts will get used often, especially if there's no way to communicate them in the UI. We show hints for the tagging shortcuts and most people don't figure that out.
