### ISSUE TITLE
SMIL animations are deprecated

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#636]
The new overlay animation is awesome, but Chrome warns that the technique it uses for animation will be removed soon:

> SVG's SMIL animations (<animate>, <set>, etc.) are deprecated and will be removed. Please use CSS animations or Web animations instead.

/cc @ericnelson0

**Comment by ericnelson0** [comment]
Thanks for bringing this up. I saw the warning and I intended to move the animations to css, but I got distracted. 

The following changes should allow us to deal with the deprecation of SMIL animations:

Starting on line 65 of <code>dimStoreItem.directive.js</code> add a div around the overlay image
```
        '    <div ng-if="vm.item.isNew" class="new_overlay_overflow">',
        '      <img ng-if="vm.item.isNew" class="new_overlay" src="/images/overlay.svg" height="44" width="44"/>',
        '    </div>',
``` 

In _style.scss we need to add:

```
// OVERLAY /////////////////
@keyframes new_overlay { /* CSS3 */
	0%   { transform: translate(-44px, -44px) scale(2)}
	100% { transform: translate(44px, 44px) scale(2)}
}
@-moz-keyframes new_overlay { /* Firefox */
	0%   { transform: translate(-44px, -44px) scale(2)}
	100% { transform: translate(44px, 44px) scale(2)}
}
@-webkit-keyframes new_overlay { /* Webkit */
	0%   { transform: translate(-44px, -44px) scale(2)}
	100% { transform: translate(44px, 44px) scale(2)}
}
.new_overlay {
	animation:         new_overlay 5s infinite; /* CSS3 */
	-moz-animation:    new_overlay 5s infinite; /* Firefox */
	-webkit-animation: new_overlay 5s infinite; /* Webkit */
}
.new_overlay_overflow {
  overflow: hidden;
}
////////////////////////
```

and finally the animations in the svg of <code>overlay.svg</code> should be removed (or commented out).

**Comment by bhollis** [comment]
Would you mind making that into a PR? Thanks!
