### ISSUE TITLE
Allow a single loadout to specify armor sets for each class

### ISSUE THREAD

**Issue by rentalhost** [DestinyItemManager/DIM#6374]
**Proposed change**

Currently, on apply an existing loadout it will move all equips, even incompatible to the target character. My proposal is avoid move incompatible items because... it is incompatible.

For instance: I have one different loadout depending of the activity (ex. "Deep Crypt" contains The Lament as heavy, all Legacy equips, etc.). But I have only one loadout for this activity for my three classes characters. So it contains armors from titan, hunter and warlock. But make no sense I move titan equips to hunter, for instance, because hunter cannot use titan equips.

So my proposal is just avoid incompatible equips to target.

---

**Full example:**

1. Create a loadout called "Test" containing one hunter helmet, one titan helmet and one warlock helmet. Save it.
2. Apply this loadout to hunter.
3. Only the hunter helmet must move, titan and warlock must be just ignored.

---

**Considerations:**

* During move, instead of shows "moving 3 items" it must shows only "moving 1 item" (only the compatible item).
* Inside the loadout editor the highlighted armor (that is equiped automatically) will needs supports the three characters classes. So to make it easier, I think that instead of make possible mark three items inside one category, must have one category for each class (eg. "hunter helmet", "titan helmet", "warlock helmet"). The class should be displayed only if the loadout mixes a lot of classes, else it will shows only "helmet".

![image](https://user-images.githubusercontent.com/421851/102938611-688ac580-448b-11eb-8b46-06fee596acdd.png)

---

The reason for that is that I can only keeps one loadout for all chars, so the maintenance is easier that keeps one for each char for each activity. For instance, currently I do not have the Anarchy, but when I have it I will add to Crypt loadout. Having three Crypt loadout I will need modify all, but with this feature I just need do it once. Now multiply it for each available activity.

**Comment by bhollis** [comment]
We already filter out un-equippable items when applying a loadout, but we don't support multiple equipped (one per class) nor do we avoid moving them.

We should think about this, but my gut feeling is that this would require a rethink of how loadouts are edited and presented, and I'm not sure that's worth it vs. just making three loadouts.

**Comment by rentalhost** [comment]
@bhollis I think that avoid moving, at least, will help a lot. So on future it could create separated categories.
