### ISSUE TITLE
comparison view sort does not sort correctly

### ISSUE THREAD

**Issue by deangaudet** [DestinyItemManager/DIM#6384]
**What version of DIM are you using?** 6.44.0

**What Browser and OS are you using?** chrome/windows

**Describe the bug and how to make it happen**
if i compare multiple weapons, then click "range" it doesn't sort properly.  at least i assume it's supposed to sort, because it did in the past.  for example, in the included screenshot i have clicked "range" once, but the items are ordered 69, 71, 62, 65, 61, 60, ...
<img width="767" alt="{F7EA68E5-08D9-4EC5-8248-5FFB37ACCDBD}" src="https://user-images.githubusercontent.com/76624780/103155922-a07a5d00-4758-11eb-99f0-90cea04f812c.png">

**Include devtools console logs**

```
log.ts:11 [app] DIM v6.44.0 (release) - Please report any errors to https://www.github.com/DestinyItemManager/DIM/issues
log.ts:11 [dim sync] globalSettings Object
2log.ts:11 [bungie auth] Successfully updated auth token from refresh token.
log.ts:43 Timer 'Load manifest' already exists
i @ log.ts:43
log.ts:44 Load manifest: 3179.06689453125 ms
log.ts:11 [dim sync] Saving profile data to IDB
log.ts:44 Timer 'Load manifest' does not exist
(anonymous) @ log.ts:44
log.ts:44 Process inventory: 302.31591796875 ms
log.ts:44 Inventory state update: 1739.7119140625 ms
log.ts:44 Process inventory: 266.34521484375 ms
log.ts:44 Inventory state update: 998.041259765625 ms
log.ts:44 Process inventory: 210.51611328125 ms
log.ts:44 Inventory state update: 514.743896484375 ms
log.ts:11 [dim sync] Saving profile data to IDB
log.ts:44 Process inventory: 326.033203125 ms
log.ts:44 Inventory state update: 192.177001953125 ms
log.ts:44 Process inventory: 147.989990234375 ms
log.ts:44 Inventory state update: 376.677001953125 ms
log.ts:44 Process inventory: 379.664794921875 ms
log.ts:44 Inventory state update: 245.2568359375 ms```

**Comment by kyleshay** [comment]
fyi issue is related to "show base stats", we sort on the actual stats and not base (even if it is checked.)
