### ISSUE TITLE
missing vendor

### ISSUE THREAD

**Issue by i1ich** [DestinyItemManager/DIM#6388]
**What version of DIM are you using?**
Версия 6.45.0.1000119 (beta), собрана 28.12.2020, 05:16:59
**What Browser and OS are you using?**
windows 10 chrome

**Describe the bug and how to make it happen**
missing petra venj in vendors window

**Include devtools console logs**
If you can, open the devtools console (ctrl+shift+J on PC and cmd+option+J on Mac) and paste what you see in the window that pops up:

```
Paste console logs here
```

**Comment by delphiactual** [comment]
Bungie-net/api#655
