### ISSUE TITLE
CORS error connecting to the DIM API

### ISSUE THREAD

**Issue by 48klocs** [DestinyItemManager/DIM#6389]
`Access to fetch at 'https://api.destinyitemmanager.com/profile?platformMembershipId=4611686018467401675&destinyVersion=2&components=settings%2Cloadouts%2Ctags%2Chashtags%2Csearches%2Ctriumphs' from origin 'https://beta.destinyitemmanager.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

This is in beta, on Chrome 87/Windows 10.

Connecting directly to https://api.destinyitemmanager.com/ I see a "hello" JSON response.

**Comment by bhollis** [comment]
Yes, this is caused by the service being down. We have been having some issues talking to the database.
