### ISSUE TITLE
Active mode on portrait displays is hard to use

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#6393]
Current beta on Chrome on Windows 10.

I use DIM on a 1440 x 2560 portrait display.

Here's what it looks like normally.

![image](https://user-images.githubusercontent.com/25425159/103390560-fab65c00-4b64-11eb-8f97-d8626dd202a7.png)

Click inventory mode.

![image](https://user-images.githubusercontent.com/25425159/103390568-0c97ff00-4b65-11eb-978c-eedf2cd614f1.png)

New column addeed to the left, taking about 25% of available screen space, and the vault gets pushed off the screen to the right, and the << button next to the vault isn't shown unless you scroll.

Click the << button.

![image](https://user-images.githubusercontent.com/25425159/103390597-3e10ca80-4b65-11eb-96cc-86aedef43599.png)

Now we have a useful display.

If clicking inventory mode would cause the display to have to scroll, it should automatically select current character mode as well.

**Comment by bhollis** [comment]
I think I generally disagree that we should couple Active Mode and Single Character Mode automatically, as they are for different purposes.

**Comment by philkernick** [comment]
Fair enough.  But there has to be a better way to use Active Mode on a portrait display.  How does it work on a mobile device that has vastly less screen space?

**Comment by bhollis** [comment]
It isn't available on mobile. TBH Active Mode was a beta thing that hasn't been finished.
