### ISSUE TITLE
Precision handcannon magazines are especially wrong

### ISSUE THREAD

**Issue by nev-r** [DestinyItemManager/DIM#6395]
but i figured out why!

https://www.bungie.net/en/Explore/Detail/News/49676
> Precision Hand Cannon
> (180 RoF) magazine scaled up by 37 percent.

this is not reflected in definitions, it is applied as an effect. we can account for it with a multiplier, and i think we should. because 37% error is a lot to hand-wave away, when it's known both how and why we should adjust it. this one we have the supporting info for, it's not simply data quirks.

**Comment by nev-r** [comment]
adjusting after interpolation is the one that gets some values right
![image](https://user-images.githubusercontent.com/68782081/103437387-faa57300-4bdb-11eb-9ecc-c3f7d122e386.png)

**Comment by bhollis** [comment]
That's a real bummer. I support fixing it on our side if we can get it right. 

Couple thoughts on where to apply the scale:

1. Have you applied banker's rounding to the scale-up? 
2. Should we scale up the interpolated value, then round, or round, then scale, then round again?

**Comment by nev-r** [comment]
rounding twice is a great idea i hadn't tried. tried banker and i couldn't get meaningfully better or worse, but i will retry with the other idea.

**Comment by bhollis** [comment]
Is this still in effect?
