### ISSUE TITLE
Deep Stone Crypt raid mods not in Loadout Optimizer but checked off in Records

### ISSUE THREAD

**Issue by fourdegrees** [DestinyItemManager/DIM#6398]
I am able to navigate within DIM to Records -> Collections -> Mods -> Armor -> Legacy and Raid and I can see that all four Deep Stone Crypt mods (Herd Thinner, Enhanced Operator Augment, Enhanced Scanner Augment, and Enhanced Suppressor Augment) are "double checked" by DIM as "This item is in your inventory" and "This item is unlocked in collections." Unfortunately, when I open the Loadout Optimizer tab and click on "Select mods" then try to find them, I cannot locate any of them. If I type in "Search a mod or description" and try things like "raid" or "enha" or "herd" or whatever, they don't show. If I type "raid" then I correctly see the Garden of Salvation mod I have unlocked (I only have one unlocked for that activity). 

I have tried logging out of DIM and back in. I have tried closing and reopening the tab. I have tried opening DIM in different browsers. I talked to ace on the Discord server and he recommended filing an issue here. Cheers.

**Comment by chrisdouglass** [comment]
Hitting this too. Is there a definitions file for what shows in the optimizer?
