### ISSUE TITLE
Collect bounties through DIM

### ISSUE THREAD

**Issue by Poltergeisen** [DestinyItemManager/DIM#6406]
**Proposed change**
Now that bungie has implemented a way for the mobile app to collect bounties from vendors it would be nice for DIM to be able to do the same

**How does this fit into your workflow?**
Collect bounties through dim while in orbit

**Comment by delphiactual** [comment]
Not available to 3rd party applications at the moment

**Comment by bhollis** [comment]
https://destinyitemmanager.fandom.com/wiki/Category:FAQ#Will_DIM_be_able_to_pick_up_bounties.3F

**Comment by Revadike** [comment]
> https://destinyitemmanager.fandom.com/wiki/Category:FAQ#Will_DIM_be_able_to_pick_up_bounties.3F

Interesting. Did Bungie disallow this explicitly? I imagine it wouldn't be impossible to reverse engineer this functionality?

**Comment by bhollis** [comment]
It is not allowed for third party apps.

**Comment by Revadike** [comment]
> It is not allowed for third party apps.

Bungie said so? For what reason?
