### ISSUE TITLE
Local DIM error

### ISSUE THREAD

**Issue by gingerwilliams** [DestinyItemManager/DIM#6407]
**What version of DIM are you using?**
6.46.0

**What Browser and OS are you using?**
Chrome on MacOS

**Describe the bug and how to make it happen**
When running local copy of DIM on https://localhost:8080 from instructions here: https://github.com/DestinyItemManager/DIM/blob/master/docs/CONTRIBUTING.md
I get the following error: 
Unable to load your Destiny 2 characters and inventory
Bungie.net is currently experiencing difficulties.

**Include devtools console logs**
```
[d2-stores] Vault or character inventory was missing - bailing in order to avoid corruption 
[d2-stores] Error loading stores Error: Bungie.net is currently experiencing difficulties.
```

**Comment by delphiactual** [comment]
Join us in discord @ https://discord.gg/3PsHff5d in the #dim-developer-chat so we can help troubleshoot this. It appears to me, that a step was probably missed.
