### ISSUE TITLE
Ghost shell, ship and sparrow equipped by other characters appear in vault when other character view is hidden

### ISSUE THREAD

**Issue by buncieboy343** [DestinyItemManager/DIM#6408]
Version 6.46.0 (release)

Chrome

When I minimize my other character view their equipped ghost shell, ship and sparrow all appear as being in the vault when they aren't. This may also affect extra shells/ships/sparrows, but I can't test/verify as I only have 1 on each character. Attached screenshots of it open and minimzed. Also attached screenshot showing it is equipped on 2nd character, but appears in vault. Obviously a very minor issue, but thought I would report anyways :)

![image](https://user-images.githubusercontent.com/76978475/103593024-912fa800-4eec-11eb-913a-e0e19a683409.png)
![image](https://user-images.githubusercontent.com/76978475/103593051-a7d5ff00-4eec-11eb-93f3-961f146e3582.png)
![image](https://user-images.githubusercontent.com/76978475/103593066-b4f2ee00-4eec-11eb-8216-274bf64f90bf.png)

Omitted console logs as I assume not needed, let me know if you want me to add them.

Thanks!

**Comment by buncieboy343** [comment]
Just realized when playing around with this that it might be intended, as the same thing happens with weapons (but not armor). Just seems strange to me as I would assume they were in vault, not on other character. Could it be grouped into another tab (a slim tab on right side called "equipped on other characters" or something)?

**Comment by kyleshay** [comment]
hmm maybe a mini icon on the item image to denote it's equipped on another character? i can see not wanting to move a ghost/ship/sparrow but weapons not being as important. though some users may just have one generic ghost they share between characters.

**Comment by bhollis** [comment]
Yeah this is intentional. Single character mode treats your other characters as "vault".
