### ISSUE TITLE
Custom god roll weapon

### ISSUE THREAD

**Issue by rishabhdeepsingh** [DestinyItemManager/DIM#6419]
It will be great if we can add a custom roll for a weapon that we want to have(currently don't have that weapon). and it gets highlighted in a different color.

**Comment by bhollis** [comment]
We have https://destinyitemmanager.fandom.com/wiki/Wish_Lists as the solution to this. You can craft your own wish list.

**Comment by rishabhdeepsingh** [comment]
IS there an easy way to create a custom wishlist?

**Comment by delphiactual** [comment]
Easy is subjective, have you tried d2gunsmith.com

**Comment by rishabhdeepsingh** [comment]
Thanks a lot.
