### ISSUE TITLE
Weapons not showing

### ISSUE THREAD

**Issue by burk757** [DestinyItemManager/DIM#6420]
**What version of DIM are you using?**
Find the version in "About DIM" from the menu (the button with three bars on the upper left of the screen). Is the DIM icon orange, or blue?

Version 6.46.0 (release), built on 1/3/2021, 9:24:52 PM

**What Browser and OS are you using?**
It helps to know what type of browser and what version you're using. Have you installed DIM as an app through Chrome or Safari?

downloaded as an app through chrome

**Describe the bug and how to make it happen**
Tell us what's wrong. A great format for bug reports is "I did X, and I expected Y, but instead Z happened." If it helps illustrate the issue, please add screenshots to help explain your problem.

weapons just stopped showing up

**Comment by bhollis** [comment]
Screenshot? Developer console logs?

**Comment by wein3967** [comment]
Not saying it's the case here ... but make sure you didn't accidentally collapse the Weapons rows.
![image](https://user-images.githubusercontent.com/11590326/103800415-02b54680-5012-11eb-9308-74e097de6827.png)

**Comment by bhollis** [comment]
No followup info, closing.
