### ISSUE TITLE
Loadout Optimizer crashing

### ISSUE THREAD

**Issue by 48klocs** [DestinyItemManager/DIM#6427]
An error reported from Discord.

`I'm getting a error when trying to use the loadout optimizer, everything else works fine. I've used the optimizer in the past with no issues. Same error using DIM stable and beta. Same error when using different browsers (firefox and chrome). Tried logging out and back in and have cleared my browser cache as well. Anybody have any ideas?`

The error message is `Cannot read property 'base' of undefined`

![image](https://user-images.githubusercontent.com/606888/104106554-cb9a9b80-5284-11eb-868f-93764d370b1c.png)

**Comment by ryan-rushton** [comment]
Did you figure out what item is causing it out of interest? Stats on items in process should never be undefined as they are all armour

**Comment by 48klocs** [comment]
No idea, but the person that brought it up in Discord said that it's resolved. I'll close this + the PR.

**Comment by wein3967** [comment]
I'm still getting the same crash when using LO. Once I click on LO I get this screen and DIM is "locked" there until I close the browser tab.
![image](https://user-images.githubusercontent.com/11590326/104131970-d82ffa00-533f-11eb-8265-cd9f59a89116.png)

**Comment by ryan-rushton** [comment]
@wein3967 do you have any armour items in your inventory or on you character that most people wouldn't have? I'm thinking maybe a festival of the lost mask or really old armour? The reason I ask is that it would be good to figure out what item is causing this.

**Comment by wein3967** [comment]
I haven't acquired any "old" stuff recently, meaning I have the same "old" stuff as I've had in the past when LO has worked fine. However, yes, I've got probably got some non-typical stuff. Mainly, a FOTL mask and the white Brave set of Titan armor.
![image](https://user-images.githubusercontent.com/11590326/104135957-b98a2d00-5358-11eb-9ab9-e91dad8008f8.png)

**Comment by ryan-rushton** [comment]
Awesome I will add some of those to my inventory and give it a test.

**Comment by ryan-rushton** [comment]
@wein3967 Where did you get the white Brave set from? I don't have that in collections.

**Comment by wein3967** [comment]
Yeah, the reason I've held on to them is that they aren't pullable from Collections. I believe that is the set you get as soon as you start the campaign on a new Titan ... before Gaul takes the light.

**Comment by wein3967** [comment]
They have stats though.
![image](https://user-images.githubusercontent.com/11590326/104139299-2d83ff80-5370-11eb-8fa0-c8d40180d65a.png)

**Comment by ryan-rushton** [comment]
Ok I am pretty happy to rule out those then. It might be that FoL mask then. I can only pull the forsaken one from collections.

**Comment by wein3967** [comment]
@ryan-rushton Yay! It works again. Thanks.

**Comment by ryan-rushton** [comment]
It appears a number of items were causing this, the main examples seem to be
- festival of the lost masks
- scorched hunter cloak (white version of solstice class item)
- bond of the raven shard (green warlock bond)
- scavenger cloak (green hunter cloak)
- tattered titan mark (white titan mark)

It's also possible there may be a armour 1.0 item of two in there causing issues but the above are the main culprits.
