### ISSUE TITLE
Search Condition for Checking for Items equal to the Seasonal Power Cap

### ISSUE THREAD

**Issue by TMMania** [DestinyItemManager/DIM#6439]
![image](https://user-images.githubusercontent.com/74565769/104245339-b0b55c00-5429-11eb-8b42-8c09e19ca48c.png)

From the referenced image, the blue number next to "seasonal power cap" is a value that changes once one season ends and another begins. This value increases by 50. So from Season 12 to Season 13 it goes from 1260 to 1310.

"power:SeasonalPowerCap" Shows items that have a power level equal to the seasonal power cap of the currently active season.

**How does this fit into your workflow?**
This would allow players to identify items that are at the maximum power level for the current active season and be able to look at their rolls and see which ones are good for infusion or just how many items they have at the current power cap with a static condition.

For my workflow, this would allow my Master Filter to have massively increased longevity without updates. Currently I have a condition that checks if an item is at the Seasonal Power Cap but is using the format "power:1260" and I would have to update this every time a season ends and the seasonal power cap increases. Having "power:SeasonalPowerCap" would allow a smooth hands-off transition from season to season.

**Comment by bhollis** [comment]
What I was thinking of doing, instead, was to make "hardcap" and "softcap" into keywords that can be used in place of specific power levels in any search that takes power level. These would resolve to the current seasonal hard and soft cap each season.

**Comment by TMMania** [comment]
That would work fine and the differentiation between hard and soft cap would be great.
