### ISSUE TITLE
DIM Desktop app disappears from PC

### ISSUE THREAD

**Issue by MonkeyNinja7008** [DestinyItemManager/DIM#6446]
**What version of DIM are you using?**
Find the version in "About DIM" from the menu (the button with three bars on the upper left of the screen). Is the DIM icon orange, or blue? 

- **Version 6.47.1, icon is Orange**

**What Browser and OS are you using?**
It helps to know what type of browser and what version you're using. Have you installed DIM as an app through Chrome or Safari?

- **Installed app from Microsoft Store**

**Describe the bug and how to make it happen**
Tell us what's wrong. A great format for bug reports is "I did X, and I expected Y, but instead Z happened." If it helps illustrate the issue, please add screenshots to help explain your problem.

- **Once installed app works absolutely fine, however after turning my PC off the app is completely uninstalling itself, even searching via the windows task bar doesn't find the app. I have to redownload the app from the store again (this has happened twice now)**

**Include devtools console logs**
If you can, open the devtools console (ctrl+shift+J on PC and cmd+option+J on Mac) and paste what you see in the window that pops up:

```
Paste console logs here
``` log.ts:11 [app] DIM v6.47.1 (release) - Please report any errors to https://www.github.com/DestinyItemManager/DIM/issues
5Tracking Prevention blocked access to storage for <URL>.
log.ts:11 [dim sync] globalSettings Object
log.ts:44 Load manifest: 1880.080078125 ms
log.ts:11 [dim sync] Saving profile data to IDB
log.ts:44 Process inventory: 62.036865234375 ms
log.ts:44 Inventory state update: 364.14697265625 ms
inventory:1 [Intervention] Images loaded lazily and replaced with placeholders. Load events are deferred. See https://go.microsoft.com/fwlink/?linkid=2048113
log.ts:44 Process inventory: 61.8837890625 ms
log.ts:44 Inventory state update: 101.548095703125 ms
log.ts:11 [SW] Got server version Object

**Comment by bhollis** [comment]
@kyleshay we've gotten tons of reports of this, but of course we have no control over how the Microsoft Store works. Do we want to just remove DIM from there?

**Comment by kyleshay** [comment]
Hi @MonkeyNinja7008 ! We've pushed a new version out to the Windows stores. When you have a moment could you please give it a try? Thanks for your support!
