### ISSUE TITLE
A “Move all glimmer items to vault” button

### ISSUE THREAD

**Issue by twe4ked** [DestinyItemManager/DIM#645]
I'd love a button to move all the items that you can trade for glimmer ([axiomatic beads](http://db.destinytracker.com/items/2904517731-axiomatic-beads), [house banners](http://db.destinytracker.com/items/269776572-house-banners), etc.) into the vault.

**Comment by bhollis** [comment]
Neat idea. Could you expand a bit on why this would help you out?

**Comment by twe4ked** [comment]
When I've got lots of glimmer I like storing the items I can trade in so that I don't hit the 25k glimmer cap. A button would be faster than me trying to remember what the different items are.

😃

**Comment by nki2bpz** [comment]
i do the same thing i think its quite common among my clan so as to avoid dealing with glimmer cap although i may be extreme 240,000 glimmer in vault

**Comment by kyleshay** [comment]
@bhollis with the addition of the custom search loadout, thing... if we added a new filter for items that were consumables, this would be easy enough for any user to create a custom search loadout filter. wonder how we could train our users on that though.

**Comment by kyleshay** [comment]
will be resolved once we have savable search filters per #397

**Comment by twe4ked** [comment]
Awesome, thanks.
