### ISSUE TITLE
Edge Android Browser

### ISSUE THREAD

**Issue by elokaynu** [DestinyItemManager/DIM#6452]
Using current version of Edge on Android,  browser / app works flawlessly as it uses Chromium. But there is an annoying issue that says it's not supported, been using Edge since beta as well as DIM. Is there a way we can get it added?

**Comment by bhollis** [comment]
"It works" and "it's supported" are two very different things. "It's supported" means we'll fix bugs in it.

I'll look and see if there's an easy way to add this most recent Chrome clone to our support policy, but a better recommendation for Android is to install the app via the Play Store or Chrome, after which it doesn't matter what browser it's using and it works better too.

**Comment by elokaynu** [comment]
Didn't realize there was an Android app for it. Been using it as a Chrome\Edge app since D1. Always thought it would be awesome to just have an app for it.

**Comment by bhollis** [comment]
Can you go to https://www.whatismybrowser.com/detect/what-is-my-user-agent with Edge for Android and paste what your user agent string is?

**Comment by bhollis** [comment]
No response, closing.
