### ISSUE TITLE
Filtering for "dragonfly" returns the patched Cold Front SMG if it used to have the "Dragonfly" perk

### ISSUE THREAD

**Issue by jbccollins** [DestinyItemManager/DIM#6456]
**What version of DIM are you using?**
6.48.0

**What Browser and OS are you using?**
Chrome / MacOS 10.15.7

**Describe the bug and how to make it happen**
On 2021-01-19 Bungie published update 3.0.2 which removed the perk "Dragonfly" from any Cold Front SMGs that had the perk as it was "unintended" that this weapon could roll that perk. They replaced it with the perk "Swashbuckler". Using DIM to filter for the keyword "dragonfly" that weapon is still matched.
![Screen Shot 2021-01-20 at 2 01 05 PM](https://user-images.githubusercontent.com/8915552/105222835-06c08880-5b29-11eb-9daf-f7f1a77b961f.png)

**Comment by bhollis** [comment]
You have the "Dragonfly Spec" mod on that gun.

**Comment by jbccollins** [comment]
I am so dumb :(

**Comment by bhollis** [comment]
To be fair, I've wanted to highlight *what* matches the search on the item card for years. Just haven't gotten to it.
