### ISSUE TITLE
modslot:season filter doesn't show amor

### ISSUE THREAD

**Issue by IlMollaz** [DestinyItemManager/DIM#6458]
**What version of DIM are you using?**
6.48.0 (2021-01-17)
Version 6.48.0.1000164 (beta)

**What Browser and OS are you using?**
I have installed DIM through Chrome on a Windows 10 pc.

**Describe the bug and how to make it happen**
Using the modslot filter with the name of a season (I have tried so far with "forsaken", "undying" and "forge"), the UI doesn't highlight the armors with that specific seasonal mod slot
![Cattura](https://user-images.githubusercontent.com/66443443/105406363-9dc23900-5c2c-11eb-8bc8-489f424d1b05.PNG)

**Include devtools console logs**
```
Some messages have been moved to the Issues panel.
View issues
instrument.ts:129 [dim sync] Saving profile data to IDB
log.ts:44 prepareUpdateQueue: 0.090087890625 ms
instrument.ts:129 [flushUpdates] Flushing queue of 1 updates
instrument.ts:129 [flushUpdates] got results 
[{…}]
 
[{…}]
instrument.ts:129 
```

**Comment by bhollis** [comment]
That's correct, modslots are no longer named after seasons. Please look at the "Filter Help" entry from the search dropdown for a list of all valid keywords for this search.
