### ISSUE TITLE
Exclude items from loadout builder

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#646]
https://www.reddit.com/r/DestinyItemManager/comments/4qbsr8/t12_builder_exclude_some_items/

We used to have similar functionality (shift click I think?) for the infusion calculator.

**Comment by kyleshay** [comment]
should be simple enough! [for reference](https://github.com/DestinyItemManager/DIM/commit/38562f39b1af63bfbf8dc972cb23fd9823dcfdc9)
