### ISSUE TITLE
Half tier stats not working as they should be

### ISSUE THREAD

**Issue by ReTem** [DestinyItemManager/DIM#6469]
**What version of DIM are you using?**
Version 6.49.0.1000177 (beta), built on 1/27/2021, 1:02:30 AM (blue icon)

**What Browser and OS are you using?**
Firefox 84.0.2 (64-bit)

**Describe the bug and how to make it happen**
The new update states: Loadout Optimizer shows "half tiers" (0.5) to help you see where a 5-point mod might bump you up a tier. Note that this does not suggest we're displaying a new 0.1 precision for tiers - we are specifically rounding down to half-tiers now instead of full tiers.

The feature is nice, but there are some things wrong with it atm. First of all half stats should not count towards the Tier total since it is straight up inflating the tier numbers without actually being a T31 (picture example). 
For some reason the selection pane on the left doesn't work properly, for example the discipline tier on the left always drops back to 2.5 even though there are higher builds possible. If i select 10 on recovery for example it drops down to the minimum as well, because 9 is the highest possible i can reach with my armor. 
![image](https://user-images.githubusercontent.com/61243690/105985590-f1ed7300-609b-11eb-8c39-9bf8af166b95.png)

**Comment by bhollis** [comment]
Maybe worth reverting the feature and taking another, more targeted pass at it?

**Comment by bhollis** [comment]
This also seems to make the tier effect tooltips inaccurate: 
<img width="298" alt="image" src="https://user-images.githubusercontent.com/313208/106041720-0415e400-6091-11eb-90e1-1b2a63490ad2.png">

**Comment by bhollis** [comment]
Maybe what we need is just a flag within each armor set that says "this could be boosted by a 5pt mod"?

**Comment by ryan-rushton** [comment]
Yeah let's revert it and have another go.
