### ISSUE TITLE
Flexible sorting

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#647]
Right now we have a bunch of different options for sorting items. I'd like to propose replacing this with a list of properties, and folks can choose to enable/disable the property or change its order relative to other properties, in order to create their own fancy sort order.

A next-level enhancement would be an option that adds groupings with headers to items in the vault based on these options - maybe just the top sort, or certain checked sort properties?

We'd probably want to put this under a "Custom" search option and still have the simple options we have now.

See https://www.reddit.com/r/DestinyItemManager/comments/4pygfp/please_pleaseone_complex_enhancement_suggestion/ for an example.

**Comment by kyleshay** [comment]
agreed this would be very useful, especially as vault space may possibly grow with future expansions.

similar to #573 ?

**Comment by bhollis** [comment]
Yeah this would implement #573.

**Comment by SunburnedGoose** [comment]
@delphiactual, do you have any capability to mock up what you're thinking in #815?  Balsamiq maybe?

**Comment by delphiactual** [comment]
@SunburnedGoose 

https://dl.dropboxusercontent.com/u/27235337/Sorting.bmpr

Of course you would remove the selected from combo boxes below..

**Comment by delphiactual** [comment]
Actually, even better

http://rotundasoftware.github.io/backbone.collectionView/

Just add checkboxes on the left hand side for enabled or disabled...

**Comment by bhollis** [comment]
@delphiactual yeah that's exactly what I was thinking of!

**Comment by JakeWhitaker** [comment]
Could put it in with the filter list. Enable or Disable the sorting options too(e.g. even though rarity is second, if I don't want to sort by rarity at all, I'd uncheck it or something) Slide them higher or lower on the list to prioritize sorting.
![0014 sorting mock](https://cloud.githubusercontent.com/assets/21060251/19526204/b2944dce-95f1-11e6-8bc9-c2dc06f10c4f.gif)

**Comment by kyleshay** [comment]
Just got a suggestion for an additional sort option: by weapon archetype (then for armor, guessing by stat split distribution.)
