### ISSUE TITLE
incorrect message: "You must go to the tower to retrieve this item"

### ISSUE THREAD

**Issue by nev-r** [DestinyItemManager/DIM#6473]
something, i assume #6461, changed the "pullable-ness" determination conditions, incorrectly.

pre-#6461 code:
![image](https://user-images.githubusercontent.com/68782081/106238596-fad26780-61b5-11eb-81de-c94532457c38.png)

this is correct. i can pull these.

<hr />

main branch:
![image](https://user-images.githubusercontent.com/68782081/106238850-716f6500-61b6-11eb-98cc-ac470ab95cfa.png)
incorrect. though at least the pull buttons are still there.

**Comment by goomba5** [comment]
@nev-r if you are willing and still have the Ascendant Shards in your Postmaster, would you mind copy/pasting or sending a screenshot of the properties for the Ascendant Shard?

**Comment by nev-r** [comment]
attached is that stack's DimItem
[shards.txt](https://github.com/DestinyItemManager/DIM/files/5893367/shards.txt)

**Comment by goomba5** [comment]
Thank you!

**Comment by bhollis** [comment]
The `notransfer` property isn't super useful for stuff in Postmaster. We should use the utility functions we have for postmaster pullability like https://github.com/DestinyItemManager/DIM/blob/151c708fce22df8e889311d938b568947b15d548/src/app/loadout/postmaster.ts#L91-L97

**Comment by goomba5** [comment]
@bhollis That's what I get for not following directions. Sorry about that. I just created #6477 which uses `canBePulledFromPostmaster` instead of `notransfer`. If there's anything else I should update, definitely let me know.
