### ISSUE TITLE
Cooldown and Effects partially wrong on Hunter and Titan

### ISSUE THREAD

**Issue by Berndserk** [DestinyItemManager/DIM#6478]
**What version of DIM are you using?**
6.49

**What Browser and OS are you using?**
Crome on Windows 10

**Describe the bug and how to make it happen**
Some Cooldown and Effect stats are different from ingame stats:
Hunter:
Mobilty T5 Cooldown: DIM 0:20, Game 0:24
Strengh T5 Cooldown: DIM 0:59, Game 1:09

Titan:
Resilience T5 Effect: DIM 6%, Game 5%

The rest of the stats were equal to ingame, but i was not able to compare them accross all tiers, so I don't know if there any other differences too.

I have no mods or anything else applied... 

regards
Bernd

**Comment by ryan-rushton** [comment]
This was crowd sourced data. I might see if I can get some legitimate values from Bungie for this.

**Comment by ryan-rushton** [comment]
For reference I opened a bungie api ticket for this, https://github.com/Bungie-net/api/issues/1402.

**Comment by ryan-rushton** [comment]
I am going to sit down and check what values I can in this in the next few days. Also stasis effects will be wrong so I am going to get what I can there.

**Comment by ryan-rushton** [comment]
Closing this as some new crowd sourced cooldowns have gone into beta.
