### ISSUE TITLE
Loadout Optimizer for Hunter not working

### ISSUE THREAD

**Issue by m4tr1xusmc** [DestinyItemManager/DIM#6481]
**What version of DIM are you using?**
Find the version in "About DIM" from the menu (the button with three bars on the upper left of the screen). Is the DIM icon orange, or blue? ORANGE

**What Browser and OS are you using?**
It helps to know what type of browser and what version you're using. Have you installed DIM as an app through Chrome or Safari? CHROME

**Describe the bug and how to make it happen**
Tell us what's wrong. A great format for bug reports is "I did X, and I expected Y, but instead Z happened." If it helps illustrate the issue, please add screenshots to help explain your problem. 

Using loadout optimizer for Hunter, click on select perk, but it wont let me choose certain perks, for example I have old stompees, and it wont let me select it, among other perks. I have the exotics in my inventory as well

**Comment by m4tr1xusmc** [comment]
Just noticed, only under Hunter, when clicking select perks, for some reason some mods appear there. When I change class to warlock and titan, it works fine. only exotic perks show up. Hunter seems to be bugged?

**Comment by bhollis** [comment]
Can you share some screenshots of this?

**Comment by m4tr1xusmc** [comment]
![image](https://user-images.githubusercontent.com/78515235/106829611-55017b80-6641-11eb-9dc2-a8466f4545f0.png)

**Comment by ryan-rushton** [comment]
Those are the original mods leaking through, something must have changed in the API as I don't think that code has changed.

I also find it interesting that you don't have any class items showing in that visible build.

**Comment by ryan-rushton** [comment]
Regarding the original issue, its quite possible those stompee's are not being included in the result set as they don't have stats associated with them (no stats breaks the optimiser). If you pull a set from collections you should get an armour 2 version. Does this fix the issue?

**Comment by m4tr1xusmc** [comment]
Hi, thanks for getting back to me. Looks like I can select the perk once i pull it from collections, so that works. but dont know why those mods are showing up like that. 

Thanks again, much appreciated!!!

**Comment by ryan-rushton** [comment]
No worries at all, I will look into that and I might reach out here once its done to get you to see if it's fixed. I don't have much old gear so it's a little hard to test.
