### ISSUE TITLE
Error in mod picker

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#6485]
https://twitter.com/dennisk04296487/status/1357522536523837440

**Comment by ryan-rushton** [comment]
So digging into the item definitions on https://data.destinysets.com the only item definitions that dont have itemTypeDisplayName are the classified ones. To have a look use the following query in the console 

```
window.$DestinyInventoryItemDefinition.filter(i => i.itemTypeDisplayName === undefined);
```

That being the case I am going to make that part of the filter. I could be persuaded to have a falsey check on on the name and have "Other" in the event we get some mods that come through on the API that have this missing.

Side note, being as though that can be undefined, should we update the bungie generated API to possibly be undefined?

**Comment by nev-r** [comment]
> Side note, being as though that can be undefined, should we update the bungie generated API to possibly be undefined?

classified items defy all advertised definition structure, so really any work around item defs needs to filter out classified stuff.
typing ItemDefinition truly accurately would mean every operation is full of property existence checks
