### ISSUE TITLE
In Loadout Optimizer, add the ability to lock an Exotic armor piece in general, not just a specific one

### ISSUE THREAD

**Issue by KAdams91** [DestinyItemManager/DIM#6487]
**Proposed change**
In Loadout Optimizer, add the ability to lock an Exotic armor piece in general, not just a specific one

**How does this fit into your workflow?**
As a Warlock main and avid PvP player, I only ever use Transversive Steps as my exotic armor piece. When in loadout optimizer, I'd like the ability to only show loadouts with T-Steps locked in and it'd include all of my available T-Steps in my vault in the optimizer. As of right now in order to do this you can only lock a specific pair of T-Steps or exclude every single other piece of leg armor other than your pairs of T-Steps. 

Thank you for all of your hard work on this! DIM is amazing and I use it every single time I play Destiny. Thank youuuuu!

**Comment by bhollis** [comment]
Hi there! Please read our user guide and watch the tutorial video, which goes over how to do this.
