### ISSUE TITLE
Loadout Optimizer: Mod itemTypeDisplayName i18n

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#6500]
![image](https://user-images.githubusercontent.com/4798491/107595946-78916c80-6bd3-11eb-8686-41fec2d4e69b.png)

https://data.destinysets.com/i/InventoryItem:4048838440

itemTypeDisplayName needs either ellipsis or some other form of css magic

**Comment by ryan-rushton** [comment]
I am actually stripping words out of them currently as they are really long and we don't need all that info. The only problem with this is those words are english. 

Also they are buttons which are usually centre aligned and explains why we are getting that behaviour.

Taking this a step further the mobile view of this is pretty wild, we might need to rethink how we display these altogether.

![Screen Shot 2021-02-11 at 1 39 21 pm](https://user-images.githubusercontent.com/7344652/107597406-a677bf00-6c6e-11eb-85d6-b1cfdfcd29e9.png)
