### ISSUE TITLE
New Ritual Vendors

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#6505]
The Crucible and Gambit vendors now use a Ritual rank system instead of the default. The API has been updated to indicate that, though I'm not sure what the other implications are. We should update our display if possible. Their icons suck too.

**Comment by delphiactual** [comment]
https://data.destinysets.com/i/Vendor:248695599

`displayProperties.smallTransparentIcon` should probably be overlaid onto `displayProperties.icon`
