### ISSUE TITLE
New search for all items at max power for each slot

### ISSUE THREAD

**Issue by hendersj** [DestinyItemManager/DIM#6521]
**What version of DIM are you using?**
Version 6.52.0.1000223 (beta), built on 2/17/2021, 2:04:21 AM

**What Browser and OS are you using?**
Chrome 88 on Linux

**Describe the bug and how to make it happen**
I've found that if I search for items using "is:maxpower", often times (but not always) only one items is found per slot, even if there are multiple items at the max power level.  I also find that if I use "-is:maxpower" or "not:maxpower", I will see similar behavior, but it might be a different item.

What I'm doing is using that filter to tag items so I can lock them and add a note (so I know that I locked them because at one time, they were my maxpower items) so I don't accidentally delete them.  I later than can do a search that includes "notes:maxpower not:maxpower" so I can unlock the item and remove the note.

**Comment by nebloc** [comment]
@hendersj have you noticed if it is specifically with exotics? The maxpower filter seems to be done on loadout, not per slot - for example in the image below, my 302 xenophage is not being highlighted as it would conflict with the 1304 divinity, and there is no other 1304 legendary energy weapon so xenophage can't be in a maxpower loadout
![image](https://user-images.githubusercontent.com/15227649/109309751-9ac5f400-783b-11eb-8b65-0466ccaf441c.png)

**Comment by hendersj** [comment]
That's not it - for example, in my setup, I currently have two power weapons at 1285 - a search for "is:maxpower" turns up only one of the items; if I search for "power:=1285", I see two power weapons at 1285 - both of them legendary.

"not:maxpower power:=1285" turns up the item that isn't identified by "is:maxpower".

It would be useful if the maxpower search (or a variant of it) showed everything that was at that power cap - I'm using this to determine what I should delete (along with a specific note field value) in order to keep my vault relatively clean (I keep having problems maxing out my vault space).

**Comment by nebloc** [comment]
Interesting! I have managed to replicate it now, as if I move the Interference GL to my vault, the Bequest suddenly doesn't show as a maxpower item...

**Comment by bhollis** [comment]
The maxpower search specifically shows the items that would be in your max power loadout.

**Comment by nebloc** [comment]
Am I correct that some are being hidden from the filter because the max power loadout functionality has biases as to where the item is (prefer equipped, then vault, then other character)? 
@bhollis Would a filter like `is:maxpowerslot` that highlights all items of that type that are at the max power, regardless of exotic restrictions or other loadout constraints be useful?

**Comment by hendersj** [comment]
That makes sense, @bhollis - but the determination of which of multiple equivalent pieces of gear would be used seems to be based on the first item found in a list.

So I guess if the way I'm using it isn't the way it's intended to be used, then I'm submitting an enhancement idea here to show all gear that is maxpower for the slot, rather than just what can go in a loadout to become maxpower.

The process I'm following right now (after having deleted items that reduced my maxpower) is this:

1.  Search for "is:maxpower"
2. Lock the items
3. Add a note with the value "maxpower"

Then when I've farmed gear for a while, I'll do it again, and then do:

1.  Search for "notes:maxpower not:maxpower"
2. Remove the note (set it to a blank value)

I used to unlock them as well, but with some items getting infusion, I was unlocking items that I didn't want to.  While this does preserve the maximum power even if I delete something that's equivalent (so I don't drop my max power), I like to keep multiple items at that power for infusion as I get near the soft cap.

I like the idea of "is:maxpowerslot" that nebloc proposed.

**Comment by bhollis** [comment]
I'm not opposed to it, it'd just be a different search. The current maxpower search is based on the loadouts code so it does stuff like not allowing two equipped exotics, for example. I think what you're proposing would just be purely based on maximum power per slot. 

PRs are welcome!

**Comment by hendersj** [comment]
That makes sense.  What you're describing is correct - a search term that's
based on maximum power per slot (and it would naturally need to be filtered
by class - I wouldn't want max power items for a hunter to show up for a
warlock and vice versa).

Is there a guide to the way in which the filter code is written?  I've not
looked at the language used for writing DIM or anything like that, but if
there was a guide to data structures and that sort of thing, I could look
over the next week or so and see if I could whack something together.

**Comment by hendersj** [comment]
It looks like the recent changes to is:maxpower and the addition of is:maxpowerloadout differentiate and make this work the way I had thought that is:maxpower worked - I really like the change and that differentiation now.

I think that this means that this can be closed.
