### ISSUE TITLE
Launch Active Mode

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#6522]
What do we still need to be able to launch active mode?

* [ ] Better UX for showing/hiding the sidebar
* [ ] Figure out whether to couple Single Character Mode and Active mode: https://github.com/DestinyItemManager/DIM/issues/6393

**Comment by bhollis** [comment]
@kyleshay do you have any thoughts on this?

**Comment by kyleshay** [comment]
Think if you're on active mode we could force single character mode. And then outside of active mode you could still toggle multi/single character mode.
