### ISSUE TITLE
Lock Icons don't update in Compare pane

### ISSUE THREAD

**Issue by Scuzzlebuttt** [DestinyItemManager/DIM#6525]
**What version of DIM are you using?**
Version 6.52.0 (release), built on 2/14/2021, 7:47:13 PM

**What Browser and OS are you using?**
Chrome on Windows 10

**Describe the bug and how to make it happen**
Click on an item.
Click Compare.
Click the "Lock" icon.

The "lock button" icon doesn't change from "unlocked" to "locked".  And the item thumbnail doesn't get a "lock icon" on it.  However, the main inventory screen does update properly (indicating lock status).  Also, it seems like once you have locked or unlocked an item from the compare pane, then further clicks to the button do nothing.

**Include devtools console logs**
Don't see anything in the console appearing after clicking on the icon.

![image](https://user-images.githubusercontent.com/25851142/108308827-0e9a3980-7176-11eb-973b-cd4c7cc8c618.png)

**Comment by delphiactual** [comment]
Dupe #5852

**Comment by Scuzzlebuttt** [comment]
Yep its a dupe, my search abilities failed me (miserably).
