### ISSUE TITLE
differences between DIM and Destiny-Internal.

### ISSUE THREAD

**Issue by Ted-Env** [DestinyItemManager/DIM#6534]
**What version of DIM are you using?**
Find the version in "About DIM" from the menu (the button with three bars on the upper left of the screen). Is the DIM icon orange, or blue?
![image](https://user-images.githubusercontent.com/55099788/108621179-756c6b00-7474-11eb-9df4-93fb27a4c308.png)

**What Browser and OS are you using?**
It helps to know what type of browser and what version you're using. Have you installed DIM as an app through Chrome or Safari?
Chrome, Windows OS

**Describe the bug and how to make it happen**
Tell us what's wrong. A great format for bug reports is "I did X, and I expected Y, but instead Z happened." If it helps illustrate the issue, please add screenshots to help explain your problem.
![D2 リロード数値 おかしいin DIM 2021-02-20 154841](https://user-images.githubusercontent.com/55099788/108621151-540b7f00-7474-11eb-9f15-b827a2306cc0.png)

This is about the Elemental Capacitor.

There is difference between In-Game value and DIM's value.
In-Game value is before reflecting conditions.
DIM's value is after reflecting multiple conditions.

at least, multiple conditions are applied that is not right.

If Adopting multiple conditions, then I request you those colors like:
 solar subclass: orange
 arc subclass: cyan
 void subclass: purple
 stasis subclass: dark blue
Or set same value of Game to those item of holding the Elemental Capacitor.

**Include devtools console logs**
If you can, open the devtools console (ctrl+shift+J on PC and cmd+option+J on Mac) and paste what you see in the window that pops up:

```
Paste console logs here
```

**Comment by 48klocs** [comment]
Could you inspect your item in the Destiny Companion App and let us know if you're seeing a discrepancy between its values and DIM's?

**Comment by Ted-Env** [comment]
Thanks 48klocs,

Now I inspected,
>let us know if you're seeing a discrepancy between its values and DIM's?
there is no discrepancy. 

Then, this is Destiny 2 supplier's matter.

Could you write here the feedback URL that Destiny 2 supplier see/handle ?

**Comment by 48klocs** [comment]
Thanks for checking that for us.

If the values are the same, then it's almost certainly a known limitation of how things work (see https://github.com/Bungie-net/api/issues/754 for one such example) - the API gets numbers, but the game servers can do things beyond that baseline input to change them. Neither Bungie nor us can do much about that.
