### ISSUE TITLE
MinMax: prepopulate with current equipped items

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#655]
Sometimes, I just want the minmax tool to tell me how to configure the perks on my currently equipped gear in order to max stats. The tool could do this if it'd have a button to populate the "locked" items from currently equipped.

**Comment by kyleshay** [comment]
If a user has 3 warlocks and wants to populate with equipped, for simplicity should it just look at the first one?

**Comment by bhollis** [comment]
Why not do the prepopulate by character, not class?

**Comment by ericnelson0** [comment]
Could we add this as an option in the loadout dropdown instead of in the loadout builder?
