### ISSUE TITLE
Update power cap logic/searches to reflect announced sunsetting changes

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#6556]
While I expect the API will be updated with the sunsetting changes, we're going to start getting more and more questions from people about DIM not reflecting the announced-but-not-implemented sunsetting of sunsetting. Can/should we update our code to take this new info into account?

**Comment by nev-r** [comment]
> We’ve made the decision that any weapon or armor that can currently be infused to max Power will continue to be able to reach max Power permanently.

weapon or armor that can currently be infused to max Power = item that can currently be infused to 1310
(this includes weapons from season of the worthy, onward)

this just means freezing `is:sunset` to current 1310.
there's absolutely no change required this season, except that we can now remove the ranged sunset filter `sunsetsin:`
