### ISSUE TITLE
Rare items not working with Loadout Optimizer

### ISSUE THREAD

**Issue by jpaulrhodes5** [DestinyItemManager/DIM#6559]
Version 6.54

Using Chrome built-in extension

I was able to see rare items i.e. my rare gauntlets in Loadout optimizer two weeks ago, now I cant? Help!

**Comment by bhollis** [comment]
@jpaulrhodes5 you've failed to fill out our issue template and you include no real information - no screenshots, no details about what items you have. On my side, I can see rare items in the Loadout Optimizer.

**Comment by ryan-rushton** [comment]
Yeah I need more information before I can look into this.
