### ISSUE TITLE
Sort by ammo type

### ISSUE THREAD

**Issue by abea** [DestinyItemManager/DIM#6562]
**Proposed change**
Proposed in reddit: https://www.reddit.com/r/DestinyItemManager/comments/lyt4w1/suggestion_sort_items_by_ammunition_type/

Add the ability to sort weapons by ammo type (e.g., special, primary).

**How does this fit into your workflow?**
Since special and primary ammo weapons generally have different roles (yellow bar clearing vs. general damage) it could be nice to sort by that to quickly choose a loadout. Similar to sorting by type, but in bigger categories.

**Comment by bhollis** [comment]
Sure, this could be a nice first contribution for someone.

**Comment by BrightReach** [comment]
I'd be more than interested in working on it.

**Comment by bhollis** [comment]
Sounds great!

**Comment by BrightReach** [comment]
I'm not 100% familiar with the environment, so which files should I go through to get started?

**Comment by bhollis** [comment]
The sorting methods are declared here: https://github.com/DestinyItemManager/DIM/blob/master/src/app/shell/filters.ts#L112

And the UI for selecting them is here: https://github.com/DestinyItemManager/DIM/blob/master/src/app/settings/SettingsPage.tsx#L182-L194

**Comment by kyleshay** [comment]
hey! might want to see how we handle the logic for splitting armor by class type here:

https://github.com/DestinyItemManager/DIM/blob/fbd32b3c213dcd1114ed453e778e9e3edffa3ea8/src/app/inventory/StoreBucket.tsx#L134

also check out our discord channel dim developer chat. 
https://discord.gg/6893Wcn3ck

excited to help you get started in the codebase, have you been able to get out up and running locally?
