### ISSUE TITLE
DIM DOESNT WORK WORK ANYMORE

### ISSUE THREAD

**Issue by hellbig125** [DestinyItemManager/DIM#657]
DIMdoesnt work anymore and bungie wont let me login too wtf happen

**Comment by Mulchman** [comment]
Can you elaborate a bit?

**Comment by hellbig125** [comment]
every time im trying to log destiny item manager or the bungie  website when im trying to log my xbox id there is a window who pop and say We're unable to complete your request

Microsoft account is experiencing technical problems. Please try again later. but its already a mont they say that

**Comment by SunburnedGoose** [comment]
DIM uses your Bungie.net login.  If you're having trouble logging into Bungie.net, that's beyond our control.
