### ISSUE TITLE
Organizer Feature Request: Ctrl+Click anywhere on row toggles selection checkbox

### ISSUE THREAD

**Issue by dlobue** [DestinyItemManager/DIM#6573]
**Proposed change**
I'd like to be able to toggle the selection checkbox of a row in the organizer by holding the control key (or any keyboard key really) and clicking anywhere on the row.

**How does this fit into your workflow?**
This would make cleaning out my vault a lot faster. I personally control my mouse using a trackpoint (the little red joystick nub), and as accurate and as fast as I am from years of practice, I spend more time moving the mouse to the checkbox and clicking it than I do reading armor stats and deciding whether I'm going to keep it. It would be really great if I could just ctrl+click the row to select it and move on.

**Comment by bhollis** [comment]
Yeah, that sounds pretty good. Would be a good first issue for someone!
