### ISSUE TITLE
Multiple custom stats per character

### ISSUE THREAD

**Issue by jeremy2345** [DestinyItemManager/DIM#6580]
Using specific stat filters and an OR/AND is simply not flexible enough. I don't care if one stat is 20 and another is 15, I care that the TOTAL of the two stats are at least 35. If one of the stats rolls 18 and the other rolls 17, I still get what I want, but the current filters won't pick this up. This can be somewhat overcome by simply listing each possible combination if you only care about a two stat combination, but if you want to look for combinations of THREE stats, the filter suddenly rockets into thousands of lines.

This feature would allow for some pretty awesome filters, such as the following filter that would work really nicely for all my stuff at once:

( is:titan AND (
basestat:custom1:>=50 OR
basestat:custom2:>=50 OR
basestat:custom3:>=50 ) )
OR
( is:hunter AND (
basestat:custom1:>=50 OR
basestat:custom2:>=50 OR
basestat:custom3:>=50 ) )
OR
( is:warlock AND (
basestat:custom1:>=40 OR
basestat:custom2:>=40 OR
basestat:custom3:>=40 ) )

If it is not feasible to give users the ability to dynamically create as many custom stats as they like, then I imagine 3 would be a good number. This provides one custom stat each for discipline, intellect, and strength builds. This would be sufficient for the vast majority of users.

**Comment by bhollis** [comment]
This is what our "Custom Stat" feature is for - you can set it up per-character in Settings.

**Comment by jeremy2345** [comment]
I've updated this issue per our discussion in discord. It is now entirely focused on multiple custom stats.

**Comment by bhollis** [comment]
We're not likely to do multiple custom stats or support math in searches.

**Comment by delphiactual** [comment]
#6591
