### ISSUE TITLE
Latest release to BETA drops all icons

### ISSUE THREAD

**Issue by ppokorny** [DestinyItemManager/DIM#659]
Beta channel reports version as "Version 3.7.4.223"  Is that this commit? fc0f0e5a4a9d5efac93644a8a2b6807766d05d86 ??  

All icons are missing and only the item decorations (element, T12 rating, etc) show up all smushed together.

Using Chrome: Version 45.0.2454.85 (64-bit)

But the T12 loadout builder is working now.  So that's an improvement. (See https://www.reddit.com/r/DestinyItemManager/comments/4os0ji/t12_builder_page_is_broken/)

**Comment by bhollis** [comment]
I just checked on DIM v3.7.4.223 and everything works fine. Could you take a look at the developer console and tell me what you see?

**Comment by SunburnedGoose** [comment]
Hmm, that version of Chrome is a bit dated.  It was released on Sept 1, 2015.  Can you get latest and retest?

**Comment by ppokorny** [comment]
DIM v3.7.4.223 - Please report any errors to https://www.reddit.com/r/destinyitemmanager
http://www.bungie.net/common/destiny_content/icons/53b28017a0fbed3fc82da5a7654746d1.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.bungie.net/common/destiny_content/icons/e586bc58586cec2cc96e06fff3f4c620.png Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by ppokorny** [comment]
I tried, but as you point out, I'm back dated on a bunch of software on this system.  An update will take a while and I'm having trouble figuring out how to get apt to upgrade just one package (chrome) and it's dependancies.

**Comment by ppokorny** [comment]
OK.  Figured out how to upgrade chrome to 51.0.2704.106-1

Icon issue solved.

**Comment by ppokorny** [comment]
However, I do still get those two "404" errors on the console.

**Comment by SunburnedGoose** [comment]
Those are fine.  They are related to an out-of-date manifest file.  We're due for an update.
