### ISSUE TITLE
Search suggestions is gone in beta and isn't in normal either

### ISSUE THREAD

**Issue by ahydronous** [DestinyItemManager/DIM#6599]
**What version of DIM are you using?**
Beta: 6.56.1.1000301
Normal: 6.56.1

**What Browser and OS are you using?**
Brave on macOS
Brave on Windows
PWA on iOS

**Describe the bug and how to make it happen**
For a long time, when searching for an item in a bottom bar it would pop-up the items you were looking for. That is gone now.

This feature is extremely important to me and everyone else I have recommended DIM to. Until DIM had this feature, me and my friends were still all on Little Light, as it makes quickly getting the item you are looking for much easier.

**Comment by bhollis** [comment]
I think you mean the search results page? It was removed from beta because it was half-baked and needed more work, and it was never launched to prod. Feel free to continue using Little Light until it returns.

**Comment by bhollis** [comment]
Closing in favor of #6202

**Comment by ahydronous** [comment]
Yes the search results.

I literally never ran into a bug with it, except for trying to dismiss the pane whilst the search in the search bar was still active, and that wasn't any sort of showstopper.

Using Little Light was a stopgap measure. All our loadouts are in DIM, and DIM can be called up via alt+tab or the Steam overlay browser. We all much prefer DIM and it's PWA counterpart over Little Light.

Would it not be possible to put a radio box in Settings that allows to 'Enable experimental search feature', keeping the current feature available until the reworked one is ready for beta?
