### ISSUE TITLE
Search for item and perk not working 

### ISSUE THREAD

**Issue by ShojiC** [DestinyItemManager/DIM#6600]
I used to be able to search Ex: lonesome zen
And it would list all my Lonesome Sidearms with Zen Moment. Or Ex: gnaw rampage zen And it would show me all my Gnawing Hungers with Zen Moment and Rampage. But for weeks now, if I try to search for an item and perk it breaks and displays nothing and greys out the whole screen.

**Comment by bhollis** [comment]
Yes, this was changed to make it easier for people who don't know about the more advanced searches. Your searches will work if you quote the strings:

`"lonesome" "zen"` = `"lonesome" AND "zen"` wheras `lonesome zen` = `"lonesome zen"` now.

A more precise search would be:
`name:"lonesome" perkname:"zen"`

**Comment by bhollis** [comment]
Reverted to the old search behavior.
