### ISSUE TITLE
Newly acquired Frozen Orbit snipers not displaying in inventory

### ISSUE THREAD

**Issue by BlackjackMKV** [DestinyItemManager/DIM#6628]
Newly acquired Frozen Orbits don't seem to show on your character. I've been getting them from Crucible as usual, but for some reason they don't show on DIM until I move them to my vault and back even if I refresh or reload the page entirely.
It's specifically that gun, too. No other guns do this as far as I know.

**Comment by delphiactual** [comment]
Have you checked the Official Companion App and see if it displays the same behavior?

**Comment by BlackjackMKV** [comment]
It does not. The official app appears to function properly. Additionally, I also tried a third party app as well called 'The Vault', which behaves properly as well. Definitely something specific to DIM.

(Link to the Vault app in case it might be handy for comparisons or something: [https://play.google.com/store/apps/details?id=com.crocusgames.destinyinventorymanager&hl=en_US&gl=US](https://play.google.com/store/apps/details?id=com.crocusgames.destinyinventorymanager&hl=en_US&gl=US))

**Comment by BlackjackMKV** [comment]
Initially I thought it was one of my adblockers/anti-trackers and so on, but I have since set up DIM as trusted for all of those as well as setting it up to be excluded by my other scripts and addons such as my universal dark mode, so it's an unmodified, vanilla version of the app. Clearing cookies additionally did not seem to work.

**Comment by bhollis** [comment]
Could you fill out the full bug report template with all the info (dev logs, etc?)

**Comment by BlackjackMKV** [comment]
Ah, that means I'm going to need to play some more crucible, won't it. Dang. I hate Crucible. Yeah, I'll do that when I get a chance.

**Comment by bhollis** [comment]
Let us know if you're able to do that. Until then I'll have to assume that you're seeing stale cached data, which is unfortunately a known problem with the Bungie.net API that we're not able to fix.
