### ISSUE TITLE
Rotate inventory between characters

### ISSUE THREAD

**Issue by broady** [DestinyItemManager/DIM#6632]
**Proposed change**

Rotate equipped weapons between characters.

**How does this fit into your workflow?**

Complete raid on one character. Change to next character to run the raid again. Want same weapon loadout. Easier to move them all than to drag one by one.

**Comment by delphiactual** [comment]
Is:weapon is:equipped is:in(left|right|mid)char -> char drop-down to xfer to `equip loadout`

**Comment by bhollis** [comment]
Or just make a loadout
