### ISSUE TITLE
Weapon-only loadouts

### ISSUE THREAD

**Issue by broady** [DestinyItemManager/DIM#6633]
**Proposed change**

Loadouts of weapons that can be applied across all characters.

**How does this fit into your workflow?**

Create different weapon loadouts, for example a "PVP" loadout would equip PVP rolled hand cannon, shotgun, sniper, etc.
"DSC" loadout would equip xeno, lament, etc.

**Comment by delphiactual** [comment]
Already possiblt

**Comment by bhollis** [comment]
https://destinyitemmanager.fandom.com/wiki/Loadouts

**Comment by broady** [comment]
Thanks!!!
