### ISSUE TITLE
Improve documentation for is:dupelower search

### ISSUE THREAD

**Issue by DHager** [DestinyItemManager/DIM#6646]
**Version:** Version 6.59.0 (release), built on 4/4/2021, 7:11:54 PM

**Reproduction**: 

1. Identify a set of weapons or armors where you have multiple items (using `count:>1` or `is:dupe`)  and where each of those items are all the same power-level. 
2. Search using `is:dupelower`
3. Within the set of interest, you will see see that one single item (apparently arbitrary) is highlighted.

**Expectation:**  *None* of those items should be highlighted, based on the filter-name and its description:

> Duplicate items, including reissues, that are not the highest power dupe.

When only a single power-band exists, *all* of the duplicates are the "highest" power, and therefore none should be highlighted. Conversely, the opposite `not:dupelower` should highlight them all.

**Comment by DHager** [comment]
The logic seems to be here:  https://github.com/DestinyItemManager/DIM/blob/a0c03a594c8d30b4839fd3580950f5257a3f3ee8/src/app/search/search-filters/dupes.tsx#L37-L50

I feel that this logic does not match the user-facing description.

**Comment by bhollis** [comment]
It's maybe a bit much to say it "breaks" - I believe the original purpose of this filter was to help you find dupes that you could be OK with getting rid of - thus, if you have a bunch of items at the same power, it picks one to "keep" and marks the rest as "dupelower".

What workflow are you attempting which would be helped by the stricter definition where none of the items at the same, maximum power are highlighted?

**Comment by DHager** [comment]
Well, it doesn't match the described behavior at any rate. 

As for an example, suppose Iron Banner is coming up and I have some infusion-fuel. I wish to find out what models of exotic armor I have where *not even one* copy is already at the power-cap: `is:gauntlets is:exotic power:<1310 not:dupelower`

I would expect this search to show me items that match the ANDed criteria of:

* Are gauntlets
* Are exotic
* Are below the power-cap
* Are the highest power among similar models (whether individually or tied)

**Comment by bhollis** [comment]
As this is one of our oldest special filters, I'm not inclined to change its behavior. I'll take applications for the name of a different filter that does what you suggest, and in the meantime this issue can be to fix the documentation to be more explicit.
