### ISSUE TITLE
Filter condition for items usable in glimmer-only infusion

### ISSUE THREAD

**Issue by DHager** [DestinyItemManager/DIM#6647]
**Proposal:** A new filter condition (e.g. `is:glimmerinfusable`) to help players more easily make infuse-or-shard decisions.

**Example scenario:** I have a bunch of items already marked as `tag:junk` due to individually disappointing perks or stats, but before dismantling them I want to ensure that I didn't miss a convenient opportunity to use one for a glimmer-based infusion, which would allow me to cheaply bring up the power of some gear in my vault. 

I search for `tag:junk is:glimmerinfusable`. I see that I have a power-1300 Night Watch highlighted. At this point I trigger the existing infuse-button workflow, and see that it can be infused into a power-1250 Night Watch, and I transfer both items to complete the process in-game.

**Mechanics:** The condition is true for any item if one or more "dupes" exists at a lower power level.  While similar logic exists with the Infuse button (#3297), I have a suspicion this feature may require a different algorithm to efficiently scan the whole vault. 

**Can you already do this?:** No, the `is:dupelower` filter seems promising, but will not work except for edge-cases where all items fall into only two power-levels. For example, suppose you have four dupes with strictly descending power levels, `A>B>C`.  The new filter `is:glimmerinfusable` will select `[A,B]` as possible fuel for infusion, whereas `not:dupelower` will only find `[A]`.

**Comment by bhollis** [comment]
Linking #6262 because it might also be worthwhile for us to have a notification when you mark something as Junk/Infuse that says "OK but you *could* infuse this into something for glimmer"
