### ISSUE TITLE
Comparing a non-adept weapon should also compare the adept version

### ISSUE THREAD

**Issue by thomaskchan** [DestinyItemManager/DIM#6649]
**What version of DIM are you using?**
Version 6.59.1.1000358 (beta), built on 4/5/2021, 6:54:25 AM

**What Browser and OS are you using?**
Chrome on MacOS

**Describe the bug and how to make it happen**
If you compare one of the non-adept weapons that have adept versions (Palindrome, SWARM, Shadow Price), it also pulls in the adept version in the comparison, which is nice.  However, if you do the same compare starting with the adept version of the weapon, it does not pull in the non-adept versions.

I would prefer that it pulls in both adept and non-adept versions if you start the comparison from either version.

**Comment by bhollis** [comment]
Yeah that's because behind the scenes it's just a search for the name, and in one case the name is a subset of the other name.

**Comment by nev-r** [comment]
ah i was wondering why.
if there's some intrinsic link we can find, i am ok to do this, but i suspect they are just fully different items and we get into localized string processing.. maybe a d2ai job.... :shrug:

**Comment by bhollis** [comment]
Yeah best you could do is to generate a table of the " (Adept)" string in each language to strip it off for comparison. But then you'd need to make a special name search command too.

**Comment by delphiactual** [comment]
don't need d2ai just make add an i18n value AdeptString: " (Adept)", no table needed, and only needs pulled from manifest once by me, and can be hidden from the translation team entirely. working on the i18n keys now...

**Comment by bhollis** [comment]
You'd still need a special "namewithoutadept:" search filter though

**Comment by bhollis** [comment]
Or I suppose you could just strip it from the input, duh

**Comment by delphiactual** [comment]
table for my future self
lang code | i18n
---|---------
en | (Adept)
fr | (expert)
es | (experto)
es-MX | ???
de | (Meister)
it | (affinata)
ja | 新・
pt-BR | (Adepto)
ru | (адепт) 
pl | (adept)
ko | (숙련자)
zh-CHT | （精通）
zh-CHS | （专家）
