### ISSUE TITLE
Slow calls to Advisor API

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#665]
The addition of three more API calls for every refresh seems to slow things down quite a bit:

<img width="1429" alt="screen shot 2016-07-07 at 11 24 19 pm" src="https://cloud.githubusercontent.com/assets/313208/16679197/85b0be44-449a-11e6-8cfb-5a8e6f71ee55.png">

Maybe we could do those calls truly async, rather than ganging them all together into one promise?

**Comment by SunburnedGoose** [comment]
After they are moved to their own promise, they are expensive call to have to make often.  Long term fix would be to move bounties and quests off the items page.
