### ISSUE TITLE
Individual stat ratings gone?

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#666]
https://www.reddit.com/r/DestinyItemManager/comments/4rtdkd/individual_stat_quality/

I didn't think we removed this...

**Comment by bhollis** [comment]
Maybe it got lost in all the changes with the popup header, somehow?

**Comment by bhollis** [comment]
Thanks! Good catch! I'm sorry I missed that.

**Comment by kyleshay** [comment]
no prob. happy it was an easy fix! :)
