### ISSUE TITLE
Support Choice for Weapon Roll Viewer

### ISSUE THREAD

**Issue by abhipatel** [DestinyItemManager/DIM#6673]
**Proposed Change**
Support choice on weapon viewers when clicking on the weapon name.

**Example**
Open d2gunsmith instead of destiny tracker based on user settings.

**Details**
It looks like the URLs for both destinytracker and d2gunsmith are based on weapon ID. So, this should be a fairly small change. We could support a default list of sites in settings to keep control over URL definition. The other option is to allow users to define the weapon view URL but this exposes the tool to more error and it doesn't look like the settings support custom setups. So, happy not to include this last custom option in the PR.

**Questions**
Is it OK to link DIM to other tools or does there have to be an agreement between both tool owners? We don't want to add unexpected traffic to other tool services if they aren't ready for it or agreed this is ok.

_Happy to work on this feature if people would find it useful._

**Comment by nev-r** [comment]
https://github.com/DestinyItemManager/DIM/issues/6196
