### ISSUE TITLE
Loadout sheet - mod editor - Armor Mods picker empty

### ISSUE THREAD

**Issue by nev-r** [DestinyItemManager/DIM#6674]
If there's no armor in the loadout, clicking `(+) Armor Mods` confusingly comes up with the mod picker but 0 mods listed/searchable. Adding an armor, or even adding then removing an armor, seems to populate the mods.

Not technically wrong, that no armor mods can be applied, but I noticed they aren't filtered to the available slots anyway, so maybe this wasn't the intention? Regardless, the behavior was a bit confusing to me.
Populating mods regardless, an error notification, or even just not popping up the picker, all seem like valid options.

**Comment by ryan-rushton** [comment]
Yeah that's a bug, it should be pulling mods from the users entire inventory at the moment. I was in fact going to convert it so you can only pull mods for items in the loadout but that isn't done yet.

**Comment by ryan-rushton** [comment]
Figured it out, it's because there is no class selected. If you choose a class to be something other than Any you get mods.
