### ISSUE TITLE
Cache busting file names for assets.

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#668]
We're getting rendering issues from users because the CSS files are stale.  They have to clear their cache, or in some cases, reinstall DIM.  

Apply some cache busting solution to the JS/CSS/HTML files that we resolve locally.

**Comment by kyleshay** [comment]
would adding `?v=$DIM_VERSION"` to `<link rel="stylesheet" href="styles/main.css>` be enough?

**Comment by bhollis** [comment]
Very likely!

**Comment by kyleshay** [comment]
this is v3.8.1

https://github.com/DestinyItemManager/DIM/commit/d9792386968bf1086833f390c2555c76f26e3395#diff-b9707fe88797285e93483456d1389b61L24

will keep an eye out for future reports/issues
