### ISSUE TITLE
Extra Tag Category: PvP

### ISSUE THREAD

**Issue by CyberBlaed** [DestinyItemManager/DIM#6683]
**Proposed change**
For the organisation of DIM it would be extra helpful to have a PvP weapons category, at the moment it is just become difficult after making notes on all my armour and weapons so the search can find them and its become disorganised trying my best to keep it organised with what I have.

Loadout is not a viable alternative as it doesn't allow change mid mission.

**How does this fit into your workflow?**
It would allow me to easily see, select, categorise my PvP weapons to the side (liked the archived ones without being blanked out) and avoid mish-mashing them among all my PvE weapons of choice and struggling to visually find them.

**Comment by kyleshay** [comment]
We're currently working to enhance the notes section to help with organization, [check this help article for now](https://destinyitemmanager.fandom.com/wiki/Tags_and_Notes#Using_notes_as_tags)

[We go in to reasons why we won't add more tags here](https://github.com/DestinyItemManager/DIM/wiki/Frequently-Requested-Features#add-more-tag-values).

Dupe  #5427
