### ISSUE TITLE
Add Item Year to Exports

### ISSUE THREAD

**Issue by knuxem95** [DestinyItemManager/DIM#671]
Loving the addition of the built-in weapon and armor exports to DIM. One suggestion/request I have is to add the item year to the csv exports. I used to use a homemade script to grab item information and used the year of an item for my Excel based collection workbook. Having the year (1 or 2) information makes it possible to track a wider array of duplicate items (exotics) that have year 1 and 2 variants. Thanks!

**Comment by kyleshay** [comment]
Should be simple enough! We'll have that in 3.8.2
