### ISSUE TITLE
socket categories still store indexes for sockets that were skipped

### ISSUE THREAD

**Issue by nev-r** [DestinyItemManager/DIM#6717]
need to remove or account for these indexes
![image](https://user-images.githubusercontent.com/68782081/116013164-860b9f80-a5e3-11eb-8523-277296a53877.png)

**Comment by nev-r** [comment]
@bhollis poke

**Comment by bhollis** [comment]
Yeah that's a really interesting one. I had imagined that the socketIndexes would be "raw" and we'd just deal with the fact that some sockets wouldn't be found. But I guess we don't account for empty categories well when displaying.

**Comment by bhollis** [comment]
I think I actually just fixed this to show the mod sockets.
