### ISSUE TITLE
Stat Percentage Calculation Off For Artifacts

### ISSUE THREAD

**Issue by jbarnett-r7** [DestinyItemManager/DIM#672]
The stat calculations for percent of max on artifacts seems to be a little off. I have 3 artifacts that are reporting at 100+%. 

<img width="327" alt="screen shot 2016-07-08 at 11 55 21 am" src="https://cloud.githubusercontent.com/assets/12236529/16695151/b54e79d4-4503-11e6-9d22-c0c7a2771dd5.png">
<img width="325" alt="screen shot 2016-07-08 at 11 55 30 am" src="https://cloud.githubusercontent.com/assets/12236529/16695156/bb0586a6-4503-11e6-947e-2cd6e2800a28.png">
<img width="325" alt="screen shot 2016-07-08 at 11 55 38 am" src="https://cloud.githubusercontent.com/assets/12236529/16695164/c53cd58e-4503-11e6-9eb0-0209664cf404.png">

Other item managers like Tower Ghost and Ishtar Commander show different results.

<img width="267" alt="screen shot 2016-07-08 at 11 58 46 am" src="https://cloud.githubusercontent.com/assets/12236529/16695169/cb8258d8-4503-11e6-864e-50fbcaa372b1.png">

I THINK the stat calculation is only off for the discipline roll on the artifacts, but I don't have 100% evidence. Also, I don't know if this is affecting all classes or Titan only.

**Comment by kyleshay** [comment]
int/dis artifacts are bugged in the game itself to go "over 100%"

more info in this issue:
https://github.com/DestinyItemManager/DIM/pull/555

not exactly sure what we ant to do.
