### ISSUE TITLE
Landscape on iPhone X has grey corners

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#6721]
Apparently. Ryan showed me a screenshot.

**Comment by ryan-rushton** [comment]
iPhone XR in landscape with the installed app (beta).

![image](https://user-images.githubusercontent.com/7344652/116685563-e8a2d800-a9f5-11eb-82ff-ddf89b5082f8.png)

**Comment by ryan-rushton** [comment]
Can confirm this is fixed
