### ISSUE TITLE
Sort by recently acquired in Organizer

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#6722]
It'd be nice for triage

**Comment by RocheM** [comment]
Can we use the ItemID to sort by recency?  It seems like this is being done in filters.ts.

If that's the only way, I can think of two ways to accomplish it:

1. Add a button to sort by recency on the top bar (next to tag, move etc.). Probably the best in terms of User understanding, but it goes against the design of the rest of the page. Using Columns to sort is the general pattern.

2. Expose the ItemID (or an abstraction of it) as an additional Column. This would fit the pattern of using columns to sort, but would be pretty bad UX as 6917529362922309753 != recency for most. We could abstract it with a "recency" score, 1 being most recent - higher being older. But that'd add a little complexity.

Open to thoughts, I might give this one a shot this week.

**Comment by bhollis** [comment]
Yeah I think making it a column is best. @nev-r had some ideas about using historical data to build a mapping of instance ID to time. D2Checklist makes it a sortable column but just doesn't show anything in the cells.

**Comment by RocheM** [comment]
Think I'll work on a sortable blank column to start, should be pretty easy. Then I'll work into how to best transform it into something more human readable

**Comment by RocheM** [comment]
So I got it working with blank values, I think it works pretty well. It's particularly interesting to see the oldest items I've acquired (I'll never share you Redrix's Claymore ❤️).

Still thinking about the best way to represent a value for "Recency" though. I was thinking I might maintain a sorted list of IDs and the "recency" value could be the index (+ 1) of the item's position in that list.

Where Redrix's Claymore is more oldest it'd have a "recency" value of 1 in this case.

I'm new to this codebase (and typescript in general) so I'll need to toy around with it. Not sure where best to calculate that sorted list.

**Comment by RocheM** [comment]
So I got what I described above working, below is a screenshot of how it looks in action. If it looks good I'll stick up a PR sometime tomorrow.

![SortByRecency](https://user-images.githubusercontent.com/6667803/121606674-82729180-ca46-11eb-89ef-ffcd5efc4ed3.png)

**Comment by RocheM** [comment]
Created a PR with these changes, curious to hear any feedback!
