### ISSUE TITLE
Exotic missing from optimizer

### ISSUE THREAD

**Issue by somerandomahole** [DestinyItemManager/DIM#6733]
**What version of DIM are you using?**
Find the version in "About DIM" from the menu (the button with three bars on the upper left of the screen). Is the DIM icon orange, or blue?

Orange. Version 6.63.0

**What Browser and OS are you using?**
It helps to know what type of browser and what version you're using. Have you installed DIM as an app through Chrome or Safari?

chrome

**Describe the bug and how to make it happen**
Tell us what's wrong. A great format for bug reports is "I did X, and I expected Y, but instead Z happened." If it helps illustrate the issue, please add screenshots to help explain your problem.

I have Eye of another world equipped, but cannot choose this item in the loadout optimizer. 

**Include devtools console logs**
If you can, open the devtools console (ctrl+shift+J on PC and cmd+option+J on Mac) and paste what you see in the window that pops up:

Posting this on mobile. I can post logs if asked

```
Paste console logs here
```

**Comment by delphiactual** [comment]
![image](https://user-images.githubusercontent.com/4798491/117462442-ea93fc00-af0b-11eb-8cfd-c5565eff7e5a.png)

**Comment by delphiactual** [comment]
is yours by chance an `armor 1.0`?

**Comment by somerandomahole** [comment]
Just got home and of course the servers are down. There is a pretty high chance that it is an armor 1.0 helm. I wasn’t aware that would matter

**Comment by somerandomahole** [comment]
Yeah, armor 1.0. Reacquired from collection and works fine. Thanks
