### ISSUE TITLE
(Beta) select exotic in LO issue. 

### ISSUE THREAD

**Issue by inexorableAce** [DestinyItemManager/DIM#6742]
**What version of DIM are you using?**
Beta 

**What Browser and OS are you using?**
Happens on everything I’ve tried. Chrome desktop and mobile. iOS safari / install. 

**Describe the bug and how to make it happen**
When using the new select exotic option making any selection yields zero results. No matter what any other setting is. 
![FE8998EF-E27D-4C7B-B7CF-C10A5ACFD4C2](https://user-images.githubusercontent.com/29002828/117560667-d19b6000-b05d-11eb-808b-9a6d92541d28.jpeg)

**Include devtools console logs**
No errors

**Comment by ryan-rushton** [comment]
@inexorableAce where did this one come from? I can't reproduce it myself, beta is working fine. Is it possible its the old armour 1.0 issue?

**Comment by inexorableAce** [comment]
Nope it's literally every single exotic I try. I can even lock a single exotic of the same name fine just can't use the exotic picker. 

here are the logs before selecting anything
```[app] DIM v6.63.0.1000447 (beta) - Please report any errors to https://www.github.com/DestinyItemManager/DIM/issues
instrument.ts:129 [dim sync] globalSettings {dimApiEnabled: true, destinyProfileMinimumRefreshInterval: 15, destinyProfileRefreshInterval: 30, autoRefresh: false, refreshProfileOnVisible: true, …}
log.ts:44 Load manifest: 1543.801025390625 ms
instrument.ts:129 [dim sync] Saving profile data to IDB
log.ts:44 Process inventory: 76.45703125 ms
log.ts:44 Inventory state update: 82.777099609375 ms
157-ba5083.js:1 [loadout optimizer] found 200 stat mixes after processing 38808 stat combinations in 226.23500000918284 ms -  171538.4445307967 combos/s {numCantSlotMods: 0, numSkippedLowTier: 37432, numStatRangeExceeded: 0} {numInserted: 1376, numRejectedAfterInsert: 1176, numDoubleExotic: 0}
instrument.ts:129 [loadout optimizer] useProcess: worker time 307.95000004582107ms
instrument.ts:129 [loadout optimizer] useProcess 346.5200000209734ms
464-a29f67.js:2 [Violation] 'setTimeout' handler took 143ms```

and after selecting an exotic
```[loadout optimizer] useProcess: worker time 24.315000046044588ms
instrument.ts:129 [loadout optimizer] useProcess 34.045000036712736ms```

**Comment by inexorableAce** [comment]
also for the record, 1.0 exotics don't even show up in the list. I only have one 1.0 exotic (ST0MP-EE5) and they aren't even an option to choose from in the select exotic menu. Which is good. 👍

**Comment by ryan-rushton** [comment]
Awesome, by the looks of that something is getting filtered down and sent to the process worker. Is this also happening on the main app?

**Comment by inexorableAce** [comment]
Now that it has the exotic picker, yes, same issue

**Comment by dwimmer** [comment]
The fact that you had numDoubleExotic=0 before selecting anything looks suspicious. That would imply you only have exotics in one slot. Is that true?

**Comment by inexorableAce** [comment]
No I have exotics available in every slot. 
![image](https://user-images.githubusercontent.com/29002828/117598243-6ad97d80-b115-11eb-9f49-87c4073e4565.png)

**Comment by inexorableAce** [comment]
oh... you know what I bet I just figured it out. It's the default search of `-tag:archive` isn't it?

**Comment by ryan-rushton** [comment]
yeah a search will mess with it

**Comment by dwimmer** [comment]
Yep that would do it. Try "-tag:archive or is:exotic"

**Comment by inexorableAce** [comment]
yup altering the search works... so no one is going to know that... I do since I'm kinda in the know... but I'd be willing to wager not many people know the archive function works by defaulting a search when none exist.

**Comment by dwimmer** [comment]
I guess it depends on what archive is intended to mean. I could see it being exactly what some people would want.

**Comment by inexorableAce** [comment]
very true, but they can always search for that and know that;s what it's doing opposed to someone seeing nothing in the search bar and having no idea that it's doing that :P

**Comment by inexorableAce** [comment]
Yeah, I get why it is the way it is. but yeah for those not in the know it's a little odd... but again I am using the tag in an unconventional way. To be fair on the inventory page exotics are just not important much of the time... you set one or two and that's that. So it works well for me to keep them to the bottom and out of the way...

**Comment by ryan-rushton** [comment]
Yeah ok, good to know for future reference anyway.
