### ISSUE TITLE
comparing deleted item error

### ISSUE THREAD

**Issue by nev-r** [DestinyItemManager/DIM#6744]
some version of this bug still exists i guess
![image](https://user-images.githubusercontent.com/68782081/117567052-01069880-b06f-11eb-8034-52c7eda60d4f.png)

**Comment by RocheM** [comment]
Looks like this has been addressed: Issue #6750 / PR #6778

Can this be closed as a duplicate?

@nev-r  / @bhollis  / @delphiactual

**Comment by bhollis** [comment]
I think so. Thanks for checking :-)
