### ISSUE TITLE
Notch covers checkboxes when scrolled over

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#6748]
![image](https://user-images.githubusercontent.com/313208/117765141-63cc7100-b1e2-11eb-8aae-284e1d6512b3.png)

Screenshot doesn't show it but there's a notch there

**Comment by thebtm** [comment]
If you highlight what your trying to capture then push <Win Key> + Shift + S, it should also capture the mouse over part when your mouse is over it as long as your mouse doesn't move when you push that key combination.

**Comment by bhollis** [comment]
This is on an iPhone...

**Comment by thebtm** [comment]
My mistake then, I thought it was the desktop app.
