### ISSUE TITLE
Random items moving whenever I transfer anything

### ISSUE THREAD

**Issue by dbh133** [DestinyItemManager/DIM#6753]
**What version of DIM are you using?**
Version 6.64.1.1000457 (beta), built on 5/12/2021, 6:02:44 PM

**What Browser and OS are you using?**
Chrome

**Describe the bug and how to make it happen**
Any time I move equipment from my character to another character or the vault it pulls random items to replace it.

**Include devtools console logs**
If you can, open the devtools console (ctrl+shift+J on PC and cmd+option+J on Mac) and paste what you see in the window that pops up:

```
[move] User initiated move: 1 Ignition Code Kinetic to Human Warlock from Awoken Hunter
instrument.ts:129 [move] Move 1 Witherhoard Kinetic to Vault from Human Warlock
instrument.ts:129 [move] Try blind move of The Messenger to Awoken Hunter
instrument.ts:129 [move] Move 1 The Messenger Kinetic to Awoken Hunter from Vault
instrument.ts:129 [move] Move 1 Ignition Code Kinetic to Vault from Awoken Hunter
instrument.ts:129 [move] Resetting lock status of Ignition Code to false when moving to Vault to work around Bungie.net lock state bug
instrument.ts:129 [move] Move 1 Ignition Code Kinetic to Human Warlock from Vault
```

**Comment by delphiactual** [comment]
Is your vault close to 500/500?

**Comment by bhollis** [comment]
For reference, https://github.com/DestinyItemManager/DIM/wiki/Frequently-Requested-Features#disable-smart-moves

**Comment by dbh133** [comment]
Holy crap I feel stupid now my vault was at 499/500 didn't know I had that much junk!  Thank you!
