### ISSUE TITLE
Artifact name and image not updated (when I see its contents)

### ISSUE THREAD

**Issue by Bagny89** [DestinyItemManager/DIM#6754]
**What version of DIM are you using?**
Icon Blue, i use DIM 6.64.1

**What Browser and OS are you using?**
I use Google Chrome last version (90.0.4430.212 64bit)

**Describe the bug and how to make it happen**

When I click on "**Preview artefact content**", the right page opens (with the relevant mods), but the name and image are still from the very old "Eye of the Gatekeeper" artefact.
![image](https://user-images.githubusercontent.com/33706352/118118428-356eb180-b3ed-11eb-8a95-0a772b35190e.png)

Name and image that in the menu "Inventory" correspond to the current artefact (from season 14):
![image](https://user-images.githubusercontent.com/33706352/118118602-71097b80-b3ed-11eb-89df-062e805aedd7.png)

I hope we can change that. It would be more credible. Thank you

**Comment by delphiactual** [comment]
Known API issue https://github.com/Bungie-net/api/issues/1286
