### ISSUE TITLE
Gambit/Crucible ranks missing

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#6755]
Looks like the hashes changed again?

**Comment by bhollis** [comment]
Yeah totally

**Comment by delphiactual** [comment]
It actually looks like they consolidated them

https://archive.destiny.report/version/eae0152b-b870-4f29-8b7f-75b0fef50968/DestinyProgressionDefinition

**Comment by bhollis** [comment]
nice

**Comment by delphiactual** [comment]
Cannot test that this works as I am not gaining any Valor currently
