### ISSUE TITLE
Logging into DIM shows my D1 inventory

### ISSUE THREAD

**Issue by mmg68** [DestinyItemManager/DIM#6756]
When accessing DIM that was already open, I got a Bungie is having trouble connecting error. I closed tab and tried to login again and now I'm only seeing my Destiny 1 content. 

I'm on DIM: Version 6.64.1 (release), built on 5/11/2021, 3:15:52 PM

I'm using Firefox 88.0.1 on a Mac

Just experienced this when trying to login to DIM

Here is the console log:
Google Analytics is being shimmed by Firefox. See https://bugzilla.mozilla.org/show_bug.cgi?id=1493602 for details. sandbox eval code:1:9
Failed to register/update a ServiceWorker for scope ‘https://app.destinyitemmanager.com/’: Storage access is restricted in this context due to user settings or private browsing mode. main-6e32f9.js:1:97774
[SW] Unable to register service worker. DOMException: The operation is insecure. 464-a29f67.js:2:95495
[app] DIM v6.64.1 (release) - Please report any errors to https://www.github.com/DestinyItemManager/DIM/issues 464-a29f67.js:2:95495
[dim sync] globalSettings 
Object { dimApiEnabled: true, destinyProfileMinimumRefreshInterval: 15, destinyProfileRefreshInterval: 30, autoRefresh: false, refreshProfileOnVisible: true, bustProfileCacheOnHardRefresh: false, dimProfileMinimumRefreshInterval: 300, showIssueBanner: false }
464-a29f67.js:2:95495
The resource at “https://platform.twitter.com/widgets.js” was blocked because content blocking is enabled. inventory
[dim sync] Saving profile data to IDB 464-a29f67.js:2:95495
Content Security Policy: Ignoring “'unsafe-inline'” within script-src or style-src: nonce-source or hash-source specified
Content Security Policy: This site (https://opencollective.com) has a Report-Only policy without a report URI. CSP will not block and cannot report violations of this policy.
Partitioned cookie or storage access was provided to “<URL>{%22h2%22:{%22color%22:%22white%22}}” because it is loaded in the third-party context and dynamic state partitioning is enabled. 2
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://app.destinyitemmanager.com/main-63e20c.css
Source Map URL: main-63e20c.css.map
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://app.destinyitemmanager.com/234-6dc561.css
Source Map URL: 234-6dc561.css.map
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://app.destinyitemmanager.com/130-c44050.js
Source Map URL: 130-c44050.js.map
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://app.destinyitemmanager.com/589-32d279.js
Source Map URL: 589-32d279.js.map
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://app.destinyitemmanager.com/210-a5c0a2.js
Source Map URL: 210-a5c0a2.js.map
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://app.destinyitemmanager.com/browsercheck-db9d12.js
Source Map URL: browsercheck-db9d12.js.map
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://app.destinyitemmanager.com/twitter-a65c8e.js
Source Map URL: twitter-a65c8e.js.map
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://app.destinyitemmanager.com/runtime-115fb3.js
Source Map URL: runtime-115fb3.js.map
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://app.destinyitemmanager.com/6-742bab.js
Source Map URL: 6-742bab.js.map
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://app.destinyitemmanager.com/64-e06471.js
Source Map URL: 64-e06471.js.map
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://app.destinyitemmanager.com/617-aeb15b.js
Source Map URL: 617-aeb15b.js.map
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://app.destinyitemmanager.com/inventory-3f8725.js
Source Map URL: inventory-3f8725.js.map
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://app.destinyitemmanager.com/464-a29f67.js
Source Map URL: 464-a29f67.js.map
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://app.destinyitemmanager.com/main-6e32f9.js
Source Map URL: main-6e32f9.js.map
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://app.destinyitemmanager.com/620-f9aa1b.js
Source Map URL: 620-f9aa1b.js.map
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://app.destinyitemmanager.com/464-a29f67.js
Source Map URL: 464-a29f67.js.map
[dim sync] Saving profile data to IDB 464-a29f67.js:2:95495
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://app.destinyitemmanager.com/234-6dc561.css
Source Map URL: 234-6dc561.css.map
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://app.destinyitemmanager.com/main-63e20c.css
Source Map URL: main-63e20c.css.map
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://app.destinyitemmanager.com/464-a29f67.js
Source Map URL: 464-a29f67.js.map
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://app.destinyitemmanager.com/main-6e32f9.js
Source Map URL: main-6e32f9.js.map

**Comment by delphiactual** [comment]
https://twitter.com/BungieHelp/status/1392943984725565440

![image](https://user-images.githubusercontent.com/4798491/118188462-ab7b1480-b3fd-11eb-9421-64c0efcb7f55.png)
