### ISSUE TITLE
Cannot move the new gun CHROMA RUSH that another character has equipped.

### ISSUE THREAD

**Issue by eTepidWater** [DestinyItemManager/DIM#6757]
I'm using DIM version 6.64.1 and the icon is Blue.

I'm using Chrome on Windows 7 (Happens on Windows 10 as well)

When I try to move CHROMA RUSH from my Warlock to either other character it doesn't let me and says "Bungie.net message: This item cannot be equipped." Every other equipped weapon seems to work fine and I don't have another chroma rush to test unfortunately. 

instrument.ts:129 [move] error moving item Chroma Rush to Exo Hunter DimError: Bungie.net message: This item cannot be equipped.
    at https://beta.destinyitemmanager.com/main-b38b3e.js:1:116168
    at https://beta.destinyitemmanager.com/main-b38b3e.js:1:116378
    at async https://beta.destinyitemmanager.com/main-b38b3e.js:1:219696
    at async https://beta.destinyitemmanager.com/main-b38b3e.js:1:226143
    at async https://beta.destinyitemmanager.com/main-b38b3e.js:1:219998
    at async https://beta.destinyitemmanager.com/main-b38b3e.js:1:225984

**Comment by bhollis** [comment]
Can you move it in the D2 Companion App?

**Comment by eTepidWater** [comment]
> Can you move it in the D2 Companion App?

Unfortunately, I've since manually moved it which fixed the bug completely. Sorry about that.

**Comment by delphiactual** [comment]
Did you possibly logout from a loadout locked activity with returning to orbit?

**Comment by eTepidWater** [comment]
Yes actually, I'm pretty sure I went to "switch character" right after completing a legendary lost sector before it kicked me. Now that you mention that, I think I had trouble taking a different weapon off that same character.

**Comment by bhollis** [comment]
Maybe we should load activities to try and detect this... or I wonder if there's any other indication that your inventory is locked.
