### ISSUE TITLE
Restrict to modern Chrome

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#676]
Apparently some Linux users (and maybe others?) are stuck on old versions of Chromium/Chrome that aren't auto-updating. We should either force a minimum Chrome version in the manifest or give up on using ES6 directly and use Babel.

**Comment by kyleshay** [comment]
for reference the key/val in the `manifest.json` is `"minimum_chrome_version": "versionString"`

**Comment by kyleshay** [comment]
fixed in #691
