### ISSUE TITLE
Lost Item

### ISSUE THREAD

**Issue by GaDeLizvy** [DestinyItemManager/DIM#6762]
Good afternoon. Today I was transferring items from my Warlock to my Hunter and one of the items I transferred was my god roll, Gnawing Hunger. After I transferred it, it never popped up in my inventory. I didn't delete it or anything, it just disappeared. I tried resetting my DIM however this did not work as I was completely gone from my vault and all 3 of my characters. I also tried resetting Destiny and this didn't work either. If I could get some help I would really appreciate it as it is the gun I use the most. Thanks.

**Comment by delphiactual** [comment]
Lock any item in DIM, press the refresh button, in the search bar start typing gnawing hunger

**Comment by delphiactual** [comment]
https://destinyitemmanager.fandom.com/wiki/Category:FAQ#DIM_deleted_my_item.21
