### ISSUE TITLE
Restore the ability to run multiple DIM instances

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#677]
https://www.reddit.com/r/DestinyItemManager/comments/4rteq2/multiple_tabs_of_dim/

Another person said they use this to log into two characters at once (one in incognito).

**Comment by kyleshay** [comment]
👍 should be an easy enough patch. can't please everyone :/

**Comment by bhollis** [comment]
It's been a long time since this was gone - do we want to give up on multi-DIM?

**Comment by kyleshay** [comment]
I think it was actually recently fixed: https://github.com/DestinyItemManager/DIM/pull/1081

**Comment by delphiactual** [comment]
One Caveat: if they want multi-instance they must run DIM in incognito.
