### ISSUE TITLE
закройте доступ для моего акк на DIM

### ISSUE THREAD

**Issue by LemonDic** [DestinyItemManager/DIM#6775]
**What version of DIM are you using?**
Find the version in "About DIM" from the menu (the button with three bars on the upper left of the screen). Is the DIM icon orange, or blue?

**What Browser and OS are you using?**
It helps to know what type of browser and what version you're using. Have you installed DIM as an app through Chrome or Safari?

**Describe the bug and how to make it happen**
Tell us what's wrong. A great format for bug reports is "I did X, and I expected Y, but instead Z happened." If it helps illustrate the issue, please add screenshots to help explain your problem.

**Include devtools console logs**
If you can, open the devtools console (ctrl+shift+J on PC and cmd+option+J on Mac) and paste what you see in the window that pops up:

```
Paste console logs here
```

**Comment by delphiactual** [comment]
https://translate.google.com/?sl=auto&tl=en&text=%D0%B7%D0%B0%D0%BA%D1%80%D0%BE%D0%B9%D1%82%D0%B5%20%D0%B4%D0%BE%D1%81%D1%82%D1%83%D0%BF%20%D0%B4%D0%BB%D1%8F%20%D0%BC%D0%BE%D0%B5%D0%B3%D0%BE%20%D0%B0%D0%BA%D0%BA%20%D0%BD%D0%B0%20DIM&op=translate

There is no DIM account, you can clear your DIM Sync data yourself. If you mean the link between bungie.net and DIM you must revoke that yourself on bungie.net.
