### ISSUE TITLE
Problem with progress page....Invalid hash-153950757...where bounties should be. See picture below in comments.

### ISSUE THREAD

**Issue by Bhold353** [DestinyItemManager/DIM#6787]
**What version of DIM are you using?**
Find the version in "About DIM" from the menu (the button with three bars on the upper left of the screen). Is the DIM icon orange, or blue?

**What Browser and OS are you using?**
It helps to know what type of browser and what version you're using. Have you installed DIM as an app through Chrome or Safari?

**Describe the bug and how to make it happen**
Tell us what's wrong. A great format for bug reports is "I did X, and I expected Y, but instead Z happened." If it helps illustrate the issue, please add screenshots to help explain your problem.

**Include devtools console logs**
If you can, open the devtools console (ctrl+shift+J on PC and cmd+option+J on Mac) and paste what you see in the window that pops up:

```
Paste console logs here
```

**Comment by Bhold353** [comment]
![1BAFB882-7FC5-4488-8D84-E36EDD023A7F](https://user-images.githubusercontent.com/58037251/119668404-27fdf200-be05-11eb-8c18-8ac1b1c1396a.jpeg)

**Comment by Bhold353** [comment]
Why is my problem closed? It is still valid.

**Comment by delphiactual** [comment]
go to https//:beta.destinyitemmanager.com and verify and then I can cut a patch to `app`, it is closed because it was addressed in #6788 which is currently available in beta

**Comment by Bhold353** [comment]
Fixed in Safari. Can you fix in Google Chrome?

**Comment by Bhold353** [comment]
Thanks...fixed in both. Cheers.
