### ISSUE TITLE
Some SoS Prismatic Lenses weapon icons have a malformed title text

### ISSUE THREAD

**Issue by uberfuzzy** [DestinyItemManager/DIM#6791]
**What version of DIM are you using?**
Noticed in Version 6.66.2 (release), confirmed in Version 6.66.2.1000496 (beta), screenshots taken on beta.

**What Browser and OS are you using?**
Cross verified in Chrome91/windows, but normally DIM is run "as an app" which is technically Edge based.

**Describe the bug and how to make it happen**
Triumphs -> Season Splicer -> Splicer Mastery -> Prismatic Lenses.

The Triumphs that have weapons sometimes have useful `title` text, like `[Auto Rifle]`, but some(many?) of them have a single `` as the text.

![Screenshot 2021-05-27 01 09 34](https://user-images.githubusercontent.com/1438723/119769807-28d86780-be89-11eb-8322-2bc3db5be792.png)

![Screenshot 2021-05-27 01 09 37](https://user-images.githubusercontent.com/1438723/119769811-2bd35800-be89-11eb-8f56-198ade810f98.png)

![image](https://user-images.githubusercontent.com/1438723/119769852-3f7ebe80-be89-11eb-8c5a-973f2308a8d6.png)

**Include devtools console logs**
If you can, open the devtools console (ctrl+shift+J on PC and cmd+option+J on Mac) and paste what you see in the window that pops up:

```
[dim sync] globalSettings {dimApiEnabled: true, destinyProfileMinimumRefreshInterval: 15, destinyProfileRefreshInterval: 30, autoRefresh: false, refreshProfileOnVisible: true, …}
instrument.ts:129 [app] DIM v6.66.2 (release) - Please report any errors to https://www.github.com/DestinyItemManager/DIM/issues
log.ts:44 Load manifest: 1503.707763671875 ms
instrument.ts:129 [dim sync] Saving profile data to IDB
log.ts:44 Process inventory: 119.84814453125 ms
log.ts:44 Inventory state update: 102.64306640625 ms
```

**Comment by delphiactual** [comment]
Dupe #6760
