### ISSUE TITLE
Dunemarchers do not show up in the Loadout Optimizer

### ISSUE THREAD

**Issue by DynamoPat** [DestinyItemManager/DIM#6807]
**What version of DIM are you using?**
Version 6.66.2.1000504 (beta), built on 5/30/2021, 10:51:09 AM

**What Browser and OS are you using?**
MS Edge Windows 10

**Describe the bug and how to make it happen**
Dunemarchers do not show up in the Loadout Optimizer.

**Comment by bhollis** [comment]
Are they armor 1.0?

**Comment by DynamoPat** [comment]
Yup, they were Armor 1.0, picked up the 2.0 version from collections and they're showing up now.
