### ISSUE TITLE
Calculate stats for Elemental Capacitor

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#6814]
This'll be somewhat tricky, and it won't mean anything in some contexts (LO, Organizer) but it maybe will stop people pointing it out?

Alternatively we could add a note.

**Comment by nev-r** [comment]
so, i thought that stuff was set as conditional, did the conditional checks break?

**Comment by delphiactual** [comment]
https://github.com/DestinyItemManager/DIM/pull/6387#issue-545953765 `except for elemental capacitor`

**Comment by ryan-rushton** [comment]
I never did elemental capacitor as we need to know which subclass is equipped and what weapons are currently equipped. I personally don't see any value in it but we could add it I suppose. I think it only really makes sense in loadouts and maybe on the main inventory screen.

**Comment by nev-r** [comment]
i don't care if it's calculated but i would like them to default off because they completely blow out stat comparison

**Comment by ryan-rushton** [comment]
I kinda figured it would default to off anyways. If it doesn't we probably need a check around conditional stats when looking at perks.
