### ISSUE TITLE
Find armor 1.0 exotics in the exotics picker (bring back armor 1.0 to LO)

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#6815]
You don't have to calculate the stats if you don't want to but we should probably allow LO to "find" armor 1.0 exotics so people stop getting confused. You could display them in red with a warning or something, but don't hide them.

**Comment by ryan-rushton** [comment]
Yeah ok, I might make them look disabled with a press tip about pulling a 2.0 version from collections. It will guide people to pull better stat rolls then.
