### ISSUE TITLE
Age:N, a search condition that handles a smaller scale than Season: and Year:

### ISSUE THREAD

**Issue by TMMania** [DestinyItemManager/DIM#6818]
Age:N

The value of N being the number of weeks or weekly resets since the item was released in the API, or something similar.

Trying to figuring out a way to include weapon Wishlists as an opt-in feature in my Vault Analyzer or as an alternative search. I'd like to make sure that weapons aren't filtered until ample time has passed to allow weapon recommenders to do their work and currently the smallest scale I can work with is "-season:current" which means I'm only filtering after the season has passed. 

An example: 'is:weapon -is:wishlist -age:<5' filtering weapons that are not wishlist'ed while ignoring weapons younger than 5 weeks.

**Comment by delphiactual** [comment]
Unfortunately `season` is not provided by Bungie and figured out by heuristics. This seems unnecessarily complex anyways, if the are holding rolls while waiting for wishlist one could simply:

`season:current is:wishlistdupe -is:wishlist`

**Comment by TMMania** [comment]
Alrighty, was unsure how practical this would be and wanted to shoot my shot. Feel free to close this if there is little to no momentum to this.

**Comment by nev-r** [comment]
doesn't this boil down to wanting a `haswishlist`

**Comment by 48klocs** [comment]
Sounds that way - #6538 tracks that.

**Comment by delphiactual** [comment]
closing in favor of issue mentioned above

**Comment by TMMania** [comment]
`haswishlist` will work, the rest of this comment is just my analysis on a time gate vs `haswishlist`.

The reason I wanted to utilize a time gate over something like `haswishlist` is that some recommendations are solidified more quickly which are the obviously great rolls, but there may still be good perk permutations that aren't added yet. I'm not 100% aware on the logistics of wishlists updates, but this is something I thought about if roll inclusion was staggered.
