### ISSUE TITLE
Better/Smarter Tracking of Analytics on the Settings Object.

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#683]
Lets try and read what people typically use as their custom settings in DIM. 

We should only track for people that actually open the settings (or if ANY of their settings are mismatched from all setting defaults) let's report out what their settings are. If they're just users who are unaware of the settings box all together, I suppose that might just be another issue.

This will help us learn about our users and help us control the settings in the app. 

We've learned that removing some options have had a negative effect, while others people don't even seem notice.

**Comment by bhollis** [comment]
Is there a good way to do this?
