### ISSUE TITLE
Xbox Series X/S Edge Browser

### ISSUE THREAD

**Issue by GMDGeek** [DestinyItemManager/DIM#6834]
**Proposed change**
Still reading through all the forums so if this is a duplicate request I apologize.  Will there be the ability to run DIM from the Series X/S Edge browser.  Many of my friends who DON'T have a PC but have a console are wanting to use the app and ask me about it all the time.  With GPUs limited and hardware extremely over MSRP a lot of people are starting to use the X/S as a PC due to mouse and keyboard compatibility.  

**How does this fit into your workflow?**
Ability to flip out of game (quick resume) and hit the EDGE browser would be a welcome flow.

**Comment by delphiactual** [comment]
What version of Edge is available on the Series X|S?

**Comment by bhollis** [comment]
This appears to only be available to Insiders / Xbox Alpha. Wait for it to be released, and then if it's a reasonably recent version of Edge (which it should be), DIM should work on it.

**Comment by GMDGeek** [comment]
Appreciate y'alls feedback. I'll share out with my community the news and
look forward to when it becomes available on X/S Edge Browser.
