### ISSUE TITLE
List loadout(s) in which item is present

### ISSUE THREAD

**Issue by jlj-ee** [DestinyItemManager/DIM#6835]
**Proposed change**
I would find it useful to be able to quickly see if an armor piece I have selected is already part of an existing loadout/build. This could be linked from the item details panel. This would be most useful when using the loadout optimizer, but ideally could be seen when selecting an item in the inventory screen as well. This feature would probably be less useful for weapons than it would be for armor.

**How does this fit into your workflow?**
Sometimes I may not want to include the same armor piece in multiple loadouts if there would be a clash in mods, appearance (especially with transmog), etc.

**Comment by delphiactual** [comment]
`is:inloadout`

**Comment by jlj-ee** [comment]
Cheers, I'm dumb. Thanks!
