### ISSUE TITLE
LoadoutBuilder.Nothing cannot be selected

### ISSUE THREAD

**Issue by rentalhost** [DestinyItemManager/DIM#6849]
Open the Loadout Builder, modify the new option to something else and try to back to "nothing". It will not works and the previous option will keep actived.

https://github.com/DestinyItemManager/DIM/blob/0fabcc9aa4b40886f33d70ffb9a11e9bbe14044c/src/app/loadout-builder/filter/FilterBuilds.tsx#L61-L69

**Comment by bhollis** [comment]
Duplicate of #6848
