### ISSUE TITLE
creating a loadout using the unequipped tag also adds any items in the postmaster

### ISSUE THREAD

**Issue by nki2bpz** [DestinyItemManager/DIM#6851]
I'm trying to make a quick loadout of everything on this character so i can move it off, claim postmaster items delete dupes etc, then move it all back when i'm done. I couldn't figure out why my loadout had 15 energy weapons LOL. If this is intended or unavoidable behavior please disregard.

**Comment by nki2bpz** [comment]
oops

**Comment by nki2bpz** [comment]
For a second I thought it was my mistake but this still happens. Create loadout from equipped, add unequipped and it includes all the postmaster items in the loadout.

**Comment by bhollis** [comment]
Will take a look. However, you don't need to create a loadout to do this, just use the search `is:haspower -is:equipped is:inleftchar`, move the search to the vault, then "undo" the search loadout when you're done.
