### ISSUE TITLE
Add support for `holdsmod:raid`

### ISSUE THREAD

**Issue by michaelabon** [DestinyItemManager/DIM#6855]
I would love to be able to search through my inventory/vault to find and lock any hard-earned raid armor, so that I don't accidentally delete it.

I have a few copy-paste "tag as junk" searches for poorly rolled armor:

```
is:armor basestat:total:<64 basestat:custom:<32 not:classitem not:exotic not:maxpower  not:tagged not:inloadout
```

I realized that I was sharding raid armor that held armor mod slots. I know that I can add in specific raids, using `holdsmod:lastwish` or `holdsmod:vaultofglass`. It would be nice to have a search filter that combined all of these, to make it easier to protect those armor pieces.

(I searched the existing issues and was not able to find an existing request.)

**Comment by delphiactual** [comment]
`source:raid is:armor` should already handle this

**Comment by michaelabon** [comment]
Amazing, that's perfect. Thank you!
