### ISSUE TITLE
In build optimizer, there is some problem with finding a build when global reach mod is selected.

### ISSUE THREAD

**Issue by OscarSheng** [DestinyItemManager/DIM#6858]
**What version of DIM are you using?**
6.69.0 This issue appears on DIM beta  also

**Describe the bug and how to make it happen**
In build optimizer, there is some problem with finding a build when global reach mod is selected.
![image](https://user-images.githubusercontent.com/36452729/122705167-2c120980-d223-11eb-9aee-92d0cd5de4e7.png)

**Comment by bhollis** [comment]
I wonder if the metadata or d2ai mappings are wrong. I can reproduce - with the first three mods I get a bunch of builds, and I still have two open combat mod slots open, but adding Global Reach shows no builds available.

**Comment by SolWatcher** [comment]
Hi, I commented on a similar (or the same) issue on discord. Using most element neutral mods seemed to return 0 builds when used with other mods. This includes the general armor mods (mobility/recovery, etc.) and the element neutral mods in the combat slot (taking charge or the elemental well mods, or something like this case of global reach). For me, I could use a single element neutral mod, and LO would return builds, but would return 0 builds if I used something like 2 minor discipline mods. When I would test a single affinity-neutral mod, they always were slotted on void armor, even if I had higher tier armor available.

**Comment by ryan-rushton** [comment]
Interesting, none of that code has changed lately and I usually test it when I touch that code. I will look into it.

**Comment by SolWatcher** [comment]
I’m sorry, I left out the most important part when I commented here; this is all when “nothing” is selected for how much I want to spend to upgrade or change armor element affinities. If you select anything other than nothing, it will find builds, but it won’t slot mods to what would seemingly (to me anyways, maybe it’s intended) be the best armor pieces. LO seems to suggest changing the element affinity for most armor pieces whenever anything other than nothing is selected too.

**Comment by ryan-rushton** [comment]
Ah, that could be something then. For reference, the new select takes energy into account but previously we always assumed armour had 10 energy when fitting mods. This new way will allow people to find sets that fit their gear now with nothing spent. I kinda expect people will use the legendary shards at a minimum to make the optimiser think their armour has 7 energy at the minimum.

Saying all this though, something is definitely off with the nothing option. I have a set of all solar armour that is masterworked and I can't slot all solar mods with one global reach. All solar mods is fine though.

**Comment by ryan-rushton** [comment]
@OscarSheng and @SolWatcher, thanks for the report. It has been found and should be fixed on beta. Report back if not.
