### ISSUE TITLE
Loadout Optimizer unnecessarily prefers to change armors element type to fit mod selection

### ISSUE THREAD

**Issue by HardcoreWaffles** [DestinyItemManager/DIM#6872]
**What version of DIM are you using?**
Version 6.70.0.1000556 (beta), built on 6/23/2021, 9:16:17 AM

**What Browser and OS are you using?**
Microsoft Edge 91.0.864.54

**Describe the bug and how to make it happen**
1. Open "Loadout Optimizer"
2. Select "Ascendant Shard" from "what you will spend" dropdown
3. Pin a loadout such that you have only at least 2 arc affinity items and that either helmet or arms or both are not arc
4. Select "Radiant Light" and "Powerful Friends" mods

Expected:
Mods are slotted into already available Arc affinity armor

Actual:
Mods are slotted into Helmet and Arms regardless of their affinity
![image](https://user-images.githubusercontent.com/2857734/123202380-581ecc00-d469-11eb-9a19-027248d5f254.png)

Note that as long as you don't select "Ascendant Shard" as something you'd be willing to spend mods are placed as expected (if possible) however this makes it difficult to compare loadouts between things you've already masterworked vs things you are willing to masterwork. This is a regression of behavior with what was possible with the "Assume masterworked" checkbox

**Include devtools console logs**
If you can, open the devtools console (ctrl+shift+J on PC and cmd+option+J on Mac) and paste what you see in the window that pops up:

```
JQMIGRATE: Migrate is installed, version 3.0.0
instrument.ts:129 [app] DIM v6.70.0.1000556 (beta) - Please report any errors to https://www.github.com/DestinyItemManager/DIM/issues
instrument.ts:129 [dim sync] globalSettings Object
log.ts:44 Load manifest: 1632.14501953125 ms
log.ts:44 Process inventory: 160.87890625 ms
log.ts:44 Inventory state update: 86.13720703125 ms
optimizer:1 [Intervention] Images loaded lazily and replaced with placeholders. Load events are deferred. See https://go.microsoft.com/fwlink/?linkid=2048113
instrument.ts:129 [dim sync] Saving profile data to IDB
​ [loadout optimizer] found 200 stat mixes after processing 186732 stat combinations in 309 ms -  604310.6796116505 combos/s [object Object] [object Object]
instrument.ts:129 [loadout optimizer] useProcess: worker time 363.70000000018626ms
instrument.ts:129 [loadout optimizer] useProcess 405.89999999990687ms
DevTools failed to load source map: Could not load content for chrome-extension://eobkhgkgoejnjaiofdmphhkemmomfabg/libs/jquery.qtip.min.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
114-5f4e09.js:1 [loadout optimizer] found 1 stat mixes after processing 1 stat combinations in 0.5 ms -  2000 combos/s {numCantSlotMods: 0, numSkippedLowTier: 0, numStatRangeExceeded: 0} {numInserted: 1, numRejectedAfterInsert: 0, numDoubleExotic: 0}
instrument.ts:129 [loadout optimizer] useProcess: worker time 102.10000000009313ms
instrument.ts:129 [loadout optimizer] useProcess 146.20000000018626ms
114-5f4e09.js:1 [loadout optimizer] found 1 stat mixes after processing 1 stat combinations in 1.1000000000931323 ms -  909.0909090139403 combos/s {numCantSlotMods: 0, numSkippedLowTier: 0, numStatRangeExceeded: 0} {numInserted: 1, numRejectedAfterInsert: 0, numDoubleExotic: 0}
instrument.ts:129 [loadout optimizer] useProcess: worker time 49.60000000009313ms
instrument.ts:129 [loadout optimizer] useProcess 66.6999999997206ms
```

**Comment by ryan-rushton** [comment]
This was expected with the recent changes and I have expected some discourse around it. As you have pointed out we are allowing energy affinity swaps on items if the selected material can be used to convert it. This is actually a long requested feature, see #5241 as an example.

As mentioned it would be idea if we could align energy with gear initially and if not use energy swaps as a failover. Unfortunately this would blow out armour processing times to something around a minute as soon as you select a few mods. We aren't willing to do that.

What I propose as a solution is to add another option to the new select. Something like "Ascendant Shard (Not already masterworked)" or "Ascendant Shard (no energy swaps)", we obviously need better wording. This would allow people to leave existing masterworked items alone but also allow people to upgrade items.

What we don't want to do is add too many options as it gets very hard to manage in the app. The logic to do all this is complicated to say the least.

@bhollis and @nev would love your thoughts.

**Comment by bhollis** [comment]
As I understand it there are two roughly independent functions - one that sees if the mods could fit on the set as a whole (to determine set feasibility), and one to assign mods to individual items for display. I think the latter is what has people confused. If you *needed* to switch affinity to fit a mod, that'd probably be OK, but in the example shown there's an affinity swap when the mod could have gone on another piece that was already arc.

In the back of my mind I've been thinking about building a solution using a linear constraint solver for this display problem, which would also be able to give the minimum cost series of actions to apply the mods to your loadout. That'd solve this problem, and give us a way to show instructions and total cost when you apply loadouts, and give us a path to AWA powered mod loadouts.  But it's quite tricky to build.

**Comment by ryan-rushton** [comment]
> As I understand it there are two roughly independent functions - one that sees if the mods could fit on the set as a whole (to determine set feasibility), and one to assign mods to individual items for display

They are actually the same function at this point but they have slightly different inputs for the display case. Namely an object that is used to track which items the mods go on for the first matching set found.

We could do two things in the short term to try and find matching sets. 
1. Let the display version find all the possible matches, so no early exits.
2. Track the number of energy swaps to achieve the result, then the lowest number is what we display.

My concern with seperate function was that it was hard to test the underlying algorithm used for feasibility. Now we have profile tests that isn't an issue, I do need to set up some tests sooner rather than later though.

**Comment by nev-r** [comment]
yes more options sucks, but
where energy upgrades are objective improvements,
element changes are effectively destructive. they levy an opportunity cost against other possible, or already planned/saved, loadouts

really "needs" to be a separate opt in

**Comment by ryan-rushton** [comment]
A big reason I like the dropdown is that it is now very unobtrusive to the UI to just add more. In most cases the hardest part will likely be articulating what the option actually does.

**Comment by ryan-rushton** [comment]
Also this is only really an issue for Ascendant Shards the way I see it. All the other options are only there for energy affinity changes.

**Comment by HardcoreWaffles** [comment]
While the dropdown option would solve this case in particular it would still leave the plain "Ascendant Shard" option essentially broken.
Suppose I actually was open to changing the affinity of a piece of armor, and my armor setup was Solar-Solar-Arc-Void-Void if I put "Powerful Friends" and "Radiant Light" as required mods the implementation will still suggest that I change my 2 solar pieces to Arc, which is still wrong.
Also am I wrong or aren't the other options broke in the same way in cases where the armor that needs to change affinity is not already masterworked fully and therefore would not require Ascendant Shards to change? Or does the code just assume you will need an Ascendant Shard?

**Comment by ryan-rushton** [comment]
Yeah you are correct, it is still too aggressive and I think I have a strategy to fix it. All the options will suffer from this because it is in the core of out algorithms for finding mods. Basically we only care about finding out if it is possible. Not the best combination for slotting mods.

It is hard to distinguish the best mod slotting due to the possible number of mod combinations. We can potentially tackle this by taking the first one when we are figuring out if a set is viable, and then when we go to render it on screen find the best possible permutation so that the minimum number of energy swaps have been done. 

To give you an idea, the possible number of mod permutations we care about is for general, combat, and raid and is (5!)^3 which is approximately 1.7 million. Doing that for 2 million different combinations of armour can break the browser.

**Comment by ryan-rushton** [comment]
I am planning on tacking this next fyi, I have half a solution.
