### ISSUE TITLE
Moments of Triumph doesn't have completion percentage

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#688]
<img width="344" alt="screen shot 2016-07-09 at 10 56 24 pm" src="https://cloud.githubusercontent.com/assets/313208/16711906/6e54983a-4628-11e6-899a-ad8d6a905c53.png">

**Comment by SunburnedGoose** [comment]
Hmmm...  Used too. Wonder if eutrals fix broke that.

**Comment by bhollis** [comment]
Hmm, never mind. Amend this to say "It's confusing that objectives can show as complete but you still have to go into the game UI and hit a button to activate the completion."

**Comment by SunburnedGoose** [comment]
Hmm, wonder if there is a indeterminate we can use if we have a signal.
