### ISSUE TITLE
i18n support for "currently equipped" not available

### ISSUE THREAD

**Issue by rentalhost** [DestinyItemManager/DIM#6883]
https://github.com/DestinyItemManager/DIM/blob/89844990985e04e040605202ae8a4fdbf190d37a/src/app/loadout-drawer/loadout-utils.ts#L261

**Comment by bhollis** [comment]
https://github.com/DestinyItemManager/DIM/pull/5983

**Comment by ryan-rushton** [comment]
Gah all these modules are still intertwined.
