### ISSUE TITLE
iPad Pro has a gap above header

### ISSUE THREAD

**Issue by msdurex** [DestinyItemManager/DIM#6885]
**What version of DIM are you using?**
6.17.0

**What Browser and OS are you using?**
iPadOS 14 Safari

**Describe the bug and how to make it happen**
Scroll down the inventory list and scroll down. You can see the tiles through the top bar. (where the clock and iPad statu icons.)

**Include devtools console logs**
If you can, open the devtools console (ctrl+shift+J on PC and cmd+option+J on Mac) and paste what you see in the window that pops up:

```
Paste console logs here
```

**Comment by shockthealien** [comment]
I’ve observed this bug too for a while now. Still happening on version 6.72.1.1000579 (beta), built on 07/07/2021, 19:35:47 on an iPad Pro (12.9-inch) (3rd generation) using iPad OS 14.6. 

See screenshot attached
![7CA72B97-B0D9-4BC3-9EC4-DABB25218698](https://user-images.githubusercontent.com/2083273/125159708-ec2eaa00-e170-11eb-8c91-0cf66f83fb77.png)

**Comment by bhollis** [comment]
Should be fixed as of the latest release. Would someone mind confirming that?

**Comment by msdurex** [comment]
Fixed at 6.80.0.
