### ISSUE TITLE
Organizer: Shift-click on modslot doesn't use the right filter

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#6889]
![image](https://user-images.githubusercontent.com/313208/124368846-30262a00-dc1a-11eb-9153-836443a57b30.png)

Shift-clicking on the *second* modslot here filters by `modslot:combatstyle` instead of `modslot:deepstonecrypt`.

**Comment by nev-r** [comment]
i don't think there is support for shift-click on anything smaller than the entire cell. but this should be narrowed to only show (and filter) DSC anyway. the work is half done on this already, just needs replacing, it's a function called something like getInterestingModslots instead of getModslots
