### ISSUE TITLE
Alert in the UI when a filter is invalid when trying to save/fav it

### ISSUE THREAD

**Issue by abea** [DestinyItemManager/DIM#6893]
Right now when you're trying to save an invalid filter there is no indication that it is invalid. The star simply doesn't respond. In the browser console there is a console error indicating what is going on, but most people won't check that.

**Proposed change**

There should be an alert pop up when trying to save an invalid filter warning that the operation is not possible.

**How does this fit into your workflow?**

It's really a frustration prevention tool. And saving people's mice from when they're spamming clicks to save in vain until their mouse explodes.

Example invalid filter:
```
(((is:weapon -is:maxpower -is:masterwork (is:sunset or is:blue)))is:sword
```

**Comment by bhollis** [comment]
In Beta, we now grey out invalid searches and hide the favorite button. Does that do it?

**Comment by abea** [comment]
It does! This looks great. Thank you.
