### ISSUE TITLE
New Tags to Label PVP or PVE

### ISSUE THREAD

**Issue by nki2bpz** [DestinyItemManager/DIM#6894]
Not sure how limited  tags are but  I think they could be more useful.

Based on the wish lists etc there are a lot of weapons that have better rolls for PVP vs PVE and I've been using the "Junk" Tag for PVE stuff and "Infuse" Tag for PVP so i can see the Lightning Bolt and know which one to grab. The "Favorite" tag i use when i'm comparing different versions of the same weapon.

**Comment by inexorableAce** [comment]
we have an FAQ about this right here on github. https://github.com/DestinyItemManager/DIM/wiki/Frequently-Requested-Features

we have notes for this type of personal tagging. Notes also autocomplete when you use a `#` before you note text like `#pvp` for instance. they are also searchable with those `#`

**Comment by nki2bpz** [comment]
Thanks for the link but I'm well aware of what has been said on it in the past.  I understand  they are limited, just didn't know  2 more tags would "break the bank" limited.  If that has  been requested a lot of times there is probably a reason. I have tried notes and and i get they are searchable but for me seeing the post it note icon just obscures more of the weapon icon w/o actually giving me any information.  Still have to open the item to see the note. when i look at the screen and go to grab a hung jury i don't wonder which and then go to the search bar and type #pvp then go back to the icon to see which one to grab. The junk tag works fine  for me , if i have 3 different versions of a sniper i can know the junk one is pve just by looking at it.

**Comment by bhollis** [comment]
Your feedback has been heard but we currently have no plans to expand tags to cover PvP vs PvE.
