### ISSUE TITLE
LO crash when no sockets available

### ISSUE THREAD

**Issue by nev-r** [DestinyItemManager/DIM#6911]
when sockets are down in the API,
```
instrument.ts:129 TypeError: Cannot read property 'socketDefinition' of undefined
    at i (energy.ts:32)
    at g (utils.ts:145)
    at useProcess.ts:232
```

**Comment by ryan-rushton** [comment]
Hmmm what cases would this happen, the item would need to have energy but no tier socket. Blues maybe?

**Comment by delphiactual** [comment]
Socket data not available during just after maintenance

**Comment by ryan-rushton** [comment]
Ah ok, I will try make it more resistant to that.

**Comment by ryan-rushton** [comment]
I am guessing removing the non-null coercion might fix it.
https://github.com/DestinyItemManager/DIM/blob/master/src/app/inventory/store/energy.ts#L30-L32
