### ISSUE TITLE
Selecting an exotic in LO interacts badly with search

### ISSUE THREAD

**Issue by amacdonel** [DestinyItemManager/DIM#6921]
On loadout optimizer, if I search for armor pieces and then select an exotic I get zero loadouts. 

Steps to reproduce:
1) Enter a search for items you want in your build (season:current or 'hezen')
2) Select an exotic

Loadout Optimizer returns zero loadouts.

**Comment by delphiactual** [comment]
You would need to add an `or is:exotic` since the exotic you selected does not match your search criteria

**Comment by amacdonel** [comment]
Ah! I didn't expect this behavior. Thanks for clarifying. 

I suspect the exotic selector is separate, but if possible, can an enhancement request be entered to have the exotic be an included 'or' to the contents of the search bar?

**Comment by ryan-rushton** [comment]
Two ways we can look at doing it is the 'or' as you suggested. It kinda feels like it is overriding the search filter though which is more global than the optimiser. Another solution may be to only show exotics that match the search filter, then the search bar keeps a more global function.

**Comment by bhollis** [comment]
The search filtering should probably just be applied after the exotic - the way it's supposed to work is if anything in a bucket doesn't match the search, the search doesn't apply at all to that bucket, to prevent exactly this kind of thing.

**Comment by ryan-rushton** [comment]
I've been working under the assumption that anything in the filters on the left hand side doesn't follow that behaviour. For example, if I pin an item, say a set of gloves, and I add a search filter for name"contraverse hold" (exotic warlock gloves) then I get no results. It's a bit of a contrived example but I am sure you get the drift.

**Comment by ryan-rushton** [comment]
Happy to change it but we should probably look at making all the things in the filter section follow that behaviour with the exception of mods. That filtering happens at a different spot and it would be pretty tricky to make it work that way.

**Comment by bhollis** [comment]
Perhaps an easier solution is to just not apply the search at all to whichever bucket the pinned exotic is?

**Comment by ryan-rushton** [comment]
Yeah that probably would be easier. I will get to it when I can.
