### ISSUE TITLE
LO crash: Energy Swap

### ISSUE THREAD

**Issue by nev-r** [DestinyItemManager/DIM#6924]
fixed this temporarily with an optional chain here:
https://github.com/DestinyItemManager/DIM/blob/master/src/app/loadout-builder/generated-sets/GeneratedSetItem.tsx#L28

but lockedMods is undefined when TS says it shouldn't be,
so i think the assumption (accessing a specific key in assignedMods) on this line needs reexamining:
https://github.com/DestinyItemManager/DIM/blob/master/src/app/loadout-builder/generated-sets/GeneratedSet.tsx#L117

**Comment by ryan-rushton** [comment]
I think the type def is just wrong, being as we are accessing an object like that the result should be an array or undefined. Probably just best to add the optional to the props as well.

**Comment by ryan-rushton** [comment]
FWIW those mod assignments are about to become a class so we can show the least expensive assignment. It should all go away after that too.
