### ISSUE TITLE
Undefined object error with Loadout Optimizer

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#6927]
https://twitter.com/diplomat696/status/1417898373936463872?s=21

Player is reporting an issue with loadout optimizer that is only reproducible with one character. 

![9DDC45FD-437B-426A-A4E8-10084C243FF2](https://user-images.githubusercontent.com/984608/126533413-c17e7200-646e-42f4-9c96-85bb041d0ddd.jpeg)

**Comment by nev-r** [comment]
dupe https://github.com/DestinyItemManager/DIM/issues/6924
