### ISSUE TITLE
Incorrect magazine size calculation

### ISSUE THREAD

**Issue by Zeiin** [DestinyItemManager/DIM#6929]
**What version of DIM are you using?**
Version 6.74.0 (release), built on 7/18/2021, 10:04:38 PM

**What Browser and OS are you using?**
Chrome on Win10

**Describe the bug and how to make it happen**
I set up my Uzume RR4 in game to use adept backup mag instead of backup mag. In game, this bumps the magazine up to 6, but DIM only displays 5.
![image](https://user-images.githubusercontent.com/12564684/126848917-27610df3-5d93-427e-ad0e-d3931f55a696.png)

![image](https://user-images.githubusercontent.com/12564684/126848943-d340ceb9-f9da-4079-9693-7ab48d5f9c91.png)

Note that in-game, hovering over Adept Mag when Backup mag is equip doesn't preview that the mag size will go up. Normally a small green arrow would appear near magazine to indicate the upcoming bump:
![image](https://user-images.githubusercontent.com/12564684/126848892-77f9927b-97e9-46c4-9803-3ee6fc695191.png)

**Comment by nev-r** [comment]
unfortunately this is just gonna be wrong sometimes. bungie's mag calculations are performed in game at runtime and a lot of API data is close but not quite right. for context, 

uzume's raw magazine stat is 50
![image](https://user-images.githubusercontent.com/68782081/126852889-29ac73ee-7c08-4f13-96c5-55166ab6340d.png)

adept mag provides +40
![image](https://user-images.githubusercontent.com/68782081/126852904-521e1ce2-d2dc-410b-b839-b7951f0633c8.png)

and the statgroup curve, specifically says the result, 90, should give you a 5 bullet mag
![image](https://user-images.githubusercontent.com/68782081/126852920-e0528241-47db-4f45-ad79-9690fd4beed4.png)
