### ISSUE TITLE
Can't select "bottomless grief" perk in item comparison for this season's Nightfall Adept weapons

### ISSUE THREAD

**Issue by thomaskchan** [DestinyItemManager/DIM#6934]
**What version of DIM are you using?**
Version 6.74.0.1000613 (beta), built on 7/24/2021, 7:37:52 PM

**What Browser and OS are you using?**
Chrome on MacOS

**Describe the bug and how to make it happen**
Use compare for Plug One.1 (Adept), Uzume RR4 (Adept), Hung Jury SR4 (Adept) and try clicking the Bottomless Grief perk.  The perk will be unselectable.  You can click on mag or barrel options on the same weapon and those are selectable.

**Comment by nev-r** [comment]
that's pretty legit. i think the assumption written into the perk changer is that mags/scopes/barrels/etc can change stats. but it's true some "primary" perks have stat bonuses
