### ISSUE TITLE
Tactical mag isn’t properly working in DIM

### ISSUE THREAD

**Issue by reneheideveld** [DestinyItemManager/DIM#6938]
**What version of DIM are you using?**
Find the version in "About DIM" from the menu (the button with three bars on the upper left of the screen). Is the DIM icon orange, or blue?

Orange version

**What Browser and OS are you using?**
It helps to know what type of browser and what version you're using. Have you installed DIM as an app through Chrome or Safari?

IOS, Safari 

**Describe the bug and how to make it happen**
Tell us what's wrong. A great format for bug reports is "I did X, and I expected Y, but instead Z happened." If it helps illustrate the issue, please add screenshots to help explain your problem.

Tactical mag on uzumi with bottomless grief gives 6 ammo ingame. In the app it gives 5 ammo.

**Include devtools console logs**
If you can, open the devtools console (ctrl+shift+J on PC and cmd+option+J on Mac) and paste what you see in the window that pops up:

```
Paste console logs here
```

**Comment by delphiactual** [comment]
#6929

**Comment by reneheideveld** [comment]
Sorry just saw it and it's bottomless grief that doing it
