### ISSUE TITLE
Styling of scrollbars

### ISSUE THREAD

**Issue by alfyboza** [DestinyItemManager/DIM#694]
I created PR #620 a while back that updated the scrollbars in DIM. Glad to see it was liked and merged in right away! 🎉 

As a result of a recent refactor, the scrollbar styling is no longer applied however. Should the scrollbar styles be removed from the codebase entirely? Or updated so that they are applied once again?

In the aforementioned refactor, the scrollbar definitions were appended by the `.ndialog` class:

https://github.com/DestinyItemManager/DIM/blob/c313bfc3d5e0f711695e80b335e6dcde67e8601c/app/scss/_style.scss#L410-L424

(That blob is the current Git commit on `dev` at the time I write this.)

It's been my experience that Google Chrome doesn't honor scrollbar changes that aren't global. I applied the styles globally on my local branch and the scrollbars were reverted back to the styles initially applied in #620:

![screen shot 2016-07-13 at 9 17 10 am](https://cloud.githubusercontent.com/assets/471333/16805191/0ba8ce24-48dd-11e6-9c93-b20eb3241c67.png)
![screen shot 2016-07-13 at 9 25 01 am](https://cloud.githubusercontent.com/assets/471333/16805194/0fda7998-48dd-11e6-874c-4dedc69d3e0b.png)

https://github.com/DestinyItemManager/DIM/compare/dev...alfyboza:webkit-scrollbar-fix?expand=1

With the current scrollbars, the default scrollbar style is used throughout DIM:

![screen shot 2016-07-13 at 9 18 15 am](https://cloud.githubusercontent.com/assets/471333/16805350/c37790ee-48dd-11e6-9f54-1e479f3ad8e8.png)
![screen shot 2016-07-13 at 9 19 14 am](https://cloud.githubusercontent.com/assets/471333/16805352/c5e28c6c-48dd-11e6-954d-bf376bfccff3.png)

However, there's a weirdness with the horizontal scrollbar that gives the user the impression that one cannot scroll all the way to the right:

![dim - horizontal scrolling](https://cloud.githubusercontent.com/assets/471333/16805601/f07c1faa-48de-11e6-9431-d92dc310c7bd.gif)

(The horizontal scrolling issue is fixed by the changes on my fork.)

Circling back to the original question: should I create a PR and remove the scrollbar updates entirely (no hard feelings, honestly!), or should I update the scrollbar styles to be global?

**Comment by bhollis** [comment]
Hmm. I'd rather not have the custom scrollbars everywhere - I'd prefer them
only for the loadouts drop down. Is there a good way to achieve that?

**Comment by alfyboza** [comment]
There isn't - to my knowledge. It's been my experience that it's an all-or-nothing approach when it comes to scrollbars. Perhaps others have had luck with a workaround? I certainly have not.

Should I create a PR and remove the scrollbar CSS since it isn't applied?

**Comment by bhollis** [comment]
Let's put back your custom scrollbars everywhere.
