### ISSUE TITLE
On Compare Stats - Columns not aligned 

### ISSUE THREAD

**Issue by rekcluse** [DestinyItemManager/DIM#6945]
As shown below, the stats don't align with the text.

Using Galaxy S10 Plus.

![Screenshot_20210809-175756_Chrome](https://user-images.githubusercontent.com/62358799/128745760-3606a411-9889-400e-9330-7192f2ec417e.jpg)

Version 6.77.0 (release), built on 09/08/2021, 03:01:44

**Comment by bhollis** [comment]
For anyone who wants to take a crack at this, it's because part of the screen can scroll vertically while the stats don't. It's a real weird and janky layout.
