### ISSUE TITLE
Allow consumable items to be pulled out of offline characters.

### ISSUE THREAD

**Issue by Visoral** [DestinyItemManager/DIM#6946]
I noticed that DIM can't do that, but D2 Checklist can. (ex. Spoils of Conquest)

**Comment by bhollis** [comment]
Can you elaborate? I don't understand

**Comment by nev-r** [comment]
@bhollis the pull from postmaster buttons aren't offered on non-current chars. they used to be but something changed in the ispullable check or smth

**Comment by bhollis** [comment]
They should be available, no idea why they aren't.

**Comment by SudoForkBomb** [comment]
May take a crack at this if it's still open.

**Comment by delphiactual** [comment]
go for it
