### ISSUE TITLE
Organizer: CSS issue in Perks Mods & Shaders

### ISSUE THREAD

**Issue by nev-r** [DestinyItemManager/DIM#6949]
i don't really understand what this mixin's purpose is
https://github.com/DestinyItemManager/DIM/blob/4faa2632548b89fceaa000d97ae6787ef422edc3/src/app/_variables.scss#L84-L87

but it's causing some odd margins here in the organizer
![image](https://user-images.githubusercontent.com/68782081/128944605-1e645cb6-9c00-4e2a-b5ac-9c95b74b9e20.png)
which is displacing mod images
![image](https://user-images.githubusercontent.com/68782081/128944744-205e0a15-7de7-45f9-9d63-6c9cfc6a1cd9.png)

**Comment by bhollis** [comment]
Its purpose is to put vertical space between children of an element - equivalent to `row-gap: $space` if `row-gap` actually worked on all browsers (thanks Safari).

**Comment by Ray10** [comment]
How can I locate this issue in production? I am not sure where this is coming from. Thanks.

**Comment by bhollis** [comment]
Are you trying to fix it? It's on the Organizer page when you enable the perks column.
