### ISSUE TITLE
display exotic weapons

### ISSUE THREAD

**Issue by telluoff** [DestinyItemManager/DIM#6952]
**What version of DIM are you using?**blue
Find the version in "About DIM" from the menu (the button with three bars on the upper left of the screen). Is the DIM icon orange, or blue?

**What Browser and OS are you using?**chrome
It helps to know what type of browser and what version you're using. Have you installed DIM as an app through Chrome or Safari?

**Describe the bug and how to make it happen**Why does DIM display some exotic weapons and not others?
Tell us what's wrong. A great format for bug reports is "I did X, and I expected Y, but instead Z happened." If it helps illustrate the issue, please add screenshots to help explain your problem.

**Include devtools console logs**
If you can, open the devtools console (ctrl+shift+J on PC and cmd+option+J on Mac) and paste what you see in the window that pops up:

```
Paste console logs here
```

**Comment by delphiactual** [comment]
Can you give some examples of exotics that do not display

**Comment by telluoff** [comment]
Of all the exotics I have only hawkmoon and dead man's tale display.

**Comment by delphiactual** [comment]
Screenshot

**Comment by telluoff** [comment]
Sorry, I was talking about light.gg not DIM.
