### ISSUE TITLE
Add the ability to Vault loadouts we create (In the same manner we pull them from Vault).

### ISSUE THREAD

**Issue by Swiftclaw8** [DestinyItemManager/DIM#6953]
I want to preface that I know nothing about webapps, or anything about programming DIM specifically, so if this is above and beyond feel free to ignore.

Being able to pull stuff from my vault using the built-in loadouts system is really cool, it saves me a lot of time! But when I'm done using a certain build, it's really annoying to individually click-drag each item back to the Vault. Having another button where we select preset loadouts so that we can Vault gear we're not using quickly would also be nice (without having to use Farming mode).

**Comment by delphiactual** [comment]
Vault dropdown -> Select Loadout
