### ISSUE TITLE
DIM and 

### ISSUE THREAD

**Issue by Spuner** [DestinyItemManager/DIM#6955]
DIM (Chrome App) does not correctly show which bounties are done and which are not. And this is not the first time...

![Screenshot](https://user-images.githubusercontent.com/30773815/129611358-0a493422-5896-4810-b22c-c2f0f79a1a76.png)
![Screenshot (1)](https://user-images.githubusercontent.com/30773815/129611353-d2c5dfa4-010d-469c-90a3-7a4ebe0bc595.png)

**Comment by delphiactual** [comment]
We can only return what the API is currently telling us. We also no longer have the ability to auto-refresh your data (Bungie asked us to remove it). Please try refreshing your current info by pressing `r`.

**Comment by Spuner** [comment]
Are they sending updates with a delay of 1 hour and more?

**Comment by delphiactual** [comment]
Did you press `r`

**Comment by Spuner** [comment]
I've updated it more than once.

**Comment by Spuner** [comment]
I noticed this a long time ago. It's probably been going on for a few seasons now...

**Comment by delphiactual** [comment]
Lock any item, then press `r`, and let me know...

**Comment by delphiactual** [comment]
Also wrong area of DIM to look for bounty status... Check the `Progress` tab

**Comment by Spuner** [comment]
Locked in DIM, but in the app - does not show that the item is locked. Apparently, there is a delay with the API - the data is not updated immediately. But it's been more than an hour since the daily reset, the contract should have updated.

**Comment by Spuner** [comment]
The app showed that it was blocked. And it took ~5 minutes.
