### ISSUE TITLE
Idea: Loadout Optimizer by Bounty/Quest/Triumph

### ISSUE THREAD

**Issue by aweghorst** [DestinyItemManager/DIM#6957]
# Early ideas for a very complex feature using the loadout optimizer.

## Basic Idea:
DIM looks at collected bounties, in-progress quests, incomplete triumphs, etc. and determines what loadout will help knock out them out in an effective manner. 

## Reason:
I can't keep up with the amount of quests, triumphs, masterworks, etc. that I'm currently working on.  I tend to focus on completing the daily bounties first and then I'll check my quests tab and knock out what's there. Naturally there is a bit of overlap where I could have made progress on both if I had just switched subclasses or something like that.  Maybe I have a bounty that says I need arc kills and another that says I need sniper kills.  Well, there isn't a legendary arc sniper that I have so I'll use Trinity Ghoul and get sniper kills with any sniper.  But turns out I'm 30 or so kills away from earning the DARCI catalyst which I haven't touched for 10 months, so that would have been a better loadout than what I went with.  Point is it seems like there is almost always progression to be made that I have forgotten about or simply just looked over.  There is a **_most_** efficient path to completing everything and it's definitely not what I do when I play.  I'd like to fix that.

## Notes:
* This would require further breakdown of anything with a progress bar.  All these endpoints would have to be broken down into specific weapon, weapon class, activity, destination, etc.  so that we can say "okay, if we equip a solar shotgun, a bow, and linear fusion rifle, and the stasis subclass while running strikes, we can knock out these 6 bounties at once.  Scan through the inventory and see that Lord of Wolves still needs kills for it's catalyst so that's the solar shotgun.  Scan through bows and sees there is no _best_ bow so we'll use the highest level bow (or most used/last used but I don't know if that data is available), stasis super kills and stasis grenade kills will work towards these two quests, etc.". 
* You can get advanced with it and include filters like "strikes only" or "lets work on the objectives that are nearest completion", lock in a specific quest meaning "this takes priority, lock in the required loadout for this objective but you can backfill the rest of my loadout to work towards something else".
* This app would be better if it was continuously refreshing.  Meaning once a bounty is completed, a popup appears and says "the next loadout has been found.  Click to move items to your character. Suggested activity: Europa.  Suggested focus: Grenade Kills" 

## Thoughts
I know this is a rough idea but It's something I'd like to see.  I'm very new at coding so it's something I'm gonna work towards but it could easily take me several months to get to anything remotely useful.  I think I'll aim first for an MVP that only looks at bounties.  If anyone has suggestions or would like to take lead on something like this, I'd love to talk.

**Comment by bhollis** [comment]
Have you looked at the [Bounty Guide](https://destinyitemmanager.fandom.com/wiki/Progress)? It's basically this and gives you access to weapons that match bounties in one easy click.

**Comment by aweghorst** [comment]
I knew there was a place that listed bounties and quests but didn't notice the breakdown/filter section.  I also didn't know about moving the required weapons over to your character.  I guess my ask would then be is it possible to perform an analysis that creates a loadout and suggested activity/focus from that information?  Being able to sort things by nearest completion would also be nice.  I'll take a closer look at what is already there though.  Thanks!

**Comment by bhollis** [comment]
I think this is our attempt at solving that - creating full loadouts automatically would be much harder, and I'm not sure anyone would choose to use it vs. picking the combination of things they'd like to work on based on the count of bounties that overlap with each requirement.

**Comment by bhollis** [comment]
I'm going to close this as we have a solution for this, but if you ever want to prototype something and open a PR for it I'd be interested.
