### ISSUE TITLE
getSimilarItem may return undefined

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#696]
if `getSimilarItem` returned `undefined`, it causes the app to break since `getSimilarItem` is `undefined` and we're trying to get the `.owner` property off of that. 

line approx:
https://github.com/DestinyItemManager/DIM/blob/dev/app/scripts/services/dimItemService.factory.js#L212

reported here:
https://www.reddit.com/r/DestinyItemManager/comments/4sa7jj/everything_in_my_dim_flashes_sometimes/d5cfujr?context=3

**Comment by bhollis** [comment]
Fixed in 12b758599b03fd2a78ccd00daee52ce5981edd38.
