### ISSUE TITLE
Loadout Optimizer doesn't show new armors with stasis element

### ISSUE THREAD

**Issue by fre-sch** [DestinyItemManager/DIM#6967]
### DIM Version

Version 6.79.0 (release), built on 8/23/2021, 3:55:05 AM

### Browser Details

Version 92.0.4515.159 (Official Build) (64-bit)

### OS Details

Windows 10

### Describe the bug

Loadout Optimizer doesn't show and use new armors with stasis element.

While the new armors with stasis element show in inventory without stasis symbol, in loadout optimizer, they're not shown at all and aren't used in loadouts.

This is easiest to see when opening "Pin item", where none of the new armors with stasis element will show up.

**Comment by geesus808** [comment]
Same here.

**Comment by inexorableAce** [comment]
bungie's fix, fixed this.
