### ISSUE TITLE
Zavala's Vendor tab Rank is one lower than the player's listed rank in game

### ISSUE THREAD

**Issue by TMMania** [DestinyItemManager/DIM#6968]
### DIM Version

Version 6.79.1.1000642 (beta), built on 8/25/2021, 2:17:18 PM

### Browser Details

Chrome

### OS Details

Windows 10

### Describe the bug

Both screenshots show the same amount of required XP (which scales up per level) and the earned XP of the current rank. DIM lists one level lower than what the player actually has in game.

![image](https://user-images.githubusercontent.com/74565769/130869824-db78eba8-9e6b-4fd1-9e62-02f2b45e75c0.png)
![image](https://user-images.githubusercontent.com/74565769/130869923-968363c4-c933-4de6-8de5-18b742c00261.png)

**Comment by bhollis** [comment]
Probably means that the actual data says the faction rank is 11. The Progress tab shows the new rank setup for Vanguard.
