### ISSUE TITLE
Wishlist Features: New Line Characters & `dimnotes` entries

### ISSUE THREAD

**Issue by TMMania** [DestinyItemManager/DIM#6969]
### Two Features
1.  New line character, `\n` works or whatever you'd like. This would allow the user to utilize some basic formatting in the notes section of wishlists.

2. A `dimnotes:item` entry that just applies notes to a roll without a thumbs up or thumbs down. This would allow users to create pre-assigned notes to rolls without impacting the recommended weapons and trashlist weapons.

### How would this be used:
These 2 features would allow me to take community curated information and compile it into a wishlist repo that applies the information to the relevant items. Here is a sample:
![image](https://user-images.githubusercontent.com/74565769/130870425-1dd6bec3-911c-435d-b232-0117dab43f44.png)

By clicking on a gun you could pull up the notes and know everything about it like the DPS, Burst DPS, Sustained DPS, PvP damage per bullet values, TTK with optimal shots, the effective range in meters, the list goes on. There are a lot of community members who source this data and it's all spread out across individual spreadsheets and I'd like to bring it all to one place expanding the "one stop shop" capabilities of DIM.

### "But you couldn't use compare for these values"
Having this information at easily accessible just makes it more likely that the user will begin to memorize this information which will just elevate the conversation surrounding items on Destiny 2. If the user wants want to compare values, the source spreadsheets all have great formatting and it's what the community has been using anyways. If comparison within DIM is a huge thing, then have fun with pandora's box.

**Comment by bhollis** [comment]
Why not just enable these as extended stats directly?

**Comment by TMMania** [comment]
If ya'll like the idea of more accurate information about weapons from community sourcing and want to develop it and implement that information instead of the proposed notes system with super basic/gross formatting and presentation, great! I'd just love to see the information that the community has sourced implemented in any fashion, and it'd be even better if it's done in a way that can utilize the many other features of DIM.

**Comment by 48klocs** [comment]
Reiterating what nev said, this additional list would be at odds with how wish lists get processed - the first wish list roll that matches is picked as the winning entry. If you were to publish a list and a user were to pick it in addition to a voltron or whatever, then that means we'd show either the wish list roll with all the DPS information, or the wish list roll from a gear knower.

D2AI seems like a saner place to put this (maybe?) but expect to answer the "who will maintain this collection of data when it invariably changes and answer questions from people who ask if it's right" questions, not to mention figuring out how to surface it.

**Comment by 48klocs** [comment]
As a quick follow up, folks have already done something like this - https://github.com/rslifka/fate_of_all_fools

**Comment by TMMania** [comment]
Bhollis and nev, I'm not sure what the exact functional meaning of "per-itemhash notes" and "enable these as extended stats," but they sound fun and I'm willing to hear about that if there is anything to elaborate on there.

48klocs, if I were to use wishlists for this I could voltron the voltron list with this and by giving each item from the voltron list a wishlist entry and the matching generated informational entry and giving a section for "Expert Meta-Analysis" using the notes from Voltron. Again, thats if I were to use wishlists.

The linked Fate of all Fools is interesting, but that style of project is not exactly what I'm going for and also out of my capabilities at the moment and I'd like to capitalize on my free time that I have right now before life gets busy in november/december.

I'm going to go ahead and make the original wishlist idea if there is not an alternative solution/plan found in this ticket. Wishlists as they currently exist could support this project, it'll just be a bit wonky. I'll send ya'll a link when its done via DMs. I'd rather not publically advertise something like this if it has some gross formatting/logistical limitations. Also publicly announcing it would force ya'll into supporting the project via development and that'd be unfair imo. I'd just like to at least have this for my regular gaming group and my day one raid group.

So, the idea will exist, I'm just here to see if ya'll liked the idea enough for a more interesting input (per-itemhash notes?) and/or information output (extended stats?) or if ya'll would be willing to make the project easier/more presentable (`dimnotes` and easy new lines).

**Comment by bhollis** [comment]
How are these special stats calculated? Are they based on the stats of the item itself? If so, you'd probably want to take perk values into account, which means they should be calculated "on the fly" as part of the stats system, not statically determined per-item-hash.

**Comment by TMMania** [comment]
These are values sourced and stored in spreadsheets by the community. I don't believe you can intrinsically calculate them per weapon, although you could modify the base values from the spreadsheets with the modifiers of damage perks to show those changes.

PvE Damage: https://docs.google.com/spreadsheets/d/12vF7ckMzN4hex-Tse4HPiVs_d9huFOKlvUoq5V41nxU
PvP Damage: https://docs.google.com/spreadsheets/d/1_6zsM7kzvg0aUT8YtM_-Wg_5K1gKDOlrwfVzutEjq-s/htmlview#

Effective Range: https://docs.google.com/spreadsheets/d/1LWsExOPoP3Ycx4p1E99aUhKQucP_VguT08TbL7sf_6U/edit#gid=1301739003
These values need to be confirmed for newer updates but they come with actual calculations.

**Comment by TMMania** [comment]
Also, I've been talking with Panda and they gave me an open invitation to send questions about all this data, so if ya'll have any questions about this information or anything, I'm 95% sure they would be willing to answer questions.
