### ISSUE TITLE
Error while Creating Similarly Named Loadouts with Multiplatform Accounts

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#697]
Creating a loadout that is named the same on one platfrom will override and remove the original loadout from the other platform.

1. Create loadout on Xbox, named "Loadout-1", from equpiped.
2. Switch to PS.
2. Create loadout on PS, named "Loadout-1", from equipped.
3. Switch to Xbox.

Result:

Loadout on Xbox removed from UI.

**Comment by SunburnedGoose** [comment]
https://github.com/DestinyItemManager/DIM/blob/dev/app/scripts/services/dimLoadoutService.factory.js#L83

The error is when the save operation occurs for Loadouts, we're getting the loadouts from the service, but they are filtered by the platform.  This orphans the other platform.

**Comment by SunburnedGoose** [comment]
The loadout service getLoadouts function will always return all the loadouts in the config file.  The loadout popup will filter the loaouts by platform when binding to the directive.  These bindings are updated everytime a loadout is changed, or the platform updates.

**Comment by kyleshay** [comment]
nice find @SunburnedGoose ! thanks for getting that in there.
