### ISSUE TITLE
Ornaments and Ownership

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#6989]
### DIM Version

Version 6.80.0.1000663 (beta), built on 9/1/2021, 8:59:49 AM

### Browser Details

Version 92.0.4515.159 (Official Build) (64-bit)

### OS Details

Windows 10

### Describe the bug

Ornaments and Ownership are incorrect...
Checkmarks vs Greyed-out
![image](https://user-images.githubusercontent.com/4798491/131734531-3af1c00c-1c27-4625-a831-10151eefa9aa.png)

**Comment by bhollis** [comment]
I'm not seeing anything like that on my account... someone else will have to look.

**Comment by inexorableAce** [comment]
I think mine are back to normal too. Perhaps it had to do with that bungie bug where tess' inventory was wrong?

**Comment by delphiactual** [comment]
![image](https://user-images.githubusercontent.com/4798491/132015369-d8023906-b447-421f-9dd3-224b0cbca80e.png)
