### ISSUE TITLE
Missing "Infuse item" button in beta

### ISSUE THREAD

**Issue by Anthropole** [DestinyItemManager/DIM#6990]
Version 6.80.0.1000666 (beta), built on 9/1/2021, 10:30:03 PM

The "Infuse item" button is missing from the item popup. Disambiguation: The "Notes" dropdown is still available.

Tested on:
MacOS Monterey 12.0 Beta (21A5304g)
Brave Version 1.29.76 Chromium: 93.0.4577.58 (Official Build) (x86_64)
Microsoft Edge Version 92.0.902.84 (Official build) (x86_64)

**Comment by delphiactual** [comment]
Intended

![image](https://user-images.githubusercontent.com/4798491/131834884-8a89589c-3420-4256-b426-46d3d73e3cbc.png)

**Comment by bhollis** [comment]
Out of curiosity how were you using it?
