### ISSUE TITLE
LO not always showing energy increases

### ISSUE THREAD

**Issue by inexorableAce** [DestinyItemManager/DIM#6993]
### DIM Version

Version 6.80.0.1000666 (beta), built on 9/2/2021, 1:30:03 AM

### Browser Details

Chrome Version 92.0.4515.159 (Official Build) (64-bit)

### OS Details

Windows 10

### Describe the bug

LO isn't showing all armors that need an energy increase, it shows some that stay the same, some that need an affinity swap, but not just general energy increases. 

![image](https://user-images.githubusercontent.com/29002828/131901814-f3f16159-fcb8-4bee-bc69-c41c02834a27.png)

**Comment by ryan-rushton** [comment]
Yeah it is because there is no energy mod on that item.

**Comment by inexorableAce** [comment]
Ahh that makes sense I guess. Still would be nice to see that it needs an energy increase to make it all happen.
