### ISSUE TITLE
Season of Lost Triumph for Wayfinder's Concussion count wrong?

### ISSUE THREAD

**Issue by wkearney99** [DestinyItemManager/DIM#7002]
### DIM Version

Version 6.80.0.1000672 (beta), built on 9/3/2021, 3:51:13 PM

### Browser Details

Chrome

### OS Details

Windows 10

### Describe the bug

When tracking Triumphs->Season of Lost->Prismatic Lenses->Wayfinder's Concussion it doesn't seem to have the right total number of kills needed.  It shows 0/200 at the start.  In-game it doesn't have a segmented bar for progress on it.

That is, for shotgun & heavy grenade kills it lists 200 as the total.  In the game, however, getting to 210 is only 43%.  So I'm thinking the total number of kills needed is more like 500 (as are some others).

Reloading DIM and Chrome did not solve this.  It wasn't until I hovered over the Triumph in the game itself, and reloaded DIM, that it automagically reset itself to use 500.

So much for banging out a quick 200 kills, eh?

**Comment by bhollis** [comment]
What does the companion app show?

**Comment by bhollis** [comment]
It says 500 for me.
