### ISSUE TITLE
When comparing exotic armor ignore element

### ISSUE THREAD

**Issue by wanton7** [DestinyItemManager/DIM#7009]
**Proposed change**
When you compare exotic armor it only loads same same exotic armors that have same element. Change this so every same exotic armor is loaded to comparing ignoring the element.

**How does this fit into your workflow?**
When I get exotic armor drops I compare them but now I have to visually find all same kind of exotic armors to add them all to compare .

**Comment by bhollis** [comment]
Have you tried clicking this button?
<img width="549" alt="Screen Shot 2021-09-05 at 10 23 23 AM" src="https://user-images.githubusercontent.com/313208/132135577-d307b3bf-ef2b-4f35-9568-e81c129bd665.png">

**Comment by wanton7** [comment]
It seems I haven't thanks! I still think better default would be to bring all of them.

**Comment by bhollis** [comment]
Noted
