### ISSUE TITLE
Enhancement Request:  Option to keep exotics in Vault

### ISSUE THREAD

**Issue by brailsmt** [DestinyItemManager/DIM#701]
As a user
I want to keep exotic engrams in the vault
So that I can save them for the next expansion

As it currently stands, "Gather Engrams" moves all engrams to inventory, causing a UX problem by forcing me to manually move the exotics back to the vault.

**Comment by brailsmt** [comment]
Yes, I'm a programmer by profession, hence the user story verbiage, however I don't do javascript and don't have any interest in learning it, I'm more interested in data processing, hadoop, and functional programming which is where I spend my non-work programming time.  So if someone else thinks this is worthwhile, I'd love this feature.

**Comment by SunburnedGoose** [comment]
I can understand this. We could add a checkbox to the gather dialog that remembers preference.

**Comment by bhollis** [comment]
We already prioritize non-exotic engrams for that guy action, and you can
use the "before" auto loadouts to restore everything to its original
position. You can also note use search loadouts to move all exotic engrams
to the vault in o e go. I'd rather not add check boxes and options.

**Comment by SunburnedGoose** [comment]
Exotics are special.  If you don't want to exclude them via a checkbox, then it might make sense to exclude them completely.

**Comment by bhollis** [comment]
I'd prefer not to. I redeem them immediately. I know others don't, which is
why we have so much flexibility for how you organize your stuff, without
resorting to a bunch of prefs.

**Comment by SunburnedGoose** [comment]
Moving their exotics engrams is frustrating, especially when they have been farming and holding them.  They avoid the feature.

**Comment by SunburnedGoose** [comment]
Just reflecting on it some more, I don't think we're flexible in this scenario.

We don't have a convenient way in the app to highlight exotic engrams and move them easily to the vault after using "Engrams to Vault".  You can filter and see theme easily, but if you have many of them, that's a lot of manual transactions to tidy up.

I would agree with the flexibility argument if we had a filter+move feature where a user can filter for items, and move them to a store as if they were a temporary loadout.

**Comment by bhollis** [comment]
We do have that feature. We launched it in the last version. Check out the
change log!

**Comment by SunburnedGoose** [comment]
We're not doing a good enough job showing this feature if even I missed it.

**Comment by kyleshay** [comment]
Maybe if a search is active, we should show a save icon... when clicked, saves that search filter to all characters, and lets users know via a toaster?

**Comment by kyleshay** [comment]
-- But, we keep the current functionality of the current search being a temp loadout as well

**Comment by bhollis** [comment]
Saved search he's are a feature that I mean to add soon.

How should we indicate super advanced corner case features like this?

**Comment by SunburnedGoose** [comment]
Now that people are saving exotic engrams to edge the crypt arch for RoI,
I'm going to add text to inform users of the feature.

Adding a button to that popup that moves them back would be better if you
don't want to add it as a feature. It's a great feature and it will reduce
friction 1% players will experience.

**Comment by bhollis** [comment]
I like more pop-ups about as much as I like more settings.

Let me try something else when I'm back from traveling.

**Comment by SunburnedGoose** [comment]
I'm talking about the engram farm popup.

**Comment by kyleshay** [comment]
What if when the 'farming mode' popped up, there were options on that. It has enough screen real-estate to support it. 

If we did that, we could make it a more generic 'farming mode' and also support farming other types of items (glimmer consumables https://github.com/DestinyItemManager/DIM/issues/645, etc.)

**Comment by brailsmt** [comment]
I don't understand the aversion to a configuration setting.  If it is added, and defaulted to behave as it currently does, then most users will never be impacted, but for those of us that care enough to go digging can find it and enable it.  IOW, it is quite possible to add this change in a way that is passive to users that don't care about it, but makes it a lot less frustrating to transfer over 30 engrams and then move 12 exotic engrams back to the vault.  The numbers will only increase.  Furthermore, this is not a one time Rise of Iron thing, we stock up on exotics for every expansion.

**Comment by kyleshay** [comment]
quick mock of what i'm describing: <img width="672" alt="screen shot 2016-07-18 at 9 37 30 am" src="https://cloud.githubusercontent.com/assets/424158/16916533/487bf956-4ccb-11e6-842e-7cfc2254ff52.png">

**Comment by kyleshay** [comment]
or instead of a checkbox, it could be a set of options: blue and below, legendary and below, exotic and below...

**Comment by SunburnedGoose** [comment]
@kyleshay That mock is what I had in mind.  This isn't something that is hidden away in settings, but more interactive and in the popup.

**Comment by SunburnedGoose** [comment]
+1 for the glimmer farming.  I would much rather save those in the vault for a rainy day (like Iron Banner).

**Comment by brailsmt** [comment]
@kyleshay I like that mock up, so long as the setting is sticky between DIM sessions.  I think the settings should be on the "Gather Engrams" dialog, not the "Engrams to Vault" dialog.  I don't want to exclude exotics when farming, just when moving engrams to a character.  IMO, I think the Farm Glimmer Consumables should be a default part of farming mode.

**Comment by SunburnedGoose** [comment]
So, how do we prevent the "Gather Engrams" feature from slurping up the exotics into the player inventory right now?  Currently, you have to...

1. Gather Engrams to current character.
2. Filter 'exotic engram'.
3. Move filtered items back to the vault.
4. Be disappointed by the Cryptarch.

**Comment by brailsmt** [comment]
Also, in an effort to reduce the impact of a growing number of settings, can the settings be hidden behind an "advanced settings" button?  Basically, just hide them unless someone wants the advanced settings?

**Comment by SunburnedGoose** [comment]
What if we added this feature to the "Gather Engram" feature? Clicking on a color will pull it, and every engram with lower rarity to the selected character inventory.

![image](https://cloud.githubusercontent.com/assets/984608/16918444/f58076a0-4cca-11e6-8a01-e1dffa2eef43.png)

**Comment by SunburnedGoose** [comment]
One scenario I have is I like to keep one legendary class item engram in the vault in case Veriks has a 100% class item. I would be helpful if I could just 'lock' the engram and it wouldn't be moved.  They may not be lockable within Destiny, but it's something we can provide.

**Comment by brailsmt** [comment]
"Locking" an engram in the vault sounds like a good general and intuitive feature.  Perhaps the term "lock" should not be used to avoid overloading the term.  Maybe "hold in vault"...  However, if this is what was decided, there should be some clear visual cue for which items were being held in the vault, otherwise users will forget which items were being held and might log issues for engrams that were "stuck" in the vault.

**Comment by SunburnedGoose** [comment]
Thinking about my mockup, Destiny doesn't save green engrams to be decrypted?  Aren't they all automatically decrypted?  We can cut it out I believe.

![image](https://cloud.githubusercontent.com/assets/984608/16918777/9eaff632-4ccc-11e6-9686-93490b99f7a4.png)

Also, the default behavior of clicking on "Gather Engrams" is the same as clicking on the exotic engram icon.  We can remove that too.

![image](https://cloud.githubusercontent.com/assets/984608/16918825/d0b8b40c-4ccc-11e6-8e7b-6c5f8340dde6.png)

**Comment by kyleshay** [comment]
what about removing the 'gather engrams' option, and eventually adding negation for search filters, so someone could do "is:engram not:exotic"

![screen shot 2016-07-18 at 11 17 48 am](https://cloud.githubusercontent.com/assets/424158/16919862/48f54c3a-4cd9-11e6-9306-ce4aa9bf87db.png)

**Comment by SunburnedGoose** [comment]
So adding filters as Loadouts?  Powerful.

**Comment by kyleshay** [comment]
I think that it would solve a lot of issues. Would probably want to also (eventually) have the option to do OR in search queries though... `(is:engram or is:glimmerconsumable) not:exoitc` :/

**Comment by brailsmt** [comment]
From a UX perspective, saved filters is probably the least attractive option.  I'm a power user, have perused the code for DIM, and often run straight from master, yet I have never used a search filter and did not even know it was an option for solving this problem.

**Comment by kyleshay** [comment]
A power user might actually see this as a better solution as it opens unlimited options, versus a single function button. 

The search filter function is brand new and we haven't yet figured outhow/invested time in how we can train users of its existence. Simplicity is key, of course.

**Comment by brailsmt** [comment]
Maybe.  When I'm playing I don't really want/care to do things like type in filters, the simplicity of a button is what I want.  Which is why I mentioned UX.  It would make my experience as a user better, sometimes I don't want to figure stuff out and just want a button, like when playing a video game.

**Comment by SunburnedGoose** [comment]
So what do you think of the mocks I made with the engrams in the dialog @brailsmt?

**Comment by brailsmt** [comment]
I think that the mock-up with the engram icons on the dialog are good, but I think that users may be confused by the cumulative nature of the icons and will think that clicking purple will copy just the purples, etc...

**Comment by SunburnedGoose** [comment]
They would learn quickly through experience.  Threshold of error is low as
it's easy to move back

**Comment by bhollis** [comment]
Please give me a.chance to catch up with this on Thursday when I'm done
traveling.

**Comment by SunburnedGoose** [comment]
Look forward to seeing what you have in mind @bhollis.  We're spitballin' ideas still.

**Comment by kyleshay** [comment]
> When I'm playing I don't really want/care to do things like type in filters

Which is why I suggested we have a save icon next to an active search to save it, and name it whatever you choose. Create your own custom 'move engrams' loadout/button/action.... maybe I wasn't clear

**Comment by kyleshay** [comment]
That way we're not forcing users to have a ton of iterations of actions, they can roll their own.

**Comment by brailsmt** [comment]
That's the thing though, I only use the application when I'm playing Destiny and I'm not interested in learning a new filtering language so I can save a search.  I think a feature to keep exotics in the vault is broadly applicable and would provide a but UX than a user by user saved search.

**Comment by bhollis** [comment]
@kyleshay I like the mockup of the options on the farming popup. As long as they don't get out of control, it could work. I don't know that "Exclude Exotics" belongs there, because people *want* to keep them in the vault.

@SunburnedGoose I like your mockups for adding the alternate options. We already have a precedent for doing this for other auto-loadouts (like the "undo" loadout). I'd propose we move that to text (colored icons aren't good for colorblind folks) and only have "Gather Items | Except Exotics". I think having every grade of filter is too confusing.

Complete +1 on "not" filters.

One thing I'd like to do soon (it's hinted in the filtering mega-issue), is to have saved/pinned searches. I love @kyleshay's idea of also being able to pin them, separately, as search-driven loadouts.

To aid in discovery of the search loadouts feature, I was also thinking that the same dropdown we use on the search box for "previous/saved searches" could show something a lot like the move popup that just says "move currently filtered items to: [character icons]". What do you think of that? I can mock it up in Photoshop a bit later if it's not clear.

As far as "locking" stuff to the vault, I think that's pretty interesting. Personally I'd group that under the "tags and notes for items" work, since it also depends on having a much bigger editing surface for items. It'll be a lot of work to really do it right, though - we should prevent those items from being auto-moved to make space, as well.

If everyone's cool with these ideas (or even just some of them), I'd propose breaking them out into separate issues.

**Comment by SunburnedGoose** [comment]
Atm, I am moving individual engrams from the vault to the character to avoid this issue. When I transfer an engrams to an inventory that is full, the app logic will move an engram (a similar item) out of the inventory to make room for my selected engram from the vault.  Sigh...

Now I have to make room manually.

**Comment by kain243** [comment]
Hello, goose asked me to leave a comment here. I made this thread : https://www.reddit.com/r/DestinyItemManager/comments/4wex65/feature_request_gather_blues_to_dismantle_them/

A lot of times, i end up with blues in lots of different spaces (vault, multiple characters etc). Similar to "gather engrams", itd be nice to gather all blues (and lower rarity items if applicable) to a single character so i can dismantle them all at once.

This could potentially be associated with the gather engrams feature as an option (i.e. gather engrams and blues).

The problem of having blues in the vault is especially prevalent when using the "engrams to vault" feature which makes space in every slot on your character, sometimes blues get pushed to vault before i see them to dismantle them.

**Comment by bhollis** [comment]
@kain243 

Try this:

1. Type "is:rare" in the filter box.
2. Open loadouts for your target character and select 'Search "is:blue"'.

All your blue items will go to that character. You can refine the search (is:blue light:<310) to grab only specific stuff.

**Comment by bhollis** [comment]
Resolving - we now have an option to keep exotics in the vault when gathering engrams. The rest of the suggestions go towards saved searches and search-based loadouts. See #397.

**Comment by brailsmt** [comment]
+1

Awesome!  Thank you!
