### ISSUE TITLE
Creating a Loadout with "Add Unequipped" puts all unequipped items into the "Equipped" slot.

### ISSUE THREAD

**Issue by bachmanetti** [DestinyItemManager/DIM#7010]
### DIM Version

Version 6.81.0.1000686 (beta), built on 9/5/2021, 11:02:47 PM

### Browser Details

Google Chrome is up to date Version 93.0.4577.63 (Official Build) (64-bit)

### OS Details

Windows 10

### Describe the bug

Reproduction steps:
1. Create a new Loadout
2. Click "Add Unequipped"
3. All Unequipped items will be moved to the Loadouts equipped slot, creating a vertical stack.
![image](https://user-images.githubusercontent.com/38538127/132172229-9156d9b2-696d-4093-a90f-bc3463a7b262.png)

Note: This does not happen if you already have items in the Loadouts "equipped" slot.

Expected behavior:
Clicking "Add Unequipped" should place items in the Loadouts "Unequipped" area.

**Comment by bhollis** [comment]
Thanks for noticing that. This must be such a popular feature to not have anyone point it out for like a year :-)

**Comment by bachmanetti** [comment]
> Thanks for noticing that. This must be such a popular feature to not have anyone point it out for like a year :-)

I actually missed this feature had been added till just before this season. I now use it whenever I am cleaning my vault or moving a lot of gear to help reset my character to my preferred "default" state.

The first two times when putting on the loadout it wasn't clear to me exactly what was happening, I thought I had maybe misclicked something. 

Thanks for the quick fix!
