### ISSUE TITLE
Loadout Optimizer - Compare Loadout > Save As 

### ISSUE THREAD

**Issue by inexorableAce** [DestinyItemManager/DIM#7013]
### DIM Version

Version 6.81.0.1000687 (beta), built on 9/6/2021, 11:53:06 AM

### Browser Details

Chrome Version 92.0.4515.159 (Official Build) (64-bit)

### OS Details

Windows 10

### Describe the bug

now that we can open a loadout in LO and it will apply the LO params (stat prefs, mods, etc) when using the Compare Loadout > Save As button to overwrite an existing loadout it's not saving the new params, just the items. So if you open it back up the mods and stat prefs will be from the old loadout and not the new one you just saved.

**Comment by bhollis** [comment]
Good catch, I've got some changes I want to make around re-opening a loadout anyway
