### ISSUE TITLE
Vendor Items out of Order

### ISSUE THREAD

**Issue by inexorableAce** [DestinyItemManager/DIM#7024]
### DIM Version

current beta and app

### Browser Details

Chrome Version 92.0.4515.159 (Official Build) (64-bit)

### OS Details

Windows 10

### Describe the bug

Currently the Vendors inventory items are out of order from what the game has. This goes for all vendors and the seasonal stull like the compass. We had a request to put the compass items in order and I fell down the rabbit hole of finding out all these vendor sections function differently sort wise at first just adding `compareBy((item) => parseInt(item.item?.id ?? '', 10)),`  to the `itemSort` var in ventorItems.tsx seemed to do the trick. but upon further testing that puts other things out of order. 
![image](https://user-images.githubusercontent.com/29002828/132567864-9eb4e6de-4706-4ee9-b206-ce96cfa9bf9d.png)

For example: 

Weapons from vendors seem to need to be sorted by itemCategoryHash then ID to be correct, while armors need typeName and then ID, rewards need something like tier then ID, etc. 

At any rate I think we should include the ID in this sort somewhere as it does get us closer, it's more now a question of, how do we or do we even want to make it all work in the correct order. I think the only way would be to separate item sorts based on conditions per type of thing a vendor is peddling.

**Comment by delphiactual** [comment]
```
const itemSort = chainComparator<VendorItem>(
  compareBy((item) => item.item?.bucket.name === 'Quests' ? item.item?.typeName : ''),
  compareBy((item) => item.item?.bucket.sort === 'Weapons' ? item.item?.itemCategoryHashes : parseInt(item.item?.id ?? '', 10)),
  compareBy((item) => item.item?.bucket.sort !== 'Weapons' ? item.item?.itemCategoryHashes : ''),
);
```

Fixes everything except for `Rank Rewards` as I cannot figure out how to test for them.
