### ISSUE TITLE
Feature Request: Display "Enemies Defeated" counter when comparing weapons

### ISSUE THREAD

**Issue by MothraTL** [DestinyItemManager/DIM#7028]
Include the "enemies defeater" counter when comparing weapons.
This would allow a user to see at a glance which weapons have been used and by how much.

Enemies Defeated is visible when inspecting a single weapon:
![image](https://user-images.githubusercontent.com/620107/132642465-406adcd9-f361-469b-afad-490a25d7dac6.png)

Current compare weapons display:
![image](https://user-images.githubusercontent.com/620107/132642693-3e77a20d-e853-407f-9f82-a8d5edc33c52.png)

**Comment by bhollis** [comment]
We won't be arbitrarily adding more stats to Compare just yet - you probably want to use the Organizer which has this column and more. Also consider marking your favorite weapons with the "favorite" tag.

**Comment by nev-r** [comment]
yeah with space at a premium in compare, we need to make decisions about information importance,
a masterwork icon border might be a good sign to click the icon in compare, and check its kill counter if you're worried
