### ISSUE TITLE
dupelower doesn't work on Vendor filtering

### ISSUE THREAD

**Issue by Reithan** [DestinyItemManager/DIM#7041]
### DIM Version

6.81.0

### Browser Details

Chrome 93.0.4577.63 (64-bit)

### OS Details

Windows 10

### Describe the bug

Filtering vendors with is:dupe seems to work as expected, but trying to filter by is:dupelower doesn't seem to work properly.
For example, 1100 power weapons at Banshee-44 that I already have copies of do not show up. Conversely, as expected -is:dupelower won't filter them out.

**Comment by bhollis** [comment]
That's right, dupelower only considers items in your inventory.
