### ISSUE TITLE
Loadout Optimizer Unable to Find Builds, Locks at T10 Strength

### ISSUE THREAD

**Issue by jblenman** [DestinyItemManager/DIM#7044]
This is in the beta version.  Without selecting or changing anything, Loadout Optimizer is locking a stat at T10.  If I attempt to lower that stat, it doesn't change.  If I ignore that stat, it still doesn't find any builds.  I have to ignore another stat for it to find any builds with minimum stats and no mods picked or equipment locked.  

I have had it start with stats already at higher tiers, but I have been able to lower them to get the build back to a default state.  I assumed it had just saved the values I used previously.  This time it is locking Strength at 10 and I have to ignore both that stat and Resilience to get it to find any builds.

![dim_lo_issue_1](https://user-images.githubusercontent.com/33501993/133007410-2869dbf4-30a6-4b13-9246-f0695c2adf9a.png)
![dim_lo_issue_2](https://user-images.githubusercontent.com/33501993/133007411-56331084-d2d1-4c15-9b44-37b86a5abb57.png)
![dim_lo_issue_3](https://user-images.githubusercontent.com/33501993/133007413-5d23c7de-ed29-44c0-b4b9-7f68787c303b.png)

**Comment by bhollis** [comment]
And it doesn't do this on the app version?

**Comment by bhollis** [comment]
I assume this is because in beta we now remember your stat range settings where we didn't before.

**Comment by jblenman** [comment]
That was quick!  Thanks!
