### ISSUE TITLE
Organizer CSS Issue - Perks Mods & Shaders doesn't occupy entire cell height

### ISSUE THREAD

**Issue by nev-r** [DestinyItemManager/DIM#7047]
style regression of unknown origin:

![image](https://user-images.githubusercontent.com/68782081/133066564-d275c80c-d24d-413f-ba74-a75a6a2f9fe0.png)

**Comment by bhollis** [comment]
What columns do you have enabled? I'm not seeing this happen.

**Comment by nev-r** [comment]
happens with as little as name, icon, and PM&S. chrome windows.
![image](https://user-images.githubusercontent.com/68782081/133203949-9be70aab-aeaa-41df-8239-1652e6711120.png)

**Comment by nev-r** [comment]
![2021-09-13_23-10-42](https://user-images.githubusercontent.com/68782081/133204282-26916437-cad4-4512-95d8-2b239063b035.gif)

seems like this cell isn't expanding to full available height??

**Comment by bhollis** [comment]
That'd be my guess. Let me try to repro with some different columns.

**Comment by cfreear** [comment]
This seems to be an issue with Chrome (doesn't happen in FF), setting `column-count` on the perks, mods & shaders column causes the grid cell height to collapse but my google-fu has failed me and I can't figure out why.

Giving the column `height: 100%` and `box-sizing: border-box` fixes it but this feels like a "bandaid" solution.

![image](https://user-images.githubusercontent.com/619726/133889043-927b9580-4884-4243-8a49-1d5dbd382283.png)
