### ISSUE TITLE
DIM is broken.  Thanks Bungie.

### ISSUE THREAD

**Issue by brailsmt** [DestinyItemManager/DIM#705]
I am signed into Bungie.net, but when I attempt to transfer an item it tells me I must sign in to Bungie.net.  In an effort to workaround this issue, I signed out of Bungie.net and signed back in.  I get the exact same error message when I try to xfer an item between characters.

DIM version:  3.8.3

**Comment by kyleshay** [comment]
Thanks for the report. Waiting on a fix by bungie

**Comment by brailsmt** [comment]
Screenshots of the issue: 
<img width="1552" alt="screen shot 2016-07-20 at 15 36 57" src="https://cloud.githubusercontent.com/assets/551010/17002219/f052fae2-4e8f-11e6-8b0b-08e8791dae16.png">
<img width="1552" alt="screen shot 2016-07-20 at 15 36 54" src="https://cloud.githubusercontent.com/assets/551010/17002235/f8dce6be-4e8f-11e6-8c5e-9e85276942dd.png">

**Comment by brailsmt** [comment]
I attempted to downgrade to the v3.6.2 branch, but 'grunt css' fails with:
```
cwd: ~/dev/DIM  ((v3.6.2) %)
[mb013619]$ grunt css
Loading "sass.js" tasks...ERROR
>> Error: Node Sass does not yet support your current environment: OS X 64-bit with false
>> For more information on which environments are supported please see:
>> TODO URL
Warning: Task "sass" not found. Use --force to continue.

Aborted due to warnings.
```

**Comment by brailsmt** [comment]
I used the --force option, enabled the local extension and the same error appeared.  Basically confirming an issue with Bungie.net.

**Comment by brailsmt** [comment]
Screenshot for completeness:
<img width="1552" alt="screen shot 2016-07-20 at 15 46 26" src="https://cloud.githubusercontent.com/assets/551010/17002490/2b6867b0-4e91-11e6-96c6-6323b3f3c1a4.png">

**Comment by mykkenny** [comment]
Also have this issue. Chrome version 52.0.2743.82 m if it helps, but sounds like it may be a Bungie issue.

**Comment by brailsmt** [comment]
Yup, I confirmed this was not introduced by the 3.8.3 update.  This is an issue with Bungie.net, not DIM.
