### ISSUE TITLE
Uncommon type???

### ISSUE THREAD

**Issue by nev-r** [DestinyItemManager/DIM#7052]
https://github.com/DestinyItemManager/DIM/blob/7c180eec111a304c5043bf901e8e900583c5f6db/src/app/farming/actions.ts#L140

**Comment by nev-r** [comment]
@bhollis do you think this is supposed to be `i.tier` ?

**Comment by bhollis** [comment]
Definitely.

BTW at one point I tried to change this to the tier enum from the API, but it is *wacky* and does not line up with the words you'd actually use. We should probably create our own that lines up in value but not in name.
