### ISSUE TITLE
Loadout Optimizer should show an error when stats are not available from API

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#7058]
![image](https://user-images.githubusercontent.com/4798491/133662731-72dbaee3-4588-4e6e-a276-65d827cdb154.png)

**Comment by ryan-rushton** [comment]
Would we just check to see if stat definitions exist?

**Comment by bhollis** [comment]
Well the definitions will always exist. We could check whether the profile component is coming back, or try and rely on the bungie.net status API...
