### ISSUE TITLE
Provide a stable default sort in Compare

### ISSUE THREAD

**Issue by inexorableAce** [DestinyItemManager/DIM#7059]
When you pull to current character from the new compare sometimes it rearranges the items in the compare sheet. This gets pretty confusing and could cause one to pull the wrong item into their inventory for deletion. I'll grab a video in the morning.

**Comment by bhollis** [comment]
Yeah it's because we don't have a default sort. We should have one.

**Comment by nev-r** [comment]
big to little dimitem.id sort would be nice. there should already be a comparator for it
