### ISSUE TITLE
Lost a weapon during a move

### ISSUE THREAD

**Issue by kcostello2000** [DestinyItemManager/DIM#7062]
### DIM Version

6.82.0

### Browser Details

Chrome 93.0.4577.82 

### OS Details

Windows 10

### Describe the bug

I was moving my Threaded Needle from my Titan to my Hunter and it disappeared.  I was simply dragging it from one character to another.  It appears that deleted it.

I do see in the devtools console something about discarding 15204 duplicate rolls from wish list.  Could something odd have happened and it got deleted?

### Logs

```shell
app] DIM v6.82.0 (release) - Please report any errors to https://www.github.com/DestinyItemManager/DIM/issues
instrument.ts:129 [dim sync] globalSettings Object
instrument.ts:129 [wishlist] Discarded 15204 duplicate rolls from wish list
(anonymous) @ instrument.ts:129
log.ts:44 Parse wish list: 177.97802734375 ms
instrument.ts:129 [wishlist] Refreshed wishlist, but it matched the one we already have
log.ts:44 Load manifest: 2899.42724609375 ms
instrument.ts:129 [dim sync] Saving profile data to IDB
log.ts:44 Process inventory: 103.965087890625 ms
log.ts:44 Inventory state update: 626.84619140625 ms
log.ts:44 Process inventory: 79.5263671875 ms
log.ts:44 Inventory state update: 155.527099609375 ms
log.ts:44 Process inventory: 98.2470703125 ms
log.ts:44 Inventory state update: 209.27001953125 ms
log.ts:44 Process inventory: 120.64404296875 ms
log.ts:44 Inventory state update: 284.59619140625 ms
log.ts:44 Process inventory: 89.5927734375 ms
log.ts:44 Inventory state update: 185.055908203125 ms
instrument.ts:129 [dim sync] Saving profile data to IDB
log.ts:44 Process inventory: 82.5869140625 ms
log.ts:44 Inventory state update: 163.656005859375 ms
instrument.ts:129 [dim sync] Saving profile data to IDB
log.ts:44 Process inventory: 110.984130859375 ms
log.ts:44 Inventory state update: 242.22802734375 ms
```

**Comment by kcostello2000** [comment]
Add a little more detail I should have put in. I was dragging and dropping if from my Titan to my Hunter. It was the current active weapon on the Titan. I had also just successfully moved a hand cannon and a bow from the Titan to the Hunter.

**Comment by bhollis** [comment]
https://destinyitemmanager.fandom.com/wiki/Category:FAQ#DIM_deleted_my_item.21

Your item is somewhere! Search for it.

**Comment by kcostello2000** [comment]
Hehe...I did. I used the search option and it is no where in my inventory.  No where in the vault nor on any of my other characters. I have since gotten another one from a focused engram. But the original one is no where that I can find it.

And to be certain I search again just now.  The only one I have is the one I just got from the engram.

**Comment by bhollis** [comment]
Well I'm afraid we can't help besides the info in that FAQ. DIM cannot delete items wither intentionally or by mistake, so either it didn't get deleted by the move (e.g. it's still there or you deleted it ingame) or Bungie has a bug in their API and you should contact Bungie Support. Make sure to look in your Application History to see where the moves happened.

**Comment by kcostello2000** [comment]
Not a problem. It was not something that I was not able to get again through the engram. I had thought about reporting it to Bungie also, but I wanted to go here first.  Appreciate the feedback and I will try putting something into Bungie Help.
