### ISSUE TITLE
Escape key should only dismiss the topmost sheet or popup

### ISSUE THREAD

**Issue by irons** [DestinyItemManager/DIM#7063]
### DIM Version

6.82.0

### Browser Details

Safari 605.1.15

### OS Details

iPadOS 14.8

### Describe the bug

I love the new ability to bring up an item’s full detail view from the Compare interface, for quick access to wishlist notes, transfer functionality, and tagging keyboard shortcuts. 

After hitting one of those shift-[number] tagging shortcuts, I usually tap escape to dismiss that modal, but in this context, doing so also dismisses the Compare UI. That’s unexpected, and if I do want to dismiss both, I expect to hit Escape a second time.

This behavior is consistent on a Mac running Chrome 93.0.4577.82 and Safari 14.1.2 (14611.3.10.1.5). Thanks for your time.

**Comment by irons** [comment]
This same issue also applies to the mod/masterwork/shader/infuse modals that can surface on top of the Compare UI. But when there’s a stack of three (compare UI -> full item details -> mod overlay), the escape key has no effect.

The escape key also does not dismiss the Compare UI in isolation. This seems like a bug; happy to file a separate issue on that if you’d prefer.

**Comment by bhollis** [comment]
Not so much a bug as something that works very naively and we haven't yet put in the effort to make it correct. "Esc" dismisses any and all sheets on the page.

**Comment by nev-r** [comment]
> The escape key also does not dismiss the Compare UI in isolation

this is not universally true, but the dropdowns and buttons swallow keypresses if they're focused

**Comment by MrTact** [comment]
I started to take a look at this. Here's what I'm thinking:

- Have some top-level component register for esc key handling via the useHotKey hook. This could be an existing component (App?) or a new component specifically for this purpose which we wrap around a big chunk of the component tree.
- Create a new hook to register/unregister open panels with this component, which maintains them in a stack
- In ItemPopupContainer (which appears to be the only components that currently registers its own ESC key handling), instead have it call the hoook to register with the panel stack manager via the new hook when the container is opened.
- In the panel manager, 
  - Registering a panel pushes it to the top of the stack
  - Deregistering a panel (e.g. when the close element on the panel itself is clicked) pops it off the stack.
  - Handling an ESC keydown event sends onClose to the panel. The panel sends deregister as part of its onclose, so it gets cleanly removed from the stack whether you hit ESC or click the panel close button.
- Tapping off the current top panel acts like pressing the ESC key. (Not exactly sure how this works, still digging into touch interface handling)
- Perhaps throw up a full-screen scrim component to eat mouseclicks on panels beneath the topmost? (This prevents you from clicking the close button for a parent control, for example)
