### ISSUE TITLE
Tarantula is showing as having 6 magazine but it's 5

### ISSUE THREAD

**Issue by wanton7** [DestinyItemManager/DIM#7064]
### DIM Version

Version 6.82.0 (release), built on 9/13/2021, 5:02:52 AM

### Browser Details

Version 93.0.4577.82 (Official Build) (64-bit)

### OS Details

Windows 10

### Describe the bug

Tarantula is shown as having 6 magazine but in-game it has 5 magazine. I'm not sure if this is something on your side or is API returning wrong information
![tarantula_dim](https://user-images.githubusercontent.com/1009930/133922262-59267162-0b09-4e39-a43c-2e20b3189dbe.png)
![tarantula_in-game](https://user-images.githubusercontent.com/1009930/133922335-0a53f4b3-fcc9-47dd-8ec6-5fde0392880a.png)

**Comment by nev-r** [comment]
https://github.com/DestinyItemManager/DIM/issues/6929#issuecomment-885977791

**Comment by bhollis** [comment]
For future searchers: https://destinyitemmanager.fandom.com/wiki/Category:FAQ#Why_is_the_Magazine_stat_in_DIM_different_from_in_game.3F

**Comment by wanton7** [comment]
How about adding a list of actual magazine sizes for weapons that are calculated wrong? Or at least way for user to override magazine size for specific weapons?

**Comment by delphiactual** [comment]
no
