### ISSUE TITLE
Add Subclass to Loadout Optimizer

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#7067]
For share-able builds, there's often a specific Subclass (and subclass configuration) associated with that build. Today this is often implicit in the choice of Exotic, but Darkness subclasses introduced mods-for-subclasses, which can be incorporated into both the total stats and the saved mods in the loadout. In the future, Light subclasses will get a similar treatment. We can probably skip supporting talent grid (subclass path) selection given that they will be reworked.

**Comment by ryan-rushton** [comment]
Did we want to do this in the Opimizer or should this be a thing in Loadouts? If both we need yet another Drawer to share across the two. The number of drawers is getting quite high, I wonder if there is something else we can do in the UI to make all this flow a little nicer.
