### ISSUE TITLE
item modal lock icon links to bungie and doesn't toggle

### ISSUE THREAD

**Issue by chuckreynolds** [DestinyItemManager/DIM#707]
Using v3.8.3 in Chrome v51.0.2704.106 (64-bit) on mac. 
Clicking the lock icon doesn't toggle lock/unlock and links to _blank bungie.net

**Comment by chuckreynolds** [comment]
okay maybe it's a bigger issue or localized because I can't even drag items from the vault to a character... everything i do just opens a new bungie.net tab

**Comment by SunburnedGoose** [comment]
I'll loop back on this after the API issues with Bungie have stabilized.

**Comment by chuckreynolds** [comment]
yeah confirmed it was the API issue.  So I'll close this.  BUT.... I'd vote for some sort of error notification that says "`Bungie's API is having problems right now; we're on it`" sort of thing instead of it breaking. just a thought. Cheers guys!

**Comment by SunburnedGoose** [comment]
There is no way for us to get a signal into DIM remotely atm. It's a free app so we're a bit cost sensitive with regard to hosting etc.

**Comment by chuckreynolds** [comment]
AH... fair enough. Well THANK YOU guys... it's an awesome product and for that I just threw you a $100 on paypal. Cheers!

**Comment by kyleshay** [comment]
amazing! :O thank you @chuckreynolds!! :)
