### ISSUE TITLE
Armory followups

### ISSUE THREAD

**Issue by RenierZA** [DestinyItemManager/DIM#7073]
### Proposed change

I love the new item detail popup.

Please consider adding the following features/fixes:
- The link to DestinyTracker used to include all the selected perks too. Please add this again.
- The new link to Light.gg could also include the perks.
- Please add a link to D2 Gunsmith (with perks) too. This is really useful for checking range.
- Please highlight the perk icons of the current item.
- If possible highlight the wishlisted perks similar to how Little Light does.

### How does this fit into your workflow?

I often click on a weapon and then click through to see what the possible god rolls are according to other sites. I also wrote my own TamperMonkey script to view the item in D2 Gunsmith to see the calculated range. (Which of course now no longer works).

**Comment by bhollis** [comment]
Thanks! We're definitely planning more here, and what you're seeing is just the first iteration.

> Please highlight the perk icons of the current item.
> The link to DestinyTracker used to include all the selected perks too. Please add this again.

For sure, perks are next up!

> The new link to Light.gg could also include the perks.

Can it? Do you know the URL format? I couldn't get them to select specific perks, and you can't click on perks in light.gg either to share rolls.

> Please add a link to D2 Gunsmith (with perks) too. This is really useful for checking range.

I was planning on just implementing everything D2 Gunsmith does. The range / reload stats are an interesting bit that we'd need to figure out the source of data for, and get someone to commit to keeping them up to date as the game changes.

> If possible highlight the wishlisted perks similar to how Little Light does.

Lots of stuff coming for wishlists as well. This page is really here so we can do more with our wishlists.

**Comment by RenierZA** [comment]
Ah that's great news. Thank you.

Looks like I'm mistaken on linking with perks to Light.gg, I just made an assumption after looking at DestrinyTracker and D2Gunsmith.

The range calculator on D2Gunsmith is their best feature. I assume they figured out the formulas themselves, so it might be a pain to maintain.  Another nice feature of D2Gunsmith is they give more information about the perk rather than just the API text.

For example for Kill Clip:
> Has a duration of 5 seconds. Marksman's Dodge and Wraithmail Metal (Dragon's Shadow) can also trigger this perk.
•  Precision » 33%
•  Non-precision » 30%

So linking to D2 Gunsmith would still be nice, unless all this information can be duplicated.

FYI this was how I converted the DestinyTracker URL to a D2Gunsmith URL:
```
const itemNameElm = itemPopup.querySelector('a[href^="https://destinytracker.com/"]');
const url = itemNameElm.href;
const itemId = url.match(/\/items\/(\d+)\?/i)[1];
const perks = (url.match(/perks=(.+)/i)[1]).split(',');
const newP = [perks[1], perks[2], perks[3], perks[4], perks[7], perks[6]].join();
const newURL = 'https://d2gunsmith.com/w/' + itemId + '?s=' + newP;
```
The perks are in a slightly different order.

**Comment by bhollis** [comment]
Gotcha. Yeah we've talked with a few people about those extra stats, and they're coming from hand-maintained Google Spreadsheets based on people measuring numbers in videos and carefully reading TWABs... not necessarily something we want to sign up to support.

**Comment by RenierZA** [comment]
Thank you very much for the link to Gunsmith.  And the perks look great too.

One small request. (I know this issue is closed now). The armory doesn't display your masterwork. So that also means the masterwork is not included in the DIM permalink, DestinyTracker link, or Gunsmith link.

Is this possible?
