### ISSUE TITLE
[JP] Warlock's name on the Loadout screen inhibits clicking

### ISSUE THREAD

**Issue by devdyaya** [DestinyItemManager/DIM#7074]
### DIM Version

6.83.0 (release), built on 2021/9/20 11:04:48

### Browser Details

Chrome 93.0.4577.82（Official Build） （x86_64）

### OS Details

Mac OS X Big Sur

### Describe the bug

We have identified a problem where the "Mobility"(可動性) selector cannot be clicked on the loadout screen when the DIM language is set to Japanese.

This may be due to the fact that the name of the Warlock in the Japanese language setting is separated by a line depending on the font size and overlaps the Mobility selector.

*I tried changing the font size of the warlock from 20px to 19px and it became clickable.

![image](https://user-images.githubusercontent.com/8044800/134035164-6f247422-443e-4a0c-9f49-a2314dbfe5c6.png)

**Comment by nev-r** [comment]
thank you! this is fixed in beta now

**Comment by devdyaya** [comment]
Thank you!
I just checked with beta too, and it confirms the Issue is resolved!
