### ISSUE TITLE
Add sort by archetype / RPM

### ISSUE THREAD

**Issue by VoxMaro** [DestinyItemManager/DIM#7076]
Since you can already sort by weapon type, sorting further by archetype/intrinsic perk/rpm for weapons on the inventory screen would be convenient. In theory it seems relatively simple to do, as weapon rpm is already a number value in DIM.

**Comment by bhollis** [comment]
Check out the Organizer for all your sorting needs. In general we're avoiding adding every sort type to inventory because that's not what it's for, and sorting on properties that aren't visible on the item tile is hard to make use of.

**Comment by Revadike** [comment]
> Check out the Organizer for all your sorting needs. In general we're avoiding adding every sort type to inventory because that's not what it's for, and sorting on properties that aren't visible on the item tile is hard to make use of.

Can we replace archetype by RPM? We're getting archetypes now that are basically other archetypes under the hood, but with some difference, like the new vent weapons. It would be really nice to sort by RPM instead (or both). Usually higher RPM is better too.

**Comment by Revadike** [comment]
Also, I don't see a way to use multiple sort priorities in the organizer

**Comment by bhollis** [comment]
Shift click
