### ISSUE TITLE
Armory doesn't display masterwork plugs in wishlists

### ISSUE THREAD

**Issue by RenierZA** [DestinyItemManager/DIM#7077]
### DIM Version

Version 6.83.0 (release), built on 20/09/2021, 04:04:48

### Browser Details

Microsoft Edge Version 93.0.961.52

### OS Details

Windows 10

### Describe the bug

I'm using the default voltron wishlist.  I noticed on the new item detail popup that one of my Fatebringer rolls are shown in the wishlist, but it is not marked in DIM and the perks are not highlighted.

![image](https://user-images.githubusercontent.com/1150349/134119979-f927b2de-4770-46cd-90b7-72892197d7dd.png)

Here are the corresponding lines in voltron.txt:
```
// Fatebringer
//notes:PVP recommended roll: Full Bore (MKB)|tags:Sharditkeepit Community

dimwishlist:item=2171478765&perks=3250034553,106909392,3038247973,47981717,684616255
dimwishlist:item=2171478765&perks=202670084,106909392,3038247973,47981717,684616255

dimwishlist:item=2171478765&perks=3250034553,106909392,3038247973,47981717,2697220197
dimwishlist:item=2171478765&perks=202670084,106909392,3038247973,47981717,2697220197
```

It seems they also list the masterwork. Does that mean you have to have the correct masterwork for it show marked in DIM?  The item detail popup does not show this on the rolls it is showing.

**Comment by bhollis** [comment]
Hmm, I don't think having masterwork in a wishlist is a good idea.

**Comment by RenierZA** [comment]
Found another example:

![image](https://user-images.githubusercontent.com/1150349/134124379-ca18d0c5-ddac-4fd7-b683-645afc98e8a8.png)

```
// Fatebringer
//notes:Sharditkeepit Community: PVE recommended roll

dimwishlist:item=2171478765&perks=1482024992,106909392,3038247973,4104185692,684616255
dimwishlist:item=2171478765&perks=1482024992,106909392,3038247973,4104185692,178753455
dimwishlist:item=2171478765&perks=1482024992,106909392,3038247973,4104185692,2697220197
dimwishlist:item=2171478765&perks=1482024992,106909392,3038247973,4104185692,758092021
```

**Comment by nev-r** [comment]
> It seems they also list the masterwork. Does that mean you have to have the correct masterwork for it show marked in DIM?

yes. thumbs ups are contingent on _all_ things in a wishlist line matching

**Comment by 48klocs** [comment]
Adding a little extra flavor, we do (did?) remove some odds and ends (shaders and ornaments, maybe MWs?) from URL-based imports, but expert mode lets you get as particular as you want.

This is why in the voltrons, I include recommended MWs in the notes rather than in the rolls.

**Comment by bhollis** [comment]
I think OP is claiming these rolls that include the masterwork are from voltron

**Comment by nev-r** [comment]
they are from voltron

**Comment by nev-r** [comment]
masterworks are almost precisely as impactful as barrels/mags/etc and are no more impactful on the number of permutations than barrels, so they have a completely rightful place in wishlists.
treating them as first class citizens of wishlists might actually help with not marking every dang gun as a 'godroll'

**Comment by RenierZA** [comment]
Even when you have the correct masterwork, it still won't mark the weapon unless you masterwork it all the way to 10. A masterwork below 10 has a different hash, and voltron only lists the hash masterwork=10.

Example:
![image](https://user-images.githubusercontent.com/1150349/134296462-11d2a9d0-a6e6-4d87-bd22-2e740784f8fe.png)

Voltron.txt:
```
// Finite Impactor
//notes: sharditkeepit Community - PVP recommended roll - Eye of the Storm (Controller)
dimwishlist:item=3813153080&perks=1926090094,1885400500,1570042021,699525795,684616255
dimwishlist:item=3813153080&perks=1926090094,1885400500,1570042021,699525795,2697220197
```

My roll with range masterwork 4:
https://d2gunsmith.com/w/3813153080?s=1926090094,1885400500,1570042021,699525795,150943602,0

Voltron listing with range masterwork 10:
https://d2gunsmith.com/w/3813153080?s=1926090094,1885400500,1570042021,699525795,2697220197,0

Personally I would prefer an option to exclude masterwork. But if it's included then it's a problem that it won't show up until you fully masterwork it. The wishlist is there to help decide if you should fully masterwork it.

**Comment by delphiactual** [comment]
I'm sure I can throw something together in `d2ai` to make grouping of MW's (e.g. Level 1 - Level 10) happen, just need to figure out call it out on wishlist if desired.

**Comment by 48klocs** [comment]
On the default list side of things, I removed the references to MW perks that were in there - sorry I didn't catch that the first time around.

Wish lists do support calling for MWs; I don't have strong feelings about them one way or another, but I'm not intentionally including them in the default lists until I update the form we recognize + translate the existing lists to be more JSON-y.

**Comment by bhollis** [comment]
Yeah we'd need a specific masterwork callout that recognizes all 9 masterwork mods for a stat without repeating the wishlist.

**Comment by RenierZA** [comment]
> On the default list side of things, I removed the references to MW perks that were in there - sorry I didn't catch that the first time around.

Thank you very much. My wishlist matched items went from 130 to 139, including the examples above.

**Comment by bhollis** [comment]
As another twist, it appears that we aren't including the masterwork socket when building the item from definitions...

**Comment by bhollis** [comment]
We can consider adding "recommended masterwork" to https://github.com/DestinyItemManager/dim-api/pull/70, but until that's adopted wishlists aren't going to support masterworks.
