### ISSUE TITLE
Randomise weapon doesn't randomise subclass

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#7078]
### DIM Version

beta

### Browser Details

Chrome

### OS Details

Win10

### Describe the bug

If you select Randomise (Weapon) the alert popup says that it will randomise weapons and subclass.  However it only randomises weapons.  Either the alert needs to reflect it's just weapons, or randomise needs to also change subclass.

Equipped void subclass on a hunter if it matters.

**Comment by nev-r** [comment]
which, to be fair, :grinning:
