### ISSUE TITLE
organizer cell height issues

### ISSUE THREAD

**Issue by inexorableAce** [DestinyItemManager/DIM#7081]
### DIM Version

Version 6.83.0.1000731 (beta), built on 9/21/2021, 7:34:09 PM

### Browser Details

Chrome Version 92.0.4515.159 (Official Build) (64-bit)

### OS Details

Windows 10

### Describe the bug

seems to only happen with armors. the empty cells are not cover the full height of the cell so you see the background through it making it look like the columns are off 
![image](https://user-images.githubusercontent.com/29002828/134271376-2c8106d2-624b-4a1b-b4c6-7e58670a5d6f.png)

**Comment by bhollis** [comment]
Duplicate of https://github.com/DestinyItemManager/DIM/issues/7047
