### ISSUE TITLE
LO resets when scrolling on iPad

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#7087]
https://reddit.com/r/DestinyItemManager/comments/psvib3/cant_scroll_optimizer_on_ipad/

**Comment by jbozanowski** [comment]
Appears to work fine now (DIM beta on iPad Air 4th gen).

https://imgur.com/a/pBbG7k7

**Comment by bhollis** [comment]
Nice. We didn't do anything to fix it.

**Comment by jbozanowski** [comment]
iOS version changed for me in the meantime, I was experiencing it on 15.0 before and this recording is on 15.0.1, so maybe that was it.

**Comment by bhollis** [comment]
Yeah Safari is a real special browser

**Comment by helianth** [comment]
Still experiencing issue on 4th Gen iPad Pro on 15.1 as of this week 12/12/2021
