### ISSUE TITLE
Vendor page has a lot of empty space

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#709]
What do you guys think? It seems to me that there's a lot of empty space here:

<img width="791" alt="screen shot 2016-07-21 at 10 19 42 pm" src="https://cloud.githubusercontent.com/assets/313208/17047304/44770c60-4f91-11e6-85b5-fef0d2ec6f22.png">

I also noticed that it's off-center.

/cc @ericnelson0

**Comment by bhollis** [comment]
Meanwhile here, the spacing/alignment is inconsistent and sometimes too cramped:

<img width="115" alt="screen shot 2016-07-21 at 10 20 53 pm" src="https://cloud.githubusercontent.com/assets/313208/17047317/6ada83be-4f91-11e6-99a2-f4d63e949dd8.png">

I really think this is great work, I'm just thinking we could do another pass on look & feel.

**Comment by ericnelson0** [comment]
Completely agree on the second pass and about the empty space. I'd love to hear any ideas on the look and feel. I'll try to iterate on the UI tomorrow.

**Comment by bhollis** [comment]
Closing in favor of #741.
