### ISSUE TITLE
Detail info on possible max light shows two exotic weapons for loadout

### ISSUE THREAD

**Issue by belykhk** [DestinyItemManager/DIM#7095]
### DIM Version

Version 6.84.0 (release), built on 27.09.2021, 05:04:01

### Browser Details

Chrome 93.0.4577.82

### OS Details

Windows 10 2004 build 19041.1237

### Describe the bug

When i clicked on maximum power of gear value under non-main characters (for me it is Warlock and Hunter), DIM shows me in loadout to equip exotics in secondary and heavy slots. 

Video: https://youtu.be/tmnPZ2L994I

**Comment by inexorableAce** [comment]
Correct, your maximum power that determines your drops does not have the one exotic limitation. That's what that is showing you, and how the fraction is determined. 

If you want your max power loadout you should search `is:maxpower`

**Comment by inexorableAce** [comment]
the card is telling you where you need to drops for power not a loadout. again both the maxpower search and the maxpower button in the character dropdown will do the loadout.

**Comment by delphiactual** [comment]
https://destiny-power-bars.corke.dev/
