### ISSUE TITLE
Tagging gear for PVP or PVE

### ISSUE THREAD

**Issue by crazybobbles** [DestinyItemManager/DIM#7099]
### Proposed change

At a glance icons to indicate whether your gear is indented for PVP or PVE. Can embed with existing tag system which already displays icons on the gear. Could even pick up PVE / PVP intentions via kill tracker settings

### How does this fit into your workflow?

For weapons: when you own duplicates of the same weapon (e.g. Fatebringer) you need to click into the icon to figure out whether or not it's your pvp gun or your pve gun. Having the tag would remove that additional step.
For builds, you can at a glance move gear into your vault based on whether gear is intended for PVP or PVE.

**Comment by bhollis** [comment]
Where on the icon would you put it?

**Comment by bhollis** [comment]
Keep in mind this: https://github.com/DestinyItemManager/DIM/wiki/Frequently-Requested-Features#add-more-tag-values

**Comment by crazybobbles** [comment]
Would it work if we could customise the tags instead? I personally just lock and unlock gear I want to dismantle so have never used the prebuilt tags. Right now several others just recommended me to just repurpose the existing tags as PVP / PVE (hence submitting the feature request in the first place) but if the rationale is already stated in the past then I guess I'd work at using a style to modify the content: value of the existing ones and essentially customise it myself

**Comment by bhollis** [comment]
Sounds good
