### ISSUE TITLE
Hide past seasonal challenges

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#7102]
### Proposed change

Allow users to toggle hiding past seasons' challenges from the Seasonal Challenges tab. I'm not sure if there's any real value to them - should this be an option or not?

### How does this fit into your workflow?

 https://twitter.com/bhollis/status/1443274475378823175

Folks who didn't finish all the challenges last season don't necessarily care about them this season.

**Comment by inexorableAce** [comment]
Search works for quests, not for seasonal challenges or milestones though. I wonder if that's because of api limits or something else? 

But yeah `season:current` should work for this kinda thing I'd imagine.
