### ISSUE TITLE
Add rewards to bounty guide

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#7103]
### Proposed change

It might be nice to be able to include the reward type in the bounty guide - at least limited to things like seasonal currency or bright dust.

### How does this fit into your workflow?

If a user wants to focus on bright dust, pinnacles, etc, they could use this to do it.

**Comment by philkernick** [comment]
I have another usecase for this as well.

Towards the end of the season, many like to stack bounties, but want to preferntially stack those that offer the most XP.

I'm imagining a filter for the vendor screen like:
reward:xp
reward:xp+
reward:xp++

This could extend your original proposed change:
reward:brightdust

**Comment by Revadike** [comment]
> I have another usecase for this as well.
> 
> Towards the end of the season, many like to stack bounties, but want to preferntially stack those that offer the most XP.
> 
> I'm imagining a filter for the vendor screen like: reward:xp reward:xp+ reward:xp++
> 
> This could extend your original proposed change: reward:brightdust

I came here to suggest exactly this. Should I make a new issue about it?

**Comment by LuscaMamede** [comment]
Maybe something like destinyrecipes.com do, u can track everything regardless the new season and how properly be prepared.
