### ISSUE TITLE
Popularity Counter

### ISSUE THREAD

**Issue by DarkArc** [DestinyItemManager/DIM#7104]
### Proposed change

It would be potentially useful if every item and roll was counted globally across all users, then that number could be sorted on.

### How does this fit into your workflow?

I think having such a counter would be useful for determining what's a junk roll vs what's worth keeping. Presumably the god and good rolls are statistically elevated.

**Comment by bhollis** [comment]
Putting aside the expense of storing and maintaining that number (which would be real $$), my gut says that you wouldn't get particularly great info from this - most people don't know what to keep beyond what's in the wishlist, so the data would either be super noisy or just be the wishlist picks. A better approach would be to join those data with information about activity history and ranking and try to figure out what rolls are used by for example successful PvP players, but that'll basically just track the well known meta and would skew towards weapons that require high skill to use which may not be for everyone. 

If you want a version of this go to light.gg, which has a perk popularity chart per weapon that I personally find useless.

**Comment by DarkArc** [comment]
> Putting aside the expense of storing and maintaining that number (which would be real $$)

I'm not sure this would be much more than a mapping of items to numbers; that should be pennies-low dollars worth of database usage. Assuming processing occurs server side and can't be manipulated by clients, you shouldn't have to maintain table rows for every item in every player's inventory if that's what you're thinking.

> most people don't know what to keep beyond what's in the wishlist, so the data would either be super noisy or just be the wishlist picks.

Stuff that's not in a wishlist that players like should still standout in that dataset, because the player wouldn't destroy that item. With enough data, you should see results.

> A better approach would be to join those data with information about activity history and ranking and try to figure out what rolls are used by for example successful PvP players, but that'll basically just track the well known meta and would skew towards weapons that require high skill to use which may not be for everyone.

This does sound interesting. I'm not sure the "well known" meta is that "well known" or established. I certainly couldn't list off the current PvP meta/meta choices as someone that falls between casual and hard-core gaming.

> If you want a version of this go to light.gg, which has a perk popularity chart per weapon that I personally find useless.

This looks interesting, particularly looks like they have a review system which I'd also be a fan of seeing; kind of thought DIM was going to have something like that only to realize it's just a D1 armor rating feature.

**Comment by inexorableAce** [comment]
We had user ratings before. Wishlists are a way to do that with exactly what you want instead of what others say. And if you don't know what you want, the default wishlist is the same thing as user ratings; someone else opinion on something. 

I don't see how storing a lot of data has any value of what wishlists already offer.

**Comment by DarkArc** [comment]
The wishlist are great, but they lack granularity without reading, and looking through my vault very little had feedback either way. I'm trying to clean up my vault, but I don't want to delete something just because it's not on the wishlist -- maybe it just hasn't been "reviewed" by those writing the official wishlist.

**Comment by inexorableAce** [comment]
Have looked at the item detail sheet? It has every wishlist roll spelled out for the gun you click on. (Open the item pop up and click the item name)
