### ISSUE TITLE
All items new if state changed before stores first loaded

### ISSUE THREAD

**Issue by ericnelson0** [DestinyItemManager/DIM#711]
Trying to change app state (clicking minmax/vendors) before the stores are initially loaded causes all items to show as new.

![example_issue_new](https://cloud.githubusercontent.com/assets/4594931/17047475/17446d7e-4fa4-11e6-819e-896adcc5e0a0.gif)

**Comment by bhollis** [comment]
Fixed in #713.

**Comment by SunburnedGoose** [comment]
![screen shot 2016-08-05 at 11 12 18 am](https://cloud.githubusercontent.com/assets/984608/17442937/b564c60c-5afd-11e6-8c93-596e77eb3036.png)

![screen shot 2016-08-05 at 11 12 44 am](https://cloud.githubusercontent.com/assets/984608/17442941/b8bde9d2-5afd-11e6-80fd-b9a134d4d6db.png)

**Comment by SunburnedGoose** [comment]
Still having issues switching platforms.
