### ISSUE TITLE
Allow user to configure the amount of space to clear when using make space.

### ISSUE THREAD

**Issue by xXInfamousWolf** [DestinyItemManager/DIM#7114]
Essentially there would be config in settings to configure how much inventory space to clear when using the "make space/farming mode", leaving the default set to one but allowing the user to increase this. As I often find that a lot of this will end up going to the postmaster despite having this one as thing drop in the same slot fairly frequently.

**Comment by xXInfamousWolf** [comment]
I am keen to have a go at adding this myself by the way.

**Comment by nev-r** [comment]
https://github.com/DestinyItemManager/DIM/issues/7083 dupe
