### ISSUE TITLE
Vendor service calls cause errors to be reported double

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#712]
For example, if you select a platform you don't own, you'll get two popups about it. This is because the vendor service calls the same "getcharacter" stuff the main getStores does.

/cc @ericnelson0

**Comment by ericnelson0** [comment]
Since these are tied to characters anyway should the vendors be tied to the stores like advisors?

**Comment by bhollis** [comment]
Probably, though hopefully in a way that doesn't add latency.

**Comment by bhollis** [comment]
I can confirm this is now fixed.
