### ISSUE TITLE
Support Little Light JSON wishlist format

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#7129]
Little Light has a nicer, JSON-based wishlist format which supports tags and multiple perks per socket. It'd be great to remove our combinatoric wishlists in favor of something like this.

**Comment by delphiactual** [comment]
it should also include a `version` tag at the highest level

**Comment by bhollis** [comment]
I personally try to avoid versioned formats/APIs and try to make only backwards compatible changes - if that fails and a version is needed, a version field can be added at that point and the "unversioned" documents implicitly become v1.

**Comment by delphiactual** [comment]
I more meant for knowing that, the data is newer than some other data
