### ISSUE TITLE
perk selection in Armory does not work on mobile 

### ISSUE THREAD

**Issue by inexorableAce** [DestinyItemManager/DIM#7133]
### DIM Version

Version 6.85.0.1000756 (beta), built on 10/6/2021, 3:38:52 PM

### Browser Details

Safari PWA

### OS Details

iOS 14.7.1

### Describe the bug

Since the armory had press to view perk information, now that there is both a hover and click action in the armory, you can no longer reliably see perk info or select perks on mobile in the armory. I assume this will also affect the app normal perk view for mobile (this is why we made the new perk view in beta to begin with I think was planning for perk selection like this.)

### Logs

```shell
n/a
```

**Comment by bhollis** [comment]
Yeah I think it's the same Safari touch/popper issues. Planning on revisiting all that soon.
