### ISSUE TITLE
Items Disappearing

### ISSUE THREAD

**Issue by dupree027** [DestinyItemManager/DIM#7145]
I have now had TWO energy Weapons disappear when transferring them to classes classes.  Igneous hammer and Infinity fusion from Gambit. Where did they go??

**Comment by bhollis** [comment]
https://destinyitemmanager.fandom.com/wiki/Category:FAQ#DIM_deleted_my_item.21

**Comment by dupree027** [comment]
Still nothing, Tried it on two separate items
