### ISSUE TITLE
Vendor tab doesn't show weapons

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#716]
I went to look at what Saladin had, but it's only armor. Can we get weapons and other stuff too?

/cc @ericnelson0

**Comment by ericnelson0** [comment]
Yeah, weapons and other items could be added as well. That might help with some of the empty space.

I have some initial work done on moving vendors to the store abstraction, but I'll be out of town this week.

**Comment by ericnelson0** [comment]
Ok, just got back. I'm going to work on this and #712 tomorrow.

**Comment by bhollis** [comment]
Resolving in favor of #741.
