### ISSUE TITLE
Named Filters

### ISSUE THREAD

**Issue by Korrasera** [DestinyItemManager/DIM#7174]
### Proposed change

Filters are great, but they can be cumbersome if you use a long filter copied in from a text file. I propose adding the ability to add a name to a filter. If a filter has a name, it gets displayed in the dropdown list as a named filter, rather than as the raw filter itself.

While this wouldn't be useful for short, simple filters, it'd be fantastic for those filters we build to sort through junk armor and the like, as they can be several lines long.

### How does this fit into your workflow?

I use DIM on desktop and tablet and this kind of change would make it much easier to use filters everywhere, but they'd be particularly useful on a tablet where it's harder to interact with text and where screen space is limited. With named filters it would be very easy to add complex filters using a desktop, name them, and then have a short and easy to interpret list when I move over to my tablet.

Since complex filters can easily take up three lines, this change would simplify the filter dropdown, making it much more readable during normal operations.

**Comment by Korrasera** [comment]
I don't think that would have the same effect, as it would then mean you'd need to decipher each complex filter you used with your eyes. If all of your complex filters started with (is:armor is:exotic is:inloadout) for example, you'd have a bunch of things that all looked the same but might be designed to do very different things. Names would give them a shorthand context that's very easy to interpret at a glance.

**Comment by bepoli** [comment]
> You can write a name into your filter.

Yep, but keep in mind that if the string partially matches anything (a perk, a weapon name, a shader, etc...) it will interfere with your filter (it happened to me). Using long strings, possibly with special characters, will surely avoid that.

**Comment by Korrasera** [comment]
And yes, implementing this kind of change would mean adding a naming interface. You could do both naming and management functions together in one step. Click a small icon, something like the three dots, get a field, the field is populated with nothing (if the filter has no name set) or the filter name, which you can then edit as normal and then commit the change.

Or it could be integrated into the filter field itself, since the field already has buttons for manipulating the filters as it stands, since you can favorite and delete them. This would just add a 3rd option to add the name, that particular filter line would become editable, and then you'd enter the name and watch it take effect.

The constraints for the field are easy, just start with something like a 20 or 30 character string that only allows alphanumerics. It could always be revised or increased in future releases.

**Comment by Korrasera** [comment]
The thought occurs that you don't technically even need a button. Just add right-click functionality to the filters so that you can right click on them and add a tag/name/whatever. That would be unobtrusive and wouldn't add another button.

**Comment by Korrasera** [comment]
Actually, I did think of something that would be unobtrusive. Just add it to the favorite star functionality. When you favorite a filter it could bring up a small box that lets you add the name there.

Since the design language in DIM is already edit-less, since editing a filter means un-starring it, writing a new filter, and re-starring it, this would just be an extension of that same functionality. And designed correctly you could make it so that people could just ignore it if they don't want to use it.

**Comment by Korrasera** [comment]
I think I came up with a better idea. Add it as another filter tag.

filtername:"Bob's Discount Filter Name"

If filtername is present, it summarizes the entire filter as that name, otherwise it treats them like normal.

**Comment by inexorableAce** [comment]
That's pretty much the idea

**Comment by Korrasera** [comment]
The point behind this suggestion is to improve readability and reduce visual clutter, allowing someone to easily and quickly select the filter they're looking for. Putting the label in the first position, along with some sort of a visual spacer that makes it stand out distinctly could do if you don't want to hide the search text itself.

**Comment by bhollis** [comment]
Thanks, I think I understand the intent of the suggestion
