### ISSUE TITLE
Refactor Directives to Components

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#719]
Review directives and refactor them to components to give them an upgrade path to Angular 2.

A useful article, https://toddmotto.com/exploring-the-angular-1-5-component-method/

**Comment by kyleshay** [comment]
going forward, i'll try and just do this class by class as i'm in them. we do need to be a bit careful on this, as it could lend toward some major merge conflicts

**Comment by bhollis** [comment]
I've been making new stuff as components where possible (it isn't, always) and moving old stuff to components as well.

**Comment by bhollis** [comment]
We're doing this as we modify and add new stuff. Closing since this is just a reminder.
