### ISSUE TITLE
Allow for Notes/Description on the "Edit Loadout" Page

### ISSUE THREAD

**Issue by mattsigal** [DestinyItemManager/DIM#7193]
### Proposed change

When we create/edit a loadout, the Edit Window shows the name of the loadout, which class it applies to, the stat distribution of the loadout, and which items/mods and included in the build (including where the mods were placed using the "Show Mod Placement" button). The main feature that I believe is missing is a notes field where we can leave some comments/reminders about the build (e.g., for the stasis classes, my aspects and fragments get swapped when flipping between PVE and PVP and I might want to write down which).

I think either having a notes field that mirrors what we have on weapons/armor pieces next to the build stat line would work perfect (the red rectangle in this screenshot):

![Screen Shot 2021-10-27 at 2 18 11 PM](https://user-images.githubusercontent.com/1421758/139148628-a8886830-d1ee-49d1-9f3b-232bc80058ce.png)

### How does this fit into your workflow?

The ability to save, equip, and swap between builds quickly is one of DIM's best features (and one I regularly recommend to my friends). Allowing a notes field would make it substantially easier to remember specifics about a build, especially if some things need to be changed (like in the class screen or on the seasonal artifact) to get it up and running.

**Comment by bhollis** [comment]
I'm generally into this, but in a world where we save which mods you want to use, and tell you where they go, and maybe even apply them for you (in the future if we're allowed to), what else would you want to put in the notes?

**Comment by mattsigal** [comment]
The specific use case that prompted the issue was switching my stasis builds between PVE and PVP (since I swap like 90% of the aspects/fragments and wanted somewhere to write down which to swap); but beyond that, I think it would be useful more generally as a place to put a slightly longer note than the load-out name. 

Could use it to note which mods will go away at the end of the season or any specific nuances to remember for that load-out - for example, I've put together a few builds based on ideas I saw online that require/promote specific gameplay loops but sometimes, by the time I go to actually try the build out, I've forgotten the nuances that I was supposed to remember, haha. Since that would be load-out specific, it would make more sense to leave a note on the load-out itself than on a particular piece of gear that is in the load-out.
