### ISSUE TITLE
Save perk selections from loadout builder to show in popup on equip

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#720]
Users would like to recall what perks to apply to their loadouts when they are equipping them if they were created from the loadout builder page. 

https://www.reddit.com/r/DestinyItemManager/comments/4ukc74/loadout_perks_reminder/

**Comment by SunburnedGoose** [comment]
https://twitter.com/sir_mashaa/status/762925254306041856 

Question coming to us a lot lately.

**Comment by ericnelson0** [comment]
Any ideas on this? I've thought about an overlay on equipped items until any item of the loadout is unequipped, but it doesn't seem very nice.

**Comment by SunburnedGoose** [comment]
Can't we just add a 'notes' section to loadouts that we show in the drop down beneath the name?

**Comment by ericnelson0** [comment]
Hmm. I was thinking the bonus types should be separate from the notes though.

**Comment by shockthealien** [comment]
How about this? we can integrate it with the loadout editor and have it do both functions, editing and keeping a reminder of the settings. (please excuse the quick and dirty ps chop)

![loadout_settings](https://cloud.githubusercontent.com/assets/2083273/18289093/e7c48d1c-7475-11e6-94f4-699a383c9282.png)

**Comment by kyleshay** [comment]
nice @shockthealien ...

another thought-- maybe we could even just show the int/dis/str column instead of all the perks?

**Comment by bhollis** [comment]
As a short term solution, what do folks think about auto-generating the loadout name with a pattern like "T12 DIS - DIIDDS" where it calls out the tier, the stat priorities, and then the stat choice per item starting from the top down? It's cryptic, but I think folks are already doing something similar, and it'd be easy.

**Comment by weborican** [comment]
I’d like to see a button to show all possible perk combinations for your equipped armor. A list of possible perk combinations would be best since that 5/5/2 build, for example, may be able to become a 5/4/3 build with a different set of perks selected, a 3/5/4, etc. This way, when selecting the “equip highest light” loadout, you will have a way to quickly see what that equipped armor set is capable of together with the perk combinations to select in order to change it in-game.

**Comment by kyleshay** [comment]
@weborican that's already possible in DIM, if you click the bar icon at the top of the page and "equip from character"
