### ISSUE TITLE
clicking mod icon in LO selects 3 of that mod. 

### ISSUE THREAD

**Issue by inexorableAce** [DestinyItemManager/DIM#7200]
### DIM Version

current beta and app

### Browser Details

Chrome Version (current)

### OS Details

Windows 10

### Describe the bug

best illustrated by this GIF
![modsBug](https://user-images.githubusercontent.com/29002828/139701985-8098418e-d5c8-4f76-9ff1-f29a0e39e3aa.gif)

**Comment by bhollis** [comment]
Efficient!

**Comment by ryan-rushton** [comment]
Ooof

**Comment by ryan-rushton** [comment]
Bonus fact, tabbing around the mod picker display also selects mods. We have to tab 3 times to get to the next item. a11y would have a field day with this.
