### ISSUE TITLE
Tweak stat color range

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#7202]
It'd be nice to have some more separation between the colors - today almost everything is red, then the very best are blue or green. One issue is that this isn't implemented as a smooth ramp, instead it's just sharp breakpoints.

**Comment by bhollis** [comment]
Naively using a smooth ramp instead of the steps we have today (which mark everything below 85th percentile red, and then have a few defined steps above that), looks like this:

![image](https://user-images.githubusercontent.com/313208/141402486-faa69dd6-a681-4b78-9182-bd82bb689547.png)

**Comment by kyleshay** [comment]
It looks a lotttt better, but it may be difficult for some to quickly parse the more subtle variations. Could play w/ the ramp to make it more logarithmic / slightly less color steps? 

----- 

Another (semi-related, ish... maybe better in it's own ticket) thought is we could set a default sort on the compare and highlight the background column of the original item you clicked. I wonder if some may not know that the rows can be sorted? 

<img width="1271" alt="Screen Shot 2021-11-11 at 7 52 59 PM" src="https://user-images.githubusercontent.com/424158/141406350-399a5dc7-8d1f-4a38-b676-4ddc574871c0.png">

**Comment by kyleshay** [comment]
Could highlight just the lowest number with red, highest with blue and everything else non-color? I do like how it looks in the organizer view.

**Comment by bhollis** [comment]
For reference this is the original scale:
![dim-scale](https://user-images.githubusercontent.com/313208/141519989-38521d38-3b37-4cdd-aa83-a103af8e815a.png)

And the new one is a bit closer to what people thought it was:
![](https://images.wikia.com/destiny_item_manager/images/archive/6/63/20211112185333%21Compare_Menu_Scale.png)
