### ISSUE TITLE
Vault separators

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#7206]
Add a setting to group items in the vault based on the first item ordering discriminator. 

Alternatively, we could have a new grouping setting just for the vault that's independent of the sort setting. Would that be better? It's a bit more complicated.

**Comment by JakeSidSmith** [comment]
This and or a combination with [Group Items](https://github.com/DestinyItemManager/DIM/issues/8729) are a feature(s) I really need.

It would be ideal if we could define groups outside of the usual sorting option e.g. I would like to group items into ones that I "only keep to infuse others", or more recently "things I might activate deepsight resonance on".

I'm happy to have a look at implementing any of the above myself. Have had a read of the contributing doc, and it seems pretty straightforward (and luckily uses my usual tech stack).
