### ISSUE TITLE
RFC: add “keep pvp”, “keep pve” tags

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#7208]
One thought to solve a very very common request is to add two new tags, one for keep pvp and keep pve. This would give coverage of the common case without combinatorial explosion. You wouldn't be able to mark favorite pvp/pve which is weird, and we'd either need to make the tag list longer or come up with a clever UI for compacting the three "keep" options.

**Comment by SplendidHowl** [comment]
It would also be interesting to actually have a segregation of recommended PvE vs. PvP roles from the curators list.

**Comment by philkernick** [comment]
There are very few weapons I can think of that would have a roll that would be both keep pvp and keep pve.  So perhaps we don't need three options, just two.

**Comment by bhollis** [comment]
The "keep" option is for people who don't care about the difference between pvp and pve, such as myself.

**Comment by philkernick** [comment]
From a UI consistency approach I'd recommend tag:keep[:qualifier]

That would give

- tag:keep
- tag:keep:pvp
- tag:keep:pve

Then it's 100% backwards compatible, but allows qualifiers on the tag.
