### ISSUE TITLE
Cannot Transfer or Equip while Developing Locally

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#721]
Cloing DIM and adding it as a package to Chrome will not allow you to transfer or equip items.  Bungie has white listed the origin. 

https://github.com/DestinyItemManager/DIM/tree/remove-origin

A commit was added to this branch that lets us to perform these actions with DIM by stripping out the origin header from the request.

TODO

- [ ] Remove Permissions from Production Releases
- [ ] Remove the code to modify the request from Production Releases

**Comment by bhollis** [comment]
That looks great. I'm surprised that just taking the Origin out works, but I'll take it.

I have a branch that's 90% done that adds a bunch of post-processing to our JS, I can add a thing to that which will strip out that code from release builds.

**Comment by SunburnedGoose** [comment]
@kyleshay and I are talking about just adding that to the release build.  We can test the permission change in the beta build and give Bungie a chance to comment.  They asked that we change the *.bungie.net wildcard to www.bungie.net, which will require a permission change.  You need unlimited storage in the SQLite PR...  So we could just go out with it.

**Comment by bhollis** [comment]
I am able to move items from dev again - have Bungie reverted their change?
