### ISSUE TITLE
Auto lock based on tag

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#7220]
As an alternative to #7219, we could maybe have an option to sync lock state to tags. This would lock keep/favorite/archive and unlock junk/infuse. If this was enabled we could stop showing the lock icon and locked options when an item is tagged. 

One problem is this might run into differing opinions on what the tags mean (e.g. infuse is for infusion fuel vs infusion target)

**Comment by zacgoodwin** [comment]
A way around this would be to allow the user to define what they want to do in the settings page; display each tag with radio / drop down of auto lock, Auto Unlock, none

could add the same option for wish listed rolls as well

personally I have some edge cases where I mark something as junk but want to think about it a while so I’ll leave it as locked. When I review later and am confident in my decision I’ll unlock it for the next shard spree

**Comment by bhollis** [comment]
Yeah, I don't think we'd do that level of customization necessarily - for folks who have really tricky rules around what to do they can just manage locked state manually.
