### ISSUE TITLE
Error building record books if they are in the vault.

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#723]
An error is thrown if any record book is in the vault. 

getDestinyAdvisors is called only with your characters, and not the vault... so the vault does not have the advisors object on it:

https://github.com/DestinyItemManager/DIM/blob/dev/app/scripts/services/dimBungieService.factory.js#L516-L526

if owner = vault, advisors = undefined property -> can see why it would break here:
https://github.com/DestinyItemManager/DIM/blob/dev/app/scripts/services/dimStoreService.factory.js#L561

**Comment by bhollis** [comment]
Is this a "breaks things" error, or just a logs-in-the-console error? Wondering if this should be release-blocking.

**Comment by SunburnedGoose** [comment]
You don't see progress in the popup.  It needs to use the account wide endpoint.

**Comment by bhollis** [comment]
Yeah, I'm wondering if that should be release-blocking.

**Comment by SunburnedGoose** [comment]
eh, don't put it in the vault :)

**Comment by Mulchman** [comment]
and keep it on our player taking up valuable space!? pssh

**Comment by kyleshay** [comment]
we should have this done by RoI, but not release blocking.

**Comment by delphiactual** [comment]
Might not need it done by RoI...

https://youtu.be/xGMemFnSpP8?t=83

**Comment by bhollis** [comment]
Checking back in - it sounds like record books are console-wide, so with #940 is this issue still valid?

**Comment by kyleshay** [comment]
close in favor of the #940 solution.
