### ISSUE TITLE
Missing substitutions in subclass ability text

### ISSUE THREAD

**Issue by ryan-rushton** [DestinyItemManager/DIM#7237]
### DIM Version

beta

### Browser Details

Chrome 95

### OS Details

MacOS

### Describe the bug

<img width="541" alt="Screen Shot 2021-11-07 at 8 03 28 pm" src="https://user-images.githubusercontent.com/7344652/140638898-dcf44436-bcfd-465c-9256-f11474ec85cc.png">

**Comment by bhollis** [comment]
This appears to be an API data issue - mind filing a bug with Bungie?
