### ISSUE TITLE
Visual overlap in currency when item size is small

### ISSUE THREAD

**Issue by inexorableAce** [DestinyItemManager/DIM#7239]
### DIM Version

current beta and app

### Browser Details

Chrome Version (current)

### OS Details

Windows 10

### Describe the bug

if you're item size is small enough and you have a lot of currency, they overlap one another. perhaps we should ellipsis these? or abbreviate them and show real number on click?
![image](https://user-images.githubusercontent.com/29002828/140665659-7a7bee9b-4ab4-438d-a412-fae80e696171.png)

**Comment by bhollis** [comment]
Or change the minimum item size...

**Comment by inexorableAce** [comment]
Yeah, the person who reported it really lamented that option because they enjoy the smallest item size.
