### ISSUE TITLE
Allow more than 10 items per slot in loadouts (since a loadout can serve multiple classes)

### ISSUE THREAD

**Issue by tehtrav** [DestinyItemManager/DIM#7241]
### Proposed change

10 items was great for when loadouts were class specific, but now that loadouts can be used with armor for different classes it makes sense that you may want to add more than 10 items to a slot. For example, a PVP loadout may have 4 titan legs, 4 hunter legs, 4 warlock legs but that would exceed the slots available. 

### How does this fit into your workflow?

The goal for me is to click one button any time I play crucible on a different character and have all the current meta armor and exotics transferred. Currently it can't be done because I run out of armor slots. Thanks for considering!

**Comment by bhollis** [comment]
I'm afraid I alerady regret making that change to allow multiple classes, and doing this would make me regret it more! It makes  everything more complicated when we could have just had three loadouts.

**Comment by inexorableAce** [comment]
yeah it really opened up a rabbit hole... I guess I see the benefit for people that are making like pvp / pve loadouts for each class... you go from 6 loadouts to 3. But that's only if you're doing that very specifically. Like my LOs are way too specific to make use of the class change. They are exotic and subclass based as well as activity based.

**Comment by tehtrav** [comment]
@inexorableAce yeah I have a mix of specific and non specific. It's all good, for now at least I can have my PVP loadout include armor for my Titan, and my other two will simply get the weapons and no armor. Still thankful for the recent loadout change!

**Comment by bhollis** [comment]
Closing as multi-class loadouts are deprecated
