### ISSUE TITLE
LO-generated loadout can't slot all mods

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#7247]
I generated this loadout by selecting these mods and choosing the top loadout in LO. However when I go to the loadout itself and ask for mod assignments, it now says it can't slot two of the mods: 
<img width="965" alt="Screen Shot 2021-11-11 at 11 29 17 AM" src="https://user-images.githubusercontent.com/313208/141357392-e3c01d9f-3c2c-4540-b76b-54f795630d0a.png">

**Comment by bhollis** [comment]
Here's LO's opinion of it:
![image](https://user-images.githubusercontent.com/313208/141357587-205772c5-f86f-4ea7-ac53-ef2e9069d714.png)

**Comment by ryan-rushton** [comment]
So the loadout one is correct it's just that we aren't showing the energy upgrade icons for some reason in LO. The loadout one assumes no armour upgrades and won't swap energy type.

**Comment by ryan-rushton** [comment]
Your arms should stay the same energy type but be upgraded to 8 energy

**Comment by bhollis** [comment]
I see so we still need to incorporate planning energy upgrades?

**Comment by ryan-rushton** [comment]
I purposely didn't include then at this stage because I am assuming we won't be able to upgrade armour with AWA. We can revisit that situation though if you think it makes sense to signal this to the user.

**Comment by bhollis** [comment]
I think any changes that need to be done, whether we can do them or not, need to be called out so people know what to do.

**Comment by ryan-rushton** [comment]
Hmm ok, I wonder what the best way to display this is. Users can modify mods directly on the loadout so the state that came from LO originally isn't always representative of the current mod set. Maybe we should let the user select an upgrade option and pre-populate it with whatever was saved in LO. That way there can be an option for AWA if/when we get it.

**Comment by bhollis** [comment]
I don't think we should worry about having them choose an upgrade option - we should just figure out the cheapest way to slot all the mods, and then show a guide for how to do it.

**Comment by ryan-rushton** [comment]
Should we close this now or maybe add options for loadouts to show the needed upgrade path?

**Comment by bhollis** [comment]
I'd still like to show what the minimum upgrades would be to make them fit.

**Comment by ryan-rushton** [comment]
Ok, this will be an interesting problem to solve but I think we could augment the current mod assignment algorithm to do this. We would need to return the necessary upgrade per item to make the assignment work.

**Comment by bhollis** [comment]
Linking #9017
