### ISSUE TITLE
LO optimizer disabled, even without maintenance

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#7256]
https://github.com/DestinyItemManager/DIM/pull/7231/files#diff-6136da939d41e6778ae37f470b0cc966c9d207d06d31f6d89a630a5d4b52c7f2R144-R147

report in discord

https://discord.com/channels/316217202766512130/333464468241514497/908694031570178091

**Comment by delphiactual** [comment]
We either need to log what item triggers this or change to `every`

**Comment by ryan-rushton** [comment]
How about we do both? I am interested to see what is getting that property set to trigger this.
