### ISSUE TITLE
Syntax error Unexpected token d in JSON at position 5130

### ISSUE THREAD

**Issue by wkearney99** [DestinyItemManager/DIM#7258]
### DIM Version

Version 6.90.1.1000845 (beta), built on 11/12/2021, 5:30:10 PM

### Browser Details

Version 95.0.4638.69 (Official Build) (64-bit)

### OS Details

Windows 10

### Describe the bug

Using version 6.90.1.1000845 (beta), built on 11/12/2021, 5:30:10 PM and selecting Progress or Records tab it throws a syntax error.

Something went wrong SyntaxError
Unexpected token d in JSON at position 5130

Version 6.90.1 (release), built on 11/8/2021, 11:06:58 PM doesn't have the same problem.

Error is repeatable on other browsers.  Edge does the same thing, as does Chrome running on a Linux box.

### Logs

```shell
instrument.ts:130 [DIM Code] SyntaxError: Unexpected token d in JSON at position 5130
    at JSON.parse (<anonymous>)
    at Object.13476 (/267-41eaad.js:1)
    at s (runtime-57d38d.js:1)
    at Object.87828 (/267-41eaad.js:1)
    at s (runtime-57d38d.js:1)
    at Module.92464 (/progress-e08a72.js:1)
    at Function.s (runtime-57d38d.js:1) Object
```

**Comment by bhollis** [comment]
Thanks for letting us know. This has been fixed.
