### ISSUE TITLE
Clicking and dragging the element icon of an item

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#726]
This is very much just a minor styling issue, but normally when you drag an item you can see an outline of it... but if you click and drag the element, it just shows that element.

dropping the element in any bucket still moves the item as expected

.. hope i explained that well enough.
<img width="470" alt="screen shot 2016-07-29 at 11 11 22 am" src="https://cloud.githubusercontent.com/assets/424158/17253153/83aebc9c-557d-11e6-926b-de7645e0a992.png">

**Comment by bhollis** [comment]
This is the problem with options.... only the options *I* have enabled get tested.
