### ISSUE TITLE
I don't understand how LO chooses class items

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#7261]
![image](https://user-images.githubusercontent.com/313208/141660449-d17adcb8-2c2a-4fa7-9c1d-59df7936ba29.png)

I have one already-masterworked class item. I've selected the "Ascendant Shard" upgrade option and locked Powerful Friends (arc). But LO is selecting a bunch of random class items that aren't masterworked.

Also for some reason when I click the swap icon I'm only shown void class items, even though there's no constraint that would limit us to void class items - *all* class items should be eligible.

**Comment by ryan-rushton** [comment]
I created a PR to do this better. It's all in the pre-process grouping of items. After having a look at this if it still doesn't make sense let me know and I will try write a bunch of docs on it.
