### ISSUE TITLE
Strange coin icon background

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#727]
Consider searching for/making a strange coin icon that does not have a blue background (transparent instead) 

<img width="305" alt="screen shot 2016-07-29 at 11 41 05 am" src="https://cloud.githubusercontent.com/assets/424158/17254116/7053b9e6-5581-11e6-9940-f1cd4d8a6102.png">

**Comment by kyleshay** [comment]
ex.
![](http://i.imgur.com/wUgJYPw.png)

**Comment by bhollis** [comment]
I'm not sure it'd be recognizable at such a small size

**Comment by delphiactual** [comment]
Using a little photoshop magic I created a mockup, with the dev tab open.

![screenshot 2016-08-11 11 47 24](https://cloud.githubusercontent.com/assets/4798491/17599441/4cc658ae-5fbc-11e6-89b0-dcd2edc83ad7.png)

**Comment by SunburnedGoose** [comment]
That looks good :)

**Comment by bhollis** [comment]
Wow it looks a lot better!
