### ISSUE TITLE
Tags Disappear from Weapons and Armor when Compare is Selected.  Using Opera Browser.

### ISSUE THREAD

**Issue by timothyjdaniel** [DestinyItemManager/DIM#7281]
### DIM Version

6.91.1

### Browser Details

Opera Version:80.0.4170.63

### OS Details

Windows 10

### Describe the bug

Tags appear on my weapons and armor in the default inventory view, but when I click on an individual item and select compare, the tags on all the items I'm comparing disappear.

**Comment by bhollis** [comment]
https://github.com/DestinyItemManager/DIM/blob/master/docs/CHANGELOG.md
