### ISSUE TITLE
Use StatsSet to filter out strictly-worse stat rolls from LO

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#7284]
These are rare, but every bit of filtering counts, and it's pretty fast, so might as well use it to filter out strictly-worse-stat items? We'd still need to group by mods and element and all that.

For example in `groupItems`, we could group by mods and element and masterwork(?) first, and then within each of those groups, throw out anything that has strictly worse stats than something else *in that same group*, then split the groups by exact stats. 

Though 99.999% of the time all that'll do is knock out your non-masterworked class items, and maybe it's better to just write a simpler function that always grabs the masterworked class item.

**Comment by ryan-rushton** [comment]
I think its quite possible we hit this for items with full stats, for example an item with 50 total points vs an item with 65.

**Comment by bhollis** [comment]
I'll maybe take a stab at it once your other changes merge. I understand the workflow a lot better now.
