### ISSUE TITLE
Hezen Vengeance has incorrect phrasing in a specific wishlist roll.

### ISSUE THREAD

**Issue by rmfarwell** [DestinyItemManager/DIM#7285]
When going through the wishlisted rolls for the Hezen Vengeance VoG rocket launcher, I noticed the second roll breakdown has incorrect phrasing when describing the benefits of the Overflow perk.

It reads: "Inspired by Destiny Massive Breakdowns from Podcast 234. PvE first choice roll for boss DPS - get a kill, reload to get two in the tubes and throw a grenade for a quick third. Recommended MW: Reload with Boss Spec mod." The roll shown below the text is Quick Launch / Impact Casing / Overflow / Demolitionist.

![Hezen 1](https://user-images.githubusercontent.com/86750197/142253583-70625fe5-b670-4187-903e-8a0322b0755e.jpg)
![Hezen](https://user-images.githubusercontent.com/86750197/142253587-3aea073c-2862-43d6-b2c5-621206315aba.jpg)

The focus here is "get a kill, reload to get two in the tubes." I believe that the text has Overflow confused with Ambitious Assassin, which is not an available perk on Hezen Vengeance. Overflow only increases magazine capacity when picking up special or heavy ammo, and is not activated on reload after a kill like Ambitious Assassin is. See above pictures for reference. <3

**Comment by bhollis** [comment]
Thanks for the feedback - you should file this over in https://github.com/48klocs/dim-wish-list-sources where the wishlists are.

**Comment by rmfarwell** [comment]
Done. Thanks for the guidance, Ben!
