### ISSUE TITLE
Loadout Builder is broken 

### ISSUE THREAD

**Issue by kohum** [DestinyItemManager/DIM#729]
Hi, the current beta version(3.8.3.301) seems to be broken.

![loadoutbuilder](https://cloud.githubusercontent.com/assets/6478196/17270668/923fd594-56bc-11e6-9027-25d075ce021a.PNG)

**Comment by ericnelson0** [comment]
Can you show us the dev console output?

**Comment by SunburnedGoose** [comment]
![screen shot 2016-07-30 at 12 11 12 pm](https://cloud.githubusercontent.com/assets/984608/17271935/f941e0ac-564e-11e6-94ef-dd76f8a464dd.png)

![screen shot 2016-07-30 at 12 12 32 pm](https://cloud.githubusercontent.com/assets/984608/17271936/fc952ebc-564e-11e6-9c0d-070bf18d0a18.png)

**Comment by bhollis** [comment]
Hmm, getActiveStore was added in https://github.com/DestinyItemManager/DIM/commit/dd515abc23fc5edaf0764f1528cc783782814606.

**Comment by kyleshay** [comment]
thanks for the report/logs/link to commit! whoops 😞
