### ISSUE TITLE
Ability to sort your created loadouts based on various criteria

### ISSUE THREAD

**Issue by Zenorax** [DestinyItemManager/DIM#7290]
### Proposed change

In the Beta, it seems that loadouts are now listed by how recently they were created, but my loadouts are named "1.1 ________," "1.2 ___________," etc. Can you add the ability to sort loadouts by alphabetical order (A-Z/Z-A) as well as most/least recent?

### How does this fit into your workflow?

I use 5 loadouts per char every day, and it's important that they're in the same place when i need them.

**Comment by bhollis** [comment]
Yeah it's in the plans. Any sorts other than name and date?

You can reorder them by just going and re-saving them in the order you want.

**Comment by Zenorax** [comment]
Maybe manual and most recently edited? I don't see use for any other sorting beyond that.

**Comment by bhollis** [comment]
"Manual" won't be one of the options

**Comment by Zenorax** [comment]
Fair enough.

**Comment by bhollis** [comment]
BTW the current sort is most recently edited, not most recently created

**Comment by subversity** [comment]
I just want to second the request for alphabetic sorting. I have more than 30 loadouts on my warlock and its a bit hard to find them now. Like the user above, I have mine sorted with a prefix (a-, b-, c-) etc. Thanks!

**Comment by delphiactual** [comment]
alphabetic sorting was added last night

**Comment by subversity** [comment]
oh? how do I activate it? Im stillcseeing them in saved order. Thanks.
