### ISSUE TITLE
Stasis Quests Not Filtered Correctly

### ISSUE THREAD

**Issue by matthewdenison** [DestinyItemManager/DIM#7300]
This might have been reported already but my Stasis quests aren't filtering correctly. Only 2 of the 5 I have remaining are highlighted.

![image](https://user-images.githubusercontent.com/19811356/142774133-daaaaf39-0a96-4df7-a1a2-4d7bc6440ef6.png)

**Comment by delphiactual** [comment]
you are cropping important information out.

**Comment by matthewdenison** [comment]
What do you need?

**Comment by delphiactual** [comment]
what is currently causing the highlight a search or?

**Comment by matthewdenison** [comment]
I just clicked on Stasis in the filters when looking at my quests in progress.

**Comment by matthewdenison** [comment]
![image](https://user-images.githubusercontent.com/19811356/142774302-bd9a236c-37b2-417c-b321-bc33f5a6f131.png)

**Comment by delphiactual** [comment]
ok let me do some checking on how we decide what makes a quest stasis or not

**Comment by matthewdenison** [comment]
Ok, sounds good!

**Comment by delphiactual** [comment]
can you click on one of the non-highlighted stasis quests and post a screenshot of that?

**Comment by matthewdenison** [comment]
Sure, give me a sec.

**Comment by matthewdenison** [comment]
![image](https://user-images.githubusercontent.com/19811356/142774448-535557ef-0c7d-44de-a13e-395ec27e13a1.png)

**Comment by delphiactual** [comment]
can you do the same for one that is highlighted as well please?

**Comment by matthewdenison** [comment]
Sure thing!

**Comment by matthewdenison** [comment]
![image](https://user-images.githubusercontent.com/19811356/142774760-933e041a-34e8-4c49-93a8-d5635cbca648.png)

**Comment by matthewdenison** [comment]
Wow, that is quite the turnaround time! :) Great job on the tool! It has made playing D2 so much better.
