### ISSUE TITLE
Loadouts page shows some small icons

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#7305]
### DIM Version

current beta

### Browser Details

Chrome

### OS Details

Windows 11

### Describe the bug

The new loadout view shows one of my loadouts with a very small head.

![image](https://user-images.githubusercontent.com/25425159/143187113-0c559fb3-c71d-4400-9a8a-2a67ddb967a6.png)

All of the others are displayed correctly.

**Comment by nev-r** [comment]
i think this means it's in the loadout but not set to equip itself when applied

**Comment by nev-r** [comment]
![2021-11-24_12-37-57](https://user-images.githubusercontent.com/68782081/143309861-dc98405e-c9a4-4c6e-9fe7-34b750a409c3.gif)

**Comment by bhollis** [comment]
That is correct, it's a non-equipped item.

**Comment by philkernick** [comment]
Ok.  I had no idea you could create loadouts with unequipped items, and I've never consciously done it.

That said, having the icon small to mean "unequipped" is really not obvious.  Perhaps making them look desaturated like the archived items in the main inventory screen or some other visual cue.

**Comment by nev-r** [comment]
it's a fair point and we are discussing possibilities for marking and separating the two sections, but i hope this solves the mystery of the incredible shrinking helmet
