### ISSUE TITLE
Loadout organization

### ISSUE THREAD

**Issue by maviza67** [DestinyItemManager/DIM#7306]
Loadout pull down list for each character recently changed from alphabetical order to random. This makes it very difficult to find load outs. For example, I have 5 stompee load outs which were labeled "stompee hi int" etc.  sorting through my entire list of load outs is time consuming.  The alphabetic order allowed me to quickly find the one I wanted. Is this a bug or is there a setting to change this.  I'm using version 6.92.1 on iPad Pro. Thanks.

**Comment by maviza67** [comment]
I found an answer to my question on the release notes. Never mind!

**Comment by delphiactual** [comment]
https://github.com/DestinyItemManager/DIM/blob/master/docs/CHANGELOG.md#beta-only

**Comment by bhollis** [comment]
This is also only on beta (or should be).
