### ISSUE TITLE
loadout page: optimize button exists when there's no armor

### ISSUE THREAD

**Issue by nev-r** [DestinyItemManager/DIM#7307]
![image](https://user-images.githubusercontent.com/68782081/143310868-530c7487-2ada-4801-a246-49e243ba7ba3.png)

**Comment by nev-r** [comment]
or maybe that fact that it's there at all is the problem

**Comment by bhollis** [comment]
Yeah the layout is wrong but the idea was to guide you towards the optimizer for picking armor.
