### ISSUE TITLE
Loadout drawer shows stats of items as currently configured, not how they'd be with saved mods

### ISSUE THREAD

**Issue by kohum** [DestinyItemManager/DIM#7313]
### DIM Version

Version 6.92.1.1000886 (beta), built on 11/25/2021, 11:30:21 AM

### Browser Details

Version 97.0.4692.20 (Official Build) beta (64-bit)

### OS Details

Windows 10

### Describe the bug

1. I created a build in Loadout Optimizer.
2. The stats in the Loadout Optimizer window are displayed correctly.
3. Pressed the 'Save Loadout' button to get the Loadout tray at the bottom.
4. The stats here are incorrectly displayed for Resilience and Recovery for some reason and don't match what was displayed in the Loadout Optimizer window (step 2 above).

Screenshot - 
![image](https://user-images.githubusercontent.com/6478196/143382458-f3600ab6-fc7b-4604-be12-c242ce849f4b.png)

**Comment by nev-r** [comment]
loadout tray shows the armors' current state, not the mods you planned to attach in the optimizer. can you confirm if that is the correct current total of those armors?

**Comment by kohum** [comment]
You're right.  It shows the stats if I equipped the specific armor pieces in that loadout with whatever mods those armor pieces currently have.  Confusing.

**Comment by ryan-rushton** [comment]
Just stumbled across this. We should also be incorporating stasis fragments stat effects when I get that feature merged.
