### ISSUE TITLE
DIM constantly reloads in steam browser

### ISSUE THREAD

**Issue by bsrini** [DestinyItemManager/DIM#7315]
When using DIM from the Steam browser overlay, the site keeps constantly reloading, preventing its use. This issue persists even after clearing cookies and cached content from the steam settings pane.

Repo steps:
* Launch Destiny 2 from steam
* Press SHIFT + TAB to launch the steam overlay
* Click the browser button at the bottom of the overlay
* Navigate to https://app.destinyitemmanager.com
* Notice that the page keeps reloading repeatedly

**Comment by bhollis** [comment]
Thanks for the report. We're aware of this, but we do not have the debugging tools to support DIM in the Steam overlay. You'll have to use another browser.

https://destinyitemmanager.fandom.com/wiki/Desktop_and_Mobile_Apps#Steam
