### ISSUE TITLE
Trials Passage should not show `Flawless` completed with wins < 1

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#7336]
Unless I am misunderstanding something...
![image](https://user-images.githubusercontent.com/4798491/143959268-b0764bfc-54eb-4824-9da4-dad5ba63a0d9.png)

**Comment by intolerance** [comment]
In game, I believe it says "Flawless" until you actually lose twice -- then the card is no longer "Flawless".
