### ISSUE TITLE
Allow users to favorite finishers

### ISSUE THREAD

**Issue by nev-r** [DestinyItemManager/DIM#7348]
"Favoriting" finishers is not only reported as a lock state, but it's toggleable with the SetLockState endpoint.
Enabling this would be as simple as re-labeling and enabling the Lock button in the sidecar, for finishers.

Users have also suggested this capability might be a nice component of fashion loadouts.

**Comment by bhollis** [comment]
I distinctly remember implementing this, so it must have broken at some point

**Comment by RocheM** [comment]
Had a shot at this, I was able to favourite a finisher by manually setting "lockable" to true for finishers. I'm a little confused though as finishers seem to be returned from the API with lockable "false" for finishers.

I'm thinking I could add a manual case to set lockable to true if the itemType is finisher. Any thoughts on this?

**Comment by bhollis** [comment]
Yeah my guess is that it used to get marked lockable by some code that accidentally got removed.

**Comment by nev-r** [comment]
if we believed everything the API claimed, nothing would get done

**Comment by RocheM** [comment]
Created a PR for this #7482
