### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#735]
Let users choose from the available languages that Destiny provides.

**Comment by bhollis** [comment]
It'll be relatively easy to get all game data and all strings that can come
from the manifest (including this like "Attack" and "Defense") localized.
The thing I don't know how to manage is translating all the DIM-specific
strings. Who will maintain those?

**Comment by SunburnedGoose** [comment]
We can extract from a spreadsheet, and keep that in github.  Let folks who are adept at language modify the file.  Format is up in the air.  CSV, XLS, JSON...

**Comment by SunburnedGoose** [comment]
Nigel says he uses a Google Spreadsheet, which makes his life easy.

**Comment by bhollis** [comment]
I'm way less concerned about the format than I am about who is going to do
the translation.

**Comment by SunburnedGoose** [comment]
I'm sure we can find users in the locales we're interested in that would be willing to help with a translation.

**Comment by kyleshay** [comment]
Can just continue to fallback to English for strings we dotn have.  Can also make out about sections and such more lean. 

There was an i18n issue and lukefx had started use with angular translate

**Comment by kyleshay** [comment]
linking #204

**Comment by delphiactual** [comment]
https://www.oneskyapp.com/

**Comment by bhollis** [comment]
Addressed in the manifest-service branch.
