### ISSUE TITLE
Ability to find armor pieces with similar rolls

### ISSUE THREAD

**Issue by ryan-feigenbaum** [DestinyItemManager/DIM#7364]
### Proposed change

I think a feature to group armor pieces by similar rolls would be useful for vault cleaning. I've been playing around with something like this on a little node.js application and currently am finding similar armor pieces by getting the percent difference between each stat (between two armor pieces) and am considering them similar if all of the stats' percent difference is within a certain threshold.

A sample output for what I have currently is 
```
Philomath Gloves                 19 10  2  2 29  2
Dreambane Gloves                 16 15  2  2 26  2
==================================================
Philomath Gloves                 13  2 16 10 20  2
Simulator Gloves                 14  2 16  9 20  2
==================================================
Iron Forerunner Vestments         9 11 12 18 11  2
Legacy's Oath Robes               8 15  7 16 14  2
==================================================
Lightkin Robes                   12  2 17  2 22  7
Lightkin Robes                   14  2 13  2 20  9
==================================================
Iron Forerunner Vestments         9 11 12 18 11  2
Philomath Robes                  12  8 13 23  6  2
==================================================
Praefectus Boots                  2 22 10 12  9 12
Moonfang-X7 Boots                 2 12 19  9 12 11
==================================================
Insight Vikti Boots              10 12 12  2 12 20
Holdfast Boots                    6 17 10  2 11 20
==================================================
Legacy's Oath Boots              17  6 10  8  7 16
Reverie Dawn Boots               14  6  9 11  9 12
Legacy's Oath Boots              15  8  9  9  8 15
```

It seems silly to have both the philomath gloves and simulator gloves (second group). So a feature like this would help find those so I can choose one and delete the other.

**Concerns:**
I'm still not sure if this is the best method for finding similar rolls and am not sure how this would work from a UI perspective. Maybe a button on the organizer page when a user is looking at armor "Find Similar Rolls". But I think the layout would be different for showing the similar rolls, so I'm not sure about that either. 

### How does this fit into your workflow?

I'd like to use this feature to find armor pieces that there is no reason to keep, since I have other armor pieces with nearly the exact same roll.

**Comment by bhollis** [comment]
@nev-r is this similar to your Item Triage idea?

**Comment by nev-r** [comment]
yeah i can absorb this for now
