### ISSUE TITLE
Don't clear out all existing mods when applying mods from loadout

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#7371]
Right now, just to make things easier, if you apply a loadout with mods in it, we remove all mods from all armor, and then apply the mods you've asked for in the loadout. This works, but it can be disappointing because it may remove some incidental mods you wanted - for example it'd be nice to have your slot specific mods all figured out, and only apply changes to your combat style mods from the loadout.

To do this I think we should plan all mods in the beginning (as we do with `getCheapestModAssignments`) but also take into account both the existing mods on the armor we're assigning to, AND which armor is part of the loadout and which isn't. The goals are:

1. If a mod in the loadout is already on some armor somewhere, try to leave it there *if we can*
2. If an item has mods on it, try to keep them equipped when applying the mods from the loadout. Obviously we will have to swap out some mods because of slot restrictions, and remove some mods because of energy constraints, but we should attempt to remove the fewest mods from the existing items. This also implies that if we have a choice of where to put a mod we should choose the least disruptive location.
3. Minimize the number of operations required to apply the loadout. The current InsertPlugs API takes about 2 seconds per operation.

**Comment by ryan-rushton** [comment]
Partially fixed by #7382 but should be completed by #7388

**Comment by bhollis** [comment]
What's left on this? Do we correctly prioritize leaving mods where they're already equipped?

**Comment by ryan-rushton** [comment]
I think we are close enough, @nev-r did most of it [here](https://github.com/DestinyItemManager/DIM/pull/7440). 

The one thing I don't think we have done is determine whether we can reorder bucket independent mods to do less swaps. This could be another check in the mod assignment algorithm similar to when I added the conditional mod check.
