### ISSUE TITLE
"Look" Loadouts

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#7373]
### Proposed change

I'd like to be able to create saved "looks" consisting of ornaments and shaders that can be applied either on their own or as part of another loadout. To do this will likely require creating a special editor for choosing ornament/shader per slot.

At first I'd probably avoid applying shaders/ornaments to weapons, since they're much more specific to individual items.

Looks should be part of the "share build settings" URL, and we should optionally allow you to share just the look part of a loadout.

### How does this fit into your workflow?

People come up with all kinds of cool looks and would like to share them. Individual users might craft a few nice looks and want to apply them automatically to updated armor combinations - otherwise the upgrade treadmill slowly causes your look to drift.

**Comment by bhollis** [comment]
These probably should be called Fashion Loadouts

**Comment by FlaminSarge** [comment]
Calling it "Outfits" as opposed to "Loadouts" could also work. Would love to see an outfit manager in DIM.

**Comment by FlaminSarge** [comment]
This was closed by #7600, right?

**Comment by bhollis** [comment]
Yup
