### ISSUE TITLE
Share loadout link fails

### ISSUE THREAD

**Issue by joshhunt** [DestinyItemManager/DIM#7390]
### DIM Version

Version 6.94.0.1000957 (beta), built on 07/12/2021, 12:50:08

### Browser Details

Chrome 96.0.4664.93 (Official Build) (64-bit)

### OS Details

Windows 11

### Describe the bug

Opening a "share build settings" link I generated fails with the exception `Cannot read properties of undefined (reading 'findIndex')`

Link: https://beta.destinyitemmanager.com/optimizer?class=2&p=%7B%22mods%22%3A%5B3961599962%2C2128395292%2C2128395292%2C3632415743%2C1740246051%5D%7D

I created this loadout today 
![image](https://user-images.githubusercontent.com/46142/145042040-96706a56-66dd-4faf-a193-5f80ef31ca60.png)

Loadout JSON:

```json
{
    "id": "625ce521-7b8a-42cd-beef-455b418e47da",
    "name": "x Lost Armor",
    "classType": 2,
    "clearSpace": false,
    "equipped": [
        {
            "id": "6917529517594151875",
            "hash": 3642146012
        },
        {
            "id": "6917529539007380976",
            "hash": 2259629899
        },
        {
            "id": "6917529491440194505",
            "hash": 2319651767
        },
        {
            "id": "6917529538998610044",
            "hash": 616346210
        }
    ],
    "unequipped": [],
    "createdAt": "2021-12-07T12:45:11.377Z",
    "lastUpdatedAt": "2021-12-07T12:45:11.377Z",
    "parameters": {
        "mods": [
            3961599962,
            2128395292,
            2128395292,
            3632415743,
            1740246051
        ]
    }
}
```

Exception is thrown from https://github.com/DestinyItemManager/DIM/blob/338c6d7bc7063bbfc9c1d105820ffcf8302b4eec/src/app/loadout-builder/loadout-params.ts#L63

Maybe Typescript was right!

Feel free to close if you already know, or aren't that fussed, of course :) 

### Logs

```shell
[app] DIM v6.94.0.1000957 (beta) - Please report any errors to https://www.github.com/DestinyItemManager/DIM/issues
log.ts:44 Load manifest: 1944.235107421875 ms
log.ts:44 Process inventory: 92.334228515625 ms
instrument.ts:130 TypeError: Cannot read properties of undefined (reading 'findIndex')
    at loadout-params.ts:63
    at _baseOrderBy.js:39
    at r.exports (_arrayMap.js:16)
    at _baseOrderBy.js:38
    at _baseMap.js:17
    at _createBaseEach.js:24
    at r.exports (_baseMap.js:16)
    at r.exports (_baseOrderBy.js:37)
    at sortBy.js:45
    at r.exports (_apply.js:15)
    at _overRest.js:32
    at ao (loadout-params.ts:62)
    at Object.useReducer (react-dom.production.min.js:172)
    at t.useReducer (react.production.min.js:23)
    at loadout-builder-reducer.ts:333
    at LoadoutBuilder.tsx:192
```

**Comment by bhollis** [comment]
> Maybe Typescript was right!

Good catch. That type is supposed to be filled in with defaults before being used, but I should've created a new type to represent that.
