### ISSUE TITLE
Register installed app as URL handler

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#7392]
For each of the ways our app can be installed, we should find out how to register as a URL handler for the relevant URLs, so loadout share links open in the installed app instead of in the browser

**Comment by delphiactual** [comment]
https://developer.android.com/training/app-links#android-app-links

**Comment by bhollis** [comment]
https://web.dev/pwa-url-handler/

**Comment by bhollis** [comment]
The spec keeps shifting:

https://chromestatus.com/feature/5746537956114432
https://developer.chrome.com/docs/web-platform/launch-handler/

**Comment by bhollis** [comment]
Looks like the Launch Handler will show up in Chrome for Desktop 110 and could work well with the code in #8840
