### ISSUE TITLE
Vault Increase Strategy

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#740]
I have a feeling that the vault will be increased with Destiny removing legacy console support.  How do we want to handle a larger vault in DIM?  What if it can hold 200+ items for weapons/general/inventory?  Current is 108.

What are our options.  Just spitballing some ideas...

1. Do nothing
2. Pagination
3. Filtering
4. Hide Vault Items and Show on Demand

**Comment by bhollis** [comment]
I think most folks will want to see everything.

**Comment by SunburnedGoose** [comment]
If it is unbound, we'll have to break some hearts. How many watchers are we
up to now? We can get our upper bound from that for what we can show on
page.

So, what are our options if we can't show them all on the page? I'd like to
be prepared for Sept 20th.

**Comment by SunburnedGoose** [comment]
oph, ~11k watchers.  That feels like a lot.

**Comment by SunburnedGoose** [comment]
We're averaging 20ms per digest, up to 150ms according to ng-stats.

![screen shot 2016-08-03 at 9 43 40 pm](https://cloud.githubusercontent.com/assets/984608/17388687/5d5e464e-59c3-11e6-96d1-fd9fadccc0c3.png)

**Comment by kyleshay** [comment]
#573 #654

**Comment by bhollis** [comment]
Yeah, I like the sorting and collapsing. Being able to sort year1 (or junk, or stuff marked "sentimental") and hide it by default would really help.

**Comment by wein3967** [comment]
I'd say this kinda starts to line up with the whole "add labels/notes" topic we had awhile back.

**Comment by ericnelson0** [comment]
Looks like vault space isn't being increased: [gameinformer](http://www.gameinformer.com/b/features/archive/2016/08/10/three-days-exploring-destiny-rise-of-iron.aspx?PostPageIndex=3)

> It also creates a challenge on a topic that has plagued Bungie for a long time within Destiny, which is vault space. A lot of players (myself included) like to hold on to the treasures they’ve earned by playing. It’s hard to hold down that delete button! With all this new stuff coming in, and Year 2 items coming along for the ride, people are going to have to make some hard choices. I asked the development leads for Rise of Iron, and they didn’t have any current plans to further expand vault space. That’s not to say it couldn’t ever happen, but they didn’t tell us about any new initiatives there. I think holding on to old rewards is going to continue to be an issue that both players and the game’s developer are going to have to confront on a regular basis. 

That doesn't make any sense to me.

**Comment by kyleshay** [comment]
***gasp!!***... *phew*

**Comment by joshmedeski** [comment]
I've got a few interesting ideas, maybe if we hit that obstacle we can talk more about it.

**Comment by bhollis** [comment]
Closing until there's news about an expanded vault. I have some ideas around virtual-paging that might help us too.
