### ISSUE TITLE
Errors when applying loadout

### ISSUE THREAD

**Issue by effernity** [DestinyItemManager/DIM#7405]
### DIM Version

Version 6.94.0 (release), built on 06.12.2021, 05:06:08

### Browser Details

Chrome 96.0.4664.93 64 bit

### OS Details

Windows 10

### Describe the bug

Hello 
I'm trying to apply my saved loadout, but get error inside DIM (Bungie.net message: The request to modify an item failed. Refresh the item and try again), and inside mobile app log (Could not apply the mod, or something like that)
Here are the links for two loadouts that I'm trying to change (although it opens for me with error and doesn't show loadout):
First (currently equipped):
https://app.destinyitemmanager.com/optimizer?class=2&p=%7B%22mods%22%3A%5B3682186345%2C322752304%2C322752304%2C3632726238%2C2850583378%2C4184328258%2C1515669996%2C2645858828%2C3566745556%2C2588939505%2C3523075120%2C2645858828%2C3598368346%2C3598368346%2C1824486242%2C3947616002%2C3561960031%2C4288515061%5D%7D
Second one (trying to apply):
https://app.destinyitemmanager.com/optimizer?class=2&p=%7B%22mods%22%3A%5B2850583378%2C3319681729%2C2919349723%2C2645858828%2C2214082005%2C2645858828%2C2379452959%2C3523075120%2C2645858828%2C2001283033%2C3632726238%2C2645858828%2C3561960031%2C3632726237%5D%7D

When I try to apply loadout, i get "DimError: Bungie.net message: The request to modify an item failed. Refresh the item and try again"

Here are the screens if needed:
https://imgur.com/a/KrJGU4y

### Logs

```shell
Process inventory: 93.0009765625 ms
log.ts:44 Inventory state update: 142.9208984375 ms
instrument.ts:130 [loadout mods] Mods to apply (14) [2850583378, 3319681729, 2919349723, 2645858828, 2214082005, 2645858828, 2379452959, 3523075120, 2645858828, 2001283033, 3632726238, 2645858828, 3561960031, 3632726237]
instrument.ts:130 [loadout mods] equipping mod Pulse Rifle Targeting into The Stag socket 1
instrument.ts:159 POST https://www.bungie.net/Platform/Destiny2/Actions/Items/InsertSocketPlugFree/ 500
(anonymous) @ instrument.ts:159
l @ authenticated-fetch.ts:48
await in l (async)
processQueue @ rate-limiter.ts:68
add @ rate-limiter.ts:45
(anonymous) @ rate-limiter.ts:118
(anonymous) @ http-client.ts:126
(anonymous) @ http-client.ts:160
(anonymous) @ http-client.ts:254
(anonymous) @ http-client.ts:201
(anonymous) @ bungie-service-helper.ts:90
v @ api.js:155
Z @ advanced-write-actions.ts:130
(anonymous) @ advanced-write-actions.ts:100
(anonymous) @ index.js:16
dispatch @ redux.js:659
(anonymous) @ loadout-apply.ts:764
(anonymous) @ index.js:16
dispatch @ redux.js:659
(anonymous) @ loadout-apply.ts:664
(anonymous) @ index.js:16
dispatch @ redux.js:659
(anonymous) @ loadout-apply.ts:292
await in (anonymous) (async)
(anonymous) @ index.js:16
dispatch @ redux.js:659
(anonymous) @ loadout-apply.ts:104
(anonymous) @ action-queue.ts:13
Promise.then (async)
a @ action-queue.ts:12
(anonymous) @ loadout-apply.ts:103
(anonymous) @ index.js:16
onClick @ Loadouts.tsx:259
Be @ react-dom.production.min.js:52
qe @ react-dom.production.min.js:52
(anonymous) @ react-dom.production.min.js:53
Tr @ react-dom.production.min.js:100
Pr @ react-dom.production.min.js:101
(anonymous) @ react-dom.production.min.js:113
je @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
Mr @ react-dom.production.min.js:105
Qt @ react-dom.production.min.js:75
Xt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
$o @ react-dom.production.min.js:122
Re @ react-dom.production.min.js:292
Gt @ react-dom.production.min.js:73
r @ helpers.ts:88
instrument.ts:130 [AWA] Couldn't insert plug {owner: '2305843009881434113', destinyVersion: 2, location: {…}, bucket: {…}, hash: 2177524718, …}ammoType: 0amount: 1availableMetricCategoryNodeHashes: undefinedbreakerType: nullbucket: {description: 'Helmets and hoods.', name: 'Helmet', hash: 3448274439, hasTransferDestination: true, capacity: 10, …}canPullFromPostmaster: trueclassType: 2classTypeNameLocalized: "Warlock"classified: falsecollectibleHash: 846189251collectibleState: 0comparable: truecomplete: falsedescription: ""destinyVersion: 2displaySource: ""element: {displayProperties: {…}, transparentIconPath: '/img/destiny_content/damage_types/destiny2/void_trans.png', showIcon: true, enumValue: 3, capacityStatHash: 16120457, …}energy: {energyTypeHash: 4069572561, energyType: 3, energyCapacity: 9, energyUsed: 9, energyUnused: 0}equipRequiredLevel: 50equipment: trueequipped: trueequippingLabel: "exotic_armor"hash: 2177524718hiddenOverlay: "/common/destiny2_content/icons/591f14483308beaad3278c3cd397e284.png"hidePercentage: falseicon: "/common/destiny2_content/icons/16634beca2ccdda00a47e8615dbc89f7.jpg"iconOverlay: "/common/destiny2_content/icons/591f14483308beaad3278c3cd397e284.png"id: "6917529501639155539"index: "6917529501639155539"infusable: trueinfusionFuel: trueinfusionQuality: {itemLevels: Array(0), qualityLevel: 0, infusionCategoryName: '1046741990', infusionCategoryHash: 1046741990, infusionCategoryHashes: Array(1), …}isEngram: falseisExotic: trueitemCategoryHashes: (3) [21, 45, 20]location: {description: 'Helmets and hoods.', name: 'Helmet', hash: 3448274439, hasTransferDestination: true, capacity: 10, …}lockable: truelocked: trueloreHash: 3008550972masterwork: falsemasterworkInfo: {tier: 9, stats: Array(1)}maxStackSize: 1metricHash: undefinedmetricObjective: undefinedmissingSockets: falsename: "The Stag"notransfer: falseobjectives: nullowner: "2305843009881434113"percentComplete: 0perks: nullplug: undefinedpower: 1330powerCap: nullpreviewVendor: 0primaryStat: {statHash: 3897883278, value: 1330, stat: {…}}pursuit: nullsecondaryIcon: "/common/destiny2_content/screenshots/2177524718.jpg"sockets: {allSockets: Array(12), categories: Array(4)}source: 1563875874stats: (7) [{…}, {…}, {…}, {…}, {…}, {…}, {…}]taggable: truetalentGrid: nulltier: "Exotic"trackable: falsetracked: falsetype: "Helmet"typeName: "Helmet"uniqueStack: false[[Prototype]]: Object DimError: Bungie.net message: The request to modify an item failed. Refresh the item and try again.
    at bungie-service-helper.ts:206
    at bungie-service-helper.ts:92
    at async advanced-write-actions.ts:100
    at async loadout-apply.ts:762
    at async loadout-apply.ts:664
    at async loadout-apply.ts:292
(anonymous) @ instrument.ts:130
s @ log.ts:33
(anonymous) @ advanced-write-actions.ts:108
await in (anonymous) (async)
(anonymous) @ index.js:16
dispatch @ redux.js:659
(anonymous) @ loadout-apply.ts:764
(anonymous) @ index.js:16
dispatch @ redux.js:659
(anonymous) @ loadout-apply.ts:664
(anonymous) @ index.js:16
dispatch @ redux.js:659
(anonymous) @ loadout-apply.ts:292
await in (anonymous) (async)
(anonymous) @ index.js:16
dispatch @ redux.js:659
(anonymous) @ loadout-apply.ts:104
(anonymous) @ action-queue.ts:13
Promise.then (async)
a @ action-queue.ts:12
(anonymous) @ loadout-apply.ts:103
(anonymous) @ index.js:16
onClick @ Loadouts.tsx:259
Be @ react-dom.production.min.js:52
qe @ react-dom.production.min.js:52
(anonymous) @ react-dom.production.min.js:53
Tr @ react-dom.production.min.js:100
Pr @ react-dom.production.min.js:101
(anonymous) @ react-dom.production.min.js:113
je @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
Mr @ react-dom.production.min.js:105
Qt @ react-dom.production.min.js:75
Xt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
$o @ react-dom.production.min.js:122
Re @ react-dom.production.min.js:292
Gt @ react-dom.production.min.js:73
r @ helpers.ts:88
loadout-apply.ts:142 Uncaught (in promise) DimError: Bungie.net message: The request to modify an item failed. Refresh the item and try again.
    at bungie-service-helper.ts:206
    at bungie-service-helper.ts:92
    at async advanced-write-actions.ts:100
    at async loadout-apply.ts:762
    at async loadout-apply.ts:664
    at async loadout-apply.ts:292
```

**Comment by RemnantOfFire** [comment]
I'm also having this issue and it appears to be tied to armor mods in the loadout for me at least. I made duplicates of my loadouts without any armor mods and they worked fine so that's what I'd say to do until this gets fixed.

**Comment by coxd6953** [comment]
Also having this issue. 
Thanks. 

![Screenshot_20211208-073905](https://user-images.githubusercontent.com/43526859/145210086-7c0e93c0-05d4-4f6e-8bbf-7b8bd455e687.png)

**Comment by delphiactual** [comment]
@coxd6953 please try on https://beta.destinyitemmanager.com

**Comment by effernity** [comment]
@delphiactual looks like it's working, but I get this error(?)
![image](https://user-images.githubusercontent.com/20191947/145221239-1bbbda50-e749-4f30-a33d-c2f950bfac67.png)

Maybe it's because of my two loadouts share some items?

**Comment by delphiactual** [comment]
do you have the available energy to slot the mods?

**Comment by effernity** [comment]
Yes
Here are my 2 loadouts:
![image](https://user-images.githubusercontent.com/20191947/145228241-3f7c8508-0bc8-4217-a273-726414df73da.png)
![image](https://user-images.githubusercontent.com/20191947/145228302-2537c006-74ad-4523-b762-3c3a3fffa972.png)

**Comment by effernity** [comment]
Yep, sure
`log.ts:44 Process inventory: 61.764892578125 ms
log.ts:44 Inventory state update: 303.279052734375 ms
instrument.ts:130 [loadout] Apply loadout ticuus to Awoken Warlock
instrument.ts:130 [move] Try blind move of Ticuu's Divination to Awoken Warlock
instrument.ts:130 [move] Move 1 Ticuu's Divination Energy to Awoken Warlock from Vault
instrument.ts:130 [loadout mods] Mods to apply (14) [2850583378, 3319681729, 2919349723, 2645858828, 2214082005, 2645858828, 2379452959, 3523075120, 2645858828, 2001283033, 3632726238, 2645858828, 3561960031, 3632726237]
instrument.ts:130 [loadout mods] equipping mod Grenade Launcher Dexterity into Pathfinder's Wraps socket 1
instrument.ts:130 [loadout mods] equipping mod Empty Mod Socket into Pathfinder's Pants socket 2
instrument.ts:130 [loadout mods] equipping mod High-Energy Fire into Pathfinder's Pants socket 3
instrument.ts:130 [loadout mods] equipping mod Pulse Rifle Holster into Pathfinder's Pants socket 1
instrument.ts:130 [loadout mods] equipping mod Empty Mod Socket into Tethering Void socket 1
instrument.ts:130 [loadout mods] equipping mod Empty Mod Socket into Tethering Void socket 3
instrument.ts:130 [loadout mods] equipping mod Recovery Mod into Tethering Void socket 0
instrument.ts:130 [loadout mods] Mods applied 7 14`

There are no errors, only that message on the site itself
Again, the loadout seems to be applied correctly

**Comment by ryan-rushton** [comment]
Yeah I think there are some issues with that message. I was messing with what I thought should be correct the other night but was getting that it appled 20 out of 15 mods, so I wasn't quite there. I will try again in a bit.

**Comment by ryan-rushton** [comment]
I just read through the code in it's current form. I think @bhollis has fixed it. @effernity can you verify for us on beta whether you think this is fixed

**Comment by effernity** [comment]
Yep, can confirm, everything is working on beta:
![image](https://user-images.githubusercontent.com/20191947/145389869-3aebf64d-6072-42f0-8be8-0f603d18b284.png)
No error message

**Comment by ryan-rushton** [comment]
Awesome, I might leave this up until the changes hit prod then close it. Thanks for the report!

**Comment by effernity** [comment]
Thank you for your amazing work!
