### ISSUE TITLE
DIM Loadout Error

### ISSUE THREAD

**Issue by coxd6953** [DestinyItemManager/DIM#7406]
Saved Loadout will not update Subclass or import exotic armor. 

![Screenshot_20211208-073905](https://user-images.githubusercontent.com/43526859/145209795-960bd471-e2d0-46f8-b5a6-fcc2b5fc171d.png)

Installed and updated Destiny 2 Companion App. 

Thanks.

**Comment by delphiactual** [comment]
Dupe #7405
