### ISSUE TITLE
LO assigns mods of one element, but displays the item as another element

### ISSUE THREAD

**Issue by tanglueyi** [DestinyItemManager/DIM#7407]
### DIM Version

Ver6.94.0.1000978(beta)，build：2021/12/8 4:48:22pm

### Browser Details

Microsoft Edge 96.0.1054.43

### OS Details

MacOS 12.0.1

### Describe the bug

![](https://cdn.discordapp.com/attachments/333464468241514497/918045447262699530/unknown.png)

**Comment by bhollis** [comment]
Can you provide any more info here that could help? A larger screenshot of your whole build maybe?

**Comment by bhollis** [comment]
Repro - add a mod with some affinity, set upgrades to allow upgrades but without locking element, then scroll until you find something wrong:

![image](https://user-images.githubusercontent.com/313208/145293714-3c49aabf-058a-423f-b8c5-a944935cbf0f.png)

**Comment by tanglueyi** [comment]
A little supplement
![CleanShot 2021-12-09 at 09 27 27@2x](https://user-images.githubusercontent.com/3315564/145317769-04553189-3a0b-47e6-b98f-a73d84e10997.png)
