### ISSUE TITLE
Store on Guardian no longer pulls matching items from postmaster

### ISSUE THREAD

**Issue by Anthropole** [DestinyItemManager/DIM#7409]
### DIM Version

Version 6.94.0.1000980 (beta), Version 6.94.0 (release)

### Browser Details

Brave Version 1.32.113 Chromium: 96.0.4664.45 (Official Build) (x86_64)

### OS Details

MacOS 12.1 Beta (21C5045a)

### Describe the bug

I searched for tag:junk, clicked on the three dots on the right of the search bar, clicked on "Store on Awoken Hunter," and I expected the items in both postmaster, characters and vault to be moved to Awoken Hunter (old behavior) but instead only the items in vault and other characters transferred (the same function as 'Transfer search "x"' from the character drop down menu.

**Comment by delphiactual** [comment]
Dupe #7400
