### ISSUE TITLE
Remove "DIM cannot equip mods, it must be done in game."

### ISSUE THREAD

**Issue by omznc** [DestinyItemManager/DIM#7418]
### DIM Version

Version 6.94.0 (release), built on 12/6/2021, 3:06:08 AM

### Browser Details

Any

### OS Details

Windows 11

### Describe the bug

Since mods are supported now, we should remove
`"ModsInfo": "DIM cannot equip mods, it must be done in game.",`
from the edit loadout overlay, as shown at the bottom of the image below.

![msedge_oGSz0yKloV](https://user-images.githubusercontent.com/38432561/145274913-9db86d42-f422-405d-9016-04b2b48fd645.png)

**Comment by delphiactual** [comment]
try beta
