### ISSUE TITLE
Edge Extension Support

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#742]
Edge has added extension support.  It's currently a closed list of extensions and I've registered DIM to be considered.  

Current issues with Edge support atm:

1.  CSS Variables
2.  Sync'ing Multiple Clients
3.  Some ES6 features such as destructuring are not supported.

**Comment by bhollis** [comment]
Destructuring can be solved by babel, but CSS variables are harder. We
could try to offer a degraded experience. Why do we care about Edge,
though? Anything that can run edge can run chrome. I'd rather go towards an
Electron app than try to support more browsers.

**Comment by bhollis** [comment]
It's also worth noting that I don't own a machine that runs Edge, so I
would never test on it.

**Comment by SunburnedGoose** [comment]
I don't run Firefox so I don't test that build either.

**Comment by bhollis** [comment]
Yup, and we never launched it (I hope we don't, it just adds support burden
for no real gain). The difference is that, if I had to, I could test in
Firefox - I can't test in Edge.

**Comment by SunburnedGoose** [comment]
Could...  https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

Electron is a good goal to have.  Once Bungie releases their authentication feature, we should embrace that model for releases.  If we're committed to releasing DIM on Electron, I'll close this issue.

**Comment by bhollis** [comment]
I'd rather support one desktop app than three browsers. Linking #278.
