### ISSUE TITLE
Allow manual placement of mods

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#7421]
It'd be neat to allow dragging mods into specific locations and saving that with a loadout. Wouldn't even need to do all of them - others could be in an "auto" bucket. This allows people to precisely manage their mods without preventing us from rearranging them all again to fit a new loadout (or a share). 

We could do it by using socketOverrides *in addition to* the flat mods list.

**Comment by ryan-rushton** [comment]
I really like this idea, there is a bit of work but I think it would be worth it.

**Comment by bhollis** [comment]
After a few years without this feature, it doesn't seem to be terribly necessary. I think folks have gotten used to the auto placement, and there's a lot of benefits to it.
