### ISSUE TITLE
Transfer search "X" now pulls matching items in postmaster in addition to in character and in vault

### ISSUE THREAD

**Issue by Anthropole** [DestinyItemManager/DIM#7431]
### DIM Version

Version 6.94.0.1000987 (beta)

### Browser Details

Brave Version 1.32.113 Chromium: 96.0.4664.45 (Official Build) (x86_64)

### OS Details

MacOS 12.1 (21C51)

### Describe the bug

I searched for "tag:junk", clicked on the Guardian banner (Exo Warlock), clicked on 'Transfer search "tag: junk"' and I expected the items in only characters and vault to be moved to Exo Warlock (expected behavior) but instead the items in vault,  characters and postmaster also transferred (the same behavior as "Store on X Y" from the search down menu; where X is Awoken, Exo or Human and Y is Hunter, Titan or Warlock). Release version retains the expected behavior.

**Comment by bhollis** [comment]
Fixed
