### ISSUE TITLE
Finishers in loadouts

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#7436]
Probably as part of "Look loadouts" we should allow adding finishers to loadouts. This would be something new since finishers get locked/unlocked rather than being equipped.

**Comment by Robinatk** [comment]
Does anyone know if this is being looked at?

**Comment by bhollis** [comment]
Nobody has claimed the task. Loadouts are probably going to change significantly in Lightfall so there's not a lot of energy for making more loadout features in the meantime.

**Comment by robojumper** [comment]
This is obsolete now -- as per the [TWID 2023-08-24](https://www.bungie.net/7/en/News/Article/this-week-in-destiny-8-24-23):

> FINISHER CHANGES
>
> With the launch of 7.2.0, the option to favorite cosmetics was added to the game. As a result of this implementation, the option to favorite Finishers in player inventories was deprecated. Players who would like to only use specific Finishers in gameplay can Store their Finishers in their Flair Collections. To obtain them again or to obtain other Finishers, players can reacquire them in their Collections under Flair > Finishers.
