### ISSUE TITLE
Investigate idle detection API

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#7441]
https://web.dev/idle-detection/

It'd be interesting to use this combined with reenabling auto refresh.

**Comment by delphiactual** [comment]
there is also this...
https://github.com/qramilq/react-idle-detector
no open issues or PRs though so this may be vaporware

**Comment by bhollis** [comment]
Yeah we've had those in the past, but it's all based on things like "is the mouse moving over the page". This new idle detector is cool because it can tell if you're using your computer in general (playing Destiny for example), even if DIM is off on another screen.

**Comment by bhollis** [comment]
This requires a permission and lots of browsers disable it entirely.
