### ISSUE TITLE
Aeon gauntlets reset to the first Sect when switching to a loadouts

### ISSUE THREAD

**Issue by imagowastaken** [DestinyItemManager/DIM#7442]
### DIM Version

Version 6.94.0.1000994 (beta), built on 12/10/2021, 7:39:36 AM

### Browser Details

Chrome 96.0.4664.93

### OS Details

Windows 11

### Describe the bug

When switching to a loadout with mods and Aeon gauntlets, the gauntlets will be automatically reset to the first "Sect" mod (Sect of Force). I assume this is because when switching loadouts, all the mods will be cleared. It would be nice if there was an exception for that.

**Comment by bhollis** [comment]
Linking #7440 which should handle this. We may need to revisit this if we have a loadout option to clear mods anyway.
