### ISSUE TITLE
Unresolved string variables

### ISSUE THREAD

**Issue by jshaffstall-bng** [DestinyItemManager/DIM#7444]
### DIM Version

Version 6.94.0.1000994 (beta), built on 12/9/2021, 8:39:36 PM

### Browser Details

Chrome Version 96.0.4664.93 (Official Build) (64-bit)

### OS Details

Windows 11

### Describe the bug

1. Open DIM or DIM Beta - https://beta.destinyitemmanager.com/
2. Sign in
3. Select the Progress tab
4. Expand the Ranks sections
5. Mouse over the Strange Favor progression
6. Observe the unresolved string variable in the progression description.

The game is going to keep showing these string variables in new and interesting places, so keep an eye out!

![image](https://user-images.githubusercontent.com/25537692/145643298-45ddeac2-ef03-4b86-9c6d-e7e59243720b.png)

**Comment by delphiactual** [comment]
![image](https://user-images.githubusercontent.com/4798491/146365590-ae6cbab7-b825-4c0c-9a25-5c599e6249e9.png)
