### ISSUE TITLE
Apply perks should not be on the vendor page

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#7447]
### DIM Version

current beta

### Browser Details

chrome

### OS Details

Windows 10

### Describe the bug

The option to apply perks to weapons is active on the vendor page.  It doesn't do anything, but as it can't possible work, it probably shouldn't be there.

![image](https://user-images.githubusercontent.com/25425159/145660746-18edb0f3-bcf9-4e00-a47a-39b4a8fe93bb.png)

**Comment by bhollis** [comment]
Thanks for the catch.
