### ISSUE TITLE
Double Click flashes Move Popup

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#745]
Can we create a timeout for ng-click that opens the popup menu that the ng-double-click can cancel if it fires?  Make the delay small, 300ms.

**Comment by kyleshay** [comment]
i thought about it... but at the same time i didn't want the move popup to appear after an artificial delay. 

figure mostly power users will be using the 2x click feature and they might understand the behavior. 

being said, i could experiment a bit with it if you think we should

**Comment by SunburnedGoose** [comment]
You've got to do it. I tried using it and it makes me have to click away to close the dialogs after dbl click.  Try it and see if there is a sweet spot for the delay.

**Comment by SunburnedGoose** [comment]
Combine popup delay with a close all dialog call so dbl click ensures dialogs are closed and cleans up.

**Comment by bhollis** [comment]
I'm not real bothered by it, but I also don't use the double-click that much. Perhaps it should be press-and-hold instead of double-click?

I'd rather nix the whole feature than add a delay to opening the popup.

**Comment by bhollis** [comment]
http://twitter.com/ID_AA_Carmack/status/762834463063617536

**Comment by kyleshay** [comment]
haha, timely. must have read this issue... 😎

**Comment by kyleshay** [comment]
should we remove this or just let power users experience the flash?

**Comment by SunburnedGoose** [comment]
We haven't tested it yet.

**Comment by SunburnedGoose** [comment]
Touch has a 300ms delay built in to watch for double clicks I believe. I usually remove it when I only need single clicks and taps.

**Comment by bhollis** [comment]
Touch used to have a 300ms delay but most browsers have gotten rid of it because the latency was annoying. And that was only for mobile/touch browsing.
