### ISSUE TITLE
Strange Layout after Double Click

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#746]
I moved Dreadfang to my active character by double clicking.  DIM moved it but it disappeared, and the heavy inventory had a layout rendering error.  Refreshing DIM resolved the issue.  I haven't been able to replicate.

![screen shot 2016-08-05 at 10 41 17 am](https://cloud.githubusercontent.com/assets/984608/17442068/9fe1ca7c-5af9-11e6-9423-fc6b979c68ee.png)

![screen shot 2016-08-05 at 10 41 39 am](https://cloud.githubusercontent.com/assets/984608/17442072/a321f950-5af9-11e6-9f9e-bc829beb586a.png)

**Comment by bhollis** [comment]
That is super weird. What it looks like is that the item didn't get `equipped` set to `true` on it. That'd be a bug in `dimItemService.updateItemModel` but I'm not sure how to repro.

**Comment by SunburnedGoose** [comment]
I have gotten a strange error message when moving an item in DIM.  After it was moved to a character, a toaster appeared, "Cannot find item."

**Comment by bhollis** [comment]
I think I figured it out - the double-click action wasn't wrapped in the action queue, so multiple actions could interleave. Should be fixed now.

**Comment by kyleshay** [comment]
whooops. nice find. i'll be mindful of the action queue, thanks.
