### ISSUE TITLE
Strange Favor's reset count switched with Vanguard's

### ISSUE THREAD

**Issue by f-t-alves** [DestinyItemManager/DIM#7463]
### DIM Version

Version 6.94.0.1001006 (beta), built on 12/11/2021, 9:49:52 PM

### Browser Details

Chrome version 96.0.4664.93

### OS Details

Windows 10

### Describe the bug

In the Progress tab, each rank lists its reset count. Strange Favor (the new Xûr rank) is listing my Vanguard reset count, while the Vanguard node itself is listing no resets.

**Comment by delphiactual** [comment]
https://github.com/Bungie-net/api/issues/1544

**Comment by f-t-alves** [comment]
But why does it show up on Strange Favor at all?

**Comment by delphiactual** [comment]
because that is how bungie has it currently coded.
