### ISSUE TITLE
Handle mods with restrictions on similar mods being applied

### ISSUE THREAD

**Issue by ryan-rushton** [DestinyItemManager/DIM#7465]
## Issue
We don't currently handle insertion rules for mods that can only have a single "similar mod" applied. For example you cannot equip two finisher mods to your class item.

### Mods with this restriction in some form
![image](https://user-images.githubusercontent.com/7344652/145704502-98353497-fb5f-45d3-863f-feda1aee9a57.png)

### Potential fixes
There are potentially a few things we can do
1. Hard code a ruleset of "similar mods"
2. Better error notifications when a mod fails, we could show the user the insertion rule if it fails maybe?

### Example of a failure while applying two finisher mods
![image (1)](https://user-images.githubusercontent.com/7344652/145704564-ed29a796-9b77-434c-8772-f956495a2d43.png)

### Logs

```shell
[loadout] Apply loadout ARTIFICER TEST to Exo Warlock
log.ts:11 [loadout mods] Mods to apply (2) [4237638094, 4237638090]
log.ts:11 [loadout mods] Applying [] to Nezarec's Sin
log.ts:11 [loadout mods] Skipping applying because it would reset all sockets to default
log.ts:11 [loadout mods] Applying [] to Gloves of the Hezen Lords
log.ts:11 [loadout mods] Skipping applying because it would reset all sockets to default
log.ts:11 [loadout mods] Applying [] to Legacy's Oath Robes
log.ts:11 [loadout mods] Skipping applying because it would reset all sockets to default
log.ts:11 [loadout mods] Applying [] to Iron Truage Legs
log.ts:11 [loadout mods] Skipping applying because it would reset all sockets to default
log.ts:11 [loadout mods] Applying (2) [{…}, {…}] to Fragment of the Prime
log.ts:11 [loadout mods] equipping mod Special Finisher into Fragment of the Prime socket 2
authenticated-fetch.ts:48 POST https://www.bungie.net/Platform/Destiny2/Actions/Items/InsertSocketPlugFree/ 500
fetchWithBungieOAuth @ authenticated-fetch.ts:48
await in fetchWithBungieOAuth (async)
processQueue @ rate-limiter.ts:68
add @ rate-limiter.ts:45
(anonymous) @ rate-limiter.ts:118
(anonymous) @ http-client.ts:126
(anonymous) @ http-client.ts:160
(anonymous) @ http-client.ts:236
(anonymous) @ http-client.ts:201
(anonymous) @ bungie-service-helper.ts:90
insertSocketPlugFree @ api.js:155
awaInsertSocketPlugFree @ advanced-write-actions.ts:125
(anonymous) @ advanced-write-actions.ts:110
(anonymous) @ index.js:16
dispatch @ redux.js:659
(anonymous) @ loadout-apply.ts:854
(anonymous) @ index.js:16
dispatch @ redux.js:659
(anonymous) @ loadout-apply.ts:799
(anonymous) @ index.js:16
dispatch @ redux.js:659
(anonymous) @ loadout-apply.ts:332
await in (anonymous) (async)
(anonymous) @ index.js:16
dispatch @ redux.js:659
(anonymous) @ loadout-apply.ts:112
(anonymous) @ action-queue.ts:13
Promise.then (async)
queueAction @ action-queue.ts:12
(anonymous) @ loadout-apply.ts:111
(anonymous) @ index.js:16
dispatch @ VM25092:14608
handleApply @ Loadouts.tsx:251
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4070
executeDispatch @ react-dom.development.js:8243
processDispatchQueueItemsInOrder @ react-dom.development.js:8275
processDispatchQueue @ react-dom.development.js:8288
dispatchEventsForPlugins @ react-dom.development.js:8299
(anonymous) @ react-dom.development.js:8508
batchedEventUpdates$1 @ react-dom.development.js:22396
batchedEventUpdates @ react-dom.development.js:3745
dispatchEventForPluginEventSystem @ react-dom.development.js:8507
attemptToDispatchEvent @ react-dom.development.js:6005
dispatchEvent @ react-dom.development.js:5924
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
discreteUpdates$1 @ react-dom.development.js:22413
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
log.ts:11 [loadout mods] Mods applied 1 2
```
```

**Comment by bhollis** [comment]
I figure we might want to generate a mapping in d2ai of mod affinity and anti-affinity. Mod affinity would be things like Powerful Friends and arc mods, and anti-affinity would be these finisher mods and mods whose bonus doesn't stack on the same piece (are there any?)

Not sure how best to represent that.

**Comment by robojumper** [comment]
Another example of this bug that needs fixing when we have this info: DIM sometimes can't come up with a valid strategy to apply some mods (reported on the Discord):

Loadout:

![grafik](https://user-images.githubusercontent.com/14299449/211862136-6c125d7f-7d70-42ef-90f2-41dbcaeeeba7.png)

Existing mods on the piece:

![grafik](https://user-images.githubusercontent.com/14299449/211862206-c6683fe2-2032-4794-a1be-ff37731fbf79.png)

Mod assignment:

![grafik](https://user-images.githubusercontent.com/14299449/211862282-ca1682a0-eead-41b9-9e0b-d1455e0fec50.png)

DIM needs to change two mods, but:

* Replacing the 1-energy finisher mod with Distribution first can't be done because of energy constraints
* So it tries to place the second finisher mod first, and then change the equipped finisher mod with Distribution

But this fails due to Bungie.net rules. So once we do have mod exclusion rules, this is something where either `pickPlugPositions` needs to get smarter, or `createPluggingStrategy` needs to split a "replace X with Y" action into "replace X with EMPTY, do something else, then replace EMPTY with Y" actions. Gnarly.

**Comment by delphiactual** [comment]
https://github.com/DestinyItemManager/d2-additional-info/pull/432 we could just use the finisher behavior for now...

**Comment by bhollis** [comment]
Are these rules still in place post-Lightfall? Can we figure them out automatically from the tooltips (e.g. stacks vs. doesn't stack)?

**Comment by robojumper** [comment]
So the "Equipping additional copies of this mod provides no benefit." info tooltip mostly describes that slotting two copies of the exact same mod isn't going to provide a benefit, while the "Similar mod already applied" is a hard error condition that DIM must prevent. This condition applies to Fastball (you literally cannot equip two copies of Fastball) and class item Armor Charge finisher mods (where you can only have one copy in that entire group). This must be forbidden in mod selection, and loadout application must ensure to remove any conflicting mod first.
