### ISSUE TITLE
group by name in mod picker?

### ISSUE THREAD

**Issue by nev-r** [DestinyItemManager/DIM#7466]
there's 2 different sections labeled Charged With Light 

also user suggestion i agree with is raids should sort to bottom

**Comment by ryan-rushton** [comment]
This will be easier to do now that I made those changes to the plug picker. Basically where we take a plug set, and create further groups by plug category hash, we should instead make groups by the group name.

Regarding raid mods, I don't have a good suggestions for that without digging.

**Comment by ryan-rushton** [comment]
@nev-r we can close this now right?

**Comment by nev-r** [comment]
yep
