### ISSUE TITLE
Stats don't match between Loadouts page / Mod Assignment, and Mod Assignment shows different mod assignments than what gets applied

### ISSUE THREAD

**Issue by simozx** [DestinyItemManager/DIM#7469]
### DIM Version

Version 6.95.0 (release), built on 13/12/2021, 12:35:34

### Browser Details

Chrome

### OS Details

Windows 10

### Describe the bug

https://www.youtube.com/watch?v=4cdW6A-_Vas

The above video is me going through and showing the bugs take place.

In summary: The stats shown in DIM do not match the actual/in-game stats from the built loadouts. Also, Taking Charge and Elemental Ordnance are being applied to the wrong armour piece, and not following the build on DIM? Not sure if exclusive to those mods, or i've created the loadout incorrectly, but yeah.

insipidAce#3333 made a good comment on the Discord server here which may relate to what's happening - https://discord.com/channels/316217202766512130/333464468241514497/919811656316518420

**Comment by bhollis** [comment]
Could've sworn I already had an issue for the stats thing, but I filed it as #7472.

**Comment by bhollis** [comment]
The second bug, if I may rephrase, is that the mods that were actually applied by a loadout don't match what the "Show Mod Assignment" menu shows. Is that right?

**Comment by simozx** [comment]
> 

Yes correct. The 'Show Mod Placement' has my gloves with Elemental Ordnance and my chest with Taking Charge. When I go to the loadout and click Apply, it then changes the gloves to Taking Charge and changes the chest to Elemental Ordnance, when no change is necessary.

The mods being applied do not 1:1 match the loadout in the 'Show Mod Placement' button

Hopefully this clears it up a bit, thanks

**Comment by ryan-rushton** [comment]
@simozx can you see if the mod application issue persists after the latest release?
