### ISSUE TITLE
Popup for Xur Items remains after Dialog is Dismissed

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#747]
Open Xur, and click on an item to show the popup.  Now click elsewhere on the page to dismiss the Xur dialog.  The popup will remain on screen.  I cannot dismiss the popup until I reopen Xur again.

![screen shot 2016-08-05 at 11 08 23 am](https://cloud.githubusercontent.com/assets/984608/17442799/3b5a62ea-5afd-11e6-93e1-a956f01d6325.png)

**Comment by ericnelson0** [comment]
Just want to keep a note that this will apply to vendors as well.
