### ISSUE TITLE
Selecting a second mod slot from the GeneratedSet mods erases the first

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#7470]
1. Go to Loadout Optimizer
2. Click on one of the mod slots on one of the generated sets and choose a mod
3. Click on a second mod slot on the same item of that set, and choose another mod
4. The first mod is gone

You'll notice that even in step 3, the original selected mod isn't there. I tracked it as far as `PlugDrawer#createInternalSelectedState` but I'm honestly not sure what's going on there.

**Comment by ryan-rushton** [comment]
I will fix it tonight. I need to do more refactoring of this stuff to try and make it more obvious too
