### ISSUE TITLE
Show mod slot name in mod tooltip

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#7473]
It'd be great for places where they're shown out of the context of their slot, to know where they go.

**Comment by vivekhnz** [comment]
I started looking into this and noted a few things:

- We already show the mod type (`DestinyInventoryItemDefinition.itemTypeDisplayName`) in the tooltip for empty 'specialty' sockets (e.g. Combat Style, Raid etc.)
![dim-mod-tooltip-subtype](https://user-images.githubusercontent.com/17512262/146365520-c9b68a19-2905-4635-bf0a-1d743cd13e3e.png)
- It should be straightforward to expand this to all mods e.g.
![dim-mod-tooltip-subtype-2](https://user-images.githubusercontent.com/17512262/146366248-33c96010-b2c7-48b5-8259-f54e54257dcc.png)
- In most cases, the mod's `itemTypeDisplayName` will be the same as the socket's name (only **Helmet Armor Mods** go into a **Helmet Armor Mod Slot**) but there are exceptions e.g. the **Combat Style Armor Mod** slot contains **Charged With Light**, **Warmind Cell** and **Elemental Well** mods
- Always showing the mod type might make the tooltip look a bit busy. Maybe we should adjust the styling of it to make it easier to distinguish from the mod name? e.g.
![dim-mod-tooltip-subtype-3](https://user-images.githubusercontent.com/17512262/146367454-ed14ffa3-b856-4328-8361-abb57fb5c690.png)
- Should we show the subtype for perks as well? e.g.
![dim-mod-tooltip-subtype-4](https://user-images.githubusercontent.com/17512262/146368788-c4678ebb-9207-493e-8523-01430c5d0619.png)
