### ISSUE TITLE
Add support for elemental searches in add mod screen of loadout optimizer

### ISSUE THREAD

**Issue by billwert** [DestinyItemManager/DIM#7474]
### Proposed change

I would like to be able to see only mods of a given element in the add mod panel. Typing `is:arc` in the search of the add mod panel didn't behave as I'd expected.

### How does this fit into your workflow?

For mods that depend on other mods of a given element being equipped (such as Powerful Friends) it's nice to be able to look only at the mods of the same type to pick one.

**Comment by delphiactual** [comment]
#7468

**Comment by bhollis** [comment]
We really need a full search config for mods. It'd be great to have a set of search pills for common searches like this too.

**Comment by bhollis** [comment]
Mods will no longer have elements in Nightfall.
