### ISSUE TITLE
Mods not being removed/added from Loadouts?

### ISSUE THREAD

**Issue by Deepy73** [DestinyItemManager/DIM#7478]
### DIM Version

6.95.0

### Browser Details

Safari

### OS Details

iOS

### Describe the bug

So, when changing loadouts, some mods on armor pieces don't remove or won't add. Example in my case, I'm running an Auto Rifle Reload mod in my gauntlets. When I hit "Apply" loadout, it also adds a Fusion Rifle Loader mod, which is present on another build I have, but not on the one I want to apply. The same is also happening on my class item, it adds a Supercharged mod into my loadout, even though there isn't one in my actual build. Thanks in advance.

### Logs

[loadout] Apply loadout Font of Might and Nezarec Build to Awoken Warlock
instrument.ts:130 [loadout mods] Mods to apply Array(14)
instrument.ts:130 [loadout mods] Applying Array(3) to Nezarec's Sin
instrument.ts:130 [loadout mods] Applying Array(3) to Pathfinder's Wraps
instrument.ts:130 [loadout mods] equipping mod Font of Might into Pathfinder's Wraps socket 3
instrument.ts:130 [loadout mods] equipping mod Discipline Mod into Pathfinder's Wraps socket 0
instrument.ts:130 [loadout mods] equipping mod Auto Rifle Loader into Pathfinder's Wraps socket 1
instrument.ts:130 [loadout mods] Applying Array(4) to Philomath Robes
instrument.ts:130 [loadout mods] Applying Array(3) to Tesseract Trace IV
instrument.ts:130 [loadout mods] equipping mod Font of Might into Tesseract Trace IV socket 3
instrument.ts:130 [loadout mods] equipping mod Minor Discipline Mod into Tesseract Trace IV socket 0
instrument.ts:130 [loadout mods] equipping mod Rocket Launcher Scavenger into Tesseract Trace IV socket 1
instrument.ts:130 [loadout mods] Applying Array(1) to Memory of Cayde
instrument.ts:130 [loadout mods] equipping mod Bomber into Memory of Cayde socket 1
instrument.ts:130 [loadout mods] Mods applied 14 14

**Comment by ryan-rushton** [comment]
Can we get some logs when the issue happens. They can be found by opening developer tools in chrome and getting the relevant output of the `console` tab.

**Comment by Deepy73** [comment]
![Screenshot_20211214-181428_Samsung Internet](https://user-images.githubusercontent.com/96087563/146056377-7cf87121-f7e7-4670-ae11-59a6fbe1ef3e.jpg)
![Screenshot_20211214-181437_Samsung Internet](https://user-images.githubusercontent.com/96087563/146056383-29d9236d-d534-488c-a3cc-6e3f328a8217.jpg)

**Comment by Deepy73** [comment]
> ![Screenshot_20211214-181428_Samsung Internet](https://user-images.githubusercontent.com/96087563/146056377-7cf87121-f7e7-4670-ae11-59a6fbe1ef3e.jpg) ![Screenshot_20211214-181437_Samsung Internet](https://user-images.githubusercontent.com/96087563/146056383-29d9236d-d534-488c-a3cc-6e3f328a8217.jpg)

The first screenshot shows what should be applied, the second shows what gets applied instead

**Comment by ryan-rushton** [comment]
Ok so I think I know what is happening here, and the confusion is largely our fault as the messaging is wrong in the notification.

Originally we were wiping all mods and then applying the new mods. Now though we only remove mods if we need to, this means that you may have existing mods stay on your items. I think this is what is happening here as you will notice that the mods in the first screenshot are a subset of the mods in the second screen shot.

The best way to validate this is to go into your character and remove all mods, then apply your loadout. Can you give that a try for me just to ensure we don't have something funky going on? In the meantime I will change the messaging in the notification.

**Comment by Deepy73** [comment]
> Ok so I think I know what is happening here, and the confusion is largely our fault as the messaging is wrong in the notification.
> 
> Originally we were wiping all mods and then applying the new mods. Now though we only remove mods if we need to, this means that you may have existing mods stay on your items. I think this is what is happening here as you will notice that the mods in the first screenshot are a subset of the mods in the second screen shot.
> 
> The best way to validate this is to go into your character and remove all mods, then apply your loadout. Can you give that a try for me just to ensure we don't have something funky going on? In the meantime I will change the messaging in the notification.

Yeah, that seemed to work! Will I have to do this for the time being? 
Many thanks again!

**Comment by ryan-rushton** [comment]
If you really want to clear mods not in the loadout yes. We are planning on having the option to clear all mods that aren't in the loadout but in the interest of reducing strain on bungies servers and wait times for loadout application, we chose this as our initial method applying mods.

**Comment by Deepy73** [comment]
I can live with that until the feature to clear mods that aren't in the loadout comes around! But thank you for your help! Very much appreciated!

**Comment by ryan-rushton** [comment]
No worries at all
