### ISSUE TITLE
Some Well Mods in Loadout Optimizer missing description

### ISSUE THREAD

**Issue by bachmanetti** [DestinyItemManager/DIM#7479]
### DIM Version

Version 6.95.0.1001011 (beta)

### Browser Details

Chrome Version 96.0.4664.110 (Official Build) (64-bit)

### OS Details

Windows 10

### Describe the bug

In the Loadout Optimizer, "Choose your Mods" screen, The following mods have no description:
"Elemental Armaments"
"Elemental Charge"
"Font of Might"

**Comment by bachmanetti** [comment]
Also, "Warmind Cell" section is mislabeled "Charged with Light Mod"
And a few more are missing descriptions:
"Chosen of the Warmind"
"Burning Cells"
"Rage of the Warmind"
"Cellular Suppresion"

**Comment by nev-r** [comment]
fixed f4c20a3daad93a83162f822dfe00baac3b2b3bd7
