### ISSUE TITLE
DIM Platform Toggle Shows Incorrect Platform

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#748]
If I refresh my platform while DIM is refreshing, sometimes I can get DIM into a state where the platform will show Playstation, but I'm seeing my Xbox items.

DIM does not work in this state.

PS Platform with Xbox Characters.

![screen shot 2016-08-05 at 11 15 37 am](https://cloud.githubusercontent.com/assets/984608/17443021/08a561fa-5afe-11e6-93bb-7797a68fb17b.png)

Errors while trying to use DIM in this state.

![screen shot 2016-08-05 at 11 17 19 am](https://cloud.githubusercontent.com/assets/984608/17443064/3cea5880-5afe-11e6-9fe7-790128a9b55e.png)

Refreshing resolves issue.

![screen shot 2016-08-05 at 11 15 52 am](https://cloud.githubusercontent.com/assets/984608/17443025/0b6bdf5e-5afe-11e6-9665-2ebfe9ca9b77.png)

**Comment by bhollis** [comment]
I think this gives me the insight to fix both this and the "all items show as new" problem. Give me some time to build a testing mode that lets me simulate actually having multiple platforms.

**Comment by SunburnedGoose** [comment]
Too bad you can't cancel promises easily.
