### ISSUE TITLE
Consider secondary perk requirements for mods like Heavy Handed and Powerful Friends

### ISSUE THREAD

**Issue by tehtrav** [DestinyItemManager/DIM#7486]
### Proposed change

If mods like Heavy Handed and Arc resist are both in a loadout and there is room for them it would be nice if they could be combined on the same piece of armor. Screenshot below shows an example, if the Heavy Handed and Resilience mod were swapped with the Elemental Ordnance and Recover mod, the secondary perk of Heavy Handed would activate. 

<img width="1203" alt="Screen Shot 2021-12-14 at 7 15 48 PM" src="https://user-images.githubusercontent.com/351975/146099621-534bf374-c15b-4b94-a775-0ea7fde47cb1.png">
 

### How does this fit into your workflow?

This would prevent users having to make corrections to their loadout to activate the secondary perk.

**Comment by delphiactual** [comment]
Dupe #7198

**Comment by delphiactual** [comment]
also this all has to be manually curated with some ruleset
