### ISSUE TITLE
Gear Share Links Go Directly to Login Screen

### ISSUE THREAD

**Issue by mrbeauregardsscooter** [DestinyItemManager/DIM#7487]
Hey guys, not sure if you are aware but when sharing a build loadout, the link generated will require whoever clicks it to link their bungie account. Meaning I click the build link, login and get sent to my own character sheets, then need to click the link again in order to see my friend's build. Please make it so whoever clicks the link can just easily see the build loadout without the need for these extra steps. Thanks for all your hard work love the app!

**Comment by delphiactual** [comment]
Dupe #7449

**Comment by delphiactual** [comment]
This also only occurs if you are using a different version e.g. you are using `beta` and the link was using `app`
