### ISSUE TITLE
nao consigo iniciar minha missão renegados

### ISSUE THREAD

**Issue by ishyno** [DestinyItemManager/DIM#7489]
### DIM Version

destiny 2

### Browser Details

destiny 2

### OS Details

ps4

### Describe the bug

a missao nao aparece

### Logs

```shell
a missao nao aparece
```

**Comment by duckmanBR** [comment]
Opa, isso não é um problema no DIM, é ou na sua conta ou no jogo, e quem pode te ajudar melhor é o pessoal da Bungie.  Manda mensagem no fórum que lá eles te encaminham melhor.
https://help.bungie.net/hc/pt-br

Closed because it's not DIM related
