### ISSUE TITLE
Having an Exotic in an Armor Slot Breaks Loadout with Exotic

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#749]
I have a loadout with an exotic helmet marked as equipped.  If I have an exotic chest piece currently on the character, the loadout will try to 

1. Move all the items to the character.
2. Call equip all to put the gear marked 'equipped' on the character.

Since I have an exotic item on, it fails.

Subsequently applying the Loadout to the character, it will remove the exotic chest piece and then the equip all will succeed.

I should note that the I do have a chest piece in the loadout, but it is not marked as equipped.

**Comment by bhollis** [comment]
Hmm, I'm unable to reproduce this with a loadout that contains an exotic and an already-equipped exotic.

I remember that there used to be a problem with equipItems and exotics -  https://github.com/DestinyItemManager/DIM/issues/323#issuecomment-217699993 - but I fixed it on our side via 3a769929ee3c56ee7fd1893f50ae3d49e0da9640. The only reason I can think this would fail is if Bungie is messing with their API and no longer applying the changes in order.

**Comment by SunburnedGoose** [comment]
Just to roundtrip some side chats about this issue.  Here's my loadout, and the state of the character.

![screen shot 2016-08-06 at 8 59 05 pm](https://cloud.githubusercontent.com/assets/984608/17460014/b47fcbee-5c18-11e6-8238-edf3e370b057.png)

![screen shot 2016-08-06 at 8 59 11 pm](https://cloud.githubusercontent.com/assets/984608/17460015/b87dc930-5c18-11e6-8839-a69a04aa8ab1.png)

The issue is we're trying to equip a loadout with an exotic helmet to a character that already has an exotic chest piece.  The chest piece in the loadout is not marked as equip, so it will not force the exotic chest piece on the character to be unequipped.
