### ISSUE TITLE
Filter for "full" stacks

### ISSUE THREAD

**Issue by DHager** [DestinyItemManager/DIM#7492]
### Proposed change

Add a filter named `is:stackfull` which selects things which are at-capacity for their stack. (This naming means it shares a prefix with `is:stackable`, so it might be easier to discover.)

I think this is a good issue to keep around for first-contributors, since it's simple and low-priority. It can be based off the same logic that sets the `.fullstack` style, where `item.amount === item.maxStackSize`.

### How does this fit into your workflow?

Two main uses:

Highlights stacks that have reached capacity, so that the user knows to spend them, ex:

 * Strange Coins 
 * Treasure Keys
 * Synthcord variations
 * Corrupted Key Codes 
 * Enhancement Prisms
 * Ascendant Shards

 For consumables that support vaulting, makes it easier to move only "complete" stacks into the vault, ex:

 * Enhancement Cores
 * Gunsmith Materials
 * Raid Banners

**Comment by nev-r** [comment]
fixed i think ^
