### ISSUE TITLE
Additional Equipped Menu When Creating Loadout From Equipped.

### ISSUE THREAD

**Issue by ItzIte** [DestinyItemManager/DIM#7499]
### DIM Version

Version 6.95.1.1001024 (beta), built on 12/16/2021, 8:03:59 AM

### Browser Details

Version 1.32.115 Chromium: 96.0.4664.93 (Official Build) (64-bit)

### OS Details

Windows 10

### Describe the bug

When going into the loadouts section of DIM and trying to create a new loadout based on what is already equipped, to save it for later to come back to, instead of just creating a new loadout, it creates the new loadout, as well as creating an additional "equipped" category that will not go away even after a restart. Attempting to delete this new Equipped menu will instead delete the new loadout you were trying to make instead, and then it will go away after a restart.

**Comment by inexorableAce** [comment]
I'm not able to reproduce this. Is it possible that you are just naming the new loudout... "equipped" and that is what you are seeing?

**Comment by ItzIte** [comment]
Here is a video I screen recorded of the issue happening, I am able to very consistently.

https://youtu.be/vZ7ndjMHozk

@inexorableAce

**Comment by bhollis** [comment]
Thanks, we'll try to figure it out.
