### ISSUE TITLE
Android: App install auto rotates despite Auto-rotate being disabled 

### ISSUE THREAD

**Issue by JasonBlackthorn** [DestinyItemManager/DIM#7506]
### DIM Version

Version 6.95.1.1001032 (beta), built on 18/12/2021, 14:13:11

### Browser Details

 Chrome 96.0.4664.140

### OS Details

Android 11

### Describe the bug

Using the app install, DIM will auto-rotate even even Auto-rotate is disabled in system settings. This is actually quite maddening.

Accessed in Chrome, the DIM website does not auto-rotate. This behavior occurs with both the release and beta versions installed as app.

**Comment by bhollis** [comment]
That's a bummer. Can you help us understand how you installed the app? There's lots of ways to install DIM.

**Comment by JasonBlackthorn** [comment]
I installed the app by going to the website on my device in Chrome and selected "Install as an App" from the side-menu.

I'd be a little surprised if installation method altered this behavior - I'm also a not familiar with the other ways to do it. If you let me know other methods I'll be happy to test them (I have significant QA experience).

Some apps still auto-rotate even when it is disabled in settings (notably the Camera app). I vaguely suspect there's flag for it, somewhere...

**Comment by delphiactual** [comment]
https://github.com/discourse/discourse/pull/4703

**Comment by delphiactual** [comment]
https://github.com/DestinyItemManager/DIM/commit/6940e54a9b54703a3f4b6041f9dd8048ca655455#diff-6adbf45b60c2a066e82b84c3cdfe262d8fda0bae85813b36c8156d456ebee230R41

**Comment by JasonBlackthorn** [comment]
Thank you for reopening the issue. 

To my surprise, the switch to natural orientation via #7532 did not not resolve it, and it still occurs in Version 6.99.1.1001184 (beta), built on 10/01/2022, 11:32:08

**Comment by JasonBlackthorn** [comment]
Oh. Uninstalling the installed-as-app version and reinstalling it resolves the issue (the orientation tag must be have been persisting despite updates).

I really should have checked that first - I apologize for wasting your time.

Thank you for the fix! It was driving me crazy.
