### ISSUE TITLE
View to Screenshot Guardian

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#751]
Would be useful to have a view in DIM for users to screenshot (can we do it for them?) their Character and let them show off their gear.  Could let them pick and choose what to show off, and in what manner.

**Comment by Mulchman** [comment]
Or a static version of DIM? Eh? Eh?

**Comment by SunburnedGoose** [comment]
Static in what way?  We're not hosting a snapshot of characters if that's what your meaning.

**Comment by kyleshay** [comment]
would be an awesome thing to have, but sadly the chrome API that provides that requires us to have a pretty intense permission

> Read and modify all your data on all websites you visit

more info:
https://developer.chrome.com/extensions/tabs#method-captureVisibleTab

**Comment by bhollis** [comment]
+1 to @kyleshay's comment - OS built-in screenshot or another chrome extension are a more general solution.

**Comment by SunburnedGoose** [comment]
Screenshots aside, having a view that lets a user show off their character would be helpful expecially since DIM is now so VERY LOOOOOOONG :)

**Comment by kyleshay** [comment]
how would it be different and where would that view live? the nice thing now is people can collapse sections and shrink the icon size, so taking a screenshot might be a bit more manageable.

**Comment by SunburnedGoose** [comment]
I like how we can see perks and selected nodes in the loadout builders.

I would like a panel that would show the current character's equipped items, perks with nodes, and their tiers.  I want them to screenshot it for a #Year2Items contest.

Not much happens when I click on the player card in the header...

**Comment by SunburnedGoose** [comment]
1.
![b6951672-5e76-11e6-9fe6-b85b76e19750](https://cloud.githubusercontent.com/assets/984608/17539815/ec6a8fd4-5e76-11e6-981b-df05e59198be.png)

2.
![48299c1c-5e76-11e6-9b17-6b9fb56f7210](https://cloud.githubusercontent.com/assets/984608/17539816/ec75a6a8-5e76-11e6-88b6-d2ea1be43a67.png)

3.
![afd041f0-5e75-11e6-9d8e-5c3c2002aa3d](https://cloud.githubusercontent.com/assets/984608/17539817/ec826e88-5e76-11e6-87bb-b0fe62bb789d.png)

**Comment by Mulchman** [comment]
Off Center Disease people will probably prefer 1 or 3

**Comment by SunburnedGoose** [comment]
![image](https://cloud.githubusercontent.com/assets/984608/17539901/b6d46998-5e77-11e6-9198-5c8dc4283a9a.png)

**Comment by SunburnedGoose** [comment]
![image](https://cloud.githubusercontent.com/assets/984608/17539902/c101ebd4-5e77-11e6-9a83-27d17ccd4552.png)

**Comment by SunburnedGoose** [comment]
5

![image](https://cloud.githubusercontent.com/assets/984608/17539941/1094a5ce-5e78-11e6-8659-a675e12b9585.png)

**Comment by SunburnedGoose** [comment]
Regardless of what we do, this format fits really well in a tweet.  It would look amazing for Y2Gear Celebration.  

![screen shot 2016-08-09 at 9 40 32 pm](https://cloud.githubusercontent.com/assets/984608/17540215/077cc3f2-5e7a-11e6-821a-8a0f51839420.png)

**Comment by kyleshay** [comment]
would be cool if we loaded the 3d model of the char with that gear equipped.. 😎

**Comment by SunburnedGoose** [comment]
Oh man that's too cool but too much :)
 
Need to work on this for the #YearTwoItems giveaway.

**Comment by kyleshay** [comment]
Maybe we can reopen something like this for D2
