### ISSUE TITLE
Cache Vendor Endpoint for 15m

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#752]
From Bungie,

> I'll be changing up my code to start using the character endpoints as much as I can. Since they aren't affected by long caching. It's a better solution than having the people at Reddit wait a minimum of 15 minutes until the issue causing the high caching is solved.
> I already expected that the flip-flopping was caused by multiple servers/a loadbalancer. Didn't know it was controlled by cookies though (only really looked at the auth cookies). I'll see if I can easily set the cookies, a consistent response for all requests would be pretty nice.
> Do you have an idea when the caching time will lower? If not, I and I think others would appreciate it if you gave us an update here if it lowers (and to how much) so we can update our systems. thanks!

We should cache our request to that end point to speed up refreshes and avoid 1.2s requests to the advisor endpoint.  Currently Bungie is caching the request so subsequent alls are ~200ms but we can avoid the request all together if we reuse the promise.

**Comment by bhollis** [comment]
In #741 @ericnelson0 is changing to only reloading vendors when their refresh time is up.

**Comment by kyleshay** [comment]
not seeing vendor cached requests. did that go in? DIM beta branch is always reloading the vendors... causing a longer startup (for me, at least)

<img width="1590" alt="screen shot 2016-09-06 at 9 12 18 pm" src="https://cloud.githubusercontent.com/assets/424158/18296292/a131f226-7476-11e6-989b-1f4f39daae19.png">

**Comment by SunburnedGoose** [comment]
First load is long, and subsequent refreshes are faster.

**Comment by kyleshay** [comment]
it always takes that long (I don't have disable cache checked)

maybe it's just me?

we should also consider lazy loading those endpoints...

**Comment by SunburnedGoose** [comment]
Definitely should lazy load.

**Comment by ericnelson0** [comment]
If you're talking about the 3 calls each that is because the vendors are tied to characters hence one call for each. After that it shouldn't be called again until the minimum time remaining on a refresh for a vendor is up.

My load times are around 5s or less. You said yours was ~20s?

**Comment by kyleshay** [comment]
hmm. that's weird. yeah load time is ~20s each time i close and re-open dim.

**Comment by ericnelson0** [comment]
@bhollis and I talked about doing a lazy load at one point, but figured after the initial load it wouldn't be a problem, plus it makes it a lot easier when using the vendor items in the loadout builder, but 20s is just ridiculous.

**Comment by kyleshay** [comment]
derrrrrpppp. sorry all. forgot my NAS was syncing all of my photos to amazon drive... essentially killing my network traffic. paused the sync and vendors are coming down quicker/DIM loads in 5s...

😨
