### ISSUE TITLE
Subclass and tree issues

### ISSUE THREAD

**Issue by pinomat81** [DestinyItemManager/DIM#7524]
### DIM Version

Version 6.96.0.1001043 (beta), built on 21/12/2021, 11:45:20

### Browser Details

Version 96.0.4664.110 (Build officiel) (64 bits)

### OS Details

Windows 10 LTSC 2021

### Describe the bug

Hello, 

I have 4 issues, I don't know if they are known issues, improvement or real bugs : 
1) Inventory Pages - subclasses shows 0% for all character. Waiting for a few seconds to a few minutes and it will appears with the correct tree
![0pct](https://user-images.githubusercontent.com/96484147/146955981-34c4f42b-8ce6-44b2-acec-aa5e83907330.jpg)
![0_pct](https://user-images.githubusercontent.com/96484147/146955984-04ee7add-2876-402a-ac6b-e71fb9de95b9.jpg)
2) Subclass tree/Subclass do not apply correctly to the Destiny 2 character. When subclass tree is different than the one selected ingame for the subclass, it will not apply subclass at all. i.e. : I have a loadout with arc+middle tree. If ingame I have arc subtree+bottom tree selected, it will change subclass but not subclass tree. Sometimes it even do not change subclass at all.
3) In loadouts page, subclass is sometimes not correctly displayed in the list.
![loadouts_no subclass](https://user-images.githubusercontent.com/96484147/146955971-a90a842c-7cb4-4210-b081-9ef7ee5ba3b3.jpg)
![loadouts_no subclass_2](https://user-images.githubusercontent.com/96484147/146955976-dfe3613d-c589-4003-ac32-6d6478a85755.jpg)
4) In loadouts panel, it shows multiple subclass for the same class when you have more than 1 character for that class
![multiple subclass](https://user-images.githubusercontent.com/96484147/146955978-468b7918-52f6-4623-82db-28a0b58e44c0.jpg)

**Comment by bhollis** [comment]
* 1 is something of a known issue but should be fixed - Initially we load without sockets/talents to get to the inventory display faster, but it causes those items to display weird until the followup load that includes sockets/talents.
* 2 is expected - there's no way to change Light subclass trees from the API, only Stasis. Light subclasses will be updated in the next year to the same system as Stasis.
* 2b is a bug, it should always swap subclass, do you have logs?
* 3 is a bug, no idea why it wouldn't show
* 4 is a bug but an easy one

It's helpful to have these all filed as separate bugs instead of one giant bug, so they can be dealt with independently. It's also helpful if you can provide logs for any case where you're trying to apply a loadout but it doesn't work as you'd expect.

**Comment by bhollis** [comment]
I suspect 3 is that you've chosen the subclass instance from one character and are displaying on another character. The Loadout should be smart enough to pick the right subclass when applying but the Loadouts display may not be.

**Comment by pinomat81** [comment]
@bhollis Thank you. I will create separate issues for bugs and check for logs for point 2b.

**Comment by ryan-rushton** [comment]
Will check those issues out today. Also as @bhollis pointed out we need logs for 2b, otherwise all I can try and do is recreate it. I have 3 different classes for characters so I may not be able to recreate the issue if the root cause is coming from that.

**Comment by pinomat81** [comment]
About 2b here are the logs (I hope this is what you expected).
[logs.txt](https://github.com/DestinyItemManager/DIM/files/7770686/logs.txt)
![2b](https://user-images.githubusercontent.com/96484147/147274055-4462b505-2d9a-4ae1-a9f9-2e1e05c33272.jpg)
So I tried to apply Loadout "LS - Aphelion's Rest" on Titan with Red Banner.

**Comment by ryan-rushton** [comment]
Been having a look at this I think we need #7491 before we can actually fix this. This all stems from having two characters of the same class (I think). My hypothesis is that each character has its own subclass.

@pinomat81 as a workaround you can likely "fix" this issue by adding both titan subclasses, and in the case of stasis having the same set of abilities, aspects, and fragments on each. 

It would actually be excellent if you could test this for me and see if the issue goes away. It would confirm my suspicions, I don't particularly want to delete a character to test this.

**Comment by pinomat81** [comment]
You are totally right. This is because I have 2 titans. In DIM when I select 1 titan then the other, the interface shows correctly the subclass.
![Titan 2](https://user-images.githubusercontent.com/96484147/147597363-9292a2b8-7d53-4e88-8278-01dfa52aeb7f.jpg)
![Titan 1](https://user-images.githubusercontent.com/96484147/147597367-192d3e1e-30db-4055-9cb3-b59c531db3e8.jpg)

I also could test in loadout when I select the first titan's subclass, it shows correctly on the first Titan and not on the second titan and vice versa.
How can I add both titan subclasses ? I tried but I can only select one subclass for titan and one for the other class (I think this is not yet possible)...

**Comment by ryan-rushton** [comment]
Ok as a temporary solution for you I might change that check if I can so you can select a subclass for each character, if I can that is.

**Comment by pinomat81** [comment]
thanks ;)

**Comment by ryan-rushton** [comment]
@pinomat81 a fix is now in beta version 6.97.3.1001107 (or later). I think I fixed this properly, so rather than needing to save two subclasses it should work off a single one, I think. If you can test it for me and verify it would be much appreciated.

**Comment by pinomat81** [comment]
![Sans titre 1](https://user-images.githubusercontent.com/96484147/147855871-e4220c52-c99f-4c83-9f92-74007ed28c2b.jpg)
![Sans titre](https://user-images.githubusercontent.com/96484147/147855872-acc76410-89a9-4e5a-90a0-1b0d990910ac.jpg)
Hey, That seems to do the job. Now loadouts applies correctly whatever Titan I use.
Thank you.
