### ISSUE TITLE
Line breaks for Loadout Notes

### ISSUE THREAD

**Issue by 8BitYoda** [DestinyItemManager/DIM#7525]
### Proposed change

Note: This is purely a stylistic request

Add `white-space: pre-line`, or `white-space: pre-wrap`, to the `.loadoutNotes` class to preserve any whitespace added by the user when writing notes for their loadout.

This change would also bring loadout notes inline with how gun/armor notes are formatted. 

### How does this fit into your workflow?

This change would allow users to create makeshift bulleted lists within their notes or add newlines between notes. The css default of `white-space normal` causes any notes that contain line returns to be rendered as just spaces and thus collapsed down into a single line to fill the container.

**Comment by bhollis** [comment]
Sounds good, want to submit a PR?

**Comment by 8BitYoda** [comment]
@bhollis sure, while I'm at it are there any other "note" type text areas out there that you can think of off hand that would benefit from a similar update?

**Comment by bhollis** [comment]
Not offhand
