### ISSUE TITLE
I hope to be able to manually adjust the position of the MOD

### ISSUE THREAD

**Issue by yuehongcheng** [DestinyItemManager/DIM#7545]
### Proposed change

I hope to be able to manually adjust the position of the MOD

### How does this fit into your workflow?

https://imgur.com/a/74EIifu

I want to change the position of these two mods, but I can't do it

**Comment by ryan-rushton** [comment]
It is planned, not sure on ETA

**Comment by bhollis** [comment]
Duplicate of #7421

**Comment by bhollis** [comment]
It would help to know why you want to change the assignment of those two mods.
