### ISSUE TITLE
Missing item doesn't go away after selecting a replacement or clicking the X

### ISSUE THREAD

**Issue by Anthropole** [DestinyItemManager/DIM#7547]
### DIM Version

Version 6.96.0.1001062 (beta)

### Browser Details

Brave Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (x86_64)

### OS Details

MacOS 12.2 beta 21D5025f

### Describe the bug

I selected a replacement weapon for an item no longer in a loadout and I expected the item to go away but instead it stays visible. I also clicked on the X to remove the item and expected it to go away but it also stays visible. Doing either still adds the replacement to the loadout as expected.

**Comment by bhollis** [comment]
Beta?

**Comment by bhollis** [comment]
I think I know what's going on
