### ISSUE TITLE
DIM messes up mod positions, making it unable to do the full loadout

### ISSUE THREAD

**Issue by ahydronous** [DestinyItemManager/DIM#7549]
### DIM Version

6.96.0

### Browser Details

All browsers

### OS Details

All OSs 

### Describe the bug

Loadouts often applies mods in the wrong slots and runs out of energy space.

For example, I have the current PvP loadout:

Void helmet: HC targetting + Sniper targetting 

Stasis gauntlets: Discipline +  Fastball + Sniper dexterity

Arc chest: Discipline +  HC unflinching + Radiant Light

Solar legs: Discipline +  Sniper scavenger

Arc class: Discipline +  Outreach + Powerful Friends

then, I have another loadout that uses some of those pieces for another type of loadout (think Protective Light in the helmet, Concussive Dampener in the chest, etc)

Without fail, DIM will slot Radiant Light in the class item and Powerful Friends in the chest item, which leaves it unable to slot the Discipline mod in the chest item because Powerful Friends + HC unflinching = 8 energy. It then also leaves Concussive Dampener in there.

**Comment by bhollis** [comment]
Can you post screenshots of the mod assignment screen for these loadouts?

**Comment by bhollis** [comment]
Can you try on Beta and see if it does better?

**Comment by ahydronous** [comment]
I will tomorrow, I’ll be home from the holidays then!

**Comment by ahydronous** [comment]
This is the mod placement.

![image](https://user-images.githubusercontent.com/57762816/147594059-de35abc4-d82b-45d0-ade0-2a3d060e6a0a.png)

The issue also happens with the beta.

A separate (but feels like related) issue is that DIM will choose extremely odd stat mod placements. I keep my helmet armor free of stat mods so I can easily swap between HC+shotty/sniper targetting.

DIM will pop out the HC targetting out of my helmet so it can slot a stat mod there, despite there only being a sniper / shotty scavenger in my leg amor.

**Comment by bhollis** [comment]
That's not the mod placement screen. The mod placement screen shows up if you press the button labeled "Show Mod Placement".

**Comment by ahydronous** [comment]
![image](https://user-images.githubusercontent.com/57762816/147607849-2c1882d7-d6be-4944-9624-bc02cf524959.png)

**Comment by bhollis** [comment]
I'll let Ryan explain more but I don't think we currently take existing mods into account while doing the assignment. All that matters is what's in the loadout. 

Assigning to specific slots is coming at some point.

**Comment by ryan-rushton** [comment]
That is correct, we aren't currently looking at your items and trying to find the combination with the least number of swaps using the items currently equipped mods. It's on my todo list. I might have a look at it seen and see how difficult its going to be.

**Comment by ahydronous** [comment]
Alright, that makes more sense, thanks for the info and taking the time!

For posterity:
The full use case for me is that I have my ‘core mods’ set up like this, and then another loadout that is ‘gun mods’. So I have a HC-Shotty loadout that applies HC targetting+Shotty targetting, Shotty dex, HC unflinching, Shotty scav. And another one like that for for example SMG-Sniper.

That way I can apply my gun loadouts to any exotic loadout I’ve made, even on other classes. So first I apply Ophidian-Discipline or Stompees-Res and then HC-Sniper.

**Comment by ryan-rushton** [comment]
FWIW I raised a fix for this. It needs some testing but should be in beta in the next few days. You will see this issue close and 10 minutes later you should be able to test.

**Comment by ahydronous** [comment]
The fix works swimmingly, even with my my `core mods loadout` + `gun mods loadout` system!
Thanks a lot!
