### ISSUE TITLE
DIM places mods in incorrect spots, even on new beta version

### ISSUE THREAD

**Issue by thetangyryan** [DestinyItemManager/DIM#7562]
### DIM Version

6.96.0.1001069 (beta) (blue icon)

### Browser Details

Chrome and app

### OS Details

Windows 10

### Describe the bug

I love the loadout feature and all it provides. For fast and easy swaps after bosses in raids or between crucible matches. But as of this version, whenever you swap loadouts, DIM always seems to find it impossible to place your mods in the correct slots, which then causes you to take more time then if you were to just swap your mods in game. It's nice that a step is being taken forward to include mods in the loadout feature but it's completely broken and frustrating in it's current state.

**Comment by bhollis** [comment]
I'm afraid there's not enough information in this issue for us to do anything. If you have example screenshots of the mod assignment screen showing mods in sub-optimal locations, and explanations for why they're suboptimal, feel free to open an issue with that information.
