### ISSUE TITLE
Opening a shared loadout overwrites your LO stat preferences. 

### ISSUE THREAD

**Issue by inexorableAce** [DestinyItemManager/DIM#7572]
### DIM Version

all versions

### Browser Details

Firefox Current

### OS Details

windows 10

### Describe the bug

when you click someone's shared loadout link, LO loads up with that build preferred stats. but from then on when you go into LO those preferences are saved as default till you change them back to your preferred.

**Comment by bhollis** [comment]
Yeah it's a bummer, it really shouldn't
