### ISSUE TITLE
Beta: Cannot select plugs in item sockets (SocketDetailsSelectedPlug dismisses itself)

### ISSUE THREAD

**Issue by robojumper** [DestinyItemManager/DIM#7578]
### DIM Version

Version 6.97.1.1001086 (beta), built on 28.12.2021, 01:21:34

### Browser Details

Firefox 95.0.2, Edge 96.0.1054.62

### OS Details

Windows 10

### Describe the bug

I clicked on a weapon, then on the shader socket. `SocketDetailsSelectedPlug` appears with a list of shaders. Clicking on a shader immediately dismisses the plugs popup and the item popup without applying the shader. Happens to all kinds of sockets and plugs.

Bisected to <https://github.com/DestinyItemManager/DIM/commit/901c585ce9911bd68d64835c05ed1bb20ecb21ce>

### Logs

```shell
[clicked item] ...
```

**Comment by bhollis** [comment]
Thanks, I'll get it
