### ISSUE TITLE
stray header on loadouts page

### ISSUE THREAD

**Issue by nev-r** [DestinyItemManager/DIM#7586]
![image](https://user-images.githubusercontent.com/68782081/147654919-d0a63264-ffe0-4c1d-a1a9-f602f33e52c4.png)

i don't really feel like the word Abilities belongs here. there's nothing we can really do here.

~~another thing that's weird:~~ fixed in https://github.com/DestinyItemManager/DIM/pull/7619

![image](https://user-images.githubusercontent.com/68782081/147827224-38c4116d-e507-4220-b0bb-05a9fca7c6a0.png)

**Comment by SunnySoldier357** [comment]
Interestingly, looks like it's only for light subclasses. Maybe in preparation for the light subclass reworks?
![image](https://user-images.githubusercontent.com/35979525/147679693-f0998d0a-2b83-4652-9d97-7b84dbeb327b.png)

**Comment by bhollis** [comment]
I think it was meant to be a grey block the same way "Weapons" was, as a placeholder.
