### ISSUE TITLE
Tracked Triumphs should be sorted or grouped

### ISSUE THREAD

**Issue by lithium** [DestinyItemManager/DIM#7590]
### Proposed change

I would like to see the Tracked Triumphs that appear at the top of the Progress and Records tabs to be "sorted" in someway, at the very least I would like to have records or triumphs from the same category be grouped together.  All my exotic catalysts progress together in one spot, each season's triumphs are next to each other, etc.

### How does this fit into your workflow?

When you have a moderate amount of tracked records or triumphs (10 or more) it can become difficult to find the tracked triumph you are looking for.  If they were grouped together in a consistent manner it would be easier to navigate a longer list and find which one you are looking for.

an example of many tracked triumphs in a seemingly random order:
![image](https://user-images.githubusercontent.com/16558/147675333-54645189-1fdf-43f8-8123-760df7c01b26.png)

**Comment by nev-r** [comment]
good i think?
