### ISSUE TITLE
Available bounties incorrect over multiple characters

### ISSUE THREAD

**Issue by buncieboy** [DestinyItemManager/DIM#7594]
If I purchase a bounty on one character it will show as purchased on all 3 from the vendor view. This only started happening in the last few months, and is happening on desktop (chrome) and android. I've attached some screen shots to explain it better.

From the D2 app you can see I have purchased the daily crucible bounties on my hunter but not on my warlock.
![image](https://user-images.githubusercontent.com/26060706/147691657-b5734c2e-b9b7-4e64-9b6a-f16016168272.png)
![image](https://user-images.githubusercontent.com/26060706/147691644-7fd2ab7c-6a0d-4381-b630-a6cc7be6ea83.png)
But within DIM they show as purchased on both accounts.
![image](https://user-images.githubusercontent.com/26060706/147694574-b7615220-1f5d-4f2f-ab69-e90a2f769c82.png)
![image](https://user-images.githubusercontent.com/26060706/147694583-de213aa4-6efd-41fd-b033-fea53ab3530d.png)

If I complete the bounty on my hunter it then correctly shows as completed (not just purchased) on my hunter, and available on my warlock.

Let me know if I can provide any more detail.

**Comment by buncieboy** [comment]
I've tried clearing cache and cookies etc on desktop but the same thing is still happening.

**Comment by bhollis** [comment]
Interesting, we'll take a look! I don't know that that calculation has changed in a long time, but maybe the data has.
