### ISSUE TITLE
The progress bar of exotic weapons in collections clipping into other items

### ISSUE THREAD

**Issue by Ice-mourne** [DestinyItemManager/DIM#7622]
### DIM Version

Version 6.97.3 (release), built on 12/31/2021, 5:37:12 AM
Version 6.97.3.1001110 (beta), built on 12/31/2021, 7:46:49 PM

### Browser Details

Chrome Version 96.0.4664.110 (Official Build) (64-bit)

### OS Details

Win 10

### Describe the bug

Location in DIM: Records > collection > exotic > weapons
The progress bar under weapon image clipping into other things [img 1 link](https://cdn.discordapp.com/attachments/333464468241514497/926578908072140800/unknown.png) | [img 2 link](https://cdn.discordapp.com/attachments/333464468241514497/926579639420342323/unknown.png)

It's more obvious if you make a window wight smaller making items go into rows as shown in img 1
extra img I changed colors just to show the problem no extension was used [img 3 link](https://i.imgur.com/AVSmPXp.png)

**Comment by 8BitYoda** [comment]
I can look into this
