### ISSUE TITLE
beta DIM throwing a SyntaxError on load

### ISSUE THREAD

**Issue by nivshah** [DestinyItemManager/DIM#7648]
### DIM Version

hasn't loaded can't see version

### Browser Details

Firefox 95.0.2 (64-bit)

### OS Details

macOS Monterey

### Describe the bug

when visiting beta.destinyitemmanager.com this error shows up in the console:

Uncaught SyntaxError: identifier starts immediately after numeric literal
main-3cb9b5.js:1:569356

This started about 30 minutes ago.

### Logs

```shell
Uncaught SyntaxError: identifier starts immediately after numeric literal
main-3cb9b5.js:1:569356
```

**Comment by nivshah** [comment]
This has been fixed.

**Comment by nivshah** [comment]
It's back in the last 15 minutes or so.

**Comment by ryan-rushton** [comment]
Are you still seeing it, seems to be working fine for me now.

**Comment by nivshah** [comment]
I still get this error

https://beta.destinyitemmanager.com/

```Uncaught SyntaxError: identifier starts immediately after numeric literal
main-3cb9b5.js:1:569356```

**Comment by nivshah** [comment]
I inconsistently get the error when I hit https://beta.destinyitemmanager.com/, which redirects to my inventory https://beta.destinyitemmanager.com/4611686018429104473/d2/inventory

If I refresh once my inventory is open https://beta.destinyitemmanager.com/4611686018429104473/d2/inventory I get this error more consistently

**Comment by bhollis** [comment]
Try clearing your service worker cache from the Application tab in DevTools

**Comment by nivshah** [comment]
This worked for me temporarily. When I press cmd+R to refresh, the beta DIM continues to work. When I press cmd+shift+R to do a hard refresh, I get this error.

I do not have this issue with app.destinyitemmanager.com - only the beta

**Comment by nivshah** [comment]
At this point this isn't a massive breaking bug, but it is behavior that wasn't there before so I am continuing to report.

**Comment by bhollis** [comment]
Thanks, it makes sense but beta has been fixed, at this point the issue is some local cache you've got.
