### ISSUE TITLE
Can’t switch between characters

### ISSUE THREAD

**Issue by vanhauser-thc** [DestinyItemManager/DIM#7656]
### DIM Version

Version 6.98.0 (release), built on 3.1.2022, 03:09:13

### Browser Details

iOS app

### OS Details

iOS 15.2

### Describe the bug

I haven’t found a way to switch characters. I can only switch between my current active one (hunter) and the vault by swiping left or right but I did not find a way to access the load out of my warlock and titan. I feel dumb because I am sure this must be possible but I can’t find out how …

**Comment by bhollis** [comment]
Try going into Settings and turning off "single character mode".

**Comment by vanhauser-thc** [comment]
thank you! I must have unwittingly enabled it ...
