### ISSUE TITLE
Allow Wishlists to be refreshed without caching, for developing a wishlist

### ISSUE THREAD

**Issue by lassevk** [DestinyItemManager/DIM#7659]
### Proposed change

When constructing a gist or a github repository with a new wishlist, the raw download link seems to use a cached copy for quite some time.

Instead of having to manually either paste in the updated full gist link, or manually adjust the shortened one that should auto-update, with a new cache-bash parameter each time just to force a reload, it would be nice if I could just add some "magic syntax" in the URL and have it automatically replaced.

For instance, I could do this:

    https://gist.githubusercontent.com/lassevk/28be861a59fabfb8a6bffa3bee4f4dfc/raw/?cachebash=<T>
                                                                                    ^------------^

and have the `<T>` be replaced with the current timestamp whenever the wishlist is refreshed. This circumvents the caching done by gist/github.

Note that the gist/github site doesn't actually use this parameter, it's just a random parameter that needs a unique value each time to circumvent the caching.

### How does this fit into your workflow?

It would make it easier when testing wishlist changes. I could update the wishlist, then go to the settings and click the update button and a new copy would be downloaded. Right now the log just states that the file is the same as one it already has so no update took place.

**Comment by bhollis** [comment]
We should probably force update when you re-click it from settings. Having caching is important to prevent DIM from too-frequently requesting from GitHub (and potentially getting blocked) but I can see that while developing that might be annoying. That said, you might want to use a tool like https://wishlists.littlelight.club instead of having to check in DIM all the time.
