### ISSUE TITLE
Distinguish identical items with a little marker (A, B, C, D, ...)

### ISSUE THREAD

**Issue by ahydronous** [DestinyItemManager/DIM#7662]
### Proposed change

I think it would be neat if items of the same name would get a little marker in the bottom right so they are visually distinguishable from each other.

I am not versed in the Destiny API, but I assume there is some sort of ID attached to each item.
To me, A, B, C, D, E, F, G, H, etc. would make the most sense as most of the other values that you see with an item are numerical.
There is the problem of how to assign the markers. If you do it based on acquired date, you run into the problem that you either A) have the markers constantly swapping as some of the identical items are dismantled or B) markers have to keep incrementing upwards.

### How does this fit into your workflow?

This help when building loadouts, transferring stuff etc. since you don't have to check which item is which, and in some places in DIM (loadouts and one or two others that I can't remember) where you literally cannot watch item info.

**Comment by nev-r** [comment]
i agree with the use case, but consider this to be a failure of some interfaces, like loadout editor, to let you click the polaroid to find out details.
actually, know what would be super cool in places we don't allow item popup? 
![image](https://user-images.githubusercontent.com/68782081/148157505-ba4ee2fa-8991-4d7a-abde-f15da68363f0.png)

**Comment by ahydronous** [comment]
This problem has not been fixed at all @bhollis, can you reopen?

**Comment by bhollis** [comment]
Not fixed, but closed. We won't be adding these indicators.
