### ISSUE TITLE
header no longer scrolls when off screen

### ISSUE THREAD

**Issue by inexorableAce** [DestinyItemManager/DIM#7666]
### DIM Version

Version 6.98.0.1001152 (beta), built on 1/4/2022, 6:35:47 AM

### Browser Details

ios mobile, ff desktop

### OS Details

windows 10, ios

### Describe the bug

![ezgif com-gif-maker](https://user-images.githubusercontent.com/29002828/148313361-f771f744-af29-4d97-b9b4-273b0514fc05.gif)

**Comment by inexorableAce** [comment]
my assumption is that this is due to the mobile fixes recently merged for the header spacing due to notch

**Comment by kyleshay** [comment]
Ack good catch. Looks like I introduced that in https://github.com/DestinyItemManager/DIM/pull/7596 I'll take a look now.
