### ISSUE TITLE
Progress > Ranks shows rank reset counts incorrectly

### ISSUE THREAD

**Issue by rusakko** [DestinyItemManager/DIM#7669]
DIM has been showing rank reset counts incorrectly for me: 

- After resetting Vanguard rank for the first time, it showed "1 reset" under Strange Favor
- After resetting Vanguard rank for the second time, it showed "2 resets" under Strange Favor
- After resetting Strange Favor, nothing changed.

I have not done any other resets this season.

### Screenshots
![Vanguard](https://user-images.githubusercontent.com/378838/148374808-83752689-696a-496a-98c1-fad7cb14848b.png)
*In-game screenshot shows 2 resets for Vanguard Rank*.

![Strange Favor](https://user-images.githubusercontent.com/378838/148374425-d8775dfe-b60e-4a7c-a774-3c9f50987b97.png)
*In-game screenshot shows 1 reset for Strange Favor*.

![DIM](https://user-images.githubusercontent.com/378838/148372099-3b18058b-bd29-4d31-82ec-111271918727.PNG)
*DIM screenshot shows 2 resets for "Strange Favor", no resets for Vanguard Rank*.

**Comment by delphiactual** [comment]
Bungie-net/api#1544
