### ISSUE TITLE
Fashion Loadouts Followup Tasks

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#7671]
Followups from #7600

* [x] Add help text to sync buttons
* [x] "Use Equipped" should draw from the equipped items if no item is in the loadout.
* [x] Fix reporting of applying a default plug when the default plug was already applied.
* [x] Fix which default ornament plug we use
* [x] Sharing a fashion loadout doesn't appear to work
* [x] Sync ornament and sync shader should work on "default plug"
* [x] Choose fashion button should disappear if there's no class for the loadout
* [x] #7693
* [ ] #7694
* [ ] #7695
* [ ] #7699
* [x] #7696
* [ ] #7698
* [ ] #7726
* [x] #7704
* [x] #7697

**Comment by nev-r** [comment]
> we should just skip and count that as a success
would prefer to see this count as a didn't-try? like fewer than 5 items in the progress notif.

**Comment by nev-r** [comment]
![image](https://user-images.githubusercontent.com/68782081/148502022-feeb4687-7f46-4729-ba35-b86c0c4844ba.png) needs to not appear when the loadout has no associated guardian class
