### ISSUE TITLE
item tagging should clear new item dot

### ISSUE THREAD

**Issue by inexorableAce** [DestinyItemManager/DIM#7677]
### Proposed change

currently with the item feed (i think) and search / tagging it's possible to take action on an item with out the new item dot being cleared. If you tag the item via the item feed or search bulk action it should no longer be "new" 

### How does this fit into your workflow?

just seems counter intuitive and was surprised to see this after tagging everything and clearing my item feed list. 
![image](https://user-images.githubusercontent.com/29002828/148621372-b9438f55-f49f-413f-94d5-f28fc5062ae3.png)

**Comment by delphiactual** [comment]
uploading notes via csv should also clear new
