### ISSUE TITLE
for review: character dropdown layout

### ISSUE THREAD

**Issue by nev-r** [DestinyItemManager/DIM#7687]
is it weird that loadout-related things are mixed around with non-loadout stuff?

what does [Space] do?

is it weird that only one thing in this list (Manage Loadouts) takes you to a whole new page? and with no warning?

![image](https://user-images.githubusercontent.com/68782081/148658774-45e15c3a-0c16-4e2e-8d7d-b112dd4bf83d.png)

**Comment by delphiactual** [comment]
Space makes room for items in the postmaster... Useful for things that cannot be pulled automatically

**Comment by bhollis** [comment]
> is it weird that loadout-related things are mixed around with non-loadout stuff?

Yeah. It's always bugged me, but technically this is the "character actions menu" not the "loadout menu". We could make it clearer by giving them sections with headings, but I don't know that this is causing any major confusion

> what does [Space] do?

In the olden days this was a whole separate row called "Make Space for Postmaster Items". I'm actually not sure if anyone uses this, which means if I remove it I will find all the people who find it critical to their workflow. I could be convinced to move this to a button alongside "Pull from Postmaster" under the postmaster bucket.

> is it weird that only one thing in this list (Manage Loadouts) takes you to a whole new page? and with no warning?

Maybe? This was an attempt at educating people that they don't need to do all their loadout work from this menu. What warning would we need for that navigation? I haven't heard any complaints about it - if anything it's superfluous, but there's a competition between whether this menu or the links in the header are less discoverable for people.

**Comment by nev-r** [comment]
> Space makes room for items in the postmaster... Useful for things that cannot be pulled automatically

so if i understand correctly, this clears space on char, so that items can be clicked in-game?  
weird, but yeah that's a use case

> I could be convinced to move this to a button alongside "Pull from Postmaster" under the postmaster bucket.

that might make more sense

> technically this is the "character actions menu" not the "loadout menu"

agreed, and its better that it not just be "the loadout menu", it just circumstantially has become full of loadout things and i am not sure the order makes any particular sense

>  What warning would we need for that navigation?

i could be alone in this, but that menu has always been "do a thing" and not "go somewhere" so it's offputting to lose my inventory view/current search/compare sheet etc. usually i am actually going for "create loadout" but my brain sees "loadout" really clearly (the other one's a bit more cramped/cluttered) and decides to click it. i'm not saying it's not a good option or doesn't belong, just registering a thought about how much it differs as an experience from anything else in that menu

**Comment by bhollis** [comment]
> clears space on char, so that items can be clicked in-game?

Yeah it clears just enough space on the character that you can click them in-game to take them out of postmaster.

> full of loadout things

The other weird one is farming mode - no idea where that belongs. If I moved out pull from postmaster it becomes the only non-loadout thing.

> offputting to lose my inventory view/current search/compare sheet etc.

I could see having a prompt if you have some interesting state. We'd have to set up a tracker for when that condition is true.
