### ISSUE TITLE
Fashion: Ornament is dimmed when it's the same item hash as the equipped item

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#7693]

**Comment by bhollis** [comment]
I still can't reproduce this. I thought maybe it meant the ornament would be dimmed when it's a transmog ornament that matches the actual item it would be applied to, but that works:

![image](https://user-images.githubusercontent.com/313208/148664589-6537a13b-da77-4a93-8292-c34d2f0b3e71.png)

**Comment by robojumper** [comment]
I can't reproduce it either. I think in the screenshot the issue might not have been that it's the same item, but that I didn't actually have the ornament unlocked (but because it was the same item, SocketDetails allowed me to select it before #7676 and I thought I had it unlocked).
