### ISSUE TITLE
Fashion: clicking [Save fashion] causes no feedback or change to the loadout edit sheet

### ISSUE THREAD

**Issue by nev-r** [DestinyItemManager/DIM#7703]

**Comment by bhollis** [comment]
Yep - this is sort of a "known issue" until the redesigned loadout page can be built. cc @ryan-rushton

**Comment by ryan-rushton** [comment]
Will this be fixed by #7912? I am thinking yet.

**Comment by nev-r** [comment]
already addressed by the baby fashion tiles present below the big ones, imo, this issue is just that you literally couldn't tell if a loadout had fashion settings. but https://github.com/DestinyItemManager/DIM/pull/7912 will help too and makes it way more obvious
