### ISSUE TITLE
Loadout Optimizer mobile display text overlap

### ISSUE THREAD

**Issue by inexorableAce** [DestinyItemManager/DIM#7707]
### DIM Version

all

### Browser Details

all

### OS Details

all

### Describe the bug

In LO if you select an exotic and some mods, then you have a loadout in your list that has 2 rows with a special perk (IB armor, raid armor, teh exotic perk, etc) the  action buttons over lap the stat text of the next loadout. 

![image](https://user-images.githubusercontent.com/29002828/148692941-03af56d5-5be0-4c23-801e-2be0ba0fe104.png)

![image](https://user-images.githubusercontent.com/29002828/148692962-bbe41ba2-fe61-4652-b107-d2ffd3b74af4.png)

**Comment by robojumper** [comment]
This is also possible to trigger on desktop by using a query that excludes all intrinsics and activity slots, e.g. `-is:exotic -modslot:activity -perkname:"friendly competition" -perkname:"artifice armor" -perkname:"iron lord's pride"`, resizing the screen, and then removing that query: 
![grafik](https://user-images.githubusercontent.com/14299449/150221342-4cc2117f-5307-4e9a-a3b9-68883642c319.png)
