### ISSUE TITLE
Ornament/Shaders being removed when applying mods loadout, with no fashion specified

### ISSUE THREAD

**Issue by Skulled117** [DestinyItemManager/DIM#7708]
### DIM Version

Version 6.98.0 (release), built on 1/2/2022, 6:09:13 PM

### Browser Details

Chrome Version 96.0.4664.110 (also the app version 3.0)

### OS Details

Windows 10 and IOS 15.1

### Describe the bug

When changing to a specific titan loadout, the helmet stays the same while 3 mod slots are supposed to change, from 10 resil and 2 hands on seasonal mods, to a 10 int mod. Before the Hands on/ resil mods change however, it removes the shaders and ornament from the helmet. This is not on the current beta, so fashion shouldnt be touched by loadouts. (Link to a video of it happening https://www.youtube.com/watch?v=dM_VS_qoaNQ ) 

(edit) Upon looking at logs, it changes the ornament and shader slot (lines 2 and 7 respectfully) when it changes the loadout

### Logs

[loadout mods] Applying (7) [{…}, {…}, {…}, {…}, {…}, {…}, {…}] to Kabr's Battlecage
instrument.ts:130 [loadout mods] equipping mod Default Ornament into Kabr's Battlecage socket 10
instrument.ts:130 [loadout mods] Applying (4) [{…}, {…}, {…}, {…}] to Lightkin Gauntlets
instrument.ts:130 [loadout mods] Applying (4) [{…}, {…}, {…}, {…}] to Cuirass of the Falling Star
instrument.ts:130 [loadout mods] Applying (4) [{…}, {…}, {…}, {…}] to Kabr's Forceful Greaves
instrument.ts:130 [loadout mods] Applying (3) [{…}, {…}, {…}] to Sunstead Mark (Magnificent)
instrument.ts:130 [loadout mods] equipping mod Default Shader into Kabr's Battlecage socket 4
instrument.ts:130 [loadout mods] equipping mod Empty Mod Socket into Kabr's Battlecage socket 1
instrument.ts:130 [loadout mods] equipping mod Empty Mod Socket into Kabr's Battlecage socket 2
instrument.ts:130 [loadout mods] equipping mod Intellect Mod into Kabr's Battlecage socket 0
instrument.ts:130 [loadout mods] Mods applied 17 17

**Comment by Skulled117** [comment]
Update, with fashion loadouts the bug still persists when there is no set fashion for either loadout.
HOWEVER, by using fashion you can circumvent the bug

(log from swapping to either one post fashion setting)
[loadout mods] Mods to apply Array(20)
instrument.ts:130 [loadout mods] Applying Array(6) to Kabr's Battlecage
instrument.ts:130 [loadout mods] equipping mod Resilience Mod into Kabr's Battlecage socket 0
instrument.ts:130 [loadout mods] Applying Array(6) to Synthoceps
instrument.ts:130 [loadout mods] equipping mod Unstoppable Pulse Rifle into Synthoceps socket 2
instrument.ts:130 [loadout mods] Applying Array(6) to Iron Forerunner Plate
instrument.ts:130 [loadout mods] Applying Array(6) to Pyrrhic Ascent Greaves
instrument.ts:130 [loadout mods] Applying Array(6) to Light of the Great Prism
instrument.ts:130 [loadout mods] equipping mod Focusing Lens into Light of the Great Prism socket 1
instrument.ts:130 [loadout mods] equipping mod Hands-On into Kabr's Battlecage socket 1
instrument.ts:130 [loadout mods] equipping mod Hands-On into Kabr's Battlecage socket 2
instrument.ts:130 [loadout mods] Mods applied 30 30
log.ts:44 Loadout Application: 8955.758056640625 ms
log.ts:44 Process inventory: 64.071044921875 ms
log.ts:44 Inventory state update: 54.121826171875 ms
instrument.ts:130 [loadout socket overrides] Socket overrides to apply Array(1)
instrument.ts:130 [loadout socket overrides] Socket overrides applied 0 0
instrument.ts:130 [loadout mods] Mods to apply Array(17)
instrument.ts:130 [loadout mods] Applying Array(7) to Kabr's Battlecage
instrument.ts:130 [loadout mods] equipping mod Empty Mod Socket into Kabr's Battlecage socket 1
instrument.ts:130 [loadout mods] Applying Array(6) to Lightkin Gauntlets
instrument.ts:130 [loadout mods] Applying Array(6) to Cuirass of the Falling Star
instrument.ts:130 [loadout mods] Applying Array(6) to Kabr's Forceful Greaves
instrument.ts:130 [loadout mods] Applying Array(5) to Sunstead Mark (Magnificent)
instrument.ts:130 [loadout mods] equipping mod Empty Mod Socket into Kabr's Battlecage socket 2
instrument.ts:130 [loadout mods] equipping mod Intellect Mod into Kabr's Battlecage socket 0
instrument.ts:130 [loadout mods] Mods applied 27 27

**Comment by inexorableAce** [comment]
got another report of this with loadout image and logs showing the shader get set to default. 
![image](https://user-images.githubusercontent.com/29002828/148865346-e9aef5dc-c07e-4e59-b629-699dd27ad447.png)
![image](https://user-images.githubusercontent.com/29002828/148865426-3308c93f-c1cf-4574-b51f-04553a4b1222.png)
