### ISSUE TITLE
Remove hashLookupFailure reporting

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#7727]
It was a good idea, but I don't think we're paying much attention to them, and loadouts throws them for a curve since they can contain mods that have been removed (by the passing of seasons).

**Comment by bhollis** [comment]
I left some of this in place and it's still really noisy. Maybe we need the API to change to express the intent of the caller better or something.

**Comment by robojumper** [comment]
We removed the loadouts hashLookupFailure spam in #9919 by changing the API and expressing more clearly when we expect a def to be missing.
