### ISSUE TITLE
DIM cannot remove mod - 2 characters with same class with 2 artefacts and different mods selected

### ISSUE THREAD

**Issue by pinomat81** [DestinyItemManager/DIM#7731]
### DIM Version

Version 6.99.1.1001184 (beta), built on 10/01/2022, 17:32:08

### Browser Details

Version 96.0.4664.110 (Build officiel) (64 bits)

### OS Details

Windows 10 LTSC 2021

### Describe the bug

Hello,

I have 2 Titans. One titan have an artefact (the compass) with specific mod seleced and the other Titan have different mod selected. For example Titan 1 has Particle Deconstruction Mod and Titan 2 do not.
When I apply a loadout with an armor which already has Particle Deconstruction Mod applied on it on Titan 2, loadout failed, mod are not changed and the mod stays on the armor. 
I can provide you log/printscreen if needed as soon as Destiny 2 is back online ;)

**Comment by robojumper** [comment]
This might be an instance of Bungie-net/api#1574 -- because the mod is disabled from the perspective of Titan 2, Bungie.net incorrectly reports less energy used and DIM thinks it doesn't need to make space?

**Comment by pinomat81** [comment]
Sure it seems to be related to it. Because I am really new here, you confirm from Bungie-net/api#1574 that : 
"isEnabled":false : for each mod place, this tells that there is no mod ?
"energyCapacity":10 : is how many energy the armor can have at max (no matter any mod is set or not)
If so, I understand it will be barely impossible to solve. 
If we have info about if a mod disabled (for a particular character) and if it is set in a mod place. We can first remove all of them then apply the loadout.
![titan 1 - ingame after apply](https://user-images.githubusercontent.com/96484147/149116503-def3b6a9-4960-42a6-a250-b1ae05ab76eb.png)
![titan1 - loadout](https://user-images.githubusercontent.com/96484147/149116516-a01c7dda-0ad1-4e2e-a677-16630e6b055e.jpg)
[Titan 2 - DIM log.txt](https://github.com/DestinyItemManager/DIM/files/7853503/Titan.2.-.DIM.log.txt)
![titan 2 - ingame after apply](https://user-images.githubusercontent.com/96484147/149116521-45ec0621-37d0-4f01-85a4-568d3a7a3e24.png)
![applying to titan 2 - mod does not show](https://user-images.githubusercontent.com/96484147/149116526-c75df558-8fa5-484c-8736-f2acb79fbdbc.png)
