### ISSUE TITLE
tag_cleanup may not be deleting enough

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#7734]
I fixed that bug that could cause total tag annihilation, but there may still be a bug cleaning up tags, as the max tags returned by the API has slowly grown to about 2,000:

![image](https://user-images.githubusercontent.com/313208/149050863-62c3eea0-ca3c-43ff-ac6d-f5830778022e.png)

That said, it could just be a few people who use something like D2Checklist which may not run tag_cleanup. Worth digging into.

**Comment by inexorableAce** [comment]
The item list probably too. I normally do not tag all my items... but I have trouble leaving lists with things in them, be it email or items list in DIM I want it clear. So I tagged it all. That list really incentivizes people to tag literally every single thing they have.

**Comment by bhollis** [comment]
That's the goal :-)

But it's hard to get to 2000 tagged items with 500 vault space plus 80 per character, which is why I think this is a leak.

**Comment by bhollis** [comment]
Gonna need to dig into this with some logging
