### ISSUE TITLE
Potential Memory Leak

### ISSUE THREAD

**Issue by ryan-rushton** [DestinyItemManager/DIM#7749]
[Reported](https://www.reddit.com/r/DestinyItemManager/comments/s4go1i/possible_memory_leak_or_something_ive_done/?utm_source=share&utm_medium=ios_app&utm_name=iossmf) on reddit. It sounds like there isn't a specific page it happens in.

**Comment by bhollis** [comment]
I don't see a memory leak right off the bat looking at the memory tab in Chrome (don't forget to trigger GC) but we are using a lot more memory at steady state than we used to (about 270MB vs ~170MB before)

**Comment by ryan-rushton** [comment]
The user has DIM using up 2.5GB in that thread. Could it be a windows thing.

**Comment by bhollis** [comment]
No leads, closing unless someone can show there's actually a leak.
