### ISSUE TITLE
Add loadout builder option to only use items in the guardian's inventory

### ISSUE THREAD

**Issue by DesktopMan** [DestinyItemManager/DIM#776]
The armor I keep on my guardians are generally armor with the perks I want. It would be great if there was an option in the loadout builder to only use armor currently on my guardian. Not only would it reduce the number of possible loadouts, but it would pre-screen for the perks I want.

**Comment by SunburnedGoose** [comment]
Loadouts uses the items you specifically added to the loadout.

**Comment by DesktopMan** [comment]
What do you mean? Title says "loadout builder", as in, generate tiered loadouts. By default it uses every item across your guardians and your vault, the suggestion is an option to only use items currently on the guardian.

**Comment by SunburnedGoose** [comment]
Missed that. I believe that loadout builder looks for specific items that achieve tier 12. If you have specific items you would like to use, then specify them in the loadout builder. 

If we use random items of the same type then it is unlikely that they will be T12.

**Comment by DesktopMan** [comment]
Here's an example: Say I have 3 helmets, 4 chests, 6 gauntlets and 5 greaves, all with perks I'm OK with. Their stat distributions vary wildly. I have no idea what tiers I can build with those because that's too many to manually check. This proposed option would solve the problem by showing me all the loadouts (T12 or not) I can build using them.

**Comment by DesktopMan** [comment]
An alternate way to solve this would be to have an option to lock in perks per slot in the builder instead of specific gear, but that's probably a lot more work?

**Comment by ericnelson0** [comment]
@DesktopMan Thanks for the suggestion. 

We have added the option to exclude items in the latest beta. Maybe that'd make what you're trying to do a little easier.

**Comment by SunburnedGoose** [comment]
@ericnelson0 Could you imagine a way to influence the builder to prefer items with specific perks?  I don't know how you order items when doing the calculations but it would be useful for 335 players who aren't chasing T12, but the perfect T12 to be able to select perks and then order the items by those perks, and then do the calculations.

**Comment by ericnelson0** [comment]
I haven't put much thought into it yet. But you are right, it'd be awesome to have a preference like "faster pulse rifle reload or solar armor" and have the builder use those preferences.

I'll see what I can come up with
