### ISSUE TITLE
Item last equipped

### ISSUE THREAD

**Issue by arimorcos** [DestinyItemManager/DIM#7767]
### Proposed change

It would be really great if it were possible to show when a weapon/armor was last equipped/used. 

### How does this fit into your workflow?

When vault cleaning, it would be great if we could identify items we never use. So I would want to filter on this property, say "last equipped > 30 days" to identify rarely used weapons/armor.

**Comment by bhollis** [comment]
Unfortunately we have no way of determining when an item was last equipped.

**Comment by arimorcos** [comment]
Is there any way to look through the activity history to see something related like weapons with at least 1 kill in the last 30 days? Destiny tracker can show which weapons were equipped for each activity.
