### ISSUE TITLE
Loadout Scripts

### ISSUE THREAD

**Issue by colberony** [DestinyItemManager/DIM#7771]
### Proposed change

It'd be nice if there was a "Loadout Script" feature that would basically just take a few loadouts you have configured and fully equip the first, and move all other loadouts you have into your inventory. For loadouts that share armor pieces, the first one to use it in the script would get precedence for mod equipping. The "move other items away" setting would be ignored when a loadout was used as part of a script.

There could be a checkbox for whether to move other items away after the first loadout in the script is equipped.

This would be some work to implement and some UI work, but I don't see it too bad since the core functionality would just be equipping loadouts in series with a few overrides (ignore move others away setting, move to inventory but don't equip for all but first loadout in script).

### How does this fit into your workflow?

Let's say I'm about to run Vault of Glass, and say I had a few different armor sets as a hunter I wanted to use: an omniculus one, an add clear one, and a DPS one. Let's say you already have these all saved as loadouts, complete with mod equips and everything. To make room for drops, I typically move other items away with all loadouts.

Currently, to support this, I have two options: make a 'superset' loadout that forces work duplication as I add all the armor pieces of each of the three loadouts, or manually disable the move other items away each time and remember to reenable that option later.

The former doesn't allow mods to be equipped past the first set, and the latter creates a large amount of overhead to get my loadouts ready each time. I'd rather have a one click and done set up.

This would declutter loadouts - would no longer need a specific VoG armor loadout that's just a super set of others - and would also allow mod equipping onbmore than one set of armor.

**Comment by bhollis** [comment]
I think the best solution is probably for you to just not use the move others away option, and rely on Farming Mode to keep space open for drops.

**Comment by colberony** [comment]
Maybe I misunderstand how farming mode works, but in general I prefer not to move extra drops into my vault (then I have to move them back out to dismantle versus visiting post, which I do anyway).

I also prefer to keep a clean inventory, only having what I need for a given activity. Without move items away, I have to do extra steps when switching to PvP to ensure my PvE sets aren't hanging around (which makes it harder to quick swap mid game).

Maybe loadout scripts wouldn't be used enough to make the dev time worth it. Another, much simpler but albeit more obscure, option is to have a global setting a user could use to ignore the "move items away setting" if a previous loadout has been applied within N minutes.
