### ISSUE TITLE
Select Other Loadouts to Exclude in Optimizer

### ISSUE THREAD

**Issue by colberony** [DestinyItemManager/DIM#7772]
### Proposed change

In loadout optimizer, allow a selection to exclude armor from already created loadouts. Ideally, the user would be able to select from a list of their loadouts which loadout's armor pieces should be excluded.

### How does this fit into your workflow?

Since Bungie still doesn't (and likely won't) allow equipping of loadouts/mods on the fly, this would be useful in crucible. There's times mid match when I decide I want to swap from, say, shotgun to sniper. To make this easy, I generally have two complete armor sets in my inventory - one for shotgunning, one for sniping. Then it's just a few quick armor/weapon swaps to completely move to a new loadout, armor and all. This doesn't work if those two armor loadouts share an armor piece, since then mods need to be changed.

This is slightly annoying to set up in DIM because I have to make sure I'm excluding pieces from set A when optimizing set B. Throw in a third set, and I need to make sure to exclude sets A and B manually. This would just be a nice QoL change.

It'd be nice to select which loadout's are excluded because obviously I don't care if my PvP sets share armor with a PvE set (especially now that mods can be equipped in orbit via API).

**Comment by delphiactual** [comment]
`-is:inloadout`
