### ISSUE TITLE
Move items to inactive characters to work around inability to equip mods in an activity

### ISSUE THREAD

**Issue by mrbjnb** [DestinyItemManager/DIM#7773]
### Proposed change

Basically, DIM works normally like this: Move armors to current character-> Equip mods then shader and stuff if available in loadout. (Limited to orbit)
My suggestion: Move armors to alternative character (if available) -> Equip mods -> Transfer back to current character inventory -> Equip any shader or ship if available. (Orbit)

A demonstration video of how it works: https://youtu.be/ccCLxuqD8Ks

### How does this fit into your workflow?

By using this way, I can equip any loadout anywhere and anytime (beside locked activities) and it doesn't make any conflict at all because it works in an offline character. But the limitation is the player need to unequipping current armor if it is included in the loadout they want to change.

**Comment by zacgoodwin** [comment]
Can't wait for this to happen. Hopefully Bungie add weapon mods to the API then you combine it with this feature and it will be amazing. A different loadout for every Raid encounter :D

**Comment by bhollis** [comment]
Closing as in-game loadouts offer the mods-in-activities functionality.
