### ISSUE TITLE
Class specific items for alts do not appear in vault when displaying only current character of different class

### ISSUE THREAD

**Issue by adepssimius** [DestinyItemManager/DIM#7777]
### DIM Version

Version 7.1.0 (release), built on 1/16/2022, 9:12:32 PM

### Browser Details

Chrome Version 97.0.4692.71

### OS Details

OSX Monterey

### Describe the bug

`is:sword is:void` returns 5 items, but only 3 items are displayed in the vault and the other two are hidden. (crown splitter and quick fang hidden, I am on a warlock)

![image](https://user-images.githubusercontent.com/5257052/150657591-9eb73da0-3dad-4d3a-98c8-89edef71449e.png)
Expanding to view all three characters shows the items in the vault. 

![image](https://user-images.githubusercontent.com/5257052/150657654-2f2c79a8-e4b8-4379-b6b1-5bb17dc27c72.png)

The behavior I would expect is to see them in the vault, but not equippable.

**Comment by delphiactual** [comment]
what about your marks and capes?

**Comment by bhollis** [comment]
That's right, we hide class-specific items for other classes in the vault while you're in single-character mode. You can turn off single-character mode if you want to see other characters' stuff.

**Comment by adepssimius** [comment]
Well then not a bug, but I guess just a little odd that there are 5 results returned in the search box but that number does not match the displayed items.

**Comment by adepssimius** [comment]
The behavior is also not consistent with the description of single character mode. 
![image](https://user-images.githubusercontent.com/5257052/150698720-b162b06f-09e8-45ee-962e-c41b73a30d5d.png)
