### ISSUE TITLE
Petra is missing from the vendors screen

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#7788]
### DIM Version

Current beta

### Browser Details

Chrome

### OS Details

Windows 10

### Describe the bug

Just noticed that Petra is missing as a vendor for bounties.

![image](https://user-images.githubusercontent.com/25425159/150908382-a2f46e1b-0618-4924-8906-cb16e0d191e1.png)

**Comment by nev-r** [comment]
This is a quirk of the Bungie API. Petra doesn't show up in the API unless the character is logged in and standing in the Dreaming City.
