### ISSUE TITLE
Loadout Optimizer sets wrap at higher item size

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#7799]
Item Size above 61 causes LO to add a line of class items instead of extending right when space is available.

![DIM_LO](https://user-images.githubusercontent.com/4798491/151416911-2962ea53-0959-4289-a470-6fa60297481e.png)

https://discord.com/channels/316217202766512130/333464468241514497/936317825612668938

**Comment by jerrycarlson** [comment]
Just a comment to confirm that I also have been experiencing this issue (for basically as long as I can remember).  I normally use item size 65 and never considered that the item size setting might be at fault here.

For what it's worth, I am running Google Chrome browser (always the latest stable version) on Windows 10 Pro (always the latest updated version).  The issue happens whether the browser is in full screen or windowed mode, and is unaffected by window zoom setting or making the window wider.

Screenshot attached, zoom at 100 percent.
![Capture at 100](https://user-images.githubusercontent.com/9376071/162093980-e741e3db-a3e8-4cc9-b4c3-d83afefc7f59.PNG)
