### ISSUE TITLE
Creating a loadout with "add equipped" won't let you remove shaders/ornaments from armor

### ISSUE THREAD

**Issue by hendersj** [DestinyItemManager/DIM#7802]
### DIM Version

Version 7.2.0.1001233 (beta), built on 1/28/2022, 4:07:01 AM

### Browser Details

97.0.4692.99 (Official Build) (64-bit)

### OS Details

openSUSE Leap 15.3

### Describe the bug

I tried creating a loadout using my equipped gear, but I only wanted the weapons.

1. Click the three-dot menu for the character
2. "Create Loadout"
3. "Add Equipped"
4. Delete armor, ghost, ship, sparrow, emblem, class, and all mods
5. Select "Any Class", give it a name, and save it.
6. Open in the organizer - here's what's shown:

![dim-bug](https://user-images.githubusercontent.com/2662071/151583258-c9582261-f7eb-47a3-bb30-c99f6598f81e.png)

Clicking "Edit" for the loadout doesn't show me the shaders or ornaments.  When loading the loadout on a character, the ornaments don't apply (if the class doesn't match), but the shaders do.  There doesn't appear to be a way to remove ornaments or shaders from the loadout.

**Comment by delphiactual** [comment]
1. Click the three-dot menu for the character
2. "Create Loadout"
3. "Add Equipped"
4. Delete armor, ghost, ship, sparrow, emblem, class, and all mods
5. Click `Choose Fashion` Click Eraser
6. Select "Any Class", give it a name, and save it.
7. Open in the organizer - here's what's shown:

**Comment by hendersj** [comment]
Thanks - this option doesn't seem to be present in the "edit loadout" screen for me (so you can't fix it after the fact), but I do see it when creating the loadout (I thought I'd looked for it, but somehow missed it).

It does seem like if you add equipped items and then delete equipment with fashion applied, the fashion should be removed as well.

So perhaps a slightly different issue. :)

**Comment by delphiactual** [comment]
yes, once you change to `Any Class`... `Choose Fashion` disappears.

**Comment by hendersj** [comment]
Ah, that would explain it.  Thanks!  (I think that could perhaps be a little more intuitive, but that does help me find what I was looking for) :)
