### ISSUE TITLE
Old Weapon Mods don't count towards vault space logic

### ISSUE THREAD

**Issue by Daniel3009** [DestinyItemManager/DIM#7816]
### DIM Version

Version 7.3.0 (release), built on 31.1.2022, 02:59:41

### Browser Details

Chrome

### OS Details

Windows 10

### Describe the bug

In my vault were still old Boss Spec and Radar mods. My vault was at 500 but DIM only showed 496 because of those 4 mods 

When I try to transfer items it always fails because DIM thinks there is space but the transaction fails.
So instead of making space I simply cannot transfer items.

![image](https://user-images.githubusercontent.com/63856880/152567146-5910efaa-666e-4ae1-b59a-873d5ced1cbc.png)

**Comment by Daniel3009** [comment]
manually storing the mods in the inventory fixes this bug

But it's still a bug that a space error doesn't trigger item moving when the vault is "not full"

**Comment by robojumper** [comment]
This looks related to #7182. Out of curiosity, are you able to transfer these mods back to the vault?

**Comment by nev-r** [comment]
weird because weapon mods weren't marked as an invisible no-space bucket like armor mods were. it would be really nice if we could get a profile export from someone experiencing this

**Comment by bhollis** [comment]
Unfortunately I don't have any of these mods anymore to test with. Please reopen if you can send a profile export (from the Settings page, at the very bottom)
