### ISSUE TITLE
Perk tooltip behind item popup when item popup spawned in Armory sheet

### ISSUE THREAD

**Issue by robojumper** [DestinyItemManager/DIM#7823]
Go to a weapon's armory sheet, then click on an item in the "your items" section. Hover over a perk in that item popup, the tooltip will be hidden behind the item popup: 
![grafik](https://user-images.githubusercontent.com/14299449/152699969-91f92d5e-0a88-4888-9877-7b1368b2a660.png)

**Comment by bhollis** [comment]
To fix this we should have a Context provider that allows us to stack z-indexes based on the component tree.
