### ISSUE TITLE
Loadout Optimizer: add assumed armor upgrade option for "exotics only"

### ISSUE THREAD

**Issue by jerrycarlson** [DestinyItemManager/DIM#7825]
### Proposed change

At present, DIM allows essentially 3 masterwork options in the loadout optimizer: (1) "no upgrades", i.e., treat all armor pieces as-is, masterworked or not; (2) "ascendant shard (not exotics), i.e., "treat all legendary armor pieces as if masterworked but no exotics"; and (3) "ascendant shard (not masterworked)" and "ascendant shard", i.e., "treat all armor pieces as if masterworked".

I would like to request a 4th option along the lines of "ascendant shard (exotics only)".  This option would treat all *legendary* armor pieces as-is, the way "no upgrades" does, but all *exotic* pieces as if masterworked.

### How does this fit into your workflow?

My typical workflow is as follows:
1. Drag my (already masterworked) class item and whatever exotic piece I'm going to be using (whether masterworked or not), to the "Pin Item" button.
2. Choose the appropriate option under "Select Armor Upgrades".
3. Set my preferred stat tier parameters.
4. Review the results.

At present, under "Select Armor Upgrades" I can only have the optimizer assume (1) all pieces have *current* masterwork status, (2) all *legendary* pieces should be treated as if masterworked, or (3) all *legendary and exotic* pieces should be treated as if masterworked.  Unless I've missed something, the option to treat *only the exotic* piece as if masterworked is missing.

Masterworking exotics is much more expensive than legendaries, and it would be useful for my analyses if I could consider situations where my exotic of interest is masterworked but all other pieces are in their current masterwork status.

**Comment by ryan-rushton** [comment]
Hey @jerrycarlson 👋

My issue with adding this is we are getting a pretty crowded UI, particularly with the streamlined armour upgrade settings we now have with lock element and assume masterwork toggles. 

Being as legendary items are pretty cheap to masterwork, you get 3x the stat improvements for masterworking 3 legendary items over a single exotic (given you have all 3 non-masterworked legendaries). If you already have a bunch of masterworked legendaries in a row, then you might as well use the masterwork all functionality if you are going to spend 3 shards on an exotic. 

While I see value in your case for experimentation I am not sure it has enough utility to be introducing more UI and processing complexity to what is already a pretty complicated UI/processing.

**Comment by jerrycarlson** [comment]
Hi Ryan,

I understand.  My particular use case is fairly niche and only comes up when I'm comparing duplicate exotic armor.

When I get a new piece that isn't obviously better/worse than an existing piece I run two sets of analyses and then keep whichever piece performed best in both/overall.  The first analysis is "assume everything is masterworked" and the second is "assume everything has its current masterwork status".  Naturally, if I've previously masterworked an exotic piece, that piece will "unfairly" score higher in that second analysis than the new, duplicate exotic piece, and thus skew the results in the incumbent's favor.

By way of example, I might run the query 'is:warlock ((is:legendary -tag:junk -tag:infuse -is:helmet) or name:"verity's brow")' once with "assume masterwork" = all, and then again with "assume masterwork" = none, to see how a new Verity's Brow performs compared to an existing Verity's Brow in all investment scenarios (or, if I'm farming lost sectors, to see how *several* Verity's Brows perform).  I do the "as-is" analysis to identify which piece(s) theoretically will perform best if I just drop them in without having to maybe wait for upgrade investment.

Going through these analyses is already somewhat tedious, especially if more than two duplicates of an exotic piece are being compared, and so my suggestion was an attempt to reduce the pain both for myself and any fellow sufferers.  😉

Thanks for having considered my suggestion, and thanks very much to you and the team for this outstanding service/product.  I couldn't play Destiny without it any more.
