### ISSUE TITLE
Add ability to lock / unlock item in the item feed

### ISSUE THREAD

**Issue by zacgoodwin** [DestinyItemManager/DIM#7848]
### Proposed change

It would be great to have the ability to lock an item in the new item feed. I like to lock everything I mark as "Keep" so I don't accidently be a moron. 

![image](https://user-images.githubusercontent.com/666712/153685068-1de4b27f-535a-42bf-ba80-1d7d82a171c3.png)

### How does this fit into your workflow?

The item feed is super helpful to manage incoming gear but I have to take an extra step afterwards to lock all the items I've kept. 

tag:keep is:unlocked > Lock Items

**Comment by bhollis** [comment]
Linking #7219

**Comment by bhollis** [comment]
Linking #7220

**Comment by bhollis** [comment]
I think I'm likely to not do this in favor of #7220. Thoughts?

**Comment by zacgoodwin** [comment]
That would work :)
