### ISSUE TITLE
Arc and Void Combat Style Mods Error

### ISSUE THREAD

**Issue by Kaidarra** [DestinyItemManager/DIM#7859]
### DIM Version

Version 7.5.0.1001291 (beta), built on 2/14/2022, 2:11:42 PM

### Browser Details

Firefox 97.0

### OS Details

Windows 10

### Describe the bug

I tried applying a few loadouts that used CwL mods. It would equip the armor pieces to my character, but wouldn't change the fashion or mods applied. When I tried to inspect the mods using Show Mod Placement, I got this error:

![image](https://user-images.githubusercontent.com/32661834/153939533-ceb852ed-4e20-4339-96b5-3c0222091c86.png)

I started remaking my loadouts to see if that would fix it. While doing so, I noticed that if I tried to add certain CwL mods using Show Mod Placement, I would get the same error.

I tried adding all of the CwL mods to a test loadout one by one, and while the Neutral and Solar ones applied correctly, the Arc and Void ones gave me the error.

I tried doing the same thing with Warmind and Elemental Well mods after, and again, the Arc and Void ones gave me an error. Solar and Stasis mods did not.

**Comment by bhollis** [comment]
Can you show some of the loadouts that have trouble? Do you have a set of steps that I can follow to make this happen?

**Comment by smanzo** [comment]
Either of these will throw the error, by choosing Show Mod Placement or Optimize Armor
 ![0EF780A3-D637-4D1F-A98C-D69B286F15DC](https://user-images.githubusercontent.com/492746/153944870-12a2fddd-3258-4461-b89a-6184083047e9.png)
![201D969C-A49F-4B04-A2BD-69EE901F6E6E](https://user-images.githubusercontent.com/492746/153945233-e7ceff8e-515e-47b8-a562-23dbc589de54.jpeg)

**Comment by delphiactual** [comment]
can you `Share Build Settings` and post them

**Comment by Kaidarra** [comment]
Here is one of the loadouts I tried earlier:
![image](https://user-images.githubusercontent.com/32661834/153945176-361cc173-05de-44c3-abeb-d953406b29b9.png)
https://dim.gg/q4uce2y/Arcstrider-Raiden-Flux

When I tried to apply it, this happened: 
![image](https://user-images.githubusercontent.com/32661834/153945315-41c92a18-3d0c-4a5a-a9ae-cd9db00a8792.png)
My hunter is now wearing the correct armor but the fashion and mods have not changed.

Steps to recreate using a new loadout:
- Create a new loadout in DIM
- Select any armor (I made sure to have one of each elemental type)
- Click Show Mod Placement
- Click the Combat Style slot on any armor piece
- Select an Arc or Void Combat Style mod and click Select Mods

**Comment by delphiactual** [comment]
crashes on `beta` not on `app`

**Comment by delphiactual** [comment]
possibly related to https://github.com/DestinyItemManager/DIM/pull/7845

**Comment by bhollis** [comment]
Reverted that, check back in a few minutes and see if it's better

**Comment by delphiactual** [comment]
works for me

**Comment by Kaidarra** [comment]
Fixed for me as well. Thank you!
