### ISSUE TITLE
Error when loading DIM without Logging into Bungie

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#786]
Logout of Bungie.net.  Open DIM, and you'll get an error message in the header.

![buggy](https://cloud.githubusercontent.com/assets/984608/17626939/053b67e0-6075-11e6-86a0-ae2fabfee3b6.png)

**Comment by ericnelson0** [comment]
Console:
![image](https://cloud.githubusercontent.com/assets/4594931/17630470/0cb4db72-6085-11e6-97a6-c91e04c55439.png)

**Comment by delphiactual** [comment]
This only occurs in dev branch, not master

**Comment by delphiactual** [comment]
ErrorCode: 1627
https://github.com/DestinyDevs/BungieNetPlatform/wiki/Error-Codes
`Destiny Vendor not found`
It appears Vendors are trying to be loaded before login is confirmed

**Comment by SunburnedGoose** [comment]
The active platform was null.  Within reloadStores function, I exit early with a rejection when encountering a null platform.
