### ISSUE TITLE
Quick Filter buttons; Ability to name saved filters

### ISSUE THREAD

**Issue by zacgoodwin** [DestinyItemManager/DIM#7861]
### Proposed change

I would like the ability to push a quick filter button instead of relying on the dropdown. In addition, I want the ability to name filters for easy access

![image](https://user-images.githubusercontent.com/666712/153952738-a6f9d272-cbfc-49a3-8146-df8ba4abe7b0.png)

### How does this fit into your workflow?

Right now, with saved filters you are limited to the 7 most recent ones showing up on the dropdown. If I want to access any of my other saved filters I need to start typing them which creates a couple extra clicks. It would be great if I could have buttons for my most commonly used filters in the empty space where the Postmaster is. Then I could just just push button and do action.

In addition, the ability to name saved filters would be really handy. Instead of having to type part of a query to get something to show up I could just type the name I made it. It makes you have to think less especially if you have a couple similar queries. 

The buttons would display what you named the query :)

**Comment by robojumper** [comment]
#7174 for previous discussion on named filters.

**Comment by zacgoodwin** [comment]
What about the part of the quick selection buttons? 

Another example would be in JIRA; filtering a large amount of items to a smaller subset quickly

![image](https://user-images.githubusercontent.com/666712/153955841-d3c20235-ff53-47a6-8d51-c65ca6a1a56c.png)

**Comment by bhollis** [comment]
Given the issue is that you can only see 7 saved filters without typing, does that imply that you'd need at minimum 8 buttons?

**Comment by bhollis** [comment]
Also keep in mind that *very* few users save searches.

**Comment by zacgoodwin** [comment]
Ahhh in that case it's probably not worth it. 

8 buttons would be nice but I imagine 6 would do. The appeal was more the buttons themselves to quickly access a query or a query that I may not use as much but want easy access to when I do. 

For example, I'd love a button for a query to show me all the guns with either adrenaline junkie or demolitionist but I only need it when I switch to my grenade spam loadout. Because it's not used as frequently as the queries I have to clean my gear it doesn't make it into the top 7 and I have to type it out again. Just less mental load + steps to click a button rather than a search field, type a partial name, then either click on the filter or push down twice and select it.
