### ISSUE TITLE
A "Remove All Mods" option

### ISSUE THREAD

**Issue by TheGokki** [DestinyItemManager/DIM#7865]
### Proposed change

Title. I would like an option to remove all mods from selected/filtered items. Same thing in the Loadouts menu.

### How does this fit into your workflow?

It's a "start fresh", basically. Letting me create loadout and avoid slot conflicts. I have recently tried to do it but was unable, had to manually do it on a lot of items and took some time.

**Comment by bhollis** [comment]
Yup, it's in the works
