### ISSUE TITLE
Loadout Optimizer no longer saves selections for "Assume Masterwork"  or "Lock Element"

### ISSUE THREAD

**Issue by zacgoodwin** [DestinyItemManager/DIM#7867]
### DIM Version

Version 7.5.1.1001295 (beta), built on 2/14/2022, 4:10:38 PM

### Browser Details

Chrome App

### OS Details

Windows 11

### Describe the bug

When I saved a loadout and set "Assume Masterwork" as "All", I expected it to keep those setting next time I opened the Optimizer, but instead it did not. 

![chrome_2tUgmcHjDz](https://user-images.githubusercontent.com/666712/154134462-314abd77-981f-4003-a5e7-7c0a535db3c6.gif)

**Comment by bhollis** [comment]
@ryan-rushton looks like the changes to upgrade settings weren't fully plumbed through?

**Comment by ryan-rushton** [comment]
I thought they were but I will check again now.
