### ISSUE TITLE
Unselected items in Vendor item popup are hard to see

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#787]
For the unselected items I already own, the opacity is making it hard to see what their stats values are.  

Suggest bringing the opacity value up to .7.

![2016-08-12_102345](https://cloud.githubusercontent.com/assets/984608/17627510/200b2bbc-6077-11e6-9eca-31705e9dd15f.png)

**Comment by bhollis** [comment]
I made these a lot less transparent a while back.
