### ISSUE TITLE
When clicking the "Add Unequipped" button, the loadout editor fills the screen

### ISSUE THREAD

**Issue by zacgoodwin** [DestinyItemManager/DIM#7870]
### DIM Version

Version 7.5.1.1001295 (beta), built on 2/14/2022, 4:10:38 PM

### Browser Details

Version 97.0.4692.71 (Official Build) (64-bit)

### OS Details

Windows 11

### Describe the bug

When I click the "Add Unequipped" button on the loadout editor, the editor expands to fill the entire screen. Once it is in this state you can't revert it. I would expect it to remain the same size on the screen as when I originally opened it. 

![chrome_pEH9B89s6l](https://user-images.githubusercontent.com/666712/154141460-a4e37fb8-66b4-48e5-bd36-a07366223afe.gif)

The "Add Unequipped" button under the 3 dot menu works as expected

![image](https://user-images.githubusercontent.com/666712/154142027-80db6502-413d-4479-9062-d4cf880a6940.png)

**Comment by bhollis** [comment]
The sheet expands to fit what you put in it - if you put a lot of stuff in it, it expands until it is the maximum height. 

The alternative would be to scroll, but that has its own challenges.

**Comment by zacgoodwin** [comment]
Oh I see that now. I am dumb. Thanks!
