### ISSUE TITLE
No button to add unequipped items to a loadout

### ISSUE THREAD

**Issue by zacgoodwin** [DestinyItemManager/DIM#7871]
### DIM Version

Version 7.5.1.1001295 (beta), built on 2/14/2022, 4:10:38 PM

### Browser Details

Version 97.0.4692.71 (Official Build) (64-bit)

### OS Details

Windows 11

### Describe the bug

When I edit a loadout there is no longer a way to add items to the unequipped section. 

![chrome_B75z6P3JCc](https://user-images.githubusercontent.com/666712/154141816-7e30c5c1-90e3-4968-bcb7-f8e2128a5aa9.gif)

**Comment by bhollis** [comment]
Yup, that's mentioned in the release notes. 

You can add an equipped item then double click it to make it unequipped. 

You can drag an item in to the "Unequipped" area from your inventory or other loadouts. 

You can click "fill from non-equipped" to use items in inventory. 

But also we acknowledge that this still needs work and we're still working on it.

**Comment by zacgoodwin** [comment]
Cool; I must have missed it in the release notes. Should I close this ticket out?

**Comment by bhollis** [comment]
You can leave it. Most of the followup tasks are in #7841.
