### ISSUE TITLE
Vault class type separators too large and misaligned, breaking item grid

### ISSUE THREAD

**Issue by robojumper** [DestinyItemManager/DIM#7878]
![grafik](https://user-images.githubusercontent.com/14299449/154266820-89774f2c-f9cb-45be-aeff-3a61849dce80.png)

This is on beta but not on app. Firefox, Edge, mobile. Looks like a side effect of the upgrade from #7873?

**Comment by bhollis** [comment]
Interesting, I wonder what dependency could've affected that

**Comment by delphiactual** [comment]
https://github.com/DestinyItemManager/DIM/pull/7874/files#diff-1390a5bb2e615d85c49f18030bc5ce026b28e4626260c47754ac7abec4662fc1L10-R11

**Comment by bhollis** [comment]
Hmm, but that PR isn't merged. And it's just replacing one export for a different export of the same icon.

**Comment by robojumper** [comment]
Looks like a fontawesome styles change:

```diff
-svg:not(:root).svg-inline--fa {
-  overflow: visible;
-}

+svg:not(:root).svg-inline--fa, svg:not(:host).svg-inline--fa {
+  overflow: visible;
+  box-sizing: content-box;
+}
```

**Comment by bhollis** [comment]
That'd do it. We should probably pin all font awesome at v6 - their v7 icons don't look the same and I don't think we want them.

**Comment by nev-r** [comment]
#7910 fixed and pinned

**Comment by robojumper** [comment]
With #7978 this is back.

**Comment by nev-r** [comment]
@bhollis is there a stricter way i can pin this

**Comment by bhollis** [comment]
Does it change in a patch version? I had changed it so we would still get patches but wouldn't accept even minor version bumps.

**Comment by bhollis** [comment]
The other option is to tweak our CSS to handle the change
