### ISSUE TITLE
Download classified JSON data from dim.org on start

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#788]
Let's test loading a JSON file on our .org to load additional data into DIM such as amendments to classified objects to enhance their attributes.

**Comment by delphiactual** [comment]
@SunburnedGoose, which attributes would you like to collect for these? Bucket would remove the need for  #1097 and put the classified item in the correct vault location, instead of an assumed one. Also the correct name? Still using the classified icon?

**Comment by delphiactual** [comment]
#1396

**Comment by bhollis** [comment]
This is in PR. Closing the issue.
