### ISSUE TITLE
Pull from postmaster, overflow

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#7883]
![image](https://user-images.githubusercontent.com/4798491/154356739-36a488f1-200e-487e-bc46-20c7d08f41dc.png)

**Comment by nev-r** [comment]
temporarily addressed in https://github.com/DestinyItemManager/DIM/pull/7913 but confirm button needs to be modified to measure and handle arbitrary height next

**Comment by nev-r** [comment]
addressed in https://github.com/DestinyItemManager/DIM/pull/7919
