### ISSUE TITLE
Add a weapon type seperator

### ISSUE THREAD

**Issue by zacgoodwin** [DestinyItemManager/DIM#7891]
### Proposed change

I'd like the ability to toggle on a weapon type separator similar to this one in Braytech so I can visually find the items I want quicker. 

[http://www.zoph.net/seperator.png](http://www.zoph.net/seperator.png
)
### How does this fit into your workflow?

When I am looking for a gun or a specific type of gun this will let me see it faster in my vault than I currently can.

**Comment by zacgoodwin** [comment]
![Uploading seperator.gif…]()

**Comment by delphiactual** [comment]
Dupe https://github.com/DestinyItemManager/DIM/issues/3613
