### ISSUE TITLE
Better selection of default socket when clearing unselected mods

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#7896]
This tries to plug the Riven's Curse plug into Dreaming City armor as a means of resetting it, which is not allowed.

**Comment by robojumper** [comment]
In general we should add a notion of the "empty" plug item hash for every socket, if it exists. Right now we rely on `singleInitialItemHash`, which is often not the empty one, and in cases where there is no empty plug (abilities, aeon sect mods, masterworks) actively misleading. I did some experiments a while back, which I'm looking to revive when the WQ definitions hit -- we'll see how weapon crafting affects that approach.

**Comment by bhollis** [comment]
That sounds great, having a stable concept of "empty" would be very helpful.
