### ISSUE TITLE
DestinyPresentationNodeDefinition.children.craftables

### ISSUE THREAD

**Issue by nev-r** [DestinyItemManager/DIM#7916]
- [x] build craftables in DIM's node tree structure, for this new type of PresentationNode child
- [x] set up basic rendering for this leaf type
- [x] decide what conditions, if any, should determine tile greyed-out-ness
- [ ] display stuff related to the profile-provided crafting metadata: requirements met/unmet
- [ ] display stuff related to which plug? plugsets? are unlocked. in a sheet? popup?

**Comment by bhollis** [comment]
Craftables in presentation nodes turned out to be kind of a bummer - the records version is much more consumable.
