### ISSUE TITLE
Engram Pull from Postmaster count is wrong

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#7932]
![image](https://user-images.githubusercontent.com/4798491/154854892-d0bac890-e280-4932-8e06-7fde24f4aef9.png)

**Comment by bhollis** [comment]
Can you explain more about what makes it wrong? When you push the button how many items get collected?

**Comment by delphiactual** [comment]
One, I only have one engram space available.

**Comment by bhollis** [comment]
I think it's counting things that could be pulled, disregarding whether there's space for them.
