### ISSUE TITLE
Witch Queen to-dos

### ISSUE THREAD

**Issue by nev-r** [DestinyItemManager/DIM#7942]
- [x] investigate user-reported missing item warning in loadouts. maybe void subclass related? maybe nothing
- [x] there's a new "crafted" tile overlay symbol.
![image](https://user-images.githubusercontent.com/68782081/155312002-2251cd04-68e9-4f04-b38c-c1e0acbecd68.png)
completely onboard with just sticking to the red border for "crafted items", space is at a premium. HOWEVER, red border does have a different meaning in-game (highlighted objective+incomplete)
- [x] lot of blank boxes on a crafted glaive
![image](https://user-images.githubusercontent.com/68782081/155206047-7fd8e04e-38be-471e-a6ab-9bac6014987b.png)
- [x] move this thing elsewhere on crafted weapons
![image](https://user-images.githubusercontent.com/68782081/155206146-9dda749f-5f62-42d2-97d4-2c8b44f27b3a.png)
- [x] that shaping date may be available as an objective! forgot to implement the new date thing huh.
- [x] #7983
- [x] DIM claims "This weapon has active Deepsight Resonance that can be progressed. This weapon has Resonant Elements available to be extracted. Open the details screen of the weapon to extract." but it's not supported by the in-game item details screen
- [ ] pending resolution of https://github.com/Bungie-net/api/issues/1598, turn tooltips back on (moved to issue https://github.com/DestinyItemManager/DIM/issues/8386 )
- [x] season number metadata for new items
- [x] #7984

**Comment by bhollis** [comment]
>  investigate user-reported missing item warning in loadouts. maybe void subclass related? maybe nothing

Pretty sure #7929 will fix it

**Comment by MZorzy** [comment]
+ Add season number to new weapon.  

like Krait is not filtered season:15 or season:current . have "null" undel seasno colum

**Comment by nev-r** [comment]
this failed https://github.com/DestinyItemManager/d2-additional-info/actions/runs/1882979170 so new season info wasn't processed

**Comment by philkernick** [comment]
> like Krait is not filtered season:16 or season:current . have "null" undel season colum

If you want to find them for now, you can do this:
`-season:>1 is:legendary`
