### ISSUE TITLE
Cant clear out titan inventory

### ISSUE THREAD

**Issue by jamessmithh2002** [DestinyItemManager/DIM#7946]
### DIM Version

Version 7.6.0 (release), built on 21/02/2022, 12:26:08

### Browser Details

opera GX

### OS Details

Windows 10

### Describe the bug

when i try to transfer something from my titan to my vault it works but then something else from my vault in the same slot witll transfer from the vault to my titan it doesn't happen on other characters

**Comment by bhollis** [comment]
Your vault is full? I'm afraid you haven't provided enough info to help. Feel free to hop on the Discord and folks can walk you through providing enough information.
