### ISSUE TITLE
Mouse hover no longer working on iPad touchpad

### ISSUE THREAD

**Issue by Funktion29** [DestinyItemManager/DIM#7951]
### DIM Version

7.6.0 release 2/21/2022 04:26:08am

### Browser Details

iOS app on iPad

### OS Details

iOS 15.3.1

### Describe the bug

When using an iPad Pro and the Magic Keyboard with touchpad the “cursor” no longer has a hover action when viewing perks in the compare window. Tapping the trackpad will change the perks, but one must actually touch/long press the screen to see the perks now. The touchpad does still work to sort the stats and preview perk changes and seems to function normally in the inventory window of DIM. 

Thanks

**Comment by bhollis** [comment]
This would likely be fixed by #7643
