### ISSUE TITLE
Loadout optimizer fails to compute a load out that should be possible

### ISSUE THREAD

**Issue by Anthropole** [DestinyItemManager/DIM#7959]
### DIM Version

Version 7.6.0.1001353 (beta), built on 2/24/2022, 6:40:19 AM

### Browser Details

Version 1.35.103 Chromium: 98.0.4758.102 (Official Build) (x86_64)

### OS Details

MacOS 12.3 Beta 21E5212f

### Describe the bug

In "Loadout Optimizer" I setup a Loadout (https://dim.gg/x7nkpsq/Loadout-Optimizer-Settings) with "The Bombardiers" as pinned exotic (combined mods costing 6, current energy value at 1) and I chose a Mobility mod to complete the loadout (bringing the cost to 9 energy) I epected DIM to update its callout that the exotic needs to be upgraded from 1 to 9 in order to fit the selected mods but instead Loadout Optimizer says there's "No builds found."

**Comment by bhollis** [comment]
Screenshot?

**Comment by ryan-rushton** [comment]
Hi @Anthropole, we need some more information to be able to debug this. Because your loadout is instanced from your items we cannot reproduce with only the link. I really need to see some screenshots to see what is going on.
