### ISSUE TITLE
LO: Indicate missing mods from shared loadouts.

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#7966]

**Comment by bhollis** [comment]
I think it does?

**Comment by delphiactual** [comment]
![image](https://user-images.githubusercontent.com/4798491/156032303-c09dc17e-166f-4c3d-8556-a9f2ec1d1759.png)
Only when trying to apply

**Comment by delphiactual** [comment]
Instead of just saying no builds found; Maybe we should show the missing mods etc

**Comment by bhollis** [comment]
If I can get #7929 merged, then shared loadouts won't go to LO anymore.
