### ISSUE TITLE
Dragging items with Deepsight objective icon freezes Chrome

### ISSUE THREAD

**Issue by tcurtin** [DestinyItemManager/DIM#7974]
### DIM Version

Version 7.6.0.1001361 (beta), built on 2/27/2022, 9:04:27 PM

### Browser Details

Standalone version

### OS Details

MacOS 12.2, Apple M1 Max

### Describe the bug

When attempting to drag a new attunable weapon to a new location, the app freezes hard (to the point that I can't even use the Mac menu bar to force quick via right click, I need to command-option-escape to bring up the Force Quit window.)

I'm quite space-limited, but that doesn't seem to be the issue, as it happened even when moving from postmaster to character when there were weapon slots free.

I *am* able to move these weapons by clicking on the weapon and then clicking the icon for the character or vault I want it to go, and that works fine every time.

**Comment by tcurtin** [comment]
As an added piece of info, weapons that have already been attuned (ie enough kills and resource harvested) can be moved by dragging without any issue.

**Comment by bhollis** [comment]
Interesting, there's nothing about the attunable weapons that should matter at all for moving them.

**Comment by tcurtin** [comment]
I just confirmed that dragging attunable weapons works fine for me on iPad standalone and Chrome browser version.  But Apple MBP standalone version hangs hard every time.

**Comment by bhollis** [comment]
You didn't say what browser you're using, but on my M1Max laptop on Chrome I have no problems with dragging any item.

**Comment by tcurtin** [comment]
I'm on Chrome, Version 98.0.4758.109 (Official Build) (arm64) (although not sure how that factors into the standalone version...)

**Comment by bhollis** [comment]
I can't help but think it's something specific to your machine, not DIM, given that I can't reproduce it on a nearly-identical machine and browser, and nothing about these weapons are any different to the other weapons to the move logic.

**Comment by tcurtin** [comment]
Just did an update to [Version 7.7.0.1001368 (beta), built on 2/28/2022, 3:36:13 PM] and that seems to have fixed things!  Most excellent.  :)

**Comment by bhollis** [comment]
Nice!

**Comment by tcurtin** [comment]
I take it back...  it did work... once, immediately after updating to the new version.  I was able to move a Forensic Nightmare from postmaster to character, and then from character to vault... and that was the end of the fun.  Now as soon as a drag starts it locks up again, without even any output to the debug console.

**Comment by bhollis** [comment]
From discussion on Discord, this seems to only happen on items with the red triangle exclamation mark SVG showing. Of course, I can't reproduce it on my Mac.

**Comment by bhollis** [comment]
I have no idea why having an extra SVG there would lock anything up.

**Comment by bhollis** [comment]
I *think* I've fixed this by blocking pointer events from the icon. Any luck?

**Comment by bhollis** [comment]
Getting reports that this is fixed
