### ISSUE TITLE
Some craftable sockets not displaying

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#7975]
<img width="356" alt="image" src="https://user-images.githubusercontent.com/313208/156036156-d27782a9-d681-4d3f-a6d8-e87e59a864f7.png">

**Comment by robojumper** [comment]
This is the regular Y2+ masterwork socket. The Bungie.net API says that some sockets should be hidden but we throw that infi away, maybe we should start obeying that. Probably also works for the deepsight socket I manually hid before.
