### ISSUE TITLE
Rework in-memory loadout structure

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#7986]
Our loadout structure in memory is really hard to work with, and so are DimLoadoutItems that mash the loadout item spec and a real DIM item together. I'm going to redo them all to be a lot clearer.

@ryan-rushton FYI

**Comment by ryan-rushton** [comment]
Sounds great, I have been meaning to find a better solution to DimLoadoutItem's as they were meant to be a temporary solution. 

I've seen you mention having something that indexes DimItem's by id so we don't need to continually loop over allItems from stores. I would be pretty keen to get that into redux as it would provide a nice means to get perf improvements and clean up a bunch of code.
