### ISSUE TITLE
void 1.0 subclasses are still showing in loadouts and cannot be removed.

### ISSUE THREAD

**Issue by inexorableAce** [DestinyItemManager/DIM#7989]
### DIM Version

7.7.0.1001370 (beta)

### Browser Details

FF current

### OS Details

windows 10

### Describe the bug
![image](https://user-images.githubusercontent.com/29002828/156089161-d00d7bfd-69b0-40c7-a437-1c8808d24ad3.png)
![image](https://user-images.githubusercontent.com/29002828/156089186-8da74dc1-aee5-497c-ae53-501fe7dbfbbb.png)
![image](https://user-images.githubusercontent.com/29002828/156089052-3f4490d2-56c8-4f07-9731-17d9116f56b0.png)

**Comment by JonEffingSnow** [comment]
Browser is actually Google Chrome, current version (98.0.4758.102). These loadouts created before Witch Queen seem to have a subclass on them that cannot be removed or changed with the edit button.

**Comment by bhollis** [comment]
I see, apparently they changed the subclass to a whole other item.
