### ISSUE TITLE
Randomize Equipped Items

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#799]
Someone asked nicely if we could add a feature to randomize their equipped items for streaming shenanigans. Sounded like a great idea.

Pi.

**Comment by SunburnedGoose** [comment]
Look at what I found @chrisfried #177

**Comment by chrisfried** [comment]
There it is. Looks like I just shuffled all equipment, grouped it back together by type -- `var groups = _.groupBy(_.shuffle(_.where(dimItemService.getItems(),{equipment:true})), 'type');` -- then grabbed the first item from each, ignoring subsequent exotics after one is found.

**Comment by kyleshay** [comment]
this was implemented, for future dev visit: #836
