### ISSUE TITLE
Inventory not resetting to proper orientation in beta on mobile using safari app version

### ISSUE THREAD

**Issue by Aragornking41** [DestinyItemManager/DIM#7996]
I am on an iphone 12 mini and when I rotate my phone, in beta, to landscape mode (usually an accident) and then back to portrait this happens to the sorting. My item size is 50px and my character inventory width is set to 5. I am on iOS 15.2.1. This issue does not happen in normal dim.

![F94558C0-3755-4456-BF0F-0BA97B06BBF3](https://user-images.githubusercontent.com/63864737/156230111-24d6155c-e306-4293-8e85-89dc973b9c19.png)

**Comment by Aragornking41** [comment]
Yeah I can't figure out what to do with this. It first started happening in December. I brought it up in discord support on new years eve and no one could replicate it then. Was really hoping it could be now.

**Comment by bhollis** [comment]
I figured this out. It's because the item feed sidebar is open.

**Comment by bhollis** [comment]
This should be fixed in 5 minutes once Beta updates.

**Comment by Aragornking41** [comment]
Oh my goodness!! I know this isn't a big deal to anyone but that was an awesome QoL for me thank you!
