### ISSUE TITLE
Plain text search on perk description not working

### ISSUE THREAD

**Issue by shockthealien** [DestinyItemManager/DIM#800]
As discussed over twitter, I was requesting that the plain text search would use the description of the perks, mainly for searching on the ghosts to quickly identify which to equip depending on the enemy type (i.e. search HIVE to find which ghost gives glimmer for hive kills) but apparently this is a bug and been asked to raise the issue here, so yeah that. 

Screenshot attached of search and item not included in search results

![cp6d00pwaaabcwd jpg-large](https://cloud.githubusercontent.com/assets/2083273/17695026/a72299a8-639e-11e6-9133-3f31241e5dce.jpeg)

**Comment by SunburnedGoose** [comment]
Fixed.
