### ISSUE TITLE
Enhanced weapon trait styling in Organizer

### ISSUE THREAD

**Issue by vivekhnz** [DestinyItemManager/DIM#8005]
With the introduction of weapon shaping, weapons can now have Enhanced Traits. These are styled slightly differently and we should reflect that in DIM:
- Update perk 'bubbles' in the item popup (both list & grid) and armory views to include a yellow (`#f3cf55`) arrow intersecting with the left edge of the bubble and a yellow linear gradient at the bottom of the bubble (see in-game perk bubble)
- When the item popup is displayed in perk list mode, style the separator line above an enhanced trait 'row' as a yellow line + gradient to match the in-game item tooltip. Note that shaped weapons cannot currently have multiple perk choices in the same column, so we don't need to worry about having a mix of non-enhanced and enhanced traits in the same column.
- Update the **Perks, Mods & Shaders** and **Weapon Traits** columns in Organizer to display a yellow arrow to the left of enhanced traits (see in-game item tooltip)
- Style the item subtype text in the perk PressTip to match the in-game perk tooltip for enhanced traits

See below for reference screenshots:
![dim-enhanced-traits-reference](https://user-images.githubusercontent.com/17512262/156352655-c4616bc8-7516-4195-b8d8-be6ff6bd000b.png)

**Comment by vivekhnz** [comment]
Regarding my comment regarding the yellow horizontal line above enhanced traits:
> Note that shaped weapons cannot currently have multiple perk choices in the same column, so we don't need to worry about having a mix of non-enhanced and enhanced traits in the same column.

It seems like Adept weapons from Vow of the Disciple (Master difficulty presumably) will be able to drop with Enhanced Traits based on their perk pools. If they can also drop with multiple perks in the same column (as was the case for Timelost weapons from Master difficulty Vault of Glass), we would need to account for a having a mix of non-enhanced and enhanced traits in the same column.

**Comment by nev-r** [comment]
i am not of the opinion we need this styling 
![image](https://user-images.githubusercontent.com/68782081/157806429-13fb2033-7df2-4709-bbd3-b782ddb90509.png)

for 1, it's hideous, for 2, we aren't braytech

**Comment by vivekhnz** [comment]
Yep, fair enough. I think what we have in beta looks good so will close this.

**Comment by nev-r** [comment]
i was leaving it open because it's not yet implemented in organizer, and possibly other places, haven't really done a thorough sweep
