### ISSUE TITLE
Vendor items grouped with wrong character

### ISSUE THREAD

**Issue by puzelek** [DestinyItemManager/DIM#801]
Vendor items are not grouped correctly with character. Under Titan i have Warlock items and under Warlock i have Titan items. 
Chrome version: Version 51.0.2704.103 (64-bit)
OS: OSX 10.11.3 El Capitan 
(if Chrome version or os version mean anything to You :))
pic:
https://pbs.twimg.com/media/Cp-Mt5pWAAARhgs.jpg
Closing and relaunching DIM does not help.

**Comment by delphiactual** [comment]
@ericnelson0 it appears that the headers support character order, but the columns are hard-coded.

**Comment by ericnelson0** [comment]
@puzelek @delphiactual Thanks.

**Comment by SunburnedGoose** [comment]
This has been fixed.
