### ISSUE TITLE
Fynch level is wrong as shown on Vendor tab

### ISSUE THREAD

**Issue by quetschke** [DestinyItemManager/DIM#8016]
### DIM Version

Version 7.7.0 (release), built on 2/28/2022, 12:09:23 PM

### Browser Details

Firefox on Windows 10 and Chrome on Android

### OS Details

Windows 10 and Android

### Describe the bug

See the level of Fynch being shown as 2, but it is higher than that as deepsight tier 2 is already purchased.

![image](https://user-images.githubusercontent.com/5354403/156459487-3d4a3d0b-827b-4290-9172-e8792d65d35c.png)

**Comment by robojumper** [comment]
This was fixed in #8255.
