### ISSUE TITLE
Loadout: Don't Share Empty Fragment Slots

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#8019]
https://dim.gg/fw3wada/VOIDLOCK-2.0

**Comment by robojumper** [comment]
The reason this is happening is that the singleInitialItemHash of the void 3.0 sockets isn't actually the void empty plug, but rather the stasis empty plug. The one in the plug set is a different one. So Void subclasses start with the stasis empty plug inserted. Once the user plugs something else it's never considered empty by DIM.

Bungie said this won't be fixed on their side https://github.com/Bungie-net/api/issues/1606

I'll put something up that opens a path to addressing this very soon.
