### ISSUE TITLE
Rapid scrolling gestures close popups on mobile both beta and regular

### ISSUE THREAD

**Issue by Aragornking41** [DestinyItemManager/DIM#8031]
When opening a popup in mobile such as: armory, item details, or compare, attempting to scroll down with too quick of a gesture causes the window to close. This was not this touchy pre witch queen.

**Comment by bhollis** [comment]
We didn't change anything about it though

**Comment by rekcluse** [comment]
I can second this and just came here to post about the issues. Currently using a Samsung Galaxy S10+ and when trying to view the bottom of an items details it will immediately close that item. 

The input is touching and scrolling upwards - this is when it will close the item. 

Its not something happens 100% of the time but happens more ofte  than not.

**Comment by bhollis** [comment]
Got it, I think I know what's going on.
