### ISSUE TITLE
Add the ability to add filter queries to a loadout.

### ISSUE THREAD

**Issue by couldie** [DestinyItemManager/DIM#804]
With the addition of "is:glimmeritem" and "is:glimmerboost" it made me think it'd be nice to have the ability to add a filter query to a loadout as a "move all" function.

This would stop people having to type in a full filter query every time they wanted all of one type of item added to a character. Whenever I switch character, I like having all glimmer items and materials on the character I'm playing on, just incase I need them in a hurry. Having this option would mean I wouldn't need to manually add each glimmer boost to a loadouts inventory.

I hope this makes sense, and I hope it would come in handy for others.

**Comment by SunburnedGoose** [comment]
All we need then is the loadout to filter by the character on the search resultset owners.  I can dig it...

**Comment by couldie** [comment]
Couldn't you just add "is:titan" to the query that you add for it to only move Titan specific items?

**Comment by SunburnedGoose** [comment]
I have two warlocks :)

**Comment by couldie** [comment]
I have three Titans and don't understand your meaning

**Comment by SunburnedGoose** [comment]
I assumed you had one of each class and you were using it as a discriminator.

**Comment by kyleshay** [comment]
#397 will allow you to save filters as loadouts

**Comment by bhollis** [comment]
Closing in favor of #397.
