### ISSUE TITLE
Bring back selected super display?

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#8045]
The new subclass reworks mean our custom super display doesn't work anymore:
<img width="247" alt="image" src="https://user-images.githubusercontent.com/313208/156703222-c3fe20ef-dc8e-4850-be53-69169294a9e4.png">

Should we:
1. Show the selected super for mod-style subclasses
2. Leave it as is and when they get upgraded they show the generic subclass icon
3. Remove the selected super for non-upgraded subclasses

cc @vivekhnz

**Comment by vivekhnz** [comment]
I vote for option 1.

This is some of the new Void Super icons overlaid on top of a modified Void base image, I think it looks good:
![dim-void-subclass-supers](https://user-images.githubusercontent.com/17512262/156707005-bba03d42-d2a7-483f-96cb-59db17228408.png)

The base images would need some adjustment to accommodate for the gradient at the bottom of the super icons. In the image above, I applied +50% brightness and +25% contrast.
