### ISSUE TITLE
Build math and class item % are off

### ISSUE THREAD

**Issue by renaldafeen** [DestinyItemManager/DIM#805]
World Class work here, folks!

However, I still find myself switching to Tower Ghost for accurate roll quality and loadout numbers. Perhaps it's just me, but DIM's are consistently off.

In particular, DIM tells me that many of my ~~Class Items~~ artifacts are >100% rolls which, of course, is erroneous.  I can't find anything on erroneous numbers for artifacts using the Filter, so maybe I'm doing something wrong??

Also, when I use the loadout builder, the total is frequently incorrect, both based on manually summing the stat values and examining the equipped loadout in Bungie's Destiny App (or in-game), which matches my manual sum. This is after carefully comparing the build in DIM with the stats/perks selected on each item.

Will provide screenshots, if needed, once Bungie's maintenance is complete.

**Comment by SunburnedGoose** [comment]
We base artifacts at 38, and the buggy int/dis artifacts can reach 51, which is > 100%.  Send your screenshots and data where the stats are off.

**Comment by ericnelson0** [comment]
@renaldafeen Are you items ranked to 335 and using the correct bonus types to get your total from the loadout builder? If so, screenshots would help debug the issue.

**Comment by renaldafeen** [comment]
Yes - ranked to 335. However, after looking at each piece carefully, I think the cause was that the builder selected a chest piece that isn't fully leveled. The numbers it was using were for a fully-leveled item and, as such, the total Dis was 25 pts high. I think I've run into this before without realizing the cause. Taking that into account, the numbers add correctly. Thanks!
