### ISSUE TITLE
Ace of spades perk wrong

### ISSUE THREAD

**Issue by that-paramecium** [DestinyItemManager/DIM#8050]
### DIM Version

7.70

### Browser Details

Chrome 99.0.4844.47

### OS Details

iOS 15.3.1

### Describe the bug

I was looking at my Ace of Spades when I noticed that firefly (perk) looked like Smart Drift Control (?).  Screenshot attatched
![A5B36D12-B32D-4186-841F-C8B560FB367A](https://user-images.githubusercontent.com/100944531/156774024-bb6b82f6-44f6-40c2-8db7-607b0a7682c1.jpeg)

**Comment by delphiactual** [comment]
What does it look like in-game.
https://data.destinysets.com/i/InventoryItem:1561789734

**Comment by delphiactual** [comment]
![image](https://user-images.githubusercontent.com/4798491/156941628-2d8ddac9-7ad2-4c66-b4b7-0faba6d4de2a.png)
