### ISSUE TITLE
Mod selection on iOS loses position when keyboard automatically opens

### ISSUE THREAD

**Issue by brwaters** [DestinyItemManager/DIM#8064]
### DIM Version

Version 7.7.0.1001429 (beta), built on 2022-03-04, 1:08:18 PM

### Browser Details

Safari iOS 

### OS Details

iOS 15.3.1

### Describe the bug

Safari web app DIM beta: when the mod selector comes up and the cursor is placed into the search field automatically, iOS will fetch the keyboard and then various elements will shift upward and off the screen.  If the keyboard is dismissed most elements return to intended position except loadout manager page which will have moved down showing the next loadout in the list. 

https://imgur.com/a/Bb9FMPh

![69ABBB79-5FEF-41E5-B996-1A3F695529ED](https://user-images.githubusercontent.com/35816999/156845986-bf1cde9b-e0e5-44d9-868f-2fac5c69b586.png)
![F974642E-FAE1-4C82-B9CD-A59EE2DA6DA2](https://user-images.githubusercontent.com/35816999/156845991-cc81e850-574f-415c-be65-ea36b00b1e45.png)

**Comment by bhollis** [comment]
Thanks, we should specifically be disabling autofocus on Safari
