### ISSUE TITLE
Armor mod images in item popup are too large

### ISSUE THREAD

**Issue by vivekhnz** [DestinyItemManager/DIM#8068]
### DIM Version

Version 7.7.0.1001432 (beta), built on 3/5/2022, 4:53:10 PM

### Browser Details

Version 98.0.4758.102 (Official Build) (64-bit)

### OS Details

Windows 10 (10.0.19043.1526)

### Describe the bug

Armor mod images in the item popup are too large (energy cost no longer aligns properly).
![dim-armor-mods-too-large](https://user-images.githubusercontent.com/17512262/156867240-7141187a-69d3-4bfc-a7de-cd833abd5e18.PNG)

`git bisect` is blaming 73be21dba72c7efc27635a0a8a44c8c1917683eb for #8025.
cc @nev-r

**Comment by nev-r** [comment]
thank you!
