### ISSUE TITLE
Adding Class names to Vendor Page Categories

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#808]
I want to tweet pics of gear, but it helps if I can show the user which class the gear is associated with...

Can we add Titan, Hunter, Warlock to the title are (Armor) so it is clear which owns which?

![296db5f132f20d8fc4b0e12596d4fd2c](https://cloud.githubusercontent.com/assets/984608/17723892/37b7e6c6-6403-11e6-9732-16ff084d037f.png)

**Comment by ericnelson0** [comment]
What's wrong with including the headers?

**Comment by SunburnedGoose** [comment]
They are not fixed.  It won't just be Iron Banner :)  I'm open to alternative though...  I just need the ability to let the user know which class is which column when I screenshot a vendor.

**Comment by ericnelson0** [comment]
Hmm. Like collapse maybe?

**Comment by tehtrav** [comment]
Sticky headers would work well, just like the main DIM gear view

**Comment by ericnelson0** [comment]
@SunburnedGoose Is this ok to close with the sticky headers?

**Comment by SunburnedGoose** [comment]
Sure.
