### ISSUE TITLE
Show Empty Catalyst Sockets that do not exist.

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#8084]
We are currently showing empty catalyst sockets for every exotic weapon, even if they do not have catalysts available.

**Comment by bhollis** [comment]
To know if they have catalysts available we'd have to have a mapping to Records, right?

**Comment by bhollis** [comment]
Linking #8085

**Comment by bhollis** [comment]
What's a good example of an exotic that should hide its catalyst socket?

**Comment by delphiactual** [comment]
This is already complete https://github.com/DestinyItemManager/DIM/pull/8085/commits/70f36a47177648290fc875c5cceaa5af26a84bc1
