### ISSUE TITLE
Add Gunsmith to Vendors?

### ISSUE THREAD

**Issue by tehtrav** [DestinyItemManager/DIM#809]
It would be neat to see what gunsmith rolls, test weapons, and packages are available at the Gunsmith.

**Comment by SunburnedGoose** [comment]
+ Tess and Shader vendor too.

**Comment by ericnelson0** [comment]
Should we just go with all available kiosks/vendors? 

I'm not sure it'll be possible to get the choice of rolls from the gunsmith packages either using only the API.

**Comment by delphiactual** [comment]
I recommend making tabs on the vendor page, it seems redundant to show the same set of weapons on all classes... Or just only show weapons in the middle column...

**Comment by ericnelson0** [comment]
They might be different if your characters are different levels because the way the API works is the vendors are tied to characters. 

I'd be up for a change in UI though, maybe a mockup would help?

**Comment by delphiactual** [comment]
![screenshot 2016-08-17 14 03 43](https://cloud.githubusercontent.com/assets/4798491/17751420/49b61a6a-6484-11e6-8fb4-8cc1c07d6bea.png)

**Comment by SunburnedGoose** [comment]
That's going to be a lot of clicking to see what's up with a faction.  What if they had class specific items like we do now with Taloc?

**Comment by ericnelson0** [comment]
@delphiactual I see what you mean now. Interesting idea.

**Comment by kyleshay** [comment]
added in #862

**Comment by bhollis** [comment]
Closing since it went in as part of #862.
