### ISSUE TITLE
Suggestion for materials loadouts

### ISSUE THREAD

**Issue by AAraKKe** [DestinyItemManager/DIM#81]
I see that in v3 loadouts with materials are still being worked out so I have a suggestion on how to manage materials loadouts before they are finished and working.

Material transfers are different from armor and wepons transfer. When trasferring weapons you usually wnat a weapon in a given character so selecting the weapon to add to the loadout is all you need to do. When transferring material you don't usually want to transfer a given material which is a character but you want to have N materials in a different place. Imagine that I have a total of 100 strange coins scattered in different characters and vault. If I create a loadout with strange coins selecting the ones in my hunter, for instance, I would transfer the coins in my hunter to other place but they might not be enough or too many. What I was thinking is if it possible to add maerials to loadouts as a concept.

Imagine I want a loadout with strange coins so I can have all the strange coins that I need in a given character. I would create a loadout with strange coins and when I want to transfer that loadout I will be asked how many of them I want where the total is sum of all strange coins that I have and DIM would do the math needed to get the amount I need to my character, it doesn't matter where they are. 
In the case of having different materials in the same loadout I would have to choose how many of each material I want to transfer. 

I don't know how hard it could be to implement, maybe it is no feasible but I knew how to do it I would love to try. What do you think? Maybe it has already been discussed.

**Comment by SunburnedGoose** [comment]
I had to pull consumables and materials from loadouts because I wasn't able to get the dialog into this version to specify an amount.  The ideal I had was when a user adds materials to a loadout, they are saying I want at least 'x' amount.  When the transfer occurs, I will make sure that the user has at least the amount specified in the loadout.

**Comment by kyleshay** [comment]
#398
