### ISSUE TITLE
Drag and drop in the DIM App causes system hangup with classified items

### ISSUE THREAD

**Issue by mattsigal** [DestinyItemManager/DIM#8100]
When using drag and drop on the latest DIM beta to move a classified item (raid weapon or armor) between characters/the vault, it results in the DIM app locking up the system (beach ball) and requires a force quit. Using the buttons to transfer the items (e.g. store on Hunter) works. This is the same issue that deepsight weapons had a few days ago.

**Comment by mattsigal** [comment]
Looks like it was fixed when the pieces become unclassified, no need for any further work :)

**Comment by bhollis** [comment]
We'll fix it for next time
