### ISSUE TITLE
Multi basestat filter wildcard (any2)

### ISSUE THREAD

**Issue by Chahta** [DestinyItemManager/DIM#8105]
### Proposed change

This proposed change is similar to #7195 which introduced the highest, et. al. wildcard, but distinct. I propose adding `any2`, `any3`, etc. keywords which searches for the combined TOTAL of any two stats on a piece of armor. Currently, the "highest" series of keywords dictates that each stat individually must meet a threshold (e.g. >17.5 as given in the original post). Using `basestat:any:>=35` for example, could highlight a gear piece with 20 mobility and 15 recovery whereas `basestat:highest&secondhighest:>=35` would not. If numbers are not possible, `anytwo`, `anythree`, etc would also work.

For example,

```
basestat:mobility+resilience:>=35 or
basestat:mobility+recovery:>=35 or
basestat:mobility+discipline:>=35 or
basestat:mobility+intellect:>=35 or
basestat:mobility+strength:>=35 or
basestat:recovery+discipline:>=35 or
basestat:recovery+intellect:>=35 or
basestat:recovery+strength:>=35 or
basestat:discipline+intellect:>=35 or
basestat:discipline+strength:>=35 or
basestat:intellect+strength:>=35
```

becomes

```
basestat:any2:>=35
```

or else

```
basestat:mobility+resilience+recovery:>=49 or 
basestat:mobility+resilience+discipline:>=49 or
basestat:mobility+resilience+intellect:>=49 or
basestat:mobility+resilience+strength:>=49 or
basestat:mobility+recovery+discipline:>=49 or
basestat:mobility+recovery+intellect:>=49 or
basestat:mobility+recovery+strength:>=49 or
basestat:mobility+discipline+intellect:>=49 or
basestat:mobility+discipline+strength:>=49 or
basestat:mobility+intellect+strength:>=49 or
basestat:resilience+recovery+discipline:>=49 or
basestat:resilience+recovery+intellect:>=49 or
basestat:resilience+recovery+strength:>=49 or
basestat:resilience+discipline+intellect:>=49 or
basestat:resilience+discipline+strength:>=49 or
basestat:resilience+intellect+strength:>=49 or
basestat:recovery+discipline+intellect:>=49 or
basestat:recovery+discipline+strength:>=49 or
basestat:recovery+intellect+strength:>=49 or
basestat:discipline+intellect+strength:>=49
```

becomes

```
basestat:any3:>=49
```

### How does this fit into your workflow?

Like #7195, the goal is to find armor with "spiky" stats, but this allows for a less-strict manner. I wouldn't want to miss out on a piece of gear that has 25 recovery and 16 discipline because I set my threshold to `basestat:highest&secondhighest:>=17` while a (in my view) inferior piece of gear with 18 recovery and 17 discipline makes it through.

I can also envision these two filters being used in conjunction like

```
basestat:highest&secondhighest:>=12 and basestat:any2:>= 30
```

This combo would effectively set a minimum for the two highest individual stats of 10, but combined these two stats need to exceed 30.

The any# filters could also be used to find super spiky gear, like a 2/2/27/2/26/2 distribution I have on a Winter's Guile by using

```
is:armor -is:classitem basestat:any4:<=8
```

The `<=` part is probably not necessary, but this filter would be checking that 4 stats combined total 8 or less, meaning it will find any gear that has all its eggs in just two stats. In my collection, I have 17 armor pieces that would fit `is:armor -is:classitem basestat:any3:<=6` but I have to write out the filter long-hand.

**Comment by robojumper** [comment]
How are `basestat:highest+secondhighest:>=35` /  `basestat:highest+secondhighest+thirdhighest:>=49` / ... not sufficient?

Your proposed `basestat:any4:<=8` can also be expressed by `basestat:thirdhighest+fourthhighest+fifthhighest+sixthhighest:<=8`

Also `&` is the mean of values, not that the condition has to hold for both of them.

**Comment by Chahta** [comment]
Sorry, I did not realize `+` and `&` were distinct functions, the Filters Help description makes them sound interchangeable so I didn't test highest with `+`. I also got unlucky with the test value I tried which only returned results with both stats above the threshold using `&` because I did not in fact have any pairs straddling that value. I guess I'm all set then, thanks.
