### ISSUE TITLE
Drowned Element crafting material missing from currencies, filters

### ISSUE THREAD

**Issue by robojumper** [DestinyItemManager/DIM#8106]
https://github.com/DestinyItemManager/d2-additional-info/blob/master/src/generate-crafting-resonant-elements.ts is not generating the drowned element objective hash.

https://github.com/DestinyItemManager/DIM/blob/master/src/app/store-stats/MaterialCounts.tsx is missing the drowned alloy for crafting raid weapons.

https://github.com/DestinyItemManager/DIM/blob/351f9b83143d156d88c7d2827a3dc14d038882ee/src/app/inventory/selectors.ts#L110-L118 is missing the string variable for drowned element.

Maybe the string variables could be auto generated by d2ai too?

**Comment by vivekhnz** [comment]
The first issue (missing entry in `crafting-resonant-elements.ts`) is fixed in d2ai by https://github.com/DestinyItemManager/d2-additional-info/pull/332 and should be resolved in DIM when #8108 is merged.

**Comment by robojumper** [comment]
This was addressed by #8108 and #8115.
