### ISSUE TITLE
Multiple Equipped Items in the same Type on a Character

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#811]
I get multiple equipped items sometimes with DIM.  It isn't restricted to loadouts.  No errors in console.

![2016-08-17_111317](https://cloud.githubusercontent.com/assets/984608/17744036/a2f3b092-646b-11e6-8342-6f89cbf192a0.png)

**Comment by bhollis** [comment]
Linking #898.

**Comment by SunburnedGoose** [comment]
I haven't seen this bug for a while.
