### ISSUE TITLE
Vanguard Reset Count In Wrong Spot

### ISSUE THREAD

**Issue by liamgeor** [DestinyItemManager/DIM#8114]
### DIM Version

Version 7.8.0 (release)

### Browser Details

Chrome

### OS Details

Windows 10

### Describe the bug

My reset count for my vanguard rank is showing under the dares progress. I have reset vanguard twice and dares never (see image)

[
![image](https://user-images.githubusercontent.com/25595832/157490273-e59e370e-c9b4-4fb7-ab90-3d88ecb6b974.png)
](url)

**Comment by delphiactual** [comment]
https://github.com/DestinyItemManager/DIM/issues/7463
