### ISSUE TITLE
Slot and element search prefixes

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#8131]
slot:[kinetic,energy,power,head,arms,chest,legs,class,etc]
element:[none,arc,solar,void,stasis]

**Comment by MeatSim** [comment]
Is it too late to add `craftable:unlockable` to this issue or should I open a new issue? Basically, this would filter `is:craftable is:deepsight`, but only for weapons with unlocked patterns, i.e., incomplete pattern progress in Records > Patterns & Catalysts: 
![image](https://user-images.githubusercontent.com/31776312/158843967-c24f5132-2ab1-40cb-a930-4a87b8200ded.png)
This would be useful to focus on unlocking patterns without going back and forth between Inventory and Records.

**Comment by delphiactual** [comment]
it is not too late, but it is more closely related to #8085 as they both need information from `Records`

**Comment by delphiactual** [comment]
yes please

**Comment by bhollis** [comment]
I'm not sure I like having these types of filters unless our help system can be upgraded to show documentation for them individually.
