### ISSUE TITLE
notes appended to line terminated by punctuation

### ISSUE THREAD

**Issue by jrpayne** [DestinyItemManager/DIM#8137]
### DIM Version

Version 7.8.0.1001488 (beta), built on 3/11/2022, 4:35:13 PM

### Browser Details

any

### OS Details

any

### Describe the bug

Inline notes terminate at punctuation. eg:
dimwishlist:item=-69420&perks=3643424744,2896038713#notes:Over, FocuFury
Shows "Over" in notes element, presumably because the ',' is parsed as a separator.  Replacing it with %2C doesn't matter.  I haven't dared look at the code yet, but if anything from "#notes" to "$" isn't just treated as a single string, it may lead to other issues.  Cheers.

**Comment by bhollis** [comment]
Hmm, I just added a test for the string you provided, and it parses correctly. Can you share more information, such as a screenshot or the entire wish list file?
