### ISSUE TITLE
[Feature Request] Damage falloff in meters and reload speed in seconds shown when viewing individual rolls for guns 

### ISSUE THREAD

**Issue by 32423d** [DestinyItemManager/DIM#8138]
Damage falloff in meters and reload speed in seconds are already shown when picking weapon perks for guns on d2gunsmith.com. It would be more convenient towards DestinyItemManager users if the users would be able to see the damage falloff in meters and reload speed in seconds stats for their individual rolls of guns in DestinyItemManager instead of having to open d2gunsmith.com and select their perks for their rolls to view the stats.

Example of d2gunsmith.com displaying damage falloff in meters and reload speed in seconds:
![image](https://user-images.githubusercontent.com/95009201/158036591-ad6646d9-55de-4ad3-9910-37c406a5cc93.png)

Example of where damage falloff in meters and reload speed in seconds stats for a roll can be placed in DestinyItemManager when viewing an individual roll for a gun:
![image](https://user-images.githubusercontent.com/95009201/158036690-a7d43a48-7c71-46c7-8f17-a8dd6b85e7fc.png)

**Comment by bhollis** [comment]
This is something that's been suggested before, but it's a lot of manual effort to maintain. Unless we had a dedicated maintainer who would make sure that data was always up to date, it's not worth us doing this. I'm not convinced d2gunsmith stays correctly up to date with the game, but even if it does, the maintainer puts work into keeping it up to date, and we have nobody on our side who'll do that.

**Comment by aescolastico** [comment]
I believe light.gg is calculating these values based on the range and zoom stats. They also have a qualifier for when rangefinder is added. They call it their "stat/perk playground". Such a solution could be implemented for light.gg without having to do manual work

https://www.light.gg/announcements/76/lightgg-patch-v21-notes-popularity-ranks-roll-appraiser-item-detail-page-updates-and-more/#item-detail-pages
