### ISSUE TITLE
Loadout Trash Button

### ISSUE THREAD

**Issue by pattont** [DestinyItemManager/DIM#814]
Can we please move the trash can icon elsewhere? 

![image](https://cloud.githubusercontent.com/assets/2903357/17777278/f44d63ee-652d-11e6-8c42-960d58821ec8.png)

It makes me want to click on it every time when I try to go to equip a loadout. Maybe move it inside of the edit flyup?

Thanks!

**Comment by bhollis** [comment]
We do have a confirm dialog before trashing. Where else could we put it? Inside the open loadout editor?

**Comment by kyleshay** [comment]
What if we had an apply loadout icon... (we should use a font-awesome icon for create loadout)

All other loadout options have an icon on the far-left

..anyway, what about moving the trash icon to the far right? 

<img width="314" alt="screen shot 2016-09-10 at 12 50 25 am" src="https://cloud.githubusercontent.com/assets/424158/18408035/9ad26d3a-76f0-11e6-97f7-e4d8201baa38.png">

**Comment by SunburnedGoose** [comment]
Well, you're going to mess people up who are used to the order that they are in now.  So if you're going to change it, it's got to be for a great reason and I don't know if we've met the threshold yet.

Now, what might be a good idea is to put the delete option in the 'edit' loadout popup.  Keep it away from fat fingers :)

**Comment by SunburnedGoose** [comment]
Another reason is people are trying to quickly equip a loadout, we should avoid forcing them into a fine motor skill with a screen or mouse that is probably arm's length away.

**Comment by pattont** [comment]
I agree. The button to delete should be a bit harder to select than the
equip.

It would also be nice if there was a separator between character specific
load outs and global load outs.

**Comment by bhollis** [comment]
This has been this way forever - I think we should just close this and handle deleting loadouts better when we completely redesign how loadouts are created and edited.
