### ISSUE TITLE
Deepsight Farming Mode

### ISSUE THREAD

**Issue by bnb** [DestinyItemManager/DIM#8149]
### Proposed change

A new farming mode where DIM will automatically move all unfinished deepsight weapons to your inventory.

There could also be a few additional toggles:

- Move all non-deepsight weapons out (Boolean)
- Move completed deepsight weapons out (Boolean)
- Attempt to balance special and primary across kenetic/energy if possible (Boolean)

### How does this fit into your workflow?

With the number of deepsight weapons that we're getting, it's borderline necessary to collect then burst farm them in my experience. It's nice to get as much of that done at once as is possible, and I already manage most of it through DIM. It'd be nice if DIM did that management for me.

**Comment by bhollis** [comment]
You could make a saved search for them and just move with the search once you finish one. Farming mode is really for keeping space open for drops - something automatic wouldn't work well since we can't equip in activities.
