### ISSUE TITLE
Miscategorized Pinnacles

### ISSUE THREAD

**Issue by nev-r** [DestinyItemManager/DIM#8151]
"Weekly Gambit Challenge" and "Weekly Vanguard Strikes" and whatever the crucible version is, don't seem to be +2 but +1 pinnacles
![image](https://user-images.githubusercontent.com/68782081/158104684-a138ae37-4840-41da-9c8e-eac68a4cf735.png)

**Comment by bhollis** [comment]
Unfortunately +2 pinnacles and +1 pinnacles share the same item hash, so we'd need to build a manual mapping of milestone to reward.

**Comment by nev-r** [comment]
well rewards are bungie-hand-selected dummies and not indicative of anything programmatic so we should definitely not rely on them alone anyway

**Comment by robojumper** [comment]
Hawthorne's 5000 Clan XP engram is also a +1 pinnacle that's even displayed wrongly in-game IIRC.
