### ISSUE TITLE
"Powerful armor on wrong character" followups

### ISSUE THREAD

**Issue by nev-r** [DestinyItemManager/DIM#8161]
followups to https://github.com/DestinyItemManager/DIM/pull/8154

feel free to split these off into other issues, to address just one

- [x] make this live. right now it's set/built once per inventory refresh. it ought to re-measure when items are moved
- [ ] find someone with 2 same-class characters and test to see if this works differently if characters share a class
- [x] double check move-aside logic to make sure DIM never causes this (it really shouldn't. it may avoid moving high PL off chars, and pretty sure it avoids moving items to wrong-class chars)

**Comment by bhollis** [comment]
> double check move-aside logic to make sure DIM never causes this

I actually suspect that, given the prioritization in https://github.com/DestinyItemManager/DIM/blob/master/src/app/inventory/item-move-service.ts#L1118-L1154, DIM would move higher-light items onto secondary characters if the vault was full and the primary character was also full.
