### ISSUE TITLE
Separate out completed bounties, group by vanguard/crucible/gambit, and show a count in the header

### ISSUE THREAD

**Issue by slhad** [DestinyItemManager/DIM#8199]
### Proposed change

The goal is to have the number of completed bounties next to the number of current bounties in parenthesis

![DIMCompletedBounties](https://user-images.githubusercontent.com/4113601/159158693-72a405a2-7bd5-4117-bd53-76193aafead2.jpg)

### How does this fit into your workflow?

I am and I know some people that are bounties hoarders, we lose a lot of time counting our number of bounties finished to be sure we have 8 bounties in each Vanguard, Crucible and Gambit to redeem them at the next reset for a nice pile of dust.

And to check it quickly on our 3 characters !

**Comment by slhad** [comment]
I have done a PR illustrating the code change https://github.com/DestinyItemManager/DIM/pull/8198

**Comment by bhollis** [comment]
This only really applies to the Vanguard, Crucible, and Gambit bounties right? I don't think it's appropriate to add this to the "Bounty Guide" which splits things out by all kinds of different properties.

Maybe completed bounties should be separated and have their counts listed out in a separate section?

**Comment by slhad** [comment]
> This only really applies to the Vanguard, Crucible, and Gambit bounties right? I don't think it's appropriate to add this to the "Bounty Guide" which splits things out by all kinds of different properties.
> 
> Maybe completed bounties should be separated and have their counts listed out in a separate section?

Indeed it apply mostly to Vanguard, Crucible, Gambit and Banshee bounties, it is also working on other pills but as less to no meaning (I think)

I was hoping to propose an easy implementation with a on/off switch for users that are aware and understand why there would be a lot of pills.

I am not confident enough to create separate section but that would be a lot better UI wise than too much pills

**Comment by bhollis** [comment]
The real trick here is how to identify what are Vanguard, Crucible, Gambit, and Banshee bounties.
