### ISSUE TITLE
New Ornaments and Record Book Sections

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#820]
https://www.reddit.com/r/DestinyTheGame/comments/4yq0qz/a_look_at_the_all_new_progression_character/

Check to make sure there is no block for DIM to pick this up automatically on Sept 20th.

**Comment by bhollis** [comment]
My guess is it'll just show up as another talent grid item, so we *should* be good to go (once we update manifest, or use the manifest-service code).

**Comment by bhollis** [comment]
#882 should get us there.

**Comment by bhollis** [comment]
Closing in favor of #940 since we definitely support ornaments now.
