### ISSUE TITLE
Test exceptions when loading images from http vs https

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#821]
Google Analytics is showing that there are 6 users with image misses per 1000 users with https with v3.9.2.  I would like to test the endpoint with the http endpoint for image to see if there is any change in the rate.

I want to also add a hash of the membership id to make sure that these are for single users since we restrict the error message to once per hour, but it is also reset when a user hard-refreshes the page.

@bhollis I'm comfortable removing the dim-bungie-image-fallback directive based on the data so far, but I just want to test what it was like before the change to https to just know.

- [ ] Add membership id hash to GA event value & publish update.
- [ ] Gather analytics for exceptions per value for a few days over the work week and weekend to see if there is any flux between home and workplace
    - [ ] per https
    - [ ] per http

**Comment by bhollis** [comment]
Good call. It's worth noting that the error logging will fire for other failures to load the image, too (such as a routine network problem/timeout).

**Comment by bhollis** [comment]
Closing since we dumped the backup images
