### ISSUE TITLE
OAuth Token code references deleted Bungie Help article

### ISSUE THREAD

**Issue by nwLSteam** [DestinyItemManager/DIM#8213]
The initial OAuth token functions (PR https://github.com/DestinyItemManager/DIM/pull/2639) reference a no longer existent Bungie Help article. While I support the notion of linking to a Bungie Help page, the closest thing we have to an official Bungie source now might be [the github.io page](https://bungie-net.github.io/multi/index.html), or even the [GitHub page itself](https://github.com/Bungie-net/api).

https://github.com/DestinyItemManager/DIM/blob/71e19d43e2c975c0096e1b17ee6091c0b7035cea/src/app/bungie-api/oauth-tokens.ts#L26-L27

Clickable defunct link: https://www.bungie.net/en/Help/Article/45481

I'd submit a pull request but I don't know what the DIM team considers to be the next best source.

**Comment by delphiactual** [comment]
https://bungie-net.github.io/multi/index.html#about-security
