### ISSUE TITLE
When sorting vault by item type, show icon for weapon types

### ISSUE THREAD

**Issue by tehtrav** [DestinyItemManager/DIM#8216]
### Proposed change

Much like DIM splits the vault by character type, this idea is to break up the grid in the vault with an icon of each weapon when your primary sort criteria is set to item type. The screenshot below will probably describe it best:

![DIm idea](https://user-images.githubusercontent.com/351975/159330409-bf5b3e1d-6a4a-4984-91af-143148e9e6f3.png)

### How does this fit into your workflow?

This would make it easier to quickly choose an item when your vault is crowded with lots of similar icons.

**Comment by delphiactual** [comment]
Dupe #7206
