### ISSUE TITLE
DIM should automatically recognize the enhanced versions of requested perks

### ISSUE THREAD

**Issue by 48klocs** [DestinyItemManager/DIM#8218]
### Proposed change

With craftable weapons have come enhanced perks.

For example, where there was once one `Overflow` ( https://data.destinysets.com/i/InventoryItem:3643424744 ), now there's also the enhanced version of `Overflow` ( https://data.destinysets.com/i/InventoryItem:2682205016 ).

When reading in a wish list where a user has indicated that they want `Overflow`, DIM should also quietly add in a roll indicating that enhanced `Overflow` is a perfectly acceptable subsitute.

The inverse is not true - if a user has indicated that they want enhanced `Overflow`, DIM should not accept the non-enhanced version.

### How does this fit into your workflow?

Wish lists should quietly work as expected, and folks creating lists shouldn't have to double-check for enhanced perks as they configure their lists.

- [x] Get merged in
- [ ] Update documentation to note that we'll automatically enhance for end users

**Comment by nev-r** [comment]
think we're good on implementation? docs might need update
