### ISSUE TITLE
Loadouts: Cannot fill mods from equipped if everything else is full

### ISSUE THREAD

**Issue by ryan-rushton** [DestinyItemManager/DIM#8219]
### DIM Version

Latest

### Browser Details

Chrome

### OS Details

OSX

### Describe the bug

If a loadout is full with everything except mods you cannot fill mods from equipped.

https://user-images.githubusercontent.com/7344652/159479195-91cddc92-db4f-447f-814e-37361ebc73ff.mov

**Comment by bhollis** [comment]
I don't think that's necessarily new - fill in from unequipped only pulls in mods from newly added items and ignores any slots that already have an item. There's an option in the mods menu called "Sync from equipped" that does what I think you want.
