### ISSUE TITLE
Collection indicator issues

### ISSUE THREAD

**Issue by cxen** [DestinyItemManager/DIM#8226]
### DIM Version

Version 7.9.0 (release), built on 3/21/2022, 3:34:41 AM

### Browser Details

Firefox 98.0.1

### OS Details

Windows 10

### Describe the bug

Some collection items do not have the blue checkmark indicator that they have been unlocked in Collection.

Ada-1 (issue is present)
![image](https://user-images.githubusercontent.com/46993334/159991625-664ec892-5888-40ad-a13e-2347a87e8918.png)

In-game collection completed
![image](https://user-images.githubusercontent.com/46993334/159991753-0a915169-bea6-4caa-a05f-cd4defc53add.png)

Examples of properly tracked items:
![image](https://user-images.githubusercontent.com/46993334/159991801-d1115790-0d13-4b6d-b442-62b77fc21d83.png)
![image](https://user-images.githubusercontent.com/46993334/159991811-45cb39aa-551c-432f-847b-7d9f6cd32b9b.png)

**Comment by delphiactual** [comment]
Dupe #7023
