### ISSUE TITLE
Identify Current Character

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#823]
Add a means to identify which character is the current, or last played, character.

**Comment by SunburnedGoose** [comment]
Added a swatch to the character box for the current user.  The store has a new property, current, that can be used to identify the current store.  I've seen areas in the app where that code was used, but custom made.  We can replace that code with the property.

![screen shot 2016-08-21 at 4 03 15 pm](https://cloud.githubusercontent.com/assets/984608/17839793/cc751820-67b8-11e6-9e6a-8412e58195ae.png)

**Comment by kyleshay** [comment]
#824

**Comment by bhollis** [comment]
PR was merged.
