### ISSUE TITLE
Search displays wrong total while on any locale but english

### ISSUE THREAD

**Issue by stb1rd** [DestinyItemManager/DIM#8230]
### DIM Version

Version 7.9.0 (release), built 21.03.2022, 05:34:41

### Browser Details

Safari 15.4 (17613.1.17.1.6)

### OS Details

macOS Monterey

### Describe the bug

I opened DIM in english language
I searched `tag:junk is:dupelower`
I got total of 47 items
<img width="744" alt="image" src="https://user-images.githubusercontent.com/13750125/160119160-72823192-8f52-410a-b8ba-20fa56d9cd33.png">

I opened DIM in any other language
I searched `tag:junk is:dupelower`
I got total of 1 item
<img width="709" alt="image" src="https://user-images.githubusercontent.com/13750125/160119077-f5548ee5-fe07-4462-8b92-831131a4eda2.png">

**Comment by delphiactual** [comment]
only seems to happen on non-latin based languages... digging further
