### ISSUE TITLE
Remove All in Loadout sections working backwards. 

### ISSUE THREAD

**Issue by AaronC31** [DestinyItemManager/DIM#8235]
### DIM Version

Version 7.9.0.1001565 (beta), built on 3/26/2022, 7:28:18 AM

### Browser Details

Chrome  99.0.4844.82

### OS Details

Windows 10 Pro

### Describe the bug

When clicking Remove All in any of the Weapons/Armor/General loadout sections, it removes everything else instead of just what's in the column like it use to.

**Comment by robojumper** [comment]
Fixed by #8234 on beta.
