### ISSUE TITLE
Avoid CHANGELOG.md conflicts

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#8249]
https://about.gitlab.com/blog/2018/07/03/solving-gitlabs-changelog-conflict-crisis/

https://github.com/PrefectHQ/prefect/pull/2529

**Comment by delphiactual** [comment]
Using these strategies we could have CHANGELOG.md, CHANGELOG_NEXT.md, and changes/####.md.

CHANGELOG.md is for app and is updated whenever a release is published.

CHANGELOG_NEXT.md is for beta, but only has the currently added notes. it requires CHANGELOG.md.

changes/####.md are for unmerged changes which get automatically added to the bottom of CHANGELOG_NEXT.md as merging occurs.

**Comment by bhollis** [comment]
I suppose, though it seems a lot harder than just making sure to update the changelog at some point.

**Comment by delphiactual** [comment]
#8250

**Comment by nev-r** [comment]
i thought i thought of a better idea but turns out it sucked. idk how i feel about this it's very unintitive at first glance.
are you saying i have to make a pr, see what number it comes out, then make a [that number].md?
where does the yaml come into it?

**Comment by delphiactual** [comment]
no yaml needed, and the changes/filename.md does not actually matter bc only one will ever get into master...

**Comment by delphiactual** [comment]
just have the GHA, check the changes directory and cat any files there onto CHANGELOG_NEXT.md. The only problem I can foresee is multiple PRs getting merged simultaneously cancelling a previous run...
