### ISSUE TITLE
Farming mode Wishlist-Locking 

### ISSUE THREAD

**Issue by SentryTheDefiant** [DestinyItemManager/DIM#825]
Feature idea: for farming mode, allow for a scriptable wishlist of items. When an item matching a description on the list is moved to the vault, automatically lock the item. Maybe also notify the user if possible either through chrome system notifications (chrome flag must be enabled?) or just an attention grabbing icon at the top of DIM the next time the user refreshes. 

This idea brought to you by the 10 month wait in year 2 to finally  get a pair of gloves for titan with melee attack speed and auto rifle reloader together that was not exotic, and very nearly deleting them based on low level.

**Comment by bhollis** [comment]
It's definitely a cool idea, but the UI to set up something like that would be pretty gnarly. I think it's more complex than we'd want to do, though I'm receptive to reopening this issue if somebody else wants to take a crack at it.
