### ISSUE TITLE
sheet ui hotzone conflict

### ISSUE THREAD

**Issue by nev-r** [DestinyItemManager/DIM#8258]
it's weird that this point right here counts as close button
![image](https://user-images.githubusercontent.com/68782081/160925994-0567bb80-fc48-4b2f-9377-e3bceebb2999.png)

at least for people who use scroll handles which is apparently only me

**Comment by bhollis** [comment]
I'm not sure why a scrollbar would even appear there. That's not part of the scrollable area. There's also a Firefox-only thing where clicks on scrollbars still propagates to elements under the scrollbars.

**Comment by bhollis** [comment]
What sheet is this?

**Comment by nev-r** [comment]
windows chrome

![2022-03-31_22-13-42](https://user-images.githubusercontent.com/68782081/161199133-53817a91-1da5-49f0-adf7-6e2c5fbcf6bb.gif)

**Comment by nev-r** [comment]
disadvantage being,
![2022-03-31_23-04-24](https://user-images.githubusercontent.com/68782081/161204625-e71380c2-becf-4a6f-825d-f5925ec29710.gif)
