### ISSUE TITLE
there's no changelog for 3.92

### ISSUE THREAD

**Issue by nki2bpz** [DestinyItemManager/DIM#826]
Latest changlelog link goes to 3.83

**Comment by SunburnedGoose** [comment]
We've been keeping it up in the CHANGELOG.md file, but we should go back to making releases in Git.

**Comment by nki2bpz** [comment]
Well either way the link in the popup should link to the current one wherever it is.


-------- Original message --------

**Comment by SunburnedGoose** [comment]
Which popup?

**Comment by nki2bpz** [comment]
Within dim the new version popup gives a short synopsis of the most recent changes and has a link to the changelog to learn more.


-------- Original message --------

**Comment by kyleshay** [comment]
this will auto resolve with the next version bump
