### ISSUE TITLE
Make shaders on weapons part of a loadout?

### ISSUE THREAD

**Issue by scarcry** [DestinyItemManager/DIM#8260]
### Proposed change

Weapon shaders currently are not saved as part of a loadout.
When using the same gun(s) on 2 different loadouts it would be very nice if the applied shader would cross over for each loadout.
Now one has to alter the shader when switching loadouts if one wants a different shader applied.

### How does this fit into your workflow?

I have Fatebringer in my primary kinetic slot with the arctic pearl shader applied for my void loadout (the light side) with my Hunter wearing mostly white skinned armour.
When I switch to my stasis loadout (the darkness side) it would be really nice if my Fatebringer would then rock the bloody tooth shader (mostly black to embrace the darkness .. my stasis Hunter wears very dark skinned armour (amethyst veil shader))

**Comment by bhollis** [comment]
https://github.com/DestinyItemManager/DIM/issues/7460 will accomplish this.
