### ISSUE TITLE
Dim Lag

### ISSUE THREAD

**Issue by SirLethal** [DestinyItemManager/DIM#827]
For some reason, when I start up DIM, it always lags for a few seconds and is fine after a few more. I've done all I know of. Uninstalling chrome, DIM, etc. Even started the beta to see if that was the issue and it wasn't. I can't seem to find a fix. I'm surely not the only one experiencing this problem. Is there any way to fix this or is it a bug in the extension itself? Startup lag is what I'm experiencing. It was fine a few months ago. Since then I've had this problem.

**Comment by ericnelson0** [comment]
Did this start with the latest update?

**Comment by SirLethal** [comment]
No, ive been having this problem for a few months now. Earlier this year, around January it was fine.

**Comment by ericnelson0** [comment]
Any way you could post a gif/video of the lag you are describing? Would be a huge help.

**Comment by SirLethal** [comment]
I'd have to when I get home. Or at least try to. Should be within a couple hours. I'll let you know.

**Comment by kyleshay** [comment]
@SirLethal are you still experiencing issues? Current load time for DIM (for me) is close to 20 seconds. We do need to tackle loading times, but that's a seperate issue and requires a plan entirely on it's own.

**Comment by kyleshay** [comment]
I'm going to close this for now. Feel free to make another report or open. We're always working on seeing where we can make the performance better.
