### ISSUE TITLE
Organize mod picker menu

### ISSUE THREAD

**Issue by insin** [DestinyItemManager/DIM#8275]
### Proposed change

The current Combat Style Mod view sorts mods into Charged With Light/Elemental Wells/Warmind Cells categories.

Since these are at the heart of any build, it might be useful to be able to view combat mods in even more specific categories, e.g.

- Becoming Charged With Light
- While Charged With Light
- Charged With Light Utility
- Spawning Elemental Wells
- Picking Up Elemental Wells
- Elemental Well Utility
- (Warmind Cell mods are all over the place, a few of them would appear in Becoming Charged With Light, though)

I was going to suggest these could appear progressively based on what you've selected, e.g. don't show "While Charged With Light" until you've selected a "Becoming Charged With Light" mod, but other guardians can make you become charged with light, and generate elemental wells and warmind cells you can use, so perhaps that would be a step too far.

Perhaps a semi-guided view like that could be launched from a new "Combat Mods" button alongside "Show Mod Placement". In any case, it would be useful to my workflow to be able to jump straight to Combat Mods from the main loadout view.

(Spitballing ideas a bit here, as this is a good excuse for me to set up DIM for local development to play with it 🙂)

### How does this fit into your workflow?

When putting together a new build from scratch, I usually Create Loadout → Show Mod Placement and click on an empty Combat Style Armor Mod slot to filter down to the initial mods which define the build. This would provide a slightly more guided way to put the main part of a build together from scratch, as the means of obtaining and spending combat style effects are separated.

**Comment by bhollis** [comment]
Agree on having better organization of this menu and some quick navigation/filters between the types.

**Comment by TheGokki** [comment]
![image](https://user-images.githubusercontent.com/87334024/170867129-b4c1a2fe-d8da-4b0f-af82-f3f579fa31c3.png)

The same way we have a folder for each slot, we could have subfolders within for each type of item. In this case: we could have subfolders for each type of mod in the list. This way users could simply do it themselves, adding new subfolders by simply dragging the icons into them, similar to how the Tiles in Windows 10 Start Menu work. All this is saved in user settings so no need for DIM to sort it out.

![image](https://user-images.githubusercontent.com/87334024/170867248-ffbc2824-8323-4c23-bd4d-b1ba500414d6.png)

**Comment by bhollis** [comment]
Closing in favor of discussion in #9304
