### ISSUE TITLE
Be able to clone a loadout or edit and save loadout as new name while preserving original loadout.

### ISSUE THREAD

**Issue by wickedshrapnel** [DestinyItemManager/DIM#8277]
### Proposed change

Add a clone button next to Apply Edit Share Loadout buttons in the main Loadouts view. 
or when editing a loadout allow to "save as" to save it as a new loadout and preserve the original loadout.

### How does this fit into your workflow?

I often want to have multiple loadouts with some of the same items. I want to build off current loadouts and just make the changes I need like changing weapons and mods and saving as a new loadout.

**Comment by robojumper** [comment]
Have you tried editing a loadout, entering a different name, and pressing "save as new"?

**Comment by wickedshrapnel** [comment]
Wow! You added that feature fast! Glad I could help. lol j/k. Thanks for the tip.
