### ISSUE TITLE
When opening a shared DIM loadout build show which elements the armor is in the original build.

### ISSUE THREAD

**Issue by wickedshrapnel** [DestinyItemManager/DIM#8278]
### Proposed change

When you open a shared DIM link it shows all the armor dimmed out and doesn't show if the armor is solar, arc, void, etc. The mods in the build often need to go into certain element armor. If you know all the mods and where they go you can figure it out but it would be a lot easier to just show what the original builder used. solar helmet, void gauntlets, arc chest piece, etc. So when you click on that item you can choose the correct element for that piece of armor.

### How does this fit into your workflow?

I like to test out a lot of different builds the community shares and it would make life easier to know what elements of armor where used in the original builds.

**Comment by robojumper** [comment]
Shared loadouts don't contain this information. A scheme to provide extra information to instanced items in shared loadouts would probably be helpful (weapon perks?) but for mods in particular we have Loadout Optimizer, which will assemble an armor set that can fit all those mods.

Right now you could drop the missing armor from the loadout and save it, click "Optimize Armor", let Loadout Optimizer present you with sets that could fit all these mods, and add the armor to that loadout by clicking "Compare".

**Comment by bhollis** [comment]
That's right, the intention is to use Loadout Optimizer to find armor that fits the mods saved on the loadout.
