### ISSUE TITLE
Wishlist render in armory view sometimes repeating picks

### ISSUE THREAD

**Issue by 48klocs** [DestinyItemManager/DIM#8288]
### DIM Version

current

### Browser Details

?

### OS Details

?

### Describe the bug

https://twitter.com/Mark_Almighty/status/1511197511544983557?s=20&t=zMFIgzH4Z4p5MYLysYsdpw is a report of the perk combo collapser acting up.

I also got a report over on Discord of roughly the same - https://github.com/Adamsdown-Boy/destiny-rolls/blob/main/player-versus-enemies-rolls/ep8-witch-queen-dlc-weapons.txt is showing more combinations in the wish list preview renderer than it should.

https://media.discordapp.net/attachments/894601018585776188/960951699994992681/unknown.png?width=1664&height=936

These are both cases where only a couple of sockets have desirable traits in them.

**Comment by nev-r** [comment]
fixed innnnnn https://github.com/DestinyItemManager/DIM/pull/8329 ?
