### ISSUE TITLE
Auto-disable farming mode

### ISSUE THREAD

**Issue by hendersj** [DestinyItemManager/DIM#8289]
### Proposed change

Provide a configuration to auto-disable farming mode after a period of user inactivity in DIM.

Alternatively, if it's possible to query if the player is actively playing, use that "in-game" state rather than a timer.

### How does this fit into your workflow?

I usually play D2 in the evening, with DIM running on a separate monitor.  I often will run playlist activities, and let DIM keep a space free in my character inventory so I can pick up stuff as it drops, and I will tag items in the new "Item Feed" so I can clean things up later.

Sometimes I forget to disable farming mode when I'm done playing - which means (I believe) that DIM is constantly hitting the API overnight unnecessarily.

If an 'inactivity timer' (defined as 'lack of user interaction with DIM') were implemented, these extraneous API calls could be limited.  Since different people would interact differently, letting the user configure a timer would allow for different play styles to adapt.

If it were implemented using a query to see if the user was active in the game, and farming mode wasn't able to be enabled if they weren't, that would also provide a configuration-less way of accomplishing the goal.

**Comment by bhollis** [comment]
Included in #7263
