### ISSUE TITLE
Filter Suggestion: is:hasmemento

### ISSUE THREAD

**Issue by mattsigal** [DestinyItemManager/DIM#8298]
With mementos now a thing, it would be great to see at a glance which weapons have a memento equipped. I suggest the filter is:hasmemento to quickly see which weapons have a trials/gambit/vanguard memento equippped.

**Comment by robojumper** [comment]
In the meantime you can use `"rare curio"` to find these.

**Comment by nev-r** [comment]
closed in https://github.com/DestinyItemManager/DIM/pull/8301
