### ISSUE TITLE
DIM sometimes ends up without the extended GetProfile call

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#8299]
### DIM Version

Current beta

### Browser Details

Chrome

### OS Details

Windows 10

### Describe the bug

Today's beta update changed how weapon level is shown in the weapon screen. They now all show 0% rather than the weapon level.

![image](https://user-images.githubusercontent.com/25425159/162568923-1cc2d86b-271b-411c-9ae9-65564e67ef3e.png)

Also means that the weaponlevel: filter no longer works.

**Comment by robojumper** [comment]
Try hitting [R] or the refresh button when that happens, I think it's just that DIM is using the initial reduced API results necessary to show the inventory and didn't get the extended info with all the details like weapon level.

**Comment by philkernick** [comment]
Ok that fixed it.  Is there some way we can indicate this in the UI?

**Comment by philkernick** [comment]
It's doing permanently since reset.  No weapons are showing their weapon level.  Trying full reload and even loading DIM on an iPad.

**Comment by robojumper** [comment]
That's a different bug, see https://github.com/Bungie-net/api/issues/1650, which will be fixed by next Tuesday (2022-04-26).
