### ISSUE TITLE
Automated loadouts should check faction alignment before selecting exotic faction class items

### ISSUE THREAD

**Issue by cowgod** [DestinyItemManager/DIM#830]
Selecting automated loadouts such as "Item Leveling" tries to equip a faction class item, but fails because my character is not aligned with that particular faction. The loadout selection code should consider a character's faction before choosing an exotic faction class item for an automated loadout.

![screen shot 2016-08-24 at 3 25 58 pm](https://cloud.githubusercontent.com/assets/523086/17944797/2cbc6514-6a0f-11e6-8dfb-1fed4da399c7.png)

**Comment by bhollis** [comment]
Good catch! I don't have any of the exotic faction items so I'd never seen these, and I didn't realize they required faction alignment. Frustratingly I'm not sure that requirement is stated anywhere in the item. I think I can come up with a fix though.

**Comment by SunburnedGoose** [comment]
We have a node that we can go off of for each faction...  Would have to hardcode them though.

![screen shot 2016-09-04 at 7 33 42 pm](https://cloud.githubusercontent.com/assets/984608/18234852/877ca926-72d6-11e6-8a5f-42801540e373.png)

**Comment by bhollis** [comment]
That's not so bad. I can probably make that happen.

**Comment by delphiactual** [comment]
Faction | Node Name | Node Hash
--------|---------------|---------------
New Monarchy | Vanquisher | 652505621
FWC | Gladiator | 2669659850
Dead Orbit | Pathfinder | 2794386410

**Comment by bhollis** [comment]
Wonderful, thank you!
