### ISSUE TITLE
Feature request: Vendor armour pieces that haven't been purchased yet being available to use in the loadout optimizer

### ISSUE THREAD

**Issue by 32423d** [DestinyItemManager/DIM#8302]
### Proposed change

Vendor item pieces that haven't been purchased yet should be available to be used in the loadout optimizer. They can have some special tag to the icon of the armour pieces in the loadout optimizer indicating that they are from vendors and haven't been purchased yet.

### How does this fit into your workflow?

Adding this feature will make it so it will be easier to see if buying an armour piece from a vendor will be worth it by seeing if you can create a loadout with your desired stat distribution with it before purchasing it in game.

**Comment by delphiactual** [comment]
dupe #6878
