### ISSUE TITLE
Automated loadout builder tries to equip exotic when another exotic is already equipped

### ISSUE THREAD

**Issue by cowgod** [DestinyItemManager/DIM#831]
When selecting the "Item Leveling" automated loadout, it selects an exotic primary to equip (No Land Beyond, in this case) although my character currently has a (fully-leveled) exotic already equipped (Truth, in this case). I have no heavy weapons that aren't fully leveled, so it wasn't able to select something else to put in that slot.

If a fully-leveled exotic is equipped, and no unleveled items are found for that slot, and the builder wants to equip an unleveled exotic in another slot, it should equip a legendary in the slot of the existing exotic, to allow the other, unleveled exotic item to be equipped.

![screen shot 2016-08-24 at 3 26 33 pm](https://cloud.githubusercontent.com/assets/523086/17944972/d8747810-6a0f-11e6-87c7-9784f5fc24e4.png)

(Disregard the other error message, about Cloak of the Rising -- I opened a separate issue for that bug).

**Comment by bhollis** [comment]
Great catch!
