### ISSUE TITLE
Invalid SSL certs. 

### ISSUE THREAD

**Issue by bigblev** [DestinyItemManager/DIM#8315]
### DIM Version

7.12.0 (2022-04-10)

### Browser Details

Chrome Version 100.0.4896.88 (Official Build) (x86_64)

### OS Details

Mac OS 12.3.1 (21E258)

### Describe the bug

Hello, 

Getting this error from multiple web sites serving DIM links. 

"Error 526 Ray ID: 6fbd0e213e767ac5 • 2022-04-14 14:15:43 UTC
Invalid SSL certificate"

Not sure who is issuing your certs but they look overloaded.

**Comment by bhollis** [comment]
Upgraded/fixed cert issuer
