### ISSUE TITLE
Loading loadout while in mission

### ISSUE THREAD

**Issue by Korben85** [DestinyItemManager/DIM#832]
Hi all,
why is it not possible to load an loadout while in a mission? Other managers can do that. F.e.Tower Ghost for Destiny
It would be nice if you could at this in the future.

Unfortunately I'm not used to Angular, but I'm learning right now to contribute to this project in the future.

Regards,
Thomas

**Comment by SunburnedGoose** [comment]
There is no way to equip a loadout while you're playing in a darkness zone or crucible play.  Limitation from Bungie.  No other manager can do that. POIDH :)

**Comment by Korben85** [comment]
Tried it now myself. You'r fully right.
Sorry for misunderstanding, a friend suggested that it is possible, he mend just the transfer, which of course is possible in DIM :smile:.

**Comment by SunburnedGoose** [comment]
GG's :)
