### ISSUE TITLE
Random rolled vendor items interact badly with wish list cache?

### ISSUE THREAD

**Issue by robojumper** [DestinyItemManager/DIM#8327]
This was posted to the Discord shortly after a daily reset:

![screenshot](https://cdn.discordapp.com/attachments/518872098522005534/964574418347118632/unknown.png)  
(a gun has thumbs up icons on some perks but not others, the roll appears incomplete)

This needs some investigation, but I think this is because wish list rolls are cached by item ID internally: https://github.com/DestinyItemManager/DIM/blob/ea8fee4686ff543da7f865a2455a608c92714794/src/app/wishlists/selectors.ts#L32-L40

but vendor items never take these randomly rolled perks into account when generating a fake ID

https://github.com/DestinyItemManager/DIM/blob/ea8fee4686ff543da7f865a2455a608c92714794/src/app/vendors/vendor-item.ts#L170-L172

so the internal cache is just inconsistent if the perks change. Maybe the plugs in randomized vendor items should be hashed and included in the ID too?

**Comment by bhollis** [comment]
Or maybe we can append the vendor's last update time, if that's a property?
