### ISSUE TITLE
Materials management macros

### ISSUE THREAD

**Issue by SentryTheDefiant** [DestinyItemManager/DIM#833]
Any chances there are plans for a button or section of buttons to allow for splitting all or sections of materials at once? Perhaps a move all chroma to vault.  

Maybe a way to edit preferential treatment of certain characters when splitting stacks, maybe so your main always has 40-50% and other characters split what's left. 

Perhaps this could be incorporated into improved features of the farming mode, for instance active character automatically gets rep boosters, three of coins and a healthy amount of synths periodically transferred/split.

**Comment by SunburnedGoose** [comment]
atm, you can search for chroma, and use the loadout feature to move all searched items to the vault.

**Comment by SentryTheDefiant** [comment]
Good point, but non even splits, and across the board mats splits would still be super useful. 

Also, can we add an option to farming mode that puts trinkets like house banners and silken codex right in the vault?

**Comment by bhollis** [comment]
I can imagine how we'd present a UI for something like non-even splits, but I'm not sure it's worth the increased complexity in the app.

**Comment by kyleshay** [comment]
somewhat related to #967

**Comment by bhollis** [comment]
I'd like to vote this as "wontfix" - I don't see how we'd present non-even splits, and we have even split mode already.

**Comment by kyleshay** [comment]
Eventually, we might support this type of a feature in a smarter version of our loadout system. 

Currently, you could create a loadout that moves X number of materials.

> Also, can we add an option to farming mode that puts trinkets like house banners and silken codex right in the vault?

FYI - that is done now
