### ISSUE TITLE
An improvement in armor mod placement

### ISSUE THREAD

**Issue by hh393** [DestinyItemManager/DIM#8332]
### Proposed change

One of common usage of mod changing is weapon ammo finder and scavenger. I like to create a loadout called "rocket launcher" to equip rocket launcher ammo finder and scavenger in my armor. But there is 2 slots for these mods. I like to assign special weapon mods to first slot and heavy weapon mods to second slot. So a can easily equip whatever I need before an activity. But you NEED to add an option so we can specify mod location (slot 1 or 2). It is a better approach to let user have control over mod location. Many similar use cases can be managed if we have control over mod location. But I think automatically deciding for us where to put mods is not helpful.

### How does this fit into your workflow?

Above ...

**Comment by bhollis** [comment]
We don't NEED to do anything, but manual mod placement is on the roadmap: #7421
