### ISSUE TITLE
Weapon Level of all crafted weapons are permantly 0%

### ISSUE THREAD

**Issue by xuanhieu1479** [DestinyItemManager/DIM#8338]
### DIM Version

7.13.0

### Browser Details

Chrome 100.0.4896.127

### OS Details

Windows 10

### Describe the bug

For now all the crafted weapon stuck with 0% weapon level process.

Also not related but completed attunement weapons used to have a "!" on their icon, now they only show red border same as uncompleted ones.

**Comment by delphiactual** [comment]
https://github.com/Bungie-net/api/issues/1650
