### ISSUE TITLE
Linux/Ubuntu Desktop Application 

### ISSUE THREAD

**Issue by HannaSamia** [DestinyItemManager/DIM#8340]
### Proposed change

Any plans on releasing desktop version of DIM to the Linux users?

### How does this fit into your workflow?

Linux's user are increasing fast, and I just switched from windows to Pop_os.
And really wants a dim application.

I know we can use the browser version, but a full-blown application is nicer.

**Comment by delphiactual** [comment]
The Desktop App for Windows/Mac is just a PWA shortcut

**Comment by bhollis** [comment]
https://destinyitemmanager.fandom.com/wiki/Desktop_and_Mobile_Apps
