### ISSUE TITLE
move applyRandomLoadout out of dimAppCtrl.controller.js

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#836]
we should clean up dimAppCtrl... the random loadout logic should eventually move to it's own file

also should support the 'revert loadout' or 'before random'

maybe consider moving the logic to where we do the max-light loadout to reuse and get some additional logic for free.

**Comment by SunburnedGoose** [comment]
Absolutely agree. Just a quick hack for a friend.
