### ISSUE TITLE
Kinetic Scoutrifle Perses-D is not considered "kinetic"

### ISSUE THREAD

**Issue by timcoots** [DestinyItemManager/DIM#8366]
### DIM Version

Version 7.16.1.1001687 (beta), built on 5/10/2022, 10:52:08 AM

### Browser Details

Brave Version 1.38.115 Chromium: 101.0.4951.64 (Official Build) (64-bit)

### OS Details

Windows 10

### Describe the bug

"is:scoutrifle is:kinetic" will de-select Perses-D.

Perses-D is both of those attributes.

**Comment by bhollis** [comment]
It's stasis, not kinetic

**Comment by delphiactual** [comment]
`is:kineticslot`
