### ISSUE TITLE
re-enable crafting tooltips, sort of

### ISSUE THREAD

**Issue by nev-r** [DestinyItemManager/DIM#8386]
#7950 filtered out attunement/pattern tooltips, and ought to be un-done,
**but** attunement tooltips are noisy and redundant.
we should use d2ai to filter to only show the "pattern can be extracted" tooltip, which currently has no representation in DIM, and is useful to call out

**Comment by bhollis** [comment]
I decided the tooltips didn't add anything while adding pattern unlock info - I think we can leave these until there's a tooltip we really want to show.
