### ISSUE TITLE
Add a filter for items with enhanced perks

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#8387]
### Proposed change

There is currently no reliable way to search for crafted weapons that have enhanced perks.

perkname:enhanced

This doesn't work as expected, as some weapons have an "enhanced intrinsic" frame, and there is already the perk "enhanced battery", both of which are matched by the filter, and neither of which have anything to do with crafted enhanced perks.

Proposal:

is:enhancedperk              matches if the weapon has a craftable enhanced perk

There is also a reasonable usecase to determine how many enhanced perks a weapon has (0, 1, 2) using the standard numerical comparison operators

enhancedperk:=1
enhancedperk:=2
enhancedperk:>=1

### How does this fit into your workflow?

The workflow for this is: I have an Ascendant Alloy, where should I use it?

is:crafted -is:enhancedperk is:legendary weaponlevel:>=7

is:crafted enhancedperk:<2 is:legendary weaponlevel:>=13

Currently the only way to do this is to mouse over every single crafted weapon and manually work out where you can craft a new enhanced perk.

**Comment by brootroot** [comment]
@philkernick What occurs if either is:enhancedperk or is:weaponlevel are applied without is:crafted? Would is:crafted just be intrinsically part of those filters?
