### ISSUE TITLE
Create constants for classType values

### ISSUE THREAD

**Issue by yannickguillemot** [DestinyItemManager/DIM#839]
It'd be useful to define constants for values that tend not to be modified at all in the future. For instance, in the load-out logic layers, I see a lot of classType values (any = -1, warlock = 0,..) being explicitly set, exposing the codebase to typos and subsequent bugs.

I propose to have a new constants directory. One file for classTypes that would look like this:

```
angular.constant('CLASS_TYPES', {
  'ANY': -1,
  'WARLOCK': 0,
  'TITAN': 1,
  'HUNTER': 2
})
```

Of course, that would impose to migrate all current class types values to use those constants.

**Comment by SunburnedGoose** [comment]
angular.constant('CLASS_TYPES', {
  'ANY': -1,
  'WARLOCK': 0,
  'TITAN': 1,
  'HUNTER': 2,
  '-1': 'ANY',
  '0': 'WARLOCK',
  '1': 'TITAN',
  '2': 'HUNTER',
})

**Comment by yannickguillemot** [comment]
If you need the string version, I think lodash has a [helper](https://lodash.com/docs#invert) for that.

`_.invert(CLASS_TYPES)[-1]`

**Comment by SunburnedGoose** [comment]
I don't want a helper...  I just want to do it :)  You'll find that they are used interchangeably often within the code so it is easier to have both if we walk this route rather than hunt for references and determine if they need the lodash helper.

**Comment by yannickguillemot** [comment]
I was just worried with redundancy.

**Comment by SunburnedGoose** [comment]
We can handle it in one place with some redundancy, or have helpers throughout the code...  I'd rather just deal with it in one place.

**Comment by bhollis** [comment]
This is a good idea, but I'd like to close the issue in favor of a future PR whenever somebody gets inspired to actually make the change (or lack of the change becomes a problem for the codebase).
