### ISSUE TITLE
Reward Amount (XP, bright dust, vendor progress)

### ISSUE THREAD

**Issue by Revadike** [DestinyItemManager/DIM#8396]
### Proposed change

Similarly to how DIM displayed the exact expiry time of bounties, I would love it if DIM would display the exact reward amount. 

For example:
![image](https://user-images.githubusercontent.com/4411977/169946172-ec2ce49c-1ee7-408b-8582-7d962a1d3134.png)

### How does this fit into your workflow?

It allows you to make more informed choices on what goals to focus on.

**Comment by bhollis** [comment]
A great idea, but there's no way to determine that XP amount automatically - the Destiny API doesn't include that information. We'd need to manually build a mapping from every bounty/quest/milestone to its XP value, and keep that up to date.

**Comment by Revadike** [comment]
> A great idea, but there's no way to determine that XP amount automatically - the Destiny API doesn't include that information. We'd need to manually build a mapping from every bounty/quest/milestone to its XP value, and keep that up to date.

What about just for bright dust, for now?
