### ISSUE TITLE
Tooltip hitboxes of square plugs with season watermark are wonky

### ISSUE THREAD

**Issue by robojumper** [DestinyItemManager/DIM#8399]
This is the hitbox of the ornament plug tooltip:

![image](https://user-images.githubusercontent.com/14299449/170026227-1af4d85b-8b1a-47d5-80a3-3f8d4043925c.png)

The entire highlighted area (except for where it overlaps with the mod on the right) triggers the presstip, particularly the half below the weapon mod, which is weird. This happens to all plugs with season watermarks -- shaders, transmat effects, ornaments, ghost projections, emotes.

**Comment by bhollis** [comment]
I think this was fixed - you can see that the overlay itself is too big. I don't see that anywhere now.
