### ISSUE TITLE
Add weapon tag for deepsight resonance and pattern concerns

### ISSUE THREAD

**Issue by matthewlehew** [DestinyItemManager/DIM#8410]
### Proposed change

I'd like to see a tag alongside the Favorite/Keep/Infuse/Etc. tags that help denote items being kept for crafting purposes. This is a unique suggestion that stems from some of the same concerns discussed in #8176, especially concerns with tracking deepsight weapons that should be prioritized for resonance extraction because the patterns are not yet unlocked. 

A possible tag name would simply be "Deepsight".

### How does this fit into your workflow?

Other issues have suggested filters for isolating deepsight weapons and, very helpfully, deepsight weapons whose patterns have not yet been unlocked. This helps with these concerns by giving the user manual control over designating the weapons whose resonance needs to be extracted. 

Currently, I save deepsight weapons I would otherwise discard with the "Infuse" tag. But this messes up some of my existing queries, especially since some deepsight weapons may be good infusion material but shouldn't be prioritized for resonance extraction since the pattern is already unlocked. 

With this feature, I can add the "Deepsight" tag to weapons I am vaulting for the specific purpose of eventually extracting resonance, whether it be for pattern unlocking or simply farming the material. If I need to make vault space I know I can delete some of these without deleting anything useful for gameplay or infusion.

**Comment by bhollis** [comment]
We probably won't add a tag for this. We plan on adding searches to match items that have patterns that aren't unlocked instead.
