### ISSUE TITLE
Solar abilties have Stasis coloring in Loadouts

### ISSUE THREAD

**Issue by jakenorris1124** [DestinyItemManager/DIM#8421]
### DIM Version

Version 7.18.1 Orange

### Browser Details

Firefox Nightly 102.0a1

### OS Details

Windows 10

### Describe the bug

Under the loadouts tab, some Solar abilities have Stasis colors as seen in this [screenshot](https://i.imgur.com/jxjeiXy.png).

**Comment by robojumper** [comment]
Behaves the same way in the Companion App and Bungie is [likely aware](https://www.bungie.net/en/Explore/Detail/News/51392):

> Solar icons for class abilities, melees, and movement have blue backgrounds when viewed from Ikora's inventory.
