### ISSUE TITLE
Mobile App does not display legendary shard count outside the vendor tab

### ISSUE THREAD

**Issue by Fading-Shadow** [DestinyItemManager/DIM#8431]
### DIM Version

7.18.1

### Browser Details

Mobile app

### OS Details

Android 11

### Describe the bug

Same as the title. Legendary shard counts are nowhere to be found on mobile. Or if they are somewhere, I haven't been able to come even close to finding them.
![IMG_20220528_073209](https://user-images.githubusercontent.com/94243772/170811703-980d6d7f-e622-4e9d-9c6a-9f9df758fcac.jpg)

**Comment by Fading-Shadow** [comment]
Update: you can view it at certain vendors where that currency is relevant but I don't think that's the ideal way of going about it.

**Comment by bhollis** [comment]
It's a bit weird but the currencies only show when you select "armor" on the strip at the bottom. This is because it's the same portion of the UI that shows per-character stats. They should definitely at least be included in the material counts popup.

**Comment by Fading-Shadow** [comment]
Ah ty, that works. Still very inconvenient but at least that's a thing.

**Comment by bhollis** [comment]
Yeah it definitely could be better. I hadn't noticed because I've been playing so long I never have to worry about how many legendary shards I have.

**Comment by Fading-Shadow** [comment]
Yea I only wanted to look at it because I wanted to take a screenshot of how many I got from farming the bug. It's not a deal breaker just a minor inconvenience pretty much.
