### ISSUE TITLE
Option to remove Seasonal Insignias on items

### ISSUE THREAD

**Issue by TheGokki** [DestinyItemManager/DIM#8434]
### Proposed change

![image](https://user-images.githubusercontent.com/87334024/170864837-9ec9d130-c281-4bd1-94ef-04f55dc1e59d.png)

Option to remove those triangle corner symbons for a cleaner look.
Separate option for sunset items i guess.

Should be good for it to fit between these two, similar to that posmaster toggle:

![image](https://user-images.githubusercontent.com/87334024/170865002-89ad214e-1317-4baf-b86e-f9570435b587.png)

### How does this fit into your workflow?

A simpler, cleaner look makes it easier and faster to identify items by revealing more of the item itself.

**Comment by delphiactual** [comment]
Those are part of the icon from bungie
