### ISSUE TITLE
Vault Overflow...

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#844]
This only seems to occur when you only have 1 guardian

Changing Character Inventory Columns to 5 causes a weird problem on the right edge of the screen...

![overflow](https://cloud.githubusercontent.com/assets/4798491/18214644/412da8b6-710b-11e6-88da-ba8361246cdd.gif)

**Comment by delphiactual** [comment]
Also does this with 2 guardians...

**Comment by bhollis** [comment]
Hmm, I'm unable to reproduce, but I also have nearly-full vaults. Could that be related?

**Comment by delphiactual** [comment]
Steps to reproduce: 

Character Inventory Column: 5
Item Size: `Reset to Default`

Does it with both account, mine has nearly full vault as well

**Comment by bhollis** [comment]
I haven't been able to repro it on my laptop screen, but 5 columns takes up a ton of space there. I'll have to try it on a bigger monitor later.

**Comment by bhollis** [comment]
I haven't been able to reproduce this with any size screen, item size, and combination of character and vault columns. Any tips?

**Comment by delphiactual** [comment]
My laptop resolution is `1366x768`

**Comment by bhollis** [comment]
At that resolution, at 5 columns, I do push the vault off the screen with 3 characters.

**Comment by bhollis** [comment]
OK, I can reproduce. The problem doesn't happen with 3 characters.

**Comment by bhollis** [comment]
Check out #1001 and see if it helps.

**Comment by delphiactual** [comment]
nope, still offscreen
![screenshot 2016-10-01 14 15 52](https://cloud.githubusercontent.com/assets/4798491/19016793/ca78cc80-87e1-11e6-89d8-9d4b6f0dbede.png)

**Comment by bhollis** [comment]
That's not the same bug. That's just the display being configured wider than your screen - you can't have 3 characters plus the vault at 5 items wide fit on that screen.

**Comment by delphiactual** [comment]
True, but vault is set to auto; which should make the vault 4 items wide...

**Comment by bhollis** [comment]
The vault can never be smaller than a single character so when you set
characters to 5 it'll be that wide.

**Comment by delphiactual** [comment]
That makes sense.
