### ISSUE TITLE
Masks and engrams are included in the maxpower filter

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#8444]
Current beta, Chrome on Windows 10.

Using the is:maxpower filter I've found two items that as highlighted, but are definitely not maxpower.

1. Glitterball Festival of the Lost mask.
2. Every Umbral engram in a character inventory at 1560.

**Comment by nev-r** [comment]
masks don't identify themselves as helmets in any way, so they are the "max" within their own category of item. same with umbrals which cannot be directly compared to any distinct armor piece or weapon. so this is an expected quirk and not worth doing battle with unless you're experiencing a negative effect from it, allows people... i guess..... to find their highest engram?

**Comment by delphiactual** [comment]
#8521 should fix the problem with masks

**Comment by njrardin** [comment]
It may make sense to allow the maxpower filter to highlight engrams if they're the max power overall (for example it's an engram of LL 1670 and you only have things 1669 or below) or if it's an engram that has a possibility of decrypting into something that elevates the max light level, but that's just a thought.
