### ISSUE TITLE
Equipped a loadout now my character is bugged

### ISSUE THREAD

**Issue by jbashepperd** [DestinyItemManager/DIM#8445]
### DIM Version

Orange

### Browser Details

Chrome

### OS Details

Windows 10

### Describe the bug

Swapped loadouts in a vow run and now I get kicked for error code plum every 10 mins. Also reset my witch queen progress.

**Comment by bhollis** [comment]
Unfortunately this is beyond DIM's ability to diagnose - please reach out to Bungie Help.
