### ISSUE TITLE
incorrect error message "you may not be connected to the Internet"

### ISSUE THREAD

**Issue by tomperrine** [DestinyItemManager/DIM#845]
This seems to be happening for "API timeout" when the Bungie API servers are too slow to respond. I know I'm connected to the 'net, and I can see the requests to the server, but no responses (in Wireshark) 

Could/should this error message be (in more user friendly terms):

"Bungie server not responding" might be more useful?

**Comment by bhollis** [comment]
I'm not sure we can easily distinguish between the two, but we've really improved error handling as of the latest Beta, so hopefully this is taken care of.
