### ISSUE TITLE
Did any calculations change?

### ISSUE THREAD

**Issue by UNIcodeX** [DestinyItemManager/DIM#8451]
### DIM Version

7.20

### Browser Details

Vivaldi (Chrome modded latest)

### OS Details

Windows 10

### Describe the bug

I have some loadouts which were saved as T34 but are now showing up as T28. The individual stats are showing differently as well. Resilience was at 10 and now it's at 9.

I think the issue is coming in with the calculation of void fragment buffs. I have echos of expulsion (+10 intellect), leeching (+10 resilience), dilation (+10 mobility and intellect), obscurity (+10 recovery) equipped.

Could you shed some light on what's going on here? Is this a bug or is this a fix for a bug?

![image](https://user-images.githubusercontent.com/8235002/172251518-26adc387-c6bd-4b16-97e4-ba20c658b9a4.png)

Thanks!!

**Comment by robojumper** [comment]
Your armor is not masterworked. Masterworking all pieces gives you a bonus tier in each stat, so the numbers would add up to T28+6=T34.

You did not share all Loadout Optimizer settings, but try clicking the "Assume Masterworked: All" option. Note that you'd have to follow through and actually masterwork those pieces to hit these stats.

**Comment by UNIcodeX** [comment]
that could be it. although I don't remember having selected assume masterworked for that session, however... it's possible.
