### ISSUE TITLE
Add auto tag to farming mode for easier loot sorting.

### ISSUE THREAD

**Issue by BuffMcMuff** [DestinyItemManager/DIM#8454]
### Proposed change

Add an option to automatically tag new items that farming mode moves to your vault so you can more easily sort through them. Maybe add specific tag for this feature.

### How does this fit into your workflow?

This change would improve the efficiency of sorting through new loot as browsing the item feed after a long session can cumbersome and you may easily miss some items. 

Helps specifically to spot new loot at a glance of the vault and helps to search through items with the use of tags.

**Comment by BuffMcMuff** [comment]
I find that if you end up farming same activity for a while, lets say the new dungeon you end up with **a lot** of the same items. Armor especially is a problem as it can be difficult to distinguish between armors you've kept from before and haven't upgraded yet but forgot to tag, from new armor's that the farming mode has sent to the vault.

An _option_  for farming mode tag would make it easier to sort through new items in bulk with the use of search filters and mass tagging.

I find the item feed a tad cumbersome for armor since it can be hard to quickly evaluate the total stat spread of an item by just looking at the numbers since the game makes you get used to seeing the bars in addition to the numbers.

I think it should also be noted that this is only a sizeable problem in my experience during long farming sessions where you end up with a lot of items or if you forget to go through your new items semi-regularly.

**Comment by bhollis** [comment]
You might find it helpful to turn on the "new item dot" or use the `is:new` search as well. At the end of the day, the tools we have for determining which armor to keep are the Compare tool, Organizer, Loadout Optimizer, and search (see https://github.com/TMMania/Vault-Analyzer)

**Comment by BuffMcMuff** [comment]
I did not see the new item dot was a thing even tough I thought that I went over all the option semi-thoroughly. That and the tools above should alleviate most of my problems. Thanks for the help and discussion.
