### ISSUE TITLE
Ignore items in General (Ships/Sparrows/Ghosts/Emblem)

### ISSUE THREAD

**Issue by victor6267** [DestinyItemManager/DIM#8456]
### Proposed change

Could a toggle be added in the settings so that any builds saved auto removes the items in the General section (Ships/Sparrows/Ghosts/Emblem) from the build you are about to save?

### How does this fit into your workflow?

Most of the time I completely ignore what is in the general section when build crafting and having this toggle would be a nice QoL feature.

**Comment by bhollis** [comment]
There's a quick menu item that lets you remove everything in a section:
<img width="318" alt="image" src="https://user-images.githubusercontent.com/313208/172746111-3ef5cc56-18f3-4a87-97ac-d634e4f1a093.png">
