### ISSUE TITLE
Add Level Requirement for Items to Popup Menu

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#846]
I've got a level 2 and and level 5 character on Playstation and they need to know what they can equip.  It would be useful to show that detail in the popup and give a search filter to show these items.

**Comment by kyleshay** [comment]
hmm. we currently have (for example) `level:<=value` but level is an alias for `light:<=value`... should fix that as part of this.

**Comment by SunburnedGoose** [comment]
They wanted it in the popup somehow similar to the attributes and details.

**Comment by kyleshay** [comment]
How would we show the detail in the popup? 

Something like:
> This item can not be equipped on your level 2 Exo Male Warlock or level 7 Exo Female Warlock

**Comment by SunburnedGoose** [comment]
This has the level info in the detail screen.

![screen shot 2016-09-06 at 12 05 29 pm](https://cloud.githubusercontent.com/assets/984608/18283310/3ea5ee7e-742a-11e6-88dd-ee5cd03625ff.png)

**Comment by kyleshay** [comment]
Buy that's on your current character... DIM popup is for up to 3 characters, some who might me level 40, others level 2.

**Comment by kyleshay** [comment]
Ah, I see what your saying. Just show the level needed. nevermind 📦

**Comment by bhollis** [comment]
Do we really want to bother? Level requirement isn't relevant after a few days' play, and we don't have a ton of free space in the popup.

**Comment by bhollis** [comment]
So, do we want to do this, or should we just tell people to level up ;-)

**Comment by kyleshay** [comment]
Since we're blocking the action to move it to characters that are under-leveled anyway... To me, that seems to be the best way to implement this. Since the popup is shared between the 3 characters, it can't quite match the destiny UX exactly.
