### ISSUE TITLE
item popup not choosing a great place to pop up

### ISSUE THREAD

**Issue by nev-r** [DestinyItemManager/DIM#8461]
i think this is a regression? chrome + firefox, when i click an icon tile near the very bottom, the item popup ust gives up and sticks off the bottom. there's a bunch of space above it that it could use, but it doesn't.

the entire move/equip sections are offscreen here
![image](https://user-images.githubusercontent.com/68782081/173020263-156db532-2a80-4108-8059-0109a4b67eeb.png)

**Comment by bhollis** [comment]
Definitely seems like a regression - maybe it's measuring the container element incorrectly (or not getting it set in the first place). Linking #8374

**Comment by bhollis** [comment]
Actually 99% sure it's related to my change to position the sidecar with a popper plugin. I'll fix.
