### ISSUE TITLE
Tagging items doesn't re-sort them immediately

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#8463]
I'm noticing that updating the tag on items isn't causing them to re-sort in the inventory grid until the next data refresh, even though tag is my primary sort. It's supposed to update immediately. I wonder if we're over-memoizing somewhere.

**Comment by nev-r** [comment]
even weirder it reorders as soon as you hit refresh button, but before the api call actually even completes.
so it's interesting to me that the state of things is changed enough by that, to cause an inventory re-render.
