### ISSUE TITLE
Searching for "active" perks on weapons

### ISSUE THREAD

**Issue by DHager** [DestinyItemManager/DIM#8477]
### Proposed change

A filter like `perkactive:` or `perkselected:` which would find all items with a matching perk/socket that is currently configured, not just available on the weapon.

### How does this fit into your workflow?

The specific reason I'm asking for this general-feature involves kill-trackers. Now that the game has made them standard on all weapons, I want to find all the weapons with `perkactive:"tracker disabled"` so that I can find and switch them to the appropriate PVE/PVP setting. (I'm aware that changing the setting directly is not possible as per #8081.)

____

A workaround is to export `destinyWeapons.csv` and filter all rows with `tracker disabled*` present, save the `Id` column one per line in a text file, and use a small script or regex to change them to a query in the form `(id:1 or id:2 or id:3)`.

**Comment by robojumper** [comment]
> I want to find all the weapons with `perkactive:"tracker disabled"` so that I can find and switch them to the appropriate PVE/PVP setting

Try `-kills:>=0 is:weapon -is:crafted`.

**Comment by DHager** [comment]
Checking the kill-counter helps, but it has some pitfalls with respect to:

* Weapons set correctly but simply not yet used. (Ex: Some specialty osmosis weapons for anticipated end-game content where the particular weapon/elemental-spread has not been needed yet.) 
* Weapons set incorrectly so not gaining kills (set to PVE but only used in PVP or vice-versa.)

**Comment by DHager** [comment]
**P.S.:** I readily admit this feature is... marginal, unless someone can think of another use-case that might be improved by being able to filter by active perks.

**Comment by robojumper** [comment]
Did you try out the filter? For a weapon with an active kill counter, the number of kills is `>=0`, so `-kills:>=0` shows weapons where DIM didn't even find an active kill counter to extract the number of kills from.
