### ISSUE TITLE
Text length on move-popup overflows expand button for longer items.

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#849]
guessing with i18n it will also be an issue --

ex:
<img width="358" alt="screen shot 2016-09-05 at 8 18 19 pm" src="https://cloud.githubusercontent.com/assets/424158/18258551/f4235ac8-73a5-11e6-93e5-6cae2c968909.png">

**Comment by joshmedeski** [comment]
So Bungie left room for two lines of text if needed. Do we want to do something similar?

![screen shot 2016-09-09 at 10 41 34 pm](https://cloud.githubusercontent.com/assets/2036594/18407709/9b7b5cfe-76de-11e6-89dc-bea086434fb3.png)

**Comment by SunburnedGoose** [comment]
Could use an ellipsis on the overflow.

**Comment by kyleshay** [comment]
`overflow: scroll` 😎 

... Ellipsis or wrap to two lines would be fine. Another option might be to rescale the text size to fit... might not have the best results (especially so on with i18n.)

I'm ok with 2 lines, It's only for a handful of items and we're currently on desktop with whatever space we need. Can reconsider design later.

**Comment by CaseyMichael** [comment]
I see the issue with this one. The css style .item-header has a property white-space: nowrap !important. If you remove that style it allowed the header to wrap onto 2 lines. However I'm not sure what the original intent was for this css style property.

![image](https://cloud.githubusercontent.com/assets/2779354/18410717/1b689546-7737-11e6-9156-db6e2e4492ec.png)

**Comment by kyleshay** [comment]
yup, thanks @CaseyMichael :)

**Comment by joshmedeski** [comment]
@CaseyMichael I'm not sure of the original intent of this property either because I recently adjusted the popup (https://github.com/DestinyItemManager/DIM/pull/598).

Thankfully my CSS changes allowed the `nowrap` property to be removed with no problems, since the header is now non-fixed, block element 😉
