### ISSUE TITLE
Too much space around bungie icons?

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#8496]
<img width="371" alt="Screen Shot 2022-06-16 at 10 36 54 AM" src="https://user-images.githubusercontent.com/313208/174132384-1c5cdf5f-bfcd-42bc-a2a4-8e0f8269ae34.png">

**Comment by nev-r** [comment]
the .25em margin exists to give them breathing room in cases where there's no inline space between symbol and next word.
without it, some cases don't have any breathing room and look weird/incomparable to game.
![image](https://user-images.githubusercontent.com/68782081/174358029-b192fc43-0c26-4856-8103-d153e6401f7f.png)

the solution here might be to investigate why threader example ends up with the spaces intact, but objective display doesn't render that white space
![image](https://user-images.githubusercontent.com/68782081/174358329-d6343f0a-0e3a-45cc-be32-37536af6f912.png)

**Comment by bhollis** [comment]
Yeah as part of this change I fixed things to render the whitespace correctly (by wrapping in a span)
