### ISSUE TITLE
Relic Tether Incorrect Info Displayed

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#8505]
![image](https://user-images.githubusercontent.com/4798491/174613237-81248e46-396d-4604-8da8-e81f4eef6e84.png)

![image](https://user-images.githubusercontent.com/4798491/174613448-31eda880-7815-45e0-bf9e-6baffa09fc79.png)

**Comment by nev-r** [comment]
it's not hooked up properly in the api. it's been mentioned to shaffstall but no issue is filed atm

**Comment by delphiactual** [comment]
I knew I had seen it somewhere just could not remember where or the context.
