### ISSUE TITLE
Scrollbar/overlay gap

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#852]
notice you can see the icons below the right + bottom edge

![gap](https://cloud.githubusercontent.com/assets/424158/18282346/c1103172-742e-11e6-89f3-97e022ba6b72.gif)

**Comment by joshmedeski** [comment]
Can you be more specific with how to recreate this bug?

**Comment by kyleshay** [comment]
ah. just noticed it doesn't happen if your window is wide enough.

if you resize DIM to < 900px width (and the horizontal scrollbar appears) it should happen. (on mac, at least.)

**Comment by bhollis** [comment]
Ah, it's because the custom scrollbars are transparent, but the blackout div is "fullscreen" (which doesn't intrude into scrollbar area.

We didn't have this problem before because we were using the native scrollbars that either always took up space or always hovered over content (on mac)

**Comment by ericnelson0** [comment]
Simple hack is to change the width/height of the overlay to 110%

**Comment by joshmedeski** [comment]
I think @ericnelson0 is onto something.

I changed the scrollbar's background to the semi-transparent black (to match the overlay) and it looks kind of cool.

Let me know if this bug is a priority and I'll make a PR and we can work out the final implementation.

**Comment by bhollis** [comment]
New scrollbar style doesn't have this issue.
