### ISSUE TITLE
integration with destinyscopes.com

### ISSUE THREAD

**Issue by shockthealien** [DestinyItemManager/DIM#853]
Not sure about you guys but the scopes always baffle me and never know what to use.

Lately been using destinyscopes.com to try and figure out whats best to use but the back and forth between the pages makes the process longwinded and tedious. Is there any way we can either integrate it or pull data from it? (or same data from somewhere else?)

**Comment by delphiactual** [comment]
https://github.com/DestinyItemManager/DIM/pull/661

**Comment by shockthealien** [comment]
oh dang. I did a search for destinyscopes and nothing came up. Sorry for the duplicate

**Comment by SunburnedGoose** [comment]
If you searched issues, it wouldn't have shown up because it's a pull request.
