### ISSUE TITLE
List View shows perks from right (top) to left (bottom)

### ISSUE THREAD

**Issue by GTink911** [DestinyItemManager/DIM#8532]
### DIM Version

Version 7.23.2.1001854 (beta), built on 6/29/2022, 1:15:13 PM

### Browser Details

Chrome Version 103.0.5060.66 (Official Build) (64-bit)

### OS Details

Windows 10

### Describe the bug

When using List View, the right-most perks are displayed at the top of the list, and the left-most perks are displayed at the bottom of the list. This is contrary to what a English user might expect - left to right, top to bottom.

You can see this issue by selecting List View on any weapon.

![1](https://user-images.githubusercontent.com/42620721/176574729-c686679d-548f-42f6-8ebb-0beede1016ea.PNG)
![2](https://user-images.githubusercontent.com/42620721/176574733-34a2c5ad-0fc4-47fe-b5ad-5f1df82c9ebc.PNG)

**Comment by delphiactual** [comment]
Hover the weapon in question in-game

**Comment by bhollis** [comment]
We decided to order the perks by their importance (reading top to bottom) rather than in their left to right order.
