### ISSUE TITLE
D2 Gunsmith does not work on iOS app

### ISSUE THREAD

**Issue by mannyrye** [DestinyItemManager/DIM#8537]
### DIM Version

7.23.2

### Browser Details

iOS app

### OS Details

iOS 15.5

### Describe the bug

D2 Gunsmith is not working within the DIM app downloaded from the app store. The solution on Safari is to clear the cache entry for d2gunsmith, as instructed by that site’s developer: “Hard-refresh or clear your cache if you don't have any perks visible on a Weapon page.” However, for the DIM app, that is not possible (deleting the app and reinstalling it does not work). Therefore, one cant use D2 gunsmith from within the app.

**Comment by mannyrye** [comment]
> Interesting, but this is the GitHub project for DIM, not D2Gunsmith.

The instance of D2 Gunsmith that DIM opens is inside the DIM app. You should have access to the cache of all of those. In my case it is corrupted and I can’t delete it, because it lives inside DIM. So I would ask that you kindly reconsider. 
Thank for all your work.

**Comment by bhollis** [comment]
Ah, understood. No, unfortunately we do not have any control over that.
