### ISSUE TITLE
Apply mods and fashion to single (unequipped) armor set in loadout

### ISSUE THREAD

**Issue by wasamandrapo** [DestinyItemManager/DIM#8538]
### DIM Version

Version 7.23.2 (release), built on 29/6/2022, 15:10:05

### Browser Details

Chrome 103.0.5060.66

### OS Details

Windows 10

### Describe the bug

When I try to load a saved loadout, instead of getting the loadout (which is a completely different set of armor with different mods/shaders/ornaments) it changes the mods/shaders/ornaments to my current equipped armor (both loadouts dont share any piece of armor), the bugged loadout is set to only have it in the inventory, not to autoequip it. It only happens with this loadout, others loadouts (for other characters too) work completely fine. I tried to delete that loudout and save it again, still broken. Oddly enough, after all of this happens, when I try to load it one more time, it actually loads the correct content of the loadout.
1- Current equipped loadout:
![Screenshot_2](https://user-images.githubusercontent.com/51026386/176977962-559e1a45-ab1d-4178-98d1-a2f04db0f0a9.png)
2- Loadout I try to get in inventory:
![Screenshot_1](https://user-images.githubusercontent.com/51026386/176978191-3d71998d-61ae-404e-a92d-121c8acd82d3.png)
3- DIM trying to change the mods/shaders/ornaments to the current equipped armor.
![Screenshot_3](https://user-images.githubusercontent.com/51026386/176978014-ffff6185-f5a4-4299-9fbe-b31cacca7e25.png)
If you want any more details, please let me know. Thanks.

**Comment by robojumper** [comment]
It looks like you're expecting DIM to equip mods and fashion into the armor your solar loadout has listed as unequipped/pocketed? This is not supported right now; DIM will always equip armor if the loadout lists it as equipped and then apply fashion and mods to the armor currently equipped on your character. This is to allow fashion- and mods-only loadouts.

#7773 could be related.

**Comment by wasamandrapo** [comment]
> It looks like you're expecting DIM to equip mods and fashion into the armor your solar loadout has listed as unequipped/pocketed? This is not supported right now; DIM will always equip armor if the loadout lists it as equipped and then apply fashion and mods to the armor currently equipped on your character. This is to allow fashion- and mods-only loadouts.
> 
> #7773 could be related.

Hello, thanks for answering. This is not the case, my solar loadout already has the mods/ornaments/shader applied, I just want to get them from my vault. The solar loadout isn't configured to change any armor I'm currently wearing (as I said before, it's a completely different set of armor pieces). I have other loudouts with the exact same function and they work perfectly fine. Yestarday, I made another (new) loudout for my Warlock and this happened again, I don't know if something with DIM changed or it's bugged. Sorry If I wasn't clear enough before, thanks.

**Comment by bhollis** [comment]
Glad you got it figured out!
