### ISSUE TITLE
Item Popups and Sidebars close quickly without user input

### ISSUE THREAD

**Issue by OkumuraTR** [DestinyItemManager/DIM#8539]
### DIM Version

Version 7.23.2.1001860 (beta), built on 7/2/2022, 3:13:47 PM

### Browser Details

Version 103.0.5060.66 (Official Build) (64-bit)

### OS Details

Windows 10

### Describe the bug

https://imgur.com/8HYTxDj

This bug has been plaguing me on both main and beta branch. Whenever I click on anything that "pops up", so any of the weapons and armor I have, or the sidebar, it opens momentarily and closes within a second. It is extremely rare for it to stay open for more than 2-3 seconds. The imgur link above shows both the log and a gif of the issue. 
Edit: I should clarify that I have the "Clarity" extension installed, but this bug predates that as well.
### Logs

```shell
The logs seemed to be flying at the speed of light, so I took a screenshot of it. https://imgur.com/2PoNhra
```

**Comment by robojumper** [comment]
Are you using a DIM Streamdeck browser extension? Try completely uninstalling that browser extension, (beta) DIM can now connect to the Streamdeck plugin without any extension.

**Comment by bhollis** [comment]
Are you the same person who asked on Twitter and on Discord? Trying to figure out if it's one person or many.

**Comment by OkumuraTR** [comment]
@robojumper  It was indeed the plugin, removing it fixed the bug immediately.

@bhollis I have not asked anywhere else, just posted it here.
