### ISSUE TITLE
T12 Builder equip Option as well as create loadout option.

### ISSUE THREAD

**Issue by themacguy2k** [DestinyItemManager/DIM#854]
I LOVE the t12 builder, thank you for making it. I would like to suggest the option to equip the loadouts that it creates as an alternative to creating a saved loadout. Sometimes its nice to mix things up and having to save a new loadout each time can be a hassle.

I'm aware we can click each piece of gear and equip it that way (that is what I do now), but having the option for DIM to do them all in one shot would be nice.

**Comment by ericnelson0** [comment]
I would also like this, but it's kind of tricky. 

Should it be integrated with the loadout dropdown so that "previous" can be used?

**Comment by SunburnedGoose** [comment]
All you have to do is create an in-memory loadout similar to the Random Loadouts feature.  Apply the loadout and let the garbage collector take it away.

**Comment by ericnelson0** [comment]
Does the random loadout integrate with the "before" option in the loadout dropdown?

**Comment by SunburnedGoose** [comment]
Nope.  It just applies the loadout.  That would be a nice add on...

**Comment by themacguy2k** [comment]
I wish I could contribute more to this conversation besides making the suggestion. You guys are awesome. Is there a dept for helping with graphics? Thats about all I could do around here besides make suggestions and be a smart ass. :P

**Comment by SunburnedGoose** [comment]
I tend to say, "Make your own action".  Where do you think we could improve?  Can you make pretty pictures for a website?

**Comment by themacguy2k** [comment]
well, I am photographer mostly so I make pretty pics that way. I know my way around PS well enough to make things happen that way.

**Comment by SunburnedGoose** [comment]
Ummm...  yeah, don't really use that much photography in DIM :)  But hey, I love the ideas though.  If you feel friction, let us know.

**Comment by themacguy2k** [comment]
Yeah, figured that photography was not high on the priority list of things to get done. I do play a LOT of destiny and use DIM 100% of the time while I am playing so there are always little things that I come up with that I think are neat or could help, but may not really be helpful overall. So that was why I made the suggestion. I am happy to suggest ideas, even do mockups and such if that helps, but I also don't want to be a bother with and waste ppls time.

**Comment by kyleshay** [comment]
when https://github.com/DestinyItemManager/DIM/pull/855 hits, it might be easier to do this.

**Comment by h3adache** [comment]
Hi sorry I'm confused. Update 3.10.6 says this is done but this ticket is open.

> Can equip loadouts onto the current character from Loadout Builder.

I see the equip option from the loadout builder but it doesn't seem to do anything? No errors just doesn't do anything even though the message pops up saying it did equip the loadout.

**Comment by kyleshay** [comment]
ooh. thanks for the report @h3adache, hadn't actually tested that feature. just submitted something that may fix it which would allow us to close this afterward.
