### ISSUE TITLE
Items deleting from vault

### ISSUE THREAD

**Issue by Someone133** [DestinyItemManager/DIM#8548]
### DIM Version

7.24, built on 7/3/2022

### Browser Details

Ps4

### OS Details

Ps4

### Describe the bug

So i tried to store an armor piece in my vault while the armor tab was full. It put the piece at the end and deleted something in my vault to make the space. I now cannot buy heavy ammo synth or move the shaders in my warlock.

**Comment by bhollis** [comment]
https://github.com/DestinyItemManager/DIM/wiki/FAQ#DIM_deleted_my_item
