### ISSUE TITLE
Landscape mode

### ISSUE THREAD

**Issue by allen99309** [DestinyItemManager/DIM#8558]
I am not sure if this is the right place to share this.

When opening DIM on my iPhone 13 Mini and putting it in Landscape mode, if you expand the character list to show all characters and the vault, I am then unable to un-expand the character list and go back to just showing my current active character and vault. The two little arrows are covered up by the “Item Feed” sidebar.

**Comment by bhollis** [comment]
You're not really meant to use landscape on a phone. That said, you can turn Single Character Mode on and off in Settings.
