### ISSUE TITLE
Feature Request - T12 "what if" calculation

### ISSUE THREAD

**Issue by bnacey** [DestinyItemManager/DIM#856]
The T12 build calculator is nice, but prior to reaching T12 it can be difficult to tell how close you are without switching back and forth to the inventory screen.
While showing the T11 "best" builds, would it be possible to also show a few T12 builds if only one item slot need improvement. This should, of course, be an optional setting so calculation times are only impacted for users who intentionally choose the "what-if" processing.

**Comment by ericnelson0** [comment]
@kyleshay We used to have a sorting option so people could see how close they were to the next tier. Did it just look too ugly as a drop down?

**Comment by bhollis** [comment]
With the stat bars shown, it seems like it's easy enough to see which stat you need to improve, right?

Closing for now since we don't really have the infrastructure to display "what if" builds.
