### ISSUE TITLE
DIM sync is not working

### ISSUE THREAD

**Issue by andrewpong** [DestinyItemManager/DIM#8566]
### DIM Version

7.25.0.1001881 (beta)

### Browser Details

Chrome 103.0.5060.114 (Official Build) (64-bit)

### OS Details

Windows 11

### Describe the bug

DIM sync stopped working.

### Logs

> Access to fetch at 'https://api.destinyitemmanager.com/auth/token' from origin 'https://beta.destinyitemmanager.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

```
instrument.ts:151
POST https://api.destinyitemmanager.com/auth/token net::ERR_FAILED
```

```
instrument.ts:123 
[flushUpdates] Unable to save updates to DIM API TypeError: Failed to fetch
    at instrument.ts:151:1
    at l (dim-api-helper.ts:40:26)
    at dim-api-helper.ts:155:29
    at async util.ts:78:7
```

**Comment by FreakiiNinja** [comment]
Having the same issue. My loadouts are gone.

**Comment by whiskeytangofx** [comment]
I am having the same trouble.  I made some loadouts on the app and they haven't synced to my PC.  Both the app on my Android phone and Windows 11 desktop are reporting sync errors.

I tried to manually back up the .JSON data from my phone and import in to the desktop app.  There's no errors, but it also doesn't import.
