### ISSUE TITLE
DIM Sync Error. Load failed.

### ISSUE THREAD

**Issue by mannyrye** [DestinyItemManager/DIM#8568]
### DIM Version

Version 7.25.0 (release), built on 7/10/2022, 5:13:31 PM

### Browser Details

MacOS and iPhone Chrome, iPhone and iPad Safari, App Store DIM, DIM Beta

### OS Details

MacOS, iOS most current versions

### Describe the bug

DIM Sync Error. Load failed.
DIM tries to load over and over again. Only disabling DIM Sync and reenabling stops things, but the error persists.
Another symptom is that links for Loadouts cannot be created.
The only thing that makes my DIM setup weird is that I use pictographs at the beginning of my loadout names (not letter characters, say a snowflake for stasis ❄︎ ).
I've tried Deleting All Data from DIM Sync Servers to no avail.
To make matters worse one can't backup or restore from the App Store iPhone app, the backup I was able to make was from an instance of DIM I opened in iPhone Safari a couple of days ago (see attached). So all the work since then cannot be backed up. I can still access the new builds in the App Store app, but can't share them (links can't be created in Loadouts), or back them up. 
[dim-data 5.zip](https://github.com/DestinyItemManager/DIM/files/9111040/dim-data.5.zip)
.

**Comment by Cqkkkkkk** [comment]
Same to me.

**Comment by Zyybolt** [comment]
I'm having the same issue.

**Comment by johulv** [comment]
+1 Did all the recommended troubleshooting+ browser fixes but same issue persists.

**Comment by Cqkkkkkk** [comment]
I recommend turnning of the option `Enable DIM Sync (recommended) `. My DIM works after doing so. If not, please try turn it on and off several times.

**Comment by johulv** [comment]
https://twitter.com/ThisIsDIM/status/1547612739849240576?s=20&t=z13iejy5AP93x6aLSIYweA
