### ISSUE TITLE
Add the ability to load a shared DIM loadout to the iOS App Store DIM app

### ISSUE THREAD

**Issue by mannyrye** [DestinyItemManager/DIM#8569]
### Proposed change

Add the ability to load a shared DIM loadout to the iOS App Store DIM app.
Right now the workaround is to use Safari.

### How does this fit into your workflow?

Would be able to import loadouts directly to the app.

**Comment by bhollis** [comment]
Duplicate of https://github.com/DestinyItemManager/iOS/issues/16
