### ISSUE TITLE
loadout builder shows duplicates

### ISSUE THREAD

**Issue by chillenious** [DestinyItemManager/DIM#857]
For instance: http://screencast.com/t/vNRRC4mkg. The first few rows seem to be exact duplicates of each other.

**Comment by ericnelson0** [comment]
This just means that there are a few different ways to hit 5/5/2 with that character based on selecting different bonuses on the armor. 

We kept this is because some configurations might get you closer to the next tier than others.

**Comment by SunburnedGoose** [comment]
Closer to the next tier doesn't get you the next tier, but the user sees a long list of items that seem very similar.  People are just pushing a button and want to be told what to put on and how to wear it.  Sometimes too many options can give a user some anxiety about choice.

**Comment by chillenious** [comment]
DIM is not showing different bonuses though. If you look at the list, exactly the same bonuses are selected on the same pieces of armor.

**Comment by SunburnedGoose** [comment]
The text beneath the perks is the perks that need to be selected and they are all different.  So what you're seeing is all the permutations of the perks that get you to T11 with that gear.

**Comment by SunburnedGoose** [comment]
Is white text below the items is different for each row?

**Comment by SunburnedGoose** [comment]
#860

**Comment by ericnelson0** [comment]
Oh. You might be looking at the perk grid instead of the text underneath?

**Comment by chillenious** [comment]
Ok, got it. Well, one can debate on whether that's helpful if it leads to the same end result in terms of int/dis/str on your character, but I was looking at the icons rather than the text. It makes sense now, but I'd welcome a way to filter that out or also show the selected icons instead of just the text. Thanks.
