### ISSUE TITLE
Add pictogram to beginning of a loadout name to indicate the element and allow to sort loadouts by element 

### ISSUE THREAD

**Issue by mannyrye** [DestinyItemManager/DIM#8570]
### Proposed change

Add pictogram to beginning of a loadout name to indicate the element, if any, and allow to sort loadouts by element .

### How does this fit into your workflow?

I currently label my loadouts with pictograms so that I can easily look for in my long lists the element I want. For example I use a snowflake ❄︎ for stasis, a sun for solar ☼, etc.
I also use this symbol ⋒ for legend and master lost sector loadouts and a crescent moon for nightfall loadouts.
If it was done automatically and with better pictures it would be really helpful.

**Comment by bhollis** [comment]
We tried this - automatically adding icons to loadouts based on contents - and it wasn't useful enough without extreme customization. Either we'd show too many symbols you don't care about, or we'd miss ones you want. Better to name them the way you want, yourself.
