### ISSUE TITLE
Batch change weapon and armor shaders

### ISSUE THREAD

**Issue by mannyrye** [DestinyItemManager/DIM#8572]
### Proposed change

Be able to apply shaders according to criteria. 

### How does this fit into your workflow?

Right now shaders have to be applied one gun at a time. With armor one can change thing in the fashion portion.

**Comment by bhollis** [comment]
Can you provide more detail on how you'd use this? You like to put the same shader on all your weapons?

**Comment by mannyrye** [comment]
Or on all weapons that match a search.

**Comment by bhollis** [comment]
Yeah but why

**Comment by mannyrye** [comment]
I like to change the appearance of my guns to match the fashion I'm wearing. DIM loadouts sand transmog made fashion easy. 
Also, I like to assign the same default shader to all my guns.

**Comment by bhollis** [comment]
OK. The first part would be handled by having the ability to set weapon perks/mods in loadouts, which is planned. The second sounds like a fine idea but maybe of limited usefulness.
