### ISSUE TITLE
A way to find loadouts with deprecated artifact mods.

### ISSUE THREAD

**Issue by mannyrye** [DestinyItemManager/DIM#8575]
### Proposed change

A way to find loadouts with deprecated artifact mods. Perhaps mark them with an error.

### How does this fit into your workflow?

At the beginning of the these last two season I have to go loadout by loadout checking to see if there are armor mods that are deprecated. Some of my loadouts have no artifact mods, others can be tweaked to still be useful.

**Comment by bhollis** [comment]
Note to self: Might be a nice thing to go with the search filter pills idea for loadouts

**Comment by robojumper** [comment]
Filter pills implement this now.
