### ISSUE TITLE
Vendor page should allow filtering by is:craftable

### ISSUE THREAD

**Issue by mturquette** [DestinyItemManager/DIM#8576]
When viewing the Vendor page, many search terms work correctly. For instance, if I type `is:arc` in the search bar, I will only see Vendor items with Arc elemental affinity.

This does not work for the `is:craftable` search term. When I search by `is:craftable` the entire page becomes blank with no items and no vendors shown. It would be cool to see the focusable weapons that have the possibility to become crafted (e.g. Opulent, Haunted, Umbral focusing at War Table).

My use case is that I would like to use the Vendor page to see which vendors allow me to focus craftable weapons. I guess today that is just the War Table & Crown of Sorrow, but it's reasonable to think that more vendors will get focusing (Drifter & Saint-14 already have it) and that some of those weapons will become craftable.

I'm not sure if this is a trivial bug or something more challenging. If the latter, is it possible to cross reference the weapons listed in the vendor page with another list of known-craftable weapons, in order to highlight the *possibility* that these weapons might be craftable when purchased?

I hope all of that makes sense ...

**Comment by bhollis** [comment]
This appears to work now.

**Comment by mturquette** [comment]
Yes, I confirm it works as requested. And it is awesome. Thank you!
