### ISSUE TITLE
loadout builder filters items that it should show

### ISSUE THREAD

**Issue by chillenious** [DestinyItemManager/DIM#858]
I'm trying to get a T5 build that includes the twilight garrison (tactical air support perk). When I select that perk, it finds a build that includes it. The chest piece it includes even has the next perk I care about, which is arc armor. However, when I select the arc armor perk also, builds are shown without the twilight garrison. See for instance: http://screencast.com/t/FclSo0Lyl152

Two questions:

* when I select tactical air support, why is it still showing me chest pieces that don't have that? doesn't it work like a filter (if conditions aren't met, don't show)?

* why does it hide the twilight garrison it just showed, even though it should still satisfy the constraints I put in?

**Comment by ericnelson0** [comment]
So if you want to "and" two perks you should shift + click the perks they will appear with a purple background. 

The default behavior is to "or" perks so it will show the best build with any of the orange perks.

**Comment by SunburnedGoose** [comment]
You're going to need a touch friendly way of doing that.  Shift is not on my screen :)

**Comment by ericnelson0** [comment]
@SunburnedGoose can you open an issue for that? I'm gonna close this for now as it's expected behavior.

**Comment by chillenious** [comment]
Gotcha, thanks

**Comment by adamksib** [comment]
This needs to be more visible to the user. I use DIM load out builder daily on PC and specifically came here to request this as a feature.

**Comment by kyleshay** [comment]
We're open to suggestions. There is a 'help' button on that page which describes the functionality

**Comment by adamksib** [comment]
Great, thanks for responding. I was really pleased when you added the perks functionality. 

I've been thinking of some options. 

1. Cycle through three states. Blank/or/and. This would be visually clean, obvious to the user and the most mobile friendly. 

2. The left half of each icon is or, the right is and. This would be quicker for the user, it would require the right logic to turn off or when you select and etc.

3. A mini icon in one corner 

4. Mouse over tooltip, quickest option, no change to current function, not mobile compatible, might go unnoticed. 


I favour option 1 myself as it's how I imagined it to work. I also find the wording or/and a bit abstract. Something like option and lock might be more understandable to common users. 

I have not actually been able to test the current functionality as I'm travelling and on mobile only, but I wanted to give you a rough draft response.

**Comment by adamksib** [comment]
Having managed to get on a PC, I think cycling through blank - or - and would work perfectly.
