### ISSUE TITLE
Find according to shader name

### ISSUE THREAD

**Issue by mannyrye** [DestinyItemManager/DIM#8587]
### Proposed change

I would like to search by shader name assigned to equipment. 

### How does this fit into your workflow?

It would allow me to find and then change shaders I don't fancy anymore.
Also, one could use the shaders as tags (not my main desire). For example, could tag say a few special pieces with shaders that otherwise don't fall under, easily or at all, what can be searched for now.

**Comment by inexorableAce** [comment]
You can do this now with the `perkname` search like this `perkname:"descendant vex chrome"`
