### ISSUE TITLE
Searches font changes size when turning iPhone to landscape and back

### ISSUE THREAD

**Issue by mannyrye** [DestinyItemManager/DIM#8588]
### DIM Version

Version 7.25.0 (release), built on 7/10/2022, 5:13:31 

### Browser Details

iPhone Safari 

### OS Details

iOS 15.5

### Describe the bug

The font in searches changes size when turning iPhone to landscape and back. 
![55CD8743-9305-4417-98D4-AE41A7A83D04](https://user-images.githubusercontent.com/20385998/179367195-fee16f6f-ad97-4e15-9d0e-9eb1bac3fc06.png)
![6BB4662C-73ED-4876-9092-A16F84CD3B29](https://user-images.githubusercontent.com/20385998/179367197-a3e1c1f5-f389-413c-86ef-5b4383ff03a1.png)

**Comment by bhollis** [comment]
I can take a look but I can only imagine this being a Safari bug, since we don't do anything particular to make this work.

**Comment by bhollis** [comment]
Any hints on how to reproduce?
