### ISSUE TITLE
Find items that can’t be ornamented

### ISSUE THREAD

**Issue by mannyrye** [DestinyItemManager/DIM#8591]
### Proposed change

Find items that can’t be ornamented

### How does this fit into your workflow?

It'll allow me to filter for things like these gauntlets I got from Xur a couple of weeks back. 
![76AC31F9-E688-499D-A2C6-09E7BC2ACCE6](https://user-images.githubusercontent.com/20385998/179367951-98c1f885-dbe2-4a90-86a7-1bcab47e5841.jpeg)

**Comment by robojumper** [comment]
Try `is:armor -is:ornamented -"default ornament"`
