### ISSUE TITLE
Solstice Triumph "Ash Tray" not tracking in Beta Dim

### ISSUE THREAD

**Issue by xoxoKaralee** [DestinyItemManager/DIM#8596]
### DIM Version

Version 7.26.0.1001890 (beta)

### Browser Details

Version 103.0.5060.134 (Official Build) (64-bit)

### OS Details

windows

### Describe the bug

![image](https://user-images.githubusercontent.com/49349280/180102583-55437cff-0c38-4651-9e04-59335a532d73.png)
![image](https://user-images.githubusercontent.com/49349280/180102675-de576647-6685-4c07-a67a-1e24baa79507.png)

In beta dim, the Solstice triumph "Ash tray" is not tracking at all.

**Comment by xoxoKaralee** [comment]
Yes, sorry, it is not showing objective progress.
I just checked the d2 app and it is showing objective progress.

**Comment by bhollis** [comment]
Seems to be tracking now, are you still having a problem?

**Comment by robojumper** [comment]
Solstice has ended, so this is no longer actionable. The game itself also had its fair share of issues with that currency though, so I don't feel super bad about this one.
