### ISSUE TITLE
DIM is equipping wrong Solstice Cloak (Majestic)

### ISSUE THREAD

**Issue by Coleboto** [DestinyItemManager/DIM#8597]
### DIM Version

Version 7.26.0

### Browser Details

Chrome

### OS Details

Windows 10 

### Describe the bug

When trying to equip the "upgraded" version of the Solstice Cloak (Majestic) using transmog, I get the non upgraded version instead. I've saved my equiped loadout several times with the fully upgraded armor set, but each time the upgraded cloak is not equipped.
This may be because I transmogged both upgraded and non upgraded versions

![SupposeToLookLike](https://user-images.githubusercontent.com/109718181/180141272-25226f53-e986-47b9-b5bc-ab698ec1149e.png)
![WhatIGet](https://user-images.githubusercontent.com/109718181/180141280-86adc9df-cce3-4bae-845b-dffeb66ebf7e.png)
.

**Comment by bhollis** [comment]
Can you help clarify a bit? Let us know each specific step you did in DIM, and what you expected to happen, then what actually happened.

**Comment by Coleboto** [comment]
Sure!
I created a load out that uses the ornament seen above. 
I use DIM to save my currently equipped load out which includes the “upgraded” set of solstice gear (where the colors of your subclass get shown)
When trying to re-equip the same load out using DIM it instead equips the “un-upgraded” cape (without the subclass color)

This only happens with the cloak. 
I expect to get the cloak that shows the subclass color, instead I get the default cloak of the ornament.

**Comment by delphiactual** [comment]
Are you sure DIM had current information about what was equipped when you created the loadout?

**Comment by Coleboto** [comment]
Yes I am sure, I refreshed DIM and re-equipped the cloak multiple times while also creating new load outs.
Is it possible to upload the video clip so you could get a better understanding?

**Comment by robojumper** [comment]
Video, loadout share, browser logs can all help.

**Comment by bhollis** [comment]
Feel free to reopen if you can provide more info like a link to your loadout, otherwise there's not much we can do to investigate.

**Comment by Coleboto** [comment]
DIM.mp4
<https://drive.google.com/file/d/1xm8wyIql5fSrdsY6ZorqtXqFBi0Q6L2I/view?usp=drive_web>
Trying to replicate my issue, not a huge thing, just something I noticed.

**Comment by robojumper** [comment]
@Coleboto That video appears to be set to private.
