### ISSUE TITLE
Loadout builder not properly reassigning element

### ISSUE THREAD

**Issue by Benjamin-Berger** [DestinyItemManager/DIM#8599]
### DIM Version

Version 7.27.0 (release), built on 7/25/2022, 6:20:44 AM

### Browser Details

chrome

### OS Details

mac m1

### Describe the bug

When attempting to make a loadout that would require multiple element changes based on mods, the loadout organizer will just assume there are no possible configurations. 

in the first image it changes the helm to accommodate ashes to assets (solar):
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/10641881/181000272-fa21f998-83a8-4bbe-8a5b-07a85da3fd8a.png">

in the second adding well of tenacity (void) should change any number of elements but it does not:
<img width="1331" alt="image" src="https://user-images.githubusercontent.com/10641881/181000966-4e478dd6-3760-4907-8bd8-d6b78e9588b6.png">

**Comment by robojumper** [comment]
You're not assuming masterworked items, so the class item has an assumed 10 energy while the rest only has 7. The helmet in particular only has 0-1 energy capacity available (depending on stat mod choice), so it's not possible to fit 5 CWL mods when all of them cost >=2 energy. LO is correct in not showing any feasible mod assignment.
