### ISSUE TITLE
Add foundry as search term

### ISSUE THREAD

**Issue by mturquette** [DestinyItemManager/DIM#8608]
I'd love to be able to filter items (specifically weapons) by the foundry they were created from in-lore. For example, `foundry: veist` or `foundry: hakke`. 

Is this data exposed in the api? Origin traits are not sufficient to cover every corner case, unfortunately.

**Comment by robojumper** [comment]
Why is this info important? How does this fit in your workflow?

> Origin traits are not sufficient to cover every corner case, unfortunately.

Would be good to specify what are these corner cases and how would you expect DIM to behave :)
I guess some pre-Witch-Queen weapons don't have any origin traits, so the filter should match those. Are there any weapons that do have a foundry origin trait but shouldn't match the filter?

> Is this data exposed in the api?

Sort of -- see Bungie-net/api#1605, it's all a bit inconsistent on the game data side.

**Comment by mturquette** [comment]
The workflow is that one of my chars is a "Veist Main" and I'd like to easily browse all weapons from that Foundry when building a loadout in DIM. It's a stupid role-playing thing, but one of my characters is loyal to a particular foundry. I'm hopefully not the only other player that plays this way (I know some folks like Suros, Omolon, etc).

This has been a fun learning moment. Thanks to your link I dug around a bit more and confirmed that one of my "corner cases" does correctly identify Veist. I was worried that Quickfang, the Hunter-only sword that has no origin trait, wouldn't correctly identify but it does: https://data.destinysets.com/i/InventoryItem:2782325300

Seems like the data is there. The bug you identified is just that: a bug in the data exported by Bungie and should be reported back to them. Thanks for your consideration!

**Comment by nev-r** [comment]
does having veist stinger make something a veist gun even if it has a non-veist model, no veist branding, and no veist overlay on gun details?

**Comment by delphiactual** [comment]
is this hypothetical? 
![image](https://user-images.githubusercontent.com/4798491/192124782-cff32f33-eaa1-43dc-a974-f6ba0b230636.png)

**Comment by nev-r** [comment]
this is new trials bow

**Comment by delphiactual** [comment]
removed trials weapons from foundry search

**Comment by mturquette** [comment]
Thanks @delphiactual for taking this on! I reviewed and it looks like it matches my expectations. I wasn't sure about the removal of the trials weapons, but I guess it makes sense.

**Comment by delphiactual** [comment]
I re-added them this morning after discussions last night
