### ISSUE TITLE
Only show one instance of a set in Loadout Builder

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#861]
Loadout Builders shows all the permutations of a set of items in the UI.  This is causing some friction as users are faced with many choices that lead to the same goal, a T12 build.

<img width="1250" alt="00000193" src="https://cloud.githubusercontent.com/assets/984608/18317972/571e8b6c-74e5-11e6-86c2-0177c7b94975.png">

Once we've computed all the sets, we should present the user with only one instance of a set that has the highest stats. This helps users quickly see their choices.  Once you get to T12, seeing the variations is unnecessary.  If you're moving towards T12, picking the set with the highest stats will be sufficient if the user wants to fiddle with their gear on their own and look at other builds in the Item Manager screen.

Loadout builder has a great feature set but we're just sending too many similar options to the user that has little benefit.

**Comment by ericnelson0** [comment]
@kyleshay and I discussed this at one point, but I can't find the thread. 

We decided on keeping them in as one configuration can get you closer to another tier than another. Maybe there is a better way of handling it in the UI than just a bunch of rows though?
