### ISSUE TITLE
Recent searches are not the most recent

### ISSUE THREAD

**Issue by SwaggySpaghetti** [DestinyItemManager/DIM#8620]
### DIM Version

7.28.0 

### Browser Details

Chrome

### OS Details

Win 10

### Describe the bug

When you have multiple searches favorited, the ''most recent searches'' are never the actual last ones you searched for.

**Comment by bhollis** [comment]
That's right. They're not "recent searches", they're ranked by frecency, which is a combination of recency and frequency of usage: https://github.com/DestinyItemManager/DIM/blob/master/src/app/search/autocomplete.ts#L128-L143
