### ISSUE TITLE
New tooltips feedback

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#8626]
Playing with them a bit - just some random thoughts:

1. I *love* the colored sections.
2. The borders do feel like a bit much. I don't have a great idea of how best to set them off but it might be worth trying some other options. I feel like the borders pull my eyes off the text. We also don't have these borders on the item popup (which also suffers from contrast/separation issues)
2. The borders are a bit angled at the corners because the top border and the side borders are different colors:
<img width="326" alt="Screen Shot 2022-08-08 at 4 09 47 PM" src="https://user-images.githubusercontent.com/313208/183529871-ae3d12a8-e378-4bb3-bdd3-cd63e558fb1c.png">

4. I'm getting a bit overwhelmed with purple since my inventory is also mainly Legendaries. I wonder if we should experiment with complementary or triad opposing colors (e.g. yellow, or green/red)
5. Margins, especially vertical, feel a little cramped with the added borders and backgrounds. Feels like they need a bit more room to breathe.
6. I noticed that the inline perk descriptions in grid view now don't match the ones in press tips. Not sure if that matters or not.

**Comment by vivekhnz** [comment]
Good feedback, I'm in agreement with a lot of that.

> I noticed that the inline perk descriptions in grid view now don't match the ones in press tips. Not sure if that matters or not.

Could you clarify what you mean here / provide an example? That sounds like a bug, but I haven't been able to repro.

This is probably a bit over the top, but here's a variant with more padding, rounded corners, more drop shadow and less pronounced borders:

![dim-tooltip-alt-design](https://user-images.githubusercontent.com/17512262/183892103-31b0db30-2724-41b8-a082-5fb2c9e581f0.png)

I've pushed it into the `alt-tooltip-design` branch if you want to play around with it. It's a bit of a departure from DIM's much more compact design, but maybe there's something useful here. I think these changes give the tooltip more depth, as if it's floating 'higher' than before.

I originally added the outer border to provide contrast against the item popup background, which is a very similar color to the tooltip background. The heavier drop shadow provides more contrast though, so we could potentially darken the border or get rid of it entirely. I'll try some other color variations, including one with a lighter background without a border.

**Comment by bhollis** [comment]
> Could you clarify what you mean here / provide an example? That sounds like a bug, but I haven't been able to repro.

Here you go:
<img width="661" alt="Screen Shot 2022-08-26 at 7 19 08 PM" src="https://user-images.githubusercontent.com/313208/187010484-cb079474-840b-4585-aba7-2367b8e2acf9.png">

FWIW I'm not sure I like the rounded corners - at some point in the past we had more rounded corners in DIM and eventually eliminated them all.

**Comment by vivekhnz** [comment]
Ah, I misunderstood, thought you meant that the perk description text itself differed between the item popup and tooltips. Maybe we could try something like this?

![dim-alt-inline-community-insight](https://user-images.githubusercontent.com/17512262/187024348-60674399-498d-4336-824f-a0b86425dbc7.png)

Re. the rounded corners, I like them because it sets the tooltip apart from the UI it's in front of. That being said, I wouldn't mind if we go back to the sharper corners.
