### ISSUE TITLE
Add or remove wishlisted rolls directly from Armory popup

### ISSUE THREAD

**Issue by maxlesser** [DestinyItemManager/DIM#8629]
### Proposed change

Currently, clicking a gun name brings up a full popup with all possible perks/slots. There is an option to copy the perk selections as a wishlist roll to be manually added to your wishlist and then imported into DIM.

Suggested feature: A button on the full gun perks popup that automatically adds the selected perks to your wishlist. 

Suggested feature: An X button next to each roll on the "Wishlisted Rolls" list to remove a roll from your wishlist.

### How does this fit into your workflow?

When a new gun is added or perks are reworked, or I see a new perk combination I want, I would bring up the gun, select the perks I'm looking for, and add that roll to my wishlist directly. Or, when a roll goes out of fashion and I no longer want it, I could click through to the gun and remove directly from the list of my wishlisted rolls for that gun. 

This would save me the time of going into a text file, adding or removing lines, and then re-importing to DIM.

**Comment by bhollis** [comment]
Yes, this is the planned wishlist editing functionality, and it was a large part of why the Armory screen was built. There's a lot of work to do on Wishlists first to prepare them, though.

**Comment by bhollis** [comment]
Rolling this into https://github.com/DestinyItemManager/DIM/issues/10313, it doesn't need to be tracked separately.

**Comment by Revadike** [comment]
Good idea!
