### ISSUE TITLE
Add button in compare for all "Artifice Armor" items

### ISSUE THREAD

**Issue by thomaskchan** [DestinyItemManager/DIM#8632]
### Proposed change

In the comparison it would be nice to be able to select all "Artifice Armor" items if your initial item has the artifice perk.

### How does this fit into your workflow?

Both master Grasp and master Duality drop artifice armor, so if you've done both dungeons you may have artifice armor from both.  It would be useful to be able to quickly compare all the artifice armor you have from both dungeons rather than just comparing the armor from one dungeon and having to manually select the others.

**Comment by robojumper** [comment]
Such a feature should probably work for all intrinsic armor perks: Artifice, Iron Lord's Pride, the Y5 seasonal armor perks, etc.

Needs to be added here
https://github.com/DestinyItemManager/DIM/blob/c1801804034f6f453d0024e1ee1783e214b6a88e/src/app/compare/compare-buttons.tsx#L23-L117

**Comment by nev-r** [comment]
closed by #8754
