### ISSUE TITLE
Loadout name field shouldn't autocomplete

### ISSUE THREAD

**Issue by saxamaphone69** [DestinyItemManager/DIM#8636]
### Proposed change

Currently when naming or renaming a loadout, due to the input field having a generic name, Chrome (might be other browsers too) will auto suggest things from other websites that also use a generic name attribute.

```html
<input class="CmFsFmLf" name="name" minlength="1" maxlength="50" required="" type="text" placeholder="Loadout name" value="">
```

![image](https://user-images.githubusercontent.com/877480/184525160-cc66deea-d2e2-4d18-ba3d-915a75235c98.png)

Changing `[name="name"]` to something else (e.g. `name="dim-name"`) fixes the issue.

![image](https://user-images.githubusercontent.com/877480/184525130-df556342-a306-4410-9437-bb4d0e25e1a0.png)

If I had to guess, [changing this line](https://github.com/DestinyItemManager/DIM/blob/master/src/app/loadout-drawer/LoadoutDrawerHeader.tsx#L21) should do it?

### How does this fit into your workflow?

Since Destiny uses display capture when streaming on PC, there is a potential that when you Alt+Tab into DIM to make a new loadout, if you have ever entered personal information into another website that uses a generic `[name=name]` attribute, it would appear on stream.

I guess it also keeps things contained within DIM, so that loadout names wouldn't also start appearing on other websites.

**Comment by bhollis** [comment]
The correct answer is to add `autoComplete="off"`. I'll make the change.

**Comment by saxamaphone69** [comment]
Thank you @bhollis, appreciate this.
