### ISSUE TITLE
Loadout View Issue (App on Android) 

### ISSUE THREAD

**Issue by rekcluse** [DestinyItemManager/DIM#8637]
### DIM Version

Version 7.29.1 (release), built on 08/08/2022, 05:21:50 Icon Orange. 

### Browser Details

App

### OS Details

Android. Samsung Galaxy S10 +.

### Describe the bug

On loading a loadout to edit, the class items are too far off screen to the right to be able to delete from the loadout. 

Pic enclosed.  

![Screenshot_20220812-154916_Chrome](https://user-images.githubusercontent.com/62358799/184532030-dc9f8bbe-3ec7-4957-a720-7e8122a01f85.jpg)

Thank you.

**Comment by bhollis** [comment]
Hmm, I'd need to know more about your screen size and any changes or customizations you've made. By default, the icons are supposed to resize automatically so five can fit across the screen (as in this emulated Galaxy S8):

<img width="233" alt="Screen Shot 2022-08-26 at 7 13 38 PM" src="https://user-images.githubusercontent.com/313208/187010287-8435aa04-7676-4716-9cd5-ae87a89736e7.png">
