### ISSUE TITLE
Display element and Power Level on Stream Deck buttons

### ISSUE THREAD

**Issue by schmittyd** [DestinyItemManager/DIM#8644]
### Proposed change

It would be good if the element and power level were displayed on the Stream Deck button below the item's icon. Like in DIM.
Also, if an icon or some sort of indicator can be shown if item is a PvE and/or PvP roll.

### How does this fit into your workflow?

It would make it easier to identify the correct weapon or armor piece without having to label everything.

**Comment by nev-r** [comment]
https://github.com/fcannizzaro/com.dim.streamdeck/issues

**Comment by schmittyd** [comment]
> https://github.com/fcannizzaro/com.dim.streamdeck/issues

I've had a look at the post in the link you posted, but they don't apply to my request.

**Comment by nev-r** [comment]
DIM team does not develop the streamdeck app. feature requests belong in that github repository

**Comment by schmittyd** [comment]
Ah ok, was not aware of that. Apologies.
