### ISSUE TITLE
Filter to show armor with artifact mods equipped

### ISSUE THREAD

**Issue by ZetaTauEpsilon** [DestinyItemManager/DIM#8645]
### Proposed change

Hello all!

I'd like to propose the `is:artifactmodded` filter for DIM search. I have implemented this filter locally in my forked DIM repo [here](https://github.com/DestinyItemManager/DIM/commit/6ec11cee015f32622470b0dc17e6730000d71b78) and would like to open up the conversation to see if a PR would be welcome for this feature!

This filter displays armor pieces that have either an active or deprecated artifact mod currently socketed.

### How does this fit into your workflow?

This filter may be useful to DIM users for the purposes of pre-season prep. Historically, issues have arisen when artifact mods are left socketed in armor during the changeover of seasons (For instance, the recent bug which caused artifice armor to lose its artifice slot permanently) therefore, a quick way to identify any "cleanup" required may be helpful.

**Comment by robojumper** [comment]
DIM can perform this cleanup for you: https://github.com/DestinyItemManager/DIM/wiki/Item-Search#strip-sockets
