### ISSUE TITLE
Armory View in D1 crashes DIM

### ISSUE THREAD

**Issue by WindedHero** [DestinyItemManager/DIM#8647]
This error occurs when you touch/click the item name in the Destiny 1 item inventory, as you would in the Destiny 2 item inventory to view wishlist items and duplicates. It completely bricks the app, cannot load another section or refresh to remove the error. 

Version 7.31.0.1001932 (beta), built on 8/21/2022, 11:33:52 PM

**Comment by delphiactual** [comment]
should also remove links to destinysets for D1 and hashlookups

**Comment by delphiactual** [comment]
starting with D2 account loaded and switching to D1 provides a error header
![image](https://user-images.githubusercontent.com/4798491/186022857-37599da5-b943-4fc5-95ee-1d59f26b9027.png)

starting with D1 loaded causes the above error.

**Comment by bhollis** [comment]
Hmm, the armory link shouldn't even be there on D1. Armory was never supported for D1. I'll investigate when the D1 API is back.
