### ISSUE TITLE
Perks in Loadout Builder do not point to Bungie.net

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#865]
The perks should use the bungie.net url instead of the bundled images.

![cr0plbrvmai9fuf](https://cloud.githubusercontent.com/assets/984608/18351857/75a7b88a-75a1-11e6-9e78-debf249b880b.jpg)

**Comment by bhollis** [comment]
I'll get it once b.net is back.

**Comment by bhollis** [comment]
@ericnelson0 fixed this.
