### ISSUE TITLE
Will not let me save from d2armorpicker

### ISSUE THREAD

**Issue by nickyst1x** [DestinyItemManager/DIM#8651]
### DIM Version

7.31.1

### Browser Details

Safari 

### OS Details

iPhone 

### Describe the bug

Will not let me save a load out I created on d2 armor picker even if recreated on the app .

**Comment by delphiactual** [comment]
screenshot / logs / anything

**Comment by nickyst1x** [comment]
> 

![6C0DC662-8B12-4642-A75A-A1BDC6DC84B5](https://user-images.githubusercontent.com/111992557/186444346-c3f8f662-0436-45a4-b3bb-b148152e70ca.jpeg)

**Comment by delphiactual** [comment]
show full subclass loadout please or link from d2armorpicker

**Comment by nickyst1x** [comment]
id:'6917529203665640480' or id:'6917529798563402412' or id:'6917529615697510151' or id:'6917529798539943584'

**Comment by delphiactual** [comment]
so the only thing is the armor?

**Comment by nickyst1x** [comment]
Yes because I don’t need any of fragments to get what I want

**Comment by nickyst1x** [comment]
Still will not let me save a loadout is there a max of loadout you can have ?

**Comment by delphiactual** [comment]
no

**Comment by delphiactual** [comment]
do you already have a loadout with that name?

**Comment by nickyst1x** [comment]
Ok no I didn’t but it seem to have fixed it self thanks for the help
