### ISSUE TITLE
It is hoped to increase the sorting by the total attribute value of clothing

### ISSUE THREAD

**Issue by zqq-nuli** [DestinyItemManager/DIM#8654]
### Proposed change

In the sorting options, how to add one to sort according to the total attribute value of equipment

在排序的选项中怎加一个按照装备的总属性值来排序

### How does this fit into your workflow?

As long as players play for a long time, the warehouse will accumulate an abnormally large amount of clothing equipment. However, in order to pursue more six-dimensional attributes, it is difficult for some players to choose some equipment. However, some equipment with a low total attribute value may not be needed, but it will be troublesome and take a lot of time to clean up. Therefore, I urgently hope to add this function. I am a guardian and a web developer, However, the framework I am familiar with is that Vue is not react, so I may start to slowly try to understand react.

因为只要游玩时间过长的玩家，仓库就会积累异常多的服装装备，但是某些玩家为了追求更多的六维属性，所以难以取舍一些装备，但是某些总属性值很低的装备可能并不需要，但是清理起来会很麻烦 需要花费大量时间，所以迫切希望可以新增这个功能，我是一名守护者的同时也是一名web开发者，不过我熟悉的框架是Vue并不是React，所以我可能会开始慢慢尝试理解React。

**Comment by bhollis** [comment]
Thanks for the suggestion. We don't generally add inventory sort properties that are based on values not visible on the item tile. Instead, please make use of [Item Search](https://github.com/DestinyItemManager/DIM/wiki/Item-Search), [Compare](https://github.com/DestinyItemManager/DIM/wiki/Compare), [Organizer](https://github.com/DestinyItemManager/DIM/wiki/Organizer), [Custom Stat Total](https://github.com/DestinyItemManager/DIM/wiki/Custom-Stat-Total), and (Loadout Optimizer](https://github.com/DestinyItemManager/DIM/wiki/Loadout-Optimizer) to help decide which items to keep - they're all designed with that in mind. You may also want to use a community-developed search like https://github.com/TMMania/Vault-Analyzer
