### ISSUE TITLE
Artifact Mods vendor from seasonal artifact shows second grid of deprecated mods

### ISSUE THREAD

**Issue by robojumper** [DestinyItemManager/DIM#8657]
This can be reached by clicking the seasonal artifact on the main inventory screen, then choosing "Preview Artifact contents" in the item popup. First season this is happening.

![grafik](https://user-images.githubusercontent.com/14299449/186942797-f1a27922-2c13-4c69-b5fb-7e7349866611.png)

**Comment by delphiactual** [comment]
https://github.com/Bungie-net/api/issues/1712

**Comment by robojumper** [comment]
This was fixed in #8688.
