### ISSUE TITLE
Proposal: Weapon loadout optimizer

### ISSUE THREAD

**Issue by bjacobel** [DestinyItemManager/DIM#8658]
### Proposed change

The Loadout Optimizer currently deals only with armor and armor mods. I'm interested in a similar feature for _weapons_, where the constraints would be:

* what shield types you need to be able to break
* what champions you need to be able to stun
* optionally, a specific exotic weapon you want to use
* optionally, specific pinned legendary weapons
* [stretch goal] optionally, a weapon type you want to run (eg: I gotta have a glaive)

and the outputs would be weapon loadouts with:

* a kinetic, energy and heavy weapon
* a list of arms/class item mods you need to equip

From the results view you could equip these weapon loadouts or save them to a loadout (or pull them into a WIP loadout if you got to the weapon loadout optimizer from the loadout creation view).

This would be a separate view from the armor optimizer but could probably re-use some of that code (? The tricky part here I guess is part of the "weapon loadout" is armor mods, so you need to link those things somehow.)

Quirk: There are armor exotics that give anti-champ functionality to any weapon. Not sure how that would fit in.

### How does this fit into your workflow?

I think this feature would be very useful for those putting together builds for GMs. I usually run either solo or in a mic-less fireteam so I try to cover all shields+champs myself if I can. With the addition of all the new exotics with intrinsic champ mods there's a lot to remember when trying to piece together a loadout. I would use this probably in combination with when I'm already using the armor optimizer before running a GM or other endgame PVE content because that's when I'm thinking about what burns I need to worrying about and what mods/armor exotics would be useful and trying to figure out how many modslots to reserve for champion mods.

It looks like [a similar proposal](https://github.com/DestinyItemManager/DIM/issues/7376) was closed as "Not Planned" earlier but this proposal is maybe more narrowly targeted (at least initially) on generating weapon sets that break shields/champs rather than on weapon perks that synergize with builds.

**Comment by bhollis** [comment]
I think the bit we'd need to work past, that's stopped me from going further on this before, is how this isn't just a search. That said I'd definitely be open to thoughts on what a good UX for this would be.

**Comment by bhollis** [comment]
This seems less relevant post-Lightfall.
