### ISSUE TITLE
New Items Issues with Icons

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#866]
When an items is marked as new, there is an artifact in the icon where the image is above the expected location.

![cr1djfbvmaam_rp](https://cloud.githubusercontent.com/assets/984608/18351883/9bc71452-75a1-11e6-924f-f372ff48d300.jpg)

**Comment by ericnelson0** [comment]
I can't reproduce this locally. Is it on the beta branch? With or without animations?

**Comment by SunburnedGoose** [comment]
I don't know.  I'm just getting screenshots on Twitter.  It's happened to several people.

**Comment by shockthealien** [comment]
Yup, it happened to me this morning when i updated

**Comment by shockthealien** [comment]
![photo 08-09-2016 09 42 04](https://cloud.githubusercontent.com/assets/2083273/18352905/2ad589d6-75d8-11e6-8975-197f2176d666.jpg)
![Uploading Photo 08-09-2016, 09 42 53.jpg…]()

**Comment by shockthealien** [comment]
looks like the new item overlay is not overlaying and rather just displaying underneath

**Comment by SunburnedGoose** [comment]
Animated or static image?

**Comment by shockthealien** [comment]
it was animated, i remember i questioned whether to capture a video instead because of it

**Comment by bhollis** [comment]
This is probably because I made the images actual IMG tags instead of
backgrounds

**Comment by SunburnedGoose** [comment]
The reason they were not image tags is because IMG tags have their own drag behavior.  You don't get the whole div with the yellow border, etc.  You have to use the background-image feature of the DIV to get this to look good.

**Comment by ffilll** [comment]
I'm seeing the issue on Chrome version 52.0.2743.116 m.  I'm using DIM version 3.9.2.364.
![screen_grab](https://cloud.githubusercontent.com/assets/22078854/18353599/9dfd487c-75b0-11e6-9816-2c2a7978a733.PNG)  What I'm seeing is on the whole page.  It appears on every item except in the General and Reputation category.  Ghosts and banners and artifacts are all appearing this way on my screen.

**Comment by ericnelson0** [comment]
Ah, ok. I haven't pulled yet. I'll do that now.

**Comment by bhollis** [comment]
Ok, I'll fix it tonight

**Comment by bhollis** [comment]
OK I'll fix it whenever the API comes back...
