### ISSUE TITLE
Upgrade level does not work on ghosts

### ISSUE THREAD

**Issue by Aholicknight** [DestinyItemManager/DIM#8664]
### DIM Version

7.31.1

### Browser Details

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edge/105.0.1343.10

### OS Details

Windows 11

### Describe the bug

https://user-images.githubusercontent.com/7843719/187010903-634231b4-e65f-4f14-b5a0-c5d51ccd6a88.mp4

For some reason if you want to preview a power level for a ghost it will not load.

**Comment by tsuther-ludvik** [comment]
Hello! I was looking to contribute and saw this as a good first issue. 
Does anyone have thoughts on what the display should be? Right now I have this:
![Screenshot 2022-09-10 182449](https://user-images.githubusercontent.com/98835644/189505056-b3a13f49-5519-4ef3-a285-597a15a109eb.png)

**Comment by trevor-sutherland** [comment]
Oops. I was on my work git account for the above comment. This one is my personal.

**Comment by Aholicknight** [comment]
> Hello! I was looking to contribute and saw this as a good first issue. Does anyone have thoughts on what the display should be? Right now I have this

@trevor-sutherland @tsuther-ludvik what did you do to show the ghost energy level? I am still having the same error.


https://user-images.githubusercontent.com/7843719/189706975-b42527ac-1476-4701-84a1-f32144266321.mp4

**Comment by delphiactual** [comment]
They are working on a feature

**Comment by robojumper** [comment]
I believe this is fixed now.
