### ISSUE TITLE
Saved Search Queries Missing

### ISSUE THREAD

**Issue by hendersj** [DestinyItemManager/DIM#8665]
### DIM Version

Version 7.31.1.1001939 (beta), built on 8/26/2022, 5:36:36 PM

### Browser Details

104.0.5112.101 (Official Build) (64-bit) 

### OS Details

openSUSE Leap 15.4

### Describe the bug

With one of the recent updates, the starred queries seem to have disappeared.  I recently had some issues with DIM Sync not working (not sure if this is related or not), so I had disconnected and reconnected to DIM sync, and in the export taken during that process, I do see the search queries present, but even after a re-import, they're not there.

I'm not sure what logs would be useful here, since it's not an activity - it seems to just be missing data.  Let me know what steps I can take to provide useful logs or data (happy to provide the JSON export if that's of use).

**Comment by Zirake** [comment]
I am also noticing this issue, I was about to submit a bug regarding this as well. I can export the JSON and within there you'll see "saved":true results for queries, however they do not appear. If you check the search history as well under settings, nothing appears. If my JSON file will help as well, I can upload it.

Thank you!

**Comment by hendersj** [comment]
That's good to know, I had wondered how I was going to handle newly tagged items (I tried importing the saved JSON before opening the bug, and lost a few tags that I had set up).  Sounds like it's just the search field history/display of saved searches that's not working properly.

**Comment by Zirake** [comment]
Yeah that's what I also did. That way I can rule out maybe the current data missing the search history, and even after importing, still nothing. I agree with you, probably just something with reading the history/favorites data into the search field while typing.

**Comment by DanishAce** [comment]
Me too, I can not even store new favorite searches between sessions, they will be there until I close the DIM session, when I come back they are gone. They will also disappear immediately after going to "View and edit search history" found under "Filters Help..." in the search bar. The searches will be displayed in the "View and edit search history" for a very short while, and then be cleared.

**Comment by delphiactual** [comment]
https://twitter.com/ThisIsDIM/status/1563292696239751168

**Comment by hendersj** [comment]
That explains it, thanks.  Is it possible to have them shown if DIM sync is off?  On balance, I'd rather have the saved searches (at least) available, since the ones I've created are quite complex and have become a part of how I manage my inventory.

**Comment by bhollis** [comment]
Again, they're not gone, and they'll return automatically when they are reenabled.

**Comment by hendersj** [comment]
I was looking at a new export and didn't see them there, where I had seen them in the export that I had from when I turned sync off.

But if the original searches will overwrite anything that's local when it's reenabled, that's good to know.

**Comment by GHOSTJR12** [comment]
Restarting DIM sync did not work for me. I am glad to see others having the same issue.
