### ISSUE TITLE
Tracked Triumphs Fully Resets between DIM sessions

### ISSUE THREAD

**Issue by Neothopolis** [DestinyItemManager/DIM#8668]
### DIM Version

7.31.1

### Browser Details

FireFox Desktop (likely current) and Mobile (104.1.0 (Build #2015898515), 99759dd72+)

### OS Details

Windows 10 and Android 12 (July 2022 Security Update)

### Describe the bug

When the season 18 launched, all of my tracked triumphs reset and were no longer tracked. I tried tracking them again, but they've reset again as well.
I'm not sure if it's me having DIM open on multiple devices and it's not syncing right with all the API issues. I cannot confidently say that I have DIM closed on my computer as I write this on mobile.

**Comment by bhollis** [comment]
Tracked triumphs are disabled in the DIM API while we deal with massively increased load.

**Comment by Neothopolis** [comment]
Good to know! I wondered if that was the case. Thanks for the reply.
