### ISSUE TITLE
Add an option to give notifications their own "column"

### ISSUE THREAD

**Issue by chrisfried** [DestinyItemManager/DIM#8669]
### Proposed change

This might just be a "just me" problem, but I'd like the option to add a large enough margin on the right side of the Vault so that I can still see all of my items while I have a large number of pending transfer notifications active.

![image](https://user-images.githubusercontent.com/422381/187055859-5c5a3429-941c-4484-b7d8-72881300342b.png)

![image](https://user-images.githubusercontent.com/422381/187055889-9f9bc420-36e7-424b-8f95-ca65d6981d66.png)

### How does this fit into your workflow?

Sometimes, I type in a search, and then I manually queue up a bunch of transfers, which covers one or more further items that I would also like to transfer. Sure, I can clear each of the notifications, but that becomes quickly tedious.

**Comment by bhollis** [comment]
It's definitely an interesting idea. I think it's particularly bad right now when moves are very slow. I still recommend just clicking the popups to dismiss them - I can't quite figure out how it would work to make space for them (would the space appear and disappear when notifications show up, or would there always be space there?).

I've always wanted to replace these notifications with something more subtle, but people seem to *really* have trouble understanding when a transfer is pending without them.

**Comment by chrisfried** [comment]
I'm all for "solving" this by coming up with a more subtle replacement for the toast notifications. I don't have any suggestions off the top of my head, but I'll let that thought simmer.

**Comment by inexorableAce** [comment]
Could just stick them all in a Notification Center and only pop out yellow / red / complex alerts? 

So you have a place to view everything basically and if bungie is taking a while we pop that out.  If something fails we pop that out. And if you're doing like something with progress (a loadout or something) we can pop that single progress one. 

Would cut down in the main complaint which seems to be quick adhoc moves. And things that succeed over and over anyway.

**Comment by bhollis** [comment]
Quick adhoc moves only stay up for 2 seconds after completing though - I'm not sure they're that obtrusive? They exist because people really don't know that items are moving if we don't show something.

**Comment by chrisfried** [comment]
Like I said, it may be a me problem. If I initiate enough manual moves, even those two seconds feel an interminable wait. Almost long enough to take a couple screenshots and create an enhancement request.

**Comment by bhollis** [comment]
Understood. I don't really do manual moves so much anymore, it's all searches and loadouts.
