### ISSUE TITLE
DIM continuously loading 

### ISSUE THREAD

**Issue by Caluben** [DestinyItemManager/DIM#8670]
I have been having an issue with DIM continuously loading and never actually working. I think it might have something to do with a software called Qstudio, which my parents downloaded onto my computer about a month ago, as it worked perfectly fine up until that point. It works fine on my iPad so I know it's not my connection to anything. The website works just fine and I can navigate through everything, it just doesn't load anything. 
![image](https://user-images.githubusercontent.com/65260869/187077321-18ec3164-531b-4d42-943a-706dff776d70.png)

**Comment by bhollis** [comment]
I'm sorry, you did not include enough info in the report as was requested, so we cannot help.
