### ISSUE TITLE
Temporary Sort Options in Search Bar

### ISSUE THREAD

**Issue by CyberTacoX** [DestinyItemManager/DIM#8674]
### Proposed change

I would absolutely love the ability to temporarily sort by a particular stat (or total stats for that matter) from the search bar, completely overriding the default sort order. For instance, something like "sort:reload" could temporarily change the order weapons are shown in (with weapons that don't have a reload speed per se, like swords, put at the end. Likewise, something like "sort:recovery" would of course be useful to quickly find the armor piece with the highest recovery.

Additionally, something like "sort:stattotal" to sort weapons and especially armor by their total stats added up would be incredibly handy as well.

### How does this fit into your workflow?

I have a perfect example right now. I have a bounty to take out enemies with shotguns. I have several shotguns, but I'm not a shotgun kind of person and I don't know mine well. Since I'm just gunning down redbars, by far the most important stat for me is going to be reload speed. I would find it REALLY useful to search for something like "is:shotgun sort:reload" to have my shotguns highlighted and in order by fastest reload to slowest.

This happens to me all the time with bounties for weapons I don't use very much. If I could temporarily sort by an important stat, that would save me a lot of time and trouble.

**Comment by bhollis** [comment]
Try out the Compare. Or Organizer functions, they're designed for this.
