### ISSUE TITLE
Destiny 2 account Working, But Destiny 1 account NOT Working 

### ISSUE THREAD

**Issue by SnowyEgress** [DestinyItemManager/DIM#8676]
Destiny 2 item manager works completely, but is slow (maybe its network congestion, or my connection) 

However, when I attempt to load my Destiny 1 account I get this message:

" Unable to load your Destiny 1 characters and inventory TypeError BungieService.NotConnectedOrBlocked
You may not be connected to the internet, or an ad blocking or privacy extension may be blocking Bungie.net. "

I don't have any ad blockers installed, nor a vpn, so I am not sure why I am getting this message. Or, why Destiny 2 works fine and Destiny 1 does not. 

I've gone through all the troubleshooting steps but the message persists. 
Please help if you can, thanks.

**Comment by delphiactual** [comment]
Dupe https://github.com/DestinyItemManager/DIM/issues/8666
