### ISSUE TITLE
D2 King's Fall raid armor needs modslot: filter, CSV export

### ISSUE THREAD

**Issue by DHager** [DestinyItemManager/DIM#8679]
### DIM Version

Version 7.32.0.1001952 (beta), built on 8/30/2022, 12:43:37 PM

### Browser Details

Version 104.0.5112.102 (Official Build) (64-bit)

### OS Details

Windows 10

### Describe the bug

What already works:

1. The new King's Fall raid armor can be found with `source:kingsfall`
2. Clicking on the armor shows a "King's Fall Mod" and what mods may be used

What's missing:

1. No `modslot:` search filter, e.g. `modslot:kingsfall`
2. No information on the additional mod-slot is present in the Armor CSV export, only the usual `combat` slot.

**Comment by delphiactual** [comment]
the modslot was just declassified...

**Comment by DHager** [comment]
> the modslot was just declassified...

I know. I'm not casting blame, I'm just adding something I didn't see already on the to-do list.
