### ISSUE TITLE
Allow rare items to be considered in loadout builder

### ISSUE THREAD

**Issue by philipmat** [DestinyItemManager/DIM#868]
Currently (v3.9.2) the loadout builder only allows legendary and exotics.  
On occasion, and particularly in the early stages of character build-outs, a player might have higher level Rare items, or no Legendary/Exotics at all for a given spot. In the latter case, the Loadout builder does not work at al: *"Missing legendary or exotic pieces to build a full set!"*.

Please consider allowing Rare items to be used in building Loadouts, even if it's via an advanced option.

**Comment by geck0s** [comment]
Also, when using Current Light mode under advanced options, Legendaries under 280 should still be considered but they are currently unavailable in the "show titan gear" section and I would guess they are left out of the set making, though I didn't specifically try to test for that.
