### ISSUE TITLE
Bundle dependencies and code using Webpack

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#869]
A LONG TERM goal for DIM was to start bundling our dependencies.  This has come consequence that needs to be considered.  
1. Bundle source code
2. Bundle vendors
3. Watch source and rebundle
4. Adding new files
5. Adding new vendors
6. Updating Index File with latest bundle hashed filenames.

**Comment by bhollis** [comment]
Definitely. I have something half-built in a branch but I haven't had a chance to get back to it.

**Comment by joshhunt** [comment]
👋 Happy to help out where I can! Webpack's the sort of thing I guess where its very easy to step on other people's toes and waste effort, so I'm happy to do as much (or little) to move this forward, given some direction.

**Comment by bhollis** [comment]
Nice! This is a great step. I agree that we should get babel going - we can use the plugin to auto select the minimum transforms to support our target platforms, plus babili for modification and ng-annotate for automatic $inject. I can work on that if you're not already doing it - I got stalled because I didn't have webpack working yet. 

-Ben

**Comment by bhollis** [comment]
It's also worth testing if combining scripts actually helps performance. With HTTP/2, it's generally suggested to not concatenate since multiple small requests can be handled better that a large one. 

-Ben

**Comment by SunburnedGoose** [comment]
@joshhunt What should we be looking out for?  We're incrementally updating our build process so atm all of our code is ES5.

**Comment by joshhunt** [comment]
First up, Webpack 2 is in a pretty stable now (I think its in RC or something, I've been using a much earlier beta in a project for a while and its fine), so I would recommend we go with that from the start. There's not too much different (in terms of config and using it) from Webpack 1, so it should be fine. [Docs are on this new site](https://webpack.js.org/configuration/).

Personally, I think the priority is to bundle everything together first, building your dependency graph using imports/requires. This would require 'minimal' code changes to the application, but we would have to go through and make sure that every source file and external dependency is 'required' from some place.

There's a bunch of ways to architect this for an Angular app (or so I've read, I don't really use Angular all that much), but I think the best way for now would be to treat... `dimApp.module.js` as the entry point and add a whole bunch of imports at the top:

```javascript
import "scripts/dimApp.config";
import "scripts/dimApp.i18n";
import "scripts/services/dimActionQueue.factory";
import "scripts/services/dimBungieService.factory";
import "scripts/services/dimDefinitions.factory";
import "scripts/services/dimManifestService.factory";

angular.module('dimApp', [
    'ui.router',
    'timer',
    ...
])
```

We would also need to import at least Angular at the top of every file (that uses it). Technically you could use `webpack.ProvidePlugin()` to make it 'global' to every module, but I'm not really a fan of that.

Adding a babel config to pop in ES6+ syntax as we go would also be a great idea. [`babel-preset-env`](https://github.com/babel/babel-preset-env) is all the rage these days as a good preset to use.

And then I guess a switch to generate 'production' and 'development' builds (to minify) would also be recommended. 

This might sound like a lot, but I think it's *fairly* straightforward. That should be the target for the 'first release' of webpack. After that we can work on reaping the benefits like seperate vendor builds, ng-annotate, directive templates, etc.

I'm happy to build on what's been done here and take a stab at the above, as long as I don't step on anyone toes. I should be able to get something solid done today...

**Comment by joshhunt** [comment]
Oh, few other random points:

- WebpackDevServer during development to serve out and watch for changes in files.
- Not 100% sure on the best way to get the build to work nicely for both a Chrome Extension AND a published website (in terms of asset URLs), but it shouldn't be a showstopper.
- Using `[hash]` in the output filename, together with `HtmlWebpackPlugin` is a great way to hash the files and update the index.html file to reflect the URLs
- CSS-Loader + ExtractTextPlugin should be good to handle the CSS with webpack. This should also sort out the Hotkey CSS and Font Awesome stuff
- Should be able to move most of the deps to package.json, and make sure the the build artefacts aren't committed to git.

**Comment by SunburnedGoose** [comment]
@joshhunt Go for it. The branch is up to date so it's yours to build upon.

**Comment by SunburnedGoose** [comment]
FYI, the zip.js module has js files that are loaded by the zip.js file.  These can't be front-loaded in the bundle.  I was going to try to copy the files during a build step to the vendors folder as we do now, but without the use of bower.

**Comment by bhollis** [comment]
I like everything you're saying here !

-Ben

**Comment by bhollis** [comment]
Also, not sure if it's clear, but we're using es6 extensively in the existing code. 

-Ben

**Comment by delphiactual** [comment]
Couple of issues that remain on the webpack branch.

When running LoadoutBuilder the following error occurs:
```
angular.js:14328 TypeError: tierString.split is not a function
    at dimMinMax.controller.js:569
    at underscore.js:399
    at Function._.each._.forEach (underscore.js:153)
    at Function.groupBy (underscore.js:398)
    at step (dimMinMax.controller.js:568)
    at angular.js:19916
    at completeOutstandingRequest (angular.js:6111)
    at angular.js:6390
```

The following html files do not load:
 - About
 - Support
 - Settings
 - Filter
 - Infuse
 - Xur

**Comment by delphiactual** [comment]
@joshhunt I tried to get this working but something about `context`...

https://github.com/DestinyItemManager/DIM/blob/dev/app/scripts/shell/dimAppCtrl.controller.js#L141

**Comment by joshhunt** [comment]
Yeah... you need to be careful when doing dynamic requires with Webpack. If
you make this a simple expression in the form of 'require('views/' +
viewname + '.template.html')' it *should* work. Gotta make sure the
templates have the extension .template.html so they get loaded correctly.

Otherwise if the dynamic require/context doesn't work, you could just
always great an object of all the languages that way webpack has static
requires that it can understand easier.

Or I'll check it out tomorrow in the new year :)

**Comment by delphiactual** [comment]
I figured it out, I was missing the `template` part of the file and that did the trick #1308

**Comment by bhollis** [comment]
Closing this because we're well on our way!
