### ISSUE TITLE
Filter vendors items by types of currency

### ISSUE THREAD

**Issue by kennedy** [DestinyItemManager/DIM#8690]
### Proposed change

Often I look at the Ventors tab in DIM and toggle `Only show uncollected items`, this change will allow the user to not display items that _only_ cost silver.

### How does this fit into your workflow?

Often I would like to see what missing items purchasable with Bright Dust or Legendary shards. I don't want to use Silver but Tess Everis has so many silver currency items. It is difficult to quickly see what I am missing.

**Comment by bhollis** [comment]
It'd be nice, yeah.

**Comment by tjames192** [comment]
I wrote this little JavaScript today, you can use this in the console window.

```
(function() {
    rows = document.getElementsByTagName('div');
    results = [];
    silver = [];

    // VendorItem
    for (var i = 0; i < rows.length; i++) {
        className = rows[i].className;
        match = className.match("VendorItem-m_vendorItem");
        if (match) {
            results.push(rows[i]);
        }
    }

    // Items costing silver
    for (var i = 0; i < results.length; i++) {
        try {
            title = results[i].children[1].children[0].attributes.title.value
            title = title.match("Silver")
            if (title) {
                silver.push(results[i]);
            }
        } catch {}
    }

    // set Silver items display to none
    for (var i = 0; i < silver.length; i++) {
        silver[i].style.display = "none";
    }

})();
```
