### ISSUE TITLE
Add Folders to Character DropDown Menu

### ISSUE THREAD

**Issue by Zurnic** [DestinyItemManager/DIM#8694]
### Proposed change

I know I'm not the only one who has more loadouts than they'd care to admit. It would be useful to have the ability to create folders so that I could group certain loadouts together ie all the arc loadouts, all the builds from a certain creator, etc.

### How does this fit into your workflow?

I currently have to scroll for a long time to find the specific loadout I'm looking for or use the search feature which can take a while.

**Comment by bhollis** [comment]
Duplicate of #7663
