### ISSUE TITLE
Incorrect destination shown on claimable engrams

### ISSUE THREAD

**Issue by Pieontoast** [DestinyItemManager/DIM#8695]
### DIM Version

Version 7.33.0 (release), built on 05/09/2022, 13:48:02

### Browser Details

Chrome,  104.0.5112.105

### OS Details

Chrome OS, Windows 11

### Describe the bug

When selecting an item from a non tower based vendor, the text below the title says "must go to the tower to retrieve this item", even when the vendor is Xur in eternity for example. It is the same with star chart, crown of sorrow, war table in the HELM and starhorse.
![image](https://user-images.githubusercontent.com/113069718/188996447-a478a5a4-f557-4238-8e23-d0eb079a6e85.png)

**Comment by delphiactual** [comment]
That is the error wording from bungie
