### ISSUE TITLE
Loadout mods for unequipped armor (and subclass?)

### ISSUE THREAD

**Issue by broady** [DestinyItemManager/DIM#8698]
### Proposed change

Allow mods to be slotted into unequipped armor in a loadout. Less important but also good would be to set up multiple subclasses.

### How does this fit into your workflow?

Needed for situations where hot swapping armor is a thing. For example, in DSC I swap to a loadout using Cuirass for the 2nd encounter and to Aeon Safe for final encounter. Currently able to get all of this set up by using loadouts for each encounter and equipping all of them while in orbit, but would be nice to have a single loadout to cover all encounters.

**Comment by bhollis** [comment]
I understand the desire, but loadouts really aren't oriented around managing your non-equipped items. It's better to have multiple loadouts and set the mods for each one.
