### ISSUE TITLE
Feature Request:  Auto-balance materials/synths/etc...

### ISSUE THREAD

**Issue by joshgarnett** [DestinyItemManager/DIM#87]
This is very much on the nice to have list, but it'd be handy to just click a button and have it automatically distribute certain items evenly across all of your characters.  For class based materials, such as sapphire wire, it'd be great if it could just automatically move those to the correct class.

**Comment by Mulchman** [comment]
I wrote a feature like this for a different extension based off of DIM. I like your idea of automatically distributing the class materials, and wanted to poke in and say thanks for that.

**Comment by kyleshay** [comment]
follow along in #398
