### ISSUE TITLE
Unsupported browser (iPadOS 15.7)

### ISSUE THREAD

**Issue by J-Wo** [DestinyItemManager/DIM#8702]
### DIM Version

Version 7.34.0.1001972 (beta), built on 2022-09-12, 10:46:37 AM

### Browser Details

Safari version 15.6,2 (Engine: WebKit)

### OS Details

iPadOS 15.7

### Describe the bug

After upgrading my iPad to iPadOS 15.7, DIM beta now reports that my browser is unsupported. 
![0420ABF5-4576-482A-AA1D-F11F64B1E4D3](https://user-images.githubusercontent.com/25711856/189961610-6bad797c-f1c8-478d-8e62-67beaaff85fd.jpeg)

**Comment by bhollis** [comment]
Can you go to https://www.whatismybrowser.com/detect/what-is-my-user-agent/ and copy/paste your user agent string here?

**Comment by TheGokki** [comment]
> Can you go to https://www.whatismybrowser.com/detect/what-is-my-user-agent/ and copy/paste your user agent string here?

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6,2 Safari/605.1.15` with my iPad Pro on iPadOS 15.7

**Comment by bhollis** [comment]
Is this still happening?

**Comment by J-Wo** [comment]
No seemed to be a one time thing that resolved itself.
