### ISSUE TITLE
Duplicate loadout

### ISSUE THREAD

**Issue by Aholicknight** [DestinyItemManager/DIM#8706]
### Proposed change

I would love a feature to duplicate a previously created loadout. Doing this a player can quickly make PVE or PVP loadouts with only changing the subclass while keeping the same mod placements and other stuff that does not need to be changed. 

### How does this fit into your workflow?

I can quickly create subclass loadouts for PVP or PVE instead of remembering where mod placements go and other stuff I have equipped such as weapon mods.

**Comment by delphiactual** [comment]
Loadouts -> `Edit`-> Change Name -> `Save as New`

**Comment by Aholicknight** [comment]
> Loadouts -> `Edit`-> Change Name -> `Save as New`

Did not know that this duplicates the loadout, I thought this would just rename the loadout. Thanks for resolving this issue!
