### ISSUE TITLE
When Farming mode is active, it will fight item movement

### ISSUE THREAD

**Issue by Zero834** [DestinyItemManager/DIM#8707]
### DIM Version

Version 7.34.0 (release), built on 9/11/2022, 8:55:05 PM

### Browser Details

Chromium: 105.0.5195.127 (Official Build) (64-bit)

### OS Details

Windows 10

### Describe the bug

When farming mode is active, transferring an item from one character to another when vault space is limited will cause farming mode to fight with item movement.

Farming mode should pause when items are manually being moved or should lose priority. 

https://user-images.githubusercontent.com/54686180/190353489-e7bf56c3-2512-4aa3-b51d-1bf0df0e8f65.mp4

**Comment by bhollis** [comment]
Hmm, it's supposed to pause during moves, I'll look at it.

**Comment by bhollis** [comment]
I haven't been able to reproduce this.
