### ISSUE TITLE
Custom Stats: Does not include MW or Mods

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#8708]
![image](https://user-images.githubusercontent.com/4798491/190430662-b4c43c01-6f7b-4116-b6fe-73a2d2840719.png)

Maybe it shouldn't include mods, but it definitely should include masterwork.

**Comment by bhollis** [comment]
Custom stat is always base stat to allow for comparison with other armor regardless of masterwork status.
