### ISSUE TITLE
Delay of ALL items showing in postmaster

### ISSUE THREAD

**Issue by kornholeo** [DestinyItemManager/DIM#8709]
### DIM Version

1.0.0.1

### Browser Details

firefox and Windows edge

### OS Details

w 10

### Describe the bug

The postmaster has a total of 21 "slots" to catch overflow of incoming items. Apparently the backlog of items that are in "postamster inventory" are more than what you actually see when you view your PM inventory. Even when the viewable quantity is lets say 15 items, when you go to the tower, and then interact with the PM to retrieve those items, you will see that those 15 items you previously saw in PM were in fact 25+ items and those 25+ items overflowed the "container", thus shoving out the residing pieces because that were already in PM. Last night when i finished playing game, i purposely removed items from my PM so that I hade ONLY 15 items showing (in PM)..this am.m when i logged back in, my PM was FULL again, and the items residing on top 2 lines were forced out to make room for the incoming, PREVIOUSLY UNSEEN inventory....making several weapons and armor permanently disappear! This happens constantly, and indicated there is a serious lag between what you SEE IN YOUR PM vs. whats truly in your PM thats in cue to actually GO TO your PM.
This causes major problems loosing exotic weapons AND RESOURCES by forcing them out via overflowing, when in fact the player's last view of his/her PM showed the PM slots were only 1/2 occupied!
WHY DOES THIS HAPPEN, AND CAN IT BE FIXED???????

**Comment by bhollis** [comment]
I'm afraid this isn't a DIM issue.

**Comment by kornholeo** [comment]
Please enlighten me on who's issue it is then, and any contact info for
them you can share.
Thanks!

**Comment by bhollis** [comment]
Either:

1. You haven't refreshed DIM's view of your inventory(the icon in the top right of the page) and are thus seeing outdated data. 
2. There's some complex behavior in the game or the API as you describe, which leaves our view behind what's visible in game. This would be Bungie's responsibility.

**Comment by kornholeo** [comment]
I've refreshed the view multiple times AFTER finishing my last encounter to
make sure everything I was seeing was accurate and there would be no
"stragglers".
I then would pick n choose certain pieces in PM and pull.them out so I
could manually bring the item count down to, lets say 15 items...leaving 6
open spaces.
I then refresh view of PM several times, still seeing only 15 items in PM.
I spawn in to tower, go to the postal station, open up PM, and see that's
it's either TOTALLY FULL OR OVER FLOWING....AGAIN.
This "hidden lag" can make resources (golf balls, armor, primo 'keeper'
weapons disappear in a blink of an eye.
When the above happens and its 10 golf balls that vanish,  that seriously
gets me pissed off...the major amount of time spent in-game to play for,
and win these resources is substantial.
In the last 6 mos. I've had at least 50-60 golf balls disappear.
I sincerely appreciate your help/time discussing this w/ me and hope you
can direct me to a actual person at bungie that could dive into this
specifically.
Fyi- I am 55, and am very active in game with almost 5400 hours playtime.
My goal is to help fix things, not just complain about something. 👍

If you are 99% sure this is a bungie thing, could you give me someone to
reach out to?

Thanks!
Brian K

**Comment by bhollis** [comment]
I think your best bet is the Bungie support forums.
