### ISSUE TITLE
Infinite Progress Bar while in Maintenance 

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#871]
Can this screen be hidden when there is no data?

![screen shot 2016-09-08 at 2 16 37 pm](https://cloud.githubusercontent.com/assets/984608/18363248/ed45541a-75ce-11e6-8fab-f4066c2adc0e.png)

**Comment by bhollis** [comment]
I'll beef up the error handling. FWIW it clears out for me right now (with "Bungie.net is down for maintenance").

**Comment by bhollis** [comment]
Fixed to show an error message in #880. Things get a little weird when some APIs are working and some aren't - I can still think of situations where this'd get left up such as if the manifest API worked but getPlatforms didn't.

**Comment by bhollis** [comment]
Did this happen again on Monday's maintenance?

**Comment by bhollis** [comment]
Closing for now - reopen if it starts happening again.
