### ISSUE TITLE
Pattern Progress sometimes does not accurately reflect actual in-game pattern completion

### ISSUE THREAD

**Issue by murcurin** [DestinyItemManager/DIM#8710]
### DIM Version

Version 7.34.0.1001974 (beta), built on 9/13/2022, 4:56:07 PM

### Browser Details

Chrome Version 105.0.5195.126 (Official Build) (64-bit)

### OS Details

Windows 11

### Describe the bug

Pattern progress for Ammit AR2 is not correct. I have already crafted this weapon, but the progress indicator on the non-crafted version still shows as 1/2, even after I've completed deepsight extraction on additional copies of the weapon. So far, this is the only weapon I've encountered this bug on, most other weapons seem to reflect the correct pattern extraction status. Deepsight pattern progress for this weapon was also tied to a new seasonal quest which seemed to be a bit buggy about progressing, so this may be a problem with the underlying data that is exposed by Bungie rather than a bug in DIM

![image](https://user-images.githubusercontent.com/113636232/190493767-58023098-710b-4bc3-a9a2-31bd5b82783c.png)

### Logs

```shell
[app] DIM v7.34.0.1001974 (beta) - Please report any errors to https://www.github.com/DestinyItemManager/DIM/issues
instrument.ts:123 Language Detected: en-us
instrument.ts:123 Language Assigned: en
instrument.ts:123 [dim sync] globalSettings Object
log.ts:58 Load manifest: 1631.36376953125 ms
instrument.ts:123 [dim sync] Saving profile data to IDB
log.ts:58 Process inventory: 63.679931640625 ms
log.ts:58 Inventory state update: 6.618896484375 ms
instrument.ts:123 [clicked item] https://data.destinysets.com/i/InventoryItem%3A2119346509 Object
instrument.ts:123 [dim sync] Saving profile data to IDB
log.ts:58 prepareUpdateQueue: 0.2099609375 ms
instrument.ts:123 [flushUpdates] Flushing queue of 1 updates
instrument.ts:123 [flushUpdates] got results Array(1) Array(1)
instrument.ts:123 [dim sync] Saving profile data to IDB
log.ts:58 Process inventory: 75.5810546875 ms
log.ts:58 Inventory state update: 13.064208984375 ms
instrument.ts:123 [clicked item] https://data.destinysets.com/i/InventoryItem%3A2119346509 Object
log.ts:58 Process inventory: 47.0078125 ms
log.ts:58 Inventory state update: 9.533935546875 ms
instrument.ts:123 [clicked item] https://data.destinysets.com/i/InventoryItem%3A2119346509 Object
log.ts:58 Process inventory: 42.69287109375 ms
log.ts:58 Inventory state update: 9.033935546875 ms
log.ts:58 Process inventory: 35.93798828125 ms
log.ts:58 Inventory state update: 9.489990234375 ms
instrument.ts:123 [clicked item] https://data.destinysets.com/i/InventoryItem%3A2119346509 Object
log.ts:58 Process inventory: 42.430908203125 ms
log.ts:58 Inventory state update: 9.783935546875 ms
log.ts:58 Process inventory: 35.005859375 ms
log.ts:58 Inventory state update: 8.5517578125 ms
instrument.ts:123 [dim sync] Saving profile data to IDB
instrument.ts:123 [clicked item] https://data.destinysets.com/i/InventoryItem%3A2119346509 Object
log.ts:58 Process inventory: 53.97705078125 ms
log.ts:58 Inventory state update: 13.505859375 ms
log.ts:58 Process inventory: 39.949951171875 ms
log.ts:58 Inventory state update: 9.466064453125 ms
```

**Comment by delphiactual** [comment]
what does it show in-game in the records?

**Comment by murcurin** [comment]
In the Patterns & Catalysts section of the Triumphs page, it shows 1/2 on
pattern progress. At the relic it shows the pattern as available for
crafting.

**Comment by bhollis** [comment]
It's a known game bug. DIM shows the same thing as everything else.

**Comment by robojumper** [comment]
[Destiny 2 Hotfix 6.2.0.7](https://www.bungie.net/en/Explore/Detail/News/51807) fixed this issue:

> Fixed an issue where players completing the new Season 18 crafting quests failed to have pattern Triumphs unlocked when acquiring the weapon patterns.
