### ISSUE TITLE
Seasonal Artifact Improvements

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#8716]
![image](https://user-images.githubusercontent.com/4798491/190769607-bcc60ced-c5c5-49a4-b833-6658fe86a4bc.png)

![image](https://user-images.githubusercontent.com/4798491/190755126-5b885cb2-b763-4ca0-8c74-228b9821c00b.png)

We should try to replicate this display as much as possible in DIM. We currently are not showing `Next Power Bonus`, `Next Artifact Unlock`, `Unlock Count`, `Available Unlocks`, etc

**Comment by trevor-sutherland** [comment]
I can grab this if nobody else has.

**Comment by trevor-sutherland** [comment]
I think I have all the asset data accounted for except the background image. I see "screenshot" which is close- but looks cut off.
Is there a better solution out there I can pull that I'm missing?

[https://www.bungie.net/common/destiny2_content/screenshots/2871264750.jpg](url)

**Comment by delphiactual** [comment]
I do not think there is a better asset file for background than that

**Comment by jamiesanerd** [comment]
guessing this is open to pick up?

**Comment by bhollis** [comment]
Yup, should be fine to take!

**Comment by bhollis** [comment]
What's left here?
