### ISSUE TITLE
Automatic loadout builder

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#872]
[Some ideas around this from here.](https://www.reddit.com/r/DestinyItemManager/comments/50y7az/bug_saved_loadout_limit/d7eg0bo?context=3)

This might be something we can focus more on post RoI, unless someone is really inclined to get a feature like this in---

The T12 loadout build we have is totally amazing, and is an incredible base to work from. 

What if (akin to the max-light option) we allowed users to automatically equip the highest tier loadout, based on some criteria?

For example (pulled my comment from the post), my "Loadout" has rules defined as (everything would be optional, maybe more):
- "This Exotic"
- "These Legendary items" (maybe you love a specific class item, even if it would be better to use another for more T12 options.)
- "These Perks"
- "Must have at least T5 int"
- "Must have at least T4 dis"
- "Must have at least T1 str"

You know your armor best, but DIM might find two T12 loadouts, a 5/5/2 loadout and a 5/4/3 loadout, and just pick one... You could instead say at least T5 int, T5 dis, T1 str, and will load a T12 set if possible, otherwise loads a T11 set that matches.

The idea for this is that it would allow you to easily copy the rules for one loadout, and change a minor rule. I might want to copy all of my rules, but instead of "locking" the shotgun reloader perk, I lock a "sniper reloader perk" so I then have two loadouts that always update based on whatever gear I have, but w/ a sniper perk instead of a shotty perk...

Would this buy us anything more than that Loadout builder gives us, or would we actually be losing func?

Thoughts?

**Comment by MistaTwist** [comment]
I'm imagining a small set of "focus" drop-downs, that update based on equipped weapons, with a checkbox-type lock next to each so you can re-apply it like you say above. So you could select, say, Ammo, Reload, Switch etc for each of your weapons, and not be tied to a weapon type. Is that what you were thinking? So, as per your example above, you'd build a loadout for with "reload" selected and locked against the special weapon slot. 

I don't think it would lose func moving forward if it was in the right place, and showable/hideable, perhaps as an "advanced" kind of thing in the loadout section. Intriguing stuff though!

If I can get up to speed, I might try this out, but I'm an Angular novice, so I might be a while!
