### ISSUE TITLE
[Feature Request] Option to have a notification at the top right corner of DIM when ada-1 or banshee is selling a armour or weapon mod that you don't own yet

### ISSUE THREAD

**Issue by 32423d** [DestinyItemManager/DIM#8720]
### Proposed change

The proposed feature request is the option to have a notification at the top right corner of DIM when ada-1 or banshee is selling a armour or weapon mod that you don't own yet. By clicking on the notification it takes you to the vendors tab and shows you the vendor that has the mod that you don't have yet.

### How does this fit into your workflow?

This makes obtaining armour or weapon mods more convenient for players that don't have them yet. It eliminates the need for the user to manually check the vendors tab every day when ada-1 and banshee's stock mods refresh.

**Comment by bhollis** [comment]
The only bit that makes this difficult is that DIM doesn't load vendors information until you get to the page (it's very slow to load).

**Comment by bhollis** [comment]
Well, that and after we do this then someone would want it to show when ornaments they don't have are for sale, or when any thumbs-up weapon is for sale, etc. Hard to satisfy all use cases.
