### ISSUE TITLE
Add loadout info to compare panel

### ISSUE THREAD

**Issue by Revadike** [DestinyItemManager/DIM#8724]
### Proposed change

Add information about what loadouts each item from the compare panel is included in. Maybe something like this?

![image](https://user-images.githubusercontent.com/4411977/191839121-4457f191-e741-4a2d-86a0-bc734b0cf31c.png)

### How does this fit into your workflow?

I often use the compare armor feature to see what armor I would like to shard, but I don't want to accidentally shard an armor piece that's included in a saved loadout without good reason. I'm using the lock feature right now, but this is not really sufficient, since I keep wondering what loadout it belongs to, and I'd need to check manually, which is tedious.

**Comment by robojumper** [comment]
Organizer allows you to enable a Loadouts column -- does that help?

**Comment by Revadike** [comment]
yes

**Comment by bhollis** [comment]
One day I will have Compare built on the code from Organizer so you can choose what it shows. Until then, organizer is what you should use.

**Comment by Revadike** [comment]
Fair enough, I still think my idea from the first post is a pretty good one.

**Comment by Revadike** [comment]
:(
