### ISSUE TITLE
Feature request: Pick weapon type-based mods automatically based on currently equipped items.

### ISSUE THREAD

**Issue by amackenzie** [DestinyItemManager/DIM#8725]
This mainly applies to ammo finders, scavengers, and seasonal anti-champion mods. I generally run double finders/double scavs (and in fact, always leave my boots/gloves/head slots open for this in loadouts).

It would be great if there was a button that would just look at what weapons you have equipped and equip a scavenger+ammo finder for your special, a scavenger+ammo finder for your heavy, and possibly also any relevant anti-champion mods (eg, if you have a pulse rifle equipped, it'll put on anti-barrier pulse this season).

Alternatively, perhaps it could be limited by having dummy mods in a loadout? eg, "Special Ammo Scavenger", that just applies the first special weapon you have equipped when you apply a loadout, or so on.

**Comment by bhollis** [comment]
Both are neat ideas!

**Comment by bhollis** [comment]
Folding into #8995
