### ISSUE TITLE
Loadout: Offer Help on why `Save` is disabled

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#8726]
Offer onhover help for grayed out `Save`... (e.g. name your loadout)
Probably also need something mobile friendly

**Comment by Bailejd** [comment]
I don't know if anyone is working on this currently but I had a question regarding the onHover method. I'm no UI/UX expert so this might seem like a dumb question and might be trivial.

Is using onHover for help text in this case actually the preferred method? It might look cleaner but seems like it is less user friendly. I'm just thinking, would a user miss the help text by simply not hovering over the grayed out save button?

This might be a case by case thing but would it make more sense to make the help text immediately visible to the user by putting the text "A Loadout requires a name" somewhere near the grayed out button button when no name is given by the user. It would be easier for most users to find and would be more mobile friendly be from the start. But making this look nice might be difficult.

Another idea would be to put an error icon next to the button to make it obvious there is an error causing the save button to be disabled. The user could hover or click it to show the reason the save button is grayed out. This just makes it more obvious that there is an error and in my opinion more likely to be hovered/clicked on.

Here is a quick and not so nice looking example I threw together. The image includes both examples I discussed above. We would only need to use one, either the orange text or the red button with hover/click to show text.

![Screenshot 2022-10-02 150537](https://user-images.githubusercontent.com/35389557/193471752-a3097446-34c5-4069-aa6f-8ccdc80c0caa.png)

I'm still pretty new to this so let me know if I am missing something important.

**Comment by bhollis** [comment]
Yep that's how we would do it, not a hover tooltip.
