### ISSUE TITLE
Support for ps5 default browser

### ISSUE THREAD

**Issue by zachpainter77** [DestinyItemManager/DIM#8727]
### Proposed change

No changes to DIM. Just would love to be able to use dim while playing D2 on console. 

### How does this fit into your workflow?

I would open DIM in a ps5 browser, pinned to left or right while I play D2.

**Comment by delphiactual** [comment]
Can you go to https://www.whatismybrowser.com/detect/what-is-my-user-agent/ and copy/paste your user agent string here?

**Comment by zachpainter77** [comment]
Mozilla/5.0 (Playstation; Playstation 5/6.00) Apple Webkit/605.1.15 (KHTML,
like Gecko) Version/15.4 Safari/605.1.15

**Comment by delphiactual** [comment]
does it load DIM at all, and you just get the warning?

**Comment by zachpainter77** [comment]
I am able to access the url but am only shown a message stating that the
browser is unsupported.

**Comment by bhollis** [comment]
Since the PS5 web browser isn't even supported by Sony, we're not going to support it. The biggest reason is that we can't really test or debug issues with it. If it works for you, despite the "unsupported" warning, then that's great, but we won't fix issues with it.

**Comment by zachpainter77** [comment]
I can't get past the warning lol

**Comment by zachpainter77** [comment]
I'm not asking that you support it I just ask that you don't block me from
trying is all. It's a super nice to have for ps5 users. Tbh bungie really
just needs an interface to do what dim does imo. It's 2022 and we still
have to use a third party app to manage our inventory.

**Comment by bhollis** [comment]
We don't block anything. We just show the warning on the bottom of the screen for a little while.

**Comment by zachpainter77** [comment]
Ok, thanks.
