### ISSUE TITLE
Use CommonSettings to Check Feature Availability

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#873]
http://destinydevs.github.io/BungieNetPlatform/docs/CoreService/GetCommonSettings

Look at the 'systems' property for features like advisors.

**Comment by kyleshay** [comment]
Could we instead somehow gracefully fail... if something isn't returning, instead of not loading the app at all, throwing an error and turning off function to that feature? 

Could use it in tandem w/ GetCommonSettings, but that's just one more request...

**Comment by SunburnedGoose** [comment]
Sure.  Fail gracefully.  With CommonSettings, we could know in advanced and disable the interface if that feature is broken.  If we fail gracefully, we would have to test, and then message the user that it is broken.

**Comment by bhollis** [comment]
Closing since we're already trying to handle failures and gracefully degrade - no need for an extra call.
