### ISSUE TITLE
Bug: Some armor mods are not displaying perks (charged with light, warmind...)

### ISSUE THREAD

**Issue by mehdibouaziz** [DestinyItemManager/DIM#8732]
### DIM Version

Version 7.36.0 (release), built on 26/09/2022, 05:54:16 / orange

### Browser Details

Chrome Version 105.0.5195.125 (Official Build) (64-bit)

### OS Details

Ubuntu 22.04 and Win10

### Describe the bug

When clicking on an armor mods to display additional informations about its effects, some of them don't have perks displayed.
The issue is present both in Ada-1 inventory and in collections
It makes it difficult to review what Ada-1 has to sell daily, if the mod is useful enough to log in.

Mod with missing perk:
![image](https://user-images.githubusercontent.com/31729703/192509049-15a47551-019b-4635-aaa7-eb1b6f148a7a.png)

Mod with perk:
![image](https://user-images.githubusercontent.com/31729703/192508926-812c1967-e1f8-408d-814a-b052f2840abe.png)

It seems to affect only Combat Style mods: Elemental wells, Charged with Light and Warmind cells.
Not all of them are missing their perks.

I tried to find what was causing the issue and the object containing the mod's data for the affected mod is missing the perks :
![image](https://user-images.githubusercontent.com/31729703/192510094-483cc05e-eb46-4f47-b1cb-616ca201d914.png)

I used https://data.destinysets.com/ to check with bungie's API and for the same mod the perk is here but its perkVisibility value is set at 1 (enum ItemPerkVisibility "Disabled").
![image](https://user-images.githubusercontent.com/31729703/192511198-80927222-7ee4-4ad4-a3f6-c9775b469df9.png)

Interestingly, the perk is correctly displayed when choosing a mod for a loadout:
![image](https://user-images.githubusercontent.com/31729703/192511793-63242ea7-f8f6-4818-8a2e-b89b1cd68e9d.png)

I would love to contribute to solve this if that's possible.

**Comment by bhollis** [comment]
Yeah, we have a couple different paths to this data - the mod picker starts from the definitions, while collections/vendors uses a "processed" inventory item. Would love help with this if you want to work on it.

**Comment by ModEngineer** [comment]
This has been bugging me for quite some time. As was mentioned in the opening comment, the perks are there but are hidden; I tried commenting out the check for perk visibility in the item factory, which solved this particular issue, but I can imagine it causing other issues. The cleanest implementation that I can think of would be to add another condition such that `perkVisibility` is ignored if the item is an armor mod, but this doesn't seem like an ideal solution.

**Comment by bhollis** [comment]
Linking #9076

**Comment by robojumper** [comment]
Do we have any new examples of this problem? CWL/Warmind Cell mods are gone now.
