### ISSUE TITLE
Figure out how to handle `autoStatMods` Loadout property

### ISSUE THREAD

**Issue by robojumper** [DestinyItemManager/DIM#8733]
With #8605, Loadout Optimizer will automatically assign some stat mods, and they are supposed to be saved separately in the Loadout, and behave a bit differently (they're not shared or retained when clicking Optimize Armor) but DIM doesn't handle that property very well yet.

* [ ] They aren't distinguished anywhere despire being save differently, which would be confusing
* [ ] ModPicker doesn't take them into account when checking how many general mods we already have
* [ ] possibly other issues

So I decided to not save loadouts with `autoStatMods` for now. I've left a bunch of FIXMEs referencing this issue number in the code.

**Comment by bhollis** [comment]
Is this still relevant? I thought you were actually using autoStatMods.

**Comment by robojumper** [comment]
No, that property is still unused. The checkboxes remain relevant, another problem is still unclear semantics -- e.g. when do auto mods stop being auto mods? Do they appear selected in the mod picker when editing the mods of a loadout? If so, does the user confirming the mod picker transfer them to regular mods?

Additionally, right now LO forcefully discards artifice mods when clicking "optimize armor" (even if the user manually specified them in the loadout) since setting artifice mods across the LO sets is a bad idea, so the property wouldn't even be useful for that.

**Comment by bhollis** [comment]
I'm starting to think the best way to do this is to just ignore any saved stat mods when we open a loadout in LO and auto stat mods is on.
