### ISSUE TITLE
See daily activities and modifiers

### ISSUE THREAD

**Issue by arimorcos** [DestinyItemManager/DIM#8736]
### Proposed change

Show somewhere (maybe progress page?) the daily activities, such as lost sectors, along with current modifiers. This would also be useful for the rotating daily nightfall modifiers, etc.

### How does this fit into your workflow?

To see what current modifiers are while not currently playing.

**Comment by bhollis** [comment]
There are some pretty cool sites like https://todayindestiny.com/ that do this!

**Comment by bhollis** [comment]
I won't say we shouldn't do this, because it'd be cool to have that info, but someone would need to volunteer to figure out how to get/maintain that info.

**Comment by bhollis** [comment]
For nightfall modifiers, we actually already show them: 
<img width="408" alt="image" src="https://user-images.githubusercontent.com/313208/209418994-01438f2d-c01d-42db-9d93-394e4bc54ffa.png">

**Comment by robojumper** [comment]
Though this only shows the modifiers for the first difficulty level. So yeah TodayInDestiny is definitely more complete, our milestones disappear when completing the associated challenge anyway.
