### ISSUE TITLE
Sort with recursive item groupings

### ISSUE THREAD

**Issue by jonwl** [DestinyItemManager/DIM#8740]
### Proposed change

I'd love a toggle to be able to group the same items regardless of sort setting.  For example, if sorted by power -> name, if the first item is Ager's Scepter, it would be nice to have every other Ager's Scepter (still power level sorted) before the next item in the standard sort.

To restate - currently, the example sort behavior for power -> name would be:

- 1580 Ager's Scepter
- 1580 Boudica-C
- [other 1580 stuff alphabetically]
- [1579-1571 stuff]
- 1570 Ager's Scepter
- [...]
- 1350 Ager's Scepter

The proposal is a toggle to change this behavior to:

- 1580 Ager's Scepter
- 1570 Ager's Scepter
- 1350 Agers Scepter
- 1580 Boudica-C
- [...]

### How does this fit into your workflow?

I personally like keeping things power -> name sorted, to see stuff to infuse with and regularly used and infused stuff near the top (and power-based sorting is just satisfying, honestly).  However, I find that it's easier to find individual copies that you're looking for without having to search if the same items are grouped together, like in the in-game vault or having name as the first priority in sort settings.

Maybe a weird use case, but I figured I'd throw it out there anyways.

**Comment by bhollis** [comment]
It's an interesting idea, and I see the utility, though I'm not sure how we would expose it. You might find that Compare or the Infuse tool is better overall for finding infusion fuel.

**Comment by f-t-alves** [comment]
Suggestion for how to expose: let users repeat sort groups in the sort settings list. It would need two lists, though, one of possible sort groups and one with the actual setting.

**Comment by humandxp** [comment]
have you tried to enable in settings more options, i have type, damage type, name, power level. if you want sort by power you grab and move power to top.
but after 2 weeks when you reach max level on armor and weapons when you play with 3 characters, simply all for infusion you tag as junk and on top in search type tag:junk and you will quickly find something to infuse weapon that is lower light, same with armor.
and it groups always weapon by assault, same weapon and same element, then different arc assaults
