### ISSUE TITLE
Bug: Loadouts: Excessively long string in notes pushes buttons offscreen

### ISSUE THREAD

**Issue by JBlackCat** [DestinyItemManager/DIM#8741]
## Description
If the user adds an exessively long string, such as youtube->DIM url, in the notes of a loadout, once the loadout is saved the buttons for all loadouts are pushed off screen.

![loadout-layout-offscreen](https://user-images.githubusercontent.com/5446373/193444510-e7cbcbd5-458e-4a98-8639-57dd246e91be.jpg)

## Enviroment Observed
_I did not test in other browsers._
- DIM: Stable & Beta
- MacOS 12.6 / Safari 16.0
- Viewport: 1440 x 1165
- devicePixelRatio: 2

## Steps to reproduce:
1. Create new DIM loadout or edit existing.
2. Open notes
3. Add the following string, `https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqa296bWR5UXBjLWNHQXJ6T1NoeFpzaWFyaU1pUXxBQ3Jtc0ttTHFpYTdJckZLdXpveUhsd1kyb0JOT2t3bVZrSjdIQ0w1bEJqeURMd1U5MUdnVU1vTm93MEFMa2o0LUNIRkxqQXdPd2podFZZNHdNU2JERGxDV0RBekdOV3RxY0pLckw1YnJnd0FvbGdyTzhzblBXOA&q=https%3A%2F%2Fdim.gg%2Fmd2bp4q%2FMAIN-S18-Titan-Melee-DPS-Build&v=W8WsztcPuWI`
4. Click `Save Changes` button
5. Observe Loadout UI buttons are pushed off screen by responsive layout.

**Comment by delphiactual** [comment]
the string you are adding is a redirect to dim with the loadout and not a reference back to the video...
