### ISSUE TITLE
Firefox slow profile refreshes - Possibly related to withCredentials / Bungie.net cookies

### ISSUE THREAD

**Issue by afpac** [DestinyItemManager/DIM#8742]
### DIM Version

7.36.0

### Browser Details

Firefox 105.0.1 64 Bit

### OS Details

Windows 10

### Describe the bug

I received a bug report for my roll appraiser tool that Firefox was particularly slow in recognizing new items / dismantled items. In the process of diagnosing it, I was using DIM (also in Firefox) to determine if the issue was with my code or just the API or what, for comparison. I was able to replicate what the user was reporting both in my tool and in DIM by:

1) Purchase item from Banshee and note the time / start stopwatch
2) Refresh profile by pressing R until the item appears where it should
3) Stop stopwatch

This process revealed that there was fairly consistently a 2-5 minute delay between when the purchase was actually made and when the item would appear in either of our tools in Firefox.

What I came to determine was that any GetProfile request that presents bungie.net's bungled, bungledid, bungleanon, etc cookies seems to cause this delay. I'm not sure if there's some sort of non-Cloudflare caching that happens on their end that's only intended to fire when the user is actually on bungie.net or what. Regardless, by switching my XHR GetProfile request to set withCredentials to false, I was able to eliminate the delay. Apparently in Chromium based browsers these cookies do not get presented even if withCredentials is set to true, so updates are nearly instantaneous.

I'm still looking into the ramifications of setting withCredentials to false for other API requests, but I wanted to let you guys know what helped my tool in case you wanted to take a look at it in DIM as well.

Here's a screenshot of a DIM request that shows it presenting the bungie.net cookies in Firefox:

![image](https://user-images.githubusercontent.com/32434371/193475040-8dda864d-8a33-4c2f-a9a0-ac29910e461f.png)

**Comment by bhollis** [comment]
Interesting, and also somewhat sad. This may explain why @nev-r sees outdated inventory far more frequently than I do.

**Comment by bhollis** [comment]
I suspect the difference in behavior with Chrome is due to https://web.dev/samesite-cookies-explained/#changes-to-the-default-behavior-without-samesite

**Comment by humandxp** [comment]
well for dim better switch to brave, for browsing and old plugins i use waterfox cos new firefox is trash. like android they block more and more what you can do

**Comment by bhollis** [comment]
@afpac thanks for the tip, we've rolled out a change to stop sending cookies and folks have noticed an improvement!
