### ISSUE TITLE
Loadout - Ability to move only other weapons away

### ISSUE THREAD

**Issue by rfeigenbaum** [DestinyItemManager/DIM#8744]
### Proposed change

I think it would be a nice change to have a toggle to only move other weapons out of character with a loadout. Could also add another toggle if you just other armor pieces moved out of the character.

### How does this fit into your workflow?

I have loadouts that have lots of weapons in them, but I don't really have any that have lots of armor in them. So, if I use "move other items away" I would send too much armor to my vault and stuff would have to overflow onto my other characters. However, since some loadouts have a lot of weapons I'm moving enough weapons onto my character where my vault should have space for the weapons that would be moved out.

**Comment by bhollis** [comment]
I don't have a lot of appetite for making this more complex - it's recommended to just accept that if your vault is full items will get moved around, and use searches and tags and loadouts to bring them back when you need them.

**Comment by bhollis** [comment]
Note that "move other items away" will already ignore any bucket that doesn't have an item in the loadout.
