### ISSUE TITLE
save/export the item feed to enable statistical analysis of rewards

### ISSUE THREAD

**Issue by deangaudet** [DestinyItemManager/DIM#8751]
### Proposed change

it would be useful to me, and other "destiny science" folks, to have a long-term record of every item drop.  i realize that DIM's item feed is based on polling the API for current items, but even that could be useful if we could somehow persist a record of every item observed.  a log of all items ever observed by DIM.  some sort of raw JSON i could export locally and manipulate with external tools.

### How does this fit into your workflow?

for years i've done this manually by transcribing reward data to a spreadsheet.  naturally i don't do this for everything, but it has allowed me to make reddit posts such as [high-stat armour guides](https://www.reddit.com/r/DestinyTheGame/comments/ppfluk/highstat_armour_guide_updated_for_season_of_the/) (now out of date, but working on a new one), or to [debunk a reddit myth](https://www.reddit.com/r/DestinyTheGame/comments/vtny1s/playlist_drops_improve_after_3_resets_heres/) that stopped people from resetting their playlist vendors in season of the haunted.

after bungie's most recent TWAB, where they made the claim that all perks are equally likely, folks asked me whether i had the data to support the claim... and well, that's just way more data than i want to manually type in.  however if i had a feed of every item dropped so far this season, then i could go write some code to extract the sample.

i understand that the samples are polling based, and if i shred an item quickly it may never show in the feed... but i think it would be useful even without that.

even better would be some sort of correlation with the PGCR so i could make an attribution of item source, but that could be done externally if i had the item hashes and some sort of timestamp.

**Comment by bhollis** [comment]
The best way to do this is to use DIM's Spreadsheet export. Then, sort by item instance ID. That's what the item feed is doing. This won't include items that have subsequently been deleted, but neither does our Item Feed - we have no place we store a record of all drops.

Beyond that, I can recommend dipping your toes into the Bungie.net API to build something that polls for new items and records them somewhere. It should be pretty straightforward to make your own app like that, and you can get it to do whatever you want.
