### ISSUE TITLE
DIM sync error

### ISSUE THREAD

**Issue by WargalKnight** [DestinyItemManager/DIM#8753]
After resetting Chrome I cannot access DIM for my loadouts and I keep receiving the same error in the screenshot. I do believe DIM sync was enabled before I reset Chrome. I did go through you troubleshooting guide and it didn't fix the issue.

[
![DIM sync error](https://user-images.githubusercontent.com/115497526/194928332-fa2e975c-ff53-4d66-86cc-655c0d63313a.png)
](url)

**Comment by WargalKnight** [comment]
Also, this screenshot is from dim beta as I wanted to test both dim and beta versions. The error on the far right appeared on both.

**Comment by delphiactual** [comment]
https://twitter.com/ThisIsDIM/status/1579495165651140608
