### ISSUE TITLE
Strange DIM Beta issue not showing my characters

### ISSUE THREAD

**Issue by Samsinite** [DestinyItemManager/DIM#8758]
### DIM Version

Version 7.38.0.1002003 (beta), built on 10/11/2022, 3:07:09 AM

### Browser Details

Firefox 105.0.3 (64-bit)

### OS Details

OSX 11.6

### Describe the bug

This is not my character, still see the same thing after logging out/in of DIM. If it helps debug, the non-beta build works fine and the mobile app works fine. This issue started happening around two or so weeks ago when Destiny was having issues with signing into the game and DIM beta has never fixed itself.
<img width="531" alt="Screen Shot 2022-10-14 at 2 20 43 PM" src="https://user-images.githubusercontent.com/166847/195946169-135b6f00-7815-4f8f-84c7-e2b1e2d3d007.png">

### Logs

```shell
[app] DIM v7.38.0.1002005 (beta) - Please report any errors to https://www.github.com/DestinyItemManager/DIM/issues instrument.ts:123:32
Language Detected: en-us instrument.ts:123:32
Language Assigned: en instrument.ts:123:32
[dim sync] globalSettings 
Object { dimApiEnabled: true, destinyProfileMinimumRefreshInterval: 15, destinyProfileRefreshInterval: 60, autoRefresh: true, refreshProfileOnVisible: true, dimProfileMinimumRefreshInterval: 600, showIssueBanner: false, flavor: "beta" }
instrument.ts:123:32
[dim sync] Saving profile data to IDB instrument.ts:123:32
```
```

**Comment by delphiactual** [comment]
This is your D1 account

**Comment by Samsinite** [comment]
@delphiactual I have never played d1.

**Comment by delphiactual** [comment]
click hamburger menu
![image](https://user-images.githubusercontent.com/4798491/195953724-2b7efefd-85ff-4761-889e-9b428d6bb1a0.png)

**Comment by Samsinite** [comment]
@delphiactual Ah that worked, thanks much!

**Comment by delphiactual** [comment]
but you have a D1 Account associated... btw
