### ISSUE TITLE
Show catalyst progress in inventory

### ISSUE THREAD

**Issue by Revadike** [DestinyItemManager/DIM#8771]
### Proposed change

Similar to pattern progress, I'd love to see the catalyst objective progress for exotic weapons that aren't fully masterworked yet. 

### How does this fit into your workflow?

Easily see progression without having to look in-game or use records page.

**Comment by bhollis** [comment]
Most catalysts are visible as quests on the progress page now. For the older style catalysts, I actually thought we did show the progress - maybe @vivekhnz's tooltip redesign dropped that?

**Comment by Revadike** [comment]
You mean craftable exotics? Because newer exotics don't have this:
![image](https://user-images.githubusercontent.com/4411977/196060938-c96ea6f2-3b0f-4ced-953c-dcf087f2c912.png)
![image](https://user-images.githubusercontent.com/4411977/196060949-eb2ab269-fdd9-4f24-bfe4-ee3d09e279c3.png)

Just like old ones.

**Comment by Revadike** [comment]
Also, they don't appear in the progress page at all, as you claim. Unless you track the corresponding triumph of course. Which is great if you're focussed on farming for it, but I'm more of a passive exotic catalyst farmer, so it takes a long time for me to complete. Keeping taps on it via inventory would be great.

**Comment by bhollis** [comment]
Yeah right now they're mostly on the Records page:

<img width="1697" alt="image" src="https://user-images.githubusercontent.com/313208/196066413-d0ad2367-613e-4cfc-a320-c17a9716665a.png">

This is just due to how the data comes back these days, but it's certainly possible for us to display it directly on items.

**Comment by mattjbones** [comment]
I have been noodling around with this just to see what it would take (super useful idea!) 


Reusing the existing `WeaponDeepsightInfo` component as a base and pulling out the objectives from `buildCatalystInfo` function I was able to land on something like this:

<img width="322" alt="image" src="https://user-images.githubusercontent.com/10519003/197028935-702db6e8-c101-4e6e-9cd6-05c5e0d28475.png">

I wonder whether this is good enough or something to indicate this is catalyst progress?

**Comment by bhollis** [comment]
Looks good to me
