### ISSUE TITLE
DIM won't load if my browser is sending a bungie api key as a request header

### ISSUE THREAD

**Issue by WalkerSakatch** [DestinyItemManager/DIM#8782]
### DIM Version

7.39.0

### Browser Details

Chrome 106.0.0.0

### OS Details

Windows 10

### Describe the bug

I have an extension for chrome called ModHeader which allows me to add headers to the http requests my browser makes (pic 1). I noticed that if I add a header called X-API-Key and try to open DIM it will not load, regardless of whether or not the value of that header is a valid api key. (pic 2). I assume this is somehow conflicting with how DIM makes requests to Bungie as Bungie requires that api keys be sent using a header called X-API-Key. The really easy workaround is to just disable my bungie api key from being sent through the extension, but that's a bit annoying and I'm lazy.

I'm not sure if this is even possible to fix but I figured I'd post it because it was quite the troubleshooting journey for me to figure out why I couldn't get DIM to load.

pic 1:
![image](https://user-images.githubusercontent.com/4109476/196487158-56c86527-37f9-4018-ad7d-ea163450ef18.png)

pic 2:
![image](https://user-images.githubusercontent.com/4109476/196487397-c543630b-82a9-4b2e-badf-d78fb61374a5.png)

**Comment by robojumper** [comment]
Yeah I don't think there's anything DIM can do to circumvent users/browsers/extensions overwriting crucial authorization headers. You may want to look into ModHeader's documentation for a way to restrict those header overwrites to certain sites (or prevent them from applying to DIM's and Bungie's sites).
