### ISSUE TITLE
Different sorting settings for weapons and armor

### ISSUE THREAD

**Issue by BuffMcMuff** [DestinyItemManager/DIM#8808]
### Proposed change

I think it would be useful to have separate settings for sorting armor and weapons since a user might have a sorting setup which is good for weapons for but not for armor or the other way around.

### How does this fit into your workflow?

This would help users organize their items better.

**Comment by bhollis** [comment]
Can you give an example of how you would configure it?

**Comment by humandxp** [comment]
i think you can do it already. simply in sort items enable and set in order:
type, damage type, name, power level
it will group weapons by class, and by element, name, and power. so they are still grouped.
like first arc assault and first same weapons with different perks, sorted by light. then different arc assault, then solar, void, stasis, then fussions etc.
btw why you need sorting for armor, for that you use loadout optimizer. you never pick armor by hand
