### ISSUE TITLE
Interface stuck showing old data and loadouts gone

### ISSUE THREAD

**Issue by andhubhelp** [DestinyItemManager/DIM#8812]
### DIM Version

7.40.0

### Browser Details

Edge

### OS Details

Windows 10

### Describe the bug

Approximately 5 hours ago give or take an hour something (maybe 5-6pm UK time) went wrong and the interface was showing and constantly refreshing to the items as I had them at about that time.

I could still move items but everything shown would revert to the gear from before regardless of any changes actually made and also the character list did not refresh to reflect changing character in game or any changes of gear etc.

I also noticed all my loadout details were gone.

About 30 mins ago again give or take 20-30 mins (10ish pm UK time) things finally started to update again correctly and the interface shows the current and correct gear. HOWEVER my loadouts have not come back.

I realise its probably my own fault if i didn't keep a recent backup, the only json file i have in my downloads folder is 2 years old (EEK!) but I do have Dim sync on so is there any chance of my loadouts coming back or being restored?

Is there something saved locally that i can restore or will they reappear from dim sync or are they gone?

I'm hoping maybe whatever was down is coming back up and everything will re-appear but so far no loadouts.

Help please if you can, its a lot of work gone if I need to recreate all my saved loadouts.

**Comment by bhollis** [comment]
If you're still missing your loadouts, head to our Discord and join #missing-loadouts

**Comment by andhubhelp** [comment]
Ok will do
