### ISSUE TITLE
You can not drag an item, you can only double-click it with the cursor.

### ISSUE THREAD

**Issue by Sundae6832** [DestinyItemManager/DIM#8814]
### DIM Version

orange 7.40

### Browser Details

google

### OS Details

windows11

### Describe the bug

You can not drag an item, you can only double-click it with the cursor.

**Comment by delphiactual** [comment]
can you send a video of this and console logs

**Comment by bakerjpeg** [comment]
I'm also getting this but it is inconsistent. Here are my console logs for when it last occurred. I was using this search: `not:hasnotes is:crafted` and clicking on the item tiles to enter notes. I single clicked on my Firefright and it did the double click action of equipping. 
[beta.destinyitemmanager.com-1667268700898.log](https://github.com/DestinyItemManager/DIM/files/9906184/beta.destinyitemmanager.com-1667268700898.log)
