### ISSUE TITLE
DIM showing weapon perks that do not exist on weapon in game

### ISSUE THREAD

**Issue by nycphog** [DestinyItemManager/DIM#8816]
### DIM Version

Version 7.40.0 (release), built on 10/23/2022, 11:55:47 PM

### Browser Details

Chrome 106.0.0.0 - Mac OS 10.15.7

### OS Details

macOS Monterey Version 12.6

### Describe the bug

On one particular Mechabre Sniper Rifle, I see secondary perks (autoloading holster with a vorpal weapon) that do not exist while in-game.  When I try to apply the perks in DIM I get an "Error changing mods or perks". We couldn't equip Auto-Loading Holster in Mechabre.

Bungie.net message: You cannot afford the material requirements for that action.

### Logs

```shell
Failed to load resource: the server responded with a status of 500 ()
www.bungie.net/:1
```

**Comment by delphiactual** [comment]
https://github.com/Bungie-net/api/issues/1732
