### ISSUE TITLE
"Hot Items" area

### ISSUE THREAD

**Issue by Razzupaltuff** [DestinyItemManager/DIM#8818]
### Proposed change

I would love to have my vault split in two parts: A "hot items" area and a "general storage" area. In hot items I would store all items that I use frequently, want to have a quick overview over and acess easily. "General storage" would be kind of an archive, where I store items I rarely use and just keep in case they become attractive because of a meta change or because I consider them a collector's item regardless of usability.

I could imagine the tab item "Inventory" to be replaced by "Hot Items" and "Storage", and a context menu entry for each item either saying "send to storage" or "make hot item", depending on where it is currently stored.

DIM would need to keep track of that itself, so this might be a question of storage (probably local cookies, which may all item assignments getting lost on a browser cache clear - a central database would ofc be perfect, but probably out of the scope of the DIM project, since it would require storage for millions of data sets).

### How does this fit into your workflow?

I have a bunch of items (mostly guns, not armor) I use all the time, while the majority of my stuff rests in the vault. I got too many frequently used guns to just keep them on my characters and move them around between them. Finding them between all the stuff in the vault is tedious. So I would love to have DIM split the vault in a "hot items" area where I store or see only the items I use all the time, and a "general storage" area where all the other stuff is displayed without obstructing my quick overview over my go to items.

**Comment by bhollis** [comment]
The recommended way to achieve this is to tag your favorite items. Then, you can select in settings to sort by tag, and your favorites will always be in front. 

Also, make loadouts for specific sets you want to use together and you can pull all the pieces together in one click from wherever they are.

**Comment by Razzupaltuff** [comment]
Thanks for hint. Now if I could mark a bunch of items (e.g. with
Ctrl+Click) and then tag them all at once I would be really happy. :)

Am Fr., 28. Okt. 2022 um 21:31 Uhr schrieb Ben Hollis <
***@***.***>:

**Comment by Razzupaltuff** [comment]
I tried the tagging now, and there are a few things I am not happy with.

First of all, there is no clear distinction between the groups of items
with different tags (like a gap). I also would like the archived items to
not be grayed out, as they are really hard to read for me.

Generally, I am not excited about having to tag a ton of items and then
have DIM simply display them the usual way, just sorted differently. I
would prefer completely distinct screen areas where the stuff is kept, e.g.
selectable via tabs.

The perfect solution would ofc be allowing the user to create his own tabs
and screen areas where he can move stuff around between. Tagging would be
automatic, simply based on which area the user drops an item in.

Of course this is all just a proposition. I understand that - apart from
donations - you are doing this for free.

Independently of this message I would just like you to know that I have
donated to DIM twice already as a sign of appreciation.

Keep up the good work!

Cheers

Am Sa., 29. Okt. 2022 um 11:04 Uhr schrieb Razzu Paltuff <
***@***.***>:

**Comment by bhollis** [comment]
For separating things in the vault, we have https://github.com/DestinyItemManager/DIM/issues/7206 on the backlog.

For the item tabs/folders, unfortunately that's in the list of https://github.com/DestinyItemManager/DIM/wiki/Frequently-Requested-Features#custom-groupings-within-the-vault
