### ISSUE TITLE
DIM - Community Descriptions Missing Only on Android Version

### ISSUE THREAD

**Issue by WilliamTell13** [DestinyItemManager/DIM#8820]
### DIM Version

7.40.0

### Browser Details

Chrome 107.0.5304.91

### OS Details

Android 11

### Describe the bug

My setting for Community Perk Insights is set to Both Descriptions. Even when changing it to Community Descriptions, it still just shows the same default description for the perks. I know a few other people that said the same thing is happening to them. The screenshots I have included show that I have the Community Descriptions setting selected. On my computer, it successfully shows only the Community Descriptions. On Android, on the same account and everything, it does NOT show the Community Descriptions. When I select Both Descriptions, it successfully shows both on PC, but again, it ONLY shows the default Bungie description on Android. My Android used to show the Community Descriptions. It stopped working probably about a month ago. I would take a log if I knew how to on the Android version, but the Logs section below only says how to do it on PC and Mac.

![Android 1](https://user-images.githubusercontent.com/104655992/198800282-baac8340-939e-45c3-9c17-162e0b30ecf6.jpg)
![Android 2](https://user-images.githubusercontent.com/104655992/198800286-6dc33400-e409-456f-889c-47627a1fd35e.jpg)
![DIM on Computer](https://user-images.githubusercontent.com/104655992/198800290-4f0961c4-f4a6-4bdd-8e86-b97feb086bdd.png)

**Comment by inexorableAce** [comment]
Are you using the version from the App Store or is it the raw PWA? (Add to home screen from the web app)

**Comment by robojumper** [comment]
cc @Ice-mourne

**Comment by Ice-mourne** [comment]
Interesting it works for me on android 11
Also, both PWA and app work
Most likely it gets blocked for some reason 
Download "Kiwi Browser" from the app store
Go to the DIM website if descriptions are not working
Press 3 dots to open settings > developer tools > console (it's very similar to how it is on desktop crome)
And show us everything in where

**Comment by WilliamTell13** [comment]
> Are you using the version from the App Store or is it the raw PWA? (Add to home screen from the web app)

I'm using the DIM app from the Play Store.

**Comment by WilliamTell13** [comment]
> Interesting it works for me on android 11 Also, both PWA and app work Most likely it gets blocked for some reason Download "Kiwi Browser" from the app store Go to the DIM website if descriptions are not working Press 3 dots to open settings > developer tools > console (it's very similar to how it is on desktop crome) And show us everything in where

So I downloaded Kiki Browser and the Community Descriptions work perfectly as expected in that browser. I just opened DIM in my actual Chrome browser (instead of the app) and it still only shows the default Bungie descriptions.

Do you still want me to copy the log from Kiki Browser, even though it's working fine in that browser?

**Comment by inexorableAce** [comment]
Have you tried clearing your chrome browser cache? Both the play store app and opening in chrome are using chrome browser. So if it works in a fresh browser there's a good chance it's cache related.

**Comment by Ice-mourne** [comment]
> Do you still want me to copy the log from Kiki Browser, even though it's working fine in that browser?
No, if it works then logs won't show anything useful

**Comment by WilliamTell13** [comment]
> Have you tried clearing your chrome browser cache? Both the play store app and opening in chrome are using chrome browser. So if it works in a fresh browser there's a good chance it's cache related.

Yes, I have tried that before. I just cleared it again (584MB of cache) and it is still not working. I also cleared the DIM app's cache and Force Closed both apps before trying to restart the DIM app.

**Comment by WilliamTell13** [comment]
> > Do you still want me to copy the log from Kiki Browser, even though it's working fine in that browser?
> 
> No, if it works then logs won't show anything useful

That's what I figured.

**Comment by inexorableAce** [comment]
Cookies too?

**Comment by WilliamTell13** [comment]
> Cookies too?

No, but I just did and now the Community Descriptions are working as expected. 👍

**Comment by Ice-mourne** [comment]
You said, "I know a few other people that said the same thing is happening to them."
I just changed the description version that will force an update in 1-2h don't remember the exact timing
Can you ask them if it works for them in a few hours

**Comment by WilliamTell13** [comment]
> You said, "I know a few other people that said the same thing is happening to them." I just changed the description version that will force an update in 1-2h don't remember the exact timing Can you ask them if it works for them in a few hours

Yes, I will ask them later today/tonight and let you know.

**Comment by inexorableAce** [comment]
Will leave this open till then 👍

**Comment by WilliamTell13** [comment]
> You said, "I know a few other people that said the same thing is happening to them." I just changed the description version that will force an update in 1-2h don't remember the exact timing Can you ask them if it works for them in a few hours

Just got word that it wasn't working on his Android OR PC. He just tried both and they are both working correctly now!

**Comment by humandxp** [comment]
is community description connected to clarity cos i hate this plugin and it only works in list mode, i prefer grid. and community description in dim works on random. clarity still needs months of development

**Comment by Ice-mourne** [comment]
> is community description connected to clarity cos i hate this plugin and it only works in list mode, i prefer grid. and community description in dim works on random. 

Community descriptions are built directly in DIM you do not need anything to get descriptions
> clarity still needs months of development

Tell me something I don't know I haven't updated clarity for about 2-3 mounts was busy with the back end
All current code will be trashed and rewritten from scratch it's so bad I don't even want to look at it
