### ISSUE TITLE
[Feature Request] Add option to hide loadout from Inventory loadout picker dropdown

### ISSUE THREAD

**Issue by Korrasera** [DestinyItemManager/DIM#8829]
### Proposed change

Add an option to the loadout builder that allows you to toggle whether or not the loadout will appear in the Inventory page loadout picker dropdown. So, instead of seeing all of your loadouts when you're on your Inventory page and are selecting from the dropdown, you'd only see the loadouts that you've toggled as visible. This would be a toggle just like the Any Class or Move Other Items Away toggle, and all loadouts would still be fully visible on the Loadouts page, where you could edit them as normal.

In essence, this would create two different states of loadouts, visible and archived. Visible loadouts are in-use and appear both in the picker dropdown and on the Loadouts page. Archived loadouts don't appear in the picker dropdown and are visible only from the Loadouts page.

### How does this fit into your workflow?

The loadout picker dropdown on the Inventory page can only handle so many loadouts before it gets difficult to use, requiring you to scroll the list up or down to find the loadout you want. As a result I tend to limit myself to 6 armor/subclass loadouts and 4 weapon loadouts, since I'm usually using DIM on a tablet and that's the sweet spot in terms of how much screen real estate I have to work with. This experience will obviously vary from device to device.

Keeping the loadout picker dropdown trimmed to a manageable size for your device currently means deleting any extra loadouts DIM. You want to try out a solar Synthoceps build instead of void Wormgod Caress build? You'll probably want to delete the Wormgod Caress build. Since I don't want to lose loadouts that I'm not using immediately, saving them means I need to generate a share url for the loadout, record it in a text file, and then delete the loadout from DIM. If I want to return to that loadout in the future, I need to load it back into DIM using the share url. It works, but it's extremely cumbersome and it means I can't use the Loadouts page in DIM as my one-stop-shop for managing my loadouts.

In other words, we've got two problems here:

1) The picker dropdown can get overloaded with loadouts, which makes the UX worse.
2) If you fix the picker dropdown by removing loadouts, you lose the ability to manage those loadouts inside of DIM.

If you add a visibility toggle, we can use the Loadouts page to maintain *all* of our loadouts while also keeping the picker dropdown to a manageable size. This would also further strengthen the identity of the Loadouts page by turning it into a proper repository that can store every loadout you've ever wanted to use. You can then promote or demote them as you like.

Decide you want to run more void builds this month? Just turn off visibility for the solar builds you've been using and turn on the visibility for all of your void builds. And it would let you store all kinds of specialty builds in the loadout page. You're only going to equip that one weird raid-specific divinity+wells build every other week or so? Leave the visibility turned off and you can just dip into the Loadouts page and equip it from there if you need it.

I don't know how much additional data footprint the loadouts create for DIM Sync so this might not be feasible, but if it's trivial to have a ton of loadouts in DIM without a perf or footprint change I think this would make for a great enhancement to the way DIM handles loadouts and loadout switching.

**Comment by bhollis** [comment]
Linking #7663
