### ISSUE TITLE
Ctrl+z behavior of search bar

### ISSUE THREAD

**Issue by Revadike** [DestinyItemManager/DIM#8833]
### DIM Version

Version 7.42.2 (release), built on 11/9/2022, 8:17:00 PM

### Browser Details

Brave Version 1.45.118 Chromium: 107.0.5304.91 (Official Build) (64-bit)

### OS Details

Windows 11

### Describe the bug

I did ctrl+z (undo) in the main search field, and I expected my previous input to replace my current one, but instead both inputs get concatenated. 

![image](https://user-images.githubusercontent.com/4411977/200973700-833cd4ba-0349-4cc4-9519-100da816c4c5.png)

The issue may be exclusive to saved queries?

**Comment by Revadike** [comment]
Firefox doesn't seem to have this issue

**Comment by bhollis** [comment]
I'm gonna have to call this a browser bug in Chrome / the web platform. `execCommand` is the only way to do this text modification, but it's deprecated so it probably won't be fixed.
