### ISSUE TITLE
Thumbnail hover shows exotic thumbnail

### ISSUE THREAD

**Issue by Robnroll** [DestinyItemManager/DIM#8834]
### DIM Version

Version 7.42.2 (release), erstellt am 9.11.2022, 20:17:00

### Browser Details

Firefox 106.0.5 (64-Bit), appears on Chrome as well

### OS Details

Windows 10

### Describe the bug

Since two days i guess every thumbnail i hover over is replaced / highlighted with the thumbnail of an exotic.
Not sure if this is a feature that i don't know or if its a bug :D

![DIM_Bug_01](https://user-images.githubusercontent.com/11501155/201066307-7a73a2e3-9d6c-40b1-a4ce-60924de96b8a.png)
![DIM_Bug_02](https://user-images.githubusercontent.com/11501155/201066315-fabba3b1-215d-49da-b477-8fc559c0daec.png)
![DIM_Bug_03](https://user-images.githubusercontent.com/11501155/201066317-9f835d63-fe06-4fbb-b31b-c98b6d81eb11.png)
![DIM_Bug_04](https://user-images.githubusercontent.com/11501155/201066319-e96c013b-583b-40ab-a0b7-a3b547839fa6.png)

This happens on different computers and browsers.

**Comment by humandxp** [comment]
i bet its not a bug only joke from devs. that telesto become sentient and is alive

**Comment by jakobo** [comment]
Intentional change 

https://github.com/DestinyItemManager/DIM/commit/49206d21b912fc557d55d58364685d6cda3d63d5

 /cc @nev-r
