### ISSUE TITLE
Organizer Search across subcategories

### ISSUE THREAD

**Issue by Robnroll** [DestinyItemManager/DIM#8835]
### Proposed change

Maybe this is already possible and I just havn't found out how.
I would like to have the option to be able to get search results across subcategories in the organizer.
For example listing pistols and pulse rifles at the same time or even all weapons or all gear items.

### How does this fit into your workflow?

- I usally go through my gear and mark items for junk, favorite etc and dismantle them at the end. It would be nice to be able to see all junk items at once to double check or for transfering them to my char for dimantling.

- Seeing all my favorit tagged gear at once would be nice just to have a quick overview of "good" item options.

- Weapon selection based on specific attributes may be a weird approach but sometimes I just need to know which options i have in terms of solar weapons or volt shots for example. So it would be nice to see them all at one page without going through the sub categories.

**Comment by robojumper** [comment]
Sounds similar to #7790 -- are the ideas expressed there what you're looking for?

**Comment by Robnroll** [comment]
I'm not completly sure.
For me it would be fine if you could use the organizers search bar on all or multiple weapon types at the same time, showing them in one list and not separatly.

**Comment by humandxp** [comment]
you can use compare in inventory, click one weapon and compare, first it will list only same weapons with different perks like pulse, but you can click on top of opened window is:solar so it will add also all solar pulses, is:energy and it will add to list all pulses with any element. when i dont want weapon but is 1580 so can be used to infuse i simply click icon of weapon and press shift+3 to tag as junk and move to vault. on top search line type tag:junk and it will show only junk. i do that to remove if i have more than 2 in any slot and any armor. weapons i use i lock them so, never delete them by accident, same with masterworked armor you can use then is:unlocked -is:exotic so it will show only unlocked but not exotic.
best line is:
basestat:total:<65 is:armor -is:masterwork -tag:junk
cos there is no point to keep armor below 65

if you want voltshot again just type volt in search in inventory and dim is inteligent and gives you lines you can use:
perkname:voltshot

sorting items in setting enable and move lines in order from top:
type, demage type, name, power level and you already have all same arc assaults, all arc assaults, all solar assaults, all void, then fusions and rest

**Comment by Robnroll** [comment]
Thanks for your comment. For me it feels like the solutions you mentioned are more or less workarounds for the feature i am missing.
I didn't mean to say that its currently not possible to find what I am looking for, its just that it could be easier.
Like seeing all solar weapons at the same time no matter which type it is, to find a shield breaking weapon fitting my setup. Listing pulses, sidearms and snipers at the same time. 

At the moment i just get an empty list when i am searching without choosing a category.

![DIM_SearchBar01](https://user-images.githubusercontent.com/11501155/201609366-536b9adf-9a54-4cce-b509-71b9e3cb8cd5.png)
![DIM_SearchBar02](https://user-images.githubusercontent.com/11501155/201609665-eb599ccb-2dc3-4cba-868c-531faf4225e3.png)
