### ISSUE TITLE
Show armor total stat for vendor items on the item tile

### ISSUE THREAD

**Issue by humandxp** [DestinyItemManager/DIM#8836]
### Proposed change

since you can change affinity anytime there is no point to show energy and element on armor, instead skillpoints like 63 64 65 or even like haunted every class item element had different skillpoints 63arc 65stasis

### How does this fit into your workflow?

it would save time for example checking all armors on vendors if there are any decent

**Comment by bhollis** [comment]
Sorry, I can't quite understand what you're suggesting. Can you write out in more detail what you mean?

**Comment by humandxp** [comment]
funny goolag didnt send me info about bhollis reply but robo yes.
yes robo that exactly what i was thinking about. maybe 1st version is cleaner looking.
still my idea was about having total skillpoints in place of energy so you can also display light level, cos some vendors default to 1350 and some armors you will get with current light level like 1570 now.
not that it would matter to anybody cos you need to infuse that anyway
