### ISSUE TITLE
Link/use (any class) gear loadouts within class-specific loadouts

### ISSUE THREAD

**Issue by jamieastley** [DestinyItemManager/DIM#8837]
### Proposed change

The (any class) gear loadout is very useful to create activity-specific weapon loadouts that you tend to use for each class for a given activity.

As a quick mockup suggestion shown below, potentially adding a dropdown menu item to relevant sections of the loadout creator to be be able to link to/import a specific (any class) weapon loadout.
![dim-feature](https://user-images.githubusercontent.com/6836556/201449140-8f1f3e75-db6d-485c-bd0c-5a314df93630.png)

### How does this fit into your workflow?

I'd argue the vast majority of players will use the same weapon loadout across classes for things like raids/dungeons/PvP etc, so being able to maintain a "single source of truth" for items that can be equipped on any character between multiple loadouts for these activities would be very helpful to cut down on re-configuring these aspects of loadout items across classes.

**Comment by bhollis** [comment]
This is definitely an idea we've talked about a lot, but it feels super "advanced" - the idea of linking multiple loadouts together may be beyond your average user. However, we should definitely continue to think through it and see if there's a nice way to do this.

Also, keep in mind that we're probably going to have to make major changes to Loadouts when Lightfall drops, so we may not make a bunch of new features until then.

**Comment by jamieastley** [comment]
This was something I was potentially going to have a stab at implementing and PR-ing myself (though I've not ventured into the React world myself previously, be warned 😅), but good point around incoming Lightfall changes, may just hold off until then.

**Comment by molague2021** [comment]
How about exporting those loadouts to a JSON so users can easily import them, kind of a sharing feature, maybe a content creator can export the file place it somewhere for users to easily grab, rather than pausing the video at every second to take a look.

**Comment by bhollis** [comment]
Well we do have a share button that generates a link to the loadout that other people can import into their setup, that feels like enough.
