### ISSUE TITLE
Look of item-drag-container

### ISSUE THREAD

**Issue by Revadike** [DestinyItemManager/DIM#8842]
### Proposed change

So, even though DIM is in darkmode, I've been using Darkreader on DIM since forever, simply because I much prefer the look of this:
![image](https://user-images.githubusercontent.com/4411977/201947642-34856c79-e840-4ba0-a0d5-164126b22b37.png)
Over this:
![image](https://user-images.githubusercontent.com/4411977/201947736-b51463ec-a932-4a8e-8b9e-c1ec306e03e2.png)

The white/light text on a dark background just look better, imo. So, I'm wondering, any chance you'd consider doing this for the default DIM theme?

### How does this fit into your workflow?

Makes it look better (imho)

**Comment by bhollis** [comment]
We've talked about it, but we're not going to do a darker theme - what you've got there is certainly darker but we like the contrast afforded by the polaroid tiles.

**Comment by Revadike** [comment]
Hmm, that's unfortunate. How about just making it an option and disabled by default?
