### ISSUE TITLE
Vendors Tab - Unable to See Possible Weapon Perks

### ISSUE THREAD

**Issue by dannystirl** [DestinyItemManager/DIM#8845]
### DIM Version

7.43.0

### Browser Details

Opera

### OS Details

Windows 10

### Describe the bug

While in the vendors tab, when clicking on a focusable weapon, I expected to see its available perks, but instead saw either an origin trait and random nodes or just empty nodes
- Seasonal weapons: 
    - Star Chart
    - Crown Of Sorrow
    - War Table
- Playlist weapons: 
    - Lord Saladin
    - Saint 14
    - The Drifter

Origin Trait and Random Nodes
![image_2022-11-16_082510503](https://user-images.githubusercontent.com/77759414/202192418-e804cc3b-017f-43c4-91f6-ff7a317a5b69.png)

Empty Nodes
![image_2022-11-16_082433850](https://user-images.githubusercontent.com/77759414/202192281-c75afc33-4223-4ccd-b45e-cb0f32a58637.png)

**Comment by robojumper** [comment]
This is because the vendor is only offering fake weapons and when you buy them, you get the correct, different item instead. We could maybe do some workarounds for specific vendors but you're probably better off searching for those weapons on the Records page and see what perks they have there.

**Comment by humandxp** [comment]
even game shows weapons like that when you have total rng, better when banshee shows your roll and weapon drops how dim shows you. btw go to saint and check fusion, shows magazine as 37, earlier it was as bow.
