### ISSUE TITLE
"Most Popular Weapon Roll" identifier for inventory organizer

### ISSUE THREAD

**Issue by OmniDefenestrator** [DestinyItemManager/DIM#8847]
### Proposed change

Sites like light.gg have breakdowns of what the distribution of each perk is for a given weapon. It'd be cool to have an improved way to identify weapons to keep by simply saying "mark the weapon that has the rolls closest to what the most popular in the playerbase is" so you can keep those integrated directly into DIM.

For example, say you have 20 different Duty Bound autorifles in your vault, and you want to keep one of them (many folks keep one of every weapon). Instead of having to read through every perk of every roll (which can quickly be hundreds of weapons to review), you can press a button that highlights the roll of each weapon that's closest to the "most popular perks" (e.g. first it'd check if you have any perfectly matching "Popular Trait Combos", and if not, it'll see what the highest of the individual perks is and highlight that for you. That way, you can easily sort and keep the "closest to best" of each weapon.

### How does this fit into your workflow?

I prefer to play uninterrupted and then clear out my vault in a separate session. Whenever my vault fills up, I often have 100+ weapon rolls to review, and I'd like to keep one of each weapon, but I don't care enough to test each weapon or pick perks that are particularly good for me; I'd rather just keep whatever's the most popular traits.

**Comment by bhollis** [comment]
Thanks for the idea. This is one we've heard a bunch, and we've talked about it. Unfortunately I don't think it's going to make it into DIM, for a couple reasons:

1. This data is from light.gg - they would need to share the data with us in some easily consumable format, but it's an important part of their site!
2. When we've talked about this "roll popularity", we've generally concluded that it's of limited usefulness despite looking valuable. This info is based on light.gg users uploading their vault, and it cannot discriminate between rolls that were configured a certain way on purpose, and rolls that were left the way they dropped. It's also influenced by vendor rolls and the overall rarity of certain combinations. We think our approach of allowing you to load curated wishlists of good rolls is a better way of approaching the problem.

In the end, we don't need every Destiny tool to present the exact same info, the same way. I'd recommend using the link to light.gg that we provide from the item popup (click the item title, then light.gg) if you want to check your roll against their popularity ratings.
