### ISSUE TITLE
Stray comma in power level

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#8854]
https://reddit.com/r/DestinyItemManager/comments/zenwau/stray_comma_after_infusing_in_game_and_refreshing/

**Comment by robojumper** [comment]
This seems to have gotten worse after #8971, which to me indicates that previously the comma NOT showing was a bug in how DIM used framer and now it shows the comma reliably. Since this is only used for stats, seems best to just replace `toLocalString` with `toString` in `AnimatedNumber`?

**Comment by bhollis** [comment]
Sounds good to me.
