### ISSUE TITLE
season:current filters out season of Plunder weapons instead of Serath

### ISSUE THREAD

**Issue by Luckbox777** [DestinyItemManager/DIM#8855]
### DIM Version

Version 7.46.0.1002098 (beta), built on 12/6/2022, 11:53:28 AM

### Browser Details

Firefox 107.0

### OS Details

Windows 10

### Describe the bug

season:current filters out season of Plunder weapons instead of Serath

**Comment by Luckbox777** [comment]
Would be cool to also be able to use season:19

**Comment by delphiactual** [comment]
you should be on 7.46.1
