### ISSUE TITLE
Add last used field to weapons and armor

### ISSUE THREAD

**Issue by DMcP89** [DestinyItemManager/DIM#8856]
### Proposed change

Add an additional field to weapons and armor that would record the last time they were equipped.

### How does this fit into your workflow?

This would be helpful when organizing my vault as I could tell what weapons and armor I'm actually using and what I can scrap.

**Comment by delphiactual** [comment]
what constitutes used?

**Comment by delphiactual** [comment]
If you equip in-game and before the next update change armor; DIM will have no record...

**Comment by DMcP89** [comment]
@delphiactual @bhollis  great points didn't seems what I'm actually looking for is for Bungie to add this to their API. Still think this would be a useful feature should that ever happen.

**Comment by delphiactual** [comment]
If/when bungie has this we will utilize this info.
