### ISSUE TITLE
Allow using cached manifest data if Bungie API is down

### ISSUE THREAD

**Issue by thomaskchan** [DestinyItemManager/DIM#8859]
### Proposed change

It would be nice for DIM to use the old/cached manifest data if new data can't be gotten from the Bungie API.

### How does this fit into your workflow?

During this weekend's API downtime, I was able to use DIM for a day to at least look up my weapons rolls, loadouts, and light.  This was helpful in tracking down where a particular weapon was, and to compare against new drops.  Doing armor loadouts manually was also possible.  I then accidentally updated DIM from instinct, and now I can no longer see that old data since the new manifest can't be gotten.  It would be nice if there was an offline type mode that would use either a locally cached (or even synced) manifest so you can at least explore your inventory.

**Comment by bhollis** [comment]
Duplicate of #2164
