### ISSUE TITLE
Pinnacle dungeon showing last week's pinnacle

### ISSUE THREAD

**Issue by sushi-juice** [DestinyItemManager/DIM#8867]
### DIM Version

Version 7.47.0.1002107 (beta), built on 12/13/2022, 10:15:19 AM

### Browser Details

Chrome Version 108.0.5359.98 (Official Build) (64-bit)

### OS Details

Windows 10 Enterprise

### Describe the bug

The pinnacle dungeon is showing Shattered Throne, but it's actually Pit of Heresy this week - found on the Progress tab on the website

![image](https://user-images.githubusercontent.com/120607718/207736731-c40349a1-1a28-4d70-8b6f-c356f36f6f85.png)

**Comment by robojumper** [comment]
This is probably Bungie-net/api#1724
