### ISSUE TITLE
Multiple custom totals

### ISSUE THREAD

**Issue by Revadike** [DestinyItemManager/DIM#8873]
### Proposed change

Instead of just one per class, allow two/tree (or more) custom totals (for every class).

### How does this fit into your workflow?

I have different needs for specific purposes. For example, the stats I want to maximize for PVE is different than for PVP.

**Comment by Revadike** [comment]
Or perhaps, allow us to edit the total formula on-the-fly.

**Comment by nev-r** [comment]
someday yes

**Comment by bhollis** [comment]
Duplicate of #7973
