### ISSUE TITLE
Latest beta update (7.48.0.1002115) on Chrome MacOS only showing header and everything else is empty

### ISSUE THREAD

**Issue by thomaskchan** [DestinyItemManager/DIM#8877]
Version 7.48.0.1002115 (beta), built on 12/19/2022, 6:36:42 PM

My friend was complaining about DIM being broken but it was working for me.  After updating to the latest beta version I now have the same symptom where only the header shows up but everything below is blank.

To get the version, I even had to open "About DIM" in a new tab.

Normal non-beta works fine.

**Comment by barn** [comment]
Logging out and then logging back in I'm presented with the D1/D2 profile selection screen, and it proceeds no further.
I don't see anything obvious in the console sadly.

**Comment by MeatSim** [comment]
Same issue in Edge on PC

**Comment by thomaskchan** [comment]
Tested on Firefox and have similar behavior, with the additional error:

Something went wrong                           SecurityError
The operation is insecure.

**Comment by robojumper** [comment]
> Is there anything we can do to help diagnose what made those upgrades unhappy?

Thanks for offering to help but I think bhollis has identified the dependency and change causing this issue: #8879.
