### ISSUE TITLE
Iron Ghost Display Issue

### ISSUE THREAD

**Issue by wein3967** [DestinyItemManager/DIM#889]
In both public and beta branches, there is a two-tone color band on the quality/light text. The quality is also showing 0% for IB ghosts.
![ghosts](https://cloud.githubusercontent.com/assets/11590326/18418912/00287074-7815-11e6-8845-4447cb752217.PNG)

**Comment by delphiactual** [comment]
I'm pretty sure this is related to the bungie bug, where it also shows as a white shell. It does this for my sunlit shell as well.

**Comment by wein3967** [comment]
Possibly, I just noticed that my Blindsight Greaves (ToO) are doing the same thing.
![blindsight g](https://cloud.githubusercontent.com/assets/11590326/18419044/80c98eea-7818-11e6-838e-36e441dc4712.PNG)

**Comment by bhollis** [comment]
Fixed it. Quality will be back when Bungie fixes the items.

**Comment by chuckreynolds** [comment]
ditto. following issue. 
![screen shot 2016-09-14 at 14 46 22](https://cloud.githubusercontent.com/assets/46185/18531609/fcf0a0e2-7a8b-11e6-938f-ca28e062d93b.png)

**Comment by SunburnedGoose** [comment]
![screen shot 2016-09-14 at 5 01 47 pm](https://cloud.githubusercontent.com/assets/984608/18531642/f65184de-7a9c-11e6-9a61-ae027355b807.png)

**Comment by SunburnedGoose** [comment]
Let's look at this again.

**Comment by kyleshay** [comment]
stats aren't coming back from bnet... not seeing the two-tone color issue on mine anymore. weird...

maybe the stats object is coming back for some items, but each perk is 0? @SunburnedGoose would you mind printing out the stats for that problematic ghost shell?

<img width="807" alt="screen shot 2016-09-14 at 6 17 20 pm" src="https://cloud.githubusercontent.com/assets/424158/18532052/95e9932e-7aa7-11e6-914c-9e21d675ae5f.png">

**Comment by SunburnedGoose** [comment]
![screen shot 2016-09-14 at 5 21 24 pm](https://cloud.githubusercontent.com/assets/984608/18532124/b07ce838-7a9f-11e6-93c1-bdc021cf2330.png)

**Comment by chuckreynolds** [comment]
v`3.10.3`fix works. 👍  
![screen shot 2016-09-14 at 17 43 32](https://cloud.githubusercontent.com/assets/46185/18534697/d6f97820-7aa2-11e6-9038-5161504f7350.png)

**Comment by SunburnedGoose** [comment]
Can we review this again for Iron Banner ghosts and other times.  I can see their stats in gear manager.
