### ISSUE TITLE
Multiple Matching Wishlist Rolls on one weapon

### ISSUE THREAD

**Issue by RedDwarfian** [DestinyItemManager/DIM#8893]
### What
Some weapons, from fixed-roll weapons, to random rolls with multiple barrel options, have the potential for multiple perk combinations to match rolls that are on your [Wish List](https://github.com/DestinyItemManager/DIM/wiki/Wish-Lists). Current functionality shows the 👍 icon if any available perk combination on a weapon matches a wishlist perk combination. For example, see the Felwinter's Lie's [Armory](https://github.com/DestinyItemManager/DIM/wiki/Armory):

![image](https://user-images.githubusercontent.com/19349621/209452350-b5b84a4c-afbc-4f07-a08c-cb96e84a2b87.png)

However, when you look at the weapon's [Item Popup](https://github.com/DestinyItemManager/DIM/wiki/Item-Popups), it shows the information and suggested roll for the _first_ Wishlist match, regardless of if the currently equipped perks match a different entry on the Wishlist:

![image](https://user-images.githubusercontent.com/19349621/209452429-7009fa00-e2eb-4dde-8582-8038b884ad7e.png)

I am proposing a new concept within the Item Popup: The Displayed Wish List Roll. This will allow the user the ability to switch which Displayed Wish List Roll (and its associated Notes) is showing, depending on the perk combinations, or it will allow the user to manually select it.

### Acceptance Criteria

- [ ] When opening the Item Popup, The Displayed Wish List Roll will default to...
  - [ ] If the currently selected perk combination matches a single Wish List entry, default to that one.
  - [ ] If the currently selected perk combination matches multiple Wish List entries, the Displayed Wish List Roll will default to the one that matches the most perks (e.g. if Subsistence/Demolitionist and Subsistence/Demolitionist/Assault Mag are on a Wish List, a weapon with all three will default to the latter). 
  - [ ] If the currently selected perk combination is not on a Wish List, it follows current behavior, and the Displayed Wish list Roll will default to the first Wish List match.
- [ ] A lower-opacity 👍 icon should show on all perks that match a Wish List roll, but do not match the currently displayed Wish List roll. (e.g. if a weapon has Corkscrew Rifling and Extended Barrel as barrel options, and both barrels are on different Wish List rolls, but Corkscrew Rifling is on the Displayed Wish List Roll, the Corkscrew Rifling will have the full opacity 👍, and the Extended Barrel will have a lower-opacity 👍 on it)
  - [ ] The Tooltip for such perks will have the lower-opacity 👍 icon at the bottom, with the message "This perk exactly matches a different weapon roll on your wishlist."
- [ ] The "Preview Wishlist Perks" button becomes a combination button-dropdown if there is more than one Wish List match. Clicking the main part of the button will follow current behavior. The dropdown portion will be a badge with the number of Wish List rolls that match. 
- [ ] The styling of the dropdown matches the Tag dropdown.
- [ ] The dropdown selection will show the icons of all possible matching Wish List rolls, in a similar way to the Armory displays the rolls. 
- [ ] The Displayed Wish List Roll will have a gray background to differentiate it. The others will have normal background color.
- [ ] Clicking the dropdown entry will assign the selected as the Displayed Wish List Roll, and preview that roll.
- [ ] When previewing perks, if the new combination matches a Wish List roll, it will make that the Displayed Wish List Roll. If it does not, do not change the Displayed Wish List Roll.

### How does this fit into your workflow?

Only displaying the first matching Wish List perk combination doesn't always help when you have weapons with multiple barrel options, multiple magazine options, or even if you have multiple available perks. Just showing the first matching Wish List roll, especially when using the Voltron or Choosy Voltron which have almost 100,000 rolls, may mean the user overlooks better barrels that more match their play style. Or it may be much less helpful if there are several potential barrel and magazine rolls available to the user, but the one that is displayed is one that just has "Subsistence/Demolitionist", because it was the first in the Wish List.

Letting the user know that multiple perk combinations can be rolls on their wish list is valuable.

**Comment by philkernick** [comment]
Bumping this, but adding a different somewhat simpler proposed solution.

I have a Hero's Burdan that matches multiple wishlist lines:
![image](https://user-images.githubusercontent.com/25425159/234546066-bf695dc3-54a9-4e87-a501-94f37c615c05.png)

But as the original poster noted, only the first one gets reflected in the item popup.
![image](https://user-images.githubusercontent.com/25425159/234546222-e96c43fc-1ea9-43c4-9623-9adc67489a1a.png)

Note that Flared Magwell does not have the thumbs up icon, even though this is a wishlist roll.

My suggestion is to mark both of the perks that match with the thumbs up, so in my case, both Appended Mag and Flared Magwell would have the thumbs up in the item popup.
