### ISSUE TITLE
Chroma Keys not showing up Beta 3.10.2.383

### ISSUE THREAD

**Issue by hiddnen** [DestinyItemManager/DIM#890]
just realized chroma keys now that they are under ornaments arent showing up via dim beta. not showing on character or vault. this may already be known. sorry if its a repeat.

**Comment by bhollis** [comment]
Unfortunately, Bungie moved Chroma to Ornaments, but hasn't released the Ornaments category in the database yet. You'll see that you're unable to see them in the Companion app or on Bungie.net either. We'll just have to wait for the update on the 20th.
