### ISSUE TITLE
DIM stuck at loading destiny accounts since the downtime in early dec.

### ISSUE THREAD

**Issue by Mickxz** [DestinyItemManager/DIM#8901]
### DIM Version

Version 7.49.0 (release), built on 12/25/2022, 11:15:06 PM 

### Browser Details

Opera 93.0.0.0

### OS Details

Windows 10

### Describe the bug

Ever since the time the api's went down on early december, i can't get dimm to work even after doing all the troubleshooting. i've tried using 3 different browsers (opera. brave, edge), clearing all the cache data and even using private tabs, but it always get stucked at loading destiny accounts.

**Comment by delphiactual** [comment]
https://github.com/DestinyItemManager/DIM/wiki/BungieError-1618

**Comment by Mickxz** [comment]
Nvm, bungie just disabled the API at the same time i just got time to play again.
