### ISSUE TITLE
Let DIM be accessible on the backup up data when bungie API is down

### ISSUE THREAD

**Issue by MichaelTorfs** [DestinyItemManager/DIM#8905]
### Proposed change

DIM settings shows that it backups some data.

Is this data enough to have a kind of "bungie off-line" mode:

- be able to view and query your inventory
- not being able to move or change anything

### How does this fit into your workflow?

DIM keeps being useful when Bungie API is down

**Comment by bhollis** [comment]
Yes this shipped to beta yesterday.
