### ISSUE TITLE
Destiny Server Errors on Ipad

### ISSUE THREAD

**Issue by spcrossman** [DestinyItemManager/DIM#8909]
### DIM Version

7.49.0

### Browser Details

IPAD app

### OS Details

IOS

### Describe the bug

For the last 2 days everytime I try to change my loadout I get "8mod errors, Bungie.net servers are down for maintenance" On the first day I believed it. But after trying again today, I know now there is an error either on my ipad or elsewhere. 

Cheers

**Comment by spcrossman** [comment]
Further to my IPAD issue. I just jumped on to my PC and got the same error.

![image](https://user-images.githubusercontent.com/54345626/210045119-4b330011-a51f-443e-989a-46b0798a373d.png)

**Comment by geekrumper** [comment]
The bungie servers are actually down. You can reassure this with the official mobile client.

**Comment by spcrossman** [comment]
Cheers for the update. Very much appreciated. 👍 :-)
