### ISSUE TITLE
Limit on tag storage?

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#892]
From #471, @delphiactual says:

> Ok... then I've experienced a bug after tagging all my gear and closing DIM, upon reopen I lost some tags, (I tagged everything on lead-up to ROI)

I wonder if we reached the storage limit for Sync Service, or whether we had some other problem. @delphiactual, could you see if you can repro the bug with the inspector open?

**Comment by SunburnedGoose** [comment]
There is an 8k limit for each item in the sync service. This is why each loadout is a unique key with a 'master list' for Loadouts.

**Comment by delphiactual** [comment]
@bhollis, I probably have the wrong thing open, I also cut out load time (for your viewing pleasure)

![animation](https://cloud.githubusercontent.com/assets/4798491/18427371/c9a30d3c-7884-11e6-94be-8d9feb72c96f.gif)

**Comment by wein3967** [comment]
I just ran into this one as well. I transferred over my Keep/Trash spreadsheet information to DIM on Saturday. Just got back home and it looks to have remembered only ~1/2 the designations.

**Comment by Marc05** [comment]
I counted 119 items with a tag and notes. When I tagged the 120th, it reverted back to 119 after a refresh. I turned off Chrome's sync service and tried again, but same results.

**Comment by bhollis** [comment]
Yup, we definitely know that our current storage system is insufficient.

**Comment by Gonzo77** [comment]
Thank you for all the updates / fixes / additions lately.  Is there any progress on getting over this storage limitation for tagging an notes?  I mean this gets addressed - it's absolute nirvana for me and I imagine many other gear hoarders like myself!

**Comment by bradchoate** [comment]
Also very interested in this issue. Thought I was losing my mind, having to reapply tags for some things but not others.

**Comment by bhollis** [comment]
No progress to report. We've been working on other stuff :-)

**Comment by wyoming01** [comment]
Will data from beta.dim.com attempt to sync using Chrome?  I've been remotely connecting to my home PC during breaks at work to tag items since I'm not seeing them sync to my work laptop, but perhaps I'm trying to do something that is only supported on the extension.  I cleared my synced data on Google's servers this morning and signed into both machines again.  Tagged items remained on home machine, but still no tags synced across to work machine.  Thanks for all the hard work everyone!

**Comment by bhollis** [comment]
It will sync eventually using google drive. Today it only stores tags locally. 

-Ben

**Comment by bhollis** [comment]
Fixed by the storage sharding I did (I think). Google Drive coming soon.
