### ISSUE TITLE
Indicate completed seals in Records

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#8923]
We show when all of the sub-records in a node are complete, but we should specially highlight when a seal has reached its completion threshold (i.e. the title is unlocked)

**Comment by NekoDrone** [comment]
Hi! I'm intending to try my hand at this. Would this requirement be based off the actual completion of the seal from Bungie, or from the 'completed' bool in PresentationNode?

**Comment by NekoDrone** [comment]
For clarification: For example, the Scallywag seal has an unlock requirement of 8/8 in-game, but is listed as 8/9 in DIM. Which means it doesn't count as 'completed' in PresentationNode even though it's completed.

**Comment by bhollis** [comment]
I was thinking it would go off whatever the game counts as completed.

**Comment by bhollis** [comment]
You'd want to look at the record linked from the seal's `completionRecordHash`, then see if that record's objective is complete. e.g. for Scallywag: https://data.destinysets.com/i/PresentationNode:1321008453/Record:4176879201/Objective:2900615122

Maybe even display the associated title when the seal is complete.
