### ISSUE TITLE
Are tags local to a device?

### ISSUE THREAD

**Issue by shockthealien** [DestinyItemManager/DIM#893]
I spent some time tagging items yesterday on my main mac and this morning popped in DIM at work and none of my tags are there. Are they device restricted?

**Comment by shockthealien** [comment]
yeah, always logged into chrome i think. The ones I did today at work show up now at home but the ones i did yesterday are gone. Oh well

**Comment by shockthealien** [comment]
is that the only way we can have them sync? i use an old laptop for DIM while I play on the ps4 and chrome doesnt let me sign in or auto update it any more (did buy a chromebook exclusively for this but turned out to be a duff one and got bricked after a few weeks) so every time i log on DIM on it it wipes all my tags :(

**Comment by bhollis** [comment]
Yeah, you have to be logged into Chrome.

**Comment by kyleshay** [comment]
#892 similar issues in, will be fixed once we merge drive sync
