### ISSUE TITLE
Authentication doesn't require verification?

### ISSUE THREAD

**Issue by d2a6on** [DestinyItemManager/DIM#8936]
### DIM Version

DIM Version 7.50.3 (release), built on 1/4/2023, 9:35:09 AM

### Browser Details

Edge 108.0.1462.54 - Windows 10

### OS Details

Windows 10

### Describe the bug

I don't know if DIM or Stream Deck has gotten a new update recently. I know the other day whenever I link my stream deck, it would ask me to verify communication with DIM and stream deck by choosing 1 of 3 codes on the Stream Deck that matches the one shown DIM. Just recently, I'm assuming there has been a new update, it doesn't require me to verify anymore and Stream Deck won't even link to DIM. So far the only work around is to add a loadout plugin onto the stream deck and it would prompt me to verify if the code on stream deck matches that on DIM.

My apologies if this is a repeat post on this issue. Also, I'm using the Stream Deck XL. I'm not sure if that makes a big difference or not.

**Comment by delphiactual** [comment]
https://github.com/dim-stream-deck/com.dim.streamdeck/

**Comment by d2a6on** [comment]
I've tried uninstalling Stream Deck and DIM and reinstalling everything. Reinstalled the DIM plugin for the Stream Deck. There's no verification to authenticate the pairing until you load a mod and Stream Deck asks you to verify if the code shown matches the one that appears on DIM, and that is the only work around everytime you load up Stream Deck and DIM and enable the Stream Deck Plugin on DIM. I'm not sure if there was a recent update, however, when I would enable the plugin through DIM, it would ask me to verify by selecting one of three codes on the Stream Deck that matches the one shown on DIM.

Thank you anyway, I'll continue to use both with the work around until it gets resolved somehow. Thank you for the response.

**Comment by delphiactual** [comment]
3 requirements
- the latest DIM (beta/app 7.50.3 or greater) 
- the latest plugin (>= 2.0.3)
- 6x version of Elgato application

**Comment by delphiactual** [comment]
Action settings empty / broken
- remove the action and create it again

**Comment by delphiactual** [comment]
Authentication keeps prompting (  >=2.0.3 version  )
- click "RESET ALL" button (on plugin)
- click "DE-AUTHORIZE" button (on DIM)
