### ISSUE TITLE
Add a Duplicate Cleaner feature

### ISSUE THREAD

**Issue by yannickguillemot** [DestinyItemManager/DIM#894]
With people cleaning up their vault space before the next expansion, I thought about one feature similar to the gather engrams feature. Instead of gathering engrams, it would send all duplicates with lower light and lower XP to one character for manual dismantling.
One question remains: some people keep duplicates with different perks, so maybe provide an UI to compare and decide whether or not we want to send for dismantling.

**Comment by delphiactual** [comment]
@yannickguillemot, with tags being implemented maybe a `gather delete` would be a more intuitive option

**Comment by SunburnedGoose** [comment]
Filter for is:delete and use the loadout move feature @delphiactual

**Comment by bhollis** [comment]
Closing in favor of using the search loadout feature. For example, "is:dupe light:<=340".

Duplicate comparison is tracked in #494.
