### ISSUE TITLE
Can't scroll selected mods in mod picker

### ISSUE THREAD

**Issue by ryan-rushton** [DestinyItemManager/DIM#8949]
### DIM Version

Latest

### Browser Details

Chrome, iOS app

### OS Details

OSX

## Overview

The selected mods cannot be reliably scrolled in the mod picker under certain conditions. So far I have confirmed that the bug exists for

- iOS app, both on portrait and landscape orientations
- Chrome developer mode on OSX, portrait only

I have confirmed the bug doesn't exist for

- Chrome on windows 11, using developer mode to mock mobile devices it works fine
- Chrome on windows 11, making the viewport small enough to force scrolling to be 
- Chrome on OSX, landscape mode works fine

## Steps to reproduce

1. Open loadouts screen and edit a loadout
2. Click the add mods button
3. Add enough mods so they overflow the container
4. Try to scroll the selected mods container horizontally

## Example issue

https://user-images.githubusercontent.com/7344652/211194286-be234378-cb5b-4c67-95dc-c615b30c0032.mov

## Investigation so far

Note in the above video that the mods will scroll when I am hovered over the selected mods in portrait. On landscape, the background app will scroll.

I have tried messing around with the stacked overflow flex containers but nothing seems to alleviate the issue. I think something might be going on with the animation libraries for the sheet but no real evidence to support that at this stage. I am 90% sure that something in the sheet itself is capturing the scroll event and stopping the mods from being able to scroll.

**Comment by bhollis** [comment]
This was the problem with the compare page - horizontal scrolling within the sheet is mega screwed up.

**Comment by ryan-rushton** [comment]
I finally started the refactor to use framer instead of spring the other night. Maybe that might fix some stuff. Hoping to have it done by the weekend at some stage so I will keep you updated if it changes anything
