### ISSUE TITLE
Show additional quests steps in UI

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#895]
https://www.reddit.com/r/DestinyItemManager/comments/52f59c/full_quest_steps_rewards/

**Comment by bhollis** [comment]
I think we directly show the "item" (which is a quest step) and there's a hash we can use to get back to the quest itself for more info.

**Comment by jflayhart** [comment]
I can work on this.

**Comment by kyleshay** [comment]
Cool Jflayhart! It would be really nice to have something like this in DIM before D2!

**Comment by jflayhart** [comment]
Should we just go off this http://imgur.com/a/YTc1E or do we need to talk UI?

**Comment by bhollis** [comment]
Closing out D1-specific stuff that isn't going to make it.
