### ISSUE TITLE
Loadout Optimizer remembers the last loadout it was loaded with

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#8950]
1. Open a loadout for editing
2. Click "optimize loadout"
3. Click "Loadouts" in the header
4. Click "Loadout Optimzier"
5. Click "Compare Loadout" on one of the sets

Unexpectedly, the loadout from step 1-2 is still selected in the compare popup.

**Comment by robojumper** [comment]
I can't reproduce this? Or at least I don't see the problem, the Compare Loadout sheet has to pick some loadout to compare to, and that could by chance happen to be the loadout previously opened (or not. For me it's always the same loadout it compares to).

The main thing that reliably indicates that LO was loaded with a particular loadout is that this tooltip 

![grafik](https://user-images.githubusercontent.com/14299449/211258457-9f91d9e9-93c0-47bd-9f2e-252b1193df0f.png)

mentions a loadout by name, and after step 4 it doesn't for me. Does it still show a loadout name for you?

**Comment by bhollis** [comment]
I see, I may have just been confused by the intended behavior.

I think I'll maybe take a stab at some of the larger UX changes I've been wanting to try for LO soon.
