### ISSUE TITLE
Can't equip or make loadouts with mods not previously acquired in collections. 

### ISSUE THREAD

**Issue by ItsCrocoSwine** [DestinyItemManager/DIM#8968]
With most mods being unlocked now, it seems DIM only lets you use mods in your collections.
![Screenshot 2023-01-11 160700](https://user-images.githubusercontent.com/28183952/211944778-a4650bb2-a314-4c9e-86e2-35c992dfcd53.png)
![Screenshot 2023-01-11 160814](https://user-images.githubusercontent.com/28183952/211944807-08f3f83c-458b-4f75-b0e3-8f1800b49174.png)

**Comment by bhollis** [comment]
Thanks, this is a known issue with the most recent update
