### ISSUE TITLE
Add toggle in loadout to specify mod placements.

### ISSUE THREAD

**Issue by TravisCalder** [DestinyItemManager/DIM#8976]
### Proposed change

While editing a Loadout, under the "Mods" section add a toggle for "Specify Mod Locations", which defaults to Off.

When the Toggle is turned on:
- The view changes from a list of mods to a display of the five inventory slots.
- Initial placement of mods that were already selected should be based on the same heuristic as "Show Mod Placement"
- A slot can be clicked and the user presented with options for that slot
- The user can select a mod, and the slot will be updated in the UI appropriately

When a loadout is applied, if the "Specify Mod Locations" is turned on:
- The specified locations for each mod will be used
- If a mod fails to apply it will be skipped with a warning to the user and the rest of the mods applied

### How does this fit into your workflow?

In order to give myself more build flexibility, I've separated my loadouts into 3 types:
 - "Armor" loadouts, which equip a specific set of armor (usually based on an exotic) and the stat-mods for that armor set.
 - "Style" loadouts, which specify shaders and legendary ornaments for each armor piece
   - _Note: When I'm using an exotic, I just let the ornament for that slot fail_
 - "Mode" loadouts, which apply things like combat or weapon mods and pull a specific set of guns.
   - _Note: These never contain stat-increase mods, since which ones I need vary by what armor I'm using_

For example, I might use a "Armor: Wormhusk" loadout to put on my armor, a "Style: Scarecrow" loadout to make it look cool, and then a "Mode: PVP HC/Shotgun" which pulls my favorite weapons and applies mods like targetting/unflinching.

This has allowed me to use a lot more of my favorite "looks" in a much wider choice of activities, where "complete" loadouts like I was using before tended to restrict me into only using specific exotics or styles in activities I had set them up for.

Currently when applying my "Mode" loadout DIM will often remove my stat-increasing mods because it isn't aware that I've applied them separately. Allowing me to specify exact mod placements fix this and allow me to better control how loadouts get applied.

**Comment by delphiactual** [comment]
#7421

**Comment by TravisCalder** [comment]
Sorry about that, I did search for it and didn't see it - my fault. The issue mentioned would solve my need 👍
