### ISSUE TITLE
Search items by the notes of loadouts they belong to

### ISSUE THREAD

**Issue by Korrasera** [DestinyItemManager/DIM#8977]
### Proposed change

Add a new search filter called hashtag: that allows you to filter on the hashtags entered into the notes or title of loadouts.

### How does this fit into your workflow?

With the release of the new functionality to add hashtags to loadouts for ease of organization, it'd be great if we could do a search filter using those hashtags. That way we can easily integrate hashtags into every aspect of inventory management.

If you want to carry all of your pve loadouts you can do hashtag:pve. If you want to avoid putting any of your pvp gear on your character you could do -hashtag:pvp. And so on.

I use is:armor is:inloadout is:invault (and variations) to make sure that I'm carrying all of my primary gear with me at all times, and adding hashtag to that would make it very easy to start segmenting out some loadouts that I don't need to have on me all the time, like my Iron Banner gear.

**Comment by Korrasera** [comment]
@delphiactual, that doesn't actually work, unfortunately. Searching by hashtag or notes only works on the Loadout page and it's just a flat text search and it can't be used to filter gear on the Inventory page.

**Comment by delphiactual** [comment]
it literally does, loadout notes are not applied to items
![image](https://user-images.githubusercontent.com/4798491/212402609-2adc8866-75a8-4f5d-af1b-9111c7e64774.png)

**Comment by robojumper** [comment]
FWIW the `inloadout` filter has a secondary format where `inloadout:#pvp` will match items in loadouts that have `#pvp` in their name. Shouldn't be too difficult to include notes in it (or make another filter that does).
