### ISSUE TITLE
Items in vault have 'equipped' property set to true.

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#898]
I don't know the scenario yet but I am able to move items into the vault somehow and they keep their equipped status as true.  This breaks Loadouts because if it encounters an items marked as equipped, it tries to find a similar item to unequip, but if you're in the vault, it cannot find an item and breaks the loadout code. 

Try it by making a loadout, put an item in the loadout into the vault, and change that items equipped property to true.  Loadouts failes.  

Have to find out what path in the code leaves equipped true.

**Comment by bhollis** [comment]
Hmm, I'm going to need help reproducing this. I've tried creating and applying various combinations of equipped and unequipped items in loadouts to the vault, but they don't show up as equipped.

I've pored over the loadoutService and itemService code, and there's a few places where we check that we're not equipping stuff in the vault, and we definitely switch `equipped` to false for all loadout items going into the vault.

**Comment by SunburnedGoose** [comment]
I tried to do it too and can not repo.  It does happen, but not when I want it to :)

**Comment by bhollis** [comment]
I believe you! I just don't have a good hint as to where to look.
![bitmoji](https://render.bitstrips.com/v2/cpanel/10212032-136424313_5-s4-v1.png?transparent=1&width=246)

**Comment by bhollis** [comment]
I haven't seen this in forever. I'm so into fixing this, but I'll need a consistent repo to do anything about it.
