### ISSUE TITLE
DIM background tasks causing spikes in CPU

### ISSUE THREAD

**Issue by Zero834** [DestinyItemManager/DIM#8986]
DIM is doing random unexpected background tasks which is leading to game stuttering.

Having DIM open on a browser with the game causes DIM to spike in CPU usage at random intervals. 

I've never noticed this before but recently within the last couple months started seeing in-game stuttering and slowdown. and upon further investigation the CPU spikes were coming from my browser. Then upon disabling all extensions and monitoring the task manager I was able to determine it was occurring due to DIM. 

![DIMcpu](https://user-images.githubusercontent.com/54686180/212528956-ed3ecef0-3f7d-4bbd-a3d6-5ca9195de60b.JPG)

**Comment by bhollis** [comment]
DIM automatically refreshes while you're in game and the tab is visible (you'll see a green dot on the refresh icon). It shouldn't take much CPU but it will take some.

**Comment by bhollis** [comment]
Do you have any extensions installed, like Clarity?

**Comment by Zero834** [comment]
No, I thought Extensions may have an affect so I ran tests without extensions (tool bar in screenshot showing no extensions) . Never heard of Clarity. The DIM window was in the background while playing D2. Background refreshing is very frequent between 30-60 seconds. The CPU spikes are the issue, I've had moments where I'm lining up a shot and it freezes or stutters and then I'll miss. 

maybe please implement a refresh setting, auto refresh or refresh only when window is active or manually only. 

![image](https://user-images.githubusercontent.com/54686180/212770436-08e0f366-a93b-4d1b-9fc8-88fccd5c5040.png)

**Comment by bhollis** [comment]
Well, we'll continue to optimize DIM.
