### ISSUE TITLE
Add `is:ritual`

### ISSUE THREAD

**Issue by Revadike** [DestinyItemManager/DIM#8989]
### Proposed change

It would be handy to have a filter to quickly find these type of guns. 

### How does this fit into your workflow?

Especially useful when working on this gambit triumph:
![image](https://user-images.githubusercontent.com/4411977/212596353-cb54fc46-efb6-4bc7-af95-d6c653f80693.png)

**Comment by Revadike** [comment]
(sub-issue):

`is:seraphic` or maybe `vendor:exoframe` (+ other vendors) would also be nice
![image](https://user-images.githubusercontent.com/4411977/212597565-cdd1b97e-44a4-491e-b891-03d011c75552.png)

**Comment by delphiactual** [comment]
Try `source:rasputin` other is PR in progress

**Comment by delphiactual** [comment]
https://github.com/DestinyItemManager/d2-additional-info/pull/436

Also `source:rasputin`
