### ISSUE TITLE
Loadout Builder is not i18n compatible

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#899]
@ericnelson0, @bhollis: Many of strings are hardcoded, most of these have already been translated and are being used throughout the rest of DIM, making loadout builder i18n compatible would be awesome..

**Comment by ericnelson0** [comment]
I'm working on the builder now. So i'll go through and update. Thanks for the warning.

**Comment by ericnelson0** [comment]
Looks like the only translations available for the builder are the bonus types (int/dis/str) is this correct?

**Comment by delphiactual** [comment]
No, the other translations are provided by DIM itself from the bungie API, all the armor slot locations...

**Comment by ericnelson0** [comment]
Oh, gotcha. There is still a lot of hardcoded text that needs to be translated. Like the help section.

**Comment by delphiactual** [comment]
Yeah, if you make thing translateable, and put them in the i18n, english section I will get the easy translates done (e.g. Loadout Builder, Back to DIM...) The longer hard-coded stuff will be handled separately if I understood @bhollis correctly...

**Comment by bhollis** [comment]
Yeah as much as possible, try to rely on the stuff from the manifest - the actual stat defs, etc. We should only have to translate our own strings.

**Comment by ericnelson0** [comment]
Ok, I'll focus on this soon.

**Comment by delphiactual** [comment]
Closing in favor of https://github.com/DestinyItemManager/DIM/issues/1029
