### ISSUE TITLE
Total Randomization Loadout Options

### ISSUE THREAD

**Issue by lowPolySkeleton** [DestinyItemManager/DIM#9000]
### Proposed change

have an option to randomize pretty much every aspect that can be changed with the ability to toggle certain things not being changed i.e. Change aspects but not fragments or keep armor the same but change mods (or vice versa)

Subclass, Aspects, Fragments, All abilities (if possible), weapons, armor, mods, ghosts, sparrow, ship, emblem (maybe), shaders (if reasonable), ect (if I'm missing anything)

OG post here https://discord.com/channels/316217202766512130/1053826381336813690

### How does this fit into your workflow?

adds some control to randomization.

**Comment by bhollis** [comment]
I'd probably do this as part of the loadout editor UI, by having a new menu per section that allows you to choose random - or maybe in the item picker?

**Comment by robojumper** [comment]
The simplest way would be to add a "randomize" counterpart to every "Sync from equipped" button in the loadout drawer

![grafik](https://user-images.githubusercontent.com/14299449/212775431-fd6033e7-78f7-4871-9518-d23a2a127459.png)

Only drawback is that "randomize aspects but not fragments" would be difficult to express but maybe that's too detailed anyway?
