### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by AHaP1998** [DestinyItemManager/DIM#9002]
### DIM Version

Version 7.52.0 (release), built on 1/15/2023, 9:19:51 PM

### Browser Details

Version 109.0.5414.75 (Official Build) (64-bit)

### OS Details

Windows 10

### Describe the bug

Whenever I launch dim memory in RAM keeps building up until it crashes out, throws error SBOX_FATAL_MEMORY_EXCEEDED. This issue is only happening on the DIM website. Logs attached in .txt file

[DIM Crash.txt](https://github.com/DestinyItemManager/DIM/files/10428715/DIM.Crash.txt)

**Comment by bhollis** [comment]
You wouldn't by chance have the Clarity extension installed, would you?

**Comment by AHaP1998** [comment]
I do should I get rid of it?

**Comment by bhollis** [comment]
Yes, it's causing the problem.
