### ISSUE TITLE
Official Light and Dark Modes

### ISSUE THREAD

**Issue by lowPolySkeleton** [DestinyItemManager/DIM#9010]
### Proposed change

I'd like to officially create Light and Dark Modes for DIM (maybe even more fine tuned settings for people that like light Polaroids but otherwise dark UI). In general having these is just an accessibly win and I'd like to make it happen.

### How does this fit into your workflow?

different users have different viewing needs based on a variety of factors and having these modes available helps in keeping DIM accessible.

**Comment by bhollis** [comment]
As long as they aren't hideous 🙏 

I've done this before with using a suite of CSS variables defined at the root of the site that can then be overridden, that makes it easy to build custom themes as well.

**Comment by guise** [comment]
Created a PR for style variable refactoring + visual tweaks in preparation for more fully fledged theming 

Would appreciate any feedback on the suitability of the visual/design tweaks

**Comment by bhollis** [comment]
One thing I'd like to see from the official dark mode is to avoid the "all black" styling for the item tiles that loses the visual association between the colorful, bright item pictures and the "polaroid" bar with the element/power.

**Comment by guise** [comment]
@bhollis Re: the visual tweaks I reverted. 

I'd propose considering these before theming proper as they would apply to all themes. 

The visual tweaks would aim to improve: 

- Visual hierarchy: by using outlines + shadows for better layer separation of popups/dropdowns to show the z-index
    
    ![image](https://github.com/DestinyItemManager/DIM/assets/1396158/1fa4242d-da67-4408-960a-ae99e66238d9)

- Accessibility: by making clearer interaction styles (click to perform operation vs click to expand vs hover for tooltip) 

I'm assuming the most efficient way to review/manage these would be as discrete PRs. (linked to this issue?) — I can include more details w/ before & afters PR descriptions.

**Comment by bhollis** [comment]
Sounds great - smaller, individual PRs are definitely the best so we can discuss the changes and merge them independently. For direction, I'll mention that while I do want better separation and visual hierarchy, I'd like to see if we can avoid "heavy handed" stuff like borders and underlines where possible. While we aren't aiming to replicate the in-game UI, I do like how they tend to work with backgrounds and padding to achieve that hierarchy.
