### ISSUE TITLE
Artifact mods not unlocked?

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#9013]
<img width="596" alt="image" src="https://user-images.githubusercontent.com/313208/213639207-fc6ef20a-af91-4f2f-99b1-126ea11c9790.png">

I have most artifact mods unlocked, but they show dimmed out on the loadout screen and don't appear at all in the mod picker.

**Comment by delphiactual** [comment]
during the hotfix Bungie reset the artifact, check in-game if yours was reset

![image](https://user-images.githubusercontent.com/4798491/213689253-7dc05b5b-a7ca-44c6-afd5-3d82171836cc.png)

**Comment by bhollis** [comment]
Oh wow
