### ISSUE TITLE
Wrong loadout shown in "compare loadouts" from optimizer

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#9018]
I click "Compare loadout" here:
<img width="862" alt="Screenshot 2023-01-20 at 9 47 42 PM" src="https://user-images.githubusercontent.com/313208/213845648-fb1c75c2-8d26-4574-be89-19c387cfef3b.png">

And see this:
<img width="1716" alt="Screenshot 2023-01-20 at 9 47 48 PM" src="https://user-images.githubusercontent.com/313208/213845617-9573dd3b-1847-4f84-99d6-b2a7b69a40cc.png">

**Comment by robojumper** [comment]
What's wrong about the loadout? The items have fashion applied in the preview because the loadout has fashion, and the loadout comparison sheet doesn't take LO's rules into account so the stats are lower because LO assumes the armor is masterworked and the comparison sheet doesn't.

**Comment by bhollis** [comment]
I guess it's hard to see in the screenshot, but the loadout I clicked on is clearly not the one shown under "Optimizer set" - in fact the "Optimizer Set" and "Existing Loadout" appear to be the same. A good tipoff are the boots, which are blue in the compare screen but purple in the optimizer itself.

**Comment by robojumper** [comment]
The optimizer set says "Existing Loadout" in yellow letters, so that makes sense. The boots are blue because the ornament is blue and the loadout preview applies the ornament.

**Comment by bhollis** [comment]
Linking #9161
