### ISSUE TITLE
Display perk combination rarity

### ISSUE THREAD

**Issue by sitch** [DestinyItemManager/DIM#9019]
### Proposed change

Display some sort of icon or percentile for the rarity of a given perk combination for weapon type, frame, and element.

So if there is a rare perk combination (say `disruption break` + `adaptive munitions`) that's available on only one gun of a given weapon type out of `N` possible non-sunset weapons of that weapon types, it would show that `1/N` score.

It may also be useful to highlight even single rare perks (desperado when it was only available on the messenger.

### How does this fit into your workflow?

This is useful for identifying guns with perk combo's that may not be "god-rolls" but are extremely rare perk combos (demo + wellspring for example).

**Comment by sitch** [comment]
Sidenote: this could be implemented without touching the UI at all by just computing the permutation counts and generating a wishlist for all items that meet some `min-rarity` cutoff

**Comment by bhollis** [comment]
I love this but it'd be pretty tricky. Maybe a Triage feature, but doing it as a wishlist first would be great.
