### ISSUE TITLE
Saved searches should be searchable by their name

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#9026]
The intention of saved searches / search history is that they come up when you start typing some part of them. I don't know if that works for named save searches searching by name though - we should check.

**Comment by robojumper** [comment]
![grafik](https://user-images.githubusercontent.com/14299449/214435005-7df794bb-2cdc-4525-b1d1-3a656b4de9a4.png)

https://github.com/DestinyItemManager/DIM/blob/654f2f91f780f8052a313f12184fd2bdd4e8c264/src/app/search/autocomplete.ts#L176-L193

Internally the comment is just stored as a normal part of the saved query and filtering will easily match that part. Though suggestion-based autocompletions seem to have a higher priority.

**Comment by bhollis** [comment]
Sounds good. I'm not sure why folks seem to be having such trouble finding their saved searches then.
