### ISSUE TITLE
Refresh button error message went away

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#9027]
Servers are still down but now I see this:
<img width="352" alt="image" src="https://user-images.githubusercontent.com/313208/214412467-af98cea1-dd40-42dd-8c0d-3591a7708487.png">

We must clear the error in some place where we shouldn't.

**Comment by robojumper** [comment]
Even when the game is down, sometimes Bungie.net simply pretends everything is dandy and the GetProfile API call succeeds with cached profiles for quite some time.

**Comment by bhollis** [comment]
Oh, that's cute
