### ISSUE TITLE
Search bar drop down menu

### ISSUE THREAD

**Issue by rocknrollrosie** [DestinyItemManager/DIM#9036]
### DIM Version

Both

### Browser Details

Chrome/firefox/brave

### OS Details

Windows10

### Describe the bug

The drop down menu from the 3 dots om the search is not function for me what so ever on any version of Dim I try

**Comment by bhollis** [comment]
It doesn't open? The actions don't work? What doesn't work about it? How are you triggering it, by clicking? Do you have a search active? Can you show a screenshot?

**Comment by rocknrollrosie** [comment]
https://imgur.com/a/Jm5LoA1 I am unable to click on anything in this dropdown menu

**Comment by bhollis** [comment]
See how the items are greyed out? That's because they don't do anything without a search active.
