### ISSUE TITLE
Restrict Items in Vendor Columns

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#904]
Would it be helpful to have a toggle that lets you restrict vendor items by the column class so we can avoid the issue with items repeating?

![screen shot 2016-09-13 at 9 12 05 am](https://cloud.githubusercontent.com/assets/984608/18477273/addaefd4-7992-11e6-869d-6647510f8e82.png)

**Comment by delphiactual** [comment]
Another way to do what @SunburnedGoose said would be to do away with the columns all together and return data like this. It would remove all the duplicated items from the screen entirely, but moves away from the column paradigm.

![screenshot 2016-09-13 11 37 36](https://cloud.githubusercontent.com/assets/4798491/18485036/4d846fd2-79a8-11e6-99da-79c983b10b2a.png)

**Comment by ericnelson0** [comment]
So much empty space though...

**Comment by delphiactual** [comment]
Well we could go to 4 columns instead Unrestricted / Hunter/ Warlock / Titan

**Comment by SunburnedGoose** [comment]
Group them into 3x3 blocks like we do items?

**Comment by kyleshay** [comment]
![screen shot 2016-09-13 at 1 54 36 pm](https://cloud.githubusercontent.com/assets/424158/18485158/accaf252-79b9-11e6-9d33-15e98b56742d.png)

Or move all weapons to another tab?

**Comment by kyleshay** [comment]
![screen shot 2016-09-13 at 1 57 47 pm](https://cloud.githubusercontent.com/assets/424158/18485263/2e1dc3fc-79ba-11e6-8229-d8b2b82a9d7f.png)
->
![screen shot 2016-09-13 at 1 58 29 pm](https://cloud.githubusercontent.com/assets/424158/18485264/2e26779a-79ba-11e6-87c2-982e2c9ad226.png)

**Comment by ericnelson0** [comment]
I think it's important to decide what we want this screen to do.

Do we want to show all available vendor items regardless of character or that character's ability to actually go and purchase the item?

Or, do we want to show per character vendor data that shows what items can be purchased given that character's progression?

If the second option is the answer then I think it will be hard to handle the redundancy in the data.

**Comment by delphiactual** [comment]
I think collections could be moved to it own separate tab. Since collections are per account the redundancy is overwhelming... And then in the collection view it would highlight `uncollected items` that are currently for sale by vendors...

**Comment by bhollis** [comment]
The collections pages doesn't quite show what you want to see, also - collected items don't need to be in your inventory, they just need to be unlocked, then you can get them anytime you want. If we're going to show collections, that's what we should show.
