### ISSUE TITLE
Refresh Data Not Refreshing

### ISSUE THREAD

**Issue by TheGameV30** [DestinyItemManager/DIM#9041]
Been noticing this a lot over the last couple weeks where you hit R or the Refresh Destiny Data icon in upper right but it doesn't do anything. Most of the time it doesn't even rotate. Then need to go to the hamburger icon & select Reload App - sometimes multiple times to get the app to refresh. Makes clearing out vault space take a bit longer than it used to. Not sure if this is on Bungie's end or the app's end but just what I've noticed recently compared to in the past. Thank you.

**Comment by robojumper** [comment]
Hover over the refresh icon for more info -- Bungie.net heavily caches its responses and started caching some more recently, so there's no way for us to get more up-to-date info than what Bungie.net sends.

>  select Reload App - sometimes multiple times to get the app to refresh

Reloading DIM entirely will do nothing to work around this caching; at some point the cache will go stale and Bungie will send new info, and this will happen whether you reload the app or not.

The refresh icon tooltip will tell you by how much DIM's view is out of date. 1-2 minutes are reasonable even when the game servers aren't under load.

**Comment by TheGameV30** [comment]
Sounds good! Thanks!
