### ISSUE TITLE
Pattern Progress - Add to Progress Tab

### ISSUE THREAD

**Issue by aioooli** [DestinyItemManager/DIM#9044]
### Proposed change

It'd be great to have a section in the progress tab dedicated to showing a large overview of all your **craftable weapon's pattern progress** along with completed patterns and sources filtering to easily see where a weapon pattern is acquired.

A good reference of this feature would be what engram.blue has done on their site https://engram.blue/crafting

### How does this fit into your workflow?

The current option of checking pattern progress in DIM requires the user to open records then click through the different weapon types patterns which can be quite cumbersome and doesn't quite paint enough of a picture.

**Comment by bhollis** [comment]
Personally I just use engram.blue
