### ISSUE TITLE
Can't scroll horizontal on item comparison

### ISSUE THREAD

**Issue by rkelbel** [DestinyItemManager/DIM#9048]
After I updated to the most recent build, I can no longer scroll right to see more items in the item comparison overlay in mobile. It just stays static so if I have more than two of any item I can't scroll to look at them. All other horizontal scroll features still seem to work, swiping between characters and vault all work, but the overlay for items does not.

Phone: Samsung S21 Ultra
Software: Android 13

![Screenshot_20230202_094351_Chrome](https://user-images.githubusercontent.com/9355698/216356682-1f5b5530-292c-440e-a339-f9551179fb0b.jpg)

**Comment by NoCodeLeftBehind** [comment]
Same on DIM beta in Chrome (multiple versions tested) on Android 13. This just started happening very recently, and the release (non-beta) DIM does not have this bug. I wonder if it is related to Issue #8949.

**Comment by robojumper** [comment]
If prod doesn't have this bug, then #8961 could be the cause. Related: #9042.

**Comment by ryan-rushton** [comment]
Yeah I think there are some issues with how horizontal scrolling is working on all mobile devices. In that PR is made a change so the pointer capturing would only happen on iOS devices. I would wager that needs to be all mobile devices.
