### ISSUE TITLE
Sort Records by Completion %

### ISSUE THREAD

**Issue by lowPolySkeleton** [DestinyItemManager/DIM#9056]
### Proposed change

I was working through crafting progress and could see the benefit of allowing a sort option for completion progress. 

originally from discord here: https://discord.com/channels/316217202766512130/1071125626288881765

### How does this fit into your workflow?

Deepsight Scenario: Ability to quickly see which items are closest to unlocking patterns

Triumphs: Allows for easy determination of quickest triumphs to progress.

**Comment by SpartanLight** [comment]
I am a computer science student and guardian trying to contribute to open sources projects. Would it be possible to be assigned to this issues ? I am going to start understanding how to project is built and what I should to do add this feature but however if you can give me extra information on this project I will be glad to hear it.

**Comment by bhollis** [comment]
Go for it. Start with the contributor guide!

**Comment by grSalonga** [comment]
I have code that will sort all of the triumphs and collectables on the records page, I just 1 issue. 
The way I sort the records is I look at the objectives and take the average of the completion rate for the objectives. This leads to cases like this where it appears that something that has no progress is ahead of something with progress.  I want to know if there is a proper way to check if a record is a catalyst. I can check if the record is a catalyst with its `parentNodeHash`  but I would have to hardcode the check with the hash number. 
![Capture4](https://github.com/DestinyItemManager/DIM/assets/99226958/838b7d9e-b0b8-4afc-9eb3-32a2d21960a5)

Other than that everything seems to sort correctly, I can only check with the records on my account though.
