### ISSUE TITLE
Add the name of the deprecated mod that is no longer functioning

### ISSUE THREAD

**Issue by liminalAce** [DestinyItemManager/DIM#9057]
### Proposed change

Add the name of the deprecated mod that is no longer longer functioning so you know what it was and can replace it with another or if the build won't work anymore delete the build.

originally from discord here: https://discord.com/channels/316217202766512130/1072169719047667802

### How does this fit into your workflow?

Helps to see what was there so it can be approximately rebuilt or adjusted with existing mods.

**Comment by bhollis** [comment]
To do this we'll need to use diffs of historical copies of the manifest and generate a persistent database of old mod names. I'm sure someone has archives of old manifests somewhere.
