### ISSUE TITLE
keyboard shortcuts to switch between Overview and Triage tabs

### ISSUE THREAD

**Issue by lowPolySkeleton** [DestinyItemManager/DIM#9058]
### Proposed change

Add keyboard shortcuts to switch between Overview and Triage tabs on item inspection.

originally on discord here: https://discord.com/channels/316217202766512130/1068539327296057364

### How does this fit into your workflow?

 Less mouse moving. The location (height) of the tabs change depending on how much info is on the triage tab.

**Comment by nev-r** [comment]
left and right keys used to do this when it was run by a slider dealy
