### ISSUE TITLE
Filter pill sorting and display for loadouts. 

### ISSUE THREAD

**Issue by liminalAce** [DestinyItemManager/DIM#9059]
### Proposed change

removing the # from the filter pills to save space and clean up the look. allow sorting of the pills in some useful way. 

original on discord here: https://discord.com/channels/316217202766512130/1068130995217383434

### How does this fit into your workflow?

 Sorting by symbols might be interesting. I wonder if they should be sorted by how many loadouts have that hashtag…removing the # from the filter pills as it's not too useful.

**Comment by bhollis** [comment]
We removed the #. Not sure about any sorting beyond what we have.
