### ISSUE TITLE
Download CSV Problems

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#906]
https://www.reddit.com/r/DestinyItemManager/comments/52o7aq/download_weapon_data_missing_aa_since_310/

AimAssist is showing as 0 since update.

Also ornament names are showing twice.

**Comment by bhollis** [comment]
Aim Assist is fixed in #906.

Amazingly, the ornament node is actually *present* twice in the talent grid. There are two almost identical nodes, at the same position, that differ only by their description (
"Adorn your weapons with elaborate new designs." vs. "Applies an Ornament to this weapon.")
