### ISSUE TITLE
Leviathan's Breath not showing up as having a catalyst

### ISSUE THREAD

**Issue by treadingwell** [DestinyItemManager/DIM#9060]
### DIM Version

Version 7.55.0.1002256 (beta), built on 2/5/2023, 7:21:42 PM

### Browser Details

Chrome 109.0.0.0

### OS Details

Windows 10

### Describe the bug

When running `catalyst:incomplete`, my Leviathin's Breath was greyed out.  I noticed then that it doesn't show as having a catalyst slot

**Comment by delphiactual** [comment]
https://github.com/DestinyItemManager/d2-additional-info/pull/452#issuecomment-1456773073

**Comment by delphiactual** [comment]
it is under characterRecords....

```
					"3740374319": {
						"state": 67,
						"objectives": [
							{
								"objectiveHash": 1149582218,
								"progress": 2361,
								"completionValue": 1500,
								"complete": true,
								"visible": true
							}
						],
						"intervalsRedeemedCount": 0
					},
```
