### ISSUE TITLE
ER: Add some way to put all loadout items back into the vault

### ISSUE THREAD

**Issue by sndgeek** [DestinyItemManager/DIM#9061]
I use a fair number of loadouts so my active character almost always has all 10 slots filled for everything.  When you apply a loadout, DIM will obviously pull whatever is needed out of the vault or from other characters but it'd be handy to be able to do the reverse -- take everything in a particular loadout and make sure they are all in the vault.

Definitely a nice to have kind of thing instead of a real issue.

**Comment by robojumper** [comment]
Try clicking your vault emblem -- the resulting dropdown should list all your classes' loadouts and clicking one of them should transfer this loadout's items to the vault.

**Comment by sndgeek** [comment]
D’oh!  I should’ve realized it worked there too.  Thanks!
