### ISSUE TITLE
Bulk Action "Set Note" prompt does not appear in Vivaldi PWA

### ISSUE THREAD

**Issue by ChadGarion25** [DestinyItemManager/DIM#9062]
### DIM Version

Version 7.55.0 (release), built on 2/5/2023, 6:16:56 PM Chrome 108.0.0.0 - Windows 10

### Browser Details

Vivaldi 5.6.2867.62

### OS Details

Windows 11

### Describe the bug

Using the "app" browser version of the DIM interface, when I enter in search parameters then select Bulk Actions (three vertical dots) and click "Set Note", there is no pop-up window to type out the note.
![image](https://user-images.githubusercontent.com/124755871/217429717-a67b49c5-4995-42a3-88fa-1e347c9d8e12.png)

However, when I open it up in Vivladi browser directly (not as an app), it works as intended.
![image](https://user-images.githubusercontent.com/124755871/217430202-329244af-bfca-477e-9307-642784c6c5c5.png)

I'm not sure the exact terminology I should be using for "app", so to elaborate. Vivaldi, in a manner similar to chrome, can install DIM as an app rather than just working directly in the browser. This version that I normally use is the version that cannot generate the Java Popup window.

### Logs

```shell
app] DIM v7.55.0 (release) - Please report any errors to https://www.github.com/DestinyItemManager/DIM/issues
instrument.ts:124 Language Detected: en-us
instrument.ts:124 Language Assigned: en
www.google-analytics.com/analytics.js:1          Failed to load resource: net::ERR_UNSAFE_REDIRECT
instrument.ts:124 [dim sync] globalSettings Object
instrument.ts:124 [d2-stores] Loaded cached profile from IndexedDB
instrument.ts:124 [d2-stores] Cached profile is older than Bungie.net cache time, proceeding. 199991
(anonymous) @ instrument.ts:124
log.ts:58 Load manifest: 3408.940185546875 ms
instrument.ts:124 [d2-stores] Profile from Bungie.net was newer than cached profile, using it. 201074 201074 Tue Feb 07 2023 20:02:04 GMT-0800 (Pacific Standard Time) Tue Feb 07 2023 19:58:43 GMT-0800 (Pacific Standard Time)
log.ts:58 Process inventory: 152.033203125 ms
log.ts:58 Inventory state update: 12.01318359375 ms
instrument.ts:124 [dim sync] Saving profile data to IDB
log.ts:58 prepareUpdateQueue: 0.664794921875 ms
instrument.ts:124 [flushUpdates] Flushing queue of 1 updates
instrument.ts:124 [flushUpdates] got results Array(1) Array(1)
instrument.ts:124 [dim sync] Saving profile data to IDB
```

**Comment by robojumper** [comment]
Vivaldi does not have an open bug tracker, but in their forums this is mentioned as a known Vivaldi issue: https://forum.vivaldi.net/topic/79136/javascript-popup-does-not-appear-in-web-app-why/4

**Comment by bhollis** [comment]
Another case where having our own dialog component would help.

**Comment by esotuvaka** [comment]
Perhaps we could use a modal? I'll see if I can replicate the current dialogue box into a React component and we can adjust the styling later

**Comment by bhollis** [comment]
Yeah that's what I meant about creating our own dialog component. I'd want it to be compatible with the new dialog element for accessibility, but with backwards compatibility and a nice interface that makes it reusable across the codebase.

**Comment by esotuvaka** [comment]
Apologies on the delay, I was out the house this weekend. PR opened with the new modal dialogue component. It's the rough version currently, but I opened it so edits and discussions would be easier. I'll see about integrating the new dialogue element
