### ISSUE TITLE
Shift-clicking a value in the `RPM` column of the Organizer adds a search term that uses `>=` when it should just use `=`

### ISSUE THREAD

**Issue by mturquette** [DestinyItemManager/DIM#9067]
### DIM Version

7.55.0

### Browser Details

Chrome

### OS Details

macOS Ventura 13.1

### Describe the bug

I love using the Organizer to sort through weapons and clean out my vault. It's great!

My workflow is to select a weapon type and then go through each archetype one at a time. However, when I say "archetype" I actually use "stat:rof" because that is a more inclusive way to capture all weapons that roughly compete for vault space.

So far, so good.

The problem is when using my mouse and shift-clicking the RPM value that I want (e.g. clicking `450` in the RPM column when viewing Auto Rifles), the actual search term that gets added to the search bar above is `stat:rof:>=450`, which will also include 600's and 720's. This is defies my expectations as a user and violates the principle of least surprise.

My current workaround is to manually type `stat:rof:450` or the equivalent `stat:rof:=450` into the bar to get the desired behavior; ie 600's and 720's don't show up in the search/filter results.

Can the shift-click behavior be changed to remove the unnecessary `>` greater-than symbol for RoF?

All of the other stats use the same greater-than-or-equal-to behavior and that is fine. Those stats represent a wide spectrum of possible values with huge variation. But RPM equates roughly to Archetype, and I believe that shift-click on that value should filter out all weapons that do not have a *matching* RPM.

Thank you for attending my Ted Talk.

**Comment by esotuvaka** [comment]
I'll take a look and see what I can do. Thanks for bringing this up @mturquette

**Comment by robojumper** [comment]
Fixed by #9079.

**Comment by mturquette** [comment]
(Shaxx Voice) THIS IS AMAZING
