### ISSUE TITLE
Search suggester gives hashtags priority over generated suggestions

### ISSUE THREAD

**Issue by nwLSteam** [DestinyItemManager/DIM#9069]
### DIM Version

Version 7.55.0 (dev), built on 2/11/2023, 2:08:07 AM

### Browser Details

Edge 110.0.1587.41

### OS Details

Windows 10

### Describe the bug

Typing a hashtag after a filter prefix (e.g. typing `inloadout:#`) will no longer respect a possible match from the `suggestionsGenerator` list.

For example, say the generator list looks like `['inloadout:"Loadout Name"', 'inloadout:#loadouthash']`.

* Entering `inloadout:"Lo` would correctly suggest `inloadout:"Loadout Name"` (underlining the entire suggestion).
![Search by Name](https://user-images.githubusercontent.com/25863799/218235190-760336ec-d418-4cbc-bde3-5e163d347996.png)
* Entering `inloadout:#lo` would *incorrectly* restart the search from the hash and suggest `inloadout:inloadout:#loadouthash`.
![Search by Hash](https://user-images.githubusercontent.com/25863799/218235227-d80b2cf2-eaee-4a5f-a927-ae6c5a0dfd33.png)

For the latter case, it is important to understand that the suggester completely ignores the preceding `inloadout:` and treats the input from the `#` as a new search, evident by the underlining.

**Comment by bhollis** [comment]
Is this still happening on Beta? We merged some big changes to how suggestions work, and I can't repro, but I don't have the same loadouts/tags as you.

**Comment by nwLSteam** [comment]
This appears to be fixed. Note also related PR #9501.
