### ISSUE TITLE
Sailspy Pitchglass not visible in Collections

### ISSUE THREAD

**Issue by GosubGosub** [DestinyItemManager/DIM#9078]
### DIM Version

Version 7.56.0.1002261 (beta), built on 13.2.2023, 03:28:51

### Browser Details

Chrome 109.0.0.0 - Windows 10

### OS Details

Windows 11

### Describe the bug

The heavy linear "Sailspy Pitchglass" is not visible in Collections.

Have tested multiple accounts and different versions of DIM / browsers.

**Comment by bhollis** [comment]
Doesn't appear in the D2 companion either, meaning it's a Bungie data bug: https://github.com/Bungie-net/api/issues/1786

**Comment by nev-r** [comment]
it's missing in the game too
![image](https://user-images.githubusercontent.com/68782081/218932199-e1eedf8d-acf2-4a2f-909a-1b29014a86d0.png)
