### ISSUE TITLE
Position and appearance of unavailable perks on weapons

### ISSUE THREAD

**Issue by Prometheus3375** [DestinyItemManager/DIM#9082]
### DIM Version

Version 7.56.0 (release), built on 13.02.2023, 05:24:26

### Browser Details

Chrome 108.0.0.0

### OS Details

Windows 10

### Describe the bug

On the weapons from Dares of Eternity DIM shows enhanced versions of perks that cannot be crafted.

![image](https://user-images.githubusercontent.com/35541026/219208291-d5cb61e3-8137-4892-9c15-92d350d01a5e.png)

On Posterity and Bequest unavailable perks listed within available ones. Some other weapons could be affected too.

![image](https://user-images.githubusercontent.com/35541026/219208680-fe440b8e-0f52-4889-88c5-6a318370db70.png) ![image](https://user-images.githubusercontent.com/35541026/219209119-8f12be7e-c4f3-4391-9a6a-5484205a47f2.png)

**Comment by Prometheus3375** [comment]
Removed perks of Compass Rose are in arbitrary order, but kind of OK, because this weapon is not craftable.

![image](https://user-images.githubusercontent.com/35541026/219238349-a0cab153-984d-46cd-9f85-bb63811e0347.png)

**Comment by bhollis** [comment]
A great format for bug reports is "I did X, and I expected Y, but instead Z happened." Can you explain what you expected?

**Comment by Prometheus3375** [comment]
It is convenient to see perks in the order of unlocking them on crafted weapons. Unavailable perks cannot be unlocked, so I would like to see them at the end of perk columns and I would like *not* to see their enhanced versions at all. Because order matters little on non-craftable weapons, I care little on order of perks on non-craftable weapons like Compass Rose.

Previously, the order of perks on weapons from Dares of Eternity was *absolutely* arbitrary, and presence of enhanced unavailable perks without red background was confusing. When DoE weapons became craftable, I started to think which perks I would like to put on Pardon Our Dust. I saw enhanced version of perk Danger Zone being present and wondered if it increases blind range. Googling told that it does, so I was planning to put its base version. And then I noticed that base version has red background meaning this perk is is unavailable. Some time ago order on DoE weapons got fixed, but unavailable enhanced perks are still does not have red background at least (I would like not to see them at all).

**Comment by Prometheus3375** [comment]
Also consider moving below perks that are visible in collection view, but are not obtainable.
![image](https://user-images.githubusercontent.com/35541026/228369802-a862d5cd-2cde-41b2-8c98-1d1df7b93398.png)

**Comment by bhollis** [comment]
For those "only in the collections view" perks, we don't actually know if they can roll or not. We might need a different color for them.

**Comment by robojumper** [comment]
The number of weapons where those perks can actually roll is in the single digits -- I think only the three Altars weapons and five Last Wish weapons have curated rolls. We could probably highlight those as "curated" and hide them for all other weapons.
