### ISSUE TITLE
Replace d2gunsmith with d2foundry

### ISSUE THREAD

**Issue by gossnj** [DestinyItemManager/DIM#9089]
### Proposed change

D2Gunsmith, while still functional until Lightfall, is no longer maintained. I recommend it be replaced with d2foundry.gg, which has already exceeded the feature set of Gunsmith, is actively maintained, and bears a lot of similarity in terms of ease of use and basic functionality.

### How does this fit into your workflow?

I use Foundry consistently now, but would love to have the convenience of a link out from DIM in place of the Gunsmith one.

**Comment by DMWill** [comment]
Thanks for bringing this to my attention.  I was unaware of D2Foundry and it is actually very impressive compared to D2Gunsmith which I've been using for quite a while.  I would personally be on board if they replaced Gunsmith with Foundry.  Good call.

**Comment by bhollis** [comment]
Out of curiosity what does D2Foundry have that DIM doesn't?

**Comment by gossnj** [comment]
> Out of curiosity what does D2Foundry have that DIM doesn't?

For me personally, exploration of weapons or crafted rolls that I don't have, and a better comparison tool for those hypotheticals. Also, the range/falloff calculation and link to a specific roll/screenshot feature.

**Comment by bhollis** [comment]
So we could add the range calculation and the comparison, since we have the others

**Comment by gossnj** [comment]
I'm not sure I agree that DIM captures the exploration and comparison of hypothetical rolls in a particularly friendly UX, but from a pure information perspective, yes - range info is what's missing. I basically go to Foundry (and Gunsmith before it) to look for what I want from a gun very specifically. A recent example was comparing 3 different rolls I was considering of crafted Disparity side-by-side, which I'm not sure how you'd do with DIM. With the Gunsmith / proposed Foundry link, it's just a quick jump off point from my current roll, which I have missed occasionally since switching to Foundry, thus the suggestion.
