### ISSUE TITLE
Feature Request - Swapping all weapons between two characters.

### ISSUE THREAD

**Issue by ron77** [DestinyItemManager/DIM#91]
I would like to be able to swap all weapons between 2 characters.  This would make changing characters extremely simple.  I usually use the same weapons with just a few changes depending on the situation.  If I am doing daily stuff and get done with one character, I just need to swap weapons with my next character.

Another feature that would be a similar idea would be loading weapons from a loadout to a character and automatically moving the current weapons for that character to the other characters.  This would give you exactly the weapons you want.

Both of these methods would allow a person to have exactly the weapons they want and nothing extra.

**Comment by Senaxx** [comment]
This is already possible with the loadouts? I've put all the weapons I use in a loadout for any character and can switch on the fly :)

**Comment by ron77** [comment]
I am talking about switching all the weapons so that the 2nd character has the same exact weapons that the 1st character has.  You currently can't do that.  You may be able to do something that is close but not completely.  You will still have stray weapons left over on the character you are switching to.  Even if you only have 1 primary/special/heavy on the character you switch to, you will still have those 3 weapons left in those characters, unless you are switching 10 weapons over from that category, then I think it will move the 1 weapon somewhere else.

**Comment by spkane86** [comment]
I second this request, but not just for weapons. It would be nice to have a one-button-press to move all of the materials and consumables between characters too.

**Comment by bradchoate** [comment]
Oh this would be so very awesome. You find a great set of working weapons for a given Nightfall, then you want to use the same set as you cycle through your characters. Switching them from alt to alt manually is a pain. I'd love for an option to move all weapons from one character to another, plain and simple.

Secondarily, it would be great if there was an easy method to create a loadout from all the currently equipped weapons for a given character. That could satisfy the need here, but I'd rather not create/delete a loadout everytime I want to swap all weapons.

**Comment by SunburnedGoose** [comment]
Some good ideas here.  Just need the bandwidth.

**Comment by kyleshay** [comment]
i'm tempted to close this. nowadays this would be a bit more simple to implement with how we handle bulk transfers (like 'items to level up', etc.)

but, is this sort of thing still necessary? if i'm doing the raid on 3x characters, it's easy enough just move over my spindle, hung jury, and ToM...

**Comment by SunburnedGoose** [comment]
It would be nice if there was an easy UI that would just swap characters (armor/weapons/ship/sparrow/emblem/shader).  Loadouts don't help because the gear matches the scenario and you're just character swapping to repeat.

Essentially what we're doing is making two temporary loadouts, swapping items, and deleting the loadouts.  Simple aside from the UI issue.

**Comment by ron77** [comment]
The only reason it wouldn't be as necessary any more is that nobody does NFs any more.  But that could change in the future.  I still think being able to easily switch all weapons with a couple clicks  is a great feature.  Especially since it can be done quicker now.

**Comment by SunburnedGoose** [comment]
Just add a swap character load out and two links to the characters. Move
the equipped items.

**Comment by ron77** [comment]
Not sure what you mean.

**Comment by bradchoate** [comment]
I disagree that no one does nightfalls anymore. And a specific loadout that works for a specific set of modifiers is also relevant and would be useful for the weekly challenge of elders.

**Comment by bhollis** [comment]
You can easily create a load out form one character's equipped items and
apply it elsewhere. No need for a dedicated feature.

**Comment by ron77** [comment]
Everyone always seems to miss the point.  The whole point of this feature is to be able to get the exact weapons you want and NO more with a simple click.  I was doing Iron Banner this week and I could switch items but I could not do it that easy.  To do something similar, you have to get all weapons off the other 2 characters except what is eqipped.  Make a loadout for those 3 weapons for each character.  Then, before moving weapons from that character, equip those 3 weapons with that loadout before moving the main loadout to the other character.  Then the character that has all the weapons, move that character's 3 weapon loadout to the vault.  That works but it is a bit of a pain.

I was equipping at least 7 primary weapons during IB and with 1 Armsday choice, I needed to move excess weapons out.  Having the ability to just switch weapons exactly between 2 characters would still be usefull.

**Comment by kyleshay** [comment]
Once we have https://github.com/DestinyItemManager/DIM/issues/224

You'll be able to create an account global (can equip on any character) loadout for your favorite weapons and have empty slots. 

Should be as simple as "create loadout" -> "click 3 weapons" -> "set blank slots option to true" -> "set to apply to any class"

Then when you have that loadout, you'll be able to equip it on any character and have those free spaces.
