### ISSUE TITLE
Include artifice armor in is:statlower

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#9101]
Since artifice armor will be +3 in one choose-able stat, we should mark any other item as lower stats if it could be beaten by a configuration of an artifice piece.

**Comment by robojumper** [comment]
Triage has some code for identifying these pieces:

https://github.com/DestinyItemManager/DIM/blob/ff621a5cde00ed7621da032ed8f4e2dfc227ea1c/src/app/item-triage/triage-utils.tsx#L294-L362

but it'd be an `O(n^2)` algorithm when implementing a filter on top of it.
