### ISSUE TITLE
Lightfall Loadouts

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#9103]
* [x] Publish new `bungie-api-ts`
* [x] Selector for pulling loadouts out of profile response
* [x] Selector for which loadouts are/is equipped (all mods and items match intended)
* [x] Selector/helper for determining which loadouts are equippable (on char, or in vault and space enough to move)
* [x] Show ingame loadouts on Loadouts page
* [x] Show ingame loadouts on Loadouts dropdown
* [x] Make `is:inloadout` work with ingame loadouts
* [x] Make `inloadout:${name}` autocomplete
* [x] Make ingame loadouts show up in Organizer
* [x] Make ingame loadouts show up in Triage
* [x] Button to equip ingame loadout
* [x] When equipping loadout, move items off other characters and make room
* [x] Button to snapshot currently equipped as an ingame loadout (requires a dialog/control for selecting slot)
* [x] Edit name/emblem/color for ingame loadouts from Loadouts page
* [ ] #9469
* [x] Button to save ingame loadout as a DIM loadout
* [x] Button to share ingame loadout as a DIM loadout
* [x] Show plugged sockets in loadout view
* [x] Figure out what happens when an item in a loadout is dismantled
* [x] Update the screen after a loadout is deleted

Feel free to use the button to break any of these out into their own issue and assign to yourself, or add to the list.

**Comment by bhollis** [comment]
In-progress support branch here: https://github.com/DestinyItemManager/DIM/pull/9112

**Comment by aescolastico** [comment]
Are there any plans to make ingame loadout pseudo shareable using dim loadouts as a proxy? or will the workflow simply be:
1. Copy In game loadout as DIM loadout.
2. Share newly copied loadout.
