### ISSUE TITLE
Bungie error 1622 Dim not working

### ISSUE THREAD

**Issue by SpIxshy** [DestinyItemManager/DIM#9105]
### DIM Version

Version 7.57.0.1002293 (beta), built on 2/23/2023, 7:02:10 PM

### Browser Details

chrome

### OS Details

Windows 10

### Describe the bug

Very recently i realized that my newly obtained gear isn't showing up in dim, then i realized dim is completly down for me, the refresh is not working and it says error code 1622, i tried everything including uninstalling and reinstalling but nothing worked.
please help

### Logs

```shell
DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for chrome-extension://fheoggkfdfchfphceeifdbepaooicaho/sourceMap/scripts/iframe_form_check.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://fheoggkfdfchfphceeifdbepaooicaho/sourceMap/scripts/iframe_form_detection.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
```

**Comment by robojumper** [comment]
https://twitter.com/BungieHelp/status/1629176785320529922

> We are investigating an issue where API functionality on web, mobile, and 3rd-party apps is down for some players. This includes viewing characters and loadouts, and making changes to or creating new Cross Save setups.
