### ISSUE TITLE
Some ghosts lost stats

### ISSUE THREAD

**Issue by shockthealien** [DestinyItemManager/DIM#912]
Not sure if been reported yet but some of my ghosts, interestingly only trials and IB ones, have lost the stat bars and therefore quality stats

![screen shot 2016-09-14 at 13 31 23](https://cloud.githubusercontent.com/assets/2083273/18512185/c2e781ba-7a7f-11e6-847b-803db9d6627d.png)

**Comment by wein3967** [comment]
Yep, this a known issue. Something with the Bungie API, I believe. #889
