### ISSUE TITLE
Missing legendaries in Loadout builder

### ISSUE THREAD

**Issue by struthersdan** [DestinyItemManager/DIM#913]
This is fairly ironic, but the loadout builder cannot see my blindsight boots. 
![blindsight](https://cloud.githubusercontent.com/assets/646587/18515972/de03c314-7a5c-11e6-84bf-3360076d3eea.PNG)

**Comment by wein3967** [comment]
This is probably related to the whole IB and ToO ghost issue as well. I saw this on my Blindsight boots as well. Basically, it seems to be on Bungie's end. #889

**Comment by ericnelson0** [comment]
Yeah, wein is right. Some items aren't returning any stats and so they're being ignored for now.
