### ISSUE TITLE
DIM beta lost settings

### ISSUE THREAD

**Issue by thomaskchan** [DestinyItemManager/DIM#9133]
[Version 7.58.0.1002308 (beta), built on 2/28/2023, 1:08:02 AM]

When I opened up DIM beta today, I noticed it looked different.  The icon item size was no longer at the lowest, my characters were in a weird order, and my loadouts seem to be missing.

Is this expected behavior with the lightfall changes?  I could understand loadouts being gone due to the armor changes and in-game loadouts, but it’s weird that the other settings also got reset.

**Comment by bhollis** [comment]
Not expected behavior, and loadouts should not be gone.

**Comment by bhollis** [comment]
Did you see any warning that DIM Sync couldn't be contacted? Do you have DIM Sync on?

**Comment by thomaskchan** [comment]
No DIM sync error message, and DIM sync is on.

Normal non-beta DIM does show the loadouts.

**Comment by thomaskchan** [comment]
Additionally, I had made a DIM settings export a few days ago, and loading it in beta DIM does not restore the settings or loadouts.

**Comment by bhollis** [comment]
You'll have to open up the developer console and show us what's in there then.

**Comment by thomaskchan** [comment]
[Version 7.58.0.1002309 (beta), built on 2/28/2023, 11:32:54 AM]

Looks like DIM just got updated, and the latest version now has my loadouts back!

**Comment by bhollis** [comment]
Great!
