### ISSUE TITLE
Allow adding notes to lightfall in-game loadouts

### ISSUE THREAD

**Issue by thomaskchan** [DestinyItemManager/DIM#9150]
### Proposed change

Thanks for adding in-game loadouts so quickly.

It would be awesome if we could put notes into the in-game loadouts, as things like “SOLAR” or “ALPHA” are so generic.  Having the note next to the in game name would be helpful when applying loadouts.

### How does this fit into your workflow?

This would be helpful so we could more easily remember what the purpose of the in-game loadout is.

**Comment by bhollis** [comment]
Maybe. There's nothing about the ingame loadouts that is backed/associated with data in DIM Sync, so we'd have to add something new.

**Comment by Gix3612** [comment]
If you do end up adding more DIM features around the in-game loadouts, a toggle for `Don't Change Weapons` that automatically reverts to your previous weapons after it equips the in-game loadout would also be nice alongside the notes.
