### ISSUE TITLE
is:statlower with Artifice showing incorrect results

### ISSUE THREAD

**Issue by marheine** [DestinyItemManager/DIM#9152]
### DIM Version

Version 7.58.0.1002323 (beta), built on 3/1/2023, 7:53:53 PM

### Browser Details

Chrome 110.0.5481.178 (Official Build) (64-bit)

### OS Details

Windows 10

### Describe the bug

I was checking my armor for `is:statlower` now that it considers Artifice pieces with their Lightfall stat bonus, and came across a pair that I don't think is being handled properly:
![image](https://user-images.githubusercontent.com/9285468/222356730-6e4a8f12-571f-460a-8f9e-2bf6e07fff1b.png)
I expect the _Eidolon Pursuant Gauntlets_ (EPG) to be lit up by this search, as the _Deep Explorer Gauntlets_ (DEG) could tie in all stats by applying the Artifice +3 to Resilience.
The Triage screen for this pair of items does correctly identify them with _Better Stat Artifice Armor_ on EPG, and with _Worse Stat Non-Artifice Armor_ on DEG.

I also think I found a bug in triage-utils.tsx: If line 338's if statement is satisfied, it'll expend the artifice token regardless of merit. Imagine two armor pieces:
`A: 10/10/10/10/10/10` Artifice, and
`B: 14/11/10/10/10/10` regular. The first check (Mobility?) would use the Artifice +3, and yet still lose 14-13. The second check (Resilience?) would then be forced to lose 11-10. The other 4 checks would tie, resulting in an incorrect win for B.
I believe including a check if the extra 3 points will matter would correct this behavior. Namely, changing that line to
`if (valueB > valueA && aArtificeToken && valueB <= valueA + 3) {`

**Comment by robojumper** [comment]
* `is:statlower` only checks for strictly better/worse, doesn't identify ties right now. Unsure if this can be changed with the trie implementation
* the Triage bug is being fixed in #9132, but thanks for reporting it

**Comment by bhollis** [comment]
I suppose the suggestion would be to change the logic from "a strictly better stat set exists for every configuration" to "at least one strictly better stat set exists, and all other configurations are equal or better"? I think I can make that change.

**Comment by robojumper** [comment]
Well, in this case there is no strictly better stat set, it's more that an artifice piece can be configured for a tie in all stats, but also have other configurations (that are better in some stats and worse in others).

**Comment by marheine** [comment]
Making this change would also cause all non-Artifice class items be flagged. Is this a concern?

It seems like the most complex part of making a change to this logic would be identifying cases where an artifice piece is beaten by a combination of other gear, up to 6 pieces (one per potential +3 slot).
