### ISSUE TITLE
Mod stacking rules are not shown

### ISSUE THREAD

**Issue by robojumper** [DestinyItemManager/DIM#9154]
The new mods very clearly show their stacking behavior in-game:

![grafik](https://user-images.githubusercontent.com/14299449/222448912-68cf3bb0-5ade-41c7-a27b-39c0656efd6c.png)
![grafik](https://user-images.githubusercontent.com/14299449/222448930-c71ce52b-ecba-4f0e-8e2b-224557e3bd01.png)

but this is missing from DIM's Mod Picker (and all tooltips):

![grafik](https://user-images.githubusercontent.com/14299449/222449188-ec4beddb-4080-4ab6-9245-52e9e2b6f593.png)

**Comment by aescolastico** [comment]
I would say this is a feature request, not a bug.

**Comment by bhollis** [comment]
Linking #9076
