### ISSUE TITLE
Fix punctuation consistency in CONTRIBUTING.md

### ISSUE THREAD

**Issue by redcowe** [DestinyItemManager/DIM#9156]
It appears there are a few issues with the punctuation in the CONTRIBUTING.md

**Comment by bhollis** [comment]
Could you help us by explaining what those issues are?

**Comment by redcowe** [comment]
Sure! I apologize I'm new to open source.

I just noticed a few things there were off at places like:
https://github.com/DestinyItemManager/DIM/blob/8550c679e9d8c693bf520ff70eeadd3288be8f88/docs/CONTRIBUTING.md?plain=1#L7
https://github.com/DestinyItemManager/DIM/blob/8550c679e9d8c693bf520ff70eeadd3288be8f88/docs/CONTRIBUTING.md?plain=1#L23

Just some simple fixes that caught my eye when I was reading through.

**Comment by bhollis** [comment]
Can you help by pointing out what you'd change?

**Comment by redcowe** [comment]
I have a [branch ](https://github.com/redcowe/DIM/blob/fix-punctuation-consistency-in-contributingmd/docs/CONTRIBUTING.md)open in the forked repo with the changes I have proposed. Should I open a PR for an official review?

**Comment by bhollis** [comment]
Oh yes, that would be the best way.
