### ISSUE TITLE
Include artifact mod selections in loadouts?

### ISSUE THREAD

**Issue by ccsantos23** [DestinyItemManager/DIM#9163]
### Proposed change

Is it possible to include artifact mod selections per loadout?  Because:
- can only have 12 mods active at a time
- the discount mods affect how much energy will remain on the armor
- some mods are class-specific
- some mods are activity-specific (say, some ammo mods or overcharge mods)
- resets are free (though I could have sworn my first reset cost glimmer)

### How does this fit into your workflow?

This way each loadout could remember which discount mods worked with the energy used per armor piece.  Having class-specific and activity-specific selections would make switching loadouts simpler too.

p.s. Thank you sooo much for creating this tool.  I don't think I could play D2 without it.

**Comment by bhollis** [comment]
No, it's not. We do not get APIs for resetting the artifact, or unlocking mods in it. Maybe someday.
