### ISSUE TITLE
Make "powerful items on other characters" warning reactive

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#9168]
That is, drive it off a selector so it can be up to date as you move items

**Comment by robojumper** [comment]
I wonder if it'd make sense for the actual values to still be in the DimStore object or if they should also go into the selector.

**Comment by bhollis** [comment]
I've long wanted them to be removed and calculated. It turns out to be tricky to disentangle - I have a half completed branch. Ideally a lot of the stuff in DimStore could be separated out. There used to be issues with classified items not having power level but that's no longer the case.
