### ISSUE TITLE
Weekly Crucible Competitive challenge is actually a Power +4 reward

### ISSUE THREAD

**Issue by Prometheus3375** [DestinyItemManager/DIM#9169]
### Proposed change

Currently, Weekly Crucible Competitive challenge classified as "Other Rewards". Doing this challenge gives Rose with `max power + 4` if under pinnacle cap and +0 if above or at. Thus, it can be classified as Power +4 reward.

Although I need to double check how much above max power it gives. AFAIK, my max power was 1787 before obtaining Rose and then I got it with level 1791.

### How does this fit into your workflow?

Good to know such information when increasing power level. Especially useful above pinnacle cap in cases when you need something in the first weapon slot to increase max power.

**Comment by robojumper** [comment]
All our engram power needs double checking -- there are also reports that the previous +1 playlist pinnacles are now +2. But what about Hawthornes?

**Comment by Prometheus3375** [comment]
> there are also reports that the previous +1 playlist pinnacles are now +2

This is likely to be true. I was 1797 doing compet, after 3 matches got Rose 1800 and heavy GL 1802.

**Comment by Prometheus3375** [comment]
Vanguard Ops Playlist -- Pinnacle +2
Gambit -- Pinnacle +2
Crucible -- Pinnacle +2
Hawthorne weekly reward -- Pinnacle +2
Hawthorne clan engrams -- should be unchanged (game claims powerful level 2 which means powerful +4, but honestly they felt like +3).
