### ISSUE TITLE
Users accidentally collapsing types and categories

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#917]
I'm getting several complaints about missing types/categories from users.  

https://twitter.com/Amysnice/status/776115757918806016

What I believe is happening is that they are accidentally clicking on the bar for the category which collapses all the weapons for example.  We should change that to just be a + sign, or maybe the text of the category.

**Comment by delphiactual** [comment]
I'm pretty sure this is how it happens, I've done it a few times...

![collapse](https://cloud.githubusercontent.com/assets/4798491/18524054/15cc3ee0-7a74-11e6-9733-645415e1ef04.gif)

**Comment by wein3967** [comment]
@delphiactual @SunburnedGoose , yep that is how it happens. I do that a fair amount ... and it is annoying. I just figured I needed to train myself to be more careful where I click off stuff.

**Comment by chuckreynolds** [comment]
Just make the + / - icon (or the icon and the section name) clickable and make minimized tabs a slightly different color to separate visually.
