### ISSUE TITLE
Artifact Mods as part of Load Out?

### ISSUE THREAD

**Issue by nathan-dotwork** [DestinyItemManager/DIM#9175]
### Proposed change

With the new artifact mods changes, things that were previously part of a build as an armor mod are now part of the build as artifact unlocks. Is it possible to add the configuration of the artifact mods to the saved build load outs and have them applied when switching?

### How does this fit into your workflow?

If I want to build an 'overload bow, barrier pulse rifle' build, I now have to slot those artifacts rather than armor mods. The above change would allow me to do this (this is the simplest example, but it carries to all the artifact mods)

**Comment by delphiactual** [comment]
no allowed via the api
