### ISSUE TITLE
"Harmonic X" mods don't show their effect

### ISSUE THREAD

**Issue by robojumper** [DestinyItemManager/DIM#9179]
The def has one of five perks that activates depending on current subclass; they're all hidden in the defs (https://data.destinysets.com/i/InventoryItem:3832366019)

DIM gives up here:

https://github.com/DestinyItemManager/DIM/blob/f3ed2775110622be6c7865b8d47b2267a5e6bde9/src/app/utils/plug-descriptions.ts#L223-L253

and just says "Arc"

![grafik](https://user-images.githubusercontent.com/14299449/222915901-5617b923-3dec-4544-aa9d-884de578543e.png)

**Comment by robojumper** [comment]
Update: Now that we show the stacking behavior, the condition above doesn't trigger anymore.

![grafik](https://user-images.githubusercontent.com/14299449/228059065-9a867c7e-2bb4-40dd-856a-57c16260166b.png)

Pros: It doesn't say anything incorrect.
Cons: It doesn't say what the mod does.

**Comment by StycDev** [comment]
Hey, I think I have a fix for this I'm just wondering if you would prefer it state along the lines of 

Rapid Harmonic weapon final blows create an Orb of Power.
Note: Harmonic means the element matching your subclass

or state the version that matches the subclass ?

**Comment by robojumper** [comment]
Good question! The game just shows the version matching your current subclass element, but that's difficult to figure out in the place where these descriptions are generated in DIM and I personally find that behavior of the game to be confusing -- and it'd be even more confusing in places in DIM when the user didn't pick a subclass, e.g. Loadout Optimizer's mod picker.

So I'd be fine with something that just uses the pre-Lightfall "weapon final blows with damage matching your subclass type" wording. Of course this needs to be done for all 9 Harmonic mods, which is why I was mostly hoping to maybe think of a better approach.

**Comment by StycDev** [comment]
Hey, thanks for the quick reply currently I have most of the harmonic mods working currently one of them is being a bit of a problem child but here is some examples of what the mods currently look like I would like your opinion of the message for each of these.

![Siphon](https://user-images.githubusercontent.com/98132549/230801369-3aab642c-68e9-44b0-b0b8-3a3fcfe5a2a7.png)
![Targeting](https://user-images.githubusercontent.com/98132549/230801370-892100de-b014-4105-9c47-0d5e1e60ffa3.png)
![damageresist](https://user-images.githubusercontent.com/98132549/230801371-6151fc4f-c0f8-49e6-bdf7-a92ca9c4cfbb.png)
![dexterity](https://user-images.githubusercontent.com/98132549/230801372-8b6ac6ff-067e-4974-af2d-8fd1e643d470.png)
![loader](https://user-images.githubusercontent.com/98132549/230801373-51708cf4-7efd-4b26-9621-397ac528103f.png)
![reserves](https://user-images.githubusercontent.com/98132549/230801374-a2d06bdd-e08f-40c9-93dc-f23cb81e0a8e.png)

**Comment by robojumper** [comment]
I think introducing the Harmonic keyword in descriptions and adding an explicit "Note:" to explain this keyword clashes with the Bungie description styles. Can we just follow the pre-Lightfall descriptions as closely as possible (e.g. Harmonic Siphon: "Rapid weapon final blows with damage matching your subclass type create an Orb of Power")?

**Comment by StycDev** [comment]
Hey after seeing the message you stated I've modified it a bit if you don't mind check below, this is what it states for the harmonic targeting mod. This is what I could think of without essentially needing to explicitly define the description of each of these mods.

![image](https://user-images.githubusercontent.com/98132549/230872366-47e94504-b053-4fd1-a389-af723fc32264.png)

**Comment by robojumper** [comment]
The main concern is that DIM works with all supported Destiny languages, so any sort of clever runtime replacement based on string matching needs have matchers/replacements defined for every language, which is tricky to get right. Explicitly copying the descriptions in the DIM repo would make it easier to translate.

See https://github.com/DestinyItemManager/DIM/blob/master/docs/CONTRIBUTING.md#development for DIM localization.
