### ISSUE TITLE
item roll stats percentage now showing on items < ~300?

### ISSUE THREAD

**Issue by chuckreynolds** [DestinyItemManager/DIM#918]
Is there a reason for this? I assume there's a cutoff light level for yr1 items and for the spektar stuff that drops at lvl 3 but some of this stuff I'd like to know if it's worth leveling up.. thoughts or link to issue i've missed explaining this? thx
![screen shot 2016-09-14 at 15 07 35](https://cloud.githubusercontent.com/assets/46185/18531800/0179f96e-7a8d-11e6-9249-ed9842c8fc59.png)

**Comment by SunburnedGoose** [comment]
Floor is 280 when quality rating is available.
