### ISSUE TITLE
Strand missing in Symbol Picker

### ISSUE THREAD

**Issue by seb-giroux** [DestinyItemManager/DIM#9180]
### DIM Version

Version 7.58.1.1002339 (beta), built on 03/03/2023, 16:30:15

### Browser Details

Chrome 110.0.0.0

### OS Details

Windows 10

### Describe the bug

Strand Symbol, Strand Supers, etc. missing from the picker.
![image](https://user-images.githubusercontent.com/8069361/222916051-4f891080-c700-4298-b43e-dfcb6df139bf.png)

**Comment by robojumper** [comment]
Added by #9186.
