### ISSUE TITLE
Two Tailed Fox catalyst not showing

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#9183]
### DIM Version

current beta

### Browser Details

Chrome

### OS Details

Windows 11

### Describe the bug

Probably an API bug, but the catalyst for Two Tailed Fox does not show in DIM for the catalyst:incomplete filter.

**Comment by robojumper** [comment]
Note: The catalyst is named "Third Tail" (https://data.destinysets.com/i/InventoryItem:2694576561/InventoryItem:4079681314), which makes it difficult for d2ai to associate it with the Two-Tailed Fox catalyst record. cc @delphiactual
