### ISSUE TITLE
Problem dragging itens.

### ISSUE THREAD

**Issue by Travelerslight** [DestinyItemManager/DIM#9187]
### DIM Version

Version 7.58.1.1002343 (beta), built on 05/03/2023 14:43:34

### Browser Details

Opera

### OS Details

Windows 11

### Describe the bug

For some reason I can't grab an iten to drag it to my character. The same happens if I try to drag something from my character to the vault.

**Comment by bhollis** [comment]
This is often caused by your mouse software (Windows ecosystem is wild) e.g. Razer software.
