### ISSUE TITLE
DIM shows The Other Half to have red border

### ISSUE THREAD

**Issue by Prometheus3375** [DestinyItemManager/DIM#9195]
### DIM Version

Version 7.59.0 (release), built on 06.03.2023, 05:27:57

### Browser Details

Chrome 108.0.0.0

### OS Details

Windows 10

### Describe the bug

I have got The Other Half from Dares of Eternity. DIM shows it has red border when it does not have.

![image](https://user-images.githubusercontent.com/35541026/223489844-8f7d7e46-72e2-4d0c-956f-dd4f9e390476.png)
![image](https://user-images.githubusercontent.com/35541026/223489897-f145a3bf-d096-4b7c-871e-1b8418357e58.png)

### Logs

[logs.log](https://github.com/DestinyItemManager/DIM/files/10911943/logs.log)

**Comment by delphiactual** [comment]
fixed in beta https://github.com/DestinyItemManager/DIM/pull/9176
