### ISSUE TITLE
Add tooltip help to LO about how stat priority affects builds

### ISSUE THREAD

**Issue by Prometheus3375** [DestinyItemManager/DIM#9198]
### Proposed change

Currently this is done automatically which is not convenient to me. I would like to switch off automatic adding of such mods. New setting in beta "Automatically add stat mods" does not disable it.

Suggestions:
- Add selection of Artifice Armor mods to "Select mods" menu.
- Make switch for enabling automatic adding of Artifice Armor mods.

### How does this fit into your workflow?

I usually try to maximize base stats of armor (including masterwork) and only then I am adding stat mods.

**Comment by robojumper** [comment]
Artifice mods are free and use an exclusive mod slot, so the reasoning behind always picking artifice mods automatically is that they can be considered part of the armor set's base stats.

An important reason to let Loadout Optimizer pick artifice mods is that LO can optimize for total tier and thus identify/prioritize base T33 or T34 builds. Can you give us more detail about why "set base stats without artifice mods" is something you care about?

**Comment by Prometheus3375** [comment]
Initially I was confused by this feature. I thought that it is a UI bug that shows currently equipped Artifice Armor mod. I equipped loadout and realized that this mod is actually used. Then I thought that DIM uses equipped Artifice Armor mods, but after I tried to replace class item with no mods equipped, I realized that DIM automatically adds Artifice Armor mods. Patch notes are the only place where this behavior is mentioned, so it will be good to make a note inside LO too.

There is also a confusion when showing max possible stat tier. In the screenshot below, max Recovery tier showed as 2.5 while DIM shows 30 Recovery in first loadout because +3 was added with Artifice Armor mod.
![image](https://user-images.githubusercontent.com/35541026/223724634-29419c6b-2c87-431e-a314-3653ed99455d.png)

Here is an example where I think "max base stats without artifice mods" is relevant.
![image](https://user-images.githubusercontent.com/35541026/223725595-eb0c37ec-d37e-4493-a6fb-38bed37328e8.png)
In this armor setup Resilience is 81. This loadout is also can be used with any subclass. When used with Stasis, I will get +20 Resilience from fragments I usually use. But with Strand I will lose 10 Resilience because of Thread of Warding fragment. In such case I would like to compensate loss with 3 Artifice mods for Resilience, but slots for them already in use for Mobility and Recovery. Making 2 different loadouts for Strand and Stasis is too much for me: (a) I may change the opinion about fragments so the loadout will be obsolete and must be updated and (b) I usually create separate loadouts for subclasses except for rare cases; if at some point I consider other super/grenade/melee better, then I will need to update only subclass-loadout rather than updating all loadouts with such subclass. Such approach can be suboptimal for stat tiers, but proposes more flexibility.

**Comment by robojumper** [comment]
> Patch notes are the only place where this behavior is mentioned, so it will be good to make a note inside LO too.

Agreed, a tooltip on the mods seems reasonable.

> There is also a confusion when showing max possible stat tier. In the screenshot below, max Recovery tier showed as 2.5 while DIM shows 30 Recovery in first loadout because +3 was added with Artifice Armor mod.

Will fix.

Regarding your concrete example though, **you are not forced to accept these artifice mods** when saving the loadout. You can always remove them from the loadout and replace them with different artifice mods when saving or editing later. This is really just a means of finding good tiers across all your existing sets.

And really just to reinforce why I think it's important for LO to do this by default: The set you're highlighting seems to be at the top of your generated sets list. I don't see the rest of your LO settings, but it seems it needed artifice mods in two different stats to become a T32 set. If DIM didn't assign these artifice mods, you probably wouldn't even be looking at this set because it would be a T30 set, sorted way down below some other natural T32 or T31 sets (that perhaps aren't even using artifice armor. If LO can't make use of artifice mods, it will also not rate artifice armor any higher). 

(As for your comment regarding the fact that the general mods behind the toggle aren't free -- consider just adding the 9-cost leg armor mods to LO. Again, you're not forced to accept them in the loadout later, but it gives LO an idea about how much energy is remaining and which mods it can choose to automatically slot.)

**Comment by Prometheus3375** [comment]
I honestly did not find any good reason I do not like this feature by default except for feeling uncomfortable and unusual. Like loosing control on something I used to control 😅. I think I will get used to the feature in the future.

---

The only concern I have is how long Artifice Armor will work this way. I have *plenty* good armor in my vault, so at the end of seasons I am usually capped. To make some space, I optimize every loadout to find better stat combinations. Then I make *hard* decisions to which of unused armor to dismantle. Assume now I optimize all loadouts making use of Artifice Armor and dismantle some other good armor pieces to make space. Then there is a patch where Artifice Armor is changed to give other benefits. As a result, I will lose stats on all of my loadouts. But if I create loadout considering only base stats, there will be no issues. But this is not a good reason imho.

> Regarding your concrete example though, you are not forced to accept these artifice mods when saving the loadout. You can always remove them from the loadout and replace them with different artifice mods when saving or editing later.

Sometimes results with no usage of Artifice Armor mods may be buried deep even in a very restricted configuration.
![image](https://user-images.githubusercontent.com/35541026/223803652-c17fdaeb-9a8b-4f6d-bac9-4900789c95af.png)

In this example configuration is tight, but I still got a lot of results. Existing loadout without use of AA mods is on 4th place. In same cases it can be even deeper.

> (As for your comment regarding the fact that the general mods behind the toggle aren't free -- consider just adding the 9-cost leg armor mods to LO. Again, you're not forced to accept them in the loadout later, but it gives LO an idea about how much energy is remaining and which mods it can choose to automatically slot.)

This is actually a good advice, thank you.

---

Some additional comments regarding configuration in my previous comment. All results I got.
![image](https://user-images.githubusercontent.com/35541026/223776362-302b03e9-7a2e-4bbe-a7cd-757fc5e3c7cf.png)

"Existing loadout" was created before the expansion dropped. Without Artifice mods it is T30 as the first one. Others in the list are T30 because of Artifice mods. So if Artifice mods were not added, I might have a look to the first loadout anyways, considering it has more Artifice Armor.

I've just noticed that Recovery stat in it is 31, i. e., without mods it is 25. Strength is 35, so I can use 2 mods to bump Strength instead of Recovery, but there is no such result. I restricted neither Strength nor Recovery.

Looking at the same armor sets with some stats ignored.
![image](https://user-images.githubusercontent.com/35541026/223780263-53cb0142-5519-435e-ae18-7a5ee759ff82.png)
Now existing one is the first, while former "leader" is the second. From such perspective it is clear that second is better than first because it has more artifice armor with empty slots which I can use for either Recovery or Strength depending on situation.

**Comment by robojumper** [comment]
Okay yeah, if you're using LO to look at only a small number of sets -- small enough to fit on a single screen page -- then I agree some more control over LO's behavior could make sense and it could be useful to turn artifice mods off (though LO makes this workflow difficult for other reasons, e.g. it doesn't show exact stat numbers, only rough tiers and you need to hover over stats a lot for exact numbers).

I'd prefer to not add too many options, but maybe we can turn the auto mods slider into a three option radio button (with options being no auto mods, only artifice mods, both artifice + general).

**Comment by Prometheus3375** [comment]
Did mentioned pull request released in beta? I still have an issue I mentioned before.

> I've just noticed that Recovery stat in it is 31, i. e., without mods it is 25. Strength is 35, so I can use 2 mods to bump Strength instead of Recovery, but there is no such result. I restricted neither Strength nor Recovery.

I found better example of this.
![image](https://user-images.githubusercontent.com/35541026/224785710-9586f137-c43c-4c43-8465-edbb8f103b2f.png)
In the very first loadout Mobility w/o Artifice mods is 61, Resilience w/o Artifice mods is 81. There are three slots for AA mods, so can make either 70 Mobility or 90 Resilience. I made 90 Resilience and saved such loadout.

The problem here is that DIM shows correct maximum only for Mobility (T7) while still considers maximum Resilience at T8.

**Comment by robojumper** [comment]
Yeah DIM doesn't investigate all possible assignments for stat mods when calculating the respective stat tier maxes, that'd be too expensive.

**Comment by Prometheus3375** [comment]
Hm, in such case there should be a note about this behavior. In the example above, if I move Resilience before Mobility, then max tries will be T9 and T6 respectively. Such kind of note can be added: "The order of stats specifies priority of Artifice Armor mods usage. For example, if tiers of several stats can be improved with AA mods, but not simultaneously, then LO will improve stats in the specified order until no free AA slots remain".

**Comment by humandxp** [comment]
why choose by yourself? simple cos resilience now is expensive and 4 energy vs others as 3, next many rolls show for example resilience 72 i add one mod to artifice and +5 resilience half mod andi got 80 resilience. next 3 artifice armors and 90 resilience, 90+3x3=99 +1 resilience from solstice rekindled chest ornament and i have now 100. still works just checked

**Comment by humandxp** [comment]
or simply make option to not advice artifice armor mods. so i can plan it myself

**Comment by bhollis** [comment]
I'm always onboard to add more inline help where it could be instructive.

**Comment by robojumper** [comment]
> Yeah DIM doesn't investigate all possible assignments for stat mods when calculating the respective stat tier maxes, that'd be too expensive in the general case.

With #9994 in beta this part is resolved, DIM should now correctly calculate max reachable tiers (taking constraints into account).
