### ISSUE TITLE
Infusion Pair search filter

### ISSUE THREAD

**Issue by schaefa** [DestinyItemManager/DIM#9213]
### Proposed change

During a new season leveling up is very time consuming. I would love to have a filter that allows me to find infusion pairs of same weapon or armor where the source is tagged as infuse and the target is not archive or junk and lower level.
Right now I have to compare the item, then find it and move it to my character.

### How does this fit into your workflow?

With such a filter I would be able to easily move all infusion pairs to my current character and then infuse them.

**Comment by liminalAce** [comment]
have you tried out the infusion tool? that is essentially what it does, finds cheap infusion. here is an example clicking infuse from my item marked as infuse. 
![image](https://user-images.githubusercontent.com/29002828/224795328-d01d9493-9fa1-48c8-90ce-fed965bb97b6.png)

**Comment by marheine** [comment]
That's a good tool for a single piece at a time Ace, but I believe OP is hoping for a more all-at-once option.

The search filter `is:infusionfodder` sounds like roughly what you're after. It only flags the donor piece and not both halves of the infusion, but at least it gets you a quick view of all your options as a starting point.

**Comment by liminalAce** [comment]
I wouldn’t use that… it’s going to ignore your tags… and wishlists… and everything else

**Comment by bhollis** [comment]
We could do this based on the same logic we use to pick the first choice in the infusion finder, but as ace said, it's just going to pick one with our rules, doesn't guarantee it's what you want.

**Comment by schaefa** [comment]
I used the infusion tool and it works ok. What I would love to have is to see are infusion pairs like I can see all junks (tag:junk).
To keep it simple I would have something like any duplicate with a power level differences of X.
I am more interested in a quick overview than automating the infusion process.

**Comment by bhollis** [comment]
Huh, turns out this already exists - `is:infusionfodder`. It highlights items that can be cheaply infused into lower-level gear - you can open compare/infuse and pull the corresponding items easily.
