### ISSUE TITLE
Display a subclass icon in the loadout list

### ISSUE THREAD

**Issue by Misacorp** [DestinyItemManager/DIM#9221]
### Proposed change

_Hey everyone! First time contributing to DIM in any capacity here._

I'd like to propose that we display each loadout's subclass icon in the loadout list. A loadout with no subclass equipped could simply have no icon or use a neutral icon instead.

Here's an example of what the change could look like. I've displayed two different icons of which I believe the bottom one is clearer.

![image](https://user-images.githubusercontent.com/5681847/225139121-09200d5f-0f9a-4a29-ab63-207da3ed94f5.png)

### How does this fit into your workflow?

This change would make it faster to identify loadouts of a given subclass. As you can tell from the attached image, I have "solved" the issue by prefixing the element of each loadout's subclass in the loadout's name. This is a poor solution for three reasons:

1. It is cumbersome to manually name loadouts this way.
2. Discovering loadouts of a given subclass is still quite difficult (only text vs. the proposed colorful icon).
3. Loadouts have to be sorted by name for this to provide maximum benefit.

As a tangent from reason 3, I would also love to have the ability to sort loadouts by subclass and I believe this change would pave the way for that functionality in the future.

**Comment by Misacorp** [comment]
After digging into this further I discovered an existing feature previously unknown to me: Destiny symbols in loadout names added in `7.52.0`. This is great! I can now use `:void My Loadout Name` for all my void loadouts etc.

This is a great improvement in discoverability, though I still believe it would be an improvement to do this automatically for all applicable loadouts _without_ requiring users to change the name of each loadout.

**Comment by bhollis** [comment]
We've poked at automatically adding icons, but it's tough because who says that the icon we automatically choose is better than the one you manually choose? Giving users the direct control of being able to use symbols seems like the nicest option.
