### ISSUE TITLE
Add hidden stats Recoil / Inventory to Rocket Launchers

### ISSUE THREAD

**Issue by Gonzo77** [DestinyItemManager/DIM#923]
I noticed on Tower Ghost that I am able to see the stats Recoil and Inventory for Rocket Launchers.  Inventory is the most important - it can tell us how many rockets per brick in PvP / PvE to expect.  Requires knowledge of chest / boot / tripod / fieldscout perks, but useful.

**Comment by bhollis** [comment]
We'd have to do some work - recoil direction and inventory both show up as hard-to-interpret numbers - what does a Recoil Direction of 50 and an Inventory of 70 really mean to you? There are a bunch of hidden stats like that.

**Comment by Gonzo77** [comment]
Well, I only mention the recoil because it wasn't there.  The inventory stat was my main focus.  The inventory stat determine how many rockets per brick you get in PvP.  The information I have (fairly recent) says you can get 4 - on most launchers, but I am beginning to doubt it.  I can pull this info down in TowerGhost - but I really don't know how they got it, or how theorycrafters on reddit get it.

**Comment by shockthealien** [comment]
I was listening recently to the Massive Breakdown podcast and Mercules was talking about these, in particular the recoil direction. I think from what i gathered that 100 is perfectly vertical and 50 is perfectly horizontal (i assume 75 to be a 45 degree in between)

Maybe we could invite Mercules here? He is amazingly knowledgeable about weapons and he would be invaluable if we are to implement any sort of weapon quality stat

**Comment by bhollis** [comment]
I'm on board. Showing recoil direction as an arrow or something, and inventory as "ammo per brick" would be interesting.

**Comment by kshep** [comment]
Is this a rocket launcher specific issue? Don't all weapons have Optics, Handling, Recoil and Inventory values that could/should be displayed somewhere? IIRC, much of the hype around the new Palindrome hand cannon, for example, is related to the fact it has near vertical (94) recoil. It'd be nice to see these on the list right along with Rate of Fire, Impact etc.

Nice-to-have would be a checkbox for "Display Hidden Stats" on the settings page.

Personally, I wouldn't worry too much about the fact that they're hard to interpret, and recoil direction as an arrow might be neat, but that seems like v2. I just use DIM to look at and compare stats and don't expect it to explain what they all mean.

**Comment by kshep** [comment]
OK scratch most of what I said above... brain froze up temporarily... I think Recoil Direction's the only stat we're missing across the board. It'd be nice to see that for all weapons listed along with the other state.s

**Comment by bhollis** [comment]
Agreed, but we have to be able to display it nicely. Just putting the number in there is no good.

**Comment by JakeWhitaker** [comment]
+1 on not needing the stats explained. I know that the higher number is better, and so for comparison purposes(99% of why I'd want to see those hidden stats) that's all I need to know

**Comment by kyleshay** [comment]
re inventory stat: 

https://www.reddit.com/r/CruciblePlaybook/comments/5go6ff/the_complete_guide_to_special_ammo_in_the/

**Comment by jdigweed** [comment]
Is there a way to use this to show these stats?

https://github.com/DestinyItemManager/DIM/blob/dev/app/scripts/debug/dimDebugItem.controller.js

**Comment by kyleshay** [comment]
No longer in the scope of D1, we'll reconsider hidden stats for D2.
