### ISSUE TITLE
Limit loadouts

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#9231]
I've seen users with 600, 700, 1000 loadouts. We should probably set an upper bound to save our service and their computer performance, and maybe their sanity.

**Comment by BrandonCasa** [comment]
1000 is insane. Would it not take near minutes to load the loadout screen?

**Comment by mannyrye** [comment]
Providing dates of creation and modification (with season number), would help the user when culling and updating loadouts.

**Comment by bhollis** [comment]
Linking #8015
