### ISSUE TITLE
Search filter for items that are present in in-game loadouts

### ISSUE THREAD

**Issue by matthubb** [DestinyItemManager/DIM#9252]
### Proposed change

It would be useful to be able to identify items by whether they are in a given character's in-game loadout.

e.g.
- `is:ingameloadout`
- `ingameloadout:leftchar`
- `ingameloadout:middlechar`
- `ingameloadout:leftchar`
- `ingameloadout:currentchar`

### How does this fit into your workflow?

In-game loadouts are unable to move items from other characters. It would be nice if DIM could facilitate the fulfilment of these in-game loadouts by identifying the items that the in-game loadouts cannot find and moving them to somewhere it can find them.

One way to do this might be a filter to identify weapons that the current character has linked in in-game loadouts, but are not on that character and not in the vault either. E.g.:
`ingameloadout:currentchar not:incurrentchar not:invault`

And then use DIM to move these items to the vault.

**Comment by bhollis** [comment]
If DIM automatically moved items into the right place so that the loadout can equip, would you still use these filters?

**Comment by matthubb** [comment]
I would probably not use these filters if DIM could resolve in-game loadout misplaced items automatically.
