### ISSUE TITLE
Highlight powerful/pinnacle items in the Item Feed

### ISSUE THREAD

**Issue by rossvz** [DestinyItemManager/DIM#9259]
### Proposed change

When completing an activity that drops a variety of loot, where one of those items can be a pinnacle, it would be great to mark/highlight/tag items that are substantially higher than current power level

### How does this fit into your workflow?

I usually keep the item feed up, and end up bouncing between the new item's power level and my own to confirm that was the pinnacle that dropped.

**Comment by bhollis** [comment]
This feels like a variation on https://github.com/DestinyItemManager/DIM/issues/6262

**Comment by bhollis** [comment]
Probably we'd want to highlight items that are above your current average max power. But then the question would be why we don't highlight those everywhere, which is similar to the request to highlight maxpower items. The tough part being when you hit cap you probably don't want to see all your items highlighted. Anyway, I'm open to all of it.

**Comment by bhollis** [comment]
Closing this in favor of the tracking issue https://github.com/DestinyItemManager/DIM/issues/10452, which has additional info.
