### ISSUE TITLE
Masterwork stat (in Organizer/CSV) for crafted items is weird

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#9263]
<img width="1349" alt="image" src="https://user-images.githubusercontent.com/313208/226089395-21798c42-4a30-4b53-902b-476d053c82ef.png">

It would probably make more sense if we just highlighted the effect of the enhanced intrinsic?

**Comment by robojumper** [comment]
Related: Level 20 enhanced intrinsics / T10 adept masterworks make a weapon match all the different `masterwork:statname` filters
