### ISSUE TITLE
Website opens with my Destiny 1 profile as the active profile

### ISSUE THREAD

**Issue by Anvilcrack** [DestinyItemManager/DIM#9267]
### DIM Version

7.60.1

### Browser Details

Firefox 112.0

### OS Details

Windows 10

### Describe the bug

Recently, logging into the website is defaulting to open my destiny 1 profile instead of my destiny 2 profile.  I don't see an option to set the Destiny 2 characters as the default profile

**Comment by bhollis** [comment]
You can change from the menu on the left. It's possible you bookmarked your D1 URL which is why it opens there every time.
