### ISSUE TITLE
catalyst:missing filter not highlighting LEVIATHAN'S BREATH, and REVISION ZERO is wrongly highlighted

### ISSUE THREAD

**Issue by yl10030270** [DestinyItemManager/DIM#9279]
### DIM Version

Version 7.61.0.1002405 (beta), built on 3/19/2023, 7:23:33 PM

### Browser Details

Chrome 111.0.0.0

### OS Details

Windows 10

### Describe the bug

catalyst:missing filter not highlighting LEVIATHAN'S BREATH, and REVISION ZERO is wrongly highlighted

**Comment by delphiactual** [comment]
#9060

**Comment by bhollis** [comment]
Closing as duplicate.
