### ISSUE TITLE
Master raid completion is missing

### ISSUE THREAD

**Issue by Prometheus3375** [DestinyItemManager/DIM#9301]
### DIM Version

Version 7.61.0 (release), built on 20.03.2023, 05:18:55

### Browser Details

Chrome 111.0.0.0

### OS Details

Windows 10

### Describe the bug

I completed Vault of Glass on master difficulty, only last encounter.
DIM does not display green box at the last encounter of VoG in progress tab.

![image](https://user-images.githubusercontent.com/35541026/227726010-6ce0fc03-1a36-45fc-96dc-cca96c1df724.png)
[Note](https://www.bungie.net/7/en/Pgcr/12854950837) about raid run in profile.

My [RR](https://raid.report/pc/4611686018482890420) also does not show this run for some reason. It is possible to view this run on [RR](https://raid.report/pgcr/12854950837), but it is displayed as non-Raid.

**Comment by Prometheus3375** [comment]
> It is possible to view this run on [RR](https://raid.report/pgcr/12854950837), but it is displayed as non-Raid.

Some time ago it started to be viewed as intended, maybe after my report the RR team.

**Comment by bhollis** [comment]
Can you attach a profile export (from Settings in Beta) that includes the completed step?

**Comment by Prometheus3375** [comment]
Added .txt to be able attach.
[profile-data.json.txt](https://github.com/DestinyItemManager/DIM/files/12111960/profile-data.json.txt)

**Comment by bhollis** [comment]
I can't find any evidence in that profile response that you've completed any raid encounter on any character. This suggests to me that Bungie.net is not returning that data correctly.

I'm not familiar with Raid Report, but the milestone data we use is very different from PGCR data.

**Comment by Prometheus3375** [comment]
Well, I think then this issue can be closed. If I encounter such issue again, I will create a new ticket with attached profile data and respective links.
