### ISSUE TITLE
Save Artifact mods in Loadout

### ISSUE THREAD

**Issue by Neutex** [DestinyItemManager/DIM#9325]
### Proposed change

If available in the Bungie API, It would be great if DIM could reset then assign saved artifact mods in a DIM loadout.

### How does this fit into your workflow?

Different loadouts sometimes require specific artifact mods. In season 20 we have both **Flare Up** and **Rain of Firebolts** which only applies to solar subclasses. It's a pain to manually reset and re-spec the artifact every time you switch to and from a solar loadout that uses firebolt grenades.

Since Bungie has not yet implemented artifact mods in their loadout, perhaps DIM can? It's a long requested feature on Destiny forums since Lightfall.

**Comment by robojumper** [comment]
DIM cannot reconfigure your artifact, but it could save the artifact configuration so you can tell more easily what to unlock before applying a loadout.

**Comment by Neutex** [comment]
> DIM cannot reconfigure your artifact, but it could save the artifact configuration so you can tell more easily what to unlock before applying a loadout.

That would also be good to have. That way one could at least store an entire build somewhere.

**Comment by robojumper** [comment]
> That would also be good to have.

Try [beta](https://beta.dim.gg) :)

**Comment by Neutex** [comment]
Very nice! I run beta all the time because features :)
