### ISSUE TITLE
Compare Loadouts select dropdown can get too tall

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#9334]
It needs a scrollbar

**Comment by bhollis** [comment]
![](https://cdn.discordapp.com/attachments/333464468241514497/1089858190830739508/MBEltj9.png)

![](https://cdn.discordapp.com/attachments/333464468241514497/1089858191296303124/O1wq2g3.png)

**Comment by mattjbones** [comment]
I had a go at this, pretty minor change. Lemme know if you were thinking something different?
