### ISSUE TITLE
Add don't auto-move to vault setting

### ISSUE THREAD

**Issue by CupOfTea696** [DestinyItemManager/DIM#9338]
### Proposed change

Add a setting to prevent DIM from automatically moving items to your vault when an inventory slot is full, and instead display an "inventory full" error message so I can manually pick what to send to my vault. 

### How does this fit into your workflow?

Sometimes I pull things from my vault just as DIM refreshes and realises my inventory is full, and it then sends items to my vault after which I then have to figure out what it send in there to pull it back on my character.

**Comment by bhollis** [comment]
https://github.com/DestinyItemManager/DIM/wiki/Frequently-Requested-Features#disable-smart-moves
