### ISSUE TITLE
Notes / tags not syncing?

### ISSUE THREAD

**Issue by Gonzo77** [DestinyItemManager/DIM#935]
Hi  I have Google signed in on both machines at work and home, both windows PC.  They both sync.  I lost all my notes and most of my tags from yesterday on armor.  Tags seem to still be active on my weapons, as well as notes.  It appears that only information on weapons survived.  Is there any way to troubleshoot the syncing stuff?

**Comment by Gonzo77** [comment]
I just tagged an noted a helmet to test, closed and reloaded the tab on the same computer.  The tag and note are gone.

**Comment by Gonzo77** [comment]
Is it possible I don't have this set up properly for the data to transfer?

**Comment by bhollis** [comment]
If anything transferred, it all should have. There's also nothing separate
about weapons and armor. I'm gonna have to dig into the sync service and
figure out what's going on.

**Comment by Gonzo77** [comment]
I found another discussion where someone mentioned there is an 8k limit?  Isn't that about the size of a page or two of plain text?  I was clearing out my vault doing a lot of .CSV filtering to determine what I wanted to keep / dismantle.  I tagged and made notes on probably 80% of my vault.  I wonder if hit a limit?

**Comment by kyleshay** [comment]
quite possible that you hit the limit @Gonzo77. sorry you lost your data. working to see what we can do to make sure that doesn't continue to happen.

the 8k limit can be hit pretty quickly... a single item looks like:
`{"255654879-6917529084568623395":{"tag":"favorite"}}`, which is 52 characters. That already limits the number of tags to ~150... adding notes quickly reduces that number.

**Comment by kyleshay** [comment]
closing in favor of #892
