### ISSUE TITLE
Display selected ornaments and shaders for gear in Destiny loadouts

### ISSUE THREAD

**Issue by Prometheus3375** [DestinyItemManager/DIM#9357]
### Proposed change

Currently, DIM does not display selected fashion for Destiny loadouts. I would like to see it as it is displayed in DIM loadouts.

### How does this fit into your workflow?

Destiny loadouts memorizes selected fashion for gear. And it is not possible to view anywhere. For me this is especially annoying for weapons. I can replace weapon ornament/shader for a new one, but once I apply Destiny loadout, fashion change reverted. The same is true for armor too.

Ability to view selected ornaments and shaders will help to identify which Destiny loadouts must be updated.

**Comment by bhollis** [comment]
Duplicate of #9103, fixed in #9312

**Comment by Prometheus3375** [comment]
I forgot one thing. In-game loadouts also memorize selected kill tracker for weapons. Can be useful to view this info in DIM too.

Btw, why DIM cannot change kill trackers?

**Comment by delphiactual** [comment]
bc the api does not allow it
