### ISSUE TITLE
Filter Suggestion: memento:none

### ISSUE THREAD

**Issue by marheine** [DestinyItemManager/DIM#9366]
### Proposed change

The best way to view "weapons with empty memento socket" is with a search akin to `is:crafted -memento:any -is:exotic`. A much nicer way to get this result would be if there was a `memento:none` that could light up all such gear.

### How does this fit into your workflow?

I'm the sort of person who wants to put a memento on everything I can, so having a single query for it would make it simpler to identify them.

**Comment by robojumper** [comment]
Consider saving the query `/* needs memento */ is:crafted -memento:any -is:exotic`. From that point on you can just type "needs mem..." and rely on autocompletion to suggest the full saved query.
