### ISSUE TITLE
Feature: Allow 'Best item matching this filter' in gear loadouts

### ISSUE THREAD

**Issue by Makeshift** [DestinyItemManager/DIM#9367]
### Proposed change

Have the option when creating a loadout for the slot to be filled with the best/highest light-level item matching a particular filter that's available in the players inventory.

### How does this fit into your workflow?

I'm currently creating loadouts for quickly completing groups of bounties, and I noticed I could pick multiple weapons for the same slot. I assume if the top weapon isn't available, DIM will pick the bottom one instead. However, my light level is currently pretty low so the weapons I'm choosing for my loadouts are pretty arbitrary and just happen to meet the requirements to do the bounty.

Rather than having to re-curate all my loadouts as my light level goes up, it would be cool to take advantage of DIMs amazing filters to have a filter set up on a loadout slot that equips using a filter to find the best item I currently have that matches the requirements on a loadout. I feel like this would be a really good feature for groups setting things like raid requirements, or veteran players sharing an "ideal" loadout for something to a newer player, but having the secondary option be "the best item they have that still meets x requirements".

This _could_ be expanded into the idea of having "equip everything I need to complete my bounties most effectively", but I believe that's been suggested before and was deemed to be a hell of a lot of work (I was thinking about maybe making it, but then saw D2 has 800+ bounties). The above suggestion puts the onus on the user to set up their loadouts effectively (no travelling salesman problem to solve, yay!), but still allows for flexibility based on the users inventory.

**Comment by bhollis** [comment]
> I assume if the top weapon isn't available, DIM will pick the bottom one instead.

No, the distinction is between items that are equipped and items that are just moved to the character.

The idea of search-based loadouts or loadout placeholders has come up quite often though.

Linking #8995

**Comment by Makeshift** [comment]
> No, the distinction is between items that are equipped and items that are just moved to the character.

Oh, my bad, misunderstood.
