### ISSUE TITLE
Add feature to lock all 'keep' & 'favorite' items

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#937]

**Comment by wein3967** [comment]
All for. I would've suggested it once the Tag/Notes stuff was all sorted.

**Comment by bhollis** [comment]
Linking to #397

**Comment by kyleshay** [comment]
Should we make it the default functionality when you apply a 'favorite'/'keep' tag that it auto-locks? otherwise this brings up a bigger discussion of where these types of macros could live.

**Comment by bhollis** [comment]
My thought is that it'd live in the Saved Search (#1874) dropdown - type a search, click the dropdown / menu, select "lock all".

**Comment by kyleshay** [comment]
Sounds like a good place to me! Feel free to copy the task elsewhere and close, or just link to this one.
