### ISSUE TITLE
enhancement suggestion: filter by lastused

### ISSUE THREAD

**Issue by s-diniro** [DestinyItemManager/DIM#9370]
It'd be handy to have a filter feature where we can filter for items based on the date they were last used.

A sample use case is something like **lastused:<01/01/2022** to find items that haven't been used in, say, over a year.

This'd be a nice way to identify items that can be pruned from my inventory

**Comment by bhollis** [comment]
https://github.com/DestinyItemManager/DIM/wiki/Frequently-Requested-Features#can-dim-show-me-what-weapons-i-use-the-most
