### ISSUE TITLE
Ornamented armor can show inconsistent background

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#9376]
### DIM Version

Current beta

### Browser Details

Chrome

### OS Details

Windows 11

### Describe the bug

If you take a piece of legendary (purple) gear, and apply an ornament created from a rare (blue), in game is shows with a purple background, but in DIM it shows with a blue background.

In the example Tusked Allegiance Grieves with a Hardcase Stompers ornament.

Game:
![Screenshot 2023-04-09 222142](https://user-images.githubusercontent.com/25425159/230773830-98c4ce57-1066-4dc0-9502-2be7a9f18abf.png)

DIM:
![Screenshot 2023-04-09 222245](https://user-images.githubusercontent.com/25425159/230773844-0d5fc20e-9cf4-47e4-8f96-3143ef65f977.png)

**Comment by robojumper** [comment]
Can't do anything about it -- Companion app behaves the same. Dupe #8579.
