### ISSUE TITLE
When I export my weapon list I'm getting a weapon I don't actually have

### ISSUE THREAD

**Issue by dustinrue** [DestinyItemManager/DIM#938]
When I export my weapon list to CSV I get this extra weapon that no other tool claims I have.  It is:

Cúchulainn-D, Rare, Shotgun, 317 and does ARC damage.

Anything I can do to provide additional info?

**Comment by bhollis** [comment]
Hmm, that's a real mystery. If you search for it in DIM, do you see it anywhere? It only shows up in the CSV export? Where in the CSV is it?

**Comment by kyleshay** [comment]
@dustinrue are you still seeing this issue?

**Comment by dustinrue** [comment]
After RoI dropped I managed actually get this weapon in my inventory. Not sure how this came about the weapon was found and now deleted
