### ISSUE TITLE
Add cosmetic storage/applying independent of actual items

### ISSUE THREAD

**Issue by muuyo** [DestinyItemManager/DIM#9384]
### Proposed change

Say I have an Arc build with the exact setup I'd want on my Solar build, but the wrong looks - and the right cosmetic setup is saved to the Solar build in Destiny's system.
To transfer over the cosmetics without changing the items, I'd have to create a new temporary loadout for only the cosmetics, then switch over, then let it apply them - which I've had problems with before.
I'd like to see a simple "Apply cosmetics" button or similar beside the Apply button, which transfers over *only* cosmetic stuff - no actual mods or items. Ideally, this would show up on the Destiny-based loadouts aswell, as that'd make it one-click, but they seem to be stored differently within DIM.

### How does this fit into your workflow?

Would let "fashion" players much more easily change between setups without having to recreate transmog setups each time.

**Comment by bhollis** [comment]
The suggestion is to make fashion only loadouts and apply them separately.
