### ISSUE TITLE
Change to ingame loadout display stops them being sent to streamdeck

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#9395]
### DIM Version

Current beta

### Browser Details

Chrome

### OS Details

Windows 11

### Describe the bug

The ingame loadouts have moved to a section at the top of the loadout screen.

But there is now no way to send them to streamdeck using the plugin.

![image](https://user-images.githubusercontent.com/25425159/231741109-9f293b12-2de0-43ce-a8fd-65fb25ac72b2.png)

**Comment by delphiactual** [comment]
@fcannizzaro
