### ISSUE TITLE
Enhancement: Filter by Weapon Type (not Class)

### ISSUE THREAD

**Issue by m-s-y** [DestinyItemManager/DIM#94]
Add the filter option to select by weapon type:

is:handcannon
is:autorifle
is:scoutrifle
is:pulserifle
is:fusionrifle
is:shotgun
is:sniperrifle
is:sidearm
is:machinegun
is:rocketlauncher

**Comment by SunburnedGoose** [comment]
Will do.

**Comment by kyleshay** [comment]
implemented in v3.0.18
