### ISSUE TITLE
Without perks, beta and release react differently to the absence.

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#941]
Beta client renders items with a yellow border when there are no stats.  Release client renders the border with white.  What has changed?

![screen shot 2016-09-19 at 4 21 39 pm](https://cloud.githubusercontent.com/assets/984608/18653103/438a570e-7e9d-11e6-8a7d-ba230726c174.png)
![screen shot 2016-09-19 at 4 21 16 pm](https://cloud.githubusercontent.com/assets/984608/18653104/438bfcb2-7e9d-11e6-8ad6-99f27994d093.png)

**Comment by delphiactual** [comment]
Possibly https://github.com/DestinyItemManager/DIM/commit/f5f195e26f3490c91a548c7d139707fc25ca1270

**Comment by bhollis** [comment]
@delphiactual is right - this was part of my attempt to handle the bugged `isGridComplete` in #932. I'll make it handle missing talent grid as well.

**Comment by bhollis** [comment]
Actually I'm not sure I see what caused that, and it's not reproing now. When you say there were no stats, what exactly did you mean? What was missing?

**Comment by wein3967** [comment]
I saw that earlier today as well with the beta. Everything had gold borders, no perks, no stats, no quality, and, no xp gauge. However, I guess around ~5:30 pm (central) the beta popped back and has been operating normally for me since.

**Comment by bhollis** [comment]
I've pushed e02a3e898a61d6571538a40d610bb6161bb13182 in an attempt to fix it, but I can't be 100% sure without knowing exactly what the API was returning during that period.

**Comment by SunburnedGoose** [comment]
There are no perks, stats, or primaryStats in the array.  Bungie has to regenerate those.  If you want to repo, just make empty arrays for those in your store service when generating items.

**Comment by bhollis** [comment]
In that case my commit will definitely fix it.
