### ISSUE TITLE
Kinetic Dexterity shows info about Kinetic Holster in community insight

### ISSUE THREAD

**Issue by Tenkuuu** [DestinyItemManager/DIM#9414]
### DIM Version

Version 7.64.1.1002529 (beta), built on 18/04/2023, 11:33:24 pm

### Browser Details

Firefox 112.0.1 (64-bit)

### OS Details

Windows 10

### Describe the bug

Hovering over to Kinetic Dexterity seems to show information about Kinetic Holster instead of Dexterity. Only seems to affect Kinetic ver too since every other dex shows their proper info. Here's an image showing the bug:
![image](https://user-images.githubusercontent.com/52702672/233032747-a6f6b70f-ee15-48d8-a990-b0b4404f5d38.png)

**Comment by StardustD2** [comment]
Fixed.
