### ISSUE TITLE
Feature: Fashion Locker

### ISSUE THREAD

**Issue by Mayul** [DestinyItemManager/DIM#9417]
I have a few loadouts strictly for fashion with specific exotics. If the exotic is cross-subclass, then there is probably multiple per element. This isn't including my other characters either. After loadout fashion was built, this just seems like the obvious next step!

I'm sure someone has suggested it but from googling, unless I'm using the wrong search terms, I can't seem find anything on it.

**Comment by robojumper** [comment]
It's unclear what you're actually asking for. Do you mean a loadouts subfolder that can contain all fashion loadouts?

**Comment by Mayul** [comment]
Sorry, but yes exactly that. With the ability to apply it to our character excluding the exotic slot if they do not match.

**Comment by bhollis** [comment]
I believe this falls under #7663
