### ISSUE TITLE
Enhancement: add an option to not add similar items to comparison

### ISSUE THREAD

**Issue by Prometheus3375** [DestinyItemManager/DIM#9420]
### Proposed change

Whenever I press Compare, all similar items are added. Sometimes this is not necessary. There are several options:

- Do not add items to comparison with certain tags, like Trash.
- Add a switch to settings. When on, add all similar items to comparison, when off do not.
- Add special way to open compare dialog with no similar items added. For example, pressing Shift + Left mouse button.

### How does this fit into your workflow?

For example, on the first week of GMs I was farming and got a lot of Hung Jury. Most of them were trash, so I marked them as Trash and stored for future infuse. Whenever I got good roll and press compare, all of trash rolls were added with some good ones in the end.

**Comment by robojumper** [comment]
You can always compare using a search query -- e.g. `"hung jury" -tag:junk`, then press the three dots on the right end of the search bar, choose "Compare Items".
