### ISSUE TITLE
Too many platform requests per second

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#943]
Just saw this - not sure if this is a new limit, or just DIM gaining popularity in the runup to RoI:

```
angular.js:13920 Error: Too many platform requests per second.
    at handleErrors (dimBungieService.factory.js?v=$DIM_VERSION:62)
    at angular.js:16383
    at m.$eval (angular.js:17682)
    at m.$digest (angular.js:17495)
    at m.$apply (angular.js:17790)
    at l (angular.js:11831)
    at J (angular.js:12033)
    at XMLHttpRequest.t.onload (angular.js:11966)
```

**Comment by SunburnedGoose** [comment]
Which requests?  Are these throttled?

**Comment by bhollis** [comment]
I've only seen it once, and I didn't capture the request it was associated with :-(

**Comment by bhollis** [comment]
OK it was a vendor request (https://www.bungie.net/Platform/Destiny/2/MyAccount/Character/2305843009214965410/Vendor/4275962006/), and the response was:

```json
{"ErrorCode":51,"ThrottleSeconds":0,"ErrorStatus":"PerEndpointRequestThrottleExceeded","Message":"Too many platform requests per second.","MessageData":{}}
```

Looks like [we're really hammering the API for vendors](https://github.com/DestinyItemManager/DIM/issues/939#issuecomment-248215029) so that's probably the issue.

**Comment by bhollis** [comment]
Closing in favor of #939. We need to figure out how to get the vendor stuff under control.
