### ISSUE TITLE
Include character icon in vault when there are no items

### ISSUE THREAD

**Issue by ryan-rushton** [DestinyItemManager/DIM#9431]
### Proposed change

Had a request during an LFG to include the character icon for characters with no gear in the slot. Better yet would be some kind of alignment when really low numbers of gear like this.

![image](https://user-images.githubusercontent.com/7344652/235330360-6da34f1f-0ec0-4c43-aa26-98ef2c49cc9a.png)

### How does this fit into your workflow?

Improves experience for new lights and those with minimal armour in their vault.

**Comment by ryan-rushton** [comment]
I think the Char icon makes sense, maybe with a placeholder or something after it but not sure about alignment unless it is easy and doesn't create branching

**Comment by bhollis** [comment]
I'm not sure that satisfy-OCD is a design goal for DIM

**Comment by ryan-rushton** [comment]
> I'm not sure that satisfy-OCD is a design goal for DIM

Partially a joke because you are forced to enter something, should have cleaned up after creation. 

Largely reported it as some structure for these would make it look nicer for new lights and make it clear that you can drop items here even when they have nothing in their vault. Very much an edge case though, if we can't be bothered happy to close as won't fix.

**Comment by ryan-rushton** [comment]
Fixed

**Comment by bhollis** [comment]
How would it improve their experience? Wouldn't it be confusing to show a class icon with nothing beside it?

**Comment by ryan-rushton** [comment]
The idea that was being floated was to put a placeholder next to the character icon to indicate an empty state. For characters with no gear it then just indicates something can be dropped there.

The only reason I kinda agree with it is I have a dislike for empty state that doesn't provide some kind of visual instruction or cue for users indicating that.

Again though, major edge case. Not really fussed either way.
