### ISSUE TITLE
Bulk compare weapons in D2Foundry.gg (aka //Foundry in DIM)

### ISSUE THREAD

**Issue by mturquette** [DestinyItemManager/DIM#9435]
### Proposed change

DIM already supports the basics of this feature: currently we're able to inspect a weapon in DIM, click the name of the weapon, select //Foundry, and that will open D2Foundry.gg to the weapon page that matches the inspected weapon in DIM, with matching perks pre-selected. Very convenient!

D2Foundry also has a very strong "compare" feature. While similar to DIM's Compare or Organizer screens, D2Foundry goes into far more details including TTK values, flinch resist percentage, ready/ads/stow speeds in seconds, etc. D2Foundry also allow us to theorycraft with mods, exotic armor, abilities, etc. I have attached a screenshot of what https://d2foundry.gg/compare looks like.

<img width="2560" alt="Screenshot 2023-05-01 at 10 20 39 AM" src="https://user-images.githubusercontent.com/13019/235476270-4d9df297-025c-4fa1-a9ff-0a26c4758c2f.png">

This feature request is to add an option to the Compare and Organizer views in DIM to perform a bulk transfer of multiple weapons from DIM to D2Foundry, with the express purpose of using the D2Foundry.gg compare view. If possible, the ideal flow would be something like:

1. View all of my "Snorri FR5" in DIM via the Compare view
2. Click a new button new named "Export to D2Foundry". This button might be placed alongside the "Show in Organizer" button at the top right of the Organizer modal.
3. This opens a new browser tab to https://d2foundry.gg/compare with all of the weapons in the compare view pre-loaded

The flow for doing this from the Organizer screen might look something like:

1. View all of my "Snorri FR5" in DIM via the Organizer
2. Click a new button new named "Export to D2Foundry". This button might be placed alongside the "Import CSV" and "Weapons.csv" buttons at the top right
3. This opens a new browser tab to https://d2foundry.gg/compare with all of the weapons in the compare view pre-loaded

I hope that description makes sense? I have not investigated how easy D2Foundry.gg makes this. I'm not sure if a bulk API exists or not.

As an aside, I'd love if DIM & D2Foundry made a baby. A beautiful, data-driven baby. DIM is the GOAT for weapons that I own, and D2Foundry is the GOAT for rolls that I want to get. Integrating these tools more closely would be very powerful.

Thank you for attending my Ted(x) Talk.

### How does this fit into your workflow?

The workflow that I have today is that I will use the existing export-to-D2Foundry.gg feature manually, for each and every gun that I want to compare. When I want to compare a lot of guns at once, this is very tiresome (I'm looking at you, 58x "Out Of Bounds" and 99x "Blowout"'s).

Having a bulk export to D2Foundry feature would eliminate much of this tedious clicking, just to use the Compare screen on D2Foundry.gg.

I would still need to go back to DIM to tag the rolls that I want to keep/junk, or add Notes. Maybe someday the tools can come even closer to make this process more seamless. For now, just having the bulk export would help a lot.

**Comment by bhollis** [comment]
Yeah, something like this would be nice. I'll have to look and see how D2Foundry works (I didn't know what to call it as it calls itself "// Foundry"). 

With regards to further integration, DIM has an open API for tagging items that D2Foundry could use if they wanted.

I also suspect that DIM will end up gaining a lot of the info that's currently only visible on D2Foundry.

**Comment by mturquette** [comment]
Yeah, thinking about it some more, I wonder if there is a stopgap solution similar to the Clarity add-on for DIM? Maybe a way to have an embed of D2Foundry visible within DIM? No idea how that should work in practice.

Of course DIM could eventually just add the missing values / statistics (damage falloff distance, speeds in seconds, etc). One of the most useful things that D2Foundry does is convert the obtuse values (Range, Handling, Stability, Reload) into real-world measurements that regular folk can understand. DIM could certainly replicate this functionality natively without needing to integrate with D2Foundry.

The bigger issue is the theorycrafting aspect of D2Foundry. That's the real requirement behind this Issue. In DIM I can only compare rolls that I own. If I export to D2Foundry then I can compare rolls that I have as well as rolls that I'm chasing.

Maybe DIM will develop a similar pick-your-perks kind of system later on, but that seems like a bigger ask than just making the export feature support multiple items.

**Comment by mturquette** [comment]
sadge 😭 Thanks for considering this issue though.

**Comment by bhollis** [comment]
I'd welcome this integration from the D2Foundry devs themselves, but I was personally unable to get the compare functionality to work on that site at all, let alone craft a URL into it. I suspect it'll require work on their side.
