### ISSUE TITLE
Old items in a loadout cause loadouts to fail

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#944]
I think this is since the "unknown" items change for loadouts. I have an old loadout that contains items I've since deleted. If I try to apply the loadout, I get an error:

```
angular.js:13920 TypeError: Cannot read property 'type' of undefined
    at getLoadoutItem (dimLoadoutService.factory.js?v=$DIM_VERSION:193)
    at dimLoadoutService.factory.js?v=$DIM_VERSION:231
    at underscore.js:227
    at Function.m.each.m.forEach (underscore.js:153)
    at Function.m.filter.m.select (underscore.js:226)
    at dimLoadoutService.factory.js?v=$DIM_VERSION:230
    at dimActionQueue.factory.js?v=$DIM_VERSION:19
    at angular.js:16383
```

This is just because the item in the loadout doesn't actually exist in my inventory. Previously it would have been filtered at loadout load time, but now it isn't. Actually, this probably didn't work even before, if you loaded the loadouts, then deleted one of the items in the loadout, then tried to use it.

I also notice that the loadout editor identifies these missing items as "vendor items":

<img width="463" alt="screen shot 2016-09-19 at 10 43 41 pm" src="https://cloud.githubusercontent.com/assets/313208/18658830/033b4aaa-7ebb-11e6-8fcf-c04753896db0.png">

**Comment by ericnelson0** [comment]
Maybe the copy should be changed from "These vendor items" --> "These items"

**Comment by TerraReef** [comment]
Just wanted to add this is still an issue.  You can remove any item from a load out accept for an item that no longer exists and keeps the load out from working.  
Ideally (I think)
- When you try to equip the load out it equips everything else and shows an error stating it is no longer able to add one of the items that was deleted.  
-  Items that no longer exist should still have an X at the top right so they can be removed from the loadout.
