### ISSUE TITLE
Uncollected filter

### ISSUE THREAD

**Issue by Revadike** [DestinyItemManager/DIM#9444]
![image](https://user-images.githubusercontent.com/4411977/236632653-5c050b63-b697-4248-9874-5d729f856771.png)

This doesn't make sense. It's in my inventory, yet still uncollected?

**Comment by robojumper** [comment]
That toggle refers to the state of the associated collections entry -- despite having a copy of these weapons, Bungie doesn't show them as unlocked in collections, which is presumably why you're being offered these weapons in the first place (Banshee isn't selling them to me).

**Comment by Revadike** [comment]
So, it's the blame of bungie's spaghetti code? surprise, surprise
