### ISSUE TITLE
`source:ritual-weapon` misses Ecliptic Distaff and Salvager's Salvo

### ISSUE THREAD

**Issue by 2bithacker** [DestinyItemManager/DIM#9446]
### DIM Version

Version 7.66.0.1002552 (beta), built on 5/6/2023, 12:10:59 PM

### Browser Details

Firefox 112.0.2 (64-bit)

### OS Details

Windows 10

### Describe the bug

The `source:ritual-weapon` doesn't find Ecliptic Distaff (S20, item ID 3001205424) or Salvager's Salvo (S13, item ID 2060863616) which are both the ritual weapons from their respective seasons.

**Comment by JAssertz** [comment]
Hey, I found the issue that is causing this, I also found some other ritual weapons that are not listed to be found.

Note: from my testing is:ritual-weapon does nothing its source:ritual-weapon that searches for ritual weapons.

**Comment by 2bithacker** [comment]
> Note: from my testing is:ritual-weapon does nothing its source:ritual-weapon that searches for ritual weapons.

Yeah, that was just my mistake when creating the issue, fixed the title and initial comment.
