### ISSUE TITLE
Looks like Heir Apparent's Magazine Size is Listed Incorrectly.

### ISSUE THREAD

**Issue by jbrivers7** [DestinyItemManager/DIM#9448]
Heir Apparent's magazine size is listed as 129 in DIM, but is actually 200 in game. Just any fyi! =D DIM is amazing, and we love you!!!

**Comment by delphiactual** [comment]
https://github.com/DestinyItemManager/DIM/wiki/FAQ#why-is-the-magazine-stat-in-dim-different-from-in-game
