### ISSUE TITLE
"Matching Loadouts" includes loadouts with no equipped items

### ISSUE THREAD

**Issue by Prometheus3375** [DestinyItemManager/DIM#9466]
### DIM Version

Version 7.68.0 (release), built on 15.05.2023, 05:09:21

### Browser Details

Chrome 111.0.0.0

### OS Details

Windows 10

### Describe the bug

Expected behavior: matched loadouts have similar set of weapons or armor.
Actual behavior: matched loadouts may have different weapon sets.

The tip:
![image](https://github.com/DestinyItemManager/DIM/assets/35541026/0ea3824b-4cc3-4f84-80fb-0ef65cd46062)

In-game loadout:
![image](https://github.com/DestinyItemManager/DIM/assets/35541026/73e45dde-a7fb-441d-9c14-06c5f0d67eda)

First loadout in the list (expected):
![image](https://github.com/DestinyItemManager/DIM/assets/35541026/7fd80b87-3017-43a7-ba6e-212736fcfb20)

Second loadout in the list (unexpected):
![image](https://github.com/DestinyItemManager/DIM/assets/35541026/08e3c6fe-d7b0-4e72-9f84-1554c3c8bbb7)

Logs: [logs.txt](https://github.com/DestinyItemManager/DIM/files/11512577/logs.txt)

**Comment by robojumper** [comment]
The code in question: <https://github.com/DestinyItemManager/DIM/blob/4be7854f229d76108e3ebbff41545bc6f9abeaf4/src/app/loadout/ingame/ingame-loadout-utils.ts#L78-L141>

This could probably be explained better, but the check is essentially "does in-game loadout X apply all the things a DIM loadout A would" (ignoring A's pocketed items). A loadout with mismatching subclass configuration is thus excluded, but a loadout that specifies very few things will often match.

To address this fact, there's another restriction that only loadouts with more than 4 items are considered for this "matching loadouts" list:

https://github.com/DestinyItemManager/DIM/blob/4be7854f229d76108e3ebbff41545bc6f9abeaf4/src/app/loadout/ingame/selectors.ts#L158

but this check includes pocketed items too. Maybe this should check that more than 4 items are actually equipped? I don't know why this exact number was chosen.

**Comment by bhollis** [comment]
Hmm, yeah that check doesn't quite make sense - it should probably be limited to buckets that could be equipped by an ingame loadout, and only equipped items. I don't quite know why the 4 item limit is there either, it doesn't seem necessary if we limit by the above and require that at least one thing actually matches.

It'd be a bonus if we could also match fashion loadouts that happen to match the ingame loadout...
