### ISSUE TITLE
t.recommendedPerks is not iterable

### ISSUE THREAD

**Issue by Th30utcast** [DestinyItemManager/DIM#9467]
I tried to open the normal DIM but was greeted with a type error of t.recommendedperks is not inerrable. I followed the troubleshooting guide and tried to open DIM beta, that worked. I just figured it's better to report such a bug 
![Screenshot 2023-05-20 100756](https://github.com/DestinyItemManager/DIM/assets/115406217/e725dae4-4d48-4f98-aa8c-1118a5cb172f)

**Comment by bhollis** [comment]
Sorry, this isn't enough info to make a fix. Please reopen if you can provide the info in our bug report template such as DIM version and logs.

**Comment by bhollis** [comment]
Sentry issue: [DIM-1BJW](https://destiny-item-manager.sentry.io/issues/3470363514/?referrer=github_plugin)

**Comment by bhollis** [comment]
I managed to find the Sentry issue. Still no idea how it could be in this state though.
