### ISSUE TITLE
Reputation progress visualization is incorrect

### ISSUE THREAD

**Issue by crulplay** [DestinyItemManager/DIM#947]
The diamonds representing the reputation progress do not visualize the progress correctly.

As you can see in the two screenshots (one from bungie.net, one from DIM), I have 2761 reputation, which is roughly 92% to get to the next rank. In DIM this looks more like 98-99%

<img width="182" alt="dim" src="https://cloud.githubusercontent.com/assets/6766410/18664214/e1c172a2-7f21-11e6-9ecf-a9f6fe3ec44a.png">
<img width="350" alt="bungie" src="https://cloud.githubusercontent.com/assets/6766410/18664250/06080cc0-7f22-11e6-9c90-63c04f21bcce.png">

**Comment by bhollis** [comment]
Wow, great catch. I've got a fix in #954.
