### ISSUE TITLE
Show engram count on vendors

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#9476]
It's probably too annoying to try and fish out the string vars for this popup, but we could just show the whole popup from some icon:
![](https://cdn.discordapp.com/attachments/1081323816808108064/1081351497796821162/image.png)

**Comment by robojumper** [comment]
The focusing vendors already show this simply as a resource that's needed to buy some items
![grafik](https://github.com/DestinyItemManager/DIM/assets/14299449/4b218aaf-0fbb-48a8-a0a3-2c995d09b2b9)
maybe we can bubble this up to the respective main vendor

**Comment by bhollis** [comment]
Ooh, interesting. Those come from `DestinyVendorsResponse.currencyLookups` so it should be pretty straightforward.
