### ISSUE TITLE
DIM Constantly Refreshing on Firefox

### ISSUE THREAD

**Issue by huf0001** [DestinyItemManager/DIM#9478]
So yesterday and today, whenever I've gone to DIM in Firefox, it's been stuck in a loop of constantly refreshing the page. As soon as the page loads, it automatically reloads itself again. I've cleared my cache and it hasn't changed anything. However, if I open DIM on Edge, or open the beta version in Firefox, everything is working there.

**Comment by bhollis** [comment]
Have you followed all of our troubleshooting steps?

**Comment by huf0001** [comment]
Hi Ben, I did look into a few of them, but had to go do other stuff before I could get through all of them. However, today when I updated Cold Turkey (an app blocker I use to ensure I stay focused while working from home), that seemed to fix the issue. So I expect it was an issue with their software rather than DIM itself, seeing as I was having the same problem with light.gg and a couple of other websites. Regards, Sam. From: Ben HollisSent: Tuesday, 23 May 2023 1:42 PMTo: DestinyItemManager/DIMCc: huf0001; AuthorSubject: Re: [DestinyItemManager/DIM] DIM Constantly Refreshing on Firefox (Issue #9478) Have you followed all of our troubleshooting steps?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
