### ISSUE TITLE
Shaders not applying 

### ISSUE THREAD

**Issue by Ytreza626** [DestinyItemManager/DIM#9487]
### DIM Version

Version 7.69.0 (released)

### Browser Details

Firefox 113.1.0

### OS Details

Android 12

### Describe the bug

My shader don't applies (sorry for the bad English I'm french). For précision I'm not even on the game
![Screenshot_2023-05-26-12-45-26-935_org mozilla firefox](https://github.com/DestinyItemManager/DIM/assets/134699288/a6a095b7-c3bd-4fbb-a8c2-18c6cd6b9947)

**Comment by robojumper** [comment]
Bungie fixed this today.
