### ISSUE TITLE
Dragging "new" items looks weird

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#949]
Something about the drag and drop preview gets messed up with the SVG overlay

**Comment by ffilll** [comment]
I am seeing the same thing.  I'm using chrome version53.0.2785.116 m (64-bit) and DIM version 3.10.5.416.

I am seeing it when I move engrams from the vault and between characters.

I have tried to show below.


![transfer_image_3](https://cloud.githubusercontent.com/assets/22078854/18715623/f9ad2e1c-7fe7-11e6-94ba-ec3a357371ff.JPG)
![transfer_image_2](https://cloud.githubusercontent.com/assets/22078854/18715625/f9dd1a5a-7fe7-11e6-833a-b1730c5d6136.JPG)
![transfer_image_1](https://cloud.githubusercontent.com/assets/22078854/18715624/f9b81f8e-7fe7-11e6-8d37-fd2a2f8b21c9.JPG)

**Comment by shockthealien** [comment]
yup, happening to me too

**Comment by chrismcenteer** [comment]
Me too. Didn't realize the correlation with new items until this thread though, so at least it's easy to work around.

**Comment by bhollis** [comment]
Fixed in #957.
