### ISSUE TITLE
Some is: filters not working for additional characters and vault

### ISSUE THREAD

**Issue by chrismcenteer** [DestinyItemManager/DIM#950]
Not sure when this issue started, but I noticed today that filtering isn't working correctly in some instances. Elemental filters appear to work fine (is:solar/arc/void) as do specific weapon classes (is:handcannon etc) but overarching classes do not. So if I filter by is:primary it only hides/dims out items on my Titan. The rest of my characters are as normal. As near as I can tell it's any second level category that's not working. Definitely these don't work:

`is:primary`
`is:secondary`
`is:heavy`
`is:helmet`
`is:gauntlet`
`is:chest`
`is:leg`
`is:artifact`
`is:ghost`
`is:consumable`
`is:material`
`is:emblem`
`is:emote`
`is:ship`
`is:vehicle`
`is:horn`
`is:bounties`

I have attached screenshots to demonstrate the issue I am seeing.

Thanks for making DIM, I don't think I could play Destiny without it!

![2016-09-21 04 28 38 pm](https://cloud.githubusercontent.com/assets/482637/18727810/827604be-8018-11e6-88f4-2be59e8d91ba.png)
![2016-09-21 04 28 02 pm](https://cloud.githubusercontent.com/assets/482637/18727809/8274770c-8018-11e6-94c3-ab86e994b53b.png)

**Comment by bhollis** [comment]
Thanks for the report! Turns out this is due to an error that's getting thrown halfway through the search. I've got a PR out to fix it (#952).

**Comment by chrismcenteer** [comment]
Great, will look forward to the fix!
