### ISSUE TITLE
Special Event Infrastructure to Support Messaging to End Users

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#9505]
### Proposed change

Adding support into DIM for metadata-driven events would support our ability to respond quickly to events hosted by Bungie and ourselves. It's often the case that Bungie provides only a few days between announcements and event kickoff. This behavior makes it difficult for developers to deliver updates to the app that match the high bar we set for user experience and the quality of life for the team.

The following elements would support a messaging strategy to deliver content to users with three key pathways:

- Main Navigation Destinations for Events
- In-App Notifications for High-Importance Messaging
- Banner space for Persistent On-Screen Messaging
- Integrated into the Menu's New Content Badge

### How does this fit into your workflow?

N/A

**Comment by bhollis** [comment]
You should look at how the BungieAlerts are done - it should work roughly the same way. We can use the DIM API's global_settings endpoint, but we'll need to add an admin page to set alerts: https://github.com/DestinyItemManager/dim-api/issues/121
