### ISSUE TITLE
Don't equip unattuned iron artifacts

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#951]
From Nigel on Slack:

> Max light will try and equip the new artefacts on characters who have not been to the feltwinters peak to attune it (light the fire). Anyone worked out how to detect this?

**Comment by dustinrue** [comment]
Couple of things.

Attunement is a quest so it might be tied to whether or not that quest has been completed. The items also have an 'unlockFlagHashRequiredToEquip' value that could be useful.

**Comment by delphiactual** [comment]
@ArkahnX, solved this in DestinyLootHistory right around here somewhere https://github.com/ArkahnX/DestinyLootHistory/blob/dev/app/scripts/pages/vendor.js#L137

**Comment by ArkahnX** [comment]
I'm a little rusty on my vendors, but essentially through a combination of `saleItem.item.cannotEquipReason`, `saleItem.itemStatus`, and `saleItem.requiredUnlockFlags` you can find all of the information you should need about whether an item can be purchased.

This information is however limited to items from vendors, and does not show up in your regular inventory (as far as I know)

**Comment by bhollis** [comment]
This isn't about purchaseable, thuogh - it's about equippable after purchase but before attuning.

**Comment by ArkahnX** [comment]
@bhollis, I was pinged since I had an implementation that appeared at a glance to be useful, but it ended up being for vendors, instead of regular items, that's all that was about

**Comment by bhollis** [comment]
Yup, no sweat, just not applicable to this problem.

**Comment by SunburnedGoose** [comment]
I like that quest idea.  Would be interesting to see if that can be explored.

**Comment by bhollis** [comment]
The quest idea is neat, but I don't know how to associate the open quest with the specific item that needs attunement.

I'm going to close this for now but if somebody were able to figure it out, a PR (or a pointer to a strategy) would be appreciated.
