### ISSUE TITLE
Dragging a subclass from inventory into a loadout does not copy settings

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#9519]
I dragged this strand subclass in, and got different config:

<img width="523" alt="Screenshot 2023-06-01 at 10 26 54 AM" src="https://github.com/DestinyItemManager/DIM/assets/313208/9924177c-d9ae-40df-98f8-36ffb7cccf95">

**Comment by robojumper** [comment]
Are you expecting it to copy only the selected abilities or also Aspects and Fragments?

**Comment by bhollis** [comment]
I'd hope it would copy the entire subclass state.

**Comment by robojumper** [comment]
Hmm, right now the item picker for adding a subclass to the loadout (including Loadout Optimizer's) copies abilities but not Aspects/Fragments, so we'd have to decide if this behavior should be consistently applied or if these interactions are meaningfully different enough to justify different behavior.

**Comment by ryan-rushton** [comment]
I personally think the entire thing should be copied too. I have noticed this before and either started work on it or raised an issue (can't quite remember). Been a bit busy lately so haven't got back yet
