### ISSUE TITLE
Apply time auto stat mods

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#9521]
Rather than what we do now, which is to save the result of auto stat mod selection with the list of loadouts, we could instead save *none* of the stat mods, and apply stat mods as needed when the loadout is applied. This takes away the need to ever really think about stat mods since they can just fill in empty spaces in the loadout to get the best stats possible. On the loadout view, we'd show the normal list of stat mods and then a " + Automatic Stat Mods" bit.

**Comment by JAssertz** [comment]
Hey just took a look at this and thought of an idea, what if we took inspiration from d2armorpicker, and after the user has added all mods they want we display the rows of stats with what they have and allow them to allocated stats as they like to see present and at apply time we apply the mods appropriate to reach the requested stats.
