### ISSUE TITLE
Make Loadout class restriction automatic based on contents

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#9535]
Instead of asking users to select "Any Class", we should just auto check it based on what is selected within the loadout.

Only 0.6% of saved loadouts have chosen the "Any Class" option. Instead of having an "Any Class" switch, we should set the class type automatically based on what items are in the loadout. A loadout with nothing class-specific can be implicitly "Any Class".

**Comment by robojumper** [comment]
The main question is whether we want to allow changing the backing store during editing (e.g. create a new loadout from the Warlock dropdown, should we still be able to turn this into a Hunter loadout?) - It'd introduce a few complications:

1. Fashion-only loadouts - we'd have to provide a way for the user to select which class they want to pick ornaments for.
2. Mod-only loadouts - mod unlock status/costs can differ per character. Not sure making ModPicker operate on the union of unlocked mods is what we want.
3. How to deal with sync/fill in/randomize buttons? Which character do they operate from?

Also if the subclass item picker showed all 15 subclasses (3 classes * 5 subclasses/class) it'd be nice to have class type separators like in the vault.

**Comment by bhollis** [comment]
I don't think we want to allow changing the store during editing. The loadout editor is always tied to a specific store.
