### ISSUE TITLE
 advanced stat quality comparison is broken for me

### ISSUE THREAD

**Issue by nki2bpz** [DestinyItemManager/DIM#955]
Idk if it's just me but the stat quality hasn't worked for me in any of the 10+ builds

**Comment by SunburnedGoose** [comment]
What does 'worked' mean?  Need more details.

**Comment by nki2bpz** [comment]
sorry, the percentage quality roll is not displaying on any armor

**Comment by SunburnedGoose** [comment]
Public or Beta client?  Blue logo is Beta, Orange is Public.

**Comment by nki2bpz** [comment]
it displays within the loadout builder but not the DIM main page

**Comment by nki2bpz** [comment]
public

**Comment by SunburnedGoose** [comment]
Oversight.  We've removed it on purpose while we make sure that the new update works well with the formulas to grade items.  I'll make an issue to remove it from Stats.

https://chrome.google.com/webstore/detail/destiny-item-manager/mkiipknpfaacbjdagdeppdacpgpdjklc

Our beta client has stats so you can use that and enable it in the mean time.

**Comment by nki2bpz** [comment]
gotcha, thank you, I didn't mean to waste any ones time, i did search open issues but didn't find anything relevant
