### ISSUE TITLE
Add toggle to hide completed weapons patterns/catalysts and search that shows the progress.

### ISSUE THREAD

**Issue by ferazambuja** [DestinyItemManager/DIM#9553]
### Proposed change

Make the toggle “hide completed triumphs” on the records section hide completed weapons patterns and catalysts. 
Show the more useful weapon pattern/catalyst progress boxes when using the search. 

### How does this fit into your workflow?

With so many craftable weapons available, it has become harder to keep track of the pattern's progress, i.e., which weapon is closer to being craftable, that you might want to prioritize and get it at the end of a Raid. 

Currently, the toggle for “hide completed triumphs” does not hide the complete ones, and with so many weapon kinds is hard to track. 

Using a search term such as `season:current is:craftable` only shows what you completed with a checkmark and not the more useful view with the progress. 
![IMG_1652](https://github.com/DestinyItemManager/DIM/assets/12782082/716250fd-effb-4c02-875a-8a4a16b21941)

**Comment by bhollis** [comment]
It's because these are "Collectibles", not "Triumphs". You should be looking at the "Patterns & Catalysts" section for the pattern progress records. I'd also recommend using https://engram.blue which has a focused pattern progress tool.

**Comment by robojumper** [comment]
You can also add `-is:patternunlocked` to your search query in DIM, that would hide completed patterns too.
