### ISSUE TITLE
Beta (2023-06-12) page doesn’t entirely load.

### ISSUE THREAD

**Issue by thomaskchan** [DestinyItemManager/DIM#9571]
### DIM Version

Not sure what version.  Saw a date ~PM on 2023-06-12 yesterday and also today’s beta release

### Browser Details

Safari/Firefox/Chrome

### OS Details

ipados, mac, windows

### Describe the bug

The page loads but no inventory is displayed.  The inventory/progress/and many other things are missing from the sidebar.  Can’t click on “About DIM” to get version or even “Log out”.  It’s a bit random though as through my testing I occasionally have been able to see the about dim version, where I saw a date from yesterday evening, and a date from this morning.  Wasn’t able to capture the version though.

First discovered this yesterday on iPadOS in Safari.  Tested it in all webkit based browsers there (safari, firefox, chrome).  Normal app.destinyitemmanager.com works.

Tried on other machines (incognito or new profile) on MacOS, Windows using Chrome/Firefox and am running into the same issue.

Sometimes I get the “Profiles for $USER” screen where I can click on D2 or D1 profile, but clicking on either doesn’t register.

![image](https://github.com/DestinyItemManager/DIM/assets/13026069/95f5a1ec-3b6c-4132-a926-762ef0d2993b)

**Comment by higgey123** [comment]
issue is also present on brave

**Comment by thomaskchan** [comment]
Just found that I had another beta DIM tab open in Chrome that still is open to inventory.  I can click on gear and whatnot, but can't click on sidebar (inventory->Organizer, About, What's New) or topbar links.  Some of the sidebar links do work (Keyboard Shortcuts, User Guide, Install as an App, Report a Bug).

**Comment by robojumper** [comment]
Should be fixed with #9572.
