### ISSUE TITLE
Show items matching the current filter that are re-acquirable via collections in the main 'Inventory' tab

### ISSUE THREAD

**Issue by Makeshift** [DestinyItemManager/DIM#9577]
### Proposed change

When filtering in the main 'Inventory' tab, add a section that shows items re-acquirable from collections that match the current filter.

### How does this fit into your workflow?

I often use DIM to search for weapons that match particular requirements, but I'd also like to be able to dismantle items in my vault that are simply re-acquirable via collections.

Adding a section (perhaps at the bottom, below shaders?) that includes weapons that match a given filter on the primary inventory tab would really help for allowing vaults to be cleaner, while also showing when you can simply grab a new copy of an item from collections rather than keep it around.

Showing every item available from collections on the main Inventory tab would be _far_ too many, but only rendering the section when filtering wouldn't be overwhelming.

Random addition: I see from an old reddit thread that `is:reacquirable` used to be a filter? Is that not a thing anymore?

**Comment by bhollis** [comment]
We used to have an is:reacquireable search but removed it because we cannot reliably determine when and how an item is reacquireable. These types of items are rarely available these days as well.

**Comment by Makeshift** [comment]
> We used to have an is:reacquireable search but removed it because we cannot reliably determine when and how an item is reacquireable. These types of items are rarely available these days as well.

Ah, that makes sense, fair enough.
