### ISSUE TITLE
Stream Deck alert covers loadouts

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#9586]
### DIM Version

Current beta

### Browser Details

Chrome

### OS Details

Windows 11

### Describe the bug

I have a portrait display with DIM on it 1440x2560.

If you have more than 5 in-game loadouts, and you try and send one to the Stream Deck, the alert asking to choose the loadout covers the the loadouts 6+ and you can't select them.

![image](https://github.com/DestinyItemManager/DIM/assets/25425159/c3fcb4da-33ce-4bcb-a41a-f0f498e73a43)

The only workaround I've found is to find the loadout you want to send to the Stream Deck, select loadout details so it appears at the bottom of the screen, then transfer it as the "Send to Stream Deck" is now able to be clicked in the fly-out at the bottom.

This only became a problem when the in-game loadouts were moved to the top of the screen.

I suggest reflowing the in-game loadouts so there are two rows of 5.

**Comment by robojumper** [comment]
cc @fcannizzaro

**Comment by fcannizzaro** [comment]
I'll fix it later

**Comment by bhollis** [comment]
I think you can also just click on the notification to hide it

**Comment by philkernick** [comment]
That doesn't work.  If you click the notification to hide it, the "Send to Streamdeck" button disappears from the loadout detail.  Specifically the send to streamdeck button only appears when the notification is visible.

**Comment by philkernick** [comment]
The new version of the streamdeck plugin uses drag and rop to assign loadouts, so this is no longer an issue.
