### ISSUE TITLE
Enhancement: Filter by Content Source / Expansion

### ISSUE THREAD

**Issue by m-s-y** [DestinyItemManager/DIM#96]
Enable functionality to filter by item source.  For example:

is:houseofwolves
is:vaultofglass
is:crotasend
is:ironbanner
is:eris

**Comment by SunburnedGoose** [comment]
I need to find out where that data is stored.  I could make it, but would
rather have a curated list.  Eutral?  Do you know of any lists?

**Comment by kyleshay** [comment]
it would have to be manually curated. we could re-use the list from our collections file that has this information already (which we use for the destinyexotics integration/collection view)
