### ISSUE TITLE
Feature Request: Send Uncommon and Rare Items to Vault

### ISSUE THREAD

**Issue by LongLiveCHIEF** [DestinyItemManager/DIM#960]
With the changes dropped with RoI, green engrams/items are becoming a nuisance.  I used to be able to carry 6 or 7 options in each armor/weapon slot, and still be able to farm. Now, with greens dropping constantly, they fill up my slots easily, and in a tight firefight, I'm missing out on great farm of XP/Armor Dust/Weapon Parts.

Since we farm greens much the same way we used to only do for blues, it makes sense to me that we could have a feature which auto-sends `uncommon` items to vault, just like we do for blue engrams.

This would be helpful if we could just have a "Send to Vault" service with a dropdown of options you can check:
- [ ] engrams
- [ ] uncommons
- [ ] rare

For more information about the "problem" description, view this Reddit Post: [Can we get an artifct which automaticaly dismantles greens which we pick up](https://www.reddit.com/r/DestinyTheGame/comments/543h3u/can_we_get_an_artifact_which_automatically/). I know that DIM can't dismantle, but sending greens to the vault _would_ solve the problem we're having managing inventory due to an overabundance of green engrams dropping in-game now.

**Comment by bhollis** [comment]
The engrams to vault feature sends all engrams to the vault today,
regardless of rarity.

**Comment by LongLiveCHIEF** [comment]
My apologies, I meant to say _items_ (those engrams which come into your inventory decrypted).

The rest of the post was worded correctly, but I updated the title.

**Comment by bhollis** [comment]
I think this is covered by farming mode today with the feature to keep greens on a character for dismantling.
