### ISSUE TITLE
Update or remove docs/PRIVACY.md

### ISSUE THREAD

**Issue by robojumper** [DestinyItemManager/DIM#9606]
https://github.com/DestinyItemManager/DIM/blob/master/docs/PRIVACY.md is woefully out of date -- DIM is not contacting DTR anymore, and it's missing all the actual ways in which user data is stored or submitted to Sync servers and Google Analytics. https://github.com/DestinyItemManager/DIM/blob/master/src/app/shell/Privacy.tsx has all that info already.

**Comment by bhollis** [comment]
Oh weird, I didn't even realize that was there. Best to just delete it.
