### ISSUE TITLE
Ability to REMOVE or DISABLE the "Collect Postmaster" button.

### ISSUE THREAD

**Issue by ShojiC** [DestinyItemManager/DIM#9608]
### Proposed change

D2 is severely lacking in vault space and we often depend on Postmaster to store items.  And it's happened to me repeatedly where somehow, my mouse ends up clicking on or tapping on the "Collect Postmaster" button somewhere and now I have all characters full and 600/600 in the vault because DIM pulled down everything from the Postmaster. 

It would be ultra fantastic if we had the option to have that button never exist, removed entirely, disabled, not even there, etc.  It's really just a button click from making the game even more unplayable than it already is with the utter lack of vault space.  I seriously doubt Bungie will ever increase vault space either as their good devs are all on Marathon.

Thank you for the best tool for D2 though.  The game is 100% unplayable without you!

### How does this fit into your workflow?

I try not to ever never click this button.  Because once it's clicked, I have to devote my evening to undo the destruction it has caused.  Please allow the option to remove/disable this button forever.

**Comment by robojumper** [comment]
Try visiting the Settings page and toggling the setting that does exactly that.
