### ISSUE TITLE
Armor Elemental tags

### ISSUE THREAD

**Issue by SentryTheDefiant** [DestinyItemManager/DIM#961]
Might be really useful to have elemental type tags on armor or artifacts so you can quickly grab ones that match the subclass you want to use. 

Not sure on the best way to handle armor with split types like resistance to arc splash type, but better armor when using a solar class, but things like boots or artifacts, that would be less of an issue. 

All in all, it would just allow for some disambiguation on items of the same name with different perks

**Comment by kyleshay** [comment]
until we have something like that in there, the search/filter box support searching through perks on items. for example: `arc` will return any chest armor that has armor with arc burn.

**Comment by bhollis** [comment]
Closing - I think search is good for this.
