### ISSUE TITLE
Themes?

### ISSUE THREAD

**Issue by dallasbpeters** [DestinyItemManager/DIM#963]
Would you be interested in themes? I'd be happy to code some up if you thought it might be a good idea.

**Comment by kyleshay** [comment]
Hey there! Themes would be really cool. If you want, we already did have a theme for the Crimson Doubles event.

A Trials of Osiris theme and Iron Banner theme would be really neat!

There are also parts of our app that could still use some UI/UX elbow grease.

Did you have anything specific in mind?

**Comment by bhollis** [comment]
+1 to Trials and Iron Banner! We could detect the vendor availability (well, when that API comes back) and automatically apply them, if they weren't too shocking.

**Comment by kyleshay** [comment]
Yeah, a subtle nod to in-game events would be even helpful for people who may not have realized they were active. Would be pretty cool!

**Comment by JakeWhitaker** [comment]
http://imgur.com/a/HXEfu

**Comment by cotto** [comment]
I like the idea but please make sure that they can be disabled in a way that's easy to discover.

**Comment by chuckreynolds** [comment]
yeah the idea is good but having multiple colored page background is not anything i'd enjoy looking at. i'd be cool with just the header(s) getting a seasonal makeover, but having the option to disable should obviously be there too.

**Comment by JakeWhitaker** [comment]
So more like the final iron banner one with just the header? What if the backgrounds were less vibrant? I assume the themes would be toggle-able regardless of which they did.

**Comment by chrisfried** [comment]
+1 IB and Trials themes
-1 loud background images

Here's what the Crimson Days theme looked like: https://twitter.com/ThisIsDIM/status/695639995252609025

A change to the color palette, plus falling rose petals. Were I to do that one again, I'd probably darken that background red further...

**Comment by chuckreynolds** [comment]
yeah that's what I mean w/ the background... that solid color with minimal effect adds is just fine; those loud / multi-colored bg's tho.. nope. 

that said we should be able to limit 'themes' down to:
- a header bg image (png,gif) (either full width image or a square repeating pattern)
- page background hex color

anything additional like the rose petal image and any javascript needed for it would be added to the package.
But I think just having a simple "include these two things" makes it easy to submit themes and keep it easy on the scope

**Comment by chrisfried** [comment]
> page background hex color

A few more colors need manipulating to make things look nice, but I'm with you in spirit.

**Comment by chuckreynolds** [comment]
hah. right. but you get it. thx :)

**Comment by bhollis** [comment]
Themes remain a cool idea. Please open a PR or issue for specific theme ideas!
