### ISSUE TITLE
'Undo' action overlays cannot be cancelled and take too long to disappear

### ISSUE THREAD

**Issue by Oozlum** [DestinyItemManager/DIM#9645]
### DIM Version

7.77.3 (release) and 7.77.3.1002730 (beta)

### Browser Details

iOS and Safari 16.5.2

### OS Details

iOS 17.0 and Mac OS 13.4.1

### Describe the bug

I use the Organiser to select and tag multiple items at once.  Each time I apply a tag a pop-up appears 'Tagged X selected items as junk' which takes about 30s to disappear; every bulk tag action adds another pop-up to the screen.  These pop-ups cannot be cancelled and cover other UI elements, making the app unusable until they have all disappeared after a few minutes.

Can we please have an option to disable these entirely, close the pop-ups or drastically reduce the timer?

**Comment by robojumper** [comment]
Try simply clicking the notification (outside of the "Undo" button) to dismiss it.

**Comment by Oozlum** [comment]
Thanks, I didn't notice that.  I was expecting the usual 'X' button or something.

It would still be nice if I could disable it entirely.  I can't see any real value in it -- it doesn't really tell you anything and all selected items remain selected anyway.

**Comment by robojumper** [comment]
* We have hotkeys to tag items, and the same hotkey tags an individual item (when a popup is open) or all selected items (in Organizer without a popup open).  Getting a notification + undo functionality is useful if you accidentally do a bulk tag.
* Even if the items remain selected, they may have had different tags, so undoing a bulk tagging action is not easily doable. The undo functionality is useful for that.
