### ISSUE TITLE
Select Y2 armor & Ghotst not showing quality stats

### ISSUE THREAD

**Issue by ignishen** [DestinyItemManager/DIM#966]
<img width="290" alt="screen shot 2016-09-26 at 9 53 23 am" src="https://cloud.githubusercontent.com/assets/22451448/18839050/3806a298-83cf-11e6-8d13-10e8d270d162.png">
<img width="285" alt="screen shot 2016-09-26 at 9 53 30 am" src="https://cloud.githubusercontent.com/assets/22451448/18839053/3a20e94e-83cf-11e6-94c2-91fb878b1e83.png">

**Comment by wein3967** [comment]
This is a known issue for IB ghosts and ToO gear. It is a Bungie API issue. #889
