### ISSUE TITLE
Flat Styling Tweaks [Feedback Wanted]

### ISSUE THREAD

**Issue by chrisburgin95** [DestinyItemManager/DIM#968]
Started some initial very simple flat styling work on a fork and just wanted to get some feedback. May or may not be useful but feedback is very welcome. Many of the changes are very simple and just attempting to polish some corners.

![screen shot 2016-09-27 at 12 02 41 am](https://cloud.githubusercontent.com/assets/1278846/18859964/d85bc8d2-8446-11e6-83ae-ae2352be53f0.png)
I would click to enlarge the above photo. The small size makes it hard to see divider lines between the collapsable rows. 

![screen shot 2016-09-27 at 12 09 40 am](https://cloud.githubusercontent.com/assets/1278846/18859963/d85b7616-8446-11e6-8e77-dd8f11115a23.png)
![screen shot 2016-09-27 at 12 01 58 am](https://cloud.githubusercontent.com/assets/1278846/18859966/d85c77c8-8446-11e6-98b5-ee08e6b3d5fd.png)
Modals slide out from the side.

![screen shot 2016-09-27 at 12 01 41 am](https://cloud.githubusercontent.com/assets/1278846/18859965/d85c0d88-8446-11e6-8211-c9c171495fd9.png)

**Comment by kyleshay** [comment]
sorry we haven't gotten back to you yet. looks great!! we do need some of those tweaks. could you create a pull request so it's easier to comment on and so we can try it out locally?

**Comment by chrisburgin95** [comment]
No worries! Ill find time to double check my changes first and create a pull request tomorrow hopefully.

**Comment by delphiactual** [comment]
See #1488
