### ISSUE TITLE
[Feature Request] Missing Weapon Types for Element Type

### ISSUE THREAD

**Issue by DCForever** [DestinyItemManager/DIM#9682]
### Proposed change

In Organizer, show for each archetype if there are missing element converage.

### How does this fit into your workflow?

A lot of times because of bounties or loadout needs, you want to have at least 1 of every element for each type of weapon.

It would be useful to know somehow that you are missing say a Strand Handcannon just at a glance. An enhancement could be that it notifies you that you could craft one for instance.

When trying to maximize bounties or season challenges or building a loadout, I want to get items that help complete them as fast as possible. However, I may be missing a Strand Sword or a Void Shotgun so I can't complete those as fast as possible.

**Comment by robojumper** [comment]
This is similar to #7790, I think.

**Comment by DCForever** [comment]
@robojumper Yes, it is very similar. I can close this in favor of that one.
