### ISSUE TITLE
[Feature Request] Loadouts - Top Level Weapon Search Restriction

### ISSUE THREAD

**Issue by DCForever** [DestinyItemManager/DIM#9683]
### Proposed change

In Loadouts, when choosing the weapons, have the ability to enter search that will be done first before viewing the weapon selection.

### How does this fit into your workflow?

Making a loadout for Arc Surges in Legendary Lost Sector or GMs for instance, I try to only pick Arc weapons, but have to add it to the search each time. Similarly, I am often looking for only weapons that are either seasonal or intrinsic champion handling.

This would be a little pain point solver.

**Comment by rjmagley** [comment]
So when you have the loadout screen open currently, if you click the Energy Weapons icon, you then get a list of Energy weapons in your inventory. Is the idea that before that step there'd be a search box where you can maybe type something like "is:arc" to have it pre-filtered to that element of weapons, and then if you also wanted an Arc heavy that search term would already be present to pre-filter the heavy selections?

**Comment by DCForever** [comment]
Yes, exactly. A pre-filter applied so that when I am selecting weapons. I only get the ones I am mostly interested in. 
As you can see here, I make a loadout to easily get the stasis weapons that would be useful for this season's artifact.
![image](https://github.com/DestinyItemManager/DIM/assets/1433817/2b3565b5-7f2d-4581-8560-f0bb9a4cb292)

**Comment by DCForever** [comment]
To start, perhaps just an Element Restrict selector like the Tag Selector is.

**Comment by bhollis** [comment]
I'm not sure what you mean?

**Comment by DCForever** [comment]
![image](https://github.com/DestinyItemManager/DIM/assets/1433817/802ac6c3-5415-4f8b-9f70-23e0e7a6f084)

Instead of Tags, just element icons
