### ISSUE TITLE
Quality stat display issues

### ISSUE THREAD

**Issue by geck0s** [DestinyItemManager/DIM#969]
This looks like an issue with the rounding formulas used where a single stat item can get two different percentages:

![image](https://cloud.githubusercontent.com/assets/12294244/18870734/12787aae-8480-11e6-8e74-36f65280edd4.png)

Averaging 82% with itself and getting 83% is a bit curious.

**Comment by delphiactual** [comment]
Memory of Felwinter causes weird bar display issues due to stats...

![screenshot 2016-09-27 05 26 11](https://cloud.githubusercontent.com/assets/4798491/18871562/2643fda4-8473-11e6-9063-291f94cbb394.png)

**Comment by bhollis** [comment]
Looks like the max for that stat us bugged in the Bungie data

**Comment by delphiactual** [comment]
Something is pushing the discipline green compare line down, when stats are too large.

![screenshot 2016-10-05 23 52 58](https://cloud.githubusercontent.com/assets/4798491/19141963/0492ded8-8b57-11e6-957a-a85bc9600f16.png)

**Comment by delphiactual** [comment]
It looks like no armor items are returning max for any stat from the API.

**Comment by kyleshay** [comment]
please re-open if it's still an issue.
