### ISSUE TITLE
Make MSTDN column a bit wider in "What's new" tab

### ISSUE THREAD

**Issue by Prometheus3375** [DestinyItemManager/DIM#9690]
### DIM Version

Version 7.78.0 (release), built on 24.07.2023, 05:09:36

### Browser Details

Chrome 115.0.0.0

### OS Details

Windows 10 Pro 21H1, 19044.1645

### Describe the bug

Currently, MSTDN column is not wide enough, forcing `s` to be on a separate line.

![image](https://github.com/DestinyItemManager/DIM/assets/35541026/c5d09cbc-6563-48f9-9e02-b65218c1892b)

Making DIM window wider does not help. Only shrinking it forces MSTDN to appear o the top, eliminating the issue.

https://github.com/DestinyItemManager/DIM/assets/35541026/cc5c5039-d851-4e73-a3b8-6ef6a9660d15

**Comment by bhollis** [comment]
You wouldn't by chance have your text zoom set larger?

<img width="934" alt="Screenshot 2023-07-30 at 4 58 03 PM" src="https://github.com/DestinyItemManager/DIM/assets/313208/2ebbf270-389d-45fa-828c-2cc77a0e5c34">

**Comment by Prometheus3375** [comment]
Windows setting for scaling is 100%, i.e., no changes to text or other elements. My resolution is 1920x1080.

This is the page with 125% scaling done.

![image](https://github.com/DestinyItemManager/DIM/assets/35541026/bcde884c-0509-4033-bdc7-45dbf78e370b)

Check your settings too. Windows settings -> System -> Display -> Scaling (right after Windows HD Color).

**Comment by Prometheus3375** [comment]
This is with Windows Scaling set to 125%.

![image](https://github.com/DestinyItemManager/DIM/assets/35541026/d434dc08-bcf6-43f5-a19e-4009592de5e8)

**Comment by bhollis** [comment]
I'm on macOS, perhaps that's the difference.

**Comment by bhollis** [comment]
I've tweaked the font size so it should match the rest of the page a bit better.

**Comment by Prometheus3375** [comment]
Yep, I see this in beta. Thanks! ❤️ 

![image](https://github.com/DestinyItemManager/DIM/assets/35541026/3d302cce-c615-40d7-9db4-7f401d5746bb)
