### ISSUE TITLE
Indicate capped materials on the material counts sheet

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#9691]
It could be nice to highlight globally-capped material counts on this sheet:

<img width="474" alt="Screenshot 2023-07-30 at 4 55 22 PM" src="https://github.com/DestinyItemManager/DIM/assets/313208/4519c3ad-63c2-4461-bff7-263fabc4afa3">

**Comment by robojumper** [comment]
What's the cap for materials that can go to the postmaster, e.g Spoils of Conquest with 240 per stack? 240, or 240*(numCharacters+1), or 240*4?

**Comment by bhollis** [comment]
Given we don't want to encourage postmaster hoarding I'd say 240?
