### ISSUE TITLE
Link anchors in loadout/notes are turned into hashtags

### ISSUE THREAD

**Issue by robojumper** [DestinyItemManager/DIM#9693]
![screenshot](https://cdn.discordapp.com/attachments/333464468241514497/1135222604899287123/image.png)

xyz#tag resulting in a `#tag` hashtag is intentional behavior according to tests

https://github.com/DestinyItemManager/DIM/blob/ea5d6d1c2076df21ace2b0f0c3527c7c93d6aa21/src/app/inventory/notes-hashtags.test.ts#L12

**Comment by bhollis** [comment]
It's not so much intentional as much as documented - when I wrote the tests I was just showing the current behavior without changing the implementation. But also @Gix3612 made a lot of changes to how hashtags are discovered and may have some reason to not require whitespace before tags.

**Comment by Gix3612** [comment]
I wouldn't say a lot, but, I probably was the last person to touch it. I don't think it would cause any problems to make it require a whitespace in-front.
