### ISSUE TITLE
Infusion Fuel Finder bugs

### ISSUE THREAD

**Issue by geck0s** [DestinyItemManager/DIM#970]
I noticed there is a bug with the infusion fuel finder displaying the wrong icon on the bottom row.  It always seems to show the last unlocked infusion fuel item's icon instead of the one I have clicked on.  This can be seen in the screenshots below from DIM Version 3.10.6

Of a bit less importance, the tool is still only filtering based on light level which allows it to think year1 items can be used as fuel.  I can link screenshots in game to show that y1 gear is not shown on the list of possible infusion fuel in game if someone wants:

![image](https://cloud.githubusercontent.com/assets/12294244/18871413/49d9e3b8-8483-11e6-97af-3f9079225566.png)

Note that this may be exceedingly rare as I'm not sure there are too many other y2 or y3 legendaries that can be obtained below 170 light.  I'll leave it to others to decide if the issue with advising using y1 stuff as infusion fuel even merits fixing since it is such a rare edge case.

While the iron gjallarhorn at 3 light does the same thing, if checking infusion fuel while it sits at the postmaster, the locked items check box has no effect.  The currently unlocked y1 SGA is listed as infusion fuel but none of the locked heavies of any year are displayed in this case:

![image](https://cloud.githubusercontent.com/assets/12294244/18871730/c0090dec-8484-11e6-9423-e74832907478.png)

**Comment by bhollis** [comment]
Fixed in #995. Thanks!
