### ISSUE TITLE
Armor spikiness metric

### ISSUE THREAD

**Issue by Revadike** [DestinyItemManager/DIM#9700]
### Proposed change

Since the ability for multiple custom scores does not exist, how about a more generic metric? It could replace the custom stat. It will meassure spikiness by calculating the variance between each stat.

### How does this fit into your workflow?

The more spikey, the better

**Comment by robojumper** [comment]
A fun approximation are the `basestatvalue:<nth>highest:<6` variants. E.g.

* `basestatvalue:thirdhighest:<6` matches armor with four very low stats (=two spikes)
* `basestatvalue:fourthhighest:<6` matches armor with three very low stats (=one spike and either another spike or a stat split into two)
* `basestatvalue:fifthhighest:<6` matches armor with two very low stats (...)

**Comment by Revadike** [comment]
The following is a pretty good alternative for this:
`basestat:any:>=29`
