### ISSUE TITLE
styling fix needed: vendor(/collections?) item popup ownership messages

### ISSUE THREAD

**Issue by nev-r** [DestinyItemManager/DIM#9702]
aspect ratio needs fixing and rounding shouldn't be there

![image](https://github.com/DestinyItemManager/DIM/assets/68782081/ab80b12f-ea64-49e6-a7f2-3aab30902202)

**Comment by bhollis** [comment]
The one place I can still find this is in the subclass unlock sub-vendors (Ikora, Pouka Pond, etc). Definitely still busted.
