### ISSUE TITLE
LO: Regression in mod/intrinsic styles

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#9706]
@nev-r noticed a regression in the borders of mods, including newly-appearing borders on intrinsic perks, in the Loadout Optimizer. Suspect PR is https://github.com/DestinyItemManager/DIM/pull/9699 @guise.

Beta:
<img width="672" alt="Screenshot 2023-08-08 at 1 07 29 PM" src="https://github.com/DestinyItemManager/DIM/assets/313208/47677904-5532-4273-b5cc-b6c4ab588f96">

App:
<img width="667" alt="Screenshot 2023-08-08 at 1 07 25 PM" src="https://github.com/DestinyItemManager/DIM/assets/313208/8ac11dd6-cb3e-4ffe-b8bc-4319c6abd831">

**Comment by guise** [comment]
Aah looks like an unnecessary change in #9662 - will remove
