### ISSUE TITLE
Add filter for items that cannot be transferred via the API

### ISSUE THREAD

**Issue by geck0s** [DestinyItemManager/DIM#971]
Items such as SIVA Offerings or Treasure Keys will say "Items of this type can only be transferred in-game. I know, we're bummed about it too."

Can we have a filter for those items so I can filter to them and quickly survey how many I have on each character and/or in the vault and transfer them manually when I'm in a social space?

**Comment by kyleshay** [comment]
It would need to be manually curated list. If we had those id's we'd just disable the possibility of them being able to be transferred in the first place.

**Comment by geck0s** [comment]
Yeah, that would be beneficial, but I'd also like to be able to directly filter them as a user to aid in decision making when I'm already at the vault and it's convenient to do so.

I'll start by making a list of the IDs and maybe I can try implementing something after that.

**Comment by geck0s** [comment]
So, have I got this right?

The IDs would be like the number 142694124 in the link from the Treasure Key: http://db.destinytracker.com/inventory/item/142694124#

**Comment by bhollis** [comment]
Yeah. That's the hash, so you could use that to check.

**Comment by delphiactual** [comment]
Actually you can check the following property of the item `allowActions` if it is false it can not be moved with the api
