### ISSUE TITLE
Issue: Beta Version Unusable Compared to Release Version

### ISSUE THREAD

**Issue by RomaBureacov** [DestinyItemManager/DIM#9712]
### DIM Version

Version 7.80.0.1002790 (beta), built on 8/12/2023, 12:10:24 PM

### Browser Details

Chrome 115.0.0.0

### OS Details

Windows 11

### Describe the bug

In short: DIM beta is immensely slow compared to the stable version. I have noticed it's been like this been so for a few months. Cursor takes a few seconds to recognize it's over an icon, and clicking on a weapon also takes a few seconds. Click+drag is practically impossible. It's basically unusable.

It's so slow, in fact, that the web page returns an out of memory error after some amount of time (around less than an hour).

The stable branch of DIM (Version 7.80.0 (release), built on 8/6/2023, 7:04:39 PM) works perfectly as expected. No memory issues or anything else.

Some more details on the system:
15-20% CPU usage (i7-9750H)
14-15 GB of memory usage (40 GB total; I tend to have a handful of chrome tabs open at any point in time)

I use DIM on an external machine (I play D2 on console, and use DIM on my laptop). I also use DIM through the Chrome application rather than through the browser, but observe the same behavior in both the browser and in the Chrome application. I also have a lot of items (around 599/600) in the vault at all times.

**Comment by bhollis** [comment]
You wouldn't happen to have the Clarity extension installed on beta, would you?

**Comment by RomaBureacov** [comment]
> You wouldn't happen to have the Clarity extension installed on beta, would you?

I do indeed have the Clarity extension for both. Is it an issue with some beta feature and Clarity?

**Comment by bhollis** [comment]
Yes, Clarity has had major bugs that waste resources and slow down DIM, and it is no longer being developed by its authors. Please uninstall it.

**Comment by RomaBureacov** [comment]
Ah ok, that's a shame.

I guess when the release version gets slow due to updates and Clarity not being upheld I'll get rid of it, it's just the beta that's been having trouble lately; release has been running nominal.

Good to know the specific cause.

**Comment by bhollis** [comment]
I didn't think Clarity even worked on the release version.

**Comment by RomaBureacov** [comment]
hmm, must have been my imagination then.
