### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by Veinhtah** [DestinyItemManager/DIM#9715]
### DIM Version

Version 7.81.0.1002793 (beta), built on 15/08/2023 18:43:18

### Browser Details

Opera 100.0.4815.82

### OS Details

Windows 10

### Describe the bug

Huge usage of memory ending to out of memory error

### Logs

```shell
A lot of :

Something then wrong with auth => user_info

End of error logs for => user_info
```

**Comment by robojumper** [comment]
As discussed on Discord, this is caused by the Clarity browser extension. Our [Troubleshooting](https://github.com/DestinyItemManager/DIM/wiki/Troubleshooting) page already mentions this:

> 7. If you've installed an extension such as **Clarity**, disable it.
