### ISSUE TITLE
Error Null 

### ISSUE THREAD

**Issue by popematic** [DestinyItemManager/DIM#9716]
### DIM Version

7.81.0 Relase

### Browser Details

Chrome

### OS Details

Windows 10

### Describe the bug

Beta DIM loads the inventory and Dim doesn't load says Null error

**Comment by robojumper** [comment]
Unfortunately not much to go off -- can you open the browser console (Ctrl+Shift+I or Ctrl+Shift+J), reload DIM, and post any messages in this issue?

**Comment by popematic** [comment]
> Unfortunately not much to go off -- can you open the browser console (Ctrl+Shift+I or Ctrl+Shift+J), reload DIM, and post any messages in this issue?

I attached a screenshot, as well as copy Pasted what I think are the issue messages 

![Untitled](https://github.com/DestinyItemManager/DIM/assets/142440166/5ef8800d-4e40-48b9-a6e1-5931fb8b7b7e)


An aria-labelledby attribute doesn't match any element id


An aria-labelledby attribute doesn't match any element id. This might prevent the browser from correctly autofilling the form and accessibility tools from working correctly.
To fix this issue, make sure that aria-labelledby is a space-separated list of element ids.
AFFECTED RESOURCES
2 resources
                      Violating node
                       Violating node

Page layout may be unexpected due to Quirks Mode

One or more documents in this page is in Quirks Mode, which will render the affected document(s) with quirks incompatible with the current HTML and CSS specifications.
Quirks Mode exists mostly due to historical reasons. If this is not intentional, you can add or modify the DOCTYPE to be `<!DOCTYPE html>` to render the page in No Quirks Mode.
AFFECTED RESOURCES
1 element
Document in the Dom tree Mode URL


Document
Quirks Mode
https://www.mastofeed.com/apiv2/feed?
userurl=https%3A%2F%2Fmstdn.games%2Fusers%2FThisIsDIM&theme=dark&size=100&header=false&replies=false&boosts=true

**Comment by robojumper** [comment]
We investigated another instance of this issue in Discord and nailed down the source of the `null` as this line

https://github.com/DestinyItemManager/DIM/blob/227095e4dd8bd6c2918861137c30ac8a6c100d43/src/app/storage/idb-keyval.ts#L48

where idb-keyval gets its transaction aborted for some reason and `transaction.error` is `null`, which we throw, catch, and store in redux. The catch-all Sentry issue for `null` in loadStores is [DIM-VX1](https://destiny-item-manager.sentry.io/issues/2227362286/).

Some more discussion of this phenomenon is at jakearchibald/idb-keyval#163 and jakearchibald/idb-keyval#164.

Clearing cookies and site data, or deleting IndexedDB in the dev tools, then reloading DIM should fix this temporarily until the browser's IDB breaks the next time.

**Comment by bhollis** [comment]
Seems we could fix the immediate problem with the fix from https://github.com/jakearchibald/idb-keyval/pull/164 and some try/catch, but I don't know how to recover from that state, and it would be bad if a bunch of people had non-functional IDB and were always loading from remote calls.

**Comment by robojumper** [comment]
We could also add some `get` calls to our IDB test and hope that this just causes the StorageBroken page to appear at app launch when `get` would fail later too anyway. Being unable to load anything from IDB ought to qualify as "broken storage" the same way being unable to `set`...
