### ISSUE TITLE
Osteo Striga (crafted) catalyst showing in "catalyst:incomplete" search results

### ISSUE THREAD

**Issue by diabWH3** [DestinyItemManager/DIM#9724]
### DIM Version

Version 7.81.0 (release), built on 8/13/2023, 6:50:13 PM

### Browser Details

Chrome 115.0.0.0

### OS Details

Windows 10

### Describe the bug

In my inventory, I search `catalyst:incomplete` and my crafted Osteo Striga, with its fully completed and applied catalyst, shows in the search results.
![2023-08-17 22_50_50-DIM - Inventory](https://github.com/DestinyItemManager/DIM/assets/49632769/28023aba-be1f-4816-beee-e30daf9ee399)

**Comment by robojumper** [comment]
DIM goes by your in-game triumph that tracks the Osteo Striga catalyst, and that one is incomplete. Try reshaping the weapon once without changes perhaps? But this is in part a game bug...
