### ISSUE TITLE
Green Items with no nodes have gold border

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#973]
This could be argued as expected behavior, just thought I would point it out

**Comment by bhollis** [comment]
Hmm I'll take a look. That shouldn't be happening.

**Comment by delphiactual** [comment]
Example:
![screenshot 2016-09-28 20 49 11](https://cloud.githubusercontent.com/assets/4798491/18939390/34ac4dba-85bd-11e6-899a-dd0b72a343ae.png)
