### ISSUE TITLE
Add "is:collectible" filter for items that can be collected in collection.

### ISSUE THREAD

**Issue by M7ilan** [DestinyItemManager/DIM#9731]
### Proposed change

Add a new filter that allows users to filter items that can be collected in the collection.

### How does this fit into your workflow?

This would be useful for players who want to delete items that they can get back from the collection, such as 1600 power items.

**Comment by robojumper** [comment]
Closing as discussed on Discord and per FAQ https://github.com/DestinyItemManager/DIM/wiki/FAQ#is-there-a-search-term-that-can-show-items-that-can-be-reacquired-as-is-from-collections -- we can't do "can be reacquired" reliably and the potential for damage from a false positive is too high.
