### ISSUE TITLE
Unable to sign in with Xbox live

### ISSUE THREAD

**Issue by WelshMcSpicy** [DestinyItemManager/DIM#9734]
### DIM Version

7.81.0 orange

### Browser Details

Chrome for iPhone and iPad

### OS Details

iPadOS 17.0 (21A5291j)

### Describe the bug

DIM asked me to sign in again. During the sign-in process, Microsoft’s 2FA sent a code to my mobile phone. I entered that, then DIM said:
Error authorizing DIM: We expected the state parameter to match what we stored, but it didn't. This might be a problem with DIM, or it might be an issue with Bungie.net or your browser.

Please follow our [Troubleshooting Guide](https://github.com/DestinyItemManager/DIM/wiki/Troubleshooting) to find a solution, and contact us if those steps don't work.

[Go back to DIM and try again](https://app.destinyitemmanager.com/)
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) DIM AppStore 7

**Comment by bhollis** [comment]
It looks like you got bounced to the app store version of DIM. If you want to use that version, make sure to sign in from there. Otherwise, make sure to uninstall the app if you want to sign in through Chrome or Safari.
