### ISSUE TITLE
WEAPON NOT SHOW IN INVOTORY

### ISSUE THREAD

**Issue by iifaress** [DestinyItemManager/DIM#9739]
### DIM Version

LAST VIRION DIM

### Browser Details

GOOGLE CHROM 

### OS Details

WIDOS 10

### Describe the bug

WEAPON NOT SHOW IN INVENTORY

### Logs

```shell
WEAPON NOT SHOW IN INVENTORY
```

**Comment by robojumper** [comment]
Your post is somewhat light on details but it seems like you collapsed your weapons section -- try clicking it to expand it and show your weapons again

![grafik](https://github.com/DestinyItemManager/DIM/assets/14299449/2579e409-f3aa-4c57-a69c-1f9bfb484ce1)
