### ISSUE TITLE
Felwinter is breaking Loadout Builder

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#974]
The massive stats are causing it to show up in so many builds.  Thoughts on how we can remediate this behavior?

**Comment by delphiactual** [comment]
Add checkbox `Exclude Felwinter`

**Comment by SunburnedGoose** [comment]
Checkbox "Include Felwinter" :)

**Comment by kyleshay** [comment]
even today you can click to exclude items in the loadout builder (shift + click the item)

**Comment by SunburnedGoose** [comment]
We're gonna need a FAQ on that page.

**Comment by SunburnedGoose** [comment]
I do recall this discussion because I objected to the use of modifier keys for these features.  Affects tablet users.

**Comment by kyleshay** [comment]
FAQ is in the 'Need Help?' tab

Agreed there may be a better way to do that stuff. Some discussion about it in #902

**Comment by ericnelson0** [comment]
Maybe we need a notification for doing things in the loadout builder like we have for the first time to let users know you can drag/drop items.

Should we also add the checkbox? I think it'd be annoying to always have this show up first.

**Comment by kyleshay** [comment]
We should consider using the dimSettingService to persist things in the advanced settings in the loadout builder. we could add a checkbox there to by default add those artifacts to the 'exclude list'

that way any time someone loads the builder, the settings they normally use are set, and then they can choose to add/remove things from the exclude list

?

**Comment by ericnelson0** [comment]
That's a good idea. Did the problem with space in settings get resolved? Or are we still seeing loadouts dissappear etc?

**Comment by kyleshay** [comment]
that will always be an issue, we disabled tags+notes in the release version, so that issue is still happening in beta. once we get google drive sync stable, then we'll allow tags + notes

**Comment by bhollis** [comment]
What if we just always put Felwinter into the "excluded" box by default? Then you could remove it (to have it be considered again). That also serves as a sneaky way of demonstrating the "exclude" feature...

**Comment by SunburnedGoose** [comment]
Two birds with one stone. Still no way to exclude without a mouse :/

**Comment by SunburnedGoose** [comment]
*keyboard

**Comment by bhollis** [comment]
We should probably make the excludes area a drag target, then we won't have to shift-click.

**Comment by kyleshay** [comment]
It is a drag/drop target, but only once it is visible. If we add the Felwinter artifact there by default, then that will solve that.

**Comment by SunburnedGoose** [comment]
Can't drag on a tablet atm :/

**Comment by SunburnedGoose** [comment]
https://www.npmjs.com/package/drag-drop-polyfill 

Maybe this will help fix the issues with touch-enabled devices and HTML5 drag and drop.

**Comment by ericnelson0** [comment]
I'll get this fix in today at some point.

**Comment by bhollis** [comment]
Yeah we should just make drag and drop work on tablets. I'll borrow a
Surface Pro.

**Comment by kyleshay** [comment]
this will be resolved in #1055, continue there.
