### ISSUE TITLE
Weapon perks in Organizer missing (Chromium pushes them out of view)

### ISSUE THREAD

**Issue by robojumper** [DestinyItemManager/DIM#9741]
### DIM Version

Version 7.82.0.1002810 (beta), built on 21.8.2023, 07:31:47

### Browser Details

Microsoft Edge Version 115.0.1901.203

### OS Details

Windows 10

### Describe the bug

This Last Perdition is missing a kill clip

![grafik](https://github.com/DestinyItemManager/DIM/assets/14299449/896c73ba-ffe8-4aaa-be8b-2d00c37876a7)

This is not happening in Firefox.

A reduced test case that behaves differently between Chromium and Firefox is

<details>
<summary> Click to expand </summary>

```html
<!DOCTYPE html>
<html>
  <head>
    <style>
      body {
        margin: 0 auto;
        font-family: "Open Sans", sans-serif;
        font-size: 12px;
        line-height: 1.3333333333;
        text-size-adjust: none;
        overflow-wrap: break-word;
      }

      .grid {
        display: grid;
        grid-template-columns: min-content minmax(324px, max-content) min-content;
      }

      .grid > div {
        padding: 4px 8px;
        border: 1px solid black;
      }

      .perks > *:nth-last-child(n + 2) {
        margin-bottom: 4px;
      }

      .perks {
        columns: 2;
        height: 100%;
        box-sizing: border-box;
        column-gap: 8px;
      }

      .modPerks {
        break-inside: avoid;
        display: grid;
        gap: 4px;
        padding-left: 5px;
        background-color: grey;
      }

      .isPerk {
        border-left: 2px solid red;
        padding-left: 3px;
      }

      .modPerk {
        width: 145px;
        height: 18px;
      }
    </style>
  </head>
  <body>
    <div class="grid">
      <div>item name</div>
      <div class="perks">
        <div class="modPerks isPerk">
          <div class="modPerk">Perk A1</div>
          <div class="modPerk">Perk A2</div>
        </div>
        <div class="modPerks isPerk">
          <div class="modPerk">Perk B1</div>
          <div class="modPerk">Perk B2</div>
        </div>
        <div class="modPerks">
          <div class="modPerk">Perk C</div>
        </div>
        <div class="modPerks">
          <div class="modPerk">Perk D</div>
        </div>
      </div>
      <div>item notes</div>
    </div>
  </body>
</html>

```

</details>

![grafik](https://github.com/DestinyItemManager/DIM/assets/14299449/6fcb07c3-96aa-43ef-820f-9313fef2c9f0)

**Comment by bhollis** [comment]
Interesting, looks like more of a CSS columns bug than a grid bug

**Comment by bhollis** [comment]
It seems to be related to `break-inside: avoid` which is used to prevent a group of perks from getting split across columns.

**Comment by robojumper** [comment]
Yeah, perhaps Chromium calculates the height of the cell based on the assumption that the perks get split and then un-splits them. Not sure if the test case is good enough for a Chromium bug report.

**Comment by bhollis** [comment]
Filed https://bugs.chromium.org/p/chromium/issues/detail?id=1474979
