### ISSUE TITLE
Harmonic resistance mod edge case interferes with DIM loadout swaps for strand

### ISSUE THREAD

**Issue by Korrasera** [DestinyItemManager/DIM#9767]
### DIM Version

Version 7.82.1.1002836 (beta), built on 8/24/2023, 3:18:30 AM

### Browser Details

Chrome 116.0.0.0

### OS Details

Windows 10

### Describe the bug

Preface: This may not be a bug but rather a byproduct of the way Bungie manages mod changes in the API. I'm bringing it up in case people weren't aware of this edge case. Also, this is specific to the original DIM loadouts. Since the ingame loadout functionality is currently disabled, I was not able to test to see if a similar issue can occur using Bungie's loadouts.

When you have a harmonic resistance mod loaded in equipped chest armor and you switch to a strand subclass, the harmonic resistance mod is deactivated. Since there is no enemy source of strand damage there's no strand resistance mod, so the harmonic resistance mod gets flagged as providing no benefit.

Because DIM is not able to change mod slots that contain deactivated mods, this effectively locks that mod slot whenever applying a DIM loadout that features a strand subclass. The loadout will fail to apply completely because DIM will apply the strand subclass first, deactivating the slot containing the harmonic mod, preventing that slot from being updated.

**Comment by robojumper** [comment]
Hmm yeah, this is basically an instance of Bungie-net/api#1843. DIM could work around this particular case in a few ways:

* When making the API switch to a Strand subclass, remove Harmonic Resistance from the currently equipped chest piece (simplest to implement but maybe surprising to users)
* When applying a loadout that has a Strand subclass and that needs to replace Harmonic Resistance, remove that mod first (less surprising, but blocked on groundwork for https://github.com/DestinyItemManager/DIM/issues/9455)
* When removing a Harmonic Resistance mod, temporarily switch to a different subclass

**Comment by bhollis** [comment]
> When removing a Harmonic Resistance mod, temporarily switch to a different subclass

I vote for this one, I think.

**Comment by bhollis** [comment]
Harmonic resistance is now compatible with Strand - I believe this can be resolved?
