### ISSUE TITLE
input/textarea hashtag/symbols autocomplete dropdown no longer appears

### ISSUE THREAD

**Issue by jamieastley** [DestinyItemManager/DIM#9769]
### DIM Version

Version 7.82.1.1002836 (beta), built on 24/08/2023, 8:18:30 pm

### Browser Details

Firefox 117.0

### OS Details

Windows 10

### Describe the bug

Suspect it's caused by #9765 as this was working prior to that change, but typing a colon no longer shows the symbol popup sheet in Firefox.

Opening in Chrome still works, however.

**Comment by robojumper** [comment]
What did break in #9765 however, was the actual symbols picker in the bulk note popup... I guess we need the same explicit portal parenting that the bulk note dialog already does for the autocompleter...

**Comment by jamieastley** [comment]
thanks for the quick fix!
