### ISSUE TITLE
Feature Request: Send Blues, Keep Greens

### ISSUE THREAD

**Issue by SableCentaur** [DestinyItemManager/DIM#978]
I'd be interested in a feature that sends blues to the vault but makes sure to keep greens in your inventory - because I have so many items in the vault, DIM tends to get gummed up if I don't dismantle the greens every 20 minutes or so, and having to check to see where it sent them when my inventory was full is sometimes kind of inconvenient. I'd actually rather it send away my legendaries rather than the greens. I understand the concern for keeping the interface simple without too many bells and whistles, but this is one thing that would really improve my Destiny experience while we're in this overwhelming sea of green engrams lol.

**Comment by kyleshay** [comment]
On it's way! https://github.com/DestinyItemManager/DIM/pull/967#issuecomment-250351031
