### ISSUE TITLE
Masterwork Preview color inversion for currencies looks very odd.

### ISSUE THREAD

**Issue by StardustD2** [DestinyItemManager/DIM#9784]
It would be good if the "invert on hover" behavior didn't apply to the currencies as it looks completely unnatural and made me do a double take a couple of times already. This is theme-agnostic and looks off on all the themes.
![image_2023-08-28_000316076](https://github.com/DestinyItemManager/DIM/assets/117818418/9cf672e0-59d0-4eff-a778-5a28948e1bcd)

**Comment by bhollis** [comment]
Yeah, we should have a class on all items that indicates whether they're monochrome or not, and only invert those that are.
