### ISSUE TITLE
Undefined error with Manifest file if there is an error downloading.

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#979]
Issue with a user over twitter tonight.  @bhollis seems like there is a failure to download a file and it's causing issues for this user.  They haven't been able to play since RoI.

![f5c2b27392d5b2fe59d597c2ef475848](https://cloud.githubusercontent.com/assets/984608/18945409/1026f49e-85f0-11e6-870a-4a4b28320b0d.png)
![43507bec7a62f1775161ade57e7441a1](https://cloud.githubusercontent.com/assets/984608/18945410/102d6ed2-85f0-11e6-8df1-fc907821c987.png)

**Comment by dustinrue** [comment]
Do you know what kind of network the user is on? Based on it being network error I'm going to assume campus network that has a firewall in place.

**Comment by bhollis** [comment]
Ugh, I made a mistake in the error handling that makes the stack trace useless. Doesn't help answer why they can't load the file.

**Comment by bhollis** [comment]
To get to the bottom of this user's problem we'd need to see the network tab, not the console tab.

**Comment by bhollis** [comment]
Closing unless we can get more info about what's preventing their download.

**Comment by SunburnedGoose** [comment]
![screen shot 2016-10-02 at 7 45 09 pm](https://cloud.githubusercontent.com/assets/984608/19025099/d017f484-88d8-11e6-9f09-d668239188f4.png)

**Comment by SunburnedGoose** [comment]
![screen shot 2016-10-02 at 7 46 24 pm](https://cloud.githubusercontent.com/assets/984608/19025109/eea358e4-88d8-11e6-8c35-26c93fcb95c2.png)
![Uploading Screen Shot 2016-10-02 at 7.46.16 PM.png…]()

**Comment by bhollis** [comment]
Huh, 503 service unavailable from Bungie. I usually see that when a load balancer is over capacity.

**Comment by bhollis** [comment]
Hmm I don't think those screenshots are the same thing as what happened to the person in the original incarnation of the bug. You're seeing Bungie's API be down (and a bug in the error handling which has since been fixed in dev). The original screenshot was a user who could call the Manifest API to find out which manifest file to download, but couldn't download the manifest file.

Unfortunately I still can't help that problem because I don't know what's causing it.

**Comment by SunburnedGoose** [comment]
If I recall, they were getting errors from the calls to the content files that you download after unpacking the data from the manifest call.

**Comment by bhollis** [comment]
Yup. That's the one I'd need more detail on.

**Comment by bhollis** [comment]
I've improved the error messaging. Let's tackle this again when it crops up.
