### ISSUE TITLE
Left column too narrow, truncating emblems and power number

### ISSUE THREAD

**Issue by bording** [DestinyItemManager/DIM#9795]
### DIM Version

Version 7.83.0 (release), built on 8/27/2023, 9:51:37 PM

### Browser Details

Edge 116.0.1938.62 - Windows 10 / Store App

### OS Details

Windows 11 22H2

### Describe the bug

Since the 7.83.0 update on Sunday, all of the parts of DIM that have the left column that have the character emblems at the top are too narrow, cutting off the emblem and power number:

![image](https://github.com/DestinyItemManager/DIM/assets/753669/e9171562-2322-492c-a7eb-7d4dd665f60f)
![image](https://github.com/DestinyItemManager/DIM/assets/753669/ea0e9a74-b0ca-4d64-9065-c74cd4e15fda)

**Comment by bhollis** [comment]
I assume you have the "Character Inventory Width" setting set higher than 3? In that case we'll have a fix soon.

**Comment by bording** [comment]
> I assume you have the "Character Inventory Width" setting set higher than 3? In that case we'll have a fix soon.

No, mine is still the default value of 3:
![image](https://github.com/DestinyItemManager/DIM/assets/753669/c1f7f86d-900d-4de2-8be8-fc99a0cdf07c)

I do have item size maxed though:
![image](https://github.com/DestinyItemManager/DIM/assets/753669/cbd204c0-ad8c-4ff8-96bc-f83f2edbd239)


Changing that back to the default of 50px seems to adjust it as well. Will the upcoming fix work with the larger item size as well?

**Comment by bhollis** [comment]
Yep it would
