### ISSUE TITLE
Remember which tab of the item popup you were on

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#9803]
This was an accidental feature that got nuked when we added a key to `ItemPopupContainer`. We should either store this globally in memory, or even have it in settings.

**Comment by nev-r** [comment]
this used to work when you click directly from one item to another, but i would [very personally] like if it just remembered, period

**Comment by bhollis** [comment]
Totally. We should add the toggle keyboard shortcut while we're at it (what do you think of "T" for "tab"?)
