### ISSUE TITLE
"Outbreak Prime" Classified weapon receiving errors on attempt to move.

### ISSUE THREAD

**Issue by sk8rdude461** [DestinyItemManager/DIM#981]
Attempted to move my Outbreak Prime from my warlock to my titan.

While it was equipped on the warlock, I got an error message saying "This item can only be worn by titans level 40 and up." and DIM automatically removed it from my weapon slot. I then tried to use the "Store" feature, which presents another error "Cannot read property 'capacity' of undefined". I believe both issues are due to Bungie making the weapon "Classified"; however it'd be nice if it told us that.

**Comment by delphiactual** [comment]
We could check "itemName"==="Classified" then fail in a more user friendly way.

**Comment by SunburnedGoose** [comment]
Wouldn't that fail with i18n.?

**Comment by delphiactual** [comment]
true I will look up the translations for classified from the different language databases

**Comment by delphiactual** [comment]
German: "Klassifiziert"
French: "Confidentiel"
Spanish: "Clasificado"
Italian: "Classificato"
Japanese: "機密"
Portuguese: "Acesso restrito"

**Comment by delphiactual** [comment]
or check !hasIcon as all the classified items have no icon, that could be an easier solution

**Comment by delphiactual** [comment]
Something like this should do the trick (and still be i18n compliant)

function isClassified(itemName) {
     var classified = ["Classified", "Klassifiziert", "Confidentiel", "Clasificado", "Classificato", "機密", "Acesso restrito"];
     if classified.includes(itemName) {
          return true;
     }
     return false;
}

**Comment by bhollis** [comment]
Let's do the `!hasIcon && !hasAction` check.

**Comment by bhollis** [comment]
This should be fixed now that #985 is in. Anyone with Outbreak Prime want to check?

**Comment by delphiactual** [comment]
Outbreak Prime is no longer classified but some of the shaders still are.

**Comment by kyleshay** [comment]
closing in favor of #1019
