### ISSUE TITLE
Change weapon pop-ups to indicate if a weapon is 'deepsight harmonizable'

### ISSUE THREAD

**Issue by therealjeffg** [DestinyItemManager/DIM#9810]
### Proposed change

Since Season 21 most craftable weapon drops have been able to have deepsight resonance added to them using the 3-6 deepsight harmonizers earned from the Season Pass. In #9563 we added the ability to filter the inventory looking for these guns, but there currently isn't any visual indication on the gun's pop-up to allow a user to easily see if a given gun is harmonizable or not.

### How does this fit into your workflow?

As the season draws to a close, I will be making decision on whether to spend engrams or farm particular activities in search of red borders or alternatively spend my small cache of deepsight harmonizers to get a particular pattern over the line. Not all craftable weapon drops are "harmonizable", and it would be nice to be able to see at a glance when looking at a given gun's pop-up if it was harmonizable or not.

Note: I know all of the craftable weapons have a progress bar attached to them, I think the main use cases for this feature are:

1. being able to tell if a gun has already had deepsight extracted, or
2. a gun is a drop of craftable weapon that is ineligable from being harminzed, eg it was bought from a raid vendor.

This would specifically allow me to more easily sort through duplicate drops of guns after a weekend of farming, differentiating between guns that were vendor purchases vs activity drops.

Notes on this from the [Season 21 preview](https://www.bungie.net/7/en/News/article/destiny-2-g-games-23-twab):

> Not all weapon instances will be compatible with Deepsight activation:
>
>    * You will be prevented from activating Deepsight for a weapon that has already had its pattern unlocked.
>    * Weapons that previously had Deepsight will be ineligible. You cannot activate Deepsight on a weapon instance which had originally been acquired with Deepsight, nor can you activate Deepsight multiple times on a single weapon instance.
>    * Weapon instances purchased from raid vendors will be ineligible, however weapons purchased from Xûr and the Gunsmith will support Deepsight activation.

**Comment by bhollis** [comment]
I think we can just un-hide the deepsight activation socket?

**Comment by guise** [comment]
![image](https://github.com/DestinyItemManager/DIM/assets/1396158/72cf69ac-e461-4f84-966c-6f25a84a702c)

Is this the deepsight activation socket? (just checking as I thought sockets are the interactive plugs)

Either way this could hold a similar (but more succinct) footnote like the in-game item popups and appear on weapons that match `is:craftable -is:patternunlocked` 

> [harmonizer icon] Deepsight can be activated

> [i] Ineligible for deepsight activation

**Comment by robojumper** [comment]
The deepsight activation socket is the in-game socket where you can insert Deepsight at the cost of one Deepsight Harmonizer (if the socket currently has a plug with PCH `PlugCategoryHashes.CraftingPlugsWeaponsModsExtractors` plugged and it's shown in-game). It's hidden in DIM for legacy reasons, also it's quite unappealing visually:

![grafik](https://github.com/DestinyItemManager/DIM/assets/14299449/ba3a444e-5bae-459d-b5d0-9d724a09cad0)

![grafik](https://github.com/DestinyItemManager/DIM/assets/14299449/e59711da-cf37-44a8-8bdb-5a40a03d95b0)

Another option would be reactivating the API tooltip notifications:

https://github.com/DestinyItemManager/DIM/blob/98d19b270d623da39d3af5c272dae1986a6f00e1/src/app/inventory/store/d2-item-factory.ts#L389-L390

Which would give us a small game/API-provided text at the bottom of the item tooltip

![grafik](https://github.com/DestinyItemManager/DIM/assets/14299449/ab59c731-1241-447f-900d-a1870dd5475c)

but also add a really wordy notification to all Adept weapons from Root of Nightmares and future raids

![grafik](https://github.com/DestinyItemManager/DIM/assets/14299449/7807ba68-91fa-4410-9127-38d223228860)

**Comment by therealjeffg** [comment]
> Which would give us a small game/API-provided text at the bottom of the item tooltip

This would definitely fulfill the original intent of my request!



> but also add a really wordy notification to all Adept weapons from Root of Nightmares and future raids

I agree this is wordy, which is unfortunate. I certainly don't think it's worth special casing though based on size of message, and I also assume that most players would never see this longer 'enhance-able weapon' message because most players don't do Master Raids.

**Comment by nev-r** [comment]
a third option is simply detect the socket and make our own marker/icon/whatever. put it near the pattern progress bar. we already have bungie-provided i18n for the tooltips.

**Comment by guise** [comment]
☝🏽 That sounds like a better approach - more targeted and obvious. 

![image](https://github.com/DestinyItemManager/DIM/assets/1396158/5172597a-5e57-4e1a-8425-70274cdfe971)

Inside the pattern progress container block seems to work nicely; including the harmonizer icon also makes it glanceable.

**Comment by therealjeffg** [comment]
> ☝🏽 That sounds like a better approach - more targeted and obvious.
> 
> ![image](https://user-images.githubusercontent.com/1396158/265956602-5172597a-5e57-4e1a-8425-70274cdfe971.png)
> 
> Inside the pattern progress container block seems to work nicely; including the harmonizer icon also makes it glanceable.

I love this!

**Comment by guise** [comment]
Posting the latest proposed approach here for completeness, shout out to @nev-r for the suggestion

To avoid unnecessarily increasing the height of the item popup, we opted to replace the pattern progress checkbox with the deepsight harmonizer icon for eligible weapons, with a tooltip showing additional detail: 

![deepsight-harmonizer-icon](https://github.com/DestinyItemManager/DIM/assets/1396158/704e22c7-c8a9-4f8a-aae2-ba713efd699d)

Ineligible weapons continue to appear as-is:
<img width="348" alt="image" src="https://github.com/DestinyItemManager/DIM/assets/1396158/e7a97a90-2c4e-489c-add5-1c51afe5d4e9">

**Comment by robojumper** [comment]
Fixed by #9848.
