### ISSUE TITLE
Hotfix breaks roll quality overlay?

### ISSUE THREAD

**Issue by Gonzo77** [DestinyItemManager/DIM#982]
Hi - hotfix just popped that I think may have broken the roll quality overlay stat.  I tried toggling on and off in options with no luck.

**Comment by ferazambuja** [comment]
Same here.

**Comment by delphiactual** [comment]
Once the API server starts returning the data it will be back you will also notice that weapons don't show what elements they are and no nodes are appearing on any items. Once the API server starts returning this data all will return to normal.

**Comment by Gonzo77** [comment]
you are correct, it fixed itself!  Thanks
