### ISSUE TITLE
React Router v6.4 Data Router Upgrade

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#9825]
React Router has once again changed things, but the upgrade appears to be optional. We should probably do at least some of it though: https://reactrouter.com/en/main/upgrading/v5

**Comment by robojumper** [comment]
The link points to upgrading from v5 to v6 but we've already been on React Router v6 since #7287. What am I missing?

**Comment by bhollis** [comment]
There's a whole new system in 6.4: https://reactrouter.com/en/main/routers/create-browser-router

I assumed it'd be a major version and have a migration guide but I guess not.

**Comment by robojumper** [comment]
I guess https://reactrouter.com/en/main/upgrading/v6-data is supposed to be the migration guide then.

**Comment by bhollis** [comment]
Yeah. Not clear we need any of the data loading support.

**Comment by bhollis** [comment]
I finally read through this - it's certainly possible we could make use of these features, but we already have mechanisms for managing loading state and such. I don't think we need this.
