### ISSUE TITLE
Show Community Insight on mod picker tiles

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#9826]
It'd be great to see the explanation for what armor mods really do while you're picking them. On the other hand, these tiles are already stuffed. Adding a tooltip could work, but doesn't help a user on mobile. Any thoughts for the best way to show this?

cc @vivekhnz

**Comment by robojumper** [comment]
Previous discussion: #9318, https://github.com/DestinyItemManager/DIM/pull/8641#discussion_r1020833047

**Comment by bhollis** [comment]
Yeah - putting them inline in the tiles isn't going to fly.
