### ISSUE TITLE
How to create consumables/materials loadouts?

### ISSUE THREAD

**Issue by ferazambuja** [DestinyItemManager/DIM#983]
From the 3.10.6 changelog:

> Fixed moving consumables in loadouts. Before, you would frequently get errors applying a loadout that included consumables. We also have a friendlier, more informative error message when you don't have enough of a consumable to fulfill your loadout.

How can I create consumables/materials loadouts? I'm not able to add any when I'm creating my loadouts.

**Comment by kyleshay** [comment]
it should just be working. click to add 1, shift + click to add 10.

![rec](https://cloud.githubusercontent.com/assets/424158/18966082/ec92259a-864d-11e6-88f9-0a331d6cbd1b.gif)

let me know if you're still seeing the issue.

**Comment by ferazambuja** [comment]
My bad it's working. I was trying to drag and drop.
