### ISSUE TITLE
[Finisher] text in description

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#9834]
Do we need to do something to support this in RichDestinyText?

<img width="546" alt="Screenshot 2023-09-02 at 7 21 12 PM" src="https://github.com/DestinyItemManager/DIM/assets/313208/eb59f64e-99da-41eb-a3e3-da011eed7096">

**Comment by robojumper** [comment]
I don't think so - the game replaces `[Finisher]` (or whatever the D2-internal string is, `[Finisher]` seems to be an invention of the Bungie.net API) at runtime with whatever button (combo) is mapped to the Finisher button. Some others can be found in

https://github.com/DestinyItemManager/DIM/blob/6608569677220f9e77fb176883bdf7ba05a8a475/src/data/d2/symbol-name-sources.ts#L875-L890

(Finisher isn't there, I guess the symbols code isn't looking at item descriptions)

**Comment by nev-r** [comment]
stasis locked glyphs are there actually
![image](https://github.com/DestinyItemManager/DIM/assets/68782081/adbcfdf3-baad-4bf6-92b7-d81777d2136b)

**Comment by robojumper** [comment]
Right, I think I had some problems localizing those and skipped them because of that.
