### ISSUE TITLE
dupelower description is incorrect & only mentions item power

### ISSUE THREAD

**Issue by geevensingh** [DestinyItemManager/DIM#9850]
### DIM Version

Version 7.84.1 (release), built on 9/6/2023, 11:21:05 AM

### Browser Details

Chrome 115.0.0.0

### OS Details

Windows 10

### Describe the bug

I have two "robes of detestation" - one at 1807 and one at 1800.  When I query for is:dupelower, DIM highlights the 1807 item and not the 1800 item.

![Screenshot 2023-09-06 182512](https://github.com/DestinyItemManager/DIM/assets/11344767/ffeb8ef8-f54e-420d-8b3a-82f938bc7359)

**Comment by bhollis** [comment]
The 1807 item is worse - you've marked it as infusion fuel, and the other one as "keep".

**Comment by nev-r** [comment]
dupelower help string needs updating as i wasn't aware of this behavior either and nor it seems, are the docs

**Comment by bhollis** [comment]
Yup, the description should have been changed in https://github.com/DestinyItemManager/DIM/pull/9798

**Comment by geevensingh** [comment]
Dupelower used to mean “dupe with a lower power level”. What does it mean now?

**Comment by geevensingh** [comment]
Well , for what it’s worth, I used it all the time as part of a query that was “ tag:junk is:dupe -is:dupelower -is:blue”
That represents items that are good infusion fodder. But if you’re going to give me different tools to do that job to replace dupelower, that’s fine I guess.

**Comment by bhollis** [comment]
There's a whole infusion tool for finding infusion fuel. Otherwise there's a request for a specific infusion fuel search term, but it'll be subjective: #9213. I can see how your search was useful for finding infusion fuel in bulk, but that wasn't the intended usage of dupelower.
