### ISSUE TITLE
masterworked deepsight weapons styling bug

### ISSUE THREAD

**Issue by nev-r** [DestinyItemManager/DIM#9857]
![image](https://github.com/DestinyItemManager/DIM/assets/68782081/426d9e5d-f5ac-4a24-a3a9-f68a38064b82)

the same div houses the masterwork overlay classname, and the crafted overlay classname, and when both are applied, they have conflicting `background-size` needs

![image](https://github.com/DestinyItemManager/DIM/assets/68782081/36de1d48-bdbf-4613-8ab9-a6dcc09c5496)

**Comment by robojumper** [comment]
Fixed by #9869.
