### ISSUE TITLE
No stat or quality on some gear.

### ISSUE THREAD

**Issue by Marc05** [DestinyItemManager/DIM#986]
![sketch](https://cloud.githubusercontent.com/assets/1699133/18979857/9ead7146-869c-11e6-8e4c-9086837c5fc8.png)
Some Trials and Iron Banner gear like Blindsight Boots and Iron Shell do not show stats or quality roll.

**Comment by delphiactual** [comment]
DUPE: https://github.com/DestinyItemManager/DIM/issues/889
