### ISSUE TITLE
Commendations

### ISSUE THREAD

**Issue by Berry-Rydell** [DestinyItemManager/DIM#9872]
### Proposed change

Hi, tracking commendations would be useful for triumphs, guardian ranks that require them etc.
I can't see a way to see them in DIM, but they are detailed in the Destiny 2 app.

If they are obtainable via the API, any chance of including them? The obvious place would be in the 'Records' tab.

Thanks, I am an annual backer of DIM and love your work!

### How does this fit into your workflow?

Tracking commendations would be useful for triumphs, guardian ranks that require them.

**Comment by robojumper** [comment]
Can't you just track the triumphs that require commendations in DIM directly?
