### ISSUE TITLE
armor stats cap at 350, not 335?

### ISSUE THREAD

**Issue by Lalo-ATX** [DestinyItemManager/DIM#988]
I think armor stats stop rising when the armor hits 350, not 335.

I think `getScaledStat` and `getQualityRange` should replace the values 335 with 350 (really, some sort of global "`maxStatLight`" or somesuch variable should be defined at 350 and the hard-coded numbers replaced with the variable)

https://www.reddit.com/r/DestinyTheGame/comments/543zon/items_stop_gaining_intdisstr_after_a_certain/

also that's how Tower Ghost is doing it

https://github.com/dasilva333/TowerGhostForDestiny/blob/master/www/js/tgd/bonusStat.js

`tgd.DestinyStatCap = 350`

(I'm totally new to github & javascript apps, tips/pointers on how best to help are much appreciated)

**Comment by SunburnedGoose** [comment]
Still waiting for a definitive update from notable members.  Atm, stats seem adequate to help users judge their gear and build T12 sets.  Can you show me any outliers that would be affected by this?  Need more input #jonnyfive

**Comment by Lalo-ATX** [comment]
I have no examples of this having any impact. I actually don't know how to
view the predicted stat points in the DIM UI - all I can see are the
percentages, and I don't know how to convert from percent to a value.

What happened is a friend said that the green/yellow/red ratings in DIM
were changing as he infused gear (e.g. a green rating turned yellow after
infusion), and I got curious so I dug through the DIM code for predicting
future stat levels. I saw the hard-coded 335 limit and thought it was worth
pointing out to y'all that other folks seem to think the limit is at 350.
I'm not saying that my friend's issue is related to this issue (although I
suppose somehow it might be, although that wouldn't make sense to me), just
that's the original motivation for looking into the code.

If I find concrete evidence of inaccuracy, I'll post it.

**Comment by SunburnedGoose** [comment]
If they infused a 335->350 and it changed, that would be interesting.  If it was < 335, then that's the normal formula error rate for projections from items under 335.

**Comment by kyleshay** [comment]
we have some insight from: https://docs.google.com/spreadsheets/d/1YyFDoHtaiOOeFoqc5Wc_WC2_qyQhBlZckQx5Jd4bJXI/edit

**Comment by Lalo-ATX** [comment]
kyle, that looks just like bonus stat points, not base stat points. what
I'm trying to say is that base stat points continue rising with infusion up
to 350, whereas DIM only predicts stat points up to 335.

**Comment by kyleshay** [comment]
those are base stats for split stat item types

**Comment by kyleshay** [comment]
ahh, gotcha.

**Comment by JakeWhitaker** [comment]
If they did it while item quality was broken around launch RoI I can confirm this happened. For a while my Dread Explorer Ghost was going down from 100% gradually to around 92%.

**Comment by SunburnedGoose** [comment]
That was because we did not cap light at 335.  The formula was running to the light of the item and it made it seems as if it was not as good as it was.

**Comment by bhollis** [comment]
Is there something left for us to do here?
