### ISSUE TITLE
Adding random wepons and armor into my inventory

### ISSUE THREAD

**Issue by KingBoo27** [DestinyItemManager/DIM#9885]
### DIM Version

7.86.0

### Browser Details

Firefox 117.0

### OS Details

Windows 10

### Describe the bug

All I want to do is put a weapon back into the volt. Still, for whatever reason it puts another one back most of the time not even in the same slot or even giving me an armour piece, like if I put a sidearm back, it'll pass over a helm or a heavy, no rhyme or reason ? and it does this every time. Put a helm back I could get some boots or a sword, put the boots back and then it'll pass over an auto. NGL its getting annoying.

**Comment by robojumper** [comment]
Is your vault full? If you ask DIM to move something to your vault and it's at its capacity, then DIM will move something else out to make space. See https://github.com/DestinyItemManager/DIM/wiki/Smart-Moves

**Comment by KingBoo27** [comment]
> Is your vault full? If you ask DIM to move something to your vault and it's at its capacity, then DIM will move something else out to make space. See https://github.com/DestinyItemManager/DIM/wiki/Smart-Moves

I didn't realise that was a thing tbh. I'm a bit of a collector you see so now I'm sad if I'll have to get rid of something.
