### ISSUE TITLE
More filters

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#989]
Create a filter that combines multiple filters

new filter | combined filters
-----------|-------------------
is:weapon | is:primary is:special is:heavy
is:armor | is:helmet is:gauntlets is:chest is:leg is:classitem
is:gear | is:weapons is:armor is:ghost
has:light | is:weapons is:armor is:ghost

**Comment by SunburnedGoose** [comment]
What about has:light along with is:gear?  Same filter, but different attribute.

**Comment by delphiactual** [comment]
That works, I was just passing on info from this [reddit post](https://www.reddit.com/r/DestinyItemManager/comments/558bzq/issue_with_farming_mode_all_greens_go_to_vault/)

**Comment by SunburnedGoose** [comment]
Thanks for doing that.  It really helps.

**Comment by bhollis** [comment]
I like is:light (we shouldn't invent a new prefix just for grammar's sake) and maybe is:equipment as well.

**Comment by bhollis** [comment]
Implemented in #999.
