### ISSUE TITLE
An "automatically" updating Destiny Recipes Vault Cleaner

### ISSUE THREAD

**Issue by danielmirchandani** [DestinyItemManager/DIM#9891]
### Proposed change

I'm a huge fan of https://destinyrecipes.com/vault, but it relies on the author (https://twitter.com/D2Recipes) updating their cached version of the wish list (same source that DIM uses) manually. I keep feeling like there's an automatic solution here, but I'm having trouble expressing it. Some half-baked thoughts:

1.  Perhaps the DIM Organizer could have an additional column with the raw wish-list lines for Vault Cleaner to parse from my exported vault, along with the already exported "notes" that allows it to figure out whether it's a PvE or PvP roll? This is probably the much easier solution, though I have no idea how Vault Cleaner is implemented, so I don't know how hard it is to accept this input on the other side.

2.  Perhaps there's some JS hooks I can have local-only JS running that finds the same data and shows some additional display layer on top of my own inventory? Vault Cleaner becomes a browser extension rather than a website.

### How does this fit into your workflow?

At this point, I rely on DIM's wish-list integration to manage my inventory stream. Before the seasonal update, I don't touch items new to the season. After the seasonal update, thumbs up means I keep it, no thumbs means dismantle it. But what do I do when I have multiple thumbs up? I go to Vault Cleaner once a week or so to make decisions between the thumbs ups, further limiting myself to one damage type (mostly) per weapon, so I've been able to sit around 500/600 vault space used for a while.

**Comment by bhollis** [comment]
This feels like it could maybe be a feature request for Destiny Recipes?

**Comment by danielmirchandani** [comment]
You're right. I jumped ahead. Let's assume they're working on such a feature and figuring out whether to go with option 1 or 2 as I laid out in the first comment. Here's explicitly what I'm asking:

For option 1: Can the Organizer have another column of all wish-list entries for that item, even those that don't match the given perks?

For option 2: Are there any JS objects that extensions can hook into with inventory and wish-list entries?

**Comment by bhollis** [comment]
I'm not sure I follow what exactly you're intending to achieve. The wish list file itself will tell you what wish list entries exist for every item - you don't need anything from DIM to figure that out.

**Comment by nev-r** [comment]
> Can the Organizer have another column of all wish-list entries for that item, even those that don't match the given perks?

this would probably make every row of the organizer 27 pages high.
i think what you're really asking for is the wish list to be there in the spreadsheet export?
and at that point, yeah the automation-consumable data you're asking for is pretty much just "the raw wishlist"

**Comment by danielmirchandani** [comment]
Vault Cleaner scores every weapon based on how many perks it matches, rather than just matching all of them. So, if it detects the section of the wishlist is a PvE section, and the item it's checking matches 3 of the 5 possible perks, that item gets a 60% PvE score (highly simplified).

I guess the main thing I was looking to get out of DIM was reading the wishlist without having it compiled in, parsing it, and perhaps interacting with the data in a structured way. Also, Vault Cleaner doesn't handle enhanced perks automatically, so scores are thrown off if the wishlist doesn't list them explicitly.

You've convinced me option 1 is not really an option. Unless you have any ideas about option 2 (an API that I could plug an extension into without affecting every other user), I'm fine with closing this issue. Thanks for talking it through with me.

**Comment by bhollis** [comment]
You probably want to look at https://github.com/DestinyItemManager/DIM/blob/master/src/app/wishlists/wishlist-file.ts - that's the code that parses a wish list file into something easy to use. I think that's the best road to doing what you want with wish lists.
