### ISSUE TITLE
[Question] Help accessing Destiny equipment information

### ISSUE THREAD

**Issue by sidferreira** [DestinyItemManager/DIM#9899]
### Proposed change

I want to build a tool to create DIM-compatible wishlists.
How can I get the data about Destiny2 weapons and their traits?
Is there any public repo with it?

### How does this fit into your workflow?

I'm glad to develop it myself if I find the proper info.

**Comment by robojumper** [comment]
Little light has a wishlist manager tool for creating wish lists at https://wishlists.littlelight.club/#/ (and the source is available at https://github.com/LittleLightForDestiny/wishlist_manager). If you still want to build your own tool, in addition to the source code, good places to find more info are the [Bungie.net API documentation](https://github.com/Bungie-net/api), [data.destinysets.com](https://data.destinysets.com) and the [Destiny API Discussion Discord](https://discord.com/invite/E5uB4BW).

**Comment by sidferreira** [comment]
@robojumper I'll try to reach LittleLight dev first. Although I'm looking for different features, there's no need to reinvent the wheel
