### ISSUE TITLE
Feature Request: Fill Stack from Vault

### ISSUE THREAD

**Issue by JakeWhitaker** [DestinyItemManager/DIM#990]
For things like heavy synth, planetary mats, etc. I keep a stack on each character, and reserves in the vault. Currently to refill a stack after use, I move from vault the amount need to complete the stack(if i have 155 spirit bloom I have to slide the slider or use the keyboard and type 45) A button that automatically does that could be great for tablet users like myself

**Comment by SunburnedGoose** [comment]
What's the current default for a stackable transfer?

**Comment by SunburnedGoose** [comment]
Maybe we can add some buttons to that dialog that moves the slider to fill a stack.

**Comment by Mulchman** [comment]
@JakeWhitaker a shortcut is to move a stack from the vault, then take the remainder from the character and put it back on the vault. This way you don't have to mess w/ the slider and/or do math.

I play the same way, though, keeping a full stack (and only a stack!) on a character.

I suggested options for this when the "Split" button was implemented but it was shot down.

**Comment by JakeWhitaker** [comment]
Oh thats a good idea!!! Never thought of that. It'd be nice to have but Mulchmans shortcut isn't hard to do. 

The current default if i have 236 spirit bloom on a character and I want to transfer to my vault, it ask me on a slider how many out of 236 i want to transfer. Or I can drag the stack of 200 or the stack of 36. The only thing thats difficult is filling a stack of 36 with 164 bloom, but like mulchman said, I could switch the 36 stack with a 200 from my vault. its just a quality of life thing imo

**Comment by SunburnedGoose** [comment]
Yep.  Good enough for me.  We'll save this for a rainy day.

**Comment by JakeWhitaker** [comment]
This shortcut solution is still ineffective for tablets. I cannot drag and drop on my Surface Pro in this app, but I usually have a mouse hooked up, so it isn't a big deal for me. Just figured I'd mention this if you all are going for a tablet friendly design.

**Comment by bhollis** [comment]
You should be able to drag and drop... I'll have to see if I can borrow a Surface Pro to test on.

**Comment by JakeWhitaker** [comment]
May just be Win10 if you can find a touch screen laptop running it. Just checked and it's the same in desktop and tablet mode.

Jake Whitaker

Sent from BlueMail<http://www.bluemail.me/r>


On Sep 30, 2016, at 22:58, Ben Hollis <notifications@github.com<mailto:notifications@github.com>> wrote:

You should be able to drag and drop... I'll have to see if I can borrow a Surface Pro to test on.
