### ISSUE TITLE
is:dupe pulls separate adept/normal versions as a duplicate

### ISSUE THREAD

**Issue by GlitchNDaSystem** [DestinyItemManager/DIM#9904]
### DIM Version

Version 7.86.0.1002941 (beta), built on 9/21/2023, 8:07:07 PM

### Browser Details

Chrome 116.0.0.0

### OS Details

Windows 10

### Describe the bug

Title. Previously when I had is:dupe in my search field, if I had (one copy of) a weapon like Forebearance and (one copy of) a weapon like Forebearance (Adept), neither would show up in the search. This is the desired effect for me, because they are two different guns imo. Now, if I have is:dupe in the same situation both guns would be highlighted. I am not sure if this is a bug or if the dupe filters were modified and I have to rewrite my search filter? Any insight into this would be greatly appreciated.

**Comment by bhollis** [comment]
The dupe filters were intentionally changed to include adept variants.

**Comment by GlitchNDaSystem** [comment]
OH ok great, good to know. I guess I'll need to write a new line around that then. Thank you.

**Comment by 5c0rp5** [comment]
@GlitchNDaSystem did you ever figure out a search query to account for this? I'm having the same issue and would prefer to treat Adepts/Timelosts as separate weapons when looking for dupes.
