### ISSUE TITLE
Any Class Loadouts apply Subclass

### ISSUE THREAD

**Issue by bmundt** [DestinyItemManager/DIM#9907]
### DIM Version

Version 7.86.0.1002941 (beta)

### Browser Details

Firefox

### OS Details

Windows 10

### Describe the bug

When you apply an "any class" loadout, it can change the equipped subclass. If a subclass was selected in the loadout before switching it to an "any class", then that suclass information gets retained for the loadout on that class.

### Logs

```shell
[loadout] Apply loadout aLoadout to Exo Titan instrument.ts:144:19
[equip] Equip Sunbreaker Class to Exo Titan instrument.ts:144:19
itemMovedUpdate: 163ms - timer ended log.ts:58:23
[loadout socket overrides] Socket overrides to apply 
Array [ {…} ]
instrument.ts:144:19
[loadout socket overrides] Socket overrides applied 11 11 instrument.ts:144:19
Loadout Application: 655ms - timer ended
```

**Comment by bmundt** [comment]
It also moves any armor that was selected in the loadout before it was switched to an "any class" loadout.

**Comment by robojumper** [comment]
On beta this should be fixed going forward, but you may have to edit and re-save the affected DIM Loadouts (no changes to the Loadouts themselves should be needed, but the incorrectly saved items will only be dropped when re-saving).
