### ISSUE TITLE
Sticky headers

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#992]
Have the headers float at the top until a new section is reached.

https://www.reddit.com/r/DestinyItemManager/comments/558g4v/suggestion_show_the_max_light_possible_on/

**Comment by bhollis** [comment]
Neat suggestion, but we need to make sure it doesn't make scrolling performance awful.

**Comment by delphiactual** [comment]
Another option, was a PR I saw on here awhile ago with the navbar on the left(I can not locate it right now), that just highlights the current displayed section.

**Comment by kyleshay** [comment]
#540 

https://github.com/DestinyItemManager/DIM/issues/540#issuecomment-222748042

**Comment by bhollis** [comment]
Let's resolve this in favor of #540. I don't think sticky headers on their own are worthwhile.
