### ISSUE TITLE
CSV export filters D1 nodes / D2 plugs using unlocalized names

### ISSUE THREAD

**Issue by robojumper** [DestinyItemManager/DIM#9922]
https://github.com/DestinyItemManager/DIM/blob/f81db5ebc67bad5cc3a100ce8f0975506de8477e/src/app/inventory/spreadsheets.ts#L44-L65

This only works when DIM is set to English and the English defs are loaded. E.g. the armor CSV export includes "Empty Mod Sockets" in other languages.

**Comment by bhollis** [comment]
In my defense that list was only really for D1 stuff, and I didn't feel like going back and trying to find the D1 hashes that corresponded with the talent grid nodes.
