### ISSUE TITLE
Add a new tag related to crafting, pattern unlocks or using a harmonizer

### ISSUE THREAD

**Issue by mturquette** [DestinyItemManager/DIM#9931]
### Proposed change

Now that deepsight harmonizers are a thing, I wanted to start a discussion about whether a new class of Tag should be added to DIM? Due to the scarcity of harmonizers, I might stockpile several weapons that I could potentially use harmonizers on. I feel like the Keep tag is not quite the right one, since my intention isn't to keep this weapon and use it, but to hold onto it until either burn a Harmonizer on it, or I unlock the corresponding weapon pattern some other way.

I also wonder if others have needs to categorize their gear that are related to Crafting, Patterns or Harmonizers? Maybe a broader name is helpful to others?

To be clear, this is basically bikeshedding about naming schemes and this is about the lowest priority feature request I can imagine. It's the very definition of first world problems lol

### How does this fit into your workflow?

Initially I solved this issue by tagging weapons as Keep, then adding a #harmonizer tag to the Notes. But this sort of irked me because it meant any search for tag:keep would include weapons that I do not intend to actually keep around, long-term.

As a workaround I started to tag these weapons with Infuse, but that's just sort of gross and inaccurate.

What I'd love is to have a new first-class tag titled "Harmonizer" or "Craft" or "Pattern" or something along those lines.

**Comment by delphiactual** [comment]
https://github.com/DestinyItemManager/DIM/blob/master/docs/CHANGELOG.md#7750-2023-07-02

`deepsight:harmonizable`

**Comment by bhollis** [comment]
The suggestion is to use a tag in notes for this. Add #useharmonizer and you can easily search for them.

**Comment by mturquette** [comment]
OK, will do. Thanks.
