### ISSUE TITLE
Rare bug with layout of items

### ISSUE THREAD

**Issue by geck0s** [DestinyItemManager/DIM#994]
This is like the third time I've managed to totally confuse the layout routines.  
I think it may have something to do with transferring and equipping with only one free space.  The 365 Tau Hua Yuan sniper in the vault was actually transferred and equipped to my middle character by the time I took this screenshot.

![image](https://cloud.githubusercontent.com/assets/12294244/19010926/47aec1ea-8757-11e6-828d-ce6caad789e9.png)

Is there some way I can dump the internal state the next time this happens so maybe I can figure out what is happening?

It seems pretty rare and it's not a big deal because it rearranges on the next refresh, but still if I could determine the cause, I'd like to give it a shot.

**Comment by bhollis** [comment]
I believe this is a manifestation of #811 (which I also believe is related to #898). Unfortunately I can't make it happen easily, so I don't know how to fix it.

I'm gonna close this in favor of the existing issues.
