### ISSUE TITLE
layout freakout - mods selector

### ISSUE THREAD

**Issue by nev-r** [DestinyItemManager/DIM#9949]
windows firefox at 140% zoom, seeing issues at page width 2558 px, 2571 px..
is this fixable, or likely universally an issue in width-based variable-content scenarios?

https://github.com/DestinyItemManager/DIM/assets/68782081/5cb146ad-bad7-4400-9def-655b1a55f757

**Comment by bhollis** [comment]
With the way the video is cropped, I'm not sure exactly what's going on here. Is it triggering the scrollbar, which causes some reflow that then removes the scrollbar, or something?

**Comment by liamdebeasi** [comment]
Do you have steps to reproduce this issue? I'm happy to take a look into fixing it if I can reproduce. I am testing on Firefox 126 with a zoom of 150%, but the layout does not shift on my end.

**Comment by bhollis** [comment]
I can't reproduce on my Mac, with "always show scrollbars" enabled. It's possible that Firefox had a bug here related to calculating the width of scrollbars?

**Comment by liamdebeasi** [comment]
I also tested Firefox 127 on Windows 11 with zooming enabled and was unable to reproduce the reported issue. 

https://github.com/DestinyItemManager/DIM/assets/2721089/38621a55-afc9-40d8-a85b-e8d58ade4c88
