### ISSUE TITLE
Remove default shader from 'is:dupe'

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#998]
Built in shader shows up in the is:dupe resultset.  Can't delete it, or do anything about it.

**Comment by bhollis** [comment]
Can't delete it, but it is a duplicate. Seems weird to omit it.

**Comment by SunburnedGoose** [comment]
We use dupe to find things we can delete, or at least move away.  Default shader does neither. Is it useful to have it highlighted?
